### ISSUE TITLE
r220 - Crash when selecting and Sprite and other objects

### ISSUE THREAD

**Issue by el3um4s** [Scirra/Construct-3-bugs#4287] opened 2020-10-13 15:06 UTC
## Problem description

Red screen crash when selecting Sprite and other objects together.

## Attach a .c3p

[test-c3.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/5372235/test-c3.c3p.zip)

## Steps to reproduce

1. Create a Sprite and a Text Object (Or other type)
2. Select them

## Observed result

Error

![image](https://user-images.githubusercontent.com/23579630/95879221-6531da00-0d76-11eb-9c45-a9e1f77e7c26.png)

## Expected result

I can select them

## More details

**Affected browsers/platforms:** Chrome, Windows

**First affected release:** r220

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r220/components/bars/propertiesBar/propertiesBar.js, line 71, col 287
Message: Uncaught TypeError: Cannot read property 'Ik' of null
Stack: TypeError: Cannot read property 'Ik' of null at n.RYc (https://editor.construct.net/r220/components/bars/propertiesBar/propertiesBar.js:71:287) at n.UQ (https://editor.construct.net/r220/components/bars/propertiesBar/propertiesBar.js:52:229) at n.K$b (https://editor.construct.net/r220/components/bars/propertiesBar/propertiesBar.js:19:523) at Array. (https://editor.construct.net/r220/components/bars/propertiesBar/propertiesBar.js:3:225) at Object.G8c (https://editor.construct.net/r220/main.js:428:387) at Object.dispatchEvent (https://editor.construct.net/r220/main.js:424:135) at Object.qia (https://editor.construct.net/r220/main.js:2094:372) at p.e2c (https://editor.construct.net/r220/components/editors/layoutView/layoutView.js:158:201) at p.sq (https://editor.construct.net/r220/components/editors/layoutView/layoutView.js:157:201) at e.ce (https://editor.construct.net/r220/components/editors/layoutView/layoutView.js:168:65)
Construct 3 version: r220
URL: https://editor.construct.net/r220/
Date: Tue Oct 13 2020 17:04:22 GMT+0200 (Ora legale dell’Europa centrale)
Uptime: 200.7 s

Platform information
Browser: Chrome
Browser version: 86.0.4240.75
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
C3 release: r220 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment] 2020-10-13 15:41
Regression in r220. Tagging as fixed and leaving open because more people are going to be seeing this one.

**Comment by DiegoScirra** [comment] 2020-10-13 15:43
The crash is triggered by making a selection that includes different object types.

**Comment by AshleyScirra** [comment] 2020-10-13 15:57
I think we should do a patch release, since it looks like it'd be hard to use a beta release with this issue.

**Comment by XHXIAIEIN** [comment] 2020-10-14 04:50
I was about to report when I found that someone had submitted the question.HAHA  
![img]https://i.imgur.com/xBMYtYm.gif[/img]

**Comment by AshleyScirra** [comment] 2020-10-14 11:27
OK, should be fixed in r220.2.

**Closed by AshleyScirra** 2020-10-14 11:27 UTC
