### ISSUE TITLE
Preview Drop Down Menu stayed open.

### ISSUE THREAD

**Issue by Unconected** [Scirra/Construct-3-bugs#4894] opened 2021-06-15 18:22 UTC
## Problem description

U.I. issue.

## Attach a .c3p

c3p isn't applicable, I attached an image. The preview drop down is stuck open. I can open a new drop down menu and it appears correctly, when I close it it still looks like this. I adjusted the window size and it still stays like this. Open and closing C3 fixes it of course.  I closed C3 before thinking to test if the buttons were active or not, but I think they were. This is a minor issue, I am only letting you know I experienced it. It doesn't seem to affect anything.

https://cdn.discordapp.com/attachments/816417599762989067/854424009851535361/Annotation_2021-06-15_131146.png

## Steps to reproduce

I do not know the steps to reproduce.

## Observed result

Preview drop down menu stayed open but had about 50% opacity.

## Expected result

Preview drop down fully opens and closes.

## More details
 I only use the Chrome web based version as an app.

First happen in Release r251.2 Stable

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 91.0.4472.77
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
C3 release: r251.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 324 mb
Storage usage (approx): 93 mb (28.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 950 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2021-06-16 18:18
I'm afraid as per the bug report guidelines, without steps to reproduce it's generally impossible to act on bug reports. It seems to be working fine for me.

@DiegoScirra - any idea if this is related to your previous change to menu visibility?

**Comment by DiegoScirra** [comment] 2021-06-16 19:06
Looks like it is the same as #4833, which I thought was fixed already. This happens when a context menu is open and you switch Chrome tabs and then come back. It's not 100% reproductible though, you just need to try it and eventually it happens.

**Comment by Unconected** [comment] 2021-06-17 00:12
I was using C3 in a Chrome App, I didn't have tabs to switch to. I understand there isn't anything that can be done with this report alone. I was only letting you know I experienced it and maybe provided more info or someone else could see that it is happening if they experience it. Menu stayed open and I couldn't close it, I had to close C3 to close the menu. I would guess they are related as well.
I tried opening a project, opening the menu and switching between C3 project tabs, but nothing.

**Comment by AshleyScirra** [comment] 2021-06-22 17:56
I just realised @DiegoScirra 's fix was in r252, and this report was filed for r251.2. So this should indeed already be fixed in the latest beta. Please let us know if you can still reproduce this with r252+. Closing as duplicate of #4833.

**Closed by AshleyScirra** 2021-06-22 17:56 UTC
Labels: duplicate
