### ISSUE TITLE
Unhandled exception instance not on this layer crash :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6557] opened 2023-02-17 22:24 UTC
## Problem description

Construct crashes.

## Attach a .c3p

save open project: 
[save_open_project.zip](https://github.com/Scirra/Construct-3-bugs/files/10772061/save_open_project.zip)

## Steps to reproduce

1. Create a new project.
2. On `Layout 1`: Create `Layer 1` and make it global.
3. Create a layout `Layout 2`.
4. On `Layout 2`: Create `Layer 1`.
5. On `Layout 2`: Create a sprite on `Layer 1`.
6. On `Layout 1`: Delete `Layer 1`.
7. On the instance, click on the dot to zoom in diagonally to open the settings for the instance in the left ear.
8. Move the instance to the layer by selecting `Layout 1` - `Layer 0` from the context menu.

## Observed result

https://user-images.githubusercontent.com/91274932/219808055-6c2b53d7-11cf-4509-b407-d47ec30a3fdc.mp4

## Expected result

Construct does not crash.

## More details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r330/projectResources.js, line 1343, col 474
Message: Uncaught Error: instance not on this layer
Stack: Error: instance not on this layer at d.joc (https://editor.construct.net/r330/projectResources.js:1343:480) at d.yjb (https://editor.construct.net/r330/projectResources.js:798:395) at https://editor.construct.net/r330/components/bars/propertiesBar/propertiesBar.js:18:424 at Zg (https://editor.construct.net/r330/main.js:370:408) at qq.g.K.seb.iX (https://editor.construct.net/r330/main.js:1531:418) at qq.g.K.seb.UF (https://editor.construct.net/r330/main.js:1532:71) at HTMLSelectElement.Is (https://editor.construct.net/r330/main.js:1530:343)
Construct version: r330
URL: https://editor.construct.net/r330/
Date: Sat Feb 18 2023 00:29:46 GMT+0200 (Восточная Европа, стандартное время)
Uptime: 74.7 s

Platform information
Product: Construct 3 r330 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r330b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r330 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 193 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2023-02-20 15:15
Steps to reproduce:

1. Open project [issue6557.zip](https://github.com/Scirra/Construct-3-bugs/files/10785560/issue6557.zip)
2. Select Sprite instance
3. On Layout 1, delete Layer 1

Observed result: Deleted instance remains selected. Further interacting with it causes a crash.
Expected result: Selection to disappear when layer it belongs to is deleted

(Please try to write bug reports in this format when you can, it makes it much easier to deal with)

**Comment by AshleyScirra** [comment] 2023-02-20 15:16
I think the root cause is simply that deleting a layer a selected instance is on does not immediately unselect it, even if you're not using global layers at all. That should be fixed in the next beta.

**Closed by AshleyScirra** 2023-02-20 15:16 UTC

**Comment by WilsonPercival** [comment] 2023-02-20 15:31
> Steps to reproduce:
> 
> 1. Open project [issue6557.zip](https://github.com/Scirra/Construct-3-bugs/files/10785560/issue6557.zip)
> 2. Select Sprite instance
> 3. On Layout 1, delete Layer 1
> 
> Observed result: Deleted instance remains selected. Further interacting with it causes a crash. Expected result: Selection to disappear when layer it belongs to is deleted
> 
> (Please try to write bug reports in this format when you can, it makes it much easier to deal with)

Sorry. I really tried to simplify, but then I couldn’t crash. I didn't know what was causing the crash.
