### ISSUE TITLE
Audio bug after interstitial ad

### ISSUE THREAD

**Issue by Yoshi54321** [Scirra/Construct-3-bugs#3873] opened 2020-05-21 06:25 UTC
## Problem description
Sound fx is gone after interstitial ad finishes

## Attach a .c3p
https://drive.google.com/file/d/1uS6C_o3gFQQCfgN_1vYsXsyDvmPoDEQT/view?usp=sharing

## Steps to reproduce

1. Must fill in project ID, and fill the info for Mobile Advert.(wasn't sure if I was suppose to keep my info on there)
2. Tapping the sprite triggers the sfx 
3. After interstitial finishes, this sfx feature is gone.

## Observed result
explained on top

## Expected result
expected sfx to still be available. 

## More details
I exported simple minified to xcode project. Tested on physical device plugged into macbook. This bug also happens to my live app. Also tested on multiple Construct versions, all the same.

## System details
All I remember seeing are: 
webkit.webview:113 not found or something like that. Processassertion:processassertionwasinvalidated. 
webfilterisactive returning: NO
interstitial created error(even though the ad manages to show)

**Comment by AshleyScirra** [comment] 2020-05-21 10:45
Duplicate of #3855

**Closed by AshleyScirra** 2020-05-21 10:45 UTC
Labels: duplicate
