### ISSUE TITLE
Problem with function names inside groups

### ISSUE THREAD

**Issue by Lobo93** [Scirra/Construct-3-bugs#2874] opened 2019-04-19 16:06 UTC
## Problem description
Cutting and pasting a group will change the names of the functions inside it, causing problems to open the file afterwards

## Attach a .c3p
[Function test.zip](https://github.com/Scirra/Construct-3-bugs/files/3098618/Function.test.zip)

## Steps to reproduce

1. create a new project
2. add a new group
3. inside the group, create a new function (Function1)
4. create an event calling the Function1
5. cut and paste the group (ctrl+X and ctrl+V on Windows)
6. save the project and reopen it

## Observed result

The project cannot be opened because the name Function1 changed to Function2 and the created action references the name Function1, which is now invalid

## Expected result

Function names wouldn't change upon cutting + pasting groups

## More details

Tested on Google chrome v 73.0.3683.103 on the latest beta release (145)

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.103
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
C3 release: r145 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 62 gb
Storage usage (approx): 142 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by FrozenWellStudios** [comment] 2019-04-20 09:41
I am having the same problem also when changing name of a  function in a group the old function still exist in the function selection area

**Comment by AshleyScirra** [comment] 2019-04-23 10:01
We cannot investigate bug reports if you don't provide a project that can be opened. We need steps to reproduce the problem from a working project. Anyway I suspect this is a duplicate of #2871.

**Closed by AshleyScirra** 2019-04-23 10:01 UTC
Labels: duplicate, no repro

**Comment by FrozenWellStudios** [comment] 2019-04-23 10:08
Hi

Sorry yes it is a duplicate of that bug

Richard
