### ISSUE TITLE
Own-texture layers render incorrectly after resizing window/layout view

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#671] opened 2017-08-04 16:43 UTC
## Problem description

Bounding box becomes detached from sprite in editor (vid)

see vid

happens randomly non repeatable.
fixes on reload of project.

video

[vid - 04-08-2017 17-32-06.zip](https://github.com/Scirra/Construct-3-bugs/files/1201033/vid.-.04-08-2017.17-32-06.zip)

## Attach a .c3p
this is the test file I was working on but will not be present on load
happens on various files.

[addgithub.zip](https://github.com/Scirra/Construct-3-bugs/files/1201031/addgithub.zip)

## Steps to reproduce
unknown

## Observed result

strange detached parallax effect 

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2017-08-07 10:11
Can't reproduce anything wrong in the .c3p you provided. Normally to fix bugs we need reliable steps to reproduce the issue. Can you find anything that causes this?

**Comment by NetOneGames** [comment] 2017-08-07 10:26
Yea.  I just happens randomly.  Maybe something to do with using a layer with additive blend. If it crops up again I will let u know.

**Comment by mOOnpunk** [comment] 2017-08-17 19:43
I am also getting this bug consitantly but also randomly. You can provide a file because the problem is fixed with an editor restart. You will need to investigate this issue please as there is not way we can help.

**Comment by AshleyScirra** [comment] 2017-08-29 14:56
I found a way to reproduce: open the given project, and resize the browser window a bit smaller (not bigger, only smaller). This makes force-own-texture layers go to a bit of a weird parallax type effect. (Only the layers with the Tint effect or Additive blend are affected, since they use their own texture.)

Should be feasible to fix this now with steps to reproduce.

**Comment by AshleyScirra** [comment] 2017-08-31 15:37
This turned out to be super complicated, but I think I've got it sorted for r53.

**Closed by AshleyScirra** 2017-08-31 15:37 UTC
Labels: difficult

**Comment by NetOneGames** [comment] 2017-09-01 11:16
Excellent: 
I don't know if it is related to any changes made prior to this fix in r53 
but now in r52 the versions of my project with tinted layers , when run, are causing layers above,  that are supposed to be hidden after certain actions,  not to hide , covering all other layers, and to become sort of rasterised, stretching with a window resize. 

I haven't yet been able to recreate directly in a C3 test project but it is consistent when running the C2 import of my game version with the tinted layer.  I will wait for 53 to see if there are any changes then investigate further.
