### ISSUE TITLE
Top 'strip' of layout not rendering on iPhone X and newer; Shows project bg color instead.

### ISSUE THREAD

**Issue by natebluewizard** [Scirra/Construct-3-bugs#4358] opened 2020-11-20 02:07 UTC
## Problem description

The issue I'm having is related to my layout not rendering all the way to the edge on device. I first saw the issue as a "black bar" in portrait mode along the top of the screen (in Scale Outer mode). After changing the Background Color to RED in the Project Properties panel, the 'bar' now appears as red, showing it seems to be properly rendering from Construct, but not my actual layout.

Thank you for looking into this!

## Attach a .c3p

https://www.3030.ca/proto/iOSFullScreen.c3p

## Steps to reproduce

1. Open attached project
2. Build to Xcode & open the workspace
3. Run the Xcode workspace on locally attached device. 

## Observed result

Display fills with GREEN except for a small bar of RED at the top.

## Expected result

Display should be filled with GREEN and no RED. 

## More details

1. When previewing in editor/chrome preview window i correctly see a full screen of green at any scale/ratio i make the preview window.

2. Using the Viewport fit: Cover option moves the red bar to the bottom instead of the top. I see this result on:

- iPhone 11 Pro running iOS 14.2
- iPad Pro running iOS 14.0.1
- iPhone X running iOS 13.5.1

It appears correctly on 

- iPhone 6 running iOS 12.4.7

3. If i set Viewport fit: Auto, I see the red bar at the top of the phone on

- iPhone 11 Pro running iOS 14.2
- iPhone X running iOS 13.5.1

The screen is fully green (correct) on:

- iPhone 11 Pro running iOS 14.2
- iPad Pro running iOS 14.0.1

4. I also ran an Android build on an android device (Moto G(8) Power) and it appears to be rendering correctly there. No red bar.

5. I also ran the same android build on a Google Pixel 3 XL (roughly same ratio as iPhone X / iPhone 11) and it is showing a full green screen there as well, no red bar.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 87.0.4280.67
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36
C3 release: r225 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 1.1 gb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro Vega 20 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment] 2020-11-20 12:40
Does this reproduce in the simulator? I'm afraid due to current lockdowns in the UK we don't have access to all our usual test devices, and it may be some time before we regain access to them.

**Comment by natebluewizard** [comment] 2020-11-20 18:19
@AshleyScirra sorry to hear about the lockdowns. 

It is reproducible in simulator, yeah, though with frustratingly different results:

With "Scale Outer" and "Viewport Fit: Auto"

- Red bar renders along the top of the screen in iphone 11 Pro simulator
- Red bar renders along the top of real iPhone 11 Pro
- No red bar on iPad Pro 12.9 Inch
- No red bar on iPad Pro 11 inch simulator

With "Scale Outer" and "Viewport Fit: Cover"

- No red bar on iPhone 11 Pro simulator
- No red bar renders along the top of real iPhone 11 Pro
- Red bar on the bottom of real iPad Pro 12.9"
- No red bar on the bottom of iPad Pro 11 inch Simulator
- No red bar on the bottom of iPad Pro 12.9 inch Simulator

**Comment by natebluewizard** [comment] 2020-11-20 21:08
Some more info as ive run like 50 different builds with various settings both on my own game as well as the test project trying to narrow in on what might be the issue. The problem though is i've had the exact same build run on an iPhone 11 Pro simulator BOTH with red bar and without red bar.  

The bar appears on the BOTTOM if i have "Scale Outer" and "Viewport Fit: Cover" set. If i simply run the workspace in xcode in the simulator i can hit stop and run it again for a different result. Ive attached the console logs from a couple times run with and without the red bar. It seems to be random and i cant really tell any major difference from the logs for when it shows up and when it doesnt. 

The other thing to note is that teh Construct 3 loading screen ALSO shows the red background color strip so it does appear to be something outside of the actual specific layout etc.

`NO RED BAR

2020-11-20 13:01:08.542757-0800 iOSFullScreen[56643:1199057] Apache Cordova native platform version 6.1.0 is starting.
2020-11-20 13:01:08.542895-0800 iOSFullScreen[56643:1199057] Multi-tasking -> Device: YES, App: YES
2020-11-20 13:01:08.666295-0800 iOSFullScreen[56643:1199057] The preference key "AllowNewWindows" is not defined and will default to "FALSE"
2020-11-20 13:01:08.667701-0800 iOSFullScreen[56643:1199057] The preference key "MediaPlaybackAllowsAirPlay" is not defined and will default to "TRUE"
2020-11-20 13:01:08.672936-0800 iOSFullScreen[56643:1199057] The preference key "AllowBackForwardNavigationGestures" is not defined and will default to "FALSE"
2020-11-20 13:01:08.673042-0800 iOSFullScreen[56643:1199057] The preference key "Allow3DTouchLinkPreview" is not defined and will default to "TRUE"
2020-11-20 13:01:08.673145-0800 iOSFullScreen[56643:1199057] CDVWebViewEngine will reload WKWebView if required on resume
2020-11-20 13:01:08.673234-0800 iOSFullScreen[56643:1199057] Using WKWebView
2020-11-20 13:01:08.673577-0800 iOSFullScreen[56643:1199057] [CDVTimer][console] 0.048995ms
2020-11-20 13:01:08.673748-0800 iOSFullScreen[56643:1199057] [CDVTimer][handleopenurl] 0.040054ms
2020-11-20 13:01:08.674745-0800 iOSFullScreen[56643:1199057] [CDVTimer][intentandnavigationfilter] 0.889897ms
2020-11-20 13:01:08.674895-0800 iOSFullScreen[56643:1199057] [CDVTimer][gesturehandler] 0.036001ms
2020-11-20 13:01:08.676226-0800 iOSFullScreen[56643:1199057] [CDVTimer][statusbar] 1.227975ms
2020-11-20 13:01:08.676358-0800 iOSFullScreen[56643:1199057] [CDVTimer][TotalPluginStartup] 2.874017ms
2020-11-20 13:01:08.758727-0800 iOSFullScreen[56643:1199057] WF: === Starting WebFilter logging for process iOSFullScreen
2020-11-20 13:01:08.758848-0800 iOSFullScreen[56643:1199057] WF: _userSettingsForUser : (null)
2020-11-20 13:01:08.758968-0800 iOSFullScreen[56643:1199057] WF: _WebFilterIsActive returning: NO


NO RED BAR

2020-11-20 13:01:54.935499-0800 iOSFullScreen[57315:1201134] Apache Cordova native platform version 6.1.0 is starting.
2020-11-20 13:01:54.935635-0800 iOSFullScreen[57315:1201134] Multi-tasking -> Device: YES, App: YES
2020-11-20 13:01:55.063587-0800 iOSFullScreen[57315:1201134] The preference key "AllowNewWindows" is not defined and will default to "FALSE"
2020-11-20 13:01:55.064733-0800 iOSFullScreen[57315:1201134] The preference key "MediaPlaybackAllowsAirPlay" is not defined and will default to "TRUE"
2020-11-20 13:01:55.069509-0800 iOSFullScreen[57315:1201134] The preference key "AllowBackForwardNavigationGestures" is not defined and will default to "FALSE"
2020-11-20 13:01:55.069642-0800 iOSFullScreen[57315:1201134] The preference key "Allow3DTouchLinkPreview" is not defined and will default to "TRUE"
2020-11-20 13:01:55.069767-0800 iOSFullScreen[57315:1201134] CDVWebViewEngine will reload WKWebView if required on resume
2020-11-20 13:01:55.069865-0800 iOSFullScreen[57315:1201134] Using WKWebView
2020-11-20 13:01:55.070206-0800 iOSFullScreen[57315:1201134] [CDVTimer][console] 0.046968ms
2020-11-20 13:01:55.070395-0800 iOSFullScreen[57315:1201134] [CDVTimer][handleopenurl] 0.054002ms
2020-11-20 13:01:55.071518-0800 iOSFullScreen[57315:1201134] [CDVTimer][intentandnavigationfilter] 1.010060ms
2020-11-20 13:01:55.071682-0800 iOSFullScreen[57315:1201134] [CDVTimer][gesturehandler] 0.044942ms
2020-11-20 13:01:55.073131-0800 iOSFullScreen[57315:1201134] [CDVTimer][statusbar] 1.323938ms
2020-11-20 13:01:55.073259-0800 iOSFullScreen[57315:1201134] [CDVTimer][TotalPluginStartup] 3.139973ms
2020-11-20 13:01:55.147598-0800 iOSFullScreen[57315:1201134] WF: === Starting WebFilter logging for process iOSFullScreen
2020-11-20 13:01:55.147720-0800 iOSFullScreen[57315:1201134] WF: _userSettingsForUser : (null)
2020-11-20 13:01:55.147824-0800 iOSFullScreen[57315:1201134] WF: _WebFilterIsActive returning: NO


RED BAR

2020-11-20 13:02:25.029278-0800 iOSFullScreen[57791:1203146] Apache Cordova native platform version 6.1.0 is starting.
2020-11-20 13:02:25.029450-0800 iOSFullScreen[57791:1203146] Multi-tasking -> Device: YES, App: YES
2020-11-20 13:02:25.176438-0800 iOSFullScreen[57791:1203146] The preference key "AllowNewWindows" is not defined and will default to "FALSE"
2020-11-20 13:02:25.177595-0800 iOSFullScreen[57791:1203146] The preference key "MediaPlaybackAllowsAirPlay" is not defined and will default to "TRUE"
2020-11-20 13:02:25.183089-0800 iOSFullScreen[57791:1203146] The preference key "AllowBackForwardNavigationGestures" is not defined and will default to "FALSE"
2020-11-20 13:02:25.183213-0800 iOSFullScreen[57791:1203146] The preference key "Allow3DTouchLinkPreview" is not defined and will default to "TRUE"
2020-11-20 13:02:25.183319-0800 iOSFullScreen[57791:1203146] CDVWebViewEngine will reload WKWebView if required on resume
2020-11-20 13:02:25.183418-0800 iOSFullScreen[57791:1203146] Using WKWebView
2020-11-20 13:02:25.183743-0800 iOSFullScreen[57791:1203146] [CDVTimer][console] 0.045061ms
2020-11-20 13:02:25.183946-0800 iOSFullScreen[57791:1203146] [CDVTimer][handleopenurl] 0.059009ms
2020-11-20 13:02:25.184910-0800 iOSFullScreen[57791:1203146] [CDVTimer][intentandnavigationfilter] 0.846982ms
2020-11-20 13:02:25.185068-0800 iOSFullScreen[57791:1203146] [CDVTimer][gesturehandler] 0.038981ms
2020-11-20 13:02:25.186515-0800 iOSFullScreen[57791:1203146] [CDVTimer][statusbar] 1.327991ms
2020-11-20 13:02:25.186648-0800 iOSFullScreen[57791:1203146] [CDVTimer][TotalPluginStartup] 2.989054ms
2020-11-20 13:02:25.266430-0800 iOSFullScreen[57791:1203146] WF: === Starting WebFilter logging for process iOSFullScreen
2020-11-20 13:02:25.266619-0800 iOSFullScreen[57791:1203146] WF: _userSettingsForUser : (null)
2020-11-20 13:02:25.266750-0800 iOSFullScreen[57791:1203146] WF: _WebFilterIsActive returning: NO


RED BAR

2020-11-20 13:03:15.289450-0800 iOSFullScreen[58559:1206140] Apache Cordova native platform version 6.1.0 is starting.
2020-11-20 13:03:15.289618-0800 iOSFullScreen[58559:1206140] Multi-tasking -> Device: YES, App: YES
2020-11-20 13:03:15.412599-0800 iOSFullScreen[58559:1206140] The preference key "AllowNewWindows" is not defined and will default to "FALSE"
2020-11-20 13:03:15.413718-0800 iOSFullScreen[58559:1206140] The preference key "MediaPlaybackAllowsAirPlay" is not defined and will default to "TRUE"
2020-11-20 13:03:15.418089-0800 iOSFullScreen[58559:1206140] The preference key "AllowBackForwardNavigationGestures" is not defined and will default to "FALSE"
2020-11-20 13:03:15.418192-0800 iOSFullScreen[58559:1206140] The preference key "Allow3DTouchLinkPreview" is not defined and will default to "TRUE"
2020-11-20 13:03:15.418293-0800 iOSFullScreen[58559:1206140] CDVWebViewEngine will reload WKWebView if required on resume
2020-11-20 13:03:15.418410-0800 iOSFullScreen[58559:1206140] Using WKWebView
2020-11-20 13:03:15.418726-0800 iOSFullScreen[58559:1206140] [CDVTimer][console] 0.048041ms
2020-11-20 13:03:15.418915-0800 iOSFullScreen[58559:1206140] [CDVTimer][handleopenurl] 0.056028ms
2020-11-20 13:03:15.419899-0800 iOSFullScreen[58559:1206140] [CDVTimer][intentandnavigationfilter] 0.877976ms
2020-11-20 13:03:15.420075-0800 iOSFullScreen[58559:1206140] [CDVTimer][gesturehandler] 0.048041ms
2020-11-20 13:03:15.421667-0800 iOSFullScreen[58559:1206140] [CDVTimer][statusbar] 1.469016ms
2020-11-20 13:03:15.421800-0800 iOSFullScreen[58559:1206140] [CDVTimer][TotalPluginStartup] 3.160000ms
2020-11-20 13:03:15.504607-0800 iOSFullScreen[58559:1206140] WF: === Starting WebFilter logging for process iOSFullScreen
2020-11-20 13:03:15.504739-0800 iOSFullScreen[58559:1206140] WF: _userSettingsForUser : (null)
2020-11-20 13:03:15.504844-0800 iOSFullScreen[58559:1206140] WF: _WebFilterIsActive returning: NO
`

**Comment by AshleyScirra** [comment] 2020-11-23 17:06
Unfortunately it's not very helpful if the simulator works differently - it suggests a fix for the simulator won't necessarily fix a real device. So I think we will have to wait until we get back to a real device to investigate further.

Other than that the only other key detail to be figured out at this time is: when did this start happening? Has it always been the case? (I have not heard of anyone else publishing to iOS having this problem.) Or if not was there a specific Construct or iOS update that caused this?

**Comment by natebluewizard** [comment] 2020-11-23 18:21
@AshleyScirra 

Understood about Auto vs. Cover. Agree that ideally Cover would just 'cover', so am happy to just focus on those settings moving forward

Sorry i know my initial post said that the issue didnt appear in simulator but I was able to reproduce it using the simulator, it just seems to 'randomly' happen. So in my initial tests it was working fine but if i simply stop and restart the simulator over and over about 1 every 4 times it will reproduce the issue. The other times it fills the screen as expected, with no change to the project settings or code, just simply re-running it.

This is the first mobile game I have been developing with C3, so unfortunately this is my first experience with this, just started looking into this issue the past week because ive been trying to get the game looking good on both phones and tablets which I think requires using the "Cover" setting unfortunately.

Im happy to mail you a test device if it helps the process of getting it looked at. I'm at the point in prototyping where i need to decide pretty quick if I can actually ship the game with C3 or start rebuilding it in another engine entirely. Unfortunately with this issue, I cant see shipping it as-is, as theres either a bar of background color at the top or bottom or both, depending on what settings i use.

**Comment by natebluewizard** [comment] 2020-11-23 23:37
I think i got this figured out, or at least have a workaround for myself... 

If i add <html id="html" style="height: 3000px"> to the output index.html before i build in xcode, i dont see the issue at all. If i change that line back to <html> it sometimes works, sometimes doesnt.. When it doesnt work i get a black (background color) bar on the bottom of the screen. I think whatever should be detecting / setting the device height is processing too late, so forcing the <html> to be 3000px (bigger than required in any case so far) it seems to help. 

Now the question is, and i beg of you... is there any way to customize the output html file so i dont have to change it every time i build? Or is this a 'fix' worthy of including in the actual exporter? 

Thank you so so much for any help you can give!

**Comment by AshleyScirra** [comment] 2021-01-26 16:11
@natebluewizard - r233 has a change that may help with this issue. Can you test again with that?

**Comment by Ambision** [comment] 2021-01-26 16:50
Hi, I have the same problem, and unfortunately R233 didnt resolve the issue. 

@natebluewizard - can you please refer me to the index.html and place were to put this in the html file? Thanks

**Comment by Ambision** [comment] 2021-01-26 16:51
Working now 3 days on resolving this issue, but indeed sometimes it works fine and sometimes it doesn't. Tested on 11 Pro and 12 Pro.

**Comment by natebluewizard** [comment] 2021-01-26 17:14
@AshleyScirra will try in a bit and let you know! 
@Ambision ive found if you open the downloaded XCode Workspace folder, then in the www folder there's an index.html. In that file, edit the `<html>` line to be` <html id="html" style="height: 3000px">` and its totally shippable for me, works great consistently every time.

**Comment by Ambision** [comment] 2021-01-26 17:44
@natebluewizard - I had changed it already, but found out that visual studio didn't saved the changes. And Yes, you are right! it works after testing with different devices! I am so happy that you found and shared the solution! Thanks a million! It's my birthday tomorrow and I would like to release my first app tomorrow too :) Hopefully it will be visible in a couple of days as Apple needs to review this too. By the way, I'm planning to export to android too, I hope and assume there are no difficulties on that platform :). Thanks again!

**Comment by robinhoed123** [comment] 2021-01-26 18:27
My issue white full screen inner scaling has been resolved in r 233 thanks😀

**Comment by AshleyScirra** [comment] 2021-01-27 12:43
It's not quite clear to me from these comments what the situation is - does it work now out of the box with r233, or does it only work with editing the HTML tag? Please be specific as to which you are using.

The runtime already sets a size in the HTML tag to work around an iOS viewport bug. It sets the screen size so it doesn't have to hard-code a limit. (If you hard code it, sooner or later a device with a bigger screen appears, and then it's broken again - something we already went through with a workaround for the iPad 3!) I can only guess that iOS has yet another bug that reports the screen size incorrectly? I'll see if I can adjust the workaround for the next beta cycle.

**Comment by Ambision** [comment] 2021-01-27 13:09
@AshleyScirra - for me it worked by editing the html as detailed by natebluewizard (editing the html). I agree that it isn't a long term solution, but at least I can continue for now and await a solution later on.

Re r233, this didn't worked out for me, unfortunately. When starting the app on the iphones (11 pro and 12 pro) only the C3 logo is shown, but doesn't continue loading. So it's getting stuck somehow. So as it doesn't continue loading, I'm not able to see/test whether the viewport is consistently correctly loaded.

**Comment by Ambision** [comment] 2021-01-27 13:34
By the way, I've tries to debug myself by displaying the following platforminfo properties. ("WindowsInner: " & PlatformInfo.WindowInnerWidth & "x" & PlatformInfo.WindowInnerHeight & newline &"WindowsOuter: " & PlatformInfo.WindowOuterWidth & "x" & PlatformInfo.WindowOuterHeight)

When it's running ok on the phones, then I get the following info:
WindowsInner: 375x812 (widhtxheight)
WindowsOuter: 375x812

But randomly fails, I get the following info:
WindowsInner: 375x734
WindowsOuter: 375x812

So I think you are right by saying that it's an IOS issue, reporting back different screen/display properties.

**Comment by robinhoed123** [comment] 2021-01-27 14:02
My problem/bug was white fullscreen mode  **inner scaling** that bug has been resolved in r233 the the fullscreen mode:**outer scaling** is still  buggy

**Comment by AshleyScirra** [comment] 2021-01-27 16:23
> Re r233, this didn't worked out for me, unfortunately. When starting the app on the iphones (11 pro and 12 pro) only the C3 logo is shown, but doesn't continue loading. So it's getting stuck somehow.

That sounds like a serious regression. We can't afford to break existing iOS apps. I'll revert the change for the upcoming stable release and review this again for the next release cycle, it sounds like the attempted fix wasn't effective anyway.

**Comment by AshleyScirra** [comment] 2021-01-27 16:25
BTW, one more thing to check: if you enable "Any" orientations, and then when the display looks wrong, rotate the device orientation, does changing the orientation correct it?

**Comment by robinhoed123** [comment] 2021-01-27 17:16
> > Re r233, this didn't worked out for me, unfortunately. When starting the app on the iphones (11 pro and 12 pro) only the C3 logo is shown, but doesn't continue loading. So it's getting stuck somehow.
> 
> That sounds like a serious regression. We can't afford to break existing iOS apps. I'll revert the change for the upcoming stable release and review this again for the next release cycle, it sounds like the attempted fix wasn't effective anyway.

Maybe a better solution is to only apply the fix when  **inner scaling** is selected because it did work for me and I don’t want to break my app again😀

**Comment by AshleyScirra** [comment] 2021-01-28 10:54
I don't believe the scaling mode has any impact on this. The issue appears to be related to determining the overall screen/viewport size, which is done before any scaling mode is applied.

**Comment by fomalsd** [comment] 2021-01-28 18:50
Hi! just letting you know that we had an issue with several games not always occupying full screen area on latest stable and r231 when exporting to iOS Xcode projects. It's most noticeable on wider devices like iPhones.
It used to look like that:
<img width="752" alt="Scr 2021-01-28 в 21 48 22" src="https://user-images.githubusercontent.com/10403536/106184450-98c43300-61b2-11eb-8ad6-6e84550ad429.png">

They all happened to be `Landscape` orientation, with `Viewport fit = Cover` and `Fullscreen mode = Scale outer`.
Seemed like engine didn't always detect screen size correctly when device was originally in portrait mode or something... but that's just speculation.

Now, **r233 seemed to have fixed that** for our case! So thanks for that!

**Comment by robinhoed123** [comment] 2021-02-02 14:51
> Hi! just letting you know that we had an issue with several games not always occupying full screen area on latest stable and r231 when exporting to iOS Xcode projects. It's most noticeable on wider devices like iPhones.
> It used to look like that:
> <img alt="Scr 2021-01-28 в 21 48 22" width="752" src="https://user-images.githubusercontent.com/10403536/106184450-98c43300-61b2-11eb-8ad6-6e84550ad429.png">
> 
> They all happened to be `Landscape` orientation, with `Viewport fit = Cover` and `Fullscreen mode = Scale outer`.
> Seemed like engine didn't always detect screen size correctly when device was originally in portrait mode or something... but that's just speculation.
> 
> Now, **r233 seemed to have fixed that** for our case! So thanks for that!
> P.S. we didn't change any html tags

Ps don’t update to stable release r334
Because they undid the fix that solved it.

**Comment by AshleyScirra** [comment] 2021-02-02 17:04
A [prior comment](https://github.com/Scirra/Construct-3-bugs/issues/4358#issuecomment-768274311) sounded like in some cases the attempted fix actually completely broke iOS apps, so it was removed for r234. There's a different fix which is hopefully more reliable in the next beta release.

**Comment by AshleyScirra** [comment] 2021-02-11 15:33
r235 includes a new fix for getting the right viewport consistently on iOS. Can those affected re-test with that and let me know if it's helped?

**Comment by natebluewizard** [comment] 2021-02-11 20:17
Using r234.4, ran on local device 10 times
5 times received 'background color' bar.
5 times received proper full screen.

Using r235
5 times received 'background color' bar
5 times received proper full screen
-- oddly, was getting perfect results for first 4 tries, then on 5,6,7,8,10 try it had the black background bar. 

So Tried another 10 using r235
7 times received the 'background' bar
3 times received no bar.

Your earlier question was tested too - on the times where it loads with a background bar if i tilt my phone to landscape mode then back to portrait (once all those options are available in device orientation), it will 'fix' the bar and go proper full screen.

Sorry for the bad news :(

**Comment by AshleyScirra** [comment] 2021-02-12 12:06
The workaround in r235 effectively sets `<html id="html" style="height: 3000px">`, which you previously said worked successfully. The only difference is it sets the size to the screen size plus 50%, to ensure it overshoots and avoid having to hard-code a specific size. I have no idea why what you said previously would work but not the workaround in r235. Are you sure your workaround was actually working reliably? I just don't know what else we could do about this.

**Comment by AshleyScirra** [comment] 2021-02-12 12:17
I took another look at our workaround and it was using the viewport size to determine the device orientation, which I guess we can't trust since the whole problem seems to be iOS providing the wrong size. I adjusted the workaround to not depend on the device orientation. So worth checking again with the next release.

**Comment by AshleyScirra** [comment] 2021-02-16 15:05
r236 tries another workaround, which is basically an orientation-neutral way of the workaround that @natebluewizard and @Ambision both appeared to confirmed worked. Can someone verify if r236 solves the problem?

**Comment by natebluewizard** [comment] 2021-02-16 18:42
@AshleyScirra so sorry, but i ran 10 more times in a build made with 236 and 50% of the time it launches with the black bar still. :(

**Comment by natebluewizard** [comment] 2021-02-16 18:47
Actually, it also seems like forcing height: 3000px in the index.html no longer works now either.

**Comment by natebluewizard** [comment] 2021-02-16 18:55
Just to confirm: 
Rolling back to 234.4 and using the height: 3000px edit in index.html, the app opens with fullscreen 100% of the time after 10 attempts.

**Comment by AshleyScirra** [comment] 2021-02-17 11:38
I have no idea why that works and the workaround I did doesn't work!

**Comment by AshleyScirra** [comment] 2021-02-18 14:48
Alright, I can only guess that the issue is some startup synchronisation problem, and by the time our engine runs, it's too late to amend the HTML element size. So in the next release it actually adds a large size to the root HTML tag when exporting for iOS, in effect automatically applying the workaround that seems to be the only one that works. Let's see if that sorts this out...

**Comment by AshleyScirra** [comment] 2021-02-24 12:17
r237 now exports iOS apps with an adjusted HTML tag to specify a large size, basically as per [this previous comment](https://github.com/Scirra/Construct-3-bugs/issues/4358#issuecomment-767692332), which apparently worked reliably. Can those with affected devices check again and see if this fixes it?

**Comment by fomalsd** [comment] 2021-02-27 11:47
seems to have worked for us, thanks!

**Comment by Ambision** [comment] 2021-03-02 10:31
hi all, thanks for the update! 
It seems that R237 does not export my app correctly from Construct 3. So I am not able to test the fix. The project file decreases in size from 18mb to 10mb and Xcode generates the following error:

_Showing All Messages
<app name>.ios.project (37)/cordova/../pods-debug.xcconfig:2: could not find included file 'Pods/Target Support Files/Pods-Top Tree/Pods-Top Tree.debug.xcconfig' in search paths_

**Comment by AshleyScirra** [comment] 2021-03-02 10:42
I don't know what that error means and I don't know why that would have happened.

Have you tried exporting to a new empty folder? If you overwrite an existing Xcode project with a fresh export, I think you would just end up corrupting it.

**Comment by Ambision** [comment] 2021-03-02 10:44
yes, tried that also. tried a new export with current stable release and works fine. Maybe related to another change?

**Comment by AshleyScirra** [comment] 2021-03-02 10:48
I can't think of anything we did in r237 that would have affected that. I have also done a couple of my own Xcode exports for testing various things which worked fine, and other users who have reported it works are presumably also doing successful Xcode exports in r237. My best guess is it's something wrong with your specific system or copy of Xcode.

**Comment by Ambision** [comment] 2021-03-02 11:19
Might be. I am using version 12.4 (12D4e) of Xcode. It might also be related to a plugin I'm using for push notifications.

**Comment by AshleyScirra** [comment] 2021-03-02 11:24
Could you try a separate export with a new project or something else that you can get working? It would be useful to get verification this issue is resolved regardless of that issue with Xcode.

**Comment by Ambision** [comment] 2021-03-02 12:01
tried a previous version of my app, but gets stuck on the loading layout (same issue as encountered on 27 jan). Tried a clean project with screen settings and runs ok.

**Comment by Ambision** [comment] 2021-03-02 12:04
still it concerns me that the Cordova export from current stable release 234.4 works fine with Xcode, but R237 does not. Though likely not related to this issue.

**Comment by Ambision** [comment] 2021-03-02 12:05
when other users are fine with R237, I am fine continuing working on earlier versions.

**Comment by AshleyScirra** [comment] 2021-03-02 13:18
I'm trying to establish whether the issue reported here is fixed or not. When you wrote this:

> Tried a clean project with screen settings and runs ok.

Was this confirmation that with a new project, the issue is resolved?

**Comment by Ambision** [comment] 2021-03-02 13:27
yes

> I'm trying to establish whether the issue reported here is fixed or not. When you wrote this:
> 
> > Tried a clean project with screen settings and runs ok.
> 
> Was this confirmation that with a new project, the issue is resolved?

yes

**Comment by AshleyScirra** [comment] 2021-03-02 14:23
OK, we've had a couple of confirmations now that the issue is resolved, so closing. Thanks for the feedback all.

If you have any further issues please file separate issues for them following the guidelines.

**Closed by AshleyScirra** 2021-03-02 14:23 UTC
Labels: iOS, need info
