### ISSUE TITLE
CRASH when adding PARTICLE to FAMILY

### ISSUE THREAD

**Issue by rvion** [Scirra/Construct-3-bugs#677] opened 2017-08-07 15:01 UTC
## Problem description

construct 3 crash when adding a particle object to a family

## Affected browsers

tested on Chrome

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: incompatible plugin
Stack: Error at Function.ǃE.ǃOVP (https://editor.construct.net/r48/main.js:2:202201) at t (https://editor.construct.net/r48/main.js:2:171837) at window.assert (https://editor.construct.net/r48/main.js:2:172240) at ǃE.ǃo.ǃT.ǃAlJ.ǃAlb (https://editor.construct.net/r48/main.js:149:59916) at HTMLButtonElement.ǃAlv.onclick (https://editor.construct.net/r48/main.js:149:57814)
Construct 3 version: r48
URL: https://editor.construct.net/
Date: Mon Aug 07 2017 16:58:19 GMT+0200 (CEST)
Uptime: 194.6 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r48

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2017-08-10 15:48
Can't reproduce. I can add a Particles object to a family in a new project without any problems. Please always follow the full bug report guidelines to ensure we can fix the problem.

**Comment by rvion** [comment] 2017-08-10 15:55
here is a project (renamed *.c3p to *.c3p.zip to be able to upload it here)
[bug-family.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1215517/bug-family.c3p.zip)

steps:
 1. open this project
 2. try adding "Particles" to "Family1"
 3. crash

ping @AshleyScirra

**Comment by rvion** [comment] 2017-08-10 15:56
<details><summary>Platform information</summary>

Platform information
Browser: Chrome
Browser version: 60.0.3112.90
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
C3 release: r48

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 398 mb (2.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by rvion** [comment] 2017-08-10 16:08
@AshleyScirra I'll try to make better bug report, thanks for the quick follow up :)

----------------

## Problem description

construct 3 crash when adding a particle object to a family containing a sprite 

## Attach a .c3p

[bug-family.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1215544/bug-family.c3p.zip)

## Steps to reproduce

1. open this project
2. try adding "Particles" to "Family1"
3. crash

## Observed result

a crash:


<details><summary>error message:</summary>

Error report information
Type: assertion failure
Message: incompatible plugin
Stack: Error at Function.ǃE.ǃOVP (https://editor.construct.net/r48/main.js:2:202201) at t (https://editor.construct.net/r48/main.js:2:171837) at window.assert (https://editor.construct.net/r48/main.js:2:172240) at ǃE.ǃo.ǃT.ǃAlJ.ǃAlb (https://editor.construct.net/r48/main.js:149:59916) at HTMLButtonElement.ǃAlv.onclick (https://editor.construct.net/r48/main.js:149:57814)
Construct 3 version: r48
URL: https://editor.construct.net/
Date: Thu Aug 10 2017 18:05:13 GMT+0200 (CEST)
Uptime: 752.2 s

Platform information
Browser: Chrome
Browser version: 60.0.3112.90
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
C3 release: r48

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

## Expected result

The Particles object is added to the family

## Affected browsers

* Chrome: yes : see system details below:
* Firefox: don't know
* Edge: don't know
* Safari: don't know

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 60.0.3112.90
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
C3 release: r48

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 399 mb (2.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2017-08-10 16:17
Thanks, should be fixed in r49.

**Closed by AshleyScirra** 2017-08-10 16:17 UTC
