### ISSUE TITLE
Crash Construct 3 on close timeline window

### ISSUE THREAD

**Issue by rafaeltrigo** [Scirra/Construct-3-bugs#5016] opened 2021-08-13 10:27 UTC
Error report information
Type: unhandled rejection
Reason: Error: Cannot set property 'textContent' of null @ TypeError: Cannot set property 'textContent' of null at d.g.Ia.fia.FE (https://editor.construct.net/r251-2/main.js:754:243) at k.g7a (https://editor.construct.net/r251-2/components/bars/timelineBar/timelineBar.js:9:332) at k.d2a (https://editor.construct.net/r251-2/components/bars/timelineBar/timelineBar.js:9:244) at k.Wc (https://editor.construct.net/r251-2/components/bars/timelineBar/timelineBar.js:9:494) at k.A (https://editor.construct.net/r251-2/components/bars/timelineBar/timelineBar.js:5:388) at Array.vCa (https://editor.construct.net/r251-2/main.js:2048:237) at d.Event.CRc.Wfd (https://editor.construct.net/r251-2/main.js:432:387) at d.g.Ia.fia.dispatchEvent (https://editor.construct.net/r251-2/main.js:428:135) at d.g.Ia.fia.Bf (https://editor.construct.net/r251-2/main.js:717:411) at d.g.Ia.fia.Bf (https://editor.construct.net/r251-2/main.js:728:286)
Stack: TypeError: Cannot set property 'textContent' of null at d.g.Ia.fia.FE (https://editor.construct.net/r251-2/main.js:754:243) at k.g7a (https://editor.construct.net/r251-2/components/bars/timelineBar/timelineBar.js:9:332) at k.d2a (https://editor.construct.net/r251-2/components/bars/timelineBar/timelineBar.js:9:244) at k.Wc (https://editor.construct.net/r251-2/components/bars/timelineBar/timelineBar.js:9:494) at k.A (https://editor.construct.net/r251-2/components/bars/timelineBar/timelineBar.js:5:388) at Array.vCa (https://editor.construct.net/r251-2/main.js:2048:237) at d.Event.CRc.Wfd (https://editor.construct.net/r251-2/main.js:432:387) at d.g.Ia.fia.dispatchEvent (https://editor.construct.net/r251-2/main.js:428:135) at d.g.Ia.fia.Bf (https://editor.construct.net/r251-2/main.js:717:411) at d.g.Ia.fia.Bf (https://editor.construct.net/r251-2/main.js:728:286)
Construct 3 version: r251.2
URL: https://editor.construct.net/
Date: Fri Aug 13 2021 11:17:56 GMT+0100 (Western European Summer Time)
Uptime: 27089 s

Platform information
Browser: Edge
Browser version: 92.0.902.67
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36 Edg/92.0.902.67
C3 release: r251.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0, D3D11-21.20.16.4550)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by AshleyScirra** [comment] 2021-08-13 10:51
@DiegoScirra - another duplicate of #4943?

**Comment by DiegoScirra** [comment] 2021-08-13 11:00
@AshleyScirra No, the stack trace is different. I think I fixed this one, but without reproduction steps is difficult to tell.

**Comment by DiegoScirra** [comment] 2021-08-23 16:52
Will be fixed starting on the next beta cycle.

**Closed by DiegoScirra** 2021-08-23 16:52 UTC
Labels: ignored guidelines
