### ISSUE TITLE
Custom Webfonts (.woff) Do Not Load In Preview

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#54] opened 2017-04-09 23:39 UTC
## Problem description
Custom webfonts (.woff) don't load in preview. 
They load fine inside the editor and the exported HTML5 game.

## Attach a .c3p
[Download Example](https://cdn.discordapp.com/attachments/225550155531812865/300774833330061314/Webfont_Bug.c3p)
(For some reason Git didn't like my zip archive, no clue why...)

## Steps to reproduce

1. Open Project
2. Start Preview
3. Notice that the font didn't load and is still in arial

## Observed result

*The imported font doesn't load inside the game preview.*

## Expected result

*I want my imported fonts to load in preview like everywhere else.*

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

<details><summary>View details</summary>

No crashes or error messages inside the browser log.
Using the latest version of Chrome and C3 of course.

</details>

**Comment by AshleyScirra** [comment] 2017-04-11 11:19
Looks like a duplicate of https://www.scirra.com/forum/construct-3-really-strange-behavior-with-custom-fonts_t189775, appears to already be fixed for r17.

**Comment by shortercode** [comment] 2017-04-27 16:22
Seeing this again on r22

Testcase: 

https://www.dropbox.com/s/wvt9jqc69xnjy8j/FontBug.c3p?dl=0

**Comment by shortercode** [comment] 2017-04-27 17:00
Removed the duplicate tag as we're only tracking the bug on here now.

**Comment by AshleyScirra** [comment] 2017-04-27 17:15
That project uses a bit of a weird name (.ttf.woff). Still it was a simple fix, just canvas2d not parsing the name unless it's put in quotes. Guessing it's the dot in the name. Fixed for r23.

**Closed by AshleyScirra** 2017-04-27 17:15 UTC

**Comment by shortercode** [comment] 2017-04-27 17:18
Yeah it's just how it was provided, I think it kind of makes sense though as woff files are containers for ttf and otf files? Either way it's good that we fixed the name parsing.
