### ISSUE TITLE
Error: image sprite collection needs rebuilding

### ISSUE THREAD

**Issue by Maudoz** [Scirra/Construct-3-bugs#1524] opened 2018-04-25 09:27 UTC
## Problem description
Hi, when i try to add another 
file in my project, it doesn't show the content. I can see a selected box, but its empty. When I try to delete it in my library, i get an error. Did restart my computer but that didn't work. In earlier project i did not have this problem
## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r94-2/main.js, line 63, col 706137
Message: Error: image sprite collection needs rebuilding
Stack: ǃXx@https://editor.construct.net/r94-2/main.js:63:706093 ǃXK@https://editor.construct.net/r94-2/main.js:63:1036535 ǃXN@https://editor.construct.net/r94-2/plugins/sprite/plugin.js:1:9369 ǃXN@https://editor.construct.net/r94-2/main.js:63:803548 ǃXN@https://editor.construct.net/r94-2/main.js:63:842996 ǃXN@https://editor.construct.net/r94-2/main.js:63:827299 ǃvW@https://editor.construct.net/r94-2/components/editors/layoutView/layoutView.js:1:7176 ǃva@https://editor.construct.net/r94-2/components/editors/layoutView/layoutView.js:1:1812
Construct 3 version: r94.2
URL: https://editor.construct.net/
Date: Wed Apr 25 2018 11:22:53 GMT+0200 (CEST)
Uptime: 75.4 s

Platform information
Browser: Safari
Browser version: 11.1
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
C3 release: r94.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (2.1 INTEL-10.32.48)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel HD Graphics 4000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions: EXT_blend_minmax, EXT_sRGB, EXT_frag_depth, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_standard_derivatives, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, OES_vertex_array_object, OES_element_index_uint, WEBGL_lose_context, WEBGL_compressed_texture_s3tc, WEBGL_depth_texture, WEBGL_draw_buffers, ANGLE_instanced_arrays, WEBGL_debug_renderer_info

</details>

**Comment by AshleyScirra** [comment] 2018-04-25 10:13
Looks like a duplicate of #1460. Please only file bugs if they reproduce in the latest beta release, it looks like you used r94.2.

**Closed by AshleyScirra** 2018-04-25 10:13 UTC
Labels: safari
