### ISSUE TITLE
Function parameter letter-case not updating in references 

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4864] opened 2021-06-02 18:29 UTC
## Problem description

Changing the sentence case of a parameter doesn't update the parameter in actions (e.g. setting the value of a variable, writing a browser log, etc)

## Attach a .c3p

https://drive.google.com/file/d/1OuNQ8Tj9aLBhHqKeL5gbt6D0sa2ucAHC/view?usp=sharing

## Steps to reproduce

1. Open the attached project.
2. Change the function parameter from "lowercase_param" to "lowercase_paraM" (capital M at the end).
3. Notice the browser log and sprite variable lines don't change.

## Observed result

The reference in the function call changes letter-case, but not in the actions where it's referenced. 

## Expected result

All references to the parameter would match the letter-case of the parameter.

## More details

**Affected browsers/platforms:** Chrome 91

**First affected release:** r250

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2021-06-03 11:34
Duplicate of #4819. This is currently by design as explained in [this comment](https://github.com/Scirra/Construct-3-bugs/issues/4819#issuecomment-840661205): Construct aims to preserve expressions as you typed them, and only changes the case if it has to.

**Closed by AshleyScirra** 2021-06-03 11:34 UTC
Labels: duplicate

**Comment by brushfe** [comment] 2021-06-03 11:43
Thanks for the insight behind this. While I understand the reasoning to listen to user preference, isn't there now more evidence from contemporary users that this _isn't_ the preferred style?

**Comment by AshleyScirra** [comment] 2021-06-03 11:52
Other users file issues when Construct unnecessarily changes their expressions. I don't think things like this should be considered a bug, they are design questions where different people prefer different options. If you think the design should be changed you can file a suggestion, but I suspect other users may disagree, so it's not necessarily an uncontroversial change to make, and I think it's too minor to warrant a setting. Besides you can just rename it to something else and then back again if you want to force Construct to rewrite the expressions you typed.

**Comment by brushfe** [comment] 2021-06-03 12:09
Good point — this is definitely the wrong forum for it! The new voting platform sounds like it'll be great for this kinda thing. Appreciate the discussion!
