### ISSUE TITLE
Tween Behavior pause/resume bug

### ISSUE THREAD

**Issue by Bigbeto123** [Scirra/Construct-3-bugs#3339] opened 2019-09-16 20:36 UTC
Whenever a Tween is playing and I switch the layout on the middle of its duration (to the Inventory layout, in this case), instead of it being properly resumed afterwards (I explicity paused resumed it through actions after going back to the original layout), it will just stay frozen for the rest of the game.

Download .c3p here: https://drive.google.com/drive/u/0/folders/1QVUkvaara73-0Va3ViqcQZyzN0emKObV

Just delete the section that changes the LightFlashlight's opacity at the Game-1's "Start of Layout" section and you'll see it gets frozen whenever its turn on/off opacity tween is playing and you try to access the inventory at the same time (press E to access the inventory and F to turn on/off the flashlight). 
This way, (changing the opacity and variables forcefully), I've managed to find a workaround for it. But it's pretty tiresome to do it for ALL possible tweens playing at that time (there'll be many, many more)

1.Explained
2.Above
3.Already

Opacity tween gets frozen, along with the variables that should be changed after the event's timer. 

An annoying bug, which I've described lots of times above.

It shouldn't freeze, nor should the variables along with it (in the flashlight's input event). 
Whenever you open the drop menu (press X) it doesn't get frozen, why does it only get frozen whenever I open the inventory?

**Affected browsers/platforms:** 
Windows, Chrome

**First affected release:** 

r164.3

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.132
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
C3 release: r166 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 104 gb
Storage usage (approx): 1.5 gb (1.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-09-17 11:46
@Bigbeto123 - please note the attached project is far more complex than we'd normally accept for a bug report, using well over 100 events. Please see the bug report guidelines. It's extremely common that people file bugs for mistakes in their events, and providing a minimal project avoids this. Further, note that changing layout destroys all non-global objects and recreates the new ones, so this may in fact be the intended result. I'll leave this for @DiegoScirra to review but if he cannot immediately spot anything wrong I suspect this will be closed without further investigation.

**Comment by Bigbeto123** [comment] 2019-09-18 01:08
Honestly, I have no time for recreating this fairly specific bug all over again... It's made me lose way more than on it (a supposedly simple task to achieve) than I'd like to (also I'm currently in a jam).
Alright. 
note: Yeah, I know about non-global objects. Tho the flashlight sprite (the object in question) IS a global object.

**Comment by DiegoScirra** [comment] 2019-09-18 14:22
This is working as expected.

A regular instance can not use the **Pause/Resume** logic when the layout changes, because in that case everything is destroyed in the transition, including tweens. So when you go back to the original layout there is nothing to resume. If you want to do something like this, I think it would be better to just overlay the menu on top of the current layout, so you never really leave it.

If you set the instance to be global in the **Properties Bar**, then the **Pause/Resume** logic will work because the instance is never destroyed between layouts, and neither its tweens. This can have some unexpected behavior  because a global instance is visible in all layouts, not just the one you are interested in.

Asides from that it took me a while to realize that what was locking up everything in your project is the **canControl** boolean, which sometimes is set individually and and sometimes from a pause function. If you make sure that is set properly when entering the main layout the controls work just fine.

**Comment by AshleyScirra** [comment] 2019-09-18 15:34
Sounds like a mistake in the project so closing. In future please try to provide minimal projects as per the bug report guidelines to avoid this.

**Closed by AshleyScirra** 2019-09-18 15:34 UTC
Labels: ignored guidelines, not a bug

**Comment by Bigbeto123** [comment] 2019-09-19 00:35
Oh, my bad. I've made a big confusion about it being a global obj. It actually is in my current build, but I uploaded an old one... The thing is, it IS a persistent object tho (even in the old build). So shouldn't the tween be kept intact (instead of freezing)? Or am I wrong.
Yes, on the current build it is working as you said it would (it's set as a global object in fact).
