### ISSUE TITLE
Crash when adding an object to a family with behaviors

### ISSUE THREAD

**Issue by StarCoffey** [Scirra/Construct-3-bugs#5553] opened 2022-03-23 15:05 UTC
## Problem description

When adding a new object to a family with behaviors, it will crash the program.

## Attach a .c3p
[Crash Report.zip](https://github.com/Scirra/Construct-3-bugs/files/8334008/Crash.Report.zip) ->Before saving add the second obj to the family
[Crash Report2.zip](https://github.com/Scirra/Construct-3-bugs/files/8334109/Crash.Report2.zip)->Saved when crash screen pops up
https://www.youtube.com/watch?v=xufKKhkfj3M

## Steps to reproduce

1.Create a family with an object in it
2.Add a behavior to the family
3.Add a second object to the family
4. Deselect all then reselect the second object

## Observed result

Program Crashes

## Expected result

I expected to view the new object in the family.

## More details
I used the latest beta release, r287, on the downloaded version of Microsoft Edge
Also when saving the project when the crash screen appears and then reopening up the project, the issue seems to resolve itself.

**Affected browsers/platforms:**
As far as I'm aware, Microsoft Edge

**First affected release:** This doesn't happen on the latest stable release, r285.3, while this issue happens on the latest beta release, r287. However I can't say when this started with the previous beta releases.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r287/main.js, line 945, col 65
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'tU')
Stack: TypeError: Cannot read properties of undefined (reading 'tU') at Function.Fea (https://editor.construct.net/r287/projectResources.js:833:282) at Function.Fea (https://editor.construct.net/r287/projectResources.js:825:471) at d.AZ (https://editor.construct.net/r287/projectResources.js:732:516) at d.Efb (https://editor.construct.net/r287/projectResources.js:733:365) at d.Oa (https://editor.construct.net/r287/projectResources.js:565:264) at https://editor.construct.net/r287/components/bars/propertiesBar/propertiesBar.js:136:304 at PW (https://editor.construct.net/r287/components/bars/propertiesBar/propertiesBar.js:46:162) at d.CCG.aa.$K (https://editor.construct.net/r287/components/bars/propertiesBar/propertiesBar.js:136:269) at https://editor.construct.net/r287/components/bars/propertiesBar/propertiesBar.js:24:372 at ih (https://editor.construct.net/r287/main.js:370:150)
Construct 3 version: r287
URL: https://editor.construct.net/r287/
Date: Wed Mar 23 2022 10:59:23 GMT-0400 (Eastern Daylight Time)
Uptime: 21.4 s

Platform information
Browser: Edge
Browser version: 99.0.1150.46
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.46
C3 release: r287 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6109)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment] 2022-03-24 12:37
Duplicate of #5544. Will be fixed in the next beta release.

**Closed by DiegoScirra** 2022-03-24 12:37 UTC
Labels: duplicate
