### ISSUE TITLE
Advanced Random plugin broken by minified export

### ISSUE THREAD

**Issue by Bigbeto123** [Scirra/Construct-3-bugs#3253] opened 2019-08-23 12:45 UTC
Whenever I export my project with "Minify Script" check on, it will get stuck on the "loading" phase forever.

## Attach a .c3p
[Mobile.zip](https://github.com/Scirra/Construct-3-bugs/files/3534411/Mobile.zip)

(just change the ".zip" into ".c3p", since the site wouldn't let me update a c3p file)

## Steps to reproduce

1.Export it to desktop
2.Check the Minify Script box
3.Try to run it

## Observed result

I should be able to run it normally just like it happens in the preview mode

It gets stuck on loading forever.

**Affected browsers/platforms:** 
Windows, Chrome

**First affected release:**  r157

## System details Windows 10 pro

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 7.4 gb
Storage usage (approx): 504 mb (6.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-08-23 14:38
It exported fine for me in r157 with 'Minify script' enabled. I also exported successfully with minify script set to 'Advanced' in the latest release r162.2.

When minifying the script on export, the progress bar caption says "Minifying script...", so if you see something else (e.g. it sounds like in your report it's saying something like "Loading...") then that is actually a different phase of the export process and is probably unrelated to minifying script.

When it gets stuck can you press F12 and see if there are any error messages in the browser console? Alternatively try clearing your browser cache and try again.

**Comment by Bigbeto123** [comment] 2019-08-23 15:05
The problem is not the exporting phase. Just try to open it from the nw.exe afterwards. The game will be stuck on an eternal loading.

Also tried in the latest beta and the exactly same thing happened.

The exportation completes just fine. The problem lies in the executable itself.

**Comment by AshleyScirra** [comment] 2019-08-23 15:16
Ah, I see, I didn't get that from your original report (it appears you didn't mention NW.js at all).

It looks like this is caused by the Advanced Random plugin so assigning to @shortercode. The plugin does not appear to be written minify-safe; the loading error occurs running `mod.instance.exports` and `instance` is (apparently incorrectly) minified. There seems to a be a mix of both minify-proof and minified references to the WebAssembly module; it probably needs a full review to ensure it's minify-proof.

**Comment by shortercode** [comment] 2019-08-23 15:20
"instance" and "exports" should be added to the global list I think, as they are inbuilt.

I'm reviewing the rest at the moment, got some fixes to commit.

**Comment by Bigbeto123** [comment] 2019-08-23 15:21
Well, I did say "run it". But forgot to include the nw.exe part.

Alright, thank you.

**Comment by AshleyScirra** [comment] 2019-08-23 15:55
@Bigbeto123 - just so you know it's helpful to always be as clear as possible in bug reports, since miscommunication is the #1 reason we end up being unable to resolve issues! The particular export option you chose is usually important information, and phrases like "run it" are often ambiguous (since in this case I interpreted that as meaning "run the export process", i.e. click the "export" button). So it's a good idea to make sure the steps include basically everything you click/type/choose at every point along the way.

**Comment by Bigbeto123** [comment] 2019-08-23 16:02
No problem

**Comment by shortercode** [comment] 2019-08-27 14:41
Okay this should be resolved in the next release, merged into stable candidate as well.

**Closed by shortercode** 2019-08-27 14:41 UTC
