### ISSUE TITLE
Preview with "Popup Window": window gets progressively smaller each time you preview

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#947] opened 2017-10-18 07:36 UTC
## Problem description

Each time your preview your game, the window gets progressively smaller, you have to resize it every time. This is most likely because of the useless address bar getting in the way, which you've pointed out can't be fixed. So maybe the height of that bar just needs to be accounted for in the window sizing.

## Attach a .c3p

Open Any .c3p
Here's a random one [eventsheet.zip](https://github.com/Scirra/Construct-3-bugs/files/1393745/eventsheet.zip)
Make sure you have these settings:

![image](https://user-images.githubusercontent.com/5744908/31706082-78af25a0-b433-11e7-8113-2a20668b9a51.png)

## Steps to reproduce

1. Press Preview
2. Close Preview
3. Press Preview
4. Press Preview
5. Close Preview
6. Press Preview
7. Close Preview
8. Press Preview

## Observed result

Window gets smaller

## Expected result

Not change size

## Affected browsers

* Chrome: Yes (Desktop app mode)
* Firefox: No
* Edge: ?
* Safari: ?

## Screenshots of each time I preview (15 times) showing the window gradually getting smaller

![image](https://user-images.githubusercontent.com/5744908/31705916-e0eb8664-b432-11e7-8853-bbc3b6a30399.png)

![image](https://user-images.githubusercontent.com/5744908/31705927-e7593140-b432-11e7-8a42-8dc1632cef0d.png)

![image](https://user-images.githubusercontent.com/5744908/31705937-eecf6e76-b432-11e7-95c6-f46013470a10.png)

![image](https://user-images.githubusercontent.com/5744908/31705947-f4d4d2f2-b432-11e7-8f30-c698af87f066.png)

![image](https://user-images.githubusercontent.com/5744908/31705953-fa5bb1be-b432-11e7-9d44-44e4d4e9e053.png)

![image](https://user-images.githubusercontent.com/5744908/31705962-ffca0452-b432-11e7-996f-e720554c1141.png)

![image](https://user-images.githubusercontent.com/5744908/31705967-07d4fbac-b433-11e7-9998-cdbed4159f8d.png)

![image](https://user-images.githubusercontent.com/5744908/31705975-0dc64a98-b433-11e7-952e-4a61da1ab7d0.png)

![image](https://user-images.githubusercontent.com/5744908/31705980-12c5b588-b433-11e7-828b-668ab55880ab.png)

![image](https://user-images.githubusercontent.com/5744908/31705988-18b703c0-b433-11e7-8cb8-23dde2287769.png)

![image](https://user-images.githubusercontent.com/5744908/31706041-4814556e-b433-11e7-9e2b-8b173305a3c0.png)

![image](https://user-images.githubusercontent.com/5744908/31706050-4f46c5d8-b433-11e7-95e2-17d382b374d7.png)

![image](https://user-images.githubusercontent.com/5744908/31706051-55286628-b433-11e7-94e5-55dcaf6e9519.png)

![image](https://user-images.githubusercontent.com/5744908/31706056-5b67bd54-b433-11e7-862c-7e6419cb713c.png)

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 62.0.3202.62
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36
C3 release: r64
Language setting: en-US

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 486 mb (3.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by tunepunk** [comment] 2017-10-18 11:51
Can confirm. This happened for me as well. So I used another option for the preview for now.

**Comment by AshleyScirra** [comment] 2017-10-18 16:01
Does it reproduce in Firefox, Edge or Safari?

**Comment by alastajj** [comment] 2017-10-18 23:38
Doesn't happen on Firefox, can't test on Safari or  Edge (tried updating).

**Comment by AshleyScirra** [comment] 2017-10-19 10:58
Can you include the info from the Platform Information dialog? It includes the device pixel ratio which may affect this.

It's faster to deal with bug reports if you provide all this information up-front.

**Comment by alastajj** [comment] 2017-10-19 11:17
Sorry, here you go.

## System details


<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 62.0.3202.62
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36
C3 release: r64
Language setting: en-US

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 486 mb (3.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by TheBl4ckSh33p** [comment] 2017-10-20 08:03
same on Chrome. I used C3 "on desktop" and in the normal browser window and very often the preview popup is getting smaller and smaller.

**Comment by AshleyScirra** [comment] 2017-10-23 18:15
Can't reproduce here, it opens the same size every time. I put a text object in the layout set to `windowwidth & " x " & windowheight` and every time it launches it displays 853 x 480, so it seems like it's getting the right size every time. I'm not sure what would be making it offset the size at all.

**Comment by alastajj** [comment] 2017-10-24 01:12
Thanks for trying, can you show me what it looks like for you when you preview it Ashley? 

It happens in that c3p, it happens in ally my projects. 

Here's a screenshot of it with that c3p: 
![image](https://user-images.githubusercontent.com/5744908/31920409-6e24ddfc-b8b4-11e7-9076-72f732020f35.png)

and after a few previews:
![image](https://user-images.githubusercontent.com/5744908/31920414-79d719f8-b8b4-11e7-8cd6-c3de575896a0.png)

**Comment by alastajj** [comment] 2017-10-24 04:42
@tunepunk @TheBl4ckSh33p if you run the .c3p in this issue, while having the popup window setting, do you get results like I've posted? Might be interesting to see a screenshot (alt + printscreen) and paste it here, if it please you 😊

**Comment by tunepunk** [comment] 2017-10-24 09:07
Maybe this has something to do with running C3 in app mode? Does it happen when you run C3 directly in browser? It happened for me in app mode, but havn't tested running in the browser directly.

**Comment by AshleyScirra** [comment] 2017-10-24 13:12
I tested in the browser and it didn't reproduce, but it does reproduce if you do 'add to desktop'. Almost certain this is a browser bug, will file a Chrome issue.

**Comment by AshleyScirra** [comment] 2017-10-24 13:28
Yep, it's a Chrome bug. Filed here: https://bugs.chromium.org/p/chromium/issues/detail?id=777854

Closing as will follow up the report there.

**Closed by AshleyScirra** 2017-10-24 13:28 UTC
Labels: browser, external
