### ISSUE TITLE
Exported .APK not loading on mobile

### ISSUE THREAD

**Issue by UbruPro123** [Scirra/Construct-3-bugs#4396] opened 2020-12-03 20:59 UTC
## Problem description
When I tried to load installed .APK game on my phone it freezes at loading.

## Attach a .c3p
[project.zip](https://github.com/Scirra/Construct-3-bugs/files/5638882/project.zip)

I packed into it also exported .APK file so you do not need to do that step 1. in Steps to reproduce

## Steps to reproduce
1. It is only needed to be exported: Export -> Android (Cordova) -> check both checkbox (deduplicate/recompress) -> select build Debug APK and finish.
2. When I install it on ma android phone (Xiaomi redmi note 4, with android 7.0.2) there is only C3 logo and endless loading, built is not working.

## Observed result
Via live preview in C3 (in form of HTML 5 game) it works okey on my mobile. I quess problem will be with canvas.

## Expected result
I expected to load with no problem or at least know issue, where is the problem?

## More details
Testing in latest C3 beta version r227.2.

## System details
Xiaomi Redmi note 4, android 7.0.2.
but same situation is also on other devices (testes two more)

**Comment by AshleyScirra** [comment] 2020-12-04 11:54
I built a debug APK from the project and it seems to run just fine on my Pixel 3 running Android 11.

Can you try [USB debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging) on a device where it's not working and see if any error messages are coming up in the console?

**Comment by UbruPro123** [comment] 2020-12-05 21:29
Hello I finally make it works and here you can look at my debug result

![debug](https://user-images.githubusercontent.com/44697344/101265770-5994db00-3749-11eb-82a6-9d1700af0b7a.png)

**Comment by AshleyScirra** [comment] 2020-12-07 14:31
I have no idea why that message would appear. It's going to be difficult to do anything about this unless a reliable way to reproduce the problem can be found.

**Comment by AshleyScirra** [comment] 2020-12-07 15:51
Based on some guesswork from looking at that error, I added a speculative fix for the next release. I don't know if it will help though since I can't reproduce the problem, so you'll have to re-test when the next release is out.

**Comment by AshleyScirra** [comment] 2020-12-07 17:59
BTW out of curiousity, @UbruPro123 could you find the user agent of the affected device and share it here? You can get it by entering `navigator.userAgent` in to the console and pressing enter. I wonder if the device has an out-of-date WebView and whether that may be related to the problem - this would help identify if that's part of the problem.

**Comment by AshleyScirra** [comment] 2020-12-08 12:55
r228 is now out, can you check again with that?

**Comment by UbruPro123** [comment] 2020-12-08 19:35
Hi again, I tried it at new build r228 today and situation remains same. I entered that command so you can check it on attached image:
![new test](https://user-images.githubusercontent.com/44697344/101532221-84bf3a80-3994-11eb-8860-87d68de32fcc.png)

I think as you wrote it would probably be problem with something outdated at my mobile (Redmi note 4 is old), at another newer mobile it works ok.

**Comment by UbruPro123** [comment] 2020-12-08 19:56
I observed this problem as global for my mobile, I mean few C3 builds back it was okey and now every exported project (.APK) fails with same error, so in last few builds that there must have been some change that caused it. 
I am working at one bigger project and approx 2-3 weeks back export worked ok (I have version from 17.11. tested now and works), build new .APK at C3 version r228 and it ends with an error (my project is without change).

So maybe there can be global problem for older mobiles.

**Comment by AshleyScirra** [comment] 2020-12-09 10:44
Thanks for the info. I'm guessing this is something to do with JavaScript Modules which was introduced in r226. I don't know why this would be happening though, since it seems to work just fine on my device and both appear to have up-to-date WebViews. I think this will be a tough problem to solve.

**Comment by UbruPro123** [comment] 2020-12-09 15:37
Yes I switched Scripts type from Module to Classic and it runs okey.

**Comment by AshleyScirra** [comment] 2020-12-09 16:15
I got hold of some extra Android devices for testing, and I could reproduce it on some older devices. It's mysterious why it would be inconsistent like that. I think it's some problem with either Cordova or the Android WebView when using JavaScript Modules. I managed to adjust the workaround to get it working again though, so hopefully it'll be fixed in the next release, but I'll wait until it's out to confirm.

For reference I filed two further issues with Cordova and Google in case they can fix the underlying problem, which would remove the need for our workaround and help avoid any subsequent problems later down the line:
cordova-android: https://github.com/apache/cordova-android/issues/1142
Google: https://bugs.chromium.org/p/chromium/issues/detail?id=1157088

**Comment by ConstructBugsReport** [comment] 2020-12-14 19:14
Hello! Thank you for bringing this up! Indeed, this problem has already been raised by me more than once, but not here.

I have a couple of games on Google Play and so when problems arise, my users tell me about it.
Now games are gradually decreasing in rating due to errors, and all this is due to the fact that there are problems with the Construct 3 engine.

I will not torment you.
Here are the problems:
Construct 3 version
--------------
r 225 The errors disappeared after the update, the players began to write that the game started working.
r 227, 227.2, 228 errors appeared |
Device: Samsung Galaxy J4 Core
Device: Samsung Galaxy J5 Prime
Device: Neffos C9A
Device: Acer Iconia Tab 10
Device: Huawei HUAWEI P20 Lite
Device: Samsung Galaxy Tab A 10.1
Device: Xiaomi Redmi 5 Plus
Device: Huawei Honor 7A
Device: Samsung Galaxy J2 Core
Device: Jinga SmartPRO
Device: Lenovo Tab E7
Device: SM-N975F

**Comment by AshleyScirra** [comment] 2020-12-15 11:52
r229 is now out, can you check again with that?

**Comment by UbruPro123** [comment] 2020-12-15 22:06
Hi thanks for working on it. Now in version r229 it works on my Xiaomi redmi note 4 (android 7).

**Comment by AshleyScirra** [comment] 2020-12-16 12:04
OK, thanks for confirming, I think this is now resolved.

**Closed by AshleyScirra** 2020-12-16 12:04 UTC
Labels: Android, difficult, external
