### ISSUE TITLE
in Mobile, On double tap to insert object Keyboard opens & Covers whole screen

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#138] opened 2017-05-01 05:32 UTC
## Problem description
Keyboard Covers whole screen when inserting object or behaviors 
when we pick color to choose colour bar not showing
*Enter a concise description of your problem here*
when we double tap on layout to insert new object
and popup "create new object type" comes with keyboard popup by default and covers whole screen
So Please hide keyboard by default and if we have to search anything we can do it manually when we need
and do the same for other popup windows like behaviour 
## Attach a .c3p
![keyboard popup](https://cloud.githubusercontent.com/assets/17684135/25572773/448775aa-2e5c-11e7-82b0-8a7e109d7e20.png)
Keyboard while choosing behavior 
![keyboard popup 2](https://cloud.githubusercontent.com/assets/17684135/25572774/4491fd2c-2e5c-11e7-8a62-9623ce3f4ca7.png)
Keyboard while inserting Object
![keyboard popup 3](https://cloud.githubusercontent.com/assets/17684135/25572775/4498bc34-2e5c-11e7-92af-fa8c67452001.png)
Keyboard in landscape mode
![colour option](https://cloud.githubusercontent.com/assets/17684135/25572777/4f7c78c0-2e5c-11e7-918a-9f324e22b3c0.png)
Colors bar not showing here

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce
1. Just double tap on layout to insert plugins (i.e. sprite)
2. Add behavior it sprite

## Observed result
keyboard opens by default and covering screen
*What do you see happen?*
screen fully covered by keyboard 
## Expected result
keyboard should not come here and icon should small so at-least 3 icons in a row we can see
*What did you expect to happen instead?*
only plugins should be their without keyboard, keyboard should appear when we do search and icons should little bit smaller so we can see 3 icons on a row instead of 2
![expecting without keyboard](https://cloud.githubusercontent.com/assets/17684135/25572791/6f6e8308-2e5c-11e7-8181-d5899c011e77.png)
open this without keyboard and icon should smaller so we can see 3 icons in a row
![expecting without keyboard 2](https://cloud.githubusercontent.com/assets/17684135/25572792/6f724588-2e5c-11e7-92c2-eca8f502cb89.png)

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2017-05-01 10:39
The problem is the Android keyboard resizes the window size, but Google are likely going to change it so it doesn't, which is how it works on iOS. See: https://www.chromestatus.com/features/5656077370654720
You can test it now by going to chrome://flags in Chrome on Android and enabling "Enable OSK overscroll".

This change will likely fix it so we'll wait for that to land first.

**Comment by AshleyScirra** [comment] 2017-06-20 12:54
The latest C3 releases don't show the keyboard by default in those dialogs on mobile, so this shouldn't be so annoying. Other than that, all we can do is wait for the Chrome issue to be fixed: https://bugs.chromium.org/p/chromium/issues/detail?id=404315

Since it's entirely in Google's hands to update Chrome for Android, closing this issue. Follow the linked Chrome bug for more updates.

**Closed by AshleyScirra** 2017-06-20 12:54 UTC
Labels: browser, external, mobile
