### ISSUE TITLE
"Select all in project" crashes project

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#6321] opened 2022-12-10 21:32 UTC
## Problem description

In a project file I purchased from the Asset Store, selecting an object and using "Select all in project" crashes the project. 

I've removed most everything from the project file to show the error. Removing any more assets can sometimes fix the problem, but I can't figure out why.

## Attach a .c3p

https://drive.google.com/file/d/11ND4NgvYd4BKydlUbORYsqgG4nlMq99R/view?usp=share_link

## Steps to reproduce

1. Open the attached project.
2. Right-click the object "font30b"
3. Choose "Select all in project"

## Observed result

Construct crashes (report pasted below)

## Expected result

Construct doesn't crash; all instances are selected.

## More details

**Affected browsers/platforms:** Chrome Version 107.0.5304.121 (Official Build) (x86_64), MacOS 12.6

**First affected release:** r321

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r321/components/bars/propertiesBar/propertiesBar.js, line 19, col 101
Message: Uncaught TypeError: Cannot read properties of null (reading 'G')
Stack: TypeError: Cannot read properties of null (reading 'G') at feb (https://editor.construct.net/r321/components/bars/propertiesBar/propertiesBar.js:19:101) at CCG.aa.JS (https://editor.construct.net/r321/components/bars/propertiesBar/propertiesBar.js:142:114) at Icb (https://editor.construct.net/r321/components/bars/projectBar/projectBar.js:22:272) at https://editor.construct.net/r321/components/bars/projectBar/projectBar.js:22:123 at https://editor.construct.net/r321/main.js:1871:100
Construct version: r321
URL: https://editor.construct.net/r321/
Date: Sat Dec 10 2022 16:31:24 GMT-0500 (Eastern Standard Time)
Uptime: 18.1 s

Platform information
Product: Construct 3 r321 (beta)
Browser: Chrome 107.0.5304.121
Browser engine: Chromium
Context: browser
Operating system: macOS 12.6.0
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel Inc.)
Renderer: ANGLE (Intel Inc., Intel(R) Iris(TM) Plus Graphics 655, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw
</details>

**Comment by AshleyScirra** [comment] 2022-12-12 11:44
@DiegoScirra - it looks like some of the layer property code assumes there is always an active layer. If no layout is open and 'Select all in project' is used then there is no active layer.

**Comment by DiegoScirra** [comment] 2022-12-12 15:08
Will be fixed in the next beta. Was a regression introduced in r306.

**Closed by DiegoScirra** 2022-12-12 15:08 UTC
