### ISSUE TITLE
C3 Mobile Editor in Android issue

### ISSUE THREAD

**Issue by RJP3** [Scirra/Construct-3-bugs#696] opened 2017-08-09 19:04 UTC
## Problem description

When I start to use the menu gets hidden and I can't seem to get it back
-I am using C3 on my Android phone (Galaxy S8+, OnePlus 5) 
-The Chrome version I have is -- 59.0.3071.125

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.  Launch C2 on Android Phone
2. Open a sample project
3. Run sample project
4. Close running project
5. Go back to c3 mobile editor - Menu will not be visible

## Observed result

c3 mobile editor Menu will not be visible

## Expected result

Have access to menu like when c3 starts up

## Affected browsers

* Chrome: yes on android

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>
![screenshot_20170808-185930](https://user-images.githubusercontent.com/30876470/29139062-40201bae-7d0b-11e7-8897-9a3fa4d17fe2.png)
![capture](https://user-images.githubusercontent.com/30876470/29139071-43f5899e-7d0b-11e7-8f4f-313ba46572c3.PNG)

**Comment by RJP3** [comment] 2017-08-09 19:12
![screenshot_20170808-185930](https://user-images.githubusercontent.com/30876470/29139473-b73378d4-7d0c-11e7-8ac8-f016854e4d55.png)
![capture](https://user-images.githubusercontent.com/30876470/29139490-c8d2781a-7d0c-11e7-92d7-93e9dcdfad11.PNG)

**Comment by AshleyScirra** [comment] 2017-08-10 16:26
I can't reproduce this on Chrome for Android 59, but it does reproduce on Chrome Dev (currently v61). It looks like they're adjusting how the viewport works... could be tricky.

Workaround: approve the fullscreen prompt, or add to the home screen, and the browser address bar doesn't appear.

**Comment by AshleyScirra** [comment] 2017-08-10 16:28
Actually I can reproduce in v59. Huh, seems intermittent.

**Comment by RJP3** [comment] 2017-08-10 22:28
Ashley,

Thank you for the workaround suggestions...

I tried both and this is what happens...

When I open a project (like "Kiwi Story") everything is still Ok

When I run it a new browser page opens with the project running and puts a browser address bar...that is Ok...then I close it...and go back to the C3 editor screen...still all ok...

But as soon as I touch an image or anywhere in the C3 editor it shows the browser address bar and then the menu is hidden...

Only way to get it back is to refresh the browser...

Thanks - Russell

**Comment by AshleyScirra** [comment] 2017-08-29 17:06
OK, should be fixed in r52.

**Closed by AshleyScirra** 2017-08-29 17:06 UTC
Labels: mobile
