### ISSUE TITLE
Сonstruct 3 does not open projects

### ISSUE THREAD

**Issue by ibiz3091** [Scirra/Construct-3-bugs#3005] opened 2019-06-02 21:55 UTC
## Problem description
Error report information
Type: unhandled rejection
Reason: {"response":"{\n "error": {\n "errors": [\n {\n "domain": "global",\n "reason": "internalError",\n "message": "Internal Error"\n }\n ],\n "code": 500,\n "message": "Internal Error"\n }\n}\n","code":500,"status":
Construct 3 version: r151
URL: https://editor.construct.net/r151/
Date: Mon Jun 03 2019 00:43:37 GMT+0300 (Москва, стандартное время)
Uptime: 41.7 s

Platform information
Browser: Chrome
Browser version: 77.0.3812.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3812.0 Safari/537.36
C3 release: r151 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment] 2019-06-03 09:59
Google services had an outage yesterday, so any attempts to access Google Drive was failing.

https://www.theverge.com/2019/6/2/18649635/youtube-snapchat-down-outage

Closing as a duplicate of #3004 

When filling in bug reports please complete all the sections, I would like to investigate the crash but there isn't enough information here.

**Closed by shortercode** 2019-06-03 09:59 UTC
Labels: duplicate, ignored guidelines
