### ISSUE TITLE
Promise localvars bug :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6340] opened 2022-12-16 17:10 UTC
## Problem description

After await I don't get the correct function argument value.

It works well if I do it via events:

![aaa](https://user-images.githubusercontent.com/91274932/208151679-a42e6220-c3a4-45d3-b4dd-d3f370e77139.png)

## Attach a .c3p

[promise_localvars_bug_r322b.zip](https://github.com/WilsonPercival/WilsonPercival/files/10247629/promise_localvars_bug_r322b.zip)

## Steps to reproduce

1. Open and run the project.
2. Open the console.

## Observed result

![observed](https://user-images.githubusercontent.com/91274932/208151037-0cb30e5d-d101-4529-a1a4-55f6ca1e3d2f.png)

## Expected result

![expected](https://user-images.githubusercontent.com/91274932/208151052-d800506f-c5f4-4abb-b1e8-7853c00c5f3b.png)

## More details

**Affected browsers/platforms:** Mozilla

**First affected release:** broke in r322b

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r322 (beta)
Browser: Firefox 108.0
Browser engine: Gecko
Context: browser
Operating system: Windows 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0
Language setting: en-US
Local storage

Storage quota (approx): 9.8 gb
Storage usage (approx): 34 mb (0.3%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    UI effects are disabled in settings.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2022-12-19 11:34
Duplicate of #3297 - it's currently by design (when the function returns its function parameters are cleared; Construct doesn't currently implement anything like JavaScript's closures).

**Closed by AshleyScirra** 2022-12-19 11:34 UTC
Labels: duplicate

**Comment by WilsonPercival** [comment] 2022-12-23 16:30
> Duplicate of #3297 - it's currently by design (when the function returns its function parameters are cleared; Construct doesn't currently implement anything like JavaScript's closures).

@AshleyScirra Wait, but it's working now... Has it been fixed?

![asd](https://user-images.githubusercontent.com/91274932/209368105-d57f715d-2116-4a62-987f-f3fdefe11783.png)
