### ISSUE TITLE
C3 gets up to 1.9GB ram usage after importing huge sprite of 2.6MB and stabilizes at 1.1GB

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#484] opened 2017-06-10 23:23 UTC
## Problem description

After importing a 10k by 5k pixels, 2.6MB jpeg the usage of the editor grows extremely much for no apparent reason.

![alotofram](https://user-images.githubusercontent.com/7268697/27007003-e70483c6-4e4c-11e7-9479-624af194f99e.gif)

## Attach a .c3p

Empty project, import this file as a sprite

[garden v3.zip](https://github.com/Scirra/Construct-3-bugs/files/1066166/garden.v3.zip)

## Steps to reproduce

1. create an empty project
2. right click on the layout
3. add a sprite object
4. import the attached unarchived jpg file

## Observed result

The ram goes up to 1.9GB and stabilizes later at 1.1GB, all of this for a pathetic 2.6MB sprite

## Expected result

I don't expect it to use more than the system requirement for Windows 10 on 64 bit.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r36

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 133 mb (1.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by JeFawk** [comment] 2017-06-10 23:26
By the way, when I checked the project statistic, what is the reason for a 2.6MB jpec to use up so much memory?

![image](https://user-images.githubusercontent.com/7268697/27007036-5d7af558-4e4d-11e7-9b7a-20f890b221f7.png)

**Comment by JeFawk** [comment] 2017-06-10 23:27
Building the spritesheet got to use up to 2.2GB via the tools on project.

**Comment by TheRealDannyyy** [comment] 2017-06-10 23:42
I can reproduce this bug, seems to be a memory leak within the image editor.
(Note: I had to open/import twice, before I could notice significant changes in memory use.)

**Comment by JeFawk** [comment] 2017-06-11 00:54
I updated the repro steps to be more accurate. Tell me if this works @TheRealDannyyy , thanks.

**Comment by JeFawk** [comment] 2017-06-11 00:55
As a note, when I used incognito mode, in the image editor C3 was at 1GB ram. When I closed it and returned to the layout, it peaked up at 1.5GB then stabilized at 1.3GB.

**Comment by shortercode** [comment] 2017-06-12 10:35
Should point out that once decoded that sprite would take up 150MB ( 50MP @ 3 bytes per pixel ). I'm seeing an idle increase of about 350MB when importing outside of the Animations editor ( peaks at around 1000 MB during processing )

**Comment by AshleyScirra** [comment] 2017-06-12 12:05
Actually at 10000x5000 you're probably using around 200mb memory for 32-bit ARGB format. In fact if you are unlucky and the GPU bumps it up to a power-of-two, even just on the X axis, it will go up to ~320mb, and if it bumps it on both axes, 512mb. So this is a colossal image, definitely not a "pathetic 2.6mb". You should [definitely read this](https://www.scirra.com/blog/112/remember-not-to-waste-your-memory).

I also get much reduced memory usage if I just drag-drop it in to the layout view, which bypasses the animations editor: it peaks around 1 GB and settles to around 511mb after a short while (when GC will have cleaned up). Only when using the animations editor does it peak to 2.5GB. It's also a lot slower closing the animations editor than when using drag-drop. Assigning to Diego to see if there's anything simple to do to speed up and reduce memory overhead for large images in the Animations Editor.

**Comment by JeFawk** [comment] 2017-06-12 12:40
It is a big file, but it should use up about 10.000 x 5.000 x 4 / 1024 / 1024 MB = 190.7 MB or so, definitely not 2.5GB, nor 1GB either.

**Comment by DiegoScirra** [comment] 2017-06-14 10:27
For the record, opening this image in GIMP takes the RAM usage in my computer to 500 MB.

I am sure I can cut down on some of the memory overhead on the Animations Editor, but it won't go below 500 MB.

**Comment by JeFawk** [comment] 2017-06-14 11:24
paint.net

![image](https://user-images.githubusercontent.com/7268697/27130017-253be46e-510d-11e7-9597-6fbc299627e1.png)

**Comment by DiegoScirra** [comment] 2017-06-20 16:15
I have done some work on this. 

As of r40 the memory footprint of the editor should be lower. Not dramatically though, but it's an improvement.

Leaving this one open because I still have a few things I want to try to keep memory as low as possible.

**Comment by triptych** [comment] 2017-06-20 17:29
I have a feeling this memory issue is what is partially causing crashes on preview as well.

**Comment by shortercode** [comment] 2018-01-19 13:17
I thought we could do with some up to date number here, to reflect any chrome changes and various tweaks Diego has made in the last 6 months. Idle was taken with C3 running a single project, containing a blank sprite open in the image editor. Values were taken from the chrome task manager.

The 4 values are: total, the tab, the GPU process ( shared ), the browser. 
Before: 309 MB = 120 + 108 + 81
Peak: 2001 MB = 1120 + 800 + 81
After: 650 MB = 500 + 80 + 70

**Closed** 2018-06-25 14:10 UTC
