### ISSUE TITLE
[R23] [windows 10] Impossible to add a new image point to a sprite

### ISSUE THREAD

**Issue by el3um4s** [Scirra/Construct-3-bugs#137] opened 2017-04-30 15:18 UTC
## Problem description

It's impossible to add a new image point to sprite.

## Attach a .c3p

[prova.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/966802/prova.c3p.zip)

## Steps to reproduce

1. Create a sprite.
2. Try to add a new image point.

## Observed result

It's impossible to add a new image point.
See the video
https://youtu.be/ZYpsagQ3eJk
[![Alt text](https://img.youtube.com/vi/ZYpsagQ3eJk/0.jpg)](https://www.youtube.com/watch?v=ZYpsagQ3eJk)

## Expected result

Add a new image point.

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.81
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 155 mb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by 3dParadox** [comment] 2017-04-30 16:13
I see the same thing.

**Comment by DiegoScirra** [comment] 2017-05-02 09:56
Duplicate of #139. Fixed in r24.

**Closed by DiegoScirra** 2017-05-02 09:56 UTC
Labels: duplicate
