### ISSUE TITLE
Multiple light sources do not work

### ISSUE THREAD

**Issue by Everade** [Scirra/Construct-3-bugs#86] opened 2017-04-15 12:09 UTC
## Problem description

The intermediate Example "Shadows: blending multiple lights" does only display 1 light properly.
The other 2 on the right side do not cast any light nor shadows.

Since the free edition comes with extreme boundaries i cannot and will not investage this any further myself.
There's absolutely no freedom in this free version.

It's like you give a kid a lolipop with a gum inside and let them only lick 3 times and then take it away.
Sounds like a bad joke? It is

## Steps to reproduce

1. Start the example Shadows: blending multiple lights as preview
2. Use your eyes

## Observed result

*What do you see happen?*
2 lights do not work (the colored ones)

## Expected result

I expect to see 3 different light sources with proper shadow casting.

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2017-04-17 14:19
Turns out this is a duplicate of bug #30 - the project imports with the wrong tint parameters for two of the lights, causing them to disappear. I've updated the project so it's not affected for r19, but the underlying issue still needs to be fixed, which will be handled in bug #30.

**Closed by AshleyScirra** 2017-04-17 14:19 UTC
Labels: duplicate
