### ISSUE TITLE
Gamepad index detection

### ISSUE THREAD

**Issue by theprocrastinator-dev** [Scirra/Construct-3-bugs#3987] opened 2020-06-25 12:21 UTC
Not quite sure if this is exactly a construct 3's bug or a windows 10's, but anyways: Whenever I connect my official Xbox One Gamepad via bluetooth to my Acer 5 (latest update of Windows10) Nitro laptop, it either goes to the 0 index or to the 1; kinda randomly; and since in my singleplayer, the input checks (controls and such) are ALL attributed to the 0 index gamepad, sometimes the gamepad controls will simply not work in my game because of this little issue. Either way, I think it would be a good idea to have a expression to detect the index of the currently connected gamepad (if there are more than one, return the latest or something). Already tried setting the index to Gamepad.GamepadCount but had no success (can only detect it via chaning it to 0 or 1)

Worth noting: The "on gamepad connected" trigger and "on gamepad disconnected" trigger will ALWAYS work, however, I can't seem to get the exact index from these triggers via an expression (like you can from, for example, the local storage object)

## Attach a .c3p
[bugrep.zip](https://github.com/Scirra/Construct-3-bugs/files/4831113/bugrep.zip)

## Steps to reproduce

1.create a project with the keyboard and gamepad objects
2.create a trigger to detect any key pressed on both of them
3.the gamepad won't be detected some of the time (restart the gamepad to "re-randomize" the index of it)

gamepad won't be detected via the input sometimes

it should always be, for obvious reasons.

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
r204.2 and last stable as well
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.132
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
C3 release: r204.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 115 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2020-07-02 17:23
I can't reproduce what you describe with a USB gamepad - connecting and disconnecting the USB cable always puts it at index 0. I guess with wireless it could get confused and think there's two devices, hence assigning it to index 1 instead of 0. Construct doesn't control this value, it relies on what the browser tells it. It's true there's no expression to tell you which gamepad index was connected/disconnected, and if in some cases a gamepad can be connected at a different index it's necessary. So I've added a `GamepadIndex` expression for the next beta which can be used in a connected/disconnected trigger to identify the gamepad index. Then for example if you only want to use the first connected gamepad, you can just store the index of the first connected gamepad in a global variable and just refer to that index everywhere.

**Closed by AshleyScirra** 2020-07-02 17:23 UTC

**Comment by theprocrastinator-dev** [comment] 2020-07-03 12:26
Thank you very much! That does it for me
I think its more of a windows 10 connection bug (since the bug only happens w the Xbox controller bluetooth, doesn't happens on cable). But in any cases, since (I believe) most engines have a way to detect the gamepad index (even in Bluetooth, it has no problems to be detected on other games, like from unreal engine etc), that now puts this one on pair with them in that term, which is great
