### ISSUE TITLE
Can't save project

### ISSUE THREAD

**Issue by hansonbrody** [Scirra/Construct-3-bugs#748] opened 2017-08-25 01:29 UTC
## Problem description

Worked on my .c3p file earlier today, saved my changes and went home. Logged in tonight to work on it some more and got the 'update to v50 from v49' message, so I updated. Now I can't save my project. Hitting the save button gives me a 'Array expected' error and the file doesn't save. When I try to save locally i get an error as well.

## Attach a .c3p

Tried to attached but github says they dont' support this file type.

## Steps to reproduce

1. Open my file
2. Make any change
3. Hit save 

## Observed result

Get error, doesn't save

## Expected result

Save my project

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

AND THE COPY INFORMATION BUTTON DOESN'T WORK TO COPY THE ERROR REPORT AND I CAN'T MANUALLY SELECT THE TEXT TO ADD IT HERE...AAAAHHHHHHHHHHHH

**Comment by virgulaleal** [comment] 2017-08-25 06:09
Having the very same issue, including being unable to copy the error report.

**Comment by cihanyakar** [comment] 2017-08-25 07:12
Possibly duplicate #743

**Comment by DiegoScirra** [comment] 2017-08-25 10:02
Closing this one as it is a duplicate of #744.

**Closed by DiegoScirra** 2017-08-25 10:02 UTC
Labels: duplicate
