### ISSUE TITLE
R23 - Path Finding error.

### ISSUE THREAD

**Issue by Mataguiris** [Scirra/Construct-3-bugs#134] opened 2017-04-28 22:35 UTC
## Problem description

 r23 - PathFinding error, It does not work, I tried calculating the distance and with sneak, stands still.

## Attach a .c3p

https://www.dropbox.com/s/nz1rxld1rwx0mly/PathError.zip?dl=0

## Steps to reproduce

1.
2.
3.

## Observed result

I can not use patfinding, it does not look for path according to distance, nor with a sprite that acts as a sneak.

## Expected result

That works well XD

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2017-05-02 13:34
Closing as not a bug. It's just a mistake in your events. You try to find a new path every tick, so it keeps cancelling the path it's just worked out.

**Closed by AshleyScirra** 2017-05-02 13:34 UTC
Labels: not a bug
