### ISSUE TITLE
Website unknown character in shortcuts

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#6188] opened 2022-10-14 05:12 UTC
The shortcuts page displays some unknown characters, checking the source didn't help. Happens on Safari, on Chrome, and Firefox on my Mac M1, OS Monterey 12.6:

<img width="537" alt="image" src="https://user-images.githubusercontent.com/7268697/195766899-df945718-91d8-4d86-91bc-f193a185896d.png">

https://www.construct.net/en/make-games/manuals/construct-3/interface/keyboard-shortcuts

Can I please know the character until this gets fixed? :) (for the go to the next/previous tab)

**Comment by AshleyScirra** [comment] 2022-10-14 10:20
Duplicate of https://github.com/Scirra/Construct.net-website-bugs/issues/166

Respectively they are up, down, left, right, left right arrows.

**Closed by AshleyScirra** 2022-10-14 10:20 UTC
Labels: duplicate

**Comment by JeFawk** [comment] 2022-10-15 01:16
> Duplicate of [Scirra/Construct.net-website-bugs#166](https://github.com/Scirra/Construct.net-website-bugs/issues/166)
> 
> Respectively they are up, down, left, right, left right arrows.

Thank you!
