### ISSUE TITLE
Google Drive/OneDrive/local browser saves broken in r205

### ISSUE THREAD

**Issue by captainsteff** [Scirra/Construct-3-bugs#3978] opened 2020-06-23 15:46 UTC
Problem description
Since the new Beta version r205, when trying to open an existing file that's on Google Drive within the "recent" list, I get the following message in the Google login pop-up window: 
Authorisation Error
Error 400: invalid_request
Required parameter is missing: response_type
Attach a .c3p
no need

Steps to reproduce
Try to open a recent file in C3 that was saved on your Google Drive

Expected result
The file should open as before, or at least let me click my Google username and enter my password

More details
Only happens since r205

Affected browsers/platforms:
Google Chrome

First affected release:
r205

<img width="960" alt="Google Drive login error" src="https://user-images.githubusercontent.com/46461714/85425263-f7ec0600-b546-11ea-8216-1fb322a7104d.png">

**Comment by Rhindon** [comment] 2020-06-24 06:39
I can confirm this same result.
Further, when trying to simply access my Google Cloud at all by clicking the Cloud folder at the top of the start page, it gives the same Error 400 result as noted here.

**Comment by AshleyScirra** [comment] 2020-06-24 10:46
It turns out the new Closure Compiler build tool mangled all the cloud save code wrong and broke it. I've adapted the code to work with Closure Compiler so it should be fixed in the next release. I imagine multiple people will run in to this, so leaving open with the fixed tag.

**Comment by AshleyScirra** [comment] 2020-06-24 14:41
Note this includes local browser saves, which are internally implemented as a kind of cloud save service.

I realise this issue might be quite inconvenient, but AFAIK you can still use (experimental) local files in Chrome, and drag/drop .c3p files and save them again with "Download a copy". I suspect we will yet find a few more things broken by Closure Compiler, so I would prefer not to rush out another beta. Sorry for the inconvenience but we'll have another beta release out next week which should fix this, I'll be sure to verify all this in pre-release checks.

**Closed** 2020-06-30 14:39 UTC
