### ISSUE TITLE
Export to Android Studio - Waiting to Build - Time-Out

### ISSUE THREAD

**Issue by luisforte** [Scirra/Construct-3-bugs#1427] opened 2018-03-25 16:51 UTC
## Problem description

Exported project for android studio stuck on Waiting to Build

## Steps to reproduce

Export project to Android Studio

## Observed result

Some times the export process stuck at "Waiting to build - Restored Connection"

## Expected result

Build project

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

**Comment by AshleyScirra** [comment] 2018-03-26 12:51
No project provided, but appears to reproduce with Ghost Shooter.

**Comment by luisforte** [comment] 2018-03-26 14:42
No project related issue... any project stuck at Building Server.... service got-back again

**Comment by jaydonteh** [comment] 2018-04-03 06:32
Just tried to export my apk and got stuck on "waiting to build" then "restored connection". [r94.2]

**Comment by shortercode** [comment] 2018-04-19 17:28
Realised we had 2 issues for this bug, the other one was a bit more descriptive so I'm closing this one as the duplicate of #1481

**Closed by shortercode** 2018-04-19 17:28 UTC
Labels: duplicate
