### ISSUE TITLE
Canvas paste does not produce same outcome

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#5184] opened 2021-11-03 09:05 UTC
## Problem description
Case that is different in r270. Something is different there

## Attach a .c3p

[MrCoolBug (2).zip](https://github.com/Scirra/Construct-3-bugs/files/7466367/MrCoolBug.2.zip)

## Steps to reproduce

1.Open example in r269, preview
2.Open example in r270 preview
3.

## Observed result
r270 produces some quirk differently then r269 

## Expected result
To be same

## More details

Should it be there to begin with!

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 95.0.4638.54
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
C3 release: r270 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 1.1 gb (0.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2021-11-03 17:46
Are you sure that the new way it works in r270 is not in fact correct? Previously 'Paste object with effects' could paste with an offset due to an old bug. This was fixed in r270, so it could now paste at a different position, since it's now been corrected. So it could be that the project was relying on the old bug where pasting would be offset.

It's kind of hard to tell from this project what it is trying to do or meant to be doing, so if you do think this is a regression and not in fact the new correct behavior, it would be helpful to have a simpler project demonstrating that.

**Comment by SnipG** [comment] 2021-11-03 19:40
I don't know what it is, was side effect of some test project. But from this my prediction is: the new renderer does not handle shaders with samplerBack correctly.

Changed sampling nearest. Fullscreen off
[MrCoolJr (3).zip](https://github.com/Scirra/Construct-3-bugs/files/7470260/MrCoolJr.3.zip)

![ooouuu](https://user-images.githubusercontent.com/28864889/140180949-f11475a3-3ebc-4431-8b74-2347b554734d.jpg)

**Comment by SnipG** [comment] 2021-11-04 07:07
Did futher check, and here example to show. SamplerBack loop has offset
[TestEffectsOn_Drawingcanvas (2).zip](https://github.com/Scirra/Construct-3-bugs/files/7472897/TestEffectsOn_Drawingcanvas.2.zip)
.

**Comment by AshleyScirra** [comment] 2021-11-04 17:04
I'm afraid this has just become too confusing to investigate. The expected vs. observed results are important to be able to identify what is meant to be happening versus what is supposed to be correct. There is now a bunch of different reproductions in this issue, it's not clear the original report is relevant, and there is contradictory information like the previous comment mentions using a scale of 1.0, but the actual project uses a scale of 0.8.

Debugging complicated features is already very difficult, so it's important to have clear, concise and unambiguous reports to work with. Please start over with a new issue with a single minimal repro and clear information in every part of the issue report as per the bug report guidelines.

**Closed by AshleyScirra** 2021-11-04 17:04 UTC
