### ISSUE TITLE
black screen r281 with 3d plugin

### ISSUE THREAD

**Issue by dimielannes** [Scirra/Construct-3-bugs#5412] opened 2022-02-01 16:13 UTC
## Problem description
Black Screen on version R281 with 3D plugin

## Attach a .c3p
Open MANUAL GPS template

## Steps to reproduce

1. Open template "Manual GPS"
2. Run project
3. 

## Observed result
![erro](https://user-images.githubusercontent.com/8438162/152006090-15d28358-e222-4802-ad64-cebfb7618f5d.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2022-02-01 16:18
It works fine here.

Can you provide the requested system details? We usually need this information, and it's all we have to go on for more clues if we cannot reproduce the issue.

**Comment by AshleyScirra** [comment] 2022-02-08 12:18
Works here and no further information provided, so closing.

**Closed by AshleyScirra** 2022-02-08 12:18 UTC
Labels: can't reproduce
