### ISSUE TITLE
Animations editor invisible line bug

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1648] opened 2018-05-31 14:20 UTC
## Problem description

102 beta, open up animations editor. look you have line tool selected and just click on your draw area. You can see at frame window some lines got added, but in draw area nothing changed. But then you close animations editor and you get sprite with some magical lines that you did not add.

## Steps to reproduce

1.Open 102 beta clean project
2.Open animations editor select line tool
3.Just click on draw area and look frame window
4. Magical lines appear, that do not show up in draw area.

## Observed result

having line tool selected, and you click on draw area it spawns lines that should not be spawned.

## Expected result

Having selected line tool, and clicking draw area should not add invisible lines that show up only in frame window. After you close animations editor then sprite have magical lines that you did not draw.

## Affected browsers

* Chrome: yes

**Comment by DiegoScirra** [comment] 2018-06-01 09:27
Can't reproduce this one from an empty project.

**Comment by SnipG** [comment] 2018-06-01 12:06
They happen on empty project to. I upload project, which have sprite with thous lines.
[AnimationsEditorBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2062593/AnimationsEditorBug.zip)
Line end point is where i clicked, start points seems always be 0
If i click 30 times in row, 29 disappear and 1 remains.
When clicked they do not show on draw area, only in frame but they are there when i close animations editor.
They also happen when i am in incognito mode stable 98.

**Comment by SnipG** [comment] 2018-06-01 12:10
I now tried it on chrome canarly stable 98 and beta 102, line tool still bugged.

**Comment by DiegoScirra** [comment] 2018-06-01 12:40
Fixed in r103

**Closed by DiegoScirra** 2018-06-01 12:40 UTC
Labels: can't reproduce
