### ISSUE TITLE
opening the icon files on a cloud saved project cause crash

### ISSUE THREAD

**Issue by IJCT95** [Scirra/Construct-3-bugs#1436] opened 2018-03-27 17:59 UTC
## Problem description
opening the icon files on a cloud saved project cause crash

*Enter a concise description of your problem here*

open a project that you saved on cloud, go to the project bars, go to "icons" open any of those icons, carsh.

VERSION: 93.2

**Comment by AshleyScirra** [comment] 2018-03-27 18:04
Can't reproduce in r93.2 using a project opened from Dropbox. Please always follow the bug report guidelines to ensure we can investigate the issue. Also if you at least paste in the error message you receive, we can sometimes work with that.

**Comment by IJCT95** [comment] 2018-03-27 18:35
project was saved in Google Drive.


Error report information
Type: unhandled exception
File: https://editor.construct.net/r93-2/main.js, line 74, col 207248
Message: Uncaught TypeError: Cannot read property 'ǃwe' of null
Stack: TypeError: Cannot read property 'ǃwe' of null at e.ǃTyR.ǃTQf (https://editor.construct.net/r93-2/main.js:74:207248) at e.ǃTyR.ǃTDW (https://editor.construct.net/r93-2/main.js:74:206514) at e.ǃTeI.ǃTeL (https://editor.construct.net/r93-2/main.js:74:148604) at ǃg.ǃgO.ǃVu.ǃTno.ǃu$ (https://editor.construct.net/r93-2/main.js:74:71747) at ǃg.ǃgO.ǃVu.ǃTno.ǃTec (https://editor.construct.net/r93-2/main.js:74:70953) at ǃg.ǃgO.ǃVu.ǃTno.ǃTeW (https://editor.construct.net/r93-2/main.js:74:71038) at ǃg.ǃgO.ǃVu.ǃTno.ǃStA (https://editor.construct.net/r93-2/main.js:74:70575) at a (https://editor.construct.net/r93-2/components/bars/projectBar/projectBar.js:1:32881) at Function.ǃSOB.ǃoS (https://editor.construct.net/r93-2/components/bars/projectBar/projectBar.js:1:38471) at window.ǃSOB.ǃSOB.ǃSFs (https://editor.construct.net/r93-2/components/bars/projectBar/projectBar.js:1:37971)
Construct 3 version: r93.2
URL: https://editor.construct.net/r93-2/
Date: Tue Mar 27 2018 13:34:50 GMT-0500 (Hora est. Pacífico, Sudamérica)
Uptime: 2276.1 s

Platform information
Browser: NW.js
Browser version: 0.27.4
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@d8d23fd3b95d7b3c7744027f2ea1c954aec28955) NWjs/0.27.4 (like Chrome/63.0.3239.132)
C3 release: r93.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R7 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by DiegoScirra** [comment] 2018-03-28 11:07
Fixed in r94

**Closed by DiegoScirra** 2018-03-28 11:07 UTC
Labels: can't reproduce
