### ISSUE TITLE
It is impossible to save individual files to a file sharing for example in a dropbox as in Construct 2

### ISSUE THREAD

**Issue by kop9000** [Scirra/Construct-3-bugs#1191] opened 2018-01-14 20:31 UTC
in the deskopnoy version it is impossible to save individual files in a file exchange for example in a dropbox as in Construct 2

**Comment by AshleyScirra** [comment] 2018-01-14 20:59
Do you mean Cloud Save? It works fine here. Please try to fill out as much of the bug report as possible when filing issues, it's there to make sure we understand the problem you are reporting, and if I don't understand I generally just close the issue.

**Closed by AshleyScirra** 2018-01-14 20:59 UTC

**Comment by kop9000** [comment] 2018-01-14 22:07
I mean that it is impossible to save as separate files. Ie in the cloud you can save one file c3p and not as separate files

**Comment by AshleyScirra** [comment] 2018-01-15 11:13
This would be a feature request, not a bug.
