### ISSUE TITLE
Crash when adding behavior

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#5574] opened 2022-03-28 13:26 UTC
## Problem description

Specifically I tried to add it to a family, it worked fine when I tried again. No idea what caused it but maybe this helps.

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r287/main.js, line 868, col 455
Message: Uncaught TypeError: unexpected type
Stack: TypeError: unexpected type at Function.R.i (https://editor.construct.net/r287/main.js:868:461) at d.ht (https://editor.construct.net/r287/projectResources.js:649:430) at Array.wlb (https://editor.construct.net/r287/projectResources.js:844:187) at window.P8a.dispatchEvent (https://editor.construct.net/r287/main.js:1055:42) at RAa (https://editor.construct.net/r287/projectResources.js:49:376) at window.ZAb.Va (https://editor.construct.net/r287/projectResources.js:563:242) at d.mAb (https://editor.construct.net/r287/projectResources.js:607:265) at UP.g.J.gFc.Xa (https://editor.construct.net/r287/projectResources.js:2566:380) at UP.g.J.gFc.xq (https://editor.construct.net/r287/projectResources.js:2567:234) at Array. (https://editor.construct.net/r287/projectResources.js:2564:108)
Construct 3 version: r287
URL: https://editor.construct.net/r287/
Date: Mon Mar 28 2022 12:24:20 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 6636.2 s

Platform information
Browser: Chrome
Browser version: 99.0.4844.82
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36
C3 release: r287 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9709)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment] 2022-03-28 14:22
This sounds like a duplicate of #5544

**Closed** 2022-03-31 16:38 UTC
Labels: no repro
