### ISSUE TITLE
Test Mode not working on Rewarded Ads

### ISSUE THREAD

**Issue by sizcoz** [Scirra/Construct-3-bugs#3027] opened 2019-06-10 18:15 UTC
## Problem description

Test mode does not work with the following configurations with Rewarded Ads

NOT WORKING -- With Test Mode Ticked and Ad unit ID "ca-app-pub-MY ID HERE"
NOT WORKING -- With Test Mode Ticked and Ad unit ID "TEST" 
WORKING -- With Test Mode Ticked and Ad unit ID "ca-app-pub-3940256099942544/5224354917"  Official Admob Test Ad unit ID.

## Steps to reproduce

1. Check Test mode in Mobile Advert properties
2. Start of Layout > Create Rewarded Video AD, Put your Rewared ad unit id details in or "TEST" 
3. Is Video loaded > Show Video Advert

## Observed result

The video Ad does not load.

## Expected result

The Video Ad to load

## More details

The only way to get a Test Rewarded Video Ad to load is to use Admobs official Ad unit Test ID.
Putting your own Rewarded Ad unit Id or "TEST" in will result in the Video Ad not loading.
As a comparison I tried Interstitial with my Interstitial Ad unit, and this is working well.

**Affected browsers/platforms:** 
Exported with min Android 7

Test phone Android 9 Motorola G6

Signed APK

 first started happening in r152 -->

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 74.0.3729.169
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
C3 release: r152 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 186 gb
Storage usage (approx): 284 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2019-06-13 15:10
Well I tested situation number 1 and had no issues. The only thing I would note is that it can be quite slow to load the advert.

Generally if the test advert ID works then I would think that there isn't anything wrong with the implementation. I don't believe we support the "TEST" value anymore, it was an alias to the admob test ID you listed above but it was removed in favour of the "proper" testing mode where you use your actual unit ID.

As I mentioned of the forums we have had developers mention issues with rewarded videos in the past, but I haven't been able to replicate them. Some devs have mentioned that videos didn't work for a couple of weeks. It's kinda hard to tell what the issue is. If your willing to share your details with me privately then I could try them and see if I get the same issue?

**Comment by sizcoz** [comment] 2019-06-13 16:52
Thanks for looking.
I have set up a variable that shows "yes" when **"is video loaded"** completes and it shows that the video is loading, but on **"show video advert"**, it displays nothing, while still showing it's loaded.
I will test with a blank project and see what happens
Thanks again.

**Comment by sizcoz** [comment] 2019-06-14 08:34
So I have tested on a blank project which works, which is worrying because on my project with the same code below.
Start of Layout > Create Rewarded Video AD, with my ad id.
Is Video loaded > Show Video Advert
The advert loads but nothing is shown.
I will do some further testing, I can share my project **privately** with you if you give me your email details, as its near complete.

**Comment by shortercode** [comment] 2019-06-14 11:54
Sure I'll take a look at your project, my email is iain@scirra.com

**Comment by sizcoz** [comment] 2019-06-14 16:55
Project sent from sizzgames@gmail.com.

Cheers

**Comment by shortercode** [comment] 2019-06-17 13:59
Thanks for sending that over. I'm not sure if this will be reassuring or troubling but I haven't been able to see any issues. 

I took your full project ( no modifications ) and exported it as a Android Studio 
( AS ) project ( min. Ver. 8.0 and all check-boxes unticked ). After performing some minor gradle corrections ( currently required if your using latest AS ) I ran a debug build on a Samsung S8 running Android 9. I selected "continue to show relevant ads" and after about 3 secs the textbox updated to "loaded" and then the video appeared pretty much immediately. I repeated this with a non debug build. After this I went back to C3 and exported a debug SDK and installed on the same device, and it was the same again.

I'm open to retrying this test with a different device and or different export settings; but I can't think of any major reason why we would be hitting this issue on a moto G6. It's not a flagship device but it's fairly fresh and reasonably powerful.

**Comment by sizcoz** [comment] 2019-06-17 15:05
Hi 
Thanks for looking, That a bit unusual, it sounds like maybe it's device related, seeing as the admob test id works, but my id does not, I will try with different versions of android to see if I can get it working.
Just to confirm it's a Moto g(6), running on Android 9. I will also try on a Moto g(5) plus, that I have, If I can find where I've put it.

**Comment by sizcoz** [comment] 2019-06-17 22:06
I have tried on a Moto G4 Plus, and It works, So Moto G6 is the problem.
So, I don't know where we go from here ?

**Comment by shortercode** [comment] 2019-06-18 11:22
I'm not sure there's much more I can do here to be honest.

One of the difficulties here is that we don't know the situation that causes the issue. It could be device configuration or something specific to a subset of Android devices. As our code appears to working for the majority of devices I'm inclined to think it's not something we're doing wrong.

You may be able to get additional information by debugging the device in Android studio. But if you don't have any knowledge of Java or Android Studio (?) then that probably isn't an option. If you do have some knowledge, or feel up to the challenge then I'm happy to provide some additional guidance if you have any questions.

I guess the easiest next action would be for you to ask other developers on the forum about what devices they have and if they have had issues with rewarded video. Alternatively you could try talking to developers on the Admob community, contacting Admob support or posting a question on StackOverflow.

As we have no replication, and no action to complete at this time I'm going to close this report. But if you find new information for me to investigate I will consider reopening. Similarly I will try to answer any questions you might have.

**Closed by shortercode** 2019-06-18 11:22 UTC
Labels: can't reproduce, need info

**Comment by sizcoz** [comment] 2019-06-18 11:32
Once again, thank you for your help, I think I am going to have to accept that Rewarded Ads might not work on every Device in the Market, hopefully it will be the majority of Devices. 
If I get time I will try to Debug with Studio.
Many Thanks again, for your time.
Cheers

**Comment by shortercode** [comment] 2019-06-18 13:08
No worries, hope everything works out.
