### ISSUE TITLE
Android version stuck on C3 loading screen (R146)

### ISSUE THREAD

**Issue by rhg1968** [Scirra/Construct-3-bugs#2893] opened 2019-04-25 13:58 UTC
## Problem description

I created a simple project in R146 that goes from a boot scene to a main layout. If I use the android build service provided by construct, the app gets stuck on my device on the stock C3 loader screen 97% of the time. Every once in a while it will try to go past the loader screen.

## Attach a .c3p

[Ocean Galaxy DefenderIV.zip](https://github.com/Scirra/Construct-3-bugs/files/3117185/Ocean.Galaxy.DefenderIV.zip)

## Steps to reproduce

1. Load the project in R146
2. Export to android, default options except for android 8+ and debug APK
3. Run on device

## Observed result
The app on android gets stuck most of the time on the C3 stock loader screen and never tries to move to load the default layout in the project.

## Expected result
I expect to see the green bar go across the screen on the C3 loader screen and then load the first layout.

## More details

**Affected browsers/platforms:** 
Android - Galaxy S8+

**First affected release:** 
This has been occurring for numerous releases, not sure exactly when it started.

## System details

<details><summary>View details</summary>

Galaxy S8+
One UI version      1.0
Android version    9
Kernel version    4.4.153
Android security patch level      March 1, 2019

Chrome on Android   73.0.3683.90

</details>

**Comment by AshleyScirra** [comment] 2019-04-25 16:08
It would be useful if you could provide any console messages that appear when it gets stuck - see [checking for errors in browsers](https://www.construct.net/en/tutorials/checking-for-errors-in-browsers-5).

**Comment by rhg1968** [comment] 2019-04-25 16:13
This is only happening when creating the APK. Runs fine on my desk top and it the chrome browser on my android device. Due to a damaged charging port I can not hook my phone up to my computer to see if there are any errors, I actually have to wirelessly charge my phone. 

I have brought this issue up before and to be honest, I am close to giving up because this simple version of a game I am working on will not run on my android device consistently. Not making it to my first layout most of the time as an android app is very concerning,

**Comment by rhg1968** [comment] 2019-04-26 04:33
The interesting thing is that tonight my chrome updated to version 74 and now appears to not hang anymore.

**Comment by rhg1968** [comment] 2019-04-26 04:33
I meant the upgrade was on my android device.

**Comment by AshleyScirra** [comment] 2019-04-26 10:48
The Galaxy S8+ has a Mali GPU and Chrome 74 has a fix for a known issue with WebGL 2 on Mali devices. If you cannot reproduce the problem any more I assume it is that GPU issue, so closing. If you have any further issues please file a new issue.

**Closed by AshleyScirra** 2019-04-26 10:48 UTC
