### ISSUE TITLE
Inputfield unselection lag

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#3153] opened 2019-07-18 02:35 UTC
## Problem description
When opening expression, comment etc. Then sometimes you need to click like 4-5+ times to select that input and be able to enter something.
First time input(comment, expression) etc is opened everything is selected. So you need  to click inside to unselect all, and then you are able to enter things there. But this bug causes cases you need to click like 4-5+ times and its very very annoying.  It has been like this for long long time!!!

You can always enter things instantly, but everything is preselected so all selected text will dissappear. So workaround would be disable this text is preselected at start!

## Attach a .c3p
[InputBuggg.zip](https://github.com/Scirra/Construct-3-bugs/files/3404487/InputBuggg.zip)

## Steps to reproduce

1.Open example, navigate to eventsheet
2.Double Click on comment and click to type. 
3.

## Observed result
Not always but 1 out of 5/6 try, you need to click multiple times to unselect already selected text.

## Expected result
Always able to select or click inside input instantly, so preselected text will be unselected!
Or text won't be preselected at start, not sure why it is? 
Able to disable this preselection from settings!

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment] 2019-07-18 10:30
System details might be useful on this, I can't reproduce the issues myself. Assigning to @AshleyScirra to review.

**Comment by AshleyScirra** [comment] 2019-07-18 11:45
I can't reproduce this either, it seems to work fine every time for me. I'm afraid as usual we need reliable steps to reproduce. Often reports saying "it happens randomly" actually do have a specific sequence of inputs that cause it (e.g. see #3148) and you need to find that for us to be able to investigate.

**Closed by AshleyScirra** 2019-07-18 11:45 UTC
Labels: can't reproduce

**Comment by SnipG** [comment] 2019-07-18 15:28
Already suspected that this is chrome own issue and did small testing and it does not reproduce in firefox. Something to do with already selected text.

Is there someway i can disable preselection with own theme or something?

Bug makes rly annoying to change expressions etc when you have to wait or click multiple times to be able to change inputfield.

Bug: you got inputfield, you select it with ctrl+a and then try to click  select it for unselection, sometimes it  takes 5+ clicks to unselect text. 
One can easily reproduce this on some inputfield like: https://www.w3schools.com/css/tryit.asp?filename=trycss_form_textarea

Reproduce:
1. navigate https://www.w3schools.com/css/tryit.asp?filename=trycss_form_textarea
2. Insert text to textarea: 
*
*
*
*
*
*
*
3. Keep clicking up and down( click move mouse a bit down click then move mouse back up). Press ctrl+a. Eachtime you unselect try to ctrl+a to select it again
4. See sometimes it takes like 5+ clicks to unselect text.

**Comment by AshleyScirra** [comment] 2019-07-18 15:31
> Already suspected that this is chrome own issue and did small testing and it does not reproduce in firefox. 

That suggests it's a Chrome issue then. You could file it with Google.

**Comment by SnipG** [comment] 2019-07-18 15:51
Could be this, issue with LayoutNG enabled. http://crbug.com/968386 which does bug inside chrome but no in firefox. 

> Is there someway i can disable preselection with own theme or something?
?

**Comment by shortercode** [comment] 2019-07-18 15:56
I can't reproduce anything with your new reproduction, but can reproduce the crbug, which suggests they are different. With the text input if you click the down arrow then it immediately cancels the selection, but the crbug can't be resolved like this.

In terms of possible false positives: if you click rapidly then it thinks your double clicking, and hence highlights the current line. If you move the mouse slightly when you click it treats it as if your dragging the text, so doesn't cancel the selection. 

I used to have a semi similar issue with text selection with a mac magic mouse, as the top touch surface often triggers small scroll events when you click.

**Comment by AshleyScirra** [comment] 2019-07-18 15:59
> Could be this, issue with LayoutNG enabled.

It's a Chrome bug. There's no point asking here, we don't make Chrome.
