### ISSUE TITLE
Re-sizing Eventsheet is widths is very difficult

### ISSUE THREAD

**Issue by Bat-Computer** [Scirra/Construct-3-bugs#3292] opened 2019-08-31 16:51 UTC
When trying to re-size the Eventsheet panel widths, it is very hard to select the edge in order to drag left or right. 

Most of the time the symbol for the cursor to drag changes when you're not on the edge, it's also there one second and not the next - typically when you're about to drag the edge of the panel it changes back to a pointer. Sometimes it can be at least 16 pixels out, other times you are hovering directly over the edge and it doesn't appear at all. It tool a long time just to provide a screenshot for this bug as it's so hard to get to work.

Importantly it seems to work better on smaller Eventsheets, the longer they are the more unresponsive it is.

![Adjusting issue](https://user-images.githubusercontent.com/40317509/64066876-44accc00-cc17-11e9-8a5e-adadd5bcc92c.jpg)

## Steps to reproduce

Simply create a project and go into the Eventsheet and attempt to resize the panels.

## Observed result

The cursor jumps from a normal pointer to a drag handle unpredictabily all the time when trying to select an edge or drag.*

## Expected result

You would expect the cursor to change within a few pixels either side of the edge and remain there.

Both Stable Desktop version (R157) and the Windows 10 Beta App (R163 Beta) are affected.

## System details

Windows 10, 64bit, 8GB Ram, Nvidia Geforce 560ti etc

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment] 2019-09-02 10:59
This is a very old issue #525, which we have struggled to reproduce locally. We resolved at least one variation on it in January but I guess another situation exists. Going to preemptively apply the difficult label an assign to @AshleyScirra to review.

I attempted to reproduce this in the NW.js version with the dark theme and it behaved correctly with a fresh project. I expect more information will be required. Have you customised your layout much ( moving bars around, opening in pop-ups etc. ? )

**Comment by Bat-Computer** [comment] 2019-09-02 11:33
I tested this just with the default Dark theme on two totally different machines, one laptop (1080p) and the desktop I mentioned (2560x1440). 

Nothing else was altered - the UI was intact as default. 

When you eventually grab the edge after many many attempts, the green line divider feels quite laggy too. 

I like to space out the sections so that I can read things horizontaly easier, when stacked it can be more difficult. This I'll typically do with main events and subs. 

It definitely appears to be worse if there are a lot of events. On a fresh scene with a few events it was fine. 

I've only just moved from Construct 2 to 3 in last few days and it's been a bit disappointing so far. The main reason I moved was for the easier building and the dark theme, as I have problem with my eyes, dark themes help a lot.

Jay.

**Comment by AshleyScirra** [comment] 2019-09-02 12:11
@Bat-Computer - do you have Chrome's dev tools open while doing this? The only known case this happens is when dev tools is open, which is a Chrome bug. If dev tools is closed it should never happen. I just tried and can't reproduce it with dev tools closed.

**Comment by SnipG** [comment] 2019-09-02 13:08
I think it was something to do when border was set to 0px.

**Comment by Bat-Computer** [comment] 2019-09-02 13:40
No, the only thing running is either the Construct 3 Desktop Win 10 beta app or the C3 Stable Windows download. No other software open.

**Comment by SnipG** [comment] 2019-09-02 13:53
Did test, this is caused by C3 bad eventsheet performance. I think they need to fix that to fix multiple other behaviors caused by that.
My random uess would be, loading sprite images on eventsheets take lot of performance.

**Comment by Bat-Computer** [comment] 2019-09-02 15:15
I installed Chrome to test, although not as bad as the Stable Desktop download version and Win 10 App Beta, it's still really sluggish and often misses when you attempt to select. I'm totally sure now that a heavier Event Sheet Window causes this problem. 

Running my old Construct 2 it's really responsive in comparison and it works flawlessly with resizing events.

What's going on guys, hasn't Constcut 3 been around for several years now? Surely this kinda stuff should have been sorted by now? I've just paid for an annual sub and I've a big project to create for the next year. This is the third  bug I've found and I've only had it a few days!

As my son would say "Sad face".

**Comment by AshleyScirra** [comment] 2019-09-03 11:12
There's no project attached to the report so I can't check what you're seeing. From a quick test it was working fine. If there are general performance issues in that theme, there is already #3017 filed about that, so closing this issue.

**Closed by AshleyScirra** 2019-09-03 11:12 UTC
Labels: can't reproduce, difficult
