### ISSUE TITLE
Crash After Using CTRL+F Search Results to Jump to a Deleted Event Line

### ISSUE THREAD

**Issue by Rhindon** [Scirra/Construct-3-bugs#4328] opened 2020-11-07 10:42 UTC
## What happened

C3 crashed after attempting to jump to search results still listed during a CTRL+F search for remaining event lines related to a then-deleted behavior. Even though the behavior was deleted, the event lines related to that behavior still remained in the search listings window. Clicking on one of the results caused C3 to crash.

## Attach a .c3p
[Anti_Virus alpha 0-2 crash recovery zip.zip](https://github.com/Scirra/Construct-3-bugs/files/5504577/Anti_Virus.alpha.0-2.crash.recovery.zip.zip)

## Steps to reproduce

1. Search for an object behavior (an instance variable or even the whole object might also work, but this occurred right after I had deleted a behavior) in the event sheet to bring up a list of search results.
2. Delete a behavior from an object.
3. With the related event lines deleted in response to the behavior being deleted, click on one of the search result items.
4. This should cause the program to crash since there's no associated event line attached to the search result item.

## Observed result

A complete crash of C3 and thus offering the option to save my project and to copy the system info as provided down below.

## Expected result

To be honest, I figured that if there was something still in the search results, there might have been something I missed. My expectation was for all related event lines regarding the behavior to be deleted - which they were. However, the search result items still being listed gave me the impression that maybe that wasn't the case (in my defense, it's 2:30am and I'm not fully cognitive).

I would think that if an event line no longer exists - or rather the particular thing that was searched for - then that search result item should also be deleted from the list.

## More details

**Affected browsers/platforms:** 
Chrome only. I do not use other browsers.

**First affected release:** 
r223. My project is saved on r223 and won't open in an earlier release as I understand things.

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: cannot select detached view
Stack: Error at Function.d.WTa (https://editor.construct.net/r223/main.js:287:41) at window.assert (https://editor.construct.net/r223/main.js:201:149) at ea.tq (https://editor.construct.net/r223/components/editors/eventSheetView/eventSheetView.js:162:322) at ea.Ne (https://editor.construct.net/r223/components/editors/eventSheetView/eventSheetView.js:159:464) at ea.Mv (https://editor.construct.net/r223/components/editors/eventSheetView/eventSheetView.js:161:222) at window.Heb.Xia (https://editor.construct.net/r223/components/bars/findResultsBar/findResultsBar.js:9:312)
Construct 3 version: r223
URL: https://editor.construct.net/r223/
Date: Sat Nov 07 2020 02:14:59 GMT-0800 (Pacific Standard Time)
Uptime: 37462.3 s

Platform information
Browser: Chrome
Browser version: 86.0.4240.183
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36
C3 release: r223 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment] 2020-11-09 14:40
The project provided is too big to be useful and the steps to reproduce are vague, but came up with a minimal repro: 
[issue4328.zip](https://github.com/Scirra/Construct-3-bugs/files/5511189/issue4328.zip)

Steps to reproduce:

1. Ctrl+F, search for "speed"
2. Delete 8 direction behavior (keep results window showing)
3. Double click search result

**Comment by AshleyScirra** [comment] 2020-11-09 14:45
OK, this should be fixed for the next release, but note I've only fixed it for the minimal repro I provided in my previous comment - I haven't tested your provided project, because the steps to reproduce aren't specific enough (I don't know what you searched for).

**Closed by AshleyScirra** 2020-11-09 14:45 UTC
