### ISSUE TITLE
Unhandled exception layout view crash :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6558] opened 2023-02-17 23:09 UTC
## Problem description

Construct crashes.

## Attach a .c3p

save open project: [save_open_project.zip](https://github.com/WilsonPercival/WilsonPercival/files/10772127/save_open_project.zip)

## Steps to reproduce

1. Create a new project.
2. On `Layout 1`: Create a new layer `Layer 1` and make it global.
3. Create a layout `Layout 2`.
4. On `Layout 2`: Create a new layer `Layer 1`.
5. On `Layout 2`: Create a sprite on `Layer 1`.
6. On `Layout 2`: Rename `Layer 1` to `Layer` and make it global.
7. Switch to `Layout 1`.

## Observed result

https://user-images.githubusercontent.com/91274932/219812324-13907dc6-9c25-4cb2-bea1-adefa58a1914.mp4

## Expected result

Construct does not crash.

## More details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r330/components/editors/layoutView/layoutView.js, line 52, col 205
Message: Uncaught TypeError: Cannot read properties of null (reading 'As')
Stack: TypeError: Cannot read properties of null (reading 'As') at https://editor.construct.net/r330/components/editors/layoutView/layoutView.js:52:205 at Array.filter () at y$a (https://editor.construct.net/r330/components/editors/layoutView/layoutView.js:52:179) at window.yrc.VP (https://editor.construct.net/r330/components/editors/layoutView/layoutView.js:190:114) at Array. (https://editor.construct.net/r330/components/editors/layoutView/layoutView.js:189:6) at window.Il.dispatchEvent (https://editor.construct.net/r330/main.js:1235:42) at m5b (https://editor.construct.net/r330/components/editors/layoutView/layoutView.js:87:458)
Construct version: r330
URL: https://editor.construct.net/r330/
Date: Sat Feb 18 2023 00:42:08 GMT+0200 (Восточная Европа, стандартное время)
Uptime: 93.7 s

Platform information
Product: Construct 3 r330 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r330b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r330 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 193 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2023-02-20 15:41
Should be fixed in next beta.

**Closed by AshleyScirra** 2023-02-20 15:41 UTC

**Comment by WilsonPercival** [comment] 2023-02-20 15:45
> Steps to reproduce:
> 
> 1. Open project [issue6558.zip](https://github.com/Scirra/Construct-3-bugs/files/10785690/issue6558.zip)
> 2. On Layout 2, rename "Layer 1" to "Layer".
> 
> Observed result: in this case it causes an immediate crash (whereas the original steps crashed after changing layout - but it looks like the same crash) Expected result: no crash; also no selection box when renaming an overridden layer so it's no longer inheriting content from a global layer
> 
> (Please provide information in this format when you can - otherwise it takes longer to deal with reports, as we first have to figure out this information ourselves.)

Sorry, I didn't understand what you mean. Do you want me to provide the required information in all currently open reports? It seemed to me that I provided all the necessary information, including the video, and I would hardly be able to write anything else. If you need information - you can ask me about it.

**Comment by AshleyScirra** [comment] 2023-02-20 15:57
What we need in bug reports (and what the bug report guidelines describe) is a project file to open, and then steps to follow once that project is open, that then reproduces a problem.

It looks like you often save a project after a crash or problem has happened. This is unfortunately not useful as the change has already been made, so we cannot easily reproduce the same problem in that project file.

The steps to reproduce often start from creating a new project. This is unfortunately not as helpful as it sounds because it makes for a long series of steps and following them is quite slow and error prone. (We often have to follow the steps 20+ times while diagnosing a bug so keeping them short is important.)

The video also often starts from creating a new project, which means it is usually longer than necessary, and videos are more difficult to follow than written steps because it is difficult to keep up with a video playing in real-time, and we can't see when exactly clicks and key presses happen.

In my first comment I provided the ideal information we need for a bug report: a project file to open in a state just *before* a problem happens, and then a written version of the shortest possible list of steps to reproduce a problem after opening that project. Once we have that, it is much quicker to deal with the problem. However sometimes it takes longer to establish that information than it does to actually fix the problem!

I don't think it's necessary to go back and update all existing bug reports, but please bear this in mind if you continue to file more issues. Given the number of issues you are filing, and the fact we are a small team with limited time and resources, it is very helpful if you can write reports in the way we need so we can fix them as quickly as possible.

**Comment by WilsonPercival** [comment] 2023-02-20 16:56
> What we need in bug reports (and what the bug report guidelines describe) is a project file to open, and then steps to follow once that project is open, that then reproduces a problem.
> 
> It looks like you often save a project after a crash or problem has happened. This is unfortunately not useful as the change has already been made, so we cannot easily reproduce the same problem in that project file.
> 
> The steps to reproduce often start from creating a new project. This is unfortunately not as helpful as it sounds because it makes for a long series of steps and following them is quite slow and error prone. (We often have to follow the steps 20+ times while diagnosing a bug so keeping them short is important.)
> 
> The video also often starts from creating a new project, which means it is usually longer than necessary, and videos are more difficult to follow than written steps because it is difficult to keep up with a video playing in real-time, and we can't see when exactly clicks and key presses happen.
> 
> In my first comment I provided the ideal information we need for a bug report: a project file to open in a state just _before_ a problem happens, and then a written version of the shortest possible list of steps to reproduce a problem after opening that project. Once we have that, it is much quicker to deal with the problem. However sometimes it takes longer to establish that information than it does to actually fix the problem!
> 
> I don't think it's necessary to go back and update all existing bug reports, but please bear this in mind if you continue to file more issues. Given the number of issues you are filing, and the fact we are a small team with limited time and resources, it is very helpful if you can write reports in the way we need so we can fix them as quickly as possible.

I really try to follow the bug report guidelines as much as possible. As for providing a project file instead of reproducing it from scratch: most of my reports involve using the fallback system to reproduce the problem. For example, in this report https://github.com/Scirra/Construct-3-bugs/issues/6584 the crash occurs when rolling back to the very first point. This would be impossible to repeat without making the project from scratch. Therefore, I do not understand how the project file can be useful here.

You also made a new list of steps and provided a new project file. I tried to repeat it and I got a completely different error that I didn't even know about. Here's a video:

https://user-images.githubusercontent.com/91274932/220164371-db6d63a6-6128-4d48-984f-14479f79b953.mp4
