### ISSUE TITLE
Low fps  when project is not modified at start

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1635] opened 2018-05-28 17:07 UTC
## Problem description

Strange case when opening test project cause low fps at start, adding 1 sprite or deleting folder will fix it. 
Project without modification on same test case - 15-17 fps, after i modify or change project just a little , same test case result 30 fps. 

## Attach a .c3p

[StrangeBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2045713/StrangeBug.zip)

## Steps to reproduce

1. Open project without changing anything
2.Open up debug, spawn some number of sprites and rotate them with A or D, enough to see some low fps use
3. Add 1 sprite, or delete folder/s, but not folder 1.
4.Open project debug, replicate previous test and  see fps increase.

## Observed result

On this strange case, when project is opened up and debugged fps runs low, but when project is modified fps increase. Which looks something at start is not loaded properly, and will fix itself when project is modified. I have not tested with export, so I no idea if this have influence on exported project fps.
CPU use stay about same, maybe a bit increase, but biggest hit takes fps.

## Expected result

When projects are opened up first time and tested, fps should stay same. As people have multiple saves of their project and when testing each one, they might not change anything. So this bug have big influence on C3 use. 

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment] 2018-05-29 10:52
Can't reproduce on my system, but instructions like this are tough to follow because it depends on user input and manually altering the project. It is much easier to deal with reports if the projects are automated (so there is no variation based on input), and you provide the project file for any variations (so they can be directly tested without risk that I'm making different changes to you).

There is no technical reason for a trivial change to the project to have a large performance impact, so I suspect this is just a quirk of the measurements.

**Comment by SnipG** [comment] 2018-05-29 13:43
I tested with automated, i still get the difference. I start project up, go debug tab watch,check fps (13-14). I close it, delete folder 2,3,4 or add just blank sprite on layer 0. And then i open debug go tab watch and i see difference in fps (27-30). could it just be my pc, its a bit old to ?
[strangebug2.zip](https://github.com/Scirra/Construct-3-bugs/files/2048408/strangebug2.zip)
i tried it on chrome incognito mode, still same.

**Comment by SnipG** [comment] 2018-05-29 13:56
I tried it now on chrome canarly, i opened  and closed project 3 time, each time open project - debug check fps, was always 15-17.  Then i did 3 time in row, opened project deleted folder 4 and went debug, each time fps 22-24.

**Comment by SnipG** [comment] 2018-05-29 14:57
I did huge amount of tests and it seems it have something to do with, sprites with containers and clones of them.
[StrangebugContainerTest12.zip](https://github.com/Scirra/Construct-3-bugs/files/2048737/StrangebugContainerTest12.zip)

**Comment by SnipG** [comment] 2018-05-29 15:00
When i run that test sprites with containers, mark down fps, then i delete folder 3. project gets huge fps hit. Maybe its fixed already, so i could wait for next release

**Comment by SnipG** [comment] 2018-05-29 15:06
Folder 1 is sprites with containers that are on layout and used on project. Folder 2 and 3 are full sprites that are clones from folder 1 and never been on layout. They could somehow be linked ?

**Comment by AshleyScirra** [comment] 2018-05-29 15:36
I still can't reproduce any issue. With the latest project (StrangebugContainerTest12.zip) it runs 60 FPS with ~50% CPU usage. After deleting folder 3, it runs at 60 FPS with ~40% CPU usage.

**Comment by SnipG** [comment] 2018-05-29 15:42
Maybe it is fixed, i could wait for next release. But i did test, i deleted folder 3 got low fps, i saved project. Opened saved project and fps was still low! 
You could try spawning more of thous to get fps around 30.
Anyway it seems strange, i wait for next release and report back.

**Comment by AshleyScirra** [comment] 2018-05-29 16:15
Why not look in the profiler and see what's taking longer?

I can't reproduce any issue so closing for now, please re-file if you still think there's an issue.

**Closed by AshleyScirra** 2018-05-29 16:15 UTC
Labels: can't reproduce
