### ISSUE TITLE
a glitch with Timeline in Layout

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#3876] opened 2020-05-22 05:46 UTC
## Problem description

When we remove x and y property from timeline and add width and height and while in editing mode If we scroll pan or scroll layout then it doesn't scrolling but doing some glitches. We can see layout scroll bar is moving up-down but layout is not scrolling and doing glitch.

## Steps to reproduce

1. new project
2. add sprite
3. add it to timeline
4. remove x and y from timeline 
5. add height and width in timeline
6. turn on editing mode
7. Now scroll layout and see that glitch

## Observed result

layout not scrolling but glitching 

## Expected result

scroll layout

## More details

**Affected browsers/platforms:** Desktop version only. working fine in Chrome

**First affected release:** unable to switch back to older version for testing in Desktop version 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment] 2020-05-22 09:15
Can't reproduce this one, tried the steps in the latest desktop build as well as our development build and can't see anything out of the ordinary.

**Comment by luckyrawatlucky** [comment] 2020-05-22 09:37
i still can see that glitch
repeat step 4 again by undo, it will happen

**Comment by luckyrawatlucky** [comment] 2020-05-22 10:27
i tried to reproduce it and record it, try these steps
![Timeline glitch](https://user-images.githubusercontent.com/17684135/82658435-97666200-9c44-11ea-917f-8ca8e41fd556.gif)

**Comment by DiegoScirra** [comment] 2020-05-22 10:52
I see... still can't reproduce the same issue. If I follow the same steps, when I delete the Y property track the second time, C3 crashes as in #3875. The strange thing is that it is not crashing for you, it should, but instead produces that strange layout view bug.

I am guessing this has already been fixed with the other bug, but will need you to check it out in the next beta to be sure. Thanks!

**Comment by luckyrawatlucky** [comment] 2020-05-22 10:55
it crashes on browser Not in Desktop

**Comment by AshleyScirra** [comment] 2020-05-25 13:42
r201 is now out, please check again!

**Comment by luckyrawatlucky** [comment] 2020-05-25 13:52
when i add object to timeline it got crash on both Chrome and Desktop

Error report information
Type: unhandled exception
File: https://editor.construct.net/r201/main.js, line 2, col 129106
Message: Uncaught TypeError: Cannot read property 'ǃwh' of undefined
Stack: TypeError: Cannot read property 'ǃwh' of undefined at Object.ǃhzu (https://editor.construct.net/r201/projectResources.js:1:543040) at Function.ǃhOc (https://editor.construct.net/r201/projectResources.js:1:546396) at n.ǃhOy (https://editor.construct.net/r201/projectResources.js:1:504994) at n.ǃhAg (https://editor.construct.net/r201/projectResources.js:1:503638) at n.ǃhjm (https://editor.construct.net/r201/projectResources.js:1:501488) at new n (https://editor.construct.net/r201/projectResources.js:1:494147) at Function.d.ǃF (https://editor.construct.net/r201/main.js:2:129085) at o.ǃhAh (https://editor.construct.net/r201/projectResources.js:1:465225) at o.ǃeLp (https://editor.construct.net/r201/projectResources.js:1:465436) at window.ǃeEZ.ǃec_ (https://editor.construct.net/r201/components/editors/layoutView/layoutView.js:1:33532)
Construct 3 version: r201
URL: https://editor.construct.net/r201/
Date: Mon May 25 2020 19:20:35 GMT+0530 (India Standard Time)
Uptime: 9.7 s

Platform information
Browser: Chrome
Browser version: 83.0.4103.61
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
C3 release: r201 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

**Comment by DiegoScirra** [comment] 2020-05-26 17:44
That is a different bug which has already been fixed. Will need to wait until the next beta to check if the original report was fixed

**Comment by luckyrawatlucky** [comment] 2020-06-02 14:18
Original report is fixed.
Thanks

**Closed** 2020-06-02 14:18 UTC
Labels: need info
