### ISSUE TITLE
Clone Object Type will Repeat instance Object 

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4329] opened 2020-11-08 13:37 UTC
## Problem description

Clone Object Type will Repeat instance Object 

## Steps to reproduce

1. New project
---
2. Create new object type ->  e.g: Array
3. run Debug : Array (1 instance)[#0]  
---
4. **Clone Array** --> Array 2
5. run Debug : Array (1 instance)    |    Array 2 `   (2 instance)    `
---
6. **Clone Array 2** --> Array 3
9. run Debug : Array (1 instance)    |    Array 2`   (2 instance)  `    |    Array 3 `  (2 instance)  `
---
2. Create new object type ->  e.g: Array
9. run Debug : Array (1 instance)    |    Array 2`   (2 instance)  `    |    Array 3 `  (2 instance)  `   |    Array 4 (1 instance)  

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2020-11-09 14:58
It looks like a regression caused by the fix to #4156. Thanks, should be fixed in next beta.

**Closed by AshleyScirra** 2020-11-09 14:58 UTC
