### ISSUE TITLE
Layout touch scrolling issue. Conflict in desktop version.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#1037] opened 2017-11-24 21:23 UTC
## Problem description

There seems to be a conflict with Construct and System behaviour for touch scrolling (Win10) Trying to use touch in the Layout view can behave strangely. In most browsers touch has automatically enabled scrolling. So a regular one finger touch to scroll the layout view has some wierd effects.

When touching and dragging you will both scroll and draw a selection rectangle or select an object and move it.

I think C3 needs to differentiate touch from mouse in layout view to fix this conflict, and behave more like the mobile version in this case.

## Attach a .c3p

N/A

## Steps to reproduce

1. Open Endless runner example, on a touch capable device.
2. Go to layout view and and try scrolling by using finger.
3. Notice selection rectangle If touch is not touching any objects while scrolling.
4. Notice Movement of objects if touch scrolling starts on an object.

## Observed result

Touch scrolling can conflict with other functions such as drag selection box, select object and move object.

## Expected result

No conflict:

**Suggested behaviour.**
Same as mobile version.

1. One finger tap would select object.
2. One finger drag would draw selection rectangle
3. zoom and scroll is done with two fingers.

To futureproof pen/stylus users make sure pen can't scroll, as pen (tap and drag) will also scroll, in Fall creators update. Suggested to behave like mouse, or one finger touch.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2018-07-04 12:41
I've made a few changes for touch input in the next release and everything seems to be working as intended in Chrome and Edge, so let's check the next release and see if things are working better for you there.

The only problem left I can see is that Firefox can't do pinch-to-zoom in the Layout View, but this is because of a Firefox bug where it fires multiple pointerdown events with the same ID, so it's impossible to tell them apart :-\

**Comment by AshleyScirra** [comment] 2018-07-19 12:07
Think this is as far sorted as we can now so closing. Will investigate #1760 separately. Please file new issues if you still have trouble after that issue is fixed.

**Closed by AshleyScirra** 2018-07-19 12:07 UTC
