### ISSUE TITLE
overlapping wrap-selections incorrect tab-selection

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6620] opened 2023-02-23 23:19 UTC
## Problem description
when tab selecting a wrap selection behind another wrap selection, the wrong objects are selected

## Steps to reproduce

https://user-images.githubusercontent.com/89512047/221053306-7d916c32-485c-463c-8b00-676760bf358c.mp4

1.tab click twice on the sprites
2. drag

## Observed result

two sprites of different wrap-selections are dragged

## Expected result

tab-clicking selects the either the wrap selection on top, or on bottom, not parts of both.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment] 2023-02-23 23:21
just realized with more test: the same happens if just a non wrap selected sprite is overlapping the wrap selection.

**Comment by DinoSystem** [comment] 2023-02-24 01:17
I've noticed objects are dragged also if in a global layer that is locked and transparent

**Comment by AshleyScirra** [comment] 2023-02-28 12:38
No project was provided and looks like a dupe of #6618 anyway so closing.

**Closed by AshleyScirra** 2023-02-28 12:38 UTC
Labels: duplicate, no repro
