### ISSUE TITLE
[Saving Project] Not saving to local browser storage.

### ISSUE THREAD

**Issue by SalFrisky** [Scirra/Construct-3-bugs#255] opened 2017-05-18 19:57 UTC
## Problem description

*Enter a concise description of your problem here*

## Attach a .c3p

just create a new project or open any project and try to save it to the local browser

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. create a new project
2. save it to local browser

## Observed result

*What do you see happen?*
shows mini window saying it is saving for a longer than it should, then crashes & does not save.

## Expected result
save to the local.

*What did you expect to happen instead?*
it spends longer than it should saving & then eventually crashes.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'catch' of undefined @ TypeError: Cannot read property 'catch' of undefined at Sa (https://editor.construct.net/r29/cloud/sandbox.js:1:32469) at Wa (https://editor.construct.net/r29/cloud/sandbox.js:1:32958) at Za.eb.keys.then.gb (https://editor.construct.net/r29/cloud/sandbox.js:1:33324) at 
Stack: TypeError: Cannot read property 'catch' of undefined at Sa (https://editor.construct.net/r29/cloud/sandbox.js:1:32469) at Wa (https://editor.construct.net/r29/cloud/sandbox.js:1:32958) at Za.eb.keys.then.gb (https://editor.construct.net/r29/cloud/sandbox.js:1:33324) at 
Construct 3 version: r29
URL: https://editor.construct.net/index.html
Date: Thu May 18 2017 20:51:34 GMT+0100 (GMT Daylight Time)
Uptime: 30.5 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment] 2017-05-18 20:00
We're having an issue with the save system at the moment, it will be fixed in the next patch but until then the only way to save a file will be the "download a copy" button.

**Comment by shortercode** [comment] 2017-05-18 20:03
Duplicate of [#251](https://github.com/Scirra/Construct-3-bugs/issues/251)

**Closed by shortercode** 2017-05-18 20:03 UTC
