### ISSUE TITLE
IAP Purchase Problem, Not triggering

### ISSUE THREAD

**Issue by WanKIpas** [Scirra/Construct-3-bugs#2335] opened 2018-11-18 07:54 UTC
## Problem description

Hello everyone,
I'm using the C3 Mobile IAP plugin.
IAP won't trigger the purchase action.
it runs just fine before with the previous version of my apps, and with same Events steep i used.
But a few days ago, when i uploading an update of my apps on google playstore,
i notice when I click the buy button, it is not trigger the purchase action
i tried so many adjustment to make it works, but nothing seams to work. 
Do i need to change my events? or is this really a bug?

I prepare you with a very simple c3p project to use IAP. and the In-app products is also active. 
![active](https://user-images.githubusercontent.com/43338475/48669954-0ba0e080-eb4a-11e8-800b-66e54ba5ce0d.jpg)

Please have a check and let me know.. 
Thank you.

## Attach a .c3p
Please download the c3p here.. 
https://drive.google.com/file/d/1g_gkRIi_xdMrnZQcwuO8-Z3x8_k9kdjp/view?usp=sharing

or you can download this direct it from the playstore.
https://play.google.com/store/apps/details?id=com.wankipas.constructtestapps

## Steps to reproduce
 Tap the buy button, See if you can make a purchase 

## Observed result

Nothing happen. 

## Expected result

make a purchase from google.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

No crash report dialog

**Comment by WanKIpas** [comment] 2018-11-18 16:47
I tried with the C2 Runtime, it works OK,
this prob only occur on C3 Runtime.

**Comment by shortercode** [comment] 2018-11-28 16:42
Closing as duplicate of #2057 

Please refer to that bug for progress.

**Closed by shortercode** 2018-11-28 16:42 UTC
