### ISSUE TITLE
import font from zip causes exception

### ISSUE THREAD

**Issue by 3dParadox** [Scirra/Construct-3-bugs#318] opened 2017-05-22 18:25 UTC
## Problem description

Importing a font by dragging from a zip file causes an exception on creating a text object or clicking on a text object's properties. (sometimes, just wait and it will crash.) 
I assume it's because the zip stored the font in a temp directory and once it was gone the editor couldn't reference it.

## Attach a .c3p

https://www.dropbox.com/s/zpsew6aiv2zzhnv/importfont.c3p?dl=0

## Steps to reproduce

1. open (DL) the font Zip under "files" in the C3P.
2. Right click the Fonts and import a font.
3. Drag directly from the zip (without extracting first)
4. create a text object, or try to change the font of the text object to the new one. (sometimes just wait.)

## Observed result

Crash dialog, see it below

## Expected result

A warning that the source file no longer existed, or something like that.

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Event 'error': [object ProgressEvent]
Construct 3 version: r29.2
URL: https://editor.construct.net/index.html
Date: Mon May 22 2017 13:22:46 GMT-0500 (Central Daylight Time)
Uptime: 1231.3 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R7 370 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment] 2017-05-23 14:16
Partially related to [#305](https://github.com/Scirra/Construct-3-bugs/issues/305) I've fixed 2 catch points for invalid fonts so far. When your loading the font preview and when your rendering on screen text.

**Comment by AshleyScirra** [comment] 2017-05-29 17:00
This is actually a similar issue to #374. It turns out drag-and-dropped files still reference their paths on disk. The solution is to copy the data at the point it is imported rather than using the original files. This needs to be done for both import files and import audio (when the files aren't copied), which is all Iain's code so assigning to him.

For the record, an easier repro is:

1. New project
2. Import a font
3. Drag-drop a font file in to the dialog
4. Move the font file to somewhere else on disk so it's no longer found
5. Click import files

Crashes because the blob is no longer readable. I am sure the zip case is just a variant.

**Comment by shortercode** [comment] 2017-05-31 11:38
I'm not sure this bug is actually fixable, or perhaps requires a chrome bug if we deem it a big enough problem. I've placed the fixes to cover the issue in [#374](https://github.com/Scirra/Construct-3-bugs/issues/374) into the file importer and have confirmed they work for that. However, it seems to be impossible to actually read the file in the zip case. When we attempt to copy the blob a `DOMException: A requested file or directory could not be found at the time an operation was processed.` is thrown so... short of giving a warning dialog I don't think there's much else I can do here!

I'm going to file a bug with chrome, but I expect the "fix" will be to not expose the file.

**Comment by shortercode** [comment] 2017-05-31 17:52
Okay... so with some tweaks you should now be able to include assets from a zip file, but I had to disable recursive folder import as it caused timing issues. Not really sure how I feel about that... the recursive folder import was beginning to become a pain and it used "special" chrome API's so I guess we can live with it turned off.

**Closed by shortercode** 2017-05-31 17:52 UTC
