### ISSUE TITLE
Colors are assigned to mouse buttons / pad double tap the wrong way around in the color palate

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#1263] opened 2018-02-04 09:23 UTC
## Problem description
![image](https://user-images.githubusercontent.com/21962641/35775938-0d63f926-098b-11e8-9a33-87b1db3fc8b6.png)

Pretty sure these two guys are assigned the wrong way around.  

The main color is on the right button and the underneath color is on the left button / double tap
surely should be the other-way around for default settings

its rather confusing whatever is going on anyway.

*Enter a concise description of your problem here*

as above

## Attach a .c3p
[Colors_RenameToc3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1692626/Colors_RenameToc3p.zip)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Open the sprite in the animations editor / drawing tool
2. select colors from the 2 colors  box, or use right left click to select colors or double tap mouse pad

## Observed result
colors assigned wrong way around

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: tested

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r83
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 9.9 gb (65.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by DiegoScirra** [comment] 2018-02-08 14:42
This is working as intended, but I see why it is confusing.

When drawing rectangles and ellipses, the secondary color is always used for the border. When the fill is disabled you are only drawing the border, so you are only drawing with the secondary color, which is not very intuitive.

Should be easy to fix.

**Comment by DiegoScirra** [comment] 2018-02-08 17:11
Fixed in r86

**Closed by DiegoScirra** 2018-02-08 17:11 UTC

**Comment by NetOneGames** [comment] 2018-02-08 22:15
Cool,  I do believe these little details make a big difference to the user experience.  Cheers
