### ISSUE TITLE
Cloud open and export build doesn't work in Beta205

### ISSUE THREAD

**Issue by vundurty** [Scirra/Construct-3-bugs#3994] opened 2020-06-28 11:38 UTC
Hi,

Today, I updated C3 to r205 Beta version. I noticed two issues

**1. Opening project from cloud using any cloud doesn't work**

When I try Google Drive, it says
Authorization Error
Error 400: invalid_request
Required parameter is missing: response_type

When I try Dropbox, it says
Error (400)
It seems the app you were using submitted a bad request. If you would like to report this error to the app's developer, include the information below.

When I try OneDrive, it says
Sorry, but we’re having trouble signing you in.
AADSTS900144: The request body must contain the following parameter: 'client_id'

**2. Export apps is not working. I only tried for iOS and Android.**
For both the exports, it says "Failed to export project".

I've tired it in Chrome and Edge.

I'm attaching a test project here
[Test.zip](https://github.com/Scirra/Construct-3-bugs/files/4842160/Test.zip)

Please let me know if there is something missing from end. 

Thank you. :)

**Comment by AshleyScirra** [comment] 2020-06-29 13:23
Duplicate of #3978

**Closed by AshleyScirra** 2020-06-29 13:23 UTC
Labels: duplicate
