### ISSUE TITLE
Crash while attempting to preview

### ISSUE THREAD

**Issue by 8bitThirsty** [Scirra/Construct-3-bugs#509] opened 2017-06-14 16:55 UTC
## Problem description
The app crashed when I clicked on the preview button.  I had just saved an image from a sprite to my PC within the sprite editor and had previously been moving around sprites for the most part.  I had only been working for a few minutes before this happened.  I was able to reproduce the issue multiple times.

## Attach a .c3p

[Bitmen.zip](https://github.com/Scirra/Construct-3-bugs/files/1075324/Bitmen.zip)

## Steps to reproduce

1. Open the file
2. Click the preview button

## Observed result

App crashes

## Expected result

Layout preview displayed

## Affected browsers

* Chrome: yes

## System details
Error report information
Type: unhandled exception
File: https://editor.construct.net/r37/exporters/preview/exporter.js, line 1, col 40
Message: Uncaught ReferenceError: ǃE is not defined
Stack: ReferenceError: ǃE is not defined at https://editor.construct.net/r37/exporters/preview/exporter.js:1:40
Construct 3 version: r37
URL: https://editor.construct.net/
Date: Wed Jun 14 2017 12:49:11 GMT-0400 (Eastern Daylight Time)
Uptime: 732.7 s

Platform information
Browser: Chrome
Browser version: 60.0.3112.24
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.24 Safari/537.36
C3 release: r37

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment] 2017-06-14 17:00
Duplicate of [#508](https://github.com/Scirra/Construct-3-bugs/issues/508)

@8bitThirsty There's a cache issue with r37 which seems to trigger when you launch preview. You can bypass this by either reloading the page and previewing with caching disabled in the debugger or by clearing your file and image cache with the "Clear browsing data..."

**Closed by shortercode** 2017-06-14 17:00 UTC
Labels: duplicate

**Comment by 8bitThirsty** [comment] 2017-06-14 17:19
That fixed it! Thanks.
