### ISSUE TITLE
Incorrect main editor`s window resize

### ISSUE THREAD

**Issue by IcticStep** [Scirra/Construct-3-bugs#3783] opened 2020-04-18 09:03 UTC
## Problem description
Incorrect main editor`s virtual window resize after Construct 3 real window resize. (sorry for my English, guys). Reproduces in any even empty project.

## Attach a .c3p
Empty project(not archive) for tests:
[empty.zip](https://github.com/Scirra/Construct-3-bugs/files/4496348/empty.zip)

## Steps to reproduce

1.Change windows size. 
2.Change main editors virtual windows size.
3.See the bug.

Video of reproducing:
[bandicam 2020-04-18 11-40-11-630.zip](https://github.com/Scirra/Construct-3-bugs/files/4496353/bandicam.2020-04-18.11-40-11-630.zip)

## Observed result

Resizing only main window without affecting any other pannels.
## Expected result
Normal resizing all pannels close to the main window, as usual.

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
Can`t say.
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.163
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
C3 release: r189.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 60 gb
Storage usage (approx): 345 mb (0.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2020-04-18 12:03
I've tried copying what you do in the video, and I can't reproduce this, it works fine. Can you provide more detailed steps? It's generally more helpful to have written steps than a video, because it's not always clear what's happening in a video.

Also is this specific to the dark theme or can you reproduce it in the default theme too?

**Comment by IcticStep** [comment] 2020-04-18 14:55
> I've tried copying what you do in the video, and I can't reproduce this, it works fine. Can you provide more detailed steps? It's generally more helpful to have written steps than a video, because it's not always clear what's happening in a video.
> 
> Also is this specific to the dark theme or can you reproduce it in the default theme too?

Oh.... I have just tried to reproduce it by myself again, but now I can`t. It`s fantastic, but after changing theme I can`t reproduce this bug, but I had it for few times few days ago. I am very active user of Construct 3, so I`ll add all possible information as soon, as it would happen again to me.

**Comment by AshleyScirra** [comment] 2020-04-20 10:52
OK, in the mean time there is nothing we can do about this issue, so closing it. We'll reopen and continue investigating if you can find a reliable way to reproduce it.

**Closed by AshleyScirra** 2020-04-20 10:52 UTC
Labels: can't reproduce

**Comment by IcticStep** [comment] 2020-04-20 10:53
OK, thanks.
