### ISSUE TITLE
On resolution changed trigger

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#4906] opened 2021-06-20 15:49 UTC
## Problem description
Drawing Canvas, "On Resolution Changed" is being triggered constantly.

The trigger is being tripped even tough no changes are happening after the initial change.
## Attach a .c3p
https://www.dropbox.com/s/8xx61gu2iupp23f/dcrezchange.c3p?dl=1

## Steps to reproduce

1.Preview the project
2.Click the button object to change the layout resolution
3.Note the Drawing Canvas

## Observed result
The Drawing Canvas is constantly changing it's angle because the trigger is running.

## Expected result
On resolution change should only happen when relevant, and when there is an actual change.

## More details

**Affected browsers/platforms:** 
Chrome W10

**First affected release:** 

## System details
251.2

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2021-06-21 08:28
Duplicate of #4008

**Closed by AshleyScirra** 2021-06-21 08:28 UTC
Labels: duplicate
