### ISSUE TITLE
Accessing Expressions Dictionary causes crash.

### ISSUE THREAD

**Issue by onzephyr** [Scirra/Construct-3-bugs#2357] opened 2018-11-21 17:06 UTC
## Problem description

Accessing Expressions Dictionary /System  causes crash.

## Attach a .c3p
[bugreport.zip](https://github.com/Scirra/Construct-3-bugs/files/2605131/bugreport.zip)

## Steps to reproduce

1. on event Browser on resize add action : 9patch set width
2. in popup click find expressions 
3. click on system or Browser
4.   Construct 3 crashes with error report

## Observed result

Construct 3 crashes with error report

## Expected result

access to expressions menu

## Affected browsers

* Chrome: yes
* Firefox: yes/no -not tested
* Edge: yes/no -not tested
* Safari: yes/no -not tested

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r126/main.js, line 81, col 166338
Message: Uncaught Error: instance variables not supported
Stack: Error: instance variables not supported at r.ǃgJ (https://editor.construct.net/r126/main.js:81:166344) at ǃgJ.next () at Object.ǃoin (https://editor.construct.net/r126/main.js:177:55671) at Object.ǃD$ (https://editor.construct.net/r126/main.js:177:59337) at Array. (https://editor.construct.net/r126/main.js:177:51909) at Object.ǃrYT (https://editor.construct.net/r126/main.js:2:204643) at Object.dispatchEvent (https://editor.construct.net/r126/main.js:2:202682) at Object.ǃqqg (https://editor.construct.net/r126/main.js:2:464879) at HTMLElement. (https://editor.construct.net/r126/main.js:2:468820) at HTMLDocument. (https://editor.construct.net/r126/main.js:2:199416)
Construct 3 version: r126
URL: https://editor.construct.net/r126/index.html
Date: Wed Nov 21 2018 10:01:22 GMT-0700 (Mountain Standard Time)
Uptime: 252.3 s

Platform information
Browser: Chrome
Browser version: 70.0.3538.102
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
C3 release: r126 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment] 2018-11-21 17:11
Duplicate of #2351

**Comment by AshleyScirra** [comment] 2018-11-22 10:44
Closing, let's not keep duplicates open.

**Closed by AshleyScirra** 2018-11-22 10:44 UTC
Labels: duplicate
