### ISSUE TITLE
Timeline can't find world instance, when you delete the instance and save project as a folder

### ISSUE THREAD

**Issue by nerdError** [Scirra/Construct-3-bugs#4824] opened 2021-05-13 22:36 UTC
## What happens
If you will remove an object instance from the layout, which is selected in some timeline, and then save the project as a folder, project will become broken

## C3 project (saved as a folder)
[c3 timeline worldinstance bug.zip](https://github.com/Scirra/Construct-3-bugs/files/6475357/c3.timeline.worldinstance.bug.zip)

## Steps to reproduce

1. Delete "Sprite" instance from layout
2. Save the project
3. Try to open the project again

## Observed result

You can't open the project, because timeline can't find the object it's connected to, so error happens (see screenshot below)

## Expected result

The project should open, and timeline should simply indicate that the object used in the timeline is not on the layout

**Affected browsers/platforms:** Chrome

**First affected release:** it happens in r241, but im almost sure this error happened to me much releases ago 

## System details

In debug console you will see this kind of error: 
![image](https://user-images.githubusercontent.com/55310192/118195595-2b33ce00-b454-11eb-9e19-f104607959a3.png)

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 90.0.4430.93
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
C3 release: r241 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 89 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GT 1030 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6089)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2021-05-14 12:06
Can't reproduce this one, following those steps everything seems to work properly in both the latest stable and the latest beta.

**Comment by nerdError** [comment] 2021-05-14 14:06
I still can reproduce it every time i try. I mean, i removed all addons, disabled all chrome extensions (chrome version is 90.0.4430.212) and the problem is still there and still constant

I made a [youtube video](https://www.youtube.com/watch?v=bkYInYarwcM), probably it can help. Because i don't know what else can cause this problem. It's just clear C3 in clear Chrome

**Comment by DiegoScirra** [comment] 2021-05-14 18:22
I see, I was something different. I'll give it another go and see if I can reproduce it.

**Comment by DiegoScirra** [comment] 2021-05-19 10:57
Can reproduce it now, should be an easy fix. There must be a difference between saving to project folder and saving to a .c3p file.

**Comment by nerdError** [comment] 2021-05-19 12:49
Good! Hope that fix will come out soon, because it's pretty unpleasant bug, especially because you don't see it until you open a project again. Fortunately, this problem can be solved by manually correcting the project files right now.

**Comment by DiegoScirra** [comment] 2021-05-19 14:42
This is fixed now, will be available in the next beta.

**Closed by DiegoScirra** 2021-05-19 14:42 UTC
