### ISSUE TITLE
layout upside down when using specific effects

### ISSUE THREAD

**Issue by rogerty** [Scirra/Construct-3-bugs#3413] opened 2019-10-13 20:04 UTC
## Problem description

The layout gets turned upside down when using the following layout effects:
- Line Height
- AdjustHSL
Plus when every tick a text is displayed in a text field.
Plus when fullscreen scaling is set to low quality.

## Attach a .c3p

[upsidedownbug.zip](https://github.com/Scirra/Construct-3-bugs/files/3722385/upsidedownbug.zip)

## Steps to reproduce

1. Start the project which I have uploaded to this bug report.
2. Wait 1 second.
3. See how the screen got changed to upside down.

## Observed result

The layout is upside down.

## Expected result

The layout not upside down.

## More details

I have tested the project on a Windows 10 laptop.
Chrome version: Versie 77.0.3865.90.
C3 version: 170.2 beta

**Affected browsers/platforms:** 

**First affected release:** 

I am using this effect since a short time, so I have no idea if this worked or did not work properly in previous versions of C3 or Chrome.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 77.0.3865.120
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
C3 release: r170.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 2.6 gb
Storage usage (approx): 269 mb (10.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by rogerty** [comment] 2019-10-14 07:01
The attachment is a c3p file renamed to zip.

**Comment by AshleyScirra** [comment] 2019-10-14 10:02
Duplicate of #2121

**Closed by AshleyScirra** 2019-10-14 10:02 UTC
Labels: duplicate
