### ISSUE TITLE
physics behavior/ minified script android export

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#1160] opened 2018-01-10 09:22 UTC
## Problem description

If I use the physics behavior and export it with the minified script option as a debug.apk for android, it results just in a black screen. Without minified script it works.
[debug_doggyrun_78_reduced.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1618154/debug_doggyrun_78_reduced.c3p.zip)

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.export the attached file with minified script option as a debug apk
2.test it on a device
3.

## Observed result

black screen

## Expected result

screen with a BG and a square appears

## Affected browsers

happens on OSX 10.13.2 on
Firefox: yes
Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 11.0.2
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_2
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7
C3 release: r76.2
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
Service Workers are not supported. Construct 3 cannot be used offline in this browser.
The <dialog> element is not supported. A polyfill is in use.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0 (2.1 INTEL-10.30.12)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel(R) HD Graphics 630
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions:

EXT_blend_minmax
EXT_sRGB
EXT_frag_depth
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBGL_compressed_texture_s3tc
WEBGL_depth_texture
WEBGL_draw_buffers
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by joelmayer87** [comment] 2018-01-10 12:04
I think this is a known issue, but would be neat to see it fixed sometime, so minify script will work again with the physics behaviour...

**Comment by shortercode** [comment] 2018-01-10 12:15
I think I reviewed this before and decided that the box2d.js library doesn't like being minified, it's an awkward file to work with. The parts of it that can be minified are already minified and the core of the library uses a strict subset of JS called asm.js that cannot be minified correctly by any library I'm aware of. There's a chance moving to webassembly for box2D would help solve the issue, but would reduce browser support.

**Comment by shortercode** [comment] 2018-01-10 12:19
Closing as duplicate of #560

**Closed by shortercode** 2018-01-10 12:19 UTC
Labels: duplicate

**Comment by joelmayer87** [comment] 2018-01-10 12:42
I understand, but may i suggest you'd be informing about this on either the export page under the minify script setting or at least in the documentation, or you'll be getting the same bug report over and over again. Alternatively maybe just lose the minify script option altogether, until this issue is fixed...

**Comment by bubbblebub** [comment] 2018-01-10 13:03
Thanks for the information.
Yes it would be nice to have some kind of warning, or to make the minified script option not available as soon there is physics inside the project. I spend quite some time to find where the problem is by excluding one thing after another, each time export it and test it on the phone..
