### ISSUE TITLE
Toggle 'Or' block using "Y" key doesn't work

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#230] opened 2017-05-17 11:46 UTC
## Problem description
Even though "Y" Key doesn't toggle an event block between 'OR' and 'AND', it registers itself as an action to the undo/redo history.

## Steps to reproduce

1. Select a block of events.
2. Press "Y" key to toggle 'Or' block.

## Observed result
The "Y" key doesn't work but the undo/redo history states it has taken that action.

## Expected result

"Y" key to work.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment] 2017-05-17 11:50
Looks like yet another duplicate of #118, should be fixed in r28 which we just released.

Please always include the system info since this helps clarify which version you're on, if this still happened on r28 it would probably be a new issue but I can only assume you're still on r27.

**Closed by AshleyScirra** 2017-05-17 11:50 UTC

**Comment by jaydonteh** [comment] 2017-05-17 11:52
Posted this before r28, it is now fixed on r28!
