### ISSUE TITLE
Open local folder menu is .. gone ?

### ISSUE THREAD

**Issue by Rikette** [Scirra/Construct-3-bugs#4189] opened 2020-09-07 16:27 UTC
## Problem description

Starting today, I can't open my local project folder in Construct 3 in any browser, which I did for the past month or so. The option is just simply gone. My recent projects list also got reset, so I thought the "use experimental features" option got reset as well, but it is still checked.

## Attach a .c3p

No .c3p required

## Steps to reproduce

1. Open construct 3

## Observed result

No "Open local folder" option in the Menu.
![image](https://user-images.githubusercontent.com/7189050/92405854-d73f4f80-f136-11ea-9976-a0c0dd17036f.png)
![image](https://user-images.githubusercontent.com/7189050/92405960-153c7380-f137-11ea-83c0-a37451a9494d.png)

## Expected result

Having the "Open local folder" Menu.

## More details

**Affected browsers/platforms:** Chrome, Edge (chrome), Firefox (windows, latest versions). Also tried on Chrome Mac, same issue.

**First affected release:** Worked in 210.2, broke in 210.2

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 85.0.4183.83
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
C3 release: r210.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 66 gb
Storage usage (approx): 377 mb (0.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Rikette** [comment] 2020-09-07 17:10
I tried to use the beta branch, and the menu is back for the r214. Went back to the r210, menu is gone.

**Comment by LetTheMiceFree** [comment] 2020-09-07 20:03
I have the same problem!

**Comment by AshleyScirra** [comment] 2020-09-08 10:47
Duplicate of #4188. See [this comment](https://github.com/Scirra/Construct-3-bugs/issues/4188#issuecomment-688289432).

**Closed by AshleyScirra** 2020-09-08 10:47 UTC
Labels: duplicate
