### ISSUE TITLE
Suggested "Recent" values for string instance variables and text are not relevant

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#4882] opened 2021-06-10 07:07 UTC
## Problem description

Sorry for the confusing title, I'm talking about this list which drops down when you click string instance variables or Text property of Text object:

![image](https://user-images.githubusercontent.com/36763350/121478312-3c004100-ca0c-11eb-9cf1-3f42239f24a9.png)

## Observed result

99.9% of the time these values are not relevant not only to this instance variable or object, but even to this project. I don't have any idea why it's suggesting me "Verdana" or "9patch 9patch", I don't remember ever typing these.

For every field this list of suggestions is different, but it's always some random garbage which obstructs the view and makes editing more difficult.

![image](https://user-images.githubusercontent.com/36763350/121479989-f0e72d80-ca0d-11eb-9226-07a913da912b.png)

This "island_5_5" value is from another project, I should not see it here.

## Expected result

The list of suggested values should only contain previously typed values from this particular variable in the current project. 
If this not possible, then this feature should be disabled.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 91.0.4472.101
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36
C3 release: r251 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 127 gb
Storage usage (approx): 293 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8681)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_draw_instanced_base_vertex_base_instance
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_multi_draw_instanced_base_vertex_base_instance
WEBGL_video_texture
WEBGL_webcodecs_video_frame
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment] 2021-06-15 10:59
No project was provided. I can't reproduce this in Ghost Shooter, so closing.

Besides, those look like autocomplete prompts created by the browser, not Construct, so it's probably beyond our control anyway. Maybe browser settings or browser extensions have something to do with it.

**Closed by AshleyScirra** 2021-06-15 10:59 UTC
Labels: can't reproduce, external

**Comment by dop2000** [comment] 2021-06-15 11:05
@AshleyScirra There is no point in providing the project, because these suggestions are not saved in the project. 
If they are created by the browser, can you disable autofill/autocomplete for these fields in the editor? 
Something like 
`<input type="text" id="cc" name="cc" autocomplete="off">`

**Comment by AshleyScirra** [comment] 2021-06-15 11:09
I can't reproduce any such autocomplete prompts, so I can't test if that works or not. Browsers are also notorious for ignoring autocomplete="off" anyway.

**Comment by dop2000** [comment] 2021-06-15 11:14
I tested it just now and autocomplete="off" works in Chrome. There is no dropdown list with suggestions.

![image](https://user-images.githubusercontent.com/36763350/122043448-af47ef80-ce1e-11eb-9483-98612a43e789.png)

**Comment by AshleyScirra** [comment] 2021-06-15 11:16
I won't make code changes if I can't test the result. I don't see any autocomplete suggestions, and it's not clear why you do. This is what needs to be established first, which is why I first asked about browser settings or extensions.

**Comment by dop2000** [comment] 2021-06-15 11:27
Could you check on other PCs, or browsers? The fact that you can't reproduce this doesn't mean that there is no problem..
Obviously, not everything I type into these fields is saved for autocompletion, otherwise the list will be thousands of items long. I don't understand how the browser picks what to show me in this suggestion list, but it's definitely not useful.

**Comment by dop2000** [comment] 2021-06-15 11:37
I think I found the browser setting which is causing it:
![image](https://user-images.githubusercontent.com/36763350/122045943-a4428e80-ce21-11eb-8287-8c3d49622928.png)

Thanks for pointing me in the right direction. Still it would probably be best to disable autocomplete by default for all such fields.

**Comment by AshleyScirra** [comment] 2021-06-15 11:46
I have the same setting enabled, so it doesn't seem to be solely down to that.

**Comment by dop2000** [comment] 2021-06-15 11:55
Maybe try entering some texts formatted as addresses - with leading numbers, commas etc. 
Like I said, I don't know how Chrome decides when and what to show me in this list. But disabling "Addresses and more" seems to fix it.

**Comment by AshleyScirra** [comment] 2021-06-16 11:36
For some reason this just started reproducing for me today. `autocomplete="off"` was missing only from certain property types - others did have it already. I added the missing attribute and so it should be fixed in the next beta.

**Comment by dop2000** [comment] 2021-06-16 11:37
Awesome, thank you!
