### ISSUE TITLE
iOS Native keyboard resizes whole layout.

### ISSUE THREAD

**Issue by andygilbert** [Scirra/Construct-3-bugs#2442] opened 2018-12-12 14:02 UTC
## Problem description

iOS Build - Native keyboard resizes the whole layout when focused on an input box.

## Attach a .c3p

[keyboardIssue.zip](https://github.com/Scirra/Construct-3-bugs/files/2672131/keyboardIssue.zip)

## Steps to reproduce

1. Compile the attched example to iOS Xcode (with any of the fullscreen modes selected)
2. Run in simulator or on device 
3. Click inside the input box.

## Observed result

keyboard appears but squashes the whole layout.

## Expected result

Have the option for the keyboard to overlap.

## First affected release

R120 to R131

## Affected browsers/platforms

* iOS: yes

Tested Device: Iphone XR (iOS 12)

## Suggestions

I belive there are a few cordova plugins which gives control of this, one of them below.

https://www.npmjs.com/package/cordova-plugin-keyboard

**Comment by andygilbert** [comment] 2019-02-07 15:15
Hi, any updates with this? This really is preventing any use of input boxes on iOS. I have quite a few apps on hold due to this.
Thanks

**Comment by sotano42** [comment] 2019-03-13 20:51
Hi, this issue still persist on r141.2 and affects Android phones too. I really can't publish a game using Input fields while this problem persist. @AshleyScirra have you guys taken a look at it? I was about to raise the same issue for android but then I found this thread. It fails with all type of input fields, here's a screenshot of the problem taken directly from an Android phone. It's been a while since this post came up and the issue still exist.

![image](https://user-images.githubusercontent.com/10860045/54313569-44ecd880-459f-11e9-8e42-d0557627584e.png)

**Comment by AshleyScirra** [comment] 2020-01-28 15:58
Looks like this was fixed on iOS 13. The keyboard now correctly handles the viewport by shifting the view up instead of resizing it in both Safari and an app.

Android does resizing, but it's difficult to do anything about this - it treats showing the keyboard as resizing the remaining view, rather than overlaying the keyboard on iOS. I'm not sure it's possible to work around it, it would need to be fixed by Google. It looks like this issue may cover it so you could star that to follow updates: crbug.com/404315

**Closed by AshleyScirra** 2020-01-28 15:58 UTC
Labels: external, iOS

**Comment by sotano42** [comment] 2020-01-28 16:03
I saw this corrected some months ago. I can confirm is working now.
