### ISSUE TITLE
Fullscreen mode off incorrect in C2

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1742] opened 2018-06-27 10:38 UTC
## Problem description

When fullscreen mode if set OFF in c2 runtime layout display is not correct.

## Attach a .c3p

[FullScreenOFF.zip](https://github.com/Scirra/Construct-3-bugs/files/2140822/FullScreenOFF.zip)

## Steps to reproduce

1.Preview example in C3 runtime
2.Preview example in C2 runtime
3.See that C2 has it wrong

## Observed result

When fullscreen mode it set off, c2 crops/scales black edges wrong

## Expected result

C2 should do it like C3

## Affected browsers

* Chrome: yes
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r107.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 929 mb (6.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2018-06-27 11:47
I can reproduce, but it looks like the problem is the preview window is too small. If you resize it larger you can see it correctly. This affects both runtimes and only occurs when the system devicePixelRatio is not 1. I've fixed this for the next build, but it doesn't match up entirely with what you reported (specific to C2 runtime & devicePixelRatio appears to be 1), so let's check it again when it's out and see if it's fixed.

**Comment by AshleyScirra** [comment] 2018-07-02 13:02
r108 is out now, please check again!

**Comment by SnipG** [comment] 2018-07-02 13:37
https://imgur.com/mpTRVwm  c2 runtime still has it cut from sides. I try changing resolution and some other things, to see if it changes.

**Comment by SnipG** [comment] 2018-07-02 13:50
I tried changing windows resolution, editor viewport size - nothing. But now i updated to latest chrome canarly and there i can see sprite edges on C2, but its bugged there i think.
Images: C2runtime and C3runtime
[C2runtime.zip](https://github.com/Scirra/Construct-3-bugs/files/2155469/C2runtime.zip)

**Comment by SnipG** [comment] 2018-07-03 14:35
Just adding more stuff here, which can help. 
Having viewport 600,600. I run c2 and c3 and then go chrome inspect and can see canvas sizes are different..
Pictures of thous inspects:
[C3CanvasInspect.zip](https://github.com/Scirra/Construct-3-bugs/files/2159766/C3CanvasInspect.zip)

Another thing, like i had with chrome canarly where c2 runtime had no black borders. I can reproduce it in ordinary chrome:
1.Open example
2.Switch C3runtime, click preview, then instantly when preview window opens click F11. All seems correct even with multiple attempts.
3.Switch C2runtime, click preview, then instantly when preview window opens click F11. Black borders dont appear, might need few tries.

**Comment by AshleyScirra** [comment] 2018-07-03 16:28
I've reverted the fix we made for this in r108 because it opens the wrong preview window size on high-DPI displays.

All I can reproduce here is the wrong preview window size; once you resize it larger, it appears correct (both the C2 and C3 runtimes show the green border around the edge of the sprite). The screenshots you attached to [this comment](https://github.com/Scirra/Construct-3-bugs/issues/1742#issuecomment-401811088) appear to show everything working fine, too - what do you think is wrong with them? [This screenshot](https://imgur.com/mpTRVwm) does appear to show a problem, but I can't reproduce that, I think I need more information and system details to be able to reproduce that myself.

**Comment by SnipG** [comment] 2018-07-03 17:00
The comment where everything seems to be fine, is where C2 does not crop window at all.And i can reproduce it with steps in my previous comment. that why c2 has window white instead black.

**Comment by SnipG** [comment] 2018-07-03 17:52
Something to add, pre fix stable 104, or after fix when i open C3 from browser all is good. The origin bug only happens/happened when i open C3 from desktop as independent app.

**Comment by SnipG** [comment] 2018-07-04 14:36
PS. Reverting that fix won't fix the  preview window size bug, that i had linked in that picture. I tried out Stable 104 now, and it still has wrong preview canvas sizes, it should be the pre fix release.
This thing happens when you open up C3 from browser. ->More tools -> create shortcut -> Tick Open was window.  So when you click C3 link in desktop it open was new window, without chrome tabs etc.
It can seems like chrome own issue :(

**Comment by AshleyScirra** [comment] 2018-08-22 17:08
I can't reproduce any difference between the C2 and C3 runtimes. The popup window opening code is identical (same code used regardless of runtime) so I can't think how the window size would end up being different depending on the runtime.

I can only reproduce a slight mis-sizing when Chrome's devicePixelRatio is not 1 (i.e. browser zoom or display scale is not 100%). It also works correctly in Edge regardless of the devicePixelRatio, so I believe this is a Chrome issue, and it looks a lot like this one: https://bugs.chromium.org/p/chromium/issues/detail?id=677381
Closing as a Chrome issue and will follow up at that report.

**Closed by AshleyScirra** 2018-08-22 17:08 UTC
Labels: external
