### ISSUE TITLE
Physics Behavior Ignoring Solids

### ISSUE THREAD

**Issue by Bigbeto123** [Scirra/Construct-3-bugs#3756] opened 2020-04-09 20:45 UTC
Whenever you apply a certain high amount of impulse to an object against another solid, it'll simply ignore the solid and go past through it, which as far as I know, isn't physically possible in 2d.
Now seriously though, this bug should have been fixed looong ago for the said "Physics" engine.
By the way, if you give the tilemap (of obstacles) the physics behavior, to try to workaround the issue, the whole tilemap area itself WILL become solid, instead of just the tiles (what rightfully happens by giving it the solid behavior).

## Attach a .c3p
[bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4458540/bug.zip)

## Steps to reproduce

1.Create 2 objects; one with physics behavior (and solid as well if you want), and another one with the solids behavior.
2. Apply a high amount of impulse (eg. 355) to the first object to the direction of the solid
3. Watch the 2d physics engine completely loose its mind

What should not happen in any kind of circumstances

It should simply stop at the solid

Small file created specifically for the demonstration.

**Affected browsers/platforms:** 

**First affected release:** 
r194

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.163
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
C3 release: r194 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 432 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Bigbeto123** [comment] 2020-04-09 23:01
About the tilemap-physics interaction, it's EXACTLY this very same bug
https://www.construct.net/en/forum/construct-2/how-do-i-18/tilemap-physics-problem-70904

**Comment by dop2000** [comment] 2020-04-10 07:32
Please read the documentation:

> Another consequence is Physics won't respond to objects with the Solid or Jumpthru behaviors. These behaviors are totally redundant when using Physics and have no effect. Instead, use the Immovable property.

Physics object is not supposed to be stopped by solids. Physics it not compatible with other behaviors like Solid, Pin, 8direction, Platform, MoveTo etc. You should avoid using them together, otherwise you'll have all kinds of nasty bugs.

**Comment by AshleyScirra** [comment] 2020-04-10 11:42
@dop2000 is right, closing as not a bug. The Physics and 8 Direction behaviors will conflict. Physics ignores the Solid behavior, and so can move inside it. 8 Direction is not allowed to move inside solids, so will move the object outside a solid. The result won't make any sense.

**Closed by AshleyScirra** 2020-04-10 11:43 UTC
Labels: not a bug

**Comment by Bigbeto123** [comment] 2020-04-10 18:14
Alright, but what about the tilemap physics bug?

**Comment by dop2000** [comment] 2020-04-11 03:48
@Bigbeto123 what tilemap physics bug? If you set tilemap as immovable (and don't use any other behaviors but Physics), other physics objects will collide with the tilemap correctly.
https://www.dropbox.com/s/i02tisr7lhffr5d/TilemapPhysics.c3p?dl=0

**Comment by Bigbeto123** [comment] 2020-04-11 21:45
Didn't happen like that in my project. 
Opened a new Issue about it, by the way.
