### ISSUE TITLE
Black on black in Dark theme

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#635] opened 2017-07-19 21:58 UTC
## Problem description
If you rename an animation in Animations editor, the text is black on dark.

## Steps to reproduce

1. Dark theme
2. Rename an animation in animations editor

## Observed result

When you write, the text is black on dark.

## Expected result

White text

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment] 2017-07-20 13:24
Duplicate of #631 / #591

**Closed by AshleyScirra** 2017-07-20 13:24 UTC
Labels: duplicate, theme
