### ISSUE TITLE
DARKENED SCREEN IN CONSTRUCT 3 RUNTIME PREVIEW

### ISSUE THREAD

**Issue by Sofa-King-Happy** [Scirra/Construct-3-bugs#2267] opened 2018-11-07 05:28 UTC
## Problem description

My runtime preview darkens the entire viewport. If I switch to C2 is fixes the problem, but I would like to migrate to C3. I have tried the latest release and I have checked the UI layers transparent setting.

## Attach a .c3p

Will attach a minimal version of my c3p for investigation purposes:
https://drive.google.com/open?id=1-JOTjr2D3gBbZuFKcyVSuU3izFN4R9XX

## Observed result

In the c2 preview the screen is normal, but in c3 the screen is darkened.

## Expected result

That c2 and c3 runtime previews would show the same results.

## Affected browsers

* Chrome: yes

Thanks everyone!

**Comment by AmateurX-14** [comment] 2018-11-07 08:46
It may be downloading some cache files. Usually it is a network problem, and sometimes I also encountered the problem.

**Comment by AshleyScirra** [comment] 2018-11-07 11:08
Can't reproduce in r124. Assuming you're testing with r120, closing as already fixed. Please always follow the bug report guidelines and include all the required information so we don't have to guess things like what version you're using.

**Closed by AshleyScirra** 2018-11-07 11:08 UTC
Labels: can't reproduce
