### ISSUE TITLE
Dynamic Object Creation Exception - Create by name - Stable v197

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-3-bugs#3812] opened 2020-04-28 07:08 UTC
## Problem description

Whenever I try to create an object using Create By Name system plugin, an exception is thrown. This error is causing that all of my projects that reutilize a set of routines for dynamic dialogs fail. I stripped down the project the more I could to leave it at the minimum possible.

## Attach a .c3p

[DynamicObjectError.zip](https://github.com/Scirra/Construct-3-bugs/files/4543890/DynamicObjectError.zip)

## Steps to reproduce

1.Open the project attached and run it
2. The project will try to dynamically create a frame using Create by name
3. Open the debug view of the browser while running the project and the exception will be thrown

## More details
This happened on Chrome: Version 81.0.4044.122 (Official Build) (64-bit)
Windows System 

**First affected release:** 
Failed on r197 stable

## System details

<details><summary>View details</summary>

  | _AddPendingTextureLoadPromise | @ | layout.js:1
-- | -- | -- | --
  | MaybeLoadTexturesFor | @ | layout.js:1
  | CreateInstanceFromData | @ | runtime.js:1
  | CreateInstance | @ | runtime.js:1
  | CreateObject | @ | actions.js:1
  | CreateObjectByName | @ | actions.js:1
  | _RunSystem | @ | action.js:1
  | _RunActions_Fast | @ | eventBlock.js:1
  | _RunAndBlock | @ | eventBlock.js:1
  | Run | @ | eventBlock.js:1
  | _RunSubEvents_SolWriterAfterCnds | @ | eventBlock.js:1
  | _RunSubEvents | @ | eventBlock.js:1
  | _RunAndBlock | @ | eventBlock.js:1
  | RunAsExpressionFunctionCall | @ | eventBlock.js:1
  | (anonymous) | @ | expFuncs.js?id=204w70isk6j:237
  | GetExpression | @ | parameter.js:1
  | Run | @ | action.js:1
  | _RunActions_Fast | @ | eventBlock.js:1
  | _RunAndBlock | @ | eventBlock.js:1
  | Run | @ | eventBlock.js:1
  | _RunSubEvents_SolWriterAfterCnds | @ | eventBlock.js:1
  | _RunSubEvents | @ | eventBlock.js:1
  | _RunAndBlock | @ | eventBlock.js:1
  | Run | @ | eventBlock.js:1
  | _RunSubEvents_SolWriterAfterCnds | @ | eventBlock.js:1
  | _RunSubEvents | @ | eventBlock.js:1
  | _RunAndBlock | @ | eventBlock.js:1
  | RunAsFunctionCall | @ | eventBlock.js:1
  | _RunActions_Fast | @ | eventBlock.js:1
  | _RunAndBlock | @ | eventBlock.js:1
  | Run | @ | eventBlock.js:1
  | _ExecuteTrigger | @ | eventSheet.js:1
  | _TriggerForClass | @ | eventSheet.js:1
  | _Trigger | @ | eventSheet.js:1
  | _Trigger | @ | eventSheetManager.js:1
  | Trigger | @ | runtime.js:1
  | TriggerAsync | @ | runtime.js:1
  | _StartRunning | @ | layout.js:1
  | async function (async) |   |  
  | _StartRunning | @ | layout.js:1
  | _DoChangeLayout | @ | runtime.js:1
  | async function (async) |   |  
  | _DoChangeLayout | @ | runtime.js:1
  | _MaybeChangeLayout | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1
  | requestAnimationFrame (async) |   |  
  | _RequestAnimationFrame | @ | runtime.js:1
  | Tick | @ | runtime.js:1
  | normal | @ | runtime.js:1

</details>

**Comment by AshleyScirra** [comment] 2020-04-28 13:40
I can't open the project because it uses third-party addons (Drop Hard Shadow and Gameboy). Our bug report guidelines ask that you remove third-party addons to avoid this and also to rule them out as the cause of any problems.

This looks very similar to #3809 so closing on the assumption it's a duplicate of that. Note I believe it should not have any detrimental effect on the running of the game.

**Closed by AshleyScirra** 2020-04-28 13:40 UTC

**Comment by sotano42** [comment] 2020-04-28 13:49
I'm sorry, I thought I removed the addons... I uploaded the new project code. Will follow up on the other issue. And yes, as I did more testing my games are not being hard stopped, is not affecting the rest. Thanks for the answer.

**Comment by AshleyScirra** [comment] 2020-04-28 14:07
Looking at the updated project, I can confirm this is a duplicate of #3809.
