### ISSUE TITLE
Slight display problem with the menu icons

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#706] opened 2017-08-11 07:05 UTC
## Problem description

When hovering the submenu icons of "project" or "view" under the menu button, the icons' placement is slightly flickering.

## Attach a .c3p

Not useful

## Steps to reproduce

1. Click the menu button
2. Hover over "Project" to make the submenu appear
3. Hover the cursor over the first icons.

## Observed result

The icons of a submenu which haven't been hovered yet are slightly moving.
If we close the submenu by clicking elsewhere, then reclick the menu button, the problematic behavior is still there.

## Expected result

The icons shouldn't be moving.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 60.0.3112.90
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
C3 release: r48

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 691 mb (4.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2017-08-29 14:00
Can't reproduce here. I've got a 64-bit Win10 machine with Chrome 60 as well, can't see anything wrong.

**Comment by shortercode** [comment] 2017-08-29 14:21
@AshleyScirra I can repeat it on my machine( 60.0.3112.101 ), it's been around awhile but I can't remember what version of chrome it appeared on. It appears to be fixed in canary. Here's a replication for reference though:

1. Open arbitrary project
2. Click main menu
3. Move mouse to project item
4. Move mouse to save item in sub menu
5. Repeat steps 2 & 3
6. Observe items in submenu below "save" move slightly left and right

Any items which have been hovered over lose this behaviour. If there's no project open then it will only shift once slightly to the right.

**Comment by AshleyScirra** [comment] 2017-08-29 17:51
Still can't reproduce anything wrong here. Are those steps correct? Repeating step 2 means the menu closes when you click the menu button again.

**Comment by shortercode** [comment] 2017-08-30 11:07
Sorry should say repeat steps 3 - 4, I revised the steps after I realised it behaved differently when no project was open

**Comment by AshleyScirra** [comment] 2017-09-01 15:48
I have actually seen this a couple of times. It might be related to device pixel ratio. Seems pretty minor though.

**Comment by AshleyScirra** [comment] 2018-01-17 11:36
I've put in an attempted fix for this in r79, but it's hard to reproduce so I'm not sure if it will be effective. Let's check back when it's out.

**Comment by shortercode** [comment] 2018-01-17 13:29
Well here's hoping, I'd like to see the back of the dancing icons...

**Comment by RabloGames** [comment] 2018-01-17 14:51
I checked this morning on r78 and the bug was still there. Now on r79 it seems to have vanished! Good job! :)

**Comment by AshleyScirra** [comment] 2018-01-17 16:24
That's promising! Let's leave it for a while to verify it doesn't happen for anyone else. If I don't hear back though I'll close it.

**Comment by AshleyScirra** [comment] 2018-01-22 13:39
No further reports in r79, so closing.

**Closed by AshleyScirra** 2018-01-22 13:39 UTC
