### ISSUE TITLE
Audio Bug - If switch Level and use "Every x Seconds"

### ISSUE THREAD

**Issue by Sanchopi** [Scirra/Construct-3-bugs#2375] opened 2018-11-27 19:33 UTC
## Problem description

I use the "Every x Seconds" event with "Audio Play" in my game levels ("Layout_Level_1").
If I start the game, first the main menu appears ("Layout_Start"). 

If I wait now 10 sec and click the button "PLAY", the audio which is defined in the level events will be played immediately, even though there should be a delay of x seconds ...

You can understand the issue better with the project fie, just see the comments.

## Attach a .c3p

[https://drive.google.com/open?id=1_WLCRUl_6Le59A5IS8z5CAb8AZPanZUb](https://drive.google.com/open?id=1_WLCRUl_6Le59A5IS8z5CAb8AZPanZUb)

## Steps to reproduce

1. Wait 10 sec and press the button "PLAY" (you will hear the same sound twice)
2. Restart
3. Press the button immediately (you will hear the sound once)

## Observed result

The "Every x Seconds" event loads the audio even though the related layout ("Layout_Level_1") is not active / loaded by now.

## Expected result

The "Every x Seconds" event should wait untill the related layout ("Layout_Level_1") is loaded and then start the "Every x Seconds" event. The audio should have in all cases a delay by at least 4 sec. 

## First affected release

All versions.

## Affected browsers/platforms

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment] 2018-11-28 12:30
I had a quick review of this. The "every N seconds" condition compares the current time against the last time it was triggered, or 0 if it hasn't been triggered. When the layout is switched, the event has never been triggered so it's comparing against 0. If you've waited at least 8 seconds before switching then your guaranteed to have exceeded your delay ( `random(4, 8)` seconds ), so it plays on the first tick of that layout.

If I'm honest I'm not sure if this is correct behaviour or not, I would have thought it would compare against the time the layout started.  As it seems to behave identically in the C2 runtime I'm guessing it's the expected behaviour, so I'm assigning to @AshleyScirra to review.

You can work around this by ensure that the condition fails on the first tick. An easy way of doing it in this example is to add a boolean that is initially false, then setting it after your 0.5 second wait. I've included an example.

Also I'm not sure what your button opacity code is about, you don't have any buttons in the second layout to modify. I removed it, I also placed a "world time" counter in the second layout.

[Audio Level Switch Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2624461/Audio.Level.Switch.Bug.zip)

**Comment by AshleyScirra** [comment] 2018-12-03 15:20
It's currently working as designed. This condition is so widely used that I think at this point changing how it works will cause significant backwards-compatibility problems, i.e. create more problems than it solves.

Right now the logic for "every X seconds" is essentially testing "has it been at least X seconds since this event ran". It also can run immediately, so if you have something like "is space pressed / every 1 second: shoot laser", then it can fire immediately when you press spacebar and it's been at least 1 second since you last fired. (If it didn't do that, then the first time you shoot would unnecessarily delay your first shot by 1 second, even if there was enough time for the shot to have been fully reloaded.) However to prevent it running on start of layout, which is rarely what you want, it implicitly acts as if it ran on start of layout, so will wait at least X seconds before the first time it runs. However that is a global timer.

The reason it uses a global timer is because event sheets are often shared across multiple layouts (e.g. using includes). If we changed the timer to use a per-layout timer, then switching layout will reset all "every X seconds" events, which in some cases will not be the intent. For example playing a sound every 10 seconds, and then switching to a different layout that still uses the same event sheet, currently works regularly - the sound intervals are kept 10 seconds apart even across the layout switch. With the proposed change this will then make the sound interval irregular, since switching layout will reset the timer. It's not clear to me that this is the ideal way for it to work, since in this case it's useful for it to work the way it currently does; additionally this is the backwards-compatibility risk I mentioned, since any games that currently rely on it working like that will be broken by changing it.

So I don't think there's any justification to change this. You should be able to work around it using events though.

**Closed by AshleyScirra** 2018-12-03 15:20 UTC
Labels: wontfix
