### ISSUE TITLE
Animation Editor unfocused / unresponsive 

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-3-bugs#5255] opened 2021-11-20 11:25 UTC
## Problem description
Animation Editor is unfocused and not responding after scaling an image.
## Attach a .c3p
Works in every c3p for me! Not project specific.

## Steps to reproduce

1. Create a Sprite
2. Assign a png texture to it 
3. Resize the sprite using the animation editor
4. Half of the time it is now frozen / unfocused and you need to focus another application and then construct again to get it working

## Observed result
The Animation editor is unresponsive after resizing an image

## Expected result
The Animation Editor works as expected 

## More details
Chromium (many versions) installed as an web app - issue is also there in firefox. 

The issue has always been there for me (started using construct a year ago.)

## System details

i7 8700, Rx 580, Windows 11, 144hz 1440p screen, newest construct version

**Comment by DiegoScirra** [comment] 2021-11-22 11:27
Looks like a duplicate of #5116

**Closed by DiegoScirra** 2021-11-22 11:27 UTC
Labels: duplicate
