### ISSUE TITLE
In Firefox, videos won't appear in preview or debug windows

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#5221] opened 2021-11-10 19:25 UTC
## Problem description

In Firefox, video objects will not appear or play in preview or debug windows.

## Attach a .c3p

[VideoNoPlay.zip](https://github.com/Scirra/Construct-3-bugs/files/7515340/VideoNoPlay.zip)

## Steps to reproduce

1. Open the attached Construct 3 project in Firefox or create a new project and import a video file and add a video object set to autoplay that file.
2. From the top bar, open the dropdown menu and select either 'preview layout' or 'debug layout' or press F4 or Shift + F4 to open a preview window.
3. Note that the video will not appear and begin playing.

## Observed result

No video in Firefox's preview or debug preview.

## Expected result

Video in Firefox's preview or debug preview.

## More details

Seems to be a Firefox-specific issue, as Chrome and Edge are both able to play videos in preview mode just fine. Note, videos in Firefox _do_ appear and play if you go through the steps to open a remote preview and run that in any browser, and an exported build from Firefox will also show video properly. It seems only preview and debug windows won't display video for Firefox.

Here's a clip of the attached project running in Firefox...

https://user-images.githubusercontent.com/4585257/141179307-db6c3c22-44ef-4b3d-9b76-70cd87cb5a7f.mp4

And here's a clip of the exact same project running in Chrome, where its video object works.

https://user-images.githubusercontent.com/4585257/141179447-0710e202-6740-4f85-88b8-aa346f82b11c.mp4

**Affected browsers/platforms:** Firefox

**First affected release:** First occurred no later than r268.

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 94.0
Browser engine: Gecko
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0
C3 release: r268 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 456 mb
Storage usage (approx): 468 kb (0.1%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel(R) HD Graphics 400 Direct3D11 vs_5_0 ps_5_0, D3D11-23.20.16.4973)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2021-11-22 16:43
This looks like a duplicate of #4270. As noted then I'm afraid this looks like a complicated Firefox bug that would be difficult even to report to Mozilla. AFAIK it works after export so should not affect published games. I would advise to just use a different browser to work around this as I think it will be difficult to do anything about this.

**Closed by AshleyScirra** 2021-11-22 16:43 UTC
Labels: duplicate
