### ISSUE TITLE
GamePad only works in Debug Preview, not Preview Layout or Preview Project

### ISSUE THREAD

**Issue by Laughing14** [Scirra/Construct-3-bugs#548] opened 2017-06-23 03:46 UTC
## Problem description
*Enter a concise description of your problem here*
GamePad only works in Debug Preview, not Preview Layout or Preview Project

## Attach a .c3p
*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
https://drive.google.com/file/d/0B52mOFbdMZVRVFViM1hLbV9GejA/view?usp=sharing
or
[gamepad test.zip](https://github.com/Scirra/Construct-3-bugs/files/1096707/gamepad.test.zip)

## Steps to reproduce
1. Open project, with Xbox gamepad attached to your PC
2. Click Debug. Press buttons. Text should change based on what you press.
3. Run project by preview layout or preview project, press buttons, text will not change.

## Observed result
*What do you see happen?*
When using Debug, project responds to gamepad buttons
When using Preview layout or preview project, project does not respond to gamepad buttons

## Expected result
*What did you expect to happen instead?*
Expect that project would respond to gamepad buttons regardless of debug or preview method

## Affected browsers
* Chrome: yes

(do not use these browsers)
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details
*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r40

Local storage
Storage quota (approx): 60 gb
Storage usage (approx): 222 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 5500 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment] 2017-06-23 10:15
Duplicate of #64. It's a Chrome bug.

**Closed by AshleyScirra** 2017-06-23 10:15 UTC
