### ISSUE TITLE
Cannot load or save from cloud (android and PC latest version of google chrome)

### ISSUE THREAD

**Issue by drexegar** [Scirra/Construct-3-bugs#259] opened 2017-05-18 23:46 UTC
## Problem description

*When I try to load or save from cloud, no matter what service I put and log in, I always get a cannot refresh list error*

## Steps to reproduce

1. Start up program
2. Load from or Save to Cloud (It will still prompt you to log in)
3. You will get message "Cannot refresh list" even if you hit the refresh button on any service.

## Observed result

I get a cannot refresh list error, no matter what I do?

*What did you expect to happen instead?*

## See my list of files and be able to load my files or save them

* Chrome: yes/no
* Firefox: N/A
* Edge: N/A
* Safari: N/A
## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by zakaos** [comment] 2017-05-19 01:01
I am having same issue. Cannot retrieve files with google drive

**Comment by kondokuro** [comment] 2017-05-19 01:03
me 3

**Comment by zakaos** [comment] 2017-05-19 01:07
looks like this was earlier confirmed issue 249

**Comment by Digital-Prophet** [comment] 2017-05-19 07:54
Same here. MacOS.

**Comment by jakemay74** [comment] 2017-05-19 08:30
Also occurring on PC

**Comment by AshleyScirra** [comment] 2017-05-19 10:43
Should be fixed in r29.2.

**Closed by AshleyScirra** 2017-05-19 10:43 UTC
