### ISSUE TITLE
[r27] Pressing the "B" or "X" hotkeys insert multiple events

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#224] opened 2017-05-16 21:19 UTC
## Problem description

Hitting the "B" key in the event editor inserts two blank subevents, one nested below the other, instead of just a single subevent. (Also happens with "X" key for adding else blocks.)

## Attach a .c3p

[HotkeyBug.zip](https://github.com/Scirra/Construct-3-bugs/files/1005849/HotkeyBug.zip)

## Steps to reproduce

1. Create a new project
2. Add a new event to the default event sheet
3. With the event selected, hit the "b" key to insert a blank subevent (or "x" to create an else block)

## Observed result

Two blank subevents appear (or two else blocks), one nested below the other.

## Expected result

A single blank subevent should appear.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 24 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by donkeyspaceman** [comment] 2017-05-16 23:02
This happens when pressing "X" to create an "Else" subevent as well (two "Else" blocks appear).

**Comment by Scoremonger** [comment] 2017-05-16 23:30
Thanks @donkeyspaceman, I added that info to the body of the bug.

**Comment by jaydonteh** [comment] 2017-05-17 03:10
Duplicate of https://github.com/Scirra/Construct-3-bugs/issues/118

**Closed** 2017-05-17 10:20 UTC
Labels: duplicate
