### ISSUE TITLE
Files are created in lower case

### ISSUE THREAD

**Issue by UeliSo** [Scirra/Construct-3-bugs#654] opened 2017-08-01 17:10 UTC
## Problem description

When you create a new file (eg .txt) within C3, its file name is always in lower-case, even when you enter a upper-case filename. The reference is maintained in upper-case, which can lead to problems on case sensitive operating systems.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2017-08-02 10:10
This is by design, to prevent case-sensitive servers failing to find the files. Construct should automatically also lowercase the requested name to ensure the file is found. If it is not doing that, it's a bug, but there is nothing in this report to investigate so closing. Please always follow the bug report guidelines so we are able to help.

**Closed by AshleyScirra** 2017-08-02 10:10 UTC
Labels: ignored guidelines

**Comment by UeliSo** [comment] 2017-08-02 12:44
For detailed step-by-step following the guideline please see #534.

**Comment by AshleyScirra** [comment] 2017-08-02 12:48
Please file one report including all relevant information, it gets very confusing trying to cross-reference report information between separate reports about different things.

**Comment by UeliSo** [comment] 2017-08-02 12:56
I completed the information on the original bug report:
https://github.com/Scirra/Construct-3-bugs/issues/534
It’s all there now.
Hope that helps.
U’



De: Ashley (Scirra)<mailto:notifications@github.com>
Enviado:quarta-feira, 2 de agosto de 2017 09:48
Para: Scirra/Construct-3-bugs<mailto:Construct-3-bugs@noreply.github.com>
Cc:Ueli Sonderegger (5:PM)<mailto:ueli@5pmserious.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [Scirra/Construct-3-bugs] Files are created in lower case (#654)


Please file one report including all relevant information, it gets very confusing trying to cross-reference report information between separate reports about different things.

**Comment by AshleyScirra** [comment] 2017-08-02 13:00
Please, just file a new clean issue. The other issue is already closed, resolved not a bug, and is full of comments about itch.io.
