### ISSUE TITLE
Image editor

### ISSUE THREAD

**Issue by funbot-co-uk** [Scirra/Construct-3-bugs#6586] opened 2023-02-19 18:50 UTC
I was updating an image sequence that was attached to 1 face of a 3dshape which was fine. the second time I tried to use the editor it  would just hang with a spinner. The close button did nothing but the escape key would close the image editor.
I saved my game and restarted construct, now I get this message...
I am able to roll back so I will try that
I hope that helps

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'Fk') @ TypeError: Cannot read properties of undefined (reading 'Fk') at PEa (https://editor.construct.net/r330/projectResources.js:140:253) at SFa (https://editor.construct.net/r330/projectResources.js:175:182) at Sy.pW.ga (https://editor.construct.net/r330/projectResources.js:2109:131) at yx.g.K.Sb.R (https://editor.construct.net/r330/projectResources.js:1972:232) at https://editor.construct.net/r330/projectResources.js:134:334
Stack: TypeError: Cannot read properties of undefined (reading 'Fk') at PEa (https://editor.construct.net/r330/projectResources.js:140:253) at SFa (https://editor.construct.net/r330/projectResources.js:175:182) at Sy.pW.ga (https://editor.construct.net/r330/projectResources.js:2109:131) at yx.g.K.Sb.R (https://editor.construct.net/r330/projectResources.js:1972:232) at https://editor.construct.net/r330/projectResources.js:134:334
Construct version: r330
URL: https://editor.construct.net/r330/
Date: Sun Feb 19 2023 18:36:05 GMT+0000 (Greenwich Mean Time)
Uptime: 21.8 s

Platform information
Product: Construct 3 r330 (beta)
Browser: Chrome 110.0.5481.104
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) RX Vega 11 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

**Comment by WilsonPercival** [comment] 2023-02-19 18:55
Duplicate https://github.com/Scirra/Construct-3-bugs/issues/6578

**Comment by AshleyScirra** [comment] 2023-02-20 13:41
Closing as duplicate of #6578

**Closed by AshleyScirra** 2023-02-20 13:41 UTC
Labels: duplicate
