### ISSUE TITLE
Animation Editor Crash and Freeze

### ISSUE THREAD

**Issue by corlenbelspar** [Scirra/Construct-3-bugs#6332] opened 2022-12-13 21:02 UTC
## Problem description
Anytime there is a folder present in the animation editor, C3 will just freeze. Plus trying to play an animation leads to a crash. This makes the animation editor unusable.

## Attach a .c3p

[Foldersbug.zip](https://github.com/Scirra/Construct-3-bugs/files/10221993/Foldersbug.zip)

## Steps to reproduce
1. For the freeze issue, just open the sprite object and create a folder.
2. For the crash, try to preview the sprite's animation.

## Observed result
The animations editor's folders freeze C3 the moment they appear it's open.

## Expected result
Should be able to preview animations and use folders.

## More details
**Affected browsers/platforms:** Chrome

**First affected release:** r322

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r322/main.js, line 1025, col 73
Message: Uncaught TypeError: expected string
Stack: TypeError: expected string at O.l (https://editor.construct.net/r322/main.js:1025:79) at C_a.hPb.tva (https://editor.construct.net/r322/projectResources.js:1957:415) at https://editor.construct.net/r322/projectResources.js:256:404 at https://editor.construct.net/r322/main.js:1871:100
Construct version: r322
URL: https://editor.construct.net/r322/
Date: Tue Dec 13 2022 15:01:59 GMT-0600 (Central Standard Time)
Uptime: 32.3 s

Platform information
Product: Construct 3 r322 (beta)
Browser: Chrome 108.0.5359.99
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon RX 6500 XT Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by dop2000** [comment] 2022-12-14 04:53
Same problem in r322 - closing the Animation Editor for a sprite with multiple folders causes the editor to permanently freeze.

**Comment by corlenbelspar** [comment] 2022-12-14 05:13
Oh yeah that's the other issue I ran into but forgot about. I was trying to edit some of my sprite objects and it would just freeze if I tried to close the editor, but only if folders are present.

**Comment by dop2000** [comment] 2022-12-14 14:55
@DiegoScirra Unfortunately, no. It's random and only happens in my main project, I couldn't reproduce it in a smaller file, even if I copy/paste the sprite. So it may not be related to this ticket.

**Comment by DiegoScirra** [comment] 2022-12-14 15:31
I looked a little bit on the STATUS_ACCESS_VIOLATION error code, and it looks like it is thrown when Chrome tries to access memory it is not allowed to. Not surprisingly the first thing to look at are extensions, which might not be playing nice with whatever else the browser is doing.

I know we say this all the time, but if you have any extensions running along C3, try disabling them and see if there are any improvements. Might be difficult to tell if the problem is sporadic to begin with.

**Comment by dop2000** [comment] 2022-12-14 15:40
I don't think there are any installed extensions, but I'll double check, thanks!

**Comment by DiegoScirra** [comment] 2022-12-14 17:21
I'll close this issue, if there is any more information about any problems with resizing you can just open a new one.

**Closed by DiegoScirra** 2022-12-14 17:21 UTC

**Comment by corlenbelspar** [comment] 2022-12-14 21:46
C3 freezes on me if I just open and close the animation editor on a sprite with folders in its animations.

**Comment by corlenbelspar** [comment] 2022-12-14 22:06
I just tested it in Firefox and same issues.

Error report information

Type: unhandled exception
File: https://editor.construct.net/r322/projectResources.js, line 568, col 388
Message: TypeError: f.JQc is not a function
Stack: zd@https://editor.construct.net/r322/projectResources.js:568:388 ka@https://editor.construct.net/r322/projectResources.js:1959:42 Du@https://editor.construct.net/r322/projectResources.js:1947:491 wg@https://editor.construct.net/r322/main.js:1366:75 $ea@https://editor.construct.net/r322/main.js:275:361 T6@https://editor.construct.net/r322/main.js:1341:297 e@https://editor.construct.net/r322/main.js:269:236
Construct version: r322
URL: https://editor.construct.net/r322/
Date: Wed Dec 14 2022 16:06:30 GMT-0600 (Central Standard Time)
Uptime: 54 s
Platform information

Product: Construct 3 r322 (beta)
Browser: Firefox 108.0
Browser engine: Gecko
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by corlenbelspar** [comment] 2022-12-14 22:08
If I delete the folders before closing the anim editor, it doesn't have a problem.

**Comment by DiegoScirra** [comment] 2022-12-14 22:37
@corlenbelspar Those problems will be fixed for the next beta.

**Comment by corlenbelspar** [comment] 2022-12-14 23:09
Ah, that's cool. Thanks. Wasn't sure if the additional info would help or not.
