### ISSUE TITLE
exported apk not working

### ISSUE THREAD

**Issue by drg8** [Scirra/Construct-3-bugs#2493] opened 2019-01-07 19:01 UTC
## Problem description

debug/signed apk, generating apk with android studio nothing working.
only blank screen appears when app is launched and it is stuck there forever.

## Attach a .c3p

inbuilt templates can be used to test, as they also have the same issue. 

## Steps to reproduce

1.export apk and test it
2.
3.

## Observed result

black screen

## Expected result

app starts normally

## First affected release
beta r132

## Affected browsers/platforms

* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by BonzerKitten7** [comment] 2019-01-07 20:16
I just wanted to say that NWJS is also giving me a black screen.

**Comment by AshleyScirra** [comment] 2019-01-08 11:51
Are you exporting with "Minify" enabled? If so I suspect it's another case of #2492. Exporting without minifying may work in the mean time.

**Comment by drg8** [comment] 2019-01-08 12:44
for me I'm exporting with "minify" disabled, as having it enabled the projects doesn't even start export and fails at start. tried using vpn to see if something wrong with connection, but no success.

**Comment by sizcoz** [comment] 2019-01-08 12:48
I can confirm this as a thing.
I have tried to export 2 Android signed APK projects in C3 both get build failed, If I switch to C2 Runtime they export perfectly.
I have the console report below.
main.js:177 Stop!
main.js:177 This is a browser feature intended for developers. If someone told you to copy and paste something here to enable a feature or "hack" something, it is a scam and may allow them to steal your account information or your work.
main.js:177 Registered service worker on https://editor.construct.net/r132/
main.js:177 The specified value "NaN" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?
ǃqam @ main.js:177
main.js:177 The specified value "NaN" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?
ǃqam @ main.js:177
api.onedrive.com/v1.0/drive/root:1 Failed to load resource: the server responded with a status of 401 ()
main.js:177 Error exporting:  Exception in job handler: TypeError: unknown: Duplicate declaration "NAMESPACE"
  190 | 
  191 | // c3/timelines/propertySourceAdapters/effectSourceAdapter.js
> 192 | "use strict";const NAMESPACE=C3.PropertyTrack.EffectSourceAdapter=class{constructor(a,b){this._propertyTrack=a,this._track=a.GetTrack(),this._name=b[1],this._index=b[2],this._propertyAdapter=null}Release(){this._propertyAdapter&&(this._propertyAdapter.Release(),this._propertyAdapter=null),this._propertyTrack=null,this._track=null}GetPropertyAdapter(){if(this._propertyAdapter)return this._propertyAdapter;const a=this._GetEffectParameters(),b=this._index,c=this._propertyTrack;let d=this._propertyTrack.GetPropertyKeyframeType();return"numeric"===d&&"combo"===c.GetPropertyType()&&(d="combo"),"combo"===d||"boolean"===d||"text"===d?this._propertyAdapter=C3.New(NAMESPACE.NoInterpolationPropertyAdapter,c,a,b):"numeric"===d?this._propertyAdapter=C3.New(NAMESPACE.NumericPropertyAdapter,c,a,b):"color"===d?this._propertyAdapter=C3.New(NAMESPACE.ColorPropertyAdapter,c,a,b):void 0,this._propertyAdapter}SetInitialState(){this.GetPropertyAdapter().SetInitialState()}SetResumeState(){this.GetPropertyAdapter().SetResumeState()}Interpolate(a,b,c){if(this._GetEffectParameters()){const d=C3.PropertyTrack.PropertySourceAdapter.GetInterpolateFunc(this._propertyTrack),e=d(a,b,c,this._propertyTrack);return this.GetPropertyAdapter().ChangeProperty(e)}}GetValueAtTime(){return C3.PropertyTrack.PropertySourceAdapter.GetValueAtTime(this._propertyTrack)}_GetEffectParameters(){if(this._effectParams)return this._effectParams;const a=this._track.GetWorldInfo(),b=a.GetInstanceEffectList(),c=b.GetEffectList(),d=c.GetEffectTypeByName(this._name),e=d.GetIndex();return this._effectParams=b.IsEffectIndexActive(e)?b.GetEffectParametersForIndex(e):null,this._effectParams}};
      |                    ^
  193 | 
  194 | // c3/timelines/propertySourceAdapters/instanceVariableSourceAdapter.js
  195 | "use strict";const NAMESPACE=C3.PropertyTrack.InstanceVariableSourceAdapter=class{constructor(a,b){this._propertyTrack=a,this._track=a.GetTrack(),this._index=b[1],this._propertyAdapter=null}Release(){this._propertyAdapter&&(this._propertyAdapter.Release(),this._propertyAdapter=null),this._propertyTrack=null,this._track=null}GetPropertyAdapter(){if(this._propertyAdapter)return this._propertyAdapter;const a=this._track.GetInstance(),b=this._index,c=this._propertyTrack;switch(c.GetPropertyType()){case"boolean":this._propertyAdapter=C3.New(NAMESPACE.NoInterpolationPropertyAdapter,c,a,b);break;case"string":this._propertyAdapter=C3.New(NAMESPACE.NoInterpolationPropertyAdapter,c,a,b);break;case"number":this._propertyAdapter=C3.New(NAMESPACE.NumericPropertyAdapter,c,a,b);}return this._propertyAdapter}SetInitialState(){this.GetPropertyAdapter().SetInitialState()}SetResumeState(){this.GetPropertyAdapter().SetResumeState()}Interpolate(a,b,c){const d=C3.PropertyTrack.PropertySourceAdapter.GetInterpolateFunc(this._propertyTrack),e=d(a,b,c,this._propertyTrack);return this.GetPropertyAdapter().ChangeProperty(e)}SaveState(){this.GetPropertyAdapter().SetSaveState()}ClearSaveState(){this.GetPropertyAdapter().ClearSaveState()}GetCurrentState(){return this.GetPropertyAdapter().GetCurrentState()}CompareInitialStateWithCurrent(){return this.GetPropertyAdapter().CompareInitialStateWithCurrent()}CompareSaveStateWithCurrent(){return this.GetPropertyAdapter().CompareSaveStateWithCurrent()}GetValueAtTime(){return C3.PropertyTrack.PropertySourceAdapter.GetValueAtTime(this._propertyTrack)}};
ǃMj @ main.js:177
main.js:81 Connected to server
main.js:81 Project uploaded successfully
main.js:81 Waiting to build
main.js:81 Preparing project
main.js:81 Building Android
main.js:81 Compressing builds
main.js:81 Build complete, beginning transfer
main.js:81 Connected to server
main.js:81 Project uploaded successfully
main.js:81 Waiting to build
main.js:81 Preparing project
main.js:81 Building Android
main.js:81 Compressing builds
main.js:81 Build complete, beginning transfer
main.js:177 Error exporting:  Exception in job handler: TypeError: unknown: Duplicate declaration "NAMESPACE"
  190 | 
  191 | // c3/timelines/propertySourceAdapters/effectSourceAdapter.js
> 192 | "use strict";const NAMESPACE=C3.PropertyTrack.EffectSourceAdapter=class{constructor(a,b){this._propertyTrack=a,this._track=a.GetTrack(),this._name=b[1],this._index=b[2],this._propertyAdapter=null}Release(){this._propertyAdapter&&(this._propertyAdapter.Release(),this._propertyAdapter=null),this._propertyTrack=null,this._track=null}GetPropertyAdapter(){if(this._propertyAdapter)return this._propertyAdapter;const a=this._GetEffectParameters(),b=this._index,c=this._propertyTrack;let d=this._propertyTrack.GetPropertyKeyframeType();return"numeric"===d&&"combo"===c.GetPropertyType()&&(d="combo"),"combo"===d||"boolean"===d||"text"===d?this._propertyAdapter=C3.New(NAMESPACE.NoInterpolationPropertyAdapter,c,a,b):"numeric"===d?this._propertyAdapter=C3.New(NAMESPACE.NumericPropertyAdapter,c,a,b):"color"===d?this._propertyAdapter=C3.New(NAMESPACE.ColorPropertyAdapter,c,a,b):void 0,this._propertyAdapter}SetInitialState(){this.GetPropertyAdapter().SetInitialState()}SetResumeState(){this.GetPropertyAdapter().SetResumeState()}Interpolate(a,b,c){if(this._GetEffectParameters()){const d=C3.PropertyTrack.PropertySourceAdapter.GetInterpolateFunc(this._propertyTrack),e=d(a,b,c,this._propertyTrack);return this.GetPropertyAdapter().ChangeProperty(e)}}GetValueAtTime(){return C3.PropertyTrack.PropertySourceAdapter.GetValueAtTime(this._propertyTrack)}_GetEffectParameters(){if(this._effectParams)return this._effectParams;const a=this._track.GetWorldInfo(),b=a.GetInstanceEffectList(),c=b.GetEffectList(),d=c.GetEffectTypeByName(this._name),e=d.GetIndex();return this._effectParams=b.IsEffectIndexActive(e)?b.GetEffectParametersForIndex(e):null,this._effectParams}};
      |                    ^
  193 | 
  194 | // c3/timelines/propertySourceAdapters/instanceVariableSourceAdapter.js
  195 | "use strict";const NAMESPACE=C3.PropertyTrack.InstanceVariableSourceAdapter=class{constructor(a,b){this._propertyTrack=a,this._track=a.GetTrack(),this._index=b[1],this._propertyAdapter=null}Release(){this._propertyAdapter&&(this._propertyAdapter.Release(),this._propertyAdapter=null),this._propertyTrack=null,this._track=null}GetPropertyAdapter(){if(this._propertyAdapter)return this._propertyAdapter;const a=this._track.GetInstance(),b=this._index,c=this._propertyTrack;switch(c.GetPropertyType()){case"boolean":this._propertyAdapter=C3.New(NAMESPACE.NoInterpolationPropertyAdapter,c,a,b);break;case"string":this._propertyAdapter=C3.New(NAMESPACE.NoInterpolationPropertyAdapter,c,a,b);break;case"number":this._propertyAdapter=C3.New(NAMESPACE.NumericPropertyAdapter,c,a,b);}return this._propertyAdapter}SetInitialState(){this.GetPropertyAdapter().SetInitialState()}SetResumeState(){this.GetPropertyAdapter().SetResumeState()}Interpolate(a,b,c){const d=C3.PropertyTrack.PropertySourceAdapter.GetInterpolateFunc(this._propertyTrack),e=d(a,b,c,this._propertyTrack);return this.GetPropertyAdapter().ChangeProperty(e)}SaveState(){this.GetPropertyAdapter().SetSaveState()}ClearSaveState(){this.GetPropertyAdapter().ClearSaveState()}GetCurrentState(){return this.GetPropertyAdapter().GetCurrentState()}CompareInitialStateWithCurrent(){return this.GetPropertyAdapter().CompareInitialStateWithCurrent()}CompareSaveStateWithCurrent(){return this.GetPropertyAdapter().CompareSaveStateWithCurrent()}GetValueAtTime(){return C3.PropertyTrack.PropertySourceAdapter.GetValueAtTime(this._propertyTrack)}};
ǃMj @ main.js:177
The FetchEvent for "https://editor.construct.net/r132/" resulted in a network error response: the promise was rejected.
Promise.catch (async)
(anonymous) @ sw.js:444
The FetchEvent for "https://editor.construct.net/r132/cloud/sandbox.html" resulted in a network error response: the promise was rejected.
Promise.catch (async)
(anonymous) @ sw.js:444
sw.js:386 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at HandleFetch (sw.js:386)
HandleFetch @ sw.js:386
Promise.then (async)
(anonymous) @ sw.js:444
sw.js:386 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at HandleFetch (sw.js:386)
HandleFetch @ sw.js:386
Promise.then (async)
(anonymous) @ sw.js:444
sw.js:386 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at HandleFetch (sw.js:386)
HandleFetch @ sw.js:386
sw.js:386 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at HandleFetch (sw.js:386)
HandleFetch @ sw.js:386

**Comment by shortercode** [comment] 2019-01-08 13:37
Can confirm that exporting with minification enabled causes the `Duplicate declaration "NAMESPACE"` error, that's a known problem with the minifier in this release ( see #2492 ). Going to check if there's any issues in non minified builds, but I think @DiegoScirra has fixed the namespace bug so this should be solved in the next release.

**Comment by sizcoz** [comment] 2019-01-08 13:54
Just to Add with Minify is unchecked it Exports, but when installed on an Android Phone it just gives a black screen on startup.
Cheers

**Comment by shortercode** [comment] 2019-01-08 14:56
Closing as ( not obviously ) duplicate of #2492

**Closed by shortercode** 2019-01-08 14:56 UTC
Labels: duplicate

**Comment by haypers** [comment] 2019-05-31 19:19
this happened to me when trying to export my debug apk. The app was just a blank screen of black. The problem was fixed when I turned off the minify script option. But that is not to say other forms of the problem will require other fixes.

**Comment by shortercode** [comment] 2019-06-03 11:11
@haypers this issue was resolved in January, if you have a minification issue there's a good chance it's completely unrelated to this. Please file a new issue with a minimal replication for us to investigate.

**Comment by haypers** [comment] 2019-06-06 19:30
ok. thx
