### ISSUE TITLE
Propetties bar values do not update correctly in Edge

### ISSUE THREAD

**Issue by AmateurX-14** [Scirra/Construct-3-bugs#1764] opened 2018-07-04 02:26 UTC
#desktop apps 

Screenshots
https://flic.kr/p/28HPLom

**Comment by AshleyScirra** [comment] 2018-07-04 10:32
Looks like there is a problem here, steps to reproduce should be:

1. Create a new project
2. Click in any typed property value field [side note: the field does not autoselect like it does in Chrome]
3. Select the whole field, type in a new value
4. Press enter

Observed result:
Text field updates but does not apply the value. If you click to another property and back again a couple of times it seems to make it update.

Expected result:
Changing property should update value immediately, like other browsers.

Reproduces in Edge browser, this is not specific to the Windows 10 app.

Please always follow the bug report guidelines, we often close such issues without investigation.

**Comment by AmateurX-14** [comment] 2018-07-04 10:36
when copy project viewport size and paste to layout Size, it will reproduce.

**Comment by AshleyScirra** [comment] 2018-07-04 11:17
Should be fixed in the next release, let's check it when it's out.

**Comment by AshleyScirra** [comment] 2018-07-17 12:41
r109 is now out. Can you verify it's working better now?

**Comment by AmateurX-14** [comment] 2018-07-17 12:46
R109 is working normally, thank you very much.

**Comment by AshleyScirra** [comment] 2018-07-17 15:40
Thanks for confirming!

**Closed by AshleyScirra** 2018-07-17 15:40 UTC
Labels: edge, ignored guidelines, need info
