### ISSUE TITLE
Audio files in Sounds/subfolder are not playing and can't be previewed either.

### ISSUE THREAD

**Issue by johnsmith27** [Scirra/Construct-3-bugs#6130] opened 2022-09-24 11:30 UTC
Hi,

It's a strange problem and unfortunately I can't replicate it completely on a test project.

In my game, every sound files that are in a sounds/subfolder are not played anymore and can't be previewed in the events.
In the events: audio/Play, if I press the preview button while the file is selected, nothing happens. And the sound doesn't play ingame either (no sound displayed in the Audio panel in debug mode)
If I select a different sound not in a subfolder, the preview works, and the sound plays fine ingame.

Although If I preview the files directly from the editor (right click in the editor > project windows > Sounds/subfolder), the preview is still working fine for every sound files.

## Attach a .c3p
https://www.dropbox.com/s/hovkc3268yup0ab/sound_test.c3p?dl=0

Can't replicate the problem entirely, but I managed to make the event/play file preview bug by importing the sound directly in the subfolder (right click subfolder/import sounds). I think the preview was still working if it's imported in the sounds folder and then dragged in the subfolder.

## Steps to reproduce

1. Import sound directly in a sounds/subfolder
2. Add audio/play event, select file and click the preview button

## Observed result

The sound is not previewed

The sound is played ingame though, while in my personal project, it's not...but I dont know how to reproduce this problem.

## Expected result

The sound should be previewed

(And the sound should be played in game)

## More details

**Affected browsers/platforms:** 
Brave [Version 1.25.72 Chromium: 91.0.4472.101 (Build officiel) (64 bits)] & Android debug apk

Worked in r309  but broke in r310 / r311 (related to project properties "export file structure", see my comment below)

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r311 (beta)
Browser: (unknown) (unknown)
Browser engine: Chromium
Context: browser
Operating system: undefined (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 2 gb
Storage usage (approx): 406 mb (19.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6589)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 6
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by johnsmith27** [comment] 2022-09-24 11:53
Just realized I had made a change in the project properties : Export File Structure. From "flat" to "folders" (on r311)
If I put it back to "flat", everything is working fine again. 
Any possibilities for me to switch to the recommended "folders" properties and keep the sounds/subfolder working properly ?

**Comment by AshleyScirra** [comment] 2022-09-26 14:46
> In the events: audio/Play, if I press the preview button while the file is selected, nothing happens

I can reproduce this (it's broken in the new "folders" export file structure mode), and it should be fixed for the next beta.

However I can't reproduce anything else wrong with this project - in preview it plays the sound correctly regardless of the "export file structure" mode. I suspect you are using "Play by name" in which case in folders mode you now need to specify the folder path as well as the file name. For example a sound "beep" in folder "subfolder" can be referred to as "beep" in flat mode, but must be referred to as "subfolder/beep" in folders mode. The reason projects default to using flat mode is so they work backwards-compatibly; if you want to switch to folders mode you'll need to update all references to files by name to use their subfolders. I assume that's what is going on, but if you still think there is a bug, that would need a separate bug report with its own project demonstrating that problem.

**Closed by AshleyScirra** 2022-09-26 14:46 UTC

**Comment by johnsmith27** [comment] 2022-09-26 16:17
> I suspect you are using "Play by name" in which case in folders mode you now need to specify the folder path as well as the file name.

Yes that was the problem, added the missing path and it's working now. Thank you Ashley !
