### ISSUE TITLE
Dragging a Project Folder = Construct Freeze - (Desktop Build)

### ISSUE THREAD

**Issue by AlonDan** [Scirra/Construct-3-bugs#1342] opened 2018-03-04 21:23 UTC
## Problem description
While trying to drag a Folder or Subfolder for better organized I found out that Construct 3 Desktop Build (latest version) Freezes, the only way to close it is via the Task Manager.

## Steps to reproduce
Try to drag a Folder or Subfolder to another place on the Project Panel = Freeze

## Expected result
Reorganized Folders and Subfolders by drag and drop without freezing will be great.

## System details
Windows 10 64bit
Intel Core i7-4770K CPU 3.50 GHz
SSD
32GB RAM
GeForce GTX 980

**Comment by AshleyScirra** [comment] 2018-03-04 21:42
Looks like a duplicate of #1336 - should be fixed in the next release.

**Closed by AshleyScirra** 2018-03-04 21:42 UTC
Labels: duplicate
