### ISSUE TITLE
Crash on startup on iOS export...caused by MobileAdvert...?

### ISSUE THREAD

**Issue by DaveedA13** [Scirra/Construct-3-bugs#3658] opened 2020-02-19 16:46 UTC
## Problem description

My game now crash on startup (loading). It is published on the App Store so it worked for some time but my new builds are crashing now...could be a problem with the "Build Server"?

(I'm asking since I tried with a version of my game that worked fine before (the one that is published), without changing anything, in 2 differents version of C3, Release 187, and 185)

## Attach a .c3p

[TEST_ExportiOS_StartupCrashBug - VERSION 1.11.009_BUILD10_WithoutIDsMobAdv.zip](https://github.com/Scirra/Construct-3-bugs/files/4226066/TEST_ExportiOS_StartupCrashBug.-.VERSION.1.11.009_BUILD10_WithoutIDsMobAdv.zip)

## Steps to reproduce

1. Export the minimal project (made from one of your project) to iOS (Cordova).
2. Import it into XCode and the archive it.
3. Test it in TestFlight app.

## Observed result

It is "stuck" on loading.
(full bar if "**Progress bar and logo**" is set inside C3, at 0% if "**Percentage text**" is selected instead)

## Expected result

The game should start.

## More details
No problem on startup when exporting to Android.

Made a lot of tests and backups of my game while stripping events and plugins to try to find what's causing the bug.  Seem to be linked to "MobileAvert" plugin but probably with a second variable because a new project with just the Mobieadvert plugin doesn't make the game crash.  The provided minimal project is still simple and enough and do crash. I remove my IDs in the provided zip file but I tripled-checked them and they were identical to my published version file, compared them again to AdMob website IDs too.

I was super hyped to try to publish a new version version of my game since @AshleyScirra answered my latest bug report about MobileIAP plugin with a solution while the bug get fixed, but now I have this bug... :/ 

I'm renting a Mac to create my builds from XCode so I'm disappointed a little by all those trials and errors and the time is asked me.

Btw, just a little out of topic, the "**MobileAdvert**" plugin is the one that make Apple send the "**Your app has one or more issues**" mail about "Deprecated API Usage (UIWebView)". I can confirm it because when I stripped this plugin I didn't have this mail from Apple for each build, after inserting it again I got the mail for the next build again.

**Affected browsers/platforms:** 

iOS

**First affected release:** 
Found the problem with Release 187 of C3, but made a test with a previous release (185) and the crash still happens.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.39.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.39.0 (like Chrome/75.0.3770.80)
C3 release: r187 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 661 mb
Storage usage (approx): 661 mb (100%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2020-02-19 18:36
There is a known issue with Mobile Advert that causes a crash on startup if it is misconfigured. See #3102 and this forum thread: https://www.construct.net/en/forum/construct-3/how-do-i-8/breaking-change-mobile-advert-145087

Are you sure you have configured it correctly?

Are there any relevant error messages in the Xcode log when running on the device? Usually if anything goes wrong, it is logged there.

**Comment by DaveedA13** [comment] 2020-02-19 19:49
@AshleyScirra 

Thanks a lot for the quick reply.

My game does **not** crash at all on Android so it's not the same bug or am I wrong?

I published my game on Android, complete with the "MobileAdvert" plugin fully working, so...my IDs are configured right, no?

(I can even see my stats for requests and impressions on AdMob website for my published app, with the same IDs)

Sadly I'm running it through TestFlight as I can't test with a real device from XCode since I'm renting a Mac via a cloud.  But all my previous builds worked before a few days ago.

Do you think you'll have time soon to test my provided minimal project file on your side to see if you have the same crash on startup with your owns test IDs...? (and so with Xcode log)

**I just retested again**, with the exact c3p file I used to publish to Android, and it crashes. If I remove the MobileAdvert plugin and all the events that references it, the game start and I can play without problem. :)

Thank you.

**Comment by tuzke** [comment] 2020-02-20 02:09
My game also crashes every 20-25 minutes

**Comment by AshleyScirra** [comment] 2020-02-20 12:27
I'll give it a go when I get time, but very commonly the way this works out is I run it, and it works fine, because there are non-obvious details about what you're doing that you didn't realise or explain. It's important to have a real Mac and run on a device via a cable to be able to diagnose issues like this.

**Comment by DaveedA13** [comment] 2020-02-24 15:15
@AshleyScirra 

Sadly I can't afford a Mac currently. :(

Are there a lot of things that can make the game crash on **startup**? (before the end of the loading)

When you ask if I'm sure if I have it configured properly, you mean the **"MobileAdvert" object properties**? Like I said, I didn't change anything in the properties and the very same game with the very same "MobileAdvert" config is published on the App Store.

I would have really like the game to at least not crash on startup so debugging it would be be a lot easier. :/

XCode can even provide crash reports for TestFlight crashes but not if the game doesn't even start...

The last 2 bug reports that I provided here about Construct 3 were real bugs that got fixed, so, **thanks for your time in advance** for when you'll have the time to make the test.

For now I'll still try to make a couple more builds but I'm running out of ideas...

**Comment by AshleyScirra** [comment] 2020-03-05 17:42
I looked in to this. A minimal project using Mobile Advert works fine on iOS. I can reproduce a problem with your project though (after substituting the IDs for my own which I tested worked OK in the minimal project). I don't think it's actually anything to do with Mobile Advert - if anything, the fact Mobile Advert works in a separate project proves it's *not* to do with that. However it's difficult to debug projects with lots of unrelated objects and events. Can you find a way to reproduce this with a minimal project? Ideally it should have only 2-3 objects and 2-3 events.

**Comment by AshleyScirra** [comment] 2020-03-16 18:40
Eventually through a lot of trial and error, came down to the Google Play plugin preventing iOS apps starting. Should be fixed in next release.

**Closed by AshleyScirra** 2020-03-16 18:40 UTC
