### ISSUE TITLE
Mouse position is in wrong position when expand properties panel

### ISSUE THREAD

**Issue by kppaiboo** [Scirra/Construct-3-bugs#772] opened 2017-09-02 08:43 UTC
## Problem description

*Mouse position is in wrong position. When I expand properties panel and I click on sprite and I want to resize sprite the mouse position is not in the right position*

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Create a sprite and paste in the canvas
2. Expand the size of Properties panel
3. Use mouse to resize the sprite

## Observed result

*Mouse pointer is in wrong position compare to the sprite. R51 is ok. R52 and R53  have the problem.*

## Expected result

*I can use mouse pointer to click and resize sprite in right position.*

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2017-09-02 10:11
No project provided and I can't reproduce in Ghost Shooter, so closing.

Please always follow the bug report guidelines, they're there to ensure we can fix the problem you report.

**Closed by AshleyScirra** 2017-09-02 10:11 UTC
Labels: ignored guidelines
