### ISSUE TITLE
Error when closing a project

### ISSUE THREAD

**Issue by SolunaSoftware** [Scirra/Construct-3-bugs#57] opened 2017-04-11 16:07 UTC
## Problem description

A dialog showed up containing this:

Error report information
Type: unhandled rejection
Reason: TypeError: Cannot read property 'ǃbJ' of null
Stack: TypeError: Cannot read property 'ǃbJ' of null at a.ǃJ.ǃo (https://editor.construct.net/r17/plugins/sprite/plugin.js:1:4875) at te.ǃo (https://editor.construct.net/r17/main.js:61:203987) at te.ǃo (https://editor.construct.net/r17/main.js:61:210063) at ne.ǃo (https://editor.construct.net/r17/main.js:61:157598) at xe.ǃo (https://editor.construct.net/r17/main.js:61:76307) at Oe.then.ze (https://editor.construct.net/r17/main.js:153:27390)
Construct 3 version: r17
URL: https://editor.construct.net/
Date: Tue Apr 11 2017 17:48:42 GMT+0200 (Rom, sommertid)
Uptime: 5341 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
[BugFound.zip](https://github.com/Scirra/Construct-3-bugs/files/913886/BugFound.zip)

## Steps to reproduce

1. Start Construct and a new proejct
2. Add a layer 1 above layer 0. Add a sprite to layer 0
3. Copy (Copy/Paste) that sprite so you have two sprite on layer 0.
4 Do 'Save As' so project is saved to local storage.
5. Move one sprite a bit.
6. Hide and lock layer 1. Select layer 0.
6. Right click on project and select Close.
7 When asked to save changes select Don't Save
8. Boom! (Error dialog is shown)

## Observed result

*What do you see happen?*

An error dialog!

## Expected result

*What did you expect to happen instead?*
No error dialog!

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

Chrome!

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE 

See above details.

</details>

**Comment by jaydonteh** [comment] 2017-04-11 18:00
I just got slapped by this bug and came to file, but can't reproduce it. It was with a new project, added some sprites and close project with a crash.

**Comment by SolunaSoftware** [comment] 2017-04-12 02:44
I can get the error every time now. I have updated the step by step description. Please try to reproduce it again. Thanks.


Exception:
Type: unhandled rejection
Reason: TypeError: Cannot read property 'ǃbJ' of null
Stack: TypeError: Cannot read property 'ǃbJ' of null at a.ǃJ.ǃo (https://editor.construct.net/r17/plugins/sprite/plugin.js:1:4875) at te.ǃo (https://editor.construct.net/r17/main.js:61:203987) at te.ǃo (https://editor.construct.net/r17/main.js:61:210063) at ne.ǃo (https://editor.construct.net/r17/main.js:61:157598) at xe.ǃo (https://editor.construct.net/r17/main.js:61:76307) at Oe.then.ze (https://editor.construct.net/r17/main.js:153:27390)
Construct 3 version: r17
URL: https://editor.construct.net/
Date: Wed Apr 12 2017 04:41:54 GMT+0200 (Rom, sommertid)
Uptime: 85.5 s

**Comment by shortercode** [comment] 2017-04-12 16:36
I've simplified the reproduction to:
1. create new project
2. add sprite
3. copy and paste or clone sprite
4. close project

The pasted sprite wasn't being completely created, and hence when the project closed some parts of the sprite didn't exist to remove from the editor. Should be fixed in r18

**Closed by shortercode** 2017-04-12 16:36 UTC
Labels: no repro
