### ISSUE TITLE
Tilemap editor is crashing

### ISSUE THREAD

**Issue by mnfala** [Scirra/Construct-3-bugs#4159] opened 2020-08-28 13:39 UTC
## Problem description

When I open a tilemap and change a collision box occurs a error

## Attach a .c3p

[teste.zip](https://github.com/Scirra/Construct-3-bugs/files/5142327/teste.zip)

## Steps to reproduce

1. Open the file teste.c3p
2. Double click tilemap editor
3. Change a colision box
4. Close de editor
5. A error dialog is show.

## More details
Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'rj' of null @ TypeError: Cannot read property 'rj' of null at https://editor.construct.net/r210-2/components/bars/tilemapBar/tilemapBar.js:35:365
Stack: TypeError: Cannot read property 'rj' of null at https://editor.construct.net/r210-2/components/bars/tilemapBar/tilemapBar.js:35:365
Construct 3 version: r210.2
URL: https://editor.construct.net/
Date: Thu Aug 27 2020 15:51:27 GMT-0300 (Horário Padrão de Brasília)
Uptime: 209.2 s

Platform information
Browser: Chrome
Browser version: 84.0.4147.135
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
C3 release: r210.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 3000 Direct3D9Ex vs_3_0 ps_3_0)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_color_buffer_half_float, EXT_float_blend, EXT_frag_depth, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_color_buffer_float, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2020-08-28 13:46
@mnfala - can you reproduce this in the latest release r213? We ask that you check the latest release to avoid reporting issues that are already fixed, and your report appears to be using r210.2.

**Comment by mnfala** [comment] 2020-08-28 14:52
Ok, in r213 (beta) it is fixed.

Em sex., 28 de ago. de 2020 às 10:47, Ashley (Scirra) <
notifications@github.com> escreveu:

**Comment by DiegoScirra** [comment] 2020-08-28 15:29
Duplicate of #4104.

 @mnfala If you want to continue using the stable version you can try enabling UI animations in **Menu -> Settings**. The crash was related to them being turned off

**Closed** 2020-09-01 13:29 UTC
