### ISSUE TITLE
Cannot export to android due to error

### ISSUE THREAD

**Issue by Nabbo-extreme** [Scirra/Construct-3-bugs#1872] opened 2018-07-29 22:08 UTC
## Problem description

Cannot export to android due to error, happened in latest built with GooglePlay Addon only.

## Attach a .c3p

[Android.zip](https://github.com/Scirra/Construct-3-bugs/files/2239234/Android.zip)

## Steps to reproduce

1. Open
2. Export to Android
3. You Get Error

## Observed result
Attached
<img width="714" alt="screen shot 2018-07-30 at 2 03 55 am" src="https://user-images.githubusercontent.com/41523520/43371154-2a24e286-939d-11e8-82ba-27dd2f09148c.png">

## Expected result

It should export.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1.7999999523162842
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r111 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 149 mb (0.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 6100
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Nabbo-extreme** [comment] 2018-07-29 22:12
Exporting to Debug APK causes this, and it happened on Mobile Chrome also

**Comment by shortercode** [comment] 2018-07-30 10:39
Marking as duplicate of #1865.

Issue was a bad release of construct-play-games cordova plugin, I've reverted the whitelist to disallow the bad version. Seems to work correctly now, sorry about the downtime.

**Closed by shortercode** 2018-07-30 10:39 UTC
