### ISSUE TITLE
Drawing Canvas - clears itself 

### ISSUE THREAD

**Issue by RufusRufson** [Scirra/Construct-3-bugs#4863] opened 2021-06-02 17:38 UTC
Hello,
I have made an easy to follow(self explanatory) demo to demostrate a bug: self clearing Drawing Canvas.
When Drawing Canvas have a Sine behaviour (or any change on position X,Y driven by events) and unbounded scrolling is on&scrollto behaviour is active, then this self clear issue fires(sometimes even without unbounded scrolling on) . In the demo you can easily turn on/off all scroll modes.
Also in the demo in scene 4, scroll and unbound is off and Drawing Canvas have a Mesh points 2x2 driven by sprite image points and the problem is the same.
Please, check the file below: made in beta 2.50 (this problem was also in a stable version but without scenes 3,4) This is my first bug report.
I tested this on windows 10, Chrome, Firefox, Edge.
[DrawingCanvas_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/6586396/DrawingCanvas_bug.zip)

Best
Rufus

**Comment by RufusRufson** [comment] 2021-06-02 17:41
please change zip extension to c3p to open it in r250

**Comment by AshleyScirra** [comment] 2021-06-03 11:32
Your project does not attempt to handle the 'On resolution changed' trigger, so I would guess something is changing the canvas size and you're not redrawing it, which is by design. It is difficult to follow bug reports that do not follow the guidelines (the bug template was not used and the project is actually difficult to follow, we ask for a minimal project with the fewest events/objects possible otherwise it's too difficult to investigate), so closing.

**Closed by AshleyScirra** 2021-06-03 11:32 UTC
Labels: not a bug
