### ISSUE TITLE
Construct3 Desktop Crashing during and after editing CSS and Form Objects

### ISSUE THREAD

**Issue by tkain9** [Scirra/Construct-3-bugs#3181] opened 2019-08-01 14:50 UTC
## Problem description

Crashes on latest r159beta Desktop Version. This happened twice so far. 
The first time it crashed as I had just finished adding a button object to the layout. The second time was after reloading the same crashed project. After adding a line of css to the stylesheet, I then navigated away from the Construct editor to another chrome window and a minute later it crashed without any input from me.

## Attach a .c3p

[VoiceApp1.zip](https://github.com/Scirra/Construct-3-bugs/files/3457147/VoiceApp1.zip)
[VoiceApp1.zip](https://github.com/Scirra/Construct-3-bugs/files/3457150/VoiceApp1.zip)

## Steps to reproduce

I'm not sure how to reproduce exactly, however, I was adding form elements to the layout and styling them with a css stylesheet when the crashes happened.

1. Add form objects
2. Add id tags
3. Style them with the css stylesheet
4. Repeat?

## Observed result

Crashing while adding form objects and using other program windows with Construct3 running (desktop version)

## Expected result

Form objects added to the layout and leaving the program running while investigating other browser windows without crashing.

## More details

I'll also add that:

- I had EventSheet docked to the bottom half of the program window during both crashes.

- I am using the Official Dark Theme

- I have snap to grid enabled

**Affected browsers/platforms:** 

Windows 10 using Desktop version of Construct3 r159beta

**First affected release:** 

r159beta

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: expected string @ TypeError: expected string at Function.ǃEW (https://editor.construct.net/r159/main.js:2:92364) at Function.ǃRq (https://editor.construct.net/r159/main.js:159:130423) at e (https://editor.construct.net/r159/main.js:159:117375) at https://editor.construct.net/r159/main.js:159:118084
Stack: TypeError: expected string at Function.ǃEW (https://editor.construct.net/r159/main.js:2:92364) at Function.ǃRq (https://editor.construct.net/r159/main.js:159:130423) at e (https://editor.construct.net/r159/main.js:159:117375) at https://editor.construct.net/r159/main.js:159:118084
Construct 3 version: r159
URL: https://editor.construct.net/r159/
Date: Thu Aug 01 2019 15:09:47 GMT+0100 (British Summer Time)
Uptime: 600.6 s

Platform information
Browser: NW.js
Browser version: 0.39.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.39.0 (like Chrome/75.0.3770.80)
C3 release: r159 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 / HD 7900 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2019-08-15 16:02
Without clear steps to reproduce I'm afraid it's difficult to do anything about this. I tried opening the provided project in the desktop build, changed a few CSS styles and focused other windows and switched back, and it seems fine. This is why we need specific steps that reliably reproduce the issue to be able to help, as described by the guidelines. If you can find these please file a new issue, otherwise closing as unable to reproduce. The crash also doesn't look specific to NW.js - it would be useful to know if it can be reproduced in the Chrome browser too.

**Closed by AshleyScirra** 2019-08-15 16:02 UTC
Labels: can't reproduce
