### ISSUE TITLE
theme sdk:  add ‘--window border color’ CSS variables

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5758] opened 2022-06-02 07:12 UTC
## Problem description

It is suggested to add a variable to change the  `--window-border-color`.   

```css
    --window-border-size: 1px;
    --window-border-color: #30363d  /* Not currently support */
```

Currently, the border color of the dialog is fixed to `#ccc`.  is not supported to changed.

![Snipaste_2022-06-02_15-05-28](https://user-images.githubusercontent.com/45864744/171572850-3738e59a-62eb-4c34-98cc-8091107cd37e.png)

Doesn't work even if I specify border color.
```css
dialog {
    border-color:#30363d;
}
```

Of course, I can also force it to change, but that's not good.
```css
dialog {
    border-color:#30363d !important;
}
```

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by XHXIAIEIN** [comment] 2022-06-02 13:03
And Is it possible to provide the default theme `theme.css`  download?  This will let we know what is changed by default theme

**Comment by AshleyScirra** [comment] 2022-06-06 11:13
This looks like an SDK suggestion, not a bug, so closing.

The existing color should be overridable so it should not be necessary to have a CSS variable to support changing it.

**Closed by AshleyScirra** 2022-06-06 11:13 UTC
Labels: not a bug
