### ISSUE TITLE
Canwas bug r 277, 278, 279, 280, 281

### ISSUE THREAD

**Issue by ibiz3091** [Scirra/Construct-3-bugs#5415] opened 2022-02-02 10:44 UTC
canvas incorrectly inserts shadow light when default Normalized mode is set. After installing regular mode, the display is correct. I have attached c3p. To repeat, run the project in the Normalized and regular mode and see the result.

[## Attach a .c3p
](https://drive.google.com/file/d/150oN1tC5ZANewGq-u-yK-SPs5AwD2lXO/view?usp=sharing)

https://drive.google.com/file/d/1oHwkUiSdOiRmRC98TOT6S9SoA8z-lWFf/view?usp=sharing

https://drive.google.com/file/d/1Skg7hRTeQ7b_onQiIT7Wh_2rPHchPAQ0/view?usp=sharing

What can't you reproduce? you have to be blind not to see it...

## Attach a .c3p
![2022-02-02_13-46-47](https://user-images.githubusercontent.com/44605893/152141204-14f30991-8db7-45be-b94f-8ee9acdc225c.png)

![2022-02-02_13-45-19](https://user-images.githubusercontent.com/44605893/152141238-c962f683-5a54-4c93-98c6-9ba8081f012f.png)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>
[What can't you reproduce? you have to be blind not to see it...](url)

**Comment by AshleyScirra** [comment] 2022-02-02 12:52
In r281, it looks like this to me with Z axis "normalized":

![issue5415-normalized](https://user-images.githubusercontent.com/768723/152157141-8f4cad06-7d58-4605-80f8-bcdfe9363843.png)

And like this with Z axis "regular":

![issue5415-regular](https://user-images.githubusercontent.com/768723/152157171-8a08255c-e578-4166-91d6-fe232393dd89.png)

In other words, identical. I can't see anything wrong at all.

I'm afraid there is nothing we can do unless the issue can be reproduced. It's important to fill out the full bug report details thoroughly as per the bug report guidelines otherwise it means it is impossible for us to investigate it any further. Can you provide any more information that might help identify the cause of the problem?

**Comment by SnipG** [comment] 2022-02-02 15:45
Without even looking at it i bet it's scaling issue, same issues always show up similarly. His popup opens up differently then default, because he has scaled it before and has editor open.  

Most likely preview and change preview window size, will show bugggy.

**Comment by ibiz3091** [comment] 2022-02-02 17:13
> Даже не глядя на это, я держу пари, что это проблема масштабирования, одни и те же проблемы всегда проявляются одинаково. Его всплывающее окно открывается по-другому, чем по умолчанию, потому что он масштабировал его раньше и открыл редактор.
> 
> Скорее всего, предварительный просмотр и изменение размера окна предварительного просмотра покажут багги.

Yes, I agree with you in the project settings, the aspect ratio is 16:9, the problem progresses if you run the project on a phone with a screen not 16:9

**Comment by AshleyScirra** [comment] 2022-02-03 13:53
This looks similar to #5379, which has been fixed for the next release. Let's see if the next release also fixes this case for you.

**Comment by AshleyScirra** [comment] 2022-02-14 12:00
It looks to me like this is now fixed and no further feedback as been provided so closing.

**Closed by AshleyScirra** 2022-02-14 12:00 UTC
