### ISSUE TITLE
Abnormality of DrawingCanvas Draw polygon

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5037] opened 2021-08-31 03:34 UTC
## Problem description

I use the DrawingCanvas to draw the pie, but I occasionally get an exception with the same parameter. When it's abnormal, if I change its position, or fine-tune it, it's normal again

## Attach a .c3p

[Draw FOV.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/7081014/Draw.FOV.c3p.zip)

## Steps to reproduce

1.  Just Change the 'LOS Range' Value

![1](https://user-images.githubusercontent.com/45864744/131437064-67a2a05f-4cd4-41a5-abf3-0f9d67403ced.gif)

## Observed result

result 1
<img width="785" alt="03" src="https://user-images.githubusercontent.com/45864744/131436679-79baae5a-78bc-4e99-b835-e4ef4400c6d7.png">

result 2
<img width="850" alt="02" src="https://user-images.githubusercontent.com/45864744/131436689-c3beb577-f40d-45bf-82ef-990bce380316.png">

result 3
<img width="952" alt="04" src="https://user-images.githubusercontent.com/45864744/131436692-acf0dcaa-6563-4a2b-9a4b-925a5e573f0e.png">

## Expected result

<img width="805" alt="01" src="https://user-images.githubusercontent.com/45864744/131437139-68e0f7c4-499a-4161-9cec-e3bc5d921709.png">

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2021-09-27 12:06
The problem with drawing polygons is it must first decompose concave polys in to a series of convex polys. This process relies on floating point math, which is inherently imprecise, and can have somewhat unpredictable effects, especially when using many points which are closely spaced.

The problem is made worse by the events: the event that says "Repeat DensityVerts times" appears to insert an almost identical last point over the first point, but not exactly, as it has a rounding error. This is exactly the kind of thing that throws off poly decomposition. If you replace it with "Repeat DensityVerts - 1 times", just removing the last point, it looks a bit different but appears to work far more reliably.

I think this is a mix of a problem with the events and the fundamental limitations of floating point precision, so closing as wontfix. You can probably adjust the events to work around it.

**Closed by AshleyScirra** 2021-09-27 12:06 UTC
Labels: wontfix
