### ISSUE TITLE
(C3 Runtime) Text ignores "position" on "canvas size change"

### ISSUE THREAD

**Issue by DrathVader** [Scirra/Construct-3-bugs#2141] opened 2018-10-11 19:46 UTC
## Problem description

[Fullscreen Mode] set to "Off".
On [Action]  "Set Canvas Size" 

After canvas size is changed:

- [Object] "Text" ignores "Position"  
- [Object] "obj"  Drag & Drop no longer working. Hit target is offset not the same as sprite..

- C2runtime: Works
- C3runtime: Broken

## Attach a .c3p

**C2runtime (working)**
.c3p: https://1drv.ms/u/s!AnjqkTqN7Tavh-k6K-Q3vliMjpR-ZA

**C3runtime (broken)**
.c3p: https://1drv.ms/u/s!AnjqkTqN7Tavh-k7gKxidLVfXw_7gw

## Steps to reproduce

Use keyboard keys (0, 1, 2, 3) to change canvas size.

## Observed result

1. C2: "Text Box" follows position
2. C2: Drag & Drop works correctly
-------------------------------------------------------
1. C3: "Tex Box" ignores position
2. C3: Drag & Drop hit target is offset. Unable to drag.

## Expected result

1. "Text Box" correct position
2. Drag & Drop correct hit area 

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes
* Construct Preview: yes

## System details

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment] 2018-10-12 15:39
Looks like this was caused by the fix to #1832. Should be fixed for the next release.

**Closed by AshleyScirra** 2018-10-12 15:39 UTC
Labels: c3runtime

**Comment by DrathVader** [comment] 2018-10-12 17:19
Thanks, I look forward to the next release.

**Comment by DrathVader** [comment] 2018-10-16 06:54
@AshleyScirra 

As of [R122] everything now runs correctly in "Chrome" however in "Firefox" a browser refresh is required to get things back aligned.

**Comment by DrathVader** [comment] 2018-10-16 17:13
@AshleyScirra 

However, I now notice it breaks in "Chrome" when the monitor Pixel Density changes. Refresh required.

**Comment by DrathVader** [comment] 2018-10-17 18:49
As of [R122] Chrome runs correctly until the browser is moved to a new monitor with a higher/lower "Pixel Density". Game needs to be saved and browser needs to be refreshed.

"Firefox" I encountered a few instances where the alignment broke. However unable to reproduce again.
