### ISSUE TITLE
Crash when Preview

### ISSUE THREAD

**Issue by Sanguinarias** [Scirra/Construct-3-bugs#4489] opened 2021-01-19 11:00 UTC
## Problem description

I can't preview my work when using Consctruct 3.

## Attach a .c3p

A fresh file can produce the bug.

## Steps to reproduce

1. Create a project
2. The settings doesn't matter
3. Click on preview

## Observed result

Construct 3 crashes.

## Expected result

I expect to preview the game.

## More details

  I just installed Construct 3 (for work) for the first time on this computer, and experienced crashes whenever trying to preview what I am doing. At first, I thought it was because of my project, but it appears I cannot preview any project for some reason. I cannot try other computers, because I can't access them at the moment.
  I already tried to clear my browsers cache, but it did not work, restarting my computer too.
  I submit my crash report from Firefox, with all extensions disabled (it is my default browser).

**Affected browsers/platforms:**
- Chrome
- Construct 3 Chrome App
- Firefox
- Edge

**First affected release:**
- r225
- r231

## System details

<details><summary>View details</summary>

Error report information

Type: unhandled rejection
Reason: Event 'error': [object Event]
Construct 3 version: r231
URL: https://editor.construct.net/r231/
Date: Tue Jan 19 2021 11:56:50 GMT+0100 (heure normale d’Europe centrale)
Uptime: 17.5 s
Platform information

Browser: Firefox
Browser version: 84.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
C3 release: r231 (beta)
Language setting: fr-FR
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: yes
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_filter_anisotropic, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2021-01-19 12:06
It works fine for me, and presumably everyone else, because otherwise we'd be hearing about this from a lot more people than just you. Unfortunately there is nothing in the crash report that points to any cause, and the provided steps to reproduce don't work for me (or presumably anyone else), so currently we have nothing at all to go on. Can you press F12 and check the browser console for any error messages? Further, try disabling any browser extensions, since they can interfere with Construct and cause problems.

**Comment by Sanguinarias** [comment] 2021-01-19 12:12
I know I may be the only one, my classmates do not have this problem at all.
My extensions are not the problem, since I tried to use it on a brand new Chrome browser version.

I forgot to tell that I have a lot of issues in the console for some reason, so here is a screenshot :

![Capture](https://user-images.githubusercontent.com/73843423/105033031-dbba3400-5a57-11eb-9dc4-9ade2f84dbcb.JPG)

**Comment by Sanguinarias** [comment] 2021-01-19 12:15
Here a screen after the crash, from Chrome (clean install) :
![Capture2](https://user-images.githubusercontent.com/73843423/105033412-5e42f380-5a58-11eb-9976-b0fa5c7ebe76.JPG)

**Comment by AshleyScirra** [comment] 2021-01-19 12:27
The first screenshot includes errors produced in scripts named onloadwff.js and element-collapser.js, which are not part of Construct. These must have been added by a browser extension. If you are on a school network, perhaps the network administrator enforces this browser extension. I'm afraid there's not much we can do about it - we'd at least need to know the browser extension in use, and it may be that the problem is with the browser extension itself and therefore out of our hands.

The second screenshot appears to also show a browser extension interfering with the URLs Construct is requesting, with the same implications as I just mentioned.

I'm afraid the evidence is this is not caused by Construct itself and without more detailed technical information there is nothing we can do about this, so closing this report. Perhaps you could get your network administrator involved to investigate this.

**Closed by AshleyScirra** 2021-01-19 12:27 UTC
Labels: can't reproduce

**Comment by AshleyScirra** [comment] 2021-01-19 15:12
Based on a very similar report in #4490, this might be Kaspersky Internet Security breaking Construct. This seems to have happened before and nobody seems to be able to figure out why, including Kaspersky. See [this forum thread](https://www.construct.net/en/forum/construct-3/general-discussion-7/issues-loading-construct-150535) for more details.
