### ISSUE TITLE
fullscreen no longer works at start of layout (NWJS)

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#4204] opened 2020-09-11 01:07 UTC
![image](https://user-images.githubusercontent.com/5744908/92835461-94bf9080-f41e-11ea-9f54-590ebb221f34.png)

Use to be able to set game to fullscreen at startup with exported NWJS games, but in recent times it's just been opening as a window as if that action did not exist.

(using latest beta and nwjs 48.1)

____________

A capx with that line of code [fullscreen.zip](https://github.com/Scirra/Construct-3-bugs/files/5205510/fullscreen.zip)

**Comment by simstratic** [comment] 2020-09-11 06:08
@alstajj looks like a duplicate of #4204 - been testing this in my own project too - but a couple of workarounds that might help you for now:

- use NW.js version 0.45 instead (looks like bug started in 0.46)
or
- request fullscreen after a user input (mouse or keyboard press)

**Comment by alastajj** [comment] 2020-09-11 07:11
thanks, I'll close then. 

It's a shame that NWJS always introduce new issues when everything was perfectly fine before.

**Closed** 2020-09-11 07:12 UTC
