### ISSUE TITLE
AJAX lastdata not loading Json files content into dictionary in debug apk generated from R138-2 (but work in preview mode on PC)

### ISSUE THREAD

**Issue by eonianvr** [Scirra/Construct-3-bugs#2655] opened 2019-02-25 19:44 UTC
## Problem description
After loading a json with an AJAX request project file,  AJAX.LastData is used to parse the data into a dictionary. 
It doesnt seem to even load the data when you  generate a debug apk from r138-2 (but work in browser preview on PC)
Json were created inside the Construct 3 editor.

## Attach a .c3p
https://drive.google.com/file/d/17qrYPF8VFihqsgVI3PlQCyzN-oH29iHV/view?usp=sharing

## Steps to reproduce

1. open the capx in R138-2
2. generate a debug apk  
3. spin the screen with your finger 
it will force 2 debug text field - (Event 71 action 4 and 5) to be populated with 2 key value from Dictionary_gamecardsinfo which should have the data from gamedata.json.
4. open the bottom control window using the little handle at the bottom of the screen AND notice on the right of the control window  that the 2 debug number are zero when they should be 1 and 77 (key qdownwithjoker and  qupwithjoker from Dictionary_gamecardsinfo)

**INFO:**
- The code loading the JSON files into the dictionaries is from is on event 4 to 32
- Note that it works fine when running the game in debug preview mode  and the 2 control value are filled after spinning the wheel

## Observed result
Json data are not loaded when running the debug apk (or they are but dictionnaries are not populated)

## Expected result
loading the json files and populate their respective  dictionaries with the data

## More details

see ticket 2651

**Affected browsers/platforms:** 
* Chrome: NO
  debug apk: YES

**First affected release:** 
Constuct 3 r138-2 release
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2019-02-26 11:11
This project crashes on load for me - assigning to @shortercode to investigate that.

Other than that, the project does not comply with our guidelines: it uses a few third-party addons which could cause the problem, and it has lots of events and objects, so it could simply be a mistake in the events (e.g. passing an invalid or empty URL to download). Please see the bug report guidelines.

**Comment by shortercode** [comment] 2019-02-26 16:24
@AshleyScirra is it crashing when you open the project, remote preview or opening an APK made with the project?

**Comment by AshleyScirra** [comment] 2019-02-26 16:35
It crashes the editor when opening the project:

```
Uncaught (in promise) TypeError: Cannot add property shouldEmitResizeEvent, object is not extensible
    at Dictionary.TriggerResizeEvent (:60000/components/editors/dataEditor/tableView/Table.js:441)
    at Column.Resize (:60000/components/editors/dataEditor/tableView/Column.js:49)
    at Dictionary.DeserializeCustomisation (:60000/components/editors/dataEditor/tableView/Table.js:908)
    at new DataEditor (:60000/components/editors/dataEditor/dataEditor.js:105)
    at Function.New (:60000/lib/misc/jsutil.js:331)
    at DataEditorManager.OpenFile (:60000/components/editors/dataEditor/dataEditorManager.js:66)
```

**Comment by eonianvr** [comment] 2019-02-26 17:33
the project open fine in the construct editor for me.
I can give you the debug APK. Is is what you ask?
I will clean up the addons asnd send you a new version. But are the addon in the editor compiled with the apk even if not used?
the only unoffical plugin I use in the app is [http://blackhornettechnologies.com/construct2/plugins/BHTSmartRandom.aspx](url). 

The first thing the project do (System >> on start of layout) is to load the data from the json files to the dictionaries. and that is really the problem I'm reporting here. It works in preview mode but not when generating a debug apk

**Comment by AshleyScirra** [comment] 2019-02-26 18:16
Please see the bug report guidelines about providing a minimal project.

**Comment by eonianvr** [comment] 2019-02-26 18:21
ok i removed any unofficial plugin even if they were not used.
I cleaned up the code and now all json files are loaded first on start layout before anything else

Still, it works in debug preview but not when generating a debug APK.

please find below new c3p project (r139). Could you let know if it still crash the editor and if you find the same issue?
[https://drive.google.com/file/d/1lNxrUtBUVeJbVHWMugLdUnBQWG0IuPt7/view?usp=sharing](url)

**Comment by AshleyScirra** [comment] 2019-02-26 19:01
That project still uses a third-party addon (Chance) and is still not a minimal project. Please see the bug report guidelines about providing a minimal project.

**Comment by eonianvr** [comment] 2019-02-26 19:47
ok so there is now pretty much nothing left in the project except loading on json file on layout start, then populating the dictionary and a few control text field
chance plugin removed. 
I was hoping it would work but still same unexpected result when testing as a debug apk.


[link here to cp3 ](https://drive.google.com/file/d/1lNxrUtBUVeJbVHWMugLdUnBQWG0IuPt7/view?usp=sharing)

[link here to debug APK](https://drive.google.com/file/d/1B5yLvdZJp-TJioTqFZvg9YNzG9cx-ytw/view?usp=sharing)

**Comment by eonianvr** [comment] 2019-02-26 21:42
Ok guys, i did better. I reconstructed the project from scratch in R136 and R136
the one in R136 works fine as a debut apk
the one in R139 doesnt.

here are both file for you to test:
[R136](https://drive.google.com/open?id=1i1nTKdm6QVI7iLnI3JSnaN7U2AMx503z)

[R139](https://drive.google.com/open?id=1oGmYlmozgP1mdWe6I4Tn-C5MmUdI-w4k)

**Comment by eonianvr** [comment] 2019-02-28 14:30
any news on this issue guys?

**Comment by eonianvr** [comment] 2019-03-01 04:30
question: in the meantime is there any method to downgrade my project to R136 until you solve this issue?

**Comment by shortercode** [comment] 2019-03-01 15:07
@eonianvr I'm looking into it now, had moved onto other bugs as we didn't have an initial repro.

It's possible to edit a project file to open in an older version, but depending on what has changed since that release it may corrupt the project. You can probably find details on the forum.

**Comment by shortercode** [comment] 2019-03-01 15:36
Looks like a regression caused by some refactoring for the BinaryData plugin interface. Should be fixed in the next beta release.

**Closed by shortercode** 2019-03-01 15:36 UTC
Labels: ignored guidelines

**Comment by eonianvr** [comment] 2019-03-01 16:46
can you point me out to the forum article to attempt to downgrade properly? (as a reward for this bug report) thanks!

**Comment by shortercode** [comment] 2019-03-01 16:52
https://www.construct.net/en/forum/construct-3/how-do-i-8/android-cordova-webgl-2-issues-141769#forumPost966077

**Comment by eonianvr** [comment] 2019-03-01 19:12
thank you. 
didnt' work thought, I get an obscure  "invalid combo item" message from construct 3 when trying to open the project in R136 after following the guideline to downgarde from R139 to R136. I guess I will have to wait for the fix on this problem with the next release

**Comment by shortercode** [comment] 2019-03-01 19:36
Well as I said, they aren't guidelines. More of a brief description on
hacking a project file which will possibly end up with a corrupt project.
It sounds like something in your project relies on a new feature, so cannot
be downgraded. The issue should be resolved in the next release, so you
won't have to wait long.

**Comment by eonianvr** [comment] 2019-03-03 19:45
thank you Shortercode!
