### ISSUE TITLE
The Button object doesn't respond to mouse on clicked anymore

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#5689] opened 2022-05-10 18:46 UTC
The Button object doesn't respond to _Mouse on object clicked_ anymore.
But it does still respond to _Button on clicked_.

I checked some older Construct versions and there it still worked. So it seems like it got introduced recently, probably with the additions to the html elements.

It seems to affect other form controls as well (list, textInput, sliderBar, etc...), but I didn't test that thoroughly.

**Comment by XHXIAIEIN** [comment] 2022-05-11 06:15
https://github.com/Scirra/Construct-3-bugs/issues/5669

**Comment by AshleyScirra** [comment] 2022-05-11 09:38
Duplicate of #5551. This was actually a bug and was not supposed to work.

**Closed by AshleyScirra** 2022-05-11 09:38 UTC
Labels: duplicate

**Comment by F3der1co** [comment] 2022-05-11 11:20
I see, I would suggest either adding a warning or not showing form-controls in the "on object clicked" dialog.
As this seems a bit counter intuitive.
