### ISSUE TITLE
Firefox issue, collision polygon vertex value not updating or displaying correctly while editing 

### ISSUE THREAD

**Issue by ruskul** [Scirra/Construct-3-bugs#5536] opened 2022-03-19 23:04 UTC
---
name: Firefox issue, collision polygon vertex value not updating or displaying correctly while editing 
about: Display bug in Firefox
title: ''
labels: ''
assignees: ''

---

## Problem description

When opening the sprite editor and clicking collision polygon editing... After clicking a vertex, the info panel incorrectly displays the Y value of a vertex.  (See image).  This works on a completely new file, and in every project I have.  The problem doesn't exist when I try it in Chrome, only Firefox.  There is no need to provide a project file in this case as any project will do.

Clicking the Y value field and entering a number and pressing enter causes the value to sometimes update correctly thereafter while dragging that vertex around.  If another vertex is selected the problem resumes. 

## Attach a .c3p

No.C3P required in this case.  It is an editor side bug in the Firefox browser, possibly even a Firefox bug.

## Steps to reproduce

1.  Create a Sprite.
2.  Edit a Sprite collision vertex
3.  Note the Y value display

## Observed result

The Y value field for the vertex fails to update correctly (not at all)

## Expected result

The Y value and arrows should remain visible.

## More details

**Affected browsers/platforms:** 
FireFox

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE
Platform information
Browser: Chrome
Browser version: 99.0.4844.74
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36
C3 release: r285.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 142 gb
Storage usage (approx): 25 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-25.20.100.6446)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by DiegoScirra** [comment] 2022-03-20 18:48
Duplicate of #5501. Fixed in beta r286.

**Closed by DiegoScirra** 2022-03-20 18:48 UTC
Labels: duplicate
