### ISSUE TITLE
Save problem - Cannot read property '!Fxi' of undefined

### ISSUE THREAD

**Issue by TombasOnly** [Scirra/Construct-3-bugs#1328] opened 2018-02-27 10:16 UTC
## Problem description

Construct 3 r87, save works
r88, nothing changed in project, but save didn't work, and end with error:
Cannot read property '!Fxi' of undefined
Console log bellow

## Steps to reproduce

1. I just open project in r88, previsously saved in r87
2. And try tu save it, but it end with error

## Expected result

Project saved

## Affected browsers

* Chrome: yes

## Console log

main.js:168 [Project] Exception saving:  TypeError: Cannot read property 'ǃFxi' of undefined
    at n.ǃzx (main.js:63)
    at t.ǃPWl (main.js:63)
    at window.ǃwAc.ǃwyr (main.js:168)
    at Function.ǃwrC (main.js:168)
    at m.ǃwrX (main.js:168)
    at <anonymous>

![saveproblem](https://user-images.githubusercontent.com/31991351/36723137-b3684c56-1baf-11e8-9004-64bf07affa1e.png)

**Comment by AshleyScirra** [comment] 2018-02-27 11:51
Duplicate of #1326

**Closed by AshleyScirra** 2018-02-27 11:51 UTC
