### ISSUE TITLE
Tilemap Bar not showing Tiles

### ISSUE THREAD

**Issue by renerenekk** [Scirra/Construct-3-bugs#1266] opened 2018-02-05 19:46 UTC
## Problem description

Tilemap Bar not showing any Tiles. Only when undocking the bar and docking the
floating window somewhere else in the layout.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Start Construct
2. Create Tilemap
3. Open Tilemap Bar

## Observed result

Tilemap Bar not showing any Tiles. But "0° Rotation" which usually is located
under the tiles, is right under the toolbar. Only the Tiles are missing.

## Expected result

See Tiles.

## Affected browsers

* Chrome: yes
* Firefox: yes

## System details

<details><summary>View details</summary>

Windows 7, GeForce GTX 1070 with latest Driver

</details>

**Comment by DudetteonTheEdge** [comment] 2018-02-05 21:14
OK. This must have been  a browser glich because it is working today. You can close this issue.

**Comment by Kyatric** [comment] 2018-02-06 11:21
A user reported :

![image](https://user-images.githubusercontent.com/15985625/35856934-cbbeaf26-0b37-11e8-977b-55ca3a703c4c.png)
![image](https://user-images.githubusercontent.com/15985625/35856943-d1f3a338-0b37-11e8-9e5a-64f8f5d74268.png)

"I'm using Safari (11.0.3) with no plugins on macOS (10.13.3). 
I've gotten no messages about WebGL not being supported, and my drivers are up to date."

---
Another user reported:

"Im using Construct3 with Chrome and Firefox. When creating a Tilemap Object
it won't even show the default example tilemap. In the Tilemap-Editor its
not displaying any tiles, only "Rotation: 0°" right under the Tilemap Toolbar.

With Construct2 everything works as expected."

"For me it only happens on Win7 with chrome and Firefox.
On Win10 with Chrome and Mac (osx el capitan) and chrome it works fine."

**Comment by DiegoScirra** [comment] 2018-02-06 11:43
I was able to reproduce the bug in Windows 10 using Firefox.

**Comment by DiegoScirra** [comment] 2018-02-09 15:19
Fixed in r86

**Closed by DiegoScirra** 2018-02-09 15:19 UTC
