### ISSUE TITLE
Collision Box Reverts Back After Changing / Then Cycling Frames/Animations

### ISSUE THREAD

**Issue by brainwavecreations** [Scirra/Construct-3-bugs#5936] opened 2022-07-29 00:58 UTC
Bug Video: https://youtu.be/NdMYUgw0CC0

Problem description: 

The Collision Box will move back to it's default shape if importing multiple images for a new animation.  Then Set to Animation, or Set to All Animations.  I did not test this one on existing images that were already added and changed.   Also, if you Preview the Animation and Close Animations Editor, or just Close Animations Editor it is fine when you return.  At least from what I've observed since Monday's release.

Attach a .c3p:  Attached
[Bugged 1 - Player Initialization & Player Animations.zip](https://github.com/Scirra/Construct-3-bugs/files/9215131/Bugged.1.-.Player.Initialization.Player.Animations.zip)

Steps to reproduce

1. Add New Animation
2. Change Collision Box
3. Set to Animation and/or All Animations
4. Cycle through frames/animations without previewing and closing animations editor, or just closing the animations editor
5. Watch as the Collision Box moves back to it's original whacky design while cycling Frames/Animations

Observed result:

Watch as the Collision Box moves back to it's default estimate while cycling Frames/Animations

## Expected result

Collision Box should stay where it is placed/shaped, when set to animation/animations on new animation

More details: None.  It's explained pretty well above.

**Affected browsers/platforms:** 
Windows 10, all chromium browsers I have (Chrome, Brave)

Noticed it with r304

**First affected release:** 
Noticed it with r304

System details:
Windows 10, all chromium browsers I have (Chrome, Brave)

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 103.0.5060.134
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 195 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2022-07-29 16:19
Closing this as it's basically a duplicate of #5935

**Closed by DiegoScirra** 2022-07-29 16:19 UTC
Labels: duplicate

**Comment by brainwavecreations** [comment] 2022-07-29 18:46
My bad, buddy.  I looked through the bug reports real quick last night, but hadn't noticed that one.  One, again.  Thank You, so much for all of your work, @DiegoScirra !  Every time I report a bug here, you pick it up straight away.  It's always much appreciated :)
