### ISSUE TITLE
Tween, angle. Confused behaviour

### ISSUE THREAD

**Issue by ArtRow** [Scirra/Construct-3-bugs#4837] opened 2021-05-20 00:19 UTC
It seems all angle calculations in Construct use a pattern finding a short way. If I want to rotate an object at 181 degrees clockwise, it will be rotated _counterclockwise_ at 179 degrees. It confuses because some things become are impossible to be created. You can open the file and try it to use rotary dial.

[TweenBehaviour.zip](https://github.com/Scirra/Construct-3-bugs/files/6512006/TweenBehaviour.zip)

## Steps to reproduce

1. Open file and click on the buttons to start rotate an object.
2. Rotates more than 180 degrees behave unexpected.

## Observed result

All rotations with value more than 180 degrees start rotating in the opposite direction.
Also, all values more that 360 degrees are cut to 360 coordinate system. E.g. value 560 becomes to 200 and path to rotate will be shortest (160 degrees) in the opposite direction.
Object with value 360 degrees won't be rotated

## Expected result

If value is 210, so object should rotates through 210 degrees, not 150 in opposite direction. To change rotation we can use sign minus (-210 degrees to rotate otherwise). I didn't find any way to rotate object more than 180 degrees in direction I need.
If value is 720, so object can be rotated twice. Now it does nothing because 360, 720, 1080 etc. are equal 0 in current situation.

Will be that calculation system updated? Thanks

## More details

**Affected browsers/platforms:** 

**First affected release:** r241 Stable (Honestly it was observed about more than half an year ago, but filed just now)

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 90.0.4430.212
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
C3 release: r241 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 35 gb
Storage usage (approx): 1.5 gb (4.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5167)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by dop2000** [comment] 2021-05-23 04:47
I think the behavior is working correctly. Yes, it's limited to 180 degrees, but this way there is no ambiguity - it finds the shortest route from the start to the target angle. 
Besides, changing it now will likely break lots of existing projects.

There probably needs to be a separate property in "Tween (one property)" action - "Relative angle". When you use "Relative angle", it will rotate the object the specified number of degrees (clockwise, or counter-clockwise depending on the sign).
Of course, you can do the same with "Tween value" action, but "Relative angle" would be easier to use.

**Comment by ArtRow** [comment] 2021-05-23 14:49
It was ok before Tween behaviour has been added. We didn't see transition. But now objects have it. Have you tried test file? There is no any way to rotate objects how you want (I couldn't find anyone). Tween rotate option looks very limited with transitions. 

About lots of projects. I found that issue more than half year ago and thought someone will report it. But it seems there is no lots of projects or that function used by small amount. Anyway, how it will be updated depends on creators, of course. Probably, It can be automatically transformed into new pattern, like new functions were.

**Comment by dop2000** [comment] 2021-05-24 00:30
@ ArtRow What if you need to rotate Sprite1 to Sprite2.angle with tween? You don't know the current sprite angles, they may be random. Sprite1.angle may be (-160) and Sprite2.angle may be (+160). 
How do you tell the Tween which direction it should go: 40 degrees CCW, or 320 degrees CW ?
So the current behavior when Tween chooses the shortest route between two angles is correct.
If you need more control - use "Tween Value" action. See this [demo](https://www.dropbox.com/s/0kzws8ve4vr18m4/PredictableWheelOfFortune.c3p?dl=0)

**Comment by ArtRow** [comment] 2021-05-24 07:17
As I said short path was ok when there weren't transitions. Now it confuses.
If I enter value 200, so why a path is 160 in opposite direction. **That's the point**.

If you enter X move position equal 200, it will be moved by path equal 200 in positive direction. If -200, negative direction. Right? So why radial movements should be different? 200 it's 200, not -160; 360 it's 360, not 0; 480 it's 480, not 120, etc. 

Thanks for demo

**Comment by dop2000** [comment] 2021-05-24 07:31
You are talking about relative value. Tween works with absolute values. 
When you give it two absolute angles, Tween behavior doesn't know which direction you want to rotate the object, that's why it selects the shortest route.

**Comment by ArtRow** [comment] 2021-05-24 08:54
You still can't get my point. "200 is the same as -160 degrees" yes, BUT I'm talking about HOW object reaches that point. And if I put value 200, I expect that object will be rotated by 200 degrees.

**Comment by dop2000** [comment] 2021-05-24 09:20
> And if I put value 200, I expect that object will be rotated by 200 degrees.
Again, you are talking about a relative angle! 
Tween works with absolute values. If you put "200" as the target angle, it will rotate to this exact angle the shortest way.

**Comment by ArtRow** [comment] 2021-05-24 09:49
Positions values can work with relative and absolute values. Why radials shouldn't do the same? Why that tool should be limited?

**Comment by dop2000** [comment] 2021-05-24 10:26
Tween works with absolute values. The difference between tweening to position and tweening to angle is that there are two ways to rotate to target angle. Tween chooses the shortest.

**Comment by DiegoScirra** [comment] 2021-05-24 10:54
I do think this is lacking in the tween behaviour, the problem is that it is only an issue for angles, and I am not inclined to adding special properties or similar specific features just for angles.

There is a way around it though, you can use a value tween, as long as the tween is playing you set the angle of the instance to the value of the tween.

https://www.dropbox.com/s/w9tuxck90kxzvja/TweenValueAngle.c3p?dl=0

It's a little bit more convoluted, but it works just fine.

**Comment by pigmalien** [comment] 2021-05-28 16:15
That's just the way interpolating angles works. You could take the above project and set the angle via anglelerp(0,220,Sprite.Tween.Progress("value")) and it would go the other way.

**Comment by DiegoScirra** [comment] 2021-06-07 11:22
Closing this as there is a clear way around the problem.

**Closed by DiegoScirra** 2021-06-07 11:22 UTC
