### ISSUE TITLE
Menu items move slightly on scrolling through

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#996] opened 2017-11-07 17:12 UTC
## Problem description

This is a minor issue that I've spotted for quite some time now (r61 or 62). I cannot reproduce it on my laptop, but on my desktop even after reinstalling Chrome the problem persisted.

If I open a menu, anything that's in it moves slightly left and right. This works with almost any menu.

For the attached gif, if I go in the other submenus they don't move anymore, unless I close and reopen the menu. It seems that once they moved and stopped, they won't continue doing so on that opened menu session.

## Attach a .c3p

![menuproblem](https://user-images.githubusercontent.com/7268697/32507193-83a013e0-c3ef-11e7-93ab-79c7fe66d9d0.gif)

## Steps to reproduce

1. be unlucky
2. open C3
3. open the menu
4. scroll through it

## Observed result

Notice how the icons move slightly left and right.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r66.2
Language setting: en-US

Local storage
Storage quota (approx): 95 mb
Storage usage (approx): 17 mb (17.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2017-11-07 18:46
Duplicate of #706. Seems tricky to reproduce reliably so far though.

**Closed by AshleyScirra** 2017-11-07 18:46 UTC
