### ISSUE TITLE
deleting large amounts of frames at once can lead to crash

### ISSUE THREAD

**Issue by Ldwebster111** [Scirra/Construct-3-bugs#4053] opened 2020-07-22 05:44 UTC
## Problem description

When working with large spritesheets, the game has a tendency to crash after importing the sheet then deleting the unwanted frames. This seems to happen about 1 in every 10 times for me. I managed to capture this happening on video, although I only started recording right before the crash as I had a feeling it might crash and decided to record in case.

## Attach a .c3p

I'm not really sure this is applicable. I've attached a video of this happening instead.

[2020-07-22 15-34-15.zip](https://github.com/Scirra/Construct-3-bugs/files/4958054/2020-07-22.15-34-15.zip)

## Steps to reproduce

1. import a large spritesheet into a project. I usually duplicate the animations at this point so I only have to import once, then delete the unneccesary frames from each animation
2. select a frame near the end, then hold shift and select the first frame, highlighting every frame in between.
3. press delete, this may crash the engine, though it's not a 100% thing

## Observed result

see video

## Expected result

not to crash

## More details

[2020-07-22 15-34-15.zip](https://github.com/Scirra/Construct-3-bugs/files/4958054/2020-07-22.15-34-15.zip)

Chrome, stable channel. This has been happening for a long time, I posted this bug last year but the issue was closed without resolving. Hence why I'm adding video evidence this time.

## System details

Win 10 64bit, Intel i5, Nvidia 970GTX

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: animation frame has no content @ Error: animation frame has no content at r.ǃkAz (https://editor.construct.net/r204-2/projectResources.js:1:105863) at r.ǃxp (https://editor.construct.net/r204-2/projectResources.js:1:108407) at https://editor.construct.net/r204-2/projectResources.js:1:1001981 at async Function.ǃIiD (https://editor.construct.net/r204-2/projectResources.js:1:988648)
Stack: Error: animation frame has no content at r.ǃkAz (https://editor.construct.net/r204-2/projectResources.js:1:105863) at r.ǃxp (https://editor.construct.net/r204-2/projectResources.js:1:108407) at https://editor.construct.net/r204-2/projectResources.js:1:1001981 at async Function.ǃIiD (https://editor.construct.net/r204-2/projectResources.js:1:988648)
Construct 3 version: r204.2
URL: https://editor.construct.net/
Date: Wed Jul 22 2020 15:34:25 GMT+1000 (Australian Eastern Standard Time)
Uptime: 7930.1 s

Platform information
Browser: Chrome
Browser version: 84.0.4147.89
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
C3 release: r204.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment] 2020-07-22 07:17
How many frames are your animations using?

**Comment by Ldwebster111** [comment] 2020-07-22 07:39
The spritesheet itself in this case I believe was 11 x 15 frames at 48x32 each, and the specific animation that crashed was 8 frames.

Seems to only happen when a lot of frames are deleted at once (think i deleted 157 in that vid). Never had it happen when deleting a few from a large sheet.

**Comment by DiegoScirra** [comment] 2020-07-22 14:10
This one looks hard to pin down. I created a 480x520 image divided in 20x20 squares. It has 24 rows and 26 columns, which when imported make up for 623 different frames.

Asides from some janky behaviour when you make a large selection of frames, I can't get the Animations editor to crash, so there must be something else to this issue asides from a large amount of images.

**Comment by AshleyScirra** [comment] 2020-07-22 14:39
@Ldwebster111 - please always attach a project to reports as per the guidelines, usually if it is missing we cannot do anything about your report.

**Comment by Ldwebster111** [comment] 2020-07-22 23:29
[2020-07-23 09-18-59.zip](https://github.com/Scirra/Construct-3-bugs/files/4963200/2020-07-23.09-18-59.zip)

I'm at work and decided to see if I can recreate the same crash on a different computer (work laptop this time), which I was able to do. win 64bit, Intel i5-8250U, Intel UHD graphics

I captured the entire process, starting from a blank project, right up to the crash. There's nothing in this project except the sprite. Also included a copy of the spritesheet that I used that cause the crash. importing at 30 by 30 cells.

Interesting that the program didn't crash when I first deleted a bunch of the frames, but then when I continued deleting smaller amounts of frames, I was able to trigger the crash again.

**Comment by DiegoScirra** [comment] 2020-07-23 11:31
I have been able to reproduce the crash, but not consistently. It seems to be working properly most of the time. There is a lot of asynchronous code around where the crash happens, so it's going to be hard to figure out exactly what is happening.

**Comment by DiegoScirra** [comment] 2020-07-23 11:36
I have noticed a bunch of things around the issue that don't seem quite right, like the current active frame going crazy when you select a large amount of frame using **SHIFT**.

I'll start by working on the more obvious surrounding problems, and maybe i'll be able to find out the real issue.

**Comment by DiegoScirra** [comment] 2020-07-29 22:26
@Ldwebster111 Have you noticed any improvements in the latest beta?

**Comment by Ldwebster111** [comment] 2020-07-31 04:17
@DiegoScirra Just spent about 10 minutes trying to make this crash on the beta and couldn't reproduce it. 

Also seems like there's a lot less lag when selecting large amounts of tiles at once too, which is nice.

Cheers

**Comment by DiegoScirra** [comment] 2020-07-31 12:41
Closing this.

@Ldwebster111 if you happen to come across a similar problem again, just open a new issue.

**Closed by DiegoScirra** 2020-07-31 12:41 UTC
Labels: difficult
