### ISSUE TITLE
Desktop C3 Stable Saving Project and Loading Issue

### ISSUE THREAD

**Issue by shubhamrathi9** [Scirra/Construct-3-bugs#4139] opened 2020-08-20 08:08 UTC
## Problem description
With new stable release of C3 v210 onwards, when we open an existing project first it shows a white blank popup (see screenshot attached) instead of loading popup!
Then when i hit Ctrl+S, it asks for a location to save for the first time, while before it simply used to save as it ideally should!
PS : I use latest nwjs-sdk-v0.47.3-win-x64

## Attach a .c3p
[Blank C3 File](https://drive.google.com/file/d/1D_9lYJ8Wsj7X7z_iNDxBaC-fkCLKAx9W/view?usp=sharing)
[Scrn 1](https://drive.google.com/file/d/1SLrRkhsoSBK0rJPX0EJOLdkHP8tyFJYS/view?usp=sharing)
[Scrn 2](https://drive.google.com/file/d/1R-1N4r-jPBxgji6u6qh0yEI11lsLb9sY/view?usp=sharing)

## Steps to reproduce

1. Open Project file in the latest stable desktop version in windows, see a blank popup instead of loading!
2. Once opened, save the project (i used Ctrl +Save) > It will ask for a location to save!

## Expected result
Loading should show instead of blank popup and the project should save automatically to the same location it is opened from!

## More details

**Affected browsers/platforms:** 

**First affected release:** 
Desktop Stable Version 
## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.47.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.47.3 (like Chrome/84.0.4147.125)
C3 release: r210.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 545 gb
Storage usage (approx): 723 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2020-08-24 11:55
Looks like a duplicate of #4096. It's an NW.js/Chrome bug that appears to already be fixed in the next release.

**Closed by AshleyScirra** 2020-08-24 11:55 UTC
Labels: duplicate
