### ISSUE TITLE
Tiled Background and 9-Patch objects stop updating collision polys.

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#4599] opened 2021-02-23 12:29 UTC
## Problem description

Hi! If you resize a Tiled Background or 9-Patch a couple of times, their collision polys won't update anymore and won't cover the entire bounding box size.

## Attach a .c3p

[Collision Polys Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/6028840/Collision.Polys.Bug.zip)

## Steps to reproduce

1. Create a new 9-Patch object and fill it with a solid color.
2. Enable "Show collision polygons" in the editor, so you're able to see the changes.
3. Open the same 9-Patch object in the animation editor and reduce its width in half with the "Keep aspect ratio" off and "Align Center" in the image type.
4. Close the animation editor.
5. Open the 9-Patch object one more time, but now double its width, so it's back to its previous size. Use the same settings as before.
6. Close the animation editor and watch the weird collision polys.

Example: https://i.imgur.com/WHfiRRn.png

## Observed result

Collision polys don't cover the entire bounding box as they did before.

## Expected result

Collision polys to cover the entire bounding box as they did before.

## More details

**Affected browsers/platforms:** Chrome (88)

**First affected release:** R234.4 (Stable)

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2021-02-24 16:02
I can reproduce. It looks like it's drawing the correct collision polygon, but the object has an invalid collision polygon: 9-patch and Tiled Background don't support altering the collision polygon, but it seems possible the animation editor is changing the polygon anyway, perhaps when using the resize tool. Assigning to @DiegoScirra to check.

**Comment by DiegoScirra** [comment] 2021-03-01 11:44
Fixed in the next beta.

**Closed by DiegoScirra** 2021-03-01 11:44 UTC
