### ISSUE TITLE
Pasting values in data editor no longer works properly

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#5399] opened 2022-01-26 04:11 UTC
I use to be able to copy data from my spread sheet program and paste it into Construct, but something has changed and now it only pastes the data into a single cell:

Lets copy all these cells of data from this sheet:
![image](https://user-images.githubusercontent.com/5744908/151102025-6bd060fe-94f3-417f-8fce-d475d1b528e5.png)

Now in C3 data editor (for my json file) it just pastes it in one cell:
![image](https://user-images.githubusercontent.com/5744908/151102268-31e1f03e-a9b9-490a-85e5-d8583d49c392.png)

I also don't recognize/understand why it says all that stuff in it. But when I paste in notepad it all shows up just fine, so it's not a new issue with my clipboard.

I use to be able to easily fill this sheet with data. 

r280

**Comment by alastajj** [comment] 2022-01-26 05:02
I restarted my computer and tried again, this time it doesn't paste anything in the cells, it's as if it's blank.

But there is stuff in my clipboard, so it's definitely a new problem with the data editor, since I can even paste the values into notepad just fine:

![image](https://user-images.githubusercontent.com/5744908/151106734-608d5a53-8a4a-40a1-864b-a8b9715d79d7.png)

**Comment by DiegoScirra** [comment] 2022-02-03 15:35
Can't reproduce this one, I tried copying and pasting from Google Sheets and it seems to work properly. From looking at the screenshot, what you ended up pasting looks like something that was previously copied from an event sheet.

Have you ever denied a permission to use the system clipboard? In that case, C3 falls back to using an internal clipboard, so you can at least copy and paste stuff within Construct, but copying things from other programs won't work.

You can try checking the state of the clipboard permission in Chrome by typing **chrome://settings/content/all** into the address bar and then looking for the permissions **editor.construct.net** has.

**Comment by alastajj** [comment] 2022-02-04 02:34
@DiegoScirra  that's weird as! The permissions appear to be fine to me ("allow"). 

I can't copy from either Libre Office or Google spreadsheets. It's just blank.

Thanks for helping.

Strangely, I CAN copy to the json file editor, but NOT in the Array editor:

![image](https://user-images.githubusercontent.com/5744908/152462476-6cf25790-57ce-42f8-aa97-a3758cbe29db.png)

![image](https://user-images.githubusercontent.com/5744908/152462513-fe327b69-bcd6-481c-b7c1-b2b5204f8ef2.png)

![image](https://user-images.githubusercontent.com/5744908/152462606-9df376ea-704f-40e7-9405-ed90cc52a93b.png)

______________________________________________

I cannot copy and paste from the json file editor to the array editor either.

But ONLY from inside the array editor can I copy and paste values

![image](https://user-images.githubusercontent.com/5744908/152462830-07d998f8-0823-4834-966c-45dad3404770.png)

**Comment by alastajj** [comment] 2022-02-04 02:46
@DiegoScirra I discovered the version it stops working! After attempting to paste the values in many versions.

r270 is where the issue begins! You cannot paste into the array editor.

r269 and before, you can paste into the array editor.

I think this might be the broken change!

![image](https://user-images.githubusercontent.com/5744908/152463969-b44dda41-1c5c-459b-a092-6722b5377228.png)

**Comment by AshleyScirra** [comment] 2022-02-08 13:22
r282 is now out, please check again there.

**Comment by alastajj** [comment] 2022-02-09 02:18
Ok I just tested another computer and it works fine! 

On my main computer it's still broken. I can't paste from another source into the array editor (other editors are perfectly fine), not sure why this is happening to me for just this one editor. I can copy and paste data from within the array editor, but just not from any other source. Weird... 

Maybe it is some hidden permission setting that only affects the array editor.  (I'm using the installed chrome app.)

**Comment by DiegoScirra** [comment] 2022-02-09 11:39
Have you tried any of the versions in which pasting wasn't working in the computer that works?

As far as I know there aren't any other permissions and the array editor doesn't do anything special when pasting,

Have you checked the console to see if there are any messages, probably not, but it's worth a try.

**Comment by AshleyScirra** [comment] 2022-02-09 11:42
Make sure you haven't enabled the in-app clipboard in Construct's settings.

**Comment by alastajj** [comment] 2022-02-10 11:23
@AshleyScirra  thanks for that! 

Unticking that fixed the problem!
![image](https://user-images.githubusercontent.com/5744908/153397290-87860568-1cbb-48ce-9f55-3b5e682f23e5.png)


I thought that setting would be required to make it work. My mistake.

**Comment by AshleyScirra** [comment] 2022-02-10 11:50
OK, sounds like this is all sorted then, so closing.

**Closed by AshleyScirra** 2022-02-10 11:50 UTC
Labels: can't reproduce
