### ISSUE TITLE
GamePad Frezzes (C2 RunTime)

### ISSUE THREAD

**Issue by Tarek200** [Scirra/Construct-3-bugs#3401] opened 2019-10-09 14:47 UTC
GamePad gets stuck, it Doesn't move any more, it glues to the starting position
Once it freezes there is no way to unblocked it, gets stuck on the same position even if you change layouts and come back to the same layout it will be still stuck on that same position (X,Y) and the only way to unblocked is resetting the device.

## Attach a .c3p

[c3p](https://www.dropbox.com/s/7a5s3ccv1ulfmx1/Controller%20Bug1.c3p?dl=0)

## Steps to reproduce

1.Remote Preview the project from the first layout "Menu" Layout
2. Click the Green Square and keep tapping on it as much as you can until it loads the next layout
3. Once the next layout is loaded then touch anywhere on the screen so the GamePad gets positioned on your finger 

## Observed result

1-GamePad gets freeze, stuck, it Doesn't move any more, it glues to the starting position even if you touch on different Touch(X,Y) coordinates it will not follow your new touch(X,Y), it should follow your finger every time you touch.

2-Even if you change the layout and come back the GamePad it will be still stuck at the same (X,Y) coordinates that you left it before you change the layout

## Expected result

1-GamePad will not get freeze

2- Every time you make any touch the GamePad it should position itself on the New Touch(X,Y) coordinates that the finger touched

## More details

Tested on physical Devices:

**You should test on this device to be able to reproduce quick**
-Ipad: Pro 11 inch, iOs 13.1

**Also, it happens on these devices but less frequently so is hard to reproduce quick**
-iPhone: 6, 7, 8 plus, XS Max >>>>> iOs11, iOs12, iOs13

Its been happening for the last two years so most of the iOs are affected

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 77.0.3865.90
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
C3 release: r170 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 376 mb (2.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-10-09 15:42
Can you reproduce this in the C3 runtime? If not I'd rather not fix this - the workaround for the bug in Safari took significant architectural work which would be costly to repeat for the older runtime, which we're actively trying to phase out.

**Comment by Tarek200** [comment] 2019-10-11 12:12
Hi Ashley

On C3 RunTime is working as intended still I didn't see the GamePad Freeze yet so it looks like is working grate

I understand is a complicate bug and it will require a lot of work to fix but one thing I don't understand is why in c3 is working and not in c2? 
is not that both use Safari if I'm not mistaking?

Another important note:
It looks like the problem is coming from how long c2 takes to load the layout so the longer it takes the more often the GamePad it will Freeze.

Example using the same .c3p that I posted in my bug report:
If you remove all the TileMaps the layout it will load quickly and the GamePad it will not freeze.
There is something related to how long it takes the layout to load that makes the GamePad Freeze, I'm not sure if this info helps but logically it may be that the bug is not on Safari and is c2  otherways the bug it will occur on both RunTimes (c2,c3) if it was Safari'S fault no? what do you think

Here is a working example that doesn't freeze  is the same example I use  in my bug report I just removed all the TileMaps and testing on the (Ipad Pro) it works as intended no GamePad Freeze happened yet

[Capx](https://www.dropbox.com/s/uk9mfkvzso9wc10/controller%20bug2.c3p?dl=0)

**Comment by AshleyScirra** [comment] 2019-10-11 13:15
In the C3 runtime we switched to a more modern input API (Pointer Events) for touch input, which is supported in Safari 13+. This involved significant architectural work since we had to rewrite all the input code. The C2 runtime uses the older input API (touch events), which is the only one exhibiting a Safari bug that causes freezes (issue #2750).

Since the issue is fixed in the C3 runtime with Safari 13+, closing. If you want this investigated further please report it to Apple, since the underlying issue is a Safari bug.

**Closed by AshleyScirra** 2019-10-11 13:15 UTC
Labels: duplicate, external, safari
