### ISSUE TITLE
Cannot create new object if the name was invalid once

### ISSUE THREAD

**Issue by narFnarF** [Scirra/Construct-3-bugs#320] opened 2017-05-22 18:34 UTC
## Problem description
When creating a new object in the "Create new object type" dialog, if the user enters an invalid name (ex: a name with a space between words), Construct display a warning that the name was edited to be valid. Once that happen, the dialog won't allow the user to create the object. The dialog must be closed, then reopened and a valid name must be entered.
(https://cloud.githubusercontent.com/assets/3538115/26322934/077a03f8-3efb-11e7-8c12-900634aad078.png)

## Attach a .c3p
[peggle rpg 2.zip](https://github.com/Scirra/Construct-3-bugs/files/1019797/peggle.rpg.2.zip)
![2017-05-22 14_25_01-peggle rpg - construct 3]

## Steps to reproduce

1. Right-click in the layout > Insert new object
2. Select any object type (ex: Sprite)
3. Enter a name with spaces (ex: "enemy art")
4. Construct will automatically rename it to "enemyArt" and will display a warning
5. Click the Insert button

## Observed result
The Insert button does nothing. The dialog is not closed and the object is not created

## Expected result
The dialog is closed and the new object is created.

## Workaround
The user can create new object if the name entered is valid the 1st time when clicking Insert.

## Affected browsers
* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 90 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 745 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2017-05-23 10:53
Possible duplicate of #312

**Comment by AshleyScirra** [comment] 2017-05-24 11:51
Yep, duplicate, should be fixed in r31.

**Closed by AshleyScirra** 2017-05-24 11:51 UTC
