### ISSUE TITLE
Multiplayer module (concerns rooms disconnection/connection)

### ISSUE THREAD

**Issue by Macmachi** [Scirra/Construct-3-bugs#3281] opened 2019-08-29 20:17 UTC
## Problem description

I want that  all my players (PEER and HOST) to be able to leave a room and reconnect to the same room without restarting their game. Currently it's not possible. 

## Attach a .c3p

https://mon-partage.fr/f/52VcwDjn/ 

## Steps to reproduce

1. Login to the chat room on the login page
2. Exit the chat room with the "Leave..." button (I have created a HOST and a PEER that I disconnect with the button (both). I don't know if this happens if there is only one HOST)
3. You will be sent on a temporary layout (see if this step is faculative). But in my game it works like this
4. Wait to be returned from this layout to the layout login (it's automatic) 
5. Reconnect to the chat (the same room as at the beginning, but which is empty)
6. The connection is not successful (look at the chat)

## Observed result

It is impossible to reconnect to a room (that is supposed to be empty) with the same people after having already disconnected once.

## Expected result

Be able to join/ connect again (with the same players) to the empty room (after disconnecting the players) with the assignment of a host and a PEER again. 

## More details

I used the chat template (multiplayer tutorial 1) I just added 2 blocks of code for the button "leave..." which allows you to disconnect from signaling server and room for each groupe (HOST AND PEER).

**Affected browsers/platforms:** BRAVE (chromium web browser) on windows 10, Chrome (windows 10), with remote preview from C3. 

**First affected release:**  r163 (beta)

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.132
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 47 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-08-30 14:37
Please see the bug report guidelines regarding testing the latest version. Your report mentions r157. The latest release is r163, and we may have already fixed the issue there. Can you reproduce the issue in r163?

**Comment by Macmachi** [comment] 2019-08-30 16:19
@AshleyScirra I tried with r163 and no the issue is not solved.

**Comment by AshleyScirra** [comment] 2019-08-30 16:41
It looks like the problem is you try to do *Disconnect from signalling server* and *Disconnect room* simultaneously. They are two separate processes that each take some time to complete. You also cannot leave the room if you already disconnected from the signalling server, since there's no longer any way to tell the signalling server that you've left once you've disconnected. It works if you use these events instead:

+ Bouton: On clicked
-> Multiplayer: Disconnect from room

+ Multiplayer: On signalling left room
-> Multiplayer: Disconnect from signalling server

+ Multiplayer: On signalling disconnected
-> System: Go to OtherLayout

Closing as not a bug, your events were just not set up to talk to the signalling server correctly.

**Closed by AshleyScirra** 2019-08-30 16:41 UTC
Labels: not a bug

**Comment by Macmachi** [comment] 2019-08-30 18:20
@AshleyScirra Okay I tested it better but there is still a bug. If the peer reconnects first (before the host of the old room). He becomes the host until there is no problem. However, the host of the old room also becomes the host when he reconnect after the peer !
