### ISSUE TITLE
Full screen problem

### ISSUE THREAD

**Issue by Sirtaximan** [Scirra/Construct-3-bugs#2728] opened 2019-03-12 17:27 UTC
## Problem description

A gray line on the screen, C3 does not scale the screen

## APK: https://mega.nz/#!mQoFDI7S!WN7el3sWPGIiL-fEaIquVKasTq_n_h6R_5fwLGmAVFE

1.Export a .apk for android.
2.Install the game on a phone, run the game and press exit.
3.Run the game, the gray line will never disappear.

## Observed result

 The gray line prevents the game from scaling the screen

## Expected result

 No gray line should be visible.

## More details
This project was exported from C2.
If the data is deleted in the Chrome browser (on the phone), the bug restarts.

This happens on android

**Affected browsers/platforms:** 
Android
IOS?

 

**First affected release:**  In all the versions of C3 that I have tried.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DrSquidge** [comment] 2019-03-13 11:57
Potentially related to this thread: https://www.construct.net/en/forum/construct-3/how-do-i-8/problem-with-full-screen-141487

Posting for reference.

**Comment by shortercode** [comment] 2019-03-13 12:07
Hi @Sirtaximan I've tried to replicate this on a Samsung S8 and haven't had a lot of luck. I've tried multiple restarts, rotation, dropping out to recent projects, locking/unlocking etc.

Just to check, you are using the export as APK option and not building via an external tool? Could you perhaps provide a video of you reproducing this issue with this project, in case I am missing one of the steps.

**Comment by Sirtaximan** [comment] 2019-03-13 12:13
It is exported with C3, when I get home I will record a video. I will try to use different phones.

________________________________
De: Iain Shorter <notifications@github.com>
Enviado: miércoles, 13 de marzo de 2019 13:07
Para: Scirra/Construct-3-bugs
Cc: Sirtaximan; Mention
Asunto: Re: [Scirra/Construct-3-bugs] Full screen problem (#2728)


Hi @Sirtaximan<https://github.com/Sirtaximan> I've tried to replicate this on a Samsung S8 and haven't had a lot of luck. I've tried multiple restarts, rotation, dropping out to recent projects, locking/unlocking etc.

Just to check, you are using the export as APK option and not building via an external tool? Could you perhaps provide a video of you reproducing this issue with this project, in case I am missing one of the steps.

**Comment by kingpirux** [comment] 2019-03-13 17:59
same issue here

**Comment by Sirtaximan** [comment] 2019-03-14 11:51
I have uploaded a video, the phone uses Android 6.1, I will try to do more tests. In android 7.1 also happens.

Video: https://mega.nz/#!bJ4n3CYK!zQ2MSreNv8Y9bHXun-UBDpXRAyfD_Sp-t2wNmS3Bw7c

________________________________
De: Iain Shorter <notifications@github.com>
Enviado: miércoles, 13 de marzo de 2019 13:07
Para: Scirra/Construct-3-bugs
Cc: Sirtaximan; Mention
Asunto: Re: [Scirra/Construct-3-bugs] Full screen problem (#2728)


Hi @Sirtaximan<https://github.com/Sirtaximan> I've tried to replicate this on a Samsung S8 and haven't had a lot of luck. I've tried multiple restarts, rotation, dropping out to recent projects, locking/unlocking etc.

Just to check, you are using the export as APK option and not building via an external tool? Could you perhaps provide a video of you reproducing this issue with this project, in case I am missing one of the steps.

**Comment by shortercode** [comment] 2019-03-14 14:20
Thanks for the video. I can't reproduce on a S8 so will try a couple of other devices, I think it might be related to specific screen ratio or a timing problem.

**Comment by shortercode** [comment] 2019-03-14 16:31
Have managed to confirm this bug on a S2, I believe it's a duplicate of #2364 which I couldn't replicate when it was reported.

Going to try tinkering with the start up a bit and see if I can get any improvement. It looks like the webview is incorrectly sized, so I think it's a cordova issue. This device appears to have the graphics driver periodically crashing which might slow me down a bit. Quality software development by Samsung yet again!

**Comment by shortercode** [comment] 2019-03-15 12:30
After some additional reading it appears to be a semi common issue with cordova applications. I thinks it's a timing issue on some devices. On start up the application enters "immersive mode" that hides the statusbar etc. except it ends up updating the view height to be the screen minus the statusbar. So you end up with a small gap at the bottom that's the height of the statusbar. One user mentioned using the splashscreen plugin solves the problem, which is probably changing the timing.

I've got a different workaround which I'm working on, but it's causing other problems at the moment ( seems to kill touch interactions and the back button for some reason ).

**Comment by Sirtaximan** [comment] 2019-03-18 18:15
I do not know if it will help, but if you turn off the screen when you turn it on, the bug disappears.

**Comment by Sirtaximan** [comment] 2019-05-14 10:52
Any news on this problem?

**Comment by shortercode** [comment] 2019-06-21 17:33
Going to close this, merge it into #2364 

There's a change coming in the next release that should fix this.

**Closed by shortercode** 2019-06-21 17:33 UTC
Labels: Android
