### ISSUE TITLE
Switching to next fame will disappear/delete sprite

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4330] opened 2020-11-09 14:59 UTC
## Problem description
Case that deletes sprite when you change frame

## Attach a .c3p
[buggggy.zip](https://github.com/Scirra/Construct-3-bugs/files/5511279/buggggy.zip)

## Steps to reproduce

1.Open example
2.Select one of the object
3.Use properties bar initial frame option to change frame to 7
4.Edit object to see, frame 7 does exist.

## Observed result
Frame 7 cannot be set by setting, will delete object. It does exist in debug, but it's not visible somehow

## Expected result
No buggy, see and select frame 7

## More details

I bet it happaned when frame 7 was imported from image initially, then it asked to resize canvas. Something bugged out by it. 
ie, i don't know why sometimes the resize message appears and sometimes does not. So it seems bugged and error prone logic.

Also, the imported sprite is in different spritesheet

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 86.0.4240.183
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36
C3 release: r223 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 1.5 gb (1.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2020-11-09 16:24
I think the problem is the origin of the frame that is not showing up is way off center, so when you select it it's just not drawn because it ends up outside the viewable area. If you change it to **X 0; Y 0** the frame will show up in the layout view.

A resize dialog is shown when you paste content into the Animations editor which is larger than the current canvas, did you import your image by copying and pasting by any chance?

**Comment by SnipG** [comment] 2020-11-09 17:45
If i set size "0,0" Frame does indeed show up.  And yes it's origin problem. I imported images only.
I tried to make plank project and import big images, after this bug appeared. But the resize window did not show up.

What did happen, which i recall and always happens: when you got small canvas and viewport in animation editor. You import big image, the resize window resizes canvas but it places image relative to your viewport. So usually after resize and import. You have to delete the image, zoom out and paste again into resized canvas. So when canvas and viewport was small, and it fit image depening on zoom, it could had pushed origin way out!

**Comment by DiegoScirra** [comment] 2020-11-10 18:47
Closing this.

**Closed** 2020-11-10 18:47 UTC
