### ISSUE TITLE
r141 crash when opening project

### ISSUE THREAD

**Issue by isaacMuniz** [Scirra/Construct-3-bugs#2717] opened 2019-03-11 19:43 UTC
Crash when the project opens.

I think something in the project may be causing this, and I'd like to know if the crash message says what it is; crash message is below.

Just opened the project

## Observed result

Crash

## Expected result

Should open normally like in previous releases.

## More details

**Affected browsers/platforms:** Only tested with Chrome.

**First affected release:** r141

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃrMG' of undefined @ TypeError: Cannot read property 'ǃrMG' of undefined at ǃl (https://editor.construct.net/r141/main.js:2:271748) at Object.ǃJIz (https://editor.construct.net/r141/components/editors/textEditor/textEditor.js:1:6186) at new (https://editor.construct.net/r141/components/editors/textEditor/textEditor.js:1:3142) at Function.ǃX (https://editor.construct.net/r141/main.js:2:151615) at Object.ǃsL (https://editor.construct.net/r141/components/editors/textEditor/textEditor.js:1:709)
Stack: TypeError: Cannot read property 'ǃrMG' of undefined at ǃl (https://editor.construct.net/r141/main.js:2:271748) at Object.ǃJIz (https://editor.construct.net/r141/components/editors/textEditor/textEditor.js:1:6186) at new (https://editor.construct.net/r141/components/editors/textEditor/textEditor.js:1:3142) at Function.ǃX (https://editor.construct.net/r141/main.js:2:151615) at Object.ǃsL (https://editor.construct.net/r141/components/editors/textEditor/textEditor.js:1:709)
Construct 3 version: r141
URL: https://editor.construct.net/r141/
Date: Mon Mar 11 2019 16:27:01 GMT-0300 (Brasilia Standard Time)
Uptime: 85.6 s

Platform information
Browser: Chrome
Browser version: 72.0.3626.121
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
C3 release: r141 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon (TM) R7 360 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by isaacMuniz** [comment] 2019-03-11 19:50
Guys, I just reinstalled C3 and the project opened successfully; thanks for all, you can close the issue :)

**Comment by isaacMuniz** [comment] 2019-03-11 19:53
Guys, actually, it opened successfully because it was on Firefox, in Chrome it stills crash when opening the project.

**Comment by isaacMuniz** [comment] 2019-03-11 19:56
With r140 the project opens normally.

**Comment by shortercode** [comment] 2019-03-12 10:46
Closing as a duplicate of #2714 

r141 has a regression that prevents the text editor from opening, if a project has an open text editor it will cause a crash/

**Closed by shortercode** 2019-03-12 10:46 UTC
Labels: duplicate
