### ISSUE TITLE
Parallax in editor property, doesn't work for global layers.

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4126] opened 2020-08-18 14:39 UTC
## Problem description

Parallax in editor, doesn't work for global layers.
**Configuration**:
- `Global` is a **global** layer.
- `Global` layer is in the **Source** layout.
- The **Main** layout is where you will scroll and test for `parallax in editor`.
- The `Global` layer's parallax is in `(0%, 0%)`, so it should scroll with your view.

## Attach a .c3p

[Parallax Global Layer Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/5090988/Parallax.Global.Layer.Bug.zip)

**Update:** (Added a `Local` layout to differentiate the effects when using a `local layer` instead.)
[Parallax Global Layer Bug - 2.zip](https://github.com/Scirra/Construct-3-bugs/files/5091029/Parallax.Global.Layer.Bug.-.2.zip)

## Steps to reproduce

1. Go to the **Main** layout.
2. Scroll through the layout and the `Global` layer doesn't interact.

## Observed result

The `Global` layer doesn't apply the parallax in the editor despite having the property `Parallax in editor` enabled.

## Expected result

The `Global` layer to apply parallax in editor when enabled similar to local layers.

**Comment by Chadori** [comment] 2020-08-18 14:44
**New sample project:**
- Added a **Local** layout to differentiate the **Main** layout that uses a `global` layer, with another using a `local` layer. 

[Parallax Global Layer Bug - 2.zip](https://github.com/Scirra/Construct-3-bugs/files/5091029/Parallax.Global.Layer.Bug.-.2.zip)

**Comment by AshleyScirra** [comment] 2020-08-24 11:17
It does work if you enable "Parallax in editor" for the global layer on the "Source" layout. In other words the "Parallax in editor" setting is also inherited from the global layer.

I'm not sure if this is intentional or not. It's @DiegoScirra 's code IIRC so assigning to him.

**Comment by DiegoScirra** [comment] 2020-08-24 16:46
It's just another property, so the global layer's values take precedence.

The problem is that the editor only properties are not shared like the rest of the properties. This makes sense for the Visible and Locked toggles, but it can be confusing for the Parallax in editor flag.

**Comment by Chadori** [comment] 2020-08-24 18:02
Ah, I see.
That makes sense now. I can make it scroll with the layer now.
A bit confusing though. 

Thanks!

**Comment by Chadori** [comment] 2020-08-24 18:07
It probably makes more sense to either globalize that layer property (Parallax in editor) or at least make the inheriting layout's side take precedence.

Thanks.

**Comment by Chadori** [comment] 2020-08-24 18:14
It would probably make it straightforward to grasp if the layer property (Parallax in editor) was made global or at least make the inheriting layout's side take precedence.

Thanks.

**Comment by DiegoScirra** [comment] 2020-08-28 11:43
Fixed in the next beta.

The "Parallax in editor" toggle is now inherited from the global layer. Changing it on either layer will now update the rest.

**Closed by DiegoScirra** 2020-08-28 11:43 UTC
