### ISSUE TITLE
Multiplayer with packet loss and latency player objects get destroyed for peers (not host)

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#2346] opened 2018-11-19 23:35 UTC
## Problem description

in non-ideal scenarios (with latency) players get destroyed  for peers
## Attach a .c3p

https://puu.sh/C4AlD/385130a392.c3p

## Steps to reproduce

1.Remote preview the game and connect with at least 3 players
2.do nothing and wait for some time

## Observed result
peer objects get destroyed for peers sometimes, sometimes your own peer object gets destroyed and you can't move anymore

## Expected result

 peer objects not to get destroyed for no good reason

## Affected browsers

* Chrome: yes/no

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.102
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
C3 release: r126 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 417 mb (2.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2018-11-22 10:48
Does this reproduce in the C2 runtime? The project is set to the C3 runtime, are you reporting this as a C3 runtime specific issue?

**Comment by AshleyScirra** [comment] 2019-01-18 17:44
Looks like it's crashing due to receiving invalid data and then timing out the crashed peer.

Multiplayer bugs are brutally difficult to debug. It would be helpful if you can reduce the project even further to the absolutely most minimal case possible.

**Comment by eleanorawesome** [comment] 2019-01-22 05:41
https://puu.sh/CAs8M/296c822cb7.c3p

How's this ?

**Comment by Everade** [comment] 2019-03-10 21:06
Was able to confirm it using the official example and simply adding the latency action.
And also with your small-version example above.

It happens quite often.

**Comment by AshleyScirra** [comment] 2019-08-20 14:31
The .c3p links are no longer working so this issue cannot be investigated. Please provide a permanent link (you can upload them renamed as .zip to GitHub here), or the issue will be closed in 2 weeks.

**Comment by Everade** [comment] 2019-08-20 16:21
@AshleyScirra 
Use the official Construct 3 Multiplayer Example and simply add the in-engine latency action to it to simulate latency.

I was able to reproduce it back in march doing just that.

**Comment by eleanorawesome** [comment] 2019-08-20 22:05
[lowest events possible multiplayer bug - Copy.zip](https://github.com/Scirra/Construct-3-bugs/files/3522797/lowest.events.possible.multiplayer.bug.-.Copy.zip)

**Comment by eleanorawesome** [comment] 2019-10-04 20:35
I think it might only occur when the simulate latency action is applied to the host but it works fine when it's peers

**Comment by Everade** [comment] 2020-05-11 14:45
@AshleyScirra 
Still waiting until multiplayer becomes a finished, usable feature...

https://github.com/Scirra/Construct-3-bugs/issues/2410

**Comment by AshleyScirra** [comment] 2021-02-25 18:45
I think I *finally* figured out what the problem was here. Multiplayer issues are extremely difficult to debug, which is why it took so long to get to the bottom of this issue. In the end it looks like when using "simulate latency", a message being artificially delayed could be accidentally overwritten by a later message. This meant it would send out invalid messages or skip messages, causing some instances to lose the data being received for them, which in this case made the instance time out and get destroyed as it wasn't receiving data for it. Hopefully it shouldn't be a problem any more in the next beta!

**Closed by AshleyScirra** 2021-02-25 18:45 UTC
Labels: difficult
