### ISSUE TITLE
"Request fullscreen" does not trigger "browser on resized"

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#2245] opened 2018-11-04 05:25 UTC
## Problem description

"Request fullscreen" does not trigger "browser on resized"

## Attach a .c3p

https://puu.sh/BW3dL/02479ec7af.c3p

## Steps to reproduce

1.preview the game
2.trigger a touch "on tap gesture" event to request full-screen

## Observed result

the function to change the canvas size to get rid of the black bars with letterbox integer scale doesn't work and you still have black bars

## Expected result
 the function to change the canvas size to get rid of the black bars to trigger after request full-screen has completed not while the request is pending

## Affected browsers

* Chrome: yes/no

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r123.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 422 mb (2.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2018-11-05 14:08
While I can still see the black bars after going fullscreen the resize handler is firing, I confirmed this using console logs. The issue which you are seeing is that the window size does not update until after the handler has completed. I believe we have received a report for that before, I will have a look in a second.

If you place a very short wait in before calling your function the issue is resolved.

**Comment by shortercode** [comment] 2018-11-05 14:14
Duplicate of #1921 
The viewport does not update until the frame after the resize handler. Going to assign this to @AshleyScirra to review if there is any action we should take in regard to the tutorial.

**Comment by AshleyScirra** [comment] 2018-11-06 17:20
Yes, it's easy to see "On resized" really is firing by adding a console log action to it. The issue with the viewport is indeed #1921, so closing.

**Closed by AshleyScirra** 2018-11-06 17:20 UTC
