### ISSUE TITLE
Project ain't starting with NWjs plugin [Desktop Build only] 

### ISSUE THREAD

**Issue by XpMonster** [Scirra/Construct-3-bugs#1195] opened 2018-01-15 16:33 UTC
## Problem description

Just tried to open my projects in Desktop build of C3 and all projects with NWjs don't open until plugin gets removed.  

## Steps to reproduce

1. Add NWjs plugin in Desktop Build
2. Run Project
3. See for yourself

## Observed result

https://i.imgur.com/Hd8EN5f.png 

## Expected result

Obvious

## Affected only Desktop

**Comment by TheRealDannyyy** [comment] 2018-01-15 18:25
I can reproduce this as well, which is a bit odd. C3 Desktop is using NW.js v0.27.4 and v0.27.2 fixed this issue for NW.js previews in C2. Possible regression of this issue? (https://github.com/nwjs/nw.js/issues/6321)

**Comment by AshleyScirra** [comment] 2018-01-15 18:28
I can reproduce, just an unusual case of preview mode not expecting to run in NW.js in C3 yet. Should be straightforward to fix.

**Comment by AshleyScirra** [comment] 2018-01-15 19:02
OK, should be fixed in the next build. I'll leave this open since I imagine others will run in to it.

**Closed** 2018-01-17 12:53 UTC
Labels: desktop
