### ISSUE TITLE
Open to popup window breaks dragging of events.

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4038] opened 2020-07-15 09:16 UTC
## Problem description

`Open to popup window` a layout causes dragging of events to work incorrectly.

## Attach a .c3p

`Unnecessary`

## Steps to reproduce

1. New project.
2. Select an actively shown layout.
3. Right-Mouse Click the layout tab, then select `Open to popup window`.
4. Go to the event sheet. Make at least 2 to 10 events with any condition.
5. Drag the top-most event down to the bottom-most part of the event sheet.

## Observed result

The dragged event will just keep moving up. Ignoring your mouse's drag direction.
I suspect the `popped up window layout` is interfering with the actual mouse position coordinates.

## Expected result

The dragged event should move according to the mouse's position.

## More details

As soon as the popped up window layout is normalized into the main Construct 3 editor, the issue disappears.

This issue affects multi-monitor environments.
**First affected release:** It's been like this since the feature was available.

## System details
**Construct 3 r207** - NWJS Browser.

**Comment by AshleyScirra** [comment] 2020-07-21 12:15
I can't reproduce here, everything seems to be working fine.

Please - always follow the bug report guidelines, with every single report. We always need the information, including a .c3p project demonstrating the issue, and full system details. Whenever these details are omitted, it usually ends with this result that we simply cannot observe the issue. This is why we ask for them and require the details. Missing them out makes it far less likely we will be able to do anything to help.

**Comment by Chadori** [comment] 2020-07-21 15:59
You usually wouldn't miss it. But if you really can't reproduce it, then I don't think giving more details would matter.
Just unlucky for those who use multi-monitor devices.

Anyway, thank you for the time.

**Comment by AshleyScirra** [comment] 2020-07-21 16:01
It's sheer luck if we figure out the issue with important details missing. Sometimes people are lucky. But if you want to make sure the issue is resolved you can't rely on luck and need to provide all the details. Since these aren't forthcoming, closing this issue.

**Closed by AshleyScirra** 2020-07-21 16:01 UTC
Labels: can't reproduce
