### ISSUE TITLE
Events: When Tabbing to next Insert Field (shows everything selected) doesn't replace when typing something

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#1025] opened 2017-11-21 16:42 UTC
## Problem description

*Enter a concise description of your problem here*

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. add a action that has more than 1 field where you enter something (e.g. set size)
2. add anything in the first field
3. tab - notice all text is selected, so when you type something it should replace it
4. enter other number - notice that the 0 is still there (doesn't happen always i think)

if you press Ctrl+A then it replaces correctly.
If you then again click on the just created Action and do the same, it will (probably) do the same

## Observed result

*What do you see happen?*
All text is selected but when i press something it is added instead of replacing existing text

## Expected result

*What did you expect to happen instead?*
All text is selected and when i press something only the thing i just typed is there.

## Affected browsers

* Chrome: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2017-11-24 14:16
Can't reproduce here, tried a few times and it worked fine. Am I missing something?

**Comment by JeFawk** [comment] 2017-11-29 03:56
Works for me as I messaged you on discord yesterday.

![selectingbug](https://user-images.githubusercontent.com/7268697/33357306-0dcae848-d4ca-11e7-8ab2-733fd42abbde.gif)

"It's very random to reproduce so I'll try with a test sometime this week I guess if it's not obvious for you what's wrong
I tabbed through the fileds though selecting with the mouse causes the same issue. I think this could have been before the last update though"

**Comment by AshleyScirra** [comment] 2018-01-17 13:54
A duplicate was filed at #1182 and I did end up being able to reproduce it. After looking in to it I think it's a bug in one of our third-party libraries which makes it difficult to fix, and the library itself has been unmaintained for around 3 years. So the solution is probably to remove the library and rewrite our own version, but this is quite a big job. Adding 'difficult' tag accordingly.

**Comment by AshleyScirra** [comment] 2018-01-18 16:59
Unassigning myself since it might be assigned to someone else.

(For everyone else this is one of those issues where it ends up being a lot of work to fix a small issue, so  don't hold your breath I'm afraid...)

**Comment by shortercode** [comment] 2018-03-07 16:15
So I've taken this up.

I've refactored the dialog so that we're not dependant on the 3rd party library. Even so this bug is difficult to replicate 100% of the time.  I haven't been able to reproduce this bug with the new code, which I count as a good sign. But I'm not 100% sure it's fixed. If you could give it a go in r90, and see if the bug still exists for me that would be great.

**Comment by AshleyScirra** [comment] 2018-03-07 16:43
Props to @shortercode to essentially rewriting a third-party library to work around this issue!

**Comment by JeFawk** [comment] 2018-03-07 17:11
Looking forward to this fix, it's driving me nuts.

**Comment by AshleyScirra** [comment] 2018-03-12 15:28
r90 is out now - can anyone reproduce the issue there or is it resolved now?

**Comment by shortercode** [comment] 2018-03-22 13:32
@JeFawk any news here??

**Comment by JeFawk** [comment] 2018-03-23 16:26
I don't use beta builds so I can't say anything.

**Comment by shortercode** [comment] 2018-03-23 16:35
Okay thanks @JeFawk

**Comment by AshleyScirra** [comment] 2018-03-27 13:41
@JeFawk would you be able to quickly try out a beta release and check that you can't reproduce the issue in a dummy project? We are aiming to have a stable release out shortly, and if the issue is not fully resolved there, it may take another full cycle before the fix makes the stable channel again, which could be 6 weeks or so.

**Comment by Leralasss** [comment] 2018-03-27 18:25
using beta releases since a few days, i havent noticed the bug happening

**Comment by JeFawk** [comment] 2018-03-29 15:06
Sorry I couldnt use the computer for a few days now.

**Comment by AshleyScirra** [comment] 2018-03-29 15:49
Going to close this now as we've had no further reports of any issue with this for over 2 weeks. Please let us know if you still have any trouble.

**Closed by AshleyScirra** 2018-03-29 15:49 UTC
Labels: difficult
