### ISSUE TITLE
Construct 3 android audio cracking/popping

### ISSUE THREAD

**Issue by tyler3327** [Scirra/Construct-3-bugs#2912] opened 2019-05-02 10:21 UTC
## Problem description

I've noticed this issue occurs on a remote preview to a mobile device also on export to android but if I log into construct 3 editor and play directly from my phone no issue. Even stranger only a few certain audio files are doing it. One is a truck engine the other is wind chimes and the last one is a low rumble noise. I tried lowering and raising the decibels of the audio to no avail. I'm wondering if its something to do with the audio file its self but at the same time, that seems redundant seeing as it works fine on pc even after export. But then again the export has no problem with any of the other sound effects or music.

## Attach a .c3p

[construct 3 audio cracking.zip](https://github.com/Scirra/Construct-3-bugs/files/3137600/construct.3.audio.cracking.zip)

[OpeningAudio.zip](https://github.com/Scirra/Construct-3-bugs/files/3137603/OpeningAudio.zip)

The raw audio file I'm importing is in there

## Steps to reproduce

1. Add certain sound effects I've included the raw audio that I'm importing directly also.
2.add touch behavior
3.on touch play audio

## Observed result

Audio begins to crackle/pop every few seconds

## Expected result

Audio to play smoothly

## More details
Construct 3 latest stable release 
Galaxy Note 8
Latest chrome version

**Comment by AshleyScirra** [comment] 2019-05-02 11:27
In general, sound output issues are not related to Construct - the audio output is managed by the browser and OS. Further Construct will use identical audio playback both via remote preview and editor preview on the same device, also suggesting this is not to do with Construct. I also can't reproduce on a HTC 10, so it might be a device-specific issue. Closing as not related to Construct, you'll need to report this to Google or the device maker if you want further follow-up.

Also one of the sounds is quite a high-level, low-frequency sound. It could be as simple as the low frequencies causing physical buzzing in the phone speaker or case.

**Closed by AshleyScirra** 2019-05-02 11:27 UTC
Labels: Android, external
