### ISSUE TITLE
Images points not  showing

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#139] opened 2017-05-01 09:23 UTC
## Problem description
image points not showing on image editor
*Enter a concise description of your problem here*

## Attach a .c3p
![image points](https://cloud.githubusercontent.com/assets/17684135/25576539/aa53ce3a-2e7d-11e7-958c-0f04977e803b.jpg)
*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. open image editor and add image points

## Observed result
image points not showing
*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2017-05-01 10:41
Possible duplicate of #137

**Comment by DiegoScirra** [comment] 2017-05-02 09:54
Fixed in r24.

**Closed by DiegoScirra** 2017-05-02 09:54 UTC
