### ISSUE TITLE
[r30] Cannot move image point with mouse on a big sprite

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#332] opened 2017-05-23 16:58 UTC
## Problem description

When using a sprite 2126x1242 I cannot move the image point using my mouse on the right side of the image as shown in this gif:
![imagepoint bug](https://cloud.githubusercontent.com/assets/7268697/26365977/f45174bc-3ff1-11e7-8de0-e5b66a7737ac.gif)

## Attach a .c3p

[New project.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1022982/New.project.c3p.zip)

## Steps to reproduce

1. open the project
2. double click the only sprite there
3. try to put the origin image point on the right side of the image using the mouse

## Observed result

The point of origin cannot be set, nor any other image point

## Expected result

The point of origin to move using the cursor

## Affected browsers

* Chrome: yes
## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r30

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 899 mb (13%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by JeFawk** [comment] 2017-05-23 17:10
Happens when I shrunk the image to half as well. So 1240 px width.

**Comment by DiegoScirra** [comment] 2017-05-23 17:23
Can't reproduce it. Everything seems fine, I even tried importing the file in different ways.

**Comment by JeFawk** [comment] 2017-05-23 20:42
I tried incognito and I can't reproduce it either however the main project has this problem. You could get the full project i sent to @AshleyScirra and try it there.

I'm sorry I can't find any alternative.

**Comment by JeFawk** [comment] 2017-05-23 21:12
It happens actually for every sprite I have. Cannot set the image point with the mouse on the right side of the sprite, so from center to the right of the image.

**Comment by DiegoScirra** [comment] 2017-05-25 18:29
@JeFawk

Does this still happen in r31?

**Comment by JeFawk** [comment] 2017-05-25 18:47
Yes it does 
![imagepointbugstill](https://cloud.githubusercontent.com/assets/7268697/26465397/ac4df28c-4193-11e7-9085-8f2c58061479.gif)

**Comment by JeFawk** [comment] 2017-05-25 18:58
I cleared some browsing data and it's working alright now.

![image](https://cloud.githubusercontent.com/assets/7268697/26465840/4f1ad1d2-4195-11e7-8d61-67533851264a.png)

**Comment by DiegoScirra** [comment] 2017-05-26 10:13
That is very strange. Do you have any browser extensions?

**Comment by JeFawk** [comment] 2017-05-26 11:14
4 and the only one that would do anything is disabled (adblock) on the domain.

**Comment by sizcoz** [comment] 2017-06-26 15:12
I get this more often not also , but only when using the mouse, I can move the image point using the arrows keys.

**Comment by DiegoScirra** [comment] 2018-01-08 17:01
This should be fixed already.

There were several bugs causing differences between what the main editing pane was showing and the references held internally by the image editor.

**Closed by DiegoScirra** 2018-01-08 17:01 UTC
Labels: no repro
