### ISSUE TITLE
Random Project Corruption

### ISSUE THREAD

**Issue by morrisfeldman** [Scirra/Construct-3-bugs#704] opened 2017-08-10 22:00 UTC
## Problem description

Cannot open certain projects, window pops up saying "e.!EMc is not a function" instead.
 This has happened on multiple different devices and multiple different projects/games, each at different times and occurring completely randomly. Devices include Windows computers and Androids. All affected projects have physics on sprites, non-physics projects are unaffected so far.

## Attach a .c3p

[D&D World.zip](https://github.com/Scirra/Construct-3-bugs/files/1216471/D.D.World.zip)
I deleted the others thinking it would stop it from happening on another project, yet it still happened on this afterwards. Its huge but is the only example I got.

## Steps to reproduce

I can't seem to reproduce it on command since it is completely random. Even projects exclusively made on the phone or desktop have this sort of corruption. Only connection is that so far only projects with physics enabled sprites get corrupted like this,

## Observed result

window pops up saying "e.!EMc is not a function"

## Expected result

No dialog, just open the project

## Affected browsers

Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 60.0.3112.90
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
C3 release: r48

Local storage
Storage quota (approx): 72 kb
Storage usage (approx): 72 kb (100%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2017-08-25 15:37
I think the e.!EMc error is related to a missing plugin but I can't be sure without a full stack trace. Your project has some mismatched data inside which prevents it from loading but it doesn't crash when you try to load it on r51. Do you use any plugins with C3?

**Comment by AshleyScirra** [comment] 2017-08-29 14:03
The problem is the project has an action with an object instance variable parameter (think only the Multiplayer plugin uses that?) which references an instance variable named "kills" in an object named "Peer", but the instance variable does not exist. I suppose it was deleted, but the action was not deleted when the instance variable (or whatever the instance variable belongs to) was deleted. This means when you save you can't open the resulting project.

Without steps to reproduce this whole process it's difficult to do much other than recover the project - is that enough information to help you find what causes this in the first place?

**Comment by AshleyScirra** [comment] 2017-09-01 13:30
OK, based on my speculation I found deleting an instance variable used in a 'Sync object instance variable' action in the Multiplayer object did not also delete that action. That could cause a corrupt project if you saved it with the action left behind. This should now be fixed in r54. Please let me know if you still run in to this in r54+.

**Closed by AshleyScirra** 2017-09-01 13:30 UTC
Labels: need info
