### ISSUE TITLE
Browser saves fail to refresh file list in r205

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#3982] opened 2020-06-24 12:56 UTC
## Problem description
Latest release r205 browser saves fail to open up.

## Steps to reproduce

1.Nav https://editor.construct.net/r201/   --> open car lanes example
2. Save to local browser. --> nav to r205 try open or check local browser saves
3.

## Observed result
local browser saves inaccessible

## Expected result
Should be possible to open and look local browser saves

## More details

**Affected browsers/platforms:** 

**First affected release:** 
r205
## System details

<details><summary>View details</summary>

Platform information
Browser: Opera
Browser version: 68.0.3618.173
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 OPR/68.0.3618.173
C3 release: r205 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 118 gb
Storage usage (approx): 43 mb (0%)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Persistent storage is not available. Local storage could be deleted by the browser.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2020-06-24 14:37
Local browser saves are actually implemented as a kind of cloud save service internally, and those were broken by Closure Compiler in this release under #3978, so marking as duplicate of that.

**Closed by AshleyScirra** 2020-06-24 14:37 UTC
Labels: duplicate
