### ISSUE TITLE
Project won't preview after NWjs object is added

### ISSUE THREAD

**Issue by 7Soul** [Scirra/Construct-3-bugs#2941] opened 2019-05-14 20:28 UTC
## Problem description

After adding an NWjs object my project won't preview in Worker mode, and it takes a lot longer in normal mode

Deleting the object seems to fix it sometimes? Or I need to toggle Worker mode off/on, or wait a few seconds... it's really weird. This one time I deleted it and it didn't work, then I added it back and it worked

The console gives me this error: 
https://i.imgur.com/do2BldY.png

## Attach a .c3p

https://drive.google.com/open?id=1_rxIEd_3k88i6vxWgCpDmvW80WMPfj1A

## Steps to reproduce

Doesn't happen in a new project

## Observed result

The preview window is black and console gives the message above

## More details

I'm using r149

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r149 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 168 gb
Storage usage (approx): 498 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by 7Soul** [comment] 2019-05-14 20:31
Update: Non Worker mode doesn't work sometimes either

**Comment by JeFawk** [comment] 2019-05-15 07:37
I do get these every now and then as well. Sometimes it lead to crashes if I'm using the desktop app, sometimes it doesn't. I did preview your project and it works for me right now. Have you tried in incognito on the web app?

**Comment by JeFawk** [comment] 2019-05-15 07:41
Haha I opened the bookmarks in your project and r149 crashed with this though:

Error report information
Type: unhandled rejection
Reason: Error: unexpected event object @ Error: unexpected event object at window.ǃUIh.ǃUCa (https://editor.construct.net/r149/components/bars/bookmarksBar/bookmarksBar.js:1:2980) at ǃt.ǃX.ǃKbX (https://editor.construct.net/r149/components/bars/bookmarksBar/bookmarksBar.js:1:678) at ǃt.ǃX.ǃKXV (https://editor.construct.net/r149/main.js:2:206806) at ǃt.ǃX.ǃjk (https://editor.construct.net/r149/main.js:2:206684) at Function.ǃFI (https://editor.construct.net/r149/components/bars/bookmarksBar/bookmarksBar.js:1:5869) at https://editor.construct.net/r149/components/misc/mainMenu/mainMenu.js:1:6803 at new Promise () at ǃUXQ.ǃUIt.ǃUIY (https://editor.construct.net/r149/components/misc/mainMenu/mainMenu.js:1:6416) at https://editor.construct.net/r149/components/misc/mainMenu/mainMenu.js:1:7109
Stack: Error: unexpected event object at window.ǃUIh.ǃUCa (https://editor.construct.net/r149/components/bars/bookmarksBar/bookmarksBar.js:1:2980) at ǃt.ǃX.ǃKbX (https://editor.construct.net/r149/components/bars/bookmarksBar/bookmarksBar.js:1:678) at ǃt.ǃX.ǃKXV (https://editor.construct.net/r149/main.js:2:206806) at ǃt.ǃX.ǃjk (https://editor.construct.net/r149/main.js:2:206684) at Function.ǃFI (https://editor.construct.net/r149/components/bars/bookmarksBar/bookmarksBar.js:1:5869) at https://editor.construct.net/r149/components/misc/mainMenu/mainMenu.js:1:6803 at new Promise () at ǃUXQ.ǃUIt.ǃUIY (https://editor.construct.net/r149/components/misc/mainMenu/mainMenu.js:1:6416) at https://editor.construct.net/r149/components/misc/mainMenu/mainMenu.js:1:7109
Construct 3 version: r149
URL: https://editor.construct.net/r149/
Date: Wed May 15 2019 10:39:19 GMT+0300 (Eastern European Summer Time)
Uptime: 413.7 s

Platform information
Browser: Chrome
Browser version: 74.0.3729.131
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
C3 release: r149 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX550/550 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by jaydonteh** [comment] 2019-05-15 09:31
> I do get these every now and then as well. Sometimes it lead to crashes if I'm using the desktop app, sometimes it doesn't. I did preview your project and it works for me right now. Have you tried in incognito on the web app?

I can confirm this too. It took me a while to figure what was causing my project to run preview like it's dry on petrol. Never got the urge to post this until this issue came to light.

**Comment by JeFawk** [comment] 2019-05-15 10:47
I reported it but couldn't reproduce it since it happens so randomly so nothing happened.

**Comment by AshleyScirra** [comment] 2019-05-16 11:12
This is a duplicate of #2642 and was already fixed in the NW.js 0.37 desktop download. The problem is you have stayed on an old version (NW.js 0.35.1). Please only report bugs that reproduce with the latest version.

**Closed by AshleyScirra** 2019-05-16 11:12 UTC
Labels: duplicate

**Comment by 7Soul** [comment] 2019-05-16 21:55
> This is a duplicate of #2642 and was already fixed in the NW.js 0.37 desktop download. The problem is you have stayed on an old version (NW.js 0.35.1). Please only report bugs that reproduce with the latest version.

Btw I checked the [version manager](https://www.construct.net/en/make-games/manuals/construct-3/interface/dialogs/nw-js-version-manager) manual entry but it doesn't say how to open it. The NWjs manual page itself doesn't say anything about keeping it up to date
