### ISSUE TITLE
After update to r73 can't open project

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#1109] opened 2017-12-18 16:33 UTC
## Problem description

Get stuck at "Getting Files from...." for both browser storage and cloud storage.

## Steps to reproduce

1. Open projects.

## Observed result

Can't open project.

## Expected result

Open projects.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 63.0.3239.84
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
C3 release: r73
Language setting: en-US

Local storage
Storage quota (approx): 7.2 gb
Storage usage (approx): 435 mb (5.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 765M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2017-12-18 16:55
Can't reproduce here, both cloud and browser storage work OK. Does it still happen if you clear the browser cache and retry?

**Comment by jaydonteh** [comment] 2017-12-18 17:08
Clearing the cookies did it for me, but I'm sure its the update that causes it. I wonder if it affects everyone else tho.

**Comment by shortercode** [comment] 2018-01-04 12:11
Sounds odd... I haven't experienced this myself. I'm looking through change logs to see if I can find any obvious issues, but I haven't found anything yet. I don't suppose you happened to have a look in the console to see if there was any errors that didn't trigger the crash dialog?

**Comment by shortercode** [comment] 2018-01-04 13:22
Also anyone else having this issue?

**Comment by dru1000** [comment] 2018-01-05 19:36
I just had this exact same issue, couldn't open any project from Google Drive. I cleared the browser data from the last 24 hours and now it works again.

Maybe related to yesterdays R75 release?

**Comment by shortercode** [comment] 2018-01-08 11:26
I've been having an issue with the r75 release on my machine, which I think is probably the same one. It certainly behaves the same. It appears that one of the files required for the cloud service to work has been cut in half by our CDN ( an error we have experienced before ). The file is probably not broken anymore, but it's got stuck in one of the many layers of file caching and hence some people are having trouble. Provided the server is now serving the correct version this issue should go away on the next release. I believe the caches that are affected are the browser's HTTP cache and the service worker caches for editor.construct.net, so purging those should act as a workaround for anyone who experiences this issue.

**Comment by shortercode** [comment] 2018-01-08 15:31
The problem seems to have cleared up for me with the r76 release, how is it for everyone else?

**Comment by Wugliwu** [comment] 2018-01-19 21:57
Had this problem today but on a mobile Android device. If I clear the Browser Cache I can Access storage and also have to reconnect to Dropbox.
In the next startup I permanently get this "getting Files from..." Message.

**Comment by shortercode** [comment] 2018-01-20 09:43
I can confirm this is back, just got it on my home computer. Same issue as before by the looks of it.

Cloudflare is attempting to minify a file and has broken on a template literal containing a url. Going to assign @AshleyScirra and @TomGullen to check this out, as it's a server configuration issue.

**Comment by shortercode** [comment] 2018-01-22 11:15
![screenshot 2018-01-22 11 12 16](https://user-images.githubusercontent.com/9051865/35218114-56893286-ff65-11e7-8874-ba30dae4f21b.png)

So looks like we make 2 network requests for this file, the first one which is sent without a cache bust string seems to return a working file but the other one does not. The effect is that the first time you open the cloud dialog after an update it will work, and any time after it will fail. Incidentally the network request is only made once you try to open the cloud dialog.

**Comment by AshleyScirra** [comment] 2018-01-22 11:23
Think this deserves a difficult tag :-\

**Comment by AshleyScirra** [comment] 2018-01-22 11:50
If it's a cloudflare minify bug then it may depend on a very specific pattern of JS which only occurs in that file.

It's still really dumb that their error fallback is effectively to corrupt the file rather than serve the original.

**Comment by shortercode** [comment] 2018-01-22 13:44
Switching to using plain strings for the URLs in the cloud service code seems to have resolved the issue for r80, shall we consider this closed?

**Comment by AshleyScirra** [comment] 2018-01-22 13:49
Let's leave it open a couple of days to see if anyone still has trouble, if not I guess we can close.

**Comment by shortercode** [comment] 2018-01-23 13:31
One potential report in #1223 but I haven't been able to confirm that this is the problem.

**Comment by Wugliwu** [comment] 2018-01-23 14:22
Sry to say... but still the same on r80 on mobile devices, desktop works fine. Cleared the cache.

**Comment by shortercode** [comment] 2018-01-23 14:25
Thanks for confirming @Wugliwu I've also managed to repeat it here. It's strange, I can't reproduce it in incognito. Also it seemed to be working yesterday!

**Comment by shortercode** [comment] 2018-01-23 14:47
Okay so I think I've managed to narrow down the issue here, and if I'm right the issue will already be fixed in r81.

Firstly cloudflare is treating requests with querystrings differently to requests without. Requests with a querystring get a 307 internal redirect, and the resulting content seems to be minified. A request without a querystring gets a 200 and the content is returned unminified. Just to clarify, it's the cloudflare minification which is causing this issue. Requests to fill our offline cache use querystrings, but normal requests don't.

Secondly, looking at the file that is being served, part of the workaround I added for r80 seems to have not been included in the build. So the file isn't immune to bad minification like I had hoped. 

Now there's still a lot of unknowns, and there's definitely something wrong with the servers... but hopefully it will be less of a problem when the next release goes out!

**Comment by Wugliwu** [comment] 2018-01-23 15:01
Okay found the reason and also a way to reproduce it for my case.

Reason was a kind of aborted authentification to dropbox.

Steps:
1. Clear Browser
2. Open C3 via Browser
3. Open Project from Cloud
4. Select DropBox
5. Dropbox Authentification Screen
6. Login
7. !!!Close Browser
8. Repeat Step 2. and 3.
9. Result: Endless Loading

Im not sure anymore if and why I closed the Browser every time. Maybe after confirming my dropBox login via Mail-App or a browser crash (Had a view while trying to fix this). But I guess the reason is simple the cached state of C3 waiting for authentification or not beeing authenticated. At this point the user has no option to reconnect.

Also 4 days ago I had to confirm every single attempt to authentificate to dropbox via Mail. This is gone now even if I clear the cache.

Also I allowed Pop Ups globaly not just for C3 for the authentification and disabled it afterwards. Works like a charm.

**Comment by Wugliwu** [comment] 2018-01-23 15:15
Also  #1223 is referencing local storage. So this could be a separated issue.

**Comment by newman321** [comment] 2018-01-23 15:29
@shortercode when would be next release ?

**Comment by newman321** [comment] 2018-01-23 15:32
this is end of sandbox.js code loaded in r80 
`{response_type:"token",scope:"onedrive.readwrite",state:createUUID(32),client_id:e,redirect_uri:g});return a&&a(()=>ÇƒBh.ÇƒBw(b)),b.then((a)=>a.access_token)}const d="ONE DRIVE",e="0000000048190284",f="https://api.onedrive.com/v1.0",g=document.location.origin+"/cloudauth.html",h=`https:`

**Comment by shortercode** [comment] 2018-01-23 15:54
@Wugliwu the broken file contains code for both the cloud and browser save, so if one is broken the other will be broken. If the file fails to load it just shows the "Getting files from..." message forever.

I don't think it's related to the dropbox authentication. But I'm not sure why Dropbox was requiring you to confirm each time you logged in. I think step 7 was key in your reproduction. Due to the way the offline cache works the first time you load the save dialog after a cache clear a slightly different file is returned ( which works ). Any time you open C3 after this it will load the broken file from the offline cache instead.

@newman321 Thanks for confirming that for me, I went over what we published for r80 with @AshleyScirra and part of the fix was missing. We haven't decided when the next release will go out yet but we try to avoid putting them out later in the day in case anything goes wrong. It can take several hours for a problem to become apparent, by which point people might have gone home.

**Comment by newman321** [comment] 2018-01-24 18:19
problem solved

**Comment by shortercode** [comment] 2018-01-25 12:51
@newman321 Glad to hear!

**Comment by AshleyScirra** [comment] 2018-02-05 15:54
Looks like this was left open accidentally, so closing.

**Closed by AshleyScirra** 2018-02-05 15:54 UTC
Labels: difficult
