### ISSUE TITLE
Editing collision box of tilemap cell crash.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4100] opened 2020-08-10 04:13 UTC
## Problem description

Closing the edit window after editing the collision box of a tilemap cell crashed C3.

## Attach a .c3p

n/a.

## Steps to reproduce

I could not replicate it, but i pasted the crash report below.

## Observed result

Crash.

## Expected result

No crash.

## More details

**Affected browsers/platforms:** Latest Chrome.

**First affected release:** 210

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'rj' of null @ TypeError: Cannot read property 'rj' of null at https://editor.construct.net/r210/components/bars/tilemapBar/tilemapBar.js:35:365
Stack: TypeError: Cannot read property 'rj' of null at https://editor.construct.net/r210/components/bars/tilemapBar/tilemapBar.js:35:365
Construct 3 version: r210
URL: https://editor.construct.net/r210/
Date: Mon Aug 10 2020 01:09:05 GMT-0300 (Brasilia Standard Time)
Uptime: 4255.6 s

Platform information
Browser: Chrome
Browser version: 84.0.4147.105
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
C3 release: r210 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 750 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment] 2020-08-10 12:19
There is no need to file issues only with a crash report. These are automatically logged to our server, and we routinely review and fix any issues that we can from this information alone. However, normally we require more information to be able to investigate and fix issues. Since this information is missing from this report, there is nothing we can do, so closing.

**Closed by AshleyScirra** 2020-08-10 12:19 UTC
Labels: no repro

**Comment by dupuqub** [comment] 2020-08-10 13:25
@AshleyScirra There's no information missing. Close the edit window after editing the hitbox of any tile in a tilemap. It consistently crashes. I currently cannot work with Tilemaps.

**Comment by AshleyScirra** [comment] 2020-08-10 13:32
There is no project attached and no steps to reproduce in the report. These details are required.

**Comment by dupuqub** [comment] 2020-08-10 14:06
These are my settings.

Any file should present it.

![bug1](https://user-images.githubusercontent.com/34659544/89791278-77369880-daf9-11ea-899d-e6c6f4adcd15.PNG)
![bug2](https://user-images.githubusercontent.com/34659544/89791275-769e0200-daf9-11ea-8198-c8753daec302.PNG)
![bug3](https://user-images.githubusercontent.com/34659544/89791280-77cf2f00-daf9-11ea-9a1d-7e277d1ad10d.PNG)

**Comment by dupuqub** [comment] 2020-08-10 14:06
It does not happen on Light theme btw.

**Comment by dupuqub** [comment] 2020-08-10 14:15
@AshleyScirra The culprit is "Enable UI animation" If I disable it, then closing the edit window on a tile of any tilemap, of any file, will crash.
