### ISSUE TITLE
[Desktop] No backups are created

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#2526] opened 2019-01-21 10:00 UTC
## Problem description

C3 desktop version does not save backups periodically or when I save, regardless of settings. I've been working on a project for days with auto-save and backup settings enabled yet there is only the original C3PROJ file and UIstate.

## Attach a .c3p

Can use blank .c3p

## Steps to reproduce

1. Enable all auto-save and backup features. Set interval to 1 minute.

## Observed result

No backups are made.

## Expected result

Ideally, backups would be created precisely as they are in C2.

## First affected release

Noticed over a year ago so all releases. Figured someone else would report by now.

## Affected browsers/platforms

Desktop

**Comment by shortercode** [comment] 2019-01-21 10:52
The backup system currently only works with cloud and browser saves. If you have the backup location set to one of the cloud providers it will backup there.

**Comment by AshleyScirra** [comment] 2019-01-21 11:03
@Tokinsom what backup location do you have set?

**Comment by Tokinsom** [comment] 2019-01-21 11:48
@shortercode @ashleyscirra Ah. I'm using 'same location' so that would explain it. However, I do remember using dropbox long ago and only a single backup file was created. There wasn't a "chain" of backups like C2 does (super convenient if you decide to roll back a little, need a snip of code or assets from something recently removed, or discover a problem with new content). Will we be able to set the amount of backups like this in the future for C3?

**Comment by AshleyScirra** [comment] 2019-01-21 12:54
Can you confirm that the issue is only happening when specifying "same location" as the backup location? AFAIK the cloud backups are implemented differently so anything wrong there should probably be tracked in a separate issue. Also are you using a single file project or a folder project? Again this affects what "same location" refers to.

**Comment by shortercode** [comment] 2019-01-21 14:15
Backups are always created with the same name ( although most cloud providers allow you to restore a previous revision for around a month ). I guess we could theoretically add an additional settings for this, it would make more sense for local saves than cloud ones though.

Originally the feature was implemented at the request of users that found saving to cloud too slow ( it was blocking at the time ). The idea being that it would save their projects periodically to browser storage, just in case there was an issue. It was later expanded to be more configurable ( different location and periods ), but it's only ever worked with cloud saves ( browser saves are treated as a "cloud service" but are just written to the browser cache ). 

There is a specific line that skips the backup if it's set to "same location" and the project origin is not the cloud. As it doesn't know how to save to a non "cloud service".

**Comment by Tokinsom** [comment] 2019-01-21 15:28
@shortercode @AshleyScirra Folder project (I mentioned a C3PROJ in the OP but could've specified) So I changed the backup location to Dropbox, set the interval to 1 minute, and messed around for about 20 minutes. No backup anywhere. Also, no autosave with either "Cloud" or "Same Location" after 20 minutes.

Perhaps the issue is with the timer? I will keep an eye out for auto-saves and backups appearing, and try again with a single .c3p file.

**Comment by shortercode** [comment] 2019-01-21 15:41
@Tokinsom had you actually made any changes to the project? It will only backup if there has been a change.

I just tried it myself and it displayed an error dialog, it appears to be making an assumption that the projects "last saved as" value is name, but it's a path for desktop file/folder saves which breaks dropbox.

**Comment by Tokinsom** [comment] 2019-01-21 19:45
@shortercode Yes I've been working on it for days and not a single autosave or backup has been created. Today I worked on it for a couple hours (while occasionally changing the autosave & backup location to see if it made any difference) and there is still nothing.

**Comment by shortercode** [comment] 2019-01-22 13:55
Mmmm in theory it should be showing you the popup already, the auth popup is shown whenever a "cloud action" occurs and it doesn't have a valid token.

The malformed path bug should be fixed in the next release, that was the error dialog I mentioned in my previous comment.

**Comment by shortercode** [comment] 2019-06-28 13:43
Okay I've implemented local auto saves for desktop. There's been a few small adjustments that come with it. 

- `backup location = browser` is no longer an option on desktop, as the option to open/save files to the browser save location doesn't exist on desktop.
- Any desktop apps with the backup location set to `browser` will be changed to `match` .
- The default location has been changed from `browser` to `match`.
- A new option has been added to the backup location setting, on desktop only, called "filesystem". For projects that are saved on the filesystem it will place the autosave next to the project, otherwise it will be placed in `~/C3/autosaves`
- `match` mode now also works with local saves

These changes should be in the next beta release.

**Closed by shortercode** 2019-06-28 13:43 UTC
Labels: desktop
