### ISSUE TITLE
C3 desktop crash after changing font size

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#2327] opened 2018-11-17 03:00 UTC
## Problem description

Changed the font size of a text object in the property panel and while the cursor was still blinking clicked the canvas to zoom. The moment I clicked on the canvas it crashed. Cannot reproduce, maybe you can figure it out from the error message.

## Steps to reproduce

Cannot reproduce :/

## Affected browsers

* Desktop: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r120/main.js, line 2, col 381072
Message: Uncaught TypeError: Cannot read property 'select' of null
Stack: TypeError: Cannot read property 'select' of null at ǃVuW.requestAnimationFrame (https://editor.construct.net/r120/main.js:2:381072)
Construct 3 version: r120
URL: https://editor.construct.net/
Date: Sat Nov 17 2018 04:56:45 GMT+0200 (Eastern European Standard Time)
Uptime: 36716.1 s

Platform information
Browser: NW.js
Browser version: 0.31.2
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.3541666269302368
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@878cd31214ac27a3996927cd5c9c138b10c9fc8d) NWjs/0.31.2 (like Chrome/67.0.3396.87)
C3 release: r120 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2018-11-19 11:55
I'm afraid there's little we can do without a way to reproduce it, but I've made a defensive change based on the crash message for the next release. Since there's nothing else anyone can check about this without steps to reproduce, closing.

**Closed by AshleyScirra** 2018-11-19 11:55 UTC
Labels: no repro
