### ISSUE TITLE
Crash when switching between any layout only when layer's bar is open.

### ISSUE THREAD

**Issue by lightestlou** [Scirra/Construct-3-bugs#5659] opened 2022-04-24 22:39 UTC
## Problem description

Construct will crash whenever the user switches between any two open layouts in the editor with the layers bar open.
The only way to prevent this crash is to open the project with the layers bar already closed.
Then close the layers bar before switching between layouts.

## Attach a .c3p

Occurs on a fresh project with no changes.
Do I need still need to attach a .c3p?

## Steps to reproduce

1. Open a project.
2. Open a layout.
3. Confirm the layers bar is visible.
4. Open another layout.
5. Observe the crash.

## Observed result

Construct 3 crashed.

## Expected result

Construct 3 not to crash.

## More details

Not much else to add.
Seems to be r291 only.
I accidently saved my main project while using the beta so I'm stuck with this :( but that's on me.

If it helps I tried every combination of bars and panes but only the layers bar causes this bug.
I noticed if you load a project with the layers bar already open, it'll say:
Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project.

However, it will still open.
Then it will crash on layout change no matter what you do.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r291/main.js, line 1424, col 182
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'length')
Stack: TypeError: Cannot read properties of undefined (reading 'length') at CCG.uh.g.J.$Ea.ed (https://editor.construct.net/r291/main.js:1424:182) at window.Pcb.leb.ed (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:17:454) at window.Pcb.nc (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:9:446) at window.Pcb.eGa (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:9:122) at Array. (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:8:101) at window.cIb.dispatchEvent (https://editor.construct.net/r291/main.js:1058:42) at jS (https://editor.construct.net/r291/components/editors/layoutView/layoutView.js:39:423) at window.ul.uV (https://editor.construct.net/r291/components/editors/layoutView/layoutView.js:106:30) at window.ul.Vha (https://editor.construct.net/r291/components/editors/layoutView/layoutView.js:106:20) at Array. (https://editor.construct.net/r291/components/editors/layoutView/layoutView.js:83:370)
Construct 3 version: r291
URL: https://editor.construct.net/r291/
Date: Sun Apr 24 2022 18:23:44 GMT-0400 (Eastern Daylight Time)
Uptime: 14.9 s

Platform information
Browser: Chrome
Browser version: 100.0.4896.127
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
C3 release: r291 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by Interinactive** [comment] 2022-04-25 00:14
I get this too. I first noticed it when I kept trying to duplicate layouts, and when I switched to them, it would crash 100% of the time. I've gone back to r290 where the issue doesn't occur.

**Comment by AshleyScirra** [comment] 2022-04-25 11:06
Looks like a duplicate of #5653

**Closed by AshleyScirra** 2022-04-25 11:06 UTC
Labels: duplicate
