### ISSUE TITLE
Just after opening a dropdown list, it closes automatically without even pressing anything (c3 desktop beta)

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#2776] opened 2019-03-27 07:03 UTC
## Problem description

If you open a list in the editor it will close automatically after about 0.5 seconds of them being open.

## Example story

"Let me just select a variable":

![image](https://user-images.githubusercontent.com/5744908/55056301-ec96fa00-50b9-11e9-8a18-9dbf42a4f5fa.png)

"Where is the variable I'm looking for, let's see"

![image](https://user-images.githubusercontent.com/5744908/55056363-0b958c00-50ba-11e9-8d32-b7df58ca53c1.png)

"Wait the menu suddenly closed, without me doing anything!" 😱

![image](https://user-images.githubusercontent.com/5744908/55056413-2a941e00-50ba-11e9-9bd6-0d70a1244ebc.png)

Can you reproduce in latest C3 desktop beta?

Thanks 💖

## Attach a .c3p

[list closer.zip](https://github.com/Scirra/Construct-3-bugs/files/3011912/list.closer.zip)

## Steps to reproduce

1. Try changing the variable from the drop down list in editor
2. spend a few seconds looking for a variable in the list

## Observed result

List closes suddenly by itself with no input

## Expected result

List should stay open, at least until user clicks

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 126 gb
Storage usage (approx): 924 mb (0.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DieppedalleDavid** [comment] 2019-03-27 09:14
No problems found, the list remains open, nothing to report here!

**Comment by AshleyScirra** [comment] 2019-03-27 16:41
Can't reproduce here - it's not clear exactly what's happening from your sequence of screenshots but the dropdown seems to be working just fine here. Can you provide any more information to help us reproduce the problem?

**Comment by alastajj** [comment] 2019-03-28 03:03
Clicking on a drop down list, it stays open for about 0.5 seconds then it closes again. When I get to image 2, it quickly transitions to image 3. Normally you only get to image 3 after you've selected an item in the drop down list, it shouldn't be closing by itself so suddenly.

Does that make sense?

If this is just an issue with my computer, anyone have any idea why it might happen? Thanks.

**Comment by alastajj** [comment] 2019-03-28 04:41
It only happens when I use Desktop and Chrome editor. It doesn't happen for me when I use Firefox.

Here is a gif, all I do is click to open the menu, but see how it closes by itself:

![droplist](https://user-images.githubusercontent.com/5744908/55130714-f54a0780-516f-11e9-9980-480a7070cf7e.gif)

**Comment by AshleyScirra** [comment] 2019-03-28 10:22
It might be a Chrome extension or another app on your system stealing focus. I'm afraid we can't do anything about this if we don't have steps to reproduce that work for us, so closing.

**Closed by AshleyScirra** 2019-03-28 10:22 UTC
Labels: can't reproduce, desktop
