### ISSUE TITLE
If I don't press enter when editing the speed or name of an animation in a sprite, it crashes construct

### ISSUE THREAD

**Issue by Foxy1YT** [Scirra/Construct-3-bugs#6107] opened 2022-09-15 17:25 UTC
## Problem descriptionError report information
Type: unhandled exception
File: https://editor.construct.net/r308-2/main.js, line 901, col 125
Message: Uncaught TypeError: unexpected type
Stack: TypeError: unexpected type at Q.Fa (https://editor.construct.net/r308-2/main.js:901:131) at SO.qc.XDb (https://editor.construct.net/r308-2/projectResources.js:2454:204) at CCG.Tg.g.J.Feb.hm (https://editor.construct.net/r308-2/projectResources.js:1922:384) at CCG.Tg.g.J.Feb.Yn (https://editor.construct.net/r308-2/main.js:1356:478) at CCG.Tg.g.J.Feb.SE (https://editor.construct.net/r308-2/main.js:1364:411) at HTMLInputElement.Yr (https://editor.construct.net/r308-2/main.js:1349:303) at CCG.$g.g.J.Tsa.Hjb (https://editor.construct.net/r308-2/main.js:1421:187) at CCG.$g.g.J.Tsa.Jb (https://editor.construct.net/r308-2/main.js:1420:256) at MM.wdc.ea (https://editor.construct.net/r308-2/projectResources.js:1927:260) at iy (https://editor.construct.net/r308-2/projectResources.js:145:465)
Construct version: r308.2
URL: https://editor.construct.net/
Date: Thu Sep 15 2022 18:20:57 GMT+0100 (British Summer Time)
Uptime: 8711.3 s

Platform information
Product: Construct 3 r308.2 (stable)
Browser: Chrome 105.0.5195.112
Browser engine: Chromium
Context: browser
Operating system: Chrome OS 14989.85.0
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (X11; CrOS x86_64 14989.85.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) UHD Graphics 600 (GLK 2)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2022-09-16 10:43
It seems to work fine for me - I tried these steps:

1. Create a new project, add sprite, Animations Editor opens
2. Type a new animation speed in the 'speed' property and leave it focused
3. Close the Animations Editor

No crash happens. This is why we ask you always follow the bug report guidelines - it's usually impossible to help otherwise.

@DiegoScirra any ideas from the crash report?

**Comment by DiegoScirra** [comment] 2022-09-16 11:25
According to the crash report it has something to do with renaming an animation, but there is more to it than just doing that. Most likely a very unique set of steps need to happen to trigger the crash.

**Comment by AshleyScirra** [comment] 2022-09-16 12:52
Closing as we can't reproduce the issue.

**Closed by AshleyScirra** 2022-09-16 12:52 UTC
Labels: ignored guidelines
