### ISSUE TITLE
Tiledbackground Rotation breaks things

### ISSUE THREAD

**Issue by 4demon** [Scirra/Construct-3-bugs#4148] opened 2020-08-24 13:44 UTC
## Problem description

If I rotate a tiled background, at runtime their rotations are reset and re-positioned.

## Attach a .c3p

[TiledRotate.zip](https://github.com/Scirra/Construct-3-bugs/files/5118180/TiledRotate.zip)

## Steps to reproduce

1. Create a tiledbackground and copy paste it with different directions.
2. Run it

## Observed result

At runtime, all the tiled backgrounds not at 0 angle will vanish.

## Expected result

Should be able to rotate tiled backgrounds.

## More details

This was originally posted as a physics bug, but it may be this element that is breaking things.

**First affected release:** Worked in the last stable.

**Comment by AshleyScirra** [comment] 2020-08-24 14:05
Duplicate of #4129

**Closed by AshleyScirra** 2020-08-24 14:05 UTC
Labels: duplicate
