### ISSUE TITLE
Scrolling with mouse not working on IpadOS

### ISSUE THREAD

**Issue by arturbier** [Scirra/Construct-3-bugs#5833] opened 2022-06-29 13:39 UTC
## Problem description

The mouse is touch-sensitive and when you swipe with your finger, the layout in C3 starts to twitch!

## Steps to reproduce

1. Open C3 and use the Apple Magic Mouse or another Mouse 
2. Scroll the mouse wheel or swipe on the magic mouse
3. You will see a scrolling bug

## Observed result

scrolling bug

https://user-images.githubusercontent.com/78679486/176450446-90b6f09a-4b55-455e-ab1d-a2074a4ec2ba.MOV

## Expected result

I want scrolling to work as fully on my iPad or another android devices as on a PC

## More details

The problem occurs in any browser

The problem occurs on any mobile device that I have tested (ipad pro 12.9 m1 and Samsung Galaxy Tab S8 plus

Scrolling does not work in all versions of C3 : stable and beta

**First affected release:** 

## System details

<details><summary>View details</summary>

Ipad OS 15 , Ipad Pro 12.9 m1

</details>

**Comment by AshleyScirra** [comment] 2022-06-30 11:52
I don't believe we currently have an Apple Magic Mouse in the office, so we'd need to order one in to test this.

Before we do that, can you verify if the problem occurs with an ordinary mouse (e.g. with a physical scroll wheel)? If it happens with any mouse then we may not need to order in the specific Apple Magic Mouse.

**Comment by AshleyScirra** [comment] 2022-07-01 10:28
@DiegoScirra - could you test on one of our devices?

**Comment by DiegoScirra** [comment] 2022-07-01 11:02
Confirmed.

There is a problem if you use the desktop layout in a mobile device and try to use the mouse wheel, tried it with a Microsoft bluetooth mouse and an iPad pro. It tries to scroll the layout view vertically, but it's jittery and not really useful.

It's a physical wheel but I guess the Magic Mouse ends up triggering the same events when you do the gestures.

**Comment by AshleyScirra** [comment] 2022-07-11 11:45
It turns out some old code we had working around a bug in Safari 11 broke the wheel input on iOS. However it seems that the old Safari bug no longer reproduces in Safari 15.5, and removing it fixes the wheel input on iOS. So this should be fixed in the next release cycle (and hopefully that other issue won't come back...)

**Closed by AshleyScirra** 2022-07-11 11:45 UTC
Labels: difficult, safari
