### ISSUE TITLE
Pin issue

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1623] opened 2018-05-23 19:48 UTC
## Problem description

*Enter a concise description of your problem here*
When pinned no matter the setting, it won't stay above the player directly, like a name bar would, or hit point bar would, I've tried all pin configurations.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Add 2 sprites to the scene, have 1 as player, have another as name.
2. Pin the name or hit point sprite to the player sprite
3. Add touch to the project
4. Set player to use touch for movement 
5. Set layout to stay with player

## Observed result

*What do you see happen?*
The pinned sprite, no matter which option chosen, will not stay over the top of the player

## Expected result

*What did you expect to happen instead?*
Pinned sprite to stay above player

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 11.0
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: iOS
Operating system version: 11.3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPad; CPU OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
C3 release: r101.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
Service Workers are not supported. Construct 3 cannot be used offline in this browser.
The <dialog> element is not supported. A polyfill is in use.
The Clipboard API is not supported. Some clipboard features may be unavailable.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Downloading local content is not supported.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Metal - 52.3.2)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Apple Inc.
Renderer: Apple A10X GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions:

EXT_blend_minmax
EXT_sRGB
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_depth_texture
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)
[pinbugged.zip](https://github.com/Scirra/Construct-3-bugs/files/2032539/pinbugged.zip)

</details>
[pinbugged.zip](https://github.com/Scirra/Construct-3-bugs/files/2032584/pinbugged.zip)

**Comment by AshleyScirra** [comment] 2018-05-23 20:09
It looks like it's working correctly. What exactly are you expecting to happen instead?

**Comment by zumwaltwood** [comment] 2018-05-23 20:12
The text to remain above the player in the position it is tied to, no matter the player facing.

**Comment by zumwaltwood** [comment] 2018-05-23 20:22
![playerfacing 2x](https://user-images.githubusercontent.com/4122283/40449101-1bbb6358-5e9d-11e8-8b28-042a1e98b0c9.png)
![playerfacing 3](https://user-images.githubusercontent.com/4122283/40449106-221cc494-5e9d-11e8-99e4-c74d50b3ec48.png)

Just quick example sketch's

**Comment by zumwaltwood** [comment] 2018-05-23 20:51
I‘ve just uploaded a movie to YouTube!
You can check it out here:
http://www.youtube.com/watch?v=Tioz3uMPRzs

Check out that video, same setup as the demo I attached, in this case, it is way off to the right for some bizarre reason then comes to the player, then takes off far to the right as the player moves right, totally screwy

**Comment by Wackytoaster** [comment] 2018-05-24 01:04
The text is pinned to a position based on the origin points. I adjusted your c3p a little, check it out
[Pin-unbugged.zip](https://github.com/Scirra/Construct-3-bugs/files/2033378/Pin-unbugged.zip)

As for the video, your player sprite is not on the same layer as the id text. The text is on one of the menu layers, and I can just assume you set that layers parallax to 0,0 so it works like a hud. That´s likely the reason why it looks like this.

**Comment by zumwaltwood** [comment] 2018-05-24 02:16
Thanks for the adjust, i will look at this first thing tomorrow, unfortunately, i found a major bug with pin and have posted that in another thread, if you remove pin, that can cause unwanted side affects which can totally break the layout.

**Comment by AshleyScirra** [comment] 2018-05-24 09:18
Closing as not a bug.

**Closed by AshleyScirra** 2018-05-24 09:18 UTC
