### ISSUE TITLE
Individual tile editor (Tilemap) crashes Construct after exiting

### ISSUE THREAD

**Issue by ytfcon** [Scirra/Construct-3-bugs#4120] opened 2020-08-16 20:31 UTC
Here's a video showing the issue: https://youtu.be/sRhKgekyUrk
The video shows the stable release but it happens the exact same in the beta.
And debug info:
Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'rj' of null @ TypeError: Cannot read property 'rj' of null at https://editor.construct.net/r210-2/components/bars/tilemapBar/tilemapBar.js:35:365
Stack: TypeError: Cannot read property 'rj' of null at https://editor.construct.net/r210-2/components/bars/tilemapBar/tilemapBar.js:35:365
Construct 3 version: r210.2
URL: https://editor.construct.net/
Date: Sun Aug 16 2020 21:12:02 GMT+0100 (British Summer Time)
Uptime: 97.5 s

Platform information
Browser: Chrome
Browser version: 84.0.4147.125
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
C3 release: r210.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

**Comment by DiegoScirra** [comment] 2020-08-17 11:21
Duplicate of #4104. Follow that issue for updates.

**Closed by DiegoScirra** 2020-08-17 11:21 UTC
Labels: duplicate
