### ISSUE TITLE
Shorcut B add 2 blanc sub_event

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#200] opened 2017-05-15 12:51 UTC
## Problem description

When I add blanck sub-events with right click>add>add blank sub_events it works.
But when I use the B shortcut, it add 2 blank sub-events

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. use B shortcut

## Observed result

2 blank sub_events

## Expected result

1 blank sub_event

## Affected browsers

* Chrome: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2017-05-15 14:03
Closing as duplicate of #118, should be fixed in r28.

**Closed by AshleyScirra** 2017-05-15 14:03 UTC
