### ISSUE TITLE
Desktop Build r89 - can't leave without saving the project

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#1413] opened 2018-03-22 05:30 UTC
## Problem description

When trying to close the C3 Desktop program with unsaved changes, a small message pops up:
"Do you want to leave this site? Leave/Stay".
Pressing the "Leave" button doesn't close C3 and the dialog is displayed again.
After pressing the "Leave" button once, pressing "Stay" button also has no effect and it becomes impossible to close the program.

## Attach a .c3p
n/a

## Steps to reproduce

1. Start a new project in Desktop build, add anything to layout.
2. Try to close C3.
3. Press "Leave"

## Observed result

C3 is stuck at "Do you want to leave this site?" dialog and the only way to close it is via the Task Manager.

## Expected result

Pressing "Leave" should close C3.

## Affected browsers

* Desktop build

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r89 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 142 gb
Storage usage (approx): 3.5 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2018-03-22 12:28
@DiegoScirra was looking at this before he went on holiday, so I'm going to assign him for now.

**Comment by repkino** [comment] 2018-03-22 12:48
windows10
![win10c3close](https://user-images.githubusercontent.com/35696621/37771339-5ba7f6ec-2de8-11e8-82e1-ffb626a13cd2.gif)

**Comment by dop2000** [comment] 2018-03-22 14:27
@repkino, yep, exactly like that. I'm on WIndows 10 too.

**Comment by sebastien-c3** [comment] 2018-03-22 15:22
Same here since recently (Windows 8, desktop version).

**Comment by Astolfo56** [comment] 2018-03-23 18:51
Same here (Windows 7, 64 bit) and desktop version.

**Comment by TheRealDannyyy** [comment] 2018-03-27 14:41
I can reproduce this as well.

Additionally clicking the "Exit" button in the menu ribbon completely freezes C3.

**Comment by AshleyScirra** [comment] 2018-03-28 10:50
Should be fixed in r94.

**Closed by AshleyScirra** 2018-03-28 10:50 UTC
Labels: desktop
