### ISSUE TITLE
Changes to json (dictionary) not properly saving

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#2892] opened 2019-04-25 10:14 UTC
For some reason my project does not save changes I make to a json. It only appears to affect a specific file, a different file (also dictionary json) saves fine? If I also make other changes, the other changes will safe fine, while the json does not. I can only reproduce the issue with that specific file and that specific project, but reliably so. Seems to be corrupted or something?

The changes save normally if I save it to a new file, instead of just hitting Ctrl+S, but the problem persists on the new file too.

## Attach a .c3p

[nani.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3116368/nani.c3p.zip)

## Steps to reproduce

1. Open project, save it to browser/cloud (google)
2. Close and open project (for good measure, I think it doesn´t matter)
3. Make changes to the "defaultGamesettings.json" (I usually add rows/write something, change keys/values)
4. Save project, and close it normally.
5. Open it again (Start page or open recent, doesn´t seem to matter)
6. The changes to the json did not save properly

## Observed result

The changes either don´t save, or partially save with multiple rows vanishing from it.

## Expected result

It to be saved properly I guess.

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
Must have been r145

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.103
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
C3 release: r146 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 775 mb (2.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2019-04-25 11:08
Nice catch, took me a little while to figure out what is going on here.

The problem is related to a recent change to ensure rows in dictionaries are in the user specified order. As the file format itself doesn't guarantee order it was decided to place the data in the user interface data for the dictionary file ( which also holds the sizes of rows/columns ). Turns out this data is not guaranteed to be up to date if you:

- change the dictionary row count / row names
- save the project ( without closing the dictionary file )

So the data in the file is correctly saved, but due to the customisation data being out of sync it doesn't read it all. Saving the file again after this will lose the unread data.

It should be fairly easy to workaround this until I can get a fix in place. Before saving the project either close any modified dictionary files or resize a row/ column slightly in those files.

**Comment by Wackytoaster** [comment] 2019-04-25 11:40
So I wasn´t going insane, what a relief! That was quick, thx for the info :)

**Comment by shortercode** [comment] 2019-04-25 16:24
No insanity, just edge cases! Should be resolved in the next beta :) Will also resolve another rarer issue where column/row sizes can get set to the wrong rows.

**Closed by shortercode** 2019-04-25 16:24 UTC
