### ISSUE TITLE
r295 Timeline - Crash Report When Changing Object Color

### ISSUE THREAD

**Issue by brainwavecreations** [Scirra/Construct-3-bugs#5721] opened 2022-05-20 23:06 UTC
Problem description
The Timeline Box Crashes when trying to change an objects Color value.  I've tried changing the color values within the Timeline Properties, and by clicking on the Object in the Layout then changing the Highlighted Color Value Box within the Object Properties on the Left Hand side.  It does not seem to matter what color I try to change it to.  It crashes while either scrubbing the timeline, or previewing the timeline.  Sometimes that color does not change at all, and when it does, I get the error report below.

Attach a .c3p
Any .C3P with any timeline will do.  Try to change the color.  Sometimes it will work, other times it will crash.  It's been hit or miss.  I had to give up trying to use the Timelines in r295

Steps to reproduce
1. Create New Project
2. Add Timeline
3. Add Object to Timeline
4. Add key frame to change the Object's color value.
5. Change color value in either the Timeline Properties, or by highlighting the object while in edit mode, and changing the color value in the Object Properties on the left hand side
6. Preview Timeline, or Scrub the Timeline and see the error message when the color change key frame is reached

Observed result
crash

Expected result
no crash

More details

I've tested this in multiple projects, and different objects, but the same result every time

This is the Crash Report:
Error report information
Type: unhandled exception
File: https://editor.construct.net/r295/projectResources.js, line 1160, col 153
Message: Uncaught TypeError: Cannot read properties of null (reading 'r')
Stack: TypeError: Cannot read properties of null (reading 'r') at nRa.Xm (https://editor.construct.net/r295/projectResources.js:1160:153) at d.Xm (https://editor.construct.net/r295/projectResources.js:1087:314) at d.Xm (https://editor.construct.net/r295/projectResources.js:1018:289) at d.okc (https://editor.construct.net/r295/projectResources.js:1017:470) at d.PQb (https://editor.construct.net/r295/projectResources.js:944:455) at d.Play (https://editor.construct.net/r295/projectResources.js:943:129) at d.Vhc (https://editor.construct.net/r295/components/bars/timelineBar/timelineBar.js:39:65) at d.c2.Jtc (https://editor.construct.net/r295/components/bars/timelineBar/timelineBar.js:57:470) at Iq.g.J.Xj.Yoa.Alb (https://editor.construct.net/r295/components/bars/timelineBar/timelineBar.js:50:216) at Yh (https://editor.construct.net/r295/main.js:394:158)
Construct version: r295
URL: https://editor.construct.net/r295/
Date: Fri May 20 2022 18:56:14 GMT-0400 (Eastern Daylight Time)
Uptime: 19028.9 s

Platform information
Product: Construct 3 r295 (beta)
Browser: Chrome 101.0.4951.67
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

Affected browsers/platforms:
I tested only in chromium based browsers

First affected release: r29
![Construct3 Crash Report](https://user-images.githubusercontent.com/94563122/169622959-54325a31-18ea-4ecf-b454-6f844e9c9a48.png)
5

**Comment by DiegoScirra** [comment] 2022-05-23 12:05
Is there any more information about this issue? I can't seem to reproduce it by following the steps starting from an empty project.

@brainwavecreations Can you upload a project that reproduces the crash?

**Comment by brainwavecreations** [comment] 2022-05-23 15:55
I didn't fully test different situations.  But, I was seeing this while setting color for length of time, then switching color back to normal right afterwards.  See the two key frames right next to each other at the 2 second mark.  I was setting the sprite object to Red for a length of time, then back to normal right in the next keyframe in the screenshot uploaded.  So it was set to red for over a second, then after that I was trying to switch it back to it's regular colors right after that set time.  Using the Color Property in the Timeline Editor.  I will try to do throw together a quick .c3p right now

**Comment by brainwavecreations** [comment] 2022-05-23 16:02
[error example.zip](https://github.com/Scirra/Construct-3-bugs/files/8756194/error.example.zip)

When I test play the timeline in this project, or click on the keyframe in the timeline, I get the same error.

**Comment by DiegoScirra** [comment] 2022-05-23 19:36
It looks like the problem is copying and pasting color keyframes using the keyboard shortcuts.

**Comment by brainwavecreations** [comment] 2022-05-23 19:41
Ahh, gotcha.  I tested with the buttons in the Timeline Editor as well, the copy, and paste UI buttons, with the same result.  Sometimes the color does not change as it was set on the key frame well.  I'd have to put together another .c3p to show that.

**Comment by DiegoScirra** [comment] 2022-05-23 19:44
I did find a related issue where the color changes weren't previewed, so I might have fixed that already.

**Comment by brainwavecreations** [comment] 2022-05-23 19:44
Awesome!  Glad to hear it :).  Thanks for all of your Help & Support @DiegoScirra

**Comment by DiegoScirra** [comment] 2022-05-24 12:02
This will be fixed in the next beta.

**Closed by DiegoScirra** 2022-05-24 12:02 UTC
Labels: can't reproduce

**Comment by brainwavecreations** [comment] 2022-05-24 15:39
Excellent.  Thank You!
