### ISSUE TITLE
glsl 2 dfDy, dfDx not supported in C3 effects?

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-3-bugs#2787] opened 2019-03-30 07:27 UTC
## Problem description

dfDy, dfDx functions not supported, shader compile failure on C3 (works in other Chrome online shader compilers)

## Attach a .c3p

Cannot attach project w/ effect, since effect compile fails. Addon attached, rename to Archive.c3addon.
[Archive.c3addon.zip](https://github.com/Scirra/Construct-3-bugs/files/3025224/Archive.c3addon.zip)

## Steps to reproduce

1. Load effect into c3
2. Create project w/ a sprite
3. Add effect to sprite

## Observed result
On adding effect to sprite, C3 throws an exception, unable to compile shader.
## Expected result

Shader compiler works.

## More details
Appears to fail on this line (if this is replaced, compile succeeds.)
    vec2 gradient = vec2(dFdx(intensity) * sgn.x, dFdy(intensity) * sgn.y);

This is included in the shader code at the top: #extension GL_OES_standard_derivatives : enable

**Affected browsers/platforms:** 

**First affected release:** 

## System details
Mac OS (10.14.4)
Chrome browser (73+, WebGL 2)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by MikalDev** [comment] 2019-03-30 23:14
The same code compiles on other online shader compilers in Chrome. Also is it possible to output more information from the shader compiler error output in the C3 error log? Currently, it's just a message that the compile failed and a stack trace.

**Comment by AshleyScirra** [comment] 2019-04-01 10:31
As with any WebGL extension, it must be enabled first via a call to `gl.getExtension()`, in this case `gl.getExtension("OES_standard_derivatives")`. Construct does not make this call, therefore the extension is unavailable. (Presumably other places where it works, they make that call to enable the extension.)

Currently Construct does not use any shader extensions because it affects compatibility - if some device somewhere doesn't support the extension then the shader fails to compile and the end result is the game either doesn't run or looks incorrect on that device. This inevitably results in bug reports filed with us asking for it to be fixed. So we consciously use only the ubiquitously supported subset of WebGL 1 in shaders.

In the case of OES_standard_derivatives specifically, support does not appear to be an issue as it appears to have [100% support](http://webglstats.com/webgl/extension/OES_standard_derivatives). We could add the call to enable it, but a significant complication is WebGL 2 support. The extension is built-in to WebGL 2, so it's not available as an extension. However you must enable GLSL 3.0 in the shader to switch to the newer GLSL version where it is built-in using the line `#version 300 es`. This in turn then prevents the shader compiling with WebGL 1. Therefore it is not possible to write a single shader that uses this extension and works in both WebGL 1 and WebGL 2; doing so requires multiple shader scripts for different versions of WebGL. This is not currently supported and would require a significant overhaul of the effects system to support. Given that the 80+ built-in effects all can be implemented with WebGL 1, the current approach does not seem to be too strict a limitation. Perhaps you can emulate the extension with a WebGL 1 shader only.

Classing this as a feature request and closing as not a bug; if you think the multiple shader script system is important then please file a suggestion at https://construct3.ideas.aha.io/

**Closed by AshleyScirra** 2019-04-01 10:31 UTC
Labels: enhancement

**Comment by MikalDev** [comment] 2019-04-02 20:41
Thanks for the detailed response @AshleyScirra . I will consider what if anything to ask for on the feature request and also thanks for the bug fix, that will help with shader debug (e.g. for the compile fails that only happen in C3, but not in other shader compilers.)

One quick comment on cross-platform compatibility, for some games that are targeted to only the desktop (via nw.js or Electron), I would be ok with setting a min config requiring a certain level of GLSL / WebGL2 support, since I will be working with a known 'browser' and can set user expectations on HW support. I understand for the widest possible support across web, mobile, desktop, this is a different story.

**Comment by AshleyScirra** [comment] 2019-04-03 12:27
Even on browsers that support WebGL 2, there are still a significant number of systems that only support WebGL 1, so I'm not sure that would actually work out well in practice.
