### ISSUE TITLE
project after converting to iOS has stopped working.

### ISSUE THREAD

**Issue by Madiosn** [Scirra/Construct-3-bugs#3159] opened 2019-07-19 13:32 UTC
When you convert this file to xCode and run it on an iOS device, it stops working.
## Problem description

The script associated with the search for the path stops running. That is, the ants cease to search for the path; they stand still; the conditions for the removal of the instance are not satisfied, provided that the path is not found. Some copies may start moving, but 95% of the search path does not work.

The problem only occurs on an iOS device. When running on a PC, everything works fine.
## Attach a .c3p
https://yadi.sk/d/FzejEwxhVaqQOg

## Steps to reproduce

1. Converted under iOS
2. Run the xcode
3. Installed on the iPhone X

## More details

The behavior of the search path and all actions associated with it. May work on 1 copy of the object of 20

Everything should work as it works when viewed on a PC. Ants are looking for a path, move on it, if they can not find a path, they are destroyed and new ones are created. If an ant is created in the wall, then it is also deleted because it cannot find a path.
**Affected browsers/platforms:** 
Checked on macbook Chrome browser - everything works OK!
xCode - last version 
iPhone x ios 12 (Last)

**First affected release:** 
r156-158
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2019-07-19 14:42
The project link you provided doesn't work. Please provide a valid link otherwise we cannot investigate.

**Comment by Madiosn** [comment] 2019-07-19 15:05
Sorry https://yadi.sk/d/mt75CqIbw6VMMg

**Comment by AshleyScirra** [comment] 2019-07-19 15:29
Attaching here for ease of access: [AntError.zip](https://github.com/Scirra/Construct-3-bugs/files/3411719/AntError.zip)

Please note as per the bug report guidelines it is quicker and more likely the issue will be fixed if you can provide a minimal project.

**Comment by Madiosn** [comment] 2019-07-19 15:38
Sorry, I did not quite understand what should be provided? I will provide everything you need. Here is the video https://youtu.be/dBhVPCDWIf8

It shows that the ants are standing and further stop.

If you run the project on a PC, you will see that everything is working fine and all the ants are busy.

For some reason, when importing, the search for the path for the ants and all the scripts associated with them will not stop.

**Comment by Madiosn** [comment] 2019-07-19 15:43
Here is a video of how it should work and how it works on a PC.

https://youtu.be/xuZrCas1l1o

**Comment by shortercode** [comment] 2019-07-22 11:33
There doesn't appear to be any obvious errors with the project. It looks like it's just taking a long time to calculate the paths on weaker devices. I did some comparisons between a PC, a MacBook and a first gen iPad Pro. Once the paths have been processed it behaves exactly the same as the PC version for me. These are roughly observed values, except for the last which I used a stopwatch.

PC Chrome: near instant
macOS Safari: around a second
iOS Safari: around 3 seconds
iOS Cordova: around 3 seconds
iOS Cordova ( connected to safari debugger ): 1 minute 30

There's obviously something weird that the debugger is doing that slows it down, so that's a bit of an outlier.

I can see that this project is different to the one you show in the video, so it could be that this doesn't actually reproduce with this project? My best guess is that project has a race condition. Basically part of the code only works is path finding occurs within a certain timeframe, which is an assumption that the slower path finding on iOS breaks.

I'm not that familiar with the path tracing system, and this doesn't appear to be specific to app builds ( or at least if it is, then the project provided doesn't demonstrate the issues ). Hence I'm going to reassign to @AshleyScirra, but I'm not sure there's any action to take here.

**Comment by Madiosn** [comment] 2019-07-22 11:42
Thanks for the comment. No, the project is just may differ in design, but nothing else has changed.

I distribute for xCode in iOS xCode. And run on iPhone X running iOS 12.3.1

Iphone x is quite a powerful phone to reproduce such calculations as it seemed to me. By the fact that changing the number of objects does not affect the behavior. I think the problem is something else. And I hope it can somehow solve.

**Comment by AshleyScirra** [comment] 2019-07-22 11:51
It sounds like it is working correctly, just slowly in specific circumstances. I don't think there is anything further we can do on this. If you still think there is an issue that ought to be investigated please file a new issue using the most minimal project possible, as per the bug report guidelines. This should ideally have something like 1 or 2 objects and 1 or 2 events, to prove the problem is in Construct and not a mistake in your events.

**Closed by AshleyScirra** 2019-07-22 11:51 UTC
Labels: iOS
