### ISSUE TITLE
full screen mode inerscaling does not work sometimes for iphone x or newer "r232"

### ISSUE THREAD

**Issue by robinhoed123** [Scirra/Construct-3-bugs#4504] opened 2021-01-25 19:30 UTC
## Problem description

 there is this issue where full screen mode inner scaling does not work sometimes see video.

https://user-images.githubusercontent.com/77982339/105751200-fbfd5d80-5f45-11eb-9134-71fa1cae0449.mov

## Attach a .c3p

[full screen mode bug.zip](https://github.com/Scirra/Construct-3-bugs/files/5868976/full.screen.mode.bug.zip)
 really simple project so you can test it for your self.

## Steps to reproduce

1.Open attached project
2. full screen mode has to be on inner scaling.
3.Build to Xcode & open the workspace
4.Run the Xcode workspace on locally attached device.

## Observed result

 full screen mode didn't scale the project correctly to my iPhone when i open my app. 
##e Expected result

 that it works fine every time i open the app and scales the project properly
## More details

 that it works fine every time i open the app

tested on iPhone 11and 11Pro  construct version r232 (beta) 
View port size 996x564 fullscreen mode: scale inner viewport fit: cover 
orientation Landscape pixel rounding off
**Affected browsers/platforms:** 

**First affected release:** 
i only tested  it on r232 
## System details

<details><summary>View details</summary>

PASTE HERE

</details>
[full screen mode bug.zip](https://github.com/Scirra/Construct-3-bugs/files/5868971/full.screen.mode.bug.zip)

**Comment by AshleyScirra** [comment] 2021-01-26 09:30
This looks the same as issue #4358. Does that issue also explain your issue?

**Comment by robinhoed123** [comment] 2021-01-26 10:56
No this is something else it is about full screen mode when it is set to inner scaling it doesn’t scale properly on my iPhone sometimes if I open the app and it stays that way until you re open the app (see video )

**Comment by AshleyScirra** [comment] 2021-01-26 11:01
The issue is that on the last run in the video, there is a black bar down the side, correct?

**Comment by robinhoed123** [comment] 2021-01-26 11:08
Sorry i read it more carefully and yes it like #4358. Only his issue is on outer scaling mode And mine is in inner scaling mode I didn’t  test if background coler bleeds through I’m gone do a lot more test and let you know best regards Robin

**Comment by AshleyScirra** [comment] 2021-01-26 16:11
OK, that sounds like pretty much the same issue, so closing as duplicate of #4358.

**Closed by AshleyScirra** 2021-01-26 16:11 UTC
