### ISSUE TITLE
Crash upon startup (last desktop version NWjs 0.44)

### ISSUE THREAD

**Issue by ItemME** [Scirra/Construct-3-bugs#3632] opened 2020-02-06 15:45 UTC
## Problem description

Construct Desktop version (last release) crash upon startup, it's most likely due to the fact it fails to load the profile image.

## Attach a .c3p

It's linked to the desktop version on itself, not a project (it fails to load on startup, I don't even have time to click on any project)

Happens once I'm logged in, if I'm not, it doesn't crash.

## Steps to reproduce

It reproduces everytime only on desktop, I tried to reproduce that on the online version, both on latest beta, only the desktop version crashes.

I tried to remove all data files from the desktop version (aka. appdata) to have a full fresh version, I wasn't login (obviously because of the cache clear) and it didn't crash, was working just fine, then I tried to login, and once I did it, it crashed a few seconds after saying "Error: The source image couldn't be decoded"

Also, I tried to start it in "safe mode" to make sure it wasn't on something on my end, same problem. (anyway I did a fully fresh install, and it kept happening)

## Observed result

![image](https://user-images.githubusercontent.com/6894037/73953264-6f0a6000-4900-11ea-89e0-24bab8d01b0f.png)

![image](https://user-images.githubusercontent.com/6894037/73953303-7d587c00-4900-11ea-91f8-9d6046213e02.png)

## Expected result

Well, it shouldn't crash.

## More details

It happened on the latest desktop version only, with the latest nwjs update you guys made.
Not happening on the web editor version

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: The source image could not be decoded.
Construct 3 version: r185
URL: https://editor.construct.net/r185/
Date: Thu Feb 06 2020 16:35:29 GMT+0100 (heure normale d’Europe centrale)
Uptime: 88 s

Platform information
Browser: NW.js
Browser version: 0.44.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.44.0 (like Chrome/80.0.3987.87)
C3 release: r185 (beta)
Language setting: fr-FR

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment] 2020-02-07 11:48
It works fine for me here.

The error looks like a possible failure requesting an image from the server (possibly your profile image). It could have been a brief outage. Is it working now?

**Comment by ItemME** [comment] 2020-02-07 13:24
@AshleyScirra Well, when it happened, it was working fine on the online editor, but not the desktop version. Maybe it is indeed an outage, I wouldn't know as it's not crashing anymore, I had to do a clean restart (clearing the entire cache) quite a few times in order to be able to do anything. My suggestion would be, if there's somehow a problem to load this image, place instead a placeholder, so at least the client isn't crashing because I wasn't able to work for hours, and I'm not sure I want that to happen again, if that's possible

**Comment by AshleyScirra** [comment] 2020-02-07 13:34
Without a way to reproduce the problem, it's not clear what really needs to be changed. I improved some of the error handling for the profile image, but that was a guess. Since this is no longer happening, closing the issue.

**Closed by AshleyScirra** 2020-02-07 13:34 UTC
Labels: can't reproduce, desktop
