### ISSUE TITLE
Adding a sprite (plugin) with the middle mouse button crash C3

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#29] opened 2017-04-07 12:35 UTC
## Problem description

Everytime i try to add a new sprite (plugin) by clicking with the middle mouse button C3 crash.

## Attach a .c3p

Trust me, there's no need to add a .c3p, it happens even with a blank project.

## Steps to reproduce

1. Create a new project.
2. Right click and go to "insert new object".
3. Double click on "sprite"
4. Instead of clicking with the left mouse button to position the sprite, click with the middle mouse button.

## Observed result

C3 simply crash.

## Expected result

Probably nothing.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r16/main.js, line 2, col 285224
Message: Uncaught Error: pointer already captured
Stack: Error: pointer already captured at Function.ǃQr (https://editor.construct.net/r16/main.js:2:285230) at s.ǃgs (https://editor.construct.net/r16/components/editors/layoutView/layoutView.js:1:37586) at Array.ǃxP.u (https://editor.construct.net/r16/components/editors/layoutView/layoutView.js:1:37094) at ǃp.Event.ǃWXR.ǃWXG (https://editor.construct.net/r16/main.js:2:283188) at window.ǃUN.dispatchEvent (https://editor.construct.net/r16/main.js:2:281769) at window.ǃUN.ǃgs (https://editor.construct.net/r16/components/editors/layoutView/layoutView.js:1:13559) at HTMLDivElement.ǃqD.ǃp.ǃqx.ǃp.ǃqH.ǃqR.j (https://editor.construct.net/r16/components/editors/layoutView/layoutView.js:1:3958) at HTMLDocument. (https://editor.construct.net/r16/main.js:2:278451)
Construct 3 version: r16
URL: https://editor.construct.net/
Date: Fri Apr 07 2017 09:32:17 GMT-0300 (Hora oficial do Brasil)
Uptime: 99.9 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 610 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2017-04-07 12:42
Possible duplicate of #4 ?

**Comment by BonzerKitten7** [comment] 2017-04-07 12:47
Probably, in the end the problem is the same. Sorry if my post is causing some kind of "pollution".

**Comment by AshleyScirra** [comment] 2017-04-07 15:31
Verified is same underlying cause, will follow up in #4.

**Closed by AshleyScirra** 2017-04-07 15:31 UTC
