### ISSUE TITLE
List value not available at runtime until changed

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#2363] opened 2018-11-22 14:55 UTC
## Problem description

Well this one took me a while to figure out.
I think it one of the last few in my project

## Attach a .c3p

[ListValueNotAvailable (1).zip](https://github.com/Scirra/Construct-3-bugs/files/2608495/ListValueNotAvailable.1.zip)

- Run preview
- DO NOT CHANGE LIST VALUES
- Left click to initiate adding list one value to list 2 value
- Result is displayed in Text Box below lists.

**Observe initial click results in incorrect value of 0**

- CHANGE ONE LIST VALUE ONLY
- Left click again to initiate add values

**Observe still incorrect value
as list value that was not changed is not taken into account.**

- Change other list value
- Left click

**Observe Addition calculation is correct only after both list boxes changed**

- Switch to C2 runtime
- Run preview

**Observe list calculation is correct even from first click without changing values.**

## Expected result

Like C2 default / first value is used , not zero

## First affected release

unknown I think has been since first release.

## Affected browsers/platforms

* Chrome: tested only

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 68.0.3440.75
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36
C3 release: r127 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 47 gb
Storage usage (approx): 1.1 gb (2.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA Quadro K3100M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2018-11-22 16:47
Thanks, should be fixed in the next release.

FYI normally a better approach to identifying bugs is just to display information in text objects. If you just show `List.SelectedText & newline & List2.SelectedText` in a text object, it becomes obvious both are empty strings. So the problem is actually SelectedText (and SelectedIndex it turns out) aren't initialised. By doing the int() and addition the issue got confused by the fact you're converting empty strings to numbers and adding them (in this case producing 0), making for unnecessarily complicated reproduction steps.

**Closed by AshleyScirra** 2018-11-22 16:47 UTC
Labels: c3runtime

**Comment by NetOneGames** [comment] 2018-11-23 10:52
Makes sense, noted for next time, though hopefully not too many more next times!

I think that select index one was also causing me issues... 

Cheers.
