### ISSUE TITLE
Layout view does not reset zoom

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2786] opened 2019-03-29 18:44 UTC
## Problem description
You accidentaly zoom your editor UI, you can't reset layout view zoom anymore. Only way to fix it is to close C3 editor.

## Steps to reproduce
1.Open new
2.Create sprite, color it, exit anim editor
3. Move your mouse over properties bar
4. Hold down Ctrl and scroll mouse(change zoom level)
5.Reset it back to 100%, try dragging select box in layout view or select sprite

## Observed result
You can reset other Ui zoom level, but layout view zoom is bugged out. To fix it you need to close browser tab/Close C3 editor
![ZoomBug](https://user-images.githubusercontent.com/28864889/55255355-1d666300-5263-11e9-810e-cd181c4841ff.jpg)

## Expected result
Can somehow reset layout view zoom level too.

## More details

Using C3 inside chrome browser

**Affected browsers/platforms:** 
Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 931 mb (6.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-04-01 10:07
I think this is the same issue as came up on the forum, caused by Chrome 73+. It should be fixed in the next beta. Note you can always use the zoom controls in the browser menu too.

**Closed by AshleyScirra** 2019-04-01 10:07 UTC
