### ISSUE TITLE
"find results" window is difficult to resize with Dark Theme

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#3482] opened 2019-11-18 04:18 UTC
![image](https://user-images.githubusercontent.com/5744908/69024281-3603d300-0a16-11ea-803f-aec37bc3f999.png)

When you put the mouse in that pink circle area at the bottom right corner of the window I expect it to show the resize cursor, but it only shows and allows resizing in the blue area — it feels difficult and confusing trying to find the place where to resize. Perhaps it's something to do with the subtle shadow that runs along the edges of the window?

**Comment by AshleyScirra** [comment] 2019-11-20 12:11
This is a regression from our big cursor rewrite in r173. It only happens because the non-modal find dialog is still displaying beneath the results bar, and the new cursor code did not handle this case correctly. Should be fixed in the next release.

**Closed by AshleyScirra** 2019-11-20 12:11 UTC
Labels: theme
