### ISSUE TITLE
Can't launch C3 anymore (very rarely)

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#911] opened 2017-10-10 09:35 UTC
## Problem description

when I start C3 from a desktop link (offline version) via chrome I get an error about browser plugins. I had only default google plugins enabled but after disabling all of them its still not working anymore.

I had this issue about 50% of the time when I restarted C3 it worked but I just updated Visual Studio to 15.4 and now its happening the whole time.

## Attach a .c3p

no project problem

## Steps to reproduce

1. launch desktop shortcut to offline C3

## Observed result

error message
http://www.bilder-upload.eu/show.php?file=3e242d-1507628152.png

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

not available cant launch C3

</details>

**Comment by AshleyScirra** [comment] 2017-10-10 10:00
Do you have any browser addons? Does it still reproduce if you disable them? Are there any more useful error messages in the browser console? This looks like a script simply failed to load, which might be due to content blockers.

**Comment by TheBl4ckSh33p** [comment] 2017-10-10 11:31
When I open Chrome Plugins only a few google plugins are listed but all are deactivated. It works fine in Chrome when I open C3 there but the desktop link seems broken.

**Comment by AshleyScirra** [comment] 2017-10-10 14:43
Are there any more useful error messages in the browser console?

**Comment by AshleyScirra** [comment] 2017-10-10 15:12
Also looks like the same problem as #858, which is so far inconclusive.

**Comment by tunchunairarko** [comment] 2017-10-12 06:19
I am also having the same problem. I can't open Construct 3 at all anymore since yesterday.
Browser: Chrome
![untitled](https://user-images.githubusercontent.com/7689333/31481935-a22a5e54-af47-11e7-95eb-dca35c67f53a.png)

**Comment by TheBl4ckSh33p** [comment] 2017-10-12 08:11
This is in Chrome console when I got the error:

Registered root service worker on https://editor.construct.net/
htmlimports.js:1 [HTMLImports] Using polyfill
blob:https://editor.construct.net/8b88e50a-c2af-48b4-a051-11474b653cb0:6 Uncaught TypeError: Cannot set property 'Type' of undefined
    at blob:https://editor.construct.net/8b88e50a-c2af-48b4-a051-11474b653cb0:6:22
blob:https://editor.construct.net/b5503d6c-e74f-4c86-9fbb-d4ee7eec439a:6 Uncaught TypeError: Cannot set property 'Instance' of undefined
    at blob:https://editor.construct.net/b5503d6c-e74f-4c86-9fbb-d4ee7eec439a:6:26

**Comment by AshleyScirra** [comment] 2017-10-16 10:23
We've identified a possible race condition in loading addons. This might be fixed in r64 - marking as needing a check after release.

**Comment by joelmayer87** [comment] 2017-10-16 11:27
I just wanted to note that this happens to me every time i load C3 for the first time but only on my Windows PC and with the same Addons installed. It's only after Startup and launching C3 for the very first time. As soon as i reload the site, everything works again.

**Comment by TheBl4ckSh33p** [comment] 2017-10-19 09:16
Had no error with r64 so far. (Installed 2 mods from rex: datetime and moveto)

**Comment by tunchunairarko** [comment] 2017-10-19 09:20
@AshleyScirra Fixed

**Comment by AshleyScirra** [comment] 2017-10-19 10:51
Great, thanks for confirming.

**Closed by AshleyScirra** 2017-10-19 10:51 UTC
