### ISSUE TITLE
found several bugs in the Animation editor

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#4212] opened 2020-09-13 06:28 UTC
i have seen several random bugs in the animation editor. From random i mean i have seen different different bugs on same type of tools and some of them i did not seen again and instead of that i have seen some other bugs there. looks like on each different combination of tools usage creating different bugs.

1. When i choose Eraser, Pencil, Brush, Line, Rectangle, fill, eye dropper or image point tool then if click and hold anywhere then selection toolbar was showing but later it was working good.
2. When eraser tool is selected and try to erase something whole image looks erased but bottom preview is showing there is still an image and eraser is erasing it. I mean eraser is working properly behind the scene but we can only see all screen is erased But once we switch to another frame and come back to that frame again. it showed correct image where we did some erase.

I also noted that some of these bugs activated by pressing shortcut key of these tools.

## Attach a .c3p
No file need but a video attached
Video is 3.5 min long
![Animation editor bugs](https://user-images.githubusercontent.com/17684135/93011733-6f658a80-f5b6-11ea-87ab-5d6c269d29f9.gif)

## Steps to reproduce

1. Create New Project
2. Insert Sprite
3. play here by combination of pressing short keys and click on tools directly then click drag over screen see video for reference

## Observed result

multiple bugs of animation editor tools

## Expected result

tools should work properly

## More details

**Affected browsers/platforms:** 

**First affected release:** 
worked in r214 but broke in r215

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by birbdoy** [comment] 2020-09-13 09:19
Yes, the animation editor is practically unusable in r215. Everything seems to be affected, e.g. the fill bucket fills the whole image. Changing tools and going out and back in to the animation editor breaks things further, e.g. switching between origin point mode and the paint brush lets you move the origin point while simultaneously drawing lines on your image.

**Comment by DiegoScirra** [comment] 2020-09-14 10:37
Duplicate of #4209. fixed in the next beta. The same issue is causing lot's of different problems.

**Closed by DiegoScirra** 2020-09-14 10:37 UTC
Labels: duplicate
