### ISSUE TITLE
When testing game, tiles from tilemap are incorrectly displayed

### ISSUE THREAD

**Issue by MrCreightonD** [Scirra/Construct-3-bugs#786] opened 2017-09-06 22:09 UTC
## Problem description

When I place a tile from a tilemap and then test the game, it actually displays the tile next to it in the tile map. It appears that this may be happening when using a tilemap with empty space in it. Usually starts happening when adding tiles from the 2nd row in the tilemap.

## Attach a .c3p

[tilemapissues.zip](https://github.com/Scirra/Construct-3-bugs/files/1282815/tilemapissues.zip)

## Steps to reproduce

1. Add a tilemap with empty space in it.
2. Place tiles from the 2nd row of tilemap into layout.
3. Test game

## Observed result

Wrong tile being displayed

## Expected result

The tile that I selected being displayed.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2017-09-15 15:59
The problem is the tileset image is not wide enough. There are 14 tiles sized 64x64, and a tile offset of 1px, meaning the width of the tileset image should be 897px. However it's actually truncated to 895px. Perhaps you subtracted rather than added the tile offset?

The consequence is the last tile in the row is not big enough: it's 62px wide instead of 64px. The runtime sees that the last tile is not big enough and so ignores it and wraps down to the next row. On the other hand it appears the editor uses the incomplete tile on the end, and then tile indices become offset the next row down. It should not do this, it should ignore the incomplete tile as well, and then tile indices will be consistent with the runtime. This is the best thing to do since if there is a 1px border all the way around the image with a 1px offset, you'd expect it to wrap down to the next row at the last complete tile, whereas the editor will try to use a 1px wide tile at the end of the row.

Since this is Diego's code, assigning back to him. The workaround is easy: resize the tileset image to be 897px wide.

**Comment by AshleyScirra** [comment] 2017-09-15 15:59
Oops, didn't mean to close.

**Comment by DiegoScirra** [comment] 2017-09-18 14:52
Fixed in r57.

The editor and the runtime should display the same now.

**Closed by DiegoScirra** 2017-09-18 14:52 UTC
