### ISSUE TITLE
Platform Sinking Into Jump-Thru Objects At Peak of Jump

### ISSUE THREAD

**Issue by AySquirrel** [Scirra/Construct-3-bugs#2901] opened 2019-04-30 00:24 UTC
## Problem description

Platform instances will sink into jump-thru objects if the jump-thru object is landed on at the peak of a jump. Noticed this has been brought up quite a few times, but with some trouble recreating it. So I tried doing that... again lol

## Attach a .c3p

[JumpThruSinkBug.zip](https://github.com/Scirra/Construct-3-bugs/files/3129574/JumpThruSinkBug.zip)

## Steps to reproduce

1. Start the project
2. Using the arrow keys, attempt to jump onto the green platform in the middle of the screen
3. Fall off of the platform and repeat as necessary

## Observed result

It may need to be done a couple of times, but somewhat consistently (for me at least) the red square will not fully land on the green platform, and instead will slowly "sink" through it.  The effect of this can be seen on animation triggers as well, since the red square is programmed to turn blue upon jumping, and then turn red again either upon falling or landing on another platform. When the "sink" occurs, both of these triggers fail to activate.

## Expected result

The red square to either land on the platform or fall through it, and turn red again once one of these events occured.

## More details

**Affected browsers/platforms:**

Chrome, Firefox

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.103
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
C3 release: r147 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 4.4 gb (7.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-04-30 10:36
Possibly related to #2321, #2537
I tried over 10 times and couldn't see anything wrong happening. It's essential to have a reliable way to reproduce the issue for us to be able to investigate and fix it.

**Comment by AySquirrel** [comment] 2019-04-30 16:55
That's so weird...  I opened it again just now and it happens to me almost every time...

video: https://youtu.be/YY_oBufddGY

I'll make another project that automates it at a variety of different jump heights and then try uploading that I guess? Just needa eat something first

**Comment by AshleyScirra** [comment] 2019-04-30 17:13
Closing since reporter can't reproduce any more, please re-file when you have a reliable repro.

**Closed by AshleyScirra** 2019-04-30 17:13 UTC
Labels: can't reproduce
