### ISSUE TITLE
Can’t run projects on iPad 12.9 latest model

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1493] opened 2018-04-16 19:56 UTC
## Problem description

Load any project from the construct list, hit play, fails.
Can’t switch between the project and another window, construct refreshes, closes the project, and has me as guest after refresh.
Can’t do the tutorials because can’t save anything on my iPad 12.9 inch 512gig device.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Get an iPad 12.9 inch 512 gig
2. Open construct and login
3. Open any project
4. Hit play

## Observed result

*What do you see happen?*
Error
## Expected result

*What did you expect to happen instead?*
The project to run
## Affected browsers
safari
![8773abbb-e94d-4fb0-9942-f0c1913c5cab](https://user-images.githubusercontent.com/4122283/38831845-45e742e8-4186-11e8-9ae9-1d60b6e20b74.png)
![5a1cd474-7ea6-498e-b592-7b676338c312](https://user-images.githubusercontent.com/4122283/38831846-462b6a86-4186-11e8-94e3-42497e2bc5c1.png)
![d20cd7c0-3f3c-42a9-b549-ecc9efb6f0f8](https://user-images.githubusercontent.com/4122283/38831883-662c9616-4186-11e8-9e9f-cc0b3ed69608.png)

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2018-04-16 20:07
Which C3 version are you using? Please include the information requested on the bug report forum, since it  includes this. If you haven't tried r95 it may be worth giving it a go since we already worked around a bug in Safari 11.1 (#1460).

**Comment by zumwaltwood** [comment] 2018-04-16 21:36
R94.2 on the iPad so, on the iPad how do I switch to r95?

**Comment by AshleyScirra** [comment] 2018-04-16 21:40
Visit: editor.construct.net/r95

**Comment by zumwaltwood** [comment] 2018-04-16 21:41
I loaded r95, it won't run on the iPad, gives unhandled rejection
Reason: error: creatImageBitmap with ArrayBuffer or Blob is not implemented
Construct 3 Version: r95
url: https://editor.construct.net/r95/

**Comment by zumwaltwood** [comment] 2018-04-16 21:41
Error report information

*Type:* unhandled rejection
*Reason:* Error: createImageBitmap with ArrayBuffer or Blob is not
implemented
*Construct 3 version:* r95
*URL:* https://editor.construct.net/r95/
*Date:* Mon Apr 16 2018 16:39:31 GMT-0500 (CDT)
*Uptime:* 63.7 s
Platform information

*Browser:* Safari
*Browser version:* 11.0
*Browser engine:* WebKit
*Browser architecture:* (unknown)
*Context:* browser
*Operating system:* iOS
*Operating system version:* 11.3
*Operating system architecture:* (unknown)
*Device type:* mobile
*Device pixel ratio:* 2
*Logical CPU cores:* (unavailable, defaulting to 2)
*Approx. device memory:* (unavailable)
*User agent:* Mozilla/5.0 (iPad; CPU OS 11_3 like Mac OS X)
AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148
Safari/604.1
*C3 release:* r95 (beta)
*Language setting:* en-US
WebGL information

*Version string:* WebGL 1.0 (OpenGL ES 2.0 Metal - 52.3.2)
*Numeric version:* 1
*Supports NPOT textures:* partial
*Supports GPU profiling:* no
*Vendor:* Apple Inc.
*Renderer:* Apple A10X GPU
*Major performance caveat:* no
*Maximum texture size:* 4096
*Point size range:* 1 to 511
*Extensions:* EXT_blend_minmax, EXT_sRGB, OES_texture_float,
OES_texture_float_linear, OES_texture_half_float,
OES_texture_half_float_linear, OES_standard_derivatives,
EXT_shader_texture_lod, EXT_texture_filter_anisotropic,
OES_vertex_array_object, OES_element_index_uint, WEBGL_lose_context,
WEBKIT_WEBGL_compressed_texture_pvrtc, WEBGL_depth_texture,
ANGLE_instanced_arrays, WEBGL_debug_renderer_info

**Comment by AshleyScirra** [comment] 2018-04-16 21:49
Do you get that error with the Ghost Shooter template? Which project are you testing exactly?

**Comment by zumwaltwood** [comment] 2018-04-16 22:11
That error was just trying to launch r95
Straight to that crash

**Comment by zumwaltwood** [comment] 2018-04-16 23:07
Got in r95, tried opening. Kiwi story then:
Error report information

*Type:* unhandled rejection
*Reason:* Error: createImageBitmap with ArrayBuffer or Blob is not
implemented
*Construct 3 version:* r95
*URL:* https://editor.construct.net/r95/
*Date:* Mon Apr 16 2018 18:06:23 GMT-0500 (CDT)
*Uptime:* 20.9 s
Platform information

*Browser:* Safari
*Browser version:* 11.0
*Browser engine:* WebKit
*Browser architecture:* (unknown)
*Context:* browser
*Operating system:* iOS
*Operating system version:* 11.3
*Operating system architecture:* (unknown)
*Device type:* mobile
*Device pixel ratio:* 2
*Logical CPU cores:* (unavailable, defaulting to 2)
*Approx. device memory:* (unavailable)
*User agent:* Mozilla/5.0 (iPad; CPU OS 11_3 like Mac OS X)
AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148
Safari/604.1
*C3 release:* r95 (beta)
*Language setting:* en-US
WebGL information

*Version string:* WebGL 1.0 (OpenGL ES 2.0 Metal - 52.3.2)
*Numeric version:* 1
*Supports NPOT textures:* partial
*Supports GPU profiling:* no
*Vendor:* Apple Inc.
*Renderer:* Apple A10X GPU
*Major performance caveat:* no
*Maximum texture size:* 4096
*Point size range:* 1 to 511
*Extensions:* EXT_blend_minmax, EXT_sRGB, OES_texture_float,
OES_texture_float_linear, OES_texture_half_float,
OES_texture_half_float_linear, OES_standard_derivatives,
EXT_shader_texture_lod, EXT_texture_filter_anisotropic,
OES_vertex_array_object, OES_element_index_uint, WEBGL_lose_context,
WEBKIT_WEBGL_compressed_texture_pvrtc, WEBGL_depth_texture,
ANGLE_instanced_arrays, WEBGL_debug_renderer_info

**Comment by AshleyScirra** [comment] 2018-04-17 11:07
@zumwaltwood - we just released r95.2 which hopefully fixes the second issue (involving "createImageBitmap") - could you try it and see if the issue is resolved? https://editor.construct.net/r95-2/

**Comment by jaydonteh** [comment] 2018-04-17 11:39
I recently tried C3 in an Apple store on the 12.9 Ipad Pro and seems to be fine tho

**Comment by zumwaltwood** [comment] 2018-04-17 12:32
My ipad is at home, as soon as i get home from work after 5pm CST i will
give you an update.

Thanks
Jonathan Wood

**Comment by zumwaltwood** [comment] 2018-04-18 00:34
I was able to get to login, load projects and run the examples. But can’t
do anything with google drive.

**Comment by zumwaltwood** [comment] 2018-04-18 00:43
Error report information

*Type:* unhandled rejection
*Reason:* browser does not support downloading local content
*Construct 3 version:* r95.2
*URL:* https://editor.construct.net/r95-2/index.html
*Date:* Tue Apr 17 2018 19:41:09 GMT-0500 (CDT)
*Uptime:* 99.6 s
Platform information

*Browser:* Safari
*Browser version:* 11.0
*Browser engine:* WebKit
*Browser architecture:* (unknown)
*Context:* webapp
*Operating system:* iOS
*Operating system version:* 11.3
*Operating system architecture:* (unknown)
*Device type:* mobile
*Device pixel ratio:* 2
*Logical CPU cores:* (unavailable, defaulting to 2)
*Approx. device memory:* (unavailable)
*User agent:* Mozilla/5.0 (iPad; CPU OS 11_3 like Mac OS X)
AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148
Safari/604.1
*C3 release:* r95.2 (beta)
*Language setting:* en-US
WebGL information

*Version string:* WebGL 1.0 (OpenGL ES 2.0 Metal - 52.3.2)
*Numeric version:* 1
*Supports NPOT textures:* partial
*Supports GPU profiling:* no
*Vendor:* Apple Inc.
*Renderer:* Apple A10X GPU
*Major performance caveat:* no
*Maximum texture size:* 4096
*Point size range:* 1 to 511
*Extensions:*
 EXT_blend_minmax, EXT_sRGB, OES_texture_float, OES_texture_float_linear,
OES_texture_half_float, OES_texture_half_float_linear,
OES_standard_derivatives, EXT_shader_texture_lod,
EXT_texture_filter_anisotropic, OES_vertex_array_object,
OES_element_index_uint, WEBGL_lose_context,
WEBKIT_WEBGL_compressed_texture_pvrtc, WEBGL_depth_texture,
ANGLE_instanced_arrays, WEBGL_debug_renderer_info

**Comment by zumwaltwood** [comment] 2018-04-18 00:53
Google drive, drop box, doesn’t matter, it always kicks me out of the app
and takes me to safari, showing me the last webpage I was on

**Comment by zumwaltwood** [comment] 2018-04-18 01:01
Cloud save r92.2

Found the work around, ONLY use the editor from safari not shortcut you
recommend making. In other words,this way is wrong, launched from iPad
desktop icon

This way works

**Comment by zumwaltwood** [comment] 2018-04-18 01:14
And now, I can’t open any projects, internet is fine, I have even closed
the browser etc.

**Comment by zumwaltwood** [comment] 2018-04-18 01:44
Was working with the tools on the right then the program crashed

Error report information

*Type:* unhandled exception
*File:* https://editor.construct.net/r95-2/main.js, line 74, col 1477391
*Message:* Error: Animations Editor undo buffer is already initialized
*Stack:* ǃWCO@https://editor.construct.net/r95-2/main.js:74:1477335 ǃdl@
https://editor.construct.net/r95-2/main.js:74:1184784 ǃIe@
https://editor.construct.net/r95-2/components/bars/projectBar/projectBar.js:1:7335
ǃZg@
https://editor.construct.net/r95-2/components/bars/projectBar/projectBar.js:1:7182
ǃZSX@https://editor.construct.net/r95-2/main.js:2:195481 ǃVO@
https://editor.construct.net/r95-2/main.js:2:430376 dispatchEvent@[native
code] ǃZSW@https://editor.construct.net/r95-2/main.js:2:189812 ǃZSd@
https://editor.construct.net/r95-2/main.js:2:190212
https://editor.construct.net/r95-2/main.js:2:191668
*Construct 3 version:* r95.2
*URL:* https://editor.construct.net/r95-2/
*Date:* Tue Apr 17 2018 20:42:35 GMT-0500 (CDT)
*Uptime:* 170.1 s
Platform information

*Browser:* Safari
*Browser version:* 11.0
*Browser engine:* WebKit
*Browser architecture:* (unknown)
*Context:* browser
*Operating system:* iOS
*Operating system version:* 11.3
*Operating system architecture:* (unknown)
*Device type:* mobile
*Device pixel ratio:* 2
*Logical CPU cores:* (unavailable, defaulting to 2)
*Approx. device memory:* (unavailable)
*User agent:* Mozilla/5.0 (iPad; CPU OS 11_3 like Mac OS X)
AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148
Safari/604.1
*C3 release:* r95.2 (beta)
*Language setting:* en-US
WebGL information

*Version string:* WebGL 1.0 (OpenGL ES 2.0 Metal - 52.3.2)
*Numeric version:* 1
*Supports NPOT textures:* partial
*Supports GPU profiling:* no
*Vendor:* Apple Inc.
*Renderer:* Apple A10X GPU
*Major performance caveat:* no
*Maximum texture size:* 4096
*Point size range:* 1 to 511
*Extensions:* EXT_blend_minmax, EXT_sRGB, OES_texture_float,
OES_texture_float_linear, OES_texture_half_float,
OES_texture_half_float_linear, OES_standard_derivatives,
EXT_shader_texture_lod, EXT_texture_filter_anisotropic,
OES_vertex_array_object, OES_element_index_uint, WEBGL_lose_context,
WEBKIT_WEBGL_compressed_texture_pvrtc, WEBGL_depth_texture,
ANGLE_instanced_arrays, WEBGL_debug_renderer_info

**Comment by shortercode** [comment] 2018-04-18 10:59
@zumwaltwood that crash seems to be more of a separate bug report. Nevertheless I found a replication for it.

1. Open project
2. Swipe in the project bar
3. Open a sprite
4. The animations editor will open over the top of the project bar
5. Tap on the project bar to bring it into focus ( dont close the anim editor )
6. Open a second sprite
7. Crash

The issue seems to be a combination of the mobile layout and a presumption that the anim. editor cannot be opened when it's already open.

**Comment by zumwaltwood** [comment] 2018-04-19 17:56
Add a sprite object to the scene


Double tap the sprite object to open for edit


Your now locked up, so minimize the browser back to the tablet desktop
(loose focus), then gain focus back, now you can update the sprite object

**Comment by zumwaltwood** [comment] 2018-04-19 18:01
As you select objects in the heirarchy, the properties window does not
update, this is bad...

**Comment by AshleyScirra** [comment] 2018-04-20 11:40
Please note we need a full report following all the guidelines for each reported issue to be able to investigate them. If you simply mention a problem in a comment, it is often impossible to do anything about it.

There are a number of issues mentioned in this report. As far as I can tell they are:

- Original report: should be fixed in r95.2
- "createImageBitmap" error: should be fixed in r95.2
- One report of "createImageBitmap" in r94.2: was just using older version
- "browser does not support downloading local content": need steps to reproduce this one so cannot directly investigate yet
- Cloud save issue: reported version was r92.2 which is an old version, will investigate if it reproduces in latest release
- "Animations Editor undo buffer": will split off in to separate report

If you have other issues, please file separate issues for them following all the guidelines, otherwise we likely cannot help. Closing this issue, will follow up other reports separately. To be able to investigate the "browser does not support downloading local content" error we need to know exactly what you were doing, including the steps to reproduce, so please file a new issue for that.

**Closed by AshleyScirra** 2018-04-20 11:40 UTC
Labels: iOS

**Comment by AshleyScirra** [comment] 2018-04-20 11:43
Filed animations editor issue as #1493
