### ISSUE TITLE
Broken project after copy/paste objects and events from another

### ISSUE THREAD

**Issue by IcticStep** [Scirra/Construct-3-bugs#3941] opened 2020-06-11 14:30 UTC
## Problem description

I was working on a big game and meet the unexpected behaviour I didn't understand, so I created new project to isolate the problem and maybe to ask for a solution on the forum but after pasting all objects and conditions needed, project broke. Now, I can't open it and Construct 3 crashes when I am trying to start it.

## Attach a .c3p

Project: https://drive.google.com/file/d/1aoUphMYYpWKgsLsY7PQxBbbwIyjh9XdN/view?usp=sharing

## Steps to reproduce

1.Open the project.
2.See the message "Oops! Something went wrong."

## Observed result

An error message. I can`t open the project.

## Expected result

I was expecting an normal opening my project.

## More details

**Affected browsers/platforms:** 
Construct 3 web app(installed on desktop)

**First affected release:** 
 Don`t know. I am using the last stable version and it has this problem.
## System details

<details><summary>View details</summary>
Error report information
Type: unhandled rejection
Reason: Error: invalid function name 'killThePlayersCube_GameTestingGame1' @ Error: invalid function name 'killThePlayersCube_GameTestingGame1' at t.ǃuNA (https://editor.construct.net/r197-2/projectResources.js:1:307002) at t.ǃGk (https://editor.construct.net/r197-2/projectResources.js:1:306916) at window.ǃwYM.ǃuNU (https://editor.construct.net/r197-2/projectResources.js:1:331642) at t.accept (https://editor.construct.net/r197-2/projectResources.js:1:261253) at t.accept (https://editor.construct.net/r197-2/projectResources.js:1:297456) at t.ǃuNR (https://editor.construct.net/r197-2/projectResources.js:1:283298) at t.accept (https://editor.construct.net/r197-2/projectResources.js:1:261269) at e.ǃuNR (https://editor.construct.net/r197-2/projectResources.js:1:268591) at e.accept (https://editor.construct.net/r197-2/projectResources.js:1:261269) at window.ǃwDe.ǃuNR (https://editor.construct.net/r197-2/projectResources.js:1:268591)
Stack: Error: invalid function name 'killThePlayersCube_GameTestingGame1' at t.ǃuNA (https://editor.construct.net/r197-2/projectResources.js:1:307002) at t.ǃGk (https://editor.construct.net/r197-2/projectResources.js:1:306916) at window.ǃwYM.ǃuNU (https://editor.construct.net/r197-2/projectResources.js:1:331642) at t.accept (https://editor.construct.net/r197-2/projectResources.js:1:261253) at t.accept (https://editor.construct.net/r197-2/projectResources.js:1:297456) at t.ǃuNR (https://editor.construct.net/r197-2/projectResources.js:1:283298) at t.accept (https://editor.construct.net/r197-2/projectResources.js:1:261269) at e.ǃuNR (https://editor.construct.net/r197-2/projectResources.js:1:268591) at e.accept (https://editor.construct.net/r197-2/projectResources.js:1:261269) at window.ǃwDe.ǃuNR (https://editor.construct.net/r197-2/projectResources.js:1:268591)
Construct 3 version: r197.2
URL: https://editor.construct.net/
Date: Thu Jun 11 2020 17:25:51 GMT+0300 (Восточная Европа, летнее время)
Uptime: 1617 s

Platform information
Browser: Chrome
Browser version: 83.0.4103.97
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
C3 release: r197.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2
</details>

**Comment by AshleyScirra** [comment] 2020-06-11 17:23
I've seen similar reports a few times now. The project has an action that calls a function named `killThePlayersCube_GameTestingGame1`, but the function is really called `killThePlayersCube_GameTestingGame2`. There's a similar case with a function named `scrollSmooth_GameTestingGame1_to` as well.

This ought to be impossible to achieve in the editor. I've tried to reproduce this by copying and pasting events between projects, but I've never been able to reproduce this. There must be some loophole where if you do some particular kind of copy and paste, it gets the function names wrong and results in a corrupt project.

Can you figure out what you did and come up with a way to reproduce this? As it's come up a few times there must be a real problem that people keep running in to, but I have no idea what's happening. All I can do is keep recovering the projects whenever this happens, but the underlying problem is still there so it will keep on happening to people.

Here's the recovered project for now: 
[recovered.zip](https://github.com/Scirra/Construct-3-bugs/files/4766270/recovered.zip)

**Comment by IcticStep** [comment] 2020-06-12 06:46
> I've seen similar reports a few times now. The project has an action that calls a function named `killThePlayersCube_GameTestingGame1`, but the function is really called `killThePlayersCube_GameTestingGame2`. There's a similar case with a function named `scrollSmooth_GameTestingGame1_to` as well.
> 
> This ought to be impossible to achieve in the editor. I've tried to reproduce this by copying and pasting events between projects, but I've never been able to reproduce this. There must be some loophole where if you do some particular kind of copy and paste, it gets the function names wrong and results in a corrupt project.
> 
> Can you figure out what you did and come up with a way to reproduce this? As it's come up a few times there must be a real problem that people keep running in to, but I have no idea what's happening. All I can do is keep recovering the projects whenever this happens, but the underlying problem is still there so it will keep on happening to people.
> 
> Here's the recovered project for now:
> [recovered.zip](https://github.com/Scirra/Construct-3-bugs/files/4766270/recovered.zip)

Okay, thank you a lot for recovering the project. I have just reproduced this bug and
there is the same broken file now: [project-file](https://drive.google.com/file/d/1q-j3IKh9RRPslf_UsTLr4RmnYJT8eZrW/view?usp=sharing) . There is no need to recover this, because this is the same as previous, maybe just sprites have different positions.

 I think that`s happening when you are trying to copy events from one project to another, using web app of Construct 3 installed on desktop. Important thing is that both projects should be opened in different windows of Constuct 3. So, as I see it to reproduced.

**1.** Open a project with some events and objects in one window and put it left.
**2.** Open one more time Construct, put it right and create a new project.
**2.5**. Maybe it is not important, but I have tried to copy events and had message that I forget to add object 'Touch', then I added it, had the message that I forget to add 'gameTesting_game1_touchToJumpZone', added it and then I pasted events. Important note: all events were pasted all together for one time.
**3.** Try to start project preview. In my case, all I seen after this was black screen, which boost me to restart Construct 3 and get the error.

I hope, it helps to investigate this case of strange bug. If not, I can email you my big project, from which I was copping events for your look inside. Maybe, there is something broken inside it, but I will defenitly not publish it on github, because I have worken on it half a year and have done more than 2300 actions, 1000 events, 950 conditions and 347 object types. Studing this big _[don`t know how to name it]_ should be very interesting and can take the best years of your life ;)

**Comment by AshleyScirra** [comment] 2020-06-12 12:14
Thanks, that's great - I think I can reproduce it reliably now:
[noevents-notouch.zip](https://github.com/Scirra/Construct-3-bugs/files/4770663/noevents-notouch.zip)

1. Open recovered.zip project
2. Copy all events
3. Close project
4. Open noevents-notouch.zip project
5. Try to paste events - error shown due to missing Touch object
6. Add Touch object
7. Paste events again - function names are inconsistent

It doesn't reproduce if you add the Touch plugin first so the first paste is successful - so I think it's something being left in a bad state when you paste events with functions but it shows an error. Hopefully I can figure it out from here. Thanks for the info!

**Comment by IcticStep** [comment] 2020-06-12 12:36
Ok, I was glad to help to find this bug and to contribute to Construct in all available ways. Really glad to see that developpers are really working on they product after release and have a strong connections with community. A lot of thanks! You are very nice!

**Comment by AshleyScirra** [comment] 2020-06-12 13:46
OK, I think I have a fix for this. It's a potentially serious bug but we're close to a stable release, so I think this justified a .3 release to verify it.

**Closed by AshleyScirra** 2020-06-12 13:46 UTC

**Comment by gbb6879** [comment] 2024-05-12 10:32
Hello, I seem to be having this issue, when pasting a object unsuccessfully it seems to make a invisible object or something of the sorts in the editor with the name, as "the name is already used" appears. after reloading the project you are greeted with the broken file message.

**Comment by WilsonPercival** [comment] 2024-05-12 10:38
> Hello, I seem to be having this issue, when pasting a object unsuccessfully it seems to make a invisible object or something of the sorts in the editor with the name, as "the name is already used" appears. after reloading the project you are greeted with the broken file message. -- this is with the v390 beta

@gbb6879 Can you write a new report with steps to reproduce? Otherwise it will be impossible to help.
