### ISSUE TITLE
Dark/Light theme + breakpoints can lead to locked event blocks

### ISSUE THREAD

**Issue by birbdoy** [Scirra/Construct-3-bugs#2552] opened 2019-01-25 21:25 UTC
## Problem description

I encountered this bug in Chrome, it behaves slightly differently in Firefox (see below for details). It only happens when using the dark or light theme. 
Using breakpoints and stepping through logic in the debugger outlines the whole event block instead of just the conditions (which happens when using the default theme). In this outlined state event blocks are uneditable and stay like this even after closing the debugger.

## Attach a .c3p

[breakpoints.zip](https://github.com/Scirra/Construct-3-bugs/files/2797704/breakpoints.zip)

## Steps to reproduce

1. Use the dark or light theme and start the debugger.
2. Step through logic until a whole event block is outlined like this: ![screenshot](https://user-images.githubusercontent.com/34073404/51770332-c1a61f00-20e5-11e9-877c-453df52df99b.png)
3. The outlined event block is now uneditable, the only way to make changes to it is by right clicking on the event number on the left. The conditions and actions are no longer clickable or moveable and stay this way even after closing the debugger.

## Observed result

Event blocks get locked and become uneditable.

## Expected result

Event blocks shouldn't get locked. I guess in the best case things should work identically across themes.

## First affected release

Most older releases give me an error so this is impossible for me to pin down. In chrome, r100 already has this issue while r50 only locks the events as long as the debugger is running.

## Affected browsers/platforms

* Chrome: yes, event blocks become locked and stay locked like described above. 
* Firefox: yes, but event blocks become editable again after closing the debugger (comparable to r50 in chrome).

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r135.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.9 gb
Storage usage (approx): 1.5 gb (18.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 3GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-07-04 12:24
I can't reproduce any problem in the latest release. Regardless of the theme, closing the debugger always de-highlights the event it's highlighted for a breakpoint. Editing a project during a debug session is not supported so I'm not concerned about any issue being unable to edit events during debugging, the only problem would be is if it leaves the highlight behind, but I don't see that.

**Closed by AshleyScirra** 2019-07-04 12:24 UTC
Labels: can't reproduce
