### ISSUE TITLE
SetCanvasSize() during "beforelayoutchange" returns a '"BoundScrolling" of null'.

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4333] opened 2020-11-10 17:19 UTC
##  Problem description
Hi,

The `SetCanvasSize(width, height)` action called with the Addon SDK, during the event `"beforelayoutchange"`, returns a `"BoundScrolling" of null`.

It's an old issue that started on `r191`, after fixing this issue: https://github.com/Scirra/Construct-3-bugs/issues/3701.

I really hoped to not disturb the Construct Team with this issue, but any workaround I made led to another issue, so I was hoping to get this fixed instead.

## Addon code
![image](https://user-images.githubusercontent.com/31282960/98704008-1c8e3080-23b7-11eb-9220-37336571cc70.png)
![image](https://user-images.githubusercontent.com/31282960/98704079-30d22d80-23b7-11eb-8a11-2bccc087ee37.png)

## Project Event sheet
![image](https://user-images.githubusercontent.com/31282960/98707156-ab507c80-23ba-11eb-873c-60faf46b3513.png)

## Attached .c3p and addon

[SetCanvasSize.zip](https://github.com/Scirra/Construct-3-bugs/files/5518794/SetCanvasSize.zip)
It includes a simple project and addon you can work with, to replicate the issue.

## Steps to reproduce

1. Install the addon that's in the package.
2. Open the project that's in the package.
3. Hit preview.
4. Wait for 1 second.
5. Hit F12 and review the console logs.

## Observed result

![image](https://user-images.githubusercontent.com/31282960/98703850-f072af80-23b6-11eb-8b50-cc53a7d33e47.png)

## Expected result

I was hoping the `SetCanvasSize(width, height)` to not be hardcoded with the layout's `BoundScrolling` method, like before `r191`.

Which will make it flexible for the event `beforelayoutchange`. And it seems it's the only moment where we can resize the canvas without having conflicts with the other things in the layout, like the `Anchor` behavior.

## BoundScrolling()
![image](https://user-images.githubusercontent.com/31282960/98705060-44ca5f00-23b8-11eb-897f-6ae84cb8b0f0.png)

## More details

**First affected release:** 
**Release r191**, caused by fixing this issue: https://github.com/Scirra/Construct-3-bugs/issues/3701

Let me know if you still need more information.
Thank you.

**Comment by AshleyScirra** [comment] 2020-11-11 11:53
Architecturally, calling other addon's actions directly from another addon is a poor design. Conditions, actions and expressions are intended to be used in event sheets by the user. They are not meant to be an API that is callable by other addons. Instead you should just be calling real APIs. I think the `CallAction()` method is basically a mistake and I'm more inclined to remove it than fix problems with it.

Further, it's not clear why an addon should be doing this anyway. Shouldn't your addon be firing a trigger that the user can then use any actions they wish with, such as the system 'Set canvas size' action if they want, or something else, and possibly with other actions like console logging or testing and diagnostics? It's a more flexible design and avoids the previous architectural problem.

Further, calling in to actions from "beforelayoutchange" is highly problematic and probably cannot ever be fully supported. As mentioned actions, conditions and expressions are intended to be used from event sheets, where the engine guarantees there is always an active layout. In "beforelayoutchange", the engine is *in between* two layouts, so there is no active layout. So by doing this you are breaking a fundamental assumption of the event engine. There is no way we will be updating the entire event engine and all plugins and behaviors to work with no layout active - it's just not designed to work that way. We will not fix regressions in things that were never intended to be supported to begin with.

So currently I'm leaning towards closing as wontfix, and if further problems come up related to this, deprecating and removing `CallAction()`. However if you can explain a compelling reason why what you're doing is both important and absolutely has to be done this way, then I may reconsider.

**Comment by Chadori** [comment] 2020-11-11 20:45
Hi Ashley, thank you for informing me.

It looks like there is nothing wrong with the `Call Action` and `SetCanvas(width, height)`, you're right.
I think you still should support `CallAction()` since there is nothing wrong with it, just misusage on my part with the Addon SDK.

However, the issue is, us addon developers do not have any more events available to properly time and support these methods, after the changes.
We currently only have `beforelayoutchange` and `layoutchange` for the Addon SDK.

With your permission, could I propose the following event listeners, `beforelayoutstart`, `afterlayoutstart`, `beforeprojectstart` and `afterprojectstart`, to get supported in the Addon SDK?
I really don't want to disturb, and I would use the Scripting Interface if I could, but it doesn't seem possible from the Addon SDK.

These will help solve my addon issues, with the method call timing.

Thank you.

**Comment by AshleyScirra** [comment] 2020-11-12 12:22
`layoutchange` is effectively `afterlayoutchange`. The layout has finished changing by that event.

Calling system actions directly from addons is both using undocumented features, which we specifically state is not supported in the SDK documentation, and poor design. You really should find another way to do this. I asked for details but I still don't know what you're trying to achieve here, so my only advice is: don't do this. It's impossible to make reliable software if third-party developers write code that reaches in to internal details. We have to change internal details all the time, to fix bugs, optimise performance, and make any other changes. These changes will constantly break your addon if you depend on them. This is why we say it's not supported. It's exactly what happened here: we fixed a bug, and it broke your addon code depending on undocumented internal details of the engine. The only other alternative is that we stop making improvements to our engine. What are we supposed to do - not fix the bug? Obviously this is not something we can consider. Therefore closing as wontfix.

**Closed by AshleyScirra** 2020-11-12 12:22 UTC
Labels: sdk, wontfix

**Comment by Chadori** [comment] 2020-11-12 12:38
@AshleyScirra I'm just trying to **resize the canvas** and **rescale the layout**, it's the only way we can support middle end devices with games made in Construct 3. I'm not sure if you're aware, but [mobile games made with Construct 3 are very slow and stuttered](https://www.construct.net/en/forum/construct-3/general-discussion-7/game-performance-android-sucks-155097).

If I don't do this, none of my games run smoothly in middle-end devices and I already have others asking when it'll get fixed again. It's not efficient doing in events, it's convoluted since the CPU with Construct 3's webview is quite sensitive as well.
I reached from 30 fps to 60 fps (smooth) with this, while not breaking any built-in features, like the **Anchor** behavior.

I really hope for your kind consideration on this one.
Thank you.

**Comment by AshleyScirra** [comment] 2020-11-12 12:44
As best as I can tell, only a small number of Android devices are affected by driver problems. I'm still not clear what you're trying to do - why don't the built-in options suffice? If you're trying to do something like implement a new fullscreen mode from an addon, that's exactly the kind of hacking internal details that we can't support from the SDK. It should be handled by the engine, and feature suggestions are the best route to handle that - but I think there needs to be better evidence that the problem you're trying to solve is actually widespread before jumping to that conclusion.

**Comment by Chadori** [comment] 2020-11-12 13:08
Alright, thanks.
No worries, I think I can find other ways.
