### ISSUE TITLE
Video not playing on iOS 12

### ISSUE THREAD

**Issue by SparklingAir** [Scirra/Construct-3-bugs#2125] opened 2018-10-09 08:38 UTC
## Problem description

Construct 3 121
iPhone 6 iOS 12.1 + PhoneGap Build
or Xcode 10 with any simulator device with iOS 12 
- video not playing.

## C3 project:
[TEST_VIDEO.zip](https://github.com/Scirra/Construct-3-bugs/files/2459525/TEST_VIDEO.zip)

## Steps to reproduce

1. In C3 build project with option cordova or xcode project
2. Build PhoneGap and run on device with ios12 or run in Xcode in simulator with iOS 12

## Observed result
Video not playing

## Expected result

Video playing

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

error from Xcode:
2018-10-09 11:23:18.671660+0300 TEST_VIDEO[31509:1742273] ERROR: Error updating WebGL texture:  SecurityError: The operation is insecure.

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2018-10-09 09:59
Looked in to this a bunch before and it is incredibly difficult - the security of WKWebView throws hurdles in the way at every turn...

**Comment by AshleyScirra** [comment] 2018-10-09 13:00
To properly fix this I think we are going to have to go to great lengths to work around a whole stack of iOS bugs that block any other sensible workarounds. The only way I can think to get this to work is to bring back the HTTP server we used to use, and serve video files on a HTTP server within the app. However due to iOS throwing more blockers in the way, this isn't immediately going to work: it will at a minimum need

- `Access-Control-Allow-Origin: *` header with every response
- the correct MIME type for .mp4 video (`video/mp4`)

It should also be able to host on `localhost` on any available port (ideally using OS auto-assign port, which can vary).

Previously we used [cordova-httpd](https://github.com/floatinghotpot/cordova-httpd) which worked OK, but lacks the Access-Control-Allow-Origin header, and is now unmaintained (I [asked for this](https://github.com/floatinghotpot/cordova-httpd/issues/45) in 2016, and the entire repo hasn't changed since then AFAICT). So that will need forking and some light hacking.

@shortercode does most of our Cordova work so assigning to him for this first part of getting the necessary HTTP server plugin working as we need it. Once that's done I'll take over and integrate it in to the video plugin.

**Comment by AshleyScirra** [comment] 2018-10-09 13:04
FWIW here's the WebKit bug I filed when they broke out latest workaround: https://bugs.webkit.org/show_bug.cgi?id=186353

Unfortunately, and typically, they did nothing about it and shipped iOS 12 with it still broken.

**Comment by SparklingAir** [comment] 2018-10-09 13:09
all hope for you :)

**Comment by sangeeth786** [comment] 2018-11-19 12:01
I need a help on the same above, when i export my project for IOS devices in xcode, the project runs and the video plays but not displaying it
kindly help me if you have found an solution

**Comment by sangeeth786** [comment] 2018-11-19 12:08
did you get an solution for this

**Comment by AshleyScirra** [comment] 2018-11-19 12:35
No, this issue is still open. Issues are closed once they are resolved.

**Comment by sangeeth786** [comment] 2018-11-19 12:46
Ok Lets me know when the issue is resolved

**Comment by sangeeth786** [comment] 2018-11-19 12:48
My Game is ready to export, but because of this issue i am on hold..

**Comment by AshleyScirra** [comment] 2018-11-19 12:58
Click "Subscribe" on the right of the issue to get notifications when it is updated.

**Comment by sangeeth786** [comment] 2018-11-19 13:04
Thanks Done.
Waiting for your reply.

**Comment by shortercode** [comment] 2018-11-22 12:47
Okay I've forked the plugin, made the changes for the ContentType and AccessControlAllowOrigin headers and published to npm for builds. The ID is 'construct-mobile-server' and the current version is `1.0.0-beta.2`. 

Assigning back to @AshleyScirra for integration and testing.

**Comment by Teymur969** [comment] 2018-12-06 12:50
Turning off the webgl in the project settings solved the problem for me.

**Comment by sangeeth786** [comment] 2018-12-07 07:44
@Teymur969 
Thanks alot, it worked out but would it give any issue in my game.

**Comment by Teymur969** [comment] 2018-12-07 07:46
It shouldn't give. I think it can affect your HTML export. So don't forget to switch it on before you export it for HTML. iOS version should be fine.

**Comment by sangeeth786** [comment] 2018-12-07 07:55
@Teymur969
can i have one more help from you.

**Comment by AshleyScirra** [comment] 2018-12-07 13:45
We've finally found a way to get video playback working again in iOS 12+ apps. However due to various bugs and difficulties in iOS 11, we can't support video playback there. So video playback should work for iOS 12+ apps (in both runtimes) in the next release; if video playback is important to your app, make sure you set iOS 12 as the minimum version to avoid it being distributed to iOS 11 and older devices where video playback won't work. According to [Apple's stats](https://developer.apple.com/support/app-store/) 70% of all devices are already on iOS 12 in less than 3 months since its release, and this will keep increasing, so you should still be able to reach the vast majority of devices when targeting iOS 12+ only.

**Closed by AshleyScirra** 2018-12-07 13:45 UTC
Labels: difficult, external, iOS

**Comment by sangeeth786** [comment] 2018-12-07 14:17
@AshleyScirra 
there were bugs and difficulties in IOS 12 for Video playback not in IOS11, but as per @Teymur969 suggestion i disabled the Webgl and the video is working on IOS 12 device.
Thanks,
i had one more issue reported on github retaled to iphone XR & iphone XS MAX landscape problem that its showing black bars on the right side of the device, the link is below

https://github.com/Scirra/Construct-3-bugs/issues/2396

Kindly help me out to solve this bug on landscape mode in iPhone XR & iPhone XS MAX

**Comment by pixcubeanim** [comment] 2019-04-30 11:53
Is this fix also available for construct2? Because i have the same problem there - videos arent playing on ios 12+. And it seems there is no workaround so far. 

My older Tablet (ios 12.1) Plays the video, on my newer Ipad Air 2 (Ios 12.2) it doesnt play (also on other devices having ios 12.2)

Do you have some informations about this?

Thank you very much!
