### ISSUE TITLE
MobileIAP plugin weird behavior (or not?) on iOS...?

### ISSUE THREAD

**Issue by DaveedA13** [Scirra/Construct-3-bugs#3608] opened 2020-01-24 21:50 UTC
## Problem description

I can't still seem to make IAP to work...even when using a modified c3p file created by Construct 3 dev team, there is still some weird behaviors...

## Attach a .c3p

[Report Build VERSION 1.10.10 B15 MobIAP.zip](https://github.com/Scirra/Construct-3-bugs/files/4110726/Report.Build.VERSION.1.10.10.B15.MobIAP.zip)

## Steps to reproduce

1. Run the exported XCode project on a device (I did it via TestFlight app)
2. Look at the debug info upper-left.

## Observed result

1. The first time it's run, "SR_Success" triggers...
    ("Store Registration" condition, on upper-left debug information)
    The times after that too IF you don't buy the IAP.

2. You can buy the IAP with the "Supprime les publicités" text-button on lower-right, and it works well. The "Any purchase success" trigger as it should.

3. Since it's a "consumable" IAP in this demo, you can even re-buy it again just after the confirmation.

4. The **problem** occur when you close the app and restart it. Now, the "store registration" does **not** trigger on startup... ...but the "Any purchase success" still triggers...

Is it **normal** for "store registration" to not trigger anymore?
(Am I understanding the way the plugin work wrong?)

Do you have the same behavior on your side?

...and now that I bought the IAP once, I can't buy it anymore (except in the first "session" within the game)...  The "buy button" does absolutely nothing too after this, and it's a logical thing since the manual says "You should wait for this trigger before attempting any purchases" for "On Registration Success" manual entry.

## Expected result

Should not the "store registration" condition success trigger **every time** I open my game, even if I bought the IAP?  I tested with a "Non-consumable" IAP too. (The type of IAP I want in my game in fact, for a "no-ad" option.)

And with a "Non-consumable" I still only got the "Any Purchase Success" trigger, on opening (exactly like when we buy the IAP), even if I had only one product available, and that it was marked as "available for purchase". So I'm really confused here...

Sorry if it's me and I don't know in wich event to check if a specific IAP purchase was made...

## More details
Tested on iOS devices only, since it's a IAP problem.  Tested on an iPad 2017 and an iPhone 7, both with iOS 13.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.39.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.39.0 (like Chrome/75.0.3770.80)
C3 release: r183.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 4.8 gb
Storage usage (approx): 1.1 gb (23.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DaveedA13** [comment] 2020-01-29 15:05
Just to add a little precision to my post:

For me the fact that "On Registration Success" does not fire if an IAP has already been done in the app really seems like a bug since the **C3 manual** says:

_"When making IAP events, the first thing you need to do is to complete the plugin's registration stage. **You won't be able to make any purchases OR check if a user owns a product until this is done**.
To finish registration you must call the Complete Product Registration action. If registration succeeds then On Registration Success triggers. **After this** you are free to **check the STATE of products AND make purchases**."_

**Comment by DaveedA13** [comment] 2020-01-30 14:09
@AshleyScirra 

Can I ask if there is a specific reason why my post have no answer after 5 or 6 days...? It's not "assigned" either, I see a lot of posts here that are answered after a few hours or a day or two.

Thanks in advance.  This IAP problem is really preventing me from creating games with your program, and I would really like to use it regularly in the future.

**Comment by AshleyScirra** [comment] 2020-01-30 16:53
We're a small team and these kinds of reports are very complicated and time consuming to investigate. Please be patient and refer to the bug report guidelines:

> **Why haven't you responded to my bug report yet?**
> We do look at every report, but developer and release schedules mean we may not get round to it immediately. Please allow a few weeks for it to be investigated. If you are waiting, you can improve the chance it is resolved when a developer does get round to it by carefully reviewing these guidelines and providing as much useful information about the problem as possible. If you are missing anything, you may end up waiting a few weeks for a reply simply asking for the missing information, and then you're back to waiting again.

**Comment by DaveedA13** [comment] 2020-01-31 15:51
Thanks for the reply, I understand the delay (even I'm really eager to know if it's just me or not) I was just asking myself if the post was ignored because there was no assignment either...

Thanks in advance for the upcoming check of this one, I'll be patient.

**Comment by AshleyScirra** [comment] 2020-02-14 14:37
I finally managed to reproduce it. It appears to be a problem with the underlying cordova-plugin-purchase library which in this circumstance never fires the ready event. It looks like you can carry on making successful calls, so it's only that the event is omitted and everything else otherwise appears to work (although I suppose you don't know how long to wait for before using the store).

Anyway I filed an issue with the plugin developer here with as much detail as I could find from my investigation: https://github.com/j3k0/cordova-plugin-purchase/issues/995

We'll follow up there, so closing this issue.

**Closed by AshleyScirra** 2020-02-14 14:37 UTC
Labels: external, iOS
