### ISSUE TITLE
Crash after random usage of event sheet on Mac Os (Wacom intuos)

### ISSUE THREAD

**Issue by Mak14** [Scirra/Construct-3-bugs#4460] opened 2021-01-09 08:50 UTC
Update 2:

After adjusting double click timing in the wacom settings ( set to lowest, but not off) , this issue is not happening at the moment. Still testing.

UPDATE: 

I noticed that this is happening every time i click the action "Create Object" WIth the wacom pen. 
The pop up menu duplicates itself and has two objects to select. 
Program is crashing after i'm closing this window.

<img width="200" alt="c3wacomBug" src="https://user-images.githubusercontent.com/48147508/104087591-f3343880-5271-11eb-84d9-4ec623185537.png">

____Original Text___

Hi, sometimes the C3 is crashing at random moments- most of the time when i'm using event sheet- editing actions and events, choosing objects to create etc. 
I am using wacom pen, so it happens only with it. I don't know is this a problem of the pen driver or so. 
I'm thinking this might be because of the fast clicks of the pen or so. 

Sometimes, Construct doubles action windows menu:
System-> create object- > 
and here i see two options to select object, there are two buttons for object selection on the same pop up window- one at the top and the other is below.

Here is the report i got from the recent crash:

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Function.d.g (https://editor.construct.net/r230/main.js:219:490) at d.f.I.JMd.M (https://editor.construct.net/r230/projectResources.js:2368:270) at D (https://editor.construct.net/r230/projectResources.js:2376:133) at B (https://editor.construct.net/r230/projectResources.js:2375:474) at F (https://editor.construct.net/r230/projectResources.js:2375:375) at https://editor.construct.net/r230/projectResources.js:2375:432
Stack: TypeError: unexpected type at Function.d.g (https://editor.construct.net/r230/main.js:219:490) at d.f.I.JMd.M (https://editor.construct.net/r230/projectResources.js:2368:270) at D (https://editor.construct.net/r230/projectResources.js:2376:133) at B (https://editor.construct.net/r230/projectResources.js:2375:474) at F (https://editor.construct.net/r230/projectResources.js:2375:375) at https://editor.construct.net/r230/projectResources.js:2375:432
Construct 3 version: r230
URL: https://editor.construct.net/r230/
Date: Sat Jan 09 2021 11:37:13 GMT+0300 (Moscow Standard Time)
Uptime: 2114 s

Platform information
Browser: NW.js
Browser version: 0.50.2
Browser engine: Chromium
Browser architecture: (unknown)
Context: nwjs
Operating system: Mac OS X
Operating system version: 10.15_7
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (@62f83a7521ae1f32e563795732dff0c9da1b660d) NWjs/0.50.2 (like Chrome/87.0.4280.88)
C3 release: r230 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 5300 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw
## Steps to reproduce

1. While on the event sheet try to edit events with pen tablet
2.
3.

## Observed result
Program is crashed

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2021-01-09 11:51
Please note if you cannot find reliable specific steps to follow to reproduce the problem, it may be impossible to help.

**Comment by Makarone14** [comment] 2021-01-09 14:17
Hi, Ashley, sorry for not describing the issue step by step. 
I didn't know that this bug was constant.  So here is few steps that might appear the issue.

1. Open wacom tablet settings
2. Set Tip double click distance to 0 ( off)
3. Create system action Create Object
4. Re-open created action

In my case i see doubled button 'create object'
If i press ESC or close the window program crashes.

After some tests, and with setting tip double clock distance to minimum but not 0, it doesn't happens now.
But i haven't tried this for a long time so i can't guarantee it is the fix.

**Comment by Mak14** [comment] 2021-01-09 14:21
Hi, Ashley, sorry for not describing the issue step by step.
I didn't know that this bug was constant. So here is few steps that might appear the issue.

Open wacom tablet settings
Set Tip double click distance to 0 ( off)
Create system action Create Object
Re-open created action
In my case i see doubled button 'create object'
If i press ESC or close the window program crashes.

After some tests, and with setting tip double clock distance to minimum but not 0, it doesn't happens now.
But i haven't tried this for a long time so i can't guarantee it is the fix.

**Comment by Mak14** [comment] 2021-01-10 09:43
Update

After playing with wacom tip distance options, and also the double click speed in system preferences this issue is still present.

**Comment by DiegoScirra** [comment] 2021-01-11 12:37
Can't reproduce this on Windows on either desktop or web version. I have to assume it is an OSX only issue, but I don't have a suitable device to test it out.

**Comment by DiegoScirra** [comment] 2021-02-08 16:09
Fixed in the next beta. The issue was unique to OSX (possibly iOS) in conjunction with using a pen pointer device.

**Closed by DiegoScirra** 2021-02-08 16:09 UTC
Labels: macOS

**Comment by Mak14** [comment] 2021-02-08 16:13
Thanks Diego! Yep, that's happen only with tablet pen. 
I'm so happy that you have fixed it! Cheers!
