### ISSUE TITLE
Apk google play black screen problem (r132) C3 runtime.

### ISSUE THREAD

**Issue by ibiz3091** [Scirra/Construct-3-bugs#2498] opened 2019-01-08 17:52 UTC
## Problem description
Problem after compiling apk to (r132) black screen. The problem disappears in when you compile the apk in (r131).

## Steps to reproduce

1.
2.
3.

## Affected browsers/platforms

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2019-01-08 17:59
Duplicate of #2492 (see also #2493)

**Closed by AshleyScirra** 2019-01-08 17:59 UTC
Labels: duplicate
