### ISSUE TITLE
[r31] Wrong properties when object without instance selected

### ISSUE THREAD

**Issue by blackhornet2010** [Scirra/Construct-3-bugs#380] opened 2017-05-28 02:03 UTC
## Problem description

If you clone an object from the project menu, and then select it, the properties remain for the previous object. This can lead to editing the wrong object.

## Attach a .c3p

N/A

## Steps to reproduce

1. Create a sprite.
2. Clone the sprite from the project tab.

## Observed result

The Properties tab doesn't update for the cloned sprite.

## Expected result

Minimal properties tab, similar to C2.

## Affected browsers

N/A

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

N/A

</details>

**Comment by AshleyScirra** [comment] 2017-05-29 13:19
Think this is a duplicate of #322 - at the moment you can't select objects in the project bar with no instances.

**Closed by AshleyScirra** 2017-05-29 13:19 UTC
