### ISSUE TITLE
Displays Oops! Something went wrong error

### ISSUE THREAD

**Issue by vundurty** [Scirra/Construct-3-bugs#1973] opened 2018-09-01 06:50 UTC
## Problem description
Displays Oops! Something went wrong error when I try to open a project

## Attach a .c3p

Just opening the project produces the error

## Steps to reproduce

1.Just opening the project produces the error
2.
3.

## Observed result
Provided in the second question

Provided in the second question

## Expected result

Open the project

## Affected browsers

* Chrome: yes
* Firefox: unknown
* Edge: unknown
* Safari:unknown

## System details
Provided in the second question

<details><summary>View details</summary>
Error report information
Type: unhandled exception
File: https://editor.construct.net/r111/components/editors/layoutView/layoutView.js, line 1, col 7687
Message: Uncaught NotFoundError: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
Stack: Error: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node. at window.ǃrU.ǃck (https://editor.construct.net/r111/components/editors/layoutView/layoutView.js:1:7687) at window.ǃwg.ǃCc (https://editor.construct.net/r111/components/editors/layoutView/layoutView.js:1:46801) at window.ǃwg.ǃmQ (https://editor.construct.net/r111/components/editors/layoutView/layoutView.js:1:45793) at window.ǃrU.ǃVy (https://editor.construct.net/r111/components/editors/layoutView/layoutView.js:1:26498) at window.ǃrU.ǃbX (https://editor.construct.net/r111/components/editors/layoutView/layoutView.js:1:26477) at Array.ǃX.ǃI.ǃS.ǃI.ǃO.ǃU (https://editor.construct.net/r111/components/editors/layoutView/layoutView.js:1:3165) at ǃI.Event.ǃrbq.ǃrbD (https://editor.construct.net/r111/main.js:2:200437) at ǃI.ǃP.ǃW.ǃrJG.dispatchEvent (https://editor.construct.net/r111/main.js:2:198568) at ǃI.ǃP.ǃW.ǃrJG.ǃrvw (https://editor.construct.net/r111/main.js:2:337365) at ǃI.ǃP.ǃW.ǃrJK.ǃrmg (https://editor.construct.net/r111/main.js:2:346388)
Construct 3 version: r111
URL: https://editor.construct.net/index.html
Date: Sat Sep 01 2018 12:06:54 GMT+0530 (India Standard Time)
Uptime: 801.1 s

Platform information
Browser: Chrome
Browser version: 68.0.3440.106
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
C3 release: r111 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D9Ex vs_3_0 ps_3_0)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_color_buffer_half_float, EXT_frag_depth, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_color_buffer_float, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

</details>

**Comment by shortercode** [comment] 2018-09-03 10:31
Assigning @AshleyScirra as the crash occurred in his code.

**Comment by AshleyScirra** [comment] 2018-09-03 10:54
Can't reproduce here, no project was provided, and the crash report doesn't include anything much useful unfortunately. Closing, please re-file if you can provide more details as per the bug report guidelines.

**Closed by AshleyScirra** 2018-09-03 10:54 UTC
Labels: can't reproduce
