### ISSUE TITLE
Layers are set to local but visibility is treated as "global"

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#4988] opened 2021-07-27 03:24 UTC
When I change layout and come back, it feels like some features of the layout are remembered as if it were global — despite me having set everything to local. 

My expectation from working with local and global variables is that other aspects of the editor would work in a similar way, example: if there's a local variable with an initial value of 0, but you set it to 5, when you return to that scope later on it should be 0 and not 5. 

This is how I presumed non-global layers were suppose to work, when I leave and return to a layout, or restart it, I expect that local features will return to their initial state.

## Illustration of bug

![image](https://user-images.githubusercontent.com/5744908/127083077-2c7d2a9e-585b-4a2b-b895-345cb82d6e8a.png)

In this image you can see I have "initial visibility" set to off. But if I've turned this layer to be visible at some point and then return to this layout, it remembers that I turned it on in the past as if it were some Global feature, but as you can see I have the "global" setting to "No". 

## Capx

[local_layers_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/6882417/local_layers_bug.zip)

1. Click the "restart" button to restart the layout

## Observed result

Notice a layer is now visible despite having restarted the layout.

## Expected result

One would expect that a non-global layer would return to it's initial state of being invisible when the scope has changed, just as local variables do.

**Comment by AshleyScirra** [comment] 2021-08-02 11:50
This is basically a duplicate of #4698. It's currently by design and changing it is difficult for backwards compatibility reasons, so I doubt we will change it at this point.

**Closed by AshleyScirra** 2021-08-02 11:50 UTC
Labels: duplicate

**Comment by alastajj** [comment] 2021-08-03 04:05
Fair enough. I need to put together a list of features that can't be done due to backwards compatibility, incase Construct 4 is ever a thing! Also have animation speed being capped by framerate on the list.

**Comment by AshleyScirra** [comment] 2021-08-03 12:32
We have no plans whatsoever for Construct 4, but even then, backwards compatibility would still be a concern, for the same reason C2 project compatibility is important for C3.
