### ISSUE TITLE
[r286] Construct 3 lost its ability to open projects with an object that had its property id changed in a newer release

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#5618] opened 2022-04-10 16:58 UTC
## Problem description

Construct 3 lost its ability to open projects with an object that had its property id changed in a newer release, for example the built-in Facebook object.

## Attach a .c3p

This is a project created in `r250` that was added with the built-in Facebook object.
[Facebook object.zip](https://github.com/Scirra/Construct-3-bugs/files/8459483/Facebook.object.zip)

## Steps to reproduce
1. Open the project in Construct 3 `r286` or later.
2. The project will fail to open, and output an error in the console.

## Observed result

![image](https://user-images.githubusercontent.com/31282960/162630415-dc68e5ae-811a-4d5c-8264-4f8debfc6aa1.png)

![image](https://user-images.githubusercontent.com/31282960/162630409-8de98f97-eaa8-4498-b27b-ed4ad8d60915.png)

## Expected result

For the Construct 3 editor to retain its ability to adapt to property id changes of objects.

## Steps to recover
1. Open the project in Construct 3 `r285.3` or earlier.
2. The Construct 3 editor will successfully open the project.

## More details

**Last unaffected release:** `r285.3`

**First affected release:** `r286`
**Latest affected release:** `r289`

**Comment by AshleyScirra** [comment] 2022-04-11 14:17
@DiegoScirra - this looks like a regression caused by the templates feature. Previously loading a project referencing a missing plugin property ID would just ignore it. Now it throws an exception which prevents loading the project. This must be allowed to allow backwards compatibility with old projects.

**Comment by DiegoScirra** [comment] 2022-04-11 15:24
Will be fixed in the next beta.

**Closed by DiegoScirra** 2022-04-11 15:24 UTC
