### ISSUE TITLE
Editor touch input not working on desktop-class devices (requires migration to pointer events)

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#3031] opened 2019-06-10 23:19 UTC
## Problem description

To make it clear this only affects Windows 10 touch enabled devices, an all browsers. Not iPad or Android.

There is no point listing all the bugs related to touch at this point as I would spam the bug tracker with tons of bugs that probably are related. I will list some here that I immidiately noticed.

* can't trigger context menu's with tap and hold in layout
* cant select drawing tools in animation editor
* can't draw with touch (scrolls at same time or nothing happens)
* cant tap insert button in create new object dialogue
* latest chrome stable shifts whole page when inserting sprite.
.....
and list goes on.... I think a round of QA testing using touch in C3 would be in order as there are just way too many bugs for me to list here.

Some might be browser updates breaking stuff, but C3 used to be a quite pleasant experience using touch.

## Attach a .c3p

n/a

## Steps to reproduce

1. Try latest stable of construct 3 in various browsers using touch as main input. Laptop, or tablet)

## Observed result

hardly anything works

## Expected result

Things should work.

**Comment by AshleyScirra** [comment] 2019-06-11 12:06
I can't reproduce anything you mentioned at all on Chrome for Android or Safari on an iPad Pro. Everything seems to be working normally in the latest stable release. Please do not skimp on bug reports, all the information is always important otherwise we cannot figure out what you are doing or what the problem might be. Please provide details about which specific devices and browsers you've tested and whether the issue reproduces in the latest beta release.

**Comment by tunepunk** [comment] 2019-06-11 12:09
No i'm talking about laptop with touch or windows tablet (Surface pro like win10 tablet), as mentioned in details. I'm having problems in all browsers. I can record some screen cap at some point.

**Comment by tunepunk** [comment] 2019-06-11 14:43
Hmmmm... one clue might be that some browsers disable touch events by default in favour of pointer events now, and has to be manually enabled in config/flags. I'm going to investigate further when I get back home on the Surface. Is there any plan to move on to pointer events API instead of old touch API?

Could this be the thing breaking touch in C3?

**Comment by tunepunk** [comment] 2019-06-11 15:11
Some more links that might help solve the issue:

https://www.chromestatus.com/feature/4764225348042752
Google recommends using Pointer Events instead. Touch Disabled by default on desktop version of Chrome since 70.

https://stackoverflow.com/questions/53231736/touch-handling-completely-broken-on-chrome-version-70

**Comment by AshleyScirra** [comment] 2019-06-11 15:36
If we do have to move from touch events to pointer events, I already tried a while back, and it's a huge job that would require refactoring much of the editor. The main problem is it handles scrolling differently, so we have to adjust how every single pane in the editor reacts to pointer input. Given that we're a tiny team, we're already extremely busy, this would be a lot of work, and it's not clear that we have many users who rely on touch input on desktop-class devices, I'm not sure we'll be able to do anything about this in the short term.

**Comment by tunepunk** [comment] 2019-06-11 15:44
It's understandable if it's a huge job. But might be worth to keep it in mind, as Touch Events might become deprecated sooner or later. As both desktop and mobile are moving towards pointer events, to support both, mouse, touch and Pen (which I also filed a few bugs about previously)

I'm not sure if game exports are also using touch events, which might cause problems, in the future if you're targeting mobile / tablet market.

**Comment by AshleyScirra** [comment] 2019-06-11 15:52
I want to, but it turns out to be one of these really complicated things that rapidly turns in to a giant headache. I just realised an extra thing that as long as Safari 12 is around, which has no support for pointer events, we have to keep touch events support around as well. Having two parallel systems doing the same thing in the codebase, and both needing separate debugging and maintenance, and possibly conflicting with each other in same cases, makes it more than double the complexity.

Given all of this I don't think it's sensible to consider this until Safari 13+ is widespread and we can fully drop support for Safari 12 in the editor, and then we can move everything over to pointer events only in one go.

**Comment by tunepunk** [comment] 2019-06-11 15:58
Ok - I'm not holding my breath then. But hopefully browser vendors will keep flags available to turn it back on for a while on desktop versions.

I'm curious if a game exported with NW.js would have similar problems with touch, on Touch enabled desktop devices?

Thanks for looking in to it. :)

**Comment by AshleyScirra** [comment] 2019-06-11 16:04
The runtime is a lot simpler and we already use pointer events there where supported. This only applies to the editor.

**Comment by AshleyScirra** [comment] 2020-04-06 16:32
Note to self: related to this is the increasingly awkward support for input events on iPad. The recent 13.4 update adds support for having a bluetooth mouse, which fires mouse events. Previously we blocked all mouse events on iOS because it fires compatibility mouse events after touch events, with no way to detect compatibility mouse events, and it caused double-press bugs. We had to allow mouse events on iOS again to allow a bluetooth mouse to work, but now compatibility mouse events come back for touch input. Switching everything to pointer events should avoid these complications, since it's just one API for all input types and doesn't fire compatibility events. So we should probably bite the bullet and do this overhaul some time soonish.

Meanwhile [Apple's own stats](https://developer.apple.com/support/app-store/) show only around 57% of all iPads are on v13+ (although it's more like 80% for newer devices). There's lots of old devices out there. Dropping support for iOS 12 over this might be painful...

**Comment by AshleyScirra** [comment] 2020-12-10 15:31
Turning this issue over to @DiegoScirra who is currently working on Pointer Events support in the editor. Looking at my previous comment, using a bluetooth mouse on iOS is another case to test.

**Comment by DiegoScirra** [comment] 2021-02-03 16:55
The complete migration to pointer events will be available in the next beta release.

**Comment by AshleyScirra** [comment] 2021-02-25 13:19
@DiegoScirra has done some great work migrating the whole editor to Pointer Events, which allows better customisation of the interpretation of both touch and pen input. He's also fixed a number of things along the way and so overall things should be working a lot better now in the latest beta releases.

Given the age of this issue and the amount of work done, we're now going to close it. There may be some remaining issues: if there are still any problems in the latest beta release, please file new issues for them, and we will deal with them case-by-case.

**Closed by AshleyScirra** 2021-02-25 13:19 UTC
