### ISSUE TITLE
C3 shuts down after picking external software on Mac  Nwjs build

### ISSUE THREAD

**Issue by Mak14** [Scirra/Construct-3-bugs#4403] opened 2020-12-08 14:12 UTC
## Problem description
When i'm clicking "choose a file" to define external editor, program is crashing with this error: 
<spoiler>
Error report information
Type: unhandled rejection
Reason: Error: require(...).UHd is not a function @ TypeError: require(...).UHd is not a function at Object.d.Si.jzc (https://editor.construct.net/r228/main.js:527:42) at Function.I0c (https://editor.construct.net/r228/main.js:646:39) at d.f.I.hMd.Qqd (https://editor.construct.net/r228/projectResources.js:1807:419) at HTMLButtonElement.k.onclick (https://editor.construct.net/r228/projectResources.js:1805:388)
Stack: TypeError: require(...).UHd is not a function at Object.d.Si.jzc (https://editor.construct.net/r228/main.js:527:42) at Function.I0c (https://editor.construct.net/r228/main.js:646:39) at d.f.I.hMd.Qqd (https://editor.construct.net/r228/projectResources.js:1807:419) at HTMLButtonElement.k.onclick (https://editor.construct.net/r228/projectResources.js:1805:388)
Construct 3 version: r228
URL: https://editor.construct.net/r228/
Date: Tue Dec 08 2020 17:06:35 GMT+0300 (Moscow Standard Time)
Uptime: 16.7 s

Platform information
Browser: NW.js
Browser version: 0.49.2
Browser engine: Chromium
Browser architecture: (unknown)
Context: nwjs
Operating system: Mac OS X
Operating system version: 10.15_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (@62f83a7521ae1f32e563795732dff0c9da1b660d) NWjs/0.49.2 (like Chrome/86.0.4240.111)
C3 release: r228 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 5300 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

## Steps to reproduce

1. Open image editor
2. Pick external software

## Observed result

Program is crashing with error.

## Expected result
Ability to pick external image editor

## More details

I'm also unable to set checkbox " use this as default editor"

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment] 2020-12-09 13:01
Can't reproduce this one, maybe it is an issue with OS X Catalina, but I can't verify that. In the Mac that I have for testing everything seems to work, but it is running High Sierra.

**Comment by DiegoScirra** [comment] 2020-12-09 13:20
This is a production build bug only, caused by minification, will be fixed in the next beta.

**Closed** 2020-12-09 13:26 UTC
