### ISSUE TITLE
Fullscreen mode off incorrect in c2runtime but ok in c3runtime

### ISSUE THREAD

**Issue by valerypopoff** [Scirra/Construct-3-bugs#2086] opened 2018-09-28 15:44 UTC
## Problem description

With fullscreen mode off the game shows up wrong (at least in preview mode):
— The sprite that's larger than both layout size and viewport size shows up whole.
— If the layer's parallax is set to (0%, 0%) it shows up in the middle of the screen while the other layers with parallax (100%, 100%) show up in the left top corner.

Both cases work fine in c3runtime.

## Attach a .c3p
[New project.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2428791/New.project.c3p.zip)

## Steps to reproduce
1. Click Preview

## Observed result
The whole yellow sprite is shown though both layout size and viewport size are only 500x350px

## Expected result
The yellow sprite is cut to 500x350px

## Steps to reproduce
1. Go back to the editor, set bg layer's parallax to (0%, 0%)
2. Click Preview

## Observed result
The yellow sprite is shown in the middle of the screen while the player sprite is shown in the left top corner

## Expected result
The yellow sprite is shown in left top corner

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 361 mb (2.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon HD 6770M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by valerypopoff** [comment] 2018-10-02 07:54
Yep, it does reproduce on my other Mac. Here's the screencast:
[Untitled.zip](https://github.com/Scirra/Construct-3-bugs/files/2436947/Untitled.zip)
The "System details" above are from this Mac

**Comment by AshleyScirra** [comment] 2018-10-02 09:20
Ah, you're using browser tab preview mode instead of popup, that was probably the missing repro step!

**Comment by AshleyScirra** [comment] 2018-10-05 12:10
I still can't reproduce this. Testing on Windows 10 x64 with Chrome 69 and the "browser tab" preview mode, it always looks correct, regardless of C2/C3 runtime setting, and regardless of the layer parallax.

Given you state it works on some systems but not others, I think the best theory is it's some kind of graphics driver bug, so closing on the assumption it's that. Let me know if you can find a way to consistently reproduce it across all systems.

**Closed by AshleyScirra** 2018-10-05 12:10 UTC
Labels: can't reproduce
