### ISSUE TITLE
New functions don't work if placed in groups

### ISSUE THREAD

**Issue by Boulerzzz** [Scirra/Construct-3-bugs#2805] opened 2019-04-03 10:13 UTC
## Problem description

The new functions don't work if placed within a group.

## Attach a .c3p

[test new functions 2.zip](https://github.com/Scirra/Construct-3-bugs/files/3038275/test.new.functions.2.zip)

## Steps to reproduce

1. Disable the group.
2. Open the project and the function works like excpected.
3. Disable event number 1 and event number 2.
4. Enable the group and try again. The function does not work

## Observed result

The game freezes.

## Expected result

The function should be called and change the text.

## More details

Only tried on chrome.

First started happening in r143

**Comment by shortercode** [comment] 2019-04-03 11:02
@Boulerzzz when filing bugs can you please try to stick to the template. While the information may not seem useful it's included on the template for a reason.

Going to assign this bug to @AshleyScirra to review, and see if there is enough information included.

**Comment by AshleyScirra** [comment] 2019-04-03 12:30
Duplicate of #2792. Will leave open to try to avoid more duplicates.

**Closed** 2019-04-08 12:42 UTC
