### ISSUE TITLE
Families put into subfolders are broken until project is reopened

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#3526] opened 2019-12-04 20:15 UTC
## Problem description

After moving all of my families into subfolders, the game was completely broken. I don't know the full extent, but families that had behaviors stopped the behaviors from working entirely. The only error I could get was this from the console
![image](https://user-images.githubusercontent.com/36490901/70173220-069cc980-1698-11ea-89ab-9cc1e845b78a.png)

After saving the project to a separate file, closing, and reopening it, everything worked fine.

## Attach a .c3p

Due to the nature of this issue (requiring a project restart to fix) a .c3p won't help.

## Steps to reproduce

1. Add an object to a family and give the family, say, a platform or solid behavior
2. Put the family in a subfolder
3. Preview the layout

## Observed result

Family is broken / platform doesn't work & solids aren't registered

## More details

**Affected browsers/platforms:** 
Chrome

r178

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 78.0.3904.108
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
C3 release: r178 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 618 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-12-05 13:01
I followed the steps to reproduce and it worked fine. The reason we say a .c3p project is mandatory is because in general it is impossible to investigate reports without one. It *always* helps to provide a .c3p, even if you have to follow a few steps (ideally as few as possible), so long as it reliably reproduces the problem. Can you provide this?

**Comment by cb130felix** [comment] 2019-12-07 21:24
@AshleyScirra just tested here with the project I uploaded in this issue report: https://github.com/Scirra/Construct-3-bugs/issues/3509#issuecomment-562581350

After puting the families in folders, saving the project, closing it and opening again the game isn't broken anymore.

**Comment by AshleyScirra** [comment] 2019-12-09 11:32
I believe issue #3509 is unrelated. It should not be possible for that issue to cause the JavaScript error mentioned in this report ("Cannot read property 'trim' of undefined"). Therefore I believe this issue is a different case. However we cannot investigate it without a way to reproduce it.

**Comment by AshleyScirra** [comment] 2019-12-12 16:41
I'm afraid this report is not actionable so closing. If you can provide a way to investigate it we can follow up with that.

**Closed by AshleyScirra** 2019-12-12 16:41 UTC
Labels: can't reproduce
