### ISSUE TITLE
Changing the effect parameter with events doesn't work

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#1323] opened 2018-02-25 16:36 UTC
## Problem description

Something here doesn't work correctly, or im just an idiot.
I'm trying to change the object Tint  effect parameter by pressing a key (1-4) but it looks like the only 1 is working (red).

## Attach a .c3p

[New project (8).zip](https://github.com/Scirra/Construct-3-bugs/files/1756456/New.project.8.zip)

## Steps to reproduce

1. Create object
2. Add tint effect
3. Change the effect parameter with events (only 1 should work)

## Observed result

Doesn't show the right color

## Expected result

Show the right color

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2018-02-26 12:32
Duplicate of #573, #659, #1103, #1117. Now also covered in the manual: https://www.construct.net/make-games/manuals/construct-3/tips-and-guides/importing-c2-projects

**Closed by AshleyScirra** 2018-02-26 12:32 UTC
Labels: duplicate
