### ISSUE TITLE
Start page changes size while using

### ISSUE THREAD

**Issue by shortercode** [Scirra/Construct-3-bugs#551] opened 2017-06-23 12:34 UTC
## Problem description

I've noticed that while using the dark theme the width of the start page drastically changes depending whats in focus. This can be jarring and unpleasant.

## Attach a .c3p

N/A

## Steps to reproduce

1. Open editor.construct.net with dark theme and close the "in beta" dialog
2. Move mouse over kiwi story
3. Open main menu
4. Cancel main menu by clicking off it
5. Repeat 2 - 5 to see it switching size

## Observed result

Note that the browser window was not resized between these 2 screenshots.
![screenshot 2017-06-23 13 23 44](https://user-images.githubusercontent.com/9051865/27482099-edb8a600-5817-11e7-97c4-c570baf5fadd.png)

![screenshot 2017-06-23 13 23 47](https://user-images.githubusercontent.com/9051865/27482101-efabc74e-5817-11e7-87c7-b399c7ce9215.png)

## Expected result

To be like screenshot 2 unless I make the window smaller.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 59.0.3071.109
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.109 Safari/537.36
C3 release: r40

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 90 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Animmaniac** [comment] 2017-06-23 12:57
I can't reproduce this on my machine. What resolution is your screen or browser window?

**Comment by shortercode** [comment] 2017-06-23 13:02
1080p can come try it on my machine if you like

**Comment by Animmaniac** [comment] 2017-07-06 16:59
@shortercode I just reverted some changes in the last release. Does the size flicking still happens?

**Comment by vtrixdev** [comment] 2017-07-20 13:06
I had the same issue on 1080p,  is fixed in r45

**Closed** 2017-11-30 22:04 UTC
Labels: theme
