### ISSUE TITLE
Layout view gets messed up when using Shadow Caster object

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#609] opened 2017-07-12 12:25 UTC
## Problem description

Hi. It's kind of a weird error, but i was playing around with shadow caster and light objects. Everything worked fine (except when i run the game but that might be my own shortcoming ;)) until i tried to add the "Lighten" effect to the lamp. The whole layout kinda got moved away from sight and zooming in and out seems to give additional weird results... 

## Attach a .c3p

A .c3p renamed as a .zip file is attached.

[errorwithshadowcast.zip](https://github.com/Scirra/Construct-3-bugs/files/1141935/errorwithshadowcast.zip)

## Steps to reproduce

Here's what i did:
1. Add a sprite and apply the shadow caster behaviour
2. Add a shadow light
3. I added a 8 Direction Movement behaviour to the light because i wanted to see the shadow moving around ;)
4. Add the "Lighten" Effect to the shadow light
5. Try zooming in and out

## Observed result

The Layout view zoom doesn't work properly anymore. It seems like the window area of the layout doesn't stay with the actual work area. Please see the c3p file for the result as it's kinda hard to describe...

## Expected result

Normal Zoom and Move behaviour

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r44

Local storage
Storage quota (approx): 131 gb
Storage usage (approx): 24 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M395X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2017-07-19 13:47
Can't reproduce on Windows, might be another Mac-specific rendering issue similar to #413 and #294.

**Comment by joelmayer87** [comment] 2017-07-19 16:03
Yeah i just tried it myself and i can't reproduce it anymore either, weird. But then it might have been some other issue :) Thanks for checking it out though, in case it pops up again i'll make sure to make a screenshot or something. You can close the bug in that case ;)

**Comment by joelmayer87** [comment] 2017-07-19 16:04
PS: Yes! It's exactly the same issue as with #413 . Is Kiwi Story using any Shadowcaster elements? Really weird, i'll keep an eye on it if it happens again... ;)

**Comment by AshleyScirra** [comment] 2017-07-20 13:38
Do you have access to a Windows/Linux/Chrome OS/Android system to check it there? If it is OK everywhere else but only occurs on the Mac, it is very likely a similar rendering issue (so hopefully I can just transfer that fix to wherever the shadow caster rendering path needs it).

**Comment by joelmayer87** [comment] 2017-07-21 12:12
Hi Ashley

I work mainly on Macs but i got a PC at home where i worked in C3 from time to time though very little. I'll try my file out there again but unfortunately it's kind of a weird bug that only happens very infrequently and unpredictable and therefore quite difficult to reproduce on purpose. But i'll make sure to keep an eye out for it and should it happen again i'll post a screenshot.

**Comment by AshleyScirra** [comment] 2017-07-21 12:19
I tried on a mid-2015 MacBook Pro and it seems to work fine. It's currently running the High Sierra beta (10.13), not sure if that makes a difference. It sounds a lot like a driver bug so it might depend on the kind of Mac model and GPU hardware it has. Not sure there's a lot we can do about this anyway, especially if it's intermittent - if you could find a more reliable way to reproduce the problem that would help a lot.

**Comment by AshleyScirra** [comment] 2017-07-31 14:52
Closing as can't reproduce and no further details available.

**Closed by AshleyScirra** 2017-07-31 14:52 UTC
Labels: can't reproduce
