### ISSUE TITLE
Pathfinding fails to find path in a certain condition

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#6119] opened 2022-09-18 22:17 UTC
## Problem description

If there's empty space between the clicked point and moving area pathfinding will fail to find a path.

## Attach a .c3p
[pathFindingBug.zip](https://github.com/Scirra/Construct-3-bugs/files/9595338/pathFindingBug.zip)

## Steps to reproduce

1. Run layout 1.
2. Try to click anywhere on the red tiles that are above the empty space.
3. Try the same in layout 2.

## Observed result

Layout 1 will fail to find path, layout 2 will find path.

## Expected result

Both layouts should work the same, if it can move closer on any axis, it should move.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r310

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2022-09-20 10:55
This is by design. Moving to an obstacle is not valid, as it is not allowed to make a path to an obstacle. Therefore moving to an obstacle will make a best-effort attempt to move to the nearest empty cell. If the nearest empty cell is itself blocked off by obstacles, then finding a path will fail, as it's impossible to make a path there.

Also I don't think there's any good way to fix this without doing something crazy like having a secondary pathfinding engine to find a nearest non-empty cell that is still reachable!

**Closed by AshleyScirra** 2022-09-20 10:55 UTC
Labels: not a bug

**Comment by avishaymizrav** [comment] 2022-09-20 11:10
@AshleyScirra 

I see. Is there a reason why a failed path will stop the current moving though path?

**Comment by AshleyScirra** [comment] 2022-09-20 11:12
Finding a new path clears the current path, on the assumption you don't want to keep moving to the old destination if you've chosen somewhere new to move to.
