### ISSUE TITLE
(c3 runtime) iOS 12.1 Video autoplay don't work

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#2483] opened 2018-12-30 23:52 UTC
## Problem description

The Video-**Autoplay** on iOS 12.1 (Safari) don't work. (On Android it works)

## Attach a .c3p

[Example](https://drive.google.com/open?id=16yO4SPdYtL-x7jaOgeo_CJ3lQaYK4tGr)

## Steps to reproduce

1. Create new project. 
2. Add the official video plugin from scirra.
3. Add any mp4-video for testing.
4. Check "autoplay" on the video settings.
5. Start your app/game on iOS Safari.
6. - Autoplay don't work -

## Observed result

Video autoplay don't work.

## Expected result

Video autoplay works.

## First affected release

r131 stable

## Affected browsers/platforms

* Chrome: no
* Firefox: no
* Edge: no
* Safari: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r131 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 17 gb
Storage usage (approx): 139 mb (0.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2019-01-03 11:51
Confirmed via remote preview, assigning to @AshleyScirra to review.

**Comment by AshleyScirra** [comment] 2019-01-04 15:30
In the Safari browser, I'd expect it to apply the same autoplay rules as other browsers do - i.e. it can't start playing until the first user input event. So I'd assume it's just that.

**Comment by shortercode** [comment] 2019-01-04 17:18
@AshleyScirra I should have noted above but the video did not start autoplay after the first user interaction either. Is it expected that you need to manually start video's on mobile?

**Comment by AshleyScirra** [comment] 2019-01-07 13:05
Ah OK, reopening to check.

**Comment by AshleyScirra** [comment] 2019-01-07 16:33
The problem is you only have the video in WebM format, which Safari doesn't support. You'll need to encode your video to MP4 for it to work in Safari. See the documentation: https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/video

**Closed by AshleyScirra** 2019-01-07 16:33 UTC
Labels: iOS, not a bug

**Comment by masscube** [comment] 2019-01-08 08:06
Not work with mp4 too.. thats my problem.

**Comment by AshleyScirra** [comment] 2019-01-08 11:51
I tested it with an MP4 video and it worked. If you still have an issue please file a report following all the guidelines.
