### ISSUE TITLE
Json object cannot toggle boolean.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#3475] opened 2019-11-13 03:16 UTC
## Problem description

The image below shows that it is possible to toggle a normal boolean, but it is not possible to toggle a Json boolean.
![image](https://user-images.githubusercontent.com/34659544/68730025-58c36100-05aa-11ea-8b05-fc5e645e2b50.png)

## Attach a .c3p

Any file should lack this option.

## Steps to reproduce

1. Open any file.
2. Put a Json object in your project.
3. Try to toggle one of its booleans

## Observed result

Cannot toggle Json object boolean.

## Expected result

Being able to toggle it since it would follow C3's pattern.

## More details

**Affected browsers/platforms:** Chrome, maybe others.

**First affected release:** 174, maybe others.

## System details

No crashes.

**Comment by AshleyScirra** [comment] 2019-11-13 12:00
This is a suggestion, not a bug report, but it looks trivial so I'll leave this open.

**Comment by dupuqub** [comment] 2019-11-13 12:11
I deeply appreciate the effort, thanks. I feel some minor yet useful things like this get lost easily under suggestions.

**Comment by dupuqub** [comment] 2019-11-13 13:19
also, pushing my luck to the limit... "Add to" and "Subtract from" also seem missing from Json objects. Is this also trivial? It would certainly make my life a lot better.

**Comment by shortercode** [comment] 2019-11-15 12:34
Was pretty trivial as @AshleyScirra said. I've implemented the 3 actions and committed them for the next beta release.

**Closed by shortercode** 2019-11-15 12:34 UTC
Labels: enhancement
