### ISSUE TITLE
GooglePlay plugin and Ultimate Ads plugin clash...

### ISSUE THREAD

**Issue by Bootfit** [Scirra/Construct-3-bugs#1539] opened 2018-05-02 15:31 UTC
## Problem description

Dev app has been using the ([Ultimate Ads plugin](https://www.scirra.com/store/construct2-plugins/ultimate-ads-3549)) with no problems for a couple of months - exported for Android(Cordova) and built via Phonegap. Recently also added the Construct GooglePlay plugin to connect to Google Play leaderboards. The GooglePlay plugin now clashes with the Ultimate Ads plugin resulting in no ads being shown.

If you edit the _config.xml_ and comment out the GooglePlay plugin...

```
<plugin name="construct-play-games" spec="1.0.8" >
	<variable name="APP_ID" value="" />
</plugin>
```
...and rebuild via Phonegap the app shows the ads again.

When using GameCenter for iOS and exporting and building via Phonegap there's no clash with the Ultimate Ads plugin - both the Apple leaderboard and banner ads work together. The issue is only on Android.

## Attach a .c3p

[ad-banner-test.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1967864/ad-banner-test.c3p.zip)

## Steps to reproduce

1. Export for Android, build via Phonegap and run app on Android phone - no banners will display
2. Export for Android, edit _config.xml_ and comment out the three lines for construct-play-games plugin (code highlighted above), build via Phonegap and run app on Android phone - banners will now display

## Observed result

No banners displayed

## Expected result

Expected banners to display as normal

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 66.0.3359.139
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
C3 release: r98 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 250 mb (0.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel HD Graphics 4000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2018-05-02 15:43
I don't have access to the Ultimate Ads Plugin for testing, so I'm still trying to think of a way for me to test this at the moment.

When you are building with the construct-play-games plugin enabled is the APP_ID value set?

**Comment by Bootfit** [comment] 2018-05-02 15:47
Yes - the App ID (Web), Client ID and App ID (android) values were all entered. I've left them empty for the attached .c3p

**Comment by shortercode** [comment] 2018-05-02 15:55
That's what I guessed, but it's worth checking.

Does either the Google Play Plugin or the Ultimate Ads plugin produce any errors?

Does the Google Play plugin work, or is it broken as well?

I think I might need to bring @TobyReeno in on this.

**Comment by Bootfit** [comment] 2018-05-02 15:57
Yeah the GooglePlay plugin works - I can connect to the leaderboard I created, its just that the banners no longer load when the GooglePlay plugin is part of the build.

**Comment by shortercode** [comment] 2018-05-02 16:06
It's quite odd, both plugins use parts of Google Services so it could be that the newer one is disabling the older one. Alternatively it could be that there's some code collision, but I'd have to run the project to be sure.

Could you perhaps try exporting your example project as an Android Studio project and sending that to me? Hopefully this won't be specific to PGB.

**Comment by Bootfit** [comment] 2018-05-02 16:35
Here it is exported as an Android Studio Project...

[New project.android.project.zip](https://github.com/Scirra/Construct-3-bugs/files/1968142/New.project.android.project.zip)

**Comment by shortercode** [comment] 2018-05-02 16:36
Thanks @Bootfit

**Comment by shortercode** [comment] 2018-05-02 16:48
That android project doesn't actually include the Ultimate Ads plugin...

**Comment by Bootfit** [comment] 2018-05-02 16:50
Yeah I think I’ve sent the wrong one. I’ll have to resend tonight.

**Comment by shortercode** [comment] 2018-05-02 16:57
Ah okay, I'll be finishing for the day soon anyway.

**Comment by Bootfit** [comment] 2018-05-02 21:26
Just checked and that example project does have the Ultimate Ads plugin when opened in Construct3 - however when it's exported for Android Studio it doesn't seem to include it. Not sure what to suggest.

**Comment by shortercode** [comment] 2018-05-02 21:32
Mmm export as Cordova, check that ultimate ads is included and send that
over. Might be some other issue with the build server not including the
plugin, I'll check that while I'm at it.

On 2 May 2018 22:26, "Bootfit" <notifications@github.com> wrote:

Just checked and that example project does have the Ultimate Ads plugin
when opened in Construct3 - however when it's exported for Android Studio
it doesn't seem to include it. Not sure what to suggest.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/Scirra/Construct-3-bugs/issues/1539#issuecomment-386126687>,
or mute the thread

**Comment by Bootfit** [comment] 2018-05-02 21:42
Here you go - **add-banner-test.zip** has the line...

`<plugin name="cocoon-plugin-ads-android-admob" />`

...added to the _config.xml_

Also added the c3p if you need that.

[add-banner-test.zip](https://github.com/Scirra/Construct-3-bugs/files/1968993/add-banner-test.zip)
[ad-banner-test.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1968992/ad-banner-test.c3p.zip)

**Comment by shortercode** [comment] 2018-05-02 21:45
Yeah looks like it should have been added by the build server, I'll take a
look tomorrow morning.

**Comment by shortercode** [comment] 2018-05-03 10:29
@TobyReeno thanks for replying, hopefully I will be able to resolve the issue by myself but I will let you know if it's something outside of my control.

**Comment by Bootfit** [comment] 2018-05-08 14:46
Hello folks - any update on this?

**Comment by shortercode** [comment] 2018-05-08 15:02
Hey @Bootfit sorry I haven't been able to look at the project yet. I'm trying to get a fairly substantial update of the build server done, and given the complexity of the code I'm trying to avoid any distractions. I'm going to look into this once I've finished this build server stuff.

**Comment by Bootfit** [comment] 2018-05-08 16:31
@shortercode  - OK cheers for the update. Got a couple of smaller things to sort before launch myself.

**Comment by Bootfit** [comment] 2018-05-14 08:55
Any movement guys?

**Comment by shortercode** [comment] 2018-05-14 12:58
Looking into it now. First thing I've seen is that Ultimate Ads isn't setting `AddCordovaPluginReference` within it's plugin file, so it's not listed in the config.xml or config.json files. @Bootfit Have you been adding the cordova plugin reference manually before building on PGB?

**Comment by Bootfit** [comment] 2018-05-14 13:13
Yes - I've been adding the following line in the config.xml file:

`    <plugin name="cocoon-plugin-ads-android-admob" />
`
or
`    <plugin name="cocoon-plugin-ads-ios-admob" />
`

as per the instruction video: [https://youtu.be/6CZBWlXapqs?t=2m9s](url)

It's been working fine until I dropped in the GooglePlay plugin - and then the ads no longer appear.

**Comment by shortercode** [comment] 2018-05-14 13:26
Thanks, I've already watched the video. Just wanted to check. I've built an APK and testing it at the moment.

**Comment by shortercode** [comment] 2018-05-14 14:14
Okay so I'm afraid it's pretty much exactly what I expected, and it's not an easy fix.

So pretty much all Google features are provided through the `play-services` library, which is split up into some 20 odd modules.

Ultimate ads uses:
- `play-services-ads`
Google Play uses:
- `play-services-ads`
- `play-services-ads`

**Comment by Bootfit** [comment] 2018-05-14 14:28
Ok so how do we get it that UA plugin uses the correct or current play services?

I’m guessing that the google play plugin updates regularly so any update to the UA plugin will break next time that the google play plugin updates again?

Is this something to pass back to @TobyReeno ?

**Comment by shortercode** [comment] 2018-05-14 14:47
Well I've tried making some simple changes to the plugin, and haven't had much luck reviving it.

I believe the actual cordova plugin which @TobyReeno is using is maintained by someone else. By the looks of it hasn't been updated for several years, which is unfortunately common for cordova plugins. We're moving towards using all 1st party ones to get around this. Either you or Toby might be able to get the original plugin updated. Failing that someone could fork it and fix the plugin.

The version mismatch isn't too hard to work around as a plugin author. Internally we get around it to "+" , which means latest, instead of a specific version. It does have the side effect that the plugin might be broken by a change in play services, so it increases the maintenance work for the plugin developer.

This might not be a popular suggestion, as I think you've had trouble in the past with it, but the mobile advert plugin does use the latest version of play services so should be compatible. Depends if you've got enough time for the Ultimate Ads plugin to be updated or not.

**Comment by shortercode** [comment] 2018-05-14 14:52
Incidentally @TobyReeno you can use the following snippet in your `plugin.js` file to specify the cordova plugins to be included in `config.xml` on export:

```javascript

this._info.AddCordovaPluginReference({
    id: "cocoon-plugin-ads-android-admob",
    platform: "android"
});
this._info.AddCordovaPluginReference({
    id: "cocoon-plugin-ads-ios-admob",
    platform: "ios"
});

```

**Comment by TobyReeno** [comment] 2018-05-14 16:56
As @shortercode noticed, the Cordova plugins that Ultimate ADS is using are not maintained by me. They are maintained by Ludei team. I am not a JAVA developer so I can't help here myself but I will write them an email right now asking for the update. Will keep you updated once I get a reply.

**Comment by Bootfit** [comment] 2018-05-14 21:13
@shortercode - I've just tried to use the Mobile Advert plugin and build via Phone Gap but it blows out again.

Check out the attached .c3p file and try and build via Phone Gap. It blows out, but if you comment out the line:

`<plugin name="construct-mobile-advert" spec="1.0.23" />`

in the config.xml file and try to rebuild via PGB it then builds fine.

Am I doing something wrong here to be having so many issues regarding this?

**Comment by shortercode** [comment] 2018-05-15 10:02
Is it failing to build or not running on the device? I just tried building the project you gave me on PGB and it worked fine. Are you editing the config.xml in any way?

**Comment by shortercode** [comment] 2018-05-15 10:03
There was 2 issues related to the mobile advert plugin and PGB, but I resolved them awhile back. I believe you were hitting those originally.

**Comment by shortercode** [comment] 2018-05-15 11:27
Oh your building iOS, I haven't tried iOS on PGB yet. I currently in the middle of updating the build server but will try iOS when I'm done.

**Comment by shortercode** [comment] 2018-05-16 13:02
Okay so I've done a lot of googling and several builds on PGB and the issue is basically PGB doesn't support the swift language. Which we've used to write our newer iOS plugins. By the looks of it what other developers have done is either said "we don't support PGB" or they've rewritten their iOS plugins in Objective C.

I'm not really sure what my answer is... swift is a nicer language and Apple are pushing it over Objective C now. Additionally it's a bit of a time sink to rewrite the things in a different language because of what is effectively a bug in PGB. I'll chat with @AshleyScirra about it tomorrow.

In the meantime if you have a mac then you have the option of exporting from C3 as an xcode project instead. Sorry I can't be much more help at the moment, but I can't see a "quick workaround".

**Comment by Bootfit** [comment] 2018-05-16 16:04
Okay - was hoping it wasn’t going to be something like that. I appreciate you looking into this. 

I have to use PGB as I’m using a third-party plugin that allows native social sharing as this a pretty big basic in modern apps. But if I use PGB for this I can’t implement banner ads (neither the UA plugin or the Mobile Advert plugin)? Again another basic staple for apps. So I have to choose between one of these two basics?

I do have a Mac and I have Xcode on it, however I’m not a developer and don’t know where to begin with it - I don’t want to learn to code and obviously one of the main selling points of Construct is that users can create apps with no coding knowledge. Unless of course they want to implement both native social sharing and banner ads.

Tell me I haven’t just spent the past 6 months trying to get these features to work together all for nothing. Is it worth ditching Construct and just shelling out for Buildbox?

**Comment by shortercode** [comment] 2018-05-16 16:42
Yeah I was hoping that it wasn't that as well, it's frustrating for us too when we come up against a brick wall like that. Hopefully we can come to some solution for it, but the best solution requires other developers to do work and cordova/phonegap ecosystem is kind of slow moving.

I can likely get the third party plugin to work on the build server, I just need to review it and add it to the whitelist.

While xcode can be confusing in places you shouldn't need to write any actual code to build your game from an xcode project.  I published a guide [here](https://www.construct.net/gb/tutorials/ios-application-development-and-publishing-with-xcode-25) which covers the whole process and I'm happy to help if you have any problems.

I had a look and buildbox just generates an xcode project, so I don't think it would be any easier.

**Comment by Bootfit** [comment] 2018-05-16 17:07
I don’t think exporting via Xcode as opposed to Cordova will be much help, as I still have to take the app into PGB to implement the native social sharing plugin.

**Comment by shortercode** [comment] 2018-05-16 17:16
Really? When we make xcode projects we include the plugins with them, all
the phone gap plugins are publicly available and should be compatible with
the build service. What's the social plugin called?

**Comment by shortercode** [comment] 2018-05-16 19:13
No worries, sometimes it's hard to walk to line between programming madness and a simple explanation. I'll try to keep it simple :P

Yup that's what I wanted to know.

**Comment by shortercode** [comment] 2018-05-16 19:19
You just sharing text right?

**Comment by Bootfit** [comment] 2018-05-16 19:31
I’m sharing text, a hashtag, a global variable and a Twitter handle:

Execute javascript “window.plugins.socialsharing.share(‘Text message here #Hashtag “&Highscore&” @TwitterHandle’)”

**Comment by shortercode** [comment] 2018-05-16 20:10
Cool I've written a Construct 3 plugin which has an action equivalent to `window.plugins.socialsharing.share("your text here")` I'll check it works properly when I get into the office tomorrow and publish it to the addon exchange. Sure a few other users will find it useful!

**Comment by shortercode** [comment] 2018-05-17 15:51
@Bootfit check out [https://www.construct.net/gb/make-games/addons/129/social-sharing]( https://www.construct.net/gb/make-games/addons/129/social-sharing).

The "ShareText" action should cover you.

I'm going to close this issue now, as it's proven to be an external bug. If you have additional problems with the build service etc. please open a new bug report and I'll look into it. If you have an issue with the plugin please comment on the addon exchange.

**Closed by shortercode** 2018-05-17 15:51 UTC
Labels: Android, external
