### ISSUE TITLE
Resize handles of expression window are off

### ISSUE THREAD

**Issue by TackerTacker** [Scirra/Construct-3-bugs#6281] opened 2022-11-17 22:46 UTC
## Problem description

The resize handles of the expression window are offset. They are correct on other windows.

https://user-images.githubusercontent.com/18266300/202575203-d9a9b8ca-058a-46b3-8868-4bca11dd8bb6.mp4

## Attach a .c3p

Any project will do so I post the one from my last bug report again.

[Resize handle bug.zip](https://github.com/Scirra/Construct-3-bugs/files/10036244/color_picker_bug.zip)

## Steps to reproduce

1. Open project file 
2. Create some events to open up the action events panel and then the expressions panel.
3. Hover mouse near the edge of both panels to see that the expression panel resize handles are offset

## Observed result

Resize handles of expression window are offset.

## Expected result

Resize handles should be in the correct place.

## More details

**Affected browsers/platforms:** 

I installed C3 as a PWA via chrome

**First affected release:** 

I'm on release r317.2 but noticed this in previous releases, idk when it started or if it was always an issue.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2022-11-28 15:45
This only reproduces for me once after clearing all browser data. As soon as you resize the expressions dictionary, it starts working correctly forever, even after reloading Construct (presumably because the problem doesn't happen when loading a saved dialog position, only when it's completely new).

Steps to reproduce:

1. Clear browser data
2. Reload Construct
3. Create a new project
4. Add a "Compare two values" event
5. In parameters dialog, check resize cursor at bottom-right edge of expressions dictionary.

I had a look but it seems something complicated is happening in the dialog code. The Expressions Dictionary is a bit of a special case, being non-modal, resizable and nested. I think this mostly involves your code @DiegoScirra - could you take a look?

**Comment by DiegoScirra** [comment] 2022-11-29 15:37
This will be fixed for the next beta.

Revision 18102.

**Closed by DiegoScirra** 2022-11-29 15:37 UTC
Labels: difficult
