### ISSUE TITLE
Dark Theme: renaming things makes the text black, can't see it at all

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#735] opened 2017-08-22 16:06 UTC
## Problem description

This has been around since the Dark Theme was released.

## Attach a .c3p

![image](https://user-images.githubusercontent.com/7268697/29575257-98f62186-876c-11e7-8ee7-08c9ca44eff7.png)

## Observed result

The text when deleted and typed a new is black

## Expected result

Have the text white

## Affected browsers

* Chrome: yes
## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 60.0.3112.101
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.800000011920929
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36
C3 release: r49

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 343 mb (5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by alastajj** [comment] 2017-08-25 03:12
Duplicate of #591 / #631 / #635

**Comment by AshleyScirra** [comment] 2017-08-25 11:51
All the other reports are closed and presumably were fixed, there may be some extra cases where the fix wasn't applied though.

**Comment by JeFawk** [comment] 2017-08-25 12:10
@alastajj  it's not a duplicate if it's still an issue, also 591 was mine to begin with.

**Comment by alastajj** [comment] 2017-08-29 04:23
He said it's been fixed, it's just that the Dark Theme update has not been applied to C3 yet.

**Comment by JeFawk** [comment] 2017-08-29 12:55
Well I'm not really looking whether an update has a theme update as well, but you have a point.

**Comment by AshleyScirra** [comment] 2017-08-29 17:56
BTW are you definitely using the latest dark theme? Soon after the dark theme was released we made it a built-in feature. You have to delete the original dark theme addon and switch to using the built-in one to use the latest version. If you never did that, you're still using an old version of the dark theme.

**Comment by JeFawk** [comment] 2017-08-29 22:08
Good idea to check.
( a few moments later ) 
I checked and I got the one which can't be uninstalled, so I guess it's the one embedded.

![image](https://user-images.githubusercontent.com/7268697/29846463-a99b1fd8-8d1f-11e7-8796-05482526e49a.png)

**Comment by Animmaniac** [comment] 2018-01-18 22:50
Fixed for next theme release.

**Closed by Animmaniac** 2018-01-18 22:50 UTC
Labels: theme
