### ISSUE TITLE
Incorrect height of banner ads

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#6438] opened 2023-01-30 14:06 UTC
## Problem description

Smart Portrait size in construct 3 should be "screen width x 32/50/90"
This is false, as in some situations, it is as big as 180 (double that of 90)

## Attach a .c3p

Absolutely no need. Just add banner ads at the bottom.

## Steps to reproduce

I am using Redmi 8A to test ads
To avoid Admob ban, there should be good distance between banner ads & the app content. Keeping that in mind I made my game

But on testing, I noticed abnormalities. I realised that adz height is WAY bigger than 90

![WhatsApp Image 2023-01-30 at 19 20 58](https://user-images.githubusercontent.com/46170077/215497825-5b19f247-44fc-46b1-9bd5-846656d62e9b.jpg)

This is screenshot of the game. 

![WhatsApp Image 2023-01-30 at 19 20 58 - Copy](https://user-images.githubusercontent.com/46170077/215497969-52100dd5-9979-414b-bb18-75102efbfdf7.jpg)

This is cropped part of the ads.

Resolution of mobile is 720 x 1520
Resolution of ads image is 576 x 144, equivalent to 720 x 180

## Observed result

Height of ads is 180

## Expected result

Maximum height should be 90

## More details
Affected:- Android. Did not tested on iphone as I don't have it

Using latest version of Construct 3

I discovered this issue when my 3 games got banned because of "Google-served ads obscuring content" (More details:- https://www.construct.net/en/forum/construct-3/general-discussion-7/suggestionsexperience-174945 )

This issue can get my admob account banned. And I HEAVILY use banner ads in my apps

**Comment by AshleyScirra** [comment] 2023-01-30 15:42
Please always provide a project, as per the bug report guidelines, even when you think the problem is obvious. Often the problem is not obvious or more complicated than you think. It's also not clear from your report which other ad settings you have chosen, and providing a project will help us figure out exactly what you're doing.

**Comment by layilpaht** [comment] 2023-01-30 18:19
[sample.zip](https://github.com/Scirra/Construct-3-bugs/files/10538713/sample.zip)

Here is the sample project. Rename it to c3p

**Comment by fredriksthlm** [comment] 2023-01-31 07:47
This old one seems to be the same issue as you have: https://groups.google.com/g/google-admob-ads-sdk/c/mXupo-C4Fis?pli=1

I would recommend using BANNER or LARGE_BANNER instead of SMART to get a fixed size.
(SMART is actually deprecated anyway)

**Comment by layilpaht** [comment] 2023-01-31 13:57
https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/mobile-advert

1.) What is BANNER or LARGE_BANNER ? 
2.) If it is deprecated then why it is not mentioned in manual or anywhere else?

**Comment by fredriksthlm** [comment] 2023-01-31 14:40
> 

Banners and their sizes and how they render are defined by Google and their Admob SDK, it has nothing to do with Scirra or Construct. Here are the available sizes and how they work:
https://developers.google.com/admob/android/banner#banner_sizes

You can see in the left pane that _Smart_ is marked as deprecated, it also states in the docs that they should not be used.

For your size I believe you should use what Construct call "Standard", which is just called "Banner" by Google.

**Comment by layilpaht** [comment] 2023-01-31 16:41
Important Update:-
I went for "Large" this time instead of "Smart Portrait". "Large" Dimension is 320x100

![WhatsApp Image 2023-01-31 at 22 02 17](https://user-images.githubusercontent.com/46170077/215823091-0f98678e-7286-40a5-81d8-bbcf2b4da346.jpg)

Screenshot of whole screen

![WhatsApp Image 2023-01-31 at 22 02 17 - Copy](https://user-images.githubusercontent.com/46170077/215823277-362fd980-c2cb-4385-b17b-ae7312d95395.jpg)

Screenshot of banner ads(cropped from above image)

Just by looking at screenshot, anyone can figure out that dimensions are definitely NOT 320x100
But one thing I noticed that this banner ads dimension is 512x160, exactly same ratio of 320x100
Maybe this discovery may help in the issue

**Comment by fredriksthlm** [comment] 2023-01-31 16:56
320x100 and 320x50 is not referring to pixels. it is dp. otherwise the banners would be super small on phones with high resolution and vice versa..
the ads are shown in its own activity and not the same activity as your app, so your resolution in your app is not relevant.

you should look at the ratio, which you have figured out already. so either go with _Banner_ or _Large_Banner_, and they will have the same ratio on all phones.

(_Banner_ is still the most used size, and it is not certain yo will get higher revenue with bigger banner actually..)

**Comment by DiegoScirra** [comment] 2023-02-01 13:17
Just took a look at our documentation and it makes no mention those size values are actually for device pixels, which can be confusing. Will update that to make it clear.

**Comment by DiegoScirra** [comment] 2023-02-01 13:32
Closing as there is nothing else to do.

**Closed by DiegoScirra** 2023-02-01 13:32 UTC
