### ISSUE TITLE
Audio stops in iOS with incoming calls

### ISSUE THREAD

**Issue by UpToSix** [Scirra/Construct-3-bugs#5954] opened 2022-08-02 13:24 UTC
Audio stops playing in the game, when in iOS,  with an incoming call

## Problem description

When in iOS, any game is playing a sound, if an incoming call comes, the audio stops. Reported to apple but the suggestion given by apple does not work as it is asking us to listen to OS level events.

## Attach a .c3p

Any demo projects can be taken which is developed on constuct 3 and running on an iOS device.

## Steps to reproduce

 
1. Start the game, wait untill it starts playing the music
2. Give a call to that phone
3. Sound will stop playing

## Observed result

1. You can only get sound back by restarting the game
2. It repeats this behaviour in Apple

## More details
Apple has suggested the following. We need nelp how to get rid of this issue with Construct 3.
Apple has suggested the following.
Link: https://developer.apple.com/documentation/avfaudio/avaudiosession/responding_to_audio_session_interruptions

**Affected browsers/platforms:** iOS

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2022-08-09 14:38
I can't reproduce this in the Safari browser, but it does reproduce in an exported iOS app (using WKWebView). Unfortunately it appears to be a bug in iOS. After an incoming call, everything looks normal in the code and iOS reports the audio playback state as working, but nothing can be heard.

I've reported the issue to Apple: https://bugs.webkit.org/show_bug.cgi?id=243727
Closing this issue as it will be followed up there.

**Closed by AshleyScirra** 2022-08-09 14:38 UTC
Labels: external, iOS
