### ISSUE TITLE
Dark theme event highlighting is buggy

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#3393] opened 2019-10-06 21:54 UTC
## Problem description

Event highlights are sometimes not drawn properly.

## Attach a .c3p
A .gif showing the problem:
https://www.dropbox.com/s/vsyi9tznnj5ijks/EventBug.gif?dl=0

## Steps to reproduce

Use dark theme and move your mouse around some event conditions. Try after clicking a condition too.

## Observed result

The highlight is all chopped up and showing on the wrong events.

## Expected result

The highlight to display properly and on one event at a time.

## More details
Having a hard time reproducing in Chrome. It seems to happen more with deeply nested sub-events. Might be a desktop issue but eh..If that's about to be deprecated I guess it's not a big deal. Thought I'd report anyway.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.39.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.39.0 (like Chrome/75.0.3770.80)
C3 release: r169 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 354 gb
Storage usage (approx): 875 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-10-07 10:55
It looks like a paint bug in Chrome. Can you reproduce it in Canary?

And as ever - I can't see what you're seeing if you don't provide a project, which can significantly slow down our response to this.

**Comment by Tokinsom** [comment] 2019-10-07 13:48
It's an editor bug so I didn't think a .c3p was necessary...

here's a .c3p with some simple compare events:
https://www.dropbox.com/s/jx9nx704zotwtdj/EventHighlightBug.c3p?dl=0

and a .gif showing the bug in this very same .c3p
https://www.dropbox.com/s/f7o0k1ogwmub2a5/EventHighlightBug.gif?dl=0

**Comment by AshleyScirra** [comment] 2019-10-07 14:17
Closing as Chrome bug fixed in canary.

**Closed by AshleyScirra** 2019-10-07 14:17 UTC
Labels: chrome, external, theme
