### ISSUE TITLE
Construct 3 fails to open capx if configurations are used

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#1518] opened 2018-04-23 17:22 UTC
## Problem description

Construct 3 won't open the file if multiple configurations are used.

## Attach a .capx
here's a minimal capx using configurations on Layout 1
[test.zip](https://github.com/Scirra/Construct-3-bugs/files/1939317/test.zip)

## Steps to reproduce

1.Open the capx with c3

## Observed result

![image](https://user-images.githubusercontent.com/11213825/39142578-5f08af50-472b-11e8-81fd-6baa257e2de3.png)

## Expected result

The file getting opened, or a dialog telling me to choose which configuration I want to keep using. Note that the issue is still occurring when I remove all the additional configurations for my project.

## Affected browsers

n/a

## System details

n/a

<details><summary>View details</summary>

n/a

</details>

**Comment by AshleyScirra** [comment] 2018-04-25 16:41
It fails to open because the project is corrupt and missing some files, not because it uses configurations. In fact if you open it in C2, it tells you that it's corrupt:

```
---------------------------
Project missing files
---------------------------
Some files are missing from the project. They may have been deleted, or the project may be corrupt. The missing files are:

Files\icon-16.png
Files\icon-32.png
Files\icon-114.png
Files\icon-128.png
Files\icon-256.png
Files\loading-logo.png

The project may not edit, preview or export correctly until these files are replaced.
---------------------------
OK   
---------------------------
```

Put those files back like it suggests and it should import to C3 again.

**Comment by skymen** [comment] 2018-04-25 18:56
Well it's weird because the files are there :/ 
I double checked.
I recreated a file from scratch and tried again.
![image](https://user-images.githubusercontent.com/11213825/39265612-023b52ca-48c8-11e8-8923-07c21edc292b.png)

[config Test 2.zip](https://github.com/Scirra/Construct-3-bugs/files/1948381/config.Test.2.zip)

If you want to try yourself, the steps are:
1) Create a new file in C2
2) Open the configuration window
3) Create a new configuration
4) Create a sprite
5) Make it so each configuration has a different position for that sprite
6) Save
7) Open in C3

I made a 2mn video to demonstrate it:
https://youtu.be/t3S1u-0U3_4

Now I know what you may say:
"This feature is unfinished and unsupported both in C2 and in C3 therefore no one should use it"

However, it is still pretty game breaking. Because Construct 2 can still open the file. So far this never casued any issue. Now imagine a newbie learning construct 2, making a project, and trying out every feature on the editor, and then wanting to switch to C3.

Thing is the file stays "corrupted" for C3 even after removing every configuration.
So there might be a case of someone making a project on C2 where that he started by experimenting everything then making a real game out of it. He wouldn't be able to switch to C3 because of that. 

Therefore, you should either remove everything about this in C2, or support it in C3's capx to c3p converter (or even maybe fully supporting it in C3 cause it was a pretty nice idea if it's given enough time and thought)

For the case of actually supporting it in C3, as the C2 feature now only works for object's positions, behavior values and text, it would be pretty neat to allow in C3 to have configurations per layout, allowing to have the same layout with small modifications and then being able to switch between configurations at runtime. That would make for easy layout evolution like you can see in lots of games where a map is reused multiple times at different moments but with minor changes.

Again, I know that this is a heavy idea, not easy to implement, and I also know that ideas should be submitted to the idea service, which I'm probably gonna do later.

**Comment by AshleyScirra** [comment] 2018-04-25 19:52
Ah, I can reproduce with that project, thanks.

**Comment by skymen** [comment] 2018-04-25 20:01
For the sake of it I dropped an idea in the suggestion and ideas service
https://construct3.ideas.aha.io/ideas/C3-I-471

**Comment by AshleyScirra** [comment] 2018-05-02 17:06
This should be fixed in the next release. However it may not import every property, and it uses an arbitrary configuration to read data from (there is no picker UI). You should delete all configurations except one before importing to C3 to make sure it imports with the properties you intend. I can import the C2 project OK if I delete all configurations except one, but you said that didn't work for you, so I can't reproduce that aspect. If you still can't import a project at all after the next release then please file another issue, but note we will only support this so far as fixing the "cannot import project" dialog - it may still skip or use arbitrary data.

Frankly I would sooner completely remove the configurations feature rather than add anything more to it or support it any further. It is extremely complicated to implement, and few people seem to need it, so there seems little justification for adding such a lot of complexity in to the editor.

**Closed by AshleyScirra** 2018-05-02 17:06 UTC
