### ISSUE TITLE
Construct freeze after closing animation editor

### ISSUE THREAD

**Issue by JonaszO** [Scirra/Construct-3-bugs#6337] opened 2022-12-15 11:23 UTC
## Problem description

After click on 'X' to close animation editor, whole project is freezing and i receive red scrren with error information

[## Attach a .c3p]
noo need attach c3p because this error cause in blank new project
see exacly what happen below on recorded screen

(https://www.youtube.com/watch?v=2YjPjm4ZjNk&feature=youtu.be)

## Steps to reproduce

1.Open project
2. open animation editor and add folders
3.close animation editor
4. project stops and  freeze 

## Observed result
in my opinion sprites with folders cause this problem, because i check few sprites, and sprite with removed folders dont stops editor
On mouse cursor i see rotating icon (loading?) next after 30-60 seconds i receive red clor screen with error info

## Expected result

i expect to close editor and continue work

## More details

Hard to say, i use only one third party addon by ROJOhound called Outline 
i use relase 322
maybe i have lot of animations? or maybe folders cause this problem?

I try on Chrome 
and Altroo browser
on CANARY chrome in my opinion works better

relase 322

## System details

Platform information
Product: Construct 3 r322 (beta)
Browser: (unknown) (unknown)
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

Error report information
Type: unhandled exception
File: https://editor.construct.net/r322/projectResources.js, line 568, col 388
Message: Uncaught TypeError: f.JQc is not a function
Stack: TypeError: f.JQc is not a function at d.zd (https://editor.construct.net/r322/projectResources.js:568:388) at C_a.hPb.ka (https://editor.construct.net/r322/projectResources.js:1959:42) at tx.g.J.Qb.Du (https://editor.construct.net/r322/projectResources.js:1947:491) at CCG.He.g.kc.tca (https://editor.construct.net/r322/main.js:1343:313) at HTMLDocument.e (https://editor.construct.net/r322/main.js:269:411)
Construct version: r322
URL: https://editor.construct.net/r322/
Date: Thu Dec 15 2022 12:12:13 GMT+0100 (czas środkowoeuropejski standardowy)
Uptime: 45.4 s

</details>

**Comment by DiegoScirra** [comment] 2022-12-15 11:33
Duplicate of #6332. Will be fixed in the next beta. Leaving this open as it it a pretty obvious bug and more people are likely to encounter it.

**Closed** 2022-12-19 14:26 UTC
Labels: duplicate

**Comment by PogoStick1987** [comment] 2024-05-09 12:40
This error is still an issue btw

**Comment by WilsonPercival** [comment] 2024-05-09 13:51
> This error is still an issue btw

@PogoStick1987 No, everything works fine for me. If you have a problem, post a new report.
