### ISSUE TITLE
Animation Editor:  Can't paste anything from outside the editor

### ISSUE THREAD

**Issue by shinkan-fb** [Scirra/Construct-3-bugs#872] opened 2017-10-03 20:07 UTC
## Problem description

Pasting (using ctrl+v or a button)  anything from outside of C3 like Paint, Photoshop etc. into an Animation Editor (Sprite, Tiled BG etc.) is not working at all.
Copying and pasting between sprite animation frames, or between different objects in the scope of same project works perfectly fine.

## Attach a .c3p

You can use New project, but here you go anyways ;)
[copypaste.zip](https://github.com/Scirra/Construct-3-bugs/files/1353610/copypaste.zip)

## Steps to reproduce

1. Open the project
2. Create a new Sprite or Tiled BG
3. Open any kind of third party painting software and copy something
4. Back in Animation Editor try to past it

## Observed result

Nothing is happening.

## Expected result

Stuff you copied from somewhere else should show up after pasting

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r59
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 57 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 780 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2017-10-04 10:58
Thanks for the bug report, I expect this is because we have our own clipboard. It's still rather difficult to integrate with the OS clipboard in a web-app, so we use our own clipboard in most places to get around some of the worst limitations.

I imagine @DiegoScirra made the decision to just use the C3 clipboard so that it was predictable. But you can still import an image by drag n drop or from the file system fairly easily. 

I expect this will be closed as a `wont fix` but will leave it up to @DiegoScirra.

**Comment by DiegoScirra** [comment] 2017-10-04 11:18
People have already reported this one, the main reason I didn't implement it right away is that when an image goes into the system clipboard, it looses the alpha channel information if it had any. This happens if you try and paste something from a browser into a drawing application or the other way round and it is not C3 specific.

Implementing this would be  ok if you are pasting a completely solid rectangle, but if there is any transparency information in there, it will be replaced by black or white, depending on the source.

The end result is not great either way.

Anyway this is a duplicate of #185, so closing as such.

**Closed by DiegoScirra** 2017-10-04 11:18 UTC

**Comment by shinkan-fb** [comment] 2017-10-04 11:27
But pasting an image without transparency is absolutely fine. It was like that for last 6 years in C2 and to this day you still can't paste an image with transparency to C2.
So it's really not an issue.
