### ISSUE TITLE
GL_OUT_OF_MEMORY and context lost

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-3-bugs#3754] opened 2020-04-08 22:36 UTC
## Problem description

I'm usually developing plugins in construct 3, so I exit and enter back the tool a lot of times a day. After a while, the Graph mem starts leaking, the context gets lost and an out-of-mem error starts popping out. This started happening this weekend (on Friday April 4th) and is still happening a lot

I created a camera plugin (single global) that sets BBoxChanged every tick to track an object, at first I thought this was the issue and removed the plugin from my project, but after removing it the error continued no matter if I closed Chrome or even if I kill the process using the task manager.

## Attach a .c3p

[cameraTest.zip](https://github.com/Scirra/Construct-3-bugs/files/4453103/cameraTest.zip)

## Steps to reproduce

1. Open the project and run it
2. Have open the debug tools of the browser (F12)
3. Move the player using the keyboard (arrows)

The screen will start blanking out and flashing trying to recover the context, after several tries the MEM will run out.

May not be related, but Chrome was updating while I wrote this issue, a few moments later after the MEM error.

## Observed result

Canvas stops rendering, everything blanks out. Construct 3 loses context.

## Expected result

This should not happen.

## More details

Chrome Version 80.0.3987.163 (Official Build) (64-bit)
Windows 10 Home
Construct 3 r189.2 stable

## System details

<details><summary>View details</summary>

PASTE HERE
![image](https://user-images.githubusercontent.com/10860045/78839972-3c8fe880-79bf-11ea-94e3-c6a8315f36d7.png)

</details>

**Comment by AshleyScirra** [comment] 2020-04-09 13:08
It works absolutely fine here.

Given this is such a basic demo with an apparently obvious way to reproduce it, I am sure we would be inundated with reports of this from all sorts of users if the problem really was with Construct. However this is the only case I've seen reported, which strongly suggests the problem is specific to your system. Further any problem involving weird graphics/OpenGL/D3D11 issues is likely to be a graphics driver issue. So I suspect on Friday April 4th your system updated to a broken graphics driver. You should check for an update to the driver, install any available software updates for the system, and failing that, either report it directly to Google (crbug.com) or try a different browser.

Based on the likelihood of a graphics driver issue and it not being to do with Construct, closing. If we hear similar reports from other users I might investigate further, but note r189.2 has been out for a month already.

**Closed by AshleyScirra** 2020-04-09 13:08 UTC
Labels: can't reproduce

**Comment by sotano42** [comment] 2020-04-10 05:56
On the C3P attached It started failing, with that basic functionality. I'll do some testing trying to update the graphic driver as you mentioned and update you guys if I found anything useful. It is still happening.
