### ISSUE TITLE
IDE Crash when creating a sprite, then deleting it, then "placing" it in a layout

### ISSUE THREAD

**Issue by rvion** [Scirra/Construct-3-bugs#700] opened 2017-08-10 16:28 UTC
## Problem description

IDE Crash when creating a sprite, then deleting it, then "placing" it in a layout

![ezgif-3-761230250b](https://user-images.githubusercontent.com/2150990/29180913-8fcbb87c-7df9-11e7-8c99-d2ef4b8e9374.gif)

## Attach a .c3p

blank project

## Steps to reproduce

1. create a sprite (but don't place it in any layout)
2. delete it
3. click on the layout

## Observed result

crash

## Expected result

on sprite deletion, I expect the ide to stop wanting me to place a 'first instance', and I expect the cursor to switch back to its default state

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>Platform info</summary>
Platform information
Browser: Chrome
Browser version: 60.0.3112.90
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
C3 release: r48

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 400 mb (2.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

<details><summary>Bug detail</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r48/components/editors/layoutView/layoutView.js, line 1, col 75459
Message: Uncaught TypeError: Cannot read property 'ǃ_K' of null
Stack: TypeError: Cannot read property 'ǃ_K' of null at r.ǃYh (https://editor.construct.net/r48/components/editors/layoutView/layoutView.js:1:75459) at Array.ǃGI (https://editor.construct.net/r48/components/editors/layoutView/layoutView.js:1:75030) at ǃE.Event.ǃOwF.ǃOwN (https://editor.construct.net/r48/main.js:2:256115) at window.ǃPC.dispatchEvent (https://editor.construct.net/r48/main.js:2:254766) at window.ǃPC.ǃYh (https://editor.construct.net/r48/components/editors/layoutView/layoutView.js:1:14945) at HTMLDivElement.ǃL.ǃE.ǃi.ǃE.ǃq.ǃs (https://editor.construct.net/r48/components/editors/layoutView/layoutView.js:1:3875) at HTMLDocument. (https://editor.construct.net/r48/main.js:2:251642)
Construct 3 version: r48
URL: https://editor.construct.net/
Date: Thu Aug 10 2017 18:15:13 GMT+0200 (CEST)
Uptime: 17.1 s

Platform information
Browser: Chrome
Browser version: 60.0.3112.90
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
C3 release: r48

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2017-08-29 17:09
Think this was the same underlying cause as #688, since I can't reproduce it any more, so should be fixed in r52.

**Closed by AshleyScirra** 2017-08-29 17:09 UTC
