### ISSUE TITLE
Editor loses top margin, covering half of menu

### ISSUE THREAD

**Issue by cerjo77** [Scirra/Construct-3-bugs#1110] opened 2017-12-19 10:04 UTC
## Problem description

Every time i try o open a file, or use a feature that opens a pop-up, the editor seems to lose top margin, and the menu bar is more than half covered/hidden. This problem dont-' crash the editor, but makes difficult to read the tabs names and to see the menu's buttons.

## Attach a .c3p

this problem it's not linked with a file, but the editor itself. It happens even when I am opening a file.

## Steps to reproduce

1. Open the editor
2. try to open a file form cloud / or / try to use a feature that requires the editor to open a pop-up
3. the window of the editor loses the top margin and cover more than half of the menu and the names tabs.

## Observed result

the window of the editor loses the top margin and cover more than half of the menu and the names tabs.

## Expected result

nothing would happen.

## Affected browsers

* Chrome: yes/
* Firefox: no
* Edge: not supported
* Safari: not tried

## System details

no crash report

</details>

**Comment by AshleyScirra** [comment] 2017-12-19 11:48
Can you provide the following: 

1. Which version of C3 are you using?
2. Can you share a screenshot of what it looks like for you? I'm not sure exactly what you're seeing.
3. Are you using C3 in 'Add to desktop' mode? Does it reproduce when you run it from the desktop and also in the browser normally?

Please always try to follow the bug report guidelines; if you pasted your system details in to the relevant section it would answer questions 1 and 3.

**Comment by cerjo77** [comment] 2017-12-19 19:30
The problem occours with R73, R72 and R71 as i tested in those.
It happens in desktop mode and browser mode, on chrome.
Version 63.0.3239.108 (Versão oficial) 64 bits
![r73_desktop](https://user-images.githubusercontent.com/22009378/34174954-ec479eaa-e4e1-11e7-8b83-ddff8c479ed3.png)
![r72_browser](https://user-images.githubusercontent.com/22009378/34174955-ec6b4c2e-e4e1-11e7-9bcc-83c3dd11e58d.png)

**Comment by AshleyScirra** [comment] 2017-12-19 19:52
It looks like issue #696 which we fixed back in August. I've no idea how this could still be happening, I've never seen it myself and AFAIK there have been no other reports of this. Maybe try clearing your browser cache, or disabling browser extensions?

**Comment by cerjo77** [comment] 2017-12-19 20:07
Thank you Ashley. Disabling extensions and cleaning history seems to solve the bug.

**Comment by AshleyScirra** [comment] 2017-12-22 12:24
OK, closing as a random glitch.

**Closed by AshleyScirra** 2017-12-22 12:24 UTC
