### ISSUE TITLE
Can't download NW.js versions

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3644] opened 2020-02-11 23:00 UTC
## Problem description

When I try to export my project or download NW.js versions, I get a crash

## Attach a .c3p

n/a

## Steps to reproduce

1. Export to desktop
2. Click manage versions
3. Download a NW.js

## Observed result

Errors in the console
![image](https://user-images.githubusercontent.com/11213825/74287595-9b701300-4d2a-11ea-8001-6713ebdd011e.png)
Also a crash

## Expected result

it should work

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

Note the crash says 182 but I also tried on 186 and the bug still happened

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: error fetching https://downloads.scirra.com/c3-nwjs/v0.44.0/linux32.zip (0 ) @ Error: error fetching https://downloads.scirra.com/c3-nwjs/v0.44.0/linux32.zip (0 ) at XMLHttpRequest.l.onerror (https://editor.construct.net/r182/main.js:2:110824)
Stack: Error: error fetching https://downloads.scirra.com/c3-nwjs/v0.44.0/linux32.zip (0 ) at XMLHttpRequest.l.onerror (https://editor.construct.net/r182/main.js:2:110824)
Construct 3 version: r182
URL: https://editor.construct.net/r182/
Date: Tue Feb 11 2020 23:55:22 GMT+0100 (heure normale d’Europe centrale)
Uptime: 20.2 s

Platform information
Browser: Chrome
Browser version: 80.0.3987.87
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
C3 release: r182 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment] 2020-02-12 11:27
I just tried an NW.js export and it worked fine. The log shows errors downloading, are you sure it's not a problem with your Internet connection?

**Comment by skymen** [comment] 2020-02-12 13:46
I don't think it is. When I click on the link, it downloads just fine.

It might be an issue with local storage quotas, but I just have a few C3 versions and 2 NW.js versions in there (for a total of 200MB)

But it still produces a crash sometimes, or doesn't show any info when it doesn't crash, yet doesn't download anything, might be worth at least checking for that I guess :/

**Comment by AshleyScirra** [comment] 2020-02-17 12:39
I inserted failures in to the downloads to test this. I could not reproduce any crash on export - it correctly handled the failure and showed a "failed to export project" message. However I did find some cases where it didn't handle the failure in the NW.js version manager and could crash. Those cases should be fixed for the next release.

**Closed by AshleyScirra** 2020-02-17 12:39 UTC
