### ISSUE TITLE
Full Screen Scaling issues

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#2212] opened 2018-10-30 18:14 UTC
## Problem description

there are scaling and positioning issues on 123 build 

## Attach a .c3p

[Fullscreen Issues 3.zip](https://github.com/Scirra/Construct-3-bugs/files/2531062/Fullscreen.Issues.3.zip)

## Steps to reproduce

this file only partly demonstrate the issues with regard to fullscreen  there are more issues , especially around positioning of layers, when not in full screen

(edit) ive taken out the reference to high dpi as it is indeed happening on other devices.

press the numbers and observe scaling (always too big) and positioning issues. including warping of image when using low quality rendering

issues vary depending on the last resolution used

issue not present on previous builds 122 and below

**Comment by NetOneGames** [comment] 2018-10-31 14:18
Actually this does partially happen on 1080 screens as well if you from one resolution to another.  

eg o a 1080 screen

type 1 (cancel fullscreen) then 4 (1080 fullscreen centered)  then is scaled correctly

but type 2 then 4  (to go from 800x600 to 1080p)  then scale is all off

same seen with other reoslutions.

**Comment by AshleyScirra** [comment] 2018-11-01 13:01
It's not clear from your report which runtime this is happening with. I assume you mean only the C3 runtime?

I can reproduce an issue with the incorrect display in the C3 runtime simply by pressing the keys 2, 3, 4, 5 - the scaling is wrong after pressing 3, including being offset and having an inconsistent X and Y scale so it appears stretched. I can only see this happening in fullscreen mode; windowed mode is still fine. Does this match what you are seeing? I doubt this is anything device-specific, such cases are rare.

Please try to follow the bug report guidelines as closely as possible to avoid ambiguity.

**Comment by AshleyScirra** [comment] 2018-11-01 13:22
The noted issue ought to be fixed in the next release, let's verify when it's out.

**Comment by NetOneGames** [comment] 2018-11-01 14:01
Yea im sorry man , Im up to my neck in it at work (run up to christmas is allways massive crunch time in aerospace industry) so was just trying to bang it out... 
As far as I rememeber there are issues both C2 and C3 rt but in slightly differen ways. 
Re windowed.  Yes there are also issues in windowed mode but i did not have time to replicate this in the demo file.  Bascially some layers are duplicated and not scaling they are just sitting at native resolution in the top left corner, (this is what the video was showing in the closed issue)

**Comment by AshleyScirra** [comment] 2018-11-06 12:55
r124 is now out, can you check again?

**Comment by NetOneGames** [comment] 2018-11-06 16:51
Sadly no,  I havent checked the surface pro but on a 1080p laptop there are still issues. But less than before. The distortion issues swapping from one resolution to another appear to be resolved but the full screen scaling is still too big but not by as mich as before.  You should be able to see from the test file that you cant see the edges of the 1080 box on a 1080 screen.  and the 1664x702 box should be well within the borders of the 1920x1080 screen but is not it is scaled bigger than.

Also the layer scaling issues, (in my project) are still there but less aggressive than before. im thinking may be related to https://github.com/Scirra/Construct-3-bugs/issues/2257 as there is a tint effect over the whole layer and it does not  happen using high quality scaling. 
I will check the surface pro tonight but yea it looks like not quite resolved yet

**Comment by AshleyScirra** [comment] 2018-11-08 15:19
This might be related to #2274 which is fixed for the next release. Additionally the canvas size is set in CSS pixels, and that corresponds to physical pixels according to the devicePixelRatio, so it may be that a canvas size of 1920x1080 with a devicePixelRatio >1 does not fit in a physical 1920x1080 display, and that is currently by design. Anyway I can't see anything wrong with the example project here so I'm going to close this - if anything else is still wrong after the next release please file an issue and as always follow all the bug report guidelines, including the system info for any affected devices, since that covers devicePixelRatio.

**Closed by AshleyScirra** 2018-11-08 15:19 UTC
Labels: c3runtime, need info
