### ISSUE TITLE
(Chrome on Windows) Using the Color Picker near the edge of the screen will close/crash all Google Chrome windows you have open

### ISSUE THREAD

**Issue by FreshDopeGames** [Scirra/Construct-3-bugs#5004] opened 2021-08-05 04:16 UTC
## Problem description

Using the Color Picker near the edge of the screen will close/crash all Google Chrome windows you have open.

## Attach a .c3p

This happens with every construct file, use Kiwi Story as a test.

## Steps to reproduce

1. Open a project with an object created, or create an object in a fresh new project.
2. When selecting the color of that object using the object's color picker tool (eyedropper), move the tool to the edge of your monitor's screen.

## Observed result

All of the instances of Google Chrome on your computer will be closed.

## Expected result

Color picker stays open while cursor is on/near edge of screen.

## More details

This does not happen on Firefox because the color picker is a different tool type (doesn't have eyedropper)

**Affected browsers/platforms:** Chrome, Windows

**First affected release:** r251.2

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 92.0.4515.107
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 24
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
C3 release: r251.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 712 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2080 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5751)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by DiegoScirra** [comment] 2021-08-05 09:37
This seems to be an issue with Chrome, just tried out the feature on it own, outside of C3, and it also crashes the browser. You can try out the color input on it's own in the MDN documentation page, it will also crash when trying to use the eye dropper tool.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color

**Comment by AshleyScirra** [comment] 2021-08-05 09:52
I can't seem to reproduce this. @DiegoScirra - if you can, check if it reproduces in Canary, and if it does, please go ahead and file a Chrome issue.

**Comment by DiegoScirra** [comment] 2021-08-05 13:33
Yeah, happens in Canary too, you need to choose the eye dropper tool and just move the mouse around the screen for a little bit. It is clear that something is wrong because the close up the tool is showing  is not what is directly under the pointer.

**Comment by DiegoScirra** [comment] 2021-08-05 14:20
Filed a Chromium issue.

https://bugs.chromium.org/p/chromium/issues/detail?id=1237023

Closing this as it is out of our control.

**Closed by DiegoScirra** 2021-08-05 14:20 UTC
Labels: chrome, external
