### ISSUE TITLE
C3 Runtime & Pathfinding does not work together on Mobile Devices

### ISSUE THREAD

**Issue by Sanchopi** [Scirra/Construct-3-bugs#2132] opened 2018-10-10 16:21 UTC
## Problem description

Hello construct team,
I have a game that relies on "Pathfinding", but **Pathfinding does not work with the C3 Runtime on Mobile Devices**. In the preview window of the construct editor it runs fine. In Browsers too. But not on Mobile Devices.
 
If I switch to the old C2 Runtime, no problem. Pathfinding runs fine on Mobile ...
You can test it with the attached Project (just the pathfinding demo).

## Attach a .c3p

TheProject File:
[https://drive.google.com/open?id=1V3EA7TBi0UHGqI2q_KB2eMGWFRIQMedN](url)

## Steps to reproduce

1. Open the project & build a android APK (**C3 Runtime**, min Version: 5.0+ Lollipop, Debug APK)
2. Test the APK on a mobile device (you will only see a black screen)
_
3. Open the project & build a android APK (**C2 Runtime**, min Version: 5.0+ Lollipop, Debug APK)
4. Test the APK on a mobile device (the app works fine)

## Observed result

With the C3 Runtime I can only see a black screen on my mobile device after the default splash screen.
With the C2 Runtime I can see the app acting normal on my mobile device.

## Expected result

**The "Pathfinding" should work with the C3 Runtime on mobile devices. It does in the construct preview, but not in the final app on mobile.**

Maybe there is a Bug on the Build Service in connection with C3 Runtime? Because in the preview of the construct editor it works fine. The issue comes after the export with the Build Service.

## Affected browsers

**The problem only appears on mobile devices ...**
* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

## System details

<details><summary>View details</summary>

All android mobile devices.
Not sure on ios ...

</details>

**Comment by AshleyScirra** [comment] 2018-10-10 18:55
Duplicate of #2128

**Closed by AshleyScirra** 2018-10-10 18:55 UTC
