### ISSUE TITLE
Game is stuck when start play the timeline.

### ISSUE THREAD

**Issue by kimarutaGM** [Scirra/Construct-3-bugs#4885] opened 2021-06-11 07:19 UTC
## Problem description
 Game is stuck when start play the timeline.

## Attach C3P file.
[BugTimeLine Hierarchy.zip](https://github.com/Scirra/Construct-3-bugs/files/6636516/BugTimeLine.Hierarchy.zip)

## Steps to reproduce
1. Press B key 
2. Press F12 to see the Developer Console.
3. The Bug showing there.

## Observed result
After Press B key, game is stuck.
## Expected result
The Animation of the Timeline should be play properly.

## More details
Testing on Chrome Browser, 
Editor version : R251
Note: this not happen on Editor version: R241

**Comment by DiegoScirra** [comment] 2021-06-11 09:43
This is a duplicate of #4883

**Closed by DiegoScirra** 2021-06-11 09:43 UTC
Labels: duplicate
