### ISSUE TITLE
Variables window crash

### ISSUE THREAD

**Issue by elfwy-uwu** [Scirra/Construct-3-bugs#5261] opened 2021-11-23 14:14 UTC
## Problem description

There is a subsequence leading to crash in "Instance variables" window.

UPD: This also happens with _global variables_ window, may be somewhere else?

## Attach a .c3p

https://drive.google.com/file/d/1ow7pOth1hfD8PdJvKo7a5X_UgWrfU0NU/view?usp=sharing

## Steps to reproduce

1. Array -> Instance variables -> Add new instance variable
2. Change _Type_ or _Initial value_ and press Enter, go to step 4
3. or just press OK (no need to change values here)
4. Press Enter

## Observed result

Crash dialogue

## Expected result

No crash dialogue

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r271

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r272-2/main.js, line 935, col 65
Message: Uncaught TypeError: Cannot read properties of null (reading 'getComputedStyle')
Stack: TypeError: Cannot read properties of null (reading 'getComputedStyle') at new li.g.I.qd (https://editor.construct.net/r272-2/main.js:1557:273) at Function.xa.j (https://editor.construct.net/r272-2/main.js:935:44) at Function.Pa (https://editor.construct.net/r272-2/main.js:1609:39) at KP.g.I.RAc.Ua (https://editor.construct.net/r272-2/projectResources.js:2540:487) at KP.g.I.RAc.Kd (https://editor.construct.net/r272-2/main.js:1184:259) at xra.Kd (https://editor.construct.net/r272-2/main.js:1150:296) at HTMLDocument. (https://editor.construct.net/r272-2/main.js:262:253)
Construct 3 version: r272.2
URL: https://editor.construct.net/r272-2/
Date: Tue Nov 23 2021 18:32:48 GMT+0500 (Екатеринбург, стандартное время)
Uptime: 35.2 s

Platform information
Browser: Chrome
Browser version: 96.0.4664.45
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
C3 release: r272.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9676)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment] 2021-11-23 16:00
Thanks for the report. It looks like the fix for the previous issue #5149 accidentally caused this as a regression. Dialog focus is surprisingly complicated. Anyway it should be fixed in the next beta.

**Closed by AshleyScirra** 2021-11-23 16:00 UTC
