### ISSUE TITLE
text input object behaves incorrectly with Construct 3 vs Construct 2 in one particular way.

### ISSUE THREAD

**Issue by part12studios** [Scirra/Construct-3-bugs#4472] opened 2021-01-14 05:19 UTC
[text input bug.zip](https://github.com/Scirra/Construct-3-bugs/files/5812436/text.input.bug.zip)

I think this one is pretty easy to address.  to sum up..  the text input object behaves correctly in c2 but doesn't in c3 in one particular way..   

1. go to this link and you can see the C2 version of this build in action..   https://www.construct.net/en/free-online-games/multiplayer-chat-room-3494/play 

2. open the project attached and run it from C3.  When the text fills up and starts to push the text up.. rather than showing all the text, the latest inserted line is below the visible box.  in C2, this doesn't happen.  In C3 it does.  both are using the same basic code.  Perhaps it's the "scroll to bottom" that for some reason fails to do it

Some additional testing.  i thought i could push a new line AND a blank line below that, but in reality what happens is no matter how much content is pushed.. it's all obscured.. even if it's several lines pushed in the same event.  

I have a thread in construct forum offering additional screenshots to show the difference as well
https://www.construct.net/en/forum/construct-3/general-discussion-7/bug-text-input-object-need-157648#forumPost1031910

Thanks!
Caleb

**Comment by AshleyScirra** [comment] 2021-01-14 12:27
Minimal repro since none was provided: [issue4472.zip](https://github.com/Scirra/Construct-3-bugs/files/5814386/issue4472.zip)
I can reproduce a difference between C2 and C3 runtimes, will investigate.

**Comment by AshleyScirra** [comment] 2021-01-14 12:37
OK, should be fixed in next release.

**Closed by AshleyScirra** 2021-01-14 12:37 UTC

**Comment by part12studios** [comment] 2021-01-14 13:30
fantastic, thanks!  

You all are awesome.  

Sincerely,
Caleb
