### ISSUE TITLE
Plugin does not work in r174, but works in r171.3

### ISSUE THREAD

**Issue by KekGames** [Scirra/Construct-3-bugs#3466] opened 2019-11-07 00:55 UTC
## Problem description

The game doesn't work with Enhance plugin in r174, but works in r171.3. When I export the game - it only shows black screen (whether it goes through enhancement process, or if I just build debug version - the result is the same)

## Attach a .c3p

[ExampleEnhance.zip](https://github.com/Scirra/Construct-3-bugs/files/3817363/ExampleEnhance.zip)

## Steps to reproduce

1. Export apk
2. Run the game

## Observed result

Black screen

## More details
There also is a problem with minification with this plugin. It shows "failed to export project" error in r174, so it might be related to another bug report here.

**Affected browsers/platforms:** Android (didn't test on iOS)

**First affected release:** r174

**Comment by AshleyScirra** [comment] 2019-11-07 12:08
C2 runtime projects aren't exporting correctly in r174, closing as duplicate of #3462.

**Closed by AshleyScirra** 2019-11-07 12:08 UTC
