### ISSUE TITLE
Family behavior triggers work incorrectly in r174

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#3463] opened 2019-11-06 11:37 UTC
## Problem description

![image](https://user-images.githubusercontent.com/5744908/68294626-bb1ced00-00e4-11ea-8924-f87a93abb53e.png)

The **enemy** sprite is also using event 1, the **player** sprites code, without the enemy even being referenced! 😲

## Steps to reproduce

- Both Sprites share the same Family
- The _Family_ has the Platform behavior (so both sprites use the same one)

![image](https://user-images.githubusercontent.com/5744908/68294780-0e8f3b00-00e5-11ea-9f9e-dcf54a2d4c70.png)

## Attach a .c3p

[on_landed.zip](https://github.com/Scirra/Construct-3-bugs/files/3814195/on_landed.zip)

## Observed result

The enemy and the player are both creating puffs when they land on the ground!

## Expected result

The enemy should not be using the player's events, without being told to do so!

## More details

I'm not sure when it started happening, but at least r174

I use the desktop beta

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

Thank you ❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️

**Comment by shortercode** [comment] 2019-11-06 11:42
Ah interesting. There was a change to how triggers work for behaviours recently, I expect this is regression caused by that. Going to assign to @AshleyScirra to review.

**Comment by AshleyScirra** [comment] 2019-11-06 13:24
It looks like a regression in r174 caused by #3412 which completely overhauled how behavior triggers work. Will aim to get a fix in the next release.

**Comment by ChadoriRebornXD** [comment] 2019-11-06 14:19
I'm thankful this is reproducible with the other behaviors! Thanks for reporting!

**Comment by viet31781** [comment] 2019-11-08 02:35
I notice the same problem, so I have to go back to r173, but I think the working speed of r174 is awesome, hope the problem will be fixed soon, thank you @AshleyScirra :)

**Comment by AshleyScirra** [comment] 2019-11-11 11:31
Should be fixed in the next release.

**Closed by AshleyScirra** 2019-11-11 11:31 UTC
