### ISSUE TITLE
Plugin googleplay

### ISSUE THREAD

**Issue by ERAgames777** [Scirra/Construct-3-bugs#993] opened 2017-11-07 10:45 UTC
## Problem description

GooglePlay plugin works only in web format.

## Attach a .c3p

n / a

## Steps to reproduce

The plugin works well when you start the Web page.

## Observed result

When you open the android smartphone plug does not want to work, it turns out such:
**403. That’s an error.

Error: disallowed_useragent

This user-agent is not permitted to make an OAuth authorization request to Google as it is classified as an embedded user-agent (also known as a web-view). Per our policy, only browsers are permitted to make authorization requests to Google. We offer several libraries and samples for native apps to perform authorization requests in the browser.**

## Expected result

Please create a separate googleplay plugin for the android device.

## Affected browsers

* Chrome: yes
* Firefox: no
* Edge: no
* Safari: no

**Comment by AshleyScirra** [comment] 2017-11-07 11:30
Duplicate of #452

**Closed** 2017-11-07 13:42 UTC
Labels: duplicate
