### ISSUE TITLE
Lock/unlock layers by mouse click not working since r229

### ISSUE THREAD

**Issue by UbruPro123** [Scirra/Construct-3-bugs#4421] opened 2020-12-16 13:04 UTC
## Problem description
After last beta version r229 there is bug that you cannot lock/unlock layers by clicking on icon.

## Steps to reproduce
Open any project and click (by mouse) on lock icon in layers -> nothing happens.

## Expected result
After clicking on that lock icon, layer attribute "Locked" should switch (lock/unlock) 

## More details
Simulating this bug in different browsers and with different project, it must be global bug.
Bug in beta version r229

![bug](https://user-images.githubusercontent.com/44697344/102351895-76ca7480-3fa7-11eb-9974-ee302cb23b7e.png)

**Comment by AshleyScirra** [comment] 2020-12-16 15:04
Duplicate of #4420

**Closed by AshleyScirra** 2020-12-16 15:04 UTC
Labels: duplicate
