### ISSUE TITLE
Cannot remove "!" from file name when saving to Google Drive

### ISSUE THREAD

**Issue by TGeneDavis** [Scirra/Construct-3-bugs#61] opened 2017-04-12 15:16 UTC
## Problem description

Construct 3 crashes when attempting to place cursor in filename box when saving to Goolge Drive. Cannot remove "!" from file name when saving to Google Drive

## Attach a .c3p

[SkiPenguinSki.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/917027/SkiPenguinSki.c3p.zip)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Select Save to Google Drive
2. Attempt to remove the second "!" from the file name by selecting just after it and pushing delete
3. Watch Construct 3 turn red and die.

## Observed result
Construct 3 dies due to a null pointer

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*
I want to remove the two "!" from the file name before saving to Google Drive.

## Affected browsers

* Chrome: yes
Only tried Chrome

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r17/main.js, line 2, col 210681
Message: Uncaught TypeError: Cannot read property 'toLowerCase' of null
Stack: TypeError: Cannot read property 'toLowerCase' of null at Function.ǃE.ǃbTE (https://editor.construct.net/r17/main.js:2:210681) at ǃE.ǃv.ǃEgd.ǃJU (https://editor.construct.net/r17/main.js:50:40651) at window.addEventListener.te (https://editor.construct.net/r17/main.js:50:40118)
Construct 3 version: r17
URL: https://editor.construct.net/
Date: Wed Apr 12 2017 09:05:35 GMT-0600 (MDT)
Uptime: 83 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M395X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment] 2017-04-12 16:45
closing as duplicate of [#60](https://github.com/Scirra/Construct-3-bugs/issues/60)

the cloud/local browser save dialog has a broken text input in r17

**Closed by shortercode** 2017-04-12 16:45 UTC
