### ISSUE TITLE
Assertion failure: empty object list to destroy

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#1359] opened 2018-03-10 13:45 UTC
## Problem description

In my project, when i switch from one scene to another and then back to the first one again, i get these error messages:

![image](https://user-images.githubusercontent.com/30116964/37242905-43d05238-2471-11e8-9bc9-51c08b3194f4.png)
![image](https://user-images.githubusercontent.com/30116964/37242907-49698138-2471-11e8-927b-efb23f885305.png)
![image](https://user-images.githubusercontent.com/30116964/37242910-4f109072-2471-11e8-95b0-df2ef78db626.png)

EDIT:

I tried to roll back to r85 but got this error message when trying to open the project. Don't know if it has anything to do with it but i thought i'd post it anyway:

Error report information
Type: unhandled rejection
Reason: Error: invalid property id 'enable-bbcode' @ Error: invalid property id 'enable-bbcode' at f.ǃBu (https://editor.construct.net/r85/main.js:63:222015) at f.ǃnBS (https://editor.construct.net/r85/main.js:63:223708) at f.ǃWo (https://editor.construct.net/r85/main.js:63:233594) at o.ǃny_ (https://editor.construct.net/r85/main.js:63:273432) at a.ǃnya (https://editor.construct.net/r85/main.js:63:257845) at Object.ǃf.ǃDu [as ǃBYK] (https://editor.construct.net/r85/main.js:63:257001) at t (https://editor.construct.net/r85/main.js:2:275481) at n (https://editor.construct.net/r85/main.js:2:275267)
Stack: Error: invalid property id 'enable-bbcode' at f.ǃBu (https://editor.construct.net/r85/main.js:63:222015) at f.ǃnBS (https://editor.construct.net/r85/main.js:63:223708) at f.ǃWo (https://editor.construct.net/r85/main.js:63:233594) at o.ǃny_ (https://editor.construct.net/r85/main.js:63:273432) at a.ǃnya (https://editor.construct.net/r85/main.js:63:257845) at Object.ǃf.ǃDu [as ǃBYK] (https://editor.construct.net/r85/main.js:63:257001) at t (https://editor.construct.net/r85/main.js:2:275481) at n (https://editor.construct.net/r85/main.js:2:275267)
Construct 3 version: r85
URL: https://editor.construct.net/r85/
Date: Sat Mar 10 2018 14:59:33 GMT+0100 (Mitteleuropäische Zeit)
Uptime: 36.3 s

Platform information
Browser: Chrome
Browser version: 64.0.3282.186
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
C3 release: r85
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 580 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
## Attach a .c3p

I will send a minimized .c3p to support@scirra.com directly, since it's a commercial project and i can't post it publicly.

## Steps to reproduce

1. Run the game
2. Press Spacebar to enter the cabin
3. After the dialogue in the cabin, which you skip with space again, press the left arrow key until the action shows "leave" and press space again. The scene should return to the first one.
4. Game crashes and error messages above are shown.

## Observed result
Chrome gives me the stated error message.

## Expected result
Preferably no crashing ;)

## Affected browsers
Chrome
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 64.0.3282.186
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
C3 release: r89 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 202 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 580 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment] 2018-03-12 13:34
I have received the project via email. However I cannot reproduce any issue. At step 3 I don't see any dialogue in the cabin: just a dark room and nothing happens.

Please note such reports are usually significantly harder to deal with - the bug report guidelines cover making a minimal repro, and what to do if you don't want to share your project. These are intended to avoid problems such as this and makes it far more likely we can fix the problem.

**Comment by AshleyScirra** [comment] 2018-03-12 13:35
The error looks similar to this C2 report so we may be able to fix it based on that: https://www.scirra.com/forum/uncaught-assertion-failed_t201553

**Comment by AshleyScirra** [comment] 2018-03-12 13:52
I found a fix for the linked report so assuming it is the same problem this should be fixed in the next release.

**Comment by joelmayer87** [comment] 2018-03-12 13:54
Hello @AshleyScirra Ashley, sorry about that, it should be as easy as just pressing space right when the game starts to go into the cabin, then go to the left and just leave the cabin again. That's when the error happens. I unfortunately don't know how to produce a minimal repro of this error since i gather it could be all kind of things but in case you still want any, i can try but i think it's not as easy as just switching from one room to another and then back again (which is the only case where this happens)...

**Comment by joelmayer87** [comment] 2018-03-12 14:23
Ooh woah seems we commented again almost at the same time, didn't see your last comment. Looks like about the same error and i have the feeling i didn't experience it before the latest update. Something about Box2D physics so might very well be that, i'll check the next beta, thanks ;)

**Comment by AshleyScirra** [comment] 2018-03-12 15:28
r90 is out now, could you check to see if it resolves the issue?

**Comment by joelmayer87** [comment] 2018-03-12 15:39
Hi Ashley i can't really test it because i think i know, why the game didn't play properly for you: r90 resets rotations on objects/sprites on the screen. Since i got solid objects on the sides of the screen, it rotated them 90 degrees so the character got stuck within the solid and couldn't move via the MoveTo plugin. I already opened a new bug report.

**Comment by joelmayer87** [comment] 2018-03-12 16:38
@AshleyScirra I'm happy to report, the bug seems to have been fixed ;) No more crashes. Thanks!

**Comment by AshleyScirra** [comment] 2018-03-12 16:40
Great, thanks for confirming.

**Closed by AshleyScirra** 2018-03-12 16:40 UTC
