### ISSUE TITLE
Keep logged in doesn‘t work on IOS (ipad)

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#3864] opened 2020-05-16 13:20 UTC
## Problem description

Not a huge issue but somewhat annoying: „Keep me logged in“ doesn‘t work.

https://youtu.be/3I0ocJtxF7s

## Steps to reproduce

1. Login and tick the „keep login“
2. reload

## Observed result

Not logged in anymore

## Expected result

Stay logged in

## More details

**Affected browsers/platforms:** 
Chrome & Safari

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome for iOS
Browser version: 81.0.4044.62
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: iOS
Operating system version: 13.3
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPad; CPU OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/81.0.4044.62 Mobile/15E148 Safari/604.1
C3 release: r199 (beta)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS containment is not supported. Editor performance may be significantly degraded.
Service Workers are not supported. Construct 3 cannot be used offline in this browser.
The <dialog> element is not supported. A polyfill is in use.
The Clipboard API is not supported. Some clipboard features may be unavailable.
Web Animations are not supported. Animations are disabled.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Apple Inc.
Renderer: Apple GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions:

EXT_blend_minmax
EXT_sRGB
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_depth_texture
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by AshleyScirra** [comment] 2020-05-17 11:39
This is a duplicate of #3390. It's a problem with Safari I'm afraid and is difficult to work around. See that issue for more details.

**Closed by AshleyScirra** 2020-05-17 11:39 UTC
Labels: duplicate

**Comment by Wackytoaster** [comment] 2020-05-17 12:06
Oh, well that's a bummer. But as I said, luckily just inconvenient and not breaking. Have a nice Sunday :]
