### ISSUE TITLE
Physics collision is offset when using negative width/height (to invert a sprite)

### ISSUE THREAD

**Issue by johnsmith27** [Scirra/Construct-3-bugs#6434] opened 2023-01-27 15:59 UTC
## Problem description
Hi,

If using negative width/height on a sprite with physics, the collisions still use the positive values (with either bounding box or collision polygon selected).

## Attach a .c3p

[phys_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/10520597/phys_bug.zip)

## Steps to reproduce

1. Create a sprite with a non centered origin point, and physics behavior.
2. Invert the sprite using negative height / width

## Observed result

The sprite physics collision still use the positive values of the width/height.

## Expected result

The collisions should be inverted as well

## More details

**Affected browsers/platforms:** Chrome

Worked in Stable r317.2 but broke in r327

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2023-02-06 15:39
Thanks for the report, it should be fixed in the next beta. It looks like it was a regression caused in r318 by the fix for #3821.

**Closed by AshleyScirra** 2023-02-06 15:39 UTC
