### ISSUE TITLE
App Crashing

### ISSUE THREAD

**Issue by 8bitThirsty** [Scirra/Construct-3-bugs#370] opened 2017-05-26 14:09 UTC
## Problem description
My application crashes a lot.  Always in the sprite editor doing a variety of things.  Should I paste the crash reports every time into this ticket with a brief description of what I was doing?   

I had a problem previously with a corrupted image file but I deleted the sprite and hadn't come across many more issues till recently.  The steps below are reproducible in the file I uploaded and I am working around them but wanted to open the reports to help solve this issue while in beta still.

## Attach a .c3p
[HWAS.zip](https://github.com/Scirra/Construct-3-bugs/files/1032077/HWAS.zip)

## Steps to reproduce

1. Double click the Lava sprite
2. Delete the first two frames of the image

## Observed result
App crashed
*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>
Error report information
Type: unhandled exception
File: https://editor.construct.net/r31/main.js, line 61, col 198915
Message: Uncaught Error: animation frame has no content
Stack: Error: animation frame has no content at oe.ǃB_W (https://editor.construct.net/r31/main.js:61:198921) at oe.ǃMD (https://editor.construct.net/r31/main.js:61:200827) at a.ǃUc.ǃzJd (https://editor.construct.net/r31/plugins/sprite/plugin.js:1:5945) at ǃB.ǃ$t.ǃzJx.ǃB.ǃ$t.f [as ǃzrv] (https://editor.construct.net/r31/plugins/sprite/plugin.js:1:4089) at ǃB.ǃ$t.ǃzfF (https://editor.construct.net/r31/main.js:2:296529) at ǃB.ǃ$t.ǃzfJ (https://editor.construct.net/r31/main.js:2:296657) at ǃzfa (https://editor.construct.net/r31/main.js:2:296190)
Construct 3 version: r31
URL: https://editor.construct.net/
Date: Fri May 26 2017 10:06:23 GMT-0400 (Eastern Daylight Time)
Uptime: 113.3 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.71
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.71 Safari/537.36
C3 release: r31

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment] 2017-05-26 15:52
This might be a duplicate of #350. 

Please check the next release to see if this is still happening.

**Comment by AshleyScirra** [comment] 2017-05-30 11:36
r32 is out, please verify if fixed!

**Comment by 8bitThirsty** [comment] 2017-05-31 17:21
Got another crash in the sprite editor.  It crashed twice in a row the first time it completely froze and wouldn't let me click the buttons to copy the crash report or save my work.  Then I opened the project and attempted to load images more images into an already created animation.  The issue was with the "Back" animation on the Sagan sprite.

[Bitmen.zip](https://github.com/Scirra/Construct-3-bugs/files/1042375/Bitmen.zip)


Error report information
Type: unhandled exception
File: https://editor.construct.net/r32/main.js, line 2, col 202615
Message: Uncaught Error: animation frame has no content
Stack: Error: animation frame has no content at h.ǃiRI (https://editor.construct.net/r32/main.js:61:188769) at h.ǃcf (https://editor.construct.net/r32/main.js:61:192577) at ǃNr.ǃlsd.ǃNr.ǃJV (https://editor.construct.net/r32/main.js:71:36945) at ǃNr.ǃlsd (https://editor.construct.net/r32/main.js:71:44908) at Function.ǃi.ǃa (https://editor.construct.net/r32/main.js:2:202594) at Function.ǃMW (https://editor.construct.net/r32/main.js:71:320594) at Function.ǃlML (https://editor.construct.net/r32/main.js:71:320464) at Function.s.ǃiBu.ǃlAG (https://editor.construct.net/r32/main.js:71:325752) at a.ǃlCi.ǃJh (https://editor.construct.net/r32/main.js:71:239337) at Array.ǃnu (https://editor.construct.net/r32/main.js:71:232706)
Construct 3 version: r32
URL: https://editor.construct.net/
Date: Wed May 31 2017 13:17:16 GMT-0400 (Eastern Daylight Time)
Uptime: 50.8 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.71
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.71 Safari/537.36
C3 release: r32

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by DiegoScirra** [comment] 2017-06-02 09:21
@8bitThirsty

Can you make a new issue with the second crash report that you got?

**Comment by 8bitThirsty** [comment] 2017-06-02 11:02
@DiegoScirra Should I close this one then?  I opened  #423 but I didn't have any extra details to add.

**Comment by DiegoScirra** [comment] 2017-06-02 11:40
If the original bug is already fixed, this can be closed. Have you tried that out?

**Comment by 8bitThirsty** [comment] 2017-06-02 14:15
I opened the second issue which has essentially the same steps to reproduce and not consistently reproducible.  I am unsure why you wanted me to open a new issue but from my point of view this and #423 are the same.

**Closed** 2017-06-02 16:10 UTC
Labels: need info
