### ISSUE TITLE
[r27] crash after cloning sprite

### ISSUE THREAD

**Issue by M1thrill** [Scirra/Construct-3-bugs#222] opened 2017-05-16 15:16 UTC
## Problem description

Cloning a sprite which has a behaviors from family will cause C3 to crash. 

[cloneTest.zip](https://github.com/Scirra/Construct-3-bugs/files/1004934/cloneTest.zip)

## Steps to reproduce

1. right click on sprite
2. select "clone object type"
3. left click anywhere on layout

## Observed result

"Ooop, something went wrong" -dialog box pop up and C3 crashes.

## Expected result

Be able to clone sprite with behaviors from families.

## Affected browsers

* Chrome: yes
* Firefox: untested
* Edge: untested
* Safari: untested

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: e is not defined @ ReferenceError: e is not defined at Promise.all.then.G (https://editor.construct.net/r27/components/editors/layoutView/layoutView.js:1:30290) at 
Stack: ReferenceError: e is not defined at Promise.all.then.G (https://editor.construct.net/r27/components/editors/layoutView/layoutView.js:1:30290) at 
Construct 3 version: r27
URL: https://editor.construct.net/
Date: Tue May 16 2017 18:04:40 GMT+0300 (EEST)
Uptime: 2032.9 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.9_5
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 650M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 63.375
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2017-05-16 15:58
Looks like a duplicate of #197.

**Closed by AshleyScirra** 2017-05-16 15:58 UTC
