### ISSUE TITLE
Part 3: Physics bug when velocity is 50 or less

### ISSUE THREAD

**Issue by awb11** [Scirra/Construct-3-bugs#3906] opened 2020-06-02 02:22 UTC
## Problem description

Why do you assume that 1.0f has to be that number for a good reason. Box2d gave the option to change it for a good reason. Especially is so many people are reporting that changing it to 0.0f fixes the inelasticity issue. 

You have made changes that broke games before, because it was the right thing to do. Most recently you correctly made Physics frame-rate independent. This made a significant difference as to how the ball bounces. Users had to adjust how the ball bounces in the event sheet. This broke more games than correcting the less than 50 velocity problem. Even though this broke games, this clearly the right decision. 

I understand that changing the box2d settings might affect some games. There are probably some people that have designed games so that the ball will stop bouncing if velocity is less than 50. 

However, if a ball needs to become inelastic if velocity is less than 50,  this can be easily done using the event sheet. This means you would not need to support both cases. 

The person designing the game should be able to set when the ball should not be elastic. If billiards can be created using other game engines that use Box2d that means b2_velocityThreshold  was adjusted by them without issues. Why would you want to limit the Construct game engine this way? 

I have attached a new C3P file that hopefully will make it easier to see as to how big this problem actually is. I have 2 layouts showing the extent of the issue and I hope that this will be taken seriously. 

## Attach a .c3p

https://drive.google.com/file/d/1B8Ho0EQO5Icg5kT3w6StVm5t2MT5P8Tb/view?usp=sharing

**Comment by AshleyScirra** [comment] 2020-06-02 11:39
Duplicate of #3900. Please don't keep re-filing issues. I explained why this is a difficult problem to deal with - in particular that currently this value cannot be changed after build & release - and how there ought to be a change to Box2D to support it. Insisting we take action anyway goes against the [Forum & Community guidelines](https://www.construct.net/en/forum/general/open-topic-33/forum-community-guidelines-141035) and further action may be taken unless you co-operate.

**Closed by AshleyScirra** 2020-06-02 11:39 UTC
Labels: duplicate
