### ISSUE TITLE
LayerScale below 0.01 makes sprites dissapear

### ISSUE THREAD

**Issue by kerata57** [Scirra/Construct-3-bugs#2596] opened 2019-02-09 09:57 UTC
## Problem description

When LayerScale goes below 0.01, all sprite objects on the layer dissapear.
This happens from r132 beta to r136 stable.

On r131 stable this did not happen : https://editor.construct.net/r131/

## Attach a .c3p

[bug_layout_scaling_r136.zip](https://github.com/Scirra/Construct-3-bugs/files/2847685/bug_layout_scaling_r136.zip)

## Steps to reproduce

1. Preview the attached project; On-start: layer will start zooming out.
2. After 2 seconds the sprites dissapear (around scale 0.01 )
3. You can use your mousewheel to zoom the layer manually to see the sprites re-appear

## Observed result

Sprite's dissapear when LayerScale is lower than 0.01

## Expected result

If sprites are big enough to been seen, they should stay visible, independent from LayerScale value.

## First affected release

r132 (first beta)
r136 (first stable)

## Affected browsers/platforms

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r132 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.9 gb
Storage usage (approx): 6.2 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-02-11 16:14
The problem is the new Z elevation uses true 3D Z positioning, which also means there's now a view frustum with a far Z clipping plane. Scaling the layout is now done by moving the camera on the Z axis, so a small scale means the camera is literally further away, and this means in extreme cases the far plane moves in front of otherwise visible objects.

We could fix this by making the far plane even further away, but this might run in to floating point precision issues and cause other artefacts. Also, using an extremely large Z distance would make it more difficult to later implement more 3D features if we ever wanted to do that, since it substantially decreases the precision of a depth buffer.

So my main question is: why is this important to your game? The example project is kind of bizarre. What are you doing that requires such extremely tiny layout scales, and are you sure there is no alternative way of getting the same effect?

**Comment by kerata57** [comment] 2019-02-12 08:50
Hey Ashley, thanks for the fast reply. 

My 'game' is an array of stars where you can zoom in to planets and buildings on the planets. And travel between them. (0.0003 is the current minimal scaling). This gives a feeling of scale to the game and feeling of insignificance to the player. I make the sprites invisible when they get too far.

I could use 3 layers and switch between them when they reach 0.01 scale. This will use more objects and thus more hardware resources..

If I understand correctly, you now move the camera in 3D space when scaling the layer. And if you move too far, objects reach a hard draw-distance limit (to protect the user).

You say you are planning to implement more 3D features, can I expect a parameter for this draw-distance limit in the future ?

Thanx again.

Greetz, ozz

**Comment by AshleyScirra** [comment] 2019-02-12 12:07
We do not currently have any plans to add more 3D features. However we don't want to add extra hurdles in the way in case we decide we want to do it in future. We have to impose some fixed limit, and the higher the limit, the more problematic it could be - both immediately and in future. I'd prefer not to change the existing limit if possible, especially since covering the extent you mentioned (minimal scale of 0.0003) would be an extreme change in the engine.

An alternative approach could also be to just use a fixed scale and move objects using Z elevation, which will achieve a similar visual effect without relying on extreme scales. The maximum Z distance will still apply, but it seems you should be able to use reasonably sized objects - for example your example project uses objects sized 22387 x 17942, which is truly extreme - using a normal sized object and Z elevating it closer instead will produce a similar visual effect with much more reasonable sizes and distances in the engine. Then by the time a normal sized object reaches the maximum Z distance, it is probably smaller than a pixel anyway, so shouldn't be too noticable a step. Finally another alternative could be to use your own suggestion of using multiple layers.

Based on the technical issues involved and the fact the project uses an extreme setup that is rare and should be possible to be redesigned more reasonably, closing as wontfix.

**Closed by AshleyScirra** 2019-02-12 12:07 UTC
Labels: difficult, need info

**Comment by kerata57** [comment] 2019-02-12 12:16
Thnx. Max size of my objects in the real game is 6400px, the example was a bit overkill. I'll try around with Z elevation in combination with scaling to produce the same effect Thanks for the advice.
