### ISSUE TITLE
Multiplayer and GooglePlay plugin bug in AndroidStudio Export

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-3-bugs#3752] opened 2020-04-07 18:19 UTC
## Problem description
When the google play plugin is added, the multiplayer looses the capability to comunicate with the server.

## Attach a .c3p

Minimal Project: https://drive.google.com/open?id=1GJpU903hhNjryvWOUHAoRqXvj6vGQtIT

## Steps to reproduce

1. Export the project for android studio
2. Open and look at the android manifest (it doesnt have the internet and network permission)
3. Export and test

## Observed result

Multiplayer is blocked

## Expected result

Multiplayer not blocked

## More details

It is fixed if in the android maniffest you add the next two permissions:
```
`<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="1000000" android:versionName="1.0.0.0" package="com.multiplayer.app" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <meta-data android:name="com.google.android.gms.games.APP_ID" android:value="@string/app_id" />
    </application>

<!--THIS TWO-->   
 <uses-permission android:name="android.permission.INTERNET" />
 <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<!--ONLY NEEDED-->   
 <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
</manifest>
`
```
The multiplayer works fine without the googleplay plugin.
The multiplayer works fine in android 7 and lower. This problem jumps in android 8.1 and up (only tested in 3 phones)

**Comment by AshleyScirra** [comment] 2020-04-08 10:44
This is still confusing. In the other issue thread you said this only happens with release APKs. Is that correct or did you test again with a debug APK and reproduce it there? Please ensure all important details like this are mentioned in the initial report, otherwise the same thing will happen and it'll end up so confusing it's hard to get anywhere.

**Comment by kingpirux** [comment] 2020-04-09 14:21
There was a time that the debug worked and the release dont, but when you told me that it was working i tryed again and you were right... But that could had been something else since i was always testing with my full project. So now i get to calm down, and was able to do this minimal version were the google play plugin jumps to be the one making this.
 Right now, the issue can be tested in debug and release.

**Comment by AshleyScirra** [comment] 2020-04-14 16:51
I still can't reproduce this. I opened the provided project, exported a Debug APK using Construct's build service, which you appear to have said does reproduce the issue ("Right now, the issue can be tested in debug and release"), ran it on a Pixel 3 running Android 10, and it worked fine. Besides the issue as stated doesn't make sense: adding the Google Play plugin shouldn't be retracting permissions or anything like that, generally these plugins only add new permissions that they need. So there's probably something else going on. It's hard to do anything about this without a way to reproduce the issue though, and it still seems unclear when exactly this happens, on which devices, and with which export options.

**Comment by kingpirux** [comment] 2020-04-15 15:25
> I still can't reproduce this. I opened the provided project, exported a Debug APK using Construct's build service, which you appear to have said does reproduce the issue ("Right now, the issue can be tested in debug and release"), ran it on a Pixel 3 running Android 10, and it worked fine. Besides the issue as stated doesn't make sense: adding the Google Play plugin shouldn't be retracting permissions or anything like that, generally these plugins only add new permissions that they need. So there's probably something else going on. It's hard to do anything about this without a way to reproduce the issue though, and it still seems unclear when exactly this happens, on which devices, and with which export options.

im so sorry! i forgot to explain this is for the android studio export. that's why i talk about the andriodmanifest fix

**Comment by AshleyScirra** [comment] 2020-04-15 15:36
So it doesn't work if you build with Android Studio, but does if you use Construct's build service?

That sounds like it may be a problem with your Android Studio configuration - AFAIK, both Android Studio and Construct's build service use the same build system.

**Comment by kingpirux** [comment] 2020-04-15 20:16
didnt try with the normal export, since i need android studio for my mine project. ill try to do some more test tomorrow and report back.

**Comment by kingpirux** [comment] 2020-04-28 14:49
Sorry for the delay, i tested with the construct debug export and the problem is present.
Tested on Nokia 3:
![imagen](https://user-images.githubusercontent.com/6506303/80501877-57aea200-8946-11ea-9929-77618b521a9d.png)

**Comment by kingpirux** [comment] 2020-04-28 15:16
tested with export options:
- adding wss://*/* to the permissions
- with compression and without compression
- signed debug and release

**Comment by AshleyScirra** [comment] 2020-04-28 15:38
That's odd - AFAIK the ERR_NAME_NOT_RESOLVED error is a DNS error meaning it wasn't able to look up the multiplayer.scirra.com domain. I would guess it's still something to do with the URL whitelist somehow (despite efforts to add it to the whitelist). I'll take another look with a signed debug APK soon.

**Comment by kingpirux** [comment] 2020-05-02 13:34
any idea why it's fixed if you add the internet permission to the android manifest?

**Comment by AshleyScirra** [comment] 2020-05-20 12:00
I tried with a signed debug APK. It still worked fine.

I can't see any evidence on my end so far that this permission is really required. Unless I can find a way to reproduce the issue, I don't think we'll get anywhere.

**Comment by kingpirux** [comment] 2020-05-21 13:35
can you try with an android 9 or 7.1? those are mine

**Comment by AshleyScirra** [comment] 2020-05-22 15:22
The only other device I have available for testing while working from home is a Samsung tablet (SM-T515) running Android 9. The signed debug APK still works fine.

I've tried a number of combinations and nothing I've tried reproduces the problem. My best guess at this point is it is not related to Construct. If it was, I should have been able to reproduce it in at least one of the cases I've tried (including Android 9 with a signed debug APK). I would guess this is related to the specific device or manufacturer, or some kind of system-level configuration, or some kind of firewall/filtering/protection app.

Without any way to reproduce this on a range of devices, nor any indications the problem is actually anything to do with Construct, I don't see any way forwards here so closing this issue. If you can find a reliable way to reproduce this which you think is related to the way Construct is configuring the app then please file again, but please do make sure you provide clear, concise information and follow all the guidelines, since there was already quite some confusion and delay in dealing with this issue.

**Closed by AshleyScirra** 2020-05-22 15:22 UTC
Labels: can't reproduce

**Comment by kingpirux** [comment] 2020-05-23 18:07
okey, since my fix with the internet permission still working for me i dont have issues. But i will try to find out what is going on with more detail when i get the time...

**Comment by kingpirux** [comment] 2020-09-01 21:40
just leaving here a tip if someone else has the same problem, this also fix the photon plugin problem when play 4g and wifi at the same time. 
ALSO needed for the browser plugin to detect if there is internet connection.
