### ISSUE TITLE
C3 runtime doesn't work with Use Worker

### ISSUE THREAD

**Issue by matheusgrieger** [Scirra/Construct-3-bugs#2225] opened 2018-11-01 19:54 UTC
## Problem description

When using C3 Runtime combined with Use Worker option, I cannot run on mobile with Remove Preview or even by opening the editor directly in my phone. Tested with C3 demos and they apparently work just fine. Also tested with C2 runtime and it works with my project.

Had a forum post documenting this some time ago:

https://www.construct.net/en/forum/construct-3/how-do-i-8/getting-error-when-previewing-138722

## Attach a .c3p

[SkatingTown.zip](https://github.com/Scirra/Construct-3-bugs/files/2539845/SkatingTown.zip)

## Steps to reproduce

1. Enable Remote Preview
2. Open in mobile browser

## Observed result

* Black screen on mobile;
* Connected client hangs in `Loading scripts...`
  ![screenshot from 2018-11-01 16-30-15](https://user-images.githubusercontent.com/6992464/47875548-93ba8280-ddf5-11e8-93a6-60b5d1e8bc4a.png)
* Upon inspecting my mobile browser tab from Chrome DevTools, I see that `workermain.js` resulted in a 404 (as noted in the forum post)
  ![screenshot from 2018-10-18 14-20-21](https://s1.construct.net/images/v554/uploads/articleuploadobject/0/images/7411/screenshot%20from%202018-10-18%2014-20-21.png)

## Expected result

Expected to see the simple Play Game button I made to test.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details (desktop)</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Linux
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r123 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.3 gb
Storage usage (approx): 7.4 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) Haswell Mobile 
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

<details><summary>View details (mobile)</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.80
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Android
Operating system version: 8.1.0
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2.375
Logical CPU cores: 8
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Linux; Android 8.1.0; ONEPLUS A5010) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.80 Mobile Safari/537.36
C3 release: r123 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.4 gb
Storage usage (approx): 58 mb (0.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2 is currently disabled on Android due to reports of GPU driver bugs.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Qualcomm
Renderer: Adreno (TM) 540
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1023
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
EXT_sRGB
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2018-11-02 18:19
Looks like remote preview doesn't work with "Use worker" enabled (nothing mobile specific, reproduces on desktop). Should be fixed in the next release.

**Closed by AshleyScirra** 2018-11-02 18:19 UTC
