### ISSUE TITLE
Particles Z elevation Bugged behavior, when some instance are on&off-screen

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2599] opened 2019-02-11 07:37 UTC
## Problem description

When you have multiple instances of same particle, you use z elevation and some instances are on-screen and some off-screen, then particles show bugged behavior.

## Attach a .c3p
[ParticleChangesPos_Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2850132/ParticleChangesPos_Bug.zip)

## Steps to reproduce

1.Start example, preview. See particle inside viewport with 10 Z elevation changes Position
2.Change z 0 and z 10 particle positions, see particles do not come into viewport smoothly, instead they spawn. Change outside particle range from screen, sometimes particles spawn like x +100 - literally out of nowhere.

## Observed result
When some instances of particles are outside and some inside, they start to bug.

## Expected result
No bug

## First affected release
From beginning r132, when z elevation was added.

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.96
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36
C3 release: r136 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 966 mb (7.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-02-12 12:58
I can reproduce step 1, but I cannot reproduce step 2, because you do not say where to move the objects to. It would be useful to provide a separate project for that case so I don't have to guess where you moved them and can see exactly what you've done.

**Comment by AshleyScirra** [comment] 2019-02-12 13:37
OK, first case should be fixed for the next release. Can't reproduce the second case but if you can provide a project I could verify it.

**Closed by AshleyScirra** 2019-02-12 13:37 UTC

**Comment by SnipG** [comment] 2019-02-12 16:10
I ment swap their positions.

**Comment by AshleyScirra** [comment] 2019-02-12 17:54
Both look like they're working OK now as well. The problem was using particles at different Z elevations did not render at the correct Z elevation, and that should be fixed.
