### ISSUE TITLE
Using multiple tilemaps can crash the editor

### ISSUE THREAD

**Issue by KekGames** [Scirra/Construct-3-bugs#4072] opened 2020-07-27 11:23 UTC
## Problem description

If you try to copy-paste multiple different tilemaps (or duplicate a layout with these tilemaps) - editor will use a lot of CPU power and can even crash. Also, saving/loading this project uses a lot of CPU and can also crash the editor.

## Attach a .c3p

[TilemapCrash.zip](https://github.com/Scirra/Construct-3-bugs/files/4981677/TilemapCrash.zip)

## Steps to reproduce

1. Select all tilemaps on NotEmpty layout and copy-paste it to EmptyLayout 
2. Also try to duplicate NotEmpty layout several times
3. Save and load the project

## Observed result

Every one of these actions takes significant amount of time and uses a lot of CPU

## Expected result

Everything working fast and stable

## More details

**Affected browsers/platforms:**  Chrome

**First affected release:**  stable release

## System details

<details><summary>View details</summary>

OOPS. Out of memory

</details>

**Comment by KekGames** [comment] 2020-08-03 12:25
Also, the more the layouts - the higher Chrome's memory usage. So it seems that each tilemap image is loaded into memory for each layout separately, which can also explain CPU intensive loading.

**Comment by KekGames** [comment] 2020-08-05 17:41
Actually, I tried reducing tilemap image sizes, changing tile sizes, using just one tilemap object but with multiple instances. The only thing that seems to matter is the overall number of tilemap instances in the project. So if I have like 100 tilemap instances in the project - it crashes every time I'm trying to load it (Chrome runs out of memory and CPU usage goes up to 75%)

**Comment by KekGames** [comment] 2020-08-06 10:22
![image](https://user-images.githubusercontent.com/42392288/89520399-785c8280-d7e6-11ea-98fd-88fb8e33455f.png)
I also figured out, the issue is with the bugged tilemap, here's memory snapshot. 
Very simple example project: 
[Test13.zip](https://github.com/Scirra/Construct-3-bugs/files/5034178/Test13.zip)
You have one instance of TilemapBugged (blue) and one instance of TilemapNotBugged (green). Every time you try to copy-paste the TilemapBugged - it adds more than 50MB to RAM usage and takes some time, but if you do the same with TilemapNotBugged - everything works perfectly well, even though the tilemaps are identical. And if you dublicate the TilemapBugged object - it will also be bugged

**Comment by Unconected** [comment] 2020-08-18 22:31
on Stable 210.2 I had this happen to me.
I created two duplicate TileMaps, I didn't copy or clone.
I would edit the 2nd TileMap and try to save it, but the Project would crash.
I since then just erased the TileMap and started over so i don't have the crash report.

**Comment by Schala** [comment] 2020-09-19 00:51
This has crashed for me using only one tilemap object. If I have the tilemap panel in the bottom right with the layer panel, and selected, and try editing a tile, the moment I close the tile's pixel editor, I get a crash notice.

**Comment by DiegoScirra** [comment] 2020-11-27 11:41
The original report is not a bug, the tilemaps in the project are just too large. They appear not be to be, because of the small width and height of the instances, but they are still holding the tile data. It makes sense for them to take up a lot of memory and to take a noticeable amount of time to be duplicated.  Closing this isssue.

**Closed by DiegoScirra** 2020-11-27 11:41 UTC
