### ISSUE TITLE
Remote preview is not working on android device

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-3-bugs#3579] opened 2020-01-08 23:36 UTC
## Problem description

Remote preview is not working on android device. Stuck on loading data. Remote preview on iphone works fine.

## Attach a .c3p

Not needed..

## Steps to reproduce

1. Create a project or load an existing project
2. Click on remote preview and scan QR code
3. Remote (android) device stuck on loading data

## Observed result

Stuck on loading data

## Expected result

Run remote preview properly

## More details

**Affected browsers/platforms:** Chrome/Firefox

**First affected release:** r180

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 79.0.3945.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
C3 release: r181 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 1.3 gb
Storage usage (approx): 219 mb (15.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce G105M Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2020-01-09 11:53
Attempted to reproduce using Space Blaster on r180, worked fine. Can you confirm if Space Blaster works for you, if it does then please provide a project that replicates the issue.

**Comment by AshleyScirra** [comment] 2020-01-09 14:42
It worked fine for me too. This is most likely a connectivity issue, such as for some reason your PC can't reach your mobile over your local network. This is probably to do with your network configuration and not Construct, and since it appears to be working for everyone else, closing as not a Construct issue.

**Closed by AshleyScirra** 2020-01-09 14:42 UTC
Labels: can't reproduce
