### ISSUE TITLE
Sprite editor crash. Edge

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#1041] opened 2017-11-26 10:09 UTC
## Problem description

Sprite editor Crashing in Edge

## Attach a .c3p

N/A

## Steps to reproduce

1. Open a template project eg. Endless runner.
2. Click on a sprite to edit it.
3. Crash

## Observed result

C3 Crashed

## Expected result

No Crash

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r69-2/main.js, line 73, col 356656
Message: Animations Editor undo buffer is already initialized
Stack: Error: Animations Editor undo buffer is already initialized at ǃvOr (https://editor.construct.net/r69-2/main.js:73:356656) at prototype.ǃDy (https://editor.construct.net/r69-2/main.js:73:81634) at prototype.ǃvOA (https://editor.construct.net/r69-2/main.js:73:81144) at prototype.ǃvOd (https://editor.construct.net/r69-2/main.js:73:81259) at prototype.ǃug (https://editor.construct.net/r69-2/main.js:73:80803) at prototype.ǃu_ (https://editor.construct.net/r69-2/components/bars/projectBar/projectBar.js:1:7105) at prototype.ǃVk (https://editor.construct.net/r69-2/components/bars/projectBar/projectBar.js:1:6949) at Anonymous function (https://editor.construct.net/r69-2/components/bars/projectBar/projectBar.js:1:3045) at prototype.ǃTYp (https://editor.construct.net/r69-2/main.js:2:268748) at prototype.dispatchEvent (https://editor.construct.net/r69-2/main.js:2:267200)
Construct 3 version: r69.2
URL: https://editor.construct.net/
Date: Sun Nov 26 2017 10:58:03 GMT+0100 (W. Europe Standard Time)
Uptime: 20.6 s 
Platform information
Browser: Edge
Browser version: 16.17046
Browser engine: Edge
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.17046
C3 release: r69.2
Language setting: en-US 
WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Microsoft
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: WEBGL_compressed_texture_s3tc, OES_texture_float, OES_texture_float_linear, EXT_texture_filter_anisotropic, OES_standard_derivatives, ANGLE_instanced_arrays, OES_element_index_uint, WEBGL_debug_renderer_info, WEBGL_depth_texture, EXT_frag_depth, OES_texture_half_float, OES_texture_half_float_linear, EXT_shader_texture_lod

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment] 2017-11-27 13:29
Can't reproduce this one, but I think this might be related to #1045 which has already been fixed.

@tunepunk Please check the next release.

**Comment by AshleyScirra** [comment] 2017-11-28 13:42
r70 is now out, please check again!

**Comment by tunepunk** [comment] 2017-11-28 19:45
Nope same. But not on all sprites at all times. sometimes on first try, sometimes on second.

1. Open the endless runner example in edge.
2. DoubleClick on the object called player. if it works, just close sprite editor. and..
3. click the object called block.

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r70-2/main.js, line 73, col 356706
Message: Animations Editor undo buffer is already initialized
Stack: Error: Animations Editor undo buffer is already initialized at ǃrvN (https://editor.construct.net/r70-2/main.js:73:356706) at prototype.ǃy_ (https://editor.construct.net/r70-2/main.js:73:81556) at prototype.ǃrvq (https://editor.construct.net/r70-2/main.js:73:81066) at prototype.ǃrvm (https://editor.construct.net/r70-2/main.js:73:81181) at prototype.ǃiV (https://editor.construct.net/r70-2/main.js:73:80724) at prototype.ǃNz (https://editor.construct.net/r70-2/components/bars/projectBar/projectBar.js:1:7072) at prototype.ǃhO (https://editor.construct.net/r70-2/components/bars/projectBar/projectBar.js:1:6916) at Anonymous function (https://editor.construct.net/r70-2/components/bars/projectBar/projectBar.js:1:3033) at prototype.ǃhag (https://editor.construct.net/r70-2/main.js:2:269329) at prototype.dispatchEvent (https://editor.construct.net/r70-2/main.js:2:267781)
Construct 3 version: r70.2
URL: https://editor.construct.net/
Date: Tue Nov 28 2017 20:34:38 GMT+0100 (W. Europe Standard Time)
Uptime: 15.5 s 
Platform information
Browser: Edge
Browser version: 16.17046
Browser engine: Edge
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.17046
C3 release: r70.2
Language setting: en-US 
WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Microsoft
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: WEBGL_compressed_texture_s3tc, OES_texture_float, OES_texture_float_linear, EXT_texture_filter_anisotropic, OES_standard_derivatives, ANGLE_instanced_arrays, OES_element_index_uint, WEBGL_debug_renderer_info, WEBGL_depth_texture, EXT_frag_depth, OES_texture_half_float, OES_texture_half_float_linear, EXT_shader_texture_lod

</details>

**Comment by AshleyScirra** [comment] 2017-11-28 20:20
I can't reproduce here, maybe Diego can figure something out from the stack trace.

BTW it looks like you're using an insider build (17046) and I couldn't reproduce with the current stable version (16299), so it might be a bug in the pre-release version of Edge.

**Comment by tunepunk** [comment] 2017-11-28 20:52
Yeah that could possibly be it. I'll hold and see if it's still like that on next update. I'm in the fast ring at the moment.

**Comment by AshleyScirra** [comment] 2018-01-04 14:45
Since this doesn't affect the stable release of Edge, closing for now. Please file an issue if you can reproduce it in Edge 17 nearer the time it's due for release.

**Closed by AshleyScirra** 2018-01-04 14:45 UTC
Labels: can't reproduce, edge
