### ISSUE TITLE
Physics goes slower with animation speed above 0

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#6170] opened 2022-10-06 03:38 UTC
Here is an example of #6160 still not being fixed in all cases.

2 falling apples, 1 on the left has 50fps anim speed and moves glitchy compared to the 0fps one. 

![image](https://user-images.githubusercontent.com/5744908/194208309-2d2bcde0-7abe-46a9-b9bd-901653208aba.png)

c3p file [physicsbug.zip](https://github.com/Scirra/Construct-3-bugs/files/9720939/physicsbug.zip)

**Comment by alastajj** [comment] 2022-10-06 05:45
It could be something about the frame itself that's the issue.

If the animation only contains duplicate identical frames, then it doesn't matter what animation speed it plays at.

**Comment by AshleyScirra** [comment] 2022-10-06 09:47
The problem is the animation has non-centered origins. Construct regards the origin point to be the anchor point of the object; however Box2D regards the mid-point of the body to be the anchor point. If the Construct animation frame changes and the origin does not match up with Box2D, it essentially causes the physics body to teleport to a new position; the Physics behavior does that to update it to its new position, but it seems in Box2D changing the body transform interrupts the velocity.

This is all far more complicated than I originally anticipated ([it happens](https://www.construct.net/en/blogs/ashleys-blog-2/unexpected-complications-1535)) and as we're moving towards a stable release I think it's too late to try to sort it out reliably without risking a regression. So I think the best move is to roll back all the physics changes from this release cycle reverting it to how it works in r308.2, reopen #3821, and have another go in the next release cycle. I'll close this issue and follow up back at the original issue, referring to these subsequent issues as test cases.

**Closed by AshleyScirra** 2022-10-06 09:47 UTC
Labels: difficult
