### ISSUE TITLE
Editor Construct 3 (web and desktop) super slow - MacOs -

### ISSUE THREAD

**Issue by gxalive** [Scirra/Construct-3-bugs#3795] opened 2020-04-20 16:21 UTC
My editor "Construct 3" is running super slow, and sometimes crushes out. 
working on a:
MacBook Pro (Mid 2012)
2,5 GHz Intel Core i5
16 GB 1333 MHz DDR3
24gbs of space
Intel HD Graphics 4000 1536 MB

## Attach a .c3p

https://we.tl/t-fxF7NKlOTD

## Steps to reproduce

1. starting well
2. when I jump to any of the Events, start to slow down as hell 
3. crush

## Observed result

Every time I want to edit (mostly an event page) starting to get slow and slower, exponentially

## Expected result
Running normally, I don't know if is something about this Pandemic, but, since that, the editor is getting me problems

## More details

**Explanation Video:**
If you see the cursor "not moving" its because I am waiting to construct react with the click (clicking on tabs, a line of code, or anywhere). Perhaps is my computer or the internet?, right now, I don't know for sure, and I'm starting to frustrate:
https://we.tl/t-X4RxPF8N4Z

**Affected browsers/platforms:** 
Chrome and macOS

**First affected release:** 
I think is not about the version it's about when it happens, because Works ok in r189.2 pretty well, and now, since these couple weeks the same r189.2 is giving me a hard time.
## System details

<details><summary>View details</summary>

**Error report information**

Type: unhandled rejection
Reason: Error: Cannot read property 'ǃLh' of null @ TypeError: Cannot read property 'ǃLh' of null at d.ǃLh (https://editor.construct.net/r189-2/components/editors/eventSheetView/eventSheetView.js:1:5892) at window.ǃmnJ.ǃLh (https://editor.construct.net/r189-2/components/editors/eventSheetView/eventSheetView.js:1:54111) at window.ǃmnJ.ǃZj (https://editor.construct.net/r189-2/components/editors/eventSheetView/eventSheetView.js:1:105134) at new window.ǃmnJ (https://editor.construct.net/r189-2/components/editors/eventSheetView/eventSheetView.js:1:104953) at Function.ǃc.ǃq (https://editor.construct.net/r189-2/main.js:2:129457) at e.ǃmqC (https://editor.construct.net/r189-2/projectResources.js:1:304745) at Object.ǃcQG (https://editor.construct.net/r189-2/projectResources.js:1:282916) at n (https://editor.construct.net/r189-2/main.js:2:204421) at t (https://editor.construct.net/r189-2/main.js:2:204206)
Stack: TypeError: Cannot read property 'ǃLh' of null at d.ǃLh (https://editor.construct.net/r189-2/components/editors/eventSheetView/eventSheetView.js:1:5892) at window.ǃmnJ.ǃLh (https://editor.construct.net/r189-2/components/editors/eventSheetView/eventSheetView.js:1:54111) at window.ǃmnJ.ǃZj (https://editor.construct.net/r189-2/components/editors/eventSheetView/eventSheetView.js:1:105134) at new window.ǃmnJ (https://editor.construct.net/r189-2/components/editors/eventSheetView/eventSheetView.js:1:104953) at Function.ǃc.ǃq (https://editor.construct.net/r189-2/main.js:2:129457) at e.ǃmqC (https://editor.construct.net/r189-2/projectResources.js:1:304745) at Object.ǃcQG (https://editor.construct.net/r189-2/projectResources.js:1:282916) at n (https://editor.construct.net/r189-2/main.js:2:204421) at t (https://editor.construct.net/r189-2/main.js:2:204206)
Construct 3 version: r189.2
URL: https://editor.construct.net/
Date: Thu Apr 09 2020 14:22:51 GMT-0300 (hora estándar de Argentina)
Uptime: 3585.9 s

Platform information

Browser: Chrome
Browser version: 80.0.3987.163
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
C3 release: r189.2 (stable)
Language setting: en-US

WebGL information

Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel HD Graphics 4000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2020-04-27 11:23
I'm afraid its very difficult to do anything about a report like this.

Please only report one issue at a time - we need a full set of details for every individual report. This report seems to mention two issues, slow performance and a crash, but mixes together both which means both are missing important details that we need to investigate it.

Please only test the latest beta release. We may have fixed one or both of these problems already.

Please only attach minimal projects. It's nearly impossible to investigate problems in large projects, especially if there are no steps to reproduce the problem.

All of this is covered by the bug report guidelines. Please review them since it's usually impossible to help you otherwise. They are there to ensure your problem can be investigated and hopefully solved.

**Closed by AshleyScirra** 2020-04-27 11:23 UTC
Labels: can't reproduce
