### ISSUE TITLE
Pressing Ctrl shortly after selecting something in an eventsheet deselects it

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#1454] opened 2018-03-31 20:32 UTC
## Problem description

Basically the title. If I select an event, comment, condition, action (or anything really) inside the event sheet and press Ctrl ( + C in order to copy it) The selected thing will get deselected. This happens pretty much always when I press Ctrl very shortly after selecting something, it does NOT happen if I wait a little. No big deal, but can be annoying if my fingers are quick. :V

## Attach a .c3p

🍳 

## Steps to reproduce

1. Select anything inside the event sheet
2. Right after selecting press Ctrl

## Observed result

The selected thing gets deselected

## Expected result

The selection to stay so I can Ctrl+C it.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 210 mb (0.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by BonzerKitten7** [comment] 2018-04-03 15:35
I can confirm this one, it's extremely annoying.

**Comment by AshleyScirra** [comment] 2018-04-05 17:53
More accurate repro steps:

1. Mouse down on an event
2. Push Control down
3. Release mouse
4. Release Control

Observed: at step 3, the event is unselected
Expected: at step 3, event to remain selected

You must be really rushing here, because the workaround is... finish clicking before pressing Control!

**Comment by AshleyScirra** [comment] 2018-04-13 11:30
Should be fixed in r95.

**Closed by AshleyScirra** 2018-04-13 11:30 UTC
