### ISSUE TITLE
Issues with Mobile Adverts

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#1936] opened 2018-08-20 12:49 UTC
## Problem description
This plugin working but in a wrong way
Ads are showing on Action "Create Banner Ads" or "Create Interstitial Ads" instead of "Show Interstitial Adverts" or "Show Banner Adverts"
I have attached both example 
One is working and second is not working

## Attach a .c3p
[Ads Not Showing Capx](https://www.dropbox.com/s/nu2zvl4374srywq/Ads%20Not%20Showing.c3p?dl=0)
[Ads Showing Capx](https://www.dropbox.com/s/5rlmgr94zpdik3z/Ads%20Showing.c3p?dl=0)

## Steps to reproduce

Build both apk and see weather ads showing or not 

## Observed result
Showing ads with Action "Create Banner Ads" or "Create Interstitial Ads" instead of "Show Interstitial Adverts" or "Show Banner Adverts"

## Expected result
Ads should show with Action "Show Interstitial Adverts" or "Show Banner Adverts" instead of "Create Banner Ads" or "Create Interstitial Ads".

## Affected browsers

* Chrome: yes
@shortercode 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by luckyrawatlucky** [comment] 2018-08-20 12:53
do i need to upload apk instead of capx file? just tell me

**Comment by shortercode** [comment] 2018-08-20 13:06
C3P is fine, projects are preferable to game in most situations.

**Comment by shortercode** [comment] 2018-08-20 13:07
In your "not showing" example you have "show" set to true on your create method, is this a mistake?

**Comment by luckyrawatlucky** [comment] 2018-08-20 13:18
oh! is this problem ? 
I never noticed them

**Comment by luckyrawatlucky** [comment] 2018-08-20 13:35
I also tired with set that False but still ads not showing

**Comment by shortercode** [comment] 2018-08-20 13:43
That parameter will decide if the advert should be displayed as soon as they are loaded.

On your "not working" project the configuration action is failing because of a bug, so "is configured" is always false. Another user had already mentioned that to me and it should be fixed in the next release. 

In your working project "is configured" is also false, because the plugin was never configured. It still happily shows the test ads, but configuring the plugin is a requirement if you want the GDPR user consent dialog to show.

The configure method is a legacy method really, it's better to set the properties of the plugin and it will configure itself while the app is starting.

**Comment by luckyrawatlucky** [comment] 2018-08-20 13:47
can you give us option to show banner ads on "Top Side" or "Bottom Side"

**Comment by shortercode** [comment] 2018-08-20 13:52
It's something I would consider doing, but it is an enhancement not a bug fix. As such as I've just done a batch of work on advert plugin I'd rather not be revisiting it for a few weeks, I have other work to complete with higher priority.

**Comment by luckyrawatlucky** [comment] 2018-08-20 13:54
Okey Thanks

**Comment by shortercode** [comment] 2018-08-20 14:03
no worries, let me know if you have any other issues.

**Closed by shortercode** 2018-08-20 14:03 UTC

**Comment by luckyrawatlucky** [comment] 2018-08-22 09:52
Ads still not working with Action "Show Banner Ad" and its working only with "Create Banner Ad" Action

**Comment by shortercode** [comment] 2018-08-22 10:32
Have you checked that your app configuration succeeded?

**Comment by luckyrawatlucky** [comment] 2018-08-22 10:42
Configuration Failed

**Comment by luckyrawatlucky** [comment] 2018-08-23 05:56
@shortercode what may the reason for "Configuration Fail"?

**Comment by luckyrawatlucky** [comment] 2018-08-23 09:15
@shortercode what may the reason for "Configuration Fail"?

**Comment by luckyrawatlucky** [comment] 2018-08-25 07:01
is there nothing to say ?
or you are busy on other task ?

**Comment by luckyrawatlucky** [comment] 2018-08-25 07:45
1 more issue found in this plugin
on create ad if we do hide ads and show it later, Never works
on create ad if we do show ads, It works

**Comment by shortercode** [comment] 2018-08-25 07:50
Ads that have been hidden cannot be reused, this is intentional.

I have been continuing with C3 runtime work the last few days; commenting
on bug reports is quite distracting when your trying to focus. I will take
a look in next week.

**Comment by luckyrawatlucky** [comment] 2018-08-25 07:57
I'm not saying about after hide ads.
I'm saying
on created ad their is option Show "true" or "false" 
when i select "hide" then it never show ads on action "show current ad"
