### ISSUE TITLE
.c3p project loading troubles with an older release of C3 - "Failed to open project. Check it is a valid C3 single-file (c3p) project."

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#1292] opened 2018-02-16 07:08 UTC
## Problem description

The project file is for example made in R86, try to open it in R85, the error message displayed is still "Failed to open project. Check it is a valid C3 single-file (c3p) project."
We can do clearer.

## Steps to reproduce

1. Make whatever project file in R86 (open an example if you want). Download as copy
2. Open in R85
3. See the error dialog

## Observed result

"Failed to open project. Check it is a valid C3 single-file (c3p) project."

## Expected result

"Hey, your project was made in R86. If you want to execute it execute https://editor.construct.net/r86, or later if there has been new releases since."

Or a message of the like that gives the user more informations on what may be happening and do not let them believe their project file is screwed.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment] 2018-02-16 11:33
Closing as duplicate of #1288 

There was a forwards compatibility issue between r85 and r86 when using the text or spritefont plugin. As far as I'm aware they were the only 2 plugins affected.

We had a chat about this yesterday and to keep the development complexity down we aren't going to attempt forwards compatibility. @AshleyScirra has made some changes so that it will notify the user if the project was made in a newer version of C3 instead of displaying the corrupted project message. Unfortunately they will only work in newer releases so this will still be an issue until we release a new stable release I imagine.

**Closed by shortercode** 2018-02-16 11:33 UTC
Labels: duplicate, fixed
