### ISSUE TITLE
Multiplayer - Unpredictably, Host does not receive Peer messages

### ISSUE THREAD

**Issue by Jase0000** [Scirra/Construct-3-bugs#3834] opened 2020-05-05 20:46 UTC
## Problem description

Sometimes, at random (sometimes frequently in a row), when previewing and using the Mutliplayer object, sometimes a Peer's messages refuse to reach the Host (whether that is the Peer failing to send, or the Host failing to receive, I'm not sure).

This randomly breaks multiplayer functionality when playtesting, as I cannot then send messages to "BeginGame" or anything. My project focuses online only at the moment so this can be very tiresome when playtesting as I don't know when/why this is happening.
If there was a workaround that'd be alright!

The signalling server connection, joining rooms, etc., all works perfectly, and with my main project with more information displayed, the correct HostID is seen by the peer, etc.

## Attach a .c3p

https://drive.google.com/open?id=17R0tx-klxktMAUf2g8W_fHxfq35a0TC3

I have included a video, due the unpredictable nature of this bug.

https://www.youtube.com/watch?v=DAogbKAjkqA

In the video I:

1. Click preview.
2. Click preview again with ALT (to create extra window).
3. Join room on Left Preview.
4. Join room on Right Preview.
5. I click "Send Hello" on peer, several times, you see peer's log say "Sent" so button is functional.
6. I click over to Host, and nothing appears on the log. Notice the "PeerCount" is 2 on both previews, so same room.
7. I click Preview (didn't touch any events).
8. Repeat steps 3, 4.
9. I click "Send Hello" on peer, several times, and it sends through and the Host log see's the messages.

## Steps to reproduce

1. Preview c3p file with two windows
2. Join on Left Window
3. Join on Right Window
4. On the window that the log declares as "You are a Peer!", click "Send Hello".
5. You may see that Host does not log any messages (If not, preview again and repeat, I repeated about 10 times and then it happened, but with normal usage I am playtesting every minute or two)

## Observed result

Randomly, the peer's message may not reach the host (as the log is recording incoming messages and does not see anything.

## Expected result

Once joined room successfully, then messages should be reliable.

## More details
The c3p file, I have forgotten to include "Multiplayer - On Error" trigger to append text, but I had tested this previously and no errors came through on either Host or Peer.

Chrome, no extensions
Windows 10
r198

**Comment by AshleyScirra** [comment] 2020-05-07 12:02
I tried this 5 times and it worked fine every time.

Is there anything in particular that has led you to believe this is an issue with Construct rather than an issue with network connectivity? Note that using "reliable" mode does not mean transmission is guaranteed - only that it will retry if transmission fails. Also are there any console messages of note when it's not working?

Further the project includes some suspicious events, such as trying to leave the room again when you left the room, and also leaving the room when you click "join room", which may cause a conflict (especially since both leaving and joining a room is an asynchronous process that takes some time to complete and will fire a trigger when it's done).

**Comment by AshleyScirra** [comment] 2020-05-19 15:16
Issues that cannot be reproduced are not actionable, so closing. Please re-file if you can find a way to more reliably reproduce it.

**Closed by AshleyScirra** 2020-05-19 15:16 UTC
Labels: can't reproduce
