### ISSUE TITLE
[not sure if bug]Static local variable not keeping a value from tick to tick

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#3314] opened 2019-09-08 08:09 UTC
## Problem description

A couple of static local variables that should keep a value in a persistent manner does not seem to be their job when in a group.

## Attach a .c3p

https://kyatric.com/c3/bugs/2019.09.08.local.variable.scope.c3p

## Steps to reproduce

1. Execute the project

## Observed result

In its current state, the project will create trails from the point 0,0 on screen.

## Expected result

To see the expected result from the code :
1. Move the local variables outside of Group1 (they become global variables)
2. The project executes as intended, updating the position from initialX and initialY variables

I would expect for static variables to keep the "initialX" and initial Y values within the group as local variables (but still hold the value, or be allowed to be assigned the value)

## More details

Is it a misunderstanding on my end or is it an actual issue ?

**Affected browsers/platforms:** 

Chrome

**First affected release:** 

164.2

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2019-09-09 10:24
I can't reproduce any problem - it appears to work correctly with both mouse input on Windows or touch input on Android, as expected. It doesn't ever appear to draw to the point 0,0. Are you seeing something different?

**Comment by Kyatric** [comment] 2019-09-09 10:41
Wow, I can't reproduce either now.
It was, when I posted, and the previous day in another project behaving in a way that lead to believe that initialX and initialY values both kept to 0, and the starting point of any trail created was the top left corner of the screen.

But indeed, now "it works".

Could it be a chrome update over Sunday ?

I guess this could be closed then, and is not a Construct issue...

**Comment by AshleyScirra** [comment] 2019-09-09 10:56
Static locals ought to work identically to globals, and it should be impossible for "has touch" to be true before "on touch", so I can't see a way this wouldn't work... anyway, closing, although if you can find a way to reproduce it again you can file that!

**Closed by AshleyScirra** 2019-09-09 10:56 UTC
Labels: can't reproduce
