### ISSUE TITLE
Crash: Importing multiple SVG files 

### ISSUE THREAD

**Issue by Astralgr** [Scirra/Construct-3-bugs#3549] opened 2019-12-15 16:28 UTC
## Problem description

Hello,

I have an animation with 60 frames in svg format.

Importing these frames one by one works fine but doing this manually for 60 images is a hassle.

Unfortunately when trying to import more than two files from "import frames" and then "from files" construct 3 crashes. 

## Attach a .c3p

Attached is an example of the svg files that causes the crash

[60fps.zip](https://github.com/Scirra/Construct-3-bugs/files/3965146/60fps.zip)

svg files

## Steps to reproduce

1. Import multiple svg files
2.
3.

## Observed result

Crash after import

## Expected result

Import all svg files after selecting them from a directory

## More details

Windows, Chrome, Edge, Mozilla

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information

Type: unhandled rejection

Reason: Error: e is null ǃZhd/i<@https://editor.construct.net/r171-3/projectResources.js:1:862909 ǃZhd@https://editor.construct.net/r171-3/projectResources.js:1:862897

Stack: ǃZhd/i<@https://editor.construct.net/r171-3/projectResources.js:1:862909 ǃZhd@https://editor.construct.net/r171-3/projectResources.js:1:862897

Construct 3 version: r171.3

URL: editor.construct.net

Date: Sat Dec 14 2019 21:54:21 GMT+0100 (Central European Standard Time)

Uptime: 22.8 s

Platform information

Browser: Firefox

Browser version: 71.0

Browser engine: Gecko

Browser architecture: 64-bit

Context: browser

Operating system: Windows

Operating system version: 10

Operating system architecture: 64-bit

Device type: desktop

Device pixel ratio: 1

Logical CPU cores: 8

Approx. device memory: (unavailable)

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0

C3 release: r171.3 (stable)

Language setting: en-US

WebGL information

Version string: WebGL 2.0

Numeric version: 2

Supports NPOT textures: yes

Supports GPU profiling: no

Supports highp precision: yes

Vendor: Google Inc.

Renderer: ANGLE (NVIDIA GeForce RTX 2070 Direct3D11 vs_5_0 ps_5_0)

Major performance caveat: no

Maximum texture size: 16384

Point size range: 1 to 1024

Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_filter_anisotropic, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2019-12-16 13:18
Your report appears to reference r171.3, where I can reproduce the issue. However it appears to already be fixed in r179, since I cannot reproduce the issue there. Please see the bug report guidelines - we ask you only report issues that reproduce in the latest release to avoid filing bugs for things we've already fixed.

**Closed by AshleyScirra** 2019-12-16 13:18 UTC
Labels: can't reproduce

**Comment by Astralgr** [comment] 2019-12-16 14:41
I can confirm that I am using r171.3 which is the latest **stable** build as for now.
Thank you for your time though and the good news

**Comment by shortercode** [comment] 2019-12-16 15:14
It can often be a couple of months between stable releases, but we generally do beta releases once a week. So it's worth checking if you can replicate an issue in the latest beta. We're currently moving towards a new stable release, but because of the holidays it will be in the new year.

**Comment by Astralgr** [comment] 2019-12-16 16:00
I understand, will do that next time I stumble upon a bug.
Thank again.
