### ISSUE TITLE
Tween Z-Elevation issue in 276

### ISSUE THREAD

**Issue by arcadesindo** [Scirra/Construct-3-bugs#5308] opened 2021-12-15 15:19 UTC
## Problem description
So my project was created in 268 back then, and today after I've update to stable 276, the tween of my objects not working as supposedly. But after trying back to 268, it works! not quite sure why its not working in 276.

## Attach a .c3p
[Card Test.zip](https://github.com/Scirra/Construct-3-bugs/files/7720563/Card.Test.zip)

## Steps to reproduce

1. Try to open it in 268 and run the layout
2. Try to open it in 276 and tun the layout

## Observed result
Some of the cards went missing in 276 after Z-elevation ping-pong.

## Expected result
It should not went missing like 268.

## More details

**First affected release:** 
Worked in 268 but broke in 276

**Comment by CrackHub** [comment] 2021-12-15 15:32
Oh thanks for reporting same issue i was report it. I hope Ashley can reproduce this.
https://github.com/Scirra/Construct-3-bugs/issues/5291

**Comment by programmer861** [comment] 2021-12-15 15:32
++++

**Comment by AshleyScirra** [comment] 2021-12-15 15:43
Can you make a simpler example using the fewest events and objects possible? It's difficult to debug projects like this, especially since it's hard to rule out if it's actually just a mistake in events (which is very common).

**Comment by AshleyScirra** [comment] 2021-12-15 15:50
@DiegoScirra - FWIW it looks like the Z elevation finishes on a tiny negative Z elevation like -1.8908485888147197e-16. So the tween back to the start slightly overshoots the original value of 0. I guess it should save the start value and make sure it finishes on exactly the same value? Perhaps some changes to the calculations in the last release affected the floating point precision of calculations.

It looks like this can be worked around by setting the Z elevation to 0 after the tween finished, as the bug is the Z elevation finishes slightly negative, which puts it behind the background.

**Comment by DiegoScirra** [comment] 2021-12-15 16:07
Fixed it, this got introduced in r273 with the overall performance improvements to tweens and timelines.

**Comment by CrackHub** [comment] 2021-12-15 18:48
Nice finally, thanks

**Comment by AshleyScirra** [comment] 2021-12-16 11:57
Should be fixed in r276.2.

**Closed by AshleyScirra** 2021-12-16 11:57 UTC

**Comment by arcadesindo** [comment] 2021-12-16 12:00
thanks Ashley, Diego!
