### ISSUE TITLE
Force own texture bug

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#52] opened 2017-04-09 12:19 UTC
## Problem description

When a layer has the option "Force own texture" enabled, cause bad scaling of the UI. It is further exaggerated by zooming in/out the layout view.

## Attach a .c3p

A good example that I found is the "rain demo" project and the introductory "KiwiStory" project.

## Steps to reproduce

1. Open either projects.
2. Select an object in a layer that has "Force own texture" enabled.
3. Try zooming the layout view in/out to see the effects.

## Observed result

Bad object/UI scaling and cause a shift in position much like a differing layer parallax effect.

## Expected result

No bad scaling or bad draw on screen.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Local storage
Storage quota (approx): 2.4 gb
Storage usage (approx): 72 mb (3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2017-04-11 13:00
Can't reproduce in r17. I opened Kiwi Story, enabled 'Force own texture' on the title screen layer, selected an object and zoomed in and out. It looked correct.

**Comment by jaydonteh** [comment] 2017-04-11 17:33
Apparently Kiwi Story turned out fine now, but not **"The 'rain demo'"**.

1. Open **"The 'rain demo'"**.
2. Select any objects on screen, preferably any "cloud shadow".
3. Zoom out the layout view.

You will see the UI scale bug, also the layout view is surprisingly laggy and slow to the point of non-responding. I'm now suspecting one of the WebGL effects.

**Comment by AshleyScirra** [comment] 2017-04-13 10:25
Ah, I see. Turns out it's actually to do with using layout effects. Should be fixed in r18.

**Closed by AshleyScirra** 2017-04-13 10:25 UTC
Labels: can't reproduce, need info
