### ISSUE TITLE
r296 TextInput plugin Causes Crash

### ISSUE THREAD

**Issue by Pinbak** [Scirra/Construct-3-bugs#5734] opened 2022-05-24 21:36 UTC
## Problem description
When opening a project saved from r295 in r296, the project will crash when a layout is opened with the TextInput plugin. This plugin has to be in a project saved in r295, but not necessarily created in that version. Also, the project will not crash if the layout containing the textinput is not opened (event sheets and other layouts are fine).

Note, the project does not need to be saved in r295, but r293.3 also causes this problem.

## Edit
This seems to be for all form controls on r296, even when added in r296.

## Attach a .c3p

[textInputText.zip](https://github.com/Scirra/Construct-3-bugs/files/8766339/textInputText.zip)

## Steps to reproduce

1. Open r295 (or 293.3), create a TextInput object and save the project
2. Open the saved project in r296

## Observed result

The engine crashed

## Expected result

No crash

## More details

**Affected browsers/platforms:** Tested on Chrome & Firefox

**First affected release:** broke in r296, worked in previous versions

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r296/projectResources.js, line 639, col 206
Message: Uncaught Error: effects not supported
Stack: Error: effects not supported at d.ZB (https://editor.construct.net/r296/projectResources.js:639:212) at ZB.next () at d.b7a (https://editor.construct.net/r296/projectResources.js:776:514) at b7a.next () at d.aDa (https://editor.construct.net/r296/projectResources.js:776:453) at d.Df (https://editor.construct.net/r296/projectResources.js:1269:377) at d.Df (https://editor.construct.net/r296/projectResources.js:1229:3) at QYb (https://editor.construct.net/r296/components/editors/layoutView/layoutView.js:78:153)
Construct version: r296
URL: https://editor.construct.net/r296/
Date: Tue May 24 2022 22:27:03 GMT+0100 (British Summer Time)
Uptime: 5.5 s

Platform information
Product: Construct 3 r296 (beta)
Browser: Chrome 101.0.4951.67
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment] 2022-05-25 10:42
Duplicate of #5730

**Closed by AshleyScirra** 2022-05-25 10:42 UTC
