### ISSUE TITLE
Crash when attempting to open specific layout

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#5653] opened 2022-04-21 21:15 UTC
## Problem description

Project crashes when I attempt to open a specific layout. An earlier version of the project does not have the same issue but I barely changed anything between. I have no idea what I did to cause this :I

## Attach a .c3p

[foobar.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8535115/foobar.c3p.zip)

## Steps to reproduce

1. Attempt to open Layout "thiscrashes"

## Observed result

Crash

## Expected result

Open layout

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'length') @ TypeError: Cannot read properties of undefined (reading 'length') at CCG.uh.g.J.$Ea.ed (https://editor.construct.net/r291/main.js:1424:182) at window.Pcb.leb.ed (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:17:454) at window.Pcb.nc (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:9:446) at window.Pcb.eGa (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:9:122) at Array. (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:8:101) at window.cIb.dispatchEvent (https://editor.construct.net/r291/main.js:1058:42) at jS (https://editor.construct.net/r291/components/editors/layoutView/layoutView.js:39:423) at window.cIb.lC (https://editor.construct.net/r291/components/editors/layoutView/layoutView.js:126:484)
Stack: TypeError: Cannot read properties of undefined (reading 'length') at CCG.uh.g.J.$Ea.ed (https://editor.construct.net/r291/main.js:1424:182) at window.Pcb.leb.ed (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:17:454) at window.Pcb.nc (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:9:446) at window.Pcb.eGa (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:9:122) at Array. (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:8:101) at window.cIb.dispatchEvent (https://editor.construct.net/r291/main.js:1058:42) at jS (https://editor.construct.net/r291/components/editors/layoutView/layoutView.js:39:423) at window.cIb.lC (https://editor.construct.net/r291/components/editors/layoutView/layoutView.js:126:484)
Construct 3 version: r291
URL: https://editor.construct.net/r291/
Date: Thu Apr 21 2022 23:14:40 GMT+0200 (Central European Summer Time)
Uptime: 500.2 s

Platform information
Browser: Chrome
Browser version: 100.0.4896.127
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
C3 release: r291 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by beebits** [comment] 2022-04-21 22:10
I told their yesterday, have the same problem

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'length') @ TypeError: Cannot read properties of undefined (reading 'length') at CCG.uh.g.J.$Ea.ed (https://editor.construct.net/r291/main.js:1424:182) at window.Pcb.leb.ed (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:17:454) at window.Pcb.nc (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:9:446) at window.Pcb.eGa (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:9:122) at Array. (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:8:101) at window.cIb.dispatchEvent (https://editor.construct.net/r291/main.js:1058:42) at jS (https://editor.construct.net/r291/components/editors/layoutView/layoutView.js:39:423) at window.cIb.lC (https://editor.construct.net/r291/components/editors/layoutView/layoutView.js:126:484)
Stack: TypeError: Cannot read properties of undefined (reading 'length') at CCG.uh.g.J.$Ea.ed (https://editor.construct.net/r291/main.js:1424:182) at window.Pcb.leb.ed (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:17:454) at window.Pcb.nc (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:9:446) at window.Pcb.eGa (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:9:122) at Array. (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:8:101) at window.cIb.dispatchEvent (https://editor.construct.net/r291/main.js:1058:42) at jS (https://editor.construct.net/r291/components/editors/layoutView/layoutView.js:39:423) at window.cIb.lC (https://editor.construct.net/r291/components/editors/layoutView/layoutView.js:126:484)
Construct 3 version: r291
URL: https://editor.construct.net/r291/
Date: Fri Apr 22 2022 00:09:46 GMT+0200 (hora de verano de Europa central)
Uptime: 11.6 s

Platform information
Browser: Chrome
Browser version: 100.0.4896.127
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 24
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
C3 release: r291 (beta)
Language setting: es-ES

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon RX 5700 XT Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by beebits** [comment] 2022-04-22 08:47
With r290 doent appear the error, i will to roll back.

**Comment by DiegoScirra** [comment] 2022-04-22 11:07
Will be fixed in the next beta.

**Comment by AshleyScirra** [comment] 2022-04-25 16:54
Note duplicate of #5649

**Closed** 2022-04-26 12:37 UTC
Labels: duplicate
