### ISSUE TITLE
Construct 3 - Cloud Uploading Progress Broken (Percentage Message)

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#565] opened 2017-06-28 20:21 UTC
## Problem description
This is a quick one and probably not even caused by Construct 3 itself. 
The uploading percentage found on the bottom-left isn't working, it stays at 0% even though the syncing process is working fine.

![upload progress](https://user-images.githubusercontent.com/15656049/27658160-56dd2c88-5c4f-11e7-8192-7d6c7b4f2eed.PNG)

## Steps to reproduce

1. Open any project
2. Save to cloud (in my case _Google Drive_)
3. Notice that the progress stays at 0%

## Observed result

Construct 3 displays the cloud upload percentage but it stays at 0%.

## Expected result

Construct 3 should display the progress from 0 to 100%.

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

* Chrome, latest stable. (Version 59.0.3071.115)

**Comment by AshleyScirra** [comment] 2017-06-29 10:58
Assigning to Iain, but IIRC not all cloud services actually give a progress, so it may not be fixable for every service...

**Comment by TheRealDannyyy** [comment] 2017-06-29 21:52
Yeah I knew that this was probably not a C3 issue. Either way I think it's a good thing if we keep this one open until all workarounds have been tested out or perhaps Google updates their cloud API.

**Comment by JeFawk** [comment] 2017-07-02 17:06
I'm using dropbox and it shows 0% all the time as well.

**Comment by shortercode** [comment] 2017-07-03 11:22
I can confirm this is working in development and not release. I've checked through and can't find any build related issues, the progress event seems to not be firing. 

I think this might be related to the service worker intercepting the networking request [w3c ServiceWorker issues 1141](https://github.com/w3c/ServiceWorker/issues/1141) and completing it with the fetch API.

For reference:

- all upload methods should provide progress events
- **download** methods using `xhr.onprogress` and **upload** methods are using `xhr.upload.onprogress`
- **download** methods are firing progress events, but **upload** methods are not
- in the development environment upload and download are working
- event handlers are being bound correctly in both cases
- xhr supports progress events for both upload and download
- fetch doesn't support progress events
- in release all network requests from the tab are routed via the service worker

I haven't been able to find a specific chrome bug related to this, just the github issue I linked above. By the sounds of it some slight tweaks to the service worker may solve the issue? That's more @AshleyScirra's  realm though.

**Comment by TheRealDannyyy** [comment] 2017-07-03 13:04
Alright, seems the like SW's are being a pain again. 
This isn't a high priority right now so, @AshleyScirra feel free to fix this whenever you got the time to do it.

Thanks for the heads up @shortercode.

**Comment by AshleyScirra** [comment] 2017-07-03 15:18
This sounds like the previous issue I was having where downloading example projects also failed to track progress. I never got to the bottom of that (it was another thing that changed in production), but it sounds like from that w3c thread that it's not really well supported yet to have progress events through a Service Worker. This looks like an appropriate time to add the "difficult" tag...

**Comment by shortercode** [comment] 2017-07-03 17:48
Little red label of doom...

Status on progress events is not good, they seem to have been tied up in the cancel-able promises proposal. Which was around for 2 years before ironically being cancelled.

The new proposal still looks pretty flaky, but it might arrive sometime soon(ish) if observables make it into the spec. I've tried looking into non serviceworker workarounds and I can only find ones for downloads, so that's pretty useless.

Best suggestions I have:
1. When the serviceworker receives a no-cache entry just bail instead of using `respondWith( fetch(request) )` this triggers the default behaviour instead, so the progress event starts working again ( tested )
2. Complain at the chrome team ( might do this anyway )

**Comment by shortercode** [comment] 2017-07-18 11:43
Assigning to @AshleyScirra for a possible service worker refactor ( at some point... )

**Comment by AshleyScirra** [comment] 2017-07-19 13:51
I don't think I'll actually get round to a SW refactor any time soon, and on further reflection your patch is probably a pretty straightforward hack to apply until that refactor does happen. So I've changed my mind, @shortercode  go ahead and apply your patch to the SW.

**Comment by shortercode** [comment] 2017-07-19 13:54
Okay I've merged the change in, should appear in r46

**Closed** 2017-07-19 13:54 UTC
Labels: difficult

**Comment by AshleyScirra** [comment] 2017-07-19 14:04
The root SW (for editor.construct.net) needs to be updated server-side so note this may not actually sync up with r46. Also there's probably going to be caching issues, I'm not sure when browsers will pick up an updated SW script, especially with CloudFlare's caching...

**Comment by shortercode** [comment] 2017-07-19 14:18
I'm pretty sure its the version specific service worker that catches the request, not the root service worker. So we might be in business with a release.

**Comment by AshleyScirra** [comment] 2017-07-19 15:12
Our SW setup is kind of a mess, because the version specific SW does not actually intercept any fetch requests at all :P its scope is 'eclipsed' by the root one, which always handles everything on editor.construct.net. The version-specific one only serves to fire an install event (which caches that version), or handle fetches if you directly navigate to the version (e.g. editor.construct.net/r45). None of this is what we intended, but it sort of ends up working anyway by accident.

**Comment by TheRealDannyyy** [comment] 2017-07-19 16:03
No problem if it takes a couple of releases in order to sync up. This is a visual issue and nothing engine breaking so any kind of minor delay is alright in my book.

**Comment by shortercode** [comment] 2017-07-21 15:47
Seems to be working for me in r46, look okay to you @TheRealDannyyy ?

**Comment by TheRealDannyyy** [comment] 2017-07-21 17:28
@shortercode it indeed does work now. Thanks a lot for the quick fix!
