### ISSUE TITLE
Issue with Instant Games landscape orientation

### ISSUE THREAD

**Issue by jcardenaslie** [Scirra/Construct-3-bugs#2810] opened 2019-04-04 15:15 UTC
## Problem description

C3 games set to LANDSCAPE orientation, will sometimes not scale properly within facebook instant games. I also tried tweaking the "Canvas Fixed Width" and "Canvas Fixed Height" in: App Dashboard > Settings > Basic Facebook Web Games, but didnt do much.

Currently the settings for "Canvas Fixed Width" and "Canvas Fixed Height" are set to "No".

## Attach a .c3p
[KiwiStory.zip](https://github.com/Scirra/Construct-3-bugs/files/3044122/KiwiStory.zip)

## Steps to reproduce

1 Open the base "kiwistory" project
2 Set the Orientation to "Landscape,
3 Insert the facebook instant game plugin,
4 Export it as facebook instant game
5 Upload it as an facebook app with instant game configuration,
6 Play it on a iphone devices (my devices is a iphone 8 with IOS 12.1.4), but this issue appears almost in all iphone devices

## Observed result

![fb_c3_landscape_issue](https://user-images.githubusercontent.com/6730873/55566614-6fc7d980-56d2-11e9-82d0-659c4706338f.jpg)

## Expected result

![fb_c3_landscape_issue_correctway](https://user-images.githubusercontent.com/6730873/55566805-d51bca80-56d2-11e9-86d2-5e9868579b34.png)

## More details

**Affected browsers/platforms:** 
Devices: Iphone
Platforms: Facebook Instant Games, Facebook Messenger

we are having this issue with c3 version 136r and 142.2

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by kingpirux** [comment] 2019-04-11 18:56
its not only on instants, i also had this problem running in iphone from web in normal game. Can't figure out why.

**Comment by AshleyScirra** [comment] 2019-04-17 17:19
Can't reproduce here - tested on an iPhone 7 Plus running iOS 12.2 and it looks correct: 
![Image-1](https://user-images.githubusercontent.com/768723/56307631-35802280-613d-11e9-9cef-46ae3161f213.jpg)

The sizing is set to whatever the browser engine tells JavaScript is available, so I'd guess this would be an issue with the webview not in Construct's control. I think it would be best to report this to Facebook and follow up with them.

**Comment by kingpirux** [comment] 2019-04-18 02:30
i had this issue with an iphone SE with all exports running in safari :P

**Comment by AshleyScirra** [comment] 2019-04-18 10:12
This issue appears to be specific to Instant Games. An issue involving the Safari browser may be unrelated, and if it is unrelated, would need to be filed separately following all the guidelines to be investigated.

**Comment by AshleyScirra** [comment] 2019-04-23 11:24
Since we can't reproduce this issue, closing - please report to Facebook if you want to follow this up.

**Closed by AshleyScirra** 2019-04-23 11:24 UTC
Labels: can't reproduce, external
