### ISSUE TITLE
Construct 3 loads to a blank screen :(

### ISSUE THREAD

**Issue by TwentyXP** [Scirra/Construct-3-bugs#852] opened 2017-09-27 21:40 UTC
## Problem description

I can see the loading sequence and the changelog, but when I close it the program goes blank.

If anyone has had this issue or has a possible solution, please reply!

Some info:

Construct 3 initially worked, I went on it a few weeks after its release and tried out the new features because I was a fan of construct 2. Shortly after an update, it breaks. I've updated and re-installed chrome and the program works on my other devices.

For some reason, I left it a while to see if the problem would magically fix itself with a patch.

I run windows 7 ultimate (service pack 1) and have a decent PC which I can comfortably game on. 

Thanks in advance.

(I use chrome, latest update)

(there is absolutely no crash box that comes up)

**Comment by TwentyXP** [comment] 2017-09-27 21:41
I'm sorry if I haven't given much to go on, it literally gives my nothing.

**Comment by AshleyScirra** [comment] 2017-09-28 12:29
Can't reproduce and no steps to reproduce, so closing.

You could check the browser error console for more information - it's Ctrl+Shift+J to open it in Chrome.

**Closed by AshleyScirra** 2017-09-28 12:29 UTC
