### ISSUE TITLE
Back button functionality *android*

### ISSUE THREAD

**Issue by mfoster98** [Scirra/Construct-3-bugs#365] opened 2017-05-25 22:41 UTC
## Problem description

*Loss of work due to Android back button not working with the engine. Now this one is down to my own stupidity but it's quite annoying. Say I'm adding an event and click into the wrong objects events and so I want to go back to the object picker and I press the system back button instead of the engine's back button and I haven't saved my work when the engine closes down and restarts when opened back up from my phones task manager*

## Steps to reproduce

1. Create a new event
2. Go into System for example
3. Press your phone system's back button
4. Shuts down the engine and has to be restarted from scratch. Losing any unsaved work.

## Observed result

*the engine shuts down and forces restart when the system back button is used*

## Expected result

*I do expect it to quit the engine but I think that it should do the same as the engine's back button.*

## Affected browsers

* Chrome: yes/zoom 100%

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.83
Browser engine: Blink
Browser architecture: 32-bit
Context: webapp
Operating system: Android
Operating system version: 5.0
Operating system architecture: 32-bit
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: 8
User agent: Mozilla/5.0 (Linux; Android 5.0; ALE-L21 Build/HuaweiALE-L21) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Mobile Safari/537.36
C3 release: r31

Local storage
Storage quota (approx): 643 mb
Storage usage (approx): 4.5 mb (0.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2+ is not supported. Rendering quality and features may be affected.
CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Vendor: ARM
Renderer: Mali-450 MP
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 100
Extensions:

EXT_blend_minmax
EXT_shader_texture_lod
OES_standard_derivatives
OES_vertex_array_object
WEBGL_compressed_texture_etc1
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2017-05-26 12:00
Duplicate of #174

**Closed by AshleyScirra** 2017-05-26 12:00 UTC

**Comment by mfoster98** [comment] 2017-05-26 13:33
Sorry Ashley, I'll be more careful next time!
