### ISSUE TITLE
Construct 3 Desktop Beta - Doesn't Install Updates Correctly

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#1442] opened 2018-03-28 13:27 UTC
## Problem description

I've noticed a strange issue when updating from a beta release into a "merged" stable one.

## Steps to reproduce

1. Be on **Construct 3 r93.2** and opted into **Beta Releases**
2. Notice notification to update to r94 and click on **Update**
3. Notice that the **update was successful** and the about page displays r94
4. Close Construct 3 (in my case Desktop)
5. Open Construct 3 and notice the same notification to update to r94

## Observed result

It seems like Construct 3 gets confused when updating from beta releases to "merged stable" releases and ends up in an update loop.

## Expected result

I assume the intended behavior is like how Construct 2 releases on Steam work, where you temporally update to the stable release even if you've opted into beta releases but continue to get beta releases after that. (In this case C3 obviously shouldn't notify me to update to the same version over and over again.)

## Affected browsers

* Chrome (Desktop): yes
* Firefox: no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 165 gb
Storage usage (approx): 91 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by TheRealDannyyy** [comment] 2018-03-28 14:15
Maybe this helps with isolating the bug, I've noticed that I don't get any notification telling me that C3 is ready to work offline. Perhaps that's somehow causing this issue on C3 desktop.

**Comment by AshleyScirra** [comment] 2018-03-28 15:21
I think when you get redirected from a beta to a new stable, the service worker will interfere. By default the previously loaded version of C3 loads from cache, so it works offline. So chances are you're on r93.2, get a notification about r94, get redirected to editor.construct.net, then it loads r89 because that was the last stable version that was loaded. So that will notify you again about the fact there is a newer stable release. I think if you try to reload it before it's had a few seconds to update in the background then you might possibly keep ketting r89 as well.

Not sure there's any easy solution to this - offline support fundamentally works by loading the last fully cached version...

**Comment by TheRealDannyyy** [comment] 2018-03-28 15:35
Any suggestions on how to fix this? I've cleared site data already with no luck, still looping the same notification.

**Comment by AshleyScirra** [comment] 2018-03-28 15:46
What's the URL and which version are you seeing load?

I've seen that console error before but not sure what causes it. I think it clears up when you clear browser storage and reload C3. (Chrome can be a bit finnicky about clearing storage, try restarting Chrome in between clearing storage.)

**Comment by TheRealDannyyy** [comment] 2018-03-28 15:53
Dev-tools says: _editor.construct.net_. 
I'm using C3 Desktop which comes with NW.js v0.28.1 and the version I'm trying to update from is r93.2 Beta. Used dev-tools to clear site data, is there another way for me to clear everything?

**Comment by AshleyScirra** [comment] 2018-03-28 15:57
Oh right - with the desktop build I think the only other way is to close C3, delete %appdata%/Construct3, and restart C3.

**Comment by TheRealDannyyy** [comment] 2018-03-28 16:12
Before I do that, would you like to get some of the data for debugging purposes?
(I'd send you an email since I don't know how of it contains private account data.)

**Comment by AshleyScirra** [comment] 2018-03-29 09:44
I'm afraid I don't think any of that would be much use.

**Comment by TheRealDannyyy** [comment] 2018-03-29 11:49
Alright. Unfortunately deleting the entire appdata folder didn't work as well.

I've also downloaded and completely reinstalled C3 Desktop ([Beta](https://downloads.scirra.com/c3-desktop/win64/construct3-win64-c64-beta.zip)) with the same issue happening.
This time the console gives out the following error messages:
![sw error](https://user-images.githubusercontent.com/15656049/38087204-8c31ad3e-3357-11e8-9795-bdd13fa7f8c9.PNG)

**Comment by pooyaGames** [comment] 2018-03-29 11:59
![screenshot 2018-03-29 16 27 29](https://user-images.githubusercontent.com/426713/38087655-1f819598-336e-11e8-85cc-720e198965ec.png)
This is what i see when i open construct 3 editor with latest stable release.

( i've not used r93 or previous beta versions)

**Comment by AshleyScirra** [comment] 2018-03-29 13:22
@pooyaGames that looks normal. Is there something unexpected about it?

**Comment by pooyaGames** [comment] 2018-03-30 08:09
it says construct 3 beta

**Comment by TheRealDannyyy** [comment] 2018-04-04 16:02
Still experiencing the same issue, it keeps promping me to update to 94.2 despite the update already being installed.

**Comment by AshleyScirra** [comment] 2018-04-05 11:03
I have no idea what this could be. It works fine for everyone in the Scirra office, and as far as I can tell most Construct users as well. Without a way to reproduce the issue ourselves there's not much we can do.

**Comment by TheRealDannyyy** [comment] 2018-04-05 13:27
Do the error messages help you to point me towards a general direction of what could be the cause?
Besides giving you my whole C3 data package, I don't know what else I could do.

The only "weird" thing I ever did with C3 Desktop was trying out my 3rd party plugin which crashed the editor but as you already know, I cleared everything including the appdata folder so this can't be it I suppose.

**Comment by AshleyScirra** [comment] 2018-04-05 13:47
Unfortunately the error messages are not very helpful. They do not make any sense to me at all.

**Comment by AshleyScirra** [comment] 2018-04-05 16:28
You didn't provide any system details in the original report. Are you definitely using Chrome stable?

**Comment by TheRealDannyyy** [comment] 2018-04-05 18:07
No this is exclusive to C3 Desktop (beta). I never experienced any issues in Chrome or FireFox.
I've updated the 1st comment and here is my system info:
## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 165 gb
Storage usage (approx): 91 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by sebastien-c3** [comment] 2018-04-17 08:02
Same here with r94.2 stable to r95 beta with Chrome (I want to keep my Desktop version stable - just testing the new runtime).

**Comment by AshleyScirra** [comment] 2018-04-17 10:12
@sebastien-c3 - this thread includes more than one kind of issue - can you be specific as to exactly what you're seeing?

**Comment by sebastien-c3** [comment] 2018-04-17 10:39
Thanks Ashley, and for last runtime updates (perf are great).
I'll investigate more a bit later to come back with more infos.

**Comment by TheRealDannyyy** [comment] 2018-04-17 13:45
@AshleyScirra No luck, same happened with the C3 Desktop (stable channel). I've done nothing major this time. Didn't even open any project, just changed the following settings:
- UI mode to "Desktop"
- Theme to "Light"
- Unchecked "Enable UI animations"
- Default save location to "cloud" (including backups to same location)
- Opted into "beta releases"
- GPU preference to "high performance"

Here is as usual what the console says, this time there is a bit more:
![console error](https://user-images.githubusercontent.com/15656049/38873440-0fd8f69e-4256-11e8-80a3-42bc0afea5b5.PNG)

**Comment by sebastien-c3** [comment] 2018-04-17 17:26
Here is my platform information and a gif to show you what I see. What else can I send to help?

![test-c3-beta-update](https://user-images.githubusercontent.com/28727266/38886053-1b2f7648-4275-11e8-9301-ec0e44aa3081.gif)

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 77 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment] 2018-04-17 18:00
@sebastien-c3 - thanks for the info, but it's still not clear which of the issues in this thread you're running in to exactly?

**Comment by sebastien-c3** [comment] 2018-04-17 18:38
Well, it looks like C3 doesn't keep updates to beta and comes back to the previous stable version every time I close and reopen the application.

**Comment by sebastien-c3** [comment] 2018-04-17 18:47
It works, Ashley! :) I had just to update my shortcut "Open as window".
I realized that by testing in a Chrome tab - update remains installed.

**Comment by angelo-lopez** [comment] 2018-04-19 12:07
I am getting the same problem on Google Chrome Version 66.0.3359.117. Construct keeps asking me to update to the latest Beta 95.2 (from Stable 94.2) every time I re-launch Chrome.

Platform information
Browser: Chrome
Browser version: 66.0.3359.117
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1.7999999523162842
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
C3 release: r95.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 95 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M370X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment] 2018-04-20 11:32
@angelo-lopez - I don't think that relates to this issue. It sounds like you've opted in to beta update notifications and you keep opening the stable release, which will keep telling you about the beta update.

**Comment by angelo-lopez** [comment] 2018-04-20 13:47
Thanks for the reply @AshleyScirra . That is exactly what I am experiencing. Construct keeps reverting back to the stable release every time I restart Chrome.

**Comment by TheRealDannyyy** [comment] 2018-04-20 14:33
@AshleyScirra Any progress on isolating this issue? Is there something I can do to help?

If there isn't, would it maybe be feasible for you guys to add an option in the settings menu in order to activate _manual updating_? To explain this briefly: if this option is selected, users would get no startup notification and have to manually _check for updates_ and click to confirm an update if there is one available for their version of a Construct 3 (stable/beta).

(In my opinion it would be even better for users to be able to select the version they want to use as a whole, just like you can on the releases page right now: https://www.construct.net/de/make-games/releases.)

**Comment by AshleyScirra** [comment] 2018-04-20 15:06
NW.js 0.30.0 just came out so I think the next step is to update the C3 desktop build with that and then see how things go. It may be that a Chromium or NW.js update helps.

**Comment by TheRealDannyyy** [comment] 2018-04-20 15:11
> You already can choose which release to use by visiting its URL directly. editor.construct.net defaults to loading the latest stable release.

Not really an option in the desktop releases unless you edit the package.json file.

**Comment by AshleyScirra** [comment] 2018-04-20 15:35
I haven't seen anyone else being affected by this in Chrome. The other comments in this thread appear to just be confusion over how beta update notifications work. Nobody else has shown the same console errors that you've been seeing as far as I can tell.

**Comment by AshleyScirra** [comment] 2018-04-20 16:29
I've updated the desktop download to a new one based on Chromium 66: https://www.scirra.com/forum/construct-3-desktop-build-beta-currently-win64-only_t199344

Can you try downloading that, clearing the cache/app data folder again, and then see how things go from there? I guess it will take a couple of releases to identify if the new version helps.

**Comment by TheRealDannyyy** [comment] 2018-04-20 17:30
Same results. Completely removed the app data folder and cleared the cache.

As soon as I switch to the "beta releases" this issue is back, I even watched the console and waited until the service workers finished their jobs. This has something to do with the beta releases setting I believe.

**Comment by AshleyScirra** [comment] 2018-04-20 18:12
Alright, well I guess we're kind of stuck. Based on some guesswork I made a shotgun change for the next release, let's see if that helps.

**Comment by AshleyScirra** [comment] 2018-04-23 10:49
r96 is out now so it might be worth checking again. I guess it may take a couple of releases, possibly not until the next stable release, to verify if it's working.

**Comment by TheRealDannyyy** [comment] 2018-04-23 14:19
@AshleyScirra Still the same issue. The only thing that changed is that I can now see the "construct is ready to work offline" notification again. I deleted the app data folder and cleared site data before testing.

Here is the console:
![errors](https://user-images.githubusercontent.com/15656049/39132333-e8643ee6-4711-11e8-94ae-db2e51b376ed.PNG)

**Comment by AshleyScirra** [comment] 2018-04-26 10:49
Well, the syntax error log has disappeared, so at least that's something. Have you tried clearing cache since that update? It's possible it left the cache in a bad state as a consequence of the other error.

**Comment by TheRealDannyyy** [comment] 2018-04-26 13:34
By deleting the cache you mean this right? I've done that today with r97 with no luck, still the same problem.

![cache](https://user-images.githubusercontent.com/15656049/39308926-0d3b0d74-4967-11e8-911c-6167a79778b4.PNG)

**Comment by AshleyScirra** [comment] 2018-06-29 12:31
I haven't looked at this for a while but is it still continuing to be a problem?

**Comment by TheRealDannyyy** [comment] 2018-06-29 13:39
I've downloaded the most recent C3 Desktop version (_construct3-win64-c67-beta_) and I'm using Construct 3 Release _r107.2_. Will check next release if updating works.

**Comment by AshleyScirra** [comment] 2018-07-02 13:50
OK, thanks for checking. I suppose a Chrome update sorted this out, so closing.

**Closed by AshleyScirra** 2018-07-02 13:50 UTC
Labels: desktop, difficult
