### ISSUE TITLE
(Mobile) Cordova Export Bug

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#194] opened 2017-05-15 08:22 UTC
## Problem description
Trying to Export a Blank Project JUST TESTING
I just filled Name, Description, Version, ID, Author and export to Mobile cordova
Crashing each time 
*Enter a concise description of your problem here*
I try to export 
**# Please Provide us This Export feature on Construct 2 too**

## Attach a .c3p
Blank File & Crash Report Pasted Below
*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Blank Project
2. Just Fill Name, Description, Version, ID, Author 
3. Export to Mobile cordova

## Observed result
Crash
*What do you see happen?*

## Expected result
Export
*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'androidVersion' of undefined @ TypeError: Cannot read property 'androidVersion' of undefined at ǃN.ǃiZ.ǃig.ǃqg.ǃiv (https://editor.construct.net/r26/exporters/cordova/exporter.js:1:2883) at ǃN.ǃiu.ǃfQ.ǃNH (https://editor.construct.net/r26/exporters/cordova/exporter.js:1:7983) at Promise.resolve.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.Le (https://editor.construct.net/r26/main.js:63:12548) at 
Stack: TypeError: Cannot read property 'androidVersion' of undefined at ǃN.ǃiZ.ǃig.ǃqg.ǃiv (https://editor.construct.net/r26/exporters/cordova/exporter.js:1:2883) at ǃN.ǃiu.ǃfQ.ǃNH (https://editor.construct.net/r26/exporters/cordova/exporter.js:1:7983) at Promise.resolve.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.Le (https://editor.construct.net/r26/main.js:63:12548) at 
Construct 3 version: r26
URL: https://editor.construct.net/
Date: Mon May 15 2017 13:44:14 GMT+0530 (India Standard Time)
Uptime: 66.5 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.96
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 32-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
User agent: Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment] 2017-05-15 08:34
Closing as duplicate of [#193](https://github.com/Scirra/Construct-3-bugs/issues/193)

**Closed by shortercode** 2017-05-15 08:34 UTC
Labels: duplicate
