### ISSUE TITLE
Exporting NW.JS : when Downloading the NW.JS version,  The download progress should be in the dialog

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#6466] opened 2023-02-07 05:06 UTC
## Problem description

When exporting NW.JS, if downloading the NW.JS version. the download progress should be displayed in the dialog, not in the bottom left corner. It's not obvious, and many people new to C3 will think the editor is stuck. And in many cases, the bottom of the browser window may be hidden beneath the taskbar.

## Observed result

![Snipaste_2023-02-07_12-57-38](https://user-images.githubusercontent.com/45864744/217152539-c0eae066-b3e5-44cd-8e99-2347c960b80d.png)

![Snipaste_2023-02-07_12-57-31](https://user-images.githubusercontent.com/45864744/217152531-c71b0468-1d69-4360-be9b-5fa05f5768a2.png)

## Expected result

Show 'Downloading NW.js' download progress in Dialog

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2023-02-07 11:25
This is a request for a change in design and is not a defect, so closing as not a bug. The suggestions platform is the place to go for changes in design.

**Closed by AshleyScirra** 2023-02-07 11:25 UTC
Labels: not a bug
