### ISSUE TITLE
Large projects fails to open from cloud in firefox.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#1057] opened 2017-11-29 20:31 UTC
## Problem description

Trying to open project in firefox fails and gets stuck on Loading 0%. Project opens in Chrome and Edge, so strange that it would not open in firefox (which is my main C3 browser at the moment). Possible bug or corrupted file?

This project was originally a .capx C2 project.

## Attach a .c3p

Project sent by mail, as I don't want to share my project publicly.

## Steps to reproduce

1. Start Construct 3 in firefox.
2. Open file sent by mail.

## Observed result

Project did not open and got stuck on Loading.

## Expected result

Should open correctly.

## Affected browsers

* Chrome: no
* Firefox: yes
* Edge: no

**Comment by tunepunk** [comment] 2017-11-29 20:48
On further investigation it only fails to load when loaded from cloud (dropbox). Other projects in dropbox opens as expected. Only this file and only in from dropbox.

Any idea what it could be?

**Comment by tunepunk** [comment] 2017-11-30 11:55
Just tested in Firefox on Mac as well. Same issue there, so I can rule out that it's windows specific.  There seems to be some problem with project getting stuck on loading when loading them from cloud in firefox.

**Comment by shortercode** [comment] 2017-11-30 12:00
This seem pretty weird, so your saying:
- specific project
- only firefox
- only over the cloud
- any cloud service
- downloads successfully
- fails to open

When the file has made it to me I'll try to replicate, hopefully it should produce a nice obvious error for me.

**Comment by tunepunk** [comment] 2017-11-30 12:03
It's not specific project. I was able to recreate the same thing by creating a new project. Adding a sprite with a number of big animation frames so the project would be more than 5mb. 

Saved it to cloud, closed project, and tried to open it again. Same issue. So it was nothing wrong with my project. It's firefox failing to load large projects from cloud.

**Comment by tunepunk** [comment] 2017-11-30 12:06
So you don't need my project file to recreate this issue. Any c3p file will fail to load if it's large enough.

**Comment by shortercode** [comment] 2017-11-30 12:12
Okay @AshleyScirra thinks it might be related to the project parsing code so going to leave it with him for now, you might hear from me later if it turns out to be a problem with the cloud code.

**Comment by AshleyScirra** [comment] 2017-11-30 12:24
I can reproduce in Firefox 57, but the issue looks odd - at some point during the zip file reading, it just stops making progress (it looks like a FileReader that never fires any callback). However in Nightly 59 it works correctly. So I think it's a Firefox bug that they've since fixed. @tunepunk can you check if it works for you in Nightly? If so I think we will close this as a Firefox bug.

**Comment by AshleyScirra** [comment] 2017-11-30 12:43
I think I've come up with a workaround for r71, hopefully that will mean it's fixed. Would still be useful to have verification from @tunepunk that it is fixed in Nightly.

**Closed by AshleyScirra** 2017-11-30 12:43 UTC
Labels: firefox

**Comment by tunepunk** [comment] 2017-11-30 13:07
I can confirm that large projects opens correctly in Firefox Nightly (Mac). The workaround is still welcome though is I don't use nightly on a regular day to day basis.
