### ISSUE TITLE
Crash when selecting family

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#6639] opened 2023-02-26 23:29 UTC
Some older files I have simply crash when selecting families in the Project bar or right clicking them.

## Attach a .c3p

The projects that currently crash under these conditions are games under development, I could disclose them to you via email, but not through here.

PLEASE provide an email if a project is necessary, otherwise my projects are simply lost.

## Steps to reproduce

1. Try selecting a family or right clicing it from the Project bar.
2. Optimally use an older project where elements of the family were at some point changed, added or deleted. I was not able to dissect what prompts the crash.
3. The editor crashes.

## Observed result

crash

## Expected result

no crash

## More details

**Affected browsers/platforms:**  latest chrome

**First affected release:**  331

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r331/components/bars/propertiesBar/propertiesBar.js, line 33, col 146
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'ta')
Stack: TypeError: Cannot read properties of undefined (reading 'ta') at Gfb (https://editor.construct.net/r331/components/bars/propertiesBar/propertiesBar.js:33:146) at CCG.aa.eT (https://editor.construct.net/r331/components/bars/propertiesBar/propertiesBar.js:145:167) at Adb (https://editor.construct.net/r331/components/bars/projectBar/projectBar.js:2:130) at window.NS.dLa (https://editor.construct.net/r331/components/bars/projectBar/projectBar.js:95:129) at Array. (https://editor.construct.net/r331/components/bars/projectBar/projectBar.js:91:97) at CCG.lh.g.K.HJa.dispatchEvent (https://editor.construct.net/r331/main.js:1235:399) at CCG.lh.g.K.HJa.PM (https://editor.construct.net/r331/main.js:1604:317) at CCG.lh.g.K.HJa.YF (https://editor.construct.net/r331/main.js:1599:24) at d.tk (https://editor.construct.net/r331/main.js:1627:321) at d.Ed (https://editor.construct.net/r331/main.js:1620:317)
Construct version: r331
URL: https://editor.construct.net/r331/
Date: Sun Feb 26 2023 20:16:41 GMT-0300 (Brasilia Standard Time)
Uptime: 36.3 s

Platform information
Product: Construct 3 r331 (beta)
Browser: Chrome 110.0.5481.105
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by WilsonPercival** [comment] 2023-02-27 02:52
Looks like this https://github.com/Scirra/Construct-3-bugs/issues/6595

**Comment by dupuqub** [comment] 2023-02-27 09:48
> Looks like this #6595

@WilsonPercival  I have nothing to add, but I'd just like to take the opportunity and say, Wilson, you are a monster, I don't know how you can find that many bugs, I'm in awe of your work, cheers.

**Comment by AshleyScirra** [comment] 2023-02-27 16:45
Closing as duplicate of #6595.

**Closed by AshleyScirra** 2023-02-27 16:45 UTC
