### ISSUE TITLE
Mouse Pointer not shown [r158]

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#3137] opened 2019-07-16 07:31 UTC
## Problem description

I don't see sometimes mouse pointer. Please look gif.

## Attach a .c3p
[Test.zip](https://github.com/Scirra/Construct-3-bugs/files/3395813/Test.zip)

## Steps to reproduce

![Bug3](https://user-images.githubusercontent.com/13033837/61274552-b9858d00-a7b4-11e9-8ad1-2b995154081d.gif)

## Observed result

Hide mouse pointer.

## Expected result

Show mouse pointer.

**Affected browsers/platforms:** Chrome

**Comment by shortercode** [comment] 2019-07-16 14:51
Not really sure what's going on here, I'm unable to reproduce the carat vanishing like you have in your video.

**Comment by QuasarX** [comment] 2019-07-16 15:03
@shortercode 
Hmm. Can you try %90 zoom (Chrome zoom) and Dark theme?

**Comment by shortercode** [comment] 2019-07-16 15:35
Yeah I can confirm it's related to screen DPI. At certain offsets the cursor is invisible. The library we use doesn't use a real caret in the default mode. I've seen a few comments from people online about it, with some really gnarly hacks... I think if we change mode it might fix this, but I'm not sure what the other side effects would be.

**Comment by SnipG** [comment] 2019-07-16 15:37
Not sure if same, but there is somesort of massive selection lag. When you first time  click certain comment, text area then sometimes, you need to wait 2-3 sec before that area is selectable and cursor to appear. Weaker pc it appears more often is very annoying, its been like this for long time. It's even worse then dark theme Dialog open lag.

**Comment by shortercode** [comment] 2019-07-16 15:46
@SnipG are you talking about the text editor or the event sheet? This issue is just a rendering issue with the text editor, no lag involved.

**Comment by shortercode** [comment] 2019-07-16 15:54
Changing the rendering mode for the text editor seems to have resolved the issue, so I'll check in the fix. But I will be interested if you have any new issues after this.

Issue is basically down to the emulated caret being only 1px wide before zoom modification and not pixel aligned. The hacks a saw basically try to guess the zoom level with CSS ( badly ) then increase the caret size to compensate.

**Closed by shortercode** 2019-07-16 15:54 UTC
Labels: can't reproduce
