### ISSUE TITLE
Animations Editor: Cant draw when color Alpha is set to 0

### ISSUE THREAD

**Issue by shinkan-fb** [Scirra/Construct-3-bugs#868] opened 2017-10-02 21:32 UTC
## Problem description

In Animation Editor setting RGBA to [RR, GG, BB, 0]  - where RGB have any value and Alpha is set to **zero** you are unable to draw.  
I guess it's rather working fine, but in C2 setting Alpha to zero basically work like an **eraser tool**, which was super useful.  You could set Left mouse button to some color and Right mouse button to some color with Alpha = 0 and then you could draw and fix without a need to change a tool.

## Attach a .c3p

[alphaZero.zip](https://github.com/Scirra/Construct-3-bugs/files/1350479/alphaZero.zip)

## Steps to reproduce

1. Open project
2. Open Animation Editor
3. Select any drawing tool
4. Set Alpha of the color to 0
5. Try draw something over existing image

## Observed result

Nothing is happening, drawing with alpha = 0 have no effect on the image at all

## Expected result

Drawing with Alpha = 0 should have same effect as an eraser tool.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r59
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 57 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 780 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by mOOnpunk** [comment] 2017-10-03 13:54
I posted about this ages ago, along with hardness still being soft edged but they never gets fixed.

**Comment by DiegoScirra** [comment] 2017-10-09 12:26
Closing this as a duplicate of #310.

I haven't forgotten about this one, there just have been other more important things to do.

**Closed by DiegoScirra** 2017-10-09 12:26 UTC
Labels: duplicate
