### ISSUE TITLE
 [Android related bug] Instant games can't be loaded on some android devices

### ISSUE THREAD

**Issue by istar001** [Scirra/Construct-3-bugs#1907] opened 2018-08-08 10:52 UTC
## Problem description

I developed several games for Facebook instant games platform. And I met a problem that these games couldn't be loaded on one Android phone of us successfully. They are all stopped at about 95% as attached. However, the game I developed by other engine has no problem of loading.

## Attach a .c3p

[Soccer_Master-FB-Android Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2269961/Soccer_Master-FB-Android.Bug.zip)

## Steps to reproduce

Load the game at the specific android phone (HUAWEI HORNOR 5C)

## Observed result
Stuck at 95%

## Expected result
Load complete

## Affected browsers

* Chrome: yes (Does Facebook messenger use chrome?)
* Firefox: no
* Edge: no
* Safari: no

## System details

[construct bugs.zip](https://github.com/Scirra/Construct-3-bugs/files/2269966/construct.bugs.zip)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment] 2018-08-08 11:28
I've heard a mentions about Huawei phones not supporting opus audio, which we take as a given on Android. I think they might be using their own webview implementation, but I haven't been able to confirm the problem. We don't have any Huawei devices in the office to confirm unfortunately.

**Comment by AshleyScirra** [comment] 2018-08-08 13:32
Since we don't have our own device to test on, can you attach Chrome DevTools to a device that fails to load and see if any errors appear in the console log? I think that is the only way we will be able to make progress on this.

You also didn't provide all the system details so I cannot tell which version of Construct 3 you are using, but if you published before r111 it may be worth re-publishing with that version or newer, since we worked around what appears to be a GPU driver bug using WebGL 2 on some Android devices.

**Comment by AshleyScirra** [comment] 2018-08-15 11:18
@KekGames - my previous comment still applies:

> Since we don't have our own device to test on, can you attach Chrome DevTools to a device that fails to load and see if any errors appear in the console log? I think that is the only way we will be able to make progress on this.

**Comment by KekGames** [comment] 2018-08-15 18:14
@AshleyScirra There are no errors in DevTools, it works in this mode, but not when exporting apk.

**Comment by AshleyScirra** [comment] 2018-08-16 09:13
Can you view the Browser.UserAgent string in the app? I would assume it is simply too old a webview. That's what's been the cause of problems with Opus audio in the past. Updating the webview should fix it.

**Comment by KekGames** [comment] 2018-08-18 06:06
@AshleyScirra even if it is the case - it would mean other users would also have the same issue in my game, so updating the webview can fix it for my phone, but not for other users.

**Comment by AshleyScirra** [comment] 2018-08-20 10:59
You already can import .ogg if you encode them yourself. There should not be any reason to though because all Chrome and webview versions everywhere ought to be up-to-date (they default to auto-updating from the Play store). In general it's infeasible to support users who, for whatever reason, don't update their software - it would be a great maintenance burden, significantly complicate adding new features, and inhibit our ability to track the latest and greatest web platform technologies.

Closing as there is not enough information to act on this issue; please re-file or re-open if you can provide the requested information.

**Closed by AshleyScirra** 2018-08-20 10:59 UTC
Labels: need info

**Comment by KekGames** [comment] 2018-08-22 08:59
@AshleyScirra 
![s80822-11570430](https://user-images.githubusercontent.com/42392288/44453752-8f5a3800-a602-11e8-99bf-da5167ecbcd6.jpg)
How can I import ogg? It's automatically converted to webm each time

**Comment by AshleyScirra** [comment] 2018-08-22 09:28
Just as I thought: Chrome 51 is over 2 years old. The current version is Chrome 68. You should install any available software updates.

**Comment by KekGames** [comment] 2018-08-22 09:50
I'm still affraid there will be a significant part of players having the same issue. Does new audio format solve the issue when user's music can not be played in background if music in the game is playing?

**Comment by AshleyScirra** [comment] 2018-08-22 10:11
I'm afraid as mentioned, it's infeasible to support users who do not keep their software up-to-date. I am not aware of any issues around music not playing as you mentioned, that sounds like something completely different.

**Comment by KekGames** [comment] 2018-08-22 10:32
@shortercode okay, thanks for information!
