### ISSUE TITLE
OR Operator issues

### ISSUE THREAD

**Issue by aiaicaptain** [Scirra/Construct-3-bugs#3816] opened 2020-04-29 14:25 UTC
## Problem description

Having an OR condition which is not the same type, or at least not another Variable check, as the above condition doesn't satisfy the condition concerning the object with the Second OR condition, but nonetheless executes any actions not including the object from the condition.

## Attach a .c3p

[ORoperatorBUG - Copy.Zip](https://github.com/Scirra/Construct-3-bugs/files/4552151/ORoperatorBUG.-.Copy.Zip)

## Steps to reproduce

1. Click any Mouse button, see two of the gray Sprite objects (which have Variable1 = 0) and the yellow Sprite2 object change scale. 

2. Now disable the first condition "Variable1 = 0". and leave only the the second OR condition which is a specific Sprite.Y value which only the third gray Sprite object has.

## Observed result

Observe than now when you click the mouse the third gray Sprite object, which previously did not get affected with both OR conditions active, now changes scale. NOTE: The second condition is based on Sprite.Y value, so moving the object even a bit will prompt you having to change the condition value. 

## Expected result

As two of the gray Sprites have a Variable1 var value of 0, and the third one has a Y coordinate of 127, having two OR conditions of Variable1 = 0 OR Sprite.Y = 127 should always change all the objects' scale. However, if the Condition block has both conditions on an OR, the object that is satisfied by the second OR condition doesn't get a scale change while the above OR condition is Enabled.

## More details

The logic goes on, just doesn't apply to the object with the second condition requirements. The yellow Sprite2 object is there to showcase that.

**Affected browsers/platforms:** 

Chrome
Firefox
Windows

**First affected release:**

works fine in 189.2, doesn't from 197 onward.

**Comment by aiaicaptain** [comment] 2020-04-29 15:00
Doesn't work fine in 189.2 it seems. I guessed it will as it is with 197 that the problem showed itself in my larger project and works when I run the older 189.2 just fine.

**Comment by SnipG** [comment] 2020-04-29 15:08
You can still use sprite own compare Y and make it work.

Ashley comment"I fixed this, and found that it was actually handled correctly in the C2 runtime - this was a regression when we ported the OR block code to the C3 runtime. So it should be fixed (and working consistently with the C2 runtime) in the next release."

C2 seems to handle it incorrectly, while not able to reference picked instance inside OR block. Or one of the Or block repicks it and somehow fails.

**Comment by AshleyScirra** [comment] 2020-04-30 12:40
I think it's all working correctly. The problem is a common misunderstanding with OR blocks: they can run with zero instances picked. This is when an instance fails one of the conditions - so is unpicked - but an unrelated condition in the OR block is true, causing the actions to run.

In this case for some reason you've used the system "compare values" action, which does not do picking, instead of the object's "compare Y" condition, which does do picking. This allows the OR block to run with zero instances picked, which happens with both conditions enabled: the top-left sprite fails "Variable1 = 0", so is unpicked; the subsequent "compare values" action is true, so the actions run, but with no Sprite picked (so it is not affected), and Sprite2 was not referenced in the event, so all instances are considered picked.

If it did affect the Sprite object, it would mean an action ran on an instance that failed the event's conditions, which contradicts how events are supposed to work.

Switch the second condition for "Compare Y" and you should see that the way it works makes more sense.

**Closed by AshleyScirra** 2020-04-30 12:40 UTC
Labels: not a bug

**Comment by aiaicaptain** [comment] 2020-04-30 12:52
This project was done just to highlight the issue. As you closed my previous bug for not following guidelines, you could have seen there, that the same happens with differenct conditions. The other case was, having already PICKED an instance of an object, checking a local variable (not of the objects) if true (this variable checks if the object is withing a certain goldu locks zone to be visible), but the checks with an OR condition if the object is also not PermaVisible, which if true will progress the logic as if the object was visible, as if the previous operator InGodlyLocks was true...and this had worked for me for well more than a year now... and suddenly it no longer does...the object is PICKED previously, but the OR condition forgets the PICKED context,,,not ONLY that, but if there was not picked object, what should happen if you for example destroy this object? It will destroy ALL the objects on the layout of this type if there is no picked context.... in my situation nothing happens... Please investigate this further, you are basically barring me from ever updating.

**Comment by aiaicaptain** [comment] 2020-04-30 12:55
![Demo1](https://user-images.githubusercontent.com/43926483/80712721-114e7400-8afb-11ea-98ad-eb328c0fcb24.png)

**Comment by aiaicaptain** [comment] 2020-04-30 12:58
Where do I lose the context here? if I disable the two OR conditions in 1, the logic works fine. If I have them, nothing of the actions concerning the World_Objects will fire, not to the one in context, not to anyone. Further more, I have a sub even here which prints the UID of the World_Object so Im sure I haven't lost the context, its just that I can't do anything with it...NOTE: this is down the line of a larger logic tree, I take the object's context above. Trying to do anything with the object BEFORE this step works fine. I don't know how to and what to send you, please suggest

**Comment by AshleyScirra** [comment] 2020-04-30 13:01
It could just be a mistake in your events. Or you could have accidentally, directly or indirectly, depended on a different bug that we fixed. Or it could be a misconception about how OR blocks actually work, as is what happened in this report. Unfortunately it's simply not feasible for us to debug full projects, especially if there is not strong evidence the problem is with Construct. The minimal project approach is designed to prove the issue is with Construct, and so far the only evidence we have using a minimal project, is that Construct is working correctly and there was a misunderstanding about how OR blocks work. If you still think there is a problem that ought to be fixed, you need to produce a minimal project that demonstrates the problem - our guidelines indicate this is what we need; as a small team we just do not have the resources to spend hours investigating large and complex projects, especially if the end result is it was just a mistake or misunderstanding.

**Comment by aiaicaptain** [comment] 2020-04-30 13:03
OK, fair enough. Please just tell me, why does the subevent print the correct UID of the object if I've lost the context? The one in the RED box. Thanks

**Comment by AshleyScirra** [comment] 2020-04-30 13:16
It's impossible to say since I can't see the context of any other parent events around it or the values of the variables involved, and as I said, in a large project it could take hours to figure this all out anyway even with the whole thing. However I would note that the screenshot mixes picking conditions and the non-picking system "compare values", which is also what the minimal project attached here did, which is further evidence it's a misunderstanding.

**Comment by aiaicaptain** [comment] 2020-04-30 13:18
Thanks for the time.
