### ISSUE TITLE
JSON.Parse is not reliable on low performance devices

### ISSUE THREAD

**Issue by vicbarbosa** [Scirra/Construct-3-bugs#4693] opened 2021-03-31 00:38 UTC
## Problem description

When parsing a big json, some low performance clients may fail to parse in the same frame, making the JSON.ToCompactString (or any other ACE of the JSON plugin) fail right after the .Parse action

## Attach a .c3p

[big-json-parse-bug.zip](https://github.com/Scirra/Construct-3-bugs/files/6233052/big-json-parse-bug.zip)

## Steps to reproduce

We have over 18k users using one of our projects and this JSON is the largest that we have in our projects.
Some clients are parsing the json and immediately trying to read the keys and failing because the Parse seems to be assynchronous but the parse action is not async so we can`t tell when the parse actualy finished. We can't also put an arbitrary wait after the parse because the delay to finish the parse may vary between devices and also it is a terrible, ugly hack.

In the example I sent, some of the JSON.Get(".component") will return 0, breaking the application.

## Observed result

Some clients fail to parse big jsons in the same frame. The JSON.ToCompactString may return the json string missing some of it (It is random, it returns without a random amount of characters of the end, which makes us believe it is just an async process but in a normal sync construct 3 action without a proper callback/trigger.

It`s important to note that we are 100% sure that the AJAX.LastData is returning the correct full json string. The problem is in the JSON.Parse(AJAX.LastData) that is taking more than 1 frame to load the entire json inside the JSON instance

## Expected result

Every parse (sync action) should finish right after the parse action is called, even if it would stall the game for a little while.
OR
Construct 3 should transform the Parse action in an async action and give us a proper trigger to run actions after the parse completed

Expected log no matter what client runs the application
![image](https://user-images.githubusercontent.com/27690689/113074286-29ae8f00-91a1-11eb-867a-53913662d00a.png)

## More details

Maybe this will help
https://stackoverflow.com/questions/44380744/how-to-make-json-parse-promise-or-asynchronous

**Affected browsers/platforms:** Happens on different platforms, seems to be related with device performance regardless of browser or OS.

**First affected release:** Since the first versions of Construct 3 with JSON plugin
[big-json-parse-bug.zip](https://github.com/Scirra/Construct-3-bugs/files/6233071/big-json-parse-bug.zip)

**Comment by AshleyScirra** [comment] 2021-03-31 10:48
The *Parse* action is definitely synchronous. Internally it just calls `JSON.parse()`, which is also synchronous. The amount of data does not affect this. The browser does the parsing, and this part of browsers is pretty much bulletproof.

I cannot reproduce the problem, and I'm pretty sure it's not related to asynchronous parsing. I'm afraid this means there's nothing we can do here, so closing. You'll need to file either a reliably reproducable problem, or further investigate what is really going on - I am pretty sure the cause is something different.

**Closed by AshleyScirra** 2021-03-31 10:48 UTC
Labels: can't reproduce
