### ISSUE TITLE
Main Tool Bar don't apear totally

### ISSUE THREAD

**Issue by bigheti** [Scirra/Construct-3-bugs#709] opened 2017-08-11 15:35 UTC
## Problem description

*When I open the Construct 3 the main tool bar don't appear totally*

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Click the Construct 3 icon in the Desktop
2. The Construct 3 is open
3. The main tool bar don't appear totally

## Observed result

*The main tool bar is show by half*

## Expected result

*The main tool bar is totally show*

## Affected browsers

* Chrome: yes
![main tool bar c3](https://user-images.githubusercontent.com/8853925/29220501-994eb7da-7e91-11e7-9393-aaedd6e0f122.png)

</details>

**Comment by AshleyScirra** [comment] 2017-08-11 15:40
Looks like the desktop equivalent of #696

**Comment by AshleyScirra** [comment] 2017-08-29 13:58
Can't reproduce anything wrong here. I've got a desktop shortcut for C3 with Chrome 60 and it loads normally. If I open Ghost Shooter, it still displays normally. Are you missing a step to reproduce the problem?

**Comment by AshleyScirra** [comment] 2017-08-29 17:07
#696 looks related and should now be fixed. Hopefully this is the same issue and will be fixed when r52 is out.

**Comment by AshleyScirra** [comment] 2017-09-08 16:33
No further reports so closing.

**Closed by AshleyScirra** 2017-09-08 16:33 UTC
Labels: can't reproduce
