### ISSUE TITLE
ENTER keypresses prompt page to reload or go back a page

### ISSUE THREAD

**Issue by flipog** [Scirra/Construct-3-bugs#650] opened 2017-07-28 04:27 UTC
## Problem description

Whenever I try to place an event onto an event sheet with multiple ENTER keypresses, chrome goes to the previous page I visited or

## Attach a .c3p

Every file I have, including new ones.

## Steps to reproduce

1. Start to add any action to an event sheet
2. Confirm with multiple ENTER keypresses
3. A prompt should appear asking if you really want to exit the tab

## Observed result

Often the page will reload because I'm fast pressing the ENTER key.

## Expected result

Nothing at all. It shouldn't happen.

## Affected browsers

* Chrome: yes
* Firefox: n/a
* Edge: n/a
* Safari: n/a

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

"**Menu** -> **About** -> **Platform information**" - This path could not be followed.

</details>

**Comment by AshleyScirra** [comment] 2017-07-31 14:44
Can't see anything wrong here: if I add a new condition and keep pressing enter, I get a "0 is between 0 and 45 degrees" condition, and for an action I get a "Set canvas size to 0 x 0"; further enter presses just edit and close. It doesn't ever prompt about leaving. Am I missing any steps? Also, do you have any browser extensions installed? Does it still reproduce if you remove them?

**Comment by flipog** [comment] 2017-08-01 00:06
i realized only later the problem only occurs while in fullscreen mode. Sorry about that.

**Comment by flipog** [comment] 2017-08-01 20:53
I have tried to replicate it further and what happens is:

1. On every default setting the problem does not exist.
2. When I disabled UI animations and effects it happened again.

ps: I'm truly sorry about not having a screenshot or better info about it, but it is not a crash. It's just probably some mismatched chrome shortcuts... I think.

**Comment by AshleyScirra** [comment] 2017-08-02 13:14
I still can't reproduce any issue, it's the same as my previous comment if I either press F11 to go fullscreen, or disable UI animations in settings. It never prompts about leaving. Do you have any browser extensions installed? Perhaps you've reconfigured keyboard shortcuts or something?

**Comment by flipog** [comment] 2017-08-04 07:46
Hi, I wasn't using any extensions, but also this hasn't happened to me in a while under the same circumstances. It definetely happened in the past in multiple occasions and in different machines, but it seems to have vanished now (???) Sorry about the lame issue. Wish I could've provided better feedback.

**Comment by AshleyScirra** [comment] 2017-08-04 10:12
OK, closing for now.

**Closed by AshleyScirra** 2017-08-04 10:12 UTC
Labels: can't reproduce
