### ISSUE TITLE
Animation editor - does not focus small sized sprite when opened

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2572] opened 2019-01-31 18:02 UTC
## Problem description

When you have sprite 5x5 for example, you open animation editor. Scrolling is defaulted to top-left corner.

## Steps to reproduce

1.Open r135-4, new project
2.Add sprite, resize to 5x5, color it, close editor
3.Reopen sprite, see scrolling is wrong.

## Observed result
Small sized sprite canvas is not focused when opened.

Reedit: does not focus smaller sprites then default 250x250, same problem popped-up with 50x50 sprite :(

## Expected result
Should focus sprite, when animation editor is opened.

## First affected release
r135-3 ..r135-2 has it correct

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.81
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36
C3 release: r135.4 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 1.2 gb (9.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by DiegoScirra** [comment] 2019-01-31 19:36
Can't reproduce this one, it looks like it is working just fine with those steps. Tried it with both 5x5 and 50x50 resizing.

**Comment by SnipG** [comment] 2019-01-31 20:15
Yeah, i now tried with incognite mode and could not reproduce. I have to do alot of testing, too see which thing affects it, as it does not reproduce in 135-2. 
Might take sometime :(

**Comment by DiegoScirra** [comment] 2019-01-31 20:46
I'll take another look at it tomorrow. Maybe it has to do with the pre selected tool. Lately there has been some issues related to selecting a tool and scrolling getting reset. I have the feeling that it works just fine, so long as there is no tool to be activated in the process of opening the editor.

But I will need o try all of that out, it's just a hunch.

**Comment by SnipG** [comment] 2019-01-31 20:48
I did some testing and it seems Default zoom level when editor opens is maximum. I can't zoom any more, but default zoom resets it, but when i close and reopen everything is zoomed again. 

Okey i try messing with pre selected tools.

**Comment by DiegoScirra** [comment] 2019-02-01 10:47
For very small images it is ok for the zoom to start out at maximum, the editor is attempting to find a zoom level at which the image can be properly edited. You wouldn't be able to do much of anything with a 5x5 image at 100% zoom.

**Comment by DiegoScirra** [comment] 2019-02-01 12:07
Good news, I was able to reproduce the problem. Turns out it only happens if you have UI animations turned off.

That is why you couldn't reproduce in an incognito tab, because that setting was getting reset to default.

**Comment by DiegoScirra** [comment] 2019-02-06 14:03
This is fixed in the next release.

**Closed by DiegoScirra** 2019-02-06 14:03 UTC
