### ISSUE TITLE
Error loading C3.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4098] opened 2020-08-09 06:11 UTC
## Problem description

I started C3 and it happened. It happened sometimes before and there is no real way of replicating it. It just happens sometimes.

## Attach a .c3p

n/a

## Steps to reproduce

There are no real ways of replicating this issue, I just log onto C3 and it happens. I still hope it gets investigated and fixed,

## Observed result

The layout is all messed up and there is a blank space that I cannot remove in it.

## Expected result

A stable editor.

## More details

The images below shows what happens after a first login.

![bug1](https://user-images.githubusercontent.com/34659544/89725979-11101f80-d9ec-11ea-9494-95325b313c14.PNG)
![bug2](https://user-images.githubusercontent.com/34659544/89725981-12414c80-d9ec-11ea-9cb9-46ec05014d21.PNG)

After I refresh the browser, it looks like this, and it only gets better after I erase my cache. It happens every day, it's super annoying. I just realized it happens every day because recently I started shutting down my PC.

![bug3](https://user-images.githubusercontent.com/34659544/89726046-8d0a6780-d9ec-11ea-8c22-05c8173a3009.PNG)

I also tried to shut down my PC and then quickly turning it on again repeatedly in short intervals, but it only happens after I stay hours away from the PC. I have no clue why this is happening or why it has to wait some hours for it to happen, but there is no more info I can give. I can't stand having to change all my settings every day and clearing cache and I'm not leaving my PC on just for C3.

1 client is nothing for a business, but this is such a headache that it's pushing me away from C3.

**Affected browsers/platforms:** Latest Chrome.

**First affected release:** Possibly since 208.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by dupuqub** [comment] 2020-08-10 03:08
I'm seriously confused, but I'm just trying to provide every piece of infrmation I have, so here it goes.

I didn't touch anything on the editor for some hours. I turned on the PC, started Chrome, and then magically the layout was reset to factory settings. All my preferences were kept, except for the position of the panels.

As a side note I use dual monitor setup and often I change which window displays the editor, I don't know if this is related, but it is something I do. Also I detach some panels and put them in the other display.

**Comment by AshleyScirra** [comment] 2020-08-10 12:18
I'm afraid, as ever, without steps to reproduce it's impossible to investigate the issue. This is why steps are required.

I'll keep an eye out for any further reports of this and will act on it if anything more substantial comes up, but since there is currently nothing that can be done about this report, closing.

**Closed by AshleyScirra** 2020-08-10 12:18 UTC
Labels: no repro
