### ISSUE TITLE
Construct 3 Runtime :: Memory Management, missing features.

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#2098] opened 2018-10-02 05:49 UTC
## Problem description

**Before telling me that this isn't a bug. Please hear me out.**
I don't know why these were left out but on the original **Preloader and Unloader Plugin**, all of these were present. These are important features and makes sense that shouldn't be ignored.

1. Load Object Images (by name)
2. Unload Object Images (by name)
3. Remove All Objects from Layer.
4. Remove All Objects from Layout.

## Defense

**Load Object Images (by name)** & **Unload Object Images (by name)**
We can already create object classes by names and it is very helpful, reducing **thousands** of events into just a single event. Adding this feature just makes perfect sense.

But in the case for **Memory Management,** we have no choice but to use **Load Object Image** which may take **thousands of events** on larger projects.

So, the most feasible solution without those features is avoiding the **Construct 3 Memory Management**. Through this, replicating the **Memory Management** through events.

_Pseudo Version:_
```
*For all objects
>Make a Preload "StackList" from "len" objects.
>Create object <"name">

*On Created Object <"name">
>"StackList"[i] = true
>Destroy
```

But at that case, the Memory Management feature is left unused. And the whole point of the **Memory Management for C3Runtime** was for **Large-Scale** project convenience. But, since **Large-Scale** projects always need and is required to optimize **event efficiency, neatness and avoid redundancy** to be able to **survive** the **maintenance, development time and overall performance of each sector of a game**.
At that point, the **C3Runtime Memory Management** would be counter-intuitive and using events would be wiser. But that beats the entire purpose of the **convenience of preloader and unloader**.
 
Having the option to **Load Object Images (by name)** & **Unload Object Images (by name)**, is an upmost need for the **Memory Management** to fully workout.

---------------------------------------------------------------------------------------------------------

**Remove All Objects From Layer** & **Remove All Objects from Layout**

We also had features from the original to **remove all object classes** from the **world**, also from just part of the world like the **layer**.
There are some cases when it is hard to determine which **Object Classes** are in the **layout / layer** when we have a **Dynamic Memory Management**. It would be easier for beginners and advanced users to take advantage of the **Memory Management** when you give us all the needed bells and whistles.
So that we don't have to create our own **Memory Management** again, and have a few lines of **non-used ACE scripts** on the **runtime.js**.

## Note

Thank you for giving the time to read this. I hope you consider the importance.

**Comment by SnipG** [comment] 2018-10-02 09:27
I haven't used this feature yet, but i think we need to make new idea suggestion for improved spritesheeting, which also includes your ideas, for complete memory management. We should not request small improvements that use up dev time, but at the end whole feature needs redevelopment.
When they develop thous already planned features and get them bug free, they can develop new improved spritesheeting feature.
If we talk about very large layouts, thousands of objects. Then current spritesheeting could not be up for the task in first place.

From Ashley blog: "Additionally since images can only be loaded and unloaded per spritesheet, unloading an object does not guarantee any memory will be freed - all objects on the spritesheet must be unloaded before the texture is released.

If you got thousands of objects and you unload ~100 you might not get anything. I think current memory management is sufficient atm, it can be used to unload thous mega large sprites that take whole spritesheet by itself. Unloading 30x30 sprites by 1 event or thousands might not give effect you are looking for.

So we should develop/suggest/brainstorm idea, how would be best to handle spritesheeting+memory management together with better outcome.

My 2 cents on the issue :)

**Comment by shortercode** [comment] 2018-10-02 11:03
I've marked this as an enhancement, as it sounds more like features you think the runtime should have included. Going to let @AshleyScirra review this and let him make judgement.

It might be that there are technical reasons why we haven't included them. Unload object images sounds like it might not always be able to take action when objects share a spritesheet, for instance.

**Comment by ChadoriRebornXD** [comment] 2018-10-04 18:27
@SnipG 
> We should not request small improvements that use up dev time, but at the end whole feature needs redevelopment.
> When they develop thous already planned features and get them bug free, they can develop new improved spritesheeting feature.
> If we talk about very large layouts, thousands of objects. Then current spritesheeting could not be up for the task in first place.
> 
> From Ashley blog: "Additionally since images can only be loaded and unloaded per spritesheet, unloading an object does not guarantee any memory will be freed - all objects on the spritesheet must be unloaded before the texture is released.
> 
> If you got thousands of objects and you unload ~100 you might not get anything. I think current memory management is sufficient atm, it can be used to unload thous mega large sprites that take whole spritesheet by itself. Unloading 30x30 sprites by 1 event or thousands might not give effect you are looking for.

**To be honest, I have nothing against the simplicity of the Construct 3 Sprite-sheeting.** **Batched Image Sprite-sheeting** is a feature to reduce the burden of **Texture-Swapping** which was solved after Construct 3 Editor's release. Which I am very thankful of.

Having a new Sprite-Sheeting feature is nice to override the automated Sprite-Sheeting and manually arrange Sprite-Sheets. But that would, without of doubt remove the simplicity of Construct 3 Sprite-Sheeting.

**Anyway, that is not what I am here for. I do get your point but that is for a different topic.**

------------------------------------------------------------------------------------------------------------------

I am actually here, not to focus on the Sprite-Sheeting methods but here for the **System ACEs**.
To get these features for the **Memory Management** as I previously mentioned.

- Load Object Images (by name)
- Unload Object Images (by name)
- Remove All Objects from Layer.
- Remove All Objects from Layout.

And these are the only ones available :
- Load Object Images
- Unload Object Images

I am here to ease the event-sheet **writing,** ease the **data.js** performance overhead, lessen the **event count**, ease the **event management** on large scale projects.

Because, loading each images by **object** rather than **name** will get anyone with thousands of objects to **manually load each object** on the event sheet compared to having a **list** of object names generated or predefined and loaded **dynamically or systematically** through a **For-Loop** in a **single event**. 

_Pseudo Version:_
```
*For Each <List>
>Load Object Images <"current name">
```

 For example, those games that load objects depending on the **user input** or **procedural generated** scenarios. 
I actually discussed this with @AshleyScirra , I'm not sure if he remembers though.

**That makes me disagree with your statement :**
> I think current memory management is sufficient atm.

-------------------------------------------------------------------------------------------------------------------

I do appreciate your contribution and interest to this topic @SnipG .
But, I hope that clears things up.

-------------------------------------------------------------------------------------------------------------------

To conclude,
I merely wish to have a simple but versatile **Memory Management** that can avoid the need for **Large-Scale** projects to make their own system for **preloading and unloading**. As it is a waste to have a **Memory Management targeted for Large-Scale projects** but isn't complete enough to be able to be used by **Large-Scale project developers** as it is missing a few **ACEs** that can end up as a redundant code in the **runtime.js** when the user decides on just making a custom **Memory Management**. 

Making **Large Games** is hard enough, and having a great design in terms of **event management** and **event count efficiency** could mean a lot in overall production.

-------------------------------------------------------------------------------------------------------------------

Thank you for the time.

**Comment by ChadoriRebornXD** [comment] 2018-10-04 18:38
@shortercode 

> I've marked this as an enhancement, as it sounds more like features you think the runtime should have included. Going to let @AshleyScirra review this and let him make judgement.
> 
> It might be that there are technical reasons why we haven't included them. Unload object images sounds like it might not always be able to take action when objects share a spritesheet, for instance.

Yeah but @AshleyScirra seem to have made some judgement calls and added the feature. Just without the **(by name)**, which I am targeting also to get supported.

**By the way Construct 3 is designed.** Having it supported just makes sense and convenient too.
And it would certainly help a lot of game developers.

_Create Object (by name) is supported :_
![img1](https://user-images.githubusercontent.com/31282960/46495059-052f0180-c847-11e8-8e88-709311bb7def.png)

_Having its counterpart in the Memory Management just makes sense and would be very convenient :_
![img2](https://user-images.githubusercontent.com/31282960/46495103-209a0c80-c847-11e8-80d1-008d63b3f862.png)

------------------------------------------------------------------------------------------------------------------

Thank you for considering it @shortercode for review.
I'm looking forward to how this will progress.

**Comment by AshleyScirra** [comment] 2018-10-05 14:35
This is a feature request, not a bug report, which in general should be posted to https://construct3.ideas.aha.io/. However the load/unload object by name actions are trivial so I've added them for the next beta.

It's not clear to be why you wouldn't just use "unload unused images" instead of "unload layout images" or "unload layer images". If you post a feature suggestion for those, you should include an explanation of why "Unload unused images" is not sufficient.

**Closed by AshleyScirra** 2018-10-05 14:35 UTC
Labels: enhancement
