### ISSUE TITLE
R153 corrupt debug apk  when JS script used in a c3p project

### ISSUE THREAD

**Issue by eonianvr** [Scirra/Construct-3-bugs#3037] opened 2019-06-13 00:05 UTC
when exporeting the project in R153 to generate a debug APK for android, the export works fine (minify is disabled) but when trying to install it on an android phone, you got the message  "package appears to be corrupt". It doesnt happens if the debug apk is generated from R152
## Problem description

[fingerprint R152.c3p](https://drive.google.com/file/d/1BEw4Fq-DauYJ1isScDL_0A0BsLb1DeI5/view?usp=sharing)

The JS file is big but the use of JS inside the event sheet is just 4 lines. it uses https://github.com/Valve/fingerprintjs2 in order to give something as close as possible as a unique UUID to each user of the app.

## Steps to reproduce

1. ope the project in R153
2. generate a debug apk (marshmallow)
3.try to install it on an android phone

## Observed result

you get a package appears to be corrupt message when trying to install the app on android
## Expected result

expect to install on android like the version generated from R152
## More details

**Affected browsers/platforms:** 
android (not tested on iphone)
works in preview mode in R153)

**First affected release:** 
R153
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by eonianvr** [comment] 2019-06-13 00:14
you can close it. Problem was solved using  as [] instead of . for calling the fingerprint API from the event sheet
Still minifying check box is still disable during the apk generation.

**Comment by AshleyScirra** [comment] 2019-06-13 11:21
I don't think the content of your scripts should affect whether the APK is even installable. Even invalid scripts should allow the APK to install, and then they'd encounter an error on startup. So it's probably something else that resulted in a corrupt APK. Assigning to @shortercode to check the provided project, but if he can't reproduce I think we will just close the issue.

**Comment by shortercode** [comment] 2019-06-13 14:08
Yeah scripts shouldn't have any effect on if the script is install-able, I gave it a whirl and didn't have any problems. Android can be quite tetchy about installing APK, often you can find the real reason in logcat. If your no longer having problems then I'm going to close this, as there isn't anything reproducible.

**Closed by shortercode** 2019-06-13 14:08 UTC
