### ISSUE TITLE
Edge performance (maybe).

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4362] opened 2020-11-22 15:16 UTC
## Problem description

Construct in Edge, or maybe Edge by itself, is behaving rather slow. I can't confirm that Edge is the culprit because there is no other demanding task I use it for, only C3, therefore when I experience slow performance, C3 is always running.

I tested on Chrome also, and it seems fine, C3 is fast as usual there.

## Attach a .c3p

Any file should present it, but even more when a preview is opened, and even more so when the preview has just opened.

## Steps to reproduce

1. Open C3 in Edge.
2. Preview any project.
3. You should see everything in the preview loading very slowly and also behaving slowly in the editor, mainly right after the preview starts, but also less so in the long run.

## Observed result

above.

## Expected result

Performance like in Chrome.

## More details

**Affected browsers/platforms:**  Latest Edge.

**First affected release:**  Tested in 225

## System details

<details><summary>View details</summary>

Platform information
Browser: Edge
Browser version: 87.0.664.41
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36 Edg/87.0.664.41
C3 release: r225 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 182 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 750 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment] 2020-11-23 12:32
It seems to be working just fine here.

Perhaps there is some issue specific to your system. Unfortunately there's very little we can do about issues we can't reproduce, so closing. Perhaps you could contact Microsoft if there is a clear difference between Edge and Chrome. Note that the latest Edge uses the same browser engine as Chrome (Chromium).

**Closed by AshleyScirra** 2020-11-23 12:32 UTC
Labels: can't reproduce, edge
