### ISSUE TITLE
Nondescript Error appears during autosaving to cloud

### ISSUE THREAD

**Issue by RichardMarks** [Scirra/Construct-3-bugs#2975] opened 2019-05-27 16:41 UTC
## Problem description

See the attached image.

## Attach a .c3p

Any project.

## Steps to reproduce

1. Create a new project
2. Save to cloud
3. Wait for autosave to kick in

## Observed result

![image](https://user-images.githubusercontent.com/16147/58431499-be12ac80-8073-11e9-8aa5-6822edf165dc.png)

## Expected result

No error

## More details

**Affected browsers/platforms:** 
Chrome, macOS & Windows

**First affected release:** 

I upgraded from r142 to r148 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by layilpaht** [comment] 2019-05-27 19:21
Update ??? 
That's something new I am hearing.By the way how to do that ?
Normally what I do :- Open the main construct 3 website,then click on launch construct 3 and then I jump over my work !!!!

**Comment by shortercode** [comment] 2019-05-28 09:22
Thanks for the report @RichardMarks this is a known issue that should be resolved in the next release. It's caused by a typo in the browser save corruption recovery code following a recent refactor.

There is an known issue (without a replication or fix so far) that is somehow losing metadata related to 1 or more browser saves. This is what's triggering the recovery code, which is intended to ensure projects missing metadata are not lost. If you are willing I would appreciate some assistance debugging that issue once the release is out.

**Comment by RichardMarks** [comment] 2019-05-28 16:23
@shortercode Sure. Let me know when.

**Comment by shortercode** [comment] 2019-05-28 17:41
Thanks @RichardMarks I meant to send more details earlier but been having a fun time upgrading the build server this afternoon...

I added a new button to the settings menu in the last release "Download local browser saves", this will download the entire contents of your "local browser saves" as one zip file. Inside it will contain a series of files with UID values ( these are the projects themselves ) and a JSON file which contains the metadata ( names, folders, modified date ) related to the files. It's important that you perform this download BEFORE attempting to use the browser file system in any way, as this will trigger the validation and correction code and remove any errors.

If your okay with it could you to send me that JSON file, and a list of the filenames/sizes within the zip file so I can validate the state of your saves. Once you have downloaded the zip you are free to look at your browser saves, I expect one or more will have a name like "<GUID_HERE>_unknown.c3p". Other than that it will hopefully be intact.

**Comment by RichardMarks** [comment] 2019-05-28 18:16
@shortercode I'm not comfortable dumping data that contains unreleased intellectual property and process information to the public. However, I dumped the cases of the unknowns and checked their sizes

```
"name": "unknown_329d43f6cf6bbcbc", "size": 162K
"name": "unknown_8651ea36e6d27581", "size": 159K
"name": "unknown_97b50b73732f2e8e", "size": 177K
"name": "unknown_ce5099aba41088b0", "size": 3.2M
```

The size values came from the `ls -l` output of the zip contents, the name values from the json file.
I checked the size values against the sizes in the json, and they are accurate.

One thing I noticed is that the above four unknowns are duplicated in the json file. (There are two of each of those) and the `ext` field in the json for each of them is an empty string instead of a .c3p

**Comment by RichardMarks** [comment] 2019-05-28 18:18
@shortercode Each of the unknowns has a parent GUID of a `folder` item that has an empty string for its `name` field.

**Comment by shortercode** [comment] 2019-05-29 10:46
@RichardMarks that's totally understood, and thank you for your help looking into this.

There is some duplication in the JSON file which can make it hard to read. The top level array contains all entries in a flat list, but folder entries contain a reference to entries within their children array. In the browser we store the data in indexeddb which allows for multiple references to the same entry, but when it's serialized to JSON they become copies. I believe you would get a copy per folder depth ( including the root folder ) in this situation, so entries in the root will appear twice. I tweaked the structure a bit in r151 so that now folders only contain the GUID of the child, just to make the metadata easier to read when serialized like this. 

The entry list will contain a folder with no name, and no parent value which is the root folder. That's likely the one you saw.

Unfortunately if the name values in the JSON file had already been listed as "unknown_<GUID>" then the error recovery code has already been run, so it'll be hard to tell what state the metadata was originally in. Does it look like you have lost anything? Could you tell me anything about the 3 files that were broken? How they were saved, are the backup saves for a project, etc.?

**Comment by RichardMarks** [comment] 2019-05-29 16:57
@shortercode Thank you for explaining the duplicate entries. I do not notice anything lost upon inspecting the projects in question, (not sure if it is okay to detail the reverse-engineering processes I used to inspect them publicly) and given their nature, it would not be mission critical if there was anything lost. These `unknowns` are thankfully not projects that were in production, but experimental projects to test mechanics implementations.

That said, with the latest non-stable release of C3, should I expect to not see `the key is not defined` error anymore?

Also, is there any way to rollback to a previous version of C3 at any time? I have older projects which may be unusable in future versions, that I would want to export to local disk (should have done this sooner)

**Comment by RichardMarks** [comment] 2019-05-29 16:58
Oh, the projects were very likely saved to cloud google drive storage, and probably a local browser save following that.

**Comment by shortercode** [comment] 2019-05-29 17:20
I'm glad to hear that no lasting damage was done, although I find it frustrating that I've still yet to find a replication or even a reason for this corruption bug.

You shouldn't be seeing the "key is not defined" errors in r151, but the fix was kind of an educated guess. I worked back through potential areas where it could have been breaking and found a typo where a variable was defined as "id" but referred to as "key", seemed unlikely that another similar issue existed in the same area...

In terms of rolling back I'm not sure if you mean the editor or projects. The editor is easy enough, just choose a version from the [releases page](https://www.construct.net/en/make-games/releases). We only aim for backwards compatibility not forwards so local data may cause issues if it's from a newer version. I would recommend using an incognito window or similar if your going back to older version just in case you cause some variety of corruption. Rolling back projects is a little more involved, you can edit the internal c3proj file for a c3p to refer to pretend it's from an older release... But again we don't aim for forwards compatibility so the project may not be able to open in that version, so it depends how far you want to go back.

**Comment by RichardMarks** [comment] 2019-05-29 18:31
@shortercode Thanks, that makes complete sense regarding compatibility.

I'll let you know if I see any more errors popup moving forward.

When is the next stable release expected to be? I'm not too keen on using a beta in production.

**Comment by shortercode** [comment] 2019-05-30 14:56
Thanks again for your help @RichardMarks, I'll close this issue for now as I don't think there's any action to be taken.

Mmm it's likely going to be a little while until the next stable, we've only just really started the beta cycle. I imagine the progress with scripting will dictate when the next stable is. It's unfortunate that this issue didn't pop up until after we'd shipped the stable release, but not much to be done about it now.

Theoretically just opening a newer release and viewing the open browser save dialog should correct any issues with the browser file system, allowing an older release to view it again. But again, I can't really test this because I don't know how to break it, or what the break exactly is...

**Closed by shortercode** 2019-05-30 14:56 UTC
