### ISSUE TITLE
Tilemap > Open in popup window: Selection issue

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#1871] opened 2018-07-29 14:27 UTC
## Problem description

Trying to select a single tile is impossible, seems like it doesn´t recognize that I released the mouse button and it keeps dragging a selection over multiple tiles. Works fine in non-popout window.

Also some random crash happened when I toyed around by opening and closing various popup bars, no idea how I could reproduce it but maybe it helps so I just drop it in here.

## Attach a .c3p

🐙 

## Steps to reproduce

1. Open tilemap in popup window
2. Try to select a single tile by clicking it

## Observed result

A selection is beeing dragged even though the mousebutton is released

## Expected result

Select the tile I clicked.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r111 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 41 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

<details>
Error report information
Type: unhandled exception
File: https://editor.construct.net/r111/main.js, line 2, col 112218
Message: Uncaught TypeError: expected HTML element
Stack: TypeError: expected HTML element at Function.ǃI.ǃVG (https://editor.construct.net/r111/main.js:2:112224) at Function.ǃAg (https://editor.construct.net/r111/main.js:2:258211) at ǃI.ǃP.ǃW.ǃrJG.ǃrho (https://editor.construct.net/r111/main.js:2:264342) at a.ǃxH (https://editor.construct.net/r111/main.js:2:267721) at a.ǃr$R (https://editor.construct.net/r111/main.js:2:267313) at HTMLDocument.t.document.addEventListener (https://editor.construct.net/r111/main.js:2:266092) at HTMLDocument. (https://editor.construct.net/r111/main.js:2:195324)
Construct 3 version: r111
URL: https://editor.construct.net/index.html
Date: Sun Jul 29 2018 16:28:17 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 12320.4 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r111 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by shortercode** [comment] 2018-07-30 11:34
Popups have some interesting quirks and I'm not sure many people use them, so I'm not surprised that you found a crash. If you could find out how to reproduce it, that would be great, but if it's rare then don't sink a load of time into it.

The tilemap bar looks pretty broken to me when it's in a popout, but can confirm the cursor seems to be doing strange things as well. Assigning to @DiegoScirra as this is his area.

**Comment by Wackytoaster** [comment] 2018-07-30 17:10
Yeah I think that the popout isn´t used that much, but at least when it comes to tilemaps it gets pretty handy, especially if you intend to use bigger tilemaps. Beeing able to just shift it to a second screen would be great, but as you noticed it isn´t exactly useable right now :< I can live with that until the next stable release though ^^

**Comment by DiegoScirra** [comment] 2018-08-16 17:42
Fixed in r114

**Closed by DiegoScirra** 2018-08-16 17:42 UTC
