### ISSUE TITLE
Renaming Animation in Animation Editor Crashes C3

### ISSUE THREAD

**Issue by 4demon** [Scirra/Construct-3-bugs#5985] opened 2022-08-11 15:15 UTC
## Problem description

When I try to rename an animation, C3 crashes

## Attach a .c3p

https://1drv.ms/u/s!AlZkRk7KfdFFiu5lQ4NlPosv3FKErg?e=J70oDr

## Steps to reproduce

1. Create a new sprite object
2. Change the name from "Animation 1" to anything else

## Observed result

C3 crashes, giving me an error message.

## Expected result

The name should change

## More details

**Affected browsers/platforms:** 

**First affected release:** 

305. Didn't notice it in 304.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r305/main.js, line 900, col 29
Message: Uncaught TypeError: expected string
Stack: TypeError: expected string at P.l (https://editor.construct.net/r305/main.js:900:35) at https://editor.construct.net/r305/projectResources.js:1910:491 at bh (https://editor.construct.net/r305/main.js:368:408) at CCG.Sg.g.J.xeb.PV (https://editor.construct.net/r305/main.js:1356:225) at CCG.Sg.g.J.xeb.ME (https://editor.construct.net/r305/main.js:1365:445) at HTMLInputElement.Ur (https://editor.construct.net/r305/main.js:1350:303) at CCG.Sg.g.J.xeb.Vd (https://editor.construct.net/r305/main.js:1368:131) at HTMLInputElement.mD (https://editor.construct.net/r305/main.js:1354:400)
Construct version: r305
URL: https://editor.construct.net/r305/
Date: Thu Aug 11 2022 16:15:21 GMT+0100 (British Summer Time)
Uptime: 70.4 s

Platform information
Product: Construct 3 r305 (beta)
Browser: Chrome 104.0.5112.81
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 20
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment] 2022-08-11 15:47
Duplicate of #5974

**Closed by AshleyScirra** 2022-08-11 15:47 UTC
Labels: duplicate
