### ISSUE TITLE
Viewing Any Used Addon Results In Hard Crash

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-3-bugs#5405] opened 2022-01-29 08:36 UTC
Viewing Any Used Addon Results In Hard Crash

[View_Used_Addons_Debug.zip](https://github.com/Scirra/Construct-3-bugs/files/7963286/View_Used_Addons_Debug.zip)

## Steps to reproduce

1. Right Click Top Project Folder In Project Window
2. Cursor Over Tools
3. Select View Used Addons
4. Right click any addon available
5. Click find all references

## Observed result

Error

## Expected result

Shows the list of all references to the addon.

## More details

**Affected browsers/platforms:** 

Chrome

**First affected release:**  r280

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: d.nv.G is not a function @ TypeError: d.nv.G is not a function at Vhb (https://editor.construct.net/r280/components/bars/findReferencesBar/findReferencesBar.js:1:230)
Stack: TypeError: d.nv.G is not a function at Vhb (https://editor.construct.net/r280/components/bars/findReferencesBar/findReferencesBar.js:1:230)
Construct 3 version: r280
URL: https://editor.construct.net/r280/
Date: Sat Jan 29 2022 01:35:01 GMT-0700 (Mountain Standard Time)
Uptime: 76.5 s

Platform information
Browser: Chrome
Browser version: 97.0.4692.99
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 20
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
C3 release: r280 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7141)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment] 2022-01-31 19:05
Can't reproduce this one with the example project. Does it happen consistently?

**Comment by OneRepCloser** [comment] 2022-01-31 19:08
It happens 100% of the time for me (Just tried it again, on a brand new blank project), so I guess it's specific to my setup?

Here's my platform info:

Platform information
Browser: Chrome
Browser version: 97.0.4692.99
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 20
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
C3 release: r280 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 572 gb
Storage usage (approx): 225 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7141)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment] 2022-02-01 12:09
It works fine for me too. Do you have any browser extensions installed that may be interfering? Try disabling them one by one.

**Comment by OneRepCloser** [comment] 2022-02-03 16:16
I removed every single extension I have, started a new project. Added a sprite. Viewed addons, found all references for the sprite and the error still occurs.

**Comment by OneRepCloser** [comment] 2022-02-03 16:17
Error report information
Type: unhandled rejection
Reason: Error: d.nv.G is not a function @ TypeError: d.nv.G is not a function at Vhb (https://editor.construct.net/r281/components/bars/findReferencesBar/findReferencesBar.js:1:230)
Stack: TypeError: d.nv.G is not a function at Vhb (https://editor.construct.net/r281/components/bars/findReferencesBar/findReferencesBar.js:1:230)
Construct 3 version: r281
URL: https://editor.construct.net/r281/
Date: Thu Feb 03 2022 09:10:24 GMT-0700 (Mountain Standard Time)
Uptime: 11.8 s

Platform information
Browser: Chrome
Browser version: 97.0.4692.99
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 20
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
C3 release: r281 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7141)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by AshleyScirra** [comment] 2022-02-03 17:40
It works fine for me and unfortunately it is not possible to diagnose the problem from the crash report. Without a way to reproduce the problem ourselves it is not possible to investigate it. I'm afraid since the issue is not actionable, closing this issue. If you can find a more reliable way to reproduce the problem across devices, or identify a particular setting or configuration that is necessary for the problem to reproduce, please file a new issue including this information.

**Closed by AshleyScirra** 2022-02-03 17:40 UTC
Labels: can't reproduce
