### ISSUE TITLE
AJAX Request URL of project sometimes ends with "www.construct.net/[myFiles.json]"

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#4501] opened 2021-01-24 07:06 UTC
## Problem description

This is frankly quite hard to reproduce on my end but recently my projects that are using the AJAX request URL to fetch local project json files are getting errors. This happens in preview, not sure about export.

The error proceeds to stay even on multiple requests of varying json files. It continues to fail until I restart the preview or no json files are fetched.

Looking into f12 inspection, it just says [Construct 3] Failed to parse JSON. And I saw my json project files are in the URL: "www.construct.net/[myFiles.json]", which probably is the cause.

## Attach a .c3p

Here is an attached file that replicates how I coded in my own project. Again, it happens occasionally and it was not easy to get it to browser -> alert "fail" but it did.

I've also added the log file saved from DevTools F12 in Chrome when the bug happened.

Both the project and the log is in the archive file. 
[Archive.zip](https://github.com/Scirra/Construct-3-bugs/files/5861683/Archive.zip)

## Steps to reproduce

1. Open attached project file.
2. Preview.
3. Press space bar.

Note that quick succession spam on ESC and space bar might yield the error quicker. The event sheet I provided uses [when "space bar" is down] for this reason, not sure if it makes any difference. On my own project it's only one time function call.

## Observed result

Ajax returned error occasionally. Multiple occurrence on "_TriggerError" error 404.

## Expected result

Successfully fetch data consistently. 

## More details

**Affected browsers/platforms:** 
 Tested on both MacOS and Windows in Chrome and on NWJS.

**First affected release:** 
A few releases ago. Not sure which release it started but it was in late 2020.

## System details

<details><summary>View details</summary>

Below is from my Windows machine. The bug is also found on MacOS.

Platform information
Browser: Chrome
Browser version: 87.0.4280.141
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
C3 release: r230 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 70 gb
Storage usage (approx): 333 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2021-01-26 10:58
The demo project just gets stuck in a loop endlessly prompting "success" for me. I tried modifying it so it only requests upon pressing spacebar, so it doesn't get stuck in a loop, and I could repeatedly make requests all of which were successful.

I'm afraid as per the bug report guidelines unless we have a reliable way to reproduce the issue it's generally impossible to do anything about it. Maybe try clearing your browser cache in case that helps.

**Comment by jaydonteh** [comment] 2021-01-26 11:53
@AshleyScirra 

It only happens on certain preview instances. I was testing on a NWjs app using the desktop version of C3 earlier today (https://www.construct.net/en/forum/construct-3/general-discussion-7/construct-nw-js-desktop-app-131317) and it also appears to fail on certain previews. At this point I'm certain clearing my browser cache doesn't fix it. I've gotten the bug on my PC, MacOS and on Nwjs (on both PC and MacOS).

I'm really struggling to find what was causing the inconsistency. It only happens once in a while on certain preview instances. 

I've provided the other way to reproduce. And again, rare occasion bug.

Steps to reproduce:
1. Preview.
2. Press Space bar.
3. If it alerts "success", repeat step 1 (restart preview).

Is it possible to check on the reason why it would throw the error 404 on "_TriggerError"? This should be saying something right? It just routes it to "www.construct.net/test.json" which it should've called from local project folder.

I hope this can somehow shed some light on a possible fix or at least a small tweak to see if it still shows the 404 error.

**Comment by AshleyScirra** [comment] 2021-01-26 12:43
I tried 10 separate previews. Every single one worked successfully.

> Is it possible to check on the reason why it would throw the error 404 on "_TriggerError"?

It's not possible to check anything at all unless I can reproduce the problem.

Did you try clearing your browser cache? I suggested this previously, but your following comment did not mention it at all.

**Comment by jaydonteh** [comment] 2021-01-26 12:52
Does my browser cache affect the nwjs I just downloaded earlier today? I'm asking this because I assume my other PC's cache shouldn't have affected the nwjs I just downloaded because the bug did occur also on nwjs.

I've cleared my browser cache. Will reply if it happens again.

**Comment by AshleyScirra** [comment] 2021-01-27 16:36
Clearing the cache in NW.js is trickier. It's easiest just to focus on the browser for the purposes of this issue. Besides, NW.js is just another build of Chromium, the same browser engine as Chrome.

Since I don't have a way to reproduce I'm going to close this issue - I suspect it was something involving the cache anyway.

**Closed by AshleyScirra** 2021-01-27 16:36 UTC
Labels: can't reproduce
