### ISSUE TITLE
C3 Runtime multiplayer problem

### ISSUE THREAD

**Issue by Sowhenifoundfreenickname** [Scirra/Construct-3-bugs#2424] opened 2018-12-09 21:52 UTC
## Problem description

High cpu load and low fps for peer after few min after run project. Also sync object that have been removed from the host, peer is removed only after a few seconds. When you select C2 runtime both of these problems are solved

## Attach a .c3p

[Multiplayer.zip](https://github.com/Scirra/Construct-3-bugs/files/2661030/Multiplayer.zip)

## Steps to reproduce

1. Run remote preview
2.Copy link and run on two browser pages
3.wait 2-3 min and look on fps and cpu on peer page

## Observed result

Very high cpu for peer while host save low cpu. And objects are not removed from the peer immediately

## Expected result

normal cpu for peer

## First affected release

Long time ago was this problem. I opened topic #2175 but u dont belive me. I hope u now check and fix this bug.

## Affected browsers/platforms

* Chrome: yes
* Firefox: yes
*Android yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Sowhenifoundfreenickname** [comment] 2018-12-09 22:01
If after 1-2 min cpu will be low and fps high try waiting 5 min

**Comment by TheRealDannyyy** [comment] 2018-12-10 14:49
I can reproduce this too in both FireFox and Chrome (latest stable), using C3 R129 beta.

The browser console for the peer is giving out error messages, whenever objects are created. I assume the bug has something to do with that, since removing the collision check events and similar didn't help.

_Browser Console (Peer):_
![mp error](https://user-images.githubusercontent.com/15656049/49739710-d5f79f00-fc92-11e8-91d9-c40709ab5c9f.PNG)

**Comment by AshleyScirra** [comment] 2018-12-10 14:58
Ah, looks like there's a typo in one of the Multiplayer methods in the C3 runtime... should be fixed for the next release. It just missed the r130 release but the fix is trivial so will probably include in the next release even if it's a stable release.

**Comment by AshleyScirra** [comment] 2018-12-12 13:53
r131 includes a patch for this, can you check if the issue is resolved there?

**Comment by AshleyScirra** [comment] 2018-12-13 11:38
Thanks for confirming.

**Closed by AshleyScirra** 2018-12-13 11:38 UTC

**Comment by Nolram12345** [comment] 2020-10-06 13:44
This issues has appeared to be back, FPS decrease gradually as a peer in multiplayer.
