### ISSUE TITLE
Closing panels/windows on MacOS Chrome causes crashes

### ISSUE THREAD

**Issue by tommakesgames** [Scirra/Construct-3-bugs#844] opened 2017-09-26 18:32 UTC
## Problem description

Seriously, 1/2 of the times that I close a panel or window in Construct3 in Chrome on latest MacOS, it results in a browser crash, resulting in loss of work. This is working with Ghost Shooter Project, and other projects.

SEEMS TO HAPPEN MORE WHEN OFFLINE.

## Attach a .c3p

Using Ghost Shooter project to ensure it wasn't some of my own code.

## Steps to reproduce

1. Open a panel
2. Close it.
3. Crash.

## Observed result

See above.

## Expected result

Expected to close panel and return to main window (layout/event sheet etc.)

## Affected browsers

* Chrome: yes

Not tested on other browsers due to availability, plus I thought that I can only use Chrome to run this?

## System details

Browser gives generic error ("Aw, snap..").

<details><summary>View details</summary>

</details>

**Comment by shortercode** [comment] 2017-09-27 15:53
We now have support for Safari 11 ( macOS, iOS ), Firefox and Edge 16. Although Edge 16 isn't due for release until next month.

When you say the latest MacOS have you updated to high sierra? Given that it's only been out a few days I expect there's still some compatibility issues in applications. You might find it's more stable on chrome beta or chrome canary.

I've tried this and I haven't seen any stability issues when using it online or offline ( chrome 60.0.3112.113 64 bit - High Sierra 10.13 beta ), so I expect this is specifically related to your version of chrome/macOS etc.

**Comment by tommakesgames** [comment] 2017-09-27 16:37
Thanks for replying.

I'm on Chrome Version 59.0.3071.109 (Official Build) (64-bit).
Sierra 10.12.5.

**Comment by AshleyScirra** [comment] 2017-09-27 17:03
There was a bug in Chrome that crashed the tab if you closed a dialog with UI animations disabled in settings. It should be fixed in the latest version of Chrome, which is currently Chrome 61. Please update Chrome and check again.

**Comment by AshleyScirra** [comment] 2017-09-28 12:45
Based on use of Chrome 59, closing as duplicate of #580, which was caused by [this Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=739199) which should be fixed in Chrome 60+. Please keep your Chrome up-to-date!

**Closed by AshleyScirra** 2017-09-28 12:45 UTC

**Comment by tommakesgames** [comment] 2017-09-29 08:53
Thanks for your help.

Will see how 61 works out. 

On a Uni laptop, so heavily locked down and Chrome wasn't updating. Have changed it now so it auto-updates with permissions, but this is worth you keeping in mind as you roll out to schools and Unis (we use C3 for our Games Design course here).

**Comment by tommakesgames** [comment] 2017-11-05 20:29
New version of Chrome seems to work out well.
