### ISSUE TITLE
No audio on APK export, with Advanced Minification  r214

### ISSUE THREAD

**Issue by sizcoz** [Scirra/Construct-3-bugs#4181] opened 2020-09-04 19:01 UTC
## Problem description

Audio Does not work when Advanced Minification is chosen, and exported as an APK, if No Minification is chosen, then Audio works.

## Attach a .c3p

[audiotest.zip](https://github.com/Scirra/Construct-3-bugs/files/5176500/audiotest.zip)

## Steps to reproduce

1. Export the file to cordova signed release APK
2. Choose Advanced Minification
3. Try on Mobile

## Observed result

No Audio is played

## Expected result

Audio should play

## More details
The Audio works if you **do not** choose Advanced Minification.
My test Device is Motorola G6.
Exported to Android 7
R214 Beta

R 214 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2020-09-07 12:34
I can reproduce in r214, but it works in my development build for the next release. I suspect this is to do with a bug in Closure Compiler, and we've updated it to a new version with a fix for the bug in the next release, so I think this was caused by the Closure bug and it should be working in the next release. Marking to check when the release is out.

**Comment by AshleyScirra** [comment] 2020-09-08 14:52
r215 is now out, can you verify if it's working with that release?

**Comment by sizcoz** [comment] 2020-09-08 18:31
No, Sounds work but game freezes, Simple Minify works with same APK.

**Comment by AshleyScirra** [comment] 2020-09-10 16:01
This issue only describes a problem with audio and the provided project only attempts to play audio. If that now works, then the stated issue is solved, so closing. If there are other issues, please file them separately following all the guidelines, with minimal projects that demonstrate the specific problem.

**Closed by AshleyScirra** 2020-09-10 16:01 UTC
