### ISSUE TITLE
Crashing when opening a 3D object in animations editor

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#6587] opened 2023-02-19 19:01 UTC
## Attach a .c3p

Open any example project with 3D objects in it.

## Steps to reproduce

1. Open any project (including the example projects) containing at least one 3D object.
2. Attempt to open a 3D object in the animations editor.
3. Observe Construct crash, opening an "unhandled rejection" error report.

## Observed result

C3 crashes when opening up a 3D object!

## Expected result

3D objects can safely be opened.

## More details

**Affected browsers/platforms:**  Firefox, Chrome.

 r330

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information

Type: unhandled rejection
Reason: Error: Rx(...) is undefined @ PEa@https://editor.construct.net/r330/projectResources.js:140:248 SFa@https://editor.construct.net/r330/projectResources.js:175:182 ga@https://editor.construct.net/r330/projectResources.js:2109:131 R@https://editor.construct.net/r330/projectResources.js:1972:232 Dx/<@https://editor.construct.net/r330/projectResources.js:134:334
Stack: PEa@https://editor.construct.net/r330/projectResources.js:140:248 SFa@https://editor.construct.net/r330/projectResources.js:175:182 ga@https://editor.construct.net/r330/projectResources.js:2109:131 R@https://editor.construct.net/r330/projectResources.js:1972:232 Dx/<@https://editor.construct.net/r330/projectResources.js:134:334
Construct version: r330
URL: https://editor.construct.net/r330/
Date: Sun Feb 19 2023 12:55:38 GMT-0600 (Central Standard Time)
Uptime: 20.3 s
Platform information

Product: Construct 3 r330 (beta)
Browser: Firefox 110.0
Browser engine: Gecko
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2023-02-20 13:41
Duplicate of #6578

**Closed by AshleyScirra** 2023-02-20 13:41 UTC
