### ISSUE TITLE
VIDEO - R16 Problems with event sheet on other monitor.

### ISSUE THREAD

**Issue by IJCT95** [Scirra/Construct-3-bugs#42] opened 2017-04-07 21:28 UTC
https://www.youtube.com/watch?v=EULrN96VlnQ

i also found many problems working with two monitors regarding the event sheets, if you try to drag an event a similar bug will appear.

**Comment by AshleyScirra** [comment] 2017-05-08 15:43
Closing as duplicate of #154 which is a better report following the guidelines

**Closed by AshleyScirra** 2017-05-08 15:43 UTC
Labels: confirmed
