### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by shubhamrathi9** [Scirra/Construct-3-bugs#3057] opened 2019-06-19 18:05 UTC
Build Fails when GooglePlay & Advert Plugins are used at the same time

[Test](https://drive.google.com/file/d/17-1jBsx0qkIKf3U-c8jPQ1JbH4FAutXB/view?usp=sharing)

## Steps to reproduce

1.Export the project as android as debug apk, 
2.See the Log as Build Fails

## Observed result

Build Failed

## Expected result

Build Successful

## More details

Happens when Google Play & Advert Plugins are both used together

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error: Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=~~/androidSDK (DEPRECATED)
:wrapper

BUILD SUCCESSFUL

Total time: 0.935 secs
Subproject Path: CordovaLib
Subproject Path: app
> Task :app:preBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preDebugBuild UP-TO-DATE
> Task :CordovaLib:checkDebugManifest
> Task :CordovaLib:processDebugManifest
> Task :app:preDebugBuild
> Task :CordovaLib:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :CordovaLib:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript
> Task :app:checkDebugManifest
> Task :app:generateDebugBuildConfig
> Task :app:prepareLintJar
> Task :app:generateDebugSources
> Task :CordovaLib:compileDebugRenderscript
> Task :CordovaLib:generateDebugBuildConfig
> Task :CordovaLib:generateDebugResValues
> Task :CordovaLib:generateDebugResources
> Task :CordovaLib:packageDebugResources
> Task :CordovaLib:generateDebugRFile
> Task :CordovaLib:prepareLintJar
> Task :CordovaLib:generateDebugSources
> Task :CordovaLib:javaPreCompileDebug

> Task :CordovaLib:compileDebugJavaWithJavac

> Task :CordovaLib:processDebugJavaRes NO-SOURCE
> Task :CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
> Task :app:javaPreCompileDebug
> Task :app:mainApkListPersistenceDebug
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:mergeDebugResources
> Task :app:createDebugCompatibleScreenManifests
> Task :app:processDebugManifest
> Task :app:processDebugResources

> Task :app:compileDebugJavaWithJavac

> Task :app:compileDebugNdk NO-SOURCE
> Task :app:compileDebugSources
> Task :app:mergeDebugShaders
> Task :app:compileDebugShaders
> Task :app:generateDebugAssets
> Task :CordovaLib:mergeDebugShaders
> Task :CordovaLib:compileDebugShaders
> Task :CordovaLib:generateDebugAssets
> Task :CordovaLib:packageDebugAssets
> Task :app:mergeDebugAssets
> Task :app:validateSigningDebug
> Task :app:signingConfigWriterDebug
> Task :app:transformClassesWithDexBuilderForDebug

> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
34 actionable tasks: 34 executed

</details>

**Comment by shortercode** [comment] 2019-06-19 18:23
Thanks for filing the report. I think this caused by the latest version of google play services which was released on Monday.

Long story short they've changed one of their dependencies to something with the same name as the old one. As mobile advert is using the older version still ( due to a different upgrade issue in the previous major version ) there's 2 very similar things with the same name, and it the Java compiler is failing to resolve the difference.

I've actually been looking at getting the latest version of the admob SDK working today, which would resolve the issue, but part of the change needs to go out in a construct release so would have to wait until next week. However, I think I might be able to resolve it earlier by downgrading the SDK version for Google play.

**Comment by Tibith** [comment] 2019-06-19 19:28
Was about to file the same bug report! Thank you!

**Comment by shortercode** [comment] 2019-06-20 11:12
Okay dokes I've published `construct-play-games@1.0.21` which uses:

- `com.google.android.gms:play-services-games:17.0.0`
- `com.google.android.gms:play-services-identity:16.0.0`
- `com.google.android.gms:play-services-auth:16.0.1`

These are the newest version of the respective play services libraries that haven't swapped to the new dependency. `construct-mobile-advert@1.2.12` is using `com.google.android.gms:play-services-ads:16.0.0` which uses the older dependency, so doesn't need changing.

The build server will automatically use the newest maintenance release once I've put it on the whitelist, which I've just done. **So you should now be able to build successfully**.

I'm intending to publish a new version of construct-mobile-advert and construct-play-games for the next release which will use the latest versions of the play services libs. To prevent this causing an issue for r154 and below I'm releasing them as a new minor version ( which isn't auto-updated ), so you will have to build with r155 and above to see them.

**Comment by shortercode** [comment] 2019-06-20 17:27
Sounds like from the forum post that this has been resolved, so closing this issue.

**Closed by shortercode** 2019-06-20 17:27 UTC
Labels: need info

**Comment by shubhamrathi9** [comment] 2019-06-20 18:40
Thanks!

**Comment by shubhamrathi9** [comment] 2019-06-24 17:04
hi, @shortercode
this issue was resolved for me but today i build my game again (contains mobileadvert plugin) and it is showing me this log with build failed ### error...
[Log.txt](https://github.com/Scirra/Construct-3-bugs/files/3321845/Log.txt)

**Comment by shubhamrathi9** [comment] 2019-06-24 17:12
And this log with build failed when i build the Test File that i have attached in this bug report...
[Log for Test File Posted in Report.txt](https://github.com/Scirra/Construct-3-bugs/files/3321886/Log.for.Test.File.Posted.in.Report.txt)

**Comment by AshleyScirra** [comment] 2019-06-24 17:16
@shubhamrathi9 - if this was previously working then any new issue is probably not related, so you might want to file a new issue and follow all the guidelines again to ensure it can be investigated.

**Comment by shortercode** [comment] 2019-06-24 17:19
The test file fails because it's now a requirement to have the "Android application ID" property completed. Due to changes to the mobile advert SDK the client ID must be specified at build time now, if it's not the advert SDK will force crash your app when you start it.

If you fill in a placeholder value you will see the build complete correctly.

The first build log you showed me appears to be unrelated to this problem, something is failing to compile, but I can't see what without building the project myself. Either way that should be under a new issue as @AshleyScirra says.

**Comment by shubhamrathi9** [comment] 2019-06-24 17:25
Is there any hint of what object/plugin could be causing this in the log so that i can try to reproduce this bug in a new project?

**Comment by shortercode** [comment] 2019-06-24 17:36
I'm afraid not, you can make a guess at some of the plugins your using from the log but it does not include the actual line the compiler failed on. If you do a build and tell me the time your did it I can check the server log for the build to see if it has any more information.

**Comment by shubhamrathi9** [comment] 2019-06-24 18:01
ok, i build one just now can you check it please...

**Comment by shortercode** [comment] 2019-06-24 18:11
Okay thanks for helping me with that.

I found the log file for your build. It looks like the [social sharing](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin) plugin we are using isn't android X compatible. It's kind of all or nothing with Android X support, and to use the latest versions of G play and admob we need to use Android X.

I can look and see how active the maintainers of the plugin are, might be that they will be willing to fix it.  If not then we will probably have to fork the package and make the changes ourselves.

**Comment by shubhamrathi9** [comment] 2019-06-24 18:39
Yeah i removed it and it builds fine now, please try to fix it soon.
