### ISSUE TITLE
Hierarchy creating sprites with wrong Z order

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#5373] opened 2022-01-14 21:14 UTC
## Problem description

The hierarchy Head is creating the eyes (which are the children) underneath it instead of on top of it.

![Clipboard Image](https://user-images.githubusercontent.com/7268697/149586004-991eacb0-ff8a-499d-a3a5-611176d5578e.jpg)

## Attach a .c3p

[New project.zip](https://github.com/Scirra/Construct-3-bugs/files/7873229/New.project.zip)

## Steps to reproduce

1. make a sprite
2. make 2 different sprites
3. attach sprites at step 2 to sprite at step 1
4. create the action at start of layout for sprite at step 1 to be created with hierarchy 
5. run the project

## Observed result

You will notice the sprites at step 2 (they are children), which are created after the sprite at step 1, will spawn under the parent sprite.

## Expected result

I expect sprites at step 2 to be on top.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** 276.2
                         
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 97.0.4692.71
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 32
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
C3 release: r276.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 1006 gb
Storage usage (approx): 128 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7141)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by arcadesindo** [comment] 2022-01-16 02:39
Agreed, this also occured on my side, here are the screenshot.
![image](https://user-images.githubusercontent.com/28801633/149645204-57453f2b-ecdb-44df-a741-bc5e307adf84.png)

result
![image](https://user-images.githubusercontent.com/28801633/149645195-d829e399-8a09-404e-b7d0-fdb66e4128a5.png)

**Comment by JeFawk** [comment] 2022-01-18 13:29
It doesn't seem to respect layers either. I created a layer on top, put one eye on it.
When the objects get created via hierarchy, the eye is created on the parent's layer instead.

[New project with 1 eye on higher layer.zip](https://github.com/Scirra/Construct-3-bugs/files/7889380/New.project.with.1.eye.on.higher.layer.zip)

**Comment by DiegoScirra** [comment] 2022-01-20 14:32
This seems to be a regression introduced in r269. If you try this same project in the previous stable release, r268, it works properly.

**Comment by DiegoScirra** [comment] 2022-01-20 15:25
Looks like both issues will be fixed in the next beta.

**Closed by DiegoScirra** 2022-01-20 15:25 UTC
