### ISSUE TITLE
Sprite resize scale issue

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#3577] opened 2020-01-08 10:27 UTC
If you have several instances of a sprite in different sizes on different Layers (with different Scale/Parallax numbers - dont know if this is part of the issue)- then you resize the whole animation (all frames have the same size) then in some cases the Spritesize jumps back to 100%, it doesn't keep its scale value. Its not alway the case, I found no logic and its different from browser to browser.

## Attach a .c3p
[scale Problem.zip](https://github.com/Scirra/Construct-3-bugs/files/4034755/scale.Problem.zip)

## Steps to reproduce

1.doubleklick on Sprite 
2.Resize Image Canvas - 125 (half), keep aspect ratio, stretch, smooth, apply to whole animation
3.

## Observed result
some Sprites in the editor changed their X/Y scale to 100%

## Expected result
all sprites in the editor should keep their scale number

## More details

I made the Bugreport file in Chrome. I could reproduce it, then I wanted to make it a bit more clear with more different spritesizes. But then the Bug wasn't there anymore. I ve seen no logic, but went back to my original File. Chorme seems to handle it better than Firefox/ Safari

**Affected browsers/platforms:** 
-in Chrome, only one red sprite went back to 100%
-in Safary and Firefox all sprites went back to 100%

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 71.0
Browser engine: Gecko
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:71.0) Gecko/20100101 Firefox/71.0
C3 release: r181 (beta)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 10 mb (0.5%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560 OpenGL Engine
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 2048
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    WebM Vorbis (audio/webm; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)

Video information

Supported decode formats:

    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2020-01-08 14:35
Duplicate of #3576

**Closed** 2020-01-08 14:35 UTC
Labels: duplicate
