### ISSUE TITLE
Multitouch on some iOS Devices (iOS13 or IPad OS?) not working properly

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#3545] opened 2019-12-13 13:04 UTC
## Problem description

In my Game you swipe and hold on the left side to steer, on the right side you touch to jump.
In this constellation on some Devices the touches are not properly registered what renders the game unplayable

## Attach a .c3p
[iOS_multitouch_Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/3960755/iOS_multitouch_Bug.zip)

## Steps to reproduce

1.export game to Xcode, deduplicate/ recompress images, minify mode advanced
2.Open in xcode, update alerts to recommended settings, run it on attached Ipad IOS 13.3
3.Swipe around without releasing on the left side, touch on right side  (I couldnt reproduce the bug without swiping, just holding seems to work)

## Observed result

every touch the text updates to the touch ID. But in rare occasions nothing happens, but in the next touch the ID number jumps a bigger step, so somehow it knows that there was a touch before.

## Expected result

every touch should be registered

## More details

-i updated Xcode, iPadOS all to newest versions, Construct R179
-I could not reproduce the Bug with remote Preview
-on a iPhone iOS 12.4 it works fine
-observations:
on IPhone iOS 12.4 every touchID jumps on whole number, like 
861665418
861665419
etc
on iPad Os 13.3 often (not always, and on some restarts of the App its different):
-2124451143
-2124451142,0000002
-2124451141
-then the Bug touch, nothing happens
-2124451139 then it jumps two numbers

this Problem is always there, sometimes every 10th touch, sometimes it needs 20 touches

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 78.0.3904.108
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
C3 release: r179 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 28 gb
Storage usage (approx): 1003 mb (3.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-12-13 13:27
Construct just uses whatever touch events the system/browser fires. In general it has no control over that. I would guess in some circumstances iOS interprets a touch as a system-wide gesture which means the app doesn't see it, but I don't think there's anything we could do on our side about that. Assigning to @shortercode in case he has any ideas.

**Comment by shortercode** [comment] 2019-12-13 15:27
Nothing immediately comes to mind, other than what @AshleyScirra has already guessed about a touch event being consumed by the OS. If that is the case each new touch would increment but you don't see some the touch that is consumed by the OS.

There were some historical issues about cordova apps where the touch either started or ended off the edge of the screen. You wouldn't get the touch start/end event because it occurred on the boundary of the webview, and hence only got passed to the parent view instead. **I don't know if these still exist or not, it's pure speculation**. The 2 works around were to create/destroy touch events inside the move event if the touches array didn't match up with what you expected, or to manually create the event from the native code. I tried searching for this and found [this issue](https://issues.apache.org/jira/browse/CB-7958) from 2016 for iOS. It was closed as a won't fix, because they considered it a bug with the webview.

**Comment by bubbblebub** [comment] 2019-12-13 15:46
ok thanks for your answers. I hope with a future release of iOS the Problem will be solved again, as it works nice on a older System. Else I will find another way to steer the game, with taping, not touch and move, I think this works clean. Thanks for your help

**Comment by bubbblebub** [comment] 2019-12-19 08:49
a short update on this issue:
-I tested around with other methods to control my game and used a system where you have to tap a sprite to go left, an other to go right, and a third to jump. So just touch, no angle recognition, no speed recognition. It's better this way, but still does occasionally not trigger, I think as soon as two Fingers are simultaneously touching the device.

so for a multitouch Game where precision is demanded, it seems not to be possible to work at the current state of iOS 13

I have the alternative to use tilt to steer left and right which works clean with touch for jump. The only drawback: Each restart of the App the User has to give permission to access orientation, which gives an amateurish impression of the game

**Comment by shortercode** [comment] 2019-12-19 13:06
So I've been doing a bit of testing, the only odd thing I've found so far is that some of the ID's appear as floats instead of integers. Turns out that's just a quirk in our string concatenation code, there's some code which appear to be for limiting the number of decimal places that doesn't work in this situation because the ints are so large. Hence some of them are +/- 0.0000002.

If the value is -0.0000002 then you will get a sequence like:
- 2042120464
- 2042120465
- 2042120465.9999998 ( ~ 2042120465 )
- 2042120467

If you ignore the fractional part it looks like you are getting the same ID twice, then skipping one. But bare in mind this is only an issue with string concatenation, if you are using the value as a number then the value is correct.

I don't see any issues where the ID does't increment or skips values, and there doesn't appear to be any issues around touches moving off screen as far as I can tell.

@AshleyScirra I'm not sure if you want to look the string concat bug or not, I can provide you with more details if you like.

**Comment by AshleyScirra** [comment] 2019-12-19 13:45
Construct's string concatenation applies a slight amount of rounding to numbers, ironically to try to hide small rounding errors (e.g. printing 100 instead of 99.999999998), but in this case it actually seems to introduce them. This should be unrelated to this issue though and is solely cosmetic to the Text object.

**Comment by shortercode** [comment] 2019-12-19 15:48
@bubbblebub I don't seem to be able to reproduce any real loss of pointer events. Some gestures do trigger OS levels events, notably 3 finger swipes. However, you are more likely to accidentally close the app doing that than worry about a lost user interaction. It is remarkably difficult to use multi touch interactions and test them though, there's too much going on to reliably follow the order of changes. Sometimes users will interact in a different way and trigger an issue which you weren't aware of as well.

As @AshleyScirra said before if this works correctly on other devices, then it's likely an external issue which we can't do much about. Perhaps with a more precise replication it could be investigated further, but the culmination would likely be filing a bug with Apple.

**Closed by shortercode** 2019-12-19 15:48 UTC
Labels: can't reproduce

**Comment by bubbblebub** [comment] 2019-12-19 16:12
thanks for the further investigation - I made a bit more testing to be more precise: First I added a Sprite with two different colored frames that toggle each touch, so in case its just the text object that cant screen the small integers, at least the Sprite should change its color. (I will try to add the new file to this comment)

The Bug was unfortunately still there. When I just hold one Side, on the other I tapped, I counted up to 200 touches then I stopped, everything worked fine. When I just slightly started to move the Finger on the not tapping Side, the Bug appeared very quickly, at least every 10/15 times.

I will try to find another Testdevice with iOS 13, so I can tell you if it is probably just related to a specific Device/Generation..
[iOS_multitouch_Bug_v2.zip](https://github.com/Scirra/Construct-3-bugs/files/3984462/iOS_multitouch_Bug_v2.zip)

**Comment by AshleyScirra** [comment] 2019-12-19 16:23
As noted if it works correctly on any device, that generally indicates Construct's code is correct and there is a bug with the OS/platform on certain devices. The best approach is now likely to be to file a bug with Apple directly at: https://bugs.webkit.org/

**Comment by bubbblebub** [comment] 2020-02-03 22:22
just for the record if any other users run into this, I tested now on a second device with iOS 13, and there it works without problems. On a IPad ipad mlmv2ty/a with iOS 13.3 multitouch doesn't work in my case, on an old IPhone SE I found no problems.
