### ISSUE TITLE
Bug Lens 2 effect 

### ISSUE THREAD

**Issue by tuzke** [Scirra/Construct-3-bugs#3259] opened 2019-08-24 02:23 UTC
## Problem description
I was see that flipping issue when I was use Lens 2 effect 
## More details

**Affected browsers/platforms:** 

Chrome

## System details

PASTE HERE

**Comment by NoSoul8** [comment] 2019-08-26 11:40
As i can see this issue will go down due to lack of info, i will try to make the ticket a bit clearer, without creating a dupe. 

Lens 2 effect seems to be broken as of r162-2.
Here is a minimum repro c3p file. Lens 2 seems lost/has broken it's magnifying parameter.
Also, it ignores it's sprite form (e.g.circle) and works only for sprite square borders instead.
[lenstwo.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3540932/lenstwo.c3p.zip)

**Comment by AshleyScirra** [comment] 2019-08-27 11:57
This is a regression caused by the fix to #2121. The next release will revert the incorrect fix. Closing and reopening the original issue.

**Closed by AshleyScirra** 2019-08-27 11:57 UTC
