### ISSUE TITLE
Can't click- and drag event boxes in event sheet on Android

### ISSUE THREAD

**Issue by Guramannen** [Scirra/Construct-3-bugs#5805] opened 2022-06-21 18:48 UTC
## Problem description
On Android, using my galaxy tab s7 (also tested on Samsung s21 Phone) I can't drag-and drop event sheet boxes which makes it a hastle to work with.

Issue persists in both Mobile UI mode and the normal UI mode
Tried on browsers Chrome for android and Firefox for android, but issue persists
Tried running as app and directly in browser, and in full-screen mode and the issue persists
Tried using PC-mode in browser but the issue persists

- It seems to think I want to right-click when holding down on a event box to drag. If I try to just hold and drag quickly like I would on PC, nothing happens.

## Attach a .c3p
Any of your example projects would do since this isn't a project-specific issue

## Steps to reproduce

1. Start Construct
2. Load an example project
3. Open event sheet
4. Try to drag any of the event boxes to another spot

## Observed result

Nothing happens if I drag quickly, a sub menu (as if I right clicked) happens if i keep holding for longer

## Expected result

Drag and drop, like on PC

## More details
The issue is observable on Construct 3 editor on chrome and firefox for android

**Affected browsers/platforms:** 
Android, Chome/Firefox

**First affected release:** 
I've never seen it work.
I know the issue has been here for at least a year since that's when I bought this device and its keyboard (note, the issue is here wether I use a keyboard or not)

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 102.0.0.0
Browser engine: Chromium
Context: webapp
Operating system: Android
Operating system version: 12
Device type: mobile
Device pixel ratio: 2.125
Logical CPU cores: 8
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Linux; Android 12; SM-T970) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
C3 release: r293.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 64 gb
Storage usage (approx): 89 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Qualcomm
Renderer: Adreno (TM) 650
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_filter_anisotropic
EXT_texture_norm16
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2022-06-22 10:10
The mobile UI currently does not have a method for drag & drop implemented. This is a known limitation - it's not really a bug, it's the fact it needs to be implemented differently because dragging does scrolling and tap-and-hold does a context menu, so there needs to be some other way to do drag & drop that does not conflict with the existing interactions.

Closing this issue as it's not a bug; if you want to file this as a suggestion see this thread: https://www.construct.net/en/forum/construct-3/general-discussion-7/announcing-new-construct-161682

**Closed by AshleyScirra** 2022-06-22 10:10 UTC
Labels: enhancement, mobile
