### ISSUE TITLE
Issue with drawing canvas

### ISSUE THREAD

**Issue by eleanorjmorel** [Scirra/Construct-3-bugs#5413] opened 2022-02-01 21:42 UTC
## Problem description
Drawing canvas does not produce expected results

## Attach a .c3p
https://drive.google.com/file/d/1BCwP58kgXNKVF1d8DsM3bTvMikdA7si-/view?usp=sharing

## Steps to reproduce

1. click on one of the small 4 squares
2. click apply

## Observed result
source image is changed

## Expected result
image shouldn't have changed

## More details

image goes from this 
![image](https://user-images.githubusercontent.com/32940085/152056143-c559196b-e780-4a12-8549-96aa23a6354a.png)

to this
![image](https://user-images.githubusercontent.com/32940085/152056198-ec110cd3-d3c5-4c45-82b4-337d9e3ab0d8.png)

**Affected browsers/platforms:** 
chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 97.0.4692.71
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
C3 release: r281 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 251 gb
Storage usage (approx): 2.7 gb (1.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9676)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2022-02-03 12:20
I suspect this is a duplicate of #5288 which should be fixed in the next beta. The fix for that does appear to improve rendering in this case, but it's not clear what the final result is meant to look like - there are lots of options to click and images repeated in multiple places, and it's not clear which one you're using for the observed/expected results. Further the 'Paste object' code is exceptionally complicated and difficult to work with, and this project is too complicated to debug such complicated code for - if there is still an issue after the next beta you'll need to file an issue with the absolute minimum project possible - ideally a single event with just one or two actions.

**Closed by AshleyScirra** 2022-02-03 12:20 UTC
Labels: duplicate

**Comment by eleanorjmorel** [comment] 2022-02-03 15:23
ok thanks ashley ur the best

**Comment by eleanorjmorel** [comment] 2022-02-09 04:06
Wasn'T fixed in the latest update, but behavior has changed

https://drive.google.com/file/d/1AULQKsOvxitzBGt4GmhaIWVgXhhHfrXg/view?usp=sharing
the project just pastes an object into the drawing canvas and then loads the image back into the sprite, but every time it does it it gets altered, up to a certain point at 50% of it'S size where it then pastes unaltered


 https://youtu.be/zgsbzO1tGgQ

**Comment by AshleyScirra** [comment] 2022-02-09 11:19
Please file a new issue following all the guidelines with a minimal project - the fewer the events and objects, the more likely it can be fixed.
