### ISSUE TITLE
Loading Instance From As.JSON is Broken

### ISSUE THREAD

**Issue by Tarek200** [Scirra/Construct-3-bugs#5964] opened 2022-08-05 05:55 UTC
There is a problem with loading an instance from As.JSON that belonged to an instance that was in a Hierarchy.

Object1 
Object2

1-Object1 is a child of object2

2-Save the object1 Instance As.JSON in a variable then move this instance to a new position with his parent object2

3-Then Create a new object1 Instance and load it from the JSON that we just saved in the variable, it will load wrongly with issues: 

-It will not spawn on the location (X, Y) that were saved in the As.JSON
-It will Spawn instead in object2 position which was the Parent and also it will create the Hierarchy to object2 which it shouldn't.

I have been using R268 for a long time and it doesn't behave like this.

[Hierarchy BUG.zip](https://github.com/Scirra/Construct-3-bugs/files/9265622/Hierarchy.BUG.zip)

## Steps to reproduce

1. Open Project in R268 and hit Run  
2. Drag the red Object and watch
3. Open Project in R302 and hit Run  
4. Drag the red Object and watch

## Observed result

On R302

The instance that we create and load from As.JSON:
-Spawns in the wrong (X,Y) that were saved on the AsJSON
-And also it creates a Hierarchy to the red object which it shouldn't

## Expected result

The instance that we create and load from As.JSON:
-Spawns in the right (X,Y) that were saved on the AsJSON
-And also that it doesn't create a Hierarchy to any object

## More details

Chrome

Working great on r268
 But broken on R302

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 103.0.5060.134
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 447 mb (0.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Tarek200** [comment] 2022-08-05 09:10
I was looking to roll back to an earlier version as it totally broke my project and I cannot continue working with that bag and causality I found out that the problem started in R289 so I thought to update here the new info may help you.

**Comment by DiegoScirra** [comment] 2022-08-05 10:59
This was introduced when fixing #5590. Unfortunately I don't think both cases can work together at the same time.

If you look in the change log https://www.construct.net/en/make-games/releases/beta/r289, it's the bugfix that reads:

**Scene graph: recreate missing children when using 'Set from JSON'** 

The message is a little misleading, because it doesn't say that saving a child's JSON which is part of a hierarchy will also attempt to recreate it's parent when applied.

When saved, the child is also saving who it is attached to. When you create a new instance and set that JSON to it, it is recreating what was saved, and that includes being a child of another instance.

I don't know how much your project relies on the old behaviour, some possible workarounds would be to

1. Save the child before adding to the parent
or 
2. In the case of the child already being added to a parent, remove it, save, then add it back.

In both cases what you are doing is saving JSON which does not include any hierarchy information.

**Comment by Tarek200** [comment] 2022-08-06 06:24
Hi Diego Thanks for the info:

You know I literary have been since I opened this bug till now none stop trying to fix this issue and it all broken, hours to fix one side then another side is broken so I have been running on circles with something that shouldn't have been that hard to fix.
I have Been trying none stop the 
-Remove from Parent 
-Save AsJSON 
-Add back the child to the Parent

But not sure why it finds a way to recreate objects from Hierarchy destroying the whole Picking that I have as they are so many extra objects created messing up the whole logic.

This thing should never happen, if you guys need to add that feature you should have added a flag to agree to recreate the Hierarchy if it was any, to maintain backwards compatibility and avoid breaking all the Projects that are already set up with the old system as mine (((: this is so frustrating as we shouldn't have to go through this unnecessary. 
Normally a company shouldn't change things like this as you know it will brake all the projects.
I wasn't gonna make a big deal I tried to make the workaround of removing from Parent and adding back as the child and just move on with life but even that didn't work, it works on an empty project but it brakes on my main project and is really just one single loop so it shouldn't be hard for me to do this extra steps so not sure why is still braking and I cannot reproduce on an empty project and I cannot share mine, it looks like has some other bugs as the objects have many variables etc... 
Is it not possible to add a flag so we can choose if we wanna recreate the Hierarchy or not? 
That should have been the normal procedure in this situation.
Maybe add one more Action:
1-Set From JSON
2-Set From JSON+Hierarchy

Number one is the old system
Number two for people that need to load the Hierarchy with the JSON 

Or you could do the opposite:
Save object By two options:

1-Object.AsJSON
2-Object.AsJSON+Hierarchy

**Comment by DiegoScirra** [comment] 2022-08-08 19:30
My previous suggestion was just what I thought of the top of my head. I tried applying it with a more complex setup and there were a few issues. In the next beta it should be possible to work around this problem.

The idea is to isolate the instance you want to save with no hierarchy information, to do that you need to remove it from it's parent and also remove it's children so it is not linked to anything. When the saving is complete, you put everything back where it was and you should have JSON without any hierarchy information.

As for adding an option, that is something we really don't want to do. It seems pretty innocuous, I mean it's just an option, right? The problem is that it adds yet another little bit of complexity that in the future will just fall under "C3 jargon", which most people won't even know it exists, let alone know when it right to use it.

**Comment by DiegoScirra** [comment] 2022-08-09 14:06
Closing this as the old behaviour will not be enabled again. It was an oversight to begin with.

**Closed by DiegoScirra** 2022-08-09 14:06 UTC

**Comment by Tarek200** [comment] 2022-08-10 00:35
To begin with, this is not an oversight because you changed how the AsJSON feature is working so it's more appropriate to say that you guys Planned it.
As all the projects using R288 and lower if they are using the AsJSON with an object that was in a Hierarchy never saved the Hierarchy so you didn't have to count with extra objects that will be created when you load from JSON, so all the projects before R289 using that combo (AsJSON + Hierarchy) need to update their projects as they all will be broken. 
And to be honest, I don't see you that you guys are even sorry for that, I would spect some apology for your customers at the least, as I spent already 60 to 80 hours with this unnecessary.

And finally:
I tested today the r305 and my project is still broken!
So you can keep the bug close if you like as I will not spend any more time on this because is just getting very frustrating. As I explained in my above comment this should have never had to happen you should always aim to maintain backwards compatibility and not force users to go back and change their projects because a feature has changed the way it works.
