### ISSUE TITLE
Crash when converting format of every file in project

### ISSUE THREAD

**Issue by shortercode** [Scirra/Construct-3-bugs#663] opened 2017-08-03 11:23 UTC
## Problem description

Reported by user @Jau-Al.

> It looks like the images become incredibly heavy (more than 3mb) when converted to png while being exported. I made a copy of the project and tried to replace some of them and it exported.
> I saw there was an option to change the export format. There is a crash if I ask for a format change for every image file.

> I changes the export format to JPEG Q80 the largest images. They are 1920x1080px. (one frame at a time so C3 doesn't crash). Now it exports to android again :-).

## Attach a .c3p

Unable to share project for copyright reasons.

## Steps to reproduce

See description.

## Observed result

Editor crashes

## Expected result

Images to reformat

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: animation frame has no content @ Error: animation frame has no content at g.ǃpqk (https://editor.construct.net/r47/main.js:61:190683) at g.ǃwg (https://editor.construct.net/r47/main.js:61:194495) at new ǃpr.ǃTC (https://editor.construct.net/r47/main.js:71:38365) at Function.ǃp.ǃs (https://editor.construct.net/r47/main.js:2:204435) at Function.ǃlLm (https://editor.construct.net/r47/main.js:71:330832) at Function.n.ǃptP.ǃlAh (https://editor.construct.net/r47/main.js:71:338322) at e.ǃlOe.ǃlA$ (https://editor.construct.net/r47/main.js:71:185132) at e.ǃlOe.ǃlAM (https://editor.construct.net/r47/main.js:71:185237) at e.ǃlOe.ǃlAI (https://editor.construct.net/r47/main.js:71:185322) at e.ǃlOe.ǃlAT (https://editor.construct.net/r47/main.js:71:185415)
Stack: Error: animation frame has no content at g.ǃpqk (https://editor.construct.net/r47/main.js:61:190683) at g.ǃwg (https://editor.construct.net/r47/main.js:61:194495) at new ǃpr.ǃTC (https://editor.construct.net/r47/main.js:71:38365) at Function.ǃp.ǃs (https://editor.construct.net/r47/main.js:2:204435) at Function.ǃlLm (https://editor.construct.net/r47/main.js:71:330832) at Function.n.ǃptP.ǃlAh (https://editor.construct.net/r47/main.js:71:338322) at e.ǃlOe.ǃlA$ (https://editor.construct.net/r47/main.js:71:185132) at e.ǃlOe.ǃlAM (https://editor.construct.net/r47/main.js:71:185237) at e.ǃlOe.ǃlAI (https://editor.construct.net/r47/main.js:71:185322) at e.ǃlOe.ǃlAT (https://editor.construct.net/r47/main.js:71:185415)
Construct 3 version: r47
URL: https://editor.construct.net/index.html
Date: Thu Aug 03 2017 02:41:33 GMT+0200 (CEST)
Uptime: 1189.3 s

Platform information
Browser: Chromium
Browser version: 59.0.3071.109
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Linux
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/59.0.3071.109 Chrome/59.0.3071.109 Safari/537.36
C3 release: r47

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: NVIDIA Corporation
Renderer: GeForce GTX 1070/PCIe/SSE2
Major performance caveat: no
Maximum texture size: 32768
Point size range: 1 to 189.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment] 2017-08-04 09:27
The first thing I am wondering is if the crash was when setting the export format, or while exporting.

If it was while setting the export format, it must be a silly error. Only properties in the animation frame models change when you choose any of the options in the Export dialog of the Animations Editor. Nothing too complex there.

If it's crashing while exporting because it's running out of memory from trying to convert all the images in a large project, then that would be a substantially worse problem.

I'll check out the Animations Editor.

**Comment by Jau-Al** [comment] 2017-08-04 12:14
I found two problems : One when exporting my project without modifying anything (so big image files were in png format). It crashed while making the apk.
And then, when I saw the abnormal sizes in cordova export and tried to change the format of all pictures to jpg, it crashed too (most probably unrelated).
![capture d ecran de 2017-08-03 02-49-34](https://user-images.githubusercontent.com/15030964/28968133-d792bd16-791e-11e7-9c0c-788d3b167a94.png)

[crash-select-export-png.txt](https://github.com/Scirra/Construct-3-bugs/files/1200296/crash-select-export-png.txt)

[crash-export-android-0727-17:50.txt](https://github.com/Scirra/Construct-3-bugs/files/1200299/crash-export-android-0727-17.50.txt)

**Comment by DiegoScirra** [comment] 2017-08-04 13:23
The problem with the **Image Format** dialog of the Animations Editor has been solved. The fix will be available in r48.

**Comment by Jau-Al** [comment] 2017-08-05 17:04
The android export problem is always here and weird. I changed an image (en jpg to avoid size problems) and the intro video. Now the project cordova export size is 21.4Mb. And it crashes with the following output : 
[crash-export-android-0805-17:56.txt](https://github.com/Scirra/Construct-3-bugs/files/1202533/crash-export-android-0805-17.56.txt)

**Comment by Jau-Al** [comment] 2017-08-07 17:45
sorry but about the format change ...


<details><summary>View details</summary>
Error report information
Type: assertion failure
Message: should not be using shared sprite sheet collection here
Stack: Error at Function.ǃE.ǃOVP (https://editor.construct.net/r48/main.js:2:202201) at t (https://editor.construct.net/r48/main.js:2:171837) at window.assert (https://editor.construct.net/r48/main.js:2:172240) at A.ǃEKO (https://editor.construct.net/r48/main.js:61:159055) at A.ǃEbQ (https://editor.construct.net/r48/main.js:61:159375) at p.ǃOAs (https://editor.construct.net/r48/main.js:61:190839) at p.ǃEKe (https://editor.construct.net/r48/main.js:61:191866) at p.ǃEYn (https://editor.construct.net/r48/main.js:61:187461) at e.ǃAJD.ǃAyK (https://editor.construct.net/r48/main.js:71:186442) at e.ǃAJD.ǃAyC (https://editor.construct.net/r48/main.js:71:186740)
Construct 3 version: r48
URL: https://editor.construct.net/index.html
Date: Mon Aug 07 2017 19:39:25 GMT+0200 (CEST)
Uptime: 84.1 s

Platform information
Browser: Chromium
Browser version: 59.0.3071.109
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Linux
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/59.0.3071.109 Chrome/59.0.3071.109 Safari/537.36
C3 release: r48

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: NVIDIA Corporation
Renderer: GeForce GTX 1070/PCIe/SSE2
Major performance caveat: no
Maximum texture size: 32768
Point size range: 1 to 189.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</summary

**Comment by DiegoScirra** [comment] 2017-08-15 11:56
@Jau-Al Can you provide a project that reproduces the error you got when changing the image format?

It doesn't have to be the one you are working on, just an example that demonstrates the problem. I haven't been able to reproduce it myself.

**Comment by DiegoScirra** [comment] 2017-09-08 17:34
Figured out the reproduction steps

1) Create an empty project
2) Create an instance with a single image, such as a **Particles** or **9-Patch** plugin instances
3) Place it in the Layout View
4) In the Animations Editor, bring up the Export format dialog, set it to JPEG and hit OK
5) Crash

Notes:
Affect all instances with a single image, except for **Tiled Background** instances.
Only happens in production.

From what I understand, when you change the export format, sprite sheets are rebuilt, the problem is that these instances graphics are placed in a shared sprite sheet, and the sprite sheeting system expects them to be in their own sprite sheet.

**Comment by AshleyScirra** [comment] 2017-09-18 15:21
Can't reproduce in r56 following steps in last comment by @DiegoScirra. Does it still reproduce for you?

**Comment by AshleyScirra** [comment] 2018-01-12 14:02
This has been marked "can't reproduce" since September, so closing.

**Closed by AshleyScirra** 2018-01-12 14:02 UTC
Labels: can't reproduce
