### ISSUE TITLE
Sprite Font Not Wrapping

### ISSUE THREAD

**Issue by 8bitThirsty** [Scirra/Construct-3-bugs#818] opened 2017-09-18 21:45 UTC
## Problem description

Spritfont is not word wrapping.  My project doesn't meet your guidelines but I created a brand new layout (layout 1) with even sheet and a brand new spritefont object so you can see the issue because I cannot recreate this in a blank project.

[spritefont word wrap is broken.zip](https://github.com/Scirra/Construct-3-bugs/files/1312364/spritefont.word.wrap.is.broken.zip)

## Observed result

![wordwrapbroken](https://user-images.githubusercontent.com/11980014/30566145-ce0158f0-9c98-11e7-840a-5bd581e69588.gif)

## Expected result

I expected the words to wrap.

## Affected browsers

* Chrome: yes
Version 61.0.3163.91 (Official Build) (64-bit)

**Comment by AshleyScirra** [comment] 2017-09-19 10:58
Okay, this does make it clearer there's a problem - and it turns out there was a typo somewhere that only exposed an issue with certain arrangements of spritesheets (which is why it wouldn't reproduce in a new project). There's nothing wrong with the project file, it was just a weird bug, and it's fixed in the next build (out shortly).

In my defense these kinds of bugs are very rare, and we can easily close 10 reports in a day that are just mistakes in projects, so we're fully geared to get those out of the queue quickly. I suppose we can use the "reproduce in new empty layout" approach as an alternative if it is difficult to reproduce in a new project. I think this is the first case where this approach has been necessary to resolve a bug. Anyway, I apologise for any frustration caused, but at least it's fixed now.

**Closed by AshleyScirra** 2017-09-19 10:58 UTC

**Comment by 8bitThirsty** [comment] 2017-09-19 11:35
It happens.  I work in software testing so I'm very used to arguing with developers about bugs I find it's just a lot more frustrating when I'm paying instead of being paid.  Thanks for looking into it and in the future I will be more detailed when calling out issues I run into within my project due to its size.
