### ISSUE TITLE
Construct 3 crashes when opining 3d shape editor. r330

### ISSUE THREAD

**Issue by 725101** [Scirra/Construct-3-bugs#6548] opened 2023-02-16 16:41 UTC
## Problem description

When opening the 3d shape editor in construct, construct crashes. r330

## Attach a .c3p

Sorry but github gives me an error saying I am unable to attach the file type, so I zipped it.
[construc3.zip](https://github.com/Scirra/Construct-3-bugs/files/10758303/construc3.zip)

## Steps to reproduce

1. Open construct r330
2.  double click and add a 3d shape, or edit an existing one.

## Observed result

Construct 3 crashed

## Expected result

Able to open the 3d sprite editor

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** Worked in r329 but didn't in r330

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'Fk') @ TypeError: Cannot read properties of undefined (reading 'Fk') at PEa (https://editor.construct.net/r330/projectResources.js:140:253) at SFa (https://editor.construct.net/r330/projectResources.js:175:182) at Sy.pW.ga (https://editor.construct.net/r330/projectResources.js:2109:131) at yx.g.K.Sb.R (https://editor.construct.net/r330/projectResources.js:1972:232) at https://editor.construct.net/r330/projectResources.js:134:334
Stack: TypeError: Cannot read properties of undefined (reading 'Fk') at PEa (https://editor.construct.net/r330/projectResources.js:140:253) at SFa (https://editor.construct.net/r330/projectResources.js:175:182) at Sy.pW.ga (https://editor.construct.net/r330/projectResources.js:2109:131) at yx.g.K.Sb.R (https://editor.construct.net/r330/projectResources.js:1972:232) at https://editor.construct.net/r330/projectResources.js:134:334
Construct version: r330
URL: https://editor.construct.net/r330/
Date: Thu Feb 16 2023 08:38:52 GMT-0800 (Pacific Standard Time)
Uptime: 158.4 s

Platform information
Product: Construct 3 r330 (beta)
Browser: Chrome 108.0.5359.111
Browser engine: Chromium
Context: browser
Operating system: Chrome OS 15183.69.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel
Renderer: Mesa Intel(R) UHD Graphics (JSL)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by AshleyScirra** [comment] 2023-02-16 16:44
Duplicate of #6543, should already have been fixed for next beta.

**Closed by AshleyScirra** 2023-02-16 16:44 UTC
Labels: duplicate
