### ISSUE TITLE
System memory continually increasing after every preview (in chrome) on some projects. (results in crash)

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#1338] opened 2018-03-02 08:11 UTC
## Problem description

Open the slightly modded Glokar file linked.

All ive done is add an extra large texture and music files.

Note that the original Glokar File  (and Kiwi Story File )  behave similar but this seems to be a bit more obvious.

Also note,  i could not repro by adding large png files, large wav, large text project files to a new project so may be related directly to events.

## Attach a .c3p

[Lind to modded file on gdrive](https://drive.google.com/open?id=1qb1-HPU1CM4UUwBS-GgLQ73f7W7-OUt1)

## Steps to reproduce

1.  Open the linked file in C3 web (preferably on a machine with 8GB or less system ram
2.  Preview a level/layout multiple times,  up to at least 30+ to see effect
3.  Observe ram use

## Observed result

Ram use increases after every preview and does not recover fully for next preview, eventually system will run out of memory and crash the preview and editor

(note sometimes overall memory use will drop as system manages memory but eventually cannot manage.)

## Expected result

would like to be able to preview my project without worry of crash.

## Affected browsers

* Chrome: yes
* Firefox: no (or not obvious - unable to repo)
* Edge: no
* Safari: not tried 

## System details

no crash report and no dev tools warning as dev tool disconnected in this crash

<details><summary>View details</summary>

PASTE HERE

Platform information

MS Surface Pro 4 
Browser: Chrome
Browser version: 64.0.3282.186
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
C3 release: r85
Language setting: en-US

Browser support notes
Nothing is missing. Everything is OK!

**Comment by AshleyScirra** [comment] 2018-03-02 12:31
I can reproduce in Chrome 64 (stable), but it seems to be working correctly in Chrome 66 (canary). This seems to suggest it's a Chrome bug that has already been fixed, so we just need to wait for the fix to arrive on the stable channel.

Could you try using Chrome Canary (https://www.google.co.uk/chrome/browser/canary.html) and verify if the issue is resolved for you there?

**Comment by NetOneGames** [comment] 2018-03-02 13:56
Duuuuude.    Yeaaaaaaeeee.   Thanks. 

We good!

 All is right with the world once again.....

Cheers  .   Hope you enjoin the snow...  !

**Comment by AshleyScirra** [comment] 2018-03-02 14:01
OK, closing as a Chrome issue then. (I can't wait for some sunshine 😞)

**Closed** 2018-03-02 14:03 UTC
Labels: browser, chrome, external
