### ISSUE TITLE
Massive lag when using event sheets with a high number of events

### ISSUE THREAD

**Issue by jgp1971** [Scirra/Construct-3-bugs#1684] opened 2018-06-08 14:59 UTC
## Problem description

When an event sheet has a big number of events, the editor becomes pretty much unusable due to lag, be it scrolling, zooming, adjusting the size of columns or expanding and collapsing groups, even affecting opening the menu. Tried exporting my C2 project (which I can't share here) and the size of one of the event sheets makes working on C3 impossible.

The desktop version suffers from the same problem, but seems reduced.

## Attach a .c3p

[tests.zip](https://github.com/Scirra/Construct-3-bugs/files/2084863/tests.zip)

## Steps to reproduce

1. Import either the C2 or C3 example to C3, it's the same.
2. Collapse all groups. The editor performs ok.
3. Expand all groups, notice how the lag makes the editor unusable.
4. Import the C2 test to C2, collapse, expand and check the results.

## Observed result

The C2 editor is usable without any issues; the C3 editor is too laggy.

## Expected result

C3 editor keeps being usable.

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.79
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36
C3 release: r105 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.9 gb
Storage usage (approx): 164 mb (2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_get_buffer_sub_data_async
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2018-06-08 17:20
Duplicate of #445. This is essentially limited by the browser's layout performance.

**Closed by AshleyScirra** 2018-06-08 17:20 UTC
