### ISSUE TITLE
Problem with Save Game for C2 game exported with C3's Export Manager

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#3197] opened 2019-08-08 05:42 UTC
## Problem description

(This may or not be a C2 bug. If that's the case I'll post it on the C2 bug Forum if that's  the correct place)

On iOS, the game (Healer's Quest) crashes and restarts very often, while it is perfectly stable on low end Android devices. After investigating, I think it is due to the Save Game system. At first I thought it was due to the game switching layout during the save game action, but the problem also seems to happen when it's not the case.

## Attach a .c3p

I'll send you the files via email, as this is a commercially released game.
The bug only appears on iOS, so I can either invite you on Testflight, or you can purchase it on iOS and I'll fund you back.

## Steps to reproduce

1. Open the game Healer's Quest on iOS. If your device is new (iPhone X or later), the bug may not happen. The bug appears on iPhone 7 for example.
2. Win at least one fight
3. On the win screen press immediately the button to continue (lower right arrow) as soon as it appears. (please note waiting will also make the game crash sometimes, pressing immediately just seems to increase the chance of problems)

## Observed result

The game crashes and restarts. Sometimes the game was not saved.

## Expected result

The game should have been saved and continue correctly.

## More details

The problem appears mainly on the win screen (where the game is saved) but sometimes at other places too, namely on the load game screen. Which makes me think this is more than probably a save game problem.
Please note the exact same code works perfectly on relatively low-end Android devices.

I optimized the game as much as I could; but it didn't help.
Everyone complains about this, and the game's rating is currently around 1.5/5 on iOS... :-/ https://apps.apple.com/gb/app/healers-quest-pocket-wand/id1438098941

If not a bug, an advice on the way to solve this would be greatly appreciated. 

**Affected browsers/platforms:** 

Not a browser/editor problem, but I'm using Construct 2 r269 and the Export Manager of C3 r157.

**First affected release:** 

## System details

<details><summary>View details</summary>

Not related to the editor, but here is my platform information (I switched to r159)

Platform information
Browser: NW.js
Browser version: 0.30.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@004e06da11e10bb08f6632224ae48ee3d5f7b303) NWjs/0.30.0 (like Chrome/66.0.3359.117)
C3 release: r152 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 29 gb
Storage usage (approx): 1.8 gb (6.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-08-12 11:30
Are you able to verify if this issue occurs with the C3 runtime?

**Comment by RabloGames** [comment] 2019-08-15 05:09
Due to third party addons, the project doesn't work in C3. Actually it worked a few months ago, but due to recent problems with third party addons in the editor, I had to remove some of them to allow C3 to work properly (https://github.com/Scirra/Construct-3-bugs/issues/3157#issuecomment-513183719).
I tried reinstalling the addon, but it is still unsupported, so the project doesn't open anymore in C3. And even if it did, it still wouldn't be relevant as I use a content layout in this project and this is not a viable solution in C3. This means nearly all objects are put on a single layout, so the memory usage would be incredibly high.

So I'm afraid I'm not able to verify that. :-/

I can send you the C3 file if you wish, but you'll need a way to get rid of third party addons.

**Comment by AshleyScirra** [comment] 2019-08-15 13:11
The problem could be caused by a third-party addon. This is why our guidelines require providing a project that does not use any third-party addons, in order to prove the problem really is with Construct itself and not another addon developer's code. I'll leave this assigned to @shortercode to see if he can spot anything obvious but I would expect he will be unable to act on this. As ever the only way to reliably report issues that can be fixed is to follow all the guidelines.

**Comment by shortercode** [comment] 2019-08-19 12:22
@RabloGames If it's any reconciliation iOS reviews tend to be quite harsh compared to Android, even against the first party applications.

As someone who used to be involved in the development a complex and popular ( 1M+ on Play store ) application, you have to grow quite a thick skin... even then it's not healthy to dwell on the reviews too much, most people will only review if they love or hate it leaving a large number of happy in between users that you hear nothing from.

However, you obviously want to try and fix it if there's an major crash on iOS. At the moment we don't have much to go on. If you were perhaps more experienced with iOS development I would push you to investigate yourself... but that isn't really an option. I'm happy to spend a ( relatively small ) amount of time investigating your project to see if there is a problem. If it's in a first party plugin or the runtime then we can escalate it back to an issue. If it's a problem with something third party then whatever help I can offer will be limited.

If you could email the project to iain@scirra.com I will take a look and ask you further questions there.

**Closed by shortercode** 2019-08-19 12:22 UTC
Labels: iOS

**Comment by shortercode** [comment] 2019-08-21 13:16
Realised that Support has already forwarded me the project.

**Comment by RabloGames** [comment] 2019-08-31 12:52
Sorry for the long reply delay. I've just sent you the most up to date/optimized version of the project along with all third-party plug-ins I'm using, and my current opinion of what is causing the bug.
Thanks a lot for your help!

**Comment by shortercode** [comment] 2019-09-02 11:58
Thanks @RabloGames I'll put a note on my TODO list and try to take a look this week
