### ISSUE TITLE
Permanent loss of connection to the build service.

### ISSUE THREAD

**Issue by RedAndropulus** [Scirra/Construct-3-bugs#5204] opened 2021-11-07 21:56 UTC
## Problem description

It is not possible to export the Xcode project or Android APK due to the constant failure of the connection to the build server.
Regardless of whether it is an empty project, or there is something in the project.
I am exporting my project for iOS (xcode project) or Android (debugging APK) I get the message "waiting for the build" > after that sometimes I get the message "project preparation" > then I constantly get the message "connection to the build server is lost" after about 5-10 minutes.

Note that I had successful builds a couple of days ago using the process described below. I haven't changed anything about how I use the build service.

## Attach a .c3p
[testExport.zip](https://github.com/Scirra/Construct-3-bugs/files/7493160/testExport.zip)

## Steps to reproduce

1.In C3 > Menu > Project> Export > iOS > Choose xcode project
2.In C3 > Menu > Project> Export > Android> Choose Debug APK

## Observed result
Messages display saying 'waiting to build,  sometimes "project preparation"'.
After about 3-5 minutes: 'Build Service: Connection to the build server is lost''
![Screenshot_1](https://user-images.githubusercontent.com/29873728/140663101-a1bf3100-ffbe-4e7d-af57-b138514a308d.jpg)
And after 10 min
![Screenshot_2](https://user-images.githubusercontent.com/29873728/140663237-0320fc14-0966-4438-a64a-cc8bebf6bbb7.jpg)

## Expected result
I expected to receive the Xcode project or Android Debug APK.

## More details

**Affected browsers/platforms:** 
Chrome: Yes

**First affected release:** 
r268
## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 95.0.4638.69
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
C3 release: r268 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 140 gb
Storage usage (approx): 266 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_draw_instanced_base_vertex_base_instance
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_multi_draw_instanced_base_vertex_base_instance
WEBGL_video_texture
WEBGL_webcodecs_video_frame
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2021-11-08 12:46
Duplicate of #5197

**Closed by AshleyScirra** 2021-11-08 12:46 UTC
Labels: duplicate
