### ISSUE TITLE
Crash when deleting object (no repro)

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#2482] opened 2018-12-30 20:29 UTC
## Problem description

Crashed when I tried to delete an object. A lot of Ctrl+Z was involved. Posting crashlog just in case it helps, but I can´t repro it. What I remember doing was deleting a family with a behavior (that only contained said object) then deleting that object.

## Steps to reproduce

1.
2.
3.

## Affected browsers/platforms

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: object instance does not have associated behavior instance @ Error: object instance does not have associated behavior instance at window.ǃwo.ǃXS (https://editor.construct.net/r131/main.js:81:132257) at i.ǃulJ (https://editor.construct.net/r131/main.js:81:213055) at n.ǃulJ (https://editor.construct.net/r131/main.js:81:160534) at n.ǃus (https://editor.construct.net/r131/main.js:81:59610) at n.ǃus (https://editor.construct.net/r131/main.js:81:151376) at window.ǃoF.ǃsK (https://editor.construct.net/r131/components/bars/projectBar/projectBar.js:1:10267)
Stack: Error: object instance does not have associated behavior instance at window.ǃwo.ǃXS (https://editor.construct.net/r131/main.js:81:132257) at i.ǃulJ (https://editor.construct.net/r131/main.js:81:213055) at n.ǃulJ (https://editor.construct.net/r131/main.js:81:160534) at n.ǃus (https://editor.construct.net/r131/main.js:81:59610) at n.ǃus (https://editor.construct.net/r131/main.js:81:151376) at window.ǃoF.ǃsK (https://editor.construct.net/r131/components/bars/projectBar/projectBar.js:1:10267)
Construct 3 version: r131
URL: https://editor.construct.net/r131/index.html
Date: Sun Dec 30 2018 21:27:18 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 7515.4 s

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r131 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment] 2019-01-03 12:05
Mmmm I remember seeing a crash that looked vaguely similar a few months back. I'll assign to @AshleyScirra he might remember it or be able to divine the cause.

**Comment by AshleyScirra** [comment] 2019-01-07 10:57
Unfortunately the crash report is not useful in this case - it just shows it crashing when trying to delete something. Closing, please file again if you can find steps to reproduce.

**Closed by AshleyScirra** 2019-01-07 10:57 UTC
Labels: no repro
