### ISSUE TITLE
Error on minify script on c3 runtime export

### ISSUE THREAD

**Issue by igalencar** [Scirra/Construct-3-bugs#1873] opened 2018-07-30 14:23 UTC
## Steps to reproduce

1.
2.
3.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment] 2018-07-30 14:32
I believe this is a known issue, due to issues with the export pipeline the C3 runtime is currently always minified. The minifier in the editor cannot reminify the code, so the export fails when it is enabled.

Even if it didn't fail it wouldn't produce a smaller export at the moment anyway.

**Comment by AshleyScirra** [comment] 2018-08-06 11:28
Duplicate of #1844

**Closed by AshleyScirra** 2018-08-06 11:28 UTC
