### ISSUE TITLE
New Sub-Group Not Created Bug (Using The G Keyboard Shortcut)

### ISSUE THREAD

**Issue by LukeNecklace** [Scirra/Construct-3-bugs#2611] opened 2019-02-13 08:07 UTC
## Problem description

Using the keyboard shortcut G will not create a sub-group on the event sheet if code exists somewhere in the group.

## Attach a .c3p

https://www.dropbox.com/s/y5ac5sw867hsx08/Event%20Sheet%20New%20Sub-Group%20Not%20Created%20Bug.c3p?dl=0

## Steps to reproduce

1. Highlight one of the primary groups with code in it.
2. Press G on your keyboard and fill out the dialogue and press OK.
3. Go find the sub-group you just made. I bet you can't.

## Observed result

No sub-group gets made.

## Expected result

I expected the new sub-group to be added at the bottom of the sub-groups for the next level down.

## More details

**Affected browsers/platforms:** Chrome.

**First affected release:** I have always noticed that construct 3 does this but the current version it is happening on is r137. I just haven't had a lot of time to report it, sorry.

## System details

<details><summary>View details</summary>

https://www.dropbox.com/s/y5ac5sw867hsx08/Event%20Sheet%20New%20Sub-Group%20Not%20Created%20Bug.c3p?dl=0
</details>

**Comment by AshleyScirra** [comment] 2019-02-14 13:13
Can't reproduce anything wrong here. It looks identical to #2612. At step 3, the group expands and the contents are highlighted, except for a new sub-group added near the end, which is the same as what happens in #2612. Closing as duplicate of that issue.

**Closed by AshleyScirra** 2019-02-14 13:13 UTC
Labels: can't reproduce, duplicate

**Comment by LukeNecklace** [comment] 2019-02-14 14:44
That's weird, it's now working for me. If I see this happening again where groups are not being created I will look closer at what's going on. I'll keep an eye out anyway and try to replicate it 100% if it happens again.

Also to point out this is not a duplicate of my last issue. The last issue was related to groups being created but disorganising upon created. This issue is related to groups not being created at all. For some reason it seems to be working in my sample project again which is what's confused you. I'm not sure how it consistently not working before and now it is.
