### ISSUE TITLE
Preview shows blank layout

### ISSUE THREAD

**Issue by Dimostic** [Scirra/Construct-3-bugs#257] opened 2017-05-18 20:51 UTC
## Problem description
All attempts to preview layouts result in a blank layout screen
*Enter a concise description of your problem here*

## Attach a .c3p
[MOBILE PALPATE MD (2).zip](https://github.com/Scirra/Construct-3-bugs/files/1012374/MOBILE.PALPATE.MD.2.zip)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*
I expected to see all elements of my game and I should be able to play the game as developed
## Affected browsers

* Chrome: yes/no yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details
HP notebook Windows 10
*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment] 2017-05-18 21:33
@Dimostic thanks for posting

**Comment by AshleyScirra** [comment] 2017-05-19 14:23
The project has a loader layout enabled, so it looks like a duplicate of #245.

**Closed by AshleyScirra** 2017-05-19 14:23 UTC

**Comment by Dimostic** [comment] 2017-05-19 19:32
Resolved using suggestion.
Thanks
