### ISSUE TITLE
(C2 and C3) Touch events become stuck on Android

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#1639] opened 2018-05-30 02:56 UTC
## Problem description

In a fast-paced game with on-screen virtual buttons, when pressing/tapping quickly on the screen, touch events become "stuck". 
"Is in touch" becomes always true, TouchCount property returns 1 or more.

## Attach a .c3p

Very simple project to demonstrate the issue:

[TouchBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2052208/TouchBug.zip)

## Steps to reproduce

1. Run remote preview on Android device
2. Start tapping the screen quickly and chaotically using several fingers 

## Observed result

After a few seconds you'll see that one or few "touches" become stuck and don't disappear from the screen.
See this photo:
![touchbug](https://user-images.githubusercontent.com/36763350/40696218-469ad9b2-6408-11e8-8d76-05669fcd0579.JPG)

## Expected result

This should not happen.

## Affected browsers

* Browsers on PC: no
* Chrome on Android: yes

Tested on several phones and tablets.
The same issue happens with Construct 2.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r98 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 127 gb
Storage usage (approx): 45 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

The Clipboard API is not supported. Some clipboard features may be unavailable.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by wilsonpho** [comment] 2018-05-30 09:12
I built debug APKs and came across the same issue on my tablet and phone - touch controls get stuck.

**Comment by AshleyScirra** [comment] 2018-05-30 10:37
Can't reproduce on a HTC 10 running Android 8, nor a Samsung Galaxy Tab S2 running Android 5.

The code behind touches is really very simple. We add a touch when the browser tells us a touch started, and we remove the touch when the browser tells us the touch ended. In the past we've had similar "touch left behind" bugs that were caused by either the touch input driver, Android OS, or Chrome - since these are what pass the touch start/end messages along to the page. If the system fails to pass along a "touch end" message then the page gets stuck with a left-behind touch which it still thinks is down. So I think the most likely cause is a bug in some other part of the system that is losing a touch end event somehow. Maybe the best we can do is add some kind of hack where inactive touches are removed after a timeout or something, but that could impact legitimate apps that expect users to hold touches for a long time.

**Comment by dop2000** [comment] 2018-05-30 13:38
Hi Ashley,
Maybe clearing stuck touches after a timeout is not a bad idea. 
This bug only happens with multiple touches, and it's almost impossible for a human to keep holding one finger at the exact same position on the screen, while touching the screen with other fingers.

So if some touch has not changed position after, say, 2 seconds, you can mark it as "suspicious" and wait for a new touch. After a new touch has ended while the suspicious touch is still active and still hasn't changed screen coordinates, you can safely assume that it got stuck and remove it.

Even if you clear stuck touches after 5 seconds, it will still be better than nothing. Because right now the only way to get rid of a stuck touch is to restart the app, which is a serious problem...

**Comment by dop2000** [comment] 2018-05-30 13:57
By the way, when I preview this project in Firefox on PC, I can reproduce this problem extremely easily - when I tap the screen with my fingers, within 1 seconds I get all about 10 stuck touches..

**Comment by wilsonpho** [comment] 2018-06-11 06:02
Hi Ashely,

Is this "issue" closed? After around 10 mins of play, the touch controls get stuck and the player just moves to the edge of the screen. Only after I close the game will the controls work again. I have been able to recreate this same issue many times, over a dozen actually, on my tablet and phone (with debug APK).

Plus, I don't even have to press on the buttons chaotically, they just eventually get stuck eventually.

Thanks!
Wil


[Spelling Runner Outdoors.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2088825/Spelling.Runner.Outdoors.c3p.zip)

**Comment by SnipG** [comment] 2018-06-13 07:37
I did some testing and reported the issue here:  https://bugs.chromium.org/p/chromium/issues/detail?id=851986&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

On c3 it is better not to use touch.count but variable, any touch start add 1, any touch end subtract 1. Variable version somehow fixes itself, when touches start to bug and you need touch count. Variable method is still bugged, but works better as it corrects itself.

**Comment by dop2000** [comment] 2018-06-13 08:56
@SnipG, the problem with these stuck touches is that they never trigger "On Touch end" event. Also, if you have "Is in touch" or "Is touching object" conditions in your code, they will always remain true.

**Comment by SnipG** [comment] 2018-06-13 09:31
in my test they do trigger on touch end etc. It works a bit better if screen is covered with sprite background. Test my example: 
[Test021.zip](https://github.com/Scirra/Construct-3-bugs/files/2097522/Test021.zip)

**Comment by AshleyScirra** [comment] 2018-06-18 14:21
Closing since this appears to be a Chrome issue on certain devices as filed at: https://bugs.chromium.org/p/chromium/issues/detail?id=851986
The issue will be followed up there. Thanks for filing a minimal repro with Google, looks like they can reproduce it so they should be on the case soon.

**Closed by AshleyScirra** 2018-06-18 14:21 UTC
Labels: Android, can't reproduce, external

**Comment by wilsonpho** [comment] 2018-06-18 15:01
How is this just a chrome issue when the the debug apk that i created in C3 and downloaded to my tablet and phone is having the same issue?

**Comment by AshleyScirra** [comment] 2018-06-18 15:06
Android apps use Cordova which uses the same Chromium engine to render the app in a webview.
