### ISSUE TITLE
Duplicating any Layout Crashes C3 in NWjs version

### ISSUE THREAD

**Issue by corlenbelspar** [Scirra/Construct-3-bugs#2809] opened 2019-04-04 10:00 UTC
## Problem description

Trying to duplicate a layout of any kind, including a blank one, crashes Construct 3.

## Attach a .c3p

[https://drive.google.com/open?id=1A9uiKzCzP5oS72yJ_FAjo8qbVGT008rj](https://drive.google.com/open?id=1A9uiKzCzP5oS72yJ_FAjo8qbVGT008rj)

## Steps to reproduce

1. Duplicate the empty layout I made in the new project I did absolutely nothing with.

## Observed result

The editor crashed.

## Expected result

The layout should've been duplicated.

**Affected browsers/platforms:** NWjs

**First affected release:** r143

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Function.ǃx (https://editor.construct.net/r143/main.js:2:94339) at t.ǃNH (https://editor.construct.net/r143/main.js:81:47706) at a.ǃNH (https://editor.construct.net/r143/main.js:81:255183) at https://editor.construct.net/r143/components/bars/projectBar/projectBar.js:1:30971
Stack: TypeError: unexpected type at Function.ǃx (https://editor.construct.net/r143/main.js:2:94339) at t.ǃNH (https://editor.construct.net/r143/main.js:81:47706) at a.ǃNH (https://editor.construct.net/r143/main.js:81:255183) at https://editor.construct.net/r143/components/bars/projectBar/projectBar.js:1:30971
Construct 3 version: r143
URL: https://editor.construct.net/r143/
Date: Thu Apr 04 2019 03:50:25 GMT-0600 (Mountain Daylight Time)
Uptime: 8.1 s

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r143 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by SalmanShhh** [comment] 2019-04-04 23:11
can confirm, had to downgrade to not be effected in the desktop version.

**Comment by AshleyScirra** [comment] 2019-04-05 11:09
Closing as duplicate of #2781

**Closed by AshleyScirra** 2019-04-05 11:09 UTC
