### ISSUE TITLE
r141-2 Crash report

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-3-bugs#2732] opened 2019-03-13 18:01 UTC
Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃtaj' of null @ TypeError: Cannot read property 'ǃtaj' of null at i.ǃN (https://editor.construct.net/r141-2/main.js:2:458014) at window.ǃki.ǃgx (https://editor.construct.net/r141-2/components/bars/zOrderBar/zOrderBar.js:1:6846) at window.ǃki.ǃgh (https://editor.construct.net/r141-2/components/bars/zOrderBar/zOrderBar.js:1:5275) at window.ǃki.ǃJz (https://editor.construct.net/r141-2/components/bars/zOrderBar/zOrderBar.js:1:8130) at Array.ǃkF (https://editor.construct.net/r141-2/components/bars/zOrderBar/zOrderBar.js:1:488) at ǃt.Event.ǃJPS.ǃJPA (https://editor.construct.net/r141-2/main.js:2:212102) at window.ǃhG.dispatchEvent (https://editor.construct.net/r141-2/main.js:2:209970) at window.ǃhG.ǃSw (https://editor.construct.net/r141-2/components/editors/layoutView/layoutView.js:1:48017) at window.ǃJr.ǃIf (https://editor.construct.net/r141-2/components/editors/layoutView/layoutView.js:1:27489) at window.ǃJr.ǃxp (https://editor.construct.net/r141-2/components/editors/layoutView/layoutView.js:1:27468)
Stack: TypeError: Cannot read property 'ǃtaj' of null at i.ǃN (https://editor.construct.net/r141-2/main.js:2:458014) at window.ǃki.ǃgx (https://editor.construct.net/r141-2/components/bars/zOrderBar/zOrderBar.js:1:6846) at window.ǃki.ǃgh (https://editor.construct.net/r141-2/components/bars/zOrderBar/zOrderBar.js:1:5275) at window.ǃki.ǃJz (https://editor.construct.net/r141-2/components/bars/zOrderBar/zOrderBar.js:1:8130) at Array.ǃkF (https://editor.construct.net/r141-2/components/bars/zOrderBar/zOrderBar.js:1:488) at ǃt.Event.ǃJPS.ǃJPA (https://editor.construct.net/r141-2/main.js:2:212102) at window.ǃhG.dispatchEvent (https://editor.construct.net/r141-2/main.js:2:209970) at window.ǃhG.ǃSw (https://editor.construct.net/r141-2/components/editors/layoutView/layoutView.js:1:48017) at window.ǃJr.ǃIf (https://editor.construct.net/r141-2/components/editors/layoutView/layoutView.js:1:27489) at window.ǃJr.ǃxp (https://editor.construct.net/r141-2/components/editors/layoutView/layoutView.js:1:27468)
Construct 3 version: r141.2
URL: https://editor.construct.net/r141-2/
Date: Wed Mar 13 2019 14:56:47 GMT-0300 (hora estándar de Argentina)
Uptime: 5282.9 s

Platform information
Browser: Chrome
Browser version: 72.0.3626.121
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
C3 release: r141.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon(TM) RX 460 Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by DiegoScirra** [comment] 2019-03-13 19:09
Duplicate of #2730, already fixed.

**Comment by AshleyScirra** [comment] 2019-03-15 11:42
Should be fixed in r141.3.

**Closed** 2019-03-15 11:42 UTC
Labels: duplicate
