### ISSUE TITLE
C3 Crashes when closing the Timeline window while Timeline is playing

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5013] opened 2021-08-12 09:42 UTC
## Problem description

Crash when closing the timeline window while timeline is playing

## Attach a .c3p

[Bug TL.zip](https://github.com/Scirra/Construct-3-bugs/files/6974381/Bug.TL.zip)

## Steps to reproduce

1. Open attached project
2. Click play in the timeline window to preview the animation 
3. Close the timeline window while it is playing

## Observed result

Crash

## Expected result

Animation keeps playing, without crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information

Type: unhandled rejection
Reason: Error: this.we() is null @ INa@https://editor.construct.net/r251-2/components/bars/timelineBar/timelineBar.js:7:128 vZa@https://editor.construct.net/r251-2/components/bars/timelineBar/timelineBar.js:7:207 el@https://editor.construct.net/r251-2/components/bars/timelineBar/timelineBar.js:12:430 c6@https://editor.construct.net/r251-2/components/bars/timelineBar/timelineBar.js:8:290 A@https://editor.construct.net/r251-2/components/bars/timelineBar/timelineBar.js:5:411 this.vCa@https://editor.construct.net/r251-2/main.js:2048:237 Wfd@https://editor.construct.net/r251-2/main.js:432:387 dispatchEvent@https://editor.construct.net/r251-2/main.js:428:135 Bf@https://editor.construct.net/r251-2/main.js:717:411 Bf@https://editor.construct.net/r251-2/main.js:728:286 Bf@https://editor.construct.net/r251-2/main.js:747:273 Ox@https://editor.construct.net/r251-2/main.js:740:253 xTb@https://editor.construct.net/r251-2/main.js:748:469 this.Cs.onclick@https://editor.construct.net/r251-2/main.js:745:305 Jc@https://editor.construct.net/r251-2/main.js:1222:185 this.lc@https://editor.construct.net/r251-2/main.js:1221:318
Stack: INa@https://editor.construct.net/r251-2/components/bars/timelineBar/timelineBar.js:7:128 vZa@https://editor.construct.net/r251-2/components/bars/timelineBar/timelineBar.js:7:207 el@https://editor.construct.net/r251-2/components/bars/timelineBar/timelineBar.js:12:430 c6@https://editor.construct.net/r251-2/components/bars/timelineBar/timelineBar.js:8:290 A@https://editor.construct.net/r251-2/components/bars/timelineBar/timelineBar.js:5:411 this.vCa@https://editor.construct.net/r251-2/main.js:2048:237 Wfd@https://editor.construct.net/r251-2/main.js:432:387 dispatchEvent@https://editor.construct.net/r251-2/main.js:428:135 Bf@https://editor.construct.net/r251-2/main.js:717:411 Bf@https://editor.construct.net/r251-2/main.js:728:286 Bf@https://editor.construct.net/r251-2/main.js:747:273 Ox@https://editor.construct.net/r251-2/main.js:740:253 xTb@https://editor.construct.net/r251-2/main.js:748:469 this.Cs.onclick@https://editor.construct.net/r251-2/main.js:745:305 Jc@https://editor.construct.net/r251-2/main.js:1222:185 this.lc@https://editor.construct.net/r251-2/main.js:1221:318
Construct 3 version: r251.2
URL: https://editor.construct.net/
Date: Thu Aug 12 2021 11:39:41 GMT+0200 (GMT+02:00)
Uptime: 37.1 s
Platform information

Browser: Firefox
Browser version: 91.0
Browser engine: Gecko
Context: browser
Operating system: Windows
Operating system version: 7
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0
C3 release: r251.2 (stable)
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 480 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by DiegoScirra** [comment] 2021-08-12 10:48
Duplicate of #4943. This issue was fixed in r256. The only thing worth mentioning is that if there are any timelines playing when the bar is closed, the playback will stop rather than continue.

**Closed by DiegoScirra** 2021-08-12 10:48 UTC
Labels: duplicate
