### ISSUE TITLE
C3 remote preview freezing with Cannot read property 'GetWorldInfo' of null

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#2825] opened 2019-04-08 09:33 UTC
## Problem description

Trying to bypass #2818 using the same desktop version but ends in a random crash as well for every participant of the remote preview. At least here it freezes only so I can see the console error: 

![image](https://user-images.githubusercontent.com/7268697/55713863-38bb3600-59fa-11e9-9454-ebe2e4a8f489.png)

The good news is that the editor doesn't crash anymore since it's on a separate process.

## Attach a .c3p

Blank project

## Steps to reproduce

Keep it up on remote preview for ~ 20 minutes.

## Observed result

Freezes

## Expected result

Not to freeze

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** Noticed it from current stable revision 142.2

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 515 gb
Storage usage (approx): 96 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon 550 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-04-08 10:27
The crash report indicates a project using the Tween behavior, but the report says it reproduces with a blank project. This is inconsistent, are you sure you have the right details?

**Comment by JeFawk** [comment] 2019-04-08 10:44
Does not crash anymore (for now) neither with a blank project nor with a tween behavior in it. I'll keep it running throughout the day.

**Comment by DiegoScirra** [comment] 2019-04-09 10:26
Based on the stack trace, I made some changes that should avoid this crash. But it is difficult to test.

**Comment by AshleyScirra** [comment] 2019-04-15 12:54
r145 is out now, @JeFawk is the issue resolved there?

**Comment by JeFawk** [comment] 2019-04-16 13:59
Still happening in r145. @DiegoScirra  any email i could reach you at and show you the project?
I might haved pinned it down to a situation in which a lot of instances of a sprite get destroyed, and if I don't disable the Tween before I destroy them this happens. On the other hand I can't get it to work with a simple project (anymore???) nor with Demonoir.

**Comment by AshleyScirra** [comment] 2019-04-16 15:42
The original report involves an error in the Tween behavior. Demonoire does not use the Tween behavior, therefore if there is an issue there, it is unlikely to be the same issue. Since the originally reported issue ought to be fixed and it's no longer clear what the other issues are or if they're related, closing this issue - please file new issues following all the guidelines for any remaining issues so we can investigate them separately.

**Closed by AshleyScirra** 2019-04-16 15:42 UTC
Labels: can't reproduce
