### ISSUE TITLE
Layout on a separate tab has no "hold space to move around" feature.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4338] opened 2020-11-12 19:36 UTC
## Problem description

Moving the layout holding space is possible when the layout is in the main tab, but not when it's outside.

## Attach a .c3p

any file should present it.

## Steps to reproduce

1. drag the layout editor outside of the main tab.
2. right click on the browser bar and make it a tab.
3. check that you cannot move the layout around anymore.

## Observed result

not moving layout holding space.

## Expected result

moving layout holding space.

## More details

**Affected browsers/platforms:**  Tested on latest Edge.

**First affected release:**  Tested on 224.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2020-11-13 12:09
I can only reproduce this if I use the "Open to popup window" feature, but you don't seem to mention that at all, you only seem to talk about tabs, which is confusing, do you mean browser tabs or tabs in the editor itself? Can you confirm exactly what you are doing?

**Comment by dupuqub** [comment] 2020-11-13 16:30
I opened to a popup window then turned into a browser tab, there are images in the other issue.

**Comment by AshleyScirra** [comment] 2020-11-13 17:15
OK, so I was right, you're using the "Open to popup window" feature.

Closing this as a duplicate of #4339 as it's basically the same issue (keyboard shortcuts not working in popup windows).

**Closed by AshleyScirra** 2020-11-13 17:15 UTC
Labels: duplicate
