### ISSUE TITLE
on start of layout positioning on viewport / scroll to Bug

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#5599] opened 2022-04-05 18:49 UTC
## Problem description

In the new Betacycle a different behaviour was introduced that may be connected to the combination of "on start of layout -positioning on viewport" and the "scroll to" behaviour. The first time you open the Layout it works as intended, but when you restart the layout the bug appears.
It worked different in the latest Stable and in previous versions.

## Attach a .c3p
[bug_05.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8420984/bug_05.c3p.zip)

## Steps to reproduce

1.preview the project in r285.3 
2.click once on the yellow square
3.observe the position of the pink sprite (lower edge)
4.click again on the yellow square
5.now do the same again in r289

## Observed result

-in r 285.3 the pink sprite is always at the same position
-in r 289 the pink sprite is the first time in the correct position, when you click again it changes the position

## Expected result

the pink sprite should always be at the same position
## More details

**Affected browsers/platforms:** 
i checked on chrome and Firefox on Mac

**First affected release:** 
worked in r285.3 but broke in r286
## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 99.0.4844.84
Browser engine: Chromium
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
C3 release: r286 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 3.6 gb (1.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (ATI Technologies Inc.)
Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 560 OpenGL Engine, OpenGL 4.1 ATI-4.6.21)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2022-04-06 10:59
Looks like a regression caused by the fix for #5103. Should be fixed for the next beta.

**Closed by AshleyScirra** 2022-04-06 10:59 UTC
