### ISSUE TITLE
Local storage check item doesn't work on Safari (Macbook)

### ISSUE THREAD

**Issue by andychan1998** [Scirra/Construct-3-bugs#845] opened 2017-09-26 19:16 UTC
## Problem description

A button, when clicked, will call local storage check item to see whether an item exists.  If it does, it goes to layout 2.  If it doesn't, it goes to layout 3.  However, nothing happens when the button is clicked.  This problem only happens on Safari when tested on a Macbook.  It doesn't happen on Safari when tested on iPhone/iPad.  It also doesn't happen on other browsers (e.g. Firefox, Chrome) I have tested.

## Attach a .c3p

Please download at https://drive.google.com/open?id=0B8XY81b11D4sVjgyamE5ZU5kSkU.

## Steps to reproduce

1. Export the .c3p into a HTML5 game.  Load it onto server.
2. Use Safari on Macbook to load the HTML5 game.
3. Click on the "Play" button.

## Observed result

Nothing happens.

## Expected result

It should go to layout 2 or 3.

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: haven't tried
* Safari: yes, but only on Macbook, not on iPhone/iPad

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 60.0.3112.113
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
C3 release: r58
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 576 mb (1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2017-09-27 11:15
Which version of Safari are you using?

**Comment by andychan1998** [comment] 2017-09-27 17:34
I don't have access to the device now, but I'll check later today and let you know.


Thanks.


- Andy




________________________________

**Comment by andychan1998** [comment] 2017-09-28 01:53
Hi,


  The Safari version is 9.0.2 (11601.3.9).


thanks,

Andy



________________________________

**Comment by andychan1998** [comment] 2017-09-28 19:59
Hi Ashley,


  No, I haven't tried on Safari 10 and 11.  The problem is, I only have one Macbook and the problem is only reproducible there.  If I upgrade the Safari to a newer version and the problem doesn't happen, I wouldn't have a way to test the fix.


thanks,

Andy



________________________________

**Comment by AshleyScirra** [comment] 2017-10-03 12:16
Can't reproduce on Safari 11. If this only happens on Safari 9 we won't fix it, it's probably a Safari bug that Apple already fixed.

**Closed by AshleyScirra** 2017-10-03 12:16 UTC
