### ISSUE TITLE
Text object incorrect vertical alignment with BBCode enabled

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#2985] opened 2019-05-29 08:40 UTC
## Problem description

When using the text object and setting the text to vertical align text is not properly centered.
![image](https://user-images.githubusercontent.com/27011641/58542142-4a9ca680-81fd-11e9-8305-96fc3323e48d.png)
As you can see the space between top of the text and bottom is not equal. This becomes more apparent on multi line texts in the box.
![image](https://user-images.githubusercontent.com/27011641/58542311-aa934d00-81fd-11e9-85ae-031d69d0658e.png)
Text is not centered. Tried different fonts with same result.

## Attach a .c3p

N/A

## Steps to reproduce

1. Create a text object, and set the size to support at least 2 lines.
2. Change align to center, center, and set text to something spanning 2 lines.
3. Notice text is not vertically aligned properly to center.

## Observed result

Text is not properly aligned to center vertically.

## Expected result

The distance between text and top and bottom of text box should be equal.

**Comment by Wackytoaster** [comment] 2019-05-31 12:34
I always took this as "that´s probably just because of the font". Will be kinda annoying having it fixed, "breaking" all my alignments. But I´d still agree that it should be fixed.

**Comment by AshleyScirra** [comment] 2019-05-31 17:31
Minimal repro: [text-vertical-alignment.zip](https://github.com/Scirra/Construct-3-bugs/files/3242239/text-vertical-alignment.zip)

This is a difficult text metrics problem and I'm not sure what to do about it.

The problem is caused by the "Enable BBCode" option. Notice how regardless of the vertical alignment, enabling BBcode moves the text down slightly compared to having it off. (This can be used as a workaround if you don't need BBcode.)

The change was made intentionally for the BBcode feature. Historically text rendered with a "top" baseline starting at the very top of the bounding box. In BBcode it was changed to an "alphabetic" baseline for two reasons:
1) it's required for changing text styles to render correctly - e.g. if you change the text size, with "top" alignment it aligns to the top of the current line which looks wrong, and with "alphabetic" baseline it looks right
2) the old behavior actually rendered text too high up - in some fonts and in some languages some very tall characters can ascend above the top baseline and get cut off. Some other users reported bugs about this. Using an "alphabetic" baseline and drawing from the line height as the start position results in slightly lower down text with a top alignment, ensuring even tall characters can fit in correctly.

This bug is then caused by the fact the same vertical alignment calculation is done but with text rendering slightly further down. The fix would be to move it up by the difference between the line height and the alphabetic baseline... but I don't think browsers provide enough information to calculate that. No browsers support TextMetrics and the [Chrome issue for it](https://bugs.chromium.org/p/chromium/issues/detail?id=277215) has been stuck in limbo since 2013.

So we could use a "fudge factor" and guess how much to shunt it up, but I really, really don't want to do that, because I did a similar "fudge factor" change for calculating line spacing in the original C2 runtime back in 2011, and it's impossible to remove for backwards compatibility reasons, so we're stuck with an 8-year-old hack which also got ported to the C3 runtime and will continue to be used forever. So "just hack it" means using that hack instead of a correct solution for ever.

So - a perfect example of a bug that looks simple but is a nightmare...

**Comment by AshleyScirra** [comment] 2019-05-31 17:33
Actually I just found another bug 😲 the same issue makes it render text too far down with bottom alignment: [text-bottom-alignment.zip](https://github.com/Scirra/Construct-3-bugs/files/3242276/text-bottom-alignment.zip)
That's equally difficult for all the same reasons...

**Comment by tunepunk** [comment] 2019-06-03 08:01
Disabling BB code for my text objects placed the text too high instead of too low. Just just that by itself is not a good workaround.

![image](https://user-images.githubusercontent.com/27011641/58784548-fec67480-85e3-11e9-96d2-98eae83034a9.png)
This is with BB code enabled.

![image](https://user-images.githubusercontent.com/27011641/58784583-1271db00-85e4-11e9-8bc2-b3807579a146.png)
This is with BB code disabled. 

Try this:
1. Make a text object with two rows of text. And turn off BB code.
2. Set Line height to -10 notice that only the first row changes position. 

It seems like when the text is supposed to be centered it's not taking in to account any line height. So could it be that it's just doing the calculations in the wrong order? Could it be that any calculation to center the text is just forgetting to add the line height to the calculations? 

I made a little formula in expressions that took in to account the line height to adjust the Y of text object, depending on line height and how many rows. It seemed to work fairly consistently with BB code off. 

![image](https://user-images.githubusercontent.com/27011641/58785604-1f8fc980-85e6-11e9-83e5-50ac110e2ea5.png)
Line height  "-12".

![image](https://user-images.githubusercontent.com/27011641/58785645-32a29980-85e6-11e9-8312-c0e0f7b332db.png)
Line Height "0"

If you compare these two line hight has no impact on the centering of the object, and should probably be taken in to account when doing the centering.

**Comment by AshleyScirra** [comment] 2019-06-03 10:26
I guess it's the same problem - using a top baseline isn't the right place to align vertically from. (Although in this case nobody seems to have noticed since 2011 - this is the first I remember seeing an issue about this.)

As I mentioned we can't use hacks in the engine because it varies depending on the font and styling. You can hack it for your own project, but note that if this is eventually fixed it will be offset wrong again.

Coincidentally Google just posted an "Intent to ship" for TextMetrics which normally means they're close to shipping it - so it might be on the way sooner rather than later after all.

**Comment by tunepunk** [comment] 2019-06-03 10:56
Would that only solve if for Chrome then? How about other browsers / platforms? I would much rather have a built in solution (hack) that looks good on all browsers or platforms than relying on a fix that is browser specific but will look off in other places.

**Comment by AshleyScirra** [comment] 2019-06-03 11:25
There aren't really any good options here. As I said if we do a hack we will likely have to support it forever, even years after TextMetrics is widely supported and can provide the exact answer. And then people might file bugs years later saying it's still incorrect (because it uses a hack, not the exact calculation) and we'll be unable to fix it without making a breaking change. I'd rather put up with some relatively-short-term inconsistency so in the end when TextMetrics is widely supported, it works exactly correct everywhere.

**Comment by AshleyScirra** [comment] 2019-06-07 15:52
Will wait for [TextMetrics to ship](https://bugs.chromium.org/p/chromium/issues/detail?id=277215) to ship for the correct long-term fix.

**Comment by Boulerzzz** [comment] 2019-11-29 16:22
How can we center text until TextMetrics is shipped? Whats a recommended approach? I've been struggling for a long time with centerting text.

If I Enable BBcode the text seems to be equally wrong on both android and IOS. I can then move every single text object upward and test on android/ios and redo until it is centered. It takes forever and you won't get it perfect. One problem with that is that if I rotate the text it wont rotate around its origin because the text objects hotspot will be higher than the origin of the text.

If I disable BBcode the text will be aligned differently on Android and IOS but I can adjust the line height to get the text centered.

Obviously I can't test on every single phone out there so can I assume that it will be aligned the same on all Android devices and on all IOS devices?

**Comment by AshleyScirra** [comment] 2019-11-29 17:19
I'd just use top alignment and manually position the object.

**Comment by Boulerzzz** [comment] 2019-11-29 21:18
Alright, I did that. Was a bit of extra work but now it seems to be aligned perfectly on both ios and android! 👍
Thanks!

**Comment by AshleyScirra** [comment] 2021-01-14 17:29
It looks like now both Chrome and Safari support the necessary TextMetrics to calculate the correct vertical alignment. Unfortunately Firefox doesn't appear to support it yet, but it's implemented and the flag is just turned off at the moment, so hopefully it will be enabled soon. It is quite a significant change to a fundamental feature though with some difficult backwards compatibility considerations, and we're close to a stable release, so this fix will only be applied for the next stable cycle (first beta release after the next stable release). So this should - at last - be fixed when that's out!

**Closed by AshleyScirra** 2021-01-14 17:29 UTC
