### ISSUE TITLE
Text right edge getting clipped when aligned to right

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4829] opened 2021-05-16 09:20 UTC
## Problem description

Text right edge getting clipped when aligned to right

## Attach a .c3p

[textClip.zip](https://github.com/Scirra/Construct-3-bugs/files/6488954/textClip.zip)

## Steps to reproduce

1. Open file
2. Observe text object both in edit-time and run-time

## Observed result

The last character gets clipped

## Expected result

No clipping.

## More details

**Affected browsers/platforms:** Chrome/NWjs

**First affected release:** r248

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment] 2021-05-18 17:28
Can't reproduce this. The text shows up correctly in the example.

**Comment by avishaymizrav** [comment] 2021-05-18 20:01
@DiegoScirra 
I tried it on both r248 and r241, on both NWjs and Chrome (fully updated), I updated my windows and geforce driver.
I noticed this only happens with specific font sizes (tried different fonts, same result).

At first I thought it was related to the fact my windows base text size was set to 125%, but I get the same results with 100%.
I never had this issue before, any idea what could be causing this?

https://www.youtube.com/watch?v=qNk7a3hyL9k

**Comment by AshleyScirra** [comment] 2021-05-24 09:36
I also can't reproduce this, it looks fine here. I'm afraid there's nothing we can do without a way to reproduce the issue. If you follow the bug report guidelines and include system info there may at least be some clues there, but this information was not provided, so closing.

**Closed by AshleyScirra** 2021-05-24 09:36 UTC
Labels: can't reproduce
