### ISSUE TITLE
Platformer and Solid wreck performance when used on the same family

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#4443] opened 2021-01-02 13:23 UTC
## Problem description

Hi, this was a pretty precise one to track down. 
With André, we helped debugging performance issue on Antoine's game [Baby Dino](https://store.steampowered.com/app/1271910/Baby_Dino_Adventures/).
I think it's best if I describe how we got there to get you as much info as possible.

Basically, Antoine suffered pretty big performance issues on his game on one of his levels. From what I could tell, the level was a bit big (about 800 objects, 14016 x 1280 pixels) when compared to previous levels, but far from anything massive.
When looking at the debugger, he was seing a constant 20-30fps on his machine, with 80 to 90% CPU utilisation dedicated to behavior ticks. André and I were seing similar results on our machines.

We managed to find that the issue mainly came from the destroyable boxes in his game: As soon as we deleted all 80 of them in the level, the performance would rocket back up. Boxes have both the platformer behavior and the solid behavior on them (so they can stack and fall when pushed). I am pretty sure that this is a very common setup out there, which makes this even more worrying.

André added this code:
![image](https://user-images.githubusercontent.com/11213825/103457784-8a454180-4d02-11eb-8533-539d8ea596da.png)

I added this one:
![image](https://user-images.githubusercontent.com/11213825/103457797-9e893e80-4d02-11eb-8298-d850c512f2d9.png)

Different code, same idea: Smart enable and disable behaviors when objects are off screen. This should help, right?
Well, no. Not at all actually!

I initially wrote a quick example that replicated this with a single sprite and I thought that was that. 
https://cdn.discordapp.com/attachments/794657028520804372/794670048056311858/testlagdinoplatformsolid.c3p
Even though, the performance drop wasn't as massive, I still saw issues in that minimal repro, so I guessed that on a big project scale it was scaled accordingly.

However, I then decided to check the JS profiler and see what was wrong:
![image](https://user-images.githubusercontent.com/11213825/103457856-f9bb3100-4d02-11eb-84d2-00d448030710.png)
Boxes are trying to push out solid every single frame. But not out of themselves, out of the boxes on top and under them. Multiple time per frame it seems.
I tracked it down to this function and this line that are called in both PushOutSolidNearest and PushOutSolidAxis
![image](https://user-images.githubusercontent.com/11213825/103457876-23745800-4d03-11eb-856a-93208bedbba1.png)

I then noticed that the loop would run on every instance of the family, no matter if the individual instances have platformer/solid enabled or disabled.

I then updated my minimal repro example to use a family instead, and there I had it, a much bigger performance drop.

This is the control test:
![image](https://user-images.githubusercontent.com/11213825/103457924-8fef5700-4d03-11eb-8a8b-8b22e72243f3.png)
1050 objects with only the platformer behavior, and I'm getting 20% behavior processing, and 120FPS: No issue at all there.

![image](https://user-images.githubusercontent.com/11213825/103457950-adbcbc00-4d03-11eb-8dcd-1d9477963c87.png)
Now, here, I added the solid behavior to my family, but it is DISABLED on every instance on the layout. Result: 48FPS, 93% CPU Utils on the behaviors tick

![image](https://user-images.githubusercontent.com/11213825/103457973-e2307800-4d03-11eb-9e7e-7d9d33eccccb.png)
I tried enabling solid on a single instance among the 1000+, and I did not find any performance impact, so there is no check to batch disable solid if every instance has solid disabled in the family.

Now, if I ENABLE solid:
![image](https://user-images.githubusercontent.com/11213825/103457993-1d32ab80-4d04-11eb-95be-0b25a0af45fe.png)
5% behavior tick CPU Util, with only 44 objects. That is non negligible

![image](https://user-images.githubusercontent.com/11213825/103458013-4e12e080-4d04-11eb-8d57-398914882765.png)
In fact, I get similar performance than the control test (that had 1000+ instances) with only 120 objects on screen. About 9 times worse 🤔

![image](https://user-images.githubusercontent.com/11213825/103458032-7bf82500-4d04-11eb-8113-fe834af40bcc.png)
With 1000+ instances, it's getting near 100% CPU util just for the behavior tick, and 11 FPS.

Now, my guess is that the more object types are in the family, the worse the performance, but I can't be sure.

The issue still happens when used on an instance though, so the issue is still that the behavior is constantly trying to get out of solid, on every frame. It's just that it's much more noticeable when used on a family.

## Attach a .c3p

[testlagdinoplatformsolid.zip](https://github.com/Scirra/Construct-3-bugs/files/5760269/testlagdinoplatformsolid.zip)

## Steps to reproduce

1.Hit preview in debug mode
2.Left click to add instances near the mouse
3.Right click to delete instances near the mouse
4. After noticing the performance drop, Try to disable the solid on every instance
5. After that, try removing the solid behavior entirely from the family

## Observed result

Performance takes a big hit

## Expected result

Performance should not be this low, especially when trying to do something as common as "boxes that stack up"

## More details

Please, note that I don't really think this absolutely needs to be fixed. Having both behaviors on the same object was sure to cause issues since both interact. Instead, I'm asking if you'd at least provide a clear alternative to manage the case where one might need to stack boxes. Since I assume this is something a lot of people will try to do (including me a few years ago), I also assume a lot of people will run into this once the project gets big enough. It will take time to notice, and when it does happen, it will take time to narrow down, and will cause a lot of confusion.

**Affected browsers/platforms:** n/a

**First affected release:** This seems to also happen on C2 from what I can tell, so since forever

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2021-01-04 13:11
> Boxes have both the platformer behavior and the solid behavior on them

This is not actually supported. The solid behavior blocks the platform movement. So this setup means the object blocks itself. I'm surprised it works at all! I'll check out the issue when I get more time, but it's not something the behavior was ever designed to support!

**Comment by skymen** [comment] 2021-01-04 13:42
Yeah, I could understand that much haha
> So this setup means the object blocks itself.
From what I can tell, you have a check in your collision engine so an instance can never collide with itself, this is why it works IMO

The issue is indeed that the platformer behavior always assumes that by design a solid object is either a static entity, or a moving platform to walk on. It never assumes that a solid object can be player controlled, or affected by gravity, when actually there are plenty of reasons of why you might want to do that. Especially since the Physics behavior assumes everything is both solid AND moving, and makes "solid and not moving" and "moving but not solid" two edge cases it deals with.

Anyway, I think that there are many reasons why anyone might wanna have that setup, but not use Physics for it (because they might not want to deal with running an entire physics simulation to make a player walk on boxes). I don't think it's wise to update 10 year old code in the platformer/solid behavior to change how they work  (unless you have a better idea) and instead I think it's a good idea to have an alternative to solid (like jumpthrough) that deals with this specific edge case separately.

**Comment by AshleyScirra** [comment] 2021-01-04 14:41
I think the fundamental issue is you've set up a project with O(n^2) efficiency (the amount of work to be done increases with the square of the number of instances, i.e. far faster than the number of instances, i.e. it's incredibly inefficient).

The problem is the Platform behavior has to make several collision checks every tick: is the floor still there? Has something pushed the object? etc. It looks for solids in these collision checks.

If you spawn instances with both the Platform behavior and the Solid behavior, each object has to do collision checks with every other object. So if you have 100 instances, it has to check 10000 combinations of collisions. Since the Platform behavior makes several checks per tick, it's actually a multiple of that, which is even worse. You can see in the debugger you can quickly reach tens of millions of collision checks per second. Obviously that's going to be slow.

There is no good way to solve this: the platform behavior needs to make those collision checks, and you've given it an exponentially increasing amount of work to do. This is another reason I said the platform behavior is not designed to be used this way. It's extremely difficult to make it work efficiently in this case. It would probably involve a complicated redesign of how the platform behavior works in order to efficiently support this use. However that is infeasible and difficult to justify anyway given the intended purpose of the behavior. The platform behavior is designed to be used for a player and maybe a few enemies, none of which themselves use the solid behavior - not for simulating a physics-style stack of boxes. The Physics behavior would probably actually be much more efficient in this case, even with the overhead of a full physics engine, because physics engines are specifically designed to handle difficult cases like this with good algorithmic efficiency. (One of the ways they do that is by being relatively imprecise, which is the kind of tradeoff we can't make with the built-in behaviors either.)

I'm afraid since there is no good course of action and the behavior was not designed for this, closing as wontfix. You'll need to find another way to do this.

**Closed by AshleyScirra** 2021-01-04 14:41 UTC
