### ISSUE TITLE
Issue construct game Web Mobile on iOS the canvas is selectable

### ISSUE THREAD

**Issue by LoicBlumgi** [Scirra/Construct-3-bugs#5186] opened 2021-11-03 14:41 UTC
## Problem description

I am working on a web game for Poki platform. I target desktop and mobile web.
Actually on iOS Holding the finger on the canvas highlights it as it was selected and brings up the menu to copy .

## Attach a .c3p

I attached a simple project that has the same issue than my game.

[TestInputiOS.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/7468314/TestInputiOS.c3p.zip)

You can test here in the Poki QA tool I use for my game:
https://qa.po.ki/#?key=8da1a6cc-8413-4c66-9621-3358bde17e12

I tested it on itch.io too to be sure it's not Poki related: 

https://blumgi.itch.io/testinput

## Steps to reproduce

1. Open the game with an iOS device: mine is iPhone 12 here : https://qa.po.ki/#?key=8da1a6cc-8413-4c66-9621-3358bde17e12
2. Keep touching the canvas 2-3 seconds

PS: You can remove UI by taping three times on "QA Checkpoints"

## Observed result

The canvas highlights it as it was selected and brings up the menu to copy 

## Expected result

I expect the canvas were not selected and be able to play without text and blue highlight.

## More details
Someone gave me this link about the same issue on playcanvas but I have not enough technical knowledge to 
understand.

https://github.com/playcanvas/editor/issues/160

**Affected browsers/platforms:** 

iOS

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

Thank you

**Comment by AshleyScirra** [comment] 2021-11-08 15:19
I tried this with Remote Preview and HTML5 export on an iPad Pro running iOS 15 and the canvas did not appear to be selectable for me.

Does this reproduce for you on an iPad or is it iPhone specific? Is this new to iOS 15 or did it happen on iOS 14 too? Does this happen on a normal HTML5 export or in Remote Preview or only on the certain sites you mentioned? It's possible that if it only happens on certain sites, then those sites are doing something that changes this.

**Comment by LoicBlumgi** [comment] 2021-11-08 16:47
Oh the links I gave you were removed sorry for that.

It works well in remote but not when it s exported in HTML5 I tried on my iPhone and my IPad Pro I have the issue on both.

I think it’s construct related because on poki.com in appears on a construct game but not on games made with other engines on the same portal.

you can test this one : 

https://poki.com/en/g/brain-test-2-tricky-stories

It’s not mine but I know it’s a construct game.

Thank you

**Comment by LoicBlumgi** [comment] 2021-11-12 11:56
Hi Ashley please find a link to my game that is soft launched on poki now. If you want to reproduce the bug.

https://qa.po.ki/#?url=https://76cada96-8623-477f-93f8-c2abef3929e7.poki-gdn.com/bfc46243-9e01-4e26-9355-dc1bf8274943/index.html

This link won’t be removed.

thank you,

**Comment by AshleyScirra** [comment] 2021-11-17 12:00
We still need to rule out that the portal is changing something that breaks Construct games specifically. I could not reproduce this with my own HTML5 export, which suggests that the problem is not in fact Construct, since if it was, then a normal HTML5 export would have demonstrated the problem. In order to advance the investigation of this issue we will need a way to reproduce the problem with a HTML5 export directly from Construct. If you can't do that and the problem only happens on Poki, then you'll need to contact them about it.

**Comment by skymen** [comment] 2021-11-17 15:17
I will try to make a minimal repro. My current guess is it's C3 related, but only happens when the game is played through an Iframe or something. I highly doubt it's Poki related (or exclusive to Poki)

**Comment by AshleyScirra** [comment] 2021-11-22 16:46
Until there is a minimal repro this issue is not actionable, so closing. If you produce a repro that demonstrates the problem, please file a new issue following all the guidelines.

**Closed by AshleyScirra** 2021-11-22 16:46 UTC
Labels: can't reproduce, iOS
