### ISSUE TITLE
Crash when cutting objects from a global layer (once)

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#853] opened 2017-09-28 06:22 UTC
## Problem description

I accidentally created four objects on the wrong layer, which happened to be a global layer set in another layout. I went to the layout with the global layer, selected the placed objects (I think I clicked on the object in the project view so they'd all be selected at once), hit ctrl+x to cut, got the prompt saying the browser blocked the copy, hit the "Copy" button to try again, and Construct crashed.

## Attach a .c3p

I don't have a minimal repro project for this, since it has only happened once.

## Steps to reproduce

The only steps I have are outlined above. If I find some I'll update here.

1.
2.
3.

## Observed result

Crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: object instance does not have associated behavior instance @ Error: object instance does not have associated behavior instance at window.ǃgk.ǃcP (https://editor.construct.net/r59/main.js:61:136251) at d.ǃqVr (https://editor.construct.net/r59/main.js:61:206877) at d.ǃkp (https://editor.construct.net/r59/main.js:61:71074) at window.ǃUB.ǃkR (https://editor.construct.net/r59/components/editors/layoutView/layoutView.js:1:27263) at e.then (https://editor.construct.net/r59/components/editors/layoutView/layoutView.js:1:32918) at 
Stack: Error: object instance does not have associated behavior instance at window.ǃgk.ǃcP (https://editor.construct.net/r59/main.js:61:136251) at d.ǃqVr (https://editor.construct.net/r59/main.js:61:206877) at d.ǃkp (https://editor.construct.net/r59/main.js:61:71074) at window.ǃUB.ǃkR (https://editor.construct.net/r59/components/editors/layoutView/layoutView.js:1:27263) at e.then (https://editor.construct.net/r59/components/editors/layoutView/layoutView.js:1:32918) at 
Construct 3 version: r59
URL: https://editor.construct.net/index.html
Date: Wed Sep 27 2017 22:20:14 GMT-0700 (Pacific Daylight Time)
Uptime: 7068.9 s

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r59
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2017-09-28 12:28
@DiegoScirra - "object instance does not have associated behavior instance" has been coming up a lot in crash reports lately, would be good if this helps identify the underlying issue.

**Comment by DiegoScirra** [comment] 2018-01-08 17:05
Duplicate of #962

**Closed by DiegoScirra** 2018-01-08 17:05 UTC
Labels: duplicate
