### ISSUE TITLE
Problem in mobile apk export(minify script)

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#3167] opened 2019-07-22 15:06 UTC
I made my project and i exported apk file from it.And i figured out some observation from it
1.) deduplicate and recompressing  images "have " a huge effect on performance. Selecting these options increase game's performance by atleast 20-30 fps.But the shocking fact was that "remote preview" has much better performance than the apk file (deduplicate and recompress option were not selected).Any idea regarding this observation?
2.)The main problem:-minify script option does not work at all.Only black screen appears after opening the app on mobile. But if it is not selected then the app runs smoothly.
3.)Please give me solid points to boost my game performance on mobile.My game size is only 5 mb but still it does not runs smoothly 
## Steps to reproduce
Use any project

1.export the project for android,with minify script selected(other options does not have connection with it so you are free to do anything with them)  

## Observed result

1.)black screen on running the app on mobile(minify script selected)
2.)remote preview has better performance than apk itself(although i did not selected duplicate and recompress option while doing export for apk):-i just wanted to save some time
## Expected result
app should had run smoothly

I am using latest version of chrome on windows 10
And i am using latest version of construct 3

**Comment by layilpaht** [comment] 2019-07-22 15:19
And also your build service takes a LOT of time !!!

**Comment by AshleyScirra** [comment] 2019-07-22 15:30
@layilpaht - please:
- follow the bug report guidelines
- provide a minimal project that reproduces the problem
- only describe one problem per issue filed (otherwise we cannot track each problem separately and inevitably critical details about problems are omitted, since we need full reports consistently following all the bug report guidelines for every individual problem)

**Comment by AshleyScirra** [comment] 2019-07-22 15:35
Space Blaster runs OK for me after a minified export to an Android Debug APK. Most minify issues are due to broken third-party addons; I assume this is the problem. Closing.

**Closed by AshleyScirra** 2019-07-22 15:35 UTC
Labels: can't reproduce

**Comment by layilpaht** [comment] 2019-07-22 15:46
Woah new welcome message
Error report information
Type: unhandled rejection
Reason: undefined
Construct 3 version: r157
URL: https://editor.construct.net/
Date: Mon Jul 22 2019 21:11:00 GMT+0530 (India Standard Time)
Uptime: 186.7 s

Platform information
Browser: Chrome
Browser version: 75.0.3770.142
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 710 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
Which space blaster are you talking about(link) ? And also try to attach the apk file so that i can also test the apk in my mobile
