### ISSUE TITLE
Imported web fonts freeze preview

### ISSUE THREAD

**Issue by Zhihong0321** [Scirra/Construct-3-bugs#2525] opened 2019-01-21 02:41 UTC
## Problem description

Import FONT .ttf will crash the Preview 
1) using Microsoft Store version of C3's Preview (R134)
2) Export to Desktop version and run the game, ( blank on start )
3) using any version of C3 and export the game to desktop version (NW.js)

## Attach a .c3p
[FONT_will_Crash.zip](https://github.com/Scirra/Construct-3-bugs/files/2777385/FONT_will_Crash.zip)

## Steps to reproduce

1. Preview the game ( attached the .c3p )
2. Remove ALL imported font, and preview again ( preview using MS store C3 )
3. It can work with NO FONT imported.

## Observed result

C3 with Game IN DESKTOP version CANNOT work with imported font.

## Expected result

this is long time bug that keep coming back.

## Affected browsers/platforms

* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

EXPORTED TO NW.js ( Yes )
Preview in MS Store C3 ( Yes )

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Zhihong0321** [comment] 2019-01-21 02:45
Tested with the Font converted to woff

Same result. Freezed the review.

**Comment by AshleyScirra** [comment] 2019-01-21 11:07
It's a bit confusing because you seem to have provided two different steps to reproduce.

I tried exporting from the web version to NW.js v0.35.1, and the project started up just fine with no errors. Please provide the exact details of how you are exporting the project so I can follow what you are doing exactly.

**Comment by Zhihong0321** [comment] 2019-01-21 23:49
Sorry. I retry with R135, web version ( with Chrome browser )
Export with v0.35.1, works fine.

Only Microsoft Store C3 Beta, latest, freezed on preview.
Thanks.

**Comment by AshleyScirra** [comment] 2019-01-22 11:45
Looks like a missing WebFont feature in Edge.

**Comment by AshleyScirra** [comment] 2019-01-22 11:51
OK, just worked around missing FontFace support in Edge - should be fixed in the next release.

**Closed by AshleyScirra** 2019-01-22 11:51 UTC
Labels: edge
