### ISSUE TITLE
Cannot Save / Save as   (Desktop Beta r88)

### ISSUE THREAD

**Issue by AlonDan** [Scirra/Construct-3-bugs#1326] opened 2018-02-26 16:42 UTC
## Problem description
Desktop-build Latest Beta version r88.

Can't save my project manually via Menu or the from the Disc icon for saving, it's disabled. (grey)
Window popup message appears when trying to save via Menu:
" **Unable to save file. Try checking you have premission to access the chosen folder.** "

The same file, same directory works fine and can be saved on the stable version.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
It doesn't matter, even with a new file it can't save with the same Admin error message above.

## Steps to reproduce

1. I tried to run as Admin and save, but it's producing the same error.
2. I tried to make a new project and save the file on different directory, same error.

## Observed result

*What do you see happen?*
Not saving.

## Expected result

*What did you expect to happen instead?*
To save, save as.

## Affected browsers

* Desktop Build r88

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2018-02-26 16:46
Can't reproduce here - if I create a new project and save as either a single file or folder project, it successfully saves. Where are you trying to save and are you sure you have permission? I tested saving to the desktop which normally has write permission.

Also if you could press F12 to open dev tools and look in the console, if there's any errors there please copy-paste them to here.

**Comment by AshleyScirra** [comment] 2018-02-26 16:58
Someone posted a comment on the release mentioning a similar issue and mentioned you have to add an object first. It doesn't reproduce with a completely empty project. I can reproduce it if adding an object to an empty project and doing save-as. So, oops, save seems to be broken in r88. Should have a patch out tomorrow.

**Comment by AshleyScirra** [comment] 2018-02-27 14:14
Should be fixed in r88.2!

**Closed by AshleyScirra** 2018-02-27 14:14 UTC
Labels: fixed
