### ISSUE TITLE
Failed to export project

### ISSUE THREAD

**Issue by studiofiremobi** [Scirra/Construct-3-bugs#3302] opened 2019-09-04 19:35 UTC
## Steps to reproduce

1. clicked in menu > export > android
2.here show "failed to export project"
3.

## A error message
![construct-error](https://user-images.githubusercontent.com/54912419/64285354-00c90800-cf32-11e9-971c-f09768813d02.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by lealgabriel** [comment] 2019-09-04 21:54
I also have the same problem

**Comment by AshleyScirra** [comment] 2019-09-05 09:41
This looks the same as #3300. However again as happened there I tried exporting to Android - both a Cordova project and a debug APK - and both worked fine.

Without a report following the guidelines, including a project file that demonstrates the issue, we cannot investigate this. You provided an APK file, which you can only get after a successful export, so the fact you attached that actually contradicts your report.

I will leave this open for now as this seems to have been reported a couple of times but I must emphasise the importance of following all the bug report guidelines, otherwise there is nothing we can do. Also when the error happens try pressing F12 and see if there are any error messages in the browser console; if there are please let us know here what they are.

**Comment by AshleyScirra** [comment] 2019-09-05 09:45
I figured out from the screenshot you are using Construct in Portuguese and I can reproduce a crash due to a missing translation. I'll see if I can work around that. As before please do provide the system information requested, it includes the language setting and other technical details that can help resolve the issue you are reporting.

**Comment by AshleyScirra** [comment] 2019-09-05 11:38
OK, should be fixed in an upcoming stable patch.

**Comment by luan-siqueira** [comment] 2019-09-05 13:24
Tenho o mesmo problema, quando vai ser lançada a correção?

**Closed** 2019-09-05 14:59 UTC
