### ISSUE TITLE
heelllppp!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by jefferybiceps** [Scirra/Construct-3-bugs#6320] opened 2022-12-10 06:51 UTC
So while i was trying to delete an image point if a 3d object construct 3 sent an error message and made me save the .c3p file but while i tried to re open that file its layout was empty.i tried to even zoom in and out to see the edges of the layout(the gray part) but it was all white.none of my objects were being shown(i couldn't select them either.

here is the save file:

[3d4 - Copy.zip](https://github.com/Scirra/Construct-3-bugs/files/10199360/3d4.-.Copy.zip)

## Steps to reproduce

1.open the file.
2.go to the first layout.
3.there you go.

## Observed result

blank layout

## Expected result

filled with my objects

## More details
the file that is attached contains a 3d game and i know construct's 3d feature is kind of new so that might be the problem.  
**Affected browsers/platforms:** 
Firefox

First affected release:r317.2

## System details

Platform information

Product: Construct 3 r317.2 (stable)
Browser: Firefox 107.0
Browser engine: Gecko
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0
Language setting: en-US
Local storage

Storage quota (approx): 8.6 gb
Storage usage (approx): 24 mb (0.3%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Radeon HD 5850 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2022-12-12 11:39
In the latest beta, I can see a bunch of 3D shapes in the layout. So I can't reproduce what you describe.

I'm afraid as per our bug report guidelines, it's impossible to help unless we have steps to reproduce the original problem in the first place. It is not possible to tell what happened just from a project file. Closing this issue, please file a new one if you can find what causes the original problem.

**Closed by AshleyScirra** 2022-12-12 11:39 UTC
Labels: no repro
