### ISSUE TITLE
Crash duplicating duplicated timelines

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3210] opened 2019-08-13 14:42 UTC
## Problem description

This is linked to https://github.com/Scirra/Construct-3-bugs/issues/3209

## Attach a .c3p
Same as https://github.com/Scirra/Construct-3-bugs/issues/3209
[TimelineBreaks.zip](https://github.com/Scirra/Construct-3-bugs/files/3497464/TimelineBreaks.zip)

## Steps to reproduce

1. Duplicate timeline
2. Duplicate the duplicated timeline

## Observed result

Crash

## Expected result

Not crash

## More details

This release really badly broke timelines :(
And it's not cute tiny bugs as well. I'm talking bug that will corrupt projects, and that will crash it. That has the potential to totally destroy a whole c3p file if no backup was made, and some good amount of work if there were backups made...

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: e.ǃtM is not a function @ TypeError: e.ǃtM is not a function at https://editor.construct.net/r160/projectResources.js:1:16152 at Array.map () at g.ǃzl (https://editor.construct.net/r160/projectResources.js:1:16141) at t.ǃsI (https://editor.construct.net/r160/projectResources.js:1:437073) at https://editor.construct.net/r160/components/bars/projectBar/projectBar.js:24:10345
Stack: TypeError: e.ǃtM is not a function at https://editor.construct.net/r160/projectResources.js:1:16152 at Array.map () at g.ǃzl (https://editor.construct.net/r160/projectResources.js:1:16141) at t.ǃsI (https://editor.construct.net/r160/projectResources.js:1:437073) at https://editor.construct.net/r160/components/bars/projectBar/projectBar.js:24:10345
Construct 3 version: r160
URL: https://editor.construct.net/r160/
Date: Tue Aug 13 2019 16:41:13 GMT+0200 (heure d’été d’Europe centrale)
Uptime: 3332.9 s

Platform information
Browser: Chrome
Browser version: 76.0.3809.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
C3 release: r160 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment] 2019-08-14 13:25
Duplicate of #3209.

@skymen

I tried this out, and in the mean time, if you delete the duplicated timelines from the project you should be able to save. It fails as long as there are duplicated timelines in the project, even if they are not actively used in an event sheet.

**Closed by DiegoScirra** 2019-08-14 13:25 UTC
Labels: duplicate
