### ISSUE TITLE
Turning on auto backup saves too often. (firefox)

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#938] opened 2017-10-16 18:54 UTC
## Problem description

Switching on periodically save backup with the default setting of 10 minutes triggered saving a lot more often than 10 minutes. I got the save notification once every minute or so.

## Attach a .c3p

N/A

## Steps to reproduce

1. Open a project and Turn on autosave in firefox with 10 minute interval.
2. C3 will save a lot more often than every 10 minutes.

## Observed result

Saving more often than set.

## Expected result

Should save according to interval setting.

## Affected browsers

* Firefox: yes

**Comment by AshleyScirra** [comment] 2017-10-16 19:04
Looks like a duplicate of #930

**Closed by AshleyScirra** 2017-10-16 19:04 UTC
Labels: duplicate
