### ISSUE TITLE
Image Point Coordinate Y Field Not Retaining Data

### ISSUE THREAD

**Issue by Willow65806** [Scirra/Construct-3-bugs#4614] opened 2021-02-26 15:39 UTC
## Problem description

This issue only occurs when using a sprite object with multiple frames. While changing the image point X and Y coordinates, if using 'Tab' as a hotkey to move from the X field box to the Y field box the system will not always save what is put into the Y field when you navigate away. Frame one always saves the data, but from frame two on you have to click in the Y field box to change it or it will continue to default to what it was before.

## Attach a .c3p

What I have to report isn't demonstrable through a saved project, as it has to do with fields in the actual software itself.

## Steps to reproduce

1. Create a sprite object with 2 or more frames.
2. Open the sprite object, start on frame 1, and select to edit the image points.
3. Click in the X field box, enter new X coordinate.
4. Use TAB to move to the Y field box, enter new Y coordinate.
5. Press TAB to leave Y coordinate field box. (Should highlight Frame 1 in the view box below.)
6. Click on the next frame to move over to it.
7. Click in the X field box, enter new X coordinate.
8. Use TAB to move to the Y field box, enter new Y coordinate.
9. Press TAB to leave Y coordinate field box. (Should highlight your current frame in the view box below.)
10. Continue steps 6-9 for each additional frame.
11. Click on frame 1 and confirm that X and Y are both accurate for what you entered.
12. Click on each additional frame to see that the X field box is correct, but the Y field box is incorrect for what you entered.

## Observed result

I saw that it was only retaining the entire information for frame 1 and then only the X field information for each additional frame after 1.

## Expected result

I expected it to retain the information I entered.

## More details

**Affected browsers/platforms:** Chrome. - Internet explorer is not supported with the version on my computer, so this has **only** been tested in the Chrome browser.

**First affected release:** R234.4 stable is the only version I used and witnessed this in.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 88.0.4324.190
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
C3 release: r234.4 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 134 gb
Storage usage (approx): 38 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2021-02-26 16:27
Can't reproduce this one, tried following the steps with a 3 frame animation and all the inputs keep the values.

**Comment by Willow65806** [comment] 2021-02-26 16:35
I had another individual confirm this was occurring prior to posting the issue. - Since this isn't something I can provide a saved project example to show how would you like me to provide further eveidence of it occurring?

**Comment by DiegoScirra** [comment] 2021-02-26 17:24
Asides from consistent reproduction steps there is not much else to do. I tried following those steps in both the latest stable and latest beta, and can't reproduce the problem. This might be related to #4615,, but it is hard to tell.

Have you tried reproducing the issue in the latest beta?

**Comment by Willow65806** [comment] 2021-02-26 17:29
https://user-images.githubusercontent.com/79710367/109333692-5fb8c600-7825-11eb-8d52-343c74aeabfa.mp4

I made a video reproducing this within the stable R23.4.4 version, however following the same steps as in the video I am able to recreate this in Beta version R237 as well.

**Comment by DiegoScirra** [comment] 2021-03-01 16:32
Fixed in the next beta.

**Closed by DiegoScirra** 2021-03-01 16:32 UTC
