### ISSUE TITLE
New Persistent storage on Android

### ISSUE THREAD

**Issue by MassimoF-C3** [Scirra/Construct-3-bugs#1685] opened 2018-06-10 08:35 UTC
## Problem description

This is not reaaly a bug, but an issue that could be addressed in one of next releases. Currently is to be fixed manually adding a line in Config.xml, but not everything is clear.
Few days ago, I exported a project (C3 with C2 runtime, desktop version) as a “Cordova project”, and then I proceed as usual with the apk build via Cordova CLI. This time, in the “prepare” phase of the apk building process, a warning pops up (see image below), telling that is a recent update related to the local storage, and you could have to modify config.xml. 

![android](https://user-images.githubusercontent.com/37712098/41199801-9be1b402-6c98-11e8-98ed-3b1dc39160fc.png)

The app I was building was a new one, so I didn’t modify the Config.xml as suggested, but after installing on my smartphone the local storage did not work. Then I build the same apk again, this time adding the line as mentioned, and everything worked fine. Anyway I cannot understand why, since without pre-existing storage you should have no need to modify anything.

## Attach a .c3p

Every project will do, the above snapshot was obtained building Ghost Shooter.  

## Steps to reproduce

1. Export any project selecting the "Cordova project" option (minify: yes, deduplicate: yes etc)
2. Execute the Cordova CLI command "Cordova prepare" and constatate the need to manually
modify, at least in some cases, the Config.xml file.
3.

## Observed result

See above

## Expected result

I should have no need to intervene manually in config files

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.30.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@004e06da11e10bb08f6632224ae48ee3d5f7b303) NWjs/0.30.0 (like Chrome/66.0.3359.117)
C3 release: r104 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 210 gb
Storage usage (approx): 434 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 5500 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2018-06-10 11:09
What version of Cordova CLI are you using?

On 10 Jun 2018 09:35, "MassimoF" <notifications@github.com> wrote:

Problem description

This is not reaaly a bug, but an issue that could be addressed in one of
next releases. Currently is to be fixed manually adding a line in
Config.xml, but not everything is clear.
Few days ago, I exported a project (C3 with C2 runtime, desktop version) as
a “Cordova project”, and then I proceed as usual with the apk build via
Cordova CLI. This time, in the “prepare” phase of the apk building process,
a warning pops up (see image below), telling that is a recent update
related to the local storage, and you could have to modify config.xml.

[image: android]
<https://user-images.githubusercontent.com/37712098/41199801-9be1b402-6c98-11e8-98ed-3b1dc39160fc.png>

The app I was building was a new one, so I didn’t modify the Config.xml as
suggested, but after installing on my smartphone the local storage did not
work. Then I build the same apk again, this time adding the line as
mentioned, and everything worked fine. Anyway I cannot understand why,
since without pre-existing storage you should have no need to modify
anything.
Attach a .c3p

Every project will do, the above snapshot was obtained building Ghost
Shooter.
Steps to reproduce

   1. Export any project selecting the "Cordova project" option (minify:
   yes, deduplicate: yes etc)
   2. Execute the Cordova CLI command "Cordova prepare" and constatate the
   need to manually
   modify, at least in some cases, the Config.xml file.
   3.

Observed result

See above
Expected result

I should have no need to intervene manually in config files
Affected browsers

   - Chrome: yes

System details

Platform information
Browser: NW.js
Browser version: 0.30.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36
(@004e06da11e10bb08f6632224ae48ee3d5f7b303) NWjs/0.30.0 (like
Chrome/66.0.3359.117)
C3 release: r104 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 210 gb
Storage usage (approx): 434 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could
improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 5500 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
View details

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Scirra/Construct-3-bugs/issues/1685>, or mute the thread

**Comment by MassimoF-C3** [comment] 2018-06-10 17:17
Ah sorry, I forgot to mention, I'm using version 8.0.0

**Comment by shortercode** [comment] 2018-06-10 17:46
Mm weird, I haven't seen this warning before. I'll take a look at this
tomorrow.

**Comment by shortercode** [comment] 2018-06-11 10:55
Seems like we've added the `cordova-plugin-file module` to work around a file loading issue in the C3 runtime, I'm not really sure if this is needed, particularly as it's now being included in the C2 runtime that works without it. I need to talk to Ashley about it but he's not available at the moment.

This warning is related to that plugin. It's odd because it shouldn't be causing issues with local storage, or even doing anything in the C2 runtime. Whats more I have no idea why the compatibility setting makes it any different! I think I'm going to need to do some more research.

**Comment by MassimoF-C3** [comment] 2018-06-11 11:08
Ah ok, so if I understand correctly, for the moment (since I'm working with C2 runtime) the best thing for me is to manually delete the line related to the "file" plugin from the Config.xml 
I'll make some other text and will communicate any useful result

**Comment by shortercode** [comment] 2018-06-11 11:15
I haven't tested it yet, but I would expect it to work correctly if you removed the file plugin yes. 

If you happen to be building iOS versions as well, that does require the file plugin to work.

**Comment by MassimoF-C3** [comment] 2018-06-11 11:37
Ok thanks

**Comment by AshleyScirra** [comment] 2018-06-18 14:13
I've updated the next build to only include `cordova-plugin-file` for either iOS, or Android with the C3 runtime. Android in the C2 runtime will not reference the plugin any more. Hopefully that will solve this.

**Closed by AshleyScirra** 2018-06-18 14:13 UTC
