### ISSUE TITLE
Can’t link Dropbox to iOS 11.0.2

### ISSUE THREAD

**Issue by TinyMartian** [Scirra/Construct-3-bugs#902] opened 2017-10-07 17:54 UTC
## Problem description

After I logged in to Dropbox to link it to Construct 3, I’m presented with a blank white screen.

## Attach a .c3p

N/a

## Steps to reproduce

1. Login to C3
2. Tap the “Cloud” button on the Start page
3. A pop up message stated the pop up was blocked
4. Tap “Try again”
5. A window for linking Dropobox to Construct loads full screen
6. Login in to Dropbox
7. Blank white screen loads
8. Nothing else

## Observed result

Something is preventing me from linking Dropbox to my Construct 3 account. I got up to make a sandwich and to get a drink in case it was just taking some time to load, but still nothing. The page never loaded.

## Expected result

I expect maybe a confirmation page and to gain access to projects saved to Dropbox.

## Affected browsers

* Chrome: n/a
* Firefox: n/a
* Edge: n/a
* Safari: yes (iOS only)

## System details

Construct 3
iOS 11.0.2
iPad Pro (1st gen)
Ice tea and a roasted turkey sandwich (held the pickles)

**Comment by AshleyScirra** [comment] 2017-10-09 10:12
Might be duplicate of #892

**Comment by shortercode** [comment] 2017-10-09 10:18
Yeah sounds exactly like #892, closing as a duplicate.

**Closed by shortercode** 2017-10-09 10:18 UTC
Labels: duplicate
