### ISSUE TITLE
Script type isn't saved in the project

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#4546] opened 2021-02-08 10:10 UTC
## Problem description

If a project has been created in a recent version of Construct, the script type is forced to module, even though you switch it back to classic, after saving and reopening the project, it's automatically switched to module again.

## Attach a .c3p

n/a

## Steps to reproduce

1. Create new project in the latest beta cycle
2. Set script mode to classic
3. Save
4. Reopen the project

## Observed result

Script mode is set to module again

## Expected result

Script mode should stay in classic

## More details

This is especially annoying since I have projects using addons or scripts that have not been updated yet and that I don't wanna bother updating right now, and it crashes the game every time I preview because of that.

**Affected browsers/platforms:** Chrome

**First affected release:** Whatever version implemented modules first

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2021-02-09 12:02
This is a duplicate of #4530 and is currently by design. If Construct automatically detects your project is compatible with modules it will switch it over for you. Unfortunately we don't have a way to automatically detect if third-party addons are compatible; we notified addon developers about a small change they need to make back in November, and apart from that Construct assumes third-party addons are compatible with modules mode. You'll have to contact the addon developers for support, and in the mean time continue to switch the project type manually.

**Closed by AshleyScirra** 2021-02-09 12:02 UTC
Labels: duplicate
