### ISSUE TITLE
Sometimes Crash when editing Collision box.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#3684] opened 2020-03-02 10:05 UTC
## Problem description

Not sure if this is browser related. C3 keep crashing when I try to edit the collision points. I first noticed that the numbers didn't update when i moved the points around, so I tried to manually set the desired number.

The crash followed moving points around or editing numbers.

![image](https://user-images.githubusercontent.com/27011641/75663051-7b1fde00-5c70-11ea-9941-d420b7eb3238.png)

But when one of the numbers is "marked" it doesn't update when you move the point, but C3 does not crash.

## Steps to reproduce

I don't have the exact reproduction steps as it doesn't happen, but when ever it happened both the value input boxes were marked red, and the numbers were not updating correctly when moving the points.

1. Create a new project and add a sprite object,
2. Give the object a ccolor or load a texture.
3. Select the collision box tool.
4. Move the lower right point slighty.
5. edit the Y Value to a whole number.
6. Click the input box to edit the X value.
7. C3 Crashes.

## Observed result

Numbers are not updated when moving points around, and sometimes C3 Crashes.

## Expected result

Numbers should update and C3 should not crash.

## More details

**Affected browsers/platforms:** 

Firefox.

**First affected release:** 

Latest Stable

## System details

Error report information

Type: unhandled exception
File: https://editor.construct.net/r182-4/3rdparty/codemirror/codemirror.js, line 1, col 103728
Message: Error: Permission denied to access property "parentNode"
Stack: hl@https://editor.construct.net/r182-4/3rdparty/codemirror/codemirror.js:1:103728 ld.prototype.pollSelection@https://editor.construct.net/r182-4/3rdparty/codemirror/codemirror.js:1:145990 e@https://editor.construct.net/r182-4/3rdparty/codemirror/codemirror.js:1:145170
Construct 3 version: r182.4
URL: https://editor.construct.net/
Date: Mon Mar 02 2020 11:00:16 GMT+0100 (Central European Standard Time)
Uptime: 120.9 s
Platform information

Browser: Firefox
Browser version: 73.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.7647058823529411
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0
C3 release: r182.4 (stable)
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_filter_anisotropic, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment] 2020-03-02 11:29
Can'r reproduce this one. It looks like the crash report has nothing to do with the Animations Editor, but rather codemirror, which is the library C3 uses to handle the different types of text editing. Codemirror is not used at all inside the Animations Editor.

Was anything open below the Animations Editor which was editing text? Like a JS file, JSON, XML or anything that could be considered text editing.

**Comment by tunepunk** [comment] 2020-03-02 11:36
Nope. I'm pretty sure it has something to do with the input boxes for editing the X Y values for the points when using Firefox. That's possibly the text editing you're referring to. I can send a project where it happens constantly but don't wanna share it publicly.

**Comment by AshleyScirra** [comment] 2020-03-02 11:48
The crash report is also for r182.4. We've made 7 releases since then and it could well already be fixed. Please only file issues if they reproduce in the latest release.

**Comment by tunepunk** [comment] 2020-03-02 11:56
https://www.dropbox.com/s/5r3ytsa6yd7bek8/Elena%20Endless%20Runner%20-%20Construct%203%20beta%20-%20Mozilla%20Firefox%202020-03-02%2012-51-14_Trim.mp4?dl=0

Here's a link to a video of it also happening in the latest Beta.

**Comment by ArtRow** [comment] 2020-03-02 20:04
I had that issue yeaterday. But my steps were:
- select all nodes of collision box to move them all (4 pcs)
- press keyboard arrow to move
- C3 crashes
After restart these steps worked correctly and C3 never crashed again. Also after restart just 1 node changed its position (not 4)

**Comment by DiegoScirra** [comment] 2020-03-03 13:16
Is this still a problem in the latest stable?

**Comment by tunepunk** [comment] 2020-03-03 13:23
Yes just tested. Doing the exact same steps as the video i shared. it only happens in Firefox.
i can share link to project in private mail, where can i send it?

<details><summary>View details</summary>

Error report information

Type: unhandled exception
File: https://editor.construct.net/r189/3rdparty/codemirror/codemirror.js, line 1, col 103728
Message: Error: Permission denied to access property "parentNode"
Stack: hl@https://editor.construct.net/r189/3rdparty/codemirror/codemirror.js:1:103728 ld.prototype.pollSelection@https://editor.construct.net/r189/3rdparty/codemirror/codemirror.js:1:145990 e@https://editor.construct.net/r189/3rdparty/codemirror/codemirror.js:1:145170
Construct 3 version: r189
URL: https://editor.construct.net/
Date: Tue Mar 03 2020 14:18:09 GMT+0100 (Central European Standard Time)
Uptime: 34.4 s
Platform information

Browser: Firefox
Browser version: 73.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.7647058823529411
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0
C3 release: r189 (stable)
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_filter_anisotropic, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment] 2020-03-03 13:58
you can send it to diego@scirra.com

**Comment by DiegoScirra** [comment] 2020-03-09 18:35
@tunepunk 

It seems the crash does not happen in Firefox Nightly, so it might be a bug with Firefox that has already been resolved, but is yet to reach a stable version.

**Comment by AshleyScirra** [comment] 2020-03-10 14:02
@tunepunk - can you reproduce with Firefox Nightly?

**Comment by tunepunk** [comment] 2020-03-11 12:36
I havn't had time to test it on nightly yet. I usually don't keep early builds like that installed. I have to download and test in the next few days.

**Comment by tunepunk** [comment] 2020-04-01 08:26
Sorry for the late reply. I tried to reproduce in Nightly but no crash. Numbers also updated when moving points, although there's still red borders around the X and Y when moving points or editing. Not sure that's anything to worry about. But seems to be solved in nightly, at least no crash from what I could tell, after playing around with it a few minutes.

**Comment by AshleyScirra** [comment] 2020-04-01 15:14
Thanks for checking. Going to close this on the assumption it's a Firefox bug that was fixed.

**Closed by AshleyScirra** 2020-04-01 15:14 UTC
Labels: firefox
