### ISSUE TITLE
Multiplayer doesn't work anymore

### ISSUE THREAD

**Issue by DavideGalilei** [Scirra/Construct-3-bugs#2765] opened 2019-03-24 13:03 UTC
## Problem description

I have made a game with multiplayer mode, but this days the multiplayer doesn' t work anymore

## Attach a .c3p

https://mega.nz/#!BFU11SqA!TyDELRNqJRyu97cG659MUq_CziJPLhfNJVY1BB2KfFY

## Steps to reproduce

1.  Go to the layout named "Multiplayer"
2.  See the code
3. Test with Remote Preview and two windows of a browser or with 2 phones with apk installed and in the menu touch "MULTIPLAYER" button

## Observed result

Multiplayer doesn' t work

## Expected result

Working Multiplayer

## More details
I have tested this in 2 firefox windows (Firefox 65), 2 chrome windows (Chrome 73), 2 Android phones (Lg G7, Zte Axon 7)

**Affected browsers/platforms:** All

**First affected release:**  First started happening in r142

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 47 gb
Storage usage (approx): 60 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R7 Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-03-25 10:29
Does this only happen with release APKs? If so it's likely a duplicate of #2710

**Comment by DavideGalilei** [comment] 2019-03-25 11:27
Yes, it happens, you can see it here: https://play.google.com/store/apps/details?id=com.davidegalilei.platfy

**Comment by DavideGalilei** [comment] 2019-03-25 11:27
> Does this only happen with release APKs? If so it's likely a duplicate of #2710

Yes, it happens, you can see it here: https://play.google.com/store/apps/details?id=com.davidegalilei.platfy

**Comment by AshleyScirra** [comment] 2019-03-25 11:29
OK, closing as duplicate of #2710.

**Closed by AshleyScirra** 2019-03-25 11:29 UTC
