### ISSUE TITLE
Admob+Construct 3 - Umbrella Header "GoogleMobileAds.h" not found"

### ISSUE THREAD

**Issue by Jordan1507** [Scirra/Construct-3-bugs#1231] opened 2018-01-24 13:47 UTC
## Problem description

Hi. I having somme trouble to build my construct game with Xcode because of Admob.
I build my game without Admob, it worked perfectly. So the problem is Admob.

In Xcode, i get 2 errors 
"Umbrella header "GoogleMobileAds.h" not found"
"Could not build Objective-C module 'GoogleMobileAds'"

I search over internet. Ive tried everything (Hopefully, im wrong), but nothing seems to remove these errors. Ive tried downloading the Admob SDK and add it in the Xcode project, doesn't worked. Tried to redefine the search path for headers, for framework, doesn't worked either. So ...
![capture](https://user-images.githubusercontent.com/35769563/35335184-15e1aec8-0115-11e8-8fef-971aee7297ae.PNG)

## Steps to reproduce

1. Add Admob in a project.
2. Build it in Construct 3 for Xcode
3. Try to Build it in Xcode for Itunes connect

## Expected result

Remove these errors for a build

______________________
Thanks for your answer. Hope somebody can give me some clues

Bye :)

**Comment by shortercode** [comment] 2018-01-24 14:09
Are you using the .xcproj file or the .xcworkspace file with xcode?

**Comment by Jordan1507** [comment] 2018-01-24 14:11
Im using the .xcodeproj off course ..

**Comment by shortercode** [comment] 2018-01-24 14:11
try the  workspace file ;)

**Comment by AshleyScirra** [comment] 2018-01-24 14:15
@shortercode - definitely a key point for the tutorial!

**Comment by shortercode** [comment] 2018-01-24 14:16
The workspace file is kinda like a container for multiple projects. We use cocoapods to add the admob dependency, which includes frameworks through the workspace file. This means it can't resolve the framework as part of the project unless you use the workspace file instead.

It's not massively intuitive, but cocoapods is the best module manager for xcode. I'm in the process of publishing a tutorial on using C3 and xcode. I'll link to it when it's done.

@AshleyScirra I'll add in an extra note explaining why the workspace file needs to be used!

**Comment by Jordan1507** [comment] 2018-01-24 14:20
Unfortunatly, i get the error also with the workspace :/
![2](https://user-images.githubusercontent.com/35769563/35336919-1e132afe-011a-11e8-9197-0e42304dfa60.PNG)

**Comment by shortercode** [comment] 2018-01-24 14:29
Did you make any manual changes to the project related the framework? I'm just double checking that everything is working but it should work fine just building with the workspace file.

**Comment by Jordan1507** [comment] 2018-01-24 14:33
Well, for say all, i always got a first error with a provisionning/signing profile conflict, i fix it in the build setting in "Code Signing identity.
And after that error, i get the GoogleAds one. 
After that, I tried with the workspace to add the framework manually, and i still get the error. When i click on the error, i get this : 
![3](https://user-images.githubusercontent.com/35769563/35337582-e9b369d4-011b-11e8-98e9-fddfdb35349e.PNG)

**Comment by shortercode** [comment] 2018-01-24 14:44
Provisioning needs to be set when you open the project, but it isn't needed to run on the simulator. I've just tested a build and it worked fine. I used the following steps:

1. In C3 build as xcode project
2. Download resulting zip file onto mac
3. Unzip file **on the mac** ( important that you don't unzip or rezip the files on a windows machine )
4. Double click on the workspace file
5. Press the build button on xcode

If you've been modifying the frameworks in the project I would recommend rebuilding the project, getting the provisioning to work should be as simple as setting the "Team" in the "Signing" section.

**Comment by Jordan1507** [comment] 2018-01-24 15:41
YES. It worked.
My mistakes was : 
-Use the xcodeproj instead of the workspace.
-Unzip the zip from C3 on Windows and transfer the file on Mac. Must Unzip on mac directly.

Thanks a lot for the help !

**Comment by shortercode** [comment] 2018-01-24 16:00
Glad to hear it works now! I've also added in a warning about the unzipping to the tutorial. It's due to windows not understanding mac symbolic links, so they get turned into normals files that don't work!

Going to mark this as a duplicate as it covers a previously reported issue.

**Comment by shortercode** [comment] 2018-01-24 16:01
Closing as duplicate of #1186

**Closed by shortercode** 2018-01-24 16:01 UTC
Labels: can't reproduce
