### ISSUE TITLE
Color picker in Chrome bug

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#6341] opened 2022-12-17 04:46 UTC
## Problem description

When using the color picker on the properties panel (say, to change layer color), and cursor moves just outside the right edge of the color scale, the selected color changes to grey:

![image](https://user-images.githubusercontent.com/36763350/208225472-64052bb4-7ff9-424e-b747-8e5fea2716a4.png)

## Steps to reproduce

Drag the little circle and move the mouse cursor to the right.

## Observed result

At the right edge the color changes to grey.

**Affected browsers/platforms:** Chrome

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r317.2 (stable)
Browser: Chrome 108.0.5359.125
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 275 gb
Storage usage (approx): 589 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment] 2022-12-19 11:38
I can't reproduce this, seems to work fine for me.

**Comment by DiegoScirra** [comment] 2022-12-19 13:21
We can't really do much about it anyway, because that color picker is the one from the browser.

**Comment by AshleyScirra** [comment] 2022-12-19 14:20
Yeah, I guess, so closing.

**Closed by AshleyScirra** 2022-12-19 14:20 UTC
Labels: can't reproduce
