### ISSUE TITLE
[R120] Adding mobile adverts makes Android version crash on launch since this morning

### ISSUE THREAD

**Issue by cmr333** [Scirra/Construct-3-bugs#2109] opened 2018-10-06 10:32 UTC
## Problem description

Last night I had made a patch to my game and everything went smoothly until I noticed a few polishing could be done here and there this morning, so I patched my game again but the game kept getting crashed as soon as you click on the app.

Took me 2 hours of testing to figure out that it was the "Mobile Adverts" object causing this.

Something changed behind the scenes on your android exporter this morning that may have caused this as last night was working fine.

When I try an old .apk of mine, it works however when I open that old version of my game and export a new .apk then it doesn't work. This is why I'm convinced something has changed with the android exporter as of this morning.

I've tried many old versions and few devices, same results.

Just creating a new project and adding a mobile advert object in your project alone is enough to cause the problem.
## Attach a .c3p

[test.zip](https://github.com/Scirra/Construct-3-bugs/files/2452963/test.zip)

## Steps to reproduce

1. New project
2. Add mobile advert object type

## Observed result

Crashed upon launch on Android

## Expected result

Not to crash

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 7.8 gb
Storage usage (approx): 86 mb (1.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by spinbas** [comment] 2018-10-06 12:59
I had the same issue. In logcat I see this:

    java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
    * should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
    * App ID inside the AndroidManifest. Google Ad Manager publishers should     *
    * follow instructions here: https://goo.gl/h17b6x.                           *
    ******************************************************************************
    
    
        at android.app.ActivityThread.installProvider(ActivityThread.java:5977)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5545)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5484)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
     Caused by: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
    * should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
    * App ID inside the AndroidManifest. Google Ad Manager publishers should     *
    * follow instructions here: https://goo.gl/h17b6x.                           *
    ******************************************************************************
    
    
        at com.google.android.gms.internal.ads.zzmn.attachInfo(Unknown Source)
        at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(Unknown Source)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5974)
        	... 10 more
     16468

**Comment by sotano42** [comment] 2018-10-06 20:38
I have the exact same issue, I was trying to isolate the root cause and found this post and immediately test it. After removing Mobile Advert my app ran.

Did you guys released a new version of the addon?

**Comment by Kyatric** [comment] 2018-10-07 13:32
https://www.construct.net/fr/forum/construct-3/general-discussion-7/mobile-advert-crashes-apk-138399
https://www.construct.net/fr/forum/construct-3/how-do-i-8/mobileadvert-stable-version-r1-138395

For further reference/reports/discussions of other users.

**Comment by shortercode** [comment] 2018-10-08 11:00
Closing as duplicate of #2111.

**Closed by shortercode** 2018-10-08 11:00 UTC

**Comment by shortercode** [comment] 2018-10-08 11:03
A new version of the Admob SDK was released on Friday, which now requires your application ID to be included in the manifest file ( or it will crash the app ).

I've updated the build server to only use the older version of the SDK for now. I will need to patch construct to get the plugin to work with the new Admob SDK.
