### ISSUE TITLE
"or block" causing debug preview not to load

### ISSUE THREAD

**Issue by Ocsid** [Scirra/Construct-3-bugs#5283] opened 2021-12-03 11:23 UTC
## Problem description
Game wont load in debug mode

## Attach a .c3p

[bug.zip](https://github.com/Scirra/Construct-3-bugs/files/7649053/bug.zip)

## Steps to reproduce

1. create new project
2. add two sprites and touch object
3. add event on touched sprite2
4. make event "OR" block
5. add event on sprite1 collision with sprite2
6. run in debug mode

## Observed result

Popup for preview appears but stays completley black after loading completes. 

## Expected result

Debug preview starting game correctly.

## More details

This may be the main bug in a game crash I've experienced where animations stops in normal preview mode, I traced the error down to above described bug.

**Affected browsers/platforms:** 
Constructs own user interface.

**First affected release:** 
observed in r268 stable

## System details

<details><summary>View details</summary>

no crash report

</details
[bug.zip](https://github.com/Scirra/Construct-3-bugs/files/7649116/bug.zip)
>

**Comment by AshleyScirra** [comment] 2021-12-03 11:59
Looks like a duplicate of #5227 and should already be fixed in latest beta. As per the bug report guidelines, please only report issues that reproduce in the latest beta, in order to avoid reporting issues that were already fixed.

**Closed by AshleyScirra** 2021-12-03 11:59 UTC
Labels: duplicate
