### ISSUE TITLE
Animation editor - brush tool changes luminosity of some pixels

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2577] opened 2019-02-02 15:46 UTC
## Problem description
When using brush tool and you have smooth enabled, low hardness and low opacity. It changes drawn color luminosity in certain pixels.
Does not happen when you use circle for example with smooth.

And when you merge alot of similar sprites you get artifacts on sprites, as seen below:
![luminosityartifacts](https://user-images.githubusercontent.com/28864889/52166078-86bd7000-2711-11e9-8247-41ea84b40136.jpg)

## Steps to reproduce

1.Open new, create sprite, open animation editor
2.Resize canvas to 50,50
3.Select brush tool, set hardness 0, opacity 0.3, smooth enabled, select white color(255)
4.Click on canvas, use Eye dropped to get color values
5. See some pixels are different color(different luminosity)

## Observed result
Some pixels have different luminosity. Resulting different colors. It gives nice effects which i like, when color is something different then white, but it might not be correct behavior.

![differentcolor_luminosity](https://user-images.githubusercontent.com/28864889/52166154-2e3aa280-2712-11e9-94a5-eb78990b74b4.jpg)

Something other then white:
Just with different opacity.
![colordif](https://user-images.githubusercontent.com/28864889/52166324-81adf000-2714-11e9-9ec4-eed2ba611705.jpg)

## Expected result
Color made with brush, should have same color but different alpha?
Iam not sure how it should be, just poiting it out.

## First affected release
Tried release 110, and it had similar behavior.

## Affected browsers/platforms
* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.81
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36
C3 release: r135.4 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 1.2 gb (9.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2019-02-14 13:39
Duplicate of #28

The current HTML5 Canvas implementations only support 8 bit color channels, that's 255 values for each channel, red, green, blue and alpha.

The problem with this is that when you start working with very low alpha values, the color blending calculations are not precise enough and you start seeing those color artifacts.

There isn't much to be done about this unfortunately, browser vendors are working on supporting more pixel formats for the Canvas element, there is no way to know when that will be available though.

**Closed** 2019-02-14 13:40 UTC
Labels: duplicate
