### ISSUE TITLE
Poor performance drawing in Animations Editor with long event sheet open

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4584] opened 2021-02-18 19:07 UTC
## Problem description
Could be case from my browser cache. But others could also get it like me.

https://user-images.githubusercontent.com/28864889/108408142-57f99000-722d-11eb-94e0-a6265081e483.mov

Fix another case
[2021-02-18 21-03-10.zip](https://github.com/Scirra/Construct-3-bugs/files/6005174/2021-02-18.21-03-10.zip)

## Attach a .c3p
[bugg (1).zip](https://github.com/Scirra/Construct-3-bugs/files/6005180/bugg.1.zip)

## Steps to reproduce

(steps edited in by Ashley)

1. Open project and ensure large event sheet is showing
2. Edit object type in Project Bar to open Animations Editor
3. Draw in the Animations Editor and observe performance

## Observed result

Slow performance while drawing

## Expected result

Fast performance, ideally equivalent to having no event sheet open

## More details

Your welcome

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by SnipG** [comment] 2021-02-18 19:40
Incognite mode with default theme

https://user-images.githubusercontent.com/28864889/108411878-d0fae680-7231-11eb-9c59-2e576a48c0fc.mov

**Comment by AshleyScirra** [comment] 2021-02-19 12:36
This looks like a [Chrome performance bug I filed in 2017](https://bugs.chromium.org/p/chromium/issues/detail?id=692050). Chrome seems to be doing a slow and unnecessary full-page layout when hit testing elements while drawing in the Animations Editor. It looks a lot faster in Firefox which presumably doesn't have the problem.

Assigning to @DiegoScirra since we may be able to make a simple change to work around full-page layout when drawing in the animations editor specifically. It looks like drawing depends on calling elementsFromPoint, which is what seems to be making Chrome do layout. If there's a way to avoid calling that, maybe performance will be better in Chrome.

**Comment by SnipG** [comment] 2021-02-19 13:29
This does not affect me, but overall:

- Mozilla freezes with that project while chrome handles it pretty good. So, idk if something like that should be comparable with different browsers. It could be just some CSS properties that update themself differently(grid update checks all grid, instead should check just parent), that could be worked around somehow. 

- If user has complex eventsheet, he should be able to remove spritesheet images and replace them by default sprite icon. Because loading all the images into eventsheet could cause performance loss

- from different blog posts, it's suggestable that imagesheet has poorer performance then custom font. So all icons should be made to custom font and font is used as icons.  So when user disables spritesheet images and switches to only using Font icons, he should get massive perf boost.

Other website use spritesheet for icons because they never go into extreme cases like c3 does.

This would require a lot of work and could restrict something, but I just leave it here.

**Comment by DiegoScirra** [comment] 2021-03-03 11:48
I am not 100% sure yet, but I think the problem is, of all things, the pointer position indicator at the bottom left of the Animations Editor. That little piece of text is updated constantly and under certain conditions it triggers Layout at a very high rate.

The way I have been reproducing the issue consistently is with this steps:

1) Open the provided project
2) Switch to **Layout 1**
3) Create a new sprite
4) Close the Animations editor
5) Switch to **Event sheet 1**
6) Open the newly created sprite from the project bar

After doing this the Animations Editor will be sluggish.

Strangely if you do the following steps, the sluggishness will be gone:

1) Close the Animations Editor
2) Double click any action block in the event sheet to edit it
3) Show the Expressions Dictionary
4) Close the edit window
5) Open the Animations Editor from the project bar

Now everything is ok.

If I comment out the single line of code that updates the pointer position in the Animations Editor, the sluggishness is gone completely. Interestingly enough, setting that element's CSS **display** property to **none**, but outright not setting the value does.

**Comment by SnipG** [comment] 2021-03-03 12:26
I make plot thicker. Anyway, i think editor complex as c3 is, it needs some special CSS, or avoid some cases all together. 

I changed animation editor color watches for my theme and saw strange lag, it is larger when large eventsheet is behaind. While simple UI change should not lag editor at all.
Also when playing around with it, the editor went crazy.
https://user-images.githubusercontent.com/28864889/109805408-1228c880-7c2c-11eb-8e1c-b24637737819.mov

**Comment by SnipG** [comment] 2021-03-07 23:32
Simpler reproduce steps are: 
*Enable ui effects has to be disabled
*Enable ui animation has to be disabled

If action is clicked and action dialog is closed while expression dialog was closed(hidden and not with low opacity) bug will occure. 
If user goes back and make expression dialog visible and then closes action dialog, lag will go away.

**Comment by SnipG** [comment] 2021-04-30 16:41
I happened to check some case and saw(similar to tilemap dialog, which check itself each tick). There is huge Main.js that checks UI movement on each tick.
So, overall i bet this is not chrome bug, animation editor problem or long eventsheet problem. It's overcall case where C3 editor checks UI states each change. I know it must update correct stuff, link info between dialogs and runtime, but sure it does not have to do it, when user just moves UI.

Current logic seems, if user changes UI, check all states or things or something. Workaround could be massive to implement, but there should be easy way to only apply Main.js etc when some settings changes and not UI just.

**Comment by AshleyScirra** [comment] 2022-08-09 10:51
Closing as this is an old issue, the problem appears to be related to a known Chrome bug, working around it could prove very difficult, and the workaround is simple (just make sure any long event sheets aren't showing - typical usage is in the Layout View anyway so this should be the case normally anyway).

**Closed by AshleyScirra** 2022-08-09 10:51 UTC
Labels: performance
