### ISSUE TITLE
Remote preview on Ios not working since r277

### ISSUE THREAD

**Issue by mitsuhashish** [Scirra/Construct-3-bugs#5478] opened 2022-02-11 14:32 UTC
## Problem description
Remote preview on IOS not working

## Steps to reproduce
Just try remote preview to IOS on any example from r277 and later

## Observed result
Black screen

## Expected result
The preview works

## More details

![image](https://user-images.githubusercontent.com/59168393/153609872-3a3372e7-4087-423a-bc56-34ac4fa59aca.png)

**Affected browsers/platforms:** 
Safari IOS

**First affected release:** 
worked in r276.2 but broken in r 277
## System details

<details><summary>View details</summary>

</details>

**Comment by SalmanShhh** [comment] 2022-02-13 15:55
would love some update on this 👍 since it incredibly difficult to playtest on an IOS device

**Comment by AshleyScirra** [comment] 2022-02-14 11:40
This is a duplicate of #5403 - the local preview part was fixed in r282, and the remote preview part is already fixed for the next beta.

**Closed by AshleyScirra** 2022-02-14 11:40 UTC
Labels: duplicate
