### ISSUE TITLE
Game preview in Visual Studio crashes when logging in to Xbox Live / Add Local User Timeout

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#1081] opened 2017-12-07 20:09 UTC
## Problem description
UPDATE: It worked today after a new export. Seems the Xbox Live plugin did not save/keep the values (in other report where save button does not enable). I added the IDs again and exported and I could login in the sandbox. Could the missing ID cause the addUser error?
But loggin in takes very long and I got timeout error in console but it showed gamertag in the game.
Console in Visual Studio showed this:

> [Xbox Statistics] Event: Local user added (Error -2146697205: IXMLHttpRequest2Callback::OnError: -2146697205: Das Zeitlimit für diesen Vorgang wurde überschritten.
> c2runtime.js (30690,4)

When I preview my game in Visual Studio on Xbox Live Login the game crashes.
(using sandbox with sandbox user. I added the Xbox Live Nuget package and assigned store entry).
I got this error in the VS log:

> "WWAHost.exe" (Skript): "Skriptcode (MSAppHost/3.0)" geladen. 
> Es wurde eine Ausnahme ausgelöst: in Zeile 31174, Spalte 5 in ms-appx://58213bl4cksh33p-soft.christmasdelivery/c2runtime.js
> 0x803f6107 - JavaScript runtime error: Unknown runtime error
> Das Programm "[12964] WWAHost.exe" wurde mit Code 3 (0x3) beendet.

I tried to make a minimal example without all actions and just used "Xbox Live Sign In" on Start of Layout and got this. Some problem with add user?

> 	getStatisticsManager()["addLocalUser"](xboxUser);
> 
> Die Ausnahme wird von JavaScript-Bibliothekscode aufgefangen. in Zeile 25664, Spalte 5 in ms-appx://58213bl4cksh33p-soft.bugtesting/c2runtime.js
> 0x80070057 - JavaScript runtime error: Falscher Parameter.
> 
> User already in local map
> WinRT-Informationen: User already in local map

I am trying to make a small example just with all my login actionsand post it below tomorrow. (added it)
But it seems only SignIn alone produces an error.

## Attach a .c3p

[XboxLiveLoginExample.zip](https://github.com/Scirra/Construct-3-bugs/files/1541537/XboxLiveLoginExample.zip)

## Steps to reproduce

1. Export Xbox Live enabled UWP app
2. preview in visual studio

## Observed result

Game crashes when logging in.

## Expected result

Login without crash :)

## Affected browsers

* Edge: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 62.0.3202.94
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
C3 release: r71
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 104 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by TheBl4ckSh33p** [comment] 2017-12-10 09:58
The crash/error seems to be gone now after building again with all Xbox Live IDs added again.
Gut sign in takes about 35 seconds everytime and Visual Studio console shows a timeout error. But the Gamertag from GetProfileInfo is still shown.

Is it possible to fix this to make logins faster? I did not have this problem in previous versions without the AddedLocalUser trigger.

> [Xbox Statistics] Event: Local user added (Error -2146697205: IXMLHttpRequest2Callback::OnError: -2146697205: Das Zeitlimit für diesen Vorgang wurde überschritten.

**Comment by AshleyScirra** [comment] 2017-12-12 14:15
I think the best we can do here is handle the errors and try to log a more useful message to the console. We certainly can't make Microsoft's servers go faster for them, you'll need to talk to Microsoft about that. I guess the sandbox servers are slower, it may be faster in production.

**Comment by TheBl4ckSh33p** [comment] 2017-12-15 05:06
Hi. I add some Xbox error messages to the browser console to see what shows up. But sign in in live version today took very long too.

**Comment by TheBl4ckSh33p** [comment] 2017-12-20 14:58
Sign in in sandbox and live with published game still takes about 25-30 seconds. It was much faster in my previous game published a few weeks ago. And Visual Studio always shows the Timeout error mentioned above with and without Silent Sign In (tried normal Sign In too). Is this a Microsoft/SDK or Plugin problem?

I removed most parts of my game to make an example. I kept the login and menu intact so you can see what I did there but I can remove it if its too big. The Signin Layout and eSignIn events are used for this.

[XboxLive Signin and Score Submission Issue.zip](https://github.com/Scirra/Construct-3-bugs/files/1575928/XboxLive.Signin.and.Score.Submission.Issue.zip)

**Comment by AshleyScirra** [comment] 2017-12-20 16:03
If sign-in takes a long time, that's 100% on Microsoft's end.

**Comment by TheBl4ckSh33p** [comment] 2017-12-22 06:26
I tried other creators prog. games yesterday but sign in took only 2-4 seconds for them. Not all were made in construct but I assume something is wrong with the login? My previous game just needs a few seconds too. Updated sdk broke it?

**Comment by AshleyScirra** [comment] 2017-12-22 10:53
It's literally one line of code that says "please log me in and tell me when it's done". The duration in between is 100% on Microsoft's end.

**Comment by TheBl4ckSh33p** [comment] 2017-12-22 12:33
Ok. But I don’t understand why my previous game logs in in 2 sec and new game gets timeout after 30 sec. And I can’t submit highscores anymore. I created a new issue for it. If you did not change the Xbox plugin a change from updated visual studio / sdk must be the reason it stopped working, tight? 🤔

Is it possible to take a look at it again please? Maybe an update is needed so xbox live actions work again. 

My posted example uses an additional debug layout to set highscore but it’s not sent to Xbox Live and getsat() returns 0.

**Comment by AshleyScirra** [comment] 2017-12-22 16:05
We'll be out of the office for a couple of weeks over the holiday season. Given that we haven't changed the Xbox Live plugin lately, it sounds like an issue on Microsoft's side anyway, so it might be better to pursue them about it.

**Comment by TheBl4ckSh33p** [comment] 2017-12-23 14:55
And what’s the best way to let them know it’s broken?
I bet they say the same as usual. It’s not a Microsoft plugin, contact the developer. 🙄

It’s a vital feature to have highscores and I won’t advertise my game as long as it’s broken which leads to less sales and less money to pay for the C3 subscription. 🙁

**Comment by TheBl4ckSh33p** [comment] 2017-12-24 16:20
And do you know what’s the best way to let them know it’s broken?
I posted in the Dev community forums and sent a tweet to Windows Dev. Account. 

I think they say the same as usual. It’s not a Microsoft plugin, contact the developer. 🙄

**Comment by AshleyScirra** [comment] 2018-01-18 18:00
All I've been able to identify from reviewing this report is a possible edge case where signing in twice could in theory show the "User already in local map" error. I've added a fix for this in r80 (and the next C2 update too). Apart from that I really need a minimal project and clear steps to follow to investigate anything else. It's a bit hard to tell but it looks like things later started working anyway?

Here's the test project I use for Xbox Live: [xboxlive.zip](https://github.com/Scirra/Construct-3-bugs/files/1643931/xboxlive.zip) If you still have issues after r80 please try to reproduce it in that project, and file a new issue following all the guidelines. That's the level of project we need, if you throw in a bunch of unrelated game stuff around it it's always far harder to debug.

**Closed by AshleyScirra** 2018-01-18 18:00 UTC
