### ISSUE TITLE
r286-r288  Drawing Canvas and scroll bug

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#5594] opened 2022-04-03 04:43 UTC
## Problem description

We've been using DrawingCanvas to draw a semi-transparent silhouette of a character when it's hidden behind obstacles. 
The character sprite is pasted on the canvas on every tick and the canvas is attached to it with hierarchy.
In r286-r288 the canvas for some reason is now moving slightly ahead of the character.

## Attach a .c3p

https://www.dropbox.com/s/tz7z361yimeg6rs/canvasBug4.c3p?dl=0

## Steps to reproduce

1. Try opening the project in the stable version and in beta
2. Move the red sprite around with arrow keys.

## Observed result

In beta release the shadow is now moving a few pixels in front of the player sprite:

![image](https://user-images.githubusercontent.com/36763350/161411563-75de3619-3229-4501-acaa-251f9d3d2f1e.png)

This happens only when layout is scrolled.

## Expected result

In all previous releases this didn't happen.

## More details

**Affected browsers/platforms:** Chrome/Firefox

**First affected release:** worked in r285 but broke in r286

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 100.0.4896.60
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36
C3 release: r288 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 275 gb
Storage usage (approx): 178 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2022-04-04 10:39
I don't see a project file attached, did you forget to include it?

**Comment by dop2000** [comment] 2022-04-04 12:38
Sorry, added the link.

**Comment by AshleyScirra** [comment] 2022-04-05 12:25
It looks like a regression caused by the fix for viewport handling in #5103. Should be fixed in the next beta.

**Closed by AshleyScirra** 2022-04-05 12:25 UTC
