### ISSUE TITLE
[Beta] Rename File editors UI bug

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#190] opened 2017-05-15 04:52 UTC
## Problem description
When renaming a file editor such as the Array editor and the dictionary editor is open, it will not change to the renamed file name.

## Steps to reproduce

1. Create a new array file or dictionary file.
2. Open the file editor as tab.
3. Rename the file from the project bar.

## Observed result

The opened tab does not successfully renamed.

## Expected result

Tabs should be consistent in the names of the files just like layouts and event sheets.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment] 2017-05-15 09:53
Closing as duplicate of #33

**Closed by AshleyScirra** 2017-05-15 09:53 UTC
Labels: duplicate
