### ISSUE TITLE
C3 crashes when trying to set 9patch to export as JPEG

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1201] opened 2018-01-16 05:22 UTC
## Problem description

Funny enough after that crash i tried recording the steps and windows crashed with blue screen :| seems that one was from nvidia

## Attach a .c3p

9patch template

## Steps to reproduce

![9patch](https://user-images.githubusercontent.com/7268697/34973016-ee27544c-fa8d-11e7-98da-297f3b877455.gif)

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: should not be using shared sprite sheet collection here
Stack: Error at Function.ǃl.ǃpSM (https://editor.construct.net/r78/main.js:2:206255) at t (https://editor.construct.net/r78/main.js:2:173886) at window.assert (https://editor.construct.net/r78/main.js:2:174289) at l.ǃlAq (https://editor.construct.net/r78/main.js:63:177969) at l.ǃlZw (https://editor.construct.net/r78/main.js:63:178289) at i.ǃpLv (https://editor.construct.net/r78/main.js:63:212938) at i.ǃlTi (https://editor.construct.net/r78/main.js:63:214171) at i.ǃlgF (https://editor.construct.net/r78/main.js:63:208351) at e.ǃVzb.ǃVSC (https://editor.construct.net/r78/main.js:74:195383) at e.ǃVzb.ǃVSf (https://editor.construct.net/r78/main.js:74:195286)
Construct 3 version: r78
URL: https://editor.construct.net/index.html
Date: Tue Jan 16 2018 07:15:36 GMT+0200 (GTB Standard Time)
Uptime: 3730.9 s

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r78
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by JeFawk** [comment] 2018-01-16 05:23
Same when using the same export feature on a sprite and setting it to export entire project as jpeg

**Comment by AshleyScirra** [comment] 2018-01-16 12:26
Might be worth me looking in to this if it's in the spritesheeting code, let me know what you think @DiegoScirra

**Comment by DiegoScirra** [comment] 2018-01-16 12:33
This only happens with plugins which have a single image and are not not tiled aswell, such as the 9-patch plugin.

The problem is that these object types initially use a shared sprite sheet collection, but upon changing them to JPEG format they are expected to be in their own sprite sheet collection.

At some point before recreating them they need to be removed from the object types's shared collection. Not too sure where is the best place to do that, so assigning to @AshleyScirra

**Comment by AshleyScirra** [comment] 2018-01-16 18:38
Good catch, should be fixed in r79.

**Closed by AshleyScirra** 2018-01-16 18:38 UTC
