### ISSUE TITLE
Changing an Array's size ignores following Insert actions (C3 runtime) r131

### ISSUE THREAD

**Issue by VonFirflirch** [Scirra/Construct-3-bugs#2486] opened 2019-01-01 14:26 UTC
## Problem description

I wanted to switch to C3 runtime for my project but using an Array's "define size" action will cause subsequent "inserts" to just not happen. From the minimal testing I did, other Array actions still work as intended. C2 runtime also works as intended.

## Attach a .c3p

https://www.dropbox.com/s/snijjkr77rr4bbd/Array_Resizing_Issue.c3p?dl=0
(It's my first time sharing a file like this, I hope I didn't mess up!)

## Steps to reproduce

1. Debug the only layout to see that some actions have been skipped ;
2. Switch to C2 runtime and Debug again to see the difference.

## Observed result

The values meant to have been inserted weren't. The others were successfully added/edited/removed.

## Expected result

Successful value insertions.

## Affected browsers/platforms

* Chrome: yes
* Edge: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r131 (stable)
Language setting: fr-FR

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 213 mb (0.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 705 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

Unrelated issue : Under C2 runtime, it's possible to define Objects' collision filters with Solids with given tags, but that runtime doesn't allow the latters to be set in a Solid object's property bar. Is it normal for the action to be available at all in C2 runtime?

**Comment by shortercode** [comment] 2019-01-03 11:12
Could you file your "unrelated issue" as a new bug please, I believe your right that it shouldn't be available in the C2 runtime. @AshleyScirra will likely want to look into it.

**Comment by shortercode** [comment] 2019-01-03 15:47
Your first action sets the array width to zero, then you attempt to insert at either at `0` or `array.width`. Since the array has a width of 0 there are no valid indices, any index you pass is out of bounds. In the C2 runtime passing the length ( which is out of bounds ) would basically treat insert as append, but the C3 runtime treats it as invalid and hence ignores the action.

I expect this should behave as the C2 runtime does; it may be an implementation error or a conscious change I'm not sure. I checked the equivalent behaviour in JS, which is generally a good starting point for expected behaviour. It matches the C2 runtime, but it clamps values to `0 ... array.length` so out of bounds indexes are not treated as invalid. I'm going to leave this with @AshleyScirra to decide if this needs fixing as he implemented both version of this plugin.

**Comment by VonFirflirch** [comment] 2019-01-03 17:14
> Could you file your "unrelated issue" as a new bug please, I believe your right that it shouldn't be available in the C2 runtime. @AshleyScirra will likely want to look into it.

I'm assuming I don't need a .c3p file for that one?

In any case, thank you for your time.

**Comment by AshleyScirra** [comment] 2019-01-07 14:02
Minimal repro: [array-insert-issue.zip](https://github.com/Scirra/Construct-3-bugs/files/2732991/array-insert-issue.zip)

(note it's best to remove any randomness from bug reports, such as the `choose` expression, to ensure bugs can be deterministically reproduced)

**Comment by AshleyScirra** [comment] 2019-01-07 14:07
OK, the insert issue should be fixed in the next release.

**Closed by AshleyScirra** 2019-01-07 14:07 UTC
Labels: c3runtime
