### ISSUE TITLE
Typing or Tabbing in "Set Position" parameter crashes Construct if the cursor is between text

### ISSUE THREAD

**Issue by daleinen7** [Scirra/Construct-3-bugs#1392] opened 2018-03-16 04:29 UTC
## Problem description

When text is before and after the cursor while typing Construct crashes. I believe it's specifically when the autocomplete options are showing. Because you can type otherwise. 

## Steps to reproduce

1. Create an object
2. In an action Set Position of that object
3. Type "Sprite.X" in the first parameter.
4. Type something in between "." and "X" (I was trying to type "Sprite.ImagePointX(1)")

Alternately if there is already a complete parameter, and you copy and paste information at the end it crashes. 

## Observed result
Construct crashes

## Expected result

To be able to finish the autocomplete. 

## Affected browsers

Desktop version

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r90-2/main.js, line 2, col 228610
Message: Uncaught InvalidStateError: Failed to execute 'surroundContents' on 'Range': The Range has partially selected a non-Text node.
Stack: Error: Failed to execute 'surroundContents' on 'Range': The Range has partially selected a non-Text node. at Function.ǃgOh (https://editor.construct.net/r90-2/main.js:2:228610) at n.ǃhT (https://editor.construct.net/r90-2/main.js:2:228838) at ǃs.ǃG.ǃV.ǃ$Fg.ǃ$FK (https://editor.construct.net/r90-2/main.js:155:117067) at window.ǃ$FL.ǃ$FM (https://editor.construct.net/r90-2/main.js:155:122952) at ǃ$Fw (https://editor.construct.net/r90-2/main.js:155:119380)
Construct 3 version: r90.2
URL: https://editor.construct.net/r90-2/
Date: Thu Mar 15 2018 23:27:29 GMT-0500 (Central Daylight Time)
Uptime: 154.7 s

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r90.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 550 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2018-03-16 13:37
Looks like a duplicate of #1373, should be fixed in r91.

**Closed by AshleyScirra** 2018-03-16 13:37 UTC
Labels: duplicate
