### ISSUE TITLE
Back button closing Android app 

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#4631] opened 2021-03-03 12:47 UTC
## Problem description

Browser back button is set to navigate to layouts but sometimes the Android app is closed and the code I added is not executed. 

## Attach a .c3p

Trying to reproduce. 

## Steps to reproduce

Still trying to reproduce. 

## Observed result

App is minimized. 
## Expected result

Switching to other layout. 

## More details

**Affected browsers/platforms:** 
Chrome, Android

**First affected release:** 
r234
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2021-03-04 12:03
Duplicate of #4259 - it's a Cordova bug: https://github.com/apache/cordova-android/issues/1106

**Closed by AshleyScirra** 2021-03-04 12:03 UTC
Labels: duplicate
