### ISSUE TITLE
Using Del or Back key to edit Image Point X/Y coordinates last digit results in deleting image point

### ISSUE THREAD

**Issue by johnsmith27** [Scirra/Construct-3-bugs#4045] opened 2020-07-20 08:50 UTC
Using Del or Back key to edit Image Point X/Y coordinates last digit results in deleting the image point.

## Steps to reproduce

Open the Animation Editor, add an image point. Put it where you want. Manually edit X or Y coordinates last digit and hit del or back Key.

## Observed result
The image point is deleted.

## Expected result

The last digit is deleted not the image point.

## More details

Sorry not providing much more details, hope this is sufficient..

**Affected browsers/platforms:** Chrome

R204.2 stable, not sure if this comes from this release or not..

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 83.0.4103.116
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
C3 release: r204.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 140 gb
Storage usage (approx): 213 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 6
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment] 2020-07-20 09:49
Please only report issues that reproduce in the latest beta release to avoid reporting issues we've already fixed. This looks like it was already fixed in r207:

> Animations editor: pressing delete or backspace when editing image point coordinates removed the image point itself

**Comment by johnsmith27** [comment] 2020-07-20 10:05
Oh ok sorry, my bad, will keep that in mind for the next time.
Glad it's been fixed !

**Closed** 2020-07-20 11:25 UTC
