### ISSUE TITLE
Selection issue of text in event dialogue box

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#1182] opened 2018-01-12 15:21 UTC
## Problem description

I cannot tell what exactly causes the issue, it seems to happen at random and might have something to do with editing the previous field. When I change the value of one field, then tab to the next field, sometimes the selection is sort of "not a selection" and when I start typing it does not replace it and instead appends it. This can happen in any event, I´m pretty sure it also occationally happens when using the mouse

## Attach a .c3p

🖌 
![tab](https://user-images.githubusercontent.com/31101309/34881488-fc129e04-f7b3-11e7-900f-7ffb372ddaeb.PNG)

## Steps to reproduce

1. Open any event dialogue box
2. Tab to one of the fields and start typing

## Observed result

Instead of replacing the value in the field (even though it is clearly selected) what I type gets appended instead.

## Expected result

The selected value to be replaced.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r77.2
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 216 mb (0.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2018-01-15 13:06
I've looked in to this but I have no idea why this is happening. It looks like it might be a bug in one of our third-party libraries that handle selections.

**Comment by AshleyScirra** [comment] 2018-01-17 13:52
Just realised this is a duplicate of #1025.

**Closed by AshleyScirra** 2018-01-17 13:52 UTC
Labels: duplicate
