### ISSUE TITLE
Crash when canceling export

### ISSUE THREAD

**Issue by dzibus** [Scirra/Construct-3-bugs#474] opened 2017-06-09 13:12 UTC
## Problem description

Editor crashes when when canceling export

## Steps to reproduce

1. Select "Menu -> Project -> Export"
2. Click "Cancel"

## Observed result

Editor crashes

## Expected result

Cancel export and continue work

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot set property 'tag' of null @ TypeError: Cannot set property 'tag' of null at g.ǃwt.then.then.then (https://editor.construct.net/r36/main.js:71:11082) at 
Stack: TypeError: Cannot set property 'tag' of null at g.ǃwt.then.then.then (https://editor.construct.net/r36/main.js:71:11082) at 
Construct 3 version: r36
URL: https://editor.construct.net/
Date: Fri Jun 09 2017 15:07:50 GMT+0200 (CEST)
Uptime: 91.6 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.86
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_5
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36
C3 release: r36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment] 2017-06-09 13:51
Duplicate of #461, already fixed for next build.

**Closed by DiegoScirra** 2017-06-09 13:51 UTC
Labels: duplicate, fixed
