### ISSUE TITLE
R66.2 unable to preview if project uses web fonts

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#994] opened 2017-11-07 14:47 UTC
## Problem description

And we're back to black screen on preview again which was reported and fixed not so long ago. Come on guys.

## Attach a .c3p

editor problem

## Steps to reproduce

1.
2.
3.

## Observed result

black screen on preview

## Expected result

to be able to preview project.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r66.2
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 196 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: ATI Technologies Inc.
Renderer: ATI Radeon HD 5670 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by tunepunk** [comment] 2017-11-07 15:01
My preview worked in 66.2. No issues here. 

Chrome on Mac.

**Comment by mOOnpunk** [comment] 2017-11-07 15:26
Just double checked, R66 preview is working, R66.2 just gives a black screen. Nothing else has changed, same computer, browser, file.

**Comment by XpMonster** [comment] 2017-11-07 15:27
Same. 
I could open my past small experiments, but main project either stuck on loading bar or just black screen. 
Also in most recent versions I had resolvable problem with project throwing crash report dialog or black screen. I just pressed F5 and it worked. Maybe same bug grew larger.

**Comment by AshleyScirra** [comment] 2017-11-07 15:50
No issues here. Everything looks fine. If it fails to load, are there any error messages in the console?

**Comment by mOOnpunk** [comment] 2017-11-07 16:32
The old issue was 981 https://github.com/Scirra/Construct-3-bugs/issues/981

Construct gives no error messages, preview is just black. Debug preview is black but loading is stuck at 0%.

**Comment by XpMonster** [comment] 2017-11-07 16:46
Can confirm that Remote Preview does work fine. 
So I decided to change my preview settings. All three don't work. Everything was just fine on r65 and r66

If it doesn't gets fixed soon I should waste a week to rebuild my project in Construct 2.  
All for the better. For a serious commercial project it's far more reliable at the moment.

**Comment by newman321** [comment] 2017-11-07 16:50
@AshleyScirra  i can send you .c3p file but not here and publicly

**Comment by mOOnpunk** [comment] 2017-11-07 17:04
Mine definatly not a network error. As i say R66 works fine so something must have been changed in R66.2. Providing a .c3p is not going to help as its an editor problem. Not matter what file i try to load i get a black preview screen. 
I'm sorry its difficult for you to fix but leaving it is not surely an option?

**Comment by AshleyScirra** [comment] 2017-11-07 18:48
Please provide at least any errors in the browser console if it doesn't work for you. There is still almost nothing for me to go on here, and the messages there could be important.

If it doesn't work does pressing F5 successfully load it?

**Comment by mOOnpunk** [comment] 2017-11-07 19:30
This is the console error, but as i say my network connection is not the problem. The files are loading in previous versions ok, only r66.2 is the problem.

![screen shot 2017-11-07 at 19 24 40](https://user-images.githubusercontent.com/30123541/32513353-df8bce4a-c3f1-11e7-9814-f327f547d170.png)


Remeber that error a while ago where people tried to load c3 and couldnt connect, you said its not us, then a few more people posted, you check and found an error? Please continue to check. I know this is not a problem my end.

**Comment by newman321** [comment] 2017-11-07 19:35
i have tried with another profile in chrome and still its not working

**Comment by newman321** [comment] 2017-11-07 19:51
seems it something related to fonts, i added some fonts to  my Ok project and now it doesnt works eighter

**Comment by newman321** [comment] 2017-11-07 19:54
removing fonts solves the problem in test project 
[TestProjectforcloudsave.zip](https://github.com/Scirra/Construct-3-bugs/files/1451413/TestProjectforcloudsave.zip)

Example project

**Comment by AshleyScirra** [comment] 2017-11-07 19:55
@newman321 that project uses a third-party addon (lite tween). Can you produce a minimal project as per the bug report guidelines?

**Comment by newman321** [comment] 2017-11-07 19:56
OK

**Comment by newman321** [comment] 2017-11-07 19:58
[New project.zip](https://github.com/Scirra/Construct-3-bugs/files/1451425/New.project.zip)
Here you are.

**Comment by mOOnpunk** [comment] 2017-11-07 20:15
I also have litetween installed, and use fonts.

**Comment by tunepunk** [comment] 2017-11-07 20:18
I got black screen as well after adding font, and testing attached project.

**Comment by XpMonster** [comment] 2017-11-07 20:45
Indeed! Can also confirm that deleting installed fonts resolves the issue!But not an option surely for me. 
Also my previously mentioned issue returned and I finally captured it
[https://i.imgur.com/ULdNi8n.png](url)

**Comment by Picoti** [comment] 2017-11-07 20:52
Hi! I have the same problem. Yes, it's the Fonts since R66.2.
If I delete the fonts in fonts directory, it works.

**Comment by AshleyScirra** [comment] 2017-11-07 21:37
Thanks for the minimal project @newman321, I can reproduce and verified the problem affects projects using web fonts. Other projects should not be affected.

**Comment by AshleyScirra** [comment] 2017-11-08 11:30
I just released r66.3 which should include a fix for this. Can someone confirm this resolves the issue?

**Comment by newman321** [comment] 2017-11-08 11:58
its working again

**Comment by XpMonster** [comment] 2017-11-08 12:21
It absolutely most definitely does!
Thank you, Ashley :+1:

**Comment by AshleyScirra** [comment] 2017-11-08 12:29
Thanks for confirming, marking closed now.

**Closed by AshleyScirra** 2017-11-08 12:29 UTC
