### ISSUE TITLE
stop loop not working for array, dictionary and json

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6683] opened 2023-03-02 11:42 UTC
## Problem description

stop loop not working for array, dictionary and json
## Attach a .c3p

[stopLoopNotWorking.zip](https://github.com/Scirra/Construct-3-bugs/files/10870888/stopLoopNotWorking.zip)

## Steps to reproduce

1. run the project and check the console

## Observed result
only the for loop gets stopped, the other loops count to 3

## Expected result

all 3 loops can be stopped with the stop loop action

## More details
Not being able to stop the loop in these cases can be a performance problem with large array, jsons or dictionaries.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment] 2023-03-02 11:49
just found this old report #1451...
So it's "not a bug" but still it's really awkward that we cannot stop the data type loops, so I am keeping this open.

If the stop loop should only work for system loops, the array, json and dictionary should get their own stop loop action imo.

**Comment by OverboyDev** [comment] 2023-03-02 11:52
same for loopindex

**Comment by AshleyScirra** [comment] 2023-03-02 16:14
This is a duplicate of #1451 and the description does say it applies to "for", "for each" and "repeat" so it's working as documented. For non-bug changes please file a suggestion.

**Closed by AshleyScirra** 2023-03-02 16:14 UTC
Labels: duplicate

**Comment by OverboyDev** [comment] 2023-03-02 16:35
Here is a suggestion i made a few weeks ago for Stop Loop and Loopindex equivalent for JSON https://construct23.ideas.aha.io/ideas/C23-I-63
