### ISSUE TITLE
[Mobile&Touch] Can't rearrange events and actions easily.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#1468] opened 2018-04-05 18:26 UTC
## Problem description

In desktop version it's very easy to select multiple, move around events using drag and drop, with mouse and keyboard. However in mobile version or using a touch capable desktop/tablet device this is very hard to do. It's very hard to drop events into groups and rearrange order of conditions.

You have to resort to use cut/paste functionality which is not very intuitive, as you can only select and move one by one.

## Attach a .c3p

Any built in example will do.

## Steps to reproduce

1. Open any example project on a touch capable device.
2. Go to Event sheet and try to rearrange events using touch.
3. This functionality does not exist, and only cut/paste work somewhat well, but you can only move one by one so very tedious.

## Observed result

Very hard to rearrange events, conditions and actions, especially multiple.

## Expected result

Should be easier to move around events.

Some suggested solutions.

1. Grabbable area dedicated for this purpose, so it won't conflict with scrolling. This is till restructed to moving them one by one.

2. Context menu option (select/move events) closes the context menu. Allows you to select/highlight, one or multiple events, conditions or actions. This "mode" temporarily disables touch scrolling, but scrolling can by done by dragging events to the upper or lower part of the event sheet. Like how you would do with a mouse.

3. Gesture like pinch or something to enter above mentioned select/move mode in event sheet would be great.

4. Or maybe a combination of all.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes

**Comment by tunepunk** [comment] 2018-04-05 18:46
![move_areas_touch](https://user-images.githubusercontent.com/27011641/38385516-5ba2528e-3912-11e8-9f58-ce5e2081119a.jpg)

Areas that could possibly be used for drag&drop with touch.

**Comment by AshleyScirra** [comment] 2018-04-06 08:51
Please post feature suggestions here: https://construct3.ideas.aha.io/

The current limitations are by design. The mobile view is currently intended for reviewing and tweaking rather than heavy productivity work. As you've noted, some features need fundamentally re-thinking and re-designing to work conveniently on mobile. This could be a lot of work and difficult to get right, and it's not something we're prioritising right now. Anyway this isn't a bug, it's currently meant to work like this, so closing.

**Closed by AshleyScirra** 2018-04-06 08:51 UTC
Labels: enhancement

**Comment by bilgekaan** [comment] 2019-01-18 00:57
Please add this feature. It's important and fundemental for touch base devices. It's great that we can open C3 on mobile devices or tablets but without this feature it's not usable. Mobile devices quite powerful and we can use them for developing our games. Also please enable the search bar for event/action windows for mobile like in instert object window.
