### ISSUE TITLE
Some saved projects can no longer be re-opened

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#4783] opened 2021-04-30 14:38 UTC
## Problem description

Lately, when attempting to re-open projects saved as a .c3p that have previously worked fine, I'm instead met with a message that I've "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project." At times I've been able to load an auto-saved backup version of such projects, but the project I'm currently working on will no longer open and neither will its last auto-saved backup file...

## Attach a .c3p

[Common2MA.zip](https://github.com/Scirra/Construct-3-bugs/files/6405977/Common2MA.zip)

## Steps to reproduce

1. Attempt to open the attached zipped project, Common2MA.c3p.
2. See "failure to open" message.

## Observed result

The project will no longer open.

## Expected result

The project would open as it has before.

## More details
Unfortunately I still don't know why this happens to projects now. Here's what I do know: I've been using Firefox primarily, saving with cloud saves to Google Drive, and have been using the setting to auto-save backups to the same location on Google Drive every 10 minutes. In the recent past when this would happen I could often try to open the most recent backup file which would work (though this often seemed to result in some of Construct's layout appearing to be moved around when it opened? Will try to update with a screenshot if I ever see this again). I have used add-ons in the past but I don't believe any have been used with this project which will no longer open.

I have tried opening a copy of this broken project after it was saved to my machine in case the issue was with loading from the cloud. Didn't fix it. Tried renaming the .c3p to a .zip and then back to a .c3p. Didn't fix it, still not being taken as a real .c3p file. Tried clearing my cache in case it had something to do with the browser. Didn't fix it. Tried renaming it to a .zip and taking the contents out into their own folder and opening that as a project folder instead of as a .c3p. Similar error, it was not considered a real project folder.

**Affected browsers/platforms:** Firefox, Chrome, Edge.

**First affected release:** No later than r241 (but I also tried opening this on r246 and that also didn't work)

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 88.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
C3 release: r241 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 418 kb (0%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by ChromeWisp** [comment] 2021-04-30 14:40
Could this have something to do with the periodic prompts to re-log-into Google to save to Google Drive? Like maybe something went wrong while logging in there one time, causing the save that happens after login is confirmed to get messed up in some way?

**Comment by DiegoScirra** [comment] 2021-04-30 14:49
Have you  checked the console for errors? You can bring it up by hitting CTRL + SHIFT + I in both Chrome and Firefox. Recently a bug was fixed about projects mysteriously not opening, it might be the same.

**Comment by DiegoScirra** [comment] 2021-04-30 14:52
It doesn't look like it is the same, but it looks like it is easy to reproduce, assigning to @AshleyScirra because it looks like it has something to do with the Guided Tours feature.

An error about it shows up in console when trying to open the project.

**Comment by ChromeWisp** [comment] 2021-04-30 14:54
Ohhh. Okay because yes I just opened the console and saw "[Project] Exception opening:  Error: invalid function name 'Next Tutorial Step'" so maybe I used the same function name as one used for the Guided Tours then?

**Comment by DiegoScirra** [comment] 2021-04-30 14:57
On second thought, I'm not so sure it has to do with Guided Tours, the invalid function name threw me off. In any case, it's better to wait for Ash to check this one out.

**Comment by ChromeWisp** [comment] 2021-05-03 13:54
Sometimes instead of outright refusing to open my projects on the start page, it'll try to open the editor for the project but the interface looks strangely messed up, all pushed over to the left, and then it crashes if you try and do anything like open the start page or close the project. I got a screenshot of that this time:

![Screen](https://user-images.githubusercontent.com/4585257/116885089-19992d80-abed-11eb-90ee-b3e5601c1fd3.png)

And this is the information copied from the crash message.

Error report information

Type: unhandled rejection
Reason: Error: g is null @ l.prototype.jJ@https://editor.construct.net/r241/components/bars/projectBar/projectBar.js:48:134 this.uc<@https://editor.construct.net/r241/components/bars/projectBar/projectBar.js:3:203 acd@https://editor.construct.net/r241/main.js:428:387 dispatchEvent@https://editor.construct.net/r241/main.js:424:135 zC@https://editor.construct.net/r241/main.js:2129:195 L9@https://editor.construct.net/r241/main.js:2104:348 And/<@https://editor.construct.net/r241/components/misc/mainMenu/mainMenu.js:5:352 Kd/<@https://editor.construct.net/r241/main.js:1247:431
Stack: l.prototype.jJ@https://editor.construct.net/r241/components/bars/projectBar/projectBar.js:48:134 this.uc<@https://editor.construct.net/r241/components/bars/projectBar/projectBar.js:3:203 acd@https://editor.construct.net/r241/main.js:428:387 dispatchEvent@https://editor.construct.net/r241/main.js:424:135 zC@https://editor.construct.net/r241/main.js:2129:195 L9@https://editor.construct.net/r241/main.js:2104:348 And/<@https://editor.construct.net/r241/components/misc/mainMenu/mainMenu.js:5:352 Kd/<@https://editor.construct.net/r241/main.js:1247:431
Construct 3 version: r241
URL: https://editor.construct.net/
Date: Mon May 03 2021 08:47:47 GMT-0500 (Central Daylight Time)
Uptime: 17.7 s
Platform information

Browser: Firefox
Browser version: 88.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
C3 release: r241 (stable)
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment] 2021-05-04 13:04
The project fails to open because there is an action `Call function "Next Tutorial Step"`, but no function block named "Next Tutorial Step" exists in the project.

@DiegoScirra - I can't see what this has to do with guided tours, it looks completely unrelated. What made you comment about guided tours?

@ChromeWisp - I'm afraid it's impossible to fix the bug that caused this in the first place, unless you can come up with steps to reproduce the problem. It should be impossible for this to happen to a project, since you should be able to observe that doing something like deleting a function block also deletes all its corresponding 'Call function' actions. Perhaps there is some case we overlooked though, but we need to know exactly what it is. I also note that you used r241 - it is possible we already fixed the problem in the latest betas, which is why our bug report guidelines state to only report issues that reproduce in the latest beta. Can you provide steps to reproduce? I'm afraid if you cannot we will close the issue as it's impossible to investigate.

**Comment by ChromeWisp** [comment] 2021-05-04 14:18
Well that's not great. I wish I knew what exact steps led to this pseudo-impossible state but as you can guess, if I knew them I'd have written them in the report, but I don't. In fact, it's weird that this is even about a missing function because I don't remember deleting function "Next Tutorial Step" to begin with.

I think the last I recall regarding that is that I pasted all my tutorial-related code into the project (from another older project), in case I wanted to use it here too, and I would likely have bumped into the message telling me that I don't have the objects that the tutorial events I'm pasting require, so I would have gone back and copied in those objects from the older project and _then_ tried pasting the tutorial-related events from the older project again. So maybe something got broken in the process of pasting from the old project to the new? But like you said that kinda thing doesn't outwardly _seem_ possible so I have no clue.

I mention in the report that I did try opening this project on r246 as well, with no luck. That is the most recent beta version, right?

I think it's worth noting that while I mentioned multiple of my projects no longer wanted to open, apparently today it's only this broken project I sent in my report here that won't open, and so it seems to me like what happened was Construct or my browsers were getting confused by trying to open the broken project and would then refuse to see _other_ projects as valid. So I know you're probably about to close this issue but the next time someone reports that none of their projects open because of this, maybe ask them to try and find which one is truly broken and suggest that restarting the browser and all that may let them open the non-broken ones again? I'm just guessing at what's happened to me here but if we can't fix this I'd at least like to prevent the next person panicking over losing _everything_ instead of just one thing.

**Comment by AshleyScirra** [comment] 2021-05-04 14:47
The project is corrupt. There's no point trying anything else to open it, it will never be able to be opened by anything because its data is invalid. I could try to recover the project if you like, but the same issue could happen again in future unless we figure out what caused it.

If opening a corrupt project causes other valid projects to fail to open, please file a separate issue following all the guidelines for that, as it's a different issue. Similarly, we'd need reliable steps to reproduce to follow in order to investigate.

I'm afraid there's nothing concrete we can follow up on here, so closing. Please do file a new issue with steps to reproduce if you can find them.

**Closed by AshleyScirra** 2021-05-04 14:47 UTC
Labels: no repro

**Comment by ChromeWisp** [comment] 2021-05-04 14:51
@AshleyScirra I would very much appreciate if you could try and recover the project.

I will also plan to file that separate issue when I hopefully have a reliable set of steps to reproduce that.

**Comment by AshleyScirra** [comment] 2021-05-04 15:17
Here's the recovered project: 
[Common2MA-recovered.zip](https://github.com/Scirra/Construct-3-bugs/files/6422095/Common2MA-recovered.zip)

Luckily the problem was simple to correct: it turns out the function was actually named "Next Tutorial Step2", and removing the "2" fixed it. This does point to something involving copy/paste and Construct renaming the function because it thinks something is already using that name, but missing the actions. But as I said, it's still hard to know what really happened.

**Comment by ChromeWisp** [comment] 2021-05-04 15:25
Ohh, that is really interesting. Well thank you for looking into it and recovering this, that saved me a lot of work.
