### ISSUE TITLE
[Desktop Build] the cursor switches to "expand horizontally" while there is nothing to expand

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#1802] opened 2018-07-17 17:16 UTC
## Problem description

When approaching the left border of an event sheet on the desktop build, the cursor switches to "expand horizontally" look. Actually it's the same icon used to move the vertical line between conditions and actions, except that there is nothing to expand.
_[Edit : the problem only seems to happen if there is another bigger project open]_

## Attach a .c3p

Not relevant

## Steps to reproduce

1. Create any conditions
2. Move the cursor around the left side of the condition.

## Observed result

the cursor switches to "expand horizontally" form while there is nothing to expand.

## Expected result

The cursor should stay as an arrow.

## Affected browsers

Desktop build only (NW.js)

**Comment by AshleyScirra** [comment] 2018-07-17 22:29
Which desktop build? We have two now, the NW.js one and the Microsoft Store one. It's useful to always include the system info as the guidelines suggest since it answers questions like this.

**Comment by RabloGames** [comment] 2018-07-18 06:55
Sorry, I didn't know there were two desktop builds. In this case it was on the good old NW.js one.
I'll check the Microsoft Store one immediately! :)

**Comment by AshleyScirra** [comment] 2018-07-18 11:10
Can't reproduce here, it seems to work fine.

Do you have dev tools open by any chance? There is a known issue with that breaking the cursor.

**Comment by RabloGames** [comment] 2018-07-18 12:21
I don't have dev tools open, but I noticed something special. 
If after opening C3 I open a new file and create an event, the problem doesn't happen. If I then open the project on which I'm working (about 300-400 events), then the problem appears in that project and on the new project previously created too.
Also the cursor is always good if the event is the subevent of anything. Problem only happens in the "root". Also no problem happening with groups.

**Comment by AshleyScirra** [comment] 2018-07-18 12:39
Can you provide a project that reproduces the problem?

**Comment by RabloGames** [comment] 2018-07-18 20:45
Sure, I just sent it with detailed explanations on how to reproduce it to support@scirra.com.
I can reproduce the bug every time by following the steps I describe in the email.

**Comment by Kyatric** [comment] 2018-07-20 10:35
This is indeed in the support and I was able to reproduce as well, although to a different position than the one originally provided in the reproduction steps (to me it appeared on the condition rather than the left edge of the event).

Also, it only reproduces in the desktop version.

**Comment by AshleyScirra** [comment] 2018-07-20 11:58
Thanks, could reproduce using emailed project in Chrome as well (so not desktop specific). Should be fixed for the next release.

**Closed by AshleyScirra** 2018-07-20 11:58 UTC

**Comment by RabloGames** [comment] 2018-07-20 12:11
Thanks!
