### ISSUE TITLE
My game hang when Turret behavior is set to disabled on R190 only

### ISSUE THREAD

**Issue by rraffo** [Scirra/Construct-3-bugs#3700] opened 2020-03-10 11:28 UTC
**added a sample to show the problem.**

I didn't get enough information right now but I need to start somewhere.
The problem has started with R190
I have hundreds of sprite with Turret behavior enabled. On a particular circumstance I need to disable the behavior on some sprite.
It appears that a simple disable action it hangs the game.
Please note that the same game on previous version of C3 works perfectly.

At the moment I don't have a sample to show you because I need to recreate a sort of example but I'm not sure it is a simple and quick step...

## Steps to reproduce
[Turret bug r190.zip](https://github.com/Scirra/Construct-3-bugs/files/4314112/Turret.bug.r190.zip)
this is the sample. Instruction included,
if you disable "Obstacle-->Set Turret disable" action into "Turret Acquired" group, the sample works normally.

## Observed result

The game freeze when the turret behavior is disabled on a sprite. It apparently goes in a sort of loop, the debug tabs appears as frozen and the audio effects sounds in continuous/loop.

## Expected result
The game should goes ahead smoothly...

## More details

The problems appears on several PC with Chrome and firefox browser latest public versions.

The problem appears on R190

The problem occure on Windows 7 and Windows 10 systems.
There are no crash report.
I hope to find a way to give you a sample to analyze but at the moment I don't see a logical way prepare it.
Hope the above info are considered as a starting point.

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2020-03-10 12:09
I'm afraid this still gives us absolutely nothing to go on. Since this report is not actionable I'm going to close it, but if you can provide a project demonstrating the issue then I will reopen it and investigate.

**Comment by rraffo** [comment] 2020-03-10 18:38
> I'm afraid this still gives us absolutely nothing to go on. Since this report is not actionable I'm going to close it, but if you can provide a project demonstrating the issue then I will reopen it and investigate.

I have added the sample you have requested... it has been a nightmare find an easy way to extract the problem. Hope this help.

**Comment by AshleyScirra** [comment] 2020-03-16 11:55
I think this is related to a behavior ticking issue we've already fixed in the next release, looks like it's working normally in the development copy here with the fix. Please check this when r191 is out and confirm if that resolves the issue.

**Comment by rraffo** [comment] 2020-03-16 13:49
> I think this is related to a behavior ticking issue we've already fixed in the next release, looks like it's working normally in the development copy here with the fix. Please check this when r191 is out and confirm if that resolves the issue.

Thanks Ashley, of course I will check it and confirm the soonest.

**Comment by AshleyScirra** [comment] 2020-03-16 14:49
r191 is now out, can you verify the issue is resolved there?

**Comment by rraffo** [comment] 2020-03-16 14:50
Give me a minute

Thanks

 

 

Da: Ashley (Scirra) [mailto:notifications@github.com] 
Inviato: lunedì 16 marzo 2020 15:50
A: Scirra/Construct-3-bugs
Cc: rraffo; Author
Oggetto: Re: [Scirra/Construct-3-bugs] My game hang when Turret behavior is set to disabled on R190 only (#3700)

 

r191 is now out, can you verify the issue is resolved there?

**Comment by rraffo** [comment] 2020-03-16 14:59
It looks that now turret behavior doesn’t work anymore.

It doesn’t freeze but it doesn’t work.

 

Da: Ashley (Scirra) [mailto:notifications@github.com] 
Inviato: lunedì 16 marzo 2020 15:50
A: Scirra/Construct-3-bugs
Cc: rraffo; Author
Oggetto: Re: [Scirra/Construct-3-bugs] My game hang when Turret behavior is set to disabled on R190 only (#3700)

 

r191 is now out, can you verify the issue is resolved there?

**Comment by rraffo** [comment] 2020-03-16 15:27
I'm trying to analyze the new problem.
basically it seems that now the there is a problem with the physics. 
The player into the attached c3p file actually has a physic behavior enabled into my game but it doesn't collide anymore with the obstacles.
I guess you'll catch the bug easily because I would not spend another full day to prepare you a sample.... please...

**Comment by AshleyScirra** [comment] 2020-03-16 15:45
The project attached to this issue is working fine for me in r191. Is that project working for you too? If it does I will close this issue, then if you have any other issues, those should be filed separately following all the guidelines again.

**Comment by rraffo** [comment] 2020-03-16 15:54
yes it works, but in order to speed up my troubleshooting can you please give me a tip on what should I look it for?
It looks that immovable objects (the obstacles of the example) doesn't collide anymore with physics objects (the players into the example). This problem doesn't appear into the example but there is into my project. If you would bet on something what should I check?

**Comment by rraffo** [comment] 2020-03-16 16:18
I think I have found what was the issue. 
It doesn't appear as a C3 bug.
Into my project there was a family I was using to disable collision with obstacles. There was also the player.
This was configured in this way since months. Now the player is not collide anymore with obstacles as it is wrongly configured. So... I think that there was a bug into previous release but I didn't catch it because was behave as I expecting.
Did you change something into the "Disable physics collision" or into the family that might correct this?
I still investigating on this to be sure it is everything correct.
please let me know.

**Comment by AshleyScirra** [comment] 2020-03-16 16:40
I'm closing this issue as the originally described problem now appears to be fixed. If you have a different problem involving Physics, please file a new issue following all the guidelines - we need all that information to be able to help.

**Closed by AshleyScirra** 2020-03-16 16:40 UTC

**Comment by rraffo** [comment] 2020-03-16 17:00
I have slightly modified the project correcting the content of the family and now it appears working correctly.
thanks
