### ISSUE TITLE
(Editor) Tilemap Bar - Shift Key to select patch stops working after a while

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#3711] opened 2020-03-14 20:59 UTC
## Problem description
When editing a tilemap, holding the [Shift] key temporary switches to the "select a patch from the tilemap" tool. For whatever reason, this consistently stops working after ~10 minutes of editing tilemaps.

Unfortunately it can take a while to reproduce, but I promise it happens every single time I work on my game's maps.

Probably not the best way to demonstrate the issue, but here's a .gif of me tapping shift enough times that the "Sticky Keys" prompt appears. You can see that the patch tool is never highlighted as it should be. 
![TheGif](https://user-images.githubusercontent.com/36490901/76690245-49156100-660c-11ea-8fb8-5a06ec2da52c.gif)

## Attach a .c3p

A blank project & default tilemap objects will suffice.

## Steps to reproduce

1. Unfortunately I'm having a hard time narrowing it down to reproducible steps. It happens after editing numerous tilemaps in a single layout. Opening & closing the layout / changing layers / switching to event sheet view might affect it.

## Observed result

Holding the [Shift] key to temporary switch to the "select a patch from the tilemap" tool stops working over time.

## Expected result

Holding the [Shift] key to temporary switch to the "select a patch from the tilemap" tool should consistently work.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r190 but this has been happening for a long time.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.132
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
C3 release: r190 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 744 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2020-04-03 10:29
Can't reproduce this issue. I did find that the bar was entering a strange state that could eventually lead to a crash when opening new layouts or closing the one currently being edited. That might have been related to this issue.

Check the next release!

**Comment by AshleyScirra** [comment] 2020-04-06 13:21
r194 is now out, please check again!

**Comment by Tokinsom** [comment] 2020-04-09 06:47
Unfortunately still an issue in the latest release. I'm trying to pay more attention to what I'm doing around the time it stops working, but it seems completely random so far. I've encountered the bug twice already in just a few moments of tinkering. Perhaps try playing with the tilemaps in one of the sample projects?

**Comment by DiegoScirra** [comment] 2020-05-01 10:47
I have only been able to figure out a couple of things so far. 

The first is that if you enable sticky keys when the dialog shows up, then C3 starts behaving strangely.

The second, if you for what ever reason leave the sticky keys dialog open, then the keyboard stops responding entirely, I guess that is the expected behaviour.

None of those seem to be the issue reported though. I have a feeling it has something to do with the sticky keys feature of Windows, so maybe the best thing would be to change the keyboard shortcut for the select tool, for anything other than SHIFT.

**Comment by Tokinsom** [comment] 2020-05-17 22:28
Potentially... It still happens with sticky keys disabled, so eh. It'll be really tedious but I guess I need to sit down and try to figure out how to make this reproducible. It still happens every single time I go to edit my maps.

**Comment by AshleyScirra** [comment] 2020-05-19 15:15
Issues that cannot be reproduced are not actionable, so closing. Please re-file if you can find a way to more reliably reproduce it.

**Closed by AshleyScirra** 2020-05-19 15:15 UTC
Labels: can't reproduce
