### ISSUE TITLE
Importing audio files breaks the project

### ISSUE THREAD

**Issue by cihanyakar** [Scirra/Construct-3-bugs#1309] opened 2018-02-21 11:17 UTC
## Problem description

When a sound file (~mp4~ m4a and ogg) is imported into the project, it results in an error message after reopen.

## Steps to reproduce

1. Right click "Sounds" folder.
2. Select "Import Sounds"
3. Select ~mp4~ m4a and ogg files.
4. Save the project as **FOLDER**
5. Reopen the project

## Observed result

An error message :

> Failed to open project. Check it is a valid Construct 3 folder project.

## Expected result

Expected to open properly.

## System details

r85 **desktop** build.
Folder project type (`c3proj`)
Microsoft Windows [Version 10.0.16299.248]  x64

## Changed Files

project.c3proj
![image](https://user-images.githubusercontent.com/5078937/36477627-f2e481e8-1712-11e8-9972-3d5c82175b4d.png)

project.uistate.json
![image](https://user-images.githubusercontent.com/5078937/36477649-070e51c6-1713-11e8-9185-5380bda1dbec.png)

**Comment by AshleyScirra** [comment] 2018-02-22 12:27
I can't reproduce this if starting with a new project. Are you working from an already-saved folder project?

**Comment by AshleyScirra** [comment] 2018-02-22 12:28
Right, yes you first need to save a new empty project to a folder. If you start with an unsaved new project it does not reproduce.

**Comment by AshleyScirra** [comment] 2018-02-22 12:35
Looks like newly imported files have their changed flag set to false, which means saving a folder project bypasses them (because it thinks they're already saved in the folder and don't need updating). The fix is to make sure newly imported files have their changed flag set to true. There's quite a lot of import code though and it's all Iain's, so assigning to him.

**Comment by shortercode** [comment] 2018-02-22 13:03
@AshleyScirra Under what circumstances are you not seeing the isChanged flag not being set?

I've tried:
- Adding a new audio file
- Adding a new text file
- Adding a new audio subfile
- Adding a new text subfile

... and they all seemed to work, at least in the web version.

**Comment by AshleyScirra** [comment] 2018-02-22 13:10
It's when you import files that don't need converting (e.g. .m4a and .ogg) - when you next press save, the changed flag on the sub files is false, so it skips saving it in folder mode.

**Comment by shortercode** [comment] 2018-02-22 13:30
Ah I'm seeing the project file marked as changed, but not the new subfile. Presuming that's what you mean?

**Comment by cihanyakar** [comment] 2018-02-22 15:51
Also, the audio files are not copied to project folder.

**Comment by shortercode** [comment] 2018-02-23 11:54
@AshleyScirra I've committed changes that seem to correct the issue where a SubFile is not saved, but I'm experiencing some strange behaviour around deletion and renaming.

1. Delete subFile
2. Save
3. Note; related file is not deleted from windows folder
4. Delete projectFile
5. Save
6. Note; neither file has been deleted from windows folder
7. Import new audio file
8. Save
9. Note; new file has been created in windows folder
10. Rename audio file to match one of the deleted ones
11. Save
12. Note; new audio file is deleted, old one is replaced with content from new ( this is correct )

**Comment by AshleyScirra** [comment] 2018-03-02 16:48
Fixed the removal of deleted project files for the next release.

**Closed by AshleyScirra** 2018-03-02 16:48 UTC
Labels: desktop
