### ISSUE TITLE
Tilemap possible bad indexing

### ISSUE THREAD

**Issue by flipog** [Scirra/Construct-3-bugs#747] opened 2017-08-25 00:36 UTC
## Problem description

My tilemaps just got rearranged.

## Attach a .c3p

I cannot give a small file because it is a game under production. Also I tried to replicate the issue, but new files do not suffer from this, every old one does.

EDIT: Only files in which I resized the tilemap were affected.
EDIT 2: It did not happen in tandem with the resizing. The resizing was done previously and worked fine until the last update.
EDIT 3: It is probably only an editor issue since the game preview is unnafected.

## Steps to reproduce

1. Open an old tilemapped file
2.
3.

## Observed result

Every tile out of place

## Expected result

I would expect the file to maintain its tilemap properties

## Affected browsers

* Chrome: yes
* Firefox: n/a
* Edge: n/a
* Safari: n/a

## System details

There was no crash

**Comment by MarcoWorms** [comment] 2017-08-25 00:43
This is quite a game-breaker for our game. Yesterday we couldn't log in construct and today all our tilemaps got fucked over nothing. I was a advocate for construct but TBH i'm losing faith in this software and i'm almost porting it to another engine that a least keep consistency as their principle. I'm really sad with you guys and I honestly honestly hope this has a quick fix. I', sorry for the harsh comment but you are really pushing the boundaries of our confidence in your company.

**Comment by XpMonster** [comment] 2017-08-25 02:13
I think you should post it here in addition to my report. 
No need to spread millions of same reports. 

https://github.com/Scirra/Construct-3-bugs/issues/742

**Comment by XpMonster** [comment] 2017-08-25 02:22
MarcoWorms, a bit more to advocate for C3. 
It's just a beta you should've knew what you're getting into. 
I had the same harsh feelings about it today.
I personally consider myself a fool to create my bold, ambitions project in C3. Still thinking on idea to get it all rebuild on C2, but holding faith for now.

**Comment by MarcoWorms** [comment] 2017-08-25 08:58
I mean, It's easy to charge money for a software, label it BETA, break stuff in production and use the beta as an excuse. I'm more than willing to help this grow, I literally don't care if there is a button flickering or all kinds of minor bugs, I might got a bit carried away in my previous comment but I'm seriously loosing trust in construct :/

**Comment by MarcoWorms** [comment] 2017-08-25 08:59
If the beta is gonna make people lose their time having to re-work stuff just don't charge for it then

**Comment by shortercode** [comment] 2017-08-25 10:09
Hey @MarcoWorms sorry the issues have been stressing you out.

I believe this bug only affects how a tilemap looks in the editor, the tilemap rendering code for the editor was updated in R50 to improve performance but the runtime hasn't had this change merged in yet.

However, R50 has several bad issues which we are working to remedy at the moment. While we try our best to keep bugs to a minimum small issues can often cause large issues and a lot of changes went into this release. If your worried about possibly losing projects to a bad release during the beta period I would recommend that you work on a known good release and only moving forward when you know a release is stable. You can access numbered releases at [C3 releases](https://www.construct.net/gb/make-games/releases). If you'd rather stay current you can always switch to an older release if the current one has an unresolved issue.

**Comment by shortercode** [comment] 2017-08-25 10:10
@flipog thanks for the report, but I believe this is a duplicate of #742 so please track on that.

**Closed by shortercode** 2017-08-25 10:10 UTC
Labels: duplicate
