### ISSUE TITLE
since the latest patch, the binary data object seems to slowly make the browser run out of memory over time

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#3260] opened 2019-08-24 04:50 UTC
## Problem description
since the latest patch, the binary data object seems to slowly make the browser run out of memory over time

## Steps to reproduce
I don't know yet, construct 3 just keeps running out of memory  and crashing with r162.2, but it takes a while for it to happen, I'll edit this bug report when i know more, maybe ?

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
C3 release: r162.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 966 mb (5.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2019-08-27 11:30
A project showing how your using the plugin is needed here.

I don't believe we made any changes to the plugin for r162, so it might be a bug in a new version of Chrome? Hard to tell without more information.

**Comment by shortercode** [comment] 2019-09-03 11:15
@eleanorawesome can you provide any more information? Else I will have to close this bug.

**Comment by eleanorawesome** [comment] 2019-09-03 11:16
I can try minimal projects and leaving my computer up at night !!

**Comment by AshleyScirra** [comment] 2019-09-03 11:33
Unfortunately "leave a computer on overnight" is not a feasible thing to include in steps to reproduce, since we may have to follow the steps 10-20 times to be able to diagnose the issue, and such long steps to reproduce would make it infeasible to investigate. I think the only sensible thing to do is close this issue until useful steps to reproduce the problem can be found.

**Closed by AshleyScirra** 2019-09-03 11:33 UTC
Labels: ignored guidelines

**Comment by eleanorawesome** [comment] 2019-09-03 11:34
to narrow it down and help diagnose the issue

**Comment by eleanorawesome** [comment] 2019-09-05 04:22
#3272 is related

**Comment by shortercode** [comment] 2019-09-05 11:22
what alternative were you using to base64, you say it makes it "unusable"? I can't see anything obviously leaky, involved. Perhaps Entity instances are being created in large numbers?

**Comment by eleanorawesome** [comment] 2019-09-05 12:27
I was just sending it without making it base64 because I thought If i encode it and then decode it in base64 then i should just send it without doing that but it breaks somehow, like when i go away from a certain range it teleports long distances and I didn'T really get why.

It works perfectly fine and I can leave it on with those events disabled but when i turn them on, it takes a proportionally longer time to resume after suspending depending on how long it was suspended and if you wait too long it just crashes both the game and the editor.

Maybe it'S related to the multiplayer plugin and how I guess it sorta still runs events when suspended but I'm not sure which ones and it'S not really explained anywhere

**Comment by eleanorawesome** [comment] 2019-09-22 21:10
![image](https://user-images.githubusercontent.com/32940085/65394416-db266600-dd5b-11e9-8b0a-ff9d6ac10419.png)
not sure if related but this showed up after the console said "paused to prevent out of memory crash"

**Comment by shortercode** [comment] 2019-09-23 10:31
This is the entry point for a JS task, so all it's a really saying is "I tried to start a task, but the heap was full". We already knew that it was running out of memory, so that isn't really news :/

What @AshleyScirra said here is important, we can probably track this down but a reproduction that takes ~ 30 seconds is needed. It's not feasible to track the memory allocations for several hours.
