### ISSUE TITLE
Moving file around in the project make the project unopenable 

### ISSUE THREAD

**Issue by elscarpo** [Scirra/Construct-3-bugs#2254] opened 2018-11-05 15:37 UTC
## Problem description

Moving audio files from MUSIC folder to SOUNDS folder breaks the project.  I was trying to clean up and organize audio files.  When i saved and tried to reopen the project, "Failed to open project. Check if it is a valid Construct 3 folder project"

## Attach a .c3p
[elscarpo.zip](https://github.com/Scirra/Construct-3-bugs/files/2549375/elscarpo.zip)

## Steps to reproduce

1.  open project, grab 6 files from the music folders (the ones that start with "tav_")
2.drag them up o the sounds->tav  folder
3.save project
4. try to reopen project

## Observed result

 "Failed to open project. Check if it is a valid Construct 3 folder project"

## Expected result
I expect the project to open normally

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.31.2
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@878cd31214ac27a3996927cd5c9c138b10c9fc8d) NWjs/0.31.2 (like Chrome/67.0.3396.87)
C3 release: r123.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 55 gb
Storage usage (approx): 296 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

[elscarpo.zip](https://github.com/Scirra/Construct-3-bugs/files/2549365/elscarpo.zip)

</details>

**Comment by shortercode** [comment] 2018-11-05 15:43
All that you've included in your attachment is a c3proj file, it only contains project meta data. Please include a C3P file.

Are you moving the files inside construct, or in windows explorer?

**Comment by elscarpo** [comment] 2018-11-05 15:58
within the project, NOT in windows explorer.  

sorry... that c3proj file is the one i click to open the project.  i dont see a c3p... where does it usually live?  sorry. i'm not our project's programmer 
![files](https://user-images.githubusercontent.com/44778845/48009440-58fc6700-e0e1-11e8-8ff8-e1fe90d40c1d.png)

**Comment by elscarpo** [comment] 2018-11-05 16:39
got the file, but it's too big.  can i send a link?  i'm trying to take out some of the audio files etc... but it's corrupting the project...

**Comment by AshleyScirra** [comment] 2018-11-05 16:40
In the browser choose Save as > Download a copy, or in the desktop build, save as a single file. We need the .c3p file to be able to investigate this report.

**Comment by elscarpo** [comment] 2018-11-05 16:41
got it. i did, but the file is too big to attach

**Comment by AshleyScirra** [comment] 2018-11-05 16:42
Please see the bug report guidelines. We generally don't want your entire project. If you cannot reproduce the problem in a new project, please share the file on a cloud service like Dropbox or Google Drive. If you cannot do either then we cannot help you.

**Comment by elscarpo** [comment] 2018-11-05 16:49
[SB.zip](https://github.com/Scirra/Construct-3-bugs/files/2549655/SB.zip)


OK SORRY. GOT IT.   If you take this C3P file and move the files in the music folder that start with "tav_" and move them to the sounds->tav folder, then save.  the project wont open.

**Comment by shortercode** [comment] 2018-11-05 17:38
Haven't been able to reproduce in the browser version, expecting this is a desktop ( folder ) specific issue.

**Comment by shortercode** [comment] 2018-11-05 17:42
It would appear that the files are not moved, but the location is updated in the project. Do you want to take this @AshleyScirra ?

**Comment by elscarpo** [comment] 2018-11-05 20:31
thanks for the update!

**Comment by AshleyScirra** [comment] 2018-11-08 16:03
Minimal repro (just an empty project with a single audio file): 
[project.zip](https://github.com/Scirra/Construct-3-bugs/files/2562471/project.zip)
Reproduces in desktop build with a folder project. Think it's specific to that save mode only.

**Comment by AshleyScirra** [comment] 2018-11-08 16:14
OK, should be fixed in the next release. Thanks for the report, these types of issues are important to fix.

**Closed by AshleyScirra** 2018-11-08 16:14 UTC
Labels: desktop

**Comment by elscarpo** [comment] 2018-11-08 16:16
thank you!
