### ISSUE TITLE
tiled bg offset on url load

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#3291] opened 2019-08-31 15:36 UTC
## Problem description

Loading a texture into Tiled Background results in an offset

## Attach a .c3p

https://www.dropbox.com/s/mx9bzi5r2nirpug/tiledbgurloffset.c3p?dl=1

## Steps to reproduce

1. Note the three different objects in the layout.
2. Run the c3p in browser
3. Enable event 5 if you want to see that the full texture is transfered

## Observed result

Events paste sprites into a Drawing Canvas and then transfer the created texture to both Tiled Background, and Sprite.
Tiled Background is offset, possibly scaled incorrectly.

## Expected result

No offset/ scaling issues

## More details

**Affected browsers/platforms:** Chrome
**First affected release:** 163

## System details
W10

**Comment by AshleyScirra** [comment] 2019-09-02 11:58
I can't make sense of the provided project. I can't see anything that looks wrong, but I don't know what it's supposed to look like either. It also uses lots of sprites with bizarre artwork that makes it hard to tell if it's displaying correctly or incorrectly. Please try to make sure reproduction projects are minimal, using the fewest events and objects possible, to avoid confusion. If there is a problem it should be able to be demonstrated with a single sprite with a simple image. It would help to also show expected vs. observed result screenshots. Can you provide this?

**Comment by pigmalien** [comment] 2019-09-02 15:52
Was the texture in the tiled background not different to the other objects that share the same texture?
I have edited the original file with different artwork, and the layout should show the expected result(sprite), next to the observed result(tiled background).
I have replicated on two machines.

**Comment by AshleyScirra** [comment] 2019-09-03 11:18
I still can't see anything wrong with the attached project. With event 5 both disabled and enabled, I just see this:
![bug3291](https://user-images.githubusercontent.com/768723/64169125-f1b85c00-ce44-11e9-9911-3db186af8389.png)
I still don't know if that is what it's meant to look like or not. I can't see anything wrong though so closing.

**Closed by AshleyScirra** 2019-09-03 11:18 UTC
Labels: can't reproduce, need info

**Comment by pigmalien** [comment] 2019-09-03 14:07
From your screen shot you're either not giving it enough time to tick through the gpu, or it's even more broken than I thought.
[](https://www.dropbox.com/s/7kg2bu5uf2ko04i/tiledbgoffset.png?dl=0)

**Comment by AshleyScirra** [comment] 2019-09-03 17:18
The project doesn't work for me, but I would guess from the description that this is the same as issue #3287, i.e. it's not a bug because it's not correct to assume the drawing canvas image size is the same as the object size. It's based on the display resolution, not the object size.

**Comment by pigmalien** [comment] 2019-09-03 19:51
I agree that the resolution has something to do with it, but if that were the case wouldn't it effect the Sprite object's texture as well?
I tested using on resolution changed to do the compost automatically, and the changed the window size, and it did change the scale of Tiledbg, but not Sprite.
Also the project works perfectly fine if you remove fullscreen mode, or set it to cover in Letterbox Scale, or Off.
What would happen if Sprite had a image url, and it was loaded into Tiledbg?

**Comment by SnipG** [comment] 2019-09-03 21:03
It works correctly, if you preview and do not change preview window size(on clean ingonite tab). But preview -> maximise, close preview and then again -> results wrong scaled images. It's old messy window size bug that affects this. I think there are even reports of this somewhere in this github.
