### ISSUE TITLE
C3 r151 Crash

### ISSUE THREAD

**Issue by shubhamrathi9** [Scirra/Construct-3-bugs#2992] opened 2019-05-30 11:11 UTC
## Problem description

C3 r151 is crashing with an error.

## Attach a .c3p

[Crashed](https://drive.google.com/file/d/1xgHKnI43VsKOHDmyePN35IEXzEiP5bVg/view?usp=sharing)

## Steps to reproduce

It crashes at start of engine itself, but after restarting when engine starts to work... it crashes with anything you do in project.. here is an empty project file that i created and when i tried to add a sprite to it, it crashed!

1. Start C3 engine in r151
2. It crashes with the bug report
3. Nothing else.

## Observed result

Crashes with an error report.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃpIN' of null @ TypeError: Cannot read property 'ǃpIN' of null at Function.ǃpRz (https://editor.construct.net/r151/main.js:2:320867) at Function.ǃpRz (https://editor.construct.net/r151/main.js:2:322022) at Function.ǃpRz (https://editor.construct.net/r151/main.js:2:322022) at Function.ǃpRc (https://editor.construct.net/r151/main.js:2:319983) at Object.ǃKzk (https://editor.construct.net/r151/main.js:159:47933) at Object.ǃKzk (https://editor.construct.net/r151/main.js:159:48085) at Object.ǃwBY (https://editor.construct.net/r151/main.js:159:45308) at async s (https://editor.construct.net/r151/main.js:159:91122) at async https://editor.construct.net/r151/main.js:159:93147
Stack: TypeError: Cannot read property 'ǃpIN' of null at Function.ǃpRz (https://editor.construct.net/r151/main.js:2:320867) at Function.ǃpRz (https://editor.construct.net/r151/main.js:2:322022) at Function.ǃpRz (https://editor.construct.net/r151/main.js:2:322022) at Function.ǃpRc (https://editor.construct.net/r151/main.js:2:319983) at Object.ǃKzk (https://editor.construct.net/r151/main.js:159:47933) at Object.ǃKzk (https://editor.construct.net/r151/main.js:159:48085) at Object.ǃwBY (https://editor.construct.net/r151/main.js:159:45308) at async s (https://editor.construct.net/r151/main.js:159:91122) at async https://editor.construct.net/r151/main.js:159:93147
Construct 3 version: r151
URL: https://editor.construct.net/r151/
Date: Fri May 31 2019 08:40:41 GMT+0530 (India Standard Time)
Uptime: 4.6 s

Platform information
Browser: Chrome
Browser version: 74.0.3729.169
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
C3 release: r151 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment] 2019-05-30 18:04
@shubhamrathi9 - it's unlikely we'll be able to do anything about this without steps to reproduce the problem in the first place. Please see the bug report guidelines.

**Comment by shubhamrathi9** [comment] 2019-05-31 03:20
@AshleyScirra 
I have told how to reproduce it... for me it happens when i launch C3 in r151, what else can i tell?
here is a screenshot proving the same.
[Showing Error at launch of C3  r151 Engine](https://drive.google.com/file/d/1e_yViG2t40kVsvF52st7sKCoa4m_XxBq/view?usp=sharing)

**Comment by shubhamrathi9** [comment] 2019-05-31 03:26
I tried it in desktop version too and it crashed the same way but when i just tried it in incognito tab of chrome it worked fine. Do you have any guess of what it could be causing the crash based on error i posted?

**Comment by AshleyScirra** [comment] 2019-05-31 10:12
I would guess the storage has somehow been corrupted, so clearing your browser cache should fix it. However we cannot do anything about this problem without knowing how that happened in the first place, hence the requirement to provide steps to reproduce the problem.

**Comment by pkreemer** [comment] 2019-05-31 16:51
I can repro this too, and from what I can tell it's new to R151:

**Desktop Construct 3 beta R151** & browser Chrome 74.0.3729.169 (Official Build) (64-bit)
Windows 10 on Dell XPS laptop, i7 16GB
Crash report info below is from the straight browser version. 

**Steps to Repro**
1) Open Construct 3
2) See crash, click Restart button
3) Construct restarts, and all seems good:
4) For example, open Kiwi Story, run in preview, all seems good.

New in R151, with no new browser extensions installed since using earlier beta releases.
Crash repeats every time I reload Construct 3 R151, either new tab or refresh in existing tab.
Clearing browser cache had no effect.
Removed ValleryPopoff JS plugin from browser Construct 3, but no effect.
Desktop Construct error info seems identical to browser.


**Error report information**
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃpIN' of null @ TypeError: Cannot read property 'ǃpIN' of null at Function.ǃpRz (https://editor.construct.net/r151/main.js:2:320867) at Function.ǃpRz (https://editor.construct.net/r151/main.js:2:322022) at Function.ǃpRz (https://editor.construct.net/r151/main.js:2:322022) at Function.ǃpRc (https://editor.construct.net/r151/main.js:2:319983) at Object.ǃKzk (https://editor.construct.net/r151/main.js:159:47933) at Object.ǃKzk (https://editor.construct.net/r151/main.js:159:48085) at Object.ǃwBY (https://editor.construct.net/r151/main.js:159:45308) at async s (https://editor.construct.net/r151/main.js:159:91122) at async https://editor.construct.net/r151/main.js:159:93147
Stack: TypeError: Cannot read property 'ǃpIN' of null at Function.ǃpRz (https://editor.construct.net/r151/main.js:2:320867) at Function.ǃpRz (https://editor.construct.net/r151/main.js:2:322022) at Function.ǃpRz (https://editor.construct.net/r151/main.js:2:322022) at Function.ǃpRc (https://editor.construct.net/r151/main.js:2:319983) at Object.ǃKzk (https://editor.construct.net/r151/main.js:159:47933) at Object.ǃKzk (https://editor.construct.net/r151/main.js:159:48085) at Object.ǃwBY (https://editor.construct.net/r151/main.js:159:45308) at async s (https://editor.construct.net/r151/main.js:159:91122) at async https://editor.construct.net/r151/main.js:159:93147
Construct 3 version: r151
URL: https://editor.construct.net/r151/
Date: Fri May 31 2019 09:43:42 GMT-0700 (Pacific Daylight Time)
Uptime: 0.8 s

Platform information
Browser: Chrome
Browser version: 74.0.3729.169
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
C3 release: r151 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment] 2019-05-31 17:12
@shortercode - looking at the crash message and the fact it appears to be relatively new, it might be to do with the fact some components are now loaded in the background after the start page appears, and after it restores the last used UI state. So maybe it's crashing because some component was saved but isn't loaded. It shouldn't be saving those project components anyway because they're part of project state, not UI state, and it should have sufficient robustness to handle various things being missing too, but probably a lead to look in to. At a minimum reviewing the relevant code for robustness could fix this.

**Comment by shubhamrathi9** [comment] 2019-05-31 19:26
@AshleyScirra 
its working after clearing browser cache.

**Comment by qrq** [comment] 2019-05-31 20:27
Hi
i have same problem

how an i clear browser cash in desktop ver ?

**Comment by shubhamrathi9** [comment] 2019-06-01 04:51
Just clear cache of your chrome browser and desktop version will start working too.

**Comment by shortercode** [comment] 2019-06-03 11:07
I've made a small change that might have resolved this issue in the next release. As I don't have a replication I can't tell if it has actually fixed it. If anyone hasn't cleared their cache it would be appreciated if they could check if it has fixed the problem.

**Comment by qrq** [comment] 2019-06-03 12:02
Its work fine after i clear cash.

**Comment by pkreemer** [comment] 2019-06-03 15:59
Clearing cache doesn't help me, so I look forward to trying the next release.

And I filed what might be a related issue: #3010  I see the same sort of crash when searching event sheets.

thanks!

**Comment by AshleyScirra** [comment] 2019-06-03 16:08
r152 is out now, can you confirm if fixed?

**Comment by pkreemer** [comment] 2019-06-03 16:21
Fixed on R152, thanks!

**Comment by shortercode** [comment] 2019-06-03 16:24
Glad to hear. Thank you for confirming.

**Closed by shortercode** 2019-06-03 16:24 UTC
Labels: need info, no repro

**Comment by shubhamrathi9** [comment] 2019-06-03 17:38
Not Fixed in desktop version
Error report information
Type: unhandled exception
File: https://editor.construct.net/r152/components/bars/findResultsBar/findResultsBar.js, line 1, col 1223
Message: Uncaught TypeError: Cannot read property 'clear' of null
Stack: TypeError: Cannot read property 'clear' of null at window.ǃOsm.ǃV (https://editor.construct.net/r152/components/bars/findResultsBar/findResultsBar.js:1:1223) at Array.ǃciX (https://editor.construct.net/r152/main.js:159:36624) at ǃc.Event.ǃcWB.ǃcWD (https://editor.construct.net/r152/main.js:2:193402) at ǃc.ǃOi.ǃrT.ǃcxx.dispatchEvent (https://editor.construct.net/r152/main.js:2:191270) at ǃc.ǃOi.ǃrT.ǃcxx.ǃaF (https://editor.construct.net/r152/main.js:2:324100) at ǃc.ǃOi.ǃrT.ǃcxx.ǃaF (https://editor.construct.net/r152/main.js:2:329330) at ǃc.ǃOi.ǃrT.ǃcxx.ǃaF (https://editor.construct.net/r152/main.js:2:340038) at ǃc.ǃOi.ǃrT.ǃcxx.ǃcri (https://editor.construct.net/r152/main.js:2:336421) at ǃc.ǃOi.ǃDA.ǃcr_.ǃcVU.onclick (https://editor.construct.net/r152/main.js:2:338971) at ǃc.ǃOi.ǃDA.ǃcr_.ǃpW (https://editor.construct.net/r152/main.js:52:23363)
Construct 3 version: r152
URL: https://editor.construct.net/r152/
Date: Mon Jun 03 2019 23:07:10 GMT+0530 (India Standard Time)
Uptime: 124.7 s

Platform information
Browser: NW.js
Browser version: 0.38.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.38.0 (like Chrome/74.0.3729.108)
C3 release: r152 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment] 2019-06-03 19:10
That's a different crash report so does not appear to be related to this issue, and anyway appears to have already been filed at #3011.

**Comment by corlenbelspar** [comment] 2019-06-04 02:46
It stopped crashing when I went and deleted the entire Construct 3 folder in my appdata folder, if that helps.

**Comment by shubhamrathi9** [comment] 2019-06-05 14:29
Yes, it is working fine now!
