### ISSUE TITLE
(Platform Behavior) "On Landed" is called in 2 cases it shouldn't be.

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#1530] opened 2018-04-28 02:09 UTC
## Problem description

Case 1) "On Landed" is often called when multi-jumping past a JumpThru platform. 

Case 2) "On Landed" is called when multi-jumping over the corner of a solid object.

IMPORTANT: These 2 bugs do not happen with the built-in double-jump. They only happen when using a "custom" multi-jump by setting the object's Y vector to a negative value. I'm assuming there is some flag in the behavior that's not being called/reset when setting the Y vector to a negative value, so it's not sure whether it's jumping or falling and can land when it shouldn't.

(These bugs apply to C2's platform behavior as well)

## Attach a .c3p

https://www.dropbox.com/s/9x4t94l6w2n0jy5/PlatformBugs.c3p?dl=0

## Steps to reproduce

Case 1) Press up to double-jump through the blue platform a few times
Case 2) Press up to double-jump to the green solid (while moving against it)

## Observed result

Case 1) You'll hear a landing sound effect when jumping through the platform.
Case 2) You'll hear a landing sound effect when jumping around the corner of the green solid.

## Expected result

The sound effect should not play in either of these cases.

## Affected browsers

Tested on NW.js

**Comment by Tokinsom** [comment] 2018-06-20 23:37
Bump.

**Comment by AshleyScirra** [comment] 2018-06-28 14:34
Case 1 should be fixed in the next release. I'm not sure I can reliably reproduce case 2, it seems sometimes it plays the landed sound slightly too early, but when you slide around the top of a corner and land on it that would still count as a landing because it's a new horizontal surface beneath the player. It might be fixed/improved anyway if it's the same issue as case 1.

**Closed by AshleyScirra** 2018-06-28 14:34 UTC
