### ISSUE TITLE
construct 3 crashes in Chrome On ALL of the studios computers

### ISSUE THREAD

**Issue by kundragon** [Scirra/Construct-3-bugs#5471] opened 2022-02-05 09:41 UTC
## Problem description

since three weeks ago, Construct 3 crashes in Chrome On ALL of the studios computers.
It started with one computer, so I uninstalled an erased EVERYTHING. cookies, browsers cache, the construct installed app and chrome itself.
nothing works
I get a "oops, something went wrong" message every time. most of the time when I start a new project up.
sometimes I am able to use C3 for one or two events before it crashes.

## Attach a .c3p

I cannot make one!!!!!!!!!!!!!@!!!!!!!!!@!@#@!#!@#!@#!##@!@#!@#
I cannot move past pressing new project and create.
also, it crashes if I try to load any project from the past, any.

## Steps to reproduce

1. goto: "https://editor.construct.net/"
2. press "new project"
3. select any settings you want
4. press "create"
5. sit back and enjoy

## Observed result

an "oops something went wrong" message with a big exclamation mark.

## Expected result

to be able to run Construct 3 and work. Putting the money I paid for It to use,.

## More details

**Affected browsers/platforms:** Chrome. on all the studios computers. crashes.
the desktop build. crashes.
I have run Edge and it works on Edge, but I do not use Edge in my studio and do not intend to start just for Construct

**First affected release:** best of my knowledge r276.2

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/, line 0, col 0
Message: ResizeObserver loop limit exceeded
Stack: null
Construct 3 version: r276.2
URL: https://editor.construct.net/
Date: Sat Feb 05 2022 11:28:47 GMT+0200 (Israel Standard Time)
Uptime: 3.3 s

Platform information
Browser: Chrome
Browser version: 97.0.4692.99
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
C3 release: r276.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-26.20.100.7985)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment] 2022-02-07 10:26
Looks like a duplicate of #5386

**Closed by DiegoScirra** 2022-02-07 10:26 UTC
Labels: duplicate
