### ISSUE TITLE
Doesn't open construct site

### ISSUE THREAD

**Issue by ERAgames777** [Scirra/Construct-3-bugs#3223] opened 2019-08-16 09:50 UTC
I tried using chrome and opera to go to the site https://www.construct.net/en and here is the error I get:
Critical error
This should not of happened. Please contact support.

System.IndexOutOfRangeException: Index was outside the bounds of the array. at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) at C3.Code.Controls.Application.Caching.Redis.PubSub.PubSubController.OnSubscribed(RedisChannel channelName) in C:\Construct.net\Source\C3Alpha2\Code\Controls\Application\Caching\Redis\PubSub\PubSubController.cs:line 58 at C3.Code.Controls.Application.Caching.Redis.PubSub.PubSubController.SubscribeToCacheKey(RedisChannel cacheKey, Action`2 onMessageReceived) in C:\Construct.net\Source\C3Alpha2\Code\Controls\Application\Caching\Redis\PubSub\PubSubController.cs:line 46 at C3.Code.Controls.Application.Caching.Manager.Manager.Callbacks.OnGotten[T](String cacheKey, CacheType fromType, T objectGot) in C:\Construct.net\Source\C3Alpha2\Code\Controls\Application\Caching\Manager\Callbacks.cs:line 99 at C3.Code.Controls.Application.Caching.Manager.Manager.Get[T](String key, Func`1 getFromExternFunction, Boolean skipLocalCaches) in C:\Construct.net\Source\C3Alpha2\Code\Controls\Application\Caching\Manager\Manager.cs:line 125 at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer) at C3.Code.Caching.CountryPermittedCurrencies.GetPermittedCurrencies(Int16 forCountryID) in C:\Construct.net\Source\C3Alpha2\Code\Caching\CountryPermittedCurrencies.cs:line 60 at C3.Code.Helpers.Currency.Functions.GetVisitorsCurrency(Language contentLanguage, Country currentRegion, UserSession currentSession) in C:\Construct.net\Source\C3Alpha2\Code\Helpers\Currency\VisitorCurrency.cs:line 0 at C3.Code.Controls.SEO.GA..ctor(Global mp) in C:\Construct.net\Source\C3Alpha2\Code\Controls\SEO\GA.cs:line 14 at C3.Pages.Master_Pages.Global.Page_Init(Object sender, EventArgs e) in C:\Construct.net\Source\C3Alpha2\Pages\Master Pages\Global.Master.cs:line 146 at System.Web.UI.Control.OnInit(EventArgs e) at System.Web.UI.Control.InitRecursive(Control namingContainer) at System.Web.UI.Control.InitRecursive(Control namingContainer) at System.Web.UI.Control.InitRecursive(Control namingContainer) at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
![image](https://user-images.githubusercontent.com/33450672/63159507-28b10400-c035-11e9-8856-d5dc582d8e4e.png)

**Comment by AshleyScirra** [comment] 2019-08-16 10:24
Duplicate of https://github.com/Scirra/Construct-3-bugs/issues/3223 (please use the website bug report system for website issues)

**Closed by AshleyScirra** 2019-08-16 10:24 UTC
Labels: duplicate
