### ISSUE TITLE
Runtime Freezes when accessing TileMovement.GridY

### ISSUE THREAD

**Issue by RhapsodyInGeek** [Scirra/Construct-3-bugs#2188] opened 2018-10-26 02:04 UTC
## Problem description
When attempting to use the Object.TileMovement.GridY expression or attempting to move an Object with TileMovement to a Grid location, the Runtime freezes.

## Attach a .c3p
 https://1drv.ms/u/s!Atvbm976TQtmg-F0BdIxdfle6ClMDA

## Steps to reproduce
Attempt to access or modify the Object.TileMovement.GridY behavior variable. 

1. Run project as is. Functions properly.
2. Re-enable the disabled "Append text" action that attempts to access Grid Y, Results in black screen.
3. Disable "Append text" action that attempts to access Grid Y. Re-enable disabled "On start of layout" event. After 3 seconds, instead of moving TileMovement Object to assigned grid position, Runtime freezes.

## Observed result
Runtime freezes on that tick. If the GridY variable is requested on start of layout, Runtime fails to draw a single frame. If the GridY variable is requested in the middle of play, Runtime only displays the frame before the current tick, freezing it in place.

## Expected result
Object.TileMovement.GridY / Set Grid Position Action should return the GridY position / set the grid position respectively

## Affected browsers

* Chrome: yes
* Firefox: untested
* Edge: untested
* Safari: untested

## System details
Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r122 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 62 gb
Storage usage (approx): 111 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment] 2018-10-26 10:15
Think this is a dupe of #2157 ?

**Closed** 2018-10-26 10:54 UTC
