### ISSUE TITLE
facebook instant games upload error

### ISSUE THREAD

**Issue by phill1965** [Scirra/Construct-3-bugs#6429] opened 2023-01-26 09:38 UTC
## Problem description
Must Not Call Private APIs
Games must use the Instant Games SDK properly and should not call private methods directly.

I uploaded a zip file of a test game to instant games. the same test game exactly as it was uploaded successfully before. no changes to it. however this time I get the above error message from facebook.

## Attach a .c3p
[test.zip](https://github.com/Scirra/Construct-3-bugs/files/10507952/test.zip)

## Steps to reproduce
upload to facebook instant games.

1.open test game. 
upload to facebook instant games
2.
3.

## Observed result

above error message.
## Expected result
test game successfully uploaded, as it has been before.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2023-01-26 10:24
Looks like a duplicate of #6428

**Closed by AshleyScirra** 2023-01-26 10:24 UTC
Labels: duplicate
