### ISSUE TITLE
Admob plugin not working

### ISSUE THREAD

**Issue by Leomcs1982** [Scirra/Construct-3-bugs#4941] opened 2021-07-06 18:27 UTC
## Problem description

In test mode all ads work correctly, but in real mode they are not loading, nothing works! It's not a problem with my Admob account as the old version of my game keeps showing ads. No banners, no interstitials, no reward... nothing!

.c3p (R255)
https://app.box.com/s/k28t95upe3jfvp1tfaskohwy3wynr1t5

APK
https://app.box.com/s/g3q3z5hqgto6bv5tmkmqwj81lywbb2k6

## Steps to reproduce

1 - Create banner, interstitial and interstitial with reward
2 - Export any project with the new Admob plugin, with test mode disabled, use a real Admob account. 
3 - Try closing and opening the app a few times.

## Observed result
No ad is loaded

## Expected result

Banner, interstitial and interstitial with reward being displayed in the app as configured

## More details
In previous versions of my game the ads continue to work correctly, only updates created on the R254 are inoperative.

Operating System: Windows 10 Pro
Tested browsers: Chrome, Firefox and Edge
Construct 3 Version: R254 Beta

R253 or lower: Working
R254 or high: Not working

## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 91.0.4472.124
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
C3 release: r254 (beta)
Language setting: pt-BR

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 94 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon HD 5450 Direct3D11 vs_5_0 ps_5_0, D3D11-8.17.10.1433)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2021-07-07 10:21
Please see this forum thread with changes to Mobile Advert in r254: https://www.construct.net/en/forum/construct-3/general-discussion-7/mobile-adverts-plugin-changes-161613

In particular you need to make configuration changes as described in that post. If the problem is caused by the fact you have not yet done those configuration changes, it is not a bug.

**Comment by Leomcs1982** [comment] 2021-07-07 17:35
Hi,

In this tutorial, most of the settings needed are only for IOS and EU regulation.

My project is only available for Android and is restricted to South America.

In the attached sample project, was there any configuration missing for the ad to work? Is my project wrong? If I configured everything correctly, why don't the ads load?

**Comment by DiegoScirra** [comment] 2021-07-08 14:44
Fixed in the next beta. In the r254 the consent status is not updated outside of test mode and this causes the ads to not be shown.

**Closed by DiegoScirra** 2021-07-08 14:44 UTC
