### ISSUE TITLE
Drag Sprite to another layer does not work

### ISSUE THREAD

**Issue by Robsonrpr** [Scirra/Construct-3-bugs#1016] opened 2017-11-18 03:15 UTC
## Problem description

I do not know if it is an error or a feature, but it is not possible to move an object to another layer, just by dragging it, being possible to do this only in the object's settings. Allowing drag the sprite to another layer just like in C2, is much more practical and fast.

## Steps to reproduce

1. Open C3
2. Create a sprite and Two or more layers
3. Try dragging the sprite to the other layer

## Observed result

The sprite is just dragged off the stage.

## Expected result

The sprite should switch to the new selected layer.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment] 2017-11-20 12:17
Looking at #590, it sounds like this was previously possible. Did it break in a recent build or has it never worked?

@shortercode - are you aware of this being a regression and did you assign yourself because you think you broke it? If not, it's all my code so I would prefer to assign to me.

**Comment by AshleyScirra** [comment] 2017-11-20 12:18
Actually the point about dragging instances from the layout view to the layers bar is already mentioned in #590, so closing as duplicate. @shortercode, please note that issue is already assigned to me.

**Closed by AshleyScirra** 2017-11-20 12:18 UTC

**Comment by shortercode** [comment] 2017-11-20 12:24
@AshleyScirra I was expecting it to be C2 compatibility issue, as far as I'm aware I didn't break anything!
