### ISSUE TITLE
Empty Android export still requires default permissions

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#3306] opened 2019-09-05 15:14 UTC
An empty project still requests the `INTERNET` and `WRITE_EXTERNAL_STORAGE` permissions for Android apps. In particular `WRITE_EXTERNAL_STORAGE` is a sensitive permission that shouldn't be requested for an empty project. I would guess `cordova-plugin-file` is adding that by default, but we only need it for reading the local app files.

`INTERNET` permission also isn't strictly necessary, since the game could in theory work entirely offline. Perhaps this could be a checkbox in the export process - like *Require camera permission*, but *Require internet access*, default to checked so things work out of the box, but so the user can uncheck if they know their game is fully offline. I don't know if Cordova itself requires `INTERNET` though; if it does then we're stuck with it.

**Comment by dop2000** [comment] 2019-09-05 15:20
Thanks, Ashley. According to Android documentation:

> If both your minSdkVersion and targetSdkVersion values are set to 3 or lower, the system implicitly grants your app this permission (WRITE_EXTERNAL_STORAGE). If you don't need this permission, be sure your targetSdkVersion is 4 or higher.

So it may be a matter of correctly setting min and target SDK versions in configuration files.

**Comment by AshleyScirra** [comment] 2019-09-05 15:28
A default Android export sets minSdkVersion to 21 (Android 5.0) and targetSdkVersion to 28 (Android 9), so I doubt that applies.

**Comment by shortercode** [comment] 2019-09-05 15:41
One of our components actually requires the targetSDK be 28 to compile, so we would have a bigger issue if that wasn't set.

There is an issue with Cordova at the moment when using Android studio. They set the min/target SDK in the main gradle build script, but this has been depreciated. Android studio will prevent projects from building if you do this. One developer had noted that they deleted the min SDK line from the build script to fix this issue, and ended up with the extra permissions. The build service doesn't usage Android Studio, and doesn't complain about this at the moment. But I wonder if it's silently ignoring this line.

**Comment by shortercode** [comment] 2019-09-24 17:05
I've confirmed that `uses-permission="WRITE_EXTERNAL_STORAGE"` is coming from `cordova-plugin-file`. It's always added, even if it's not needed due to how Android dual stage permissions system works. I think we will have to fork the plugin to remove this. I'm still trying to figure out where `uses-permission="INTERNET"` comes from, but I suspect it is part of the cordova core. If that's true our best way might be to modify the AndroidManifest to remove unwanted permissions after creating the project but before building it... but we will likely have to have a list of permissions we do want stored somewhere, it gets complicated.

**Comment by shortercode** [comment] 2019-09-24 17:33
It would appear to be safe to remove the INTERNET permission as well. Mmm I will think on the best way to do this.

**Comment by shortercode** [comment] 2019-09-27 15:38
After discussion with @AshleyScirra we've decided to leave the INTERNET permission as is. There is a potential way to resolve it but it has an impact on permissions for other plugins, as well as added complexity in multiple places.

As for the WRITE_EXTERNAL_STORAGE permission we have forked the cordova-file-plugin and removed the permission. In case anyone still wants the permission for some reason it's been added to the options dialog next to the camera permission. I'm just completing these revisions, but the change should be in the next beta release.

**Comment by dop2000** [comment] 2019-09-27 16:03
@shortercode , Great, thank you! 
Will this permission be also removed when building projects exported from C2? 
Also, what about the READ_EXTERNAL_STORAGE, will it disappear too?

**Comment by shortercode** [comment] 2019-09-27 16:10
I'm not sure where the READ_EXTERNAL_STORAGE even comes from, blank projects don't appear to include it. If you can send me a project that includes it then I'm happy to review that. If you have the Android SDK set up on your machine you can use `aapt d permissions "MyApp.apk"` to check what permissions an APK includes.

This revision will not affect C2 at the moment. Although the situation with C2 is slightly different. The file plugin is only needed for iOS in the C2 and C2.5 runtimes. But because exports are done for both platforms in C2 Android builds end up with the plugin for no reason.

**Comment by dop2000** [comment] 2019-09-28 01:44
@shortercode I'm sure I've seen READ_EXTERNAL_STORAGE somewhere in my projects, but I can't find it. Maybe the app installer on the phone adds it when it shows the list of permissions during apk installation. (because write permission implicitly includes read permission?)
Anyway, I don't see it in my recent APKs, so it's good.

And thank you so much for clarifying the situation with C2! I removed the file plugin from config.json and config.xml files, the apk was built without the WRITE_EXTERNAL_STORAGE  permission and it's working fine on my phone.
By the way, what's C2.5 runtime? Is this C2 runtime in C3?

**Comment by shortercode** [comment] 2019-09-30 14:49
@dop2000 It's possible that your right, it simply shows the READ permission if WRITE is specified. If you find an example that does include READ_EXTERNAL_STORAGE I would be very interested in looking at it. I'd like to do be able to put these permission issues behind us.

Yeah C2.5 runtime refers to the C2 runtime in C3, Ashley coined it in the [original C3 runtime blog post](https://www.construct.net/en/blogs/construct-official-blog-1/future-construct-runtime-884). He actually refers to it as C2.3 but I'd forgotten that. It's useful to be able to differentiate between the  C2 and C2.5 runtimes, as the version in C3 is slightly different.

> The Construct 2 runtime in the Construct 3 editor (C2.3): this is the Construct 2 runtime with some modifications to be compatible in the new editor, as well as various upgrades corresponding to Construct 3 improvements, such as improved spritesheeting support to work with the new in-editor spritesheeting


As this issue has now reached a beta release I'm going to close this issue.

**Closed by shortercode** 2019-09-30 14:49 UTC
Labels: Android
