### ISSUE TITLE
Crash when trying to delete a json project file [now reproduceable]

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#1601] opened 2018-05-18 01:49 UTC
## Problem description

Tried deleting a project file (dictionary) and I got this error. No idea if I can reproduce it. Happened after creating, moving and editing lots of project files/dictionaries/arrays. Deleted perfectly fine after restart.

## Attach a .c3p

🍞 

## Steps to reproduce

1. delete project file?

## Observed result

Crash

## Expected result

The file to get deleted, but basically anything that isn´t crashing.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Undopoint not present in buffer @ Error: Undopoint not present in buffer at window.ǃcld.ǃKc (https://editor.construct.net/r98/main.js:74:34233) at n.ǃJo (https://editor.construct.net/r98/main.js:63:102511) at x.ǃoj (https://editor.construct.net/r98/components/editors/dataEditor/dataEditor.js:1:1891) at Array.ǃV.ǃc.ǃh.ǃc.ǃq.ǃi (https://editor.construct.net/r98/components/editors/dataEditor/dataEditor.js:1:1306) at ǃc.Event.ǃnSz.ǃnSp (https://editor.construct.net/r98/main.js:2:196053) at ǃc.ǃo.ǃcd.ǃcX_.dispatchEvent (https://editor.construct.net/r98/main.js:2:194287) at ǃc.ǃo.ǃcd.ǃcX_.ǃKc (https://editor.construct.net/r98/main.js:2:315943) at ǃc.ǃo.ǃcd.ǃcX_.ǃKc (https://editor.construct.net/r98/main.js:2:321034) at ǃc.ǃo.ǃcd.ǃcX_.ǃKc (https://editor.construct.net/r98/main.js:2:331689) at window.ǃSL.ǃSC (https://editor.construct.net/r98/components/editors/dataEditor/dataEditor.js:1:10169)
Stack: Error: Undopoint not present in buffer at window.ǃcld.ǃKc (https://editor.construct.net/r98/main.js:74:34233) at n.ǃJo (https://editor.construct.net/r98/main.js:63:102511) at x.ǃoj (https://editor.construct.net/r98/components/editors/dataEditor/dataEditor.js:1:1891) at Array.ǃV.ǃc.ǃh.ǃc.ǃq.ǃi (https://editor.construct.net/r98/components/editors/dataEditor/dataEditor.js:1:1306) at ǃc.Event.ǃnSz.ǃnSp (https://editor.construct.net/r98/main.js:2:196053) at ǃc.ǃo.ǃcd.ǃcX_.dispatchEvent (https://editor.construct.net/r98/main.js:2:194287) at ǃc.ǃo.ǃcd.ǃcX_.ǃKc (https://editor.construct.net/r98/main.js:2:315943) at ǃc.ǃo.ǃcd.ǃcX_.ǃKc (https://editor.construct.net/r98/main.js:2:321034) at ǃc.ǃo.ǃcd.ǃcX_.ǃKc (https://editor.construct.net/r98/main.js:2:331689) at window.ǃSL.ǃSC (https://editor.construct.net/r98/components/editors/dataEditor/dataEditor.js:1:10169)
Construct 3 version: r98
URL: https://editor.construct.net/index.html
Date: Fri May 18 2018 03:46:01 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 22392.7 s

Platform information
Browser: Chrome
Browser version: 66.0.3359.181
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
C3 release: r98 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

EDIT: Another crash, seems to be related. I tried to close the tab for a json file (dictionary) after editing a different file (array)
<details><summary>View details crash 2</summary>
Error report information
Type: unhandled exception
File: https://editor.construct.net/r98/main.js, line 74, col 34233
Message: Uncaught Error: Undopoint not present in buffer
Stack: Error: Undopoint not present in buffer at window.ǃcld.ǃKc (https://editor.construct.net/r98/main.js:74:34233) at n.ǃJo (https://editor.construct.net/r98/main.js:63:102511) at x.ǃoj (https://editor.construct.net/r98/components/editors/dataEditor/dataEditor.js:1:1891) at Array.ǃV.ǃc.ǃh.ǃc.ǃq.ǃi (https://editor.construct.net/r98/components/editors/dataEditor/dataEditor.js:1:1306) at ǃc.Event.ǃnSz.ǃnSp (https://editor.construct.net/r98/main.js:2:196053) at ǃc.ǃo.ǃcd.ǃcX_.dispatchEvent (https://editor.construct.net/r98/main.js:2:194287) at ǃc.ǃo.ǃcd.ǃcX_.ǃKc (https://editor.construct.net/r98/main.js:2:315943) at ǃc.ǃo.ǃcd.ǃcX_.ǃKc (https://editor.construct.net/r98/main.js:2:321034) at ǃc.ǃo.ǃcd.ǃcX_.ǃKc (https://editor.construct.net/r98/main.js:2:331689) at ǃc.ǃo.ǃcd.ǃcX_.ǃKM (https://editor.construct.net/r98/main.js:2:328143)
Construct 3 version: r98
URL: https://editor.construct.net/index.html
Date: Fri May 18 2018 04:33:09 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 2670.2 s

Platform information
Browser: Chrome
Browser version: 66.0.3359.181
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
C3 release: r98 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by shortercode** [comment] 2018-05-18 08:26
Sounds like one for me! I'll see if I can track it down, but I might need a reproduction for this one. This will be the 3rd undo related bug for the array / dictionary editor...

Last one involved making a change, undoing the change then importing a file with the same name!

**Comment by Wackytoaster** [comment] 2018-05-18 13:18
I´ll keep an eye out if I can find a pattern but so far I had no luck, it seems to come out of nowhere sometimes but I´ll make sure to keep posting crashlogs and previous steps whenever it happens.

**Comment by shortercode** [comment] 2018-05-18 13:35
I spent a little while trying to figure it out. No luck so far. I'd guess that you would need to have something on your redo list for this to happen

**Comment by Wackytoaster** [comment] 2018-05-18 14:13
Yeah I defenitely was using Ctrl+Z quite a bunch

**Comment by Wackytoaster** [comment] 2018-05-19 22:33
<details><summary>another one</summary>

Error report information
Type: unhandled rejection
Reason: Error: Undopoint not present in buffer @ Error: Undopoint not present in buffer at window.ǃcld.ǃKc (https://editor.construct.net/r98/main.js:74:34233) at n.ǃJo (https://editor.construct.net/r98/main.js:63:102511) at window.ǃrV.ǃoj (https://editor.construct.net/r98/components/editors/textEditor/textEditor.js:1:3160) at Array.ǃV.ǃ_G.ǃc.ǃq.ǃi (https://editor.construct.net/r98/components/editors/textEditor/textEditor.js:1:5610) at ǃc.Event.ǃnSz.ǃnSp (https://editor.construct.net/r98/main.js:2:196053) at ǃc.ǃo.ǃcd.ǃcX_.dispatchEvent (https://editor.construct.net/r98/main.js:2:194287) at ǃc.ǃo.ǃcd.ǃcX_.ǃKc (https://editor.construct.net/r98/main.js:2:315943) at ǃc.ǃo.ǃcd.ǃcX_.ǃKc (https://editor.construct.net/r98/main.js:2:321034) at ǃc.ǃo.ǃcd.ǃcX_.ǃKc (https://editor.construct.net/r98/main.js:2:331689) at window.ǃrx.ǃrr (https://editor.construct.net/r98/components/editors/textEditor/textEditor.js:1:1407)
Stack: Error: Undopoint not present in buffer at window.ǃcld.ǃKc (https://editor.construct.net/r98/main.js:74:34233) at n.ǃJo (https://editor.construct.net/r98/main.js:63:102511) at window.ǃrV.ǃoj (https://editor.construct.net/r98/components/editors/textEditor/textEditor.js:1:3160) at Array.ǃV.ǃ_G.ǃc.ǃq.ǃi (https://editor.construct.net/r98/components/editors/textEditor/textEditor.js:1:5610) at ǃc.Event.ǃnSz.ǃnSp (https://editor.construct.net/r98/main.js:2:196053) at ǃc.ǃo.ǃcd.ǃcX_.dispatchEvent (https://editor.construct.net/r98/main.js:2:194287) at ǃc.ǃo.ǃcd.ǃcX_.ǃKc (https://editor.construct.net/r98/main.js:2:315943) at ǃc.ǃo.ǃcd.ǃcX_.ǃKc (https://editor.construct.net/r98/main.js:2:321034) at ǃc.ǃo.ǃcd.ǃcX_.ǃKc (https://editor.construct.net/r98/main.js:2:331689) at window.ǃrx.ǃrr (https://editor.construct.net/r98/components/editors/textEditor/textEditor.js:1:1407)
Construct 3 version: r98
URL: https://editor.construct.net/index.html
Date: Sun May 20 2018 00:27:23 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 1674.5 s

Platform information
Browser: Chrome
Browser version: 66.0.3359.181
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
C3 release: r98 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

It´s hard to really tell what exactly I did before the crash happened since I don´t always pay close attention to each step. In this case I was deleting several files, then edited an event referencing one of the files, then deleted the file the event was referencing (in this case I changed the event so it does not reference that file anymore)

**Comment by shortercode** [comment] 2018-05-21 13:50
That one looks like the same error, but for the text editor. They use very similar logic for undo so it's not surprising. 

It's tempting just to plaster over this error, it's basically `I tried to delete a redo point, but it doesn't exist` so it's not a critical issue. It's a case that shouldn't happen though so it worries me what unknown state the editor could get into if the error didn't happen.

**Comment by Wackytoaster** [comment] 2018-05-23 14:13
What an elusive error that is... if I try to get anything to happen it works fine no matter what kind of obscure editing, ctrl-z, duplicating files, deleting files, etc. I do. But the moment I don´t try, poof! Hmm... I´ll keep trying every now and then. Why is it even deleting redo-points? I mean I delete a file shouldn´t that create a redo-point? Also closing a file shouldn´t have any impact on undo-/redo-points, or is there something happening that I´m not aware of? (probably is :D)

**Comment by shortercode** [comment] 2018-05-23 14:48
Well that's a fun story! So most things in C3 are "live" objects, when you change them you are updating the object. Then when you save your project all those live objects are saved to the file. 

There is, however, some types of objects which can't be "live" objects. We store them as Blobs, which is basically an unchangeable chunk of bytes. I'll call these "static" objects. When static objects are updated what we  do is to create a new blob to replace the existing one. This isn't as weird as it sounds, the browsers like blobs to be treated like this. It allows them to do cool things like move them from memory to the hard drive to reduce memory pressure.

The data, text and animations editor all use static objects. So when you open the editor it "unpacks" the object into the editor, and when you close the editor it "packs" that data back up and replaces the old blob. 

Still with me? The real issue is that we can't change a static object without it being open in an editor. Any undo points created by those editors wouldn't work after they are closed. So what we do is keep a list of undo/redo points just for that editor. Then when you close the editor all those undo points are thrown away and a single point that represents the overall change is added to the project. 

The animations editor has a slight advantage that you can only have one open at a time, and you can't change the project in any way while it's open. But the text and data editor are inline, so people expect to be able to switch between them and other things and the undo list to still work and be in the correct order. To do this they add their undo points to the projects list and their own, and try to keep the lists in sync. When they are closed they remove all the points in their list from the projects list. Here is where we find the crash; we try to close text/data editor and it has a point in it's redo list that doesn't exist in the project's redo list. 

So there you go, undo is hard!

**Comment by Wackytoaster** [comment] 2018-05-23 17:03
Hohohoho, there we go indeed! **Your explanation just solved the issue**, or rather, it is now reproduceable. I think what happens is pretty simple. Construct has a limited amount of undo-points, right? Do the two lists have the same maximum lenght? I also found a second issue that might be related. So here is how to reproduce with a fresh project:

1. Create new project
2. Create a dictionary file (that´s what I used but it applies to the others too)
3. Highlight the Size setting
4. Hold arrow up until you reach any number greater than 200 (seems to be the limit of undo-points)
5. Now deselect the size setting (that´s where the second issue comes into play, more to that later)
6. Press Ctrl-Z once (note the blue notification popping up)
7. Close the file --> Crash

And part 2

1. Repeat steps 1-4 from above
2. Now do **not** deselect the highlighted setting
3. Hold Ctrl-Z as long as possible
4. Observe that there are no blue notifications showing up, further, you can ctrl-Z past the limit of 200. If you deselect the setting first, you can ctrl-Z from 205 to minimum 5, then there are no more undo points. If you keep the highlighting you can ctrl-Z from 500 and above to a minimum of 2.
5. Closing the file now also crashes

No wonder the error seemed so random and hard to reproduce. I noticed that the editor usually groups up several consecutive actions into a single undo-point so it´s pretty hard to get above 200 undo points. Using the arrow-key however creates an undo-point for every single incrementation so it´s easy to reach the limit like this. But also working on a single file for a longer time will generate the same result.

Please e-mail me my appreciation-cookie. 🍪

**Comment by shortercode** [comment] 2018-05-31 14:02
Good idea updating the title, been a busy week and completely missed that you had updated this issue! Taking a look now.

**Comment by shortercode** [comment] 2018-05-31 14:23
This is a super amazing catch, very well done! It never occurred to me that the undo limit would cause any issues, kinda kicking myself for not thinking about it.

Your right that the limit is 200 points, and the project buffer removes the oldest point when you try to add the 201st. The data editor buffer wasn't paying attention to this, so it kept all the points.

Part 2 is a nasty side effect of the toolbar spinner... when you have it selected it actually uses the browsers inbuilt text input undo. Ironically it then adds a new undo point to the editor when you do this. I'd prefer that it didn't do that, but the control is also used by the animations editor and relies on the behaviour.

**Comment by shortercode** [comment] 2018-05-31 14:40
Awesome, this issue should be fixed for the next beta release. Thanks for your help :)

**Closed by shortercode** 2018-05-31 14:40 UTC
Labels: can't reproduce
