### ISSUE TITLE
Animation editor, in zoom, sprites are not always pasted to the center of the canvas

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5949] opened 2022-08-01 08:33 UTC
## Problem description

Maybe this is the current design, but I feel that weird.  But it's really useful in some cases. But It may cause more experience problems. 

![1](https://user-images.githubusercontent.com/45864744/182108320-e837532d-386f-43b7-bc3b-68891bea18c8.png)

How should this problem be solved?  
It is to add a shortcut key that can quickly locate the pasted image to the canvas position.

## Attach a .c3p

[Animation-zoom-pasted-issue.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9232256/Animation-zoom-pasted-issue.c3p.zip)

## Steps to reproduce
Check this c3p

## Observed result
![2](https://user-images.githubusercontent.com/45864744/182107657-51506915-1c1b-46c2-b067-fea2abcdda6e.png)

## Expected result

use the num pad quickly placed or use 'C' quickly placed center
![3](https://user-images.githubusercontent.com/45864744/182107666-8d048315-fe00-445c-901f-7a3baff3e2ed.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r304 (beta)
Browser: Chrome 103.0.5060.134
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 229 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2022-08-09 10:58
As this is by design, closing - if you wish to suggest an enhancement please post as a suggestion: https://construct3-21h2.ideas.aha.io/

**Closed by AshleyScirra** 2022-08-09 10:58 UTC
Labels: enhancement
