### ISSUE TITLE
MobileIAP make my app crashes on iOS, when the "purchase" button is pressed.

### ISSUE THREAD

**Issue by DaveedA13** [Scirra/Construct-3-bugs#3464] opened 2019-11-06 17:08 UTC
[Addiction_C3 - VERSION 1.10.4 - Build 169 TEST_IAP.zip](https://github.com/Scirra/Construct-3-bugs/files/3815759/Addiction_C3.-.VERSION.1.10.4.-.Build.169.TEST_IAP.zip)
[CrashLogs.zip](https://github.com/Scirra/Construct-3-bugs/files/3815760/CrashLogs.zip)

## Problem description

MobileIAP make my app crashes on iOS, when the "purchase" button is pressed ("Purchase product" action).

## Attach a .c3p

I included a minimal c3p file AND "crash logs" files provided by Apple, not sure if those can help you...?

## Steps to reproduce

1. Export the project to iOS and archive it in XCode.

2. Run the project (in TEST FLIGHT app on my part) and when I press the "NO ADS" button, the app crashes. Apple confirmed it too in their tests, on a real iPad.

## Observed result

The app "crashes" (is closing instantly).

## Expected result

A "confirm purchase" dialog should appear I suppose... (never succeed to make it work so...)

## More details
I'm on R.174 release of C3 but it's been like that since I started working on my first iOS App, wich was on the latest stable version.

...maybe I did something wrong with my events but I followed the manual. ...and the "Is registration complete" and "Has product" are triggering.

Some names in the manual for MobileIAP entry are wrong compared to what we have in Construct 3 btw, wich make it a little harder to follow, just to let you know.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.39.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.0416666269302368
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.39.0 (like Chrome/75.0.3770.80)
C3 release: r174 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.9 gb
Storage usage (approx): 1 gb (12.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2019-11-08 16:54
Thanks for mentioning the manual, I've updated the terms so that it matches the names of the plugin. Some internal names for actions had been incorrectly used.

The crashlogs aren't supremely useful I'm afraid, as they aren't symbolized. If you can figure out how to do that they might be more useful, but it requires artifacts from the build so I can't do it I'm afraid. All I can see is that it crashed, probably somewhere in StoreKit.

I've attempted to look into this today but have been hampered by various apple ecosystem problems... I'm out of office most of next week, but will take another look at this if I have time.

Are you able to test locally on a device via xcode? If you are and can get me a stack trace it would be most appreciated.

**Comment by shortercode** [comment] 2019-11-08 17:23
I've managed to force some minimal functionality out of xcode... Although my products are appearing as invalid. Attempting a purchase with an invalid product causes the application to crash. So this might be what your seeing. I'm not really sure why my products are appearing as invalid at the moment unfortunately.

**Comment by shortercode** [comment] 2019-11-11 14:15
The release that is going out today should have the patch that prevents invalid products from crashing an app. But the product would still be invalid, so it won't do anything.

Having reviewed my own test application I can see that the store is just not returning any products to me because I wasn't signed in as a test user. Hence the products are marked as "invalid". Registration will still complete even if some/all your products are invalid ( by design ).

I looked through your event sheet and there's a few logical errors. Firstly you use trigger once with "is registration complete" then check if you own a product. Products are generally not marked as owned until AFTER registration has completed, so this is likely to always be false. Secondly you don't check if the product is available for purchase before displaying the button. This is VERY important, as the button won't be able to do anything if the product is unavailable. I realised we don't really talk about this in the manual, so I'm going through and updating it with a few additional points which will hopefully make peoples lives easier.

I'm a little confused by your statement that "Has product" is triggering but you haven't been able to make a purchase... Has product tells you if the user has purchased the product, so this is a little contradictory. Are you actually seeing this?

I expect that you have a configuration error that is preventing your products from appearing, it can be quite difficult to complete all the steps the store requires. There's a number of forms you have to complete regarding tax and payment with Apple before it will work. [I found a checklist](https://stackoverflow.com/questions/7947805/ios-in-app-purchase-no-products-received) of what you need to do before you can make purchases with your app. You can also see [Apple's guide](https://developer.apple.com/in-app-purchase/) on In app purchases, and in particular [the steps](https://help.apple.com/app-store-connect/#/dev8b997bee1) on testing sandbox purchases. You will require a sandbox user to test the purchase yourself, I'm not sure what the procedure is for submitting an app to the store regarding test purchases you should probably look this up. Mobile IAP is one of the hardest plugins to configure and test unfortunately, but it's a reflection of the services it uses so we can't streamline much of this for users.

Purchase flow  and setting up IAP are both quite complicated to get right, and you should really be confirming that it is working for you before submit it to the app store.

I don't think there are any additional actions for me to take right now, as far as I can see the purchases are working correctly. If your app is still crashing with todays update, or you experience issues purchases products that appear as available then let me know and I will reopen this issue.

**Closed by shortercode** 2019-11-11 14:15 UTC
Labels: need info

**Comment by DaveedA13** [comment] 2019-11-20 13:01
Hi Iain (@shortercode),

First, sorry for the late reply and thank you for the quick patch to the IAP that prevent the whole game for crashing. Now I can test/debug my events, I really appreciate it.

I'm not sure if I can reply to you in a closed thread and still get a reply but I'm trying...

Thanks also for all the details, I remade my events, but sadly I still can't make it work, I have the "Unable to purchase invalid product" error message.

So I have 2 quick questions:

1. Is it really the PRODUCT ID of the IAP that I must use or if it's the APPLE ID of the IAP that is also availabe in "App Store Connect"...? Just to be sure... 

2. My IAP can't be "green lighted" by Apple before I submit a version to the App Store with the IAP purchase in it. So can we really test it before sending it for review...?  Apple ask us to always have a validated first version of a free app before being able to add a IAP purchase to it... So I'm a little confused about how to test it and if the error messages will reflect this state or not with a message like "Your IAP status is not approved at this time".

I'm really sad to not being able to make the IAP plugin work because all the other things worked fine and I consider myself not bad with Construct. ;P

I read on the net that our app have more chances of being featured by Apple on the App Store when it have a t least one IAP, since they can make money out of it. My IAP is just a "no ads" option.

Thanks again for your time.

**Comment by shortercode** [comment] 2019-11-20 14:04
It's possible to reply on closed issues, but we generally advise not to. We don't look at closed issues normally, so the notification is the only prompt to remind us. If we miss it your message will likely be forgotten to the sands of time.

> I'm really sad to not being able to make the IAP plugin work because all the other things worked fine and I consider myself not bad with Construct. ;P

Heh well we try hard to make things easy, but many of the Mobile plugins ( like IAP ) require a lot of setup with complex 3rd party services . We can't do anything to improve this so people just have to kind of put up with it. I wouldn't feel too bad about it, everyone struggles to figure the systems out first time they use them.

As per the [checklist](https://stackoverflow.com/questions/7947805/ios-in-app-purchase-no-products-received )I linked previously.

> As mentioned by the official doc there is NO need to submit binaries [...] I have seen a lot of missleading info about this on various blogs.

There's just an awful lot of random things you need to do before the products will work, it took me about a week of fighting to get my test products set up initially. I would recommend taking another look at that checklist. Once you have your products set up you can generate a IAP test account. You sign into your test account on the device you wish to use for testing, then install a debug version onto your device with xcode. You will then be able to do sandbox purchases.

Your product ID is whatever you named it, I think I called mine "toasty" and "coin".

This is an example screenshot I plucked from the documentation showing the product ID, they appear to have chosen more technical names than me!

![InApp_AppDetails-menu-5_2x](https://user-images.githubusercontent.com/9051865/69245336-9160cd00-0b9e-11ea-8c8d-c6b021cd61aa.png)
