### ISSUE TITLE
Problem uploading Instant Games with this Release.

### ISSUE THREAD

**Issue by christian1966** [Scirra/Construct-3-bugs#6456] opened 2023-02-02 06:23 UTC
## Problem description

Hi, I am trying to export my game to Instant Games for facebook. Not working for this release, r327.2. I have an old zip file from the release before from construct. And that is working perfect to upload to Facebook. So why is this happening //Christian

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by XHXIAIEIN** [comment] 2023-02-02 06:26
Don't put your problems in headlines; they won't solve your problems. You might want to provide more information, such as screenshots of the problem, reproducing steps

**Comment by AshleyScirra** [comment] 2023-02-02 09:54
Duplicate of #6428 - please report it to Facebook.

**Closed by AshleyScirra** 2023-02-02 09:54 UTC

**Comment by christian1966** [comment] 2023-02-02 10:32
why did it work with the release before this one

**Comment by christian1966** [comment] 2023-02-02 10:33
Can I Downgrade to the release before ?

**Comment by XHXIAIEIN** [comment] 2023-02-02 10:36
> Can I Downgrade to the release before ?

https://editor.construct.net/r317/

**Comment by christian1966** [comment] 2023-02-02 10:43
When I click the link it is still r327-2 ?  Not as it says in your link.
