### ISSUE TITLE
Javascript error, preview error.

### ISSUE THREAD

**Issue by ERAgames777** [Scirra/Construct-3-bugs#1308] opened 2018-02-21 09:17 UTC
## Problem description

problem when launching a preview of the project

## Attach a .c3p

any project even from Scirra

## Steps to reproduce

-the error occurs in the r87 version for each preview of the project, and if you click "ok", a dark preview screen will appear.
-in r86 version everything works correctly preview.

## Observed result

I see it's 
![error](https://user-images.githubusercontent.com/33450672/36472291-3a281ca4-1713-11e8-8d9f-cc02255ae4ca.png)

## Expected result

awaited preview of the project

## Affected browsers

Chrome: yes

## System details

preview.construct.net

Javascript error!
Uncaught ReferenceError: cr is not defined
blob:https://preview.construct.net/2d9c0c15-daf4-4e3e-bcdf-eb86369a7c11, line 1 (col 1)

This may be a bug in Construct 3 or a third party plugin or behavior - please report it to the developer following the bug report guidelines. Subsequent errors will be logged to the console.

**Comment by AshleyScirra** [comment] 2018-02-21 11:29
Can't reproduce here and sounds like it was resolved anyway so closing.

**Closed by AshleyScirra** 2018-02-21 11:29 UTC
