### ISSUE TITLE
8 Direction can't perform dioganol movement using vector X and Y

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#2799] opened 2019-04-02 13:31 UTC
## Problem description

The 8 Direction behaviour can't perform dioganol movement using set vector X and Y, it only works with simulate control.

As you can see the blue character (simulate control) can walk in a perfect 315 degrees angle, but the red character (vector X and Y) keep floating around 309 degrees, which is incorrect.
https://i.imgur.com/ofM7end.gif

I really hope that you guys can fix it soon, because I first created a movement system using simulate controle for both keyboard and gamepad, then I reworked the whole movement system to use vector X and Y to be able to reach more angles while using a gamepad, then I reverted everything to simulate control because it was not working properly, but then I found out it was a bug in the engine side, so I asked you guys to fix and I reimplemented the set vector X and Y system, but now there's another bug in the engine and I really want to keep using set vector X and Y because it's way more customizable.

## Attach a .c3p

[8 Direction Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/3034089/8.Direction.Bug.zip)

## Steps to reproduce

1. Run the project.
2. Watch the text on the top right corner.

## Observed result

Using set vector X and Y is not 100% reliable.

## Expected result

The set vector X and Y to work just like simulate control, but more customizable.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2019-04-02 13:42
This happens because of the fix to your previously filed bug #2756 that setting the vector X/Y was not clamped to the maximum speed. Now that it does, setting the vector X and Y components clamps each action separately, causing unintended results. The first tick tries to set a speed of (128, -128); this is greater than the maximum speed of the behavior, so it clamps it to approximately (90.5, -90.5) for a magnitude of approximately 128. The problem comes in subsequent ticks: the next time you set a vector X of 128, you're now trying to use a speed of (128, -90.5), which is again beyond the maximum speed so gets clamped to a vector pointing slightly up-to-the-right with a magnitude of 128. Then you set the vector Y and it again clamps it to a vector pointing slightly more to the left with a magnitude of 128. So the clamping keeps shifting the direction of the vector, hence it goes off the intended angle.

The 8 direction behavior is not designed to be controlled solely from setting its vector X/Y. This is why you keep running in to problems. You really should be using the Custom Movement behavior instead. It's working correctly according to the changes you previously asked for (although the changes you asked for make it harder to use now), so closing as by design and wontfix.

**Closed by AshleyScirra** 2019-04-02 13:42 UTC

**Comment by BonzerKitten7** [comment] 2019-04-02 14:05
I reported a bug and you fixed it. I reported another bug and now it's my fault because of your previous fix. **_Yes, make a lot of sense._**

**Comment by AshleyScirra** [comment] 2019-04-02 14:45
Yes, it does make sense, I explained what is happening and it's correctly applying the speed clamping that you previously asked for.

**Comment by BonzerKitten7** [comment] 2019-04-02 15:20
I don't think I've other options. But, please consider making a more refined physics behaviour so we can create any kind of movement without "workarounds", like in Unity. Have you ever seem Colludium version of the Physics behaviour? He uses literally the same library as you but with way more features.
https://colludium.itch.io/box2d-plus

**Comment by AshleyScirra** [comment] 2019-04-02 15:22
Did you try the Custom Movement behavior?

**Comment by BonzerKitten7** [comment] 2019-04-02 15:30
Yes, me and other few people from the Discord channel are trying to create something reliable with the Custom Movement behaviour right now. But my suggestion is another topic that you should really consider, I'm one of the users who actually make commercial games and I'm giving you my feedback, you don't need to implement it if you don't want to, but at least take my suggestion.

**Comment by AshleyScirra** [comment] 2019-04-02 17:14
I don't see how the Physics behavior has any relevance to this bug report. If you have suggestions, please file them on the suggestions platform as usual.

**Comment by BonzerKitten7** [comment] 2019-04-02 17:56
We are talking about movement, how can you not see the relevance of my feedback regarding the physics behaviour? Anyway, I already did a few suggestions on your Aha eight months ago.
