### ISSUE TITLE
Crash when closing tile collision editor window

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#4124] opened 2020-08-17 20:46 UTC
## Problem description

C3 crashes when attempting to close the tile collision editor window

## Attach a .c3p

[tilemap crash.zip](https://github.com/Scirra/Construct-3-bugs/files/5086707/tilemap.crash.zip)

## Steps to reproduce

1. Click the tilemap object in the layout to view the tiles in the tilemap bar.
2. Double-click any of the tiles in the tilemap bar to open the tile collision editor.
3. Close the collision editor.

## Observed result

C3 crashes

## Expected result

C3 should not crash

## More details

**Affected browsers/platforms:** 
Chrome & Desktop

r210.2 stable & r211 beta

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'rj' of null @ TypeError: Cannot read property 'rj' of null at https://editor.construct.net/r210-2/components/bars/tilemapBar/tilemapBar.js:35:365
Stack: TypeError: Cannot read property 'rj' of null at https://editor.construct.net/r210-2/components/bars/tilemapBar/tilemapBar.js:35:365
Construct 3 version: r210.2
URL: https://editor.construct.net/
Date: Mon Aug 17 2020 15:45:30 GMT-0500 (Central Daylight Time)
Uptime: 6.3 s

Platform information
Browser: NW.js
Browser version: 0.47.2
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.47.2 (like Chrome/84.0.4147.105)
C3 release: r210.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment] 2020-08-18 08:07
Duplicate of #4104

**Closed by DiegoScirra** 2020-08-18 08:07 UTC
Labels: duplicate
