### ISSUE TITLE
R101 (macOS) - Changing Background Color of Comment doesn't work properly.

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#1629] opened 2018-05-24 17:11 UTC
## Problem description

When selecting a new Background or Text color with the color wheel, it always only picks the very first color the very first click on the color wheel selects. After that, it doesn't update in preview nor when you confirm the color change.

## Steps to reproduce

1. Open Event Sheet
2. Create Comment
3. Right Click and select change background color
4. Choose color from color wheel.

## Observed result

Color only updates once.

## Expected result

That the color updates as long as i select something from the color wheel.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment] 2018-05-25 15:51
Can't reproduce on Windows 10. No color wheel appears, so I think you have not mentioned some necessary information regarding the platform or steps to reproduce. Please fill out the entire bug report to ensure all the necessary information is included.

**Comment by joelmayer87** [comment] 2018-05-28 10:38
Hi Ashley.

Sorry, normally i'm quite conscientious about posting as much info as possible but i guess i forgot this time :S 

You're correct, i was on a Mac and the color picker looks different there than on Windows. I tried the error again but still happens.

Here's a screenshot:

![image](https://user-images.githubusercontent.com/30116964/40610772-fa970ce2-6273-11e8-8518-a2abc3366752.png)


And here is my system data:

Platform information
Browser: Chrome
Browser version: 66.0.3359.181
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
C3 release: r98 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 131 gb
Storage usage (approx): 18 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M395X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment] 2018-05-29 11:10
Ah, I see. Looks like there's something different about the color picker on macOS.

**Comment by AshleyScirra** [comment] 2018-05-29 11:31
OK, should be fixed in the next release.

**Closed by AshleyScirra** 2018-05-29 11:31 UTC
Labels: macOS
