### ISSUE TITLE
"Script type" option not saved (module/clasic)

### ISSUE THREAD

**Issue by tatosgames** [Scirra/Construct-3-bugs#4625] opened 2021-03-01 18:18 UTC
## Problem description

If you save the project with the script type "clasic" is saved in the caproj as 		"scriptsType": "classic", but when opened is re-setted as module.

## Attach a .c3p

[test.zip](https://github.com/Scirra/Construct-3-bugs/files/6063614/test.zip)

## Steps to reproduce

1. open project
2. save with scripttype "clasic" 
3.save again
4. close construct
5. reopen.... is still "module"

## Expected result

Saved as clasic

**First affected release:** last stable and last beta

**Comment by AshleyScirra** [comment] 2021-03-02 10:40
This is a duplicate of #4530 and is currently by design. If Construct automatically detects your project is compatible with modules it will switch it over for you.

**Closed by AshleyScirra** 2021-03-02 10:40 UTC
Labels: duplicate
