### ISSUE TITLE
[r218] Tilemap editor - hotkeys don't work until a click

### ISSUE THREAD

**Issue by NoSoul8** [Scirra/Construct-3-bugs#4263] opened 2020-10-05 07:36 UTC
## Problem description
Tilemap editor hotkeys don't work until user clicks the tilemap object thus placing a tile

## Steps to reproduce

1. Open Tile-based game example
2. Select a tilemap in the level editor
3. Click any tile in the tilemap editor
4. Press A or Z to rotate a tile

## Observed result

Tile won't rotate. If you click the tilemap object (place a tile) then the hotkeys will rotate tiles again

## Expected result

Hotkeys work from the start

## More details

**Affected browsers/platforms:** 

**First affected release:** 
Worked in previous stable version, issue spotted at r218

## System details

<details><summary>View details</summary>

PASTE HERE
Platform information
Browser: Chrome
Browser version: 85.0.4183.121
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
C3 release: r218 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 417 mb
Storage usage (approx): 52 mb (12.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) HD Graphics 6000
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2020-10-14 10:49
Duplicate of #4069. Fixed in the next beta. Was re-introduced by mistake in r212.

**Closed by DiegoScirra** 2020-10-14 10:49 UTC
Labels: duplicate
