### ISSUE TITLE
Animations editor line bug

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1788] opened 2018-07-11 08:12 UTC
## Problem description

It is 2 bug in one, 1 bad behavior is causing other. Anyway, when in animation editor, line tool allows to draw line on X axis from point you had selected. But on Y axis, you have to start draw line +1 spot right, for line tool to draw line from point you rly wanted. 
This causes other buggy behavior, when you try to draw line in right side of sprite, from top to down. That line will disappear and won't show up on frame window. As your starting point is outside sprite window.

## Steps to reproduce

1.Open new project
2.Open animation editor
3. resize canvas to 20x20
4. Select line tool, pixel width 1.
5. Draw 1 pixel line left side of sprite from top to down. See that you had to select +1 spot on X axis to get correct line.
6.Draw similar line to top and bottom. Line can be started from spot you selected!
7.Now draw line to right side. But don't start exactly from top. But +1 pixel and end line -1 pixel from bottom.
8. Line won't show up on frame window and will disappear on next line draw.

## Observed result

Line tool won't start from pixel you had selected. and line draw in right side will disappear.
PS. if you draw line in right side, exactly from top to bottom it will work. You need to start +1 and end -1 pixel.

## Expected result

Line should start where you select and line tool should not  get buggy when you draw it on some cases.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r108.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 609 mb (4.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2018-08-15 14:09
Can't reproduce this one.

If I turn on the grid with a cell size of 1 width and 1 height, it looks like the line tool always draws from the selected position properly.

Can you provide a video of what is happening?

**Comment by SnipG** [comment] 2018-08-15 16:16
Open  video in zip with VLC player, see line draws wrong on Y - axis, and line disappear when you draw new or click.
[2018-08-15 19-12-33.zip](https://github.com/Scirra/Construct-3-bugs/files/2290890/2018-08-15.19-12-33.zip)

**Comment by DiegoScirra** [comment] 2018-08-16 09:49
I see, looks like the problem is with the SMOOTH toggle.

**Comment by DiegoScirra** [comment] 2018-08-16 10:19
Fixed in r114.

**Closed by DiegoScirra** 2018-08-16 10:19 UTC
