### ISSUE TITLE
Changing font crashes the softwre (Chrome OS)

### ISSUE THREAD

**Issue by TMsimonW** [Scirra/Construct-3-bugs#4395] opened 2020-12-03 17:05 UTC
When changing font on any blank project with a single text object the entire software crashes  

## Attach a .c3p

Create a blank project
add a text object on the layout 
Change the font using the 3 dot selector 

Create a blank project
add a text object on the layout 
Change the font using the 3 dot selector 

## Observed result

the entire software crashes with a google chrome "aw snap" message & the error message "Error code: RESULT_CODE_KILLED_BAD_MESSAGE"

## Expected result

To be able to change the font

## More details

Chrome os in chrome browser

r216

**Comment by AshleyScirra** [comment] 2020-12-04 11:44
Duplicate of #4371. See [this thread](https://www.construct.net/en/forum/construct-3/general-discussion-7/c3-r226-close-font-changing-156837). Be careful about leaving 'Enable experimental features' on.

**Closed by AshleyScirra** 2020-12-04 11:44 UTC
Labels: duplicate
