### ISSUE TITLE
Failed to open project

### ISSUE THREAD

**Issue by rilem** [Scirra/Construct-3-bugs#3604] opened 2020-01-22 19:23 UTC
## Problem description

I've ran into a strange bug with the folder project saving/loading in r183-2. 

After doing some work on my game the project suddenly fails to load. I've been working on a new enemy for Mighty Goose and this bug has been a pain today. Thank god for git, so I went back to my previous commit. Then the project loads up fine. I thought something might have gone wrong underwater with undo's and metadata or something but I've tried to finish this enemy several times now today and I always run into this bug at some point.

## Attach a .c3p /  Steps to reproduce

I've not found the steps to reproduce this bug and my project is something I don't want to share online publically (I'd be willing to mail the project to the support team though). I have recorded a bit of footage in the hope to catch the bug:

https://youtu.be/3SdiqBf4UQ0

You'll see me save and load the project around 1:00, works fine
You'll see me save and load the project around 2:00, doesn't work.

## Observed result

You'll notice that at some point the project just wont load. To me it feels very random and I can't wrap my head around why this is happening. I can't consistently reproduce it.

## More details
I've been saving/loading/reverting for a few hours now. I can't make head or tails of it. The bug always shows up, but never at the same moment. Tomorrow I'll start working in 183 again, from my old commit. I'll try and build the exact same feature and see if any issues arise. I hope this gets fixed soon as the folder projects are essential to my workflow.

**First affected release:** 
worked in 183 *i think
broken in 183-2

Using Chrome Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by rilem** [comment] 2020-01-23 07:46
Currently working in r182.2 stable, the problem hasn't shown up yet. But I'm keeping my eyes out.

**Comment by shortercode** [comment] 2020-01-23 11:05
We probably need to review the corrupted version of the project and see why it's failing to load, that should hopefully give some hints. Assigning to @AshleyScirra to review.

**Comment by AshleyScirra** [comment] 2020-01-23 17:27
Anything that results in a corrupt project is a high priority for us to fix, but I'm afraid this report gives us nothing to go on. The bug report guidelines are there because we can't investigate problems without that information. We can't debug videos. Also the folder-saving code is based very closely on the NW.js desktop folder saving code, which has been working reliably for a long time as far as I'm aware, so this seems mysterious.

It would be ideal to provide a working project and steps to follow to reliably save a corrupt project. You can email the project to me at ashley@scirra.com if you don't want to share it and can't reproduce it in a new project. If we have that, I can probably fix the issue immediately.

Otherwise all we can do is cast around for clues. If you could do the following it will probably help identify some clues, but is probably unlikely to itself lead to a fix:
- When failing to load a project, press F12 and look for the error message in the browser console. The reason it failed to load is logged there.
- When the project is corrupt, share it with me so I can inspect what was saved and what's invalid about it.
- Leave the browser console showing (F12) while working in a long session, and see if any errors appear at any time. For example perhaps an error actually occurred when pressing 'Save', and that error is the real cause of the problem.
- Try to identify specific steps that cause an error. Hopefully this can help narrow it down to a reproducible case. In particular if there is some kind of error that occurs when pressing 'Save', you might be able to identify the step by pressing 'Save' repeatedly in between everything you do.

**Comment by rilem** [comment] 2020-01-24 12:02
Sent the project your way. Good tip about keeping the console open!

**Comment by AshleyScirra** [comment] 2020-01-27 13:10
Thanks for sending the project by email. I'm writing this here to keep the issue progress in one place.

Having reviewed a broken project, the issue is bundled addons (in the 'addons' subfolder of the project folder) are sometimes wiped to a zero size. The next time you load the project it fails trying to extract the bundled addons, which are really zip files, and a zero size file is obviously not a valid zip file.

I can reproduce with the following steps:

1. Create a project that uses a bundled addon and save it to a folder
2. Close project
3. Open project, add a layout, and save
4. Delete the added layout, and save

After that point - the second save - the bundled addon file is wiped to zero bytes. I've checked what our code is doing and verified it appears to be correctly passing the right data along to be saved. I'm pretty sure now that it's a bug with Chrome's Native File System API; I suspect the first write actually destroys the source being written, and the second save ends up writing an empty file. I'll need to find a way to produce a minimal repro and then file an issue with Chrome (which itself could be tricky); I'll leave this issue open until I get that filed. I think we might be able to work around this in C3 too by copying the data to write before writing it to disk, so only the copy is destroyed.

In the mean time, you can work around this by keeping a copy of your bundled addons, and if the project becomes unopenable, just restore the bundled addons and it should open again. However you might just want to switch back to the NW.js desktop build for the time being until this gets sorted out, since it seems kind of risky to work with a known project corruption bug.

**Comment by AshleyScirra** [comment] 2020-01-27 14:02
OK, so having looked in to this some more, it might be an issue with Construct after all, but it's not really clear. It turns out in the specific case of bundled addons in folder projects with Chrome's native file system API, we end up writing the bundled addon file over itself when you save. This works once, but then the second attempt clears the file. It's not really a normal thing to do to try to write a file over itself, since it's simultaneously reading and writing the file, and those operations could conflict. It was straightforward to stop Construct doing this via taking a copy, so I've implemented a fix for the next release, which prevents the bug happening.

It didn't happen in NW.js because due to API limitations we were forced to copy data before writing it anyway, so we already wrote a copy.

I filed a Chrome issue anyway (crbug.com/1045918) in case there is some kind of bug going on, but the resolution of that issue is a moot point now, as Construct side-steps the issue now. So: should be all fixed in the next release!

**Closed by AshleyScirra** 2020-01-27 14:02 UTC
