### ISSUE TITLE
Group Select/Deselect Enhancements

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-3-bugs#3321] opened 2019-09-10 05:57 UTC
## Problem description

When you want to select one group it is selecting all inner, it is ok. But when you try to deselect it is only apply selected not all inner.

Problem? Please watch gifs. When you try to change **TOPGROUP** color, it is apply other inner groups. Also for **"D" (Disable)** command.

**This should be like this;**
If group collapsed apply deselect all inner
If group expanded apply deselect only that group (current behavior)

## Attach a .c3p

I used for gif record
[Test.zip](https://github.com/Scirra/Construct-3-bugs/files/3593899/Test.zip)

## Steps to reproduce
**1. Example**
![Test1](https://user-images.githubusercontent.com/54614906/64587638-aa801d00-d3a8-11e9-9bdb-7bee2b184fcb.gif)

**2. Example**
![Test2](https://user-images.githubusercontent.com/54614906/64587644-af44d100-d3a8-11e9-908e-42f09e54fb9a.gif)

## Observed result

**For 1. gif**
**Group4** inner events disabled.

**For 2. gif**
Except **Group3**, all colored.

## Expected result

**For 1. gif**
**Group4** inner events should be enabled.

**For 2. gif**
Only **TOPGROUP** should be colored.

**First affected release:** r165

**Comment by AshleyScirra** [comment] 2019-09-10 10:00
Can you provide written steps to reproduce? As mentioned in the bug report guidelines videos aren't actually that helpful, especially since it's difficult to see when or if you are pressing keyboard keys.

**Comment by AshleyScirra** [comment] 2019-09-16 14:49
> 6. You can see Group4 events disabled.

I can't follow this step, because in the project you provided, there are no events in Group4. The project also differs to the gifs you attached. It looks like you attached the wrong project in the original report, so I cannot follow the steps to reproduce you later provided.

It gets increasingly confusing if I have to try to reconcile inconsistent bits and pieces of information scattered across a bug report. It would be best to start over and provide all the necessary information in the original report, as per the bug report guidelines. So I'm going to close this issue - please re-file and try to provide everything necessary in the first report.

**Closed by AshleyScirra** 2019-09-16 14:49 UTC
Labels: no repro

**Comment by CrackHub** [comment] 2019-09-16 14:51
You already see all groups in gifs. Just use blank example. You don't need any project file.

**Comment by AshleyScirra** [comment] 2019-09-16 14:53
Please always follow the bug report guidelines. They are there to ensure we can actually investigate the problem and fix the problem you are reporting. People routinely skip things and it makes the bug report impossible to deal with, even if you think it looks obvious. Our policy is, as stated in the guidelines, to close any issues not following the guidelines, to avoid wasting everyone's time.

**Comment by CrackHub** [comment] 2019-09-16 14:53
If I have time I will do but not today.
