### ISSUE TITLE
Cannot launch executable in Windows after exporting with NW.js option

### ISSUE THREAD

**Issue by JohnLeGame** [Scirra/Construct-3-bugs#5915] opened 2022-07-22 09:56 UTC
## Problem

Cannot launch executable in Windows after exporting with NW.js option.

## Descrirption

I exported to Windows 32 & 64 bit, all export checkboxes left blank. Used latest Chromium version (0.66) (I also tried 0.65 but same problem there) at the time.
And then I unzipped the file & tried to run both executables, one at a time.
Each time it doesn't run.

I tried to look up the problem & can only find [this](https://github.com/nwjs/nw.js/issues/7882) - which does not contain any solution (but may help you find it (?) )

Attached project file:
[exportBug.zip](https://github.com/Scirra/Construct-3-bugs/files/9166666/exportBug.zip)

## Steps to reproduce

1. Open project
2. Export (use NA.js option, check marks for Windows 32 bit & 64 bit, nothing else)
3. Download exported file, extract it & run asdfasdf.exe within either 32 bit or 64 bit folder.

## Observed result

- Game does not start.
- In Task Manager: Multiple Nw.js processes instantiated (image: 
<img width="589" alt="asdfasdfasdf" src="https://user-images.githubusercontent.com/109795263/180413769-0b68c9d2-8ff1-4ce4-a22b-c6df5fd926b8.PNG">)

## Expected result

- Game runs

## More details

Game works when exporting with WebView2.
The project is just a sprite with no events or variables.

**First affected release:** There's only this version of the project

## System details

<details><summary>View details</summary>

In debug.log:
[0722/161612.237:ERROR:zip_reader.cc(153)] Cannot open ZIP from file handle 0000000000000230
[0722/161612.237:ERROR:zip.cc(202)] Cannot open ZIP from file handle 0000000000000230

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 103.0.5060.134
Browser engine: Chromium
Context: browser
Operating system: Windows NT 8.0.0
Device type: desktop
Device pixel ratio: 1.125
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 110 gb
Storage usage (approx): 3.2 gb (2.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GT 730 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2022-07-22 14:08
It works fine for me.

It's difficult to help unless we can reproduce the problem ourselves. Is it just your system that has the issue or does it affect other systems too? It may be something to do with your specific system.

**Comment by JohnLeGame** [comment] 2022-07-22 15:18
Thanks for checking out the issue. I have only 1 Windows-running machine at home so cannot confirm on other systems.

**Comment by AshleyScirra** [comment] 2022-07-25 09:26
I'm afraid there's not much we can do here. It works for me, and as far as I'm aware it's working for all other users too - so far this is the only report I've seen of it not working. My best guess is it's some system-specific issue, so closing.

**Closed by AshleyScirra** 2022-07-25 09:26 UTC
Labels: can't reproduce
