### ISSUE TITLE
Wait this is bug load image :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6393] opened 2023-01-14 04:14 UTC
## Problem description

There is an error in the console, and the game freezes.

## Attach a .c3p

[wait_this_is_bug_load_image_r325b.zip](https://github.com/WilsonPercival/WilsonPercival/files/10416503/wait_this_is_bug_load_image_r325b.zip)

## Steps to reproduce

1. Open a project.
2. IMPORTANT: run the project with `Layout 2`, otherwise the bug will not occur.
3. Open the console.
4. Quickly press 1, 2, 1, 2...

## Observed result

https://user-images.githubusercontent.com/91274932/212449973-781ed325-1d57-4eba-8c02-f2153a218f2a.mp4

## Expected result

The console is error-free and the game does not freeze.

## More details

The bug will not occur if the size of the original sprite image is not 2x2.

https://github.com/Scirra/Construct-3-bugs/issues/6040

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r325b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r325 (beta)
Browser: Chrome 109.0.5414.74
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 569 mb (0.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_sRGB
OES_element_index_uint
OES_fbo_render_mipmap
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_depth_texture
WEBGL_draw_buffers
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2023-01-16 12:20
I couldn't reproduce this - even pressing 1 and 2 as fast as I possibly could no error occurred.

However based on the errors in the console I made a few changes that may help. Marking this issue to check again when the next release is out.

**Comment by WilsonPercival** [comment] 2023-01-17 13:10
> I couldn't reproduce this - even pressing 1 and 2 as fast as I possibly could no error occurred.
> 
> However based on the errors in the console I made a few changes that may help. Marking this issue to check again when the next release is out.

@AshleyScirra I can still reproduce this error in r326b.

![aaa](https://user-images.githubusercontent.com/91274932/212907296-f841536a-9d74-49ea-98e6-fd0d2643e0e5.png)

I don't always get it right the first time. Try different switching speeds. Fast pace. Try a few times.

**Comment by WilsonPercival** [comment] 2023-01-17 13:13
> @WilsonPercival - r326 is out now, can you check again there?

@AshleyScirra These are the errors even when I collapse and expand the browser page with the game.

![bbb](https://user-images.githubusercontent.com/91274932/212908019-455449c6-9b7d-4ab7-8bcd-148f074611ba.png)

**Comment by AshleyScirra** [comment] 2023-01-17 13:16
I'm afraid I was not able to reproduce the issue, which makes it difficult to make any further progress. Can you find a more reliable way to reproduce the problem?

**Comment by WilsonPercival** [comment] 2023-01-17 13:29
> I'm afraid I was not able to reproduce the issue, which makes it difficult to make any further progress. Can you find a more reliable way to reproduce the problem?

@AshleyScirra I created a new project in version r326b. I was able to repeat the bug even without the `wait 0.1 sec` action. Also, I did not feel the difference if I start from the first layout or from the second one. I set the switching time between layouts to 10ms, but it may be different for you, you can play around with it.

[wait_this_is_bug_load_image_easy_r326b.zip](https://github.com/Scirra/Construct-3-bugs/files/10435447/wait_this_is_bug_load_image_easy_r326b.zip)

While testing this project, I got the following error:

![aa](https://user-images.githubusercontent.com/91274932/212911372-8f95d61a-1eda-4908-99fb-c48ab3fd3b09.png)

**Comment by AshleyScirra** [comment] 2023-01-19 12:29
Thanks, that provides a more reliable repro.

**Comment by AshleyScirra** [comment] 2023-01-30 16:01
I've had another go at fixing this, but I still seem to only reproduce it intermittently, so it's difficult to know if it's fixed for sure. So marking to check at the next release again.

**Comment by WilsonPercival** [comment] 2023-01-30 18:05
> I've had another go at fixing this, but I still seem to only reproduce it intermittently, so it's difficult to know if it's fixed for sure. So marking to check at the next release again.

@AshleyScirra I can still reproduce it in r327-2s. Sorry if I'm too hasty and should have waited for the next beta release.

![a1](https://user-images.githubusercontent.com/91274932/215558063-5fac4e38-abd0-4f14-a5f2-cd2937924874.png)

![a2](https://user-images.githubusercontent.com/91274932/215558126-18fa229d-22ae-403e-8aae-d24e40a2c342.png)

**Comment by AshleyScirra** [comment] 2023-01-31 14:33
The fix for this is in r328 (and wasn't in r327.2). Can you check again with r328?

**Comment by WilsonPercival** [comment] 2023-01-31 14:49
> The fix for this is in r328 (and wasn't in r327.2). Can you check again with r328?

@AshleyScirra I tried my best to break it and it didn't work (looks like you actually fixed it!)

**Comment by AshleyScirra** [comment] 2023-01-31 15:37
Great, thanks for confirming.

**Closed by AshleyScirra** 2023-01-31 15:37 UTC
