### ISSUE TITLE
The sprite editor becomes inactive after resizing

### ISSUE THREAD

**Issue by TecenGOD** [Scirra/Construct-3-bugs#5116] opened 2021-10-14 11:52 UTC
## Problem description

When I open the sprite editor and resize it, the sprite editor stops being active.
Sometimes it works the first time, sometimes it takes 3-5 times.
The window becomes active again if you move the mouse cursor to another application (in my example, this is Paint).
Video - [https://yadi.sk/d/4ZNw8wmJwYg88Q](https://yadi.sk/d/4ZNw8wmJwYg88Q)
## Steps to reproduce

1. Open any example in C3 (For example Kiwi)
2. Open any sprite and change the size to 25x25
3. The sprite editor is stuck

## Observed result

The sprite editor is stuck

## Expected result

The sprite editor should not get stuck

## More details
The bug is observed on r267 and below, up to the stable release of r260

## System details

<details><summary>View details</summary>

Platform information
Browser: Edge
Browser version: 94.0.992.47
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36 Edg/94.0.992.47
C3 release: r260 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 134 gb
Storage usage (approx): 213 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5751)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2021-10-20 17:21
Can't seem to replicate this one consistently. I happens sometimes and quite rarely.

**Comment by 1mrpaul1** [comment] 2021-11-05 09:44
the same in the chrome

**Comment by therealPaulPlay** [comment] 2022-02-05 10:30
Same on Firefox, only happens sometimes though.

**Comment by DiegoScirra** [comment] 2022-02-14 18:31
A possible fix for this issue will be going out in the next beta. As I haven't been able to reproduce the issue consistently myself, it is difficult to know if the fix will work, so anyone interested will have to try it out and see if it works for them.

**Comment by AshleyScirra** [comment] 2022-02-15 15:08
r283 is now out, please try again for anyone affected to verify if the issue is resolved.

**Comment by AshleyScirra** [comment] 2022-02-22 12:24
No response for a week so closing.

**Closed by AshleyScirra** 2022-02-22 12:24 UTC
