### ISSUE TITLE
Cant open .c3p file

### ISSUE THREAD

**Issue by bedfl2016** [Scirra/Construct-3-bugs#3880] opened 2020-05-23 14:30 UTC
Hi I get this error when trying to open this .c3p file:

https://www.dropbox.com/s/3su1b03s75b6zcx/V8.c3p?dl=0

Please can you recover this file

<details><summary>View details</summary>
Error report information
Type: unhandled rejection
Reason: Error: invalid function name 'SetGKFrame' @ Error: invalid function name 'SetGKFrame' at t.ǃuNA (https://editor.construct.net/r197-2/projectResources.js:1:307002) at t.ǃGk (https://editor.construct.net/r197-2/projectResources.js:1:306916) at window.ǃwYM.ǃuNU (https://editor.construct.net/r197-2/projectResources.js:1:331642) at t.accept (https://editor.construct.net/r197-2/projectResources.js:1:261253) at t.accept (https://editor.construct.net/r197-2/projectResources.js:1:297456) at u.ǃuNR (https://editor.construct.net/r197-2/projectResources.js:1:283298) at u.ǃuNR (https://editor.construct.net/r197-2/projectResources.js:1:290119) at u.accept (https://editor.construct.net/r197-2/projectResources.js:1:261269) at e.ǃuNR (https://editor.construct.net/r197-2/projectResources.js:1:268591) at e.accept (https://editor.construct.net/r197-2/projectResources.js:1:261269)
Stack: Error: invalid function name 'SetGKFrame' at t.ǃuNA (https://editor.construct.net/r197-2/projectResources.js:1:307002) at t.ǃGk (https://editor.construct.net/r197-2/projectResources.js:1:306916) at window.ǃwYM.ǃuNU (https://editor.construct.net/r197-2/projectResources.js:1:331642) at t.accept (https://editor.construct.net/r197-2/projectResources.js:1:261253) at t.accept (https://editor.construct.net/r197-2/projectResources.js:1:297456) at u.ǃuNR (https://editor.construct.net/r197-2/projectResources.js:1:283298) at u.ǃuNR (https://editor.construct.net/r197-2/projectResources.js:1:290119) at u.accept (https://editor.construct.net/r197-2/projectResources.js:1:261269) at e.ǃuNR (https://editor.construct.net/r197-2/projectResources.js:1:268591) at e.accept (https://editor.construct.net/r197-2/projectResources.js:1:261269)
Construct 3 version: r197.2
URL: https://editor.construct.net/
Date: Sat May 23 2020 15:29:15 GMT+0100 (British Summer Time)
Uptime: 32.1 s

Platform information
Browser: Chrome
Browser version: 81.0.4044.138
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 2.5
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
C3 release: r197.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 with Max-Q Design Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment] 2020-05-23 18:00
The problem is there are a number of functions that are called with the wrong name.

Some actions call functions named `SetGKFrame`, `SetPositions` and `SetBarColours`, but the functions are actually named `SetGKFrame2`, `SetPositions2` and `SetBarColours2`.

This should be impossible: if you rename/edit/delete functions in Construct, it updates everywhere the functions are called as well. If there is something you can do in Construct that results in a corrupt project like this, it would be a high priority to fix it.

Can you remember or work out again what you did with these functions that caused this problem in the first place?

Here's the recovered project: 
[V8-recovered.zip](https://github.com/Scirra/Construct-3-bugs/files/4672262/V8-recovered.zip)

**Comment by bedfl2016** [comment] 2020-05-23 22:05
Hi @AshleyScirra, what happens is I create my screens in different projects then I put them all into one, so I copied all the events from one project and pasted it into the one that wouldn't open after I saved it. I think when you copy functions from one project to another they are renamed but when they are called the name isn't renamed so it is still calling the function without the 2 on the end. 

Thanks for recovering it for me. I hope this info helps. I can provided more if needed

**Comment by AshleyScirra** [comment] 2020-05-25 11:36
@bedfl2016 - that doesn't make sense: if you paste events from a different project but the function name exists, then the 'call function' actions just refer to the existing function, and only the duplicate function is renamed. The resulting project is still valid. I tried this and it seems fine.

Can you identify a sequence of steps to follow to reproduce the problem?

**Comment by luckyrawatlucky** [comment] 2020-05-27 09:24
i have also faced this issue in older releases in current release this is fixed. In older c3 releases when if we copy-paste any function from one project to another then functions were pasted by adding number 2 at the end. I am sure @bedfl2016 saved that file in older version which can't be opened even in the same version.

**Comment by AshleyScirra** [comment] 2020-05-27 10:31
The attached project file appears to have been saved with r197.2. @bedfl2016 can you confirm if you used an old version of Construct at any point?

**Comment by AshleyScirra** [comment] 2020-06-01 15:05
Without any way to reproduce this there is no action we can take, so closing.

**Closed by AshleyScirra** 2020-06-01 15:05 UTC
Labels: no repro
