### ISSUE TITLE
please fix this is the 31th time this has happen

### ISSUE THREAD

**Issue by cori6487** [Scirra/Construct-3-bugs#672] opened 2017-08-04 23:13 UTC
(wlosing it ever so slowly because this is the 30th time this has happen)

https://drive.google.com/open?id=0B0zF1VXpAvB6MGdHQTVTc3JvclU

## Steps to reproduce

1.open the insert new object menu
2.double-click a sprite
3. then click insert...

## Observed result

a blank sprite... and a software crash

## Expected result

to see the sprite image select menu...

## Affected browsers

* Chrome: yes
* Firefox: no
* Edge: no
* Safari: no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

i lost my crash report because i copied the google drive link D: (crashes c3 again) there we go! :D

Error report information
Type: unhandled rejection
Reason: Error: dialog not open @ Error: dialog not open at ǃp.ǃk.ǃi.ǃlUz.ǃShE (https://editor.construct.net/r47/main.js:2:318520) at ǃp.ǃk.ǃi.ǃlUz.ǃSwm (https://editor.construct.net/r47/main.js:2:319687) at t.ǃpmP.then (https://editor.construct.net/r47/main.js:71:418777) at 
Stack: Error: dialog not open at ǃp.ǃk.ǃi.ǃlUz.ǃShE (https://editor.construct.net/r47/main.js:2:318520) at ǃp.ǃk.ǃi.ǃlUz.ǃSwm (https://editor.construct.net/r47/main.js:2:319687) at t.ǃpmP.then (https://editor.construct.net/r47/main.js:71:418777) at 
Construct 3 version: r47
URL: https://editor.construct.net/index.html
Date: Fri Aug 04 2017 16:09:42 GMT-0700 (Pacific Daylight Time)
Uptime: 675.6 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 32-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 2
User agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r47

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce 405 Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2017-08-07 10:16
I can't open the .c3p file, it hangs when loading. This does not sound like it is related to the reported issue, but it looks like it hangs in Diego's code, so assigning to Diego.

**Comment by AshleyScirra** [comment] 2017-08-07 10:19
Also it appears it hangs due to loading the layout UI state, if I delete the UI state file and open the project, I can't reproduce the issue reported. @cori6487 can you provide more reliable steps to reproduce? Otherwise there is not much we can do about this.

**Comment by DiegoScirra** [comment] 2017-08-16 16:51
I sorted out the problem with the UI state, but I can't reproduce the original bug either. Closing it as there is not much to do about it, with out reproduction steps.

**Comment by DiegoScirra** [comment] 2017-08-17 13:51
@AshleyScirra

The original bug has no repro, but the project file is still quite slow to load. Might be worth checking it out.

**Comment by AshleyScirra** [comment] 2017-08-17 16:56
I've fixed a bad case where removing thousands of event listeners on startup would be O(n^2), but it's still not particularly fast to open the project. I did spot one more case of adding instances to a layer repeatedly calling includes() which is also O(n) but it only attributed 1-2% of the time to that call, and my previous change didn't seem to help massively either. Chrome's profiler says most of the time is in GC and promise .then() calls, so there doesn't seem to be much obvious to optimise. TBH there are ~30,000 instances in one layout so it's probably not going to be that fast to open anyway.

Closing as I think that's as much as we can do for now.

**Closed by AshleyScirra** 2017-08-17 16:56 UTC
Labels: no repro

**Comment by AshleyScirra** [comment] 2017-08-17 17:04
I figured out a quick fix for adding instances to a layer, but as I thought that didn't help much either.

**Comment by cori6487** [comment] 2017-08-20 01:37
when it hangs it will finish loading but its like dial-up (20 minutes-ish)

**Comment by cori6487** [comment] 2017-08-20 01:44
the problem is when there is too much delay to the sprite select so when you double click you think it didn't work so then you click insert and it crashes because you requested for the software to create 2 sprites at the same time so it crashes because it already received that you wanted a new sprite (so 2 events are triggering the same line of code?)
