### ISSUE TITLE
Tilemap shortcut keys don't work until after tile placed

### ISSUE THREAD

**Issue by Ldwebster111** [Scirra/Construct-3-bugs#4311] opened 2020-10-28 01:38 UTC
## Problem description

Using the tilemap editor to lay down tiles, the shortcut keys do not work until after a tile from the current selection has been placed. I've included a gif to demonstrate.

![tilemap](https://user-images.githubusercontent.com/46861823/97379851-e4e4aa80-1919-11eb-8b09-8ce7be29ba7a.gif)

## Attach a .c3p

[tilemap shortcut test.zip](https://github.com/Scirra/Construct-3-bugs/files/5448996/tilemap.shortcut.test.zip)

## Steps to reproduce

1. select a tile or multiple tiles from the tilemap
2. press one of the shortcut keys to rotate or flip the tiles X, Y, A, Z
3. note they do not function.
4. place a tile in the level and retry the shortcut keys. They now work.

## Observed result

Shortcut keys do not work until after a tile is placed from the current selection

## Expected result
user should be able to rotate and flip tiles as soon as a selection is made.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** This has been an issue for at least a couple of months, as it's always frustrated me that the shortcut keys didn't work. It's only today that I realised they do work after the first tile is placed.

## System details

Tested on two Windows 64-bit PCs, same result on both.

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment] 2020-10-28 10:10
Duplicate of #4069. Fixed in the latest beta. It's still present in the latest stable, r218.

**Closed by DiegoScirra** 2020-10-28 10:10 UTC
