### ISSUE TITLE
drag and drop wav file onto layout not converting to webm

### ISSUE THREAD

**Issue by stuatk** [Scirra/Construct-3-bugs#3963] opened 2020-06-20 11:47 UTC
## Problem description

if I drag a wav file onto the layout view the wav is not converted to a webm. Then when I run my game the sound does not play. However if the exact same wav file is imported by dropping it onto the "Import Sounds" window, it IS converted to a webm and plays fine when the game runs.

so basically dragging wav onto Layout acts differently to dragging onto "Import Sounds" dialogue.

## Steps to reproduce

1. drop wav file onto layout = not converted to webm, fails to play in game
2. drop same file onto "Import Sound" dialog = converts to webm, plays fine in game.
3. result should be the same

## Observed result

file not converted to webm, fails to play when game runs.

## Expected result

the file should be converted to a webm and should play back when game is run

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 83.0.4103.106
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
C3 release: r204 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 142 gb
Storage usage (approx): 438 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2020-06-21 11:58
Can't reproduce here, it works identically both ways.

The issue does not follow the bug report guidelines so I cannot investigate further, so closing.

**Closed by AshleyScirra** 2020-06-21 11:58 UTC
Labels: can't reproduce
