### ISSUE TITLE
Timeline audio stopped working after update

### ISSUE THREAD

**Issue by smGamify** [Scirra/Construct-3-bugs#6237] opened 2022-11-02 15:17 UTC
## Problem description

The timeline audio stopped working after the latest update. It was working fine till yesterday.

## Attach a .c3p

https://www.construct.net/out?u=https%3a%2f%2fdrive.google.com%2ffile%2fd%2f16MhVdonXl3g2Si9zPBGN4Y2Hnak-VZlN%2fview%3fusp%3dshare_link

## Steps to reproduce

-- Import any audio
-- Create a timeline and insert the audio
-- Then play the timeline (the audio will not play)

## Observed result

The timeline audio is not playing

## Expected result

The timeline audio should play like the earlier version

## More details
Checked in the other C3 version (r308-2), and the audio in the sample file is working fine.

**Affected browsers/platforms:** 
C3 version - Release r317 stable
OS - Windows 10
Chrome - Version 107.0.5304.88 (Official Build) (64-bit)

**First affected release:** 

Working in r308-2
Broke in r317

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment] 2022-11-03 11:32
This is fixed now, was a regression introduced in r312.

**Closed by DiegoScirra** 2022-11-03 11:32 UTC

**Comment by smGamify** [comment] 2022-11-03 15:41
When it will get released? any tentative timeline for this?

**Comment by DiegoScirra** [comment] 2022-11-03 21:44
Since this was a regression from the previous stable release we will likely make a patch, including this fix. We are giving the current stable some more time to see if there are any other outstanding issues that popup.
