### ISSUE TITLE
Is By Wall affects SOL in OR block

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3732] opened 2020-03-28 15:58 UTC
## Problem description

In a sub event where SOL isn't empty, using "is by wall" in an OR condition block affects the SOL even if it's false. That behavior is unreliable and depends on the order of the conditions too, as any condition that becomes true before it will cancel it's effect on SOL.
The behavior is also different if no instance was put in the SOL to begin with.

## Attach a .c3p

[OrSolBug (2).zip](https://github.com/Scirra/Construct-3-bugs/files/4397396/OrSolBug.2.zip)

## Steps to reproduce

1. Hit play
2. Use Left click, right click, wheel up and wheel down while away from a wall
3. Do it again while next to a wall

## Observed result

When next to a wall, all 4 triggers happen as you'd expect them to.
When away from a wall, 3 of the 4 triggers empty the SOL for Sprite2 and thus all Sprite2 actions are skipped, and the last one (Right click) keeps the SOL from the parent event block

## Expected result

IMO, all 4 SHOULD behave like the Right click trigger, and false condition should not affect SOL in OR blocks, but I'm guessing this is by design in some aspect, and for some reason I can't see.
However, the behavior is unreliable, and I think this should be fixed (especially since when no SOL is applied the behavior is reliable)

## More details

**Affected browsers/platforms:** 

**First affected release:** tested in 192. This bug comes from a project I started working on since probably 170 and I never noticed that bug. Either I just failed to notice it, or this is a fairly recent bug.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by skymen** [comment] 2020-03-28 20:05
I was told this bug also happens in 170 and even on 143, so it might be a very old bug

**Comment by AshleyScirra** [comment] 2020-03-30 11:49
For the record, minimal repro: [New project.zip](https://github.com/Scirra/Construct-3-bugs/files/4402436/New.project.zip)

OR blocks are often confusing because they allow the possibility of running events with zero instances picked. This is exactly what your events do: when the player is not by a wall either side, the two "is by wall" checks end up with no Sprite2 picked because it did not match any of the conditions. Then you use a true system condition to force the OR block to run anyway, so it runs and does all the actions, except the Sprite2 ones, since none of them are picked.

The bug is actually that all four cases work correctly, except right-clicking, which is wrong to run with a Sprite2 instance picked when it didn't meet any of the conditions. (Note this is the opposite of your stated expected result)

I fixed this, and found that it was actually handled correctly in the C2 runtime - this was a regression when we ported the OR block code to the C3 runtime. So it should be fixed (and working consistently with the C2 runtime) in the next release.

**Closed by AshleyScirra** 2020-03-30 11:49 UTC

**Comment by skymen** [comment] 2020-03-30 12:58
Yeah, when making more tests I figured out that the "expected result" was what the three other things did. And yeah, it used to work in C2 but I was unsure wether this was a recent issue or had always been like this in C3.
Anyway thanks for fixing this :)
