### ISSUE TITLE
Multiplayer Android Studio Export missing arguments

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-3-bugs#3742] opened 2020-04-03 15:27 UTC
## Problem description

If a project has GooglePlaystore plugin and Multiplayer, the android manifest needs this two permissions to make the Multiplayer work:
```
 <uses-permission android:name="android.permission.INTERNET" />
 <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```
Tested With Android Studio export
Minimal Project: https://drive.google.com/open?id=1GJpU903hhNjryvWOUHAoRqXvj6vGQtIT

**Comment by kingpirux** [comment] 2020-04-04 01:33
This problems comes from android 8.1 and up, the app can't connect to the multiplayer server on wss or ws. 
<uses-permission android:name="android.permission.INTERNET" /> is used to allow the app to open sockets and comunicate with internet.
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" /> is needed to use the "is online" from the browser plugin and the multiplayer plugin to detect https comunication.

tested on Nokia 3 and Xaomi

**Comment by AshleyScirra** [comment] 2020-04-06 17:17
I can't reproduce this. I built a debug APK of the multiplayer chat example and ran it on a Pixel 3 with Android 10. It ran just fine and was able to act as both host and peer with a desktop machine connecting over wifi, and exchanging messages. What has led you to believe that `ACCESS_NETWORK_STATE` is necessary for this?

**Comment by kingpirux** [comment] 2020-04-06 18:02
try with release, in debug it works i dont know why. 
I ended with this problem in my game (https://play.google.com/store/apps/details?id=com.luminias.app ) withou it it doesnt work, and that's the only thing i add to meke it work. ill try to make a minimal example export and share it.

**Comment by kingpirux** [comment] 2020-04-06 20:05
i cant reproduce the problem with the minimal of the chat room. But ill keep trying adding layers to simulate the same process in my app.
In the meanwhile here is the screen of the problem in debug:
![imagen](https://user-images.githubusercontent.com/6506303/78600029-8e523a80-7828-11ea-99dd-64de3548c306.png)
This doens't happen if you add those two permissions
A link to the debug apk without those two permissions: https://drive.google.com/open?id=1H0Ck0EDz9tD3R1rz0YJ-OVFSkjQsCDn2
ILL KEEP TRYING TO MAKE A MINIMAL APP.

**Comment by kingpirux** [comment] 2020-04-06 22:21
Finally found the problem!! It is related to the GooglePlay plugin, for some reason if you add that plugin the multiplayer will not connect unless you add the internet permission.
Here is the minimal example. This took me a hole day of rebuilding all the project steep by steep :-1:  
Why does it fix with that permission? i leave it to you :P 
MINIMAL: https://drive.google.com/open?id=1GJpU903hhNjryvWOUHAoRqXvj6vGQtIT

**Comment by CrackHub** [comment] 2020-04-07 09:08
> @AshleyScirra
> Finally found the problem!! It is related to the GooglePlay plugin, for some reason if you add that plugin the multiplayer will not connect unless you add the internet permission.
> Here is the minimal example. This took me a hole day of rebuilding all the project steep by steep 👎
> This problem affects mostly to android 8.1 and up (at least as far as i can test, with android 8.1 , 7 and 9)
> Why does it fix with that permission? i leave it to you :P
> MINIMAL: https://drive.google.com/open?id=1GJpU903hhNjryvWOUHAoRqXvj6vGQtIT

As I remember correctly, Googleplay plugin already adds this in your project.

`<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />`

I look latest minimal project. It is already have these permissions.
``` <uses-permission android:name="android.permission.INTERNET" />
 <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```
![image](https://user-images.githubusercontent.com/54614906/78650776-0e7bad00-78c8-11ea-9a52-234d7ef8b0b2.png)

Some reason lower Android versions need permissions for work correctly. @AshleyScirra Android 10 should be work without permission but have you tried lower android versions?

**Comment by AshleyScirra** [comment] 2020-04-07 10:58
It still doesn't make sense because normally plugins only add permissions, they don't take them away. So I don't see how adding a plugin could break the permissions needed for multiplayer.

With bug reports you should only report what's not working. If you try to jump to conclusions you will repeatedly go down misleading paths and confuse the whole issue. This issue starts with "Please add a permission" but that doesn't appear to even be the right solution to the problem, and it's still not really clear what the problem is. Further we deal with thousands of reports and it's already very complicated, and if issue reports are full of all sorts of conflicting details and missing information, it becomes extremely difficult to do anything about it.

So, as ever, yet again, please, follow the bug report guidelines, don't try to skip them, and try to include as much information as possible. To enforce this I'm going to close the issue: if you still want it investigated, please file a new issue following the guidelines.

I'd add that a WebSocket is basically a normal Internet connection. Perhaps you need to make sure wss://*/* is on the URL whitelist? The default only allows http/https.

**Closed by AshleyScirra** 2020-04-07 10:58 UTC
Labels: Android, ignored guidelines
