### ISSUE TITLE
Animation editor animation preview is buggy

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4506] opened 2021-01-26 12:18 UTC
## Problem description
I don't know if they all same case causing buggy, different cases or no bug at all.

Essentially animation preview missalign and causing offset and blur.
See images below
Case1:
![bugger5](https://user-images.githubusercontent.com/28864889/105843237-200d7d00-5fe0-11eb-8460-7b982e9b84f2.jpg)

Case2: They same image, but with different origin point
![bugger50](https://user-images.githubusercontent.com/28864889/105843555-84c8d780-5fe0-11eb-817e-f9083e27566b.jpg)

## Attach a .c3p

[Buggy5.zip](https://github.com/Scirra/Construct-3-bugs/files/5873190/Buggy5.zip)
## Steps to reproduce

1.Open example, open sprite with animation editor.
2.Preview animation, change origin, preview again
3.

## Observed result
Changing origin point changes animation preview size. From this it seems preview is zoomed in and out. Durning zoom it will blur frames. 

## Expected result
I don't rly know, as it seems "works as intended". But it can blur frames, could it not blur them?

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 88.0.4324.104
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
C3 release: r232 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 1.5 gb (1.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2021-02-04 11:36
Fixed in the next beta.

Blurriness should be gone on the next update.

The misalignment when changing the origin is the expected behaviour. It happens because the preview is taking into consideration the origin of each frame. The preview window is resized to be able to fit all the images and their origins. This is the same as in C2. 

If you manually cycle throw all the frames in the layout view, you will notice the preview is producing the same results, with each frame having slightly different positions as a result of the different origins.

**Closed** 2021-02-04 11:38 UTC

**Comment by SnipG** [comment] 2021-02-04 12:10
I put both cases there as, if you try to fix 2 case and get rid of blur. It might need to snap pixels, then first case might not work corrently after that.
Anyway, it seems fix still was able to workaround it, so it seems nice.
