### ISSUE TITLE
Black bottom bar on exported iOS game

### ISSUE THREAD

**Issue by RichardAstrom** [Scirra/Construct-3-bugs#2840] opened 2019-04-10 15:23 UTC
I'm getting black bars at the bottom of the screen on iOS devices. It doesn't happen everytime you start the game, but it does happen often. On my iPhone 7 I get a very small bar, but when I test on iPhone X, Xs, Xs Max, Xr I get bigger bars. I've used Amazon Device Farm to test on real devices.

[BlackBarTest.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3064463/BlackBarTest.c3p.zip)

1. Export project to Xcode with the Construct build service.
2. Build it with Xcode 10.1.
3. Test on a real device.
4. Sometimes there's a black bar at the bottom, sometimes there's not. It seems to occur more often when I start the game for the first time, but I'm not really sure. It's weird.

## Observed result

Black bar!

## Expected result

No black bar, just a nice fullscreen!

## More details

![blackbar](https://user-images.githubusercontent.com/3534495/55891255-88ddf800-5bb4-11e9-99fe-aba6db685c09.png)
<img width="827" alt="Screenshot 2019-04-10 at 22 57 55" src="https://user-images.githubusercontent.com/3534495/55913171-40d6c980-5be4-11e9-8a14-2971d748d814.png">

**Affected browsers/platforms:** 

Exported game on iOS 12.

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.103
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
C3 release: r144 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 11 gb
Storage usage (approx): 667 mb (5.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 7800 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-04-11 10:01
Possible duplicate of #2396

**Comment by shortercode** [comment] 2019-04-11 12:36
Sounds like the behaviour might be slightly different from #2396, as in that case the size is always displayed incorrectly and this shows an issue with an iPhone X which was unaffected by that bug. I'm going to review these various "black bar on mobile" issues after we have moved to cordova 9 on the build server.

**Comment by RichardAstrom** [comment] 2019-04-11 14:00
Thanks! Let me know if you need any additional info.

When are you planning to move to Cordova 9 on the build server?

**Comment by RichardAstrom** [comment] 2019-04-12 09:20
I might have found a temporary solution!

I think there could be a bug in the cordova-plugin-wkwebview-engine plugin that's causing this? 

I replaced it with [https://github.com/ionic-team/cordova-plugin-ionic-webview](https://github.com/ionic-team/cordova-plugin-ionic-webview) in config.xml as someone recommended here: [https://stackoverflow.com/questions/46494221/ionic-white-space-in-bottom-with-wkwebview-in-ios-11](https://stackoverflow.com/questions/46494221/ionic-white-space-in-bottom-with-wkwebview-in-ios-11) and built it with Cordova CLI (Cordova 8.0.0 iOS 4.5.4).


And it seems to be working! I have tested Several different iPhone models (X, Xs Max, Xr) 15+ times on Amazon Device Farm and I haven't seen any bars yet. The small bar that sometimes appeared on my iPhone 7 seem to be gone to. Also, I think there is a small performance boost, but I haven't measured it :)

@AshleyScirra @shortercode Would love to hear your thoughts on this?

Thanks!

**Comment by AshleyScirra** [comment] 2019-04-12 10:16
There are probably a whole bunch of other compatibility bugs that will come up if we switch the entire webview engine. As always we ought to figure out the root cause and understand the problem before we decide what to do about it.

**Comment by RichardAstrom** [comment] 2019-04-12 10:58
That sounds reasonable.

In the meantime I think I'm going to stick with the Ionic webview for now, I've done some more testing and everything we have in this game seems to be working fine so far.

The game we're testing this with - [Tiny Alien](https://itunes.apple.com/app/tiny-alien-jump-and-shoot/id1451319904) is currently pre-order featured on the US App Store with about 15K pre-orders so far, so it's going to be tested quite a lot when it's released :)

![tinyalien](https://user-images.githubusercontent.com/3534495/56032069-73d2a780-5d21-11e9-9e4c-41541d04380d.png)

**Comment by shortercode** [comment] 2019-04-12 11:21
I wasn't aware that ionic had their own webview engine separate to the cordova team implementations. I get the impression the ionic team are a lot more active than cordova, so it might be that it's more stable. But as @AshleyScirra says it's not a light undertaking ensuring support and stability on what is effectively a new platform.

**Comment by Madiosn** [comment] 2019-05-03 10:44
Whether prompt there is a solution of the given problem?

Now I have the same trouble on

iPhone 6
iPhone XS
iPad Air

Black strip bottom.

Although it is not on the iPhone XR.

**Comment by AshleyScirra** [comment] 2019-06-11 17:37
@shortercode - is this fixed now with Cordova 9? (there must be half a dozen of reports like this)

**Comment by AshleyScirra** [comment] 2019-06-24 14:46
r156 is now out, please test again!

**Comment by RichardAstrom** [comment] 2019-06-24 21:26
Great! I've done some tests with r156 and I haven't seen any black bars yet! I've tested 5-6 times on different iOS devices like the iPhone X and XR and it does seem to be working now :) (I have not done any tests on Android).

Do you mind if I ask what you did to fix this?

Thanks!

**Comment by AshleyScirra** [comment] 2019-06-25 10:54
Thanks for confirming! (@shortercode implemented the fix)

**Closed by AshleyScirra** 2019-06-25 10:54 UTC
Labels: iOS

**Comment by shortercode** [comment] 2019-06-25 12:12
We actually had several fixes related to mobile layout issues in the last release, but for simplicity we only had 1 entry in the release notes.

We previously had a fix in place that would try and correct the webview size if we thought we were on an iPhone X. I changed this to apply for all iOS app exports, and to use the screen dimensions instead of hard coded values we had for the iPhone X. This should be a lot less brittle and work on every device. It's not the ideal change, but as long as it's working for people that's what matters. I might change this again in future if I can come up with something better to work around it.

**Comment by RichardAstrom** [comment] 2019-06-25 12:30
Ok, thanks for the reply! It seems to be working fine right now, hopefully it will stay that way :)

**Comment by jaymonga** [comment] 2021-01-10 17:54
![IMG_1920](https://user-images.githubusercontent.com/48458961/104131175-c7cd4e80-5342-11eb-855f-b9f55fed8964.png)
The issue appears to be back. For the past 5-4 months I've had this issue. It only disappears by chance(Having to continuously open and close the app until it doesn't appear anymore).

**Comment by Fullstak-nl** [comment] 2021-01-15 01:38
![image](https://user-images.githubusercontent.com/55746426/104669589-9e157e00-56da-11eb-985a-2579b6c1502b.png)
Don't mind the glitchy other layout issues haha but sometimes we also experience the black bar (didn't have it before R230) :(

**Comment by Fullstak-nl** [comment] 2021-01-18 10:55
Settings StatusBarOverlaysWebView (in config.xml) to false seems to fix this...

**Comment by jaymonga** [comment] 2021-01-18 16:28
I upgraded the construct version to r231 and it seems to have fixed the problem only for landscape mode - scale outer - Viewport fit/cover, The problem will only appear upon opening the app right after updating the app but the app launches afterwards don't have the problem. But for portrait mode - scale outer - Viewport fit/auto the problem is still there, I've had to open and close the app 5 - 6 times for the problem to disappear.

**Comment by AshleyScirra** [comment] 2021-01-19 12:00
Please note as per the bug report guidelines, closed issues are not monitored - if you wish for an issue to be investigated you should file a new issue following all the guidelines.
