### ISSUE TITLE
C3 low FPS occurred after updating to 123.2 beta version. 

### ISSUE THREAD

**Issue by UbruPro123** [Scirra/Construct-3-bugs#2230] opened 2018-11-02 09:26 UTC
## Problem description

I have a problem with FPS, I do not know what slows it down. I updated Construct to 123.2 (beta), and FPS drops occurred.

## Attach a .c3p

[project.zip](https://github.com/Scirra/Construct-3-bugs/files/2541825/project.zip)

## Steps to reproduce

1. I tested my game in version 120 and it was OK
2. I updated C3 to 123.2 beta version and re-saved my project so I cant test it in previous version
3. Actually I have lower FPS and game runs slow, is there any chance that the new C3 build has some issues? 

## Observed result

Low FPS and not smooth running

## Expected result

I think I do everything correctly and in previous version it was OK, so I pretend 60 FPS and run smooth.
Please advise what makes it slow.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by ibiz3091** [comment] 2018-11-02 12:53
I also noticed that the fps in my game started falling in r123.2. Increased lags and jumps 50-60 FPS, where before it was 59-60 fps r123

**Comment by AshleyScirra** [comment] 2018-11-02 18:36
This doesn't make any sense. We only made trivial changes in r123.2 compared to r123, and none of the changes should have had any serious impact on performance. @ibiz3091 stated that there is a performance difference between those versions, but the original reporter @UbruPro123 did not specify a specific version - can you test every release and identify which release specifically caused a performance difference?

It's also not clear how you are measuring performance - the attached project doesn't display the FPS anywhere. Are you using the debugger? If so, that has a significant performance overhead so will be expected to degrade performance. The attached project also uses third-party addons; updating one of these could have caused a performance regression (which is why our guidelines require that you should not use third-party addons in bug reports).

I'm afraid we will not be able to do anything about this issue until we have clarification on the above.

**Comment by AshleyScirra** [comment] 2018-11-02 19:00
I just noticed the attached project is using the C2 runtime, which has barely been changed at all in the last few releases. It's not clear which runtime @ibiz3091 was testing with. I am pretty sure this is some kind of false positive, but I'll wait for a response before closing.

**Comment by ibiz3091** [comment] 2018-11-02 20:05
Oh yeah, C2runtime was on. Checked again with C3runtime, no problem. @AshleyScirra

**Comment by UbruPro123** [comment] 2018-11-02 23:01
I tested it for a long time and I noticed that maybe overlay graphic effect slows it down (drain FPS). I tested it with new version of project in last stable version of C3 (120) and C3 runtime.

Here you can try it, I really do not know what is wrong.
Only run project go through menu and in the game hold "is in touch" and release (spawn that charge) -> then FPS dropped down as you can see on this video (tested on android):
https://youtu.be/9x9tyYnluM8

Here is project file and exported .APK
[test_project.zip](https://github.com/Scirra/Construct-3-bugs/files/2544373/test_project.zip)

**Comment by UbruPro123** [comment] 2018-11-03 07:40
> I tested it for a long time and I noticed that maybe overlay graphic effect slows it down (drain FPS). I tested it with new version of project in last stable version of C3 (120) and C3 runtime.
> 
> Here you can try it, I really do not know what is wrong.
> Only run project go through menu and in the game hold "is in touch" and release (spawn that charge) -> then FPS dropped down as you can see on this video (tested on android):
> https://youtu.be/9x9tyYnluM8
> (for testing I am using text that shows FPS, it must be enabled in Options - Performance, it is only placeholder menu for now)
> 
> Here is project file and exported .APK
> [test_project.zip](https://github.com/Scirra/Construct-3-bugs/files/2544373/test_project.zip)
> 
> @AshleyScirra

New update, due to additional testing.

I noticed that massive FPS drop is caused by this (so nothing to do with overlay):

**every tick -> rotate 600*dt degrees toward (Touch.X, touch.Y)**

I need to make rotation behavior with some speed (acceleration) and use to follow angle of actual touch position, similar like Rex´s RotateTo and MoveTo how can I create similar thing with C3 runtime? Thanks a lot, now it is big problem for me.

**Comment by UbruPro123** [comment] 2018-11-03 07:56
It is forcing me to use older C2 runtime and solve it with Rex´s MoveTo and RotateTo, new Tween is not enough or not similar like these behavior. Is there any chance to officially bring these 2 behaviors to C3 runtime?

**Comment by AshleyScirra** [comment] 2018-11-03 15:38
It's still not clear to me what you think the problem is. Did this regress in a specific release? You still haven't answered that. It's also not clear what to do with the provided project, which also doesn't appear to take any performance measurements outside of the debugger.

Closing due to confusion and lack of evidence of any particular problem, it sounds like you might just be doing something slow or mis-attributing something expensive in your project like a slow effect to something else. If you want this to be investigated please file a new issue following all the guidelines: provide a minimal project, clear steps to reproduce, the specific version where a change was first observed, etc.

**Closed by AshleyScirra** 2018-11-03 15:38 UTC
Labels: can't reproduce
