### ISSUE TITLE
Can't open Project "Invalid expression"

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#2913] opened 2019-05-02 18:31 UTC
## Problem description

I can't open my project, when i try to it says this
![image](https://user-images.githubusercontent.com/32940085/57097789-a4857b80-6ce6-11e9-888d-037acbd0baa7.png)

## Attach a .c3p
Sent over email to support@construct.net

## Steps to reproduce

1.Open the project

## Observed result

It doesn't open and i get this 
![image](https://user-images.githubusercontent.com/32940085/57097841-c0891d00-6ce6-11e9-9282-88fdb0f43b7e.png)

## Expected result
It opens with no problem

## More details

I've tried opening it with previous versions, I've tried opening the project with a text editor to delete the event it's mentioning, no dice !

This happened from saving the project, no error messages, closing construct, opening it back up again, Unable to open the project anymore.

My array  did have a mirrored boolean instance variable but I deleted it in favor of using a bit in another variable with setbit and getbit, maybe it didn't delete the events containing it properly ?

the events regarding this were in one of those fancy new functions

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.103
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
C3 release: r147.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 806 mb (5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by eleanorawesome** [comment] 2019-05-03 00:58
update: i'Ve been able to open the project by editing line 1287 of fixedtick.json to make sure it dosen'T contain self.mirrored anymore and the project sucessfully opened, I don't know how it slipped up when deleting the instance variable and didn,t automatically get deleted

**Comment by eleanorawesome** [comment] 2019-05-03 01:00
The event that had the deleted Boolean variable in it was disabled, maybe that has something to do with it ?

**Comment by AshleyScirra** [comment] 2019-05-03 10:28
I'm afraid there's nothing we can do about this unless we have steps to reproduce the problem, going from a working project, to a not working project. If the project is broken, we can try to recover it, but that does nothing to solve the problem that caused the broken project. Closing since no steps to reproduce, will take up project recovery via email.

**Closed by AshleyScirra** 2019-05-03 10:28 UTC
Labels: no repro
