### ISSUE TITLE
help:/

### ISSUE THREAD

**Issue by jefferybiceps** [Scirra/Construct-3-bugs#5341] opened 2021-12-31 08:53 UTC
hello.i have been trying to open a new project but the layout is not opening.i can preview it and do stuff in the event sheets but nothing in the layout.A message comes says:"Failed to initialize WebGL . This prevents Construct from opening any layout views.
This can be caused by broken graphics drivers or out of date software.Try installing any available software updates for your system"

**Comment by jefferybiceps** [comment] 2021-12-31 08:54
please i want to finish my game

**Comment by dop2000** [comment] 2022-01-02 07:57
Have you tried updating the graphic drivers as the error message suggests?

**Comment by AshleyScirra** [comment] 2022-01-03 13:12
I'm afraid as the error message says, the problem is with your system. Installing system software updates may help, or you may be able to use a different browser. This is not a problem with Construct, and there isn't enough information to investigate further anyway, so closing.

**Closed by AshleyScirra** 2022-01-03 13:12 UTC
Labels: ignored guidelines

**Comment by jefferybiceps** [comment] 2022-01-07 09:10
thank you.i don't know what you did but it works now

**Comment by jefferybiceps** [comment] 2022-01-07 09:16
also sorry i'm late
