### ISSUE TITLE
Action selection sometimes bugs under specific circumstances

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#3227] opened 2019-08-17 11:32 UTC
## Problem description
Some strange case where action selection bugs out. It starts to happen when you resize UI elements. Sometime when it happens it does not go away easily. It seems to break Grid element or something.
See pic below:
![CommentSelectionBuggy](https://user-images.githubusercontent.com/28864889/63211069-0c779a80-c0fb-11e9-81fc-3952a54d04c0.jpg)

Only seen this bug once in this specific case. Could be Chrome bug, but i am not so familiar with grid element, so i don't rly know.

## Steps to reproduce

1.Open KiwiStory
2.Open eEffect eventsheet and scroll top.
3.Try selecting actions from leaf set bullet -> to  leaf destroy
4.Change Left Project UI size and try selecting again. 

## Observed result
In some case, action selection bugs out. And starts to show strange behaviors.

## Expected result
No bug

## More details

**Affected browsers/platforms:** 
Chrome

I tried Firefox and could not reproduce.

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
C3 release: r160 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 1.1 gb (8.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-08-19 10:11
The screenshot looks like a Chrome paint bug. This is supported by the fact you could not reproduce it in Firefox. Can you reproduce it in Chrome Canary?

**Comment by SnipG** [comment] 2019-08-19 12:12
Seems to be fixed in Canary

**Comment by AshleyScirra** [comment] 2019-08-19 12:26
OK, closing as a Chrome bug that was already fixed

**Closed by AshleyScirra** 2019-08-19 12:26 UTC
Labels: chrome, external
