### ISSUE TITLE
Preview loads a black screen.

### ISSUE THREAD

**Issue by whitingdj** [Scirra/Construct-3-bugs#341] opened 2017-05-24 12:51 UTC
## Problem description

Attempting to Preview the project loads a black screen. This doesn't matter whether or not it's just a specific layout or the project as a whole. It's a black screen each time. 

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

[MonksTD5202017.zip](https://github.com/Scirra/Construct-3-bugs/files/1025521/MonksTD5202017.zip)

## Steps to reproduce

1.Open project
2. Click preview
3.

## Observed result

Black screen. Nothings there.

## Expected result

My first level

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r30

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 237 mb (1.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2017-05-24 13:02
There's a bug including some of the plugins into the preview at the moment, in your case the pathfinding behaviour is not loading. Should be fixed in r31

**Comment by shortercode** [comment] 2017-05-24 13:03
Duplicate of [#336](https://github.com/Scirra/Construct-3-bugs/issues/336)

**Closed by shortercode** 2017-05-24 13:03 UTC
Labels: duplicate

**Comment by shortercode** [comment] 2017-05-24 13:07
@whitingdj also your game is looking pretty cool, that evil spirit is from Legend of Korra right?

**Comment by whitingdj** [comment] 2017-05-24 17:08
That's exactly right! Anyway, r31 totally fixed it! Thank you!

**Comment by shortercode** [comment] 2017-05-24 17:18
I'm a big fan of the Avatar series! Glad to hear it's working again, good luck with the game jam 🥇
