### ISSUE TITLE
Select next paramater with TAB and change the paramater. 

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#1319] opened 2018-02-25 08:02 UTC
## Problem description

Sometimes, when you press tab to go to next parameter and try to change it, it will keep the last value.

This gif will describe it better:

![2018-02-25_10-47-15](https://user-images.githubusercontent.com/2965842/36639280-449a05e4-1a1a-11e8-838e-e872ffc8f9df.gif)

## Steps to reproduce

1. Set sprite position from events.
2. Set X then press tab to set Y.
3. Enter a value.

## Observed result

If Y is 0 and you want to set it 100 it will write 0100.

**Comment by AshleyScirra** [comment] 2018-02-26 12:30
Duplicate of #1025

**Closed by AshleyScirra** 2018-02-26 12:30 UTC
Labels: duplicate
