### ISSUE TITLE
mobile ad does not work

### ISSUE THREAD

**Issue by Sirtaximan** [Scirra/Construct-3-bugs#3215] opened 2019-08-14 17:37 UTC
## Problem description

mobile ad does not work

## Attach a .c3p

https://drive.google.com/file/d/18GcVa0huVuhQsgpH6jbZPzktEUtDXxRM/view

## Steps to reproduce

1.Install
2.Run 
3.it does not work

## Observed result

the ad does not appear on the screen

## Expected result

the ad should show

## More details

Android, IOS?

**Affected browsers/platforms:** Android, IOS?

r160

**First affected release:** r160

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2019-08-15 13:08
Assigning to @shortercode to check but note often these issues are normally just a misconfiguration of the plugin and not actually a bug. So you might want to double-check you have everything set up correctly and no error triggers are firing.

**Comment by Sirtaximan** [comment] 2019-08-16 08:32
On r159 it works, on r160 it doesn't.

**Comment by JeFawk** [comment] 2019-08-16 20:11
I can't get it to work on r157 nor on r159 and this is just a pity since I was about to release a game on the google play store.

I checked over 10 times with 2 different projects, my own and the one posted here. I even added ca-app- every now and then to the publisher ID as it states in the documentation.

![Screenshot_20190816-230824](https://user-images.githubusercontent.com/7268697/63195400-22de1180-c07b-11e9-954c-f22b8b9e834e.png)

**Comment by shortercode** [comment] 2019-08-19 14:36
@JeFawk have you previously had this working? The publisher ID does not contain `ca-app-`, it should be in the form "pub-0123012301230123". If this is wrong you will likely receive an error from the user consent dialog along the lines of ["Could not parse Event FE preflight response"](https://github.com/googleads/googleads-consent-sdk-android/issues/94) which is what you have at the top of your error list.

@Sirtaximan I shall take a look at your project and see if there was any changes made for r160, but I cannot recall off the top of my head ( I've been on leave recently ).

**Comment by JeFawk** [comment] 2019-08-19 15:00
@shortercode  this is the first time I'm trying to publish Android apps. For my initial attempts I did not add the "ca-app", afterwards I tried it with it too as the doc states (see below). Both attempts led to the same "Could not parse .... " error

![image](https://user-images.githubusercontent.com/7268697/63275955-1b04b400-c2ab-11e9-8366-9707ab4fd095.png)

https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/mobile-advert

I googled the problem a dozen times and a lot of people did use wrong publisher IDs, however I'm sure this is not the case for me.

**Comment by shortercode** [comment] 2019-08-19 15:12
@JeFawk apologies that is a typo, I've amended the documentation and added some links to Admob's help documentation on finding it.

The issue I posted before does suggest that it can be an issue even with a correct publisher ID, but it's not an issue I'm aware of. Let me think on it while I investigate the other issue.

**Comment by JeFawk** [comment] 2019-08-19 15:44
I strongly believe the setup was done correctly, but I'll post it here in case I somehow missed something.
This is from my admob dashboard
![image](https://user-images.githubusercontent.com/7268697/63278006-19d58600-c2af-11e9-9e17-22e4e0ba8d26.png)

This is the event where I put the ad ID
![image](https://user-images.githubusercontent.com/7268697/63278076-42f61680-c2af-11e9-9cee-73af9838e31a.png)

This is the app ID in dashboard and mobile advert
![image](https://user-images.githubusercontent.com/7268697/63278174-78026900-c2af-11e9-8ea0-d0f930270628.png)

And this is the publisher ID

![image](https://user-images.githubusercontent.com/7268697/63278261-a4b68080-c2af-11e9-9acb-2ba40940731d.png)


This is what I get using a debug apk and only that event + a plugin to show console on the screen.
![Screenshot_20190819-184150](https://user-images.githubusercontent.com/7268697/63279184-3f638f00-c2b1-11e9-9f17-5aa0b4db495d.png)

And this is the apk if it can help you
[Mobile advert.android.debug.apk.zip](https://github.com/Scirra/Construct-3-bugs/files/3516602/Mobile.advert.android.debug.apk.zip)

Thanks for looking into this

**Comment by shortercode** [comment] 2019-08-19 17:01
So after reviewing the project from @Sirtaximan I can confirm that the project doesn't work, but that appears to solely be down to the fact it cannot find the application on the admob servers. This doesn't really surprise me as the publisher ID component of every ID value appears to be different, and the privacy URL is missing a protocol. After replacing the publisher ID, app ID, advert unit IDs and privacy policy with known good values the application worked correctly.

The only change that was made for r160 was to remove leading/trailing whitespace from ID values, as users often miss them and don't realise why the ID is invalid. I can't see how it would cause any problems.

@JeFawk I had a quick look through your APK and can confirm that your ID values appear not to work. They look correct, they match each other and they are the correct length. I can't physically check against your Admob dashboard, but from the screenshots you've shown me they appear to match. The failure occurs within the Admob SDK when it tries to look up the application information, so it's not something we're doing. Did you configure your Application to use custom advert providers as per the GDPR section of the manual?

**Comment by Sirtaximan** [comment] 2019-08-19 17:23
I'm trying to update one of my games, I just wanted to fix a small collision bug, but I don't get the ads to work (they worked perfectly before).

**Comment by JeFawk** [comment] 2019-08-19 17:33
@shortercode are you referring to this?

![image](https://user-images.githubusercontent.com/7268697/63286400-9fadfd00-c2c0-11e9-974e-6336d40fe440.png)

**Comment by shortercode** [comment] 2019-08-20 13:51
@Sirtaximan I can't see any issue with r160 specifically. I just edited your project to include my ID values and it worked correctly for me. Are you using the depreciated "Configure" action in your actual project?

@JeFawk I'm sorry I have no idea why your ID values aren't working. Perhaps try creating a new "application" and associated advert unit IDs. Or contact AdMob customer support I guess, as this is your first go with it there might have been an issue setting it up.

**Comment by JeFawk** [comment] 2019-08-20 14:34
@shortercode thank you for trying anyway, I will contact them and see, I shall come back here with anything useful that I find

**Comment by shortercode** [comment] 2019-08-20 14:40
I hope they can help, if there is anything I can do let me know. I can't see any actions for me to take here at the moment though. If @Sirtaximan doesn't have anything else for me I will close this issue.

**Comment by Sirtaximan** [comment] 2019-08-20 16:30
I can only show you my settings (I put it in the forum), I still can't get it to work.
`https://www.construct.net/en/forum/construct-3/how-do-i-8/r160-cant-show-ads-anything-146019#forumPost983800`

**Comment by Sirtaximan** [comment] 2019-08-20 17:47
I have done 12 tests changing everything that has occurred to me, none works ...
Would it be a bother to review my project? I have no more ideas.

**Comment by JeFawk** [comment] 2019-08-20 21:27
Okey I managed to get it to work

Had to add the payment info, and wait around 1 day to be approved and even when they were approved, I had to wait a few more hours, while using test ads which I find ridiculous.

**Comment by JeFawk** [comment] 2019-08-20 22:19
@Sirtaximan is this your first application in admob?

**Comment by Sirtaximan** [comment] 2019-08-21 08:36
The application has been published almost 1 year, I just wanted to solve a small bug. The previous version works fine, it's very strange.

**Comment by shortercode** [comment] 2019-08-21 12:32
Glad that you managed to get it to work @JeFawk sounds pretty frustrating, but I'm not all that surprised...

@Sirtaximan I can take a look at your project if you like, see if I can gleam what the problem is. You can email it to iain@scirra.com and I will get back to you.

**Comment by shortercode** [comment] 2019-08-22 14:13
Okay @Sirtaximan I've tried building your project and can confirm there is an issue. It would appear that it's an issue in the Admob SDK itself, I find it strange that this didn't occur on either mine or @JeFawk 's credentials. I think perhaps it might be related to Advertising analytics and if you have them enabled on your account? I'm going to do some more testing to see if I can find the exact cause, but I'm not sure what action we can take at the moment.

**Comment by JeFawk** [comment] 2019-08-22 14:57
There was a problem for me actually if I select this, it throws an error about the consent not being asked for or something

![image](https://user-images.githubusercontent.com/7268697/63525401-518a3b00-c506-11e9-9f1b-744a686ee905.png)

**Comment by shortercode** [comment] 2019-08-22 15:01
@JeFawk can you be more specific about where the error is thrown? If the user is inside the EEA either the user consent dialog must be shown or the user personalization status must be set to either "personalized" or "non personalized" before an advert can be shown.

**Comment by Sirtaximan** [comment] 2019-08-22 16:27
I've never had problems with ads until beta R159, I don't know if it can help.

**Comment by shortercode** [comment] 2019-08-22 16:43
> I've never had problems with ads until beta R159, I don't know if it can help.

Your original report says that you first experienced the issue in r160, not r159.

I don't believe r159 included any changes to mobile advert, r160 included some very minor changes which I doubt would cause this. But I will do a comparison. I am more inclined to think this is something that has changed on the Admob side.

**Comment by Sirtaximan** [comment] 2019-08-22 16:53
It was true on the r160, I'm sorry

**Comment by shortercode** [comment] 2019-08-22 16:54
Well interestingly the error has stopped occurring for me, and your project now works. I didn't make any changes. I think this was an issue on Admobs end that they have now resolved. Try checking yours and see if it works?

**Comment by Sirtaximan** [comment] 2019-08-22 17:14
The version I have does not work ... did you use the test mode?

**Comment by shortercode** [comment] 2019-08-22 17:17
Yes, you should not use production mode for testing. You are allowed some leeway but viewing real ads as the developer can get your account banned.

**Comment by Sirtaximan** [comment] 2019-08-22 17:19
In test mode it always works for me, but deactivating it stops working.

**Comment by Sirtaximan** [comment] 2019-08-22 17:22
upps my subscription to C3 has expired .... can that have something to do with it? I will not be able to renew it until day 2; (

**Comment by shortercode** [comment] 2019-08-22 17:38
It's nothing to do with your C3 subscription. When I was talking about
accounts I meant with Admob, after all they are paying you per advert
shown. Viewing real adverts yourself is abusing the system. They allow some
leeway for testing and accidents but you should avoid testing in production
mode.

If your recieving adverts in test mode, but not production, then I expect
that they are just not sending you adverts. It's not guaranteed that they
will send them all the time. Perhaps try viewing on a different device or
another advert type?

**Comment by Sirtaximan** [comment] 2019-08-22 17:59
To do these tests, I steal my brother's cell phone :D, and I connect it to another Wi-Fi. Nor have I ever clicked on an ad.

**Comment by JeFawk** [comment] 2019-08-25 23:38
> @JeFawk can you be more specific about where the error is thrown? If the user is inside the EEA either the user consent dialog must be shown or the user personalization status must be set to either "personalized" or "non personalized" before an advert can be shown.

A bit harder to check now, once you accept the terms they save a cookie or something so I'd need to make another test project.

**Comment by shortercode** [comment] 2019-08-27 13:14
Yeah it's saved as a preference by the SDK, I think it can be cleared by uninstalling and reinstalling. But it's probably not an issue.

I'm going to close this issue, as I don't think there's any actions for me to take right now.

**Closed by shortercode** 2019-08-27 13:14 UTC

**Comment by JeFawk** [comment] 2019-08-28 14:22
@shortercode i uninstalled the app a few times and reinstalled it but didnt ask for permission anymore, I had to give the debug apk to a friend.
