### ISSUE TITLE
Case that makes project unable to open

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4759] opened 2021-04-24 23:35 UTC
## Problem description
After latest chrome update, tried C3 a little and i had constant crash. Makes C3 unusable, if some circumstances are met.
![VeryNice](https://user-images.githubusercontent.com/28864889/115975562-861d8800-a56e-11eb-871b-31d6bc4dd7f4.jpg)

## Steps to reproduce

1.Install C3 as app
2.Change theme, log in -> Do not check 'keep me logged in'
2.Add z-order bar and merge it in layout.
3.Refresh editor and open new, or any other project

## Observed result
Projects do not open  and user is unable to open anything. User needs editor/UI reset! It does not matter if User logs in after bug has occured, it keeps happening.

## Expected result
Opens. User should be able to use editor!

## More details
Google Chrome is up to date
Version 90.0.4430.85 (Official Build) (64-bit)

**Comment by starkiJi** [comment] 2021-04-25 11:03
I have the same problem! I can work all day, save, open the project, and the next day I can’t turn it off. There are 2 plugins in the project (LiteTveen in YandexSDK), maybe they are causing problems. I can send the administrator my preparation for a game (.c3p) that does  not open.

**Comment by starkiJi** [comment] 2021-04-25 11:19
MicrosoftEdge too problem - https://ibb.co/HYMFLJY

**Comment by SnipG** [comment] 2021-04-25 13:31
This issue is solely based on editor incapability to handle difference between logged user and visitor restrictions. If it happens with 3rd party plugins, then:
If you had been logged out - it's same case and you should change theme to restart UI.
If you never logged out, it's editors incapability to save some 3rd party plugin states. Scirra does not handle 3rd party plugins, so you pretty much alone on this one.

There are cases, where editor glitzes up, but then user saves project and when project is opened up again, errors are gone and the glitzes are not there. One could easily speculate, that in some cases editor could save errors into project, which ruins saved project, especially with 3rd party plugins. Becuase they are developed by someone else and does not follow official developer coding practices! Because how low the usage could be, you alone again on this one.

**Comment by DiegoScirra** [comment] 2021-04-26 14:32
Can't reproduce in either r241 or r245.2.

**Comment by SnipG** [comment] 2021-04-26 14:43
Maybe video helps!
Made wth Incognito mode


https://user-images.githubusercontent.com/28864889/116101982-f6cfbc00-a6b6-11eb-9745-b81b8c4005d8.mov

**Comment by starkiJi** [comment] 2021-04-26 15:30
my game .c3p - https://cloud.mail.ru/public/fWxq/iKMg4MpfX

**Comment by DiegoScirra** [comment] 2021-04-26 18:51
Fixed in the next beta.

**Closed by DiegoScirra** 2021-04-26 18:51 UTC
