### ISSUE TITLE
R141 - Preview is black if timeline is present in your project

### ISSUE THREAD

**Issue by justifun** [Scirra/Construct-3-bugs#2716] opened 2019-03-11 18:20 UTC
## Problem description

Preview is black if timeline is present in your project
[previewbug.zip](https://github.com/Scirra/Construct-3-bugs/files/2953674/previewbug.zip)

## Steps to reproduce

Add timeline plugin to  your project and hit play

## Observed result

Black preview window

## Expected result

preview of game in action

## More details
removing the timeline plugin allows the game to work again,

c3 web and desktop version R141

**Affected browsers/platforms:** 

R141
**First affected release:** 

## System details

windows 10 64 bit chrome Version 72.0.3626.121 (Official Build) (64-bit)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment] 2019-03-12 10:44
I'm unable to reproduce the issue with the provided project or a new project after adding the timeline plugin. Please ensure that the reproduction steps you specify work on your device and that you are definitely using r141. Assigning to @DiegoScirra to review further.

**Comment by DiegoScirra** [comment] 2019-03-12 11:34
I can't reproduce this one either. 

I tried the development version and the production version, the preview seems to work just fine.

I also tried the different types of previews, dialog, window and tab. In every case, the preview is working.

@justifun Can you share the project that is triggering the problem? It looks like the minimal example does not trigger it.

**Comment by Wackytoaster** [comment] 2019-03-14 09:00
I shall add to this. Very rarely there seems to be a problem with previews blackscreening. This isn't tied to the timeline plugin though, but to any plugin or behavior that wasn't in the project yet. Once you add it the preview will cease to work properly and just show a blackscreen, no errors in console. It will work again if you delete it.

However, leaving the blackscreen preview open for a minute or two will actually sort it out and it will suddenly load (even when closing & reopening). Adding another new plugin will cause the issue again.

The issue is entirely resolved by just restarting construct.

**Comment by AshleyScirra** [comment] 2019-03-25 12:42
Issue is marked 'can't reproduce' and no additional information provided for ~2 weeks so closing.

**Closed by AshleyScirra** 2019-03-25 12:42 UTC
Labels: can't reproduce
