### ISSUE TITLE
Crash opening project in r288

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#5580] opened 2022-03-30 00:54 UTC
Immediately after loading my large project, it gets the red screen crash, here is the report:

It loads fine in r287 (the previous beta). 

Could not replicate, do you need me to email the project (it's ~120mb) or is this crash report enough?

________________________________________

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'size') @ TypeError: Cannot read properties of null (reading 'size') at Nib.w8b.pjc (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:60:313) at d.mE (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:15:504) at Array. (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:15:10) at Nib.w8b.dispatchEvent (https://editor.construct.net/r288/main.js:1055:42) at Nib.w8b.Ek (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:56:120) at Nib.w8b.eMb (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:50:275)
Stack: TypeError: Cannot read properties of null (reading 'size') at Nib.w8b.pjc (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:60:313) at d.mE (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:15:504) at Array. (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:15:10) at Nib.w8b.dispatchEvent (https://editor.construct.net/r288/main.js:1055:42) at Nib.w8b.Ek (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:56:120) at Nib.w8b.eMb (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:50:275)
Construct 3 version: r288
URL: https://editor.construct.net/r288/
Date: Wed Mar 30 2022 11:45:18 GMT+1100 (Australian Eastern Daylight Time)
Uptime: 97.1 s

Platform information
Browser: Chrome
Browser version: 99.0.4844.88
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 2 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.88 Safari/537.36
C3 release: r288 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8681)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by DiegoScirra** [comment] 2022-03-30 10:53
Duplicate of #5579. Will be fixed in the next beta.

**Closed by DiegoScirra** 2022-03-30 10:53 UTC
Labels: duplicate
