### ISSUE TITLE
The way to kill the Construct 3 editor 12 times in less of 2 min. Why? (My first bug report here. I tried).

### ISSUE THREAD

**Issue by williamcdubois** [Scirra/Construct-3-bugs#6192] opened 2022-10-16 01:14 UTC
## Problem description

I opened the Construct 3 editor like usual, then the page got red and an error show up saying "Construct ran in to a problem and is unable to continue." The issue seem to be linked with the size of an Opera GX windows, who can destroy Construct 3 if the windows become too small or decreasing in height.

## Attach a .c3p

I don't have one since the editor died at start up.

## Steps to reproduce

An unlisted YouTube video I made that showing the crash course of the primitive way to kill the Construct 3 editor 12 times in less of 2 minutes.

https://youtu.be/uqgBt1rdvgQ

The way to reproduce it is SO obvious in this video.

## Observed result

The Construct editor is showing this: [Screenshot of the issue](https://prnt.sc/OXY8Kj5yUffh).

## Expected result

The normal homepage of Construct 3 editor.

## More details

**Affected browsers/platforms:**

Opera GX

**First affected release:** 

r308.2, because first time I see that.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r308-2/main.js, line 1273, col 509
Message: Uncaught Error: cannot set height of horizontally docked bar
Stack: Error: cannot set height of horizontally docked bar at Qf.g.bb.Xpa.ak (https://editor.construct.net/r308-2/main.js:1273:515) at Ida (https://editor.construct.net/r308-2/main.js:297:323) at Ida (https://editor.construct.net/r308-2/main.js:297:401) at Ida (https://editor.construct.net/r308-2/main.js:297:401) at Ida (https://editor.construct.net/r308-2/main.js:297:401) at https://editor.construct.net/r308-2/main.js:1301:164
Construct version: r308.2
URL: https://editor.construct.net/
Date: Sat Oct 15 2022 20:32:23 GMT-0400 (heure d’été de l’Est)
Uptime: 61.8 s

Platform information
Product: Construct 3 r308.2 (stable)
Browser: Opera GX 105.0.5195.127
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 OPR/91.0.4516.72 (Edition std-1)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment] 2022-10-17 11:00
I can't reproduce this in either Chrome or Opera GX. In both I can resize the window all over the place, from the smallest possible window to maximized, and it doesn't crash.

Do you have any browser extensions installed? Try disabling them one by one if you do have them - often weird issues like this come down to broken browser extensions interfering with Construct.

**Comment by williamcdubois** [comment] 2022-10-17 18:11
Hi. I don't know if it's a quality or a defect with me, but when I want to debug something (well documented initially), in 95% of case, I always I find my answers.

I disactivated ALL my extensions, but the problem continue. However, after playing around with your main.js from the homepage of the Construct 3 editor, I found the problem:

[Unlisted YouTube video showing where were the problem](https://youtu.be/JSomNr3hRHk)

What I did is, from the dev tools of my browser, I removed the Global Listeners('resize') of the line 1301 of the main.js...

Then, surprise! The problem disappears like magic, never shows up again in Opera GX.

Is it still a bug from my setup if the problem is from the line 1301 of main.js?

Thanks for answering and have a nice day.

**Comment by AshleyScirra** [comment] 2022-10-18 07:53
Yeah, well, if you make Construct ignore resize events it will break other things. It needs to use those events to make sure various features correctly adapt to different window sizes.

I can't reproduce this and I've not seen any other users report it, so I guess this is a system-specific issue. Without any way to reproduce it there's not much else that can be done, so closing.

**Closed by AshleyScirra** 2022-10-18 07:53 UTC
Labels: can't reproduce
