### ISSUE TITLE
Cannot Save Project Construct 3 R88

### ISSUE THREAD

**Issue by luisforte** [Scirra/Construct-3-bugs#1327] opened 2018-02-26 17:50 UTC
## Problem description

Cannot save project, error = Cannot Read Property "!Fxi" of Undefined

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

Simple click Save Project

## Observed result

Error Cannot Read Property "!Fxi" of Undefined

## Expected result

Save normal

## Affected browsers

* Chrome: yes

<details><summary>View details</summary>

https://i.imgur.com/yc2sHdx.png

</details>

**Comment by AshleyScirra** [comment] 2018-02-26 18:50
Duplicate of #1326

**Closed by AshleyScirra** 2018-02-26 18:50 UTC
Labels: duplicate
