### ISSUE TITLE
r96 iOS and windows 10 Firefox project load issues

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1523] opened 2018-04-24 22:37 UTC
![3f379344-f887-482a-89fb-4608b0717b06](https://user-images.githubusercontent.com/4122283/39217476-d7c0799a-47e5-11e8-8291-c138e0d574f7.png)
![6e42e236-06f2-436e-b063-38dc8e2135e9](https://user-images.githubusercontent.com/4122283/39217477-d7dda858-47e5-11e8-8f90-78f48c5bdfc9.png)

## Problem description

*Enter a concise description of your problem here*

[cyborg attack.zip](https://github.com/Scirra/Construct-3-bugs/files/1944814/cyborg.attack.zip)

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. open the project on iOS 
2. open the project on Windows 10 FireFox
3. 

## Observed result

*What do you see happen?*
sprite doesn't load on FireFox, and sprite is missing frames on Windows 10 Firefox

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Firefox: yes
* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>iOS View details</summary>

Platform information
Browser: Safari
Browser version: 11.0
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: iOS
Operating system version: 11.3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPad; CPU OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
C3 release: r96 (beta)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
The Clipboard API is not supported. Some clipboard features may be unavailable.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Downloading local content is not supported.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Metal - 52.3.2)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Apple Inc.
Renderer: Apple A10X GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions:

EXT_blend_minmax
EXT_sRGB
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_depth_texture
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by zumwaltwood** [comment] 2018-04-24 22:41
Windows 10 with FireFox results

<img width="870" alt="corruptload" src="https://user-images.githubusercontent.com/4122283/39217665-aec30ea8-47e6-11e8-81b1-4352dfadf676.PNG">
<img width="870" alt="missingsprite" src="https://user-images.githubusercontent.com/4122283/39217666-aed5b7ba-47e6-11e8-854e-fcba43e0f8d3.PNG">

**Comment by AshleyScirra** [comment] 2018-04-25 09:25
Please provide all the information required. This may be a duplicate of another issue, but it's hard to tell since you didn't include the information from the Platform Information dialog.

**Comment by zumwaltwood** [comment] 2018-04-25 12:27
What are you looking for, this is safari on iPad and Firefox on windows 10, the latest build of both. With construct 3 release 96. Additionally I gave you a minimum c3 project and screen shots, so short of videos you have everything to do the test. My tablet is the 12.9 inch 512g latest iPad, which is used for all of these bug reports.

That said, platform windows 10 and iOS on iPad, but that’s mentioned already.
I can get you the about dialogue when I get home tonight from the windows machine, but that’s useless because this is browser based, not machine based.

**Comment by AshleyScirra** [comment] 2018-04-25 14:01
You did not enter anything in to the system details field. This includes the version of C3 you're using. Depending on which version you are using, this may be a duplicate, but we can't tell because the information is missing. Please follow all the guidelines for every bug reported, the guidelines are there to make it easier for us to help you, and anything you leave out makes it more difficult to deal with the report.

**Comment by zumwaltwood** [comment] 2018-04-25 14:41
The subject line had that info, but when i get home I'll move it into the
ticket so it can be found. Construct 3, release 96, that's what r96 means

**Comment by AshleyScirra** [comment] 2018-04-25 15:16
Oh right, you put it there instead. It's more helpful to simply paste in the requested information since it's all included there with a lot more useful information too.

**Comment by zumwaltwood** [comment] 2018-04-25 15:55
iOS info posted, but can’t do Firefox until later tonight sometime.

**Comment by AshleyScirra** [comment] 2018-04-25 18:02
Can't reproduce on iOS. I can reproduce on Firefox though - looks like some weird Firefox bug involving blobs somehow getting in to an unusable state. It goes away when ImageBitmaps are disabled so looks like something to do with the createImageBitmap(blob) overload. Tried debugging but Firefox's dev tools falls to pieces at the scale of C3's code, and couldn't immediately reproduce any issue in a minimal test case, so looks like this will be a tough one...

**Comment by AshleyScirra** [comment] 2018-06-29 14:33
I'm pretty sure this is a Firefox bug. I filed a Firefox issue here: https://bugzilla.mozilla.org/show_bug.cgi?id=1472194

Meanwhile I've worked around this for the next build by entirely disabling ImageBitmap support in Firefox.

**Closed by AshleyScirra** 2018-06-29 14:33 UTC
Labels: difficult, external, firefox
