### ISSUE TITLE
Failed to open file after updating to r317

### ISSUE THREAD

**Issue by Shreyas-Mith** [Scirra/Construct-3-bugs#6253] opened 2022-11-08 04:32 UTC
## Problem description

After upgrading to the latest release ie r317. I am unable to open any project that has been modified with new release (r317).
I have tested this on other device and have noticed that, this only happens on linux OS. When i tried to open the same folder in mac or windows, the project open.

I dont work on c3p file. I save the project as a folder and maintain it on git. So i have attached the project folder. 

## Attach a .c3p

[test_project.zip](https://github.com/Scirra/Construct-3-bugs/files/9957570/test_project.zip)

## Steps to reproduce

1. A teammate created a new project and saved it as a local folder and uploaded it to git
2. I pulled the changes and when i tried to open it as a folder on chrome, it throws the "Failed to open project. Check it is a valid Construct 3 folder project."  error.
3. I have noticed that this happens only on Linux OS.

## Observed result

Failed to open project. Check it is a valid Construct 3 folder project.

These are some of the errors in developer tools.
It says failed to read Touch.json and Audio.Json. But there are audio.json and touch.json file in objectTypes folder.
This is happening after updating to r317.
![image](https://user-images.githubusercontent.com/82201047/200474439-26d9bb0e-a6af-4b85-bc56-a0e1480e3fad.png)

## Expected result

Expected the project to open.

## More details

**Affected browsers/platforms:** 
I can only test on chrome, as it is the only brower which gives option to open on a local folder.
I have noticed that this issue happens only on Linux OS. Seems to be working fine on mac/windows

**First affected release:** 
Release 317
## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r317.2 (stable)
Browser: Chrome 107.0.5304.87
Browser engine: Chromium
Context: browser
Operating system: Linux 5.15.0
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 549 gb
Storage usage (approx): 55 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Vulkan 1.2.182 (Intel(R) HD Graphics 630 (KBL GT2) (0x0000591B)), Intel open-source Mesa driver)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2022-11-08 13:02
The problem is the project folder has mixed case filenames, which causes problems on case-sensitive file systems. For example the project file refers to the Audio object as "Audio", but the JSON file for it in the project folder is named "audio.json". Construct looks for "Audio.json" and can't find it.

Construct itself should prevent this from happening. I have tested the following on both Windows (a case preserving system) and macOS (a case sensitive system):

1. Create a new project in r308.2 and add Audio object
2. Save to project folder. Note that it saves "objectTypes/audio.json", with a lowercase filename.
3. Open project folder in r317.2 and hit ave.
4. File in project folder is renamed to "objectTypes/Audio.json", preserving the correct case and matching the project file.
5. Close and reopen Construct and the project folder still successfully opens.

So I can't reproduce this happening using Construct with a local project folder.

Your steps mentioned that you used git. I suspect that what really happened is after loading in r317 and saving the project, Construct renamed all the files according to the new case-preserving folder structure, but the changes were not correctly synced to git. Perhaps someone was using a case-insensitive system like Windows, or perhaps someone only committed a few files and did not commit all the files that were renamed by case only, thereby corrupting the project as in r317+ Construct expects the filenames to be case preserving.

To work around this, try reverting git to before this happened and then try again, and make sure all changes really are committed. Alternatively if you zip the project folder and rename it .c3p, it will open (as reading the zip works case insensitively), and then you can save-as a project folder again which will write all the files with the correct case. You could then commit that to git to update it to a working project again.

As I suspect this is not really a problem with Construct and was something getting mixed up on git, closing - as far as I can see Construct is doing its part correctly.

**Closed by AshleyScirra** 2022-11-08 13:02 UTC
Labels: can't reproduce

**Comment by AshleyScirra** [comment] 2022-11-08 13:21
I think Linux is the only system that still uses a case-sensitive file system. However the steps I followed clearly do preserve the case of the filename. So I still don't believe it's to do with Construct. I can only guess something went wrong on git.

**Comment by AshleyScirra** [comment] 2022-11-08 13:23
Please provide the exact steps you followed to do this then, so I can follow them, reproduce the issue, and investigate.

**Comment by Shreyas-Mith** [comment] 2022-11-08 13:46
ill try the above suggested method, just to reconfim if its a problem with git. If not, ill reach out.
