### ISSUE TITLE
[Beta] File editor cannot edit apply in realtime

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#192] opened 2017-05-15 05:30 UTC
## Problem description

This could also be related to https://github.com/Scirra/Construct-3-bugs/issues/190.

After editing the contents of a .json Array file or dictionary file using the file editor UI, it does not apply or "save". Only when you close them that the modifications are applied.

## Steps to reproduce

1. Create a .json file, Array or dictionary.
2. Make some edits or modifications.
3. Debug preview project displaying the "Last data" contents of the file using AJAX.

## Observed result

No changes applied.

## Expected result

Should apply the changes without me closing the tab each time after I edit.

## Affected browsers

* Chrome: yes

**Comment by shortercode** [comment] 2017-05-15 07:57
Duplicate of [#19](https://github.com/Scirra/Construct-3-bugs/issues/19). Saving a text file isn't super fast so at the moment it will only update the file when the editor is closed or the project is saved. I'll probably update it so that it also does this when doing a preview as well.

In the mean time I'd just close the text/data editor when you've made your edit.

**Closed** 2017-05-15 09:56 UTC
Labels: duplicate

**Comment by jaydonteh** [comment] 2017-05-15 10:42
Having the text file saved when doing a preview should do the trick. Also, I'm sick of re-docking the editor each time I close and re-open it just to have the text file saved.
