### ISSUE TITLE
Performance Issue Building/Rendering Sprites

### ISSUE THREAD

**Issue by 8bitThirsty** [Scirra/Construct-3-bugs#552] opened 2017-06-23 13:48 UTC
## Problem description

I am experiencing very slow performance in loading layouts attempting to render sprites.  Others on the forums have been discussing this same thing and I attempted to record chrome performance unsuccessfully. 

## Attach a .c3p

Unable to download a copy after attempting to record slowness.  Waited another ~10 minuets and closed the tab, reopened it and saved this.  It took ~60 seconds to load the sprite sheet without recording.

[Bitmen.zip](https://github.com/Scirra/Construct-3-bugs/files/1097957/Bitmen.zip)

## Steps to reproduce

1. Opened project to an events page
2. Selected Chrome -> developer tools and started recording
3. Navigated to Sprite Sheet

## Observed result

Program hung for 15 mins building/rendering sprites
![test1](https://user-images.githubusercontent.com/11980014/27484579-bd7aadfa-57f7-11e7-8167-19df4698ed1b.png)

Then I stopped the recording and it loaded a few moments later but gave me this error.

![test2](https://user-images.githubusercontent.com/11980014/27484606-d9d48fca-57f7-11e7-80b3-9d706841f141.png)

## Expected result

Sprite sheet would load quickly.

## Affected browsers

* Chrome: yes

## System details

No system report and if I ever get the option to save the recording I will uploaded it here.

**Comment by 8bitThirsty** [comment] 2017-06-23 14:34
Attempted to capture a recorded profile and finally got one.  I stopped the recording after a little more than 30 seconds of unsuccessful loading so hopefully it contains something useful.
[Profile-20170623T103254.zip](https://github.com/Scirra/Construct-3-bugs/files/1098090/Profile-20170623T103254.zip)

**Comment by AshleyScirra** [comment] 2017-06-23 16:08
I can't reproduce any issue here - my system is high-end, but it's so quick (just a second or two) to view spritesheets or preview the project, that it can't be just a spec difference to be that slow. There must be some kind of fault.

The profile shows a major GC that takes over 5 seconds, which is hard to explain, even a full program GC should be ~100ms. Another odd thing is it has some extremely long blob URL requests in the network section. (Again these are local resources; they should load very quickly.) It could be an issue with Chrome, but then that doesn't explain why it doesn't reproduce for other people.

Have you tried disabling all browser addons? Does it also still happen in a new incognito window?

**Comment by 8bitThirsty** [comment] 2017-06-23 16:19
This happens with incognito mode and disabling addons doesn't have any noticeable impact.  My machine is not high end but I have used it with C2 & C3 for a while and only started noticing any performance issues within the past week.  I will attempt to reproduce on another machine or two in the next few days and try to get performance recordings.

**Comment by 8bitThirsty** [comment] 2017-06-23 22:25
Alright totally different computer and network and its a bit better on this machine but still much slower than expected and the performance recording is attached.  

[Profile-20170623T181823.zip](https://github.com/Scirra/Construct-3-bugs/files/1099187/Profile-20170623T181823.zip)

I then tried incognito mode on this machine and it loaded up almost instantly so that is a workaround for this issue on this machine at least.

**Comment by vpick001** [comment] 2017-06-24 17:12
I'm in the same boat as 8bitThirsty with the long spritesheet loading/rendering times.

In Chrome (59), very slow while loading project from file, very slow to render sprites, runs out of memory during layout preview.  It's the same story with Chrome Canary (both regular and incognito), but it does not run out of memory when doing a layout preview, it just takes 5+ minutes.

In Chrome (v. 59) Incognito, Project loads perfectly, sprites render fast, but runs out of memory during layout preview.  

It's so odd that incognito in v59 works (aside from the memory issue), but in Canary incognito it goes back to  being slow again.

Here is a log I was able to make while a layout was taking a a long time rendering the sprites.  this was done in Chrome Canary 

[Canary_Loading_Layout.zip](https://github.com/Scirra/Construct-3-bugs/files/1099898/Canary_Loading_Layout.zip)

**Comment by AshleyScirra** [comment] 2017-06-26 17:11
@vpick001 - that trace is very odd, it shows most of the time spent in GC while not collecting anything (it says it cleaned up 0 bytes of memory :-\)

If it works in Incognito mode it suggests there are browser addons causing the problem, since incognito mode usually disables all/most addons. Alternatively maybe something odd has happened to some cached resources.

Anyways, I'm pretty sure this is a Chrome bug and not to do with C3, since the profiles I've seen show the time is being spent in Chrome code and not our code. Maybe it would be better to file an issue with Google at crbug.com and provide the same information as given here.

**Comment by AshleyScirra** [comment] 2017-06-26 18:02
I pointed some Chrome engineers at this thread and they also recommended to file at crbug.com. Since I can't reproduce, can I leave that with one of you to file? Let me know the bug number and I'll follow and help out if I can.

**Comment by vpick001** [comment] 2017-06-26 18:38
@AshleyScirra how bizarre.  It's odd that it works (save for the memory error/crash) in incognito while using Chrome 59, but incognito in Canary goes right back to the same issue.  

I'll go ahead and file the bug with crbug.com and link the number back here.  I'm not a programmer, but I'll do my best to describe the issue and provide any answers.

**Comment by vpick001** [comment] 2017-06-26 19:21
@AshleyScirra Here you go. https://bugs.chromium.org/p/chromium/issues/detail?id=736861  ID 736861

**Comment by AshleyScirra** [comment] 2017-06-27 10:44
@vpick001 - great, thanks - I'll close this issue here and we'll follow it up at that report.

**Closed by AshleyScirra** 2017-06-27 10:44 UTC
Labels: browser, can't reproduce, difficult

**Comment by AshleyScirra** [comment] 2017-06-28 12:45
Looks like it was a real Chrome issue after all. Sounds like good news in that report - it should be fixed now and is hopefully being merged in to Chrome 60 (the next stable release)!
