### ISSUE TITLE
Crash when closing two merged dialogue boxes from two different projects

### ISSUE THREAD

**Issue by LukeNecklace** [Scirra/Construct-3-bugs#3050] opened 2019-06-19 10:08 UTC
## Problem description

Opening a dialogue box from an external window from a different project merges existing dialogue box from the other project together then crashes on close. 

## Attach a .c3p

https://www.dropbox.com/s/k9nvy63vm9ppuzb/Opening%20a%20dialogue%20box%20from%20an%20external%20window%20from%20a%20different%20project%20merges%20dialogue%20boxes%20together%20then%20crash%20on%20close.c3p?dl=0

## Steps to reproduce

1. Open the linked project.
2. Keep that open but open another project (like Demoniore from the demo projects page)
3. Take Demoniore's eGameRoom and place it as an external window on another screen. 
4. Double click to change the set size of sprite on the event sheet from the attached project I gave you.
5. Double click to open the dialogue box to change an existing event's action.
6. Press the X to close the dialogue box.

## Observed result

1. The two pop up dialogue boxes will be merged together.
2. Crash when the dialogue box is closed.

## Expected result

A separate dialogue box opens and will not crash when either is closed.

## More details

**Affected browsers/platforms:** Desktop

**First affected release:** r154 (not tested on previous versions).

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Function.ǃa (https://editor.construct.net/r154/main.js:2:94612) at Object.ǃHE (https://editor.construct.net/r154/projectResources.js:1:1129182) at t (https://editor.construct.net/r154/projectResources.js:1:1132436) at n (https://editor.construct.net/r154/projectResources.js:1:1132278) at o (https://editor.construct.net/r154/projectResources.js:1:1132181) at https://editor.construct.net/r154/projectResources.js:1:1132237
Stack: TypeError: unexpected type at Function.ǃa (https://editor.construct.net/r154/main.js:2:94612) at Object.ǃHE (https://editor.construct.net/r154/projectResources.js:1:1129182) at t (https://editor.construct.net/r154/projectResources.js:1:1132436) at n (https://editor.construct.net/r154/projectResources.js:1:1132278) at o (https://editor.construct.net/r154/projectResources.js:1:1132181) at https://editor.construct.net/r154/projectResources.js:1:1132237
Construct 3 version: r154
URL: https://editor.construct.net/r154/
Date: Wed Jun 19 2019 19:53:27 GMT+1000 (Australian Eastern Standard Time)
Uptime: 2571.2 s

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r154 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2019-06-19 13:02
Thanks, should be fixed in the next release. The problem is the window dimmer should appear on all windows when a modal dialog shows, to block any other activity until that modal dialog is closed.

**Closed by AshleyScirra** 2019-06-19 13:02 UTC
