### ISSUE TITLE
ImagePoint editing causes Browser to Crash

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-3-bugs#1431] opened 2018-03-26 15:17 UTC
## Problem description

When trying to edit an image point in an empty Sprite, the entire browser freezes and an endless memory consumption starts in the background , including when the Editor window is closed.

## Steps to reproduce

1. New Project
2. Create Sprite
3. Go to image points -> create image point -> DONT CLICK, but try to edit manually the number in X coordinate using num pad.

## Observed result

it freezes the browser

## Expected result

Edit the number in the image coordinate

## Affected browsers

* Chrome: no
* Firefox: yes

## System details

Firefox Quantum 59.0.1

<details><summary>View details</summary>

</details>

**Comment by luisforte** [comment] 2018-03-26 15:36
Cant reproduce here... using browser R93 and all is fine.

**Comment by AshleyScirra** [comment] 2018-03-26 16:41
@kingpirux you didn't provide some of the bug report information. Have you tried the latest beta (r93)?

**Comment by DiegoScirra** [comment] 2018-03-26 17:41
Confirmed, it happens only in Firefox, Chrome works fine.

**Comment by DiegoScirra** [comment] 2018-03-29 14:53
Fixed in r95

**Closed by DiegoScirra** 2018-03-29 14:53 UTC
Labels: confirmed, firefox

**Comment by jvalks** [comment] 2019-07-05 13:55
I have the same issue using FireFox Mac:

Select one collision point, the area is now drawn outsite the sprite! When deleting a second point, CS3 crashes.

Error report information

Type: unhandled exception
File: https://editor.construct.net/r157/main.js, line 2, col 92148
Message: TypeError: expected finite number
Stack: ǃp.ǃbh@https://editor.construct.net/r157/main.js:2:92148 ǃbnU@https://editor.construct.net/r157/projectResources.js:1:150955 ǃOZc@https://editor.construct.net/r157/projectResources.js:1:802108 ǃLx/<@https://editor.construct.net/r157/projectResources.js:1:806523
Construct 3 version: r157
URL: https://editor.construct.net/
Date: Fri Jul 05 2019 15:37:19 GMT+0200 (Midden-Europese zomertijd)
Uptime: 8495.8 s
Platform information

Browser: Firefox
Browser version: 67.0
Browser engine: Gecko
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0
C3 release: r157 (stable)
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 750M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2047
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment] 2019-07-05 14:39
@jvalks - this issue was closed over a year ago and is likely unrelated to the issue you mentioned. Please file a new report and follow all the guidelines to ensure we can help.
