### ISSUE TITLE
Construct r272 error in chrome

### ISSUE THREAD

**Issue by radel999** [Scirra/Construct-3-bugs#5250] opened 2021-11-18 11:37 UTC
## Problem description

when I run construct 3 on google chrome, an error pops up called "expected function"

## Steps to reproduce

1. Open Construct 3 r272 beta in Google chrome browser
2.
3.

## Observed result

The error will appear in start page

## Expected result

Fix the error whats i can use C3 without problems

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r272

Uncaught TypeError: BEHAVIOR_CLASS.Register is not a function
    at blob:https://editor.construct.net/4f3d1be9-7fe0-490e-ba6d-e27f4cc5ffb3:38

</details>

**Comment by AshleyScirra** [comment] 2021-11-18 12:01
Duplicate of #5245

**Closed by AshleyScirra** 2021-11-18 12:01 UTC
Labels: duplicate
