### ISSUE TITLE
(PhoneGap & Xcode) Builds Fails Exporting With Min ios12 Using (C3 NewRunTime)

### ISSUE THREAD

**Issue by Gamedevolop** [Scirra/Construct-3-bugs#2548] opened 2019-01-25 13:40 UTC
## Problem description

Hi,
I wanted to test my project to see the performance with the New C3 Run Time so I successfully Exported as Cordova but when I upload to PhoneGap to create the Ipa file it fails to Build with "Error Code 65 for Command"
I have the Log files if that helps here:
[https://www.dropbox.com/s/9k0a93nlaproqv1/build.phonegap2.pdf?dl=0](url)

My  Settings:
-Hide Status Bar
-Remove Duplicate Images
-Cordova 
-Min ios12  <<<<Here is the only option it gives me I'm not sure Why
-Worker (I Tested with Both (On & Off))

And also I Tested with Exporting it as Xcode Project:
Here I tried many attempts to install it into the Devices with Xcode but strangely it keeps saying that the iPhones are busy but a few Times I manage to Install it on the iPhones so the App starts good and goes to the Menu layout but when I try to enter to the Levels the iPhones Freezes before starts the Level so the only way to stop it is to close the App other ways none of the other buttons works like Home Button etc....
All my Devices Running on ios12+ so that's, not the issue

Ho Yeah:
Another extra info it may be useful I Exported the same Project but this Time with C2 with the same settings and I put min ios12 the same as c3 settings and surprisingly PhoneGap it Fails the same way as I explained above the same code Errors 65.
Note: I can Export and Install successfully the same Project With (C2 & c3 Old Runtime) but with min ios 9+ so it seems that the issue it relays with min ios12 somehow.

I cannot share my main project but I managed to replicate the Problem with a Demo that has no Events and just a few Objects.

## Attach a .c3p

[https://www.dropbox.com/s/81n74yldszu30vt/PhoneGap%20Build%20Fails%20min%20ios12.c3p?dl=0](url)

## Steps to reproduce

1. Export it with the C3 New Run Time as Cordova min ios12
2. Upload to PhoneGap

## Observed the result

** ARCHIVE FAILED **
The following build commands failed:
ProcessPCH /private/project/build/sharedpch/BomberMan-Prefix
awkeztabglkdjecamyztweowaoua/
BomberMan-Prefix.pch.pch BomberMan/BomberMan-Prefix.pch normal armv7
objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/private/project/cordova/build
release.
xcconfig,-workspace,BomberMan.xcworkspace,-scheme,BomberMan,-configuration,Release,-
destination,generic/platform=iOS,-
archivePath,BomberMan.xcarchive,archive,CONFIGURATION_BUILD_DIR=/private/project/build/device,SHAR
ED_PRECOMPS_DIR=/private/project/build/sharedpch,-UseModernBuildSystem=0

## Expected result

To Build Successfully the IPA

## First affected release

135.2  is the only version I tested as I didn't have the chance before

## Affected browsers/platforms

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r135.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.9 gb
Storage usage (approx): 288 mb (3.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2019-01-25 13:55
That log file is huge... I'll try running your project in xcode and see if it gives me something clearer, hopefully it reproduces outside of PGB.

**Comment by Gamedevolop** [comment] 2019-01-25 14:17
> That log file is huge... I'll try running your project in xcode and see if it gives me something clearer, hopefully it reproduces outside of PGB.

Sorry for that I thought could be useful 😃
Thank you very much for looking into it
Note: 
That it may you manage to Install successfully with Xcode with this Demo but with my main project even when I managed to install successfully the App Freezes before enters to the Levels so it may not happen with this Demo as has not Levels or Events.
With my Original project, not this Demo When it Freezes it shows some Errors on Xcode Debugger, I did some Pictures if it helps 
[https://www.dropbox.com/s/9aznubhotz4diy4/Xcode%20Error.png?dl=0](url)

**Comment by Gamedevolop** [comment] 2019-01-27 12:35
Hi @shortercode 

Just to Update:
That there is another college with the same problem using Xcode the Games Freezes when trying to enter to the Levels, I'm pretty sure you will see it already but I will leave a Link here just in case as he provides a C3 Project to Investigate making it easier for you to Reproduce & investigate it

[Similar Xcode Bug Report](https://github.com/Scirra/Construct-3-bugs/issues/2553)

Thanks

**Comment by sjrya** [comment] 2019-01-28 05:52
Hi guys, 

I wonder if this is a similar issue that I seem to be encountering. 

Users are reporting that my app is crashing is freezing on the loader screen on both iOS & Android. It seems to be an intermittent issue that I can't replicate it myself. 

I tried an update and unchecked the loader layout and also removed the preload sounds checkbox but some users are still reporting the issue>

I'm using C3 runtime, no third party plugins and app has been working fine in the past.

Thanks

**Comment by AshleyScirra** [comment] 2019-01-28 11:37
It'd be extremely useful if anyone affected can attach Safari developer tools to the device and get any log messages that appear when the problem happens.

**Comment by Gamedevolop** [comment] 2019-01-28 14:11
Hi Ashley

> It'd be extremely useful if anyone affected can attach Safari developer tools to the device and get any log messages that appear when the problem happens, if there is an issue while the app is running.

I could that but I never did it before but I will try, it may not be useful as I didn't know what I'm doing so I just took random Picture of what I think was important, if this is not helphul can you tell me the steps to do and I will try again. 
doesn't let me copy & save the code from Console to paste it here & also doesn't let me see or download the two assets that fail to load so I can post it here.


Consol Log0](https://www.dropbox.com/s/r3h4m8cmmx5z7lr/Console%20Log0.png?dl=0)
[Consol Log1](https://www.dropbox.com/s/xfz9fya32r51a53/Console%20Log1.png?dl=0)
[Consol Log2](https://www.dropbox.com/s/xa3mw8r1u68ha81/Console%20Log3.png?dl=0)
[Consol Log3](https://www.dropbox.com/s/nm7b14hydxugv36/Console%20Log4.png?dl=0)
[Consol Log4](https://www.dropbox.com/s/zevq8tnro71e7o5/Console%20Log5.png?dl=0)
[Consol Log5](https://www.dropbox.com/s/uwpv6qk3mj797lz/Console%20Log6.png?dl=0)
[Consol Log6](https://www.dropbox.com/s/3k6ok50w1cuxiv3/Console%20Log7.png?dl=0)
[Consol Log7](https://www.dropbox.com/s/m7pd7ljwcivitn3/Console%20Log8.png?dl=0)
[Consol Log8](https://www.dropbox.com/s/rtfxa57ueli6vgk/Console%20Log9.png?dl=0)
[Consol Log9](https://www.dropbox.com/s/0h1qh9sprxubixq/Console%20Log10.png?dl=0)






> Note if there is an issue with actually building the app, that is different and should be tracked in a separate issue.

Sorry I notice that after I create the report that it may cause confusion as there two different bugs in one report, I will try to open another bug separately about the "PhoneGap Build Failing"

**Comment by sjrya** [comment] 2019-01-29 00:47
Hi @Ashley, 

 I'm not able to replicate the problem myself on my iPhone so can't run the Safari console. I realise thats not very helpful!

I noticed the new Beta addresses a similar issue but with the Advanced Random plugin. This isn't something I'm using. I'll push an update with the beta and see if it fixes it anyway. I'll keep you updated.

Thanks

**Comment by Boulerzzz** [comment] 2019-02-12 17:21
Hi

Did you ever find a solution to this? I ran into this today it took me a while to figure out the min IOS 12 setting was causing this build error with phonegap.

Phonegap can **ONLY build our projects if we change the min iOS to 10 or lower** or else you get this error.

Check dependencies
warning: The armv7 architecture is deprecated for your deployment target (iOS 12.0). You should update your ARCHS build setting to remove the armv7 architecture.
Swift 3 mode has been deprecated and will be removed in a later version of Xcode. Please migrate "PROJECT NAME" to Swift 4.2 using "Convert > To Current Swift Syntax…" in the Edit menu.
Swift 3 mode has been deprecated and will be removed in a later version of Xcode. Please migrate "PROJECT NAME" to Swift 4.2 using "Convert > To Current Swift Syntax…" in the Edit menu.

** ARCHIVE FAILED **
The following build commands failed:
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler

**Comment by AshleyScirra** [comment] 2019-02-12 18:45
@shortercode maybe we should just report it to PhoneGap Build and leave it with them?

**Comment by Boulerzzz** [comment] 2019-02-13 10:18
When I open my project in xcode 10.2 I get a warning about "Swift unsupported".

When I try in 9.4 I don't get that warning.

I read this blogpost on cordova (https://cordova.apache.org/announcements/2019/02/09/cordova-ios-release-5.0.0.html)
and it says: "Supports Xcode 10 New Build System" 

Does it matter what version of Xcode we use @AshleyScirra? 

I though I had to update my xcode because of Apples announcment: (https://developer.apple.com/ios/submit/)

"Update to Xcode 10.1, which includes the iOS 12.1 SDK, and build your apps. Starting March 2019, all iOS apps submitted to the App Store will need to be built with the iOS 12.1 SDK or later, and support the all-screen design of iPhone XS Max or the 12.9-inch iPad Pro (3rd generation)."

**Comment by ChadoriRebornXD** [comment] 2019-03-04 22:15
I can reproduce, I was debugging a plugin that didn't work on build and found out that it was instead a normal export causing the problem after removing the plugin.

![screenshot](https://user-images.githubusercontent.com/31282960/53766486-de681a80-3f0d-11e9-9b2c-88c40f9d1044.png)

@shortercode 
@AshleyScirra 

May I suggest to bring back **iOS12** as a workaround for current projects with **c3runtime** in need of production release?

Thanks.

**Comment by AshleyScirra** [comment] 2019-03-05 10:17
The C3 runtime doesn't work on iOS 9 or 10, and due to Safari bugs has issues on Safari 11, so the minimum requirement of iOS 12 is necessary.

**Comment by shortercode** [comment] 2019-03-08 14:41
Okay so this bug has gone a little off track, I think there's either 3 or 4 separate issues being talked about here... So I'm going to try cover a few bases here! If you have a specific problem that you don't think is being covered then please file a new issue, having multiple conversations on one report can make it very hard for us to work on.

Firstly, the issue where games would fail at a random time due to a failed texture load has been resolved in r140 so you shouldn't be having any problems related to that anymore hopefully.

In terms of the original issue mentioned here I've checked an example project in xcode and I am able to build/archive successfully in xcode 10.1 although I haven't tried exporting to the store (chances are this is fine if the archive has been built).

iOS and XCode have been a bit of a pain point for us in terms of the C3 runtime. As @AshleyScirra said we originally targeted iOS/Safari 11 for the new runtime, but Safari 11 had some critical bugs that prevented the runtime from working correctly. They didn't fix the issues until the release of iOS 12, so we had to move the target. As per normal for the release of iOS 12 xcode got a new major version. But they also packaged a new build system, that has caused some problems for the cordova project which our iOS export is built on. Most of these issues can be resolved by **switching back to the legacy build system**, but I believe that this **isn't an option for PGB**.

Now I've just been doing some reading, and apparently cordova-ios 5 released about a month ago and includes official support for iOS 12 and the new build system. After running a quick check it doesn't look like it's the default version for the current release of cordova CLI yet, so **we will have to wait for a cordova CLI release and see what the state of play is**. They have recently released a large number of new platform versions, so **hopefully the update is coming soon**!

**Comment by shortercode** [comment] 2019-04-01 15:06
**Update**: Cordova CLI 9 released recently, which include official support for Android 9 and iOS 12. We're giving it a little while, to see if any major issues come to light. Once we've evaluated it, we will look into updating the build service. Hopefully this should resolve a series of issues with both iOS and Android.

**Comment by pixcubeanim** [comment] 2019-04-30 14:53
Hey guys! What is the current status about this? I ran into the same issue - cant generate a phonegap build with cli 8.1.1, because: 

**Check dependencies
warning: The armv7 architecture is deprecated for your deployment target (iOS 12.0). You should update your ARCHS build setting to remove the armv7 architecture.**

Error code 65 for command: xcodebuild with args: -xcconfig,/private/project/cordova/build-release.xcconfig,-workspace,PROJECT.xcworkspace,-scheme,PROJECT,-configuration,Release,-destination,generic/platform=iOS,-archivePath,PROJECT.xcarchive,archive,CONFIGURATION_BUILD_DIR=/private/project/build/device,SHARED_PRECOMPS_DIR=/private/project/build/sharedpch,-UseModernBuildSystem=0

It worked with cli 6.5.0 before - now its a little mess, but i have to update everything or some things (video playback) wount work on IOS 12.2...

Updates would be very awesome! 

Thank you very much!

**Comment by AshleyScirra** [comment] 2019-04-30 17:13
@pixcubeanim - if you are not using C3's own build service, this is the wrong place to ask for Construct 2 help, it's the Construct 3 bug tracker.

**Comment by pixcubeanim** [comment] 2019-05-02 06:40
@AshleyScirra 

thanks for the feedback, iam workin with both, c2 and c3, i guess this is also relevant for c2 too and at the end it doesnt matter, because in my case both c2 and c3 projects are build with phonegap build.

**Comment by AshleyScirra** [comment] 2019-06-11 17:34
@shortercode - is this fixed now with Cordova 9?

**Comment by shortercode** [comment] 2019-06-13 15:59
This should be resolved yes, Cordova 9 was labelled as having official support for iOS 12 and the new build system. I tried a build with one of the test projects and had no problems, so I'm going to close this. The issue had got somewhat off topic really, but had become a tracking issue for proper iOS 12 support.

If anyone has issues then file a new report and I'll take a look.

**Closed by shortercode** 2019-06-13 15:59 UTC
Labels: external
