### ISSUE TITLE
Cannot paste objects in layout after popping up to new window via ctrl v

### ISSUE THREAD

**Issue by ReflextionsDev** [Scirra/Construct-3-bugs#4468] opened 2021-01-13 07:28 UTC
## Problem description

Using ctrl x or ctrl c, the player is able to copy items, but they are not able to paste item with ctrl+v in layouts opened as pop up windows on different screens. This seems like an artifact of #4339 

## Attach a .c3p
https://github.com/ReflextionsDev/c3-bugs/blob/main/DualLayout.c3p

## Steps

1. Open a C3 project
2. Open a new layout to a pop up window
3. Copy any object
4. Attempt to paste with ctrl+v

**Affected browsers/platforms:**

Still occurring in 231. Occurred in r225. Chrome.

**Comment by AshleyScirra** [comment] 2021-01-13 12:18
It seems to be working fine for me in r231. Please don't skip bug report sections, it may be important information for dealing with the problem. Please also explain every step clearly - for example there are several ways to copy/paste and it may be that some ways work and other ways don't, so I need to know exactly what you're doing.

**Comment by ReflextionsDev** [comment] 2021-01-14 17:25
Apologies for lack of detail, the repro was very consistent for me. However after more investigating, I found this does not occur in firefox. It occurs in every instance I tried in google chrome though.

Repro:
1. Open a new project in r231 in google chrome.
2. Create a new layout with no event sheet
3. Switch to the layout
4. Drag the layout to a pop-up window
5. Drag the pop-up window to a new screen to open a new window
6. Create a sprite object
7. With ctrl+c, copy the object
8. With ctrl+v attempt to paste the object

Observe the object will not paste.

**Comment by AshleyScirra** [comment] 2021-01-14 17:32
The steps look a bit confusing - in step 4 you say to open a popup window, then step 5 says to open a new window again. Are you using one popup window or two? Did you mean to say to undock the layout view in step 4 instead?

**Comment by ReflextionsDev** [comment] 2021-01-14 18:16
> 
> 
> The steps look a bit confusing - in step 4 you say to open a popup window, then step 5 says to open a new window again. Are you using one popup window or two? Did you mean to say to undock the layout view in step 4 instead?

Yes. Sorry, I didn't really know how to phrase it. Fixed it.

**Comment by ReflextionsDev** [comment] 2021-01-14 18:16
> 
> 
> The steps look a bit confusing - in step 4 you say to open a popup window, then step 5 says to open a new window again. Are you using one popup window or two? Did you mean to say to undock the layout view in step 4 instead?

Yes. Sorry, I didn't really know how to phrase it. Fixed it.

**Comment by AshleyScirra** [comment] 2021-01-16 13:26
OK, I see - the issue reproduces if you try to copy and paste within the same popup window. You can still paste in another layout view in the main editor window, but not if you try to paste in the popup.

**Comment by AshleyScirra** [comment] 2021-01-16 13:53
Should be fixed in the next beta, thanks for the report.

**Closed by AshleyScirra** 2021-01-16 13:53 UTC
