### ISSUE TITLE
Desktop version - Failed to open project

### ISSUE THREAD

**Issue by phillnexus** [Scirra/Construct-3-bugs#1256] opened 2018-01-30 21:34 UTC
## Problem description

I simply saved my file 4 times. When I tried opening each, one of the saved files returned [this message](https://i.imgur.com/JyZiTG0.png). It seems random and unreliable to be depending on for now.

Exact steps to produce the file: Opened as a browser based file, saved from C3 (desktop) as a project file. It always saves, but when it comes to reopening a file - sometimes the export works, sometimes it doesn't.

This isn't the first time it has happened either. I tried weeks ago when the desktop beta first came out.

## Attach a .c3p

I can provide a .c3p file if I can send it via email somewhere, privately

## Steps to reproduce

1. Try to open exported project file in the desktop build
2. Wallow in sadness when it only returns an error

## Observed result

The project won't open

## Expected result

I expected the project to open

**Comment by phillnexus** [comment] 2018-01-31 11:57
File sent, thanks

**Comment by shortercode** [comment] 2018-01-31 12:22
Okay so I've taken a look at this project, it's failing to load an image file. Inside the actual project there seems to be no images, did you make any changes that would have removed the images?

**Comment by shortercode** [comment] 2018-02-02 12:37
There isn't much to go on here, just a project with missing images.

@AshleyScirra It's possible that there's an issue with how SaveProjectToFolder deals with this, but I can't see  anything wrong...

**Comment by Phillwebqem** [comment] 2018-02-02 12:43
I deleted all of the images, video etc before I sent it over, I assumed they wouldn't be needed. I can assure you the issue still occurs when the images that C3 exports are present.

The issue, like always, is that I don't want to send all of my game files to anyone over the internet for various reasons. I've never had to do such a thing for any other program I've used in the past 20 years. It's not the greatest system to have to do that every time an issue pops up.

Is there a reason it doesn't generate error logs, error codes etc? Either way, I'm sure this ticket will be closed/discarded now, but as I said, I'm not comfortable sending 2 years of work to people/environments I have no idea about.

Thanks.

**Comment by shortercode** [comment] 2018-02-02 13:09
We generally don't ask for a users project, if you look at our project guidelines we ask for a
> A minimal project demonstrating the issue

as it's a lot easier for us to work with. If you have a replication from a new project that produces this error then please let me know.

When dealing with corrupted projects we sometimes attempt to recover the project for users, I presumed you were interested in this. If you don't want to send the project then it's totally fine. I was confused because you had not told me that you had removed the images, and it's the first error that is fired when you try to load the project ( and produces the same overall error that your reporting ).

We show error logs for application crashes, but adding an error code for every possible project corruption would be very time consuming. Additionally it's easier to find out what's wrong by looking at the whole project as well as the failure reason.

**Comment by shortercode** [comment] 2018-02-02 13:39
Please refer to what the guidelines say about sharing projects [do-i-need-to-share-my-entire-project-i-have-copyright-concerns](https://github.com/Scirra/Construct-3-bugs#do-i-need-to-share-my-entire-project-i-have-copyright-concerns).

Without any replication steps to produce a corrupted project it's unlikely that I will be able to fix the underlying issue. I'm willing to attempt to repair your project anyway, but with the content removed the project is unload-able anyway so I will not be able to diagnose why you were unable to open it. Your welcome to replace it with placeholder content if you want.

**Comment by Phillwebqem** [comment] 2018-02-02 13:47
There's no need for a repair, I had a backup. But this issue is why I can't rely on a desktop build. It happens randomly when I save the file. Sometimes it works, sometimes it doesn't.

Replacing hundreds of images/video/audio files will take far too long. And what if the issue is related to one of those files?

Thanks anyway

**Comment by AshleyScirra** [comment] 2018-02-05 15:40
If your project uses bundled addons, it's probably the same issue as #1262. Otherwise without steps to reproduce, there is probably nothing we can do. As is very common the problem is related to a specific aspect of the project which is why we can't reproduce the issue without the project in question.

**Comment by Phillwebqem** [comment] 2018-02-05 23:56
It's bundled with MM_Preloader

Hopefully that's it, thanks

**Comment by AshleyScirra** [comment] 2018-02-06 10:06
OK, should be fixed as per #1262 so closing.

**Closed by AshleyScirra** 2018-02-06 10:06 UTC
Labels: can't reproduce, ignored guidelines
