### ISSUE TITLE
Particles - Object sprite not rendered in the corrert angle in editor

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#5346] opened 2022-01-03 16:34 UTC
## Problem description
Sprite object attached to a particle emitter does not inherit the particle object angle in the editor.

## Attach a .c3p

[particlesObjDir.zip](https://github.com/Scirra/Construct-3-bugs/files/7802960/particlesObjDir.zip)

## Steps to reproduce

1. Start live preview and see rendered angle (always 0).
2. Run the layout and see rendered angle (inherits emitter angle).

## Observed result

See 1 above

## Expected result

See 2 above

## More details

**Affected browsers/platforms:** Chrome/NWjs, Windows

**First affected release:** I believe it's been like that for a while now.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2022-01-25 16:12
This issue does reproduce, but unfortunately I don't think it's feasible to fix. In the editor live preview can only use the built-in particles effect - there isn't actually support for object mode for live preview, as it is technically complicated to implement in the context of the editor. Therefore it just takes the image of the chosen object and runs the default particle effect with it; since the default particle effect does not support rotation, the previewed particles effect has images that are not rotated.

Even if special handling was added for rotation only, it would still not completely solve the problem: objects can have color tints, effects applied, and so on, and all these cases will also not be visible in live preview. The only way to support that would be to properly implement an object particles mode in the editor, but as mentioned that is technically complicated; in particular it would likely interfere with editing tools, various user interface bars, UID assignment, undo, saving to the project file format, and probably more - none of which is an issue at runtime (and the implementation there is pretty straightforward). Resolving all these cases would likely be long, difficult and error-prone work. Unfortunately as a small team with limited resources I don't believe we can justify this to fix a single specific case with the Particles object, so I'm afraid I think the best thing to do is just leave it as something that is not supported.

**Closed by AshleyScirra** 2022-01-25 16:12 UTC
Labels: wontfix
