### ISSUE TITLE
Build Server Issues: "Build Failed. Cannot connect to build server"

### ISSUE THREAD

**Issue by jefleppard** [Scirra/Construct-3-bugs#1206] opened 2018-01-16 23:45 UTC
## Unable to export Cordova/iOS/Xcode build due to repeated build server issues

*The build server repeatedly times out / loses connection while attempting to create an Xcode build*

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

"Empty" Test Project:
[Test.zip](https://github.com/Scirra/Construct-3-bugs/files/1637178/Test.zip)

## Steps to reproduce

1. Export project using iOS (Cordova) settings
2. Use the Export Manager and select the row for the exported project
3. In the Cordova options > iOS build, select "Xcode project"
P.S. I have tried this in three different browsers on three different machines using both wifi and ethernet connections.

## Observed result
The server then sends out the following message(s):
"Connected to server
recieved project
waiting to build
Lost connection to build server, retrying in 5 seconds (1)
Connecting to build server...
Connected to server
restored connection"
It then tries to connect 3 more times before showing this popup:
![image](https://user-images.githubusercontent.com/25141036/35017783-51236230-fad3-11e7-9dbf-2cf8e9f804d6.png)

## Expected result
*What did you expect to happen instead?*
I expected to be able to download the generated Xcode project, or have some sort of insight into why the build/build server is failing.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: not sure

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 57.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
C3 release: r78
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 59 mb (2.9%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    UI animations are disabled in Firefox due to bug 1354501
    CSS containment is not supported. Editor performance may be significantly degraded.
    The <dialog> element is not supported. A polyfill is in use.
    This browser does not support pluralisation rules. Plural forms may not be correct.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 670 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_texture_filter_anisotropic
    EXT_disjoint_timer_query
    OES_texture_float_linear
    WEBGL_compressed_texture_s3tc
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context
    MOZ_WEBGL_lose_context
    MOZ_WEBGL_compressed_texture_s3tc

Audio information

System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    WebM Vorbis (audio/webm; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2018-01-17 11:15
Looks like the server choked up after a build last night. I've restarted the process and it's working fine for now. I'm looking through the logs to see if I can identify why it got stuck.

**Comment by jefleppard** [comment] 2018-01-17 21:14
Thank-you Iain, I was able to get a build of my game finished this morning because of you. Are there any plans to better communicate this sort of issue to users if it's encountered in the future? I went through hours of troubleshooting trying to figure out what I was doing wrong. A link to a service status url that says "build server is choked up right now, we're working on it" would be ideal... at least more descriptive than the current "build failed" popup.

**Comment by shortercode** [comment] 2018-02-20 16:28
We currently don't have anywhere you could track service status for the build server. I believe in this case the server was automatically disconnecting an idle connection, so no message was sent when the connection closed for the editor to display. So "Build Failed" was about all the editor knew. 

Some work needs to be done to improve the error messages from the server certainly. I'm due to look at it soon and I also still need to track down this lockup. It's happened twice since the service was started, and there's no obvious cause.

**Comment by shortercode** [comment] 2018-02-20 16:31
I'm going to close this, as the original issue is solved and the related issue is being tracked on our internal bug tracker.

**Closed by shortercode** 2018-02-20 16:31 UTC

**Comment by jefleppard** [comment] 2018-02-20 22:39
Thanks for the response and for looking into this. :)
 

    On Tuesday, February 20, 2018, 8:28:57 AM PST, Iain Shorter <notifications@github.com> wrote:  
 
 
We currently don't have anywhere you could track service status for the build server. I believe in this case the server was automatically disconnecting an idle connection, so no message was sent when the connection closed for the editor to display. So "Build Failed" was about all the editor knew.

Some work needs to be done to improve the error messages from the server certainly. I'm due to look at it soon and I also still need to track down this lockup. It's happened twice since the service was started, and there's no obvious cause.

**Comment by gloater** [comment] 2018-04-12 11:03
hey there , how to reslove this , i get it 1000 times everyday ... tired of it

**Comment by shortercode** [comment] 2018-04-12 11:11
@gloater please don't comment on closed bugs, there's a good chance we won't see the message. The server should currently be working, and we are still working to find the root cause. At the moment this bug is occurring about once every 3 weeks or around that.

**Comment by Super-games-creator** [comment] 2022-09-26 11:13
> Looks like the server choked up after a build last night. I've restarted the process and it's working fine for now. I'm looking through the logs to see if I can identify why it got stuck.

Please restart the server again)
