### ISSUE TITLE
[Desktop Build - R105] Crash when trying to open image with Photoshop CC 2015.5

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#1707] opened 2018-06-18 12:51 UTC
## Problem description

After clicking "use external editing software" in the animation editor, I select Photoshop CC 2015.5, then click "OK" to confirm. Then the editor crashes each time.
Please note that this is the first time I define the software. I don't know if it's supposed to work once the software is already defined.

## Attach a .c3p

- not relevant

## Steps to reproduce

1. In the desktop build, create a sprite and load an image
2. Click "use external editing software" and select Photoshop 2015.5 (didn't try any other software)
3. Click OK to open the image in Photoshop 2015.5
4. the editor crashes every time.

## Observed result

The editor crashes

## Expected result

Opening the image in Photoshop 2015.5 as planned

## Affected browsers

Desktop build

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r105/main.js, line 74, col 357678
Message: Uncaught TypeError: Cannot read property 'parentNode' of undefined
Stack: TypeError: Cannot read property 'parentNode' of undefined at ǃh.ǃP.ǃu.ǃH_O.ǃjB (https://editor.construct.net/r105/main.js:74:357678) at HTMLButtonElement.ǃh.ǃP.ǃu.ǃH_O.constructor.ǃjO.onclick (https://editor.construct.net/r105/main.js:74:356638)
Construct 3 version: r105
URL: https://editor.construct.net/r105/
Date: Mon Jun 18 2018 14:39:19 GMT+0200 (Romance Daylight Time)
Uptime: 5277.5 s

Platform information
Browser: NW.js
Browser version: 0.30.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@004e06da11e10bb08f6632224ae48ee3d5f7b303) NWjs/0.30.0 (like Chrome/66.0.3359.117)
C3 release: r105 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2018-06-18 14:39
Possible duplicate of #1691?

**Comment by DiegoScirra** [comment] 2018-06-25 11:22
Fixed

**Closed by DiegoScirra** 2018-06-25 11:22 UTC
Labels: desktop
