### ISSUE TITLE
Cannot get Google Play Game Services running for Android

### ISSUE THREAD

**Issue by Scott943** [Scirra/Construct-3-bugs#808] opened 2017-09-16 15:54 UTC
## Problem description

*Enter a concise description of your problem here*
I cannot get Google Play's game services (the leaderboards specifically) to run on Android. I have followed the instructions in the Construct manual, but I cannot get the high score board to appear when a button is pressed, in an Alpha Release. It is working perfectly fine on iOS: https://itunes.apple.com/us/app/sidecar-split/id1242080473?ls=1&mt=8

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
Project with only main layout attached (see line 181 for Google Play Commands): 
[Sidecar Split (47).zip](https://github.com/Scirra/Construct-3-bugs/files/1308433/Sidecar.Split.47.zip)

## Steps to reproduce

1. Configure any game on Google Play and its game services.
2. Add Application and Client ID to Construct 3 Project Google Play Properties
3. Export to Android, sign, and upload to Google Play
4. (Add Sign in and show high score actions in Construct 3)
5. Test in an Alpha Release on an Android device.

## Observed result

*What do you see happen?* 
Nothing happens when I click the highscore button.

## Expected result

*What did you expect to happen instead?*
The top score would be submitted and the leaderboards are opened up.

## Affected browsers

* Chrome: yes
* Firefox:
* Edge: 
* Safari: 

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 60.0.3112.113
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
C3 release: r55

Local storage
Storage quota (approx): 5.2 gb
Storage usage (approx): 438 mb (8.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2017-09-18 11:22
Looks like a duplicate of #452.

**Closed by AshleyScirra** 2017-09-18 11:22 UTC

**Comment by Scott943** [comment] 2017-09-18 18:23
@AshleyScirra I wouldn't say it is an exact duplicate. At least #452 can get Google Play working. I am still stuck at the first hurdle?
