### ISSUE TITLE
HTMLElement: Position object at element. Object will not be selected

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5713] opened 2022-05-19 09:30 UTC
## Problem description

Add wait 0 can solves it
![Snipaste_2022-05-19_17-27-49](https://user-images.githubusercontent.com/45864744/169261536-bf32b333-537e-4e27-b2a7-2777885f0130.png)

## Attach a .c3p

[issue-Position-object-at-element.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8727848/issue-Position-object-at-element.c3p.zip)

## Steps to reproduce

1. Position object at element
2. Set size

4. Click "demolink" 

![Snipaste_2022-05-19_17-31-44](https://user-images.githubusercontent.com/45864744/169262462-0fce0c80-59c2-4e84-a087-9ce0b0934ede.png)

![Snipaste_2022-05-19_17-31-44](https://user-images.githubusercontent.com/45864744/169261996-c6b147a4-d792-4bf0-a434-00b0fed298f3.png)

6.  use 'wait 0'  re try

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2022-05-19 10:02
It's not clear from this report what you think the problem is. Please always fill out the full report, including the expected and observed results, otherwise it can be difficult to identify what you think the problem is.

In this case it looks like a mistake in your events, so closing. The HTMLElement actions are asynchronous, meaning they don't finish until after 'Wait for previous actions to complete'. But you don't use that, and just immediately make changes, so there will be a conflict between which change happens first.

**Closed by AshleyScirra** 2022-05-19 10:02 UTC
Labels: not a bug
