### ISSUE TITLE
Canvas paste issue

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-3-bugs#5379] opened 2022-01-17 16:47 UTC
## Problem description

Referring same issue using apk.
https://github.com/Scirra/Construct-3-bugs/issues/5375

Used this project, used r278.2 and r276.2, used C3 build service for apks. If you need any other detail please let me know.

## Attach a .c3p
Project file.
[canvasbug.zip](https://github.com/Scirra/Construct-3-bugs/files/7883435/canvasbug.zip)

[apk files.zip](https://github.com/Scirra/Construct-3-bugs/files/7883446/apk.files.zip)

## Steps to reproduce

1. Install "Bug - r278.2.apk" and run. Result should be like this. [BUG]

![Screenshot_20220117-192945_New project](https://user-images.githubusercontent.com/54614906/149808896-63161c5d-ddd0-49cb-91c1-00640d74f7cc.png)

2. Install "NoBug - r276.2.apk" and run. Result should be like this. [WORKING FINE]

![Screenshot_20220117-192918_NoBug](https://user-images.githubusercontent.com/54614906/149808919-397fb1be-3f8f-4e5f-ab9f-125692468b15.png)

## Observed result

![Screenshot_20220117-192945_New project](https://user-images.githubusercontent.com/54614906/149808896-63161c5d-ddd0-49cb-91c1-00640d74f7cc.png)

## Expected result

![Screenshot_20220117-192918_NoBug](https://user-images.githubusercontent.com/54614906/149808919-397fb1be-3f8f-4e5f-ab9f-125692468b15.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** r277

## System details

Phone: Galaxy A70 Android 11

**Comment by AshleyScirra** [comment] 2022-01-18 11:48
Is this reproducible in a desktop browser? It's much quicker and easier to deal with issues if you can reproduce it there, as building and running an APK takes quite a lot of time, and it may be necessary to test changes dozens of times while investigating the issue. Even in an Android browser would be quicker as I can use Remote Preview. Or does it only reproduce in an APK?

**Comment by CrackHub** [comment] 2022-01-18 12:56
I can reproduce using this project.
1.) Preview project using Chrome 97.0.4692.71 - Windows 11 - r278.2 - [Canvas issue]
2.) Preview project using Firefox 96.0.1 - Windows 11 - r278.2 - [Canvas issue]
3.) Remote preview project using Galaxy A70 - Android 11 - r278.2 - [Canvas issue]

If I use r276.2 all steps working fine
## System details




<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 97.0.4692.71
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
C3 release: r278.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 135 gb
Storage usage (approx): 265 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 3GB Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.15.1109)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by CrackHub** [comment] 2022-01-19 15:15
[paste_oj_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/7898221/paste_oj_bug.zip)

Easy way to reproduce (Found it on Construct Community);
1.) Change C3 settings -> Preview with "Browser Tab"
2.) Restart C3
3.) Preview project with device mode (with Chrome DevTools)

If you see this screen it is bugged.
![xxx](https://user-images.githubusercontent.com/54614906/150159362-169c2f49-3caf-48af-8321-a9b95f1aa76d.png)

**Comment by tuzke** [comment] 2022-01-21 04:13
I have the same issue

**Comment by AshleyScirra** [comment] 2022-02-03 12:25
I was able to reproduce in r281 using the steps in [this comment](https://github.com/Scirra/Construct-3-bugs/issues/5379#issuecomment-1016567608). It looks like 'Paste object' could sometimes use the wrong scale. This should be fixed in the next beta.

**Closed by AshleyScirra** 2022-02-03 12:25 UTC
