### ISSUE TITLE
Issue loading project with C3 desktop build

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#1262] opened 2018-02-03 23:55 UTC
## Problem description

I was trying out the desktop build of c3, i save the project to folder, and saved the same project the to single c3p file, i then reopened the desktop version of c3 and tried to load from the c3proj file and it fails but i am able to load the the .c3p fine, 

i first though it had something to do with git changing the line ending, but that did not seem to be the case as i created a brand new project did a git init and committed modification which changed the line ending from LF to CRLF and i was able to load that project fine.

i'm not sure but this issue sound alot like mine, but i dont know for sure.
 
https://github.com/Scirra/Construct-3-bugs/issues/1256

## Attach a .c3p

Link to c3p i was using
https://drive.google.com/open?id=1fiU7hfIsOehMFD6uJFdyAto-1KW_uCs9

Link to gif of the issue
https://drive.google.com/open?id=1IAelHXtxAc1wNZZoG1JlG9zCLnaVIogB

## Steps to reproduce

1. export my project with desktop build of c3 to folder structure
2. close c3
3. try and load project 

## Observed result

the game fails to load, get a message that it is not a valid c3 project

## Expected result

have my game load 

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.27.4
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@d8d23fd3b95d7b3c7744027f2ea1c954aec28955) NWjs/0.27.4 (like Chrome/63.0.3239.132)
C3 release: r83
Language setting: en-US

Local storage
Storage quota (approx): 811 gb
Storage usage (approx): 17 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2018-02-05 15:38
I can't reproduce with Ghost Shooter, but your project does reproduce the issue. I think the problem is to do with the fact the project uses bundled addons, which might not be handled properly in the desktop build. I'm looking in to it.

**Comment by AshleyScirra** [comment] 2018-02-05 15:50
Yeah, the problem is the desktop build fails to load bundled addons. Should be fixed in the next build.

**Closed by AshleyScirra** 2018-02-05 15:50 UTC
Labels: desktop
