### ISSUE TITLE
C2-C3 Runtime - Black Bottom Area - Android

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#2364] opened 2018-11-22 18:20 UTC
## Problem description

I see this bottom area in my Samsung Galaxy J5 phone.
Build with C3 Build service.
Hide StatusBar (Yes)

Phone Specs
Android 6.0.1

![screen](https://user-images.githubusercontent.com/13033837/48918095-7d0ac700-ee9b-11e8-8cea-9b5a03c93f10.png)

## Attach a .c3p
You can use any project but If you want my project, it is here too.
[BlackBar.zip](https://github.com/Scirra/Construct-3-bugs/files/2609028/BlackBar.zip)

## Steps to reproduce

1. Make a build with C3 Build Service or CLI.
2. Install apk on your phone. (It is happens on Samsung Galaxy J5, I don't have any other phone)

## Observed result

Black bottom area

## Expected result

No black bottom area

**Comment by QuasarX** [comment] 2018-11-22 20:51
I see that bar with Construct 2 export too **(With this project)**.

**I tested my game with Construct 2 export.
I see this bottom bar only 5 seconds. After It is removing and works fine.**

Well.
But what removing that after 5 second in my game. I will try to make little capx for this bug report.

**Comment by shortercode** [comment] 2018-11-23 11:44
If you swipe up from the bottom does the navbar fill the exact space? I expect it's related to #2092

**Comment by QuasarX** [comment] 2018-11-23 17:09
@shortercode 
No It doesn't fill. I tried slide up doesn't move that area anywhere.
But I found this.

If I click devices this button and re-back game. It is going fullscreen without that bar.
![image](https://user-images.githubusercontent.com/13033837/48954645-88252c00-ef5b-11e8-946b-daa97caea80f.png)

But still didn't found why my game don't need anything. After 5 sec auto removing that bar.

**Comment by QuasarX** [comment] 2018-11-23 20:00
Also I found one solution. Mobile advert plugin removing that bar. I tried your GDPR Test template and I don't see any bottom bar. It is removed at when I see C3 Splash image.

**Comment by shortercode** [comment] 2018-11-28 17:59
I remember seeing a bug about a week back which @AshleyScirra looked at, something about not monitoring resize events during start up. I guess this could be related.

The mobile advert plugin does some minor rejigging of the webview layout if memory serves, so that it can place banner adverts over the webview. Been quite awhile since I wrote that code, so I could be wrong. I'll see if I can get this to replicate and do some testing.

**Comment by AshleyScirra** [comment] 2018-12-03 17:06
This might be related to #2376, which should be fixed in r128. Can you reproduce it there?

**Comment by QuasarX** [comment] 2018-12-03 18:07
@AshleyScirra I tried with r128. Still same problem.

**Comment by AshleyScirra** [comment] 2018-12-03 19:03
OK, guess it's something different...

**Comment by bewa11** [comment] 2019-02-28 23:36
@AshleyScirra @shortercode there is a very simple solution to this. Splash screen with the correct sizes and the plugin has to be used.

1. Put Splash Screens into www folder with the following sizes:
LDPI: 
        ◦ Portrait: 200x320px 
        ◦ Landscape: 320x200px 
    • MDPI: 
        ◦ Portrait: 320x480px 
        ◦ Landscape: 480x320px 
    • HDPI: 
        ◦ Portrait: 480x800px 
        ◦ Landscape: 800x480px 
    • XHDPI: 
        ◦ Portrait: 720px1280px 
        ◦ Landscape: 1280x720px 
    • XXHDPI: 
        ◦ Portrait: 960px1600px 
        ◦ Landscape: 1600x960px 
    • XXXHDPI: 
        ◦ Portrait: 1280px1920px 
        ◦ Landscape: 1920x1280px 

2. Add the following to config.xml:
<plugin name="cordova-plugin-splashscreen" />

Reference the splash screen in the config file.


This fixed it. Here is how my config file looks:

<plugin name="cordova-plugin-splashscreen" />

<platform name="android">
 
    <splash src="www/splash-land-hdpi.png" density="land-hdpi"/>
    <splash src="www/splash-land-ldpi.png" density="land-ldpi"/>
    <splash src="www/splash-land-mdpi.png" density="land-mdpi"/>
    <splash src="www/splash-land-xhdpi.png" density="land-xhdpi"/>
    <splash src="www/splash-land-xxhdpi.png" density="land-xxhdpi"/>
    <splash src="www/splash-land-xxxhdpi.png" density="land-xxxhdpi"/>

    <splash src="www/splash-port-hdpi.png" density="port-hdpi"/>
    <splash src="www/splash-port-ldpi.png" density="port-ldpi"/>
    <splash src="www/splash-port-mdpi.png" density="port-mdpi"/>
    <splash src="www/splash-port-xhdpi.png" density="port-xhdpi"/>
    <splash src="www/splash-port-xxhdpi.png" density="port-xxhdpi"/>
    <splash src="www/splash-port-xxxhdpi.png" density="port-xxxhdpi"/>

</platform>

**Comment by AshleyScirra** [comment] 2019-06-11 17:33
@shortercode - is this fixed now with Cordova 9?

**Comment by QuasarX** [comment] 2019-06-11 19:32
@AshleyScirra Nope. I tried with CLI v9 + Android 8.0 still same.

@bewa11 **cordova-plugin-splashscreen** not compatible with Cordova 9

**Comment by shortercode** [comment] 2019-06-21 16:25
So only one device in the office has this bug, I think it's a legacy race condition. I've seen a few notes about similar issues in the official Android documentation. The app tries to enter fullscreen as soon as it starts, but it takes a little while before it actually works on some devices. So when the webview is created the status bar, etc. are still on screen ( making it slightly shorter ). It doesn't notice that the app has resized so stays this height.

I've made a workaround that manually triggers fullscreen mode when the runtime is starting up instead ( we already do this for iOS anyway ) and it seems to work great in the C2 runtime. However, on the C3 runtime it triggers some rendering issue, where only the background colour is drawn. I'm trying to figure out if there is a way to avoid this, it's a bit weird that it only occurs in the C3 runtime but it might be related to timing again.

**Comment by shortercode** [comment] 2019-06-21 17:33
Okay I've merged in the fix, should be resolved in the next release.

**Comment by QuasarX** [comment] 2019-06-21 20:48
Will try, thanks

**Comment by AshleyScirra** [comment] 2019-06-24 14:44
r156 is now out, please test again!

**Comment by QuasarX** [comment] 2019-06-24 16:50
Construct 3 r156

Samsung Galaxy J5 phone.
Android 6.0.1

Works fine. No more black bottom area.

**Comment by AshleyScirra** [comment] 2019-06-24 17:08
Thanks for confirming!

**Closed by AshleyScirra** 2019-06-24 17:08 UTC
Labels: Android
