### ISSUE TITLE
Crash at start resource error

### ISSUE THREAD

**Issue by benjaboyy** [Scirra/Construct-3-bugs#5966] opened 2022-08-06 14:33 UTC
## Problem description

When i open te project i get a error, worked fine on other apple laptop and windows pc (first time booted this project on this laptop)

## Attach a .c3p

[https://drive.google.com/file/d/14WqEKCdsFRceQW9et2CLrQeUXDxXrVg-/view?usp=sharing](url)

## Steps to reproduce

1. Open project

**Affected browsers/platforms:** 

Tested on my macbook pro, Chrome and Firefox

**First affected release:** 

R302

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: addon initial-frame is not registered
Stack: Error at xa.BSa (https://editor.construct.net/r302/main.js:979:289) at window.assert (https://editor.construct.net/r302/main.js:896:38) at d.N2 (https://editor.construct.net/r302/projectResources.js:1110:393) at d.qcc (https://editor.construct.net/r302/projectResources.js:1110:373) at async d.Ga (https://editor.construct.net/r302/projectResources.js:1118:376) at async d.Vwc (https://editor.construct.net/r302/projectResources.js:1120:84) at async d.Ga (https://editor.construct.net/r302/projectResources.js:1099:92) at async d.FRb (https://editor.construct.net/r302/projectResources.js:1103:24) at async d.Nlb (https://editor.construct.net/r302/projectResources.js:1103:139) at async d.Ga (https://editor.construct.net/r302/projectResources.js:1033:196)
Construct version: r302
URL: https://editor.construct.net/
Date: Sat Aug 06 2022 16:25:49 GMT+0200 (Midden-Europese zomertijd)
Uptime: 32.8 s

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 104.0.5112.79
Browser engine: Chromium
Context: browser
Operating system: macOS 12.4.0
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: nl-NL

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by AshleyScirra** [comment] 2022-08-08 10:31
Seems to work fine for me with no error, @DiegoScirra maybe there's a race condition somewhere?

**Comment by DiegoScirra** [comment] 2022-08-09 17:37
This is definitely a race condition, but I still don't understand why it's happening. It should be waiting for everything.

@benjaboyy

Does this still happen? Or did it sort itself out?

**Comment by benjaboyy** [comment] 2022-08-10 08:09
Yes it does still happen. I'll do some tests on other PCs as well.

**Comment by benjaboyy** [comment] 2022-08-21 21:16
@DiegoScirra i still can't open my project. can you please try remove the timeline objects, i have had problems with those before.

**Comment by DiegoScirra** [comment] 2022-08-22 13:56
@benjaboyy

The next beta will have a possible fix for this issue, but since I haven't been able to reproduce it myself, it is hard to tell if it will work. You will need to try it out.

**Comment by AshleyScirra** [comment] 2022-08-23 14:28
Beta r307 is now out, please check again there!

**Comment by benjaboyy** [comment] 2022-08-24 20:12
@DiegoScirra Nope the bug is still in r307 with the same message

**Comment by benjaboyy** [comment] 2022-08-24 20:39
Another observation: when i pasted my timelines back into my project on the windows pc the error happens there as well.

**Comment by DiegoScirra** [comment] 2022-10-12 12:22
@benjaboyy

Just found something that might be causing this problem, can't really verify it fixes your problem because the problem doesn't happen in any of the computers I have tried it. Please check the next beta!

**Comment by AshleyScirra** [comment] 2022-10-18 11:15
@benjaboyy - r315 is now out, please check again with that.

**Comment by DiegoScirra** [comment] 2022-11-24 19:31
Closing this as it seems to have been forgotten.

**Closed by DiegoScirra** 2022-11-24 19:31 UTC
Labels: need info
