### ISSUE TITLE
Dragging WOFF onto Import Fonts crashes

### ISSUE THREAD

**Issue by blackhornet2010** [Scirra/Construct-3-bugs#9] opened 2017-04-06 17:43 UTC
## Problem description

*Enter a concise description of your problem here*

## Attach a .c3p

Same file that is in: https://www.scirra.com/forum/woff-crash_t189904

## System details
<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r15/main.js, line 140, col 49842
Message: Uncaught TypeError: he.ǃrfC is not a function
Stack: TypeError: he.ǃrfC is not a function at ue (https://editor.construct.net/r15/main.js:140:49842) at ǃr.ǃT.ǃO.ǃZWT.ǃZWL (https://editor.construct.net/r15/main.js:140:50049) at HTMLDivElement.ǃZWn.addEventListener.ue (https://editor.construct.net/r15/main.js:140:48445)
Construct 3 version: r15
URL: https://editor.construct.net/
Date: Wed Apr 05 2017 16:35:01 GMT-0700 (Pacific Daylight Time)
Uptime: 122.1 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 6570 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2017-04-07 15:44
Can't reproduce in r16. Is it working for you there?

**Comment by blackhornet2010** [comment] 2017-04-07 18:35
(Font is in this file: http://www.blackhornettechnologies.com/C3bugs/WOFFbug.c3p.zip)

Error report information
Type: unhandled exception
File: https://editor.construct.net/r16/main.js, line 140, col 52663
Message: Uncaught TypeError: he.ǃpAJ is not a function
Stack: TypeError: he.ǃpAJ is not a function at We (https://editor.construct.net/r16/main.js:140:52663) at ǃp.ǃd.ǃLo.ǃLMg.ǃLMx (https://editor.construct.net/r16/main.js:140:52870) at HTMLDivElement.ǃLMD.addEventListener.We (https://editor.construct.net/r16/main.js:140:51255)
Construct 3 version: r16
URL: https://editor.construct.net/
Date: Fri Apr 07 2017 11:34:09 GMT-0700 (Pacific Daylight Time)
Uptime: 58.9 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 6570 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment] 2017-04-11 11:38
r17 is out, can you verify if this is still a problem?

**Comment by blackhornet2010** [comment] 2017-04-11 14:18
Error report information
Type: unhandled exception
File: https://editor.construct.net/r17/main.js, line 140, col 53100
Message: Uncaught TypeError: pe.ǃEmC is not a function
Stack: TypeError: pe.ǃEmC is not a function at ue (https://editor.construct.net/r17/main.js:140:53100) at ǃE.ǃv.ǃP.ǃajy.ǃajN (https://editor.construct.net/r17/main.js:140:53307) at HTMLDivElement.ǃajz.addEventListener.ue (https://editor.construct.net/r17/main.js:140:51689)
Construct 3 version: r17
URL: https://editor.construct.net/
Date: Tue Apr 11 2017 07:18:16 GMT-0700 (Pacific Daylight Time)
Uptime: 36.9 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 6570 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment] 2017-04-11 14:29
Ah, turns out it's a minifier related thing. Should be fixed in r18.

**Closed by AshleyScirra** 2017-04-11 14:29 UTC
