### ISSUE TITLE
effect SetColor's parameters not working in certain situation

### ISSUE THREAD

**Issue by rogerty** [Scirra/Construct-3-bugs#1117] opened 2017-12-21 20:54 UTC
## Problem description

A minor bug:
After importing a C2 project in C3, the parameter adjustments of the effect SetColor do not work anymore as intended.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Create SetColor effect on a sprite in a C2 project and adjust parameters with events
2. Import C2 project in C3 
3. Now the parameters do not give the same colors as in a C2 project

Workaround: Delete the effect in C3 and add the effect.

## Observed result

The colors only change to black or almost see through or in some cases (if adjusting the 1st parameter), shades of red.

## Expected result

I used:
every tick, mouse.x --> bind that to a parameter of the SetColor. And you see a gradual change in color.

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2017-12-21 23:24
No .c3p provided but sounds like a duplicate of #1103, #573, #659, #665 so closing.

**Closed by AshleyScirra** 2017-12-21 23:24 UTC
Labels: duplicate, ignored guidelines
