### ISSUE TITLE
expression dictionary window incorrect spacing

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#726] opened 2017-08-17 19:28 UTC
## Problem description

the expressions are very far apart for some reason and the info is all squashed up at one end. It doesnt matter how the window is resized, and it makes finding things difficult.

## Attach a .c3p

n/a

## Steps to reproduce

1.
2.
3.

## Observed result

https://www.dropbox.com/s/mrngxldbt1wldbd/expressionED.gif?raw=1

expression description is squashed up at one end making column very tall, this means only a few expressions are visible in window and requires lots of scrolling to find expressions.

https://www.dropbox.com/s/pas4gxxsrdbsv1q/Screen%20Shot%202017-08-13%20at%2014.03.12.png?raw=1

## Expected result

Description text should not be squashed up. each expression should not take up so much of window.

## Affected browsers

* Chrome: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 60.0.3112.101
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36
C3 release: r49

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 44 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: ATI Technologies Inc.
Renderer: ATI Radeon HD 5670 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2017-08-18 17:29
Are you using any plugins?

**Comment by mOOnpunk** [comment] 2017-08-18 17:36
yes, lite tween 

https://www.scirra.com/forum/behavior-litetween_t70700?sid=a27bc7f13bfe1bb01bbc744248f653d9

**Comment by DiegoScirra** [comment] 2017-08-21 10:21
I can't reproduce this one, I thought the dialog might not be working properly if an expression name was too long, but that is not the case.

I tried it on Windows and OSX aswell, seems to be working properly in both systems.

Does this happen if you try it with a new empty project?

**Comment by mOOnpunk** [comment] 2017-08-21 15:42
yes, but only with lite tween, without it looks correct.

**Comment by mOOnpunk** [comment] 2017-08-21 15:45
Could you make each window section slidable/resizable? That way i could drag the desciption section over which would narrow the expressions.

**Comment by DiegoScirra** [comment] 2017-08-22 15:15
I'll take another look at it with and without the Lite Tween plugin. It seems something is up with it, but I must have missed it the first time around.

**Comment by DiegoScirra** [comment] 2017-08-22 16:21
Ofcourse if you can provide a set up steps that will reproduce the problem 100% of the time, I would greatly appreciate it. Otherwise I am just trying to guess what is going on.

**Comment by mOOnpunk** [comment] 2017-08-23 15:38
Hi, There is no steps to reproduce, it's just like that when the plugins used in a project, as far as i can tell.

**Comment by AshleyScirra** [comment] 2017-08-29 17:54
I can sort of reproduce this: the expression name column is too wide - much wider than the widest expression name - which unnecessarily squashes the description column. The expression name column ought to shrink to fit the content.

**Comment by DiegoScirra** [comment] 2017-08-30 14:14
Should be fixed in r52. But it's hard to tell since I wasn't able to reproduce it.

**Comment by AshleyScirra** [comment] 2017-08-31 11:10
r52 is out, please verify it works as expected.

**Comment by mOOnpunk** [comment] 2017-08-31 15:31
Working now.

**Comment by AshleyScirra** [comment] 2017-08-31 15:47
Great, thanks for confirming.

**Closed by AshleyScirra** 2017-08-31 15:47 UTC
