### ISSUE TITLE
Error on preview creating an object containing two effects replace color

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#3924] opened 2020-06-06 22:21 UTC
## Problem description
Error on preview creating an object containing two effects replace color. 
Error in Chrome's console. 
The game's execution is "freezed" not displaying objects in the layout.

## Attach a .c3p

https://kyatric.com/c3/bugs/2020.06.07.bug.create.replace.color.c3p

## Steps to reproduce

1. Preview
2. Open Chrome's console

## Observed result

The game does not execute.

Uncaught (in promise) ReferenceError: ctx is not defined
    at C3.Plugins.Sprite.Instance.GetCurrentSurfaceSize (sdkInstanceBase.js:1)
    at C3.Instance.GetCurrentSurfaceSize (instance.js:1)
    at f (renderEffectChain.js:1)
    at Function.C3.RenderEffectChain (renderEffectChain.js:1)
    at C3.Layer._DrawInstanceWithEffects (layer.js:1)
    at C3.Layer._DrawInstanceWithEffectsAndRestore (layer.js:1)
    at C3.Layer._DrawInstances (layer.js:1)
    at C3.Layer.Draw (layer.js:1)
    at C3.Layout.Draw (layout.js:1)
    at C3.Runtime.Render (runtime.js:1)

In chrome's console.

## Expected result

To execute as intended, no error in console.

## More details

Removing one of the two replace color effects have the preview working as intended.

**Affected browsers/platforms:** Chrome

**First affected release:** r202

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 83.0.4103.97
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
C3 release: r202 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 117 gb
Storage usage (approx): 1.2 gb (1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2020-06-08 09:38
Duplicate of #3911. This should be fixed for the next beta.

**Closed by DiegoScirra** 2020-06-08 09:38 UTC
