### ISSUE TITLE
Crash while adding instance variables (sometimes)

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#377] opened 2017-05-27 13:00 UTC
## Problem description

I added a string instance variable called "URL" to a text and a sprite object and then C3 crashed.

## Attach a .c3p

Not able to reproduce in example yet!

## Steps to reproduce

1. Click on sprite/text
2. add instance variable ("URL")
3. set to type String
4. Click OK

## Observed result

I got a crash but it happened only very rarely so far. But it seems it happens always when editing instance var.

## Expected result

no crash :)

## Affected browsers

Chrom Editor

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: name already in object class namespace @ Error: name already in object class namespace at ie.ǃBpB (https://editor.construct.net/r31/main.js:61:154678) at re.ǃLZ.then.Be (https://editor.construct.net/r31/main.js:149:24000) at 
Stack: Error: name already in object class namespace at ie.ǃBpB (https://editor.construct.net/r31/main.js:61:154678) at re.ǃLZ.then.Be (https://editor.construct.net/r31/main.js:149:24000) at 
Construct 3 version: r31
URL: https://editor.construct.net/index.html
Date: Sat May 27 2017 14:55:30 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 367.9 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r31

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment] 2017-05-29 13:13
Can't reproduce from following your steps in a new project. We usually can't fix bugs without steps to reproduce.

The error message suggests you're creating a name collision (e.g. naming an instance variable the same as a behavior or expression, so Object.Expression becomes ambiguous). Does that help narrow down what's causing this?

**Comment by TheBl4ckSh33p** [comment] 2017-05-31 15:02
I use "ID" and "URL" as instance bars very often. So I can use new instances with different Id instead of 30 text objects. It happened a few times when I added "URL" as instance bar to a text and a sprite.

**Comment by TheBl4ckSh33p** [comment] 2017-05-31 15:02
Bar = Var

**Comment by AshleyScirra** [comment] 2017-05-31 15:52
I will still need reliable steps to reproduce to be able to do anything about this.

**Comment by TheBl4ckSh33p** [comment] 2017-06-02 19:19
Only happend twice so far. I will try to reproduce it to post more details when it happens again.

**Comment by AshleyScirra** [comment] 2017-06-20 12:56
Had needinfo tag for over 2 weeks but no new details so closing.

Issue #531 sounded similar, so I suspect there really is a problem here, but until it can be narrowed down with steps to reproduce we probably won't be able to fix it.

**Closed by AshleyScirra** 2017-06-20 12:56 UTC
Labels: can't reproduce
