### ISSUE TITLE
MobileAdvert GDPR consent form not working on IOS

### ISSUE THREAD

**Issue by Qalamar** [Scirra/Construct-3-bugs#1780] opened 2018-07-08 16:47 UTC
## Problem description

It has been weeks since the last update on this, so I have been instructed to fill an issue here.
The GDPR consent form with Mobile Advert plugin is still not working on IOS. 
Is this being worked on?

## Steps to reproduce

1. Create a project with the MobileAdvert plugin
2. Configure the consent form
3. Test the project on IOS

## Observed result

No pop-up

## Expected result

A pop-up 

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by KENYONBcom** [comment] 2018-08-05 00:12
in addition to getting this working, it would be nice if we could have two inputs for App ID, one for Android and one for iOS. As it stands now, you can only enter one in the plugin settings. and the plugin doesn't work using only configure events.
Also, it would be nice to be able to show this to anyone regardless of only EU users. Pretty soon California and others will follow suit.

**Comment by shortercode** [comment] 2018-08-07 10:58
@KENYONBcom thanks for the suggestions, I'm implementing this at the moment along with advanced testing options so I will consider those additions.

**Comment by shortercode** [comment] 2018-08-07 12:40
@Qalamar yes it's being worked on, there has been an incompatability issue with the user consent SDK that Google has provided for iOS. I've given up waiting for the issue to be resolved and I'm now working the SDK directly into our plugin, had it working yesterday so it's looking promising.

**Comment by KENYONBcom** [comment] 2018-08-08 00:15
@shortercode thanks for the update and can't wait to see the extra options.

**Comment by shortercode** [comment] 2018-08-08 10:00
@dawuwu That is a little more complicated, but I might be able to get it to work.

**Comment by dawuwu** [comment] 2018-08-08 10:18
@shortercode 
Can I help you somehow? I Have some experience with the admob sdk and already tried to turn the official MobileAdvert Plugin into a c3addon with more options. Unfortunately community plugins don't have access to load depencies like android/ios admob sdk

**Comment by shortercode** [comment] 2018-08-08 10:37
Thanks for the offer @dawuwu but it's not a technical limitation, I just mean that it requires more changes than the suggestions @KENYONBcom requested.

Community plugins do have access to loading external SDKs. It's perfectly possible to build a addon with the same functionality as the current mobile advert plugin as a community addon. 

You can specify cordova plugins as dependencies to c3addon, although quite a few developers seem to have missed that part of the documentation. In addition to specifying them as a dependency if you want it to work with our build service the cordova plugin must be on our whitelist. You can file an issue on this tracker to request a plugin to be added to the whitelist.

**Comment by dawuwu** [comment] 2018-08-08 11:18
@shortercode Thanks for the clarification, your facebook support said that's not possible

**Comment by shortercode** [comment] 2018-08-08 11:33
The documentation is [here](https://www.construct.net/make-games/manuals/addon-sdk/reference/specifying-dependencies). I expect what support was referring to was that the source for our plugins are not published, and we strongly advise that people do not attempt to fork them. It has previously caused issues when people have made use of undocumented APIs, and public usage is not something we make an effort to support. 

I would advise strongly that if you want to implement your own advertisement plugin that you go about implementing the code yourself.

**Comment by shortercode** [comment] 2018-08-17 17:37
Hey everyone, got an update for you. Despite the quiet I have been hard at work on this, I still want to review it one last time before I rubber stamp it but I think we should be good to publish in the next release!

**Comment by theBdrive** [comment] 2018-08-18 14:26
@shortercode Will the fix for adverts not loading be live on next release as well?

**Comment by AshleyScirra** [comment] 2018-08-21 15:15
@shortercode should this be working as of r114 now?

**Comment by shortercode** [comment] 2018-08-21 15:35
Yes should be working in r114

**Comment by AshleyScirra** [comment] 2018-08-21 16:06
Let's get confirmation from a user and then close the issue

**Comment by theBdrive** [comment] 2018-08-21 19:04
@AshleyScirra @shortercode The consent form is not working for me in r114.

**Comment by shortercode** [comment] 2018-08-22 10:33
@theBdrive is your configuration succeeding?

**Comment by shortercode** [comment] 2018-08-22 15:32
OnConfigurationComplete should be triggering, but if your using specifying your configuration via the plugins properties it's most likely completing it's configuration before the game has loaded, hence the callback doesn't fire. Maybe I should fire the event on load if it's already completed.

It's odd that the configuration is complete but the dialog hasn't shown... On the admob console have you set a custom provider list?

**Comment by Bootfit** [comment] 2018-08-22 15:50
Just dropping this in here to hopefully help you out - but the consent form now works fine on my iOS/Xcode build in r114. The live banners however still don't appear in iOS though.

Same build/event sheet layout etc works fine on Android.

**Comment by shortercode** [comment] 2018-08-22 16:03
@Bootfit I'm glad it's working for someone. I'm also seeing the issue with the banner view, I'm not quite sure what the issue is. Admob is returning a "no ad" error, which is typically vague. Are you testing on the simulator or a device?

**Comment by Bootfit** [comment] 2018-08-22 16:07
I've tested on both. The consent form displays on both the simulator and the iPhone and the banner displays on neither.

**Comment by shortercode** [comment] 2018-08-22 16:09
Well... I've just come back to my banner advert today and it's now working. I don't think I've changed anything.

**Comment by Bootfit** [comment] 2018-08-22 16:11
Can you share a screengrab or .c3p of your working event sheet or the stripped down relevant parts? It maybe we're just configuring things in the wrong way.

**Comment by Bootfit** [comment] 2018-08-22 16:43
I've just added my Ad values and exported etc - none of the banners etc display. Just get Banner Failed and Interstital Failed when I press the buttons.

Create banner button:
PERSONALIZED
Banner advert failed to show

Create Interstitial button:
PERSONALIZED
Request Error: No ad to show.

**Comment by KENYONBcom** [comment] 2018-08-22 16:59
@theBdrive I don't think GPS spoofing works to trigger the Consent Dialog. I've had people in the EU confirm it works in my Android game, but I tried spoofing on my device and it wouldn't trigger. Admob knew I was in the US because I couldn't spoof my WiFi or data connection location... Which is what I'm assuming Admob uses to get location instead of GPS? @shortercode do you know?

**Comment by shortercode** [comment] 2018-08-22 17:09
@Bootfit sounds like either the unit IDs are invalid or the advert unit itself is broken. When you inputted the unit IDs did you just set the global vars or did you edit the event on line 1 as well?

@KENYONBcom I'm not sure what they use to get the location to be honest, the SDK provides a method called "isRequestLocationInEeaOrUnknown". It's not listed in the documentation how it figures it out.

**Comment by Bootfit** [comment] 2018-08-22 17:26
@shortercode I've just created new Ad IDs and entered them in both the global variables and in line 1 also - still not working.

**Comment by shortercode** [comment] 2018-08-22 17:27
@Bootfit new ad units can take several hours to start working :/ I'm fairly sure the reason why my unit wasn't working on monday was that I'd created it that day

**Comment by KENYONBcom** [comment] 2018-08-22 17:37
@shortercode wow, really surprised they don't offer details in what exactly triggers in EU. 

And thanks for adding all the bonus features I requested earlier. 👍

Since you added the Application ID for both iOS and Android under the Object Type Properties, do we still need to configure as an event for each platform?
eg: System > is on platform Android > Mobile Advert > Configure App ID

This is how I was (still) configuring before you added App ID in Object Type Properties.

**Comment by theBdrive** [comment] 2018-08-22 23:15
@shortercode I am specifying the plugin properties via both the plugin properties and with the Configure condition, probably overkill ha. ConsentStatus I guess is set to whatever is default without ever actually setting it, personalized or unknown I would assume?

You were right about one thing, I did not have a custom provider list specified in Admob console. So I set the custom provider list up, but I still get no consent dialog on first run of game, nor on a user input condition, ie touch object>show consent dialog. I tried setting locations to show to both everywhere & inside EU with the EU spoofing on(I'm in the US) and neither work. @KENYONBcom is also saying this spoofing option doesn't work either? So I'm still stuck on getting consent to work until this spoofing option works I guess.

Good/weird news is after switching from commonly used provider to custom provider now the reward ads all the sudden start loading again. So with common providers selected, interstitial ads load but reward ads will not load, but with custom providers selected both interstitial and reward ads load. Not sure why it's doing this, common providers should still be able to load ads, they were loading fine before r111.

Side note in regard to your comment to @Bootfit about ad units taking awhile to start working. In my with Admob, ad units have always starting working right after(10 minutes?) creating them in the Admob console.

**Comment by KENYONBcom** [comment] 2018-08-22 23:45
@theBdrive @shortercode I finally got a chance to test the latest plugin in C3 r114. I changed the Advert properties to show the Consent Dialog to everyone and exported the signed APK and tested on my device but no Consent Dialog showed. Is this because I have already allowed personalized ads by default of not ever seeing a consent dialog? or should it show anyway? I tried uninstalling and then reinstalling instead of just updating, but still not showing.

**Comment by Bootfit** [comment] 2018-08-22 23:56
@theBdrive @KENYONBcom @shortercode 

OK - I've just managed to get live interstitial ads working on iOS for the first time.

Download the attached file and change the Add Unit IDs in the event sheet plus the Application and Publisher IDs in the Mobile Advert properties to your own.

Note I've not used 'configure' anything in the events sheet, and I've not used 'show Interstitial' as I have been in the past - just simply 'create INTERSTITIAL show:True'. The attached file also automatically launched the Consent Dialogue box (set to EU and Unknown as I'm in the UK).

Does this work for anyone else?

I've also tried the same setup for live banners but they still fail to load.

[AD TEST.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2312345/AD.TEST.c3p.zip)

**Comment by Bootfit** [comment] 2018-08-24 10:04
Anyone managed to get footer banners to display yet?

**Comment by Bootfit** [comment] 2018-08-24 15:51
Folks - don't know if this will help at all, but I've just managed to get both footer banners and interstitials to appear on iOS.

Set up your App ID, Publisher ID etc in the MobileAdvert properties. On start up **configure** your ads and then **create** them wherever you need them within your app.

**But the issue that prevents the banners appearing is in the phone itself.**
In your iPhone go to Settings > Privacy > Advertising > Limit Ad Tracking - turn this to **OFF**.

Your ads should load now.

**Comment by theBdrive** [comment] 2018-08-24 16:26
@Bootfit Limit Ad Tracking is turned OFF by default on all iOS devices already.

**Comment by QuasarX** [comment] 2018-08-26 11:29
@shortercode 
I was tried your Test Project on my Android phone. Everythink broken.
Banner, Interstitial, Video and Consent Dialog not work.

I get this error. (Ex. Banner)
> banner ad failed to load

Show Consent

> Error: request is not in EEA or unknown

I was double check all IDs.

**Comment by Bootfit** [comment] 2018-08-26 12:06
I don’t know what’s going on with this at all. I had it working on Friday - both banners and interstitials working. Then after I stopped celebrating I started the app again after 10 minutes and suddenly there are no adverts.

Spent Saturday trying to get them working again to no avail - nothing, no ads. Opened the app this morning and the ads are back. Then opened the app later on and they’re gone again. WTF?

**Comment by theBdrive** [comment] 2018-08-26 15:30
Interstitial ads and reward ads are still working fine for me on r114. A few things I noticed about loading ads, this was happening before there were problems with ads loading, so pre r111. I load ads on my splash screen with

On Start Layout>MobileAdvert>Configure
MobileAdvert>Is Configured Create Interstial: show false, Create reward: show false

Interstitials always load fine, but at least 50% of the time reward ads fail to load, it's really hit or miss. As a fix I just added

MobileAdvert>Video is not loaded>Trig once>Create reward: show false

to the layouts where reward ads can be shown, in case the reward ads fail to load on the splash screen. Then ads are just shown with MobileAdvert>Show "whatever type of ad". I have no idea what is causing reward ads to intermittently load, but checking if they have loaded on each layout fixed that problem for me.

@QuasarX Do you have a custom provider list set in Admob? Ads would not display for me until I had that set.

**Comment by QuasarX** [comment] 2018-08-26 16:05
@theBdrive 
I'm using default settings
![image](https://user-images.githubusercontent.com/13033837/44630234-0412d680-a963-11e8-8e3d-c303d0a78024.png)

**Comment by theBdrive** [comment] 2018-08-26 17:01
@QuasarX I just told you ads would not display without custom providers, and you posted a screenshot showing you are not using custom providers.

**Comment by QuasarX** [comment] 2018-08-26 17:42
@theBdrive 
I used now "Custom set of ad technology providers" option. It is not works too.

**Comment by QuasarX** [comment] 2018-08-26 19:53
@shortercode Idk what happened. I didn't change anythink on apk.
**Banner** and **Interstitial ads** working now.
**Video** and **User Consent Dialog** still not work.

**Comment by Bootfit** [comment] 2018-08-27 16:11
In regards to the custom set of EU add providers, how many are you allowed to choose? I read somewhere you're only allowed 12 but it gives you the option to choose more than that.

**Comment by Bootfit** [comment] 2018-08-28 01:45
Been trying to get this to work all day. I created a small project that the user consent/config worked fine on, I then set up two looped events to call a banner ad and an interstitial add and display the ads once they'd successfully loaded - I managed to clock up over 6000 automated separate ad requests before I cancelled it - no ads were successfully loaded.

In the AdMob EU settings I have all 709 custom ad providers selected, so I don't think it's a lack of ads or low fill rate thats an issue here.

I've created another small project that displays the consent dialogue on start up and configures the ads. There are 4 buttons: create/show banner ads and create/show interstitial ads. Neither banner ads nor interstitial ads load/display unless _very occasionally_ you rapidly and continually press the Load Interstitial button, 1/100 you'll get a loaded banner. I've attached that project - see if anyone else manages to successfully launch the consent form/configure/load ads - just add your own app/pub IDs.

[ADDTESTNEW.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2326174/ADDTESTNEW.c3p.zip)

**Comment by theBdrive** [comment] 2018-08-28 16:41
@Bootfit "No ad to show" means C3 is requesting an ad but there is literally no ad to show. Some possible reasons you are getting this error

1. Limit Ad Tracking is turned ON on your test device
2. You did not enter your ad unit ID exactly as shown in the Admob console
3. You have not added any payment information to your Admob account.

I have reward and interstitial  ads working in 4 different games since r114 released, I have a feeling your issues are more likely user error and not a C3 bug.

**Comment by Bootfit** [comment] 2018-08-28 17:20
@theBdrive 
1. Limit Ad Tracking is turned off
2. the ad unit ID is copy/pasted from Admob - the ads do load occasionally - but I'm talking 1 time out of 100 so the correct data is going back and forth
3. You can't add payment info to Admob until you're over the £100 earning threshold.

If your banners are working in your iOS apps would you consider uploading a screengrab showing how you've implemented them? Obviously obscure your app IDs etc.

**Comment by theBdrive** [comment] 2018-08-28 17:49
@Bootfit 

"You can't add payment info to Admob until you're over the £100 earning threshold."

100% incorrect. You shouldn't be seeing any ads until your payment info is added to you account, same as any other ad provider, adding payment info and/or tax info depending on where you live is required before you can use the services. I had to do this myself years ago when I started my Admob account, this question has been answered hundreds of times on the Google product forums and stackoverflow. "My ads don't show, no ad to show error message.", the fix? ADD PAYMENT INFO. I think the few times you have seen an add was a fluke because you were sending so many requests over and over.

"If your banners are working in your iOS apps would you consider uploading a screengrab showing how you've implemented them?"

This is like the 3rd time you have asked me about banners, and again I will say I don't use banners in my games. I only use interstitials and reward ads. 8 posts above this one I typed out the events I'm using for ads.

**Comment by shortercode** [comment] 2018-08-30 12:30
I will need a reporter to talk with about each issue, so can the following people please open an issue for me:

@KENYONBcom location spoofing
@theBdrive user consent outside of the EEA

anyone else who has a **specific issue** can you please open an issue, one issue per problem please.

**Comment by shortercode** [comment] 2018-08-30 12:41
To answer some of the loose questions I've seen:

- If you've provided all the addon properties the plugin will do an "automatic" configuration as your game starts up, so you do not need to call the configure action.

- The user consent dialog requires you to have 12 or less ad providers ( custom set ).

- The user consent dialog should remember what a users consent is across runs, I believe uninstalling the app will reset this.

- `No ad to show` is an admob error, literally meaning they didn't send you an advert. The reason varies, but it's hard to pin down why.

- The default state of UserConsent is `unknown`, in this state it is impossible to show ads. Being outside the EU should set it to `personalised`. 

- The UserConsent state can be checked using an expression, and set using an action.

**Comment by QuasarX** [comment] 2018-08-31 18:41
@shortercode 

I have this;
1. Empty addon properties.
2. Custom set providers ( on admob, 12 providers )
3. Signed apk uploaded on Developer Console
4. Installed on Googleplay

Not work
--------------------------------
Actions
--------------------------------
**Configure**

Conditions
--------------------------------
**On configuration complete
On configuration failed**

When I click **"Configure"** or **"Show Consent"**, I'm getting this error.

> Error: request is not in EEA or unknown

Working
--------------------------------
**Banner, Interstitial, Video**

**Tested on Android 6.0.1**

**Test Project** (I edit your project)
[TEST-GDPR.zip](https://github.com/Scirra/Construct-3-bugs/files/2341177/TEST-GDPR.zip)

**Comment by KENYONBcom** [comment] 2018-09-02 17:43
@shortercode I opened a new bug report regarding Location and Spoofing settings. Neither one works for me outside the EU.
https://github.com/Scirra/Construct-3-bugs/issues/1975

**Comment by shortercode** [comment] 2018-09-04 13:18
@QuasarX I've discovered that the "show everywhere" option is currently broken, the user consent SDK is blocking attempts to show the dialog outside of the EU with the error you posted. I've filed a bug with the admob team responsible for the user consent SDK but I'm not hopeful about a quick resolution, and they may just close it as a won't fix.

**Comment by shortercode** [comment] 2018-09-18 15:40
Okay so just to update this thread. 

I have closed the issue about location spoofing not working. If you cannot get it to work please **ensure that you have test mode enabled**. Location spoofing is a test only feature.

Additionally in the latest release "show everywhere" will behave as "show EU and unknown". As it caused a configuration error. Depending on how Google respond to the issue I filed I will either enable it's original behaviour again or remove the feature at some point in the future.

As a reminder  **during development you should avoid loading adverts with test mode disabled, if you load too many admob may decide that you are abusing their service and disable your account!** you are given some leeway for ensuring live adverts work, but they advise you not to click on live ads.

I don't believe their are any tracking bugs on this issue anymore so I'm going to close it. Thanks everyone for your help, and good luck with your games!

**Closed by shortercode** 2018-09-18 15:40 UTC

**Comment by Evilobjective** [comment] 2019-03-29 02:47
Is this issue (iOS GDPR Consent Form) confirmed to be fixed? I just ran an iOS and Android build and triggering the consent dialogue works correctly on Android but does not work on iOS. Not sure you want a duplicate bug report, but I'll file a new one if it's easier to track.
