### ISSUE TITLE
(Mobile C3 Android Chrome)  C3 reloads without warning after back tabbing from editor.

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#3294] opened 2019-09-03 16:51 UTC
## Problem description

On mobile.  Android 8.1  - Chrome. 76  -  C3  164
Back-tab chrome minimization causes C3 to restart losing unsaved work.

## Attach a .c3p

Use a new project from the mobile c3 start screen

## Steps to reproduce

Open an new project.
Add sprite object and place default sprite into layout.
Open the sprite editor
Click on fill icon to open the color picker.
On the android home/navigation bar press the back tab (triangle arrow) a few times usually 3 to 5 times.
Android will eventually "minimise" chrome and show the desktop/home screen.
Press the open apps button (square) on the home/navigation bar
In the cascade (if more than one) of open apps you will see it looks like Chrome is still open with Construct 3 project still available.
Click on the C3 project.
Chrome will Maximise the 3C tab.

## Observed result

C3 will restart losing all unsaved work.

## Expected result

C3 does not restart in this scenario or minimizing by repeatedly pressing back button is blocked.

## System details

<details><summary>View details</summary>

Android 8.1 .
Chrome. 76 
C3  164

</details>

**Comment by AshleyScirra** [comment] 2019-09-03 17:14
> On the android home/navigation bar press the back tab (triangle arrow) a few times usually 3 to 5 times.

At this point I get a "Leave site?" prompt which says "Changes that you made may not be saved." Are you pressing "Leave" here? If so the rest of your steps are the expected result. If not then you should remain in C3.

**Comment by NetOneGames** [comment] 2019-09-04 08:20
Hmm.  OK  I tried on my daughter's phone (Moto G5) and do indeed get the leave warning.  That is good to see.  However I am not getting the warning on my main personal phone (Cubot Power). ive double checked the version (164) as I know this was an issue in the past that was resolved.  I will do some digging to try to figure out what is different on my phone.  Is there any chrome settings or other that would prevent / ignore / block that leave warning??? (i dont have any add ons or pop up blockers as far as I know. just vanilla chrome).

**Comment by NetOneGames** [comment] 2019-09-04 08:37
Ok a small update  if this helps.

If I open 164 using the "Launch R164" link from the Construct website. Make a new project, verifying version is 164 under "about".  go through the above operations.  I do not get any warning when back tabbing out of the site and C3 resets on revisiting C3.

But...  If I go to an old version,  say 146,  wait for the update available dialog, then update to 164, go through the operations above then I do indeed get the warnings.

If I close everything.  Go back to the latest releases website link for 164, open than Im back to no warning when  back tabbing out.

**Comment by NetOneGames** [comment] 2019-09-29 10:18
I still have this issue, in fact it occurs when back tabbing out of any pop up.  I will try to get around to do a video just to show.   

I find there are also other issues with the mobile version that prevent it being used at a basic level, like pop ups not showing up and text boxes being squashed out of view.  I will try to raise in coming weeks.

**Comment by AshleyScirra** [comment] 2019-11-05 17:36
This is really awkward to deal with - we don't get a simple "back" event when you press the back button, instead we have to deal with a weird concoction involving the history API, which also seems pretty buggy. So it's hard to get right. I made some changes which seem to help for the next release. It works for me locally but let's check again after the next release to verify it works for you too.

**Comment by AshleyScirra** [comment] 2019-11-11 14:04
@NetOneGames r175 is out now, is it working correctly for you there?

**Comment by NetOneGames** [comment] 2019-11-12 14:32
Ok, just based a brief play around.

So in some situations I am getting the popup about pressing back again.  In this situation it is still very easy to multiple press the back button and miss the popup and thus close construct without saving.  (also just to note the phrase "Go back" feels a little like the intent could be to go back to the editor.

In other  situations I am getting the "Leave Site" Dialog.  Which truly prevents me from leaving without confirming. 

edit  (In fact now , after some time, this Leave Site dialog is the only message I am getting no matter what I am trying to quit out of with the back button. I am not seeing the "pressing back" dialog again?

will test a bit more later.

**Comment by AshleyScirra** [comment] 2019-11-12 16:38
It only shows a prompt in certain circumstances, such as if a project with unsaved changes is open. If you do not have anything open it will allow back to navigate normally. However if something like a dialog is open, pressing back should close it. I briefly tested it and it appears to be working as it's designed to now, but it would be good to have confirmation from your side.

**Comment by NetOneGames** [comment] 2019-11-13 16:32
Ok, as far as I tested, 
the "Back Navigation" (Go Back /  Stay) box will always appear before backing out of construct.

However , although the warning is consistent, which is good, there are still a number of issues.

(1) the warning  does not block further use of the back button so backing out apparently cannot be prevented? thus is it is super easy to just unintentionally multiple back tab past the warning it and get the reset issue. 

(2) If I am in a "parameters" dialog/form it pressing back does not close the dialog,  instead it backtracks through the action boxes hierarchy even if they were not previously opened.   This will encourage the multi back button pressing behaviors which is still so dangerous as per mentioned in 

(3) if a pullout side tab was open it back-tab will close it but then pressing either stay or go back results in the side tab re-opening.

(4) In many situations I have made unsaved changes and do get not leaving site warning.

It is good to have a warning now even if it can be easily missed.

but the real issue, the issue that Construct is resetting when returning from background  can this not be solved?
Is there no possibility to save state on minimize/go to background? Then reload when the windowed app is clicked again?

Eg locking phone sends apps into backgroiund including construct which again causes reset on clicking to bring back.  Is this impossible to prevent?

**Comment by AshleyScirra** [comment] 2019-11-14 17:05
> the warning does not block further use of the back button

I don't think we can prevent this since blocking the back button completely is something abusive sites would do to prevent you leaving, and browsers generally put in restrictions to avoid such abuse.

> If I am in a "parameters" dialog/form it pressing back does not close the dialog, instead it backtracks through the action boxes hierarchy

This is currently by design: if a dialog with a 'Back' button is showing, pressing the device back button activates that button. It still gets you out of the dialog if you press it 3 times.

> if a pullout side tab was open it back-tab will close it but then pressing either stay or go back results in the side tab re-opening.

I can reproduce, fixed that for the next release.

> In many situations I have made unsaved changes and do not get leaving site warning.

I cannot reproduce any such cases. I need full steps to reproduce the problem to be able to investigate.

> but the real issue, the issue that Construct is resetting when returning from background can this not be solved?

This appears to be unrelated to this issue, but I can't reproduce this either, I can still use C3 just fine after switching tabs or apps. It's possible if the device runs out of memory it could evict background apps, but I don't think there's any way it could save your project when that happens. Using autosave should help here.

There doesn't appear to be any further action to take on this issue as filed, so closing.

**Closed by AshleyScirra** 2019-11-14 17:05 UTC
Labels: Android, difficult
