### ISSUE TITLE
9Patch BUG on C3 runtime

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#2009] opened 2018-09-06 23:20 UTC
## Problem description

In the Preview, only the corner of the 9patch is properly displayed on C3 runtime.

## Attach a .c3p

[9patch_BUG.zip](https://github.com/Scirra/Construct-3-bugs/files/2359023/9patch_BUG.zip)

## Steps to reproduce

1. Open 9Patch_BUG.C3P
2. Choose C3 Runtime
3. F4

## Observed result

Only the corner of the 9patch is properly displayed

## Expected result

9patch properly displayed on C3 runtime.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2018-09-07 16:31
Note to self: looks like it involves OffscreenCanvas.transferToImageBitmap() prior to WebGL texture upload.

**Comment by AshleyScirra** [comment] 2018-09-07 16:48
Turns out it was caused by a weird quirk of a workaround to a missing OffscreenCanvas feature in current stable version of Chrome. Found a workaround that works, should be fixed in next release.

**Closed by AshleyScirra** 2018-09-07 16:48 UTC
Labels: c3runtime
