### ISSUE TITLE
Ctrl+mouse zooms browser instead layout

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1396] opened 2018-03-17 14:32 UTC
## Problem description

Ctrl+mouse wheel zooms browser instead layout

## Attach a .c3p

None

## Steps to reproduce

1.Open layout or any place within C3
2.Scroll mouse and during it click Ctrl.
3.Browser zooms  instead layout.

## Observed result

*Often triggers browser zoom what is kinda annoying to get back.

## Expected result

*Nothing, zooms layout  or if not on layout zooms browser, but as it only works scroll+ctrl then at first when it happened it took some time to get zoom lvl back to normal.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment] 2018-03-19 11:17
We specifically block Ctrl+Mousewheel from changing the browser zoom. As expected, I can open Chrome and Ctrl+Mousewheel anywhere in the UI and it never changes the browser zoom. Can you provide any more information on how to reproduce the issue? Have you tried disabling browser addons?

**Comment by AshleyScirra** [comment] 2018-03-19 11:28
It only appears to reproduce if you are already scrolling the mousewheel and then press control - if you're holding control first it appears to reliably prevent the browser zoom. This looks like a Chrome bug so I've filed it here: https://bugs.chromium.org/p/chromium/issues/detail?id=823247
Closing this issue and will follow up there.

**Closed by AshleyScirra** 2018-03-19 11:28 UTC
Labels: browser, chrome, external

**Comment by shortercode** [comment] 2018-04-17 11:08
On chrome a little magnifying glass appears in the address bar when your not at 100%, if you click it then a small dialog with a "reset" button appears.
