### ISSUE TITLE
Drawing Canvas 'line' will not draw horizontal or vertical lines

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-3-bugs#2237] opened 2018-11-03 07:30 UTC
## Problem description

Drawing Canvas 'line' will not draw horizontal or vertical lines.

## Attach a .c3p

[CanvasLineTest.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2544709/CanvasLineTest.c3p.zip)

## Steps to reproduce

1. Run project
2. Lines will draw to each node
3. Vertical/horizontal lines do not show up on canvas

## Observed result

- Lines will draw to each node
- Vertical/horizontal lines do not show up on canvas

## Expected result

- Vertical/horizontal lines to show up on canvas

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

MacOS
r123-2

<details><summary>View details</summary>
</details>

**Comment by AshleyScirra** [comment] 2018-11-03 15:33
Duplicate of #2213

**Closed by AshleyScirra** 2018-11-03 15:33 UTC
