### ISSUE TITLE
When opening files from the cloud when i wrote my password wrong it doesn't let me type my password again it just says failed

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#3193] opened 2019-08-05 23:57 UTC
## Problem description
when i tried to open my project and mistyped my password, it shows this 

![image](https://user-images.githubusercontent.com/32940085/62501881-add92500-b7ba-11e9-8a9c-bdf61195d060.png)
and I can't acess my files or find any way to correctly enter my password

## Steps to reproduce

1. open construct 3
2. press cloud at the top right-ish
3. when bring prompted for your password, type it wrong

## Observed result
failed to refresh file list
![image](https://user-images.githubusercontent.com/32940085/62501931-f55fb100-b7ba-11e9-8d7c-26dee5943d5d.png)

## Expected result
some error that lets me try my password again or clear cookies so i can try again or soemthing, not being locked out of my files

## More details

I tried this on the desktop beta version 159 and I'm not willing to try it on other platforms as it might lock me further from my files and it would be really inconvenient to not being able to access them anymore

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.33.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@032b3ca19e9af20182f9bd03deefc0faf4695558) NWjs/0.33.0 (like Chrome/69.0.3497.81)
C3 release: r159 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 45 gb
Storage usage (approx): 51 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2019-08-20 14:02
The popup doesn't close for me if the password is typed incorrectly, it just shows a message under the password box saying "Wrong password. Try again or click Forgot password to reset it.".

Doesn't it just show you the popup when you close and reopen the dialog? Or how about when you click the dialogs "refresh current folder" button?

**Comment by eleanorawesome** [comment] 2019-08-23 18:15
it does this https://puu.sh/E8G0t/d91f736446.mp4

**Comment by AshleyScirra** [comment] 2019-08-27 11:02
Note that video shows a profile error in NW.js, which indicates you've downgraded from a newer NW.js version. I think that means the storage format is incompatible and so NW.js is unable to access storage any more, which could well cause this issue. You probably need to clear all your storage from AppData/Local/construct3 and retry.

**Comment by shortercode** [comment] 2019-08-27 11:23
It's interesting that the popup closes immediately, I expect the Google login page is failing for some reason ( likely the profile issue as Ashley suggests ).

I believe our login code is actually behaving as expected here, it's invalidated the access token and requested a new one. But because the login page fails to return a token the attempt to show the files is cancelled. The correct behaviour isn't very useful, but given the situation it cannot do any better.

**Comment by AshleyScirra** [comment] 2019-08-27 11:59
I think the best thing to do is close this issue and only investigate if it can be reproduced without an NW.js profile error occurring along the way.

**Closed by AshleyScirra** 2019-08-27 11:59 UTC
Labels: can't reproduce
