### ISSUE TITLE
Mobile IAP triggers success and failure at the same time in iOS

### ISSUE THREAD

**Issue by vundurty** [Scirra/Construct-3-bugs#6390] opened 2023-01-12 19:38 UTC
## Problem description

1. I'm using Mobile IAP for iOS Consumables
2. After the purchase, I'm receiving purchase success and purchase failure
3. This has never happened before. I'm not sure what could be the reason for this issue.

Requesting you to check if this is the plugin issue.

## Attach a .c3p

[Firebase_2 (1).zip](https://github.com/Scirra/Construct-3-bugs/files/10405360/Firebase_2.1.zip)

## Steps to reproduce

1. Export to iOS
2. Deploy to testflight
3. Open the app in testflight
4. Click buy after you see "Store Registration Success" message on the screen
5. You will be asked to purchase the product. Do it
6. After a moment, you will get purchase success trigger and after clicking 'Ok', you will get the purchase failed trigger

## Observed result

After the purchase, I'm receiving both purchase success and purchase failure triggers

Added a video for your reference
https://user-images.githubusercontent.com/22640025/212164182-0986b841-72e1-49f4-a12d-f12374377185.mp4

## Expected result

After the purchase, I should receive on purchase success

## More details

iOS app

**Affected browsers/platforms:** 
None

**First affected release:** 
I'm not sure since which version

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r317.2 (stable)
Browser: Chrome 109.0.5414.74
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 240 gb
Storage usage (approx): 75 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Laptop GPU Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2023-01-16 13:17
It looks like Construct's IAP plugin actually triggers "On purchase failure" when any IAP error occurs. Construct itself doesn't do any IAP logic, it just uses `cordova-plugin-purchase` to do everything and fires triggers based on the results of that plugin.

I suspect this is a store configuration problem which is set up on your end (especially since AFAIK it's working fine for everyone else). What does the `ErrorMessage` expression say for you? More detailed error messages are also logged to the console. Can you check for errors in the Xcode log when testing on iOS? Also try double-checking your store configuration is correct and you haven't done something like mix up the wrong product id or product type.

**Comment by vundurty** [comment] 2023-01-17 16:11
Thank you for your response.

Please the Xcode log below. 

[PurchaseFailedErrorLog_1.zip](https://github.com/Scirra/Construct-3-bugs/files/10437024/PurchaseFailedErrorLog_1.zip)

Let me know if you need any further information to investigate this better. Thank you.

**Comment by AshleyScirra** [comment] 2023-01-19 12:35
The log includes errors in `sparsha_firebase_firestorebasic`, which appears to be a third party addon. I would guess that is causing the problem. This is also inconsistent with the project you provided, which does not appear to use that addon, so I am not sure where you got this error log from?

I believe the errors in the log you provided arise from a third-party addon, and our bug report guidelines require that you do not use third-party addons when submitting bug reports as we need to eliminate the possibility the problem is caused by the third-party addon. Further, as far as I'm aware, IAP is continuing to work fine for everyone else, and the most common cause of issues is a configuration problem with IAP. So I'm afraid I don't believe there is any action for us to take on this issue, so closing. Please double-check to make sure the IAP configuration is definitely correct and if you have a problem with a third-party addon you'll need to report it to that addon developer.

**Closed by AshleyScirra** 2023-01-19 12:35 UTC
Labels: external
