### ISSUE TITLE
Crash when starting construct 3

### ISSUE THREAD

**Issue by CodeZeek** [Scirra/Construct-3-bugs#141] opened 2017-05-02 19:41 UTC
## Problem description

Construct crashing on startup.

## Attach a .c3p

Not relevant

## Steps to reproduce

1.
2.
3.

## Observed result

Construct crashed on start up.

## Expected result

That it would start up to the start page.

## Affected browsers

* Chrome: yes (incognito)
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: 
Construct 3 version: r23
URL: https://editor.construct.net/
Date: Tue May 02 2017 21:38:08 GMT+0200 (CEST)
Uptime: 1.6 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 6100
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by jaydonteh** [comment] 2017-05-03 07:43
Disable your plug-ins and that's what I did to avoid the unnecessary Javascript error on launch.

**Comment by AshleyScirra** [comment] 2017-05-03 14:56
Assuming this is to do with browser addons, can you isolate which addon is causing the problem? If so we can try and test with it and see if we can work around whatever it's breaking. Otherwise we will just have to close this issue as we are not able to reproduce it.

**Comment by spesknight** [comment] 2017-05-04 10:00
I have same problem with latest Chrome (Version 58.0.3029.96 (64-bit)).
It says OpenGL are not supported, it was working before the upgrade

**Comment by shortercode** [comment] 2017-05-04 10:19
@spesknight this bug report is unrelated to your issue, please try the steps listed on the error message. If that doesn't help then take a look at [this question](https://superuser.com/questions/836832/how-can-i-enable-webgl-in-my-browser).

**Comment by spesknight** [comment] 2017-05-04 11:36
Thanks for the link, the "Override software rendering list" did the trick.
Probably a restart of the pc would also have helped.

**Comment by AshleyScirra** [comment] 2017-05-16 12:45
2 weeks with needinfo label and no response, so closing.

**Closed by AshleyScirra** 2017-05-16 12:45 UTC
Labels: need info, no repro
