### ISSUE TITLE
Particle Preview issue

### ISSUE THREAD

**Issue by Digital-Prophet** [Scirra/Construct-3-bugs#383] opened 2017-05-29 12:55 UTC
## Problem description
There is a particle preview issue.
When you create a new particle effect and click in Preview you see the preview happening but all other Sprites disappears or you see a blue but blank square the size of the sprite.
[test (1).zip](https://github.com/Scirra/Construct-3-bugs/files/1035817/test.1.zip)

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Create a sprite
2. Create a particle object with particles
3. Click Preview in the Previe Properties

## Observed result

When you create a new particle effect and click in Preview you see the preview happening but all other Sprites disappears or you see a blue but blank square the size of the sprite.

## Expected result

*What did you expect to happen instead?*
See a preivew and being able to carry on with my project when I disable preview

## Affected browsers

* Chrome: yes/no

## System details

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_5
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r31

Local storage
Storage quota (approx): 27 gb
Storage usage (approx): 267 mb (1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 650M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2047
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2017-05-29 13:21
Looks like a duplicate of #294

**Closed by AshleyScirra** 2017-05-29 13:21 UTC
