### ISSUE TITLE
Construct 3 r272 + lunarraylitetween-c3runtime-1.0.1-stable Addon = Crash (Screenshot Provided)

### ISSUE THREAD

**Issue by brainwavecreations** [Scirra/Construct-3-bugs#5247] opened 2021-11-17 18:58 UTC
While trying to load Construct 3 version r272, along with Lunarray Liteween 1.0.1 Stable Addon.  Construct 3 crashes with a red screen, with an error.  I've done all browser troubleshooting, and have tested this in Chrome, and Brave browsers, to the same effect.

While trying to load Construct 3 version r272, along with Lunarray Liteween 1.0.1 Stable Addon.  Construct 3 crashes with a red screen, with an error.  I've done all browser troubleshooting, and have tested this in Chrome, and Brave browsers, to the same effect.

I cannot get so far as to even load any of my .c3p files.

## Steps to reproduce

1. Load Construct 3 r272
2. Install lunarraylitetween-c3runtime-1.0.1-stable.addon in Addons Manager
3. Reload Construct 3 r272 for the Addon to take effect
4. See the red screen and error

## Observed result

A red screen, with an error box at the top.  I am adding a screenshot to this issue to show what is happening on my end.

## Expected result

Expected Construct 3 to load as normal, but run the latest version

## More details
I have completely wiped all of my web browsers temporary data, and have tested this in both Chrome, and Brave browsers(latest versions of each)

**Affected browsers/platforms:** 

Windows 10, Chrome, and Brave browsers(latest versions of each), Construct 3 r272

**First affected release:** 

This began with todays release, r272

<details><summary>View details</summary>

All I can share is a screenshot of the issue, explained above.  It does not allow me to click on Menu, to get the "Platform information".

</details>
![litetween 1 0 1 error](https://user-images.githubusercontent.com/94563122/142264739-a9fe822f-4acb-4552-971c-563f71474bc5.png)
[lunarraylitetween-c3runtime-1.0.1-stable.zip](https://github.com/Scirra/Construct-3-bugs/files/7557255/lunarraylitetween-c3runtime-1.0.1-stable.zip)

**Comment by RadioMars** [comment] 2021-11-17 20:03
It's the same with "Easystar.js for tilemap".

**Comment by brushfe** [comment] 2021-11-17 21:13
+1 for the Easystar.js plug-in. Downloading the plug-in [here](https://github.com/erenertugrul/construct-plugins
) and installing it causes the following error:

The C3 message says "TypeError: Expected function", and the console error reads "Uncaught TypeError: BEHAVIOR_CLASS.Register is not a function at blob:https://editor.construct.net/bcc193c8-e0ff-46ee-a723-eef15cdd7933:40"

**Comment by moonbitgames** [comment] 2021-11-17 23:08
+1 for 3DObject addon. r272 crashes on load when addon is installed. Uncaught TypeError: PLUGIN_CLASS.Register is not a function.

**Comment by elfwy-uwu** [comment] 2021-11-18 01:27
It is #5245 

By the way, why not use built-in Tween?

**Comment by dop2000** [comment] 2021-11-18 02:16
> By the way, why not use built-in Tween?

LiteTween was one of the most popular C2 plugins, it's used in lots of old imported projects. Replacing it with Tween in a large game may be an enormous task. 
And, as mentioned, other popular plugins like EasyStarJS also cause this error.

**Comment by elfwy-uwu** [comment] 2021-11-18 02:28
@dop2000 

Oh, i guess it makes sense

Also, seems like all 3rd party addons cause this crash during initialization process

**Comment by chunchuna** [comment] 2021-11-18 06:03
PLUGIN_CLASS and Behavior_CLASS Something went wrong

**Comment by ReviveR200** [comment] 2021-11-18 07:42
Crush with all custom addons: Yandex SDK, VKBridge, GS_AdaptScreen. Uninstall all - work.

**Comment by AshleyScirra** [comment] 2021-11-18 11:34
Duplicate of #5245

**Closed by AshleyScirra** 2021-11-18 11:34 UTC
Labels: duplicate
