### ISSUE TITLE
Duplicating letters when editing expressions

### ISSUE THREAD

**Issue by mfoster98** [Scirra/Construct-3-bugs#364] opened 2017-05-25 22:35 UTC
## Problem description

*When typing in value boxes during adding an event (eg. adding a variable comparison equal to Score) will make it SScScoScorScore just by typing Score on my phone's keyboard. This has happened on more than 1 occasion and makes making games on my phone harder than it has to be.*

## Attach a .c3p

*all new and old projects give me errors*

## Steps to reproduce

1.Create a variable on android mobile
2.Create a variable comparison event and start typing an expression
3.The bug should then occur.

## Observed result

Adding of letters when using expressions and when changing values for events.

## Expected result

I expected to be able to write expressions without it adding any text that I haven't told it to.

## Affected browsers

* Chrome: yes / Zoom 100%
 

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.83
Browser engine: Blink
Browser architecture: 32-bit
Context: webapp
Operating system: Android
Operating system version: 5.0
Operating system architecture: 32-bit
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: 8
User agent: Mozilla/5.0 (Linux; Android 5.0; ALE-L21 Build/HuaweiALE-L21) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Mobile Safari/537.36
C3 release: r31

Local storage
Storage quota (approx): 643 mb
Storage usage (approx): 4.5 mb (0.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2+ is not supported. Rendering quality and features may be affected.
CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Vendor: ARM
Renderer: Mali-450 MP
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 100
Extensions:

EXT_blend_minmax
EXT_shader_texture_lod
OES_standard_derivatives
OES_vertex_array_object
WEBGL_compressed_texture_etc1
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2017-05-26 11:59
Think this is a duplicate of #26

**Closed by AshleyScirra** 2017-05-26 11:59 UTC

**Comment by mfoster98** [comment] 2017-05-26 13:34
Yeah that's the same problem, much better said than me though haha.  Thanks Ashley :)

**Comment by AshleyScirra** [comment] 2017-05-26 16:08
@mfoster98 - I can't reproduce issue #26, it would be helpful if you could subscribe to that bug and offer any additional information on how to reproduce it.
