### ISSUE TITLE
[r23] CTRL+"N" creates a new project without creation dialogue

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#140] opened 2017-05-02 15:18 UTC
## Problem description
It just skips the creation dialogue and create a "new project".

## Expected result
A creation dialogue prompt to choose presets and change settings.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment] 2017-05-02 16:55
Can't reproduce: Ctrl+N opens a new tab.

Please always include the diagnostic information we ask for, it helps work out if you're doing anything different.

**Comment by jaydonteh** [comment] 2017-05-02 17:15
Thought it was really just that simple. Turns out I'm using Construct on desktop mode and it does create a new project with that shortcut. If just on the browser tab, it will open a new tab.

**Comment by AshleyScirra** [comment] 2017-05-03 14:55
Literally half the time it's not as simple as you expect! That's why we strictly enforce the requirements. This should be fixed for r24.

**Closed by AshleyScirra** 2017-05-03 14:55 UTC
