### ISSUE TITLE
saved .c3p fails to open

### ISSUE THREAD

**Issue by AndersAthleticDesign** [Scirra/Construct-3-bugs#5012] opened 2021-08-11 16:26 UTC
## Problem description

I saved several .c3p files between August 6 and August 7 that won't open. I get the error message: "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project."

Chrome console says: "Exception opening:  Error: cannot find event variable 'dx'"

I can open a .c3p saved on August 5.

They were all saved with R251.2 and attempted to load with R251.2 as well. Chrome was closed down and updated between the saves and the attempt to load them. 

No 3rd part addons have been used.

## Attach a .c3p

[fotboll with trail-210807.zip](https://github.com/Scirra/Construct-3-bugs/files/6969800/fotboll.with.trail-210807.zip)

## Steps to reproduce

Please try to open the attached project.

## Observed result

Project won't open.

## Expected result

Project should open.

## More details

Can't open in Chrome  92.0.4515.131

## System details

Chrome console message:

main.js:2108 [Project] Exception opening:  Error: cannot find event variable 'dx'
    at window.tia.aT (projectResources.js:877)
    at window.tia.Dg (projectResources.js:877)
    at window.kVc.pl (projectResources.js:813)
    at window.tia.accept (projectResources.js:681)
    at e.AU (projectResources.js:750)
    at e.accept (projectResources.js:681)
    at e.accept (projectResources.js:748)
    at g.AU (projectResources.js:724)
    at g.accept (projectResources.js:681)
    at f.AU (projectResources.js:695)
lOa @ main.js:2108
C_ @ main.js:2105
async function (async)
C_ @ main.js:2105
SCd @ main.js:2113
async function (async)
SCd @ main.js:2112
B3a @ main.js:2112
t.H.Be @ mainMenu.js:7
Md @ main.js:1256
ce @ main.js:1252

**Comment by AshleyScirra** [comment] 2021-08-11 16:46
I'm afraid as per the bug report guidelines, without knowing the steps how this happened in the first place, there is nothing we can do to fix the problem that broke the project. If you could identify the steps to follow that result in a corrupt project, it would be a high priority for us to fix it, but it's impossible to know what happened from just the project file.

I would advise to restore a backup. I can attempt to recover the project you provided if you prefer, but I can't guarantee it will be recoverable, and then the same problem could also happen again unless the cause is identified.

**Comment by AndersAthleticDesign** [comment] 2021-08-11 17:00
I had Chrome and Construct open for several days and saved regularly with Project/Save as/Save as single file. When I finaly shut down and restarted the system, I could not open the three last saves. No problem was indicated during the saving process and the faulty .c3p are the same size or slightly bigger (due to added plug-ins) compared than the last working one. 

I would very mcuh appreciate if you at least try to recover the project. I need the logic of the event sheets more than an actual working project.

**Comment by AshleyScirra** [comment] 2021-08-11 17:32
I managed to recover it: [issue5012-recovered.zip](https://github.com/Scirra/Construct-3-bugs/files/6970268/issue5012-recovered.zip)
The root cause was there were event variables named "dx", "dy", and "dist" under a function named "ballAgainstHoleWalls". However these event variables were already declared in a higher scope, so re-using the same name in their scope is invalid. I deleted the variables under "ballAgainstHoleWalls" and the project opens, but it may not be doing what you want (the function now has events referencing the higher-up event variables). The editor should prevent you ever being able to make something like this. Perhaps there is a missing check though. If you can find how you did this, please let me know; however without that information there is nothing else that can be done, so closing this issue.

**Closed by AshleyScirra** 2021-08-11 17:32 UTC
Labels: no repro

**Comment by AndersAthleticDesign** [comment] 2021-08-11 18:07
Thanks a lot. I expected somehing like that. I will take a closer look later. My guess is that the re-use happened while I shuffled around blocks of code, I will compare with the last working .cp3.

**Comment by AshleyScirra** [comment] 2021-08-12 17:48
Thanks for identifying the steps - this will be a high priority to fix. Could you file a new issue with the project file and the steps to reproduce? It would also be great if you can find a way to reduce the size of the project that you submit with the bug report - especially if you can reproduce it in a new empty project with minimal events.
