### ISSUE TITLE
On Create falsely triggered after Load

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3189] opened 2019-08-05 01:06 UTC
## Problem description

When saving an object, unloading it and reloading it, one instance of that object fires the On Create event again, even though it should not

## Attach a .c3p

[LoadBug.zip](https://github.com/Scirra/Construct-3-bugs/files/3465553/LoadBug.zip)

## Steps to reproduce

1. Open debugger
2. Open console (There should be every sprite UID listed in there
3. Press the debugger's save button
4. Press Enter (This changes the layout, essentially uloading the objects)
5. Press the debugger's load button

## Observed result

Look at the console, only one sprite has its On Create event retriggered.

## Expected result

It should not get triggered again

## More details

**Affected browsers/platforms:** all 

**First affected release:**

**Comment by AshleyScirra** [comment] 2019-08-15 15:45
This is currently by design. It's a complicated part of the engine and difficult to explain, but basically the process of switching layout involves first firing 'On created' for all instances placed on the layout, then 'On start of layout'. When you load a savegame that was saved on a different layout, the engine must first switch to that layout, and then load the state of the savegame.

In this case when the layout switches to load the savegame it fires 'On created' for the instance placed on the layout. This is (IIRC) in case it uses the 'No save' behavior, so that it gets the correct initial state. However 'On start of layout' is not fired, and 'On created' is not fired for the loaded instances, because the savegame contains already-initialised state to load.

This shouldn't matter since the savegame will overwrite anything you do in 'On created', is necessary for the case of using the 'No save' behavior, there is backwards-compatibility risk to changing this, and the report doesn't include any reason it's actually a problem, so closing.

**Closed by AshleyScirra** 2019-08-15 15:45 UTC
Labels: not a bug

**Comment by skymen** [comment] 2019-08-15 16:27
I get what you say but the issue here isn't that it fires every On create then loads. The issue is that it loads then fires ONE On Create. 

Here's where this might be an issue: 
I was working on a project using a Mode7 effect (basically, old wolfestein/doom like 3D) and I was placing my instances on the layout for the objects.
So On Create, I take their layout position and convert them to 3D coordinates, and from there I use the position of the camera and the 3D coordinates of my objects to move and scale them on the layout creating the 3D effect. 

What happened was when I would save and load, one instance's On Create would retrigger AFTER getting loaded and it would overwrite its (correctly loaded) 3D Coordinates value and that ONE instance would then be misplaced. 

Aka, if I place an instance at layout position 0,0, that gets translated to 0,0,0. The camera is at 100,0,100 facing towards 0,0,0 so my object at 0,0,0 is now at the center of the viewport (so let's say 400,400 if my viewport is 800x800) 

When loading, it will once again translate that 400,400 to 3D coordinates and thus instead of having my object get loaded at 0,0,0 it will be totally off, at 400,0,400

**Comment by AshleyScirra** [comment] 2019-08-16 10:27
Well, if you change the position of an object while loading a savegame, what should the engine do? You're adding a conflict in to the loading process - should the engine use the position you set, or the position from the savegame? I don't think there's a good answer to that question.

**Comment by skymen** [comment] 2019-08-16 10:33
I don't think you understood what I mean:
I DO NOT want to change the position post load. 
The issue is that it DOES.

**Comment by AshleyScirra** [comment] 2019-08-16 10:37
I don't understand. Loading the savegame restores the identical state at the time you saved. Why would you need to change anything?

**Comment by skymen** [comment] 2019-08-16 10:41
It is unclear why On Create would ever trigger after a load, but even if that was the case, and it was consistent that would be fine. The issue is that it triggers only one instance's On Create. 
Everything gets loaded fine, except ONE instance that gets its on Create triggered again AFTER the load. 

That makes it so I can't write events using On Create (like it's meant to do) without fearing it to break with saves.

**Comment by AshleyScirra** [comment] 2019-08-16 11:37
Well, I explained why in my earlier comment: it's the one initially placed in the layout, and it's to initialise it in case it has the 'No save' behavior.
