### ISSUE TITLE
Feature Request iOS

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1519] opened 2018-04-24 01:22 UTC
## Problem description - Feature Request

*Enter a concise description of your problem here*

When working on the Event Sheet, you have to double tap on different actions, this then causes random zooming, this is a problem because it is a zoom in and no way to zoom back out, can you also add the ability to single tap on an item then have a button on the form to do the select.  I do realize that double tapping is typically faster and easier, but man the zooming is a royal pain. I have lost a lot of work due to the zooming and this is a browser issue.

Any place in the app where we have to double tap can and does potentially cause the zoom to happen.

**Comment by AshleyScirra** [comment] 2018-04-24 08:31
This is a bug, not a feature request, and looks like a duplicate of #1284

**Closed by AshleyScirra** 2018-04-24 08:31 UTC
