### ISSUE TITLE
Save and load actions still causes a fatal crash

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#4041] opened 2020-07-17 20:31 UTC
## Problem description

Hi! I recently reported a few fatal crashes regarding the save and load actions in Construct 3 and they were all marked as fixed, however today while I was testing my game it crashed again during a load event... It's probably related to the way you fixed #3916 or #3979 , I honestly don't know, but I beg you to take a deeper look at this error, because I can't afford to strip down my project again and again, development time is so precious... Well, here's the error I found while playing my game.

Screenshot: https://i.imgur.com/VfxMl6K.png

## Attach a .c3p

Already provided projects related to the same issue in the past.

## Steps to reproduce

1. Just take a look at the console error I provided.

## Observed result

Fatal crash after using the "Load" action.

## Expected result

A smooth load transition.

## More details

**Affected browsers/platforms:** Chrome / Windows 10

**First affected release:** R207 (current beta release)

## System details

<details><summary>View details</summary>

c3runtime.js:2612 Load requested.
c3runtime.js:2281 [Construct 3] Loaded state from storage (289925 chars)
c3runtime.js:2281 [Construct 3] Failed to load state from storage:  Error: cannot call while loading state - wait until afterload event
    at C3Runtime.GetInstanceByUID (c3runtime.js:2274)
    at Track.CanInstanceBeValid (c3runtime.js:1230)
    at HasValidTracks._tracks.some.t (c3runtime.js:1217)
    at Array.some (<anonymous>)
    at Tween.HasValidTracks (c3runtime.js:1217)
    at TimelineManager._OnInstanceDestroy (c3runtime.js:1182)
    at Array.TimelineManager._instanceDestroy.e (c3runtime.js:1166)
    at EventHandler._FireNonCancellable (c3runtime.js:499)
    at EventDispatcher.dispatchEvent (c3runtime.js:509)
    at C3Runtime._FlushInstancesPendingDestroyForObjectClass (c3runtime.js:2245)
_DoLoadFromSlot @ c3runtime.js:2281
c3runtime.js:2612 Load failed.
c3runtime.js:2274 Uncaught (in promise) Error: cannot call while loading state - wait until afterload event
    at C3Runtime.GetInstanceByUID (c3runtime.js:2274)
    at Track.CanInstanceBeValid (c3runtime.js:1230)
    at HasValidTracks._tracks.some.t (c3runtime.js:1217)
    at Array.some (<anonymous>)
    at Tween.HasValidTracks (c3runtime.js:1217)
    at TimelineManager._OnInstanceDestroy (c3runtime.js:1182)
    at Array.TimelineManager._instanceDestroy.e (c3runtime.js:1166)
    at EventHandler._FireNonCancellable (c3runtime.js:499)
    at EventDispatcher.dispatchEvent (c3runtime.js:509)
    at C3Runtime._FlushInstancesPendingDestroyForObjectClass (c3runtime.js:2245)
c3runtime.js:2612 Song ended.

</details>

**Comment by AshleyScirra** [comment] 2020-07-20 09:51
This looks like a different problem involving timelines/tweens, so assigning @DiegoScirra.

Please always include all relevant information in a report - cross-referencing information in other threads is complicated and error-prone, and it may be a different developer not already familiar with the previous issues who investigates it.

**Comment by DiegoScirra** [comment] 2020-07-20 11:23
This should be fixed in the next beta. I haven't been able to reproduce the crash though, so I am not 100% sure it will be fixed.

**Comment by AshleyScirra** [comment] 2020-07-21 13:15
r208 is now out, can you check if it's working there?

**Comment by BonzerKitten** [comment] 2020-07-21 15:22
@AshleyScirra @DiegoScirra I completely understand the situation, I'm sure it's very hard to fix a bug without a reliable way to reproduce it. Well, I'll export a new version of my game using r208 and see if the whole game is playable now, I should be able to give you a definitive answer later today or tomorrow in the morning. Thanks for tagging me! 👍

**Comment by AshleyScirra** [comment] 2020-07-23 13:36
@BonzerKitten - any feedback on this? We're approaching a stable release and we're aiming to make no further changes from Tuesday onwards, so if any extra changes are needed we'd need to know soon otherwise the change will probably be punted to the next beta cycle, which would probably be ~3 weeks away.

**Comment by BonzerKitten** [comment] 2020-07-23 21:59
@AshleyScirra Hey! Sorry for taking so long to reply. So, I tested the game twice and couldn't reproduce any console errors related to this issue, so I guess we should be fine for now. But, if may I ask, is everything okay at Scirra? I mean, 3 weeks sounds like quite a lot of time, unless it's some sort of vacation.

**Comment by AshleyScirra** [comment] 2020-07-27 10:36
Thanks for confirming, closing this issue.

It's just our standard release cycle. We avoid making significant changes before stable releases to avoid any unexpected bugs. Once we've had a final beta release, made the stable release, then gotten to the first beta release of the next release cycle, about 3 weeks will have gone by.

**Closed** 2020-07-27 12:58 UTC
