### ISSUE TITLE
.c3p project loading troubles with a new release of C3 - "Failed to open project. Check it is a valid C3 single-file (c3p) project."

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#1291] opened 2018-02-16 06:53 UTC
## Problem description

Tricky problem to reproduce. I encountered it and some other people did report it to in the support.
I also have a "work-around".

Apparently, if you download a new release of Construct 3, and not have exactly all files downloaded (my guess because of the work-around) (even though you are already on the startup page) if you try to open a project saved locally it may cause an error : "Failed to open project. Check it is a valid C3 single-file (c3p) project."

## Attach a .c3p

Unfortunately, as mentioned, the issue is tricky to reproduce. A .c3p will provide this error, and once C3 given enough time to download everything on a slower connexion, the .c3p will open without issue.
We have an example of a file that caused the issue for R86 in the support though.  

## Steps to reproduce

Hard to tell.
Apparently, the user opens C3 on a new update day on, I assume, a "slower" connexion/possibly offline.
C3 updates, and the user goes to work right away on a project in progress.
They download a copy of the file (so the version is r86).
The next day, they open C3, try to open the file, and it raises the error.

It also had happened to me, although I'm using C3 online, my connexion is slower.
Even if C3 opens, there is still some delay on the startup page.

## Observed result

The project file fails to load right away.

Work-around : Reload C3 (not even force reload) and wait a few seconds on the startup page for the thumbnails of the example projects to appear. When they do, generally the project may be opened without the error message.

## Expected result

The project file to load right away.
Or perhaps a notice that C3 is not correctly updated.
Some kind of  "safeguard" for slower/offline connection making sure the update has been completed correctly.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2018-02-16 12:07
I've tried throttling the network connection in Chrome's dev tools to make C3 slow to load, and dropped in a .c3p file as soon as the UI appeared, and it still loaded correctly. So not sure how to go about reproducing this.

If you ever see a "Failed to open project" error, open the browser console and it should have a more detailed error logged there. If you can find that and post it here that would be helpful.

**Comment by Srkabeza** [comment] 2018-02-16 13:53
I,m running on the same problem. This is what my chrome console shows:
![bug report](https://user-images.githubusercontent.com/16064033/36310692-295d7006-1329-11e8-8456-6725f30fb3f0.png)

**Comment by Srkabeza** [comment] 2018-02-16 13:57
Solved when running R86

**Comment by shortercode** [comment] 2018-02-16 13:59
@Srkabeza there was a change in the text plugin between r85 and r86. Projects saved in r86 will not open in r85.

**Comment by Tokinsom** [comment] 2018-02-16 23:13
@AshleyScirra I'm getting this same error trying to open a project in the desktop version of C3. I literally just saved it, closed C3, reopened C3, and tried to open it again, but I get this error. Is it the same issue or should I file a new bug report?

**Comment by AshleyScirra** [comment] 2018-02-17 11:09
I don't know because we still don't know what the cause of the original report is:

> If you ever see a "Failed to open project" error, open the browser console and it should have a more detailed error logged there. If you can find that and post it here that would be helpful.

You should do that as well to see what the cause of the error is.

**Comment by Tokinsom** [comment] 2018-02-18 22:25
@AshleyScirra So it appears that I renamed a layout and the project still thinks the old one is still there somewhere and won't load. Was Dungeon_0, now DungeonEntrance. Console screenshot: https://puu.sh/zqFUK/840f31e9c5.png

**Comment by AshleyScirra** [comment] 2018-02-19 10:58
@Tokinsom is that the same issue as the one you filed at #1293?

**Comment by Tokinsom** [comment] 2018-02-19 12:12
@AshleyScirra Yes. I wasn't sure if there was any overlap with this issue and mine..just a similar issue so I posted here first. Sorry for any confusion.

**Comment by NetOneGames** [comment] 2018-02-20 19:24
For what it is worth I also experienced this a few weeks ago, dont ask me at what release,    Im pretty sure I even waited for the "now ready to work off line" message then shut my tablet down went to work booted up at work at lunch time (where I have to work off line) an no projects would load with same message as per OP. sure sent a shiver down my spine but as no other projects would load I figured that it was something wrong with the offline files.  When I got home on line all was well.

**Comment by AshleyScirra** [comment] 2018-03-02 12:38
There's been a couple of issues that could cause this error that we've fixed lately. Since there's been no news on this and no reports including error messages from the browser console that aren't issues we've already fixed, closing this report now. If you ever see this again please file a new issue, and make sure you open the browser console (F12) and include the contents of any error that is listed there.

**Closed by AshleyScirra** 2018-03-02 12:38 UTC
Labels: can't reproduce
