### ISSUE TITLE
The bottom part of the viewport is not clickable in the editor.

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#3917] opened 2020-06-05 15:06 UTC
## Problem description

The title says it all, the bottom part of the viewport is not clickable in the editor, like there's an invisible wall between the objects and the cursor.

Here's a Photoshoped image showing the clickable area (green) and the non-clickable area (red): https://imgur.com/jMH4PlB

## Attach a .c3p

[Clickable Area Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4736819/Clickable.Area.Bug.zip)

## Steps to reproduce

1. Open the project.
2. Try to click on one of the objects in the bottom of the screen.

## Observed result

Only part of the viewport is clickable.

## Expected result

The whole viewport to be clickable.

## More details

**Affected browsers/platforms:** Google Chrome/Window 10

**First affected release:** R197.2 (current stable version)

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by gameglaux** [comment] 2020-06-05 15:12
Confirmed here.

**Comment by AshleyScirra** [comment] 2020-06-08 10:26
It looks like it only happens in the dark/light themes, the default theme seems to work fine. Should be fixed in the next beta.

**Closed by AshleyScirra** 2020-06-08 10:26 UTC
Labels: theme

**Comment by BonzerKitten** [comment] 2020-06-08 12:39
@AshleyScirra Thanks for the fix! 👍

**Comment by BonzerKitten** [comment] 2020-06-17 13:43
@AshleyScirra Just tested the new stable and the part with the mouse, layout and zoom information still is not clickable. Is that expected?

**Comment by AshleyScirra** [comment] 2020-06-17 14:53
Yes, that's expected if it's directly on the layout view status.
