### ISSUE TITLE
Texture released too many times bug :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6472] opened 2023-02-07 18:21 UTC
## Problem description

There is an error in the console. The bug doesn't always happen.

If there are no errors in the console, restart the preview.

It seems I have already seen it here https://github.com/Scirra/Construct-3-bugs/issues/6393

## Attach a .c3p

[texture_released_too_many_times_bug_r329b.zip](https://github.com/WilsonPercival/WilsonPercival/files/10678194/texture_released_too_many_times_bug_r329b.zip)

## Steps to reproduce

1. Open a project.
2. Run `Layout 1`.
3. Open the console.

## Observed result

https://user-images.githubusercontent.com/91274932/217331171-777897c2-123c-43b6-9b39-281487f7160b.mp4

## Expected result

Everything works well.

## More details

If you can't reproduce - add more frames and increase loop length.

**Affected browsers/platforms:** Mozilla

**First affected release:** broke in r329b

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r329 (beta)
Browser: Firefox 109.0
Browser engine: Gecko
Context: browser
Operating system: Windows 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0
Language setting: en-US
Local storage

Storage quota (approx): 9.8 gb
Storage usage (approx): 29 mb (0.3%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    UI effects are disabled in settings.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2023-02-13 15:32
I previewed the project 5 times an no error ever occurred. Can you find a more reliable way to reproduce the problem?

**Comment by WilsonPercival** [comment] 2023-02-13 15:46
> I previewed the project 5 times an no error ever occurred. Can you find a more reliable way to reproduce the problem?

@AshleyScirra A friend told me about this problem. Here is his project. You can try launching it from the `Menu` layout and pressing the button in the game.

[TextureReleasedTooManyTimes (2).zip](https://github.com/Scirra/Construct-3-bugs/files/10723784/TextureReleasedTooManyTimes.2.zip)

https://user-images.githubusercontent.com/91274932/218504394-f458f86a-6498-4494-ad52-ea88c46d1353.mp4

Alternatively, you can try increasing the number of frames to 1000 and increasing the number of loop iterations.

I will also ask my friend to repeat this on his more powerful computer.

**Comment by GeekManOfficial** [comment] 2023-02-13 16:01
https://user-images.githubusercontent.com/95054989/218508432-b1201220-47d8-43ae-a302-8d871c33ee88.mp4

i can reproduce this

**Comment by jsuttonBRC** [comment] 2023-02-15 17:25
Odds are, the sprite your trying to load isn't on the layer you are loading.

"Uncaught (in promise) Error: texture released too many times"

Happens for me when loading from URL if the sprite is on layout1, but I load image on layer2.  Add the sprite to layer2 and delete it or use it, etc.

**Comment by AshleyScirra** [comment] 2023-02-21 12:54
I think I eventually figured out what is going on here - there was another race condition between a dynamic texture load (caused by creating an object not on the same layer) and using the 'Load from URL' action. Hopefully it should be fixed in the next beta.

**Closed by AshleyScirra** 2023-02-21 12:54 UTC
