### ISSUE TITLE
Fps drops when spawning objects

### ISSUE THREAD

**Issue by staarmaan** [Scirra/Construct-3-bugs#5916] opened 2022-07-22 17:38 UTC
## Problem description
After spawning lots of objects for a while, the game starts to get increasingly bad fps drops when doing so

## Attach a .c3p
[fpsdrops.zip](https://github.com/Scirra/Construct-3-bugs/files/9169540/fpsdrops.zip)
this is a small bullet hell engine made on release 293.3 to prove this bug. It only happens in r302 and onwards so open the project file on r293.3 and then on r302 to see the fps differences (despite the file using the same code).

## Steps to reproduce

1.Spawn a bunch of sprites frequently 
2.Wait for the game to start dropping fps (As far as i know, the more code and variables your sprites have, the quicker it lags)

## Observed result
The game drops fps when spawning objects and the more time passes the more fps drops. Resetting the layout or changing into another one doesn't have any effect on the fps drops.

## Expected result
This fps drops shouldn't be happening. 

## More details

some one shared this: https://drive.google.com/file/d/1JMx4M9_82Eirxq5rIfF-H2cQCyZ4Urmi/view to test the bug in the following construct 3 forum post that i made before reporting this bug:
https://www.construct.net/en/forum/construct-3/general-discussion-7/strange-fps-drops-spawning-171348#forumPost1074416
strangely enough, the fps drops never occurred on the shared file but they did happened in mine, so yeah its quite weird.

**Affected browsers/platforms:** 
Microsoft edge, Windows 11

**First affected release:** 
after r302
## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: Edge 103.0.1264.62
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62
Language setting: en-US

Local storage
Storage quota (approx): 143 gb
Storage usage (approx): 3.2 gb (2.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2022-07-25 09:04
@DiegoScirra - looks like handling tweens is significantly slower in r302 than r293.3.

**Comment by DiegoScirra** [comment] 2022-07-29 11:01
This is a regression introduced in r296 as a result of fixing issue #5709. Will be fixed in the next beta.

**Closed by DiegoScirra** 2022-07-29 11:01 UTC
