### ISSUE TITLE
C3 crashing when enabling "Show Collision Poly" for a layout

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#4532] opened 2021-02-04 11:25 UTC
When I enable show collision polygons C3 crashes.

## Attach a .c3p

could not reproduce in new project yet

## Steps to reproduce

1. enable collision plygons for current layout

## Observed result

C3 error popup
Error report information
Type: unhandled exception
File: https://editor.construct.net/r234/plugins/allEditorPlugins.js, line 227, col 55
Message: Uncaught TypeError: this.fLd is not a function
Stack: TypeError: this.fLd is not a function at f.Instance.gEa (https://editor.construct.net/r234/plugins/allEditorPlugins.js:227:55) at p.gEa (https://editor.construct.net/r234/projectResources.js:238:421) at q.Zfb (https://editor.construct.net/r234/projectResources.js:625:307) at r.Zfb (https://editor.construct.net/r234/projectResources.js:595:474) at window.ll.Ftd (https://editor.construct.net/r234/components/editors/layoutView/layoutView.js:14:72) at Upc (https://editor.construct.net/r234/components/editors/layoutView/layoutView.js:4:237)
Construct 3 version: r234
URL: https://editor.construct.net/
Date: Thu Feb 04 2021 12:19:39 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 2961.8 s

Platform information
Browser: Chrome
Browser version: 88.0.4324.104
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.399999976158142
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
C3 release: r234 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 615 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

## More details
I tried to reproduce it in a new project using SVG and text with polka dot effect applied (thats what I use in my project) but it works fine in a new project so far (with one instance of the object). 

**Affected browsers/platforms:** 

Chrome
**First affected release:** 
r234

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 88.0.4324.104
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.399999976158142
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
C3 release: r234 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 1.3 gb (1.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 615 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2021-02-04 11:52
The problem is with the SVGPicture plugin. There is a **DrawQuadCollisionPolygon** method which doesn't appear to be defined anywhere. Assigning to @AshleyScirra.

**Comment by AshleyScirra** [comment] 2021-02-04 17:09
Minimal repro: 
[issue4532.zip](https://github.com/Scirra/Construct-3-bugs/files/5927351/issue4532.zip)
Ticking "Show collision polygons" in layout properties reproduces the problem.

**Comment by AshleyScirra** [comment] 2021-02-04 17:17
Should be fixed in next beta.

**Closed by AshleyScirra** 2021-02-04 17:17 UTC
