### ISSUE TITLE
MobileIAP is not working in C3 runtime

### ISSUE THREAD

**Issue by supyoo** [Scirra/Construct-3-bugs#2057] opened 2018-09-19 16:45 UTC
(I used Google Translator. I'm sorry, if English is strange.)
## Problem description

MobileIAP is not work in C3 Runtime.
(I did test at R118. Already)

## Attach a .c3p

[SPACESHOOTER_Android_bugreport.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2397900/SPACESHOOTER_Android_bugreport.c3p.zip)

## Steps to reproduce

1. change option "Runtime C2" to "Runtime C3" 
2. Export Android Debug build(Lolipop5.0)
3. Play game on Mobile. press Shop button.
4. Shop (MobileIAP) does not work.

advenced test.
1. don't touch option "Runtime C2"
2. Export Android Debug build(Lolipop5.0)
3. Play game on Mobile. press Shop button.
4. Shop (MobileIAP) is COOL work!!!
5. but Start Stage is NOT Work. The Game Has been Stop on the battle.

## Observed result
MobileIAP is not work. registration stage is not complated

## Expected result
shop page is work on "Runtime C2"
gamescene page is work on "Runtime C3"

## Affected browsers

not browser problem.
It's android APK Export Issue

## System details

C3 = MacOS HighSierra

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 69.0.3497.92
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1.7999999523162842
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
C3 release: r118 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 212 mb (1.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel Iris Pro OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by MrWonka** [comment] 2018-10-09 13:04
I'm having a similar issue.

**Comment by Vultwo** [comment] 2018-11-16 12:00
Bump?

**Comment by vpaultech** [comment] 2018-11-18 23:35
Similar issue on android using r125. Havent got to IOS yet. Used the signed APK export. App crashes on some devices or fails to complete registration sometime between setting public key and complete registration methods. Tried multiple work arounds. I am using system platform conditionals to separate my IOS, Android and HTML5 parameters. Just an FYI to that. Also, I load all my local storage variables first and initiate store registration after to eliminate the possibility of overloading the system. Perhaps that wasn't necessary but I wanted to eliminate that possibility, especially since I'm running a large/complicated project. Thank you in advance, keep up the good work!

**Comment by WanKIpas** [comment] 2018-11-19 04:53
i change to C2 Runtime and use the signed APK export. it works.. 
but when i change back to C3 Runtime, the prob is back on. and the apps crashes.

**Comment by shortercode** [comment] 2018-11-28 16:44
Okay sorry for the slow progress on this, mobile testing is somewhat long winded so this had been shuffled to the bottom of my pile. I've just completed a batch of fixes for the next release that should have the plugin working with the C3 runtime.

**Comment by AshleyScirra** [comment] 2018-12-05 18:30
Can anyone confirm if this is resolved in r128?

**Comment by vpaultech** [comment] 2018-12-05 18:40
I can confirm that it working on Android with r128 using the signed APK export in C3.
I still have to test it on IOS. I'm hoping to do that this weekend.
Thank you for getting on this. Your diligence is much appreciated!

**Comment by drg8** [comment] 2018-12-06 11:58
> I can confirm that it working on Android with r128 using the signed APK export in C3.
> I still have to test it on IOS. I'm hoping to do that this weekend.
> Thank you for getting on this. Your diligence is much appreciated!

do we need the payment and tax info all set-up in developer console to test the plugin? as mine has tax info blank and it keeps saying update your tax info, as there is new goods and service tax stuff in india and we have to submit and id, so yesterday I've applied for that might take several days. 
till then can you please attach your example file so that I can verify that there's nothing wrong with my code and all the problem that I'm facing is because of the empty tax field in developer console's payment section.

**Comment by shortercode** [comment] 2018-12-10 13:57
@drg8 

> do we need the payment and tax info all set-up in developer console to test the plugin? as mine has tax info blank and it keeps saying update your tax info, as there is new goods and service tax stuff in india and we have to submit and id, so yesterday I've applied for that might take several days.
> till then can you please attach your example file so that I can verify that there's nothing wrong with my code and all the problem that I'm facing is because of the empty tax field in developer console's payment section.

It's been awhile since I've looked at the forms for setting up purchases. I ended up filling out all the forms in the end ( for iOS, not for Android ), even though I didn't intend to publish any games. After this I figured that it was probably something else that was preventing my test code from working.

At the time I was just trying things to see if I could get it to work, so I'm not sure if it's a hard limitation for testing or not. Your probably best off asking around the forum, and just searching the net for answers. If it's a restriction then it's with the iOS IAP service, so you don't need to look for construct specific solutions.

**Comment by drg8** [comment] 2018-12-10 14:43
@shortercode
> It's been awhile since I've looked at the forms for setting up purchases. I ended up filling out all the forms in the end ( for iOS, not for Android ), even though I didn't intend to publish any games. After this I figured that it was probably something else that was preventing my test code from working.
> 
> At the time I was just trying things to see if I could get it to work, so I'm not sure if it's a hard limitation for testing or not. Your probably best off asking around the forum, and just searching the net for answers. If it's a restriction then it's with the iOS IAP service, so you don't need to look for construct specific solutions.

I'm sure it is a hard limitation and it will vary depending on the applicable laws each country has, as in India to sell digital goods through IAP we are required to have a Business Account in Bank and TAX ID.
so these steps are actually stopping the billing service from displaying on the app.

[Test Google Play Billing](https://developer.android.com/google/play/billing/billing_testing) Here some methods are given for static testing (I guess they don't require above steps to be filled out in Developer Console). if test mode is added in the IAP plugin (just like admob plugin) it'll be quite useful for testing the IAP implementation in the game.

**Comment by shortercode** [comment] 2018-12-17 13:31
Thanks for linking the resource @drg8 I hadn't heard of the special testing ID's before, they might be worth adding in. Although I'm not sure that the same behaviour is available in iOS, and I don't how they would behave with product ownership/consumables etc. 

All the testing features are toggled by using a "testing account" so there's nothing a "test" property could actually enable. We could replace all purchases with `android.test.purchased` but as I mentioned above I'm not sure it would behave as an actual purchase would. So it wouldn't be a very good "test" mode.

**Closed** 2018-12-17 14:33 UTC
Labels: c3runtime
