### ISSUE TITLE
Gameplay still runs in background when power button is pressed Android

### ISSUE THREAD

**Issue by drexegar** [Scirra/Construct-3-bugs#762] opened 2017-08-29 14:35 UTC
## Problem description

The gameplay will pause when sent to background on any occasion, but it will not pause when you press the power button and turn off the screen while the app is in focus.

I also provided a timer that also makes a sound every second so you can cleary see the time keeps moving and the sound trigger keeps playing when screen is off

## Attach a .c3p

https://drive.google.com/file/d/0ByybatBADJBNRUxSZWFrZ1FKQm8/view?usp=sharing

## Steps to reproduce

1. Export Android App with a constant moving action or a sound
2. Run the app and press the power button
3. Screen will turn off

## Observed result

Gameplay still runs if you press the power button while the game is in focus

## Expected result

Gameplay to pause when the phone screen is off

## Affected browsers

* Chrome: no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2017-08-29 15:24
Possible dupe of #751

**Comment by drexegar** [comment] 2017-08-29 15:31
As for the possible dupe, 751 claims his game dosent pause at all, my game and the included min file pause in the background with no problem, its only the power off button with the screen off that dosent pause the gameplay.

**Closed** 2017-08-29 15:31 UTC
Labels: duplicate
