### ISSUE TITLE
Editor crash when toggle "Initially visible" checkbox

### ISSUE THREAD

**Issue by yojona** [Scirra/Construct-3-bugs#338] opened 2017-05-24 08:15 UTC
## Problem description

Editor crash when toggle "Initially visible" checkbox

## Attach a .c3p

https://www.youtube.com/watch?v=WWYagvE9mVM

## Steps to reproduce

1. Open project
2. Check "Initially visible"

## Observed result

Crash

## Expected result

Set visible to true

## Affected browsers

* Chrome: yes

## System details
<details><summary>View details</summary>
Error report information
Type: unhandled exception
File: https://editor.construct.net/r30/plugins/tilemap/plugin.js, line 1, col 6840
Message: Uncaught Error: invalid property name
Stack: Error: invalid property name at c.ǃyw.ǃyj (https://editor.construct.net/r30/plugins/tilemap/plugin.js:1:6846) at ne.ǃfA (https://editor.construct.net/r30/main.js:61:209055) at d.ǃPa (https://editor.construct.net/r30/components/bars/propertiesBar/propertiesBar.js:1:29013) at ǃJ.ǃU.ǃUu.ǃvJ.ǃJOu (https://editor.construct.net/r30/main.js:2:478212) at ǃJ.ǃU.ǃUu.ǃJJX.ǃJOC (https://editor.construct.net/r30/main.js:2:464630) at ǃJ.ǃU.ǃUu.ǃJJX.ǃCV (https://editor.construct.net/r30/main.js:2:464883) at HTMLInputElement.ǃOsW (https://editor.construct.net/r30/main.js:2:463467)
Construct 3 version: r30
URL: https://editor.construct.net/
Date: Wed May 24 2017 01:06:08 GMT-0700 (MST)
Uptime: 107.3 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r30

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel HD Graphics 4000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by DiegoScirra** [comment] 2017-05-24 09:08
Duplicate of #309. Closing.

**Closed** 2017-05-24 09:09 UTC
Labels: duplicate
