### ISSUE TITLE
Error when saving very large projects (v293.3)

### ISSUE THREAD

**Issue by starkiJi** [Scirra/Construct-3-bugs#5740] opened 2022-05-27 09:02 UTC
**Problem description**
(Hi, I'm using google translate)
In my project I have 1 sprite. This 1 sprite contains 100 identical pictures sized 1920-1080. 
I also duplicated the animation containing images 7 times and got 700 identical images and the project weight is about 1.7 gigabytes.

So far, everything is fine and the project is saved in the cloud or on a PC.

**Attach a .c3p**
https://1drv.ms/u/s!AsiOPje-rC00jDtRZ4xT3bYrTan7?e=wgmfUr

**Steps to reproduce**

Download and open the project.
If you open the sprite and **make more 10 more duplicate animations** (not the sprite), you'll have over 1400 images in your project. 
Now try to save to a PC or to the cloud and you will see an error, although the project is not gigantic, but large. 
Perhaps this shouldn't be?

**Expected result**
I can make a project even 20 gigabytes in size and it will be saved successfully

**Comment by AshleyScirra** [comment] 2022-05-27 11:36
Saving to a single file, I can reproduce an "Aw snap" error stating it is out of memory. (You did not say what the error message was in your report - I am assuming this is the same thing you saw.) A .c3p file is really a zip of a project folder, and I suspect it is failing to create a zip over around 2GB, presumably because of some memory limit in the browser engine. I am not sure it is feasible to work around that.

However saving a project folder works, and that option is more suitable for large projects anyway. We already recommend this for larger projects. So you should be able to use that to save very large projects without any particular size limit.

Given there doesn't appear to be a feasible solution for single-file projects, and the folder option is more suitable anyway and still works, closing as won't fix.

**Closed by AshleyScirra** 2022-05-27 11:36 UTC
Labels: wontfix, external
