### ISSUE TITLE
Editor crash as soon as I enter the URL (one pc only)

### ISSUE THREAD

**Issue by PSyCHoHaMSTeRza** [Scirra/Construct-3-bugs#593] opened 2017-07-07 05:57 UTC
## Problem description

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃcH' of null @ TypeError: Cannot read property 'ǃcH' of null at ǃP.ǃo.ǃXN.ǃSlU.then.then.then (https://editor.construct.net/r44/main.js:162:17133) at 
Stack: TypeError: Cannot read property 'ǃcH' of null at ǃP.ǃo.ǃXN.ǃSlU.then.then.then (https://editor.construct.net/r44/main.js:162:17133) at 
Construct 3 version: r44
URL: https://editor.construct.net/
Date: Fri Jul 07 2017 12:48:02 GMT+0700 (SE Asia Standard Time)
Uptime: 4.6 s

Unable to collect further diagnostic information because a promise rejection occurred while trying to collect it.

## Attach a .c3p

No c3p file

## Steps to reproduce

Only a problem with this specific computer. I do not know what causes this. It happens as soon as I try to go to editor.construct.net

## Observed result

Red screen with the abovementioned error

## Expected result

The editor to load as normal.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃcH' of null @ TypeError: Cannot read property 'ǃcH' of null at ǃP.ǃo.ǃXN.ǃSlU.then.then.then (https://editor.construct.net/r44/main.js:162:17133) at 
Stack: TypeError: Cannot read property 'ǃcH' of null at ǃP.ǃo.ǃXN.ǃSlU.then.then.then (https://editor.construct.net/r44/main.js:162:17133) at 
Construct 3 version: r44
URL: https://editor.construct.net/
Date: Fri Jul 07 2017 12:48:02 GMT+0700 (SE Asia Standard Time)
Uptime: 4.6 s

Unable to collect further diagnostic information because a promise rejection occurred while trying to collect it.

</details>

**Comment by shortercode** [comment] 2017-07-07 10:28
Have you tried running C3 in incognito mode on this PC?

**Comment by diegopassoscosta** [comment] 2017-07-14 16:28
Same issue with me, and I already tried to execute in incognito mode, same message.

**Comment by AshleyScirra** [comment] 2017-07-17 13:14
I've made a change which I think should fix this for r45, let's check again when that's out.

**Comment by diegopassoscosta** [comment] 2017-07-17 19:51
I tried but, same issue, 
I changed my videocard to onboard and nothing.
Construct 3 keep working on virtualbox (ubuntu 64), but very slow even using hardware acceleration.

**Comment by AshleyScirra** [comment] 2017-07-18 11:33
r45 is out now, please check again!

**Comment by diegopassoscosta** [comment] 2017-07-18 17:54
Checked on  r45
Little better,
Now I can see the first window
Game Demos
Templates

but appear this one and i have to restart

----

Error report information
Type: unhandled rejection
Reason: Error: expected function @ TypeError: expected function at Function.ǃQ.ǃfY (https://editor.construct.net/r45/main.js:2:176622) at Function.ǃQ.ǃX (https://editor.construct.net/r45/main.js:2:203962) at u.ǃYK (https://editor.construct.net/r45/main.js:71:27994) at Object.t.push.ǃQ.ǃox [as ǃagT] (https://editor.construct.net/r45/main.js:71:28383) at t (https://editor.construct.net/r45/main.js:2:258281) at a (https://editor.construct.net/r45/main.js:2:258067)
Stack: TypeError: expected function at Function.ǃQ.ǃfY (https://editor.construct.net/r45/main.js:2:176622) at Function.ǃQ.ǃX (https://editor.construct.net/r45/main.js:2:203962) at u.ǃYK (https://editor.construct.net/r45/main.js:71:27994) at Object.t.push.ǃQ.ǃox [as ǃagT] (https://editor.construct.net/r45/main.js:71:28383) at t (https://editor.construct.net/r45/main.js:2:258281) at a (https://editor.construct.net/r45/main.js:2:258067)
Construct 3 version: r45
URL: https://editor.construct.net/
Date: Tue Jul 18 2017 14:15:06 GMT-0300 (Hora oficial do Brasil)
Uptime: 9 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r45

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment] 2017-07-19 11:35
Hmm, looks like a similar underlying problem but just occurring somewhere else... so our r45 fix didn't really fix the root cause. Not sure how this is happening, seems to be a subtle race condition that only occurs on certain systems. This could be a tricky one.

**Comment by diegopassoscosta** [comment] 2017-07-21 20:23
May be this could help you, 
I can run all version, r12 to r38-2 but, in r39 the issue born 

r39
3 CHANGES

Add
New icons for Remote Preview and 'Wrap selection'
Change
Re-enabled the HTML imports polyfill. Hopefully it works this time!
Bug fix
Dialog layout persistence resets when editor is restarted

**Comment by diegopassoscosta** [comment] 2017-07-21 20:23
In the r46

---------------------------

**Comment by AshleyScirra** [comment] 2017-07-31 13:56
I'm struggling to find any reason this could possibly happen.

Can you confirm:

1) that you have no browser extensions installed, or that if you do, the problem still reproduces if you remove all the browser extensions

2) whether the problem still occurs in [Chrome Canary](https://www.google.co.uk/chrome/browser/canary.html)?

**Comment by AshleyScirra** [comment] 2017-08-02 15:16
@diegopassoscosta - we also made a small change to try to fix this in r47. As well as the other questions, can you also let us know if it works any better in this release?

**Comment by diegopassoscosta** [comment] 2017-08-02 20:52
Thank you!! It's working, I was running Windows 10 in VM. More faster than Ubuntu (in my case) 
Now it's working here on Windows 8.1

**Comment by diegopassoscosta** [comment] 2017-08-02 20:55
I tried to run on Google Canary and nothing and without extentions in my chrome, but no success.

But now it's working! on r47

**Comment by AshleyScirra** [comment] 2017-08-07 13:34
Okay, guessing this is fixed now! Please let us know if it happens again...

**Closed by AshleyScirra** 2017-08-07 13:34 UTC
Labels: difficult
