### ISSUE TITLE
Renamed backup file couldn't save, no longer have auto-backups.

### ISSUE THREAD

**Issue by Unconected** [Scirra/Construct-3-bugs#3654] opened 2020-02-17 22:40 UTC
C3 only made local backups for a few days and it stopped again.
I originally contacted support in private but was told to make a ticket.
It doesn't exactly fit the template so I figured it will be closed. 
This seems like two bugs but am not sure.
I know it sounds off, but I just know it happened and I no longer have auto backups.
(only tested local backups/download)

## Problem description
Backups were working and then they stopped.
I don't know how to reproduce it, because it happened and I can't undo what was done.
I can mention what I did before it happened.
Any c3p file I use no longer backs up

## Attach a .c3p
I don't have a c3p to attach because it affected the built in c3p examples too.
I also don't want to upload all of my work to the public.
If it were just logic I would be okay but I have tons of art/audio in it.
I opened existing built in c3p projects and downloaded to Local Disk.
I closed C3 and opened the c3p file from local disk and they also don't have auto backups.

## Steps to reproduce
I also don't know if this is what caused it...
I am kind of expecting it to not be reproducible.
I just know it happened so I reported.

Be careful if you try this.
I no longer have backups for any c3p.

Save Settings
-Download location:Download a copy
-Save location same location

I had a local project.
It gave me some auto backups and I closed the project.
I deleted the main file and copy/paste a backup and renamed it to make it the main file.
I then had trouble saving the new main file, I forget the error.
I then couldn't do anything with the file because I couldn't save it.
I decide to save it to 'Local Browser' and then I downloaded it.
I then reopened the downloaded file and saved it on Local Disk as my main.
The new Main file now saves and opens normally.

Now the Auto Backups don't work, even after closing Chrome and clearing out cache, cookies, history etc..

## Observed result
I couldn't save a backup file that I renamed to be the main file, it gave an error.
I saved it as 'Local Browser' and downloaded it and saved it to Local Disk.
The new Main file now saves and opens normally.
I no longer have backups on any c3p files. 

## Expected result
Able to rename a backup file and save it.
Interval Backups working as they were before.

## More details
I was using the site version of C3, not desktop build.

## System details
 C3 Release r182.4
Window 10 Pro Build 18362.19h1_release.190318-1202

**Comment by AshleyScirra** [comment] 2020-02-18 13:27
This could just be a simple mistake with your settings. What are your Save & backup settings?

Please also follow the bug report guidelines as closely as you can anyway, it is very difficult to help without all that information. See also the FAQ; we don't want your full project and it's unhelpful to attach it. You have also not provided all your system information, which is important information.

The first thing we do when investigating bug reports is follow the steps to reproduce it. Without these it is generally impossible to do anything to help. If you can figure out these steps we may be able to investigate, but otherwise all we have left is telepathy, which is notoriously unreliable.

**Comment by Unconected** [comment] 2020-02-19 00:45
I contacted support because it didn't fit the template and they told me to make a ticket.
I just know it happened and I no longer have auto backups.

Save & backup is Download a copy
Backup location Same location.
Backup interval 10 minutes

I did wait a few days before contacting support or making this ticket, because it was basically just running the way it was before. I was hesitant to go to support or make a ticket because I didn't have enough info. 
What I gave is all the info I had.
C3 doesn't make backups anymore so I can't try to reproduce it since I can't do what I did before it happened. I replaced the auto backups with manual made backups, so I can continue to work.

I wasn't expecting telepathy, just figured I would possibly point something out that may exist.

I did overlook system info, sorry.

Platform information
Browser: Chrome
Browser version: 80.0.3987.106
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36
C3 release: r182.4 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 320 mb
Storage usage (approx): 47 mb (14.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 950 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment] 2020-02-19 11:10
Have you actually ticked "Periodically back up active project"? You haven't mentioned whether that is enabled, and if it is unticked, Construct won't save any backups.

**Comment by Unconected** [comment] 2020-02-19 23:48
Yes it is ticked.
Sorry I thought it was implied because 'Backup interval 10 minutes'.
I should have had that to, my fault. 10 is default I believe so it did create doubt.

**Comment by Unconected** [comment] 2020-02-20 22:06
I should add a note.
I have Chrome installed at it's default location on C.
I have C3 Files on a 2nd hard drive.
That way if I have to reset my OS for any reason I don't lose my important files.
I will try to disable browser extensions and computer security to see if it is somehow interfering.
It will take me a few hours though.

**Comment by AshleyScirra** [comment] 2020-02-24 14:49
I just tried testing local browser autosaves with a modification to autosave every 10 seconds. It seemed to be working just fine.

There are several things mentioned that point to some kind of misunderstanding:

> I opened existing built in c3p projects and downloaded to Local Disk.

It's not clear what you mean by "downloaded to Local Disk". It could refer to an experimental feature we're currently testing, but in this case I presume you mean you used the "Download a copy" option? This will not make autosaves when you have "same location" autosaves set, because downloading a copy makes a one-off copy and there isn't a good way to store autosaves without spamming you with loads of downloads (which some browsers also block). So if you did this, it is by design that it will not make autosaves. Only the other save options can have autosaves.

> I closed C3 and opened the c3p file from local disk and they also don't have auto backups.

Again it's not clear which method of opening the project you are actually using. If you open a project by drag-dropping it in to the window, Construct doesn't have a save location for it. So it won't make autosaves until you save it somewhere Construct knows about, like Cloud Save. So again if you did this it is by design that it will not make autosaves.

> I then reopened the downloaded file and saved it on Local Disk as my main.

Again it's unclear which save option you're actually using here. Note if you're using the still experimental local file & folder saves in Chrome, this does not yet support autosaves, and that's one of the reasons it's still experimental. So again in this case it's currently by design that no autosaves will be made. But it's unclear whether you have previously used this feature or not. It's also unclear what your "main" is.

Most bug reports along the lines of "everything was working fine, and now it suddenly doesn't work any more" without reliable steps to reproduce, are usually because something did actually change. Maybe you changed your settings, or saved your project somewhere else, or tried one of the experimental features that doesn't cover this yet. Without steps to reproduce and no indications from any other users that anything is wrong, this seems like the most likely scenario.

If you can find a reliable series of steps to follow and reproduce the issue, please file an issue and follow all the guidelines to the full extent possible, and remember clear and concise information is necessary to be able to investigate. Since there is no clear evidence of a problem and several reasons to suspect a misunderstanding, closing.

**Closed by AshleyScirra** 2020-02-24 14:49 UTC
Labels: no repro

**Comment by Unconected** [comment] 2020-02-26 15:59
Well I did get about 3 backups from it somehow. I am very sure I had
'Download a copy' and 'Same location'.
I would suggest a chrome plugin if it will allow auto backups to work
properly.
