### ISSUE TITLE
Sprite object - export as jpg - quality 75 - layout stuck

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#3720] opened 2020-03-22 01:47 UTC
## Problem description

Setting sprite object export to jpg, quality 75, layout won't load.

## Attach a .c3p
[jpg-75bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4364522/jpg-75bug.zip)

## Steps to reproduce
1. set sprite object image export settings to jpg quality 75
2. try to run the layout

## Observed result

Layout won't load

## Expected result

Layout should load

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.44.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.44.0 (like Chrome/80.0.3987.87)
C3 release: r191 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 10 gb
Storage usage (approx): 97 mb (0.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 750 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2020-03-23 11:44
It works fine here. Besides, that setting is not used until you export the project, so it doesn't make any sense. It's probably something else. Try pressing F12 if it fails to load and check for any errors in the console.

**Comment by avishaymizrav** [comment] 2020-03-23 13:13
This is what I get in the devtools console log
![jpg-error](https://user-images.githubusercontent.com/4296822/77320206-d184b780-6d18-11ea-979b-356a2259071c.png)

**Comment by AshleyScirra** [comment] 2020-03-23 13:19
I didn't see that with the attached project. I'm afraid there's very little we can do without a project file that demonstrates the issue.

**Comment by avishaymizrav** [comment] 2020-03-23 13:24
The screenshot is from running the attached project on the nwjs version of C3.
I don't know what else you want me to give you.
I also don't really care if it gets solved, so if you don't either, it's all good.

**Comment by AshleyScirra** [comment] 2020-03-23 16:15
I didn't see you were using the NW.js version of C3. I just tried it in Chrome and it worked fine. I can reproduce with the NW.js version. No idea why it only affects that...

**Comment by AshleyScirra** [comment] 2020-03-23 16:38
It looks like some really weird NW.js bug. However it seems fixed with NW.js 0.45.0-beta1, so it seems like it was already dealt with. It should be fixed when the next NW.js update for C3 comes out. Meanwhile if you don't specifically need NW.js features, you can just test in the Chrome browser where everything works fine.

**Closed by AshleyScirra** 2020-03-23 16:38 UTC
Labels: desktop
