### ISSUE TITLE
Debug view is very slow with worker disabled and 4+ layers.

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#5926] opened 2022-07-25 12:03 UTC
The system view in the debugger is extremely slow when worker mode is disabled. More info
https://www.construct.net/en/forum/construct-3/general-discussion-7/debug-view-extremely-slow-171386

The issue is not happening when there's 1-3 layers in the project (though it might be very minimally happening already at 3) but once you add a 4th layer it drops from 144 to 50ish fps, and with a 5th layer I'm hitting 19fps.

Switching worker on fixed it for me, but other people are still reporting lagging issues regardless. We suspect it possibly has something to do with a new Chrome update.
I'm on **Version 103.0.5060.134 (Official Build) (64-bit)**

From the Chrome performance tab if it's helpful:
https://construct-static.com/images/v1024/uploads/articleuploadobject/0/images/82402/struggle.png
https://construct-static.com/images/v1024/uploads/articleuploadobject/0/images/82403/struggle2.png

## Attach a .c3p

Reproduces in Kiwi story forest map.

## Steps to reproduce

1. Set worker on, preview with debugger
2. Check performance, crisp 144fps
3. Set worker off, preview with debugger
4. Check performance, lightning fast 19fps

## Observed result

Very heavy on performance for some reason

## Expected result

Not such a performance impact

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
I went back to r250 and the issue is still present there

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r304 (beta)
Browser: Chrome 103.0.5060.134
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 285 gb
Storage usage (approx): 1.2 gb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2022-07-26 10:25
I can reproduce. It looks like a performance regression in Chrome. Even updating one or two fields with a lot of otherwise unchanging content in the debug view causes extremely slow layout in the browser.

I filed an issue with Google here: https://bugs.chromium.org/p/chromium/issues/detail?id=1347423
We will follow up there, so closing this issue.

**Closed by AshleyScirra** 2022-07-26 10:25 UTC
Labels: external, chrome

**Comment by dop2000** [comment] 2022-08-10 07:07
@AshleyScirra 
Ian from Google proposed a solution which seems to work.
When I add "overflow: hidden" to propertySectionWrap it immediately improves the performance of System tab!

Could you please test on your end and include this fix into the next beta? It's really difficult to work with debug view now.

**Comment by AshleyScirra** [comment] 2022-08-10 09:39
Yes, their suggested workaround does appear to work. I've added that for the next beta.
