### ISSUE TITLE
Shrinking Popup

### ISSUE THREAD

**Issue by huwpascoe** [Scirra/Construct-3-bugs#2918] opened 2019-05-05 02:09 UTC
## Problem description
Popup window shrinks with every subsequent preview.

## Steps to reproduce
1. Ensure Preview is set to "popup window"
2. Start a new Construct3 session
3. Create a new project
4. Hit F5 to preview
5. Note the window size and close the preview window
6. goto step 4

## Observed result
Every subsequent preview the window shrinks to about 80% of the previous size.

![c3bug](https://user-images.githubusercontent.com/1812087/57187137-b0d62800-6ee2-11e9-9806-2f3841abd6da.png)

## Expected result
Preview windows remain the same size between launches

## More details
**Affected browsers/platforms:**
Chrome, Windows Installed as Web App

## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 74.0.3729.131
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 157 mb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment] 2019-05-10 17:42
This is [a Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=777854) - please star that issue to follow updates. Duplicate of #947, #1059, #1200, #1318, #1987, #2791.

**Comment by AshleyScirra** [comment] 2019-05-10 18:07
Actually given how often this comes up and the slow response to the Chrome bug, I'll try harder to find a workaround. It'll have to be a real hack though, Chrome just creates the window at the wrong size and doesn't provide enough information to identify the amount to correctly offset it by to compensate.

**Comment by Wackytoaster** [comment] 2019-05-13 08:55
Seems like they finally started working on it. Might still be a while until it´s fixed and hits stable though.

**Comment by huwpascoe** [comment] 2019-05-13 14:41
@AshleyScirra My javascript isn't great but something like this?

```
document.getElementById("button").onclick = function ()
{
	const features = "width=500,height=300";
	let wnd = window.open("popup.html", null, features);

	// wait until it's opened somehow

	wnd.postMessage({ x: 500, y: 300 }, '*');
};

// popup.html
window.addEventListener("message", function(event) {
    window.resizeBy(event.data.x - window.innerWidth, event.data.y - window.innerHeight);
});
```

**Comment by AshleyScirra** [comment] 2019-05-13 16:15
I've tried to implement a fix something along those lines but it's really hacky - in particular on high-DPI displays there isn't actually enough information to work out the exact size (the window inner size is in rounded CSS pixels, but resizeBy takes device pixels, so you can't compensate for the amount of size that was lost to rounding error). Still hopefully it's better than it was - let's see how it works for everyone at the next release.

**Comment by TheRealDannyyy** [comment] 2019-05-13 16:54
@AshleyScirra If the hack works, could it be used to workaround this related [NW.js window size issue](https://github.com/nwjs/nw.js/issues/5337) as well?

**Comment by AshleyScirra** [comment] 2019-05-13 18:15
Maybe, the workaround could also apply to crbug.com/677381, but as I mentioned the calculation is lossy on high-DPI displays so it's impossible to work out the exact offset to apply to compensate. It can probably get within a few pixels, but not exact, hopefully that's good enough. This is the kind of hackery we're forced to do when the browser calculates the wrong numbers...

**Comment by AshleyScirra** [comment] 2019-05-20 13:46
The workaround in r150 appears to help in browser mode, but in PWA mode (installed as app) it's not effective because the address bar actually appears after a delay. I've got another hack in for the next release, let's check again when that's out...

**Comment by AshleyScirra** [comment] 2019-05-28 13:11
It seems better in r151, although there can still be much smaller size changes over time. Can anyone confirm it is better? I think that is the best we can do for a workaround anyway - there has been some activity on [the relevant Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=777854) which hopefully is a sign this will be fixed on the Chrome level, and if it's properly fixed it will automatically disable the workaround.

**Comment by TheRealDannyyy** [comment] 2019-05-28 13:46
Works fine on my end. Very accurate and I'd even say pixel-perfect in both browser and PWA mode.

Can we expect the official PWA popup fix to also apply to this? Might be a good idea to give them a heads up once it's fully fixed. (https://bugs.chromium.org/p/chromium/issues/detail?id=677381)

**Comment by AshleyScirra** [comment] 2019-05-28 14:08
Sounds like it's improved so closing. Any further improvements need to be done by Google and any further questions directed to them.

**Closed by AshleyScirra** 2019-05-28 14:08 UTC
Labels: chrome, external
