### ISSUE TITLE
Switching to fullscreen not working

### ISSUE THREAD

**Issue by MonDieu72** [Scirra/Construct-3-bugs#574] opened 2017-06-30 15:02 UTC
## Problem description

Switching to fullscreen using the browser plugin doesn't work

## Attach a .c3p

[project_file](https://www.dropbox.com/s/jr5tmrhodpxen8z/test_rpg.c3p?dl=0)
## Steps to reproduce

1. Preview the project.
2.Try switching to fullscreen by pressing "F" on keyboard or by clicking on green "fullscr" button

## Observed result

Nothing happens, doesn't switch to fullscreen.

## Expected result

The game should switch to fullscreen.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment] 2017-06-30 15:07
Can't reproduce here. In the latest r42.3, both methods correctly switch in to fullscreen mode. Did you miss anything in the steps to reproduce? Are you using any different settings?

**Comment by MonDieu72** [comment] 2017-06-30 15:38
I'm using the same version (42.3). What do you mean "settings"? I'm using the setting that are in the project file.

**Comment by TheRealDannyyy** [comment] 2017-07-03 13:41
I can reproduce this as well. It only occurs when previewing using the _Dialog_ mode.

Here is what the console says about this:
![fullscreen-error](https://user-images.githubusercontent.com/15656049/27795298-d62f679e-6005-11e7-9922-171bab96ca86.PNG)

**Comment by AshleyScirra** [comment] 2017-07-03 16:39
Ah, OK, that was the missing step, it only happens with "dialog" preview mode. I can see the same thing happening now.

Previously it was shown in an iframe that didn't allow fullscreen, so I've enabled fullscreen for the iframe in the next build. However I then ran in to a bug in Chrome where it incorrectly makes the C3 editor go fullscreen instead of the game! I filed the report here: https://bugs.chromium.org/p/chromium/issues/detail?id=738920

Closing this issue as I think we've done everything we need on our end, will follow up at that Chrome report to get it working.

**Closed by AshleyScirra** 2017-07-03 16:39 UTC
Labels: browser, external
