### ISSUE TITLE
Canvas + Mesh

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4649] opened 2021-03-09 11:30 UTC
## Problem description

Related to issue #4645 
I tried moving the second mesh point in relation to the first one, but now it looks like the baseline is shifting and it's even worse.
How do you explain the every other tick event draws it correctly?

## Attach a .c3p

[shadows2.zip](https://github.com/Scirra/Construct-3-bugs/files/6108131/shadows2.zip)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2021-03-09 15:52
Closing as duplicate of #4645. I don't see any evidence Construct is not working correctly. The purpose of filing issues is to fix problems when you have good evidence Construct is not working correctly; if you are not sure how you get your events right, please post to the forum.

**Closed by AshleyScirra** 2021-03-09 15:52 UTC
Labels: duplicate
