### ISSUE TITLE
Error when Preview animation from gif in animation editor

### ISSUE THREAD

**Issue by JonaszO** [Scirra/Construct-3-bugs#6345] opened 2022-12-18 11:07 UTC
## Problem description
Red screen when choose preview animation in aniamtion editor, sprite have one animation with 24 frames (size is less than 256px

## Steps to reproduce

1.add new gif to project by drag and drop from my desktop
2. open sprite with automatically separated frames
3.RMB on animation and choose preview

## Observed result

Red screen pop up

## More details
Error report information
Type: unhandled exception
File: https://editor.construct.net/r322/main.js, line 1025, col 73
Message: Uncaught TypeError: expected string
Stack: TypeError: expected string at O.l (https://editor.construct.net/r322/main.js:1025:79) at C_a.hPb.tva (https://editor.construct.net/r322/projectResources.js:1957:415) at https://editor.construct.net/r322/projectResources.js:256:404 at https://editor.construct.net/r322/main.js:1871:100
Construct version: r322
URL: https://editor.construct.net/r322/
Date: Sun Dec 18 2022 11:58:39 GMT+0100 (czas środkowoeuropejski standardowy)
Uptime: 8429.7 s

**Affected browsers/platforms:** 

Platform information
Product: Construct 3 r322 (beta)
Browser: (unknown) (unknown)
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Language setting: en-US

## System details

<details><summary>View details</summary>
Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by DiegoScirra** [comment] 2022-12-19 11:29
Duplicate of #6332. Will leave open because a few people have reported the same problem already.

**Closed** 2022-12-19 14:25 UTC
Labels: duplicate
