### ISSUE TITLE
Right click crash in Chrome

### ISSUE THREAD

**Issue by rilem** [Scirra/Construct-3-bugs#1239] opened 2018-01-25 09:01 UTC
## Problem description

Right clicking causes the editor to crash. Even without a project open!

## Attach a .c3p

No project is required to trigger the crash.

## Steps to reproduce

1. Open https://editor.construct.net/
2. Right click anywhere
3. Crash

## Observed result

Oops something went wrong window pops up

## Expected result

Right click context menu

## Affected browsers

* Chrome: yes
* Safari: no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/, line 1, col 784
Message: Uncaught ReferenceError: o is not defined
Stack: ReferenceError: o is not defined at HTMLDocument.document.addEventListener.t (:1:784)
Construct 3 version: r81
URL: https://editor.construct.net/
Date: Thu Jan 25 2018 09:57:04 GMT+0100 (CET)
Uptime: 3.1 s

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_0
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r81
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by rilem** [comment] 2018-01-25 09:54
Tried running the editor in safe mode but the crash still occurs.
I'm currently working in Safari where the bug does not appear.

**Comment by AshleyScirra** [comment] 2018-01-25 11:26
Duplicate of #1238

**Closed** 2018-01-25 11:27 UTC
Labels: duplicate
