### ISSUE TITLE
Crash duplicating layout with global layer (regression r283)

### ISSUE THREAD

**Issue by LoicBlumgi** [Scirra/Construct-3-bugs#5508] opened 2022-03-01 17:13 UTC
Duplicate layout make C3 crash Edit:( when a layer is global)

## Attach a .c3p
[BlumgiStickman.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8163411/BlumgiStickman.c3p.zip)

## Steps to reproduce

1. Right Click on Layout1 and duplicate 
2. 
3.  

## Observed result

 C3 Crash when duplicate a layout that has a global layer in it.

## Expected result

 Duplicate the layout

## More details

Mac Chrome r285

It works without issues on Firefox

**Affected browsers/platforms:**  Chrome

 
**First affected release:** r285 it's a new file created on r285

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: can not set global property of overriden layer @ Error: can not set global property of overriden layer at d.n2 (https://editor.construct.net/r285/projectResources.js:1188:325) at d.pNb (https://editor.construct.net/r285/projectResources.js:1211:390) at d.Sg (https://editor.construct.net/r285/projectResources.js:1211:286) at d.Ga (https://editor.construct.net/r285/projectResources.js:1212:37) at d.SLb (https://editor.construct.net/r285/projectResources.js:1212:63) at d.xfb (https://editor.construct.net/r285/projectResources.js:1170:440) at d.I5b (https://editor.construct.net/r285/projectResources.js:1167:439) at async https://editor.construct.net/r285/components/bars/projectBar/projectBar.js:40:131
Stack: Error: can not set global property of overriden layer at d.n2 (https://editor.construct.net/r285/projectResources.js:1188:325) at d.pNb (https://editor.construct.net/r285/projectResources.js:1211:390) at d.Sg (https://editor.construct.net/r285/projectResources.js:1211:286) at d.Ga (https://editor.construct.net/r285/projectResources.js:1212:37) at d.SLb (https://editor.construct.net/r285/projectResources.js:1212:63) at d.xfb (https://editor.construct.net/r285/projectResources.js:1170:440) at d.I5b (https://editor.construct.net/r285/projectResources.js:1167:439) at async https://editor.construct.net/r285/components/bars/projectBar/projectBar.js:40:131
Construct 3 version: r285
URL: https://editor.construct.net/
Date: Tue Mar 01 2022 18:12:07 GMT+0100 (heure normale d’Europe centrale)
Uptime: 868.6 s

Platform information
Browser: Chrome
Browser version: 98.0.4758.109
Browser engine: Chromium
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_7
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36
C3 release: r285 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1, OpenGL 4.1 Metal - 71.7.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by AshleyScirra** [comment] 2022-03-02 11:11
@DiegoScirra - looks like a regression in r283. I suspect it was caused by fix to #5402 (rev 16645). The fix looks like it changed how instances are copied, but also altered a code path that managed how the global setting is copied. We should probably stable patch this.

**Comment by DiegoScirra** [comment] 2022-03-02 12:30
Will be fixed in the next release.

**Closed by DiegoScirra** 2022-03-02 12:30 UTC
