### ISSUE TITLE
"b" shortcut adds two blank subevents instead of one.

### ISSUE THREAD

**Issue by oosyrag** [Scirra/Construct-3-bugs#118] opened 2017-04-23 06:16 UTC
## Problem description

When using the keyboard "b" shortcut, two blank subevents are added instead of one. When using the right click context menu to add a blank subevent, only one is added as expected.

## Affected browsers

* Chrome: yes
* Firefox: n/a
* Edge: n/a
* Safari: n/a

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.81
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36

Local storage
Storage quota (approx): 2.2 gb
Storage usage (approx): 130 mb (5.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 7800 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by oosyrag** [comment] 2017-04-23 09:05
Noticed after when navigating events by arrow keys, each keypress would also act as if pressed twice.

Unable to reproduce... this issue did not occur after opening a new C3 tab, within the same browser window/session. The existing tab still kept the bug. Even when saving the project in the old tab, opening it again in a new tab did not reproduce the double keypress behavior.

There must have been some action done on the original tab that triggered this bug, but I'm not sure what exactly...

**Comment by pixelmetal** [comment] 2017-04-23 17:10
This also occurs when launching C3 from a desktop link, as noted here: https://github.com/Scirra/Construct-3-bugs/issues/85

**Comment by tunepunk** [comment] 2017-04-24 11:54
I'm also having the same problem, on Mac.

**Comment by AshleyScirra** [comment] 2017-04-28 12:17
I still can't reproduce this. If I just open Ghost Shooter and add a blank sub-event to every single event, it correctly adds just one every time. If I navigate with arrow keys, it works correctly with no double-presses appearing to be happening. Presumably there is something you are doing before that causes the bug. This probably won't be fixed until someone can figure out what that is.

**Comment by oosyrag** [comment] 2017-04-29 03:46
I've had it occur in a brand new project now. Will keep exploring to try to reproduce.

**Comment by IJCT95** [comment] 2017-05-03 21:35
can reproduce, i tried on a new blank project and it works, it creates 2 blank sub events

**Comment by AshleyScirra** [comment] 2017-05-08 15:04
There is nothing that sounds different about your approach, but it's possible there's something you're doing beforehand that "enables" the bug - can you identify any prior actions that might cause it? Does it still reproduce if you open a fresh C3 window and immediately use a keyboard shortcut?

**Comment by neverk** [comment] 2017-05-09 18:59
Can reproduce. Creates 2 blanks with B and two elses with X

**Comment by Kyatric** [comment] 2017-05-12 16:01
Steps to reproduce in R26 

1. Create new project
2. In event sheet make a new group (Group 1/keep default names for all the following, it works)
3. Create on start of layout as sub-event of the group
4. Create a global variable
5. Create an action add to variable
6. Create an action substract from
7. Clone actions in order to have three or more (I did it with 5)
8. Go in the layout view
9. Create a new sprite
10. Open a texture from a file. 
11. Close the animation editor.
12. Open the sprite again in the animation editor.
13. Open the texture again from the same file.
14. Go back into the event sheet, the skipping bug happens/b pressed twice and so on.

**Comment by AshleyScirra** [comment] 2017-05-12 16:15
Can reproduce! Thanks for finding repro steps @Kyatric .

Assigning to @DiegoScirra - on initial investigation it looks like the Animations Editor keyboard shortcut handler is still active after it's been closed, and it forwards keyboard input back to the windowing system causing all key presses to be registered twice.

**Comment by AshleyScirra** [comment] 2017-05-12 16:17
Quicker repro

1. Open Ghost Shooter
2. Open event sheet, use up & down arrow keys, verify moves 1 at a time
3. Edit Player sprite
4. Import image from disk
5. Close animations editor
6. Edit Player sprite again
7. Import same image from disk
8. Close animations editor again
9. Go to event sheet and use up & down arrow keys again, should be skipping 2 at a time now

**Comment by DiegoScirra** [comment] 2017-05-15 13:37
Fixed in r28.

Turns out the document level keyboard events the Animations Editor uses, were not being removed on close.

**Closed by DiegoScirra** 2017-05-15 13:37 UTC
Labels: confirmed
