### ISSUE TITLE
C3 crash randomly without crash report, only dump.log

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#2819] opened 2019-04-06 15:16 UTC
## Problem description

C3 desktop version Construct3-win64-c73-stable crashed on my desktop today 5 times within 20 minutes randomly without any crash report, just everything closes. I did have Construct 3 opened on my laptop as well as I needed some code from another project and this was the easiest way of checking.

The dump.log contains the following:
[0406/180132.665:WARNING:minidump_to_upload_parameters.cc(67)] duplicate annotation name metrics_client_id, discarding value 56873513dff244cb87afde70fd200f39
[0406/180132.676:ERROR:http_transport_win.cc(178)] WinHttpCrackUrl: The operation completed successfully. (0x0)
[0406/181049.823:WARNING:minidump_to_upload_parameters.cc(67)] duplicate annotation name metrics_client_id, discarding value 56873513dff244cb87afde70fd200f39
[0406/181049.829:ERROR:http_transport_win.cc(178)] WinHttpCrackUrl: The operation completed successfully. (0x0)

Even though it crashed ~ 5 times, it added only 2 entries.

## Attach a .c3p

Use a blank project.

## Steps to reproduce

Last time it crashed was when I closed the preview. Another time without me doing anything than starting the preview. No repo steps.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 518 gb
Storage usage (approx): 93 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon 550 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by JeFawk** [comment] 2019-04-07 18:04
Still happening 1 out of 5 previews today (Sunday). My report was made Saturday. Getting a bit hard to work.
The crash made no addition to the debug.log.

**Comment by AshleyScirra** [comment] 2019-04-08 10:23
Tried previewing a new empty project 10 times and it worked fine. I'm afraid there's nothing we can do unless we can reliably reproduce the problem. Also the log messages do not appear to be at all relevant. If the issue does not reproduce in Chrome this would suggest a NW.js bug rather than an issue with Construct.

**Comment by JeFawk** [comment] 2019-04-08 10:28
I'll try in Google Chrome directly and see if it happens though a NW.js bug appearing out of the blue after so many months of daily usage is unlikely.

**Comment by AshleyScirra** [comment] 2019-04-08 10:32
We've had cases of NW.js introducing crash bugs in the past.

**Comment by JeFawk** [comment] 2019-04-08 10:43
Hoping to find out today if it happens with the Web version because it's hard to not use the desktop version due to Save as Project folder for repository which is amazing.

**Comment by JeFawk** [comment] 2019-04-08 11:11
This happens with the web version of C3 as well. 

I loaded Demonoire and started 4 remote previews. I updated the project a few times and refreshed 3 times more (so updated the project about 4 times, refreshed 12ish). 1 out of 4 clients stopped with the Connected to Host and the Client disconnected notification.

![image](https://user-images.githubusercontent.com/7268697/55719892-0b758480-5a08-11e9-836b-7d336f3f8a73.png)

I can send more info from the console log such as network perhaps, you'll have to point which though, I'm kinda clueless, thanks.

**Comment by AshleyScirra** [comment] 2019-04-08 12:40
It's always useful to provide any errors that appear in the browser console (press F12).

It's not clear that this is the same problem as mentioned in your original report though. The Remote Preview issue looks like it might be a networking issue, which wouldn't be applicable to local preview; also if the browser/app just closes that generally indicates the browser engine crashed.

**Comment by ACC-Math** [comment] 2019-04-08 12:56
Hello. It might have happened to me earlier today with desktop version too, but since there was no crash report, I thought I made something wrong. Anyway : C3 was here, and then I clicked somewhere and C3 was not here anymore in a blink.
I'll bring attention to this if it happens again.

**Comment by JeFawk** [comment] 2019-04-08 12:58
I will open up another bug regarding the remote preview issue. It might not be related at all indeed.

**Comment by JeFawk** [comment] 2019-04-08 14:20
I remember at some point before a crash seeing a glimpse of an error in the log something with Transport Closed.

@ACC-Math are you using a Tween behavior by any chance?

**Comment by JeFawk** [comment] 2019-04-08 14:29
Use remote preview and check #2825 I couldnt reproduce it again but it happened in 3 different projects. I came to the conclusion that the engine was receiving info about a sprite that was just destroyed, and tried to do somet tween stuff with it. I'm guessing mid-way of going through the tween function, the object was destroyed.

This was freezing the remote preview but C3 editor was still up.

**Comment by shortercode** [comment] 2019-04-11 12:56
Referring to the original issue, I have recently updated NW.js to same as OP on my debug build and it is frequently doing a CTOD when exiting JS breakpoints. Might not be related, but thought it worth mentioning.

**Comment by AshleyScirra** [comment] 2019-04-11 13:01
I don't think there's any action we can take over the NW.js crash issue here, so closing (this issue has already become muddied with various different problems anyway). It's likely an NW.js issue so outside of our control - you could try reporting it to the NW.js developers, but like us they'd need reliable steps to reproduce the problem. It might sort itself out in a future NW.js update too...

**Closed by AshleyScirra** 2019-04-11 13:01 UTC
Labels: can't reproduce

**Comment by JeFawk** [comment] 2019-05-04 18:11
This is till happening with the Desktop crash. It seems to be related to starting the preview only. Remote preview bypasses the crash.
I've added this idea if you'd like to consider it: https://construct3.ideas.aha.io/ideas/C3-I-892
The only thing stopping me at least from using the web app is the lack of export as project option.

Thanks.

**Comment by JeFawk** [comment] 2019-05-04 18:12
The Desktop app crash is still occurring ~ 3-4 times during an 8h session per day. 

It seems to be related to starting the preview only. Remote preview bypasses the crash.
I've added this idea if you'd like to consider it @AshleyScirra  : https://construct3.ideas.aha.io/ideas/C3-I-892
The only thing stopping me at least from using the web app is the lack of export as project option.

Thanks.

**Comment by JeFawk** [comment] 2019-05-04 18:30
Also this appeared in the dump.log after the latest desktop app crash:

[0406/180132.665:WARNING:minidump_to_upload_parameters.cc(67)] duplicate annotation name metrics_client_id, discarding value 56873513dff244cb87afde70fd200f39
[0406/180132.676:ERROR:http_transport_win.cc(178)] WinHttpCrackUrl: The operation completed successfully. (0x0)
[0406/181049.823:WARNING:minidump_to_upload_parameters.cc(67)] duplicate annotation name metrics_client_id, discarding value 56873513dff244cb87afde70fd200f39
[0406/181049.829:ERROR:http_transport_win.cc(178)] WinHttpCrackUrl: The operation completed successfully. (0x0)
[0504/210159.876:ERROR:http_transport_win.cc(178)] WinHttpCrackUrl: The operation completed successfully. (0x0)
[0504/212711.665:WARNING:minidump_to_upload_parameters.cc(67)] duplicate annotation name metrics_client_id, discarding value 56873513dff244cb87afde70fd200f39
[0504/212711.674:ERROR:http_transport_win.cc(178)] WinHttpCrackUrl: The operation completed successfully. (0x0)

Can't call the desktop stable anymore really, simply can't use it.
