### ISSUE TITLE
Admob Problems (again)

### ISSUE THREAD

**Issue by blindcrowgames** [Scirra/Construct-3-bugs#1035] opened 2017-11-24 03:52 UTC
## Problem description

I'm having problems again with Advert object. I've submitted an Issue about this few days ago, and the problem was at minify script process. You said in r69 I would not have this problem, I saw the update and I've tried but, it's still the same. I'm having the "black screen" again and if I want to export for Xcode project, the builder says Build Failure and mark me an error in Admob Plugin. The difference now is that I can't build for IOS WITHOUT minify, it's the same both options. I'm still able to build an Android APK WITHOUT minify. I'm leaving the project below.

## Attach a .c3p

https://www.dropbox.com/s/1i4p3jclexalhjk/admobtest24-11.c3p?dl=0

## Steps to reproduce

1. Export for Android (Cordova Project), Build it with Cordova.
2. Install APK in Android Device.

## Observed result

I observed Black screen and nothing happened. 

## Expected result

Game Start Layout and Interstitial shows up.

## Affected browsers

No browsers

## System details

<details><summary>View details</summary>

</details>

**Comment by shortercode** [comment] 2017-11-24 11:18
I expect there's a different minification bug, I'll look into it.

When you say you can't build an xcode project, do you mean making the xcode project using C3 or do you mean building to a device in xcode? I managed to make an xcode project with your c3p fine.

**Comment by blindcrowgames** [comment] 2017-11-24 11:45
There is no problem with export process in C3, I can generate Xcode project and open it at Xcode. The build failure is when I'm trying tu run the project over my Iphone or Ipad. Xcode says: Swift Compiler Error, and mark "Include of non-modular header inside framework 'GoogleMobileAds'" in this lines:

#import <GoogleMobileAds/GoogleMobileAdsDefines.h>

#import <GoogleMobileAds/GADAdNetworkExtras.h>
#import <GoogleMobileAds/GADAdSize.h>
#import <GoogleMobileAds/GADAudioVideoManagerDelegate.h>
#import <GoogleMobileAds/GADAudioVideoManager.h>
#import <GoogleMobileAds/GADBannerView.h>
#import <GoogleMobileAds/GADBannerViewDelegate.h>
#import <GoogleMobileAds/GADCorrelator.h>
#import <GoogleMobileAds/GADCorrelatorAdLoaderOptions.h>
#import <GoogleMobileAds/GADDebugOptionsViewController.h>
#import <GoogleMobileAds/GADExtras.h>
#import <GoogleMobileAds/GADInAppPurchase.h>
#import <GoogleMobileAds/GADInAppPurchaseDelegate.h>
#import <GoogleMobileAds/GADInterstitial.h>
#import <GoogleMobileAds/GADInterstitialDelegate.h>
#import <GoogleMobileAds/GADMediaView.h>
#import <GoogleMobileAds/GADMobileAds.h>
#import <GoogleMobileAds/GADNativeExpressAdView.h>
#import <GoogleMobileAds/GADNativeExpressAdViewDelegate.h>

**Comment by shortercode** [comment] 2017-11-24 11:47
Oh yeah I got that yesterday, seems to be a cocoapods bug, I ran update on the dependencies locally and it fixed itself. I expect I need to go tinker with the build server.

**Comment by shortercode** [comment] 2017-11-24 14:37
Okay I've patched and tested the minified version of my full mobile advert test project and Android and seems to be running fine. So that should be sorted whenever we reach r70 ( properly this time ). Going to take a look at the build server now.

**Comment by shortercode** [comment] 2017-11-24 15:56
@blindcrowgames I presume your using the inbuilt archive utility on your mac?

**Comment by blindcrowgames** [comment] 2017-11-24 23:52
Do you meant Xcode?

**Comment by KENYONBcom** [comment] 2017-11-25 00:43
I am also having an issue building an iOS archive in Xcode with the new Mobile Advert plugin.

When I try to build, I get 19 errors, all related to:
"Include of non-modular header inside framework module 'GoogleMobileAds':"

If I use the same C3 project, but remove the Advert plugin from the project and export and build in Xcode, it will build an archive without issues.

I am not using minify.

It has worked with Android Studio projects. Only issue is with iOS builds.

**Comment by blindcrowgames** [comment] 2017-11-28 03:57
There is any update about this? Thank you!

**Comment by shortercode** [comment] 2017-11-28 11:07
Sorry I meant to reply the other day, but I forgot to press submit!

The issue is that we're not storing the symlinks in the zip file correctly, I'm working on a patch for the library we use for making zip files but it's a bit of a pain testing the structure of zip files.

**Comment by KENYONBcom** [comment] 2017-11-29 00:44
I am getting the same error with r70.2
Export and build archive and error "Include of non-modular header inside framework module 'GoogleMobileAds':"

I thought release notes indicated this was solved?
or does it only work if you use minify?

**Comment by KENYONBcom** [comment] 2017-11-29 01:23
I just tested using minify and that also gave the same error.

When can we expect this to work properly?

**Comment by shortercode** [comment] 2017-11-29 15:09
@KENYONBcom this issue is tracking 2 related bugs:

1. Exporting a project with the Mobile Advert plugin to Android with minification enabled would produce an APK that when run would only show a black screen. This was fixed around 5 days ago and should now have been published.

2. Exporting a project with the Mobile Advert plugin to an xcode project would produce a project that would not build. This a problem with the build server not archiving symlinks correctly, which I believe as of yesterday I have a fix for but I haven't updated the server yet. Mainly because I have other pending changes to the build server which I wish to publish at the same time, that are not complete yet. This shouldn't require a new C3 release to be fixed.

**Comment by KENYONBcom** [comment] 2017-11-29 18:00
@shortercode Understood and thanks for the reply. I'm looking forward to a successful build in Xcode once you update the build server.

Will you notify us once here once you publish the changes that fix the issue?

**Comment by shortercode** [comment] 2017-11-29 18:20
Yeah I'll post here once the fix is up, given it's the major part of this issue I wouldn't close it before the patch was up and working.

**Comment by shortercode** [comment] 2017-11-30 18:18
Okay the server patch went up today, seems to be working for me. Can you guys sanity check it please?

**Comment by blindcrowgames** [comment] 2017-11-30 18:19
I will, just give me some minutes

**Comment by blindcrowgames** [comment] 2017-11-30 18:27
<img width="1018" alt="screen shot 2017-11-30 at 3 26 48 pm" src="https://user-images.githubusercontent.com/33832212/33447771-f4935350-d5e2-11e7-8f33-d5d8dbfc47c0.png">

I got this error now.

**Comment by blindcrowgames** [comment] 2017-11-30 18:36
I got the same without minification. . .

**Comment by shortercode** [comment] 2017-11-30 19:34
That looks different to the issue you reported before, I haven't seen that in my testing at all... Do you still see any warnings along the line of "Include of non-modular header inside framework 'GoogleMobileAds'"? Also I presume your using the xcode workspace file not the xcode project file?

**Comment by KENYONBcom** [comment] 2017-12-01 01:12
I just exported from C3 and tried to build in Xcode and got the same error "Include of non-modular header inside framework module 'GoogleMobileAds':"

Still not working.

Are there any manual steps we can take to get around this? Or do you want to try to update build server again?

**Comment by blindcrowgames** [comment] 2017-12-01 02:10
@shortercode I've tried opening .xcodeproj file that C3 gave me. No, I haven't had errors at 'GoogleMobileAds', the only one is 'Apple Mach-O Linker (Id) Error. I'm attaching both projects, first one with minification, and second one without it.

[admobtest.ios.project_minified.zip](https://github.com/Scirra/Construct-3-bugs/files/1520169/admobtest.ios.project_minified.zip)

[admobtest.ios.project _not_minified.zip](https://github.com/Scirra/Construct-3-bugs/files/1520171/admobtest.ios.project._not_minified.zip)

and this is the C3 project:

[admobtest_01_12.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1520174/admobtest_01_12.c3p.zip)

**Comment by shortercode** [comment] 2017-12-04 12:12
@KENYONBcom The issue is that some of the files within the project need to be symlinks. Before the server was replacing these symlinks with the files they pointed to, which kinda worked but it broke xcode when it tried to build. So I fixed the server so that it stores the symlinks correctly in the zip file. It's possible that whatever your using to expand the zip file is also removing the symlinks. A good check is that all the files within `/Pods/Public/Google-Mobile-Ads-SDK/GoogleMobileAds/` should be symlinks.

When you get your zip file of your project how do you normally go about loading it? 

For reference; symlinks are kinda like windows shortcuts, a special file pointing to another file. Symlinks appear with a little arrow over the icon in macOS. 

A workaround is to run the command "pod update" on the project directory, this will reinstall the dependency locally. You will need [cocoapods ](https://cocoapods.org/) installed.

**Comment by KENYONBcom** [comment] 2017-12-04 14:58
@shortercode I am using the default Archive Utility.app to extra the file.
Thanks for pointing out the location of the symlinks because I think I was able to find what was causing the problem....
Immediately after extracting, everything in /Pods/Headers/Public/Google-Mobile-Ads-SDK is a symlink. Then, if I check again after a few minutes, they are replaced with the actual files. This is because I have my project saved in Dropbox, which automatically resolves symlinks with the actual files. I'll have to test again running the project from my desktop.

**Comment by shortercode** [comment] 2017-12-04 15:20
Ah that's an interesting gotcha, I'm hoping if you load your project outside of a Dropbox synced folder that it will be buildable. Mainly because I don't have anything else obvious to fix in this area at the moment!

I've checked online and it seems to be a point of tension with developers that Dropbox behaves unpredictably when given symlinks. I'm not sure what is best to suggest for allowing you to continue using Dropbox in this fashion, expect maybe storing the project in some form of archive file on dropbox that respects symlinks.

**Comment by KENYONBcom** [comment] 2017-12-05 02:58
@shortercode a very interesting gotcha and frustrating indeed. I can confirm that it was definitely DropBox causing the issue and I was able to successfully build the archive and export the app for testing.

Now my only issue is that the Banner ad won't show on iOS, but the Interstitial shows.
Both Banner and Interstitial work on Android.
The plugin is not set to test mode.

I have it set to display the same as I do for Android. On Start of Layout...
+ System: Is on platform iOS
-> MobileAdvert: Set application ID to "ca-app-pub-###"
-> MobileAdvert: Create banner advert "ca-app-pub-###" size: Smart landscape show: true
-> MobileAdvert: Create interstitial advert "ca-app-pub-###" show: false

Any idea why the banner ad wont show?

**Comment by KENYONBcom** [comment] 2017-12-05 02:59
@blindcrowgames i got the same Apple Mach-O Linker (Id) Error after I figured out the Dropbox issue, and all I did was quit Xcode, restart, clean the project, build again, and it worked. Seems to be a phantom bug others have experienced.

**Comment by KENYONBcom** [comment] 2017-12-08 02:40
Update, I am pretty certain banner ads are working for iOS. Although they didnt show on my device, when I submit to the app store, impressions appeared in Admob. Also, when they rejected my game, the screenshots they sent from an ipad clearly showed banner ads on the bottom.

**Comment by shortercode** [comment] 2017-12-11 11:58
Sorry for the slow reply, I had the last week off.

I can't say I've experienced the banner adverts not showing. I thought perhaps it was related to the banner size. There's a warning on the admob android documentation that says:

> Note: The size of the container in which you place your ad must be at least as big as the banner. If your container has padding, that effectively decreases the size of your container. In the event that the container cannot fit the banner ad, the banner will not appear, and you will get this warning in the logs:
> `W/Ads: Not enough space to show ad. Needs 320x50 dp, but only has 288x495 dp.`

There's no such warning on the iOS documentation, but I expect the same is true. However, if your using smart landscape / portrait it shouldn't matter. Have perhaps tried it on a few different size simulators?

**Comment by KENYONBcom** [comment] 2017-12-13 00:40
I'm using smart landscape and was testing on an iPod Touch. (I own an Android phone). The Apple review testers were using iPads and they showed me screen captures that had the ads on the bottom.

I use smart landscape for Android and it shows fine.

Anybody want to touch my rejected IPA file and see if you see the ads?
https://www.dropbox.com/s/q7m4myuu8vv9zpy/Runny%20Butt.ipa?dl=0

**Comment by shortercode** [comment] 2018-01-09 17:40
Mmmm I don't have an iPod touch to test with, and it doesn't seem to be possible to simulate one on xCode. I tried the 5s simulator, thinking that would be closest size wise and didn't see any problem. I recall doing some testing on an old iPad while I was writing the plugin. The banner adverts used a surprising amount of resources, and hence took a fair while to load on a older device. Might be that causing problems for you?

I think we've solved the original issue here, and I can't reproduce this banner issue. If the device is just churning and taking a long time to do anything then I don't think I'll be able to do much anyway :/

If you find another way for me to reproduce this please open a new issue and I'll revisit.

**Closed by shortercode** 2018-01-09 17:40 UTC
Labels: fixed, need info

**Comment by KENYONBcom** [comment] 2018-01-10 00:42
@shortercode Agreed the original issue is solved and case closed.

I just tested the game again and banner ads and interstitials finally loaded. Not sure why they're working now, but I can confirm they are.

Thanks for working on this.

**Comment by shortercode** [comment] 2018-01-10 11:51
Well I'm glad to hear that it's working now! No worries, thanks for answering my questions.
