### ISSUE TITLE
xMouse & yMouse doesn't work properly in iFrame

### ISSUE THREAD

**Issue by Gildas44** [Scirra/Construct-3-bugs#3750] opened 2020-04-07 15:52 UTC
## Problem description

Bcs it's important for me, I took a lot of time to present you as well as possible with different exportations here : 

https://www.logicieleducatif.fr/divers/test/scirra02.php
This is with the Build R189.2
You'll find (with the buttons) a version with R182.4 build where xMouse & yMouse are good in the iFrame

(R148 & R164.3 & R171 are good too)

## Attach a .c3p

[survolExposure2.zip](https://github.com/Scirra/Construct-3-bugs/files/4445323/survolExposure2.zip)
[182.4.zip](https://github.com/Scirra/Construct-3-bugs/files/4445597/182.4.zip)

## Steps to reproduce

**1. Go to the R189.2 BUILD VERSION AND SEE XMOUSE AND YMOUSE (iFrame : not work)**
2. Go to the R189.2 BUILD VERSION AND SEE XMOUSE AND YMOUSE (fullScreen : it works)
3. Go to the R182.4 BUILD VERSION AND SEE XMOUSE AND YMOUSE (iFrame : it works)

## Observed result
When the mouse is at the top left of the scene, it writes xMouse:664 &yMouse:167

## Expected result
When the mouse is at the top left of the scene, it should write xMouse:0 &yMouse:0

## More details

**Affected browsers/platforms:** 

**First affected release:** 
works in r184.3 but broke in r189.2 
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2020-04-08 11:14
Duplicate of #3748.

Please note our bug report guidelines ask that you test the latest version (currently r194) since otherwise you may end up reporting issues that were already fixed.

**Closed by AshleyScirra** 2020-04-08 11:14 UTC
Labels: duplicate
