### ISSUE TITLE
Camera Permission is not granted

### ISSUE THREAD

**Issue by jagoman85** [Scirra/Construct-3-bugs#1261] opened 2018-02-02 17:41 UTC
## Problem description

When exporting a game as an APK (signed or unsigned) with a Camera / UserMedia component, the camera is not displayed on the Android device. No prompt is given, even though the 'require camera permission' checkbox was checked when exporting.

## Attach a .c3p

Please use the "Camera Input" demo from the start page of Construct 3

## Steps to reproduce

1. Open the "Camera Input" demo from C3 Start Page
2. Export to "Android (Cordova)"
3. Keep Export Options unchecked
4. Select "Debug APK" in the Android build drop down option
5. Ensure "Require Camera permission" is checked, then click Next
6. Transfer the exported Debug APK onto a device.
7. Install it, and open it
8. See that no prompt for camera permission is given, and the camera therefore can not be used.

## Observed result

No Camera Permission prompt is shown when loading the APK, so camera can not be used

## Expected result

A Camera Permission prompt should show, allowing access to the devices camera(s)

## Affected browsers

* APK: YES
* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

**Comment by shortercode** [comment] 2018-02-05 13:02
I can confirm this. @AshleyScirra do you remember anything related to this? Looks like any device with android 6+ permission model wouldn't allow getusermedia, unless it's been granted to a native plugin already ( dynamically ). The workarounds look... painful.

**Comment by AshleyScirra** [comment] 2018-02-05 15:21
Currently ticking "require camera permission" simply maps to adding the `cordova-plugin-camera` plugin, which IIRC is because Cordova's latest advice on enabling permissions is not actually to specify the permissions, but to just add a corresponding plugin which handles the permissions stuff automatically. They could have changed it again though, and Android 6 changed how the whole permissions model work, and then on top of that it depends on the target SDK version. Finally I'm not sure how permissions requested by a webview actually work. So, not sure what we need to do about this...

**Comment by shortercode** [comment] 2018-02-05 16:06
Yeah I had seen that and from what I read that does work. However, we're using the inbuilt `getUserMedia` instead of the plugin, which doesn't seem to trigger the permission request. If we used the `navigator.camera` object the plugin exposes to do something it would ask the user for permission and then `getUserMedia` would work correctly.

I've looked at the workarounds and [this plugin](https://github.com/dpa99c/cordova-diagnostic-plugin) allows you to request permission at runtime from JS, among other things.

**Comment by AshleyScirra** [comment] 2018-02-05 16:42
It's a huge pain to have to rewrite code to use a different set of APIs in a completely-compatible way. I don't want to change any of the existing code, looking in to explicitly requesting permission might be a better path.

**Comment by shortercode** [comment] 2018-02-07 11:39
The plugin I linked previously would allow us to request and check camera permissions, provided it works.

**Comment by shortercode** [comment] 2018-06-27 11:08
Okay should be resolved in the next release.

**Closed by shortercode** 2018-06-27 11:08 UTC
