### ISSUE TITLE
C3 Crashes when opening project when opening it in r177

### ISSUE THREAD

**Issue by gberenst** [Scirra/Construct-3-bugs#3502] opened 2019-11-25 19:10 UTC
## Problem description

We were working without any problem with our c3p file until r176. After updating to r177 it crashes. You can find the crash message at the bottom of this entry.

C3P: https://drive.google.com/open?id=1jeuUBjkqCck3nsdpiysZRrC9vevgYZ3v
[](https://drive.google.com/open?id=1jeuUBjkqCck3nsdpiysZRrC9vevgYZ3v)

## Steps to reproduce

1. Open project from any of the available ways: dragging and dropping into C3, open local file, or double click from windos file explorer.
2. It loads the project.
3. When finished loading, it crashes and shows the error message.

## Observed result

This:
![image](https://user-images.githubusercontent.com/48917913/69570067-c9e91800-0f9d-11ea-9fba-1610f44b15a0.png)

## Expected result

I expected it to be opened like usual.

## More details

Here´s the error message:

Error report information
Type: assertion failure
Message: unsupported path mode
Stack: Error at Function.ǃDCO (https://editor.construct.net/r177/main.js:2:125274) at e (https://editor.construct.net/r177/main.js:2:85003) at https://editor.construct.net/r177/main.js:2:85333 at Function.ǃMuj (https://editor.construct.net/r177/projectResources.js:1:455787) at a.ǃKO (https://editor.construct.net/r177/projectResources.js:1:431841) at a.ǃKO (https://editor.construct.net/r177/projectResources.js:1:496868) at a.ǃ_PT (https://editor.construct.net/r177/projectResources.js:1:434706) at a.ǃ_PT (https://editor.construct.net/r177/projectResources.js:1:502214) at a.ǃae (https://editor.construct.net/r177/projectResources.js:1:502520) at Function.ǃMf_ (https://editor.construct.net/r177/projectResources.js:1:504142)
Construct 3 version: r177
URL: https://editor.construct.net/r177/
Date: Mon Nov 25 2019 16:02:06 GMT-0300 (hora estándar de Uruguay)
Uptime: 35 s

Platform information
Browser: Chrome
Browser version: 78.0.3904.97
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
C3 release: r177 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R7 Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by BertConstanty** [comment] 2019-11-26 06:35
Same here, i worked yesterday fine, when reopen it this morning, crash...

reagards

**Comment by BertConstanty** [comment] 2019-11-26 06:37
just a precision, yesterday, i could open and work on r177... it is the reopen that crash it this morning with same message as upper

**Comment by DiegoScirra** [comment] 2019-11-26 13:58
This will be fixed in the next beta.

The problem is that there is a mistake on how r177 saves timelines, so you can open a file saved in a previous version, but when you save it, then the project enters an invalid state and can't be open again.

**Closed by DiegoScirra** 2019-11-26 13:58 UTC

**Comment by gberenst** [comment] 2019-11-26 14:00
Thank you Diego. Let's wait for next version then.
