### ISSUE TITLE
Unexpected "Cannot read property 'style' of null" crash 

### ISSUE THREAD

**Issue by NoSoul8** [Scirra/Construct-3-bugs#1162] opened 2018-01-10 21:46 UTC
## Problem description

After r76-2 installed today, i got 2 or 3 little popups "Cannot read property 'style' of null" during normal workflow actions ( adding sprites, editing events etc ). Soon after it a crash appeared, details and a screenshot are below.

I've noticed this (https://github.com/Scirra/Construct-3-bugs/issues/1151) issue tracked, so it is worth mentioning that i use dark C3 theme.

## Attach a .c3p

![darkerror](https://user-images.githubusercontent.com/34763413/34797103-cef9852a-f670-11e7-9020-3474337d96fb.PNG)

## Affected browsers

* Chrome: yes

## System details

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'style' of null @ TypeError: Cannot read property 'style' of null at ǃs.ǃ_.Notification.ǃsdw (https://editor.construct.net/r76-2/main.js:54:7522) at ǃs.ǃ_.Notification.ǃsdg (https://editor.construct.net/r76-2/main.js:54:6327) at Function.ǃsdN (https://editor.construct.net/r76-2/main.js:54:2415) at new ǃs.ǃ_.Notification (https://editor.construct.net/r76-2/main.js:54:5157) at Function.ǃs.ǃo (https://editor.construct.net/r76-2/main.js:2:208436) at Function.ǃsT (https://editor.construct.net/r76-2/main.js:54:8447) at window.ǃYnT.ǃQu (https://editor.construct.net/r76-2/main.js:168:47777) at 
Stack: TypeError: Cannot read property 'style' of null at ǃs.ǃ_.Notification.ǃsdw (https://editor.construct.net/r76-2/main.js:54:7522) at ǃs.ǃ_.Notification.ǃsdg (https://editor.construct.net/r76-2/main.js:54:6327) at Function.ǃsdN (https://editor.construct.net/r76-2/main.js:54:2415) at new ǃs.ǃ_.Notification (https://editor.construct.net/r76-2/main.js:54:5157) at Function.ǃs.ǃo (https://editor.construct.net/r76-2/main.js:2:208436) at Function.ǃsT (https://editor.construct.net/r76-2/main.js:54:8447) at window.ǃYnT.ǃQu (https://editor.construct.net/r76-2/main.js:168:47777) at 
Construct 3 version: r76.2
URL: https://editor.construct.net/
Date: Thu Jan 11 2018 01:33:42 GMT+0400 (Грузинское время (зима))
Uptime: 611.9 s

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r76.2
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D9Ex vs_3_0 ps_3_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_color_buffer_half_float, EXT_frag_depth, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_color_buffer_float, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

**Comment by DiegoScirra** [comment] 2018-01-10 22:29
This should be fixed in the next release, r77. Unfortunately I was not able to reproduce it myself, so I am not 100% sure about it.

**Comment by AshleyScirra** [comment] 2018-01-11 12:12
r77 is out, please check again!

**Comment by DiegoScirra** [comment] 2018-01-11 19:32
From looking at the crash reports, it seems this is not happening anymore.

**Closed by DiegoScirra** 2018-01-11 19:32 UTC
Labels: need info
