### ISSUE TITLE
Random Crash to multiple projects

### ISSUE THREAD

**Issue by Stefannag** [Scirra/Construct-3-bugs#6549] opened 2023-02-16 17:51 UTC
## Problem description

For 3-4 days C3 will just crash randomly on different projects. I couldn't find why or where it crash - it is just randomly. Some time when I try to save, some time when I edit something. 

## Attach a .c3p

The crash is also happening in "Farming Lines Template", an official template from Construct 3.

## Steps to reproduce

1. Enter the project
2. I can't say what to do.. sometimes it will crash after 2 seconds, other times after 5 minutes.

## Observed result

It crash.

## Expected result

I expect not to crash.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/, line 0, col 0
Message: ResizeObserver loop limit exceeded
Stack: null
Construct version: r327.2
URL: https://editor.construct.net/
Date: Thu Feb 16 2023 19:47:00 GMT+0200 (Eastern European Standard Time)
Uptime: 520.9 s

Platform information
Product: Construct 3 r327.2 (stable)
Browser: Chrome 110.0.5481.100
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by WilsonPercival** [comment] 2023-02-16 18:16
https://github.com/Scirra/Construct-3-bugs/issues/6500

**Comment by DiegoScirra** [comment] 2023-02-16 19:38
Closing as this is a duplicate of #6500. Look at the comments of that issue for some more information.

**Closed by DiegoScirra** 2023-02-16 19:38 UTC
Labels: duplicate
