### ISSUE TITLE
Tilemap Family Use Collision Bug

### ISSUE THREAD

**Issue by theprocrastinator-dev** [Scirra/Construct-3-bugs#4195] opened 2020-09-09 01:56 UTC
Whenever there are two or more tilemaps in the same family; if you uncheck any tile's "use collision" box, it'll affect all the tiles that share the same number for ALL of the family's object (intead of only the selected child's). Not to mention that, for some reason, the tiles not using collision will still count as solid for some reason (family's behavior).

## Attach a .c3p
[bugrep.zip](https://github.com/Scirra/Construct-3-bugs/files/5203189/bugrep.zip)

## Steps to reproduce

1.Create a family with 2 or more tilemaps
2.Uncheck the "use collision" box for any tiles of any member of the family
3.Watch ALL of the tiles that share the same "id"/number get affected by it - and still count as solid, for some reason).

Number 3

It should only affect the member's tiles, instead of all of the family members'.

## More details

**Affected browsers/platforms:** 
Chrome; WIndows

**First affected release:** 
210.2
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 85.0.4183.83
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
C3 release: r210.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 49 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2020-09-10 15:42
Please attach a .c3p project as per the bug report guidelines. You've only attached an exported project. We cannot investigate the report with just that.

**Comment by theprocrastinator-dev** [comment] 2020-09-10 16:13
Oh, my bad. Wrong file
Gonna upload it as soon as I'm back home

**Comment by DiegoScirra** [comment] 2020-09-14 11:20
Can't reproduce this, it looks like it is working properly.

I modified your project to make each tile more distinguishable between each other and there is no sign of what you are describing. I marked each tile with a different number so it is more clear which tile index is being used in each tilemap. 

[TilemapCollisions.zip](https://github.com/Scirra/Construct-3-bugs/files/5218036/TilemapCollisions.zip)

**Comment by DiegoScirra** [comment] 2020-09-14 11:30
@theprocrastinator-dev 

Don't think there is any problem here.

I modified the project you posted to make it more clear.

Each tile now has a number. The tile with index 13 in the **Roof** tilemap has no collision and the same index in the **Wall** tilemap has collision. You can clearly see that one is not colliding and the other is.

[TilenaoCollision.zip](https://github.com/Scirra/Construct-3-bugs/files/5218076/TilenaoCollision.zip)

Could you maybe got confused because all the tiles look so similar?

**Comment by AshleyScirra** [comment] 2020-09-18 11:50
It appears the conclusion is this is not a bug, so closing.

**Closed by AshleyScirra** 2020-09-18 11:50 UTC
Labels: not a bug
