### ISSUE TITLE
Resize object on layout bug (with steps)

### ISSUE THREAD

**Issue by sebastien-c3** [Scirra/Construct-3-bugs#424] opened 2017-06-02 11:43 UTC
## Problem description
When resizing an object, expected result is different (object resized and centered or other).

I have finally found one reason (really not easy), not sure if it's the only one.
It's related to copy function in general and probably CTRL key behavior conflict.

## Steps to reproduce

First way to reproduce:
1. Open file project attached
2. Right click on a sample object
3. Click on "Copy"
4. Click on "Copy to clipboard"
5. Try to resize one object

-> The resizing is centered or different as what is expected
NB: for sprite font and tilemap, use top and left points.

Second way to reproduce:
Same steps but with CTRL+C to copy.

_Tips for readers: Press CTRL key to cancel this effect._

[resize-object-bug.zip](https://github.com/Scirra/Construct-3-bugs/files/1047548/resize-object-bug.zip)

**Comment by AshleyScirra** [comment] 2017-06-02 12:35
Thanks for identifying steps. I can't reproduce it with the original steps provided; only when pressing Ctrl+C. The resizing you see is intentional when holding Ctrl, and the "is Ctrl pressed" state appears to get stuck when you press Ctrl+C, which explains why it only happens that way. Should be fixed in r34.

**Closed by AshleyScirra** 2017-06-02 12:35 UTC

**Comment by sebastien-c3** [comment] 2017-06-02 13:00
Thanks Ashley, strange for original steps, I can't reproduce too, I still had to confuse myself by testing... I have found the good way to reproduce thanks to your previous message "it can happen as a normal behavior", that put me in the right direction by looking for this "normal" context.

I think (but I'm not sure) it can happens in other context too, cause and for example when I make anything else than previewing or edit event sheet, it can happen when returning after a long time in layout to just rearrange objects without copy them. Mystery, perhaps a forgotten CTRL+C... Hope we'll find if there is anything else!

**Comment by sebastien-c3** [comment] 2017-06-02 13:48
CTRL+S Ashley (thanks to your previous message too).
It explains also why my original steps where messed up.
