### ISSUE TITLE
Freeze game during thy system action Save

### ISSUE THREAD

**Issue by UbruPro123** [Scirra/Construct-3-bugs#5848] opened 2022-07-01 08:52 UTC
## Problem description

Sometimes when I use the save action (in my game it is like autosave), the whole game gets stuck.

## Attach a .c3p

I am only doing this see at picture:
![c3](https://user-images.githubusercontent.com/44697344/176851626-39de52d8-51bd-47d6-baa0-c50bcb98c721.png)
Nothing else is triggered during the bug. It will do only one save action from these two depending on at which level you are. Then the game goes on, it is like autosave function.

## Steps to reproduce

This is the not usual to reproduce I know you do not like these "general" bugs without exact step by step procedure. I have to play my game for a while and approx every 20-30mins it is occurred regularly, every time during that save action. So it is quite big problem for me and I do not know how to solve it or describe it more because it is system action so it must be some kind of internal problem.

## Observed result

During the save action game is freeze and nothing helps it has to be closed via ALT+F4.

## Expected result

Complete save action and save everything correctly without freeze.

## More details

I tested more exports and it seems it is not related to it. I mean it happened to me in preview directly in C3, in exported APK, NW.js, etc... It must be independent on it.

I am not sure about C3 version because it is happening randomly and test all versions is really time consuming but if it will be problem I can try it more in older ones. Now I can say for sure that this problem was even in 285.3 stable (the oldest version I tested more in recent time). Still happening even in latest beta 300 for different exports.

## System details

During the preview from C3 I noticed this related error in browser console.
![save bug](https://user-images.githubusercontent.com/44697344/176855242-f4a17cfe-c6b6-41a1-b740-1a2a9c563873.png)
Every time during this bug this is written to the console so I hope it can help.

<details><summary>View details</summary>

Platform information
Product: Construct 3 r300 (beta)
Browser: Chrome 103.0.5060.53
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 134 gb
Storage usage (approx): 5.2 gb (3.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

## Conlusion
I know it is hard to deal with it for you, but it is also bad for me. I am planning to release my game project in matter of months after almost 2 years of development and I simply have to fix this issue it is unacceptable for future buyers. I am open for any further help I can also send you my whole big project or exported version but as I wrote before there is no exact step by step guide, you have play it for a while and then it will appear so I am not sure if it is worth trying this way for you because you will get only that error message in console as I wrote above. You can try to change something in save action and release it in next beta and then I can test it myself and let you know if it helped or something like that.
So let me know what you can do about it, or how can I assist more. I need to fix this. Thank you very much in advance!

**Comment by AshleyScirra** [comment] 2022-07-01 10:35
I'm afraid the reason we have the bug report guidelines is it's impossible to help you without that information. So unfortunately there is nothing we can do from just this information. We'd need to identify a reliable series of steps to reproduce the problem to have any chance at all of resolving the problem.

The error message looks like it might be something to do with saving when there is a pending system "Wait" action, but doesn't tell us anything much more than that. Perhaps that would help you identify a way to reproduce the problem more reliably?

I'm afraid that as it stands there is nothing that can be done about this issue, so closing. If you can find a more reliable way to reproduce the problem, please file a new issue.

**Closed by AshleyScirra** 2022-07-01 10:35 UTC
Labels: no repro

**Comment by UbruPro123** [comment] 2022-07-13 10:53
Thank you for tips, it seems that wait was really problem and causing the freeze.
