### ISSUE TITLE
CTRL + Z is not working as it should in dialog windows. r123.2

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#2251] opened 2018-11-04 21:32 UTC
## Problem description

CTRL + Z is not working as it should in dialog windows.

![2018-11-05_00-31-13](https://user-images.githubusercontent.com/2965842/47970120-2ecf8880-e092-11e8-8998-98c785d426ce.gif)

## Steps to reproduce

1. Open a dialog window with paramaters.
2. Type something after the paramater you had before.
3. Press CTRL + Z

**Comment by shortercode** [comment] 2018-11-05 14:29
Seems to trigger the autocomplete control, which is presumably blocking the browser undo action.

**Comment by AshleyScirra** [comment] 2018-11-05 16:36
Looks like a duplicate of #93. We don't actually have undo/redo implemented for parameters yet.

**Closed by AshleyScirra** 2018-11-05 16:36 UTC
Labels: duplicate
