### ISSUE TITLE
Desktop build : app restarted without any warning of unsaved work being lost when right clicking the inspector and selecting "Reload App"

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#2970] opened 2019-05-26 15:31 UTC
## Problem description

On the desktop build, when right clicking in the inspector of a debug preview, then selecting "Reload app" or "Simulate a browser restart", the editor will close immediately, without asking if the work should be saved. Any unsaved work will be lost.

## Attach a .c3p

A blank project is enough to see the problem.

## Steps to reproduce

1. Open any project
2. Start a debug preview (ctrl-F5)
3. Right click in the inspector
4. Select "Reload app" or "Simulate browser restart"

## Observed result

The editor is relaunched. Any unsaved progress is lost.

## Expected result

The editor should warn about work being lost before allowing to do this.

## More details

**Affected browsers/platforms:** Desktop build

**First affected release:** 150

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.30.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@004e06da11e10bb08f6632224ae48ee3d5f7b303) NWjs/0.30.0 (like Chrome/66.0.3359.117)
C3 release: r150 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 2.9 gb (18.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by shortercode** [comment] 2019-05-28 09:04
This would appear to be a NWJS crash, and probably a duplicate of #2962 assigning to @AshleyScirra to review but this will probably be merged.

**Comment by AshleyScirra** [comment] 2019-05-28 10:54
I think it's working correctly, in that NW.js gives you context menu options to restart the entire app... it's just not useful to us. So I've blocked the menu appearing for the next release.

**Closed by AshleyScirra** 2019-05-28 10:54 UTC
Labels: desktop
