### ISSUE TITLE
Multiplayer Plugin: Leave Room Bug

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#4967] opened 2021-07-20 00:00 UTC
## Problem description

I get a error message (console) after leaving room:

> peer.js:4 Peer '5V6Y' datachannel 'o' error:  RTCErrorEvent
> dc.onerror @ peer.js:4
> domSide.js:49 [Multiplayer] Peer '633player' (5V6Y) error:  RTCErrorEvent
> _OnPeerError @ domSide.js:49
> peer.js:4 Peer '5V6Y' datachannel 'r' error:  RTCErrorEvent
> dc.onerror @ peer.js:4
> domSide.js:49 [Multiplayer] Peer '633player' (5V6Y) error:  RTCErrorEvent
> _OnPeerError @ domSide.js:49
> peer.js:4 Peer '5V6Y' datachannel 'u' error:  RTCErrorEvent
> dc.onerror @ peer.js:4
> domSide.js:49 [Multiplayer] Peer '633player' (5V6Y) error:  RTCErrorEvent

The bug comes, when i have a "sync object" and after that, change the layout. (see the example file)

## Attach a .c3p

[network-leave-channel-bug.zip](https://github.com/Scirra/Construct-3-bugs/files/6844480/network-leave-channel-bug.zip)

## Steps to reproduce

1. Open the example file
2. Run the example twice (host and client)
3. See on client side (and server side) the error message
4. The client can't leave the room

## Observed result

The client can't leave the room and the server has the same error message too

## Expected result

Client and server leave the room

## More details

I use chrome, but don't work on other browsers too.
On the testproject - workers is auto

**Affected browsers/platforms:** 

Chrome / Windows

**First affected release:**

r255 and above

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 91.0.4472.164
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36
C3 release: r257 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 171 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5751)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2021-07-21 17:26
This looks like a mistake in your events. Notice the host waits only 3 seconds before moving to the next layout, but the client waits 4 seconds. Both then wait 1 second, then leave the room. So after 4 seconds the host leaves the room - which kicks off the client - but after 5 seconds the client tries to leave the room after the host quit and closed the room, which will fail. That's why an error happens - in fact the client will be triggering "On kicked", but since the host quitting has (presumably unintentionally) been timed to exactly coincide with the client changing layout, there's a race condition in which layout you'll be on when that fires. If I adjust the timing to make sure there's time for the client to trigger "On kicked", I can see it is triggering that correctly, so it seems to be working as designed, and the only reason in your project the client can't leave is because they got kicked already, but your events don't handle that.

**Closed by AshleyScirra** 2021-07-21 17:26 UTC
Labels: not a bug
