### ISSUE TITLE
Black Screen when using admob on android

### ISSUE THREAD

**Issue by 1mrpaul1** [Scirra/Construct-3-bugs#5211] opened 2021-11-09 16:20 UTC
## Problem description

When using admob plugin, the game freeze after preloader on android. Black screen

## Attach a .c3p

[adstest.zip](https://github.com/Scirra/Construct-3-bugs/files/7506292/adstest.zip)

## Steps to reproduce

1. ad admob
2. use ads code for android (ios is empty)
3. make an  android build 

## Observed result

black screen

## Expected result

my working game

## More details
may be the issue happen because no ios keys are used in the plugin

**Affected browsers/platforms:** 

started after adding universal admob ads

**First affected release:** 

## System details

windows 11
chrome 95

Platform information
Browser: Chrome
Browser version: 95.0.4638.69
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
C3 release: r271 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 73 gb
Storage usage (approx): 255 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9649)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by arcadesindo** [comment] 2021-11-15 02:01
its the same thing that happened to me, our game was updated on last 12 Oct, but suddenly on last friday (12 Nov) the game stuck after loading screen (cant reach first layout).

After farther try and error with r268 or r271-2, it seems like the problem was from our Admob account not from Construct side, I've tried using our clients admob id and they are working well, but not for my all admob apps id.

**Comment by jayjmon** [comment] 2021-11-15 03:21
> its the same thing that happened to me, our game was updated on last 12 Oct, but suddenly on last friday (12 Nov) the game stuck after loading screen (cant reach first layout).
> 
> After farther try and error with r268 or r271-2, it seems like the problem was from our Admob account not from Construct side, I've tried using our clients admob id and they are working well, but not for my all admob apps id.

I dont think it has anything to do with admob, I had exports from last week that worked fine. It wasn't till thursday or friday last week that r271-2 exports no longer worked for android and now yesterdays export from r268 has the same issue. This may be from a recent update.

**Comment by jayjmon** [comment] 2021-11-15 03:24
![Capture](https://user-images.githubusercontent.com/48458961/141717340-a193e44b-bb32-4089-a1a3-4370201372de.PNG)
This is an image with admob removed from the project. It gets stuck on this screen. It does it for all projects now. With or without admob

**Comment by arcadesindo** [comment] 2021-11-15 06:51
sorry Jay seems like we have different issue

**Comment by arcadesindo** [comment] 2021-11-18 12:43
Have been contacting the Admob CS, and also trying to do one more time export and see the logcat. My partner admob ID was working, but mine not. There's something about **requestInfoUpdate** that not show in the logcat on my game, but my partner was having that.

**my partner game**
after completing the requestInfoUpdate, there's admob execute, load, and other was shows on next line
![image](https://user-images.githubusercontent.com/28801633/142416338-d84f432b-304b-4701-8d69-cf81cde67693.png)

**my game**
nothing else shows after this line
![image](https://user-images.githubusercontent.com/28801633/142416546-7abf14a3-78fc-488e-ab48-f0560820d1a8.png)

Admob CS also have asking to remove the GDPR message, waiting couple hours till now but still not working. Either this was something to fix with the SDK, or just Admob itself that has the problem? but why does my partner game is working though I do compile with the same source code project just changing their package and admob id.

**Comment by eugene-tkachenko** [comment] 2021-11-18 13:14
I can see the same issue on my end as well...under the same condition. Does anyone from Scirra team looked at this issue for these 10 days? :)

**Comment by DiegoScirra** [comment] 2021-11-18 18:17
@1mrpaul1

What API levels and target SDK are you using for your build?

**Comment by arcadesindo** [comment] 2021-11-19 02:43
these all was default settings from Construct

play-services-ads:20.3.0
user-messaging-platform:1.0.0+
<preference name="android-minSdkVersion" value="23" />
<preference name="android-targetSdkVersion" value="30" />

**Comment by DiegoScirra** [comment] 2021-11-19 12:31
Can't reproduce this. Tried generating a signed APK for a project using the Mobile adverts plugin, with the build service and also by using an exported Android Studio project and in both cases everything works, both in emulator and real device.

**Comment by arcadesindo** [comment] 2021-11-19 12:47
Hi @DiegoScirra, Admob CS was telling about the GMA SDK didn't fully initialized when using our Admob App id, and it comes from the SDK, you cannot reproduce on your admob app id since its not affected, I can send mine to you for trying, please send me your contact mail

**Comment by DiegoScirra** [comment] 2021-11-19 13:33
You can send me any information to diego@scirra.com. I can try it out and see what happens.

**Comment by 1mrpaul1** [comment] 2021-11-19 14:07
> You can send me any information to [diego@scirra.com](mailto:diego@scirra.com). I can try it out and see what happens.

please show your setup. screenshot

**Comment by arcadesindo** [comment] 2021-11-19 14:14
please check your mail @DiegoScirra, I have sent it.

**Comment by DiegoScirra** [comment] 2021-11-19 17:46
I tried this out with the application id @arcadesindo sent me, and indeed I started getting a black screen right after the loading is complete.

It seems that there is a problem with Admob itself, where for some reason some application ids are just no able to initialize Google Mobile Ads SDK properly, while at the same time not reporting there has been any kind of failure, so the end result is that the application just hangs.

The only thing that I can do is to set a short timeout, so that execution can continue if the SDK takes too long to initialize. This will allow a game to continue normally, but the downside is that it won't be able to show ads.

**Comment by jayjmon** [comment] 2021-11-19 18:08
> I tried this out with the application id @arcadesindo sent me, and indeed I started getting a black screen right after the loading is complete.
> 
> It seems that there is a problem with Admob itself, where for some reason some application ids are just no able to initialize Google Mobile Ads SDK properly, while at the same time not reporting there has been any kind of failure, so the end result is that the application just hangs.
> 
> The only thing that I can do is to set a short timeout, so that execution can continue if the SDK takes too long to initialize. This will allow a game to continue normally, but the downside is that it won't be able to show ads. Hopefully this will be fixed on Google's side at some point.

In android studio, the error "E/FA: Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI" appears. when adding google-services.json and the google play plugin the error no longer appears but the problem still persist. There is something missing that the SDK is looking for that the android export build is no providing.

**Comment by DiegoScirra** [comment] 2021-11-19 18:13
I though that would be the case, but when I use my own Application ID which I use for development, I see that same message in the log, and yet everything works.

**Comment by arcadesindo** [comment] 2021-11-20 12:19
>The only thing that I can do is to set a short timeout, so that execution can continue if the SDK takes too long to initialize. This will allow a game to continue normally, but the downside is that it won't be able to show ads. Hopefully this will be fixed on Google's side at some point.
@DiegoScirra no, thats not solving the issue, is it really google side or admob plus side?
![image](https://user-images.githubusercontent.com/28801633/142725969-2c68053d-37cb-464f-bf2f-acf8f0e07314.png)
there's a guy on admob plus thread, telling that after he use this, it seems to be work.

**Comment by DiegoScirra** [comment] 2021-11-21 14:08
I will try that out, but it's a hack. Even if the success callback of MobileAds.initialize is not strictly necessary, it should still work. The Google documentations says so, and there are no mentions of it being deprecated.

The fact that this only affects some application Ids and that there haven't been any significant changes in Construct or Admob plus, suggest this is an Admob problem. Maybe it is an Android problem seeing how iOS seems to be ok.

**Comment by arcadesindo** [comment] 2021-11-21 14:19
I see, sorry to bother your weekend, I've also have been contacting the admob sdk support team regarding this issue, waiting for next monday.

**Comment by 1mrpaul1** [comment] 2021-11-22 17:53
> Unfortunately as I said before, from Construct's side the best I can do is to prevent the game from going into a black screen, but ads will not work for these particular application IDs until the underlaying problem is solved.

isn't a good idea, I tried 2 codes and they both have the same problem. And stop ads = disable monetisation for me

**Comment by DiegoScirra** [comment] 2021-11-22 19:25
Anyone who is interested can manually modify the relevant code in an Android Studio project export, and apply the workaround discussed earlier. Then build an APK or App Bundle from Android Studio.

1. Find the file **app/java/admob.plus/cordova/AdMob.java**

2. Find the following block of code at **line 62**:

`case Actions.START:
        MobileAds.initialize(cordova.getActivity(), status -> {
            helper.configForTestLab();
            callbackContext.success(new JSONObject(new HashMap<String, Object>() {{
                put("version", MobileAds.getVersionString());
            }}));
        });
        break;`

3. Change it so it looks like this:

`case Actions.START:
	MobileAds.initialize(cordova.getActivity());
	helper.configForTestLab();
	callbackContext.success(new JSONObject(new HashMap<String, Object>() {{
	    put("version", MobileAds.getVersionString());
	}}));
	break;`

4. Try it in the simulator.

### WARNING!

I would wait till the next beta to try that out and even if that works out, it seems that anything relating to GDPR still won't work as all requests regarding consent status and consent forms will be rejected.

**Comment by arcadesindo** [comment] 2021-11-23 01:56
thanks @DiegoScirra! glad this have a solution, will try that ASAP

**Comment by arcadesindo** [comment] 2021-11-23 08:51
It works! thanks Diego!

**Comment by fredriksthlm** [comment] 2021-11-23 09:11
I think the issue is in the Google Admob SDK. IT started like 1,5month ago, and seems to affects some random accounts. They say they are working on it.
At the moment the only "solution" is to don't wait for the initialize callback.

https://groups.google.com/g/google-admob-ads-sdk/c/zMshI4tmAwc/m/-PtndpmfAgAJ

https://groups.google.com/g/google-admob-ads-sdk/c/eQNcc_wU5aY/m/QCRawhr_BQAJ

https://groups.google.com/g/google-admob-ads-sdk/c/eabu4XtJLzo

**Comment by arcadesindo** [comment] 2021-11-23 09:54
hmm but seems like he said that this wasn't from their side
![image](https://user-images.githubusercontent.com/28801633/143003308-25bef06a-cce3-40d6-a459-2918f4a1df0e.png)

**Comment by fredriksthlm** [comment] 2021-11-23 10:09
> hmm but seems like he said that this wasn't from their side !

The (callback for the) Initialize is the same regardless platform. Unity users are reporting the same.

**Comment by eugene-tkachenko** [comment] 2021-11-23 10:33
I can add more. For some reason ads stopped showing up. Nothing have changed from that time when ads were showing up: code, no issues with admob, not touched admob settings. So it's indeed on their side. I added another test app and ads units and it's working just fine with a new app ids.

**Comment by DiegoScirra** [comment] 2021-11-23 11:26
The next beta will go out with a small fix to prevent an exported game from hanging up with a black screen.

Anyone wanting to apply the hack to **Admob plus** will have to do it manually.

Personally I think it's a better idea to generate a new android application ID and new ad units. It is likely that those will work.

There doesn't seem to be anything else to add to the subject, so closing.

**Closed by DiegoScirra** 2021-11-23 11:26 UTC
Labels: confirmed, Android
