### ISSUE TITLE
Popup Window decreases size with each new opening preview

### ISSUE THREAD

**Issue by Robsonrpr** [Scirra/Construct-3-bugs#1200] opened 2018-01-16 02:00 UTC
## Problem description

When I open the preview for the first time in a project, everything happens normally, and the screen is displayed in its actual size configured in the Window Size. After closing and reopening the preview, the Popup size decreases with each new opening, becoming a small bar.

## Steps to reproduce

1. Open a new project.
2. Click in preview. Close the popup.
3. Open again and repeat the closing and reopening steps successively.

## Observed result

With each new opening of the preview, the popup decreases in size, becoming a small bar.

## Expected result

The popup should keep the normal size set in the Window Size, in all previews

## Affected browsers

* Chrome: Only when saved on desktop and open as window. Running through the site does not occur this problem.

<details><summary>View details</summary>

First opening the preview
![image](https://user-images.githubusercontent.com/33605485/34968280-8d0fdbe0-fa4f-11e7-9da6-ced80008db8a.png)

After closing and opening seven times the preview
![image](https://user-images.githubusercontent.com/33605485/34968346-d9a9579c-fa4f-11e7-8a41-64d941dccae7.png)

After closing and opening twenty times the preview
![image](https://user-images.githubusercontent.com/33605485/34968377-0bd6308c-fa50-11e7-9d44-7cca7a2d84be.png)

</details>

**Comment by AshleyScirra** [comment] 2018-01-16 09:56
Duplicate of #947. It's this Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=777854
Please star the issue to follow updates.

**Closed by AshleyScirra** 2018-01-16 09:56 UTC
Labels: duplicate
