### ISSUE TITLE
Bad Loops make c3 editor unresponsive even if you close preview page 

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1683] opened 2018-06-08 08:36 UTC
## Problem description

Making some crazy  loops make c3 editor page to freeze/turn unresponsive, which needs c3 restart to fix. Even if you open preview on new tab.

## Attach a .c3p

[C3Freeze.zip](https://github.com/Scirra/Construct-3-bugs/files/2083546/C3Freeze.zip)

## Observed result

Some nested loops or similar things which hang preview window, will also freeze c3 editor. Even if it on different tab, you can still manage to close preview but Construct 3 editor tab will never recover and needs restart to fix.

## Expected result

C3 editor should works fine if preview window hangs/freeze/crash/ turn unresponsive. If you open C3 on chrome with multiple tabs, run freeze project. C3 will never recover but you can still use other tabs just fine.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment] 2018-06-08 09:40
Duplicate of #476. Should be fixed with the new worker mode in the C3 runtime when that comes.

**Closed by AshleyScirra** 2018-06-08 09:40 UTC
Labels: duplicate
