### ISSUE TITLE
drawing Canvas paste adjustHSL object offsets, goes crazy with parallax and scale

### ISSUE THREAD

**Issue by StefanSava** [Scirra/Construct-3-bugs#2755] opened 2019-03-21 14:02 UTC
## Problem description

Pasting a object that has adjustHSL effect offsets the object on the drawing canvas.

Zooming out below 0.6 makes the screen black and irrecoverable (but does not crash)

I am aware someone already reported something similar #2624 
this is using a different effect that the one used in the other issue
the bug can be seen offseting by different amounts based on parallax and zoom

## Attach a .c3p
[drawingCanvas paste object with effect bug 1.zip](https://github.com/Scirra/Construct-3-bugs/files/2992327/drawingCanvas.paste.object.with.effect.bug.1.zip)

## Steps to reproduce

1.Right click to turn effect off and on
2.Scroll down below 0.6 scale to see image go black
3.Left click to move camera around and see pasted object acting crazy

## Observed result

Pasting is not consistent

## Expected result

Object should look the same as when effect is turned off.

## More details

**Affected browsers/platforms:** 

Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 7.4 gb
Storage usage (approx): 97 mb (1.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 650 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-03-21 17:29
Closing as duplicate of #2624, it's the same issue (pasting objects with effects can be offset).

**Closed by AshleyScirra** 2019-03-21 17:29 UTC
