### ISSUE TITLE
iPhone X display issues

### ISSUE THREAD

**Issue by theBdrive** [Scirra/Construct-3-bugs#1279] opened 2018-02-11 21:33 UTC
## Problem description

Exported C3 game viewport is always shifted left off the screen on iPhone X.

## Attach a .c3p

https://i.imgur.com/izFlZRT.png

## Steps to reproduce

1. Create a blank C3 project, 16:9 aspect ratio, orientation: landscape, fullscreen mode set to scale outer, and viewport fit set to cover.
2. Export>Cordova>Xcode
3. Open xcworkspace file in Xcode and run game in iPhone X simulator or on physical device

## Observed result

Game looks like this with blackbars 
https://i.imgur.com/rFPOOI1.png

The exported C3 xcode project includes all the correct size LaunchImages but is missing the sizes for iPhone X. If you manually add a iPhoneX launchimage 1125 x 2436 res, clean project and run again it now looks like this.

https://i.imgur.com/izFlZRT.png
The viewport is pushed off the left side of the screen leaving a black bar on the right.

## Expected result

I expected to game to run and take up the full screen of the iPhone X.

![iphonex](https://user-images.githubusercontent.com/9151862/36078799-1dac0c06-0f30-11e8-8b4b-3fcb98d3828a.png)

**Comment by theBdrive** [comment] 2018-02-14 04:30
Some notes: I have tried both LaunchImages and Storboards with the correct constraints/safe area and C3 games still load up off the screen like this. I tested a Unity project but using the same storyboard in Xcode and it displays correctly on iPhone X.

**Comment by shortercode** [comment] 2018-02-20 18:02
I'm looking into this, in the meantime it looks like not using the `viewport-fit: cover` option when making an iOS application looks a little better ( it's centered at least ).

**Comment by shortercode** [comment] 2018-02-21 10:47
I think the issue is down to the build server not using the latest version of cordova-ios. If you export as a cordova project and prepare it yourself it should work fine.

The build server will eventually be updated to the latest version, but I need to run compatibility checks against the Android plugins first.

**Comment by theBdrive** [comment] 2018-03-26 20:57
Any progress on this issue? It's weird cause taking to a few other C3 users we are getting mixed results using the same blank projects with the exact same project settings, xcode settings and build service. Some are reporting it displaying fine taking up the whole screen and others like me are still getting the viewport shifted off to the right, so weird.

**Comment by kai902000** [comment] 2018-03-31 04:30
Having same problem here.  I tested all sort of screen setting, but it still wont take up all the screen.

**Comment by theBdrive** [comment] 2018-04-17 19:59
@shortercode Ok another thing I noticed is this issue only effects games in landscape orientation, portrait games display fine and take up the whole screen.

**Comment by shortercode** [comment] 2018-07-03 17:19
Okay so this should be resolved in the next release, I've also added in custom launch storyboards in C3 which should make life a little easier. 

New projects now have an extra ( optional ) icon called "storyboard-splash.png". This has a maximum ( and default ) size of 2732x2732px. If you give an icon which is smaller then when you export a 2732*2732px image will be created with your icon in the middle, and the projects "splash colour" as a background.

For anyone unfamiliar with launch storyboards; iOS will crop the image the size it needs, so make sure you only put important information in the middle of the image.

**Closed** 2018-07-03 17:19 UTC

**Comment by theBdrive** [comment] 2018-07-07 19:10
@shortercode So I just noticed this today, please check my thread at https://www.construct.net/forum/construct-3/general-discussion-7/iphone-x-display-problems-132147/page-5#forumPost942195 . This is a new problem because I released a game in portrait mode that displayed correctly using just the viewport fit cover and my own storyboards. Will this be fixed in the next release or is this a whole different problem?

**Comment by sangeeth786** [comment] 2018-12-04 06:00
I am facing an Issue with Screen size on iPhone XR & iPhone XS MAX showing Black Bars on its side
But fills the complete screen on iPhone X, and iPhone XS with no black bars.
Display Properties used in my project
Viewport Size :- 960*640
Aspect Ratio :- 3:2
Viewport fit :- Cover
FullScreen mode :- Scale Outer
Fullscreen quality :- High
Orientations :- Landscape
Sampling :- Linear

What is the solution for black bars appearing in iPhone XR & iPhone X MAX, 
and i also need an help for displaying the sprite objects in my project in centre of the viewport since it is not being displayed in centre in the device (Layout size used in my project 1200*800)
