### ISSUE TITLE
Construct (r59) crashes on changing icons.

### ISSUE THREAD

**Issue by karoi** [Scirra/Construct-3-bugs#869] opened 2017-10-03 09:39 UTC
## Problem description

So when I change the icons in my game in Construct 3 (r59) the editor crashes. Am I the only one with this problem? It worked before, since I have changed the icon and I want to update it to a new version.

## Attach a .c3p

I don't think it's usefull to include a empty project :)

## Steps to reproduce

1. Start new project.
2. Go to icons
3. Upload a image (I did use the correct sizes)
4. Crash.

## Observed result

Error report comes up with the option to save and restart.

## Expected result

That the icons would change, just like before.

## Affected browsers

* Chrome: Yes
* Firefox: N/A, don't use this browser.
* Edge: N/A, don't use this browser.
* Safari: N/A, don't use this browser.

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Function.ǃq.ǃX (https://editor.construct.net/r59/main.js:2:179732) at e.ǃKxF.ǃKVm (https://editor.construct.net/r59/main.js:71:266006) at Promise.resolve.then.then (https://editor.construct.net/r59/main.js:71:200664) at 
Stack: TypeError: unexpected type at Function.ǃq.ǃX (https://editor.construct.net/r59/main.js:2:179732) at e.ǃKxF.ǃKVm (https://editor.construct.net/r59/main.js:71:266006) at Promise.resolve.then.then (https://editor.construct.net/r59/main.js:71:200664) at 
Construct 3 version: r59
URL: https://editor.construct.net/
Date: Tue Oct 03 2017 11:38:18 GMT+0200 (CEST)
Uptime: 217.6 s

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_0
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r59
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M380 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2017-10-03 10:26
Possible duplicate of #849, assigning to Diego to verify.

**Comment by DiegoScirra** [comment] 2017-10-03 11:29
Yeah, this is the same as #849. Should be fixed in r60.

**Closed by DiegoScirra** 2017-10-03 11:29 UTC
