### ISSUE TITLE
status bar not hidden (round 3)

### ISSUE THREAD

**Issue by Bighands22** [Scirra/Construct-3-bugs#3842] opened 2020-05-07 17:07 UTC
## Problem description

The status bar is not hidden when exporting to android

## Attach a .c3p

https://drive.google.com/open?id=1g2oX5Q_LFNlmH8F11uC0JgPneVty91zX

## Steps to reproduce

Video shows how
https://youtu.be/cDiZd4F84AM

## Observed result

black bar shown at the of of android export

## Expected result

The status bar to be hidden

## More details
When i export to android the application does not hide the status bar, it hides the details in the status bar but leaves a black bar at the top of the screen

**Affected browsers/platforms:** 

**First affected release:** 

## System details

r198 and the last 2 updates before that

**Comment by AshleyScirra** [comment] 2020-05-08 12:54
Can't reproduce here, it appears correctly on a Pixel 3 with the status bar hidden (screenshot below).

There has not actually been any change in how "Hide status bar" is handled (since r197.2 anyway, which reverted an accidental change). There has however been an intentional change with devices with a notch. Previously "Hide status bar" also applied viewport fit "cover", but this was confusing and inconsistent with the project "Viewport fit" property. So now it correctly uses the project "Viewport fit" property. Try setting that to "Cover" and it should use the full display of notched devices once again.

As ever the specific details of what you're doing and the devices you are using are essential to be able to investigate and deal with reports. Please try to provide comprehensive reports from the start to avoid having to go through this repeated re-filing process, which still has not led to a conclusive result, but I'm closing this based on a guess you actually have a notched device and you need to change the "Viewport fit" property, which is an intentional change in how notched devices are handled.

![Screenshot_20200508-135039](https://user-images.githubusercontent.com/768723/81407297-0915ba80-9133-11ea-9540-de85929feb92.png)

**Closed by AshleyScirra** 2020-05-08 12:54 UTC
Labels: Android, can't reproduce
