### ISSUE TITLE
Turret Family Target Bug

### ISSUE THREAD

**Issue by ZeldaVerde48** [Scirra/Construct-3-bugs#4556] opened 2021-02-10 23:44 UTC
## Problem description

When you create a family with more than one sprites, add the turret behavior to the family, and set an object to be the target of one of the turrets, the other turrets in the family will aim for it too.

## Attach a .c3p

Example: (https://www.construct.net/out?u=https%3a%2f%2fwww.dropbox.com%2fs%2fx1wn5br7dx1iilr%2fTurretFamilyBug.c3p%3fdl%3d0)

## Steps to reproduce

1.Just drag the targets next to the turrets and you will see it happen!

## Observed result

Both turrets aim for both targets.

## Expected result

Each turret should aim for the target previously set.

## More details

Apparently, for example, the first turret won't aim for the second one's target if there is no instances of the second turret.

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment] 2021-02-11 10:52
Duplicate of #4291 and #3460. This is currently by design. There is only one turret behavior, on the family, so both 'Add target' actions affect the whole family.

**Closed by AshleyScirra** 2021-02-11 10:52 UTC
Labels: duplicate
