### ISSUE TITLE
R95.2 safari game demo projects

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1504] opened 2018-04-20 13:33 UTC
## Problem description

*Enter a concise description of your problem here*
Can’t get any to load, all give same error, failed to download project, check your internet connection.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Open c3 
2. Touch game demos
3. Click on any to open project

## Observed result
Check your internet connection error
*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2018-04-20 15:33
I've seen a similar issue in Safari 11.1 on macOS. I think there is some kind of bug involving the Service Worker, and anything involving the Service Worker will probably prove difficult...

**Comment by AshleyScirra** [comment] 2018-04-30 15:44
Found an issue where the Service Worker could fail to load projects when the storage quota was exceeded. To reproduce, simply open all the game demos one by one until an error occurs (as it has filled up the storage quota). Should have a fix in for the next release, but need to verify it works there.

**Comment by AshleyScirra** [comment] 2018-05-03 16:09
The fix for this was made on the server-side and it should be in effect already for r98. You will need to clear the Safari cache first though before it takes effect. Once you've done that then all example projects should open OK. The problem is Safari has a very low storage quota which runs out quickly; note that once the storage quota is full it will load successfully, but have to download the project from the server every time, since it can't save it.

**Closed by AshleyScirra** 2018-05-03 16:09 UTC
Labels: safari
