### ISSUE TITLE
destroy with pinned obj error r195

### ISSUE THREAD

**Issue by q3olegka** [Scirra/Construct-3-bugs#3785] opened 2020-04-19 11:40 UTC
## Problem description

When you delete an object to which another object was attached with the parameter "destroy with pinned object", it causes an error in the console "not yet implemented", after which the game may freeze, or a glitch with the animation of another object.

The problem is easily reproduced on an empty project.

![FmyEmxGqOuA](https://user-images.githubusercontent.com/50992459/79686791-95774080-824b-11ea-902a-a9c5c565870b.jpg)
![pl5iiNk2cjs](https://user-images.githubusercontent.com/50992459/79686792-96a86d80-824b-11ea-9998-60c0d773d63c.jpg)

**Comment by AshleyScirra** [comment] 2020-04-20 10:53
Ignored guidelines so closing since it's impossible to investigate, but looks like probable duplicate of #3755.

**Closed by AshleyScirra** 2020-04-20 10:53 UTC
Labels: ignored guidelines
