### ISSUE TITLE
[r46] Wrong layout shown on remote preview

### ISSUE THREAD

**Issue by gpibernats** [Scirra/Construct-3-bugs#643] opened 2017-07-25 16:16 UTC
## Problem description

Remote preview only can run the first layout created.

Video with example [here](https://www.dropbox.com/s/4tr9vats9wromhf/BugWrongLayoutOnRemotePrieview_25jul.mov?dl=0).

## Attach a .c3p

It happens creating a new project.

Example [here](https://www.dropbox.com/s/jow23oj3rzwa7l9/WrongLayoutOnRemotePreview_25jul.c3p?dl=0).

## Steps to reproduce

1. Create a project with 2 layouts
2. Run the second layout with "Remote Preview"

## Observed result

You will se the first layout.

## Expected result

Second layout shown.

## Affected browsers

* Chrome: yes
* Firefox: -
* Edge: -
* Safari: -

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

No report dialog.

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r46

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 67 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2017-07-27 12:19
Can confirm this, as a workaround use the "first layout" option for the project.

**Comment by shortercode** [comment] 2017-07-27 13:16
After a bit of reflection I'm not sure I'd call this a bug. So there's 3 preview behaviours (ignore debug for now).

- **Preview Layout (default)**: Previews the active layout of the active project
- **Preview Project**: Previews the start layout of the active project
- **Remote Preview**: same as **Preview Project** but remote

The real issue is more that **Remote Preview** doesn't behave like **Preview Layout**, or that we don't have a 4th option like **Remote Preview Layout**. This is confused by the fact that it doesn't match the default behaviour, and that it's not possible to use **Remote Preview** to test an individual layout without modifying the project.

I'll leave this open for consideration for now, as this is Ashley's area so I think he should get a shout in first on how it's changed.

**Comment by AshleyScirra** [comment] 2017-07-31 11:16
It's working as intended so closing. Use https://construct3.ideas.aha.io/ for feature requests.

**Closed by AshleyScirra** 2017-07-31 11:16 UTC
Labels: enhancement, not a bug
