### ISSUE TITLE
Animation Editor Causes Construct to Not Respond

### ISSUE THREAD

**Issue by jobel0092** [Scirra/Construct-3-bugs#6431] opened 2023-01-26 20:19 UTC
## Attach a .c3p
https://www.dropbox.com/s/vn8ifqk7jpmuwoh/SpriteEditor%2BAnimationBug.c3p?dl=0

## Steps to reproduce

1. open Sprite Editor
2. Play the Animation
3. While the Animation play window is open (animation wil end), right-click the Animation on the right and select Duplicate

## Observed result

Construct Freezes and becomes unresponsive
## Expected result

It should either not allow me to interact with anything else because the Animation Player is open, or it should allow me to Duplicate it without hanging.
## More details

Chrome
**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Page Unresponsive
You can either Wait for the page to be responsive or Exit the site.

![image](https://user-images.githubusercontent.com/5100565/214941721-7139f1b4-4fef-4816-b87f-f7db19c93440.png)

</details>

**Comment by DiegoScirra** [comment] 2023-01-27 17:23
This should be fixed in the next beta.

Wasn't able to reproduce it, but it seems to be the same as #6423. Will keep this open until the next beta to confirm if it was fixed or not.

**Comment by DiegoScirra** [comment] 2023-01-30 17:21
@jobel0092

Please try out r327.2 to see if the problem was sorted.

**Comment by DiegoScirra** [comment] 2023-01-30 18:53
Cool, thanks for checking.

It was a very old request to make the animation preview more useful.

**Closed by DiegoScirra** 2023-01-30 18:53 UTC
Labels: fixed, check next release
