### ISSUE TITLE
Crash when opening project from local browser. (R21)

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#111] opened 2017-04-21 14:50 UTC
## Problem description

C3 crashes when trying to open c3p project from local browser.

## Attach a .c3p

Can't open the project so I can't download a copy, to attach here, and don't know where to locate the browser saved file.

## Steps to reproduce

1. Start Construct 3
2. Open project.
3. Project Crash.

## Observed result

C3 crashed when opening c3p file.

## Expected result

Expected to open normally.

## Affected browsers

* Chrome: yes

## System details

Error report information
Type: unhandled rejection
Reason: TypeError: unexpected type
Stack: TypeError: unexpected type at Function.ǃG.ǃp (https://editor.construct.net/r21/main.js:2:201263) at window.ǃ_Zg.ǃ_$c (https://editor.construct.net/r21/main.js:153:24029) at ne.then.ve (https://editor.construct.net/r21/main.js:153:5179)
Construct 3 version: r21
URL: https://editor.construct.net/
Date: Fri Apr 21 2017 16:47:01 GMT+0200 (CEST)
Uptime: 11.8 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Mac OS X
Operating system version: 10.12_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GTX 775M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2047
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment] 2017-04-21 14:57
Can you go to Project => Open => Local Browser
Right click on the project and select download.
If it works then could you send the c3p over for us to look at. If it crashes then send that stack trace over instead.

**Comment by tunepunk** [comment] 2017-04-21 15:00
Nope... It crashes when I try to download the file as well..

**Comment by tunepunk** [comment] 2017-04-21 15:01
**Error message when I try to download the file as your described.**

Error report information
Type: unhandled rejection
Reason: TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
Stack: TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided. at ne.then.ve (https://editor.construct.net/r21/main.js:153:6674)
Construct 3 version: r21
URL: https://editor.construct.net/
Date: Fri Apr 21 2017 16:59:38 GMT+0200 (CEST)
Uptime: 13.7 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Mac OS X
Operating system version: 10.12_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GTX 775M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2047
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by shortercode** [comment] 2017-04-21 15:50
Sounds like the backing object is missing but the meta data still exists. If that's true it's not something we'll be able to easily replicate at the office. So I'll need a little help to understand it, hopefully I'll be able to put some preventative code in but it depends on the cause.

Do you have any other projects saved in browser storage and do they open? Would you be willing to run a couple of snippets of code in the debugger for me? Nothing crazy; just a couple of lines to get the contents of the meta data store and check if there's any files in the database.

**Comment by tunepunk** [comment] 2017-04-21 16:02
I have another project as well. It's just a copy of the KiwiStory platformer, this one doesn't open as well. When I try to open that one from recent, i get a popup saying "failed to open project".  I did this on purpose a few versions ago to see how reliable the "save to browser" is. Quite recently I had to clear cache because of a bug, after an update. The c3p files are still listed, but they don't load. So i guess they are missing because of the cache clear, but still listed as recent and in the browser projects?

Anyway, this could be pretty serious if you're using browser save as your main storage, forget about your C3 projects, and clear your cache occasionally, because of.... reasons...

Luckily I don't lose anything valuable. As it was just projects for C3 testing purposes. If this is the case, there should be a warning when saving to local browser. As clearing browser cache will delete your projects.

**Comment by tunepunk** [comment] 2017-04-21 16:04
Maybe new Repro .... save a project to local brower ... clear cache ... project still listed, but won't load.

**Comment by shortercode** [comment] 2017-04-21 16:23
Ah so you cleared the cache, not surprised that they don't load then. Little bemused the meta data wasn't cleared as well though. How did you do your cache clear?

There's an option to "request persistent storage" in Menu => About which will cause the browser to notify you when you clear the cache, saying that your attempting to delete C3 data. So that should prevent accidental deletion. I have an outstanding bug to modify the browser save to require persistent storage be enabled, but I'm not working on the editor at the moment.

I imagine a short warning could be placed on the request permission dialog.

Something along the lines of :

> Chrome will prompt you if any action you perform will delete C3 related data ( editor layout, browser saves and user preferences ). Some 3rd party "clean my computer" / "pc tuneup" style programs may not respect this setting so if you regularly use these it is advisable to regularly back up your projects with cloud save or by downloading them.

**Comment by tunepunk** [comment] 2017-04-21 17:52
That makes sense. I don't exactly remember this case, but when I clear cache I usually just clear data. Not passwords cookies etc. I hope some time in the future Scirra will offer their own cloud project hosting option, maybe for a few extra bucks or with business license. With backups, and their own cloud save. I think that would be good value for business, with more safety, in case work get lost/corrupted in any way.

**Comment by AshleyScirra** [comment] 2017-04-21 18:18
@shortercode - I think it's possible that the browser wipes arbitrary parts of storage if it's running low on space, so I guess there ought to be graceful handling of a metadata-only situation anyway.

**Comment by shortercode** [comment] 2017-04-24 13:03
I was under the impression that if it decided to clear local storage it would remove all the data for that domain; to prevent this kind of situation. But I agree that it should deal with it gracefully if either part of the data has been removed, as there's no guarantee that the store will be in a sensible state.

**Comment by shortercode** [comment] 2017-04-24 15:12
Okay so I've made some changes to harden this around the edges. Still needs the warning message though.

So firstly if the file doesn't exist it now display a message instead of crashing.

When a list of files is requested ( IE when the dialog is opened ) we check the content database vs the metadata now. If we have a metadata entry without content we log a warning and delete that metadata entry. If we have a piece of content without metadata then we log a warning and generate a metadata entry for it with a name like `unknown_[FILE_ID].c3p`.

**Comment by tunepunk** [comment] 2017-04-26 07:52
I can see that in r22 now the local projects are no longer listed. So i guess it's fixed now?

**Comment by shortercode** [comment] 2017-04-26 10:05
@tunepunk see my previous post. Files with no content will now be removed from the list.

**Comment by shortercode** [comment] 2017-05-02 11:31
Going to close this bug, as the crash doesn't exist any more. The other related improvements will be tracked on our internal tracker.

**Closed by shortercode** 2017-05-02 11:31 UTC
Labels: no repro
