### ISSUE TITLE
Import animation zip again bug :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6425] opened 2023-01-25 07:21 UTC
## Problem description

I have already reported this bug: https://github.com/Scirra/Construct-3-bugs/issues/6392

In version r327s, I still can't import this archive. I also asked my friends who have Windows 10 and Windows 11 to do this and they also did not succeed. Please try again.

[alt.zip](https://github.com/WilsonPercival/WilsonPercival/files/10496985/alt.zip)

## Attach a .c3p

There is not.

## Steps to reproduce

1. Create a new project.
2. Create a new sprite.
3. Move the animation archive to the animation panel.

## Observed result

Animation is not imported.

https://user-images.githubusercontent.com/91274932/214503229-b3f2ae13-6216-4c1e-a3c8-48a4485bc58d.mp4

## Expected result

Animation is imported.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r327s

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r327 (stable)
Browser: Chrome 109.0.5414.75
Browser engine: Chromium
Context: webapp
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 238 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by GeekManOfficial** [comment] 2023-01-25 07:28
https://user-images.githubusercontent.com/95054989/214504420-96a59d14-52c3-499b-844c-ef6ae24f0796.mp4

i can repeat it on windows 10 21H2

**Comment by DiegoScirra** [comment] 2023-01-25 11:44
Last time I wasn't able to reproduce this, but I just did. It turns out the problem only happens when C3 has been installed as an app.

**Comment by DiegoScirra** [comment] 2023-01-26 13:39
This will be fixed in the next beta.

**Closed by DiegoScirra** 2023-01-26 13:39 UTC
