### ISSUE TITLE
Construct 2 project crashes upon load, Construct 3 will then call it a non valid Construct 2 file (r17 to r19)

### ISSUE THREAD

**Issue by drexegar** [Scirra/Construct-3-bugs#100] opened 2017-04-18 15:25 UTC
## Problem description

My file use to open up on Construct 3, but from r17 to r19 I keep getting the same error message about sprites and then construct just tells me my construct 2 file is not valid.
The error info has been added, if you need to construct 2 file please let me know where I can send a google link privately, but hopefully the error message that pops up the first time can shine some light.

## Attach a .c3p

It is a construct 2 file that contains the object giving the problem:
https://drive.google.com/open?id=0ByybatBADJBNbDV0bVZ0S2ZzSDg

## Steps to reproduce

Can't Reproduce

## Observed result

First time loading the file will show error information, after that construct 3 rejects the file saying its not valid, file still open and runs in construct 2 with no problem

## Expected result

I expected the file to open

## Affected browsers

* Chrome: yes
* Firefox: N/A (didnt test)
* Edge: N/A (didnt test)
* Safari: N/A (didnt test)

## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r19/plugins/sprite/plugin.js, line 1, col 8212
Message: Uncaught TypeError: Cannot read property 'ǃBt' of null
Stack: TypeError: Cannot read property 'ǃBt' of null at a.ǃM.ǃUy (https://editor.construct.net/r19/plugins/sprite/plugin.js:1:8212) at a.ǃM.ǃiv (https://editor.construct.net/r19/plugins/sprite/plugin.js:1:7567) at a.ǃM.ǃiV (https://editor.construct.net/r19/plugins/sprite/plugin.js:1:7352) at te.ǃiV (https://editor.construct.net/r19/main.js:61:215908) at oe.ǃiV (https://editor.construct.net/r19/main.js:61:251362) at Ee.ǃiV (https://editor.construct.net/r19/main.js:61:236995) at window.ǃf_.ǃhr (https://editor.construct.net/r19/components/editors/layoutView/layoutView.js:1:6935) at ǃhZ.j (https://editor.construct.net/r19/components/editors/layoutView/layoutView.js:1:2095)
Construct 3 version: r19
URL: https://editor.construct.net/
Date: Tue Apr 18 2017 11:06:22 GMT-0400 (Eastern Daylight Time)
Uptime: 72.2 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 515 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

<details><summary>View details</summary>

Hopefully the error should help a lot, it seems to have a problem with my sprites or something

</details>

**Comment by AshleyScirra** [comment] 2017-04-18 16:37
Can you produce a minimal .capx as per the guidelines and attach it here?

Assigning to Diego since error message appears to point at something related to sprite animation frames.

**Comment by DiegoScirra** [comment] 2017-04-18 16:58
This seems to be caused by a sprite not having any animations. I am not too sure how that can happen in the first place though.

Maybe it's an edge case of an initialization sequence? I'll look into it.

**Comment by DiegoScirra** [comment] 2017-04-18 17:46
I made a small change that should prevent this problem but without clear reproduction steps we have to wait till the next release to see if it was fixed.

**Comment by drexegar** [comment] 2017-04-19 11:31
Sorry for late reply, went to hospital when typing this and the emails left by github didnt bother to add a link to go straight to the post.

anyways the problem is my sprite, which has 8 animations, all of them with at least two frames, Im using process of elimination to pinpoint the problem and ill send you a file as soon as I find it.

**Comment by drexegar** [comment] 2017-04-19 11:40
OK! SO I deleted everything, all the code all the objects, I even removed animations from the sprite and that didnt solve the problem, so its my current sprite! 

HERE IS THE FILE THAT WILL NOT OPEN:
https://drive.google.com/open?id=0ByybatBADJBNbDV0bVZ0S2ZzSDg

Did my sprite get corrupted or something happen with construct 3 that refuses to open it?

**Comment by DiegoScirra** [comment] 2017-04-19 13:11
@drexegar 

I am able to open the project in the latest build, which we haven't released yet. So I am pretty  sure this one is fixed now. Still, I would like to get your confirmation on this once r20 is out.

**Comment by drexegar** [comment] 2017-04-19 13:51
@DiegoScirra ok will do, looking foward to r20. Thank you for your hard work.

**Comment by AshleyScirra** [comment] 2017-04-20 12:52
Heads up, r20 is out.

**Comment by drexegar** [comment] 2017-04-20 13:12
Ok! All my files open and run fine, I believe its ok to close this bug.

I can resume bug hunting and will be posting more to help construct 3 become great!

**Closed** 2017-04-20 14:26 UTC
Labels: check next release
