### ISSUE TITLE
Export Andoroid Error

### ISSUE THREAD

**Issue by unluckysoon** [Scirra/Construct-3-bugs#6373] opened 2023-01-04 10:36 UTC
## Problem description
Error occurs when exporting unsigned appk to Android.
Build Service: Connected to server
Build Service: Lost connection to build server
"Websocket is not closed"
I'm in Korea.

## Steps to reproduce

1.
2.
3.

## Expected result

[error.zip](https://github.com/Scirra/Construct-3-bugs/files/10343085/error.zip)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2023-01-04 10:53
Duplicate of #6372

**Closed by AshleyScirra** 2023-01-04 10:53 UTC
Labels: duplicate
