### ISSUE TITLE
When errasing any event, the event sheet scrolls up to the firts event

### ISSUE THREAD

**Issue by IJCT95** [Scirra/Construct-3-bugs#49] opened 2017-04-08 15:58 UTC
## Problem description

whenever working on an event sheet and you are going to delete an event, it scrolls up to the firts event on the event sheet and you have to scroll down all back again to where you were working.

## Steps to reproduce

1. open any event sheets with enought events that you will need to scroll.
2. erase one from the bottom

## Observed result
C3 takes me back to the top of the event sheet
*What do you see happen?*
the events scroll up

## Expected result

*to stay where i was working*

**Comment by jaydonteh** [comment] 2017-04-09 12:39
I cannot reproduce this bug both on Windows chrome and Android chrome beta. It stays well at where I delete the event, no jerking up to the top. Tried using templates in C3 and also duplicate 40 lines of event to try reproduce but I can't.

I'm on version r16.

**Comment by jaydonteh** [comment] 2017-04-09 12:53
I manage to figure out how to reproduce this. Initially making a bunch of events to stretch the height of the page doesn't work, delete them from the bottom does not jerk them up to the top. It only works when you nest events in groups or have sub-events, then start deleting from the bottom and it will jerk to the top when the parent event is deleted or the Group head is deleted.

**Comment by AshleyScirra** [comment] 2017-04-11 12:56
No repro provided, but I could reproduce this in the Ghost Shooter tutorial. Should be fixed for r18.

**Closed by AshleyScirra** 2017-04-11 12:56 UTC
