### ISSUE TITLE
C3 Run Time (New TileMovement) Black Screen

### ISSUE THREAD

**Issue by Tarek200** [Scirra/Construct-3-bugs#2196] opened 2018-10-29 15:24 UTC
## Problem description

Black screen when trying to Preview a project that has one object with the New TileMovement Behaviour

## Attach a .c3p
[https://www.dropbox.com/s/o8pq2dse8603m1i/TileMovemen%20tBug.c3p?dl=0](url)

## Steps to reproduce

1. Hit Preview to test the project and you will see that it starts with a black screen  

## Observed result

The project starts with a black screen 

## Expected result

The project starts showing the Layout with the blue sprite

## Affected browsers

* Chrome: Yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

Windows 10 

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2018-10-29 15:39
Are you testing with r123? Please always include the requested information.

**Comment by Tarek200** [comment] 2018-10-29 16:34
> (Are you testing with r123? Please always include the requested information.)

Yess Ashley with the latest r123

What info did I miss? you mean the C3 Version?
It didn't ask me about the C3 version unless I missed it or misunderstood this is the info they request me. 
Txt File:
[https://www.dropbox.com/s/d60llwixih77p3k/BUG%20Guide%20Lines.rtf?dl=0](url)

**Comment by AshleyScirra** [comment] 2018-10-29 16:44
The bug report template asks you to paste your system information. If you do that, it includes the C3 version and lots of other useful information that helps us deal with bug reports.

**Comment by Tarek200** [comment] 2018-10-29 17:03
> The bug report template asks you to paste your system information. If you do that, it includes the C3 version and lots of other useful information that helps us deal with bug reports.

Ok cool thanks for the info I didn't know we have to paste the full info I will remember for the next time 
Now I may sound really stupid but when you say (system info) you mean this one? or a different one
[https://www.dropbox.com/s/aaczw5gaqcwq710/System%20Info.png?dl=0](url)

I ask because I didn't see the C3 Version in there either I'm pretty sure you are referring to different system info that I can't think which one it is right now but if you let me know I will post it and I will remember for the next time sorry for the headache

**Comment by AshleyScirra** [comment] 2018-10-29 17:16
> If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to Menu > About > Platform information and paste that information there instead.

**Comment by shortercode** [comment] 2018-10-29 18:37
This seems to have been caused by changes for solid collision filtering. I've corrected the code so that it no longer fails, but as you made the change it would be good if you could validate that it is correct @AshleyScirra.

**Comment by Tarek200** [comment] 2018-10-29 18:59
> Just read what the template says:
> 
> If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to Menu > About > Platform information and paste that information there instead.

Omg I feel such an idiot im totally blind :) :) I swear I didn't see that part I normally stop reading on the first part ( If you see a crash report dialogue, please copy and paste it to where it says) as it didtn give any Bug Report so I skipped the next Txt where it says (Otherwise please go to Menu > About > Platform information and paste that information there instead.)


I deeply apologyce again for my neglectfulness I will remember for the Next Time 
thanks gain for your patients 

**System Info:**
[https://www.dropbox.com/s/co3965xpl6uyiol/Bug%20Ghide%20Lines.pdf?dl=0](url)

**Comment by AshleyScirra** [comment] 2018-10-30 11:15
It's more convenient to simply copy and paste the information in to the report, there's no need to save it as a PDF. Please also check your markdown formatting, none of the links you are posting are clickable because the formatting is wrong.

This should be fixed for the next release now.

**Closed by AshleyScirra** 2018-10-30 11:15 UTC
