### ISSUE TITLE
Instant Game zip exported file issue

### ISSUE THREAD

**Issue by caioleony** [Scirra/Construct-3-bugs#6439] opened 2023-01-30 16:01 UTC
## Problem description

After the new release 327, when export the game to Instant Game and tried to upload the package to the Facebook Instant Games platform, a problem is reported:

"Game must use the Instant Games SDK properly and should not call private methods directly."

This problem was not happening in previous versions and I just noticed that if decompressed and compressed again (manually) we were able to upload.

## Attach a .c3p

[Example.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/10537521/Example.c3p.zip)

## Observed result

![photo_2023-01-30_12-57-31](https://user-images.githubusercontent.com/11369581/215530141-d440a9b0-c4d5-4377-970b-4efc8b93a78d.jpg)

## Expected result

Should be able to upload directly after being exported from Construct 3 with Instant Game plugin

**Comment by AshleyScirra** [comment] 2023-01-30 16:27
Duplicate of #6429. Please report it to Facebook.

**Closed by AshleyScirra** 2023-01-30 16:27 UTC
Labels: duplicate
