### ISSUE TITLE
Box2d stops running after several minutes

### ISSUE THREAD

**Issue by wiverson** [Scirra/Construct-3-bugs#838] opened 2017-09-26 01:03 UTC
## Problem description

Exporting an app with Box2d to iOS and running it for longer than ~10 min causes the app to lock up.

I was able to attach Safari to my iPad and got the following exception:

a: "abort() at fb@file:///var/containers/Bundle/Application/C4B07F64-F07A-4AB4-ABCB-7721171A4F40/Alpha%20Explorer.app/www/c2runtime.js:34149:3…"

The Safari Web Inspector shows this as an abort thrown from the top of the box2d asm.js compiled code.

<img width="1496" alt="screen shot 2017-09-25 at 1 50 23 pm" src="https://user-images.githubusercontent.com/873850/30837720-cfb435ea-a21b-11e7-8cf6-0a8880937d1c.png">
<img width="1861" alt="screen shot 2017-09-25 at 5 56 35 pm" src="https://user-images.githubusercontent.com/873850/30837723-d3bb9f52-a21b-11e7-9ffa-5ee68239cbfb.png">
<img width="2558" alt="screen shot 2017-09-25 at 5 57 06 pm" src="https://user-images.githubusercontent.com/873850/30837725-d6dd85ba-a21b-11e7-99b8-d0afd7ed4a2b.png">

## Attach a .c3p

I have tried to isolate this down to a specific example, but am unable to do so.  I am able to reliably trigger the error by launching my app and starting and returning to my layout.  After ~10 minutes each time I hit the same error.

I am happy to send along my project to someone at Scirra (it's not all that big) but I don't want to post it to the Internet for anyone to download.

## Steps to reproduce

Apologies, these repro steps only work if you have my app.

1. Launch app
2. Tap on Letter Match 
3. Pick any game option, 240s is least annoying
4. Let the game sit (user input optional)
5. Repeat the game running for apx 10 minutes.
6. Game render loop locks up, Box2D generates assertion in Safari as shown.

## Observed result

UI Completely stops working.

## Expected result

My game to work. ;)

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: no
* Safari iOS: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 60.0.3112.113
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
C3 release: r58
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 1.2 gb (3.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M290X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by wiverson** [comment] 2017-09-26 05:58
There is a reference to doing a build with -s ASSERTIONS=1 in the exception, not sure where/how I would do that...?

**Comment by wiverson** [comment] 2017-09-26 16:35
Confirmed that I can repro the bug in Chrome on my desktop.  Here's the message from Chrome:

```
Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 33554432, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
09:32:56.276 runtime.js:10 Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 33554432, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
09:32:56.277 runtime.js:7 Uncaught abort() at Error
    at fb (https://editor.construct.net/r59/behaviors/physics/c2runtime/runtime.js:31:26)
    at ua (https://editor.construct.net/r59/behaviors/physics/c2runtime/runtime.js:417:61)
    at Function.o [as W] (https://editor.construct.net/r59/behaviors/physics/c2runtime/runtime.js:17:91)
    at nc (https://editor.construct.net/r59/behaviors/physics/c2runtime/runtime.js:167:483)
    at NB (https://editor.construct.net/r59/behaviors/physics/c2runtime/runtime.js:196:40914)
    at _f (https://editor.construct.net/r59/behaviors/physics/c2runtime/runtime.js:184:24253)
    at Fx [as g] (https://editor.construct.net/r59/behaviors/physics/c2runtime/runtime.js:654:22)
    at behaviorProto.Instance.behinstProto.createBody (https://editor.construct.net/r59/behaviors/physics/c2runtime/runtime.js:1551:16)
    at behaviorProto.Instance.behinstProto.tick (https://editor.construct.net/r59/behaviors/physics/c2runtime/runtime.js:1888:9)
    at Runtime.logic (https://editor.construct.net/r59/preview/c2/preview.js:2630:29)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
c @ runtime.js:7
ua @ runtime.js:417
o @ runtime.js:17
nc @ runtime.js:167
NB @ runtime.js:196
_f @ runtime.js:184
Fx @ runtime.js:654
behinstProto.createBody @ runtime.js:1551
behinstProto.tick @ runtime.js:1888
Runtime.logic @ preview.js:2630
Runtime.tick @ preview.js:2354
tickFunc @ preview.js:639
requestAnimationFrame (async)
Runtime.tick @ preview.js:2265
tickFunc @ preview.js:639
[dupes deleted]
tickFunc @ preview.js:639
requestAnimationFrame (async)
Runtime.tick @ preview.js:2265
tickFunc @ preview.js:639
09:32:56.292 runtime.js:10 Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 33554432, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
09:32:56.293 runtime.js:10 Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 33554432, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
```

This error appears over and over in the JS log.

**Comment by wiverson** [comment] 2017-09-26 16:37
I'm not creating a particularly large number of objects, so I'm not sure why I'm getting what looks like an out-of-memory error.

**Comment by wiverson** [comment] 2017-09-26 16:38
The repro this morning was on r59.  Chrome Version 60.0.3112.113 (Official Build) (64-bit).  Mac OS High Sierra (10.13).

**Comment by wiverson** [comment] 2017-09-27 20:50
I sent along a link to the project file on Dropbox to support@scirra.com.  Let me know if there is anything else I can do.

I'm confused by the create fixture failing - that object is just a layout object, not sure why it would be getting a new fixture.  Can't see anything in the project that is even affecting the Sprite in question at that time - it's an immovable object created by the layout.

**Comment by AshleyScirra** [comment] 2017-09-28 12:26
It is literally 10x easier to deal with bug reports if you can isolate it to a minimal project and attach the project to the report.

**Comment by wiverson** [comment] 2017-09-28 15:19
I understand your perspective.  As I sent along the project file to support - it's not very big - I am doing my best.  It's an amazingly annoying bug - I don't know why it takes the wait to trigger.  The one good thing(?) is that I am able to consistently trigger it.

To trigger it, open the project, click Letter Match and hit Ready.  Open the JS console.  Wait and watch.  You don't have to do anything but keep an eye on the JS console.

I don't know if this is related to the https://github.com/Scirra/Construct-3-bugs/issues/855 

I will offer the observation that these kind of memory or performance issues can be very hard to track down, and that isolating them to a reproducable project at all (which I have supplied via email) is difficult.  Real world bugs in projects do not always work out so easily.

**Comment by AshleyScirra** [comment] 2017-09-28 16:09
Any bug that involves "wait 10 minutes" in the repro steps is pretty much infeasible to fix - we may have to run through the steps dozens of times while diagnosing the issue. This means it could take literally days to fix the problem, and this is far too time consuming when we deal with hundreds of reports. Marking as "no repro" as the given steps are not feasible for repro.

It looks like some kind of memory leak. Ideally this can be narrowed down to something specific that causes the memory leak, then a special project could be prepared that just does that action repeatedly. This should be able to reproduce the issue in ideally seconds, but for it to be feasible to fix, at least <30 seconds.

**Comment by wiverson** [comment] 2017-09-29 04:44
So, here is what I can tell you about the bug right now:

- The out of memory error is coming from inside the Box2d memory pool.  Using the Chrome memory allocation as well as the Construct debugger, there are no allocations of new objects at the user level occurring.  Overall memory use is absolutely rock solid flat.

- The specific cause of the OOM error is a runaway call to createBody(), allocating a new fixture to Box2d by the Construct runtime.

- This allocation is coming from this chunk of code:

```
	if (this.recreateBody || inst.width !== this.lastWidth || inst.height !== this.lastHeight
			|| inst.cur_animation !== this.lastAnimation || inst.cur_frame !== this.lastAnimationFrame
			|| (inst.tilemap_exists && inst.physics_changed))
		{
			this.createBody();

```

Looking at the values in the debugger, it is specifically inst.width != this.lastWidth that is evaluating to true and causing the allocation.  In the debugger right now, I'm seeing inst.width evaluate to 174.9245514594595 and last.width evaluate to 174.92455354541357 - the trailing digits precision error is causing a loop of createBody() fixture allocation, which is in turn blowing up Box2d with the memory allocation specific to Box2d.  I agree that allocating more memory to Box2d would not solve the issue.

Why is this occurring?  I don't know.  The objects in question are flagged as immovable in Construct, so I don't know why the width values are so close but not quite the same.  I don't know why the physics engine runs for ~10 minutes before this kicks in.

It's not a user application object allocation issue.  I am not allocating any new objects. I would guess there is some timing issue related to Box2d that is causing the two width values to fall apart.

I don't believe I have any way to control the timescale for the Box2d engine.  I'm going to try bumping the velocity and position stepping up a ton and see if that helps.

I'm not asking for days of time to repro this.  I would appreciate a few minutes of time for you to at least download and run the capx and verify the behavior and that it is not a user memory allocation bug.  Not wanting to invest the time to debug and resolve this is one thing, but from where I sit I have provided a crashing, reproducible bug in Construct related to the Box2d physics engine, with a detailed exception & stack trace and a capx to replicate the issue.  

I'm happy to continue to investigate and continue to try to sort this out, but only if you are interested in working on it.  If this is not a priority or of interest, that's fine too - let me know and I'll drop it.

**Comment by wiverson** [comment] 2017-09-29 05:56
A few additional details:

Setting a breakpoint shows that inst.width !== this.lastWidth (which leads to the call to createBody()) is occurring very quickly.  No need to wait for 10m for this to repeat.

Changing the physics stepping to Framerate independent and Set time scale to 10 does affect the game, but does not appear to affect the wait until the oom is hit.

It appears that inst.width !== this.lastWidth is being called every tick, regardless of timescale and number of objects, and it's just running until it fills up Box2d memory.  If you don't want to wait ten minutes, the only thing I can suggest is rebuilding with a much smaller memory allocation for the Box2d (a la compile the value -s TOTAL_MEMORY=X with a dramatically lower X).  I don't think that's necessary - I think you just need to sort out why inst.width and this.lastWidth are not aligning.

**Comment by shortercode** [comment] 2017-10-04 11:14
@wiverson I tried to reproduce your `inst.width !== this.lastWidth` with a basic project but it didn't repeat. If you have a simple example project can you post it here, otherwise if you can only replicate with your project please send it to iain@scirra.com

**Comment by AshleyScirra** [comment] 2017-10-04 11:24
That line of code is just to update the size of the physics body when the object size changes. If the object size is changing, then everything is working normally.

Can you attach a minimal project to this report? It makes it far easier to deal with bugs.

**Comment by wiverson** [comment] 2017-10-04 23:04
The object size is not changing by any user code.  It is an immovable object in the physics.  I was able to see the change occurring immediately by setting a breakpoint.  I sent a link to my project to support@scirra.com already, will send it along to iain@scirra.com as well.

The project is really not that big, but I don't want to post it to a public forum.  It's a small educational app that is actually almost done - I found it doing user testing with my nephew, which is why I originally thought it was an iOS-specific bug.

I have tried to recreate it several times with smaller projects, but have been unable to isolate it.  I have all sorts of whacky ideas, but quickly wind up stepping through a lot of Construct runtime code.    I could list my ideas (some kind of float conversion issue coming in and out of Box2D? Stepping/timing issue?  Something peculiar about the physics configuration of the objects?).

I will send you a check for(another) $100 if you can isolate it down to something that a "no programming required" user would have any ability to resolve or fix.  ;)

**Comment by shortercode** [comment] 2017-10-05 15:39
The objects that is being resized are your "invisible walls", they are rapidly oscillating in width because of the anchor. Try watching the debugger and you'll see them moving. Not quite sure why the anchor is causing but there's the reason the function is being called a lot.

The function itself doesn't appearing to be obviously leaking, it's certainly calling DestroyBody on Box2d before creating a new one. It's not 100% clear on how it deals with memory in the original code, so it could be leaking, fragmenting or just not bothering to clear completely.

**Comment by shortercode** [comment] 2017-10-05 15:47
Incidentally I used `var _width = inst.width; Object.defineProperty(inst, "width", { get () { return _width; } set (v) { debugger; _width = v; } });` to find where the width value was being updated.

**Comment by AshleyScirra** [comment] 2017-10-05 16:15
Here's a minimal repro. The problem is if you add Anchor and Physics behaviors to the same object, something really strange happens and the object continually grows.
[physics-anchor.zip](https://github.com/Scirra/Construct-3-bugs/files/1360079/physics-anchor.zip)
I don't know why you need the Anchor behavior. It doesn't seem necessary and we recommend against combining Physics with other behaviors in our documentation too, to avoid the teleporting effect. I suspect somewhere there's a real memory leak as well, but the Anchor bug hammers the body creation hard since it continually resizes so continually has to destroy the physics object and teleport in a new physics object to take the new object size. This shouldn't happen, and if it doesn't happen it should drastically reduce the impact of the memory leak.

**Comment by wiverson** [comment] 2017-10-05 16:27
I'm using the walls with Anchor to support different scaling scenarios.  I tried removing Anchor from the project and was still seeing the problem.  Anchor + Physics was one of the first things I thought of, and that started a process for me of deleting things to try to winnow it down.  I tried moving the Invisible Walls so they weren't overlapping, removing Anchor, changing stepping values, changing the stepping time.  :(

I will try removing Anchor again and rerunning to see what happens.

**Comment by AshleyScirra** [comment] 2017-10-05 16:30
Okay, well you can replace it with events using the system viewport expressions. If you just set it once on start of layout that should guarantee there's only one update.

**Comment by wiverson** [comment] 2017-10-05 21:29
Nope, nothing else in my project that changes the size.  I took the project I sent you, removed Anchor and it ran for several hours with no problem.  I thought I had tried that already - I apologize for that.

RE: replacing Anchor with expressions, no problem.

FWIW, my interpretation as an end user of the Anchor object was that it would trigger on initial layout load and on a resize event, but not as part of the ongoing update loop.  I've been bitten twice now by someone unintuitive bugs related to physics - this one, and the Box2D incompatibility with iOS and Minify.  I'm not sure what or how to deal with this - a UI alert that some behaviors are incompatible?  Disable Minify on export if you are using Physics?

I know that these Qs are totally outside the bounds of this bug report, but I just want to leave them as food for thought.

Thank you for your time reviewing.  For me, this bug report is resolved with the workaround, but there is no UI answer to keep this from popping up again for a non-technical user.  Let me know if there is anything else I can do.

**Comment by AshleyScirra** [comment] 2018-01-29 14:04
Finally got to the bottom of this and should have it fixed in r82. I've backported the fix to C2 as well.

FWIW this is the repro I used to figure this out: [PhysBodyStress.zip](https://github.com/Scirra/Construct-3-bugs/files/1673779/PhysBodyStress.zip) - it reproduces the issue in seconds, rather than over 10 minutes, which makes it something like 100x quicker to fix. (That's the importance of a good repro!)

**Closed by AshleyScirra** 2018-01-29 14:04 UTC
Labels: backported to c2

**Comment by wiverson** [comment] 2018-01-29 17:35
Really?  All of that back and forth, isolating things down, hooking up the debugger, to narrow things down etc. and you are still critiquing that I wasn’t able to isolate this down to a shorter time repo time?

**Comment by AshleyScirra** [comment] 2018-01-29 17:40
No, sorry, I didn't mean to critique. It's just to demonstrate the importance of this aspect of a bug report to anyone who may be following this issue. It can make the difference between an issue taking months to resolve, or fixing quickly.
