### ISSUE TITLE
Not all conditions combined from two words are taken into account

### ISSUE THREAD

**Issue by Vladimir7527** [Scirra/Construct-3-bugs#3803] opened 2020-04-25 09:26 UTC
## Problem description
If you write the condition in one word (for example animation name like this: **girl1**), then they are all satisfied. But if you use compound words in the animation name, for example like this: **character.gender & "1"**, then not all will be executed, but only some of them.

## Attach a .c3p
[https://yadi.sk/d/p5yzStkbn-czzw](url)

## Steps to reproduce

1. Run project - not all characters will run
2. If you will run disabled action, where animation names written in one word, then all characters will run

## Observed result
In my case, characters with animation names girl5 and girl8 are not running.

## Expected result
All characters should run

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
r189.2
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 81.0.4044.122
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
C3 release: r189.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 143 gb
Storage usage (approx): 3.9 gb (2.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2020-04-27 11:48
OR blocks are an extremely complicated part of the engine with lots of difficult edge cases, and this seems to run in to one of them. The problem is the expression `character.gender` normally picks the "current instance being checked", but the way OR blocks work means the "current instance being checked" was one which failed a previous condition, resulting in the wrong instance being picked to evaluate the expression with. I doubt this will be easy to solve.

Meanwhile the events you are using are wasteful using a lot of unnecessary repetition. You really just want to check "does the current animation name start with `character.gender`". You can do that with a single event like this:
[move_test_alt.zip](https://github.com/Scirra/Construct-3-bugs/files/4539371/move_test_alt.zip)
It's also not limited to 8 animations like your previous event, it will work with any number.

**Comment by Vladimir7527** [comment] 2020-04-27 13:04
This is strange, but I can not open your file. Construct 3 tells me “Unknown file extension”.
But anyway, in the test example, I just wanted to portray the found bug, and not show the effective code.
In the game I make, there is a character in one sprite of which there are animations for two of its variants, unarmed and armed. See the screenshot here: [https://yadi.sk/i/Di0ZH68n56pl4w](url)
I ran into a problem when I needed to animate her jump. See the screenshot here: [https://yadi.sk/i/LXSONp1qx72ryQ](url)
In condition No. 375, after the Vishera.vajra & "IdleToJump" animation, the Vishera.vajra & "Jump" animation should follow, and then the jump. But in reality, the character just jumps and the animation remains the same.
In event No. 376, I circumvented this bug using the condition Platform is jumping.
I wish you success!

**Comment by AshleyScirra** [comment] 2020-04-27 15:01
The project works fine here, just drag and drop the file in to C3.

**Comment by Vladimir7527** [comment] 2020-04-27 15:42
You are right, but now I have a too old version of the program :)
I prepared a project with the problem I described above. You can download it here: [https://yadi.sk/d/eeO8JBJpwvMJuw](url)
Look at event No. 19, the Vishera.vajra&"Jump" animation should play there, but it won’t play, the character just jumps.

**Comment by AshleyScirra** [comment] 2020-04-27 16:54
For the purposes of reporting a bug the original project is more useful - see the bug report guidelines. I was just pointing out a workaround using simpler events. It should work in the latest release.

**Comment by AshleyScirra** [comment] 2020-09-11 15:18
I don't think it's feasible to fix this in the current event engine architecture, or if it was possible it would impose a performance cost to all projects, even if they didn't have any relevance to this at all. I don't think that is a sensible trade-off, and as noted this particular case seems to only happen because the events were needlessly repeated. The workaround I provided uses shorter and better events and has no issue, so there doesn't seem to be a pressing need to fix the problem with the particular case of needlessly repeating events, so closing this issue as wontfix.

**Closed by AshleyScirra** 2020-09-11 15:18 UTC
Labels: difficult, wontfix
