### ISSUE TITLE
Remote preview problem (r150 Beta)

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#2969] opened 2019-05-25 16:36 UTC
## Problem description

Today, the remote preview don't work anymore. When i run with remote preview a complete empty project, i get always this error:

[Show Screenshot](https://drive.google.com/open?id=106gajp8jCWovQT_QsFAXHfSdlOCSwiOo)

## Attach a .c3p

[Empty Example-Project](https://drive.google.com/open?id=1__qpdGOtiI462W91Yt-Ap5vMrUVEyutO)

## Steps to reproduce

1. Open the example project (or create a empty project)
2. Run it with remote preview
3. Open the Preview-URL on chrome

## Observed result

Get a error-message

## Expected result

Works without errors

## More details

**Affected browsers/platforms:**

- Chrome on PC
- Chrome on Android (Samsung Galaxy S7)

**First affected release:**

r150 Beta

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.38.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.38.0 (like Chrome/74.0.3729.108)
C3 release: r150 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 22 gb
Storage usage (approx): 479 mb (2.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by luckyrawatlucky** [comment] 2019-05-28 02:22
Same problem i am facing.

**Comment by AshleyScirra** [comment] 2019-05-28 09:58
This should be fixed in the next release, but let's check since it involves server-side changes.

**Comment by AshleyScirra** [comment] 2019-05-28 13:12
r151 is out, can you confirm it is working there?

**Comment by luckyrawatlucky** [comment] 2019-05-28 14:50
@AshleyScirra 
I have check this in Android and Desktop. This is working. 
But its not working in iPhone. tried with iPhone 7Plus, Software 12.2

**Comment by luckyrawatlucky** [comment] 2019-05-28 15:00
Okay Now its working perfectly.
There was same issue in iPhone but i did clear cache and now it working on iPhone, Desktop and Android mobile.

Thanks

**Comment by AshleyScirra** [comment] 2019-05-28 15:07
I saw something similar - it reproduced once on an iPad but after retrying it started working, so I think this is just a caching issue. Closing as it looks like it sorts itself out after a couple of reloads or clearing cache.

**Closed by AshleyScirra** 2019-05-28 15:07 UTC
Labels: need info
