### ISSUE TITLE
Tweening Object and Destroy Outside Layout Causes Freezing

### ISSUE THREAD

**Issue by emcannon** [Scirra/Construct-3-bugs#3033] opened 2019-06-11 15:47 UTC
## Problem description

While making a game, I noticed that when entering a layout where an object is getting tweened and destroyed by the destroy outside layout behavior, it causes freezing. This also happens after a reload layout.

## Attach A c3p
[Flies.zip](https://github.com/Scirra/Construct-3-bugs/files/3277354/Flies.zip)

## Steps to reproduce

1. Start on layout 2
2. Click placeholder texture to enter layout 1
3. Observe freezing

## Observed result

Freezing. In debug, both the Time and WallClockTime values stop ticking.

## Expected result

The game would progress as normal. (IE: Start on layout 1)

## More details

**Affected browsers/platforms:** Preview, Remote Preview, Debug Preview

**First affected release:** Preview

## System details

<details><summary>View details</summary>

Browser: Chrome
Browser version: 74.0.3729.169
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
C3 release: r148 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 518 mb (3.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2019-06-11 17:58
Duplicate of #2999.

This is fixed already and available in the latest beta r153.

**Closed by DiegoScirra** 2019-06-11 17:58 UTC
Labels: fixed
