### ISSUE TITLE
[THEME] Event Block Shadow Indent Inconsistent in Dark and Light Themes

### ISSUE THREAD

**Issue by LukeNecklace** [Scirra/Construct-3-bugs#2735] opened 2019-03-14 14:05 UTC
## Problem description

In the default theme of Construct, there is an indented shadow underneath the conditions of each block if there are more action lines then condition lines (this includes the 'add action'). I find this helps clearly separate each block in the event sheet.

If memory serves me well, this did not exist in the early stages of Construct 3 but was later added (good). However, it was not added to the dark or light themes.

I will post screenshots you can easily see the differences in the design of each block depending on the theme selected.
![Default Theme Event](https://user-images.githubusercontent.com/28833199/54364558-372f7400-46c1-11e9-97f1-1c53284d3183.png)
![DarkThemeEvent](https://user-images.githubusercontent.com/28833199/54364561-3a2a6480-46c1-11e9-854a-b8ccf4812cf7.png)
![LightThemeEvent](https://user-images.githubusercontent.com/28833199/54364562-3bf42800-46c1-11e9-9d3e-d2e29a2737b3.png)

## Attach a .c3p

https://www.dropbox.com/s/1vdma46of9v2yjc/Event%20Block%20Shadow%20Indent%20Inconsistent.c3p?dl=0

## Steps to reproduce

1. Change the theme in settings to a different theme than the one you.
2. Reload Construct 3.
3. Do this for each theme.

## Observed result

The event block shadow indent does not exist on the dark or light themes but do exist on the default theme.

## Expected result

I expected the other themes to also have an event block shadow indent in this manner.

## More details
Also as a tweak; for the dark theme, is it possible to make this shadow darker so it is more noticable?

**Affected browsers/platforms:** 
Chrome
Microsoft Edge
Firefox

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r141.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 27 gb
Storage usage (approx): 775 mb (2.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment] 2019-03-15 11:04
Not sure if this is intentional or not, assigning to @Animmaniac to review.

**Comment by Animmaniac** [comment] 2019-03-21 21:08
This is by design to simplify the perceived complexity of eventsheets. Complex hierarchies get easier to understand at a glance without the indent, as the indent gives the impression there's an extra level to the hierarchy that isn't actually there.

**Closed by Animmaniac** 2019-03-21 21:08 UTC
Labels: theme
