### ISSUE TITLE
Layer scale is not reset to default

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#4935] opened 2021-07-03 22:28 UTC
## Problem description

When you scale a layer, go to another layout, and then go back to the previous layout, the scale remains the same as it was, and is not set to its default editor settings.
## Attach a .c3p

https://www.dropbox.com/s/jl50q2ota1bl1kl/layerscales.c3p?dl=1
## Steps to reproduce

1.Run the project
2.Wait for the layer to be scaled by events
3.Note the change of the layer scale
4.Click the sprite to move to the second layout
5.Click the sprite on the second layout to return to the first layout
6. Note the scale for the layer has not been reset

## Observed result

The layer is not reset to its default setting
## Expected result

The layer should return to the editor settings unless its a global layer
## More details

**Affected browsers/platforms:** 
w10 Chrome

**First affected release:** 

## System details
Stable

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2021-07-06 08:56
Layer properties are effectively global at runtime. I guess it could be argued that this is by design. Even if it is seen as a design mistake, it seems plausible that many projects could be depending on the current behavior, and changing it would be a breaking change for a lot of people. I don't think it's worth the headaches it would probably cause for a lot of users, especially when the workaround is simple (just reset all layer properties in 'On start of layout'). Therefore closing as wontfix.

**Comment by AshleyScirra** [comment] 2021-07-06 08:57
For reference, #4698 is also related.

**Closed by AshleyScirra** 2021-07-06 08:56 UTC
Labels: wontfix
