### ISSUE TITLE
Preparing Images 0%.... on iPhone 7. Cannot start preview.

### ISSUE THREAD

**Issue by sergeypisarev85** [Scirra/Construct-3-bugs#1487] opened 2018-04-14 18:17 UTC
## Problem description

Hello. I was trying to preview my project from iPhone 7(iOS 11.3 latest), but when i click Play button, it says me(Preparing Images (0%)...) and that's all. Nothing happens. Reloading, or even restarting iPhone doesn't help.

## Attach a .c3p

[The Mage.zip](https://github.com/Scirra/Construct-3-bugs/files/1910697/The.Mage.zip)

## Steps to reproduce

1. Click Preview button on iOS Safary.
2. 
3.

## Observed result

*What do you see happen?*

Playing a project.

## Expected result

*What did you expect to happen instead?*

Not loading...

Preparing Images (0%)...

Here is the images:
https://ibb.co/cngihS
https://ibb.co/c7fn97
https://ibb.co/kJF9NS

## Affected browsers

* Chrome: no
* Firefox: 
* Edge: 
* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 11.0
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: iOS
Operating system version: 11.3
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Downloading local content is not supported.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Metal - 52.3.2)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Apple Inc.
Renderer: Apple A10 GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions:

EXT_blend_minmax
EXT_sRGB
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_depth_texture
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 48000 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by AshleyScirra** [comment] 2018-04-15 11:15
Duplicate of #1460

**Closed by AshleyScirra** 2018-04-15 11:15 UTC
Labels: duplicate
