### ISSUE TITLE
Gamepad not detected in preview run but works in debug

### ISSUE THREAD

**Issue by Pascpell** [Scirra/Construct-3-bugs#64] opened 2017-04-13 01:00 UTC
## Problem description

I am using a dualshock 4 controller directly connected on a usb port of my samsung chromebook C303, and the controller is not detected when I run the project in preview, but is working perfectly in debug.

## Attach a .c3p

*See the "gamepad control" project in the beginner examples

## Steps to reproduce

1. With a dualshock 4 plugged in, open the gamepad control project from the beginner examples.
2. Press the preview button, and once the game is running, push any buttons on the controller.

## Observed result

In preview mode, nothing is happening when you press any button in the gamepad, the text field still says "No gamepad detected yet" no matter what. But if you do the same thing in debug mode instead, the controller is instantly recognized from the first button input. The controller informations are then displayed in the text label and the inputs are working just as intended (Moving and shooting).

EDIT: I also just noticed that if I click on preview while debug is running with the gamepad ok, the debug windows will reload to preview mode and the controller will now work... but if I close it and reopen it directly on preview the gamepad won't be detected again.

## Expected result

The gamepad should be detected when the game is running in preview mode

## Affected browsers

* Chrome: yes
* Firefox: no
* Edge: no
* Safari: no

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 57.0.2987.146
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Chrome OS
Operating system version: (unknown)
Operating system architecture: 32-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
User agent: Mozilla/5.0 (X11; CrOS armv7l 9202.64.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.146 Safari/537.36

Local storage
Storage quota (approx): 568 mb
Storage usage (approx): 86 mb (15.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: ARM
Renderer: Mali-T604
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

EXT_disjoint_timer_query_webgl2
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2017-04-13 11:17
I can also reproduce this on Windows with an Xbox 360 gamepad so it doesn't seem specific to Chromebook.

I am pretty sure this is a Chrome bug so filed here: https://bugs.chromium.org/p/chromium/issues/detail?id=711252
Closing this report, please star the Chrome bug to follow further updates.

**Comment by AshleyScirra** [comment] 2017-04-13 11:18
BTW a workaround is to change the preview mode to "dialog" in settings, which then appears to work.

**Closed by AshleyScirra** 2017-04-13 11:17 UTC

**Comment by Laughing14** [comment] 2017-06-23 10:17
Thank you Ashley. Apologies for the dupe report. p.s. I'm loving C3! Great job.
