### ISSUE TITLE
Crash / Console error on layout change

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#4011] opened 2020-07-03 16:25 UTC
## Problem description

As of r206, I'm suddenly getting an error when changing layouts:
![Annotation 2020-07-03 112133](https://user-images.githubusercontent.com/36490901/86485855-743cd100-bd1f-11ea-9318-5fdcb2b24349.png)

## Attach a .c3p

.c3proj is a full-scale commercial project and I cannot possibly trace it down to a single object or behavior. Judging by the error, I would assume it's tween related and possibly caused by this latest change:
![Annotation 2020-07-03 112417](https://user-images.githubusercontent.com/36490901/86485990-c8e04c00-bd1f-11ea-918d-f86bd9522f03.png)

## Steps to reproduce

1.
2.
3.

## Observed result

Error

## Expected result

No error

## More details

**Affected browsers/platforms:** 
Desktop / Chrome

**First affected release:** 
r206
## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.46.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.46.3 (like Chrome/83.0.4103.106)
C3 release: r206 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 797 gb
Storage usage (approx): 163 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by BonzerKitten** [comment] 2020-07-03 19:08
I already had to narrow down one of my big commercial projects 3-4 times in the most recent weeks because of fatal crashes related to the Tween Behavior and the Save/Load Actions, this process of searching for the cause of a bug can take literally days and it's so so annoying to waste time of things like that. I opened my project today hoping that the #3979 issue would have been fixed, but was surprised by a new error right after trying to leave the game introduction. 🙄
I couldn't even test if the #3979 issue was fixed or not...

Here's a screenshot of my console, apparently it's the same error, so please give this the deserved attention: https://imgur.com/a/kKuZb1W

**Comment by DiegoScirra** [comment] 2020-07-07 15:06
Duplicate of  #4002. This was caused by attempting to fix #3997. Both cases should be working properly from now on.

**Comment by BonzerKitten** [comment] 2020-07-07 15:17
Thanks a lot @DiegoScirra! I'll check if it's working as soon as the next beta goes live.

**Closed** 2020-07-13 13:20 UTC
Labels: fixed
