### ISSUE TITLE
animation editor, right-click > preview animation crash

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6335] opened 2022-12-14 22:20 UTC
## Problem description

In the animations editor, right-clicking an animation and selecting "preview animation" crashes c3

## Attach a .c3p

not project specific
## Steps to reproduce

1. right-click an animation in the animation editor
2. select preview animation

## Observed result
crash

## Expected result
animation is previewed

## More details
I guess this is just an oversight after the animation preview got changed this patch. The Button still works, just the context menu option crashes it

**Affected browsers/platforms:** 

**First affected release:** 
r322

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r322/main.js, line 1025, col 73
Message: Uncaught TypeError: expected string
Stack: TypeError: expected string at O.l (https://editor.construct.net/r322/main.js:1025:79) at C_a.hPb.tva (https://editor.construct.net/r322/projectResources.js:1957:415) at https://editor.construct.net/r322/projectResources.js:256:404 at https://editor.construct.net/r322/main.js:1871:100
Construct version: r322
URL: https://editor.construct.net/r322/
Date: Wed Dec 14 2022 23:17:08 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 8.2 s

Platform information
Product: Construct 3 r322 (beta)
Browser: Chrome 108.0.5359.99
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2
</details>

**Comment by DiegoScirra** [comment] 2022-12-14 22:38
Duplicate of #6332. Will be fixed in the next beta.

**Closed by DiegoScirra** 2022-12-14 22:38 UTC
Labels: duplicate
