### ISSUE TITLE
Open C3 show nothing, and can't open any project. 

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4730] opened 2021-04-13 09:52 UTC
## Problem description

When I open C3, I don't see anything, white page.
Even I open the Stable version or closed the browser and restart C3,  I also tried to restart the computer, But he was the same.  I don't know why this is happening all of a sudden, until a minute ago, I was using it normally.  

The only error in the console is the sandbox attribute:
```
Error while parsing the 'sandbox' attribute: 'allow-storage-access-by-user-activation' is an invalid sandbox flag.
```

| Console     | Elements   |
| ------------ | ----------- |
| ![Snipaste_2021-04-13_17-36-46](https://user-images.githubusercontent.com/45864744/114532797-c7b15780-9c7f-11eb-8645-bde99f4d54a1.png)  |  ![Snipaste_2021-04-13_17-42-25](https://user-images.githubusercontent.com/45864744/114532808-caac4800-9c7f-11eb-8b15-980e2bc9c039.png)

And I can still drag and drop .c3p in here. But then he broke again.

| Open any .c3p  |   Open any .c3p again |
| ------------ | ----------- |
|  ![Snipaste_2021-04-13_17-38-01](https://user-images.githubusercontent.com/45864744/114533533-8e2d1c00-9c80-11eb-8ebc-752ad5de8e5e.png) | ![Snipaste_2021-04-13_17-38-18](https://user-images.githubusercontent.com/45864744/114533528-8d948580-9c80-11eb-9168-8482fdeee2d1.png)

<details><summary>View details</summary>

```
Error report information
Type: unhandled exception
File: https://editor.construct.net/r243-2/components/editors/layoutView/layoutView.js, line 55, col 251
Message: Uncaught TypeError: Cannot read property 'Og' of null
Stack: TypeError: Cannot read property 'Og' of null at Object.xIa (https://editor.construct.net/r243-2/components/editors/layoutView/layoutView.js:55:251) at Object.mJa (https://editor.construct.net/r243-2/components/editors/layoutView/layoutView.js:99:226) at Object.Gla (https://editor.construct.net/r243-2/components/editors/layoutView/layoutView.js:99:476) at Array. (https://editor.construct.net/r243-2/components/editors/layoutView/layoutView.js:93:126) at Object.Oed (https://editor.construct.net/r243-2/main.js:427:387) at t.dispatchEvent (https://editor.construct.net/r243-2/main.js:423:135) at t.ku (https://editor.construct.net/r243-2/main.js:590:476) at t.Fyb (https://editor.construct.net/r243-2/main.js:591:433) at Object.OO (https://editor.construct.net/r243-2/main.js:630:438) at Object.Rc (https://editor.construct.net/r243-2/main.js:632:243)
Construct 3 version: r243.2
URL: https://editor.construct.net/r243-2/
Date: Tue Apr 13 2021 17:38:14 GMT+0800 (中国标准时间)
Uptime: 9.5 s

Platform information
Browser: Chrome
Browser version: 89.0.4389.114
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
C3 release: r243.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2
```

</details>

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** Chrome 89.0.4389.114  / Windows 10 20H2 19042.906

**First affected release:**

**Comment by XHXIAIEIN** [comment] 2021-04-13 09:59
Solution:  After I Clear site data, he can access it normally

**Comment by AshleyScirra** [comment] 2021-04-13 10:45
It looks like Construct failed to load. Perhaps there was an issue with your Internet connection. I'm afraid as per the bug report guidelines without steps to reproduce it's impossible to investigate the issue, so closing.

**Closed by AshleyScirra** 2021-04-13 10:45 UTC
Labels: can't reproduce

**Comment by XHXIAIEIN** [comment] 2021-04-13 10:51
> It looks like Construct failed to load. Perhaps there was an issue with your Internet connection. I'm afraid as per the bug report guidelines without steps to reproduce it's impossible to investigate the issue, so closing.

I think it may be with the GFW of China :(
