### ISSUE TITLE
Coordinate text isn't fully selected when clicking inside the Animation Editor's text input box

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#581] opened 2017-07-04 09:54 UTC
## Problem description

In the animation editor, when I click in the text input box for the X or Y coordinate of an image point or collision polygon vertex, the cursor jumps to the leftmost position in the text box, but in other text input fields the text is automatically selected when I click inside them.

## Attach a .c3p

Not attaching a project since this can be seen by editing any sprite in any project.

## Steps to reproduce

1. Double click a sprite or create a new sprite to open the animation editor.
2. Click the "Edit the image points" button (or click "Edit the collision polygon" and select a vertex)
3. Click inside either the X or Y text input box

## Observed result

The cursor in the input box jumps to the left, to the start of the text.

## Expected result

The text is selected, the same as with other text input boxes.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r42.3

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 305 mb (2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2017-07-05 10:40
Duplicate of #563

**Closed** 2017-07-05 14:46 UTC
Labels: duplicate

**Comment by Scoremonger** [comment] 2017-07-05 20:01
Ah, sorry, I wasn't sure whether that bug was talking about this issue or not.
