### ISSUE TITLE
NW.js Does not Resize Windows Correctly

### ISSUE THREAD

**Issue by corlenbelspar** [Scirra/Construct-3-bugs#3556] opened 2019-12-19 02:51 UTC
## Problem description

Using the NW.js object to resize a window produces a window size smaller than specified even when you take into consideration the title bar and window edges which I would assume are not supposed to be included in how the action is supposed to resize the window because it would make accurately resizing a window in game options while using letterbox integer scale downright impossible, as I demonstrated by using that very setting and in the x1 option button where it sets the window to the viewport default size, the viewport then shrinks below that where you can't even tell what you're looking at because the resolution of the graphics is destroyed.

## Attach a .c3p

[https://drive.google.com/file/d/1COHmJK1SPDDrUtejyf7D5fjRU5UX4p_Q/view?usp=sharing](https://drive.google.com/file/d/1COHmJK1SPDDrUtejyf7D5fjRU5UX4p_Q/view?usp=sharing)

## Steps to reproduce

1. Just press the x1 and x2 buttons I provided and you should be able to take it from here.

## Observed result

The window is smaller than I specified. The NW.js object also mistakenly believes the window is the size it was told to change it to as I made shown with the text object giving the dimensions of the window according to the NWjs object. This happened across multiple computers with multiple people reporting this bug to me in my actual game, so I know this isn't my fault or me to blame. This especially holds true when you consider I added an extra 10px to the window sizes the game produces in the game options and it worked fine until suddenly now and I didn't change anything in how I've been doing the window resizing.

## Expected result

The viewport, not the window itself, should match the width and height I put in. It shouldn't even be smaller in entire window size as it is by what I put in.

## More details

**Affected browsers/platforms:** NWjs

**First affected release:** It sort of worked before r180, but now it's even worse putting out even smaller window sizes than specified.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.43.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.43.1 (like Chrome/79.0.3945.79)
C3 release: r180 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 77 gb
Storage usage (approx): 169 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2019-12-19 11:36
I'm guessing this might be related to NW2 changes again. Assigning to @AshleyScirra

**Comment by AshleyScirra** [comment] 2019-12-19 12:24
Yeah, looks like another regression with the new NW2 mode enabled in NW.js 0.43. Filed it with them here: https://github.com/nwjs/nw.js/issues/7284
Closing this issue as will follow-up there.

**Comment by AshleyScirra** [comment] 2020-01-02 14:05
Reopening since this seems to be a known change in NW2 which we need to make a change for.

**Comment by AshleyScirra** [comment] 2020-01-06 11:07
The change exposed more bugs so now blocked on another NW.js issue (https://github.com/nwjs/nw.js/issues/7303).

**Comment by AshleyScirra** [comment] 2020-01-06 13:41
NW.js added some new methods to ensure it works as before. Updated our code and will verify when the next NW.js release is out.

**Comment by AshleyScirra** [comment] 2020-01-07 12:06
Verified with NW.js nightly build, looks all OK now.

**Closed by AshleyScirra** 2020-01-07 12:06 UTC
