### ISSUE TITLE
Typo: Preview button text says "undo stack"

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#511] opened 2017-06-15 06:05 UTC
## Problem description

In Construct 3 editor, when hovering over the arrow next to the "Preview" button the text from the "Undo stack" is shown. 

## Attach an image

http://i.imgur.com/nsgfo9p.png

## Expected result

This is obviously a typo and should say something like "view preview stack" instead.

**Comment by AshleyScirra** [comment] 2017-06-15 08:58
Duplicate of #494, already fixed for r38!

**Closed by AshleyScirra** 2017-06-15 08:58 UTC

**Comment by alastajj** [comment] 2017-06-15 09:32
Thanks! And apologies, I couldn't see that issue in my search (due to their limited details).
