### ISSUE TITLE
C3 Runtime: Text web font loading inconsistently on Preview

### ISSUE THREAD

**Issue by wrongtarget** [Scirra/Construct-3-bugs#1498] opened 2018-04-19 20:29 UTC
## Problem description

On a Mac Desktop using the latest Chrome or Firefox version and Construct 3 Experimental Runtime, text objects in a layout using a web font appear to be using a different default font or appear invisible  at first when running the game Preview
Maximizing the preview window (or exiting full-screen mode if the window was already maximized) 
## Attach a .c3p

[webfontissueruntimec3.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1929608/webfontissueruntimec3.c3p.zip)

## Steps to reproduce

1. Create a C3 Project with C3 Runtime
2. Add a text to the layout with a custom imported webfont
3. Run the game on Preview
3. Observe the issue

## Observed result

Text shows up using a different font or appear innvisible

## Expected result

Text should up with the correct webfont.

## Affected browsers

* Chrome: yes
* Firefox: yes

**Comment by AshleyScirra** [comment] 2018-04-20 15:56
Thanks, should be fixed in the next release. It should already work with WOFF files, I think the problem is only because you're using a TTF file instead, but that case should work too in the next release.

**Closed by AshleyScirra** 2018-04-20 15:56 UTC
Labels: c3runtime
