### ISSUE TITLE
Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project

### ISSUE THREAD

**Issue by ChizWiz1** [Scirra/Construct-3-bugs#2529] opened 2019-01-21 16:50 UTC
## Problem description
Construct 3 editor crashed, so I saved my open project. When I refresh the editor and try to open the file it said: "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project"

## Attach a .c3p
http://www.mediafire.com/file/9fl56m079s3x9k5/NewNew_TV-Boy.zip/file

## Steps to reproduce
Creating a new object called "Sign" but then it said that the name is already taken even though it wasn't, when I make an object with a different name; it works. 
PFP: 
![bug](https://user-images.githubusercontent.com/44763364/51487991-3df0d900-1d59-11e9-98b5-388ed9c6ee74.PNG)
![bug2](https://user-images.githubusercontent.com/44763364/51487998-421cf680-1d59-11e9-8a6e-0b0cb5490502.PNG)

## Observed result

- Crashes when I try over and over to create a "sign" sprite.

- The saved .c3p file does not open, says "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project"

## Expected result
- Make a "sign" sprite

- For the .c3p file to open on the editor.

## First affected release
- I was on r131 when it first happened, so I updated to 134, then r135 but they both did not work.

## Affected browsers/platforms

* Chrome: yes
* Firefox: yes/no
* Edge: yes
* Safari: yes/no
* App version: yes

## System details
Unfortunately I didn't copy the crash report.

Thank you in advance!

**Comment by ChizWiz1** [comment] 2019-01-21 16:53
It could be possible that my file is just corrupt, so I'd be happy if it got recovered for me!

**Comment by AshleyScirra** [comment] 2019-01-21 17:01
Please only describe one issue per report. We cannot track multiple issues mentioned in a single issue separately. The issue with naming a sprite "sign" is unrelated and is because it is the name of a system expression, so cannot be used for an object name.

I recovered your project: [recovered.zip](https://github.com/Scirra/Construct-3-bugs/files/2779831/recovered.zip)
It referred to an object named "oof" that did not exist. I deleted an instance relating to that object type. Note that projects saved from a crash dialog may not be openable; the editor has already crashed so there is no guarantee the project will be valid. As with any digital work, you should keep regular, independent backups.

Unfortunately without steps to reproduce the original issue there is nothing more we can do, so closing.

**Closed by AshleyScirra** 2019-01-21 17:01 UTC
Labels: no repro

**Comment by ChizWiz1** [comment] 2019-01-21 17:10
> Please only describe one issue per report. We cannot track multiple issues mentioned in a single issue separately. The issue with naming a sprite "sign" is unrelated and is because it is the name of a system expression, so cannot be used for an object name.
> 
> I recovered your project: [recovered.zip](https://github.com/Scirra/Construct-3-bugs/files/2779831/recovered.zip)
> It referred to an object named "oof" that did not exist. I deleted an instance relating to that object type. Note that projects saved from a crash dialog may not be openable; the editor has already crashed so there is no guarantee the project will be valid. As with any digital work, you should keep regular, independent backups.
> 
> Unfortunately without steps to reproduce the original issue there is nothing more we can do, so closing.

Sorry, it was my first time using github so I didn't know what to do exactly. Thank you!

**Comment by luckyrawatlucky** [comment] 2019-05-21 13:41
I am getting same error
encountered a crash of the editor and saved the project then it said **"Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project"**
My Project and plugins i used in the project i sent to support@construct.net

**Comment by shortercode** [comment] 2019-05-21 14:07
@luckyrawatlucky if you reply to closed issues ( particularly old ones ), we are unlikely to see your message.

If you experienced an editor crash then please complete a issue report with a replication of the crash. The development team does not have access to support ( with the exception of ashley who deals with some escalated issues ). So referencing a project you shared with support is unhelpful.

**Comment by luckyrawatlucky** [comment] 2019-05-21 14:10
@shortercode I received message from support team they said i can create new bug report or can do comment on existing same issue. that's why i did comment here.

**Comment by shortercode** [comment] 2019-05-21 15:19
This issue is closed, meaning we will take no more action on it.

**Comment by luckyrawatlucky** [comment] 2019-05-21 16:06
okay i did create a new report
