### ISSUE TITLE
Crash when renamig animations

### ISSUE THREAD

**Issue by isaacMuniz** [Scirra/Construct-3-bugs#2626] opened 2019-02-18 10:01 UTC
## Problem description

Crash after renaming animations.

## Attach a .c3p

https://drive.google.com/file/d/1vKMJ_-UquLLdON2IeOl6_JERvGP5TGep/view?usp=sharing

## Steps to reproduce

Open the only sprite in the project and rename it's animation.

## Observed result

Crash.

## Expected result

Should not crash.

## More details

**Affected browsers/platforms:** Only tested in Chrome.

**First affected release:** r137beta.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r137/main.js, line 2, col 222078
Message: Uncaught TypeError: this.ǃsVA is not iterable (cannot read property Symbol(Symbol.iterator))
Stack: TypeError: this.ǃsVA is not iterable (cannot read property Symbol(Symbol.iterator)) at ǃu.ǃjo.ǃsVv (https://editor.construct.net/r137/main.js:2:222078) at ǃu.ǃjo.ǃsVN (https://editor.construct.net/r137/main.js:2:222236) at ǃsV$ (https://editor.construct.net/r137/main.js:2:221726)
Construct 3 version: r137
URL: https://editor.construct.net/r137/index.html
Date: Mon Feb 18 2019 07:01:39 GMT-0300 (Brasilia Standard Time)
Uptime: 291.1 s

Platform information
Browser: Chrome
Browser version: 72.0.3626.109
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
C3 release: r137 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon (TM) R7 360 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2019-02-18 10:17
Duplicate of #2616

**Closed by AshleyScirra** 2019-02-18 10:17 UTC
