### ISSUE TITLE
Browser zooming on layout view bug

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#1479] opened 2018-04-11 12:31 UTC
## Problem description

If you mouse scroll with shift, then proceed to pressing the CTRL key to zoom, you will activate Chrome's shortcut key to zoom the layout. This can be really frustrating when you are trying to drag an object with SHIFT and proceed to CTRL+mouse scroll to zoom. Or, you are just trying to zoom in and out quickly with SHIFT+CTRL+mouse scroll.

## Steps to reproduce

1. In the layout view, hold shift and mouse scroll.
2. Then proceed to hold CTRL key while the still holding down the shift+ mouse scrolling.

## Observed result

The browser's view is zoomed.

## Expected result

It should never zoom.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 7.2 gb
Storage usage (approx): 302 mb (4.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 765M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2018-04-11 13:10
Duplicate of #1396, resolved by Chrome issue https://bugs.chromium.org/p/chromium/issues/detail?id=823247

**Closed by AshleyScirra** 2018-04-11 13:10 UTC
Labels: duplicate
