### ISSUE TITLE
C3 Theme Bugs

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#3026] opened 2019-06-10 18:13 UTC
## Problem description

Dark theme bugs (Three)

## Steps to reproduce
1.) Use %80 zoom on Chrome Browser
Use one time "Decrease scale" on Desktop version

2.) I see blur only on Desktop version.
![Blur](https://i.imgur.com/G6xV0lq.png)

3.) Please watch video
NOTE: Last bug sometimes doesn't appear.

Video: https://streamable.com/wx13m

**Affected browsers/platforms:** 
Construct 3 r153 (beta)
Desktop: Chrome 74 (NW.js 0.38.0)
Browser: Chrome 75
 
**First affected release:** idk

**Comment by shortercode** [comment] 2019-06-11 10:02
1. appears to be a plain CSS issue. 
2. is probably due to the dialog spawning at a non integer position. 
3. compositor issue... not much we can do there. 

I presume the video is recorded in the desktop version, have you seen issue 3 in Chrome?

**Comment by AshleyScirra** [comment] 2019-06-11 12:30
The blurry bar is probably some pixel snapping issue. I can't reproduce it in the Chrome browser though. Given the limited repro, the fact it easily and quickly goes away, and that it appears to only happen in a very specific set of circumstances, I don't think it warrants attention.

The rendering glitch when dragging the dialog is not normally possible to achieve in HTML so looks a lot like a GPU driver issue. There's not much we can do about that, try updating your drivers.

I've fixed the horizontal scroll issue in some menus for the next release.

There's nothing further to action on this so closing.

**Closed by AshleyScirra** 2019-06-11 12:30 UTC
Labels: theme

**Comment by QuasarX** [comment] 2019-06-11 14:10
@shortcode
Only Desktop version
