### ISSUE TITLE
Pathfinding issues after HTML5 export: When diagonals are disabled, the pathfinding doesn't work

### ISSUE THREAD

**Issue by Galejade** [Scirra/Construct-3-bugs#956] opened 2017-10-20 17:57 UTC
## Problem description

The pathfinding features are working well within the engine's preview, but doesn't work anymore after exporting and uploading the HTML5, or even locally (using MAMP), especially when Diagonals are disabled.

## Attach a .c3p

https://www.dropbox.com/s/89l0ca4muknjrlh/Test%20pathfinding.c3p?dl=0
The corresponding build in action: https://galejade.itch.io/test-pathfinding-c3?secret=FHwdyPdbryBzzjTGAmhbn9qOszk

## Steps to reproduce

1. Create a new project
2. Create a sprite (named Sprite2) with a Pathfinding behavior
3. Untick 'Diagonals' in the behavior parameters
4. Create another sprite (named Sprite) & place it anywhere on the game screen
5. Add a Mouse component
6. Add a new event: When the left button is clicked, Sprite2 finds path to Sprite.X and Sprite.Y 
7. Add another event: When Sprite2 finds a path, Sprite2 moves along the path
8. Export the project to HTML5
9. Upload the game on itch.io

## Observed result

Sprite A doesn't move when the left button is clicked.

## Expected result

Sprite A should move toward Sprite B when the left button of the mouse is clicked. 

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: Non tested
* Safari: Non tested

## System details

No crash report dialog

**Comment by AshleyScirra** [comment] 2017-10-23 14:53
The provided project doesn't work simply because the layout has no event sheet attached, so none of the events run. Setting the event sheet property of the layout makes it work, and I confirmed it works after a HTML5 export too.

**Comment by AshleyScirra** [comment] 2017-10-23 14:53
Wait, I just noticed it emits a script tag with the wrong path in the HTML. Maybe that's related...

**Comment by AshleyScirra** [comment] 2017-10-23 14:59
OK, it was confusing because the .c3p was broken, but it turns out even after fixing it the emitted script tag URL was wrong. This should be fixed for r65.

**Closed by AshleyScirra** 2017-10-23 14:59 UTC
