### ISSUE TITLE
In-app not working on iOS with MobileIAP plugin

### ISSUE THREAD

**Issue by RobinBloood** [Scirra/Construct-3-bugs#3961] opened 2020-06-20 10:55 UTC
Poor working MobileIAP plugin if you yse it export for iOS Xcode project

c3p:
https://drive.google.com/file/d/11wtFRC2gaL4Sism_Ls__y4SMoFpsQq-e/view?usp=sharing

If I try to export like Xcode project from construct 3 **r171.3 or below** MobileIAP work fine.
If I try to export like Xcode project from construct 3 **r182 or upper** MobileIAP:
After registration product you can get the product price 
"-> text: Set text to MobileIAP.ProductPrice("Product ID")"

but

"+ MobileIAP: On store registration success" - not working
"+ MobileIAP: On store registration failed" - not working
"+ MobileIAP: Is registration complete" - not working
"-> MobileIAP: Purchase product "Product ID"" - not working

I use MacOS Catalina 10.15.4 with Xcode 11.5

**Comment by RobinBloood** [comment] 2020-06-22 17:57
No one assigned? Total ignore for this huge issue?

**Comment by Mr-Josh-web** [comment] 2020-06-22 19:43
Hi RobinBloood,

I don't belong to the Construct 3 team, but are you saying that Mobile IAP and Construct 3 runtime was working fine on versions r173 or below?

This information could be very helpful for the Construct 3 team as they will be able to see which commits they have done to Construct 3 and try to identify the issue.

Thanks.

**Comment by AshleyScirra** [comment] 2020-06-23 11:04
Please be patient. We are a small team and we deal with thousands of issues. I'd also point out you originally posted this on a Saturday, when we don't normally work. Please see the [Forum & Community guidelines](https://www.construct.net/en/forum/general/open-topic-33/forum-community-guidelines-141035), which include a warning against *Nagging staff constantly, especially over weekends and holidays. We’re only human, and we need time off too.*

Please note the more details you omit from the guidelines, the harder it is to deal with the issue and the longer it will take. Your original report has omitted a number of details, so the issue will be accordingly more difficult and take longer to deal with. Further, r171.3 to r182 is quite a wide range of old releases. It would be extremely helpful if you could narrow this down to a specific release where it changed.

**Comment by RobinBloood** [comment] 2020-06-23 11:46
r171.3 to r182 is wide range? Between r171.3 and r182 you don't have stable releases. https://www.construct.net/en/make-games/releases/stable
So, as I mentioned, r171.3, r171.2, r171, r164.3 and etc. below everything work greate. Start from r182 and upper, its not working. Try my .c3p and export it with r171.3 to xcode and test on testflight and everything will be work fine. But on upper versions (include r204) its not working. Some features are working, you can register the products, after that you can get the product price, BUT you cant buy the product, you cant check if store registration was success or fail and etc.

> Please be patient. We are a small team and we deal with thousands of issues. I'd also point out you originally posted this on a Saturday, when we don't normally work. Please see the [Forum & Community guidelines](https://www.construct.net/en/forum/general/open-topic-33/forum-community-guidelines-141035), which include a warning against _Nagging staff constantly, especially over weekends and holidays. We’re only human, and we need time off too._
> 
> Please note the more details you omit from the guidelines, the harder it is to deal with the issue and the longer it will take. Your original report has omitted a number of details, so the issue will be accordingly more difficult and take longer to deal with. Further, r171.3 to r182 is quite a wide range of old releases. It would be extremely helpful if you could narrow this down to a specific release where it changed.

**Comment by AshleyScirra** [comment] 2020-06-23 11:48
See all releases including beta releases here: https://www.construct.net/en/make-games/releases

**Comment by RobinBloood** [comment] 2020-06-23 11:55
ok, I'll test when it started

**Comment by RobinBloood** [comment] 2020-06-23 16:18
> See all releases including beta releases here: https://www.construct.net/en/make-games/releases

Now I can't run with previous releases, it leads to the errors. In r204-2 I can upload without errors and launch in testflight, but in-app still doesn't work.
![1](https://user-images.githubusercontent.com/49883392/85428177-81222d80-b585-11ea-9f10-4fb829f35636.jpg)

**Comment by RobinBloood** [comment] 2020-06-23 16:21
I forgot to say I use Construct 2 runtime

**Comment by AshleyScirra** [comment] 2020-06-23 16:23
Please only use the Construct 3 runtime, we'll be retiring the Construct 2 runtime in future and so our focus is to support the Construct 3 runtime.

**Comment by RobinBloood** [comment] 2020-06-23 16:30
And what should I do? I have an old project and it use webstorage. Your information message on start constract 3 said that you will support c2 runtime till summer 2021. And I have 1 year to migrate.

**Comment by AshleyScirra** [comment] 2020-06-23 16:34
Make a new minimal project, as the bug report guidelines advise.

**Comment by RobinBloood** [comment] 2020-06-23 16:36
minimal project in here: 
c3p:
https://drive.google.com/file/d/11wtFRC2gaL4Sism_Ls__y4SMoFpsQq-e/view?usp=sharing

**Comment by Mr-Josh-web** [comment] 2020-06-24 15:09
Hi RobinBlood,

Sorry to come to this thread. 

I am facing the same issue and I do not have to solve it. Please if you find a solution to it, please let me know as I am also using Construct 3 runtime and Mobile IAP and having the same issue on iOS.

Many thanks.

Regards

**Comment by AshleyScirra** [comment] 2020-06-24 15:13
I must add it's not yet conclusive from this issue that it is the same as the other issue. It's important to avoid jumping to conclusions, or we may end up only fixing one issue when really there are two.

**Comment by RobinBloood** [comment] 2020-06-24 15:18
> Please only use the Construct 3 runtime, we'll be retiring the Construct 2 runtime in future and so our focus is to support the Construct 3 runtime.

I've tried to export with C3 runtime r204-2 and I've gotten the same result. I cant buy the product, cant check if store registration was success or fail and etc.

**Comment by AshleyScirra** [comment] 2020-06-24 16:27
It would still be useful to identify the specific release number where it changed, if that's applicable with the C3 runtime.

**Comment by RobinBloood** [comment] 2020-06-24 18:04
> It would still be useful to identify the specific release number where it changed, if that's applicable with the C3 runtime.

as I said, old releases start compile with errors

**Comment by RobinBloood** [comment] 2020-06-24 18:48
> I must add it's not yet conclusive from this issue that it is the same as the other issue. It's important to avoid jumping to conclusions, or we may end up only fixing one issue when really there are two. In particular this issue does not appear to refer to anything only going wrong when publishing to the app store, it sounds like it's an issue occuring in all circumstances, including development and testflight.

I remember I had strange behavior on TestFlight on some devices it worked sometime and not worked on other. In App Store it not worked at all. I thought that I make something wrong and start testing and it stop working in testflight on all devices. Now I found how to reproduce this bug:
1- make build r171.3 or lower, launch in testflight, everything should work
2- make build r182 or higher, launch in testflight, in-app shouldn't work 
3- delete app from device
4- install app builded with r182 or higher, and everything should work on test flight, but not working if you download from appstore

I had old versions on some devices thats why In-app dont work for me even in testflight
 
So, in any case, in the latest releases in-app don't work in the appstore

**Comment by RobinBloood** [comment] 2020-06-25 09:49
> > as I said, old releases start compile with errors
> 
> Even when you're exporting from C3 with the C3 runtime?

yes

**Comment by RobinBloood** [comment] 2020-06-25 10:02
starts when 204-2 appears.
before that old versions were compiled without errors

**Comment by AshleyScirra** [comment] 2020-06-25 10:32
It's not clear what you mean. What starts in r204-2? If the old versions compile without errors then please identify which release first caused the problem.

**Comment by RobinBloood** [comment] 2020-06-25 10:52
I started test old versions June 20, and xcode were finishing compilation without errors, but in-app didn't work. Than you made r204-2 at monday and after that old versions starts compile with errors in xcode. Maybe you change something in export-server and now export project lost some files, I dont know. So now Its imposible to test old versions.

**Comment by RobinBloood** [comment] 2020-06-25 10:58
For this days, did you even try to export and compile in xcode? It looks like you don't...

**Comment by AshleyScirra** [comment] 2020-06-25 11:13
I just tried an Xcode export in r197.2 and it works fine.

**Comment by RobinBloood** [comment] 2020-06-25 11:34
why did you export r197.2? Did you read my message?
how to reproduce this bug:
1- make build r171.3 or lower, launch in testflight, everything should work
2- make build r182 or higher, launch in testflight, in-app shouldn't work
3- delete app from device
4- install app builded with r182 or higher, and everything should work on test flight, but not working if you download from appstore

**Comment by RobinBloood** [comment] 2020-06-25 13:26
It looks like you have a product with huge bug about 6 month. 6 month Construct 3 without monetisation on iOS. But you just close issues as "external" or "no repro" without any investigation.
https://github.com/Scirra/Construct-3-bugs/issues/3973
https://github.com/Scirra/Construct-3-bugs/issues/3922
https://github.com/Scirra/Construct-3-bugs/issues/3608
https://github.com/Scirra/Construct-3-bugs/issues/3523
https://www.construct.net/en/forum/construct-3/how-do-i-8/complete-product-registration-151028

**Comment by AshleyScirra** [comment] 2020-06-25 14:05
This is getting confusing and it risks making it even harder to deal with an already difficult problem. It's important to communicate clearly and unambiguously.

I am asking about identifying the specific Construct release where this changed. You appear to have said that old versions of Construct do not export working Xcode projects. So I tried a test export using an old version of Construct (r197.2), and it worked. Therefore it should be possible to test old versions of Construct. Therefore it should be possible for you to identify the specific release of Construct where this changed. As I said, this is important information that will help us identify any problems more quickly - without it this will take longer and be more difficult to deal with.

It's also still not clear to what extent those issues are relevant (some did not follow the bug report guidelines, for instance). As I said before it is usually unhelpful to jump to conclusions. Each issue needs to be investigated and diagnosed separately, unless it's clear the issue has exactly the same circumstances (which is far from clear, especially when incomplete information is provided).

Finally it's still not clear that this is an issue with Construct. It may be an issue with Apple's service, a third-party library we use, or something else. In particular if it works in some cases but not others, it usually points to the fact our code is correct (because it works in some cases), but the difference between circumstances causes the problem (e.g. perhaps a difference between TestFlight and the App Store, which are both Apple's services, and we can't fix their services for them). I'd also point out that in the last 3 months, our stats show the IAP object being used in ~100 new projects; presumably there are at least a similar number of existing projects using IAP. A small number of reports over time does not necessarily mean it's not working at all, I would have assumed for most of those projects it's working.

I'm trying to help here regardless of all this. I'd appreciate your continuing co-operation to help us work out what's going on here.

**Comment by RobinBloood** [comment] 2020-06-25 14:29
I'm still asking why did you export r197.2? Did you read my messages?
I told that bug between r171.3 (work) and r182 (don't work). And now this versions isnt compile. But you still telling me about r197.2.
Again, how to reproduce this bug:
1- make build r171.3 or lower, launch in testflight (everything should work)
2- don't delete app from device
3- make build r182 or higher, launch in testflight (in-app shouldn't work)
4- delete app from device
5- install app builded with r182 or higher, and everything should work on test flight, but not working if you download from appstore

I'm waiting you to reproduse this bug.

**Comment by AshleyScirra** [comment] 2020-06-25 14:42
We're a small team with limited resources, and investigating issues like this is particularly time consuming, so I'm asking for information to help try to collect useful information before I start a full investigation, which should help speed things up.

The question I am asking is, which specific beta release between r171.3 and r182 did the problem first start happening in?

**Comment by RobinBloood** [comment] 2020-06-25 14:58
I don't know. Now this versions isnt compile and I cant do anything.

**Comment by AshleyScirra** [comment] 2020-06-25 16:25
I found a compatibility problem with a recent build server update - I've fixed it so old releases should be able to export working Xcode projects again.

I tried configuring App Store Connect to match your project (with an item id "en4"), exported it in the latest release, and ran it from Xcode with an attached device. It seemed to work just fine. So it looks like so far I can't reproduce any issue here.

**Comment by RobinBloood** [comment] 2020-06-25 16:28
> I found a compatibility problem with a recent build server update - I've fixed it so old releases should be able to export working Xcode projects again.
> 
> I tried configuring App Store Connect to match your project (with an item id "en4"), exported it in the latest release, and ran it from Xcode with an attached device. It seemed to work just fine. So it looks like so far I can't reproduce any issue here.

Did you try this?
1- make build r171.3 or lower, launch in testflight (everything should work)
2- don't delete app from device
3- make build r182 or higher, launch in testflight (in-app shouldn't work)
4- delete app from device
5- install app builded with r182 or higher, and everything should work on test flight, but not working if you download from appstore

**Comment by AshleyScirra** [comment] 2020-06-25 16:28
OK, if you run it a 2nd time it doesn't trigger 'On store registration success', which is the same as issue #3608 and is a problem with cordova-plugin-purchase which we've already reported to the developers. So as far as I can tell this is just the same issue as that - it has a simple workaround though looking at the other issue - everything else works, so just ignore 'On store registration success'.

**Comment by RobinBloood** [comment] 2020-06-25 16:31
can you purchase item?

**Comment by Mr-Josh-web** [comment] 2020-06-25 17:16
Hi,

In my case it does not run even the first time. Are you saying it works the first time? With which version? Since when?

Regards

**Comment by RobinBloood** [comment] 2020-06-26 08:17
Why don't you answer?
Did you try this? Did you try to purchase item?

1- make build r171.3 or lower, launch in testflight (everything should work)
2- don't delete app from device
3- make build r182 or higher, launch in testflight (in-app shouldn't work)
4- delete app from device
5- install app builded with r182 or higher, and everything should work on test flight, but not working if you download from appstore

**Comment by RobinBloood** [comment] 2020-06-26 10:55
And you have to buy something to get the result from upstairs

**Comment by RobinBloood** [comment] 2020-06-26 11:35
> OK, if you run it a 2nd time it doesn't trigger 'On store registration success', which is the same as issue #3608 and is a problem with cordova-plugin-purchase which we've already reported to the developers. So as far as I can tell this is just the same issue as that - it has a simple workaround though looking at the other issue - everything else works, so just ignore 'On store registration success'.

I've checked this bug started from r172.

A new easy edition for bug reproduction:
1- make build r172 or above, launch in testflight
2- complete registration
3- make sure that you are registered, for example you can get product price
4- buy something
5- kill the app process and launch the app again
6- complete registration
7- make sure that you are registered, for example you can get product price
8- try to buy something (you can't do this ha-ha)

**Comment by AshleyScirra** [comment] 2020-06-26 11:39
I'm afraid this issue is proving extremely difficult to make progress on. Usually as we learn about problems we turn up some interesting details that point towards a solution. However in this case so far none of the details seem to add up, only deepening the mystery. Despite all the work and investigation done so far, I'm afraid I still can't make any sense at all of what could possibly be going on. Further testing is really hard for these kinds of issues: commonly we may need to something like 20-30 change-and-test iterations when working on a bug. If I can reproduce and work on an issue on my local development issue, even a tough bug can be solved in about an hour. If we have to publish all the way to the app store, and each review takes ~24hr, then we're looking at around a month before we get anywhere with this issue - and that's not including all the other work we have to do, time off for vacations, any unexpected delays in review, and so on. That's why I'm treating that as a last-resort option, since if we have to do that, we'll be looking at a long-term project to deal with this.

So far my best theory is that both IAP issues filed recently (including #3973) are both related to an issue with cordova-plugin-purchase, a third-party library we use for managing IAP. I've contacted the developer of that library about priority support for the issue I previously filed with them and will be following up on that.

I know this can be frustrating and painful - it is for me too - but I appreciate everyone's patience as we try to work the problem. I've dealt with thousands of bug reports in my career, and this type of issue is amongst the toughest that we have to deal with.

**Comment by RobinBloood** [comment] 2020-06-26 11:48
cordova-plugin-purchase was update between r171.3 and r172? 
You dont have to publish it to the appstore you can get this bug from testflight.

**Comment by RobinBloood** [comment] 2020-06-26 11:48
> I'm afraid this issue is proving extremely difficult to make progress on. Usually as we learn about problems we turn up some interesting details that point towards a solution. However in this case so far none of the details seem to add up, only deepening the mystery. Despite all the work and investigation done so far, I'm afraid I still can't make any sense at all of what could possibly be going on. Further testing is really hard for these kinds of issues: commonly we may need to something like 20-30 change-and-test iterations when working on a bug. If I can reproduce and work on an issue on my local development machine, even a tough bug can be solved in about an hour. If we have to publish all the way to the app store, and each review takes ~24hr, then we're looking at around a month before we get anywhere with this issue - and that's not including all the other work we have to do, time off for vacations, any unexpected delays in review, and so on. That's why I'm treating that as a last-resort option, since if we have to do that, we'll be looking at a long-term project to deal with this.
> 
> So far my best theory is that both IAP issues filed recently (including #3973) are both related to an issue with cordova-plugin-purchase, a third-party library we use for managing IAP. I've contacted the developer of that library about priority support for the issue I previously filed with them and will be following up on that.
> 
> I know this can be frustrating and painful - it is for me too - but I appreciate everyone's patience as we try to work the problem. I've dealt with thousands of bug reports in my career, and this type of issue is amongst the toughest that we have to deal with.

cordova-plugin-purchase was update between r171.3 and r172? 
You dont have to publish it to the appstore you can get this bug from testflight.

**Comment by RobinBloood** [comment] 2020-06-26 12:44
Once again, super easy to reproduce:
0- delete test app from your device if you have it
1- make build r172 or above, launch in testflight
2- complete registration
3- make sure that you are registered, for example you can get product price
4- buy something
5- kill the app process and launch the app again
6- complete registration
7- make sure that you are registered, for example you can get product price
8- try to buy something (you can't do this ha-ha)

I've made all work for you. I've found how to reproduce bug that you have about 6 month. I've found were it starts. You need only check, confirm and fix ;) ha-ha

As for me, I will go test the plugin from Chidori. There is nothing to catch here.

**Comment by AshleyScirra** [comment] 2020-06-26 13:34
cordova-plugin-purchase is not our code and at the moment it appears the problem is there. It's not easy for us to fix problems in other people's code, it's generally something they have to do, which is why we're following up with them.

**Comment by RobinBloood** [comment] 2020-06-26 13:58
r172 changes. Just roll it back
![image](https://user-images.githubusercontent.com/49883392/85865023-f5e7a880-b7cd-11ea-86b7-f6e7eb57cada.png)

**Comment by AshleyScirra** [comment] 2020-06-29 15:15
So we have some promising news: I've been in contact with one of the developers of cordova-plugin-purchase, and they identified what appears to be a problem with their plugin (or the documentation). There is a verification step that seems to be documented as optional, but turns out is actually required on iOS only. (Android never seems to have had this problem.) Adding in the extra step to verify - even though it does not do anything meaningful - appears to fix the issue with IAP failing to initialise, which is the only problem I've ever been able to reproduce myself locally.

I suspect that this is behind the IAP/iOS related issues that have been reported recently, even if all the details don't seem to add up. The fix I mentioned will be included in the next beta release, currently scheduled for tomorrow (Tuesday) - so once that rolls out hopefully those of you affected can try it out and we'll find out what difference that makes.

**Comment by AshleyScirra** [comment] 2020-06-30 14:40
A potential fix is in r206, could you test again and see if that helps?

**Comment by RobinBloood** [comment] 2020-07-01 10:09
> A potential fix is in r206, could you test again and see if that helps?

![error_c2](https://user-images.githubusercontent.com/49883392/86231659-8db51000-bb9b-11ea-8070-6be06f4f7a1d.png)
Error when I'm trying to archive c2 runtime project. For now I'm interesting only in c2 runtime, so I will test only it.

**Comment by AshleyScirra** [comment] 2020-07-01 10:25
The error says something is not supported on versions older than iOS 11. You might need to set the minimum iOS version to 11 or 12.

**Comment by RobinBloood** [comment] 2020-07-01 10:36
Ok, I'll wait next beta release

**Comment by AshleyScirra** [comment] 2020-07-14 14:19
@RobinBloood - I've applied the same fix to the C2 runtime in r207, could you verify it's working with that?

**Comment by AshleyScirra** [comment] 2020-07-20 09:57
There's been no response and we know the fix worked in a related issue, so it seems reasonable to conclude this is solved. Closing.

**Closed by AshleyScirra** 2020-07-20 09:57 UTC
Labels: duplicate, need info
