### ISSUE TITLE
r235 freezes layouts - probably BBCode

### ISSUE THREAD

**Issue by salysaur** [Scirra/Construct-3-bugs#4571] opened 2021-02-15 18:55 UTC
## Problem description
After the r235 revision, there are a lot of bugs in my game, the main issue is that it freezes after ~1 second and some layouts don't even load. If I minimize the game window and restore it, the game runs for another second then freezes again. Everything works fine in r234.

Isolating a layout, I found out that enabling BBCode makes the layout freezes under certain conditions.

EDIT: is there a way to send my full project in private? I removed it from the public google drive link.

## Attach a .c3p
I'm sending 2 projects because one is saved in r235 and the other in r234 - Both freeze in r235.
r235 is a minimal project with what I think is causing the problems.
r234 is the full project where you can see everything happening.

https://drive.google.com/drive/folders/1Jm2QYOM8sEd0e2YcHmdfRSx191DOMJvc?usp=sharing

## Steps to reproduce

File: [r235Bug.c3p] 
1. Open in r235.
2. Play the layout [l_cutScene] - the game will freeze.
3. Disable the BBCode of the text object on the layout OR add some text to the block on the event sheet [e_cutscene].
4. Play the layout again - the game will run

File: [r234Freeze.c3p] 
1. Open in r235.
2. Play the layout [lay_level] - the game will load and freeze.
3. Minimize and restore the window - the game will run for some frames and freeze again.
3. Test the project in r234. - It will run as expected.

## Observed result
The layout freezes if BBCode is enabled in r235.

## Expected result
The layout should start and run.

## More details

For this report, I isolated one of the layouts and started removing everything from it and found out that:

1. There is a [On start of layout] block that set a text object to "".
2. If the BBCoded of the object is enabled, the layout freezes.
3. If I disable the BBCode, the layout runs.
4. If I set the block to show a text like "test" instead of "", the layout also runs.

I don't know if this is the problem in the rest of my game, but every scene is freezing or showing some strange behaviors.

If you want to see the isolated text bug you can open the file [r235Bug.c3p] and play the layout [l_cutscene].
If you want to investigate the game freeze, if you can open the file [r234Freeze.c3p] in r235 and play the layout [lay_level].

**Affected browsers/platforms:** Chrome/Edge/Android/Windows 

**First affected release:** Worked in r234, broke in r235.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2021-02-16 09:57
Looks like a duplicate of #4568, should be fixed in next beta.

**Closed by AshleyScirra** 2021-02-16 09:57 UTC
Labels: duplicate
