### ISSUE TITLE
DravingCanvas does not take into account the rotation angle of the layer where the inserted object is located

### ISSUE THREAD

**Issue by ibiz3091** [Scirra/Construct-3-bugs#4240] opened 2020-09-22 17:24 UTC
DravingCanvas does not take into account the rotation angle of the layer where the inserted object is located

https://drive.google.com/file/d/1lzPk0-TSGK07b3qwNFIIRY9K_PYlczlo/view?usp=sharing

Run the project. 
DravingCanvas draws a sprite that is located on a rotating layer. 
DravingCanvas ignores the rotation angle of the layer and draws the sprite without rotation.

1.Run the project
2.
3.

## Observed result
The inserted sprite does not rotate on the canvas.

## Expected result
The inserted sprite should rotate on the canvas.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## Construct r217

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by ibiz3091** [comment] 2020-10-26 21:18
Today I found a workaround that allows me to implement what I wanted. As it turned out, the problem was easily solved, I apologize for the time spent.

**Comment by AshleyScirra** [comment] 2020-10-28 17:50
This is a variant of issue #4205 - basically layer transforms (scale and angle) are not taken in to account if pasting an object on a different layer. Closing as duplicate of that issue.

**Closed by AshleyScirra** 2020-10-28 17:50 UTC
Labels: duplicate
