### ISSUE TITLE
Recent Projects page not showing recent projects (latest desktop r139)

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#2662] opened 2019-02-26 11:33 UTC
## Problem description

The recent projects tab isn't showing the project file I last used. 
My recent page hasn't updated since Feb 18th.

![image](https://user-images.githubusercontent.com/5744908/53409627-831dc000-3a15-11e9-9f9f-f729cd8347a6.png)

## Attach a .c3p

N/A

## Steps to reproduce

1. Click Cloud open to and select any project
2. Close C3
3. Open C3 and look at recent projects page

## Observed result

Don't see the most recent project

## Expected result

Most recent project should be at the top of the list

## More details

**Affected browsers/platforms:** 

Latest Desktop Construct build.

**First affected release:** 

r139 (maybe r138? whatever was on Feb 18) 

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r139 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 127 gb
Storage usage (approx): 921 mb (0.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2019-02-27 14:30
Think I've found the cause of this, I changed the storage location in r139 from localstorage to localforage. Except the upgrade code always reads from the old version to "upgrade" it if it exists, so it's basically resetting to the old version each time the editor starts.

Should be resolved in the next release.

**Comment by AshleyScirra** [comment] 2019-03-04 13:08
r140 is now out, please check again!

**Comment by alastajj** [comment] 2019-03-04 13:18
@AshleyScirra  it works well now thanks

**Comment by AshleyScirra** [comment] 2019-03-04 13:20
Thanks for confirming.

**Closed by AshleyScirra** 2019-03-04 13:20 UTC
