### ISSUE TITLE
Trouble while exporting a construct 2 project into construct 3 and building with Android Cordova options.

### ISSUE THREAD

**Issue by AmitKarr** [Scirra/Construct-3-bugs#1382] opened 2018-03-14 10:43 UTC
## Problem description

Encountering issues while Building the game from the export manager through Cordova. Please note that this was built on Construct 2 and then imported into Construct 3.

## Attach a .c3p 

*We cannot attach the file as it will mean attaching the entire project file which is quite large!*

## Steps to reproduce

1. Exported the project in Android through Cordova.
2. Downloaded the .Zip file.
3. Inside the Export Manager, when Building the .zip file we get an error.

## Observed result

We get an error message (Please find the image enclosed and the bug report copy pasted below.)

## Expected result

Expectation was that it would show the dialogue box with the cordova options but we get the error instead. 

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Failed to execute 'setAttribute' on 'Element': 2 arguments required, but only 1 present. @ TypeError: Failed to execute 'setAttribute' on 'Element': 2 arguments required, but only 1 present. at ǃr.ǃo.ǃsZ.ǃvis.ǃviy (https://editor.construct.net/r89/main.js:155:19035) at ǃr.ǃo.ǃsZ.ǃvis.ǃviC (https://editor.construct.net/r89/main.js:155:16923) at app.ǃuT.then (https://editor.construct.net/r89/main.js:155:22729)
Stack: TypeError: Failed to execute 'setAttribute' on 'Element': 2 arguments required, but only 1 present. at ǃr.ǃo.ǃsZ.ǃvis.ǃviy (https://editor.construct.net/r89/main.js:155:19035) at ǃr.ǃo.ǃsZ.ǃvis.ǃviC (https://editor.construct.net/r89/main.js:155:16923) at app.ǃuT.then (https://editor.construct.net/r89/main.js:155:22729)
Construct 3 version: r89
URL: https://editor.construct.net/r89/index.html
Date: Wed Mar 14 2018 13:37:43 GMT+0530 (India Standard Time)
Uptime: 92.6 s

Platform information
Browser: Chrome
Browser version: 65.0.3325.162
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36
C3 release: r89 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>
![asd](https://user-images.githubusercontent.com/34541244/37397637-1cba6664-27a2-11e8-925a-7d89ffb0ecd1.JPG)

**Comment by shortercode** [comment] 2018-03-14 11:29
Duplicate of #1372, which is already fixed. Going to keep this open until the patch has gone out.

**Comment by AshleyScirra** [comment] 2018-03-16 14:46
Should be fixed in r91 now.

**Closed by AshleyScirra** 2018-03-16 14:46 UTC
Labels: duplicate
