### ISSUE TITLE
NW.JS Blank Screen when importing C2 project into C3

### ISSUE THREAD

**Issue by dolomite** [Scirra/Construct-3-bugs#783] opened 2017-09-05 17:43 UTC
## Problem description

A C2 project (no plugins used) imported into C3. Runs perfectly fine through preview with no issues. When exported into NW.JS from C3, it gets a blank screen.

## Attach a .c3p

The .c3p project was already sent and received by Construct Support by email.

## Steps to reproduce

1. Import C2 project into C3.
2. Export C3 project using NW.JS (scripts minified). All other options doesn't matter.
3. Run the exported NW.JS project.

## Observed result
Blank window screen. Nothing loads.

## Expected result

Expected the actual game to load.

## Runtime Errors
When debugging in NW.JS, the resulting errors in the console : 

c2runtime.js:2 Uncaught SyntaxError: Illegal break statement
    at c2runtime.js:2
c2runtime.js:2 Uncaught TypeError: g_a.g_jt is not a function
    at g.g_iy (c2runtime.js:2)
    at XMLHttpRequest.g_gb.e.onload (c2runtime.js:2)

***However***, it was noted by Construct Support that when the ***script is NOT minified*** before exporting, the game will actually load as a temporary work around. This has been confirmed to work.

**Comment by AshleyScirra** [comment] 2017-09-05 20:37
Are you using r54? We just fixed a script minify bug. Also are you using the Physics behavior? If so, it's bug #560.

**Comment by dolomite** [comment] 2017-09-05 20:48
Yes using r54, and yes using Physics behaviors.

**Comment by AshleyScirra** [comment] 2017-09-06 08:45
OK, closing as duplicate of #560.

**Closed by AshleyScirra** 2017-09-06 08:45 UTC
Labels: need info
