### ISSUE TITLE
Black screen takes too much time on running a game on mobile

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#4019] opened 2020-07-07 11:35 UTC
## Problem description

When I export my game to mobile ( APK for android),there is approx 10 second delay (black screen) after which loading bar appears for few milliseconds and then game runs. Important point to note is that there is no lag in the game afterwards.

Exact sequence of what's happening:-
Black loading screen for 10 seconds --> progress bar and custom logo for few milliseconds --> game begins

## Attach a .c3p

I am attaching 5 c3p files and their respective APK files. All files have 428 layouts,1000 objects in common.The thing which differentiates them is number of event sheets

TestProject.c3p (80 event sheets)
https://drive.google.com/file/d/1JxHgqJH31_h9gS8sY7eR83rlCGsVnpAN/view?usp=sharing

TestProject(1).c3p (60 event sheets)
https://drive.google.com/file/d/1orUWk63mtd6W7LcBX-yUCkYDfUl4gXMu/view?usp=sharing

TestProject(2).c3p (40 event sheets)
https://drive.google.com/file/d/11_LuDAYY1BYjnwmbJziZO30cE0rfykSd/view?usp=sharing

TestProject(3).c3p (20 event sheets)
https://drive.google.com/file/d/1kwpRc1CM8gmwikmso6fjhSLKOhDRGwoW/view?usp=sharing

TestProject(4).c3p (10 event sheets)
https://drive.google.com/file/d/1eV9X7TMngJj8EwpGP_pTrWeJkJSUu_-U/view?usp=sharing

If interested then you can even download APK for faster debugging:-

TestProject.c3p (80 event sheets)
https://drive.google.com/file/d/1iCrcu2eAznXjhH02Dl0N7-twYu9wIdaf/view?usp=sharing

TestProject(1).c3p (60 event sheets)
https://drive.google.com/file/d/1e9n3vM00nl63S-F_3d0sH8Pi2PD4K7x4/view?usp=sharing

TestProject(2).c3p (40 event sheets)
https://drive.google.com/file/d/1tjWJEuMpvqtaCvnloYUPGiBDNKp-m0uf/view?usp=sharing

TestProject(3).c3p (20 event sheets)
https://drive.google.com/file/d/1GTAm98jkz8LqCLQ18ruEbaRMZRPy-PDt/view?usp=sharing

TestProject(4).c3p (10 event sheets)
https://drive.google.com/file/d/1_FQ59zefeMgUmikAe4DW8GwKJYhhzPcg/view?usp=sharing

You don't have to work on the content of the file. Infact the 'Layout' which opens at the beginning does not have any events connected to it (this also means that NO event is ever executed in the whole project at all.You will just stay at the first layout). The bug revolves around number of event sheets (or maybe on total number of events in the whole project) . I simply just want to demonstrate that more the number of events,more lengthy is the black loading screen at the beginning of the game.(and also the events filled in the event sheet is pure garbage.I just randomly filled a sheet with 50 events and made 80 copies of that event sheet.Same thing with objects too)

## Steps to reproduce

Although if the file is even executed from the browser still black screen loading can be seen for 5-6 seconds in TestProject.c3p (80 event sheets). But the bug is best seen on mobile devices.Just make its APK and run it on the mobile(although I have also provided APK files).(Regarding ios I don't have hardware for it)

## Observed result

Time results of the black screen bug:-
APK of TestProject.c3p (80 event sheet)-->Black screen appears for 10 seconds
APK of TestProject(1).c3p (60 event sheets)-->Black screen appears for 8 seconds 
APK of TestProject(2).c3p (40 event sheets)-->Black screen appears for 6.5 seconds
APK of TestProject(3).c3p (20 event sheets)-->Black screen appears for 3 seconds
APK of TestProject(4).c3p (10 event sheets)-->Black screen appears for 1.73 seconds

## Expected result

The black screen should have not been there at all.Instead the loading time should had been transferred to the loading bar which loads in milliseconds.I mean there is no purpose of loading bar at all if it has to load in milliseconds (mobile platform).Black screen leaves a very bad taste and practically it makes the whole project( game ) worthless

And infact I do not even understand that why presence of many events is causing black screen delay. I believe that loading should occur when a 'particular event sheet' is loaded into the memory. It looks like construct 3 is loading all events at once into the memory.

Or atleast the user should get ability to replace the black screen with any static image 

## More details

One thing for sure that the black screen delay has nothing to do with number of layouts and number of objects.It has something to do with number of event sheets/events. I have earlier uploaded a game to play store which had 350 layouts in it and the game was running smoothly.
And I also noticed one thing very awkward. If I store a very-very big string directly in a global variable,the black screen loading time increases. As an example if a project takes 1 second for black screen loading,same project with a global variable with very-very big string takes 20 seconds for black screen loading,even if that variable is never used.
And even more interesting,if I make that same string load in that same global variable using an event like:- first I will declare a global variable(string format) which will be empty and then using "At the start of the layout-->>set 'that' global variable equal to the very big string",then instead of taking 20 seconds ,it just takes same 1 second for black screen loading.

Platform information
Browser: Chrome
Browser version: 83.0.4103.116
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
C3 release: r204.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 67 gb
Storage usage (approx): 307 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 710 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment] 2020-07-13 15:50
I profiled this and there was some inefficiency in the code that resolves event variables (global/local/function parameter variables). It was straightforward to optimize this so it's done for the next release. The test project is an artifical test case which deliberately adds loads of event variables which causes the problem - I think we will need to check this solves the problem with your real game after the next release. I never thought anyone would use such large numbers of variables!

FYI:

> If I store a very-very big string directly in a global variable,the black screen loading time increases.

You should definitely not do this - it's really inefficient. For large amounts of pre-determined data, add it as a project file, and load it with AJAX at runtime. That will be a lot more efficient.

**Comment by layilpaht** [comment] 2020-07-13 16:28
Exactly, I was using AJAX to load data from text files. It was very neat too
Actually my game is a collection of many mini games ( 222 mini games) . And I will add more
I will notify you when I test the feature but till then don't close the bug.
But how much time will the new release take to come?

**Comment by AshleyScirra** [comment] 2020-07-13 16:29
We have a beta release scheduled for tomorrow, so hopefully not long to wait!

**Comment by AshleyScirra** [comment] 2020-07-14 14:20
r207 is now out, could you check again with that and see if it's improved?

**Comment by layilpaht** [comment] 2020-07-14 15:04
When I try to export ,a message comes "Failed to export"(signed release apk)
![image](https://user-images.githubusercontent.com/46170077/87441907-473ac900-c611-11ea-8e0f-df15eb888e71.png)

**Comment by layilpaht** [comment] 2020-07-14 15:06
My project is quite huge and hence it takes a good amount of time to re-compress image in last stage.And it is quite disappointing to see such messages.

**Comment by layilpaht** [comment] 2020-07-14 15:17
Update:-Mobile export is absolutely not working

**Comment by layilpaht** [comment] 2020-07-14 15:34
In beta version,android export does not work when minify is set to advanced.
And for my project,advanced minification is compulsory

**Comment by layilpaht** [comment] 2020-07-14 16:00
I compiled the APK using no minification. Results were awesome
Earlier :- 20 seconds
Now :- 3 seconds and I hope that advanced minification will even reduce that too
I strongly hope that the modification which solved the issue does not have any side effects on other functionality. You can now close the bug 😍
Should I file another bug report for "minification issue"?

**Comment by AshleyScirra** [comment] 2020-07-14 16:41
Great, thanks for confirming the time is much improved. I'll close this issue now - it looks like there is a separate regression with minification in the latest release, please do file that separately.

**Closed by AshleyScirra** 2020-07-14 16:41 UTC

**Comment by layilpaht** [comment] 2020-07-19 22:01
When will the next beta/stable will be released ?
Actually I want to test the performance with "minification enabled".

**Comment by AshleyScirra** [comment] 2020-07-20 09:48
We normally release betas every week.
