### ISSUE TITLE
Google Play shows "undefined" error message (SOLVED with deleting app data?)

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#3474] opened 2019-11-12 14:15 UTC
## Problem description
UPDATE: Seems its solved after deleting app data and cache from phone settings.

I added Google Play and could successfully submit scores and unlock achievements a few weeks ago. But when I launch my game now I constantly get "On Google Play Error" triggered and the error message is "undefined". I built it again with 171.3 and 175 but its the same.
When I switch layouts or try to show leaderboards or achievements (built in android popup) I get the error message.

## Attach a .c3p
working on it

## Steps to reproduce

1. add Google Play with your game ID
2. try to show built in android leaderboards or achievements

## Observed result
"undefined" error message

## Expected result
more detailed error to know whats wrong and to fix it  would be helpful

## More details

My brother tried it on his phone and it works fine there. But I dont know why.

I uninstalled the app and downloaded it from Google Play again but I always get the "undefined" error.

I added our google accounts to the internal tester list on Google Dev page. Any idea why I get "undefined" and cant use Google Play?

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
171.3 (same in 175 beta)
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 78.0.3904.97
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
C3 release: r171.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 975 mb (6.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 615 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2019-11-12 17:24
I haven't really been able to validate this today unfortunately. Until I can check it properly I'm going to rollback the version on the build server, presuming that your issue was caused by the changes that went into yesterdays revision.

**Comment by shortercode** [comment] 2020-01-24 13:55
I don't think we get any error message when the leaderboard fails to show, hence the "undefined" message, we should probably put some fallback message in like "unknown error" in this situation.

I expect your error was some random device state issue given how you fixed it, and likely not related to the update I pushed out. We need to review the release again and then push it out. I'm not expecting any problems from it though.

**Comment by AshleyScirra** [comment] 2020-01-31 14:30
We don't have a way to reproduce this issue and the original reporter doesn't seem to have an issue any more either, so closing.

**Closed by AshleyScirra** 2020-01-31 14:30 UTC
Labels: no repro
