### ISSUE TITLE
Sometimes, when C3 is opened, the UI bars is chaos

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4089] opened 2020-08-04 06:59 UTC
## Problem description

I don't know how it happened and why, but it must have happened more than once.  Each time this happens, I will reset bars & dialogs in Settings, and it won't happen for a long time. (Haven't been seen in months)
  
![](https://imgur.com/BYZKoYx.png)
  

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2020-08-04 09:12
As with any report, we need reliable steps to reproduce to be able to do anything about this.

**Comment by XHXIAIEIN** [comment] 2020-08-04 20:00
> As with any report, we need reliable steps to reproduce to be able to do anything about this.

But I didn't do anything. As usual, Construct 3 is open in the browser. and  has not cleaned up the site storage.

**Comment by iamcmnut** [comment] 2020-08-07 10:16
> > As with any report, we need reliable steps to reproduce to be able to do anything about this.
> 
> But I didn't do anything. As usual, open Construct 3 in the browser. and has not cleaned up the site storage.

What is web browser did you used?

**Comment by XHXIAIEIN** [comment] 2020-08-07 10:52
> > > As with any report, we need reliable steps to reproduce to be able to do anything about this.
> > 
> > 
> > But I didn't do anything. As usual, open Construct 3 in the browser. and has not cleaned up the site storage.
> 
> What is web browser did you used?

Win10 1909 / Chrome 84.0.417.105

**Comment by dupuqub** [comment] 2020-08-07 11:01
Happens to me to every time I shut down my computer. I opened another issue that got closed, maybe that one is a duplicate of this one, also there's some additional info there #4087 .

**Comment by AshleyScirra** [comment] 2020-08-07 11:57
I'm afraid without steps to reproduce the problem, there is virtually nothing we can do. This is why the guidelines require steps to reproduce the problem. Since there is no action we can take, closing this issue. We'll continue to monitor to see if this comes up, and if you can find a way to reliably reproduce it, please file a new issue following all the guidelines.

**Closed by AshleyScirra** 2020-08-07 11:57 UTC
Labels: no repro
