### ISSUE TITLE
[r24] Pressing X in the event sheet sometimes adds 2 Else blocks

### ISSUE THREAD

**Issue by glerikud** [Scirra/Construct-3-bugs#166] opened 2017-05-08 17:01 UTC
## Problem description

Earlier today when I edited my project and wanted to add an Else block to a sub-event by pressing the X button it added 2 Else blocks repeatedly (I tested multiple times). Sadly I can't reproduce this bug now as I write this report, but since I saw an other report with a similar issue (https://github.com/Scirra/Construct-3-bugs/issues/118) , I think it's worth submitting.

For what it's worth I had these software running while I bumped into this issue:
- Construct 3 (as an app, in the newest Chrome)
- Opera 43
- Gimp
- Paint.NET
- OneNote
- NotePad++
- TotalCommander
- Avast
- Comodo Firewall

## Attach a .c3p

Here's the project file: https://www.dropbox.com/s/79x4pspjdnm3t8c/raktari_rend.c3p?dl=0

## Steps to reproduce

1. Go to the event sheet.
2. Delete an Else sub event, then select the event before it.
3. Press X to add an event.

## Observed result

Two Else event block appeared.

## Expected result

One event block should appear only.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Local storage
Storage quota (approx): 7.7 gb
Storage usage (approx): 125 mb (1.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 6
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2017-05-08 17:21
I think this is very likely a duplicate of #118 since the comments mention it affects all keyboard input. Still no idea what is causing it though.

**Closed by AshleyScirra** 2017-05-08 17:21 UTC
