### ISSUE TITLE
Effects are messed up

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#3257] opened 2019-08-23 19:48 UTC
## Problem description

I don't know why, but I opened C3 today and the the effects were broken.
1. The warp effect is inverting the image vertically.
2. The warp effects is not being applied as mask, but as a giant square.
https://imgur.com/cvEAQT9

## Attach a .c3p

[Effects Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/3535965/Effects.Bug.zip)

## Steps to reproduce

1. Just open the project.

## Observed result

1. The warp effect is inverting the image vertically.
2. The warp effects is not being applied as mask, but as a giant square.

## Expected result

The warp effect to act like it did previously.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by aiaicaptain** [comment] 2019-08-23 21:17
Same with Water Background, with the revert part at least.

**Comment by 7Soul** [comment] 2019-08-24 21:20
The canvas object is also inverting the image vertically

**Comment by AshleyScirra** [comment] 2019-08-27 11:57
This is a regression caused by the fix to #2121. The next release will revert the incorrect fix. Closing and reopening the original issue.

**Closed by AshleyScirra** 2019-08-27 11:57 UTC
