### ISSUE TITLE
API target level requirements

### ISSUE THREAD

**Issue by ERAgames777** [Scirra/Construct-3-bugs#4077] opened 2020-07-28 10:05 UTC
When I go through the c3buildservices apk file and add an application or update an application in google play, I get this warning:
**API target level requirements from August 2020
Warning

The target API level for your application is 28. To provide the required performance and security, the target API level must be at least 29.

From August 2020, the target version of new apps must be at least Android 10 (API level 29).
From November 2020, the target version of updated apps must be at least Android 10 (API level 29).

Advice

Change the target API level for your application.**
link: https://developer.android.com/distribute/best-practices/develop/target-sdk.html

**Comment by AshleyScirra** [comment] 2020-07-28 11:01
Duplicate of #4075

**Closed by AshleyScirra** 2020-07-28 11:01 UTC
Labels: duplicate
