### ISSUE TITLE
NW.JS 0.33.3 not working for Mac & Windows after export for any project

### ISSUE THREAD

**Issue by Nabbo-extreme** [Scirra/Construct-3-bugs#3811] opened 2020-04-28 07:01 UTC
## Problem description

NW JS 0.33.3 not working for Mac & Windows after export as I want to publish on stream with Greenworks, I tried R197 & R189.2 both showing same issue

## Attach a .c3p
[Car lanes.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/4543865/Car.lanes.c3p.zip)

Other export files are on below link:
https://drive.google.com/open?id=1bqJVrFhi9AJ6jQGq0lzMF16oV_3CoBoW

<img width="614" alt="Screen Shot 2020-04-28 at 10 26 44 AM" src="https://user-images.githubusercontent.com/41523520/80457237-06031900-8940-11ea-9306-08999c82e3b9.png">
<img width="788" alt="Screen Shot 2020-04-28 at 11 09 02 AM" src="https://user-images.githubusercontent.com/41523520/80457642-b113d280-8940-11ea-8f8d-78678cf03201.png">

<img width="531" alt="Screen Shot 2020-04-28 at 10 34 10 AM" src="https://user-images.githubusercontent.com/41523520/80457265-11eedb00-8940-11ea-828b-77ab071407c8.png">
<img width="530" alt="Screen Shot 2020-04-28 at 10 36 51 AM" src="https://user-images.githubusercontent.com/41523520/80457273-14e9cb80-8940-11ea-9475-f906ca0deae4.png">

## Steps to reproduce

I used GS template car lanes and attached both output:

1. Click export to NW.JS
2. Select all export option (shown on attached) . Also tried with no option same result on 0.33.3 but on 0.45.0 its working.
3. Select 0.33.3 and download 

## Observed result

NW.JS is not opening with 0.33.3. I tried to clear chrome cache and re download all export nw.js version same results even on firefox. But 0.33.3 NW.JS was working before 12 April.

## Expected result

It should open normally but its not working on both Mac and windows

## More details
I need to publish on steam which requires 0.33.3 but its not working, please help me to sort this as I want to publish coming month.

Tried Chrome/Firefox export same results

**Affected browsers/platforms:** 
Chrome/Firefox, Windows/macOS. Didnt test on android or iOS

Happening in both R189.2 and R197

**First affected release:**
It worked before 12 April but since yesterday 0.33.3 not working after export.

I have one more question, since I do not use any Greenworks feature can I publish over steam without this plugin and how?

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 81.0.4044.122
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
C3 release: r197 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 140 gb
Storage usage (approx): 1.6 gb (1.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 6100
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment] 2020-04-28 14:05
It looks like the Chrome version in 0.33.3 is too old to support Construct's new worker mode, which is currently enabled by default. It works if you turn off 'Use worker' in the advanced project properties.

The macOS "damaged" error looks unrelated and is probably due to either transferring files incorrectly or a permission problem as described in this tutorial: https://www.construct.net/en/tutorials/exporting-desktop-apps-nw-js-15

Also note r189.2 came out on March 5th, so if you say it worked before April 12th but broke after then, that suggests it worked in r189.2 and so the problem was not caused by a change in Construct.

The official Greenworks plugin is pretty out of date now, since there haven't been any official releases of the Greeenworks library it uses for some time. I'll add to my todo list to see if that can be updated to a newer version.

**Closed by AshleyScirra** 2020-04-28 14:05 UTC

**Comment by Nabbo-extreme** [comment] 2020-04-28 15:27
Hi Ashley,
I am directly extracting and running it but its not working. Also the work mode is already disabled and still same issue. Please help to solve the issue or update greenworks as I have my app ready for publishing by end of this month..

Regards
Nabil
________________________________

**Comment by AshleyScirra** [comment] 2020-04-28 15:39
See the tutorial I linked to, there's more to it than that.

**Comment by Nabbo-extreme** [comment] 2020-05-17 13:07
Hi Ashley,
I know Mac has some security so I planned not to publish there. But I am facing same issues on Windows. The starting loading screen is getting stuck at 70% 8 times out of 10 on 0.33.3 version, with worker mode disabled with all options disabled like minify scripts. I tried the same on latest version 0.45.0 with nwjs and its not getting stuck at all on both MacOS and Windows. Please help me to just publish on steam via latest nwjs as I spend 2 years on one project and now not able to publish :(.. I am not interested in any other greenworks features just I need to publish on steam.

Regards
Nabil
________________________________

**Comment by Nabbo-extreme** [comment] 2020-05-18 20:56
Hi Ashley,
Can you please update me on this as I am planning to publish on this month end.

Regards
Nabil
________________________________

**Comment by Nabbo-extreme** [comment] 2020-05-19 16:29
Hi Team,
I know Mac has some security so I planned not to publish there. But I am facing same issues on Windows. The starting loading screen is getting stuck at 70% 8 times out of 10 on 0.33.3 version, with worker mode disabled with all options disabled like minify scripts. I tried the same on latest version 0.45.0 with nwjs and its not getting stuck at all on both MacOS and Windows. Please help me to just publish on steam via latest nwjs as I spend 2 years on one project and now not able to publish :(.. I am not interested in any other greenworks features just I need to publish on steam.

Regards
Nabil

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
