### ISSUE TITLE
when I try to draw with the Tilemap, I get an error and it tells me that I can only copy the project data or restart the page and it doesn't let me do anything.

### ISSUE THREAD

**Issue by Lindi03** [Scirra/Construct-3-bugs#4729] opened 2021-04-12 11:14 UTC
## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</sumhttps://guides.github.com/features/mastering-markdown/mary>

PASTE HERE

</details>

**Comment by Lindi03** [comment] 2021-04-12 11:14
Error report information
Type: unhandled exception
File: https://editor.construct.net/r243-2/components/editors/layoutView/layoutView.js, line 19, col 413
Message: Error: unsupported event object
Stack: LOc@https://editor.construct.net/r243-2/components/editors/layoutView/layoutView.js:19:385 prd@https://editor.construct.net/r243-2/components/bars/tilemapBar/tilemapBar.js:85:115
Construct 3 version: r243.2
URL: https://editor.construct.net/r243-2/
Date: Mon Apr 12 2021 13:10:35 GMT+0200 (CEST)
Uptime: 2679.5 s

Platform information
Browser: Safari
Browser version: 14.0.1
Browser engine: WebKit
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_6
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15
C3 release: r243.2 (beta)
Language setting: it-IT

WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Apple Inc.
Renderer: Apple GPU
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions: EXT_blend_minmax, EXT_sRGB, EXT_frag_depth, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_standard_derivatives, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, OES_vertex_array_object, OES_element_index_uint, WEBGL_lose_context, WEBGL_compressed_texture_s3tc, WEBGL_depth_texture, WEBGL_draw_buffers, ANGLE_instanced_arrays, WEBGL_debug_shaders, WEBGL_debug_renderer_info, EXT_color_buffer_half_float, WEBGL_color_buffer_float

**Comment by AshleyScirra** [comment] 2021-04-12 11:51
This looks like a duplicate of #4723, and the guidelines were not followed so it cannot be investigated anyway, so closing.

**Closed by AshleyScirra** 2021-04-12 11:51 UTC
Labels: duplicate
