### ISSUE TITLE
Deprecated Android Studio Export

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-3-bugs#2875] opened 2019-04-19 19:55 UTC
## Problem description

Exports to Android Studio uses deprecated Gradle with a lot of corrections and warnings poping in Android Studio

## Attach a .c3p

Any export to Android Studio

## Steps to reproduce

1. Export to Android Studio
2. Open in Android Studio
3. Follow the warnings

## Observed result
Android Studio doesnt allow to build apk or bundle until gradle is updated, but that breaks the project.

## Expected result

To be able to compile in Android Studio with no warnings and forced updates.

## More details

Last Android Studio is updated to Gradle 5.1 that is not compatible with the Construct3 export, if only one steep is followed in the warnings of Android Studio, the project is broken and need to be re built in construct.
There are turnarounds: avoiding all updates and forcing the gradle plugin to 3.2 and gradle version to 4.10.3, but this should be updated asap to avoid GooglePlay rejection in the future. Beside Gradle 4.10 comes with Bundle Export, that allows to administrate keys easier.
also:
![imagen](https://user-images.githubusercontent.com/6506303/56533019-44941580-652d-11e9-8853-058c148cb008.png)

**Comment by huwpascoe** [comment] 2019-04-21 20:08
👍

**Comment by shortercode** [comment] 2019-04-23 10:43
This is an issue with Cordova using an older version of Gradle, so again this is something that migrating to cordova 9 may resolve. But I'm afraid I can't do much in the mean time.

I may not be using the latest version of Android studio but in the past it would ask if you wanted to upgrade, and you could choose to keep using the older version. If you do upgrade it won't build right away, but the errors can be quite easily resolved if you click the blue highlighted text in the error message "Move minSdkVersion[...]" it will resolve the issue for you.

**Comment by kingpirux** [comment] 2019-04-23 14:13
> 
> 
> This is an issue with Cordova using an older version of Gradle, so again this is something that migrating to cordova 9 may resolve. But I'm afraid I can't do much in the mean time.
> 
> I may not be using the latest version of Android studio but in the past it would ask if you wanted to upgrade, and you could choose to keep using the older version. If you do upgrade it won't build right away, but the errors can be quite easily resolved if you click the blue highlighted text in the error message "Move minSdkVersion[...]" it will resolve the issue for you.

i already tryed that, but that is just one of many problems that goes up each time i export the game. And now AS is very annoying with the update to gradle 5.1

**Comment by AshleyScirra** [comment] 2019-06-11 17:38
@shortercode - now we're on Cordova 9 is this resolved?

**Comment by shortercode** [comment] 2019-06-14 13:27
I've just been reviewing the required changes to cordova and they are still pending, so they won't be resolved after the server update unfortunately. I believe they had planned the changes being in cordova 9 but ended up reverting the change for the release due to an unexpected edge case. Hopefully a 9.1 will be released at some point over the next couple of months that fixes the various gradle issues.

I agree this is quite frustrating, but we're waiting on a 3rd party to resolve it so it can't be fixed faster. At least it possible to work around it at the moment. Depending on how big a change your making per iteration you could just copy the contents of the www folder into your existing android studio project, as so not to invalidate your changes to the project.

**Comment by kingpirux** [comment] 2019-06-14 18:19
yes i found easier to just update the src folder each time i export. So all the changes i made for the android studio to work stay there.

**Comment by kingpirux** [comment] 2019-06-17 20:31
@shortercode  i recive this error with r154 
![imagen](https://user-images.githubusercontent.com/6506303/59634687-bf407200-9125-11e9-9840-a63885bb2d28.png)

**Comment by kingpirux** [comment] 2019-06-17 23:23
![imagen](https://user-images.githubusercontent.com/6506303/59643086-cb382e00-913d-11e9-8702-6b28da677cc4.png)

**Comment by shortercode** [comment] 2019-06-18 11:30
Mmm odd that your only just now experiencing a problem with that, I did just update the plugin but that wasn't a new addition. I expect I'm not having the issue because I have the android support library installed via the Android SDK manager.

Could you try adding the line:
`implementation "com.android.support:support-annotations:+"`

to the file `build.gradle ( Module: app )` before the line `// SUB-PROJECT DEPENDENCIES END` and then performing a gradle sync.

If it resolves your problem I will update the dependencies for the plugin to include the android support library.

**Comment by kingpirux** [comment] 2019-06-18 13:58
yes that solved the problem

**Comment by shortercode** [comment] 2019-06-18 16:29
Thanks for confirming, I've merged in that change.

**Comment by shortercode** [comment] 2019-06-21 13:02
I've had to make some additional changes related to that issue. It was caused by a breaking update to the G. play services library on Monday. More information on #3057

**Comment by kingpirux** [comment] 2019-07-28 20:09
from android studio 3.4.2 a few elements are completly incompatible. i had to downgrade to android 3.4.1 to be able to export to apk

**Comment by kingpirux** [comment] 2019-07-28 20:09
i found the gradle in 3.4.2 is 5.4.1 and the last compatible with the construct export is 5.1.1

**Comment by shortercode** [comment] 2019-07-29 09:54
Are you getting the leftShift error? There was a syntax change in gradle at some point, which prevents the script from working. The block that uses it is just logging I believe, so I have been commenting it out to get the script to work.

**Comment by kingpirux** [comment] 2019-07-29 14:02
leftshift error? no that i noticed. i dont use keyboard anyway. The error i get was incompatible dependencies, i will install the new one again and copy the error log

**Comment by kingpirux** [comment] 2019-07-29 14:17
![imagen](https://user-images.githubusercontent.com/6506303/62055600-5226fe80-b1f2-11e9-8715-454d0e03673c.png)
![imagen](https://user-images.githubusercontent.com/6506303/62055626-60751a80-b1f2-11e9-946c-11012b3ddd32.png)

**Comment by kingpirux** [comment] 2019-07-29 14:20
i have been able to export with the last version at the end. but all this warnings are new.
![imagen](https://user-images.githubusercontent.com/6506303/62055854-c661a200-b1f2-11e9-9607-004817f404a3.png)

**Comment by shortercode** [comment] 2019-07-29 16:38
That appears to just be a warning, and shouldn't prevent compilation. The error that prevents gradle sync from completing is the "The minSdk version should not be declared in the[...]" issue. If you click on a it an automatic "refactor" button appears that corrects the issue for you.

This is all still cordova-android issues, I'm keeping an eye on release but there's been no changes. Even after the next release of cordova-android I wouldn't be surprised to find a few depreciation's in the project.

**Comment by JeFawk** [comment] 2019-08-20 09:49
After failing to get ads to work with a debug apk or a cordova with phonegap as per reported issues #3215 and #3228 I tried export as Android Studio project. Ran into the Gradle problem, had some refactoring done, more refactoring, some setup (i'm not too experienced with Android studio so it was a bit confusing) and more warnings.

I ended up clearing them out but I got no idea why the Run button is grayed out with my phone attached and USB debugging on.

![image](https://user-images.githubusercontent.com/7268697/63336968-d4659700-c348-11e9-8365-dd409cacd8a0.png)

I don't have that much time available to learn Android Studio so I'll wait until there are no warnings to try again, I think the refactoring and moving files as they recommended might have broke something.

**Comment by shortercode** [comment] 2020-01-10 17:43
So we've made some adjustments to the build service, and it's now using the latest version of cordova-android. As such I am no longer seeing this issue. Given that the change was to the server it affects both the beta and stable channels.

**Closed by shortercode** 2020-01-10 17:43 UTC
Labels: external
