### ISSUE TITLE
Exported Android builds with minify selected do not load

### ISSUE THREAD

**Issue by Parth-Kadakia** [Scirra/Construct-3-bugs#779] opened 2017-09-04 16:04 UTC
[DropTheBox.zip](https://github.com/Scirra/Construct-3-bugs/files/1275154/DropTheBox.zip)
## Problem description

When trying to build an application into Release APK with minify selected, the application is run blank with blacked out screen on devices.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Open the attached C3 project file
2. Select Export>Android>Release APK
3. Download the export and unzip
4. Download the apk on LG tablet and BLU R1 mobile
5. Test on those phones.

## Observed result

There is a blank black screen with a 100*10(apprx) horizontal line on the bottom of the screen

## Expected result

Game should be running

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

## System details

Android - 6.0

**Comment by AshleyScirra** [comment] 2017-09-04 16:33
Probably a duplicate of #778. Should be fixed in the next build.

**Closed by AshleyScirra** 2017-09-04 16:33 UTC
