### ISSUE TITLE
Clicking a family in the project bar can crash Construct 3 (unhandled exception)

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#6595] opened 2023-02-21 22:39 UTC
## Problem description

When clicking on a family listed in the project bar, C3 sometimes crashes, producing an error report popup mentioning an unhandled exception.

## Attach a .c3p

[ArtStyles.zip](https://github.com/Scirra/Construct-3-bugs/files/10798240/ArtStyles.zip)

## Steps to reproduce

1. Open the attached project.
2. In the project bar, click on the object families listed.
3. Observe that C3 crashes.

## Observed result

Clicking on a family to see or edit it in the properties bar will often crash Construct.

## Expected result

Selecting families should not crash the program.

## More details

The issue doesn't seem to occur in the "Families" example project I checked, but it has been happening with multiple recent projects of mine, indicating something I've done while working may be responsible. I tried making a new project and adding a brand new sprite to a brand new family, but clicking on that family did _not_ crash C3, so I'm still unclear on what the problematic factor is.

https://user-images.githubusercontent.com/4585257/220474785-b1b10382-dcb8-4ccd-a7ab-d0bfd52a0623.mp4

**Affected browsers/platforms:**  Firefox, Chrome.

**First affected release:**  r331

## System details

<details><summary>View details</summary>

Error report information

Type: unhandled exception
File: https://editor.construct.net/r331/components/bars/propertiesBar/propertiesBar.js, line 33, col 138
Message: TypeError: e.Jg[0] is undefined
Stack: Gfb@https://editor.construct.net/r331/components/bars/propertiesBar/propertiesBar.js:33:138 CCG.aa.eT@https://editor.construct.net/r331/components/bars/propertiesBar/propertiesBar.js:145:167 Adb@https://editor.construct.net/r331/components/bars/projectBar/projectBar.js:2:130 dLa@https://editor.construct.net/r331/components/bars/projectBar/projectBar.js:95:129 this.ic<@https://editor.construct.net/r331/components/bars/projectBar/projectBar.js:91:97 dispatchEvent@https://editor.construct.net/r331/main.js:1235:399 PM@https://editor.construct.net/r331/main.js:1604:317 YF@https://editor.construct.net/r331/main.js:1599:24 tk@https://editor.construct.net/r331/main.js:1627:321 Ed@https://editor.construct.net/r331/main.js:1620:317 d/this.ie@https://editor.construct.net/r331/main.js:1610:89
Construct version: r331
URL: https://editor.construct.net/r331/
Date: Tue Feb 21 2023 16:29:49 GMT-0600 (Central Standard Time)
Uptime: 3950.6 s
Platform information

Product: Construct 3 r331 (beta)
Browser: Firefox 109.0
Browser engine: Gecko
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 400 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2023-02-22 11:46
@DiegoScirra - looks like a regression caused by fix to #6515

**Comment by DiegoScirra** [comment] 2023-02-22 14:32
Will be fixed in the next beta, was a regression introduced in r331. It happens when clicking on families which have no instances.

**Closed by DiegoScirra** 2023-02-22 14:32 UTC

**Comment by Rhindon** [comment] 2023-02-28 00:48
My listing - #6667 - might offer some more specific details. I, too, noticed that not _all_ family objects will cause a crash, but there does seem to be a correlation between how many objects are in a family and how many instances of that family - at least one of each family object - have to be in the layout to cause the crash. But this also happened when only an event sheet was active for editing, too. And some of the family objects that caused a crash when a layout was active actually didn't cause a crash.
