### ISSUE TITLE
Color and then any Blend WebGL effects behaves totally wrong (with layer transparency off)

### ISSUE THREAD

**Issue by MihaMS** [Scirra/Construct-3-bugs#2121] opened 2018-10-08 20:35 UTC
## Problem description
After adding any Color group (or most of them) effect and then adding a Blend effect to the layer and turning off layer transparency, all layer below with this effects applied are duplicated and flipped vertically, also with some parallax effect.
Construct 3 (runtime3) r120, r121
Looks like this bug happens only in editor and not when previewing project (but need to check this more carefully)...

## Attach a .c3p
[effectsbug.zip](https://github.com/Scirra/Construct-3-bugs/files/2457876/effectsbug.zip)
or
https://drive.google.com/open?id=1R0--RlQrL_TMC2ij0I-sFsbgvndqRNli

## Steps to reproduce

1. Create a Sprite object;
2. Create new layer;
3. Add Noise Effect (or any other Color effects) to that layer and then add Multiply (or any another Blend effect)
4. Turn off Transparency property from this layer.

## Observed result
Image will be duplicated and flipped vertically with this effects applied.
Looks like this bug happens only in editor and not when previewing project...

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2018-10-09 11:56
Ugh, the transforms involved in rendering effect chains are a nightmare. This is going to be tough to figure out...

**Comment by AshleyScirra** [comment] 2019-08-19 15:04
OK, fingers crossed this should be fixed in the next release...

**Comment by AshleyScirra** [comment] 2019-08-27 11:57
Reopening since fix caused more regressions. Will revert and re-investigate in the next beta cycle.

**Comment by AshleyScirra** [comment] 2019-11-05 16:06
OK, this is an extremely complicated problem, but I've now built up a small library of tests covering lots of combinations of layer and layout effects, and including all user-submitted projects from issues filed for variants of this issue (via the above issue references). After some investigation I think I've finally come up with the right sequence of handling effects in the effects compositor to handle all the known cases correctly. The last attempt at a fix didn't work out and caused regressions, and it's possible the same will happen this time, but I have a bit more confidence this time around since I've verified it works with a wide range of projects and cases now. So hopefully this time it will really be fixed - we'll see after the next beta release.

**Closed by AshleyScirra** 2019-11-05 16:06 UTC
Labels: difficult
