### ISSUE TITLE
Can't save project because of Timeline

### ISSUE THREAD

**Issue by kidswithcrowns** [Scirra/Construct-3-bugs#3406] opened 2019-10-11 15:28 UTC
## Problem description

I created a new timeline. Now, when I try to save the project, I get the error message "Cannot read property !bD of undefined."

If I clear out the timeline so it's empty, I still can't save. If I rename it, I still can't save.

If I delete the timeline entirely, I can save. 

## Attach a .c3p

I can't save the project so I can't provide a c3p

## Steps to reproduce

1.
2.
3.

## Observed result

Cannot save

## Expected result

Can Save

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** First noticed in r/170.2

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 77.0.3865.90
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
C3 release: r170.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 52 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4400 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by shortercode** [comment] 2019-10-11 15:38
I tried the following replication steps:
1. create new project
2. add timeline
3. save project

and didn't experience any issues. As you cannot save the project can you produce a series of steps that creates the issue with a fresh project?

Going to assign this to @DiegoScirra as he might be able to divine the issue from the log, but I expect a replication will be required for this.

**Comment by AshleyScirra** [comment] 2019-10-11 15:59
Note the error message appears to refer to `GetIndex` (the error message appears to have been copied out by hand so our error parsing tool does not immediately recognise it)

**Comment by AshleyScirra** [comment] 2019-10-11 16:00
Also @kidswithcrowns please note it's important to follow the bug report guidelines, especially providing reliable steps to reproduce the issue, otherwise it's very unlikely we can help, since as @shortercode found it seems to work fine. Presumably you did something different, and we need to know what that was exactly.

**Comment by kidswithcrowns** [comment] 2019-10-13 19:04
@AshleyScirra 
@shortercode 

I wasn't able to reproduce this, sorry. I recreated the timeline with no issues

**Comment by DiegoScirra** [comment] 2019-10-14 09:24
I fixed a similar issue before, so a I am pushing a similar change to attempt to solve this problem. Without clear reproduction steps it is hard to tell if the problem will be solved though.

**Closed by DiegoScirra** 2019-10-14 09:24 UTC
Labels: can't reproduce
