### ISSUE TITLE
Canvas recording in Screen Record example produces flickering videos on both macOS and iOS Safari

### ISSUE THREAD

**Issue by sweesiong** [Scirra/Construct-3-bugs#5034] opened 2021-08-28 04:55 UTC
## Problem description

Canvas recording in Screen Record example produces flickering videos on both macOS and iOS Safari

## Attach a .c3p
[screen_recording_example.zip](https://github.com/Scirra/Construct-3-bugs/files/7070133/screen_recording_example.zip)

## Steps to reproduce

1. Click Record Canvas and wait at least 5 seconds
2. Click Stop Recording
3. Play downloaded video

## Observed result
The recorded video is flickering

## Expected result
The recorded video should not flicker.

## More details

May need to record few times or longer duration to see the effect on iOS.

I am using licensed Construct 3.

**Affected browsers/platforms:** 
macOS safari, iOS safari, iOS chrome. 

**First affected release:** 
r260
## System details

<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 14.1.1
Browser engine: WebKit
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_7
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15
C3 release: r260 (stable)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
Web Animations are not supported. Animations are disabled.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Apple Inc.
Renderer: Apple GPU
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_blend_minmax
EXT_sRGB
EXT_frag_depth
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
OES_fbo_render_mipmap
WEBGL_lose_context
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_depth_texture
WEBGL_draw_buffers
ANGLE_instanced_arrays
WEBGL_debug_shaders
WEBGL_debug_renderer_info
EXT_color_buffer_half_float
EXT_float_blend
WEBGL_color_buffer_float
KHR_parallel_shader_compile
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
Supported encode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
Video information
Supported decode formats:

H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

H.264 (video/mp4; codecs=avc1.42E01E)

</details>

**Comment by AshleyScirra** [comment] 2021-08-31 12:03
Duplicate of #5032. Please see my comment on that issue.

**Closed by AshleyScirra** 2021-08-31 12:03 UTC
Labels: duplicate
