### ISSUE TITLE
[r202] sprite not created if there is no instance of that sprite in a layout

### ISSUE THREAD

**Issue by cerxer** [Scirra/Construct-3-bugs#3923] opened 2020-06-06 08:15 UTC
## Problem description

If I create an object on start of layout in r201 you can see the object, but in r202 you can not see this object if there is not an instance on the layout. I created 2 projects one with r202 and other with r201. r201 creates object with or without an instance, r202 only creates object with an instance on the layout.

## Attach a .c3p

[201-202.zip](https://github.com/Scirra/Construct-3-bugs/files/4739631/201-202.zip)

## Observed result

Object not created in r202

**Affected browsers/platforms:** 

**First affected release:** r202

**Comment by DiegoScirra** [comment] 2020-06-06 10:46
Duplicate of #3910. Fixed in the next beta.

**Closed** 2020-06-09 18:51 UTC
Labels: duplicate, fixed
