### ISSUE TITLE
Project's Loader style reverts back to C3 splash automatically when account is logged out

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#4930] opened 2021-07-01 14:30 UTC
## Problem description

C3 has a pretty common problem where every once in a while, it will disconnect you. This happens all the time when hopping from version to version, mostly when switching back and forth between beta and stable.
The most obvious difference between being logged in or not, is that C3 then reverts back to free, and you lose some features. Now, what is supposed to happen when you open a project that exceeds the free limits, is that you're still able to preview it and look around, but not edit it, as long as the project is not back under the free project limitations.

That's all fair game.

However, I just realised that this is not the only thing C3 does: It changes the splash screen option to "C3 Splash screen", this has caused me to have to rebuild an entire project multiple times, because the option kept switching to the C3 Splash screen, which I do not want to have (for many reasons, but mostly because it takes forever to move on to the game, even when the game is already fully loaded)

## Attach a .c3p

n/a

## Steps to reproduce

1. Open a new project
2. Change splash screen to "None"
3. Log out of your account
3. Log back in

## Observed result

The splash screen option changes when you log out, but most importantly, it stays that way when you log back in

## Expected result

The project should revert to being untouched when the user logs back in.

## More details

In general, it is terrible UX to change anything in the project and not make it painfully clear you changed it.
When the project auto upgrades to c3runtime, a cool little pop up appears to let you know, but that's the one instance where it does.
In general, C3 has an infuriating tendency to just change project settings silently when it deems necessary. This has happened with script mode, worker mode, and now splash screen. All 3 can cause issues on export if you are not aware they have been changed, and so all 3 inevitably lead to frustration, confusion, time lost and having to reexport the project.

Please, in general, if you want to change something in my project, at least let me know. And in that case particularly, don't double punish me for using your account system, because I already have to deal with having to log back in every other time I use C3, I don't want to have to double check my project settings every time this happens.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2021-07-02 10:12
> It changes the splash screen option to "C3 Splash screen", this has caused me to have to rebuild an entire project multiple times

Why would you have to rebuild your entire project over a single setting? Just change the setting back.

**Comment by AshleyScirra** [comment] 2021-07-02 11:24
I can't reproduce losing the setting after logging out and back in: it comes back as 'None', as it was last set.

The properties bar isn't refreshing though - if you click a layout then click back to the project to force a refresh of the project properties, you can see that after you log out it reverts to 'Construct 3 splash', and then after you log back in, it comes back to 'None', i.e. it preserves the setting you had prior to logging out. So it doesn't appear to be losing your preference after log out/log in within the same session. I've updated the next release to make sure the properties bar does refresh when you log out or back in, to make it clearer what's happening, but that's basically a minor cosmetic change.

For the record, script mode and worker mode were never affected by your account state - only the loader style is, since it is affected by free edition limits. I don't see anything else going wrong nor any justification to make further changes (I think having to rebuild your whole project over this is a bit of an exaggeration), so closing.

**Closed by AshleyScirra** 2021-07-02 11:24 UTC

**Comment by skymen** [comment] 2021-07-02 19:16
> Why would you have to rebuild your entire project over a single setting? Just change the setting back.
Well, if I builded the game with the wrong setting, I have to build the game again
Especially when the splash screen doesn't appear in preview

> For the record, script mode and worker mode were never affected by your account state
I didn't mean that, I just added that as a general notion.

Thanks for fixing, I'll let you know if this keeps being a problem in the future 👍
