### ISSUE TITLE
Error Message - iOS Cordova

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#3724] opened 2020-03-24 13:23 UTC
## Problem description

I get the error-message on iOS:

**Rejection from 'runtime' handler 'cordova-fetch-local-file':
FileError
code: 1**

## Attach a .c3p

[Download Example-File](http://massive-cube.com/public/test-ios-app.c3p)

## Steps to reproduce

1. Open example-file
2. Export as iOS-Cordova-App
3. Build the App (iOS/xcode/mac)
4. Start the App and get the error

## Observed result

Error Message

## Expected result

No Error Message

## More details

**Affected browsers/platforms:** 

iOS - Cordova-App

**First affected release:** 

r192 Beta

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.44.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.44.0 (like Chrome/80.0.3987.87)
C3 release: r192 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 76 gb
Storage usage (approx): 626 mb (0.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2020-03-24 15:30
Is there actually any issue with the running of the app itself?

On startup it checks for some optional files and if these are missing, it logs an error, but handles that and carries on as designed. If all you are reporting is that an error message appears in the log, it's not a bug and won't be investigated, it's only an issue if it actually affects the app in some way.

**Comment by masscube** [comment] 2020-03-24 16:37
Yeah, the app starts. I just wanted to report the bug for the sake of completeness.

**Comment by AshleyScirra** [comment] 2020-03-25 11:50
OK, there's no evidence this is a problem so closing.

**Closed by AshleyScirra** 2020-03-25 11:50 UTC
Labels: not a bug
