### ISSUE TITLE
Crash when press "Preview" button

### ISSUE THREAD

**Issue by ColorfulCakeChen** [Scirra/Construct-3-bugs#512] opened 2017-06-15 07:43 UTC
## Problem description

Construct 3 crashes when previewing or exporting. 

## Attach a .c3p

[TestCrash.zip](https://github.com/Scirra/Construct-3-bugs/files/1076882/TestCrash.zip)

## Steps to reproduce

1. Open the project file. (Or, create a new blank project.)
2. Press the "Preview" button. (Or, Select Menu/Project/Export.)

## Observed result

Construct 3 crashes.

## Expected result

Running (or exporting) the project.

## Affected browsers

* Chrome: yes
* Firefox: 
* Edge: 
* Safari: 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r37/exporters/preview/exporter.js, line 1, col 40
Message: Uncaught ReferenceError: ǃE is not defined
Stack: ReferenceError: ǃE is not defined at https://editor.construct.net/r37/exporters/preview/exporter.js:1:40
Construct 3 version: r37
URL: https://editor.construct.net/
Date: Thu Jun 15 2017 15:26:59 GMT+0800 (台北標準時間)
Uptime: 60.6 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5625
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36
C3 release: r37

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4400 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2017-06-15 08:59
Looks like another duplicate of #508 - workaround: try clearing your browser cache.

**Closed by AshleyScirra** 2017-06-15 08:59 UTC

**Comment by ColorfulCakeChen** [comment] 2017-06-15 09:04
It's work. After clearing browser cache, the problem solved. Thanks~
