### ISSUE TITLE
APK is not working

### ISSUE THREAD

**Issue by Leomcs1982** [Scirra/Construct-3-bugs#4848] opened 2021-05-25 05:06 UTC
## Problem description

I published an APK generated by Construct 3 and it is not installed when I download it on Google Play or when I try to install the release version on my phone

## Attach a .c3p
https://app.box.com/s/o604js8wx8xhkt6qrvrwcrijfd6ixohz

## Steps to reproduce
1. Try to export the release version
2. Try to install on your phone

## Observed result
The app has not been installed
! [Screenshot_20210522-190835] (https://user-images.githubusercontent.com/73327104/119242157-16c99280-bb32-11eb-8a91-522aebf75da9.png)

## Expected result
Application installed correctly

## More details
I tried:

    Test on 2 smartphones
    Export on 3 different devices
    Export using 4 different browsers: Chrome, Firefox, Edge and Opera
    Export 4 different projects
    Export signed and unsigned release version

None of these attempts worked.

**Affected browsers/platforms:** 

Chrome, Firefox, Edge, Opera e desktop

Construct 3 - R248

**Comment by AshleyScirra** [comment] 2021-05-25 11:28
Duplicate of #4845. Construct doesn't have any involvement in whether the app is installable or not. It depends on the configuration of the device, the store, the signing policy, the security restrictions of the device, etc. Check you have correctly published the app according to the documentation and the store policies.

**Closed by AshleyScirra** 2021-05-25 11:28 UTC
Labels: duplicate
