### ISSUE TITLE
Dark theme ? small cosmetic issue: copy pasting from one project to another something without a reference makes the event block half height

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1088] opened 2017-12-11 08:09 UTC
## Problem description

I copy pasted the following from one project to another. The project I was pasting to didn't have a reference but the event block turned pretty tiny as a side effect.

{"is-c3-clipboard-data":true,"type":"actions","items":[{"id":"set-layer-visible","objectClass":"System","parameters":{"layer":"Global_LayerName.Loading","visibility":"invisible"}}]}

## Attach a .c3p

Any empty project will do like shown in the gif

![tinyeventblock](https://user-images.githubusercontent.com/7268697/33821142-62dfaa9a-de5b-11e7-886c-7421b08f4209.gif)

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 62.0.3202.94
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
C3 release: r71
Language setting: en-US

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 630 mb (9.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2017-12-11 16:32
Did you check the default theme and verify it does not happen there?

**Comment by JeFawk** [comment] 2017-12-11 21:06
It's fine there

**Comment by Animmaniac** [comment] 2018-01-24 21:10
@JeFawk 
Is this still happening? It seems I can't reproduce it anymore.

**Comment by JeFawk** [comment] 2018-01-25 12:01
Yes it is happening, I can reproduce it 100% @Animmaniac . I've attached a small movie with repro steps.
[2018-01-25_13-59-47.zip](https://github.com/Scirra/Construct-3-bugs/files/1663846/2018-01-25_13-59-47.zip)

**Comment by JeFawk** [comment] 2018-01-25 12:05
Happens with light theme too, probably with default as well my guess. 
[2018-01-25_14-04-10.zip](https://github.com/Scirra/Construct-3-bugs/files/1663865/2018-01-25_14-04-10.zip)

**Comment by Animmaniac** [comment] 2018-01-25 19:49
OK, I discovered that it only happens when the "Hide 'Add actions' rows" is checked in Event Sheets settings. The lack of the 'Add actions' link makes the actionBlock collapse.

![bug-hasactions-a01](https://user-images.githubusercontent.com/29487913/35408430-381ce994-01f6-11e8-94f6-ec7d8e0cce58.png)

I was able to reproduce it on the default theme as well. It seems a "hasactions" attribute is added to the actionBlock even though the paste failed due to missing references.

@AshleyScirra  @shortercode It seems maybe it's something that should be fixed on the paste code rather than the theme (?)

**Comment by AshleyScirra** [comment] 2019-01-17 14:56
The "Add action" link is still meant to be shown for events with no actions even if "Hide 'Add action' rows" is enabled. For some reason the "Add action" link is unintentionally disappearing when it shouldn't be. However I can't follow the repro steps; videos aren't very useful as I can't see exactly what you're doing (e.g. which keyboard shortcuts you're using, if any), and the video is too high-speed to follow conveniently, so my efforts to reproduce this have been unsuccessful. Please use written steps to reproduce. Given the age of this issue and the minor severity, closing - feel free to re-file with clearer steps to reproduce if you still want this investigated.

**Closed by AshleyScirra** 2019-01-17 14:56 UTC
Labels: can't reproduce, theme
