### ISSUE TITLE
Sounds and music delay on Android device

### ISSUE THREAD

**Issue by Kunnatam** [Scirra/Construct-3-bugs#1434] opened 2018-03-27 17:12 UTC
## Problem description

When I try to play sounds or music on Android device (samsung s7), it feels much more delayed compare to when play on computer browser. I don't know if this is the best a mobile device can do but with sound delay, it limits the opportunity to make a hardcore rhythm game. With few slow tap sequence, it is unnoticeable, but it becomes very clear when you have to tap very fast. 

## Attach a .c3p

[here](https://www.dropbox.com/s/kgragtqej9qtq1t/sound%20delay.c3p?dl=0)

## Steps to reproduce

1.Make on touch sprite event > play sounds or music
2.Listen carefully and you will notice some delays.

## Observed result

sound delays
edit* it's like 0.1 sec delay

## Expected result

sound plays instantaneously when finger make contact with a screen

## Affected browsers

* Computer Chrome: no
* Android Mobile Chrome: yes
* APK: yes

**Comment by AshleyScirra** [comment] 2018-04-05 16:11
Construct does not control the actual audio rendering and output. Any audio latency will be caused by the browser, OS or hardware. I've seen reports of some Android devices having terrible audio output latencies in the past, although apparently it's better on newer devices.

Closing since there's nothing for us to change in our code. If you still want to pursue this you could file a Chromium bug at crbug.com but they may tell you the same.

**Closed by AshleyScirra** 2018-04-05 16:11 UTC
Labels: external
