### ISSUE TITLE
Shortcut Issues

### ISSUE THREAD

**Issue by Coyowl** [Scirra/Construct-3-bugs#175] opened 2017-05-12 14:37 UTC
## Problem description

1. "D" doesn't disable events
2. "Z" Creates 2 Else blocks instead of 1

## Steps to reproduce

1. Press "D"
2. Press "Z"

#169 
# Observed result

On D, nothing happens
On Z it creates 2 Else blocks

## Expected result

On D, Disable event
On Z create 1 Else block

## Affected browsers

* Chrome: yes
* Using r26

**Comment by AshleyScirra** [comment] 2017-05-12 14:44
Very likely duplicate of #175. 'D' would not work if it was firing twice since it would just toggle the disabled state twice.

**Closed by AshleyScirra** 2017-05-12 14:44 UTC

**Comment by Coyowl** [comment] 2017-05-12 14:45
What about the Z? It creates two Else blocks

**Comment by AshleyScirra** [comment] 2017-05-12 15:42
That's exactly what bug #118 describes.

**Comment by Coyowl** [comment] 2017-05-12 16:18
Sorry, I didn't understand
Thanks
