### ISSUE TITLE
Sprites can't be picked by UID on same tick they're created on

### ISSUE THREAD

**Issue by cb130felix** [Scirra/Construct-3-bugs#3516] opened 2019-12-03 14:06 UTC
## Problem description

I'm transitioning a project from c2 to c3 and I noticed a diference between the engines.
In construct 3 it looks like Sprites can't be picked by UID on same tick that it was created on.

## Attach a .c3p

c3 project: https://drive.google.com/open?id=1To5WaovcZR9mV5x90Q7Hqdng33wzoBxt
c2 project (for comparassion): https://drive.google.com/open?id=18zt6vJVvrFZlIFCgwmodZtVuNxz71pbw 

## Steps to reproduce

1. Just run the applcation

## Observed result

In the construct 2 project it is possible to reference the "father" object by uid in the same tick the father object was created. In the construct 3 project this is not possible.

## Expected result

To be possible to pick objects by UID on the same tick they were created.

## More details

I think it's important to notice that the incosistency still remains in c3 even if I set the c3 project to c2runtime.

c3 project was created in r178
c2 project was created in r265

**Comment by shortercode** [comment] 2019-12-03 15:52
As far as I'm aware it should be possible to reference any existing object via their UID even on their first tick, so I would assume that something else is going on here. Assigning to @AshleyScirra to review.

**Comment by AshleyScirra** [comment] 2019-12-03 17:04
It's not a bug, it's a mistake in the project. 'On created' triggers during 'Spawn', so the action to set the "son" object's "fatherUID" happens *after* 'On created' has run. Therefore 'On created' runs with `son.fatherUID` uninitialized, and set to the default 0. In one project the father object happens to have a UID of 0, so it works by chance. In the other the father object has a different UID, probably because objects were created in a different order. Since the UID is not 0, it doesn't work.

You need to make sure any events that rely on `fatherUID` being set run after the action that sets it, not before.

**Closed by AshleyScirra** 2019-12-03 17:04 UTC
Labels: not a bug

**Comment by cb130felix** [comment] 2019-12-03 17:17
Oops... yeah just tested it here and now it works. Sorry about that.
