### ISSUE TITLE
[r43] Crash when middle-click while dragging object.

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#583] opened 2017-07-05 06:40 UTC
## Problem description

Just dragging object and middle-clicked caused the crash.

## Steps to reproduce

1. Create a Sprite object.
2. Drag with left-click.
3. While dragging, middle-click.

## Observed result

Crashed.

## Expected result
No crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>
Error report information
Type: unhandled exception
File: https://editor.construct.net/r43/main.js, line 2, col 257513
Message: Uncaught Error: pointer already captured
Stack: Error: pointer already captured at Function.ǃUf (https://editor.construct.net/r43/main.js:2:257519) at l.ǃ$X (https://editor.construct.net/r43/components/editors/layoutView/layoutView.js:1:39439) at Array.ǃUQ (https://editor.construct.net/r43/components/editors/layoutView/layoutView.js:1:38899) at ǃX.Event.ǃeGB.ǃeG_ (https://editor.construct.net/r43/main.js:2:255162) at window.ǃeN.dispatchEvent (https://editor.construct.net/r43/main.js:2:253816) at window.ǃeN.ǃ$X (https://editor.construct.net/r43/components/editors/layoutView/layoutView.js:1:13734) at HTMLDivElement.ǃH.ǃX.ǃn.ǃX.ǃU.ǃN (https://editor.construct.net/r43/components/editors/layoutView/layoutView.js:1:3850) at HTMLDocument. (https://editor.construct.net/r43/main.js:2:250698)
Construct 3 version: r43
URL: https://editor.construct.net/index.html
Date: Wed Jul 05 2017 14:38:04 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 20.9 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r43

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2017-07-06 11:07
Can't reproduce here: I opened Ghost Shooter, dragged the player sprite, and right clicked while dragging. It opens the context menu. Did you miss something in the repro steps?

**Comment by jaydonteh** [comment] 2017-07-06 12:23
Oops, my mistake! It was the middle-click, not the right-click.

**Comment by TheRealDannyyy** [comment] 2017-07-06 13:36
Can reproduce this on my end as well. You can pretty much drag any sprite and middle click to reproduce this.

**Comment by AshleyScirra** [comment] 2017-07-06 14:01
Got it - should be fixed in the next build. Just missed r44 I'm afraid.

**Closed by AshleyScirra** 2017-07-06 14:01 UTC
