### ISSUE TITLE
R95.2 Zoom in/out affects browser more often than the layout

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1508] opened 2018-04-20 14:34 UTC
## Problem description

I've started noticing that zooming in or out affects the app browser window more often than the layout of the editor so I try to zoom out and using CTRL+Scroll and it most of the time zooms out the chrome window. 

This wouldnt be a big deal just that once I revert it the selection is broken. The cursor is in the middle of the screen and when I try to select the selection rectangle starts ~ 300 px away.

## Attach a .c3p

Any empty project will do.

## Steps to reproduce

1. open up a blank project
2. zoom in and out using CTRL+Scroll

## Observed result

Notice how the zoom affects the app window. Reset the zoom, notice how the selection rectangle is incorrect.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 66.0.3359.117
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 6.3 gb
Storage usage (approx): 2.8 gb (45.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2018-04-20 14:38
Duplicate of #1396 - it's a Chrome bug (https://bugs.chromium.org/p/chromium/issues/detail?id=823247) that is already fixed and should reach the stable channel in due course.

**Closed by AshleyScirra** 2018-04-20 14:38 UTC
Labels: duplicate

**Comment by JeFawk** [comment] 2018-04-20 15:33
Oh, okey thanks. I'll use ctrl+ + / - for now

**Comment by AshleyScirra** [comment] 2018-04-20 15:38
The bug only happens if you press control while scrolling the mouse wheel simultaneously, so another workaround is just to make sure control is down before you start scrolling the mouse wheel.
