### ISSUE TITLE
Importing C2 *.capx, effect parameters with non-alpha characters do not get assigned correctly

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-3-bugs#1050] opened 2017-11-28 17:35 UTC
## Problem description
Importing C2 *.capx, effect parameters with non-alpha characters do not get assigned correctly

## Attach a .c3p
[capx.zip](https://github.com/Scirra/Construct-3-bugs/files/1510986/capx.zip)
capx to import and c3addon needed at the bottom.

## Steps to reproduce

1. Load c3addon
2. Open Chrome Console
3. Load *.capx with effect parameters that are non-alpha
4. See warnings in Console on parameters not assigned.

## Observed result
Parameters not assigned for some effect parameters with non-alpha characters.

## Expected result
All parameters assigned correctly.

## Affected browsers
* Chrome: yes
* Firefox: NA
* Edge: NA
* Safari: NA

## System details
Windows 10

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

		C3.json:
		
		{
			"id": "ambient-(green)",
			"c2id": "ambient-(green)",
			"type": "float",
			"initial-value": 0.5,
			"uniform": "ambientG"
		},

		C2.xml:
    <param>
      <name>Ambient (Green)</name>
      <description>Ambient (Green) 0 to 1</description>
      <type>float</type>
      <initial>0.5</initial>
      <uniform>ambientG</uniform>
    </param>
	
	On loading *.capx from file into C3 console message:
	main.js:63 [C2 compat] Could not load effect 'normalmapext' parameter 'ambient-green' value '1' from a Construct 2 project.

</details>

**Comment by AshleyScirra** [comment] 2017-11-30 11:27
I need the full .c3addon package to be able to reproduce this. You've only provided fragments of an addon, not enough to build a full installable addon from.

**Comment by MikalDev** [comment] 2017-11-30 17:03
This addon is an effect not a plugin/behavior, so I think for an effect, I included all the files needed (it matches the number and type of files in the C3 [EffectSDK](https://s1.construct.net/articles/downloads/855/c3-effect-sdk-v1.zip) example.) I have already installed this addon in C3.

**Comment by AshleyScirra** [comment] 2017-12-01 00:39
There's no .fx file and no language file. Please just provide the .c3addon so I can reproduce the issue, otherwise I can't help.

**Comment by MikalDev** [comment] 2017-12-01 03:20
I'm am not sure what's going on, when I download the above zip file, there are two files: normal_map_extended_1v01_nosf.capx and NormalMapExtended.c3addon . When I change NormalMapExtended.c3addon to a *.zip file and unzip, I see addon.json, effect.fx and under a lang dir, en-US.json. Here's just c3addon by itself (but again it was in the original zip also.)

[NormalMapExtended.zip](https://github.com/Scirra/Construct-3-bugs/files/1520297/NormalMapExtended.zip)

**Comment by AshleyScirra** [comment] 2017-12-01 13:41
Oh right, normally a zip attached to a bug report is just a .c3p file, I didn't see you put something else in there. Well, it turns out it's actually C2 itself that strips non-alphanumeric characters when saving to the project, so the C2 XML file ends up with an ID like "ambient-green". C3 will import based on this ID. It's easy to fix, because it tells you the ID it's looking for ("ambient-green") so all you need to do is change the "c2id" to "ambient-green" and it will look up correctly.

We can't fix how C2 saves projects at this point, so closing as won't fix - just filter those characters out from your c2ids as well.

**Closed by AshleyScirra** 2017-12-01 13:41 UTC
Labels: need info
