### ISSUE TITLE
Touch: zooming C3 example spazzes out on iPhoneX

### ISSUE THREAD

**Issue by damjancd** [Scirra/Construct-3-bugs#2782] opened 2019-03-28 08:35 UTC
## Problem description

Pinch to zoom totally spazzes out as in the video example when pinched to zoom

## Attach a .c3p

[IMG_3055.TRIM.MOV.zip](https://github.com/Scirra/Construct-3-bugs/files/3016914/IMG_3055.TRIM.MOV.zip)

## Steps to reproduce

1. Open Touch: zooming example project in C3
2. Remote preview on an iphone or I suspect any phone
3. After a few tries it jumps and spazzes

## Observed result

Screen spazzes out and gets lost

## Expected result

Normal pinch to zoom and drag

## More details

**Affected browsers/platforms:** 
 
latest iOS iphone but it might be on android as well

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_1
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1.7999999523162842
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 54 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) HD Graphics 615
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment] 2019-03-28 10:20
Closing as duplicate of #2750 which already refers to issues with that example on iOS.

**Closed by AshleyScirra** 2019-03-28 10:20 UTC
Labels: duplicate
