### ISSUE TITLE
Pixelart does not support different mobile screensizes and aspect ratios

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#2246] opened 2018-11-04 05:42 UTC
## Problem description

I cannot get pixel-art to work across multiple devices and resolutions and aspect ratios

## Attach a .c3p

https://puu.sh/BW3dL/02479ec7af.c3p

## Steps to reproduce

1.preview the project either on desktop or mobile
2.on desktop resize the window a few times
3.on mobile try switchtching from portrait to landscape

## Observed result

There are black bars

## Expected result

No black bars since there is a function to resize the canvas to match the guidelines on supporting multiple screen sizes 

by simulating an integer scale outer full-screen mode

## Affected browsers

* Chrome: yes/no

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r123.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 421 mb (2.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2018-11-05 14:32
Closing as duplicate of #2245

Please refer to my response there on how to resolve your issue.

**Closed by shortercode** 2018-11-05 14:32 UTC

**Comment by eleanorawesome** [comment] 2018-11-05 15:35
@shortercode it's not a duplicate it's a different issue

**Comment by eleanorawesome** [comment] 2018-11-05 15:46
Chrome debug gives different values than Platforminfo.WindowInnerHeight  so maybe it's related to that ?

**Comment by eleanorawesome** [comment] 2018-11-06 06:48
Ok so it dosen'T work if platforminfo.WindowInnerWidth if the number after a prime number

**Comment by eleanorawesome** [comment] 2018-11-06 07:53
The bars are still pretty significant 
![image](https://user-images.githubusercontent.com/32940085/48050166-21d49700-e16f-11e8-8e7c-f676faa19d87.png)

**Comment by eleanorawesome** [comment] 2018-11-06 08:05
sometimes the screen_width formula returns infinite 
![image](https://user-images.githubusercontent.com/32940085/48050733-bee3ff80-e170-11e8-8ce7-36fa6895ed4f.png)
![image](https://user-images.githubusercontent.com/32940085/48050744-cacfc180-e170-11e8-816e-ab2d13da8741.png)
