### ISSUE TITLE
I deleted a variable and now it's corrupted my only Project Save.

### ISSUE THREAD

**Issue by mfoster98** [Scirra/Construct-3-bugs#229] opened 2017-05-17 11:39 UTC
## Problem description

I can no longer load my project as the error shown below pops up and only allows me to close project.
`Event sheet 1, event 17, action 2: Unknown expression 'stars': This is not a system expression or variable name in this scope.` You can see more of the window type by trying to open the c3p file yourself.

## Attach a .c3p

[Download ScoreThatShot.cp3](https://drive.google.com/open?id=0B0wOpAl3MFAeVXc3Nk5uLXB5WG8)

## Steps to reproduce

1.Load up construct 3
2.Load the c3p file
3.Once loaded the error appears.

## Observed result

An error window is displayed not allowing any continuation with the project.

## Expected result

I expected my project to load as it normally does, where I can edit the game/project.

## Affected browsers

* Chrome: yes
* Firefox: no
* Edge: no
* Safari: no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

Local storage
Storage quota (approx): 33 gb
Storage usage (approx): 112 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 7900 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_get_buffer_sub_data_async
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2017-05-17 11:40
Can you provide steps to reproduce this issue in the first place? The steps only cover the consequence, we need to know how to repeat the actual problem.

**Comment by mfoster98** [comment] 2017-05-17 11:52
Yeah no problem, sorry Ashley I misunderstood what was being asked 😄 

---- Edit 17/05/17 12:52PM GMT ----

Steps to reproduce

1. Create a variable and reference it by Checking if it set to 1,2, or 3 on desktop version of C3. (I also had an event to make a sprite visible or invisible.
2. Load project on android mobile (downloaded/saved) version of C3
3. Delete any events linked to the variable from the mobile edition.
4. Delete the variable created on the desktop version, but use the mobile edition to delete it.
5. Save the project and close the engine.
6. Reopen engine and project.

This is what I did, switching to different devices as I went out and worked on my project whilest on the bus.  On the mobile edition it also doesn't allow me to open the project.

Thanks!

**Comment by AshleyScirra** [comment] 2017-05-17 12:05
There is no syncing between devices unless you save to cloud and then reopen the project on a different device. Is that what you were doing? If so this should still also be reproducable on a single device doing the same sequence of save and open, which would make it easier to fix.

**Comment by mfoster98** [comment] 2017-05-17 12:09
Could still create the bug, It's strange that it's done this but it's upsetting that I've lost the work I've done already.  I did use the cloud and by the way I L-O-V-E it! I have a screenshot also of the bug I get if it would be helpful?

**Comment by jaydonteh** [comment] 2017-05-17 13:06
@mfoster98 You could try editing your c3p file and remove the event sheet associate to the problem. Perhaps you could salvage some work back?

**Comment by shortercode** [comment] 2017-05-17 13:20
[ScoreThatShot.zip](https://github.com/Scirra/Construct-3-bugs/files/1007841/ScoreThatShot.zip)

I removed the bad expression for you, glad to hear you like the cloud save!

**Comment by AshleyScirra** [comment] 2017-05-17 13:24
@mfoster98 can you reproduce following your steps but always using the desktop device only? i.e. every time you would have closed and reopened on mobile, just close and reopen on the same desktop system.

**Comment by mfoster98** [comment] 2017-05-17 13:53
When I tried this on just my desktop it didn't break and this bug didn't occur.  Strange.

**Comment by mfoster98** [comment] 2017-05-17 13:54
Also thanks for the reply @jaydonteh

**Comment by mfoster98** [comment] 2017-05-17 13:56
Also thanks for the correction haha, drive zips it for you I think

**Comment by shortercode** [comment] 2017-05-17 14:11
@mfoster98 It didn't really need zipping again **c3p** files are already compressed. It was just so github would allow me to upload it. They only allow known file extensions so it doesn't accept **c3p**.

@jaydonteh I wouldn't really recommend editing the c3p file manually, they are a little fiddly if you don't know your way around them, event sheets are referenced in several places so removing them will break a project file.

**Comment by jaydonteh** [comment] 2017-05-17 15:15
I don't think this should be closed just yet. The issue isn't resolved yet tho...

**Comment by mfoster98** [comment] 2017-05-17 18:31
Alright, sorry!  I recreated the project in the end didn't know if I should have closed it or not because of time handling etc.

**Comment by shortercode** [comment] 2017-05-17 18:50
There's definitely a bug somewhere because you managed to corrupt your project. We'd like to avoid happening to anyone else if we can as it's rather upsetting to have your project broken.

If you can't find a replication then we might close it again at a later date.

**Comment by spesknight** [comment] 2017-05-21 13:40
I had some problems too: after deleting an object that was referenced project could not be opened. It says construct2 allows wrong expression and construct3 doesn't. But how can I correct expressions using Construct3?

**Comment by jaydonteh** [comment] 2017-05-21 13:57
@spesknight 
> But how can I correct expressions using Construct3?

Short answer is you can't. Was your project made entirely in C3 before it gets corrupted? I so, your issue might not be related to this topic. If your issue is just about wrong expressions, you should correct the expressions according to what the error in C3 says in C2 before importing to C3. 

But if your project is indeed corrupted by just using C3 only, can you show more info about the errors like steps to reproduce it?

**Comment by spesknight** [comment] 2017-05-22 06:10
My project was made entirely on Construct3.
Steps to reproduce should be making a small project and deleting an object that is used in some expressions.

**Comment by shortercode** [comment] 2017-05-24 11:54
@spesknight have you created a bug for your project corruption? Can you remember what you did to the project before it became corrupted? I can likely fix your project for you, but we'd like to get rid of any project corruption bugs we can find.

**Comment by spesknight** [comment] 2017-05-24 12:03
I haven't create a bug as I thought it was similar to this bug.
What I did is remove the object "Tile" and now when I open the project I get several errors like "EGameScreen, event 10, action 1: Not an object: 'Tile' is not an object name"
I think we should be able to open the project in Construct3 and correct the errors. I don't even have Construct2 installed.
I attach my project file, just as reference, no need to recover it as I have already worked on other project files to continue with the development.
[3place002.zip](https://github.com/Scirra/Construct-3-bugs/files/1025390/3place002.zip)

**Comment by shortercode** [comment] 2017-05-24 13:58
@spesknight Your right the error message isn't great, for starters it's misleading as it presumes the invalid file was created by C2. You wouldn't even be able to open the project in C2 to correct the issue.

That's corruption is odd. The Tile object obviously no longer in the project, but the actions that reference it are still there. I can't find any way to remove the tile object without the actions. Can you remember anything else about this?

I wasn't able to replicate the original bug, so will close this if I can't repeat yours either.

**Comment by shortercode** [comment] 2017-06-01 11:58
Closing this bug, as no reproductions we're found.

**Closed by shortercode** 2017-06-01 11:58 UTC
Labels: can't reproduce
