### ISSUE TITLE
Back-button doesn't work on Android

### ISSUE THREAD

**Issue by fredriksthlm** [Scirra/Construct-3-bugs#4636] opened 2021-03-04 19:10 UTC
## Problem description

According to the Cordova documentation it should be possible to control the Back-button on android for exported APKs.
This does however only work if you do some extra (odd) step. It is required to "unfocus" the app first and go back, then the back-button work fine. But if you only open the app and press back-button it closes down directly.

## Attach a .c3p

[back-button.zip](https://github.com/Scirra/Construct-3-bugs/files/6086040/back-button.zip)

## Steps to reproduce

1. Open and export project (I used Signed release APK, without any minification)
2. Open the app on your phone
3. Press the phone BACK-button

## Observed result

The app closes down

## Expected result

The event for mobile BACK-button should trigger

## More details
Very important note: IF you open the app, and unfocus it somehow (you can click the "meny" or "recent" button in the nav bar to unfocus the app), then go back to your app. If you do this small step before cklicking the back-button, the button will start to work fine! After this the back button events works perfectly until you close the app and open it the next time.

It doesn't matter if the project is exported with or without statusbar!

I have also tried to just wrote the js code directly in a script in the project, according to the official Cordova docs: 
https://cordova.apache.org/docs/en/latest/cordova/events/events.html#backbutton
The result is the exactly same behaviour as using your browser plugin and back-button event.

**Affected browsers/platforms:** 
I have a Samsung10, Android v11

**First affected release:** 
I cannot say if this was broken at some point cause I have never used it. Now I use b238 and it works as descibed above.

NOTE:
there was a quite similar bug report a year ago, but only affected fullscreen. But it was markd as "solved", so I guess it worked back then:
https://github.com/Scirra/Construct-3-bugs/issues/3115

**Comment by fredriksthlm** [comment] 2021-03-04 19:28
Ooh! The exported project actually works fine on my super ancient phone with Android 7 !

I found this thread on Reddit:
https://www.reddit.com/r/RelayForReddit/comments/ipa4s2/pixel_4a_android_11_update_back_navigation_is/
_I just downloaded the Android 11 update for my Pixel 4a. Previously, navigation with the Back key and the Back gesture worked fine. Now, neither one works as it did before. To execute a Back, I have to hit Recent Apps then re-enter Relay. After doing that, Back works again._

This is **excatly** what I experience, you need to press Recent Apps - then go back to get the button to work.

Seems like Reddit managed to fix it for their app according to the dev there, so maybe there is some tweak you can do to make it work on Android 11?

Also found this
https://www.reddit.com/r/GooglePixel/comments/ir8aer/back_button_staying_highlighted_on_android_11/

**Comment by AshleyScirra** [comment] 2021-03-05 10:46
Duplicate of #4259 - it's a Cordova bug: https://github.com/apache/cordova-android/issues/1106

**Closed by AshleyScirra** 2021-03-05 10:46 UTC
Labels: duplicate
