### ISSUE TITLE
iframes still crashing Android exports?

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#3332] opened 2019-09-14 14:12 UTC
## Problem description
When I let the app/game run for a while or have it in background and come back its stuck and not responding again (like in 164 at release).

## Attach a .c3p
[iframeCrash.zip](https://github.com/Scirra/Construct-3-bugs/files/3612778/iframeCrash.zip)

## Steps to reproduce
add iframe to project and export for android (Scirra build service)

## Observed result
app not responding after a while, cant switch layouts, touch on sprite not working etc.

## More details

**Affected browsers/platforms:** 
Chrome/Android

**First affected release:** 
164.3
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.132
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
C3 release: r164.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 21 gb
Storage usage (approx): 720 mb (3.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 615 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-09-16 10:20
I build a debug APK and ran it on a Pixel 3 and it seemed to work fine. The steps to reproduce are missing though, it's not clear what to do with the project. So I switched layouts a few times, went to home screen, came back, and switched layouts again. There were no visible problems. Please make sure you follow all the bug report guidelines to ensure we can investigate your report properly. It may also be useful to attach USB debugging to see if there is a JavaScript error being logged to the console. However as it stands there's no evidence of a problem, so closing.

**Comment by TheBl4ckSh33p** [comment] 2019-09-17 08:45
I tried it on Huawei Mate 10 and 20 and got several reports from users and bad reviews on Google cause the app is freezing after a while. 

Instructions:
1. Open app, tap 1/2 button to switch layouts, everything seems fine
2. wait a few minutes and try again (lock screen or open other apps)
3. tapping on 1/2 button no longer switches layouts and app is frozen

**Comment by TheBl4ckSh33p** [comment] 2019-09-17 10:30
I enabled USB debugging a few times and connected my phone to my Surface Go tablet but Chrome does not find any device. -.-

**Comment by AshleyScirra** [comment] 2019-09-17 11:55
We'd need more reliable steps to reproduce to be able to investigate the problem. "Wait a few minutes" is vague and steps like that tend to make it take so long to investigate the bug that it becomes infeasible to deal with it, since we may well have to follow the steps 10-20 times while investigating. Additionally if it is not actually Construct that is hanging/crashing, and it is the browser engine, or possibly the particular content of the iframe in your real app, then there is little we can do about it anyway.

**Comment by TheBl4ckSh33p** [comment] 2019-09-19 06:45
The content of the frame seems to be irreleveant cause I used construct.net (iframe default) in the example instead of my Jimdo page and it happens everytime I open the app and keep it running for a while.

**It just stops working and is frozen.** I get new 1 star reviews every day and feedback mails telling me "app is freezing" "app not responding" etc. and **that never happened before the last stable update** of Construct. But I did not change or add new things except changing some text in text objects, just **rebuilt it with the new stable build.**

**I tried to use the USB debugging again** to see if any error messages show up but chrome does not recognize my phone, it shows no devices. -.-
I try to get a phone from someone else to see if it works with it.

**Comment by TheBl4ckSh33p** [comment] 2019-09-20 09:36
It worked on another phone after some tries. The devices page showed this:

Chrome (77.0.3865.92)
Open tab with url
Open
⚠ Remote browser is newer than client browser. Try `inspect fallback` if inspection fails.
WebView in de.bl4cksh33p.borderlands (77.0.3865.92)
⚠ Remote browser is newer than client browser. Try `inspect fallback` if inspection fails.

about:blank
about:blank
inspectpauseinspect fallback

Companion for Borderlands
file:///android_asset/www/index.html
inspectpauseinspect fallback

https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html
https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html
inspectpauseinspect fallback

https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html
https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html
inspectpauseinspect fallback

**Inspect for Companion for Borderlands**
file:///android_asset/www/index.html showed the console and errors (advert interstitial) but **only the iframe was visible in the preview on the left. No sprites/buttons or text objects. Is this how it should be?** I tried the steps I usually do to get the freezing (locking phone and/or going to home screen and wait a few min, then resuming the app and hitting a button to switch layout) but it did not freeze in debug mode so far. Need to try a few more times to see if a console error shows up.

**Comment by TheBl4ckSh33p** [comment] 2019-09-23 08:30
I tried it again today and after locking the screen and resuming 3-4 minutes later the app was frozen but no errors are in the console. It does not show the app is resuming and I can still scroll the iframe but no touch/goto layout etc. is working.

Here are the last few lines in the inspect window console:

[C3 advert] Event (failed to create interstitial Error (interstitial failed to load) Type () Amount (0))
scripts/c3runtime.js:442 [Construct 3] Suspending
c3runtime.js:442 [Construct 3] Resuming
main.js:5 Rejection from 'advert' handler 'CreateInterstitialAdvert': interstitial failed to load
(anonymous) @ main.js:5
Promise.catch (async)
_OnEventFromRuntime @ main.js:5
_OnMessageFromRuntime @ main.js:5
_messageChannelPort.onmessage @ main.js:5
c3runtime.js:466 [C3 advert] Event (failed to create interstitial Error (interstitial failed to load) Type () Amount (0))
main.js:5 Rejection from 'advert' handler 'CreateInterstitialAdvert': interstitial failed to load
(anonymous) @ main.js:5
Promise.catch (async)
_OnEventFromRuntime @ main.js:5
_OnMessageFromRuntime @ main.js:5
_messageChannelPort.onmessage @ main.js:5
c3runtime.js:466 [C3 advert] Event (failed to create interstitial Error (interstitial failed to load) Type () Amount (0))
c3runtime.js:442 [Construct 3] Suspending

It did not show the usual "Resuming" message and no other error. :(

**Comment by AshleyScirra** [comment] 2019-09-23 11:05
That message indicates an error with the Mobile Ad plugin, not the iframe plugin. I've assigned @shortercode to see if he can divine anything from this crash message, but as usual, without a project and reliable steps to reproduce, I would expect there is still not yet any action we can take.

**Comment by TheBl4ckSh33p** [comment] 2019-09-23 15:55
I try to reproduce it in my example above tomorrow. The freezing happens there too without AdMob.

Can the errors come from the limit I set in AdMob? I create interstitial on start of each layout. And one line above on start of layout, If ad is ready, it shows. But I set it to 1 impression per 8 minutes in AdMob settings.

**Comment by shortercode** [comment] 2019-09-24 11:37
I can't actually see anything wrong in that log, or at least not in terms of something that would crash an app. It's a little misleading because the runtime bridge logs out errors that pass through it, even though these are expected. I adjusted the formatting to make it more readable but the logs basically say:
- failed to create interstitial advert
- app suspended
- app resumed
- failed to create interstitial advert
- app suspended

The reason for the interstitial adverts failing in both cases were that they didn't load `Error (interstitial failed to load)`. Although it doesn't say why. Looking at the source there's an error code passed to that handler, so we could potentially report more information. The resulting options are apparently:
```
ERROR_CODE_INTERNAL_ERROR - Something happened internally; for instance, an invalid response was received from the ad server.
ERROR_CODE_INVALID_REQUEST - The ad request was invalid; for instance, the ad unit ID was incorrect.
ERROR_CODE_NETWORK_ERROR - The ad request was unsuccessful due to network connectivity.
ERROR_CODE_NO_FILL - The ad request was successful, but no ad was returned due to lack of ad inventory.
```

I presume you were suspending the application manually here? Showing an interstitial would suspend the main app activity but it shouldn't be possible to trigger showing an interstitial that hasn't loaded.

**Comment by AshleyScirra** [comment] 2019-10-07 14:47
I don't think there is any action we can take over either aspect of this report. I can't reproduce an issue with using iframes, and I suspect it's a browser engine crash and not a Construct issue anyway. If something is wrong with Mobile Ad that would need its own separate report following all the guidelines to follow up on. Closing this issue.

**Closed by AshleyScirra** 2019-10-07 14:47 UTC
Labels: can't reproduce
