### ISSUE TITLE
Hard crash when trying to build to Android/Cordova

### ISSUE THREAD

**Issue by FredFors** [Scirra/Construct-3-bugs#477] opened 2017-06-09 17:19 UTC
## Problem description

I'm tring to build a project to Android. It's basically an empty project.

## Attach a .c3p

[spark.zip](https://github.com/Scirra/Construct-3-bugs/files/1064771/spark.zip)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Open project
2. Press F6 to build
3. Choose Android (Cordova)
4. Crash

## Observed result

A pop-up frame with a crashlog.

## Expected result

Expected to see the usual dialogues for building and setting options.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot set property 'tag' of null @ TypeError: Cannot set property 'tag' of null at g.ǃwt.then.then.then (https://editor.construct.net/r36/main.js:71:11082) at 
Stack: TypeError: Cannot set property 'tag' of null at g.ǃwt.then.then.then (https://editor.construct.net/r36/main.js:71:11082) at 
Construct 3 version: r36
URL: https://editor.construct.net/index.html
Date: Fri Jun 09 2017 19:14:12 GMT+0200 (W. Europe Summer Time)
Uptime: 112.5 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by FredFors** [comment] 2017-06-09 17:22
It works as intended when i added a project description. Should probably be a warning when trying to export without a description i believe.

**Comment by shortercode** [comment] 2017-06-09 17:27
The warning dialog was broken in the last release, it's fixed but I expect
the next build won't be until next week

**Comment by harrisyu** [comment] 2017-06-10 06:44
same problem here, just create a new emptyproject and export and get:

Error report information
Type: unhandled rejection
Reason: Error: Cannot set property 'tag' of null @ TypeError: Cannot set property 'tag' of null at g.ǃwt.then.then.then (https://editor.construct.net/r36/main.js:71:11082) at 
Stack: TypeError: Cannot set property 'tag' of null at g.ǃwt.then.then.then (https://editor.construct.net/r36/main.js:71:11082) at 
Construct 3 version: r36
URL: https://editor.construct.net/
Date: Sat Jun 10 2017 14:43:17 GMT+0800 (中国标准时间)
Uptime: 14.1 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36
C3 release: r36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment] 2017-06-12 10:29
Duplicate of #461 and already leaving #465 open

**Closed by AshleyScirra** 2017-06-12 10:29 UTC
Labels: duplicate
