### ISSUE TITLE
244 Sprite Frames

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#4732] opened 2021-04-13 16:30 UTC
## Problem description

Beta 244 Sprite can't add frames
## Attach a .c3p
https://www.dropbox.com/s/s0t0y0xmjf9rpfn/244spriteframes.c3p?dl=1

## Steps to reproduce

1. Open project
2. Open Sprite editor for included Sprite object
3. Try to add frame

## Observed result
Can't add frames

## Expected result
Should be able to add frames

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment] 2021-04-13 16:51
Duplicate of #4731. Will be fixed in the next beta.

**Closed by DiegoScirra** 2021-04-13 16:51 UTC
Labels: duplicate
