### ISSUE TITLE
Scene Graph breaking other features

### ISSUE THREAD

**Issue by Lobo93** [Scirra/Construct-3-bugs#4211] opened 2020-09-12 22:50 UTC
## Problem description

Whenever an object with two or more children is deleted, it causes all sorts of weird bugs on other objects.
**IMPORTANT:** These bugs varies from breaking behaviors, stopping animations and to even freezing the game preview, but I wasn't able to reproduce all of them in a minimal project.
I'm sorry about that.

The example project attached to the issue contains only one of the bugs I've witnessed.

## Attach a .c3p

[scene-graph-bug.zip](https://github.com/Scirra/Construct-3-bugs/files/5213342/scene-graph-bug.zip)

## Steps to reproduce

1. Start a new project.
2. Create an object with the 'Scroll to' behavior and some kind of movement (I used 8-direction in the example).
3. Create an object to act as the parent and add a few instances to the layout.
4. Create an object to act as the child and add 1 instance for each parent.
5. Add **one extra instance** of child to one of the parent object instances.
6. Add an event to add the child objects to their respective parent objects with the 'Destroy with parent' option enabled.
7. Add an event to destroy a parent object (I used 'on double click' in the example).
8. Run the preview and delete parent objects.

## Observed result

After deleting parent objects with 1 child, nothing weird happens, but after destroying the parent with 2 childs, the First object's 'Scroll to' behavior stops working.

## Expected result

Deleting the parent object shouldn't affect other objects' behaviors.

## More details

**Affected browsers/platforms:** 
OS: Windows 10
Browsers: Chrome v 85.0.4183.102 64 bits and Microsoft Edge v 85.0.564.51 64 bits

**First affected release:** C3 r215 (beta)

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 85.0.4183.102
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
C3 release: r215 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 267 gb
Storage usage (approx): 1.4 gb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce RTX 2070 SUPER Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2020-09-14 13:21
It looks like a crash when destroying a parent with multiple children. Thanks, should be fixed for the next release.

Note: you don't need to describe how to build the attached project in your steps to reproduce - I just open the project you provide. You only need to explain what to do with the project once it's open.

**Closed by AshleyScirra** 2020-09-14 13:21 UTC
