### ISSUE TITLE
Dragging events from one window to another crashes Construct

### ISSUE THREAD

**Issue by daleinen7** [Scirra/Construct-3-bugs#1324] opened 2018-02-25 16:49 UTC
## Problem description

When I have two event sheet tabs side by side, ctrl clicking and dragging an event from one side to the other crashes Construct.

## Attach a .c3p

[eventsheet screen problem.zip](https://github.com/Scirra/Construct-3-bugs/files/1756476/eventsheet.screen.problem.zip)

## Steps to reproduce

1. Open two event sheets with events on both sheets.
2. Move one tab to a second window. 
3. Move ctrl click and drag one event to another.

## Observed result

Construct 3 crashes.

## Expected result

The event, action, or condition should move to the other event sheet.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r85/components/editors/eventSheetView/eventSheetView.js, line 1, col 8937
Message: Uncaught TypeError: Cannot read property 'ǃBfl' of null
Stack: TypeError: Cannot read property 'ǃBfl' of null at window.ǃbd.ǃBfh (https://editor.construct.net/r85/components/editors/eventSheetView/eventSheetView.js:1:8937) at window.ǃbd.ǃByu (https://editor.construct.net/r85/components/editors/eventSheetView/eventSheetView.js:1:24188) at window.ǃbd.ǃCu (https://editor.construct.net/r85/components/editors/eventSheetView/eventSheetView.js:1:20589) at HTMLDocument.ǃCP (https://editor.construct.net/r85/components/editors/eventSheetView/eventSheetView.js:1:1966) at HTMLDocument. (https://editor.construct.net/r85/main.js:2:267678)
Construct 3 version: r85
URL: https://editor.construct.net/index.html
Date: Sun Feb 25 2018 10:36:00 GMT-0600 (Central Standard Time)
Uptime: 64404.8 s

Platform information
Browser: Chrome
Browser version: 64.0.3282.167
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
C3 release: r85
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 550 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2018-02-26 13:46
I can't reproduce this: any time I try to drag events from one sheet to the other, I get the "not allowed" cursor and dropping has no effect. How exactly are you performing this drag-and-drop?

**Comment by daleinen7** [comment] 2018-02-26 15:20
I realized I was clicking and dragging just the condition. Not the entire
event. As soon as I drag a condition outside of the secondary window over
the "main" window, Construct crashes. But if I try to just move the entire
event you're right it just displays the "not allowed" cursor.

**Comment by AshleyScirra** [comment] 2018-03-02 13:50
I see, yes it only happens with the condition. Thanks, should be fixed in the next release.

**Closed by AshleyScirra** 2018-03-02 13:50 UTC
