### ISSUE TITLE
Objects on a scaled layout have wrong position for the first tick

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-3-bugs#5103] opened 2021-10-10 02:04 UTC
## Problem description

There is an issue trying to set an object's position on a scaled layout. Either you use Anchor behavior or "On start of layout -> Set position" or "Every tick -> Set position", the first time you visit a scaled layout, objects have wrong position for one tick.

## Attach a .c3p

[PositionOnScaledLayout.zip](https://github.com/Scirra/Construct-3-bugs/files/7316684/PositionOnScaledLayout.zip)

## Steps to reproduce

1. Preview attached project
2. Layouts are changing automatically every 1.5 sec
3. Observe objects

## Observed result

Objects have wrong position for the first tick

## Expected result

Objects to have correct position on start of layout

## More details

• Using "On start of layout -> Set Position", object has wrong position for the whole time.

• Using Anchor behavior or "Every tick -> Set Position", objects have wrong position for the first tick. 

• When you revisit a layout in the same preview "session",  everything works fine.

• Sometimes but rarely, objects have correct position right away from the start.

**Affected browsers/platforms:** Chrome/Firefox/Safari, Windows

**First affected release:** Don't know..

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 94.0.4606.71
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36
C3 release: r266 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 269 gb
Storage usage (approx): 63 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce G105M Direct3D11 vs_4_1 ps_4_1, D3D11-9.18.13.4195)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Fib100** [comment] 2022-01-29 01:13
I had this problem in one of my projects. I had to do a "Wait 0 Seconds" before I set any positions on start of layout so it waited til the next frame. I got it working eventually but it took me several hours to figure out what was happening.

**Comment by AshleyScirra** [comment] 2022-02-09 13:41
The problem is updating the viewport has been historically tied to drawing the screen, so it only updates when the next frame is drawn. I've changed this to immediately update which fixes the problem, but it's quite a fundamental change and we're close to a stable release, so the fix has been kept back for the next release cycle. It will be in the first beta after the next stable release.

**Closed by AshleyScirra** 2022-02-09 13:41 UTC
