### ISSUE TITLE
Pin object to a clone pinned object -> lag

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#2072] opened 2018-09-23 19:51 UTC
## Problem description

A very strange thing...
If I pin an object to a cloned pinned object there's a lag : the pinned object is moving later.
(Sorry for my bad English...)

## Attach a .c3p

[Pin_weird.zip](https://github.com/Scirra/Construct-3-bugs/files/2409100/Pin_weird.zip)

## Steps to reproduce

If you test the attached C3P, you can see that if you move the players with the arrows, the left player's hat is moving with a delay.
The steps to reproduce  on this C3P :
1. delete the "PLAYER1" object of the left player (this object is on the layer "2")
2. **copy** the "PLAYER1" object of the right player to the left
3. Be sure this copy is on the layer "2" (because the part who have the same layer are pinned in the event sheet)
4. FROM HERE, IF YOU PREVIEW THE PROJECT YOU CAN SEE IT WORK FINE FOR THE BOTH PLAYERS.
5. Now delete the copy of "PLAYER1" from the left player.
6. **Clone** the object "PLAYER1" and put it at the left at the place who the last "PLAYER1" was deleted
7. Be sure that the cloned object is on the layer "2"
5. NOW IF YOU PREVIEW THE GAME, THE LEFT PLAYER'S HAT HAS A DELAY

## Observed result

Delay on the hat pinned to the cloned object

## Expected result

That the hat perfectly follows the player

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by SalmanShhh** [comment] 2018-09-23 23:39
I've had this happen as well but wasn't able to replicate it in a empty project by myself earlier while trying to get one of my physics objects to NOT suddenly teleport to another position in open area.

**Comment by shortercode** [comment] 2018-09-24 11:09
I remember this being referenced in #1716. Behaviours in the C2 runtime are executed in order of creation. As you have a chain of sprites pinned together the order of execution is important. If a sprite behaviour is executed at the wrong time it will move to the position from the previous frame, hence the lag.

Here's some quotes from @AshleyScirra explaining it.

This is difficult. tl;dr: pin spr_hat to spr_player_collision instead of spr_player_graphic, and it works in the C3 runtime too.

> The fundamental issue is you have a chain of pins: the hat is pinned to the player, and the player is pinned to the collision box. This is an awkward setup for the engine since it processes behaviors one at a time, and it has to pick some order to do them in. When it processes a pin, it moves the object to the correct location according to the pin. When you have a chain of pins, it only keeps them locked together if it processes them in reverse order from the root instance back (i.e. collision box, player graphic, hat). If it processes them in the other order (i.e. hat, player, collision) then there is a frame of lag, since the hat updates its position to the player, but then the player updates its position to a different position to move with the collision box, moving it away from where the hat is.
> 
> If you pin both the hat and the player to the same object, it avoids the problem since they're both pinned to the same thing and there is no chain. [...]
> 
> The C2 runtime processes behaviors in order of object creation. [...]

I've assigned to him to confirm but I believe this will be closed as not a bug.

**Comment by AshleyScirra** [comment] 2018-09-24 11:27
Yes, this is the same thing as #1716. The workaround is simple: just pin everything to one object, rather than creating a chain.

**Closed by AshleyScirra** 2018-09-24 11:27 UTC
Labels: duplicate

**Comment by Picoti** [comment] 2018-09-24 11:51
OK thanks. I have read the #1716, and yes I understand now that the problem happens because the "The runtime processes behaviors in order of object creation".
In my case the chain was important because I wanted to make one element follow and rotate on the second following the base of the hierarchy. I feel like it's a bit of the same process that BonzerKitten7 wanted to do. I will try an other way to do it.
Maybe it would be nice to say in the comments that appears when we clik on the PIN behaviour to mention this particularity concerning the chains (order of object creation) ?
I wish you all the best.
