### ISSUE TITLE
Error closing after open a old downloadable project from c3.net

### ISSUE THREAD

**Issue by sielxm3d** [Scirra/Construct-3-bugs#261] opened 2017-05-19 00:34 UTC
Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'catch' of undefined @ TypeError: Cannot read property 'catch' of undefined at Sa (https://editor.construct.net/r29/cloud/sandbox.js:1:32469) at Wa (https://editor.construct.net/r29/cloud/sandbox.js:1:32958) at Za.eb.keys.then.gb (https://editor.construct.net/r29/cloud/sandbox.js:1:33324) at 
Stack: TypeError: Cannot read property 'catch' of undefined at Sa (https://editor.construct.net/r29/cloud/sandbox.js:1:32469) at Wa (https://editor.construct.net/r29/cloud/sandbox.js:1:32958) at Za.eb.keys.then.gb (https://editor.construct.net/r29/cloud/sandbox.js:1:33324) at 
Construct 3 version: r29
URL: https://editor.construct.net/index.html
Date: Thu May 18 2017 21:25:41 GMT-0300 (Hora oficial do Brasil)
Uptime: 60.7 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce 8400GS Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

I have a project working fine in last hour,  but after open then this project close alone.
The cloud saved file is not showing the saved files.
The drag and drop file and the local file saved, crash too.

**Comment by AshleyScirra** [comment] 2017-05-19 10:44
Looks like dupe of #251 so closing. Please always follow the bug report guidelines to ensure we can resolve the problem.

**Closed by AshleyScirra** 2017-05-19 10:44 UTC
