### ISSUE TITLE
XCode Swift compiler error 'GoogleMobileAds'

### ISSUE THREAD

**Issue by TheEndType1** [Scirra/Construct-3-bugs#3143] opened 2019-07-16 18:35 UTC
## Problem description

I have been trying to build iOS package to upload it to the appstore, however, during the process building in XCode Version 10.2.1 (macOS: Mojave 10.14.5) I receive a Swift compiler error related to 'GoogleMobileAds' and I cannot continue the process to "Archive" the build and upload.

This does not happen when I'm using XCode version 9.2 (macOS: Sierra 10.12.6) which is an old VM which I use to upload C2 builds. In this version I can build and even run the simulator and get my .IPA file. However, seems apple has set up some requirements that new builds must be uploaded in a latest XCode version so I cannot upload the resultant .IPA file.

So between the exporting process nothing changes, and do the same steps to open only .xcworkspace  in both XCode versions. 

The project includes all Admob settings iOS App ID, publisher, 
and tried both "Nowhere and EU and Unkown" and set up normally.

Please find .c3p file so you can directly just export the game and to the steps to reproduce the issue.

https://drive.google.com/open?id=13iuWPVIRbMsDrA97fLZ4hzvObWSQIRHy

# Attach a .c3p

## Steps to reproduce

Using XCode 10.2.1
1. Export iOS build in C3 -> XCode project
2. Open  .xcworkspace file in XCode (Add dev certificates)
3. "Play" to start simulator and build the app (iPhone X or fewer)
4. When XCode is building it shows up the error.

Using XCode 9.2
1. Export iOS build in C3 -> XCode project
2. Open  .xcworkspace file in XCode (Add dev certificates)
3. "Play" to start simulator and build the app (iPhone X or fewer)
4.  Build succeeds 
5. Stop simulator
7. Change the value of device to "Generic iOS device"
8. Archive 
9. Obtain resultant .IPA file

## Observed result

Seems in newest XCode version there is an issue with 'GoogleMobileAds'.  Build fails and shows up the error attached on the screenshot
## Expected result

Successfully build and obtain and upload resultant .IPA file
## More details

The problem is only with iOS XCode build. Android works fine (Ads, IAP and other stuff)

**Affected browsers/platforms:** 

iOS

**First affected release:** 
Happens on R157 stable version
## System details

<details><summary>View details</summary>

![XCODE ERROR](https://user-images.githubusercontent.com/52974130/61319758-1d17b680-a7c5-11e9-8ab3-b082f237385e.png)

</details>

**Comment by shortercode** [comment] 2019-07-17 10:48
We've seen this issue a few times before, it's normally related to the symbolic links in the framework being resolved to actual files. Visibly your project looks pretty much identical, except it won't compile.

If you look for the files mentioned in the error ( GADAdSize.h, GADAdNetworkExtras.h, etc. ) you should find 2 copies of each. One should be a symlink to the other. If something has resolved the symlink then both will appear as a normal file. In finder symlinks will have a small black arrow over the file icon.

**Comment by TheEndType1** [comment] 2019-07-17 17:38
[GoogleMobileAds.zip](https://github.com/Scirra/Construct-3-bugs/files/3403102/GoogleMobileAds.zip)
I'm sharing the current folder where those file are,

**Comment by shortercode** [comment] 2019-07-17 17:50
Well those files were obviously once symlinks, but they have been corrupted at some point.

When you do a build do you unzip/rezip move the project between computers?

**Comment by TheEndType1** [comment] 2019-07-17 17:53
I export from C3 from Windows, and then unzip just to replace game icons and splashscreen and then zip again and send to the macOS and unzip it there and open in XCode (This proces was done in both XCode versions)

**Comment by shortercode** [comment] 2019-07-17 17:54
That will corrupt your project unfortunately. Windows does not support macOS style symlinks, so unzipping them on windows will break them.

**Comment by TheEndType1** [comment] 2019-07-17 17:55
Ok, let me export again and unzip it only in macOS and load it again in XCode. Will be back with the result, going to try that

**Comment by shortercode** [comment] 2019-07-17 17:59
You might be able to use a tool like 7 zip to edit the archive without unzipping it. I'm not sure if it will leave the symlinks intact on windows or not.

When your looking at the files in finder you can tell if they are symlinks or not by checking for a small black arrow over the file icon, like I have highlighted in the picture below.

![InkedScreenshot 2019-07-17 at 18 48 01_LI](https://user-images.githubusercontent.com/9051865/61398869-d1e4cd00-a8c4-11e9-96ad-91973600d739.jpg)

**Comment by TheEndType1** [comment] 2019-07-17 18:01
Got it, will check that, and I'll be back

**Comment by shortercode** [comment] 2019-07-18 11:36
From the sounds of it this is just down to unpacking the zip file on the wrong platform. My own tests show that the server is outputting a working project, and that the default mac client is able to unpack it without corrupting it.

Feel free to mention it if you are still having a problem, but I'm going to close this as not a bug.

**Closed by shortercode** 2019-07-18 11:36 UTC
Labels: iOS

**Comment by AshleyScirra** [comment] 2019-07-18 11:40
@shortercode - maybe the export dialog should warn people not to extract an Xcode zip on Windows if it will break it.

**Comment by TheEndType1** [comment] 2019-07-18 17:02
It worked, and yes would be good to know because this was not even in the normal iOS guide provided by C3, so would be good to know! Thanks! Going to continue with the process.

**Comment by AshleyScirra** [comment] 2019-07-19 10:43
I don't know if @shortercode just edited it in but the tutorial [iOS application development and publishing with Xcode](https://www.construct.net/en/tutorials/ios-application-development-and-publishing-with-xcode-25) does include this warning:

> Depending on what plugins you have used your xcode project may include a type of file called "symbolic links" or "symlinks" for short. These are kind of like shortcuts; when a program tries to open them the symlink will redirect it to a different file in the project.
> 
> Windows doesn't understand macOS symlinks, so if you unzip the project on a Windows machine the files will be broken and you won't be able to build your project. So you should always unzip the project on the macOS system you intend to build it on.

**Comment by shortercode** [comment] 2019-07-19 13:58
I haven't updated that tutorial for quite some time, it's been a known
issue for a long time which is why it's in the iOS development tutorial.

It might help if we add it into the Mobile Advert manual page, as it's
currently the only plugin that requires it. As well as a warning in the
export complete dialog for iOS
