### ISSUE TITLE
Anchor Behavior puts sprites outside the layout

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#1827] opened 2018-07-23 03:25 UTC
## Problem description

With a project with "Orientations" set to landscape, and a sprite anchored to the bottom right side of the screen, and a device with orientation locked to portrait, the game sometimes puts the sprite into the location it should have been if the orientation was set to landscape  while forcing the game into Portrait so the UI completely dissapears, but this only has happened on one device out of 4 I tested.
## Attach a .c3p

https://puu.sh/B1sVf/dcccd2510a.c3p

## Steps to reproduce

1.Remote preview the project on a bunch of devices with the device locked in portrait mode
2. tap the screen to trigger a request full-screen
3. the purple sprite disappears

## Observed result

The purple sprite disappears

## Expected result

the purple sprite to stay on the screen

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>
samsung s7
chrome 67
android 8.0
c2 runtime
</details>

**Comment by AshleyScirra** [comment] 2018-07-23 11:01
Can't reproduce on a HTC 10 running Android 8. Remote previewed on the device, tapped the screen and it went in to landscape fullscreen mode with the sprite still in the bottom-right corner. Can you find a way to more reliably reproduce the problem?

**Comment by SnipG** [comment] 2018-07-23 11:46
The whole anchor behavior is strange and act different in C2 and C3.
[BuggyAnchor.zip](https://github.com/Scirra/Construct-3-bugs/files/2219122/BuggyAnchor.zip)
"There is one other strange behavior to during this test - so not sure if to file seperate bug report"
Anyway:
1.Open example, go preview, tap to full screen, esc to exit - nothing happens
2.Switch C3 runtime, preview, tap to full screen, esc to exit - durning exit sprites changes!!
3.Remote preview with C3 runtime, tap to fullscreen , back to exit - no sprite changes.
4. Switch C2 runtime, remote preview. Tap to fullscreen - Strange white edge appears left side, like background sprite gets resized. + no anchor sprite resize. Like it does on C3 runtime brower.

**Comment by AshleyScirra** [comment] 2018-07-23 11:51
@SnipG - this report does not mention anything different about the C3 runtime. Anything specific to the C3 runtime would be a different issue, so please file that as a separate issue.

**Comment by eleanorawesome** [comment] 2018-07-24 05:42
I'm sorry i'm not able to reproduce it it just happens to some players consistently making it unplayable to them only Ì wish I knew why so I could fix it

**Comment by AshleyScirra** [comment] 2018-07-24 11:32
Sorry, I'm afraid there's little we can do unless we have a reliable way to reproduce the issue. Closing, please file again if you find a way to do this.

**Closed by AshleyScirra** 2018-07-24 11:32 UTC
Labels: can't reproduce
