### ISSUE TITLE
Multiplayer not working with release/signed Compiling in C3

### ISSUE THREAD

**Issue by shubhamrathi9** [Scirra/Construct-3-bugs#2710] opened 2019-03-09 21:46 UTC
## Problem description

Multiplayer object does not connects to server when we compile the game with release or signed apk option in construct 3 compiler (while it works fine in preview or compiling as debug apk)

## Attach a .c3p

i am using the "multiplayer chat example" file that comes with construct 3 examples to show that when i preview it or compile it as debug apk, it works but it shows signalling error when i compile it as release/signed apk   
Here is the link to c3p file 
https://drive.google.com/file/d/1iz4sKJba20DcrgP9OEfYb24GQcaifet0/view?usp=drivesdk

## Steps to reproduce

1.Just open the file, preview it to see it works fine
2.now export it under android - signed release apk - with a key (create it with c3 or using any other key will work ) 
3.open the compiled apk file in an android device - install- run
4.enter name and hit enter- signalling error will be displayed

## Observed result

Signaling error will be displayed showing multiplayer not working (that worked fine in preview or as debug apk)

## Expected result

Signalling should connect to the server

## More details

as i said before multiplayer works fine in preview or as compled debug apk but not as released/signed apk

it works fine in all browser for preview but not as release/signed apk compiled with c3 compiler

**Affected browsers/platforms:** 

**First affected release:** 
i am using r136, although it was working before but not now

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Android
Operating system version: 9
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2.625
Logical CPU cores: 8
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Linux; Android 9; Nokia 6.1 Plus Build/PPR1.180610.011) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Mobile Safari/537.36
C3 release: r136 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 3.3 gb
Storage usage (approx): 63 mb (1.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2 is currently disabled on Android due to reports of GPU driver bugs.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Qualcomm
Renderer: Adreno (TM) 509
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-03-10 12:46
The Multiplayer code is identical no matter the build type. I suspect this is a configuration issue with a release APK - maybe it needs to whitelist the signalling server.

**Comment by shubhamrathi9** [comment] 2019-03-10 13:34
Thanks for taking a notice of this,
I dont know how to whitelist it, can you please tell me, is that a problem on my end or scirra is going to take care of it?

**Comment by AshleyScirra** [comment] 2019-03-11 10:04
Try adding wss://* to the URL whitelist on export.

**Comment by shubhamrathi9** [comment] 2019-03-11 14:44
I tried that but still same result!
I added wss://* once and once i tried adding wss://*/*, but apk still shows signalling error!
Also if it was this problem it might not have worked in past too, but as i told it used to work a few days back but not now!
Please fix it!

**Comment by shortercode** [comment] 2019-03-13 12:11
Hi @shubhamrathi9 this sounds quite difficult to debug if the issue only occurs in release builds, are you using minification in your export by any chance?

Could you check an older release which you know works? It would be good to know if the problem is related to a change in runtime code or something else.

**Comment by kingpirux** [comment] 2019-03-13 17:58
im using signed release and there is no problem and no other configuration needed.

**Comment by shubhamrathi9** [comment] 2019-03-18 20:31
@shortercode no i am not using minifying script
@kingpirux i exported today with new release, still not working for me after export ,please help!

**Comment by kingpirux** [comment] 2019-03-18 23:26
did you try to open the aplication in your phone with a chrome window?

**Comment by kingpirux** [comment] 2019-03-18 23:31
also, try to create a new keystore with 100 years of validity and check again

**Comment by shubhamrathi9** [comment] 2019-03-19 04:43
Created a keystore with 100 yr validity, still signed release apk wont work
I dont know how to open application in chrome, i have attached the link of the apk, can you try that on your end please...

**Comment by shubhamrathi9** [comment] 2019-03-20 11:12
Ashley please fix this, you can try the capx i exported... i think it confirms the bug...

**Comment by AshleyScirra** [comment] 2019-03-20 11:37
Please be patient. See the [Forum & Community guidelines](https://www.construct.net/en/forum/general/open-topic-33/forum-community-guidelines-141035).

**Comment by shubhamrathi9** [comment] 2019-03-24 18:21
Have been patient for over a week now, sorry if its still too early but multiplayer is still not working after export! can i at least ask if it is even registered as a bug and is being worked out or not? or how long do i have to wait?...

**Comment by kingpirux** [comment] 2019-03-24 23:57
> I dont know how to open application in chrome, i have attached the link of the apk, can you try that on your end please...

upload the app to you web hosting. and open it from there in your smartphone.

**Comment by AshleyScirra** [comment] 2019-03-25 10:32
@shubhamrathi9 - please be patient. We are a small team dealing with thousands of issues. As per the Forum & Community Guidelines, if you persistently nag staff, we may close the issue and stop working on it.

**Comment by shubhamrathi9** [comment] 2019-03-25 11:08
Ok!

**Comment by DavideGalilei** [comment] 2019-03-25 11:55
Multiplayer doesn't work for me in the remote preview either, but first it worked, I don't understand why it doesn't work anymore

**Comment by shubhamrathi9** [comment] 2019-03-25 12:07
@DavideGalilei 
Yeah its wiered, it stopped working unexpectedly for me too. I thought it was just me. Hope it gets fixed soon!

**Comment by AshleyScirra** [comment] 2019-03-25 12:08
@DavideGalilei - when I asked in that issue if the problem only related to release APKs, you appeared to indicate that was the case, therefore I closed it as a duplicate of this issue. If you have trouble with Remote Preview, that would be a different issue and should be filed separately. However I would point out that most of the time connection issues are due to the network configuration and not Construct.

**Comment by DavideGalilei** [comment] 2019-03-25 13:13
I have tried a lot of wifi, but it doesn't work on any, and i want to know why on mobile data multiplayer online doesn't work.
I had modified the answer while you were closing the topic, sorry if I didn't make it in time, but I'm using google translator and it takes me a while to write

**Comment by shubhamrathi9** [comment] 2019-03-25 13:23
Yeah i dont think its network config issue either, otherwise how come debug apk work and released not?(the apks i compiled last month still works fine) Also i have provided both apks, you can check it for yourself.

**Comment by DavideGalilei** [comment] 2019-03-25 13:43
I have tried debug apk, but also it doesn't work

**Comment by DavideGalilei** [comment] 2019-03-25 16:26
I want to say that multiplayer is not working on all platform

**Comment by AshleyScirra** [comment] 2019-03-25 18:43
Multiplayer is working fine for me. This issue pertains specifically to multiplayer not working in Android release APKs only. Please keep the discussion relevant only to that issue, or file a new issue following all the guidelines.

**Comment by DavideGalilei** [comment] 2019-03-25 18:51
But you have tested if it works on release apk?

**Comment by shubhamrathi9** [comment] 2019-03-27 13:37
@DavideGalilei 
What ashley said was...
This issue is for "Multiplayer not working in released apk".
So if multiplayer is not working for you in unreleased apk/remote preview/debug apk etc. Then you should file a new issue for that.

**Comment by shubhamrathi9** [comment] 2019-03-29 05:18
I noticed this issue is marked "need info", is their any more info that i need to provide?

**Comment by kingpirux** [comment] 2019-04-03 14:31
I think i found the problem: Scirra Signalling Server is SSH and last update on Chrome is rejecting crossdomain connections unsecure connections (ssh to not ssh or viceversa), ALL signed and unsigned apk's now are not SSH so the signaling server is not reached because the internal chrome is rejecting unsecure connections

**Comment by kingpirux** [comment] 2019-04-03 14:32
More info, i didnt notice this problem because i have my own signalling server with no ssh and it switchs between scirras and mine if that problem pop up.

**Comment by shubhamrathi9** [comment] 2019-04-03 15:44
What's the fix for this? Do i need to use old version of chrome or is it going to get fixed in construct update?

**Comment by kingpirux** [comment] 2019-04-03 16:52
i don't think this can be fixed by construct, since it's a chrome directive :P so the solution is to set up a signalling server or use a free one, try with mine (it is free, and it will help me to test stability of the server as well so use it as you wish) i send it to you in mp

**Comment by kingpirux** [comment] 2019-04-03 16:54
ws://ec2-18-223-3-159.us-east-2.compute.amazonaws.com:80 (this one also works with smartphone 3g and 4g) (please send me feedback if you found problems) its only open for this month so dont get used to it

**Comment by shubhamrathi9** [comment] 2019-04-03 17:12
This doesn't make sense... Scirra server is a help for construct 2 developers like me to make multiplayer games easily and if it is not working for anyone then doesnt it make sense that scirra team should fix it....?  Otherwise whats the point of having scirra server free for all users?
@Ashley i dont mean to disturb you but its a humble request to please do something about this, i dont know how to set up a server (i read in a post that scirra server handles a lot of stuff required for construct games that otherwise would be difficult to do) and you know many construct developers must be relying on scirra server too. so again its a request, please do something to comply with chrome (if thats the case)

@kingpirux thanks for the link but i need something to rely on for a longer time but thanks again for pointing out the chrome thing. I hope construct can fix this somehow (fingers crossed).

**Comment by kingpirux** [comment] 2019-04-03 17:18
Dude, everytime when you export the game it says PLEASE USE HTTPS, yo CAN enable ssh in your game, you only need to configure it in google play (uploading keys and stuff), but it's not free (you need to buy it), is not ashley's fault.

**Comment by shubhamrathi9** [comment] 2019-04-03 17:30
Sorry if what i said relfected me blaming anyone, to be clear i am not saying its anyones fault but that there must be a way to fix it on constructs end so that users can use scirra server in their games easily, thats it!
If thats not possible then m screwed! But can you tell more about how can i configure it in google play with keys etc and what would i need to spend money on?

**Comment by kingpirux** [comment] 2019-04-03 17:37
can you please test if this signallign works to you first?

**Comment by shubhamrathi9** [comment] 2019-04-03 17:38
Ok i will let you know!

**Comment by AshleyScirra** [comment] 2019-04-03 17:50
Unfortunately some issues are not feasible for us to fix ourselves. This should be obvious: clearly we cannot fix problems in Android itself, for example - that's Google's responsibility. Please note that demanding infeasible solutions is [specifically against the Forum & Community guidelines](https://www.construct.net/en/forum/general/open-topic-33/forum-community-guidelines-141035) so if a developer tells you it's not feasible to be fixed on our end, you should believe them.

According to this thread it still works in debug APKs, which suggests the security restriction is not implemented there, which would be an odd setup. I would suggest filing this at crbug.com to follow up with Google.

**Comment by shubhamrathi9** [comment] 2019-04-14 09:43
sorry for late reply,
Can someone post this bug at crbug.com as ashley suggested, i would do it myself but I did not understand the technicality of what the bug really is...
Thank you

**Comment by kingpirux** [comment] 2019-04-17 18:34
> 
> 
> sorry for late reply,
> Can someone post this bug at crbug.com as ashley suggested, i would do it myself but I did not understand the technicality of what the bug really is...
> Thank you
I can help you but first need information with:
1º did you test with my signalling server running from your hosting?
2º did you test with my signalling server running form the apk?
3º did you test with other phones (not virtual phones, real ones)?
4º did you test other similar projects?

**Comment by shubhamrathi9** [comment] 2019-04-17 18:40
Hi,
1- i dont know how to do that
2- i tried it in my game (put ur url insted of scirra) but it did not worked at my end
3 & 4 is a no.

**Comment by kingpirux** [comment] 2019-04-18 13:28
then it seems that your problem is something wrong in your code. Lets continue this in a forum or group of your choice, im in facebook "Construct 2 + 3" and "construct 2&3"  and ill try to help you with the multiplayer trouble.

**Comment by shubhamrathi9** [comment] 2019-04-19 15:27
multiplayer works great with scirra server in debug apk so there is not a problem in the code. but i do need a server like scirra server where i do not need to code the server and which is free

**Comment by kingpirux** [comment] 2019-04-22 15:28
Im using multiplayer with no problems. So lets close this:
IT'S TRUE that since the new european and USA security laws on everything in the internet, there are a lot of troubles with this, @AshleyScirra  you should give for free the signalling server files or open a non ssh sigserver, so you can release this kind of troubles to the developer and not to you or google or what ever security laws pop out in the future. Also it looks like you dont want to be resposable for attending questions on installing turn servers and all that, so let it be and let them take care of that :P (besides if they actually are going to do a multiplayer, means they already paid for the engine) i dont see why it comes separated.

**Comment by kingpirux** [comment] 2019-04-22 15:30
AND im going to do a tutorial on how to open a turn server and installing the signalling server for free using amazon aws :) :+1:

**Comment by shubhamrathi9** [comment] 2019-04-22 16:03
Thanks for doing the tutorial in advance :)
Although scirra should provide a proper working server for its multiplayer users (a server that works with signed apk)

**Comment by AshleyScirra** [comment] 2019-04-23 09:54
This is nothing to do with security laws nor anything to do with our own signaling server. It's to do with an Android app being classed as insecure (e.g. HTTP rather than HTTPS) which now by default blocks secure connections. @shortercode could you file an issue with Google on this and follow up there?

**Comment by shubhamrathi9** [comment] 2019-04-28 13:21
Can someone please file this issue like ashley said and share its link here so that we can follow it there...?
Thank you in advance!

**Comment by kingpirux** [comment] 2019-04-28 16:13
@AshleyScirra  according to this https://developer.android.com/training/articles/security-config is the way the app is exported.

**Comment by shubhamrathi9** [comment] 2019-05-06 06:51
> @AshleyScirra @shortercode i can help with the issue in google, but first i will need to ask if this steeps are all covered:
> 1º according to this https://developer.android.com/training/articles/security-config is the way the app is exported.
> 2º And mainly looks like this https://developer.android.com/training/articles/security-ssl
> 3º i also found this that might help: https://android-developers.googleblog.com/2017/06/whats-new-in-webview-security.html
no one from scirra cares that much about this issue i guess.
@kingpirux can you please please post a bug on chrome for this, it may get fixed sometime soon.

**Comment by AshleyScirra** [comment] 2019-05-06 12:14
We're a small team dealing with thousands of issues. We have already invested some effort in helping resolve this issue. Please see the [Forum & Community guidelines](https://www.construct.net/en/forum/general/open-topic-33/forum-community-guidelines-141035) regarding conducting discussions in bad faith. Please take note if you want us to continue co-operating on this issue.

> Accusing people of ignoring you or not caring, after they have tried to help

**Comment by shubhamrathi9** [comment] 2019-05-06 16:37
@kingpirux was offering to solve the problem a week ago and he just asked for some information, still no one replies for 8 days i think thats ignoring, 
Although I understand the rules and will not say that again. This may be a minor issue for the team but i did a whole game worth of work that doesnt work anymore because of this issue. And i am not even being impatient, its been 2 months since i posted. It would have been really nice if someone have answered kingpirux or just posted a bug at chrome. No offense. Love c3.

**Comment by AshleyScirra** [comment] 2019-05-06 16:56
Those were just links to miscellaneous parts of Android documentation. It is not clear if or how they are related to this problem so it is difficult to offer any meaningful response.

**Comment by shubhamrathi9** [comment] 2019-05-07 05:49
I tried posting a bug on crbug for what kingpirux suggested but i dont know how to reproduce that bug,
if someone visiting this forum have knowledge of posting a bug for this on crbug.com then i request you to please file a bug there for this issue :
> I think i found the problem: Scirra Signalling Server is SSH and last update on Chrome is rejecting crossdomain connections unsecure connections (ssh to not ssh or viceversa), ALL signed and unsigned apk's now are not SSH so the signaling server is not reached because the internal chrome is rejecting unsecure connections

i will be very thankful for this, also don't forget to share the link here.

**Comment by shortercode** [comment] 2019-05-09 17:37
I've confirmed the issue here, connections to the signalling server ( over websocket ) are failing in release exports. Working on a minimal reproduction now to submit to crbug.

**Comment by shortercode** [comment] 2019-05-09 19:12
I have been unable to create a minimal example this evening, although I'm not sure why. I have been somewhat hindered by Android studio and Play protect though. The requirement seems to be that the APK cannot be debuggable, disabling that flag in Android studio triggers the issue even on unsigned non-release builds. Although the difference between a release and debug is likely somewhat minimal with that flag disabled.

I have filed a bug report using the multiplayer chat example, and hopefully they can shed some light on the issue.

https://bugs.chromium.org/p/chromium/issues/detail?id=961393&q=webrtc%20webview&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by shubhamrathi9** [comment] 2019-05-09 19:28
Thanks a lot for ur efforts @shortercode 
I desperately hope that it get fixed soon by chrome.

**Comment by shortercode** [comment] 2019-05-10 09:04
I'll keep any eye, hopefully they can suggest a workaround so we can resolve the problem faster.

**Comment by AshleyScirra** [comment] 2019-05-10 11:58
Closing this issue as we will follow up at crbug.com/961393

**Comment by eonianvr** [comment] 2019-05-11 02:09
just saw an issue was opened. What a freaking bad timing! I just signed an apk to test a chat app and now it ruined my weekend!
Shanks Shortcode for taking action on it to the full extend!

**Comment by MehrshadFarahani** [comment] 2019-05-20 08:00
@AshleyScirra Could u take a look at crbug.com/961393 ? seems they need some information .

**Comment by AXLLLOW** [comment] 2019-06-12 09:21
I read crbug.com/961393. But there is no solution so far. There is a solution ?

**Comment by shubhamrathi9** [comment] 2019-06-13 07:48
This is what bug report at chrome concludes....
We need to fix this on scirra's end

Report....crbug.com/961393
Status: WontFix (was: Untriaged) 

This is WontFix/WorkingAsIntended.

The server, multiplayer.scirra.com, is only sending the leaf certificate. As a consequence, Android is unable to build a certificate chain to a trusted CA. Configuring the server correctly, which involves sending the expected intermediates, will resolve this problem. Working with the CA involved (Sectigo, in this case)  can help provide steps.

The variation between Debug and Release is that the Android manifest allows app developers to configure how CAs are trusted, and likely explains that variation.

**Comment by AshleyScirra** [comment] 2019-06-13 11:24
This still doesn't explain why it works in Chrome. I commented on the issue to ask about that.

**Comment by AshleyScirra** [comment] 2019-06-13 16:54
Well, it turns out the webview has different mechanisms for verifying the security chain, and that ends up meaning the signalling server's certificate is accepted by Chrome but not the webview. Ugh. I guess we will have to reconfigure the signalling server certificate, assigning to me to figure that out...

**Comment by kingpirux** [comment] 2019-06-13 17:23
just to add more headache to ashley :P multiplayer is not working at all in android 9, maybe related to that certificate permission but is weird because it works fine in 8.1 and less.

**Comment by kingpirux** [comment] 2019-06-13 18:32
@AshleyScirra i found a solution changing configuration of the CA in the android export, i was looking for android 9 but maybe this works with all versions: https://medium.com/@bouffard.jul/build-an-android-app-using-a-non-secure-api-in-android-9-88c9bafbc12

**Comment by kingpirux** [comment] 2019-06-13 20:14
> 
> 
> @AshleyScirra i found a solution changing configuration of the CA in the android export, i was looking for android 9 but maybe this works with all versions: https://medium.com/@bouffard.jul/build-an-android-app-using-a-non-secure-api-in-android-9-88c9bafbc12
> TESTED AND WORKS FINE WITH NOKIA 9 (Android 9)

works with android 6 and android 8 as well !

**Comment by eonianvr** [comment] 2019-06-14 20:31
Was  the signaling server updated with a fix? Since it is not linked to a new release of construct, how will we know when it works again?

**Comment by shubhamrathi9** [comment] 2019-06-17 09:31
> Was the signaling server updated with a fix? Since it is not linked to a new release of construct, how will we know when it works again?

I am hoping for @AshleyScirra to ask us to check if it is fixed and close this bug  asap!

**Comment by AshleyScirra** [comment] 2019-06-17 16:08
OK, we've updated the SSL configuration on the signalling server, and according to our testing with a release APK it works now. Can anyone else confirm it is also working on their end?

**Comment by DavideGalilei** [comment] 2019-06-17 17:27
yes, multiplayer works better than before, now also online

**Comment by eonianvr** [comment] 2019-06-17 18:09
confirming too that it works inside an signed  app (android tested)!

**Comment by shubhamrathi9** [comment] 2019-06-17 20:34
Working fine! Thank you.

**Comment by kingpirux** [comment] 2019-06-17 23:12
in deed working as charm :)

**Comment by AshleyScirra** [comment] 2019-06-18 09:10
Thanks for confirming all, and sorry for the inconvenience. Closing!

**Closed by AshleyScirra** 2019-06-18 09:10 UTC
Labels: Android, need info
