### ISSUE TITLE
Mobile IAP Purchase not triggering. C3 Runtime IOS

### ISSUE THREAD

**Issue by sjrya** [Scirra/Construct-3-bugs#2279] opened 2018-11-08 12:55 UTC
## Problem description

I'm using the C3 Mobile IAP plugin. The products register fine but won't trigger the purchase action.

Export from C3 (124) using xcode project. Testing on live device via USB and tried using both Dev/Dis profiles and get the same result.

Tried removing plugin and just testing with 1 simple IAP but still no luck. 

These IAP are live and I have used them successfully before within a Sandbox environment & store.

Using iOS 12.1

## Attach a .c3p

Can't attach .c3p right now. Can tomorrow if needed.

## Steps to reproduce

1. Add IAP plugin
2. Export Xcode 
3.

## Observed result

Xcode builds the project fine but IAP doesn't function properly. 

## Expected result

IAP to work

## System details

I checked the Xcode output log and I'm getting the following error:

<details><summary>Xcode Error</summary>

InAppPurchase[objc] (before init): WARNING: Your app should be single page to use in-app-purchases. onReset is not supported.

</details>

After further investigation using the Safari javascript debugger, I can see this error:

<details><summary>Safari Debugger</summary>

function deferThrow(err) { setTimeout(function() { throw err; }, 1); }

TypeError: this._Post is not a function. (In 'this._Post("product-available",a)', 'this._Post' is undefined)

</details>

I'm also seeing another error that i'm unsure if is related:

<details><summary>Additional Error</summary>

ERROR: Rejection from 'runtime' handler 'cordova-fetch-local-file': [object Object]

</details>

**Comment by WanKIpas** [comment] 2018-11-18 05:19
i have the same prob, it just won't trigger the purchase action..

**Comment by shortercode** [comment] 2018-11-28 16:41
Merging this issue with the other MobileIAP c3runtime issues, please refer to other issue for status.

Closing as duplicate of #2057

**Closed by shortercode** 2018-11-28 16:41 UTC
Labels: c3runtime, iOS
