### ISSUE TITLE
Mouse split panel cursor appears in wrong position

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#525] opened 2017-06-16 17:44 UTC
## Problem description

I've noticed this in the default theme a lot but didn't had time to try reproducing it. 

## Attach a .c3p

[Abilities System.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1081547/Abilities.System.c3p.zip)
![mousesplitpanel](https://user-images.githubusercontent.com/7268697/27238143-7a0529ec-52d4-11e7-8d52-2bf6ffd1ccb6.gif)

## Steps to reproduce

1. Open the project
2. Move your mouse cursor like in the gif

## Observed result

The mouse cursor changes to Split Panel icon when not overlapping the line. It can also be used then.

## Expected result

I expect the icon to change for the splitting to work when the mouse is overlapping the line.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by JeFawk** [comment] 2017-06-16 17:45
In my main project the offset was extremely big, but then again I had way more events and groups.

**Comment by AshleyScirra** [comment] 2017-06-20 16:07
May be related to #523 since some of the horizontal widths seem off.

**Comment by JeFawk** [comment] 2017-06-20 16:20
This does happen in the default theme as well.

**Comment by Animmaniac** [comment] 2017-07-06 17:05
It should be fixed in the dark theme released with R44.

@JeFawk Couldn't reproduce the problem in the default theme, it works as expected for me.

**Comment by JeFawk** [comment] 2017-07-07 00:45
Seems that when there are events in groups and the event hierarchy is >= 4 (event inside event inside evvent etc) this problem appears.

![image](https://user-images.githubusercontent.com/7268697/27938389-8567ad44-62c6-11e7-8a8a-09175fe07ef7.png)
![image](https://user-images.githubusercontent.com/7268697/27938410-9834ac92-62c6-11e7-89cf-ca28d59fa7f8.png)
![image](https://user-images.githubusercontent.com/7268697/27938425-a686a4ee-62c6-11e7-8d62-d944f03ae4d7.png)

**Comment by AshleyScirra** [comment] 2017-07-07 12:43
Note this may be related to #427 where there's sometimes basically a lag on the mouse cursor changing, even though the hit detection is correct.

**Comment by Animmaniac** [comment] 2017-07-07 12:51
I was unable to reproduce it. Even changing the zoom level it works properly on my machine:

![condition-split-bug-a01](https://user-images.githubusercontent.com/29487913/27955060-cc4f8030-630a-11e7-8530-111af1312c79.jpg)

I only noticed some small offset when browser's font-size is set to 'small', but just for the split areas on the far right of the event sheet. Probably some accumulated error due to different margins/paddings and stuff, but is not as bad your screenshots.

**Comment by JeFawk** [comment] 2017-07-07 15:17
I'll try to reproduce it and upload a project next week then.

**Comment by shortercode** [comment] 2018-01-10 12:24
@JeFawk what was the status on this bug? Looking through some old issues to see if we can close them.

**Comment by JeFawk** [comment] 2018-01-10 13:38
@shortercode I'll check in the next days

**Comment by JeFawk** [comment] 2018-01-11 01:32
![image](https://user-images.githubusercontent.com/7268697/34804199-f62b9048-f67f-11e7-957f-c53439d41163.png)

I'll post more as i find them but i'm working on a very light project right now and these things happened with a lot of subevents and subgroups

**Comment by JeFawk** [comment] 2018-01-15 00:39
Can't get it to reproduce anymore.

**Comment by JeFawk** [comment] 2018-01-16 20:04
![image](https://user-images.githubusercontent.com/7268697/35009594-aef5cd96-fb08-11e7-9858-e0ed3759441d.png)

![image](https://user-images.githubusercontent.com/7268697/35009599-b4d622a6-fb08-11e7-8864-e89fa81277c2.png)

I do have events looking like this but I can't reproduce it in a standalone project right now. I'll try more in the following days

![image](https://user-images.githubusercontent.com/7268697/35009750-33562aa4-fb09-11e7-872e-e9e8f339fd71.png)

**Comment by shortercode** [comment] 2018-01-18 13:06
Well I guess that means it's still lingering, keep me up to date if you do find a solid way to reproduce this

**Comment by JeFawk** [comment] 2018-01-18 17:53
Will do, i'm sick of this bug

**Comment by AshleyScirra** [comment] 2018-01-18 18:02
Just checking, you don't happen to have dev tools open when you see this? We've spotted a bug where cursors don't change correctly but only when dev tools is open, otherwise as far as we can see it works OK.

**Comment by shortercode** [comment] 2018-01-18 18:07
Yeah I think we'd all like to see the back of it!

You know I completely forgot about that dev tools bug, that was a really weird discovery...

**Comment by JeFawk** [comment] 2018-01-18 20:15
Hmm I always have dev tools opened somewhere, usually on a game instance. Does it matter or must it be the dev tools opened for the editor? Maybe even docked?

**Comment by NetOneGames** [comment] 2018-01-30 14:34
Just stopping by and saw this.  But yes these and other misalignment issues till persist for me. I put a video on the forum before Christmas. i have been meaning to raise. Will post the video here when I get home.

**Comment by AshleyScirra** [comment] 2019-01-17 16:11
I could reproduce a slight offset in hit testing when the event sheet view is in a floating window. It turned out it wasn't taking in to account the size of the left border of the floating pane. This should be fixed in the next release. Closing - given the age of this issue and the fact there appears to be some confusion around precisely what the issue is and how to reproduce it, I think it would be best to file a new issue if there is still anything wrong after the next release.

**Closed by AshleyScirra** 2019-01-17 16:11 UTC
Labels: difficult
