### ISSUE TITLE
Sorting of project files

### ISSUE THREAD

**Issue by Queueon** [Scirra/Construct-3-bugs#4511] opened 2021-01-27 19:13 UTC
## In the project files window, the files are sorted alphabetical or numerical.
Meaning, for the Layouts the sorting is like this:
Layout1
Layout2
etc...
Layout9
Layout10
Layout11

But for other folders, for example the EventSheets:
EventSheet1
EventSheet10
EventSheet11
EventSheet12
EventSheet13
EventSheet14
EventSheet15
EventSheet16
EventSheet17
EventSheet18
EventSheet19
EventSheet2
EventSheet20
EventSheet21
etc..

## Attach a .c3p

Sorting.zip attached.
[Sorting.zip](https://github.com/Scirra/Construct-3-bugs/files/5882585/Sorting.zip)

## Steps to reproduce

1. Create multiple files ending with numbers.
2. Check how Construct is sorting those.

## Observed result

Sorting is not the same for each folder.

## Expected result

Sorting should be the same for each folder.

## More details

**Affected browsers/platforms:** 
Windows 10 / Chrome Browser

**First affected release:** Since Construct 2

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 88.0.4324.104
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
C3 release: r225 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 143 gb
Storage usage (approx): 488 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 610 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2021-01-28 10:57
Duplicate of #4408. It's [by design](https://github.com/Scirra/Construct-3-bugs/issues/4408#issuecomment-741804145).

**Closed by AshleyScirra** 2021-01-28 10:57 UTC
Labels: duplicate

**Comment by SnipG** [comment] 2021-01-28 13:52
Will add this here and not in 4408 issue!

If they are already sorted by something, alphabetically in this case, and user can sort them around by renaming them. Which even examples in C3 editor do! And that project bar is for visual use and visual selection, which should indicate user can visually reorder them for himself(can already do by renaming).
From that I would see no reason why user cannot drag them around istead and which should be the case.

But this is feature suggestion and issue starter should file that instead!
