### ISSUE TITLE
Sub-layers interaction bug

### ISSUE THREAD

**Issue by elfwy-uwu** [Scirra/Construct-3-bugs#5228] opened 2021-11-12 18:08 UTC
## Problem description

In edtior I am able to interact with sub-layers while its parent is invisible or locked

## Attach a .c3p

https://drive.google.com/file/d/1Uddw-5ZjxPgMPUKzgYuHyCiF1S38YsZm/view?usp=sharing

## Steps to reproduce

1. Hide Parent layer

## Observed result

Hieararchy is visible and objects selection is not locked while the whole sub-layer is invisible

## Expected result

Sublayers should inherit their state from parent layers

**First affected release:** r271

**Comment by AshleyScirra** [comment] 2021-11-17 12:25
Looks like a duplicate of #5207

**Closed by AshleyScirra** 2021-11-17 12:25 UTC
Labels: duplicate
