### ISSUE TITLE
sprite origin point does not undo (R123.2 C3 runtime)

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#2241] opened 2018-11-03 10:43 UTC
## Problem description

Sprites origin point does not undo when undo pressed even though a message appears saying its been undone and the sprite changing position on the layout.

## Attach a .c3p

n/a

## Steps to reproduce

Create a sprite, exit sprite editor, renter sprite editor, change the sprites origin point, exit sprite editor. Now press undo button.

## Observed result

Message appears saying 1 undo applied to sprite, and it shifts position in the layout, but when you click the sprite the origin point is unchanged.

## Expected result

origin point should be reset.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r123.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 62 gb
Storage usage (approx): 8.9 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: ATI Technologies Inc.
Renderer: ATI Radeon HD 5670 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by DiegoScirra** [comment] 2018-11-05 17:11
Can't reproduce this one with the steps given. Maybe there is something else to it?

**Comment by DiegoScirra** [comment] 2019-01-17 14:22
Haven't been able to reproduce this one yet. Closing it.

**Closed by DiegoScirra** 2019-01-17 14:22 UTC
Labels: can't reproduce
