### ISSUE TITLE
Whole games moves up/down when swiping. iOS11.3

### ISSUE THREAD

**Issue by Kraudi** [Scirra/Construct-3-bugs#1472] opened 2018-04-07 06:39 UTC
## Problem description

On iOS 11.3 (only tested with iPhone) whenever I swipe down, the whole game moves down (even menu items), and when I swipe up, everything moves. It is only a small pixels but it is really really annoying. It can be tested on my games "Coloristic"  & "Squirix" which can be found on the AppStore. Seems to me that it is iOS 11.3 only. I also have some customer reports since the 11.3 dropped.

## Steps to reproduce

1. Create a 1080p or 720p project.
2. Use Unbound Scolling on
3. Compile with xCode and test it on iOS 11.3 devices

## Observed result

The whole game moves some pixels up and down. Depends if you swipe up or down. Feels like a website you can scroll up/down. But as I said it is only some pixels.

## Expected result

The game shouldn't be scrollable up/down like it was <11.3
I can send the devs a promotional code for the appstore so you can check it out on my game. Just tell me so I can send  you one via email or so.!
Thanks.

**Comment by AshleyScirra** [comment] 2018-04-11 12:25
No project provided so tested Endless Runner template. Can't reproduce on an iPad Air 2 running iOS 11.3.

**Comment by Kraudi** [comment] 2018-04-11 12:51
I could send you a promo code for one my my games on the appstore. There you can see the problem. I don't know if that is iPhone specific problem but some customers all reported the issue on an iPhone. I also have it on both my games on my iPhone 7 Plus. Any way for a private message here where I could send you a promo code?

**Comment by AshleyScirra** [comment] 2018-04-11 13:37
Also tested on an iPhone 5S with iOS 11.3 and still can't reproduce with Endless Runner. I've seen another report of this type of issue on the forum so I suspect there is an issue here, but there is little we can do unless we can reproduce it ourselves.

I'm afraid sharing published apps is not generally helpful for bug reports since we need steps to reproduce the problem from scratch to investigate, published apps are deliberately obfuscated to prevent reverse-engineering, and including an entire project severely complicates investigation (see the bug report guidelines). So the best approach is to take a minimal project, or a basic template like Endless Runner, figure out how to reproduce the project from there, and share the .c3p file.

Are you using the Touch plugin in your project? If not, perhaps adding it will work around the problem, since by default it intercepts touch events and prevents the default action.

**Comment by Kraudi** [comment] 2018-04-11 13:54
Yeah I understand. And yes I'm using the Touch plugin in my projects. 

That's my project right now:
Window-Size: 720x1280
Layout-Size: 720x1280
Unbounded Scrolling: On
Scale mode: Scale outer
Viewport-fit: cover

I use the unbounded scrolling because my tiled background is 2x the size of the window/layout size because that way it scales perfectly on every iPhone/iPad. 

I only place my buttons manually like this:
On start of Layout -> Set btn_pause X: ViewportRight(0) - 80 and so on.

That's all the changes I made to the base HD template.
Could this anything to do with the unbounded scrolling?

**Comment by AshleyScirra** [comment] 2018-04-11 14:13
Test those settings with the Endless Runner template and see if the issue reproduces. If it does, that's your .c3p project to submit for a bug report.

**Comment by djjterror** [comment] 2018-04-16 10:11
When app was on iPhone device prior to iOS update... it was not affected with this issue when iOS was updated to 11.3
But when app was rebuilt and redistributed with just a minor change to version and bacisly everything was the same as before it get affected.

**Comment by Kraudi** [comment] 2018-04-16 12:04
What does that mean? It's on apple of can c3 team do anything?

**Comment by djjterror** [comment] 2018-04-16 15:48
@Kraudi
Please try to compile with cocoon and sign in xcode... do testflight and tell me does it still scrolls?

**Comment by cjpacewicz** [comment] 2018-04-16 23:16
I tested the infinite runner template over wifi in Safari and Chrome on an Ipad Air 1 with iOS 11.3. Can confirm the screen moves up and down while dragging. Bug appears on several other templates. Drag and drop type levels become unplayable with this bug. Projects prior to 11.3 did not have this issue.

**Comment by AshleyScirra** [comment] 2018-04-17 10:11
@cjpacewicz - I tried exactly that template and could not reproduce any issue. Can you describe exactly how you exported and built the app?

**Comment by cjpacewicz** [comment] 2018-04-17 19:49
I first noticed the issue on my published app which is installed on my Ipad. It started when I upgraded to 11.3. The game was built in Construct 2 and the ios app was created with phonegap. The same error appears on my browser demo(both safari and chrome on the ipad) which is exported as html 5. To recreate the error with the templates I am opening the template on my desktop and doing a wifi preview on the ipad. The browser demo is here; www.8bitconservatory.com.

**Comment by cjpacewicz** [comment] 2018-04-18 07:07
Has anyone tried adding <preference name="DisallowOverscroll" value="true"/> to the config.xml file as suggested by djjterror?

**Comment by cjpacewicz** [comment] 2018-04-18 18:39
I had success adding preference name="DisallowOverscroll" value="true" to config.xml as suggested by djjterror. I also added it to intelxdk.config.additions.xml. The window did not move while dragging. App tested was the development version of my published app installed with Xcode on Ipad Air 1 with 11.3.

**Comment by AshleyScirra** [comment] 2018-04-20 11:49
Construct already exports `<preference name="DisallowOverscroll" value="true" />` in config.xml. Only Construct 2 exports a file named intelxdk.config.additions.xml; this tracker is only for issues in Construct 3, so please only discuss things you have tried in Construct 3 on this tracker.

Is nobody able to find any steps to reproduce this issue? If not then there's not a lot we can do.

**Comment by AshleyScirra** [comment] 2018-04-25 14:04
Closing as the issue could not be reproduced and nobody seems to be mentioning the issue any more either here on the forum. It sounded like it could have been an issue with an old Cordova release and rebuilding apps fixes the problem, or something along those lines.

**Closed by AshleyScirra** 2018-04-25 14:04 UTC
Labels: can't reproduce, iOS
