### ISSUE TITLE
Preview stops working

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#5008] opened 2021-08-10 06:38 UTC
## Problem description

This is an old issue and I've seen many people mentioning it.
If you run the preview, then realize you forgot something and quickly close the preview window, there is a chance that preview will stop working. 

## Attach a .c3p

This happens with all projects and I am able to reproduce this with Kiwi Story template after a couple of attempts.

## Steps to reproduce

1. Open Kiwi Story and run the preview.
2. As soon as the preview window appears quickly press Alt-F4 to close it

## Observed result

After a few attempts, preview window does not open anymore.
Pressing F4, F5, Shift-F4 or clicking the preview icon on the toolbar has no effect and there are no errors in the console log.
The only way to fix it is to restart the editor.

The bigger the project, the easier is to hit this bug.

## More details

**Affected browsers/platforms:** was able to reproduce this in both Chrome and Firefox

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 85.0
Browser engine: Gecko
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0
C3 release: r251.2 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 87 mb (4.2%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by easyDoesItOK** [comment] 2021-08-20 11:22
Agreed, happens frequently with remote preview for me.

**Comment by AshleyScirra** [comment] 2021-08-31 11:52
Yeah, that's exactly what I was doing, and it never reproduced for me. I'm afraid there's little we can do without steps to reproduce that work for us. Perhaps there's something you can find that will reproduce the issue more reliably?

**Comment by dop2000** [comment] 2021-08-31 14:48
Your computer might too fast..
Please try this project: 
https://www.dropbox.com/s/h05xcufmo63trkc/LargeProj2.c3p?dl=0

Run this command in CMD:
`for /l %x in (1, 1, 1000) do  taskkill /FI "WINDOWTITLE eq Loading*"`

It will terminate any window with "Loading..." title as soon as it appears.
Run preview of that project several times. On my machine it stops working after a couple of tries.

If you still can't reproduce, try cloning the sprite in the project and duplicating the code a few times. I believe the bigger is the project (or the more events are there), the easier it is to break the preview.

**Comment by dop2000** [comment] 2021-08-31 14:51
Forgot to add - please open CMD as administrator.

**Comment by AshleyScirra** [comment] 2021-09-08 16:31
I could finally reproduce this using that CMD and spam-clicking the preview button as fast as possible. Eventually it got stuck.

I've added a bunch of extra checks and error handlers to the preview process which I think deals with this - I can't reproduce it any more. It's a tricky one to reproduce though, so I will wait for the next beta to come out and then ask you to see if it's fixed on your side too.

**Comment by AshleyScirra** [comment] 2021-09-14 13:39
r263 is now out and has improvements in this area, can you confirm if it works more reliably for you now?

**Comment by dop2000** [comment] 2021-09-14 13:54
Yes, it's fixed in r263, thank you!!!

**Comment by AshleyScirra** [comment] 2021-09-14 15:13
Thanks for confirming!

**Closed by AshleyScirra** 2021-09-14 15:13 UTC
Labels: need info
