### ISSUE TITLE
effects don't show with preview

### ISSUE THREAD

**Issue by vtrixdev** [Scirra/Construct-3-bugs#657] opened 2017-08-02 15:41 UTC
a quick report on v47

tested layer and object effects, it shows in the editor but not on preview

> add effect and preview

**Comment by AshleyScirra** [comment] 2017-08-02 15:54
Can't reproduce, works here. Closing, please always follow the bug report guidelines in full otherwise it's impossible to help.

**Closed by AshleyScirra** 2017-08-02 15:54 UTC

**Comment by vtrixdev** [comment] 2017-08-02 16:05
sorry, its a local issue, my gpu is not correctly detected
