### ISSUE TITLE
Greenworks Plugin - compatibility with NW.js

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#4717] opened 2021-04-08 06:06 UTC
## Problem description

I am about to release my game on Steam, but unfortunately my game doesn't work at all with the nw.js version needed by the greenworks plugin (v0.47). I reported that a while a go in #4245 , the Desktop export stopped working for a while but now in the newest version of nw.js (v0.52) everything works smooth and perfect, so that problem seems to be solved.

So if possible for you, it would be great if you could update the greenworks plugin to the newest NW.js Version, the previous version seems to be 2 years old.

## Steps to reproduce

1.problem from #4245 is solved in the newest nw.js version
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2021-04-08 10:56
v0.47 is about 8 months old, not 2 years old. We have an update scheduled to happen shortly. This is not a bug though, so closing.

**Closed by AshleyScirra** 2021-04-08 10:56 UTC

**Comment by bubbblebub** [comment] 2021-04-08 11:09
ok thanks for the answer, great there is coming an update! 

And sorry for my english, I meant if I have to use the version before v0.47 to make it work (v0.33), who seems to be quite old.

**Comment by AshleyScirra** [comment] 2021-04-08 11:48
I just updated the Greenworks plugin to 0.52.0: https://www.construct.net/en/make-games/addons/84/greenworks
