### ISSUE TITLE
Project doesn't start if LFJS plugin is used if Worker is set to yes

### ISSUE THREAD

**Issue by rraffo** [Scirra/Construct-3-bugs#6111] opened 2022-09-16 20:34 UTC
## Problem description
Any project doesn't start if the LFJS plugin is used and Worker is set to YES.
The issue appears starting from R310 version.

## Attach a .c3p
Attached is a sample using LFJS plugin using Worker.
[Particles - Behavior Flags - Elastic R309.zip](https://github.com/Scirra/Construct-3-bugs/files/9587065/Particles.-.Behavior.Flags.-.Elastic.R309.zip)

## Steps to reproduce
Open the attached file using the LFJS plugin and try to run it. 
If Worker mode is set to NO or AUTO the project start.
The problem has appeared since version R310.

## Observed result
The project doesn't start. A Blank screen appears.

## More details
debug show the following error:
![5rtq3QldnN](https://user-images.githubusercontent.com/58107632/190625900-805e149e-7af9-4724-a535-9ceebe5be44b.png)

The developer has not replied to anyone for one year. It looks like we do not have the possibility to keep in touch with the developer.

**Comment by Wackytoaster** [comment] 2022-09-19 18:20
If a 3rd party plugin is faulty it's up to the developer of that plugin to fix it. And if that developer is gone for whatever reason... That means you are out of luck. Just go with worker off.

**Comment by AshleyScirra** [comment] 2022-09-20 11:01
Duplicate of #6109. I'm afraid we are not responsible for third-party addons.

**Closed by AshleyScirra** 2022-09-20 11:01 UTC
Labels: duplicate
