### ISSUE TITLE
Exports with sounds fail to load on iOS devices

### ISSUE THREAD

**Issue by jakemay74** [Scirra/Construct-3-bugs#358] opened 2017-05-25 09:20 UTC
## Problem description

Adding audio to a project causes it to fail to load on iOS devices (tested on iPad2, iPad2 mini, iphone 5S)

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

Link to c3p:
https://www.dropbox.com/s/udv1rzzqkwrn99u/audiotest.c3p?dl=0

Export test:
audiotest.bitballoon.com

## Steps to reproduce

1. Create project
2. Add audio
3. Export project, deduplicating, recompressing and minifying
4. Upload to site
5. Test link on iOS device

## Observed result

Adding sounds appears to stop the export loading - it hangs on the C3 loading screen, retries a few times then fails.

This seems to be independent of using a loader layout - might be something to do with preloading sounds?

Maybe bitballoon specific? Haven't tried from other site.

## Expected result

Project runs normally.

*What did you expect to happen instead?*

Project downloads
## Affected browsers
 On iOS, works fine on Android/Desktop
* Chrome: yes
* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by jakemay74** [comment] 2017-05-25 09:26
UPDATE: Appears to be due to preloading sounds - when I turned that setting off it loads fine.  Haven't tried playing any sounds yet to see if that causes problems.

**Comment by jakemay74** [comment] 2017-05-26 12:05
Same issue on Nexus 5, using Chrome.   Works fine on Nexus 5X and my 5th gen Kindle Fire

**Comment by AshleyScirra** [comment] 2017-05-26 12:24
I can reproduce on an iPad 3 running iOS 9, but Safari is completely reloading the page with a message at the top that says there was a problem with the page. So it looks like Safari is crashing. I'd guess it's due to hitting the Opus decoder a lot on startup as it preloads all the sounds. None of them are very big, but I guess ffmpeg has a big overhead itself.

Assigning to Iain; not sure if there's anything that can be done about this, maybe it needs throttling to prevent overloading Safari? If it doesn't happen on iOS 10 it might just be a Safari bug that Apple already fixed.

**Comment by shortercode** [comment] 2017-05-26 13:44
Sounds unpleasant... I'll try poking around a bit, I expect it may be related to blob GC but it could be general heap usage by ffmpeg.

**Comment by prominentdetail** [comment] 2017-05-28 21:50
I have this issue too. Any game that uses audio won't load for me. I get this error in console:
Uncaught (in promise) DOMException: Unable to decode audio data
tested with Chrome.

**Comment by shortercode** [comment] 2017-05-31 10:30
I think there might actually be 2 separate issues here. With several long audio track ( 3 minutes plus ) I'm seeing safari crash from memory pressure, but this is pretty hard to debug. I think there may also be some other issue with preloading audio? I still need to investigate that though.

**Comment by jakemay74** [comment] 2017-05-31 10:32
In the example I posted with this bug none of the samples are more than a couple of seconds - there are quite a few of them though.

**Comment by jakemay74** [comment] 2017-06-30 11:02
Just wondering if there has been any progress on this issue?  Would we be able to revert to the old audio formats until a solution is found so I can test builds properly on iOS devices?

**Comment by AshleyScirra** [comment] 2017-06-30 13:04
I think this only affects the Opus format, so you should be able to work around it by switching all those sounds to .m4a (AAC) instead, like C2 used.

**Comment by jakemay74** [comment] 2017-06-30 13:38
OK, I'll give it a go.

**Comment by jakemay74** [comment] 2017-07-05 10:39
Swapping to .m4a did the trick, thanks.  Follow-up questions: will using .m4a limit the platforms that HTML5 exports will work on? What if I'm making an Android/iOS build? Could .m4a be offered as an import option, at least as an interim solution?

**Comment by AshleyScirra** [comment] 2017-07-05 14:45
It's the same as in C2. Providing you have both .m4a and .ogg (or .opus), it will play audio everywhere.

**Comment by jakemay74** [comment] 2017-07-06 09:31
.m4a imports fine but when I attempt to import .ogg it wants to import it as webm - isn't that going to end me up back in the same place as the initial bug?

**Comment by shortercode** [comment] 2017-08-24 12:03
A major revision of the Opus decoder is being included with r50, which should improve the situation a fair amount. Should be significantly faster and use less memory than the older version. 

Unfortunately, on iPad 2, while it doesn't run out of memory anymore ( for a reasonable amount of audio ) the speed is still less than amazing. It's not 100% clear why this but we expect it may be related to it running iOS 9, and the version of safari being less optimised for that type of JS. For comparison loading a project with 60 short sound clips:

iPad 2 iOS 9.3.5 (JS decoder) 60s
iPad Air 2 iOS 10.3.1 (JS decoder) 5s
Desktop Chrome 60 (Native decoder) 4s
Desktop Chrome 60 (JS decoder) 4s
Desktop Edge 15 (JS decoder) 4s
OnePlus 3 Chrome 60 (Native decoder) 4.5s
OnePlus 3 Chrome 60 (JS decoder) 5s

Notes:
- Desktop is using a Intel 6600k (4x 3.5GHz) with 16GB RAM
- Native decoder is unavailable in Safari and Edge
- Times are taken from reload to first paint of layout
- Times are approximate
- File transfer times will be different ( desktop was running the server )
- There's no option to force the JS decoder, I modified the runtime for testing

So going forward I think the advice is: use webm ( opus ) only, but if your looking to support specific older devices and experiencing slow loading on those then include an mp3 or m4a ( aac ) file to boost your decoding speed.

**Closed by shortercode** 2017-08-24 12:03 UTC
Labels: browser, difficult, need info
