### ISSUE TITLE
Xbox - Gamepad Button B closes game 

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#942] opened 2017-10-17 19:42 UTC
## Problem description

Hitting B button closes the game and you have to start it again. 

## Attach a .c3p

Not available right now. I’m not at home. 
Example uses just show layer on Button pressed. 

## Steps to reproduce

1. use On button pressed for B button

## Observed result

Game exits and Xbox shows previous app like home or store. 

## Expected result

B should be useable for game actions 

## Affected browsers

Xbox

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by TheBl4ckSh33p** [comment] 2017-10-18 06:32
You can test it in my published minigame "The very long walk" on Xbox.
https://www.microsoft.com/store/apps/9mzxg8k8z8dh

**Comment by AshleyScirra** [comment] 2017-10-18 10:48
Are you testing from Visual Studio in debug more or running it as a release app?

**Comment by TheBl4ckSh33p** [comment] 2017-10-18 12:28
It happens when playing released app on Xbox. I tested it in visual studio on pc and it works as expected there but on Xbox B button switches back to previous app/window ☹️

**Comment by TheBl4ckSh33p** [comment] 2017-10-18 12:32
Sorry forgot to update with additional info yesterday.

**Comment by AshleyScirra** [comment] 2017-10-18 17:21
Can you provide a minimal repro? It would confirm that you haven't accidentally included something like the Browser object's "close" or "back" actions. We can't rule this out if you don't share a project (one of the reasons we routinely require this)

**Comment by TheBl4ckSh33p** [comment] 2017-10-19 07:34
Hi. I could try to remove all other parts from the game to post it as example. I have to try to enable my Xbox as Dev Console to test future builds directly on my Xbox but for now I can only test it after publishing it to the Store. :/

I used the search feature to look for "Button B" and found 2 results. I only used the"Browser" plugin to open a few websites.
It is used to open a webpage if layer X is visible and to show another layer if used on the main menu.

+ Gamepad: On gamepad 0 Button B pressed
+ System: Layer "Credits" is visible
-> Browser: Go to "http://soft.bl4cksh33p.de" in a new window ("NewWindow")

+ Gamepad: On gamepad 0 Button B pressed
+ System: [X] Layer "Credits" is visible
+ System: [X] Layer "CharEditor" is visible
-> System: Wait 0.1 seconds
-> System: Set layer "CharEditor" Visible

I try to post the example soon.

**Comment by TheBl4ckSh33p** [comment] 2017-10-19 07:41
I removed unneccessary parts like showing different sprites,the game events sheet and things without any gamepad interactions and marked the 2 uses of the B button with a bookmark.
[BButton_Example.zip](https://github.com/Scirra/Construct-3-bugs/files/1397489/BButton_Example.zip)

**Comment by huntjn** [comment] 2017-10-29 16:09
To add to this, I've also experienced this issue (in Construct 2). Definitely not in my game's code - works as it should on PC/Mac. But when testing on my Xbox One dev kit whenever I press B it suspends the application and takes me back to the Dev Home.

Construct 2 using latest r247 beta release

In VS 2017:
Release - Any CPU - Remote Machine Build and Deploy (not packaging the app)

**Comment by TheBl4ckSh33p** [comment] 2017-11-02 12:42
FoxyLand made in C2 does not seem to have this problem. https://twitter.com/bug_studio/status/925995650499653632 🤔

**Comment by AshleyScirra** [comment] 2017-11-02 15:35
That would suggest the problem is specific to your project. I must emphasise the critical importance of making a minimal project - the smallest one you have provided still has around 50 events. Ideally the problem can be demonstrated in <5 events.

**Comment by huntjn** [comment] 2017-11-03 02:51
So according to the Microsoft website apparently all UWPs  auto assign the B button as a back button which causes the app to suspend. So I'm guessing we have to disable this in VS somehow.

**Comment by AshleyScirra** [comment] 2017-11-03 11:18
@huntjn can you provide a link to the page that says that?

**Comment by huntjn** [comment] 2017-11-03 12:39
Sure, here it is. It's way down the page under the "Built-in button support" section - https://docs.microsoft.com/en-us/windows/uwp/input-and-devices/designing-for-tv

**Comment by AshleyScirra** [comment] 2017-11-03 12:49
@huntjn - that section looks like it actually describes that the keyboard key "Escape" is mapped to the B button, not that the B button on the gamepad has any default action itself or that gamepad input is mapped to keyboard input.

**Comment by huntjn** [comment] 2017-11-03 12:53
Hmmm.. what about the snippet that says "When neither the KeyDown nor KeyUp events for the B button are handled by the app, the SystemNavigationManager.BackRequested event will be fired, which should result in back navigation within the app." ?

That sounds something like what I'm experiencing.

**Comment by huntjn** [comment] 2017-11-03 12:57
It does say however you have to implement that yourself (which I didn't). So I don't know, maybe it's already implemented on export?? Just trying to figure this out.

**Comment by AshleyScirra** [comment] 2017-11-03 12:57
Oh, I missed that bit. Yeah, it looks relevant actually. Looking at some of the C# code they have, there's already some analogous code in the Browser plugin's 'On back button' trigger. If you have that trigger in your project, even if it's an empty event, then the Browser object will mark the event handled (which ought to suppress the default action). Does adding an 'On back button' trigger avoid the problem?

**Comment by huntjn** [comment] 2017-11-03 12:59
Oh okay, awesome. I'll give that a try when I get home later tonight.

**Comment by huntjn** [comment] 2017-11-04 00:35
@AshleyScirra I implemented the On back button trigger, kept it as an empty event, and voila! The B button no longer suspends the game. Thanks for the help!

**Comment by TheBl4ckSh33p** [comment] 2017-11-06 17:52
Thanks. I try it with the next update. 
BTW: do you know how to keep LocalStorage when updating a uwp xbox game? It should be in visual studio somewhere. 🤔

**Comment by AshleyScirra** [comment] 2017-11-09 12:01
@TheBl4ckSh33p - did you get round to trying this? I would presume there is no code change here needed and we just need to document that you need to add the Browser trigger to prevent the default behavior.

**Comment by TheBl4ckSh33p** [comment] 2017-11-10 17:00
Not yet. Just switched to Xbox One X and need to try if the dev kit actiation still works for it. I try to add the new line and test it on my local Xbox soon.

**Comment by AshleyScirra** [comment] 2017-11-20 12:13
Closing on assumption the Browser object's 'On back button' fixes this. I've added a section "handling back button" in this tutorial to help avoid anyone else running in to it: https://www.construct.net/tutorials/using-xbox-live-in-uwp-apps-3

**Closed by AshleyScirra** 2017-11-20 12:13 UTC

**Comment by jrett** [comment] 2019-04-23 17:11
I'm trying to fix this on my monogame as well, and it's not clear to me what you guys mean by browser. Could you please be specific and put detailed instructions on how to resolve this? I don't use construct that I'm aware of, and in fact I'm just porting an old xna game to xbox one.
I'm using visual studio community 2017. How do you add "plugins" to visual studio 2017, and where do I find this "Browser" plugin?

**Comment by AshleyScirra** [comment] 2019-04-23 17:35
@jrett - I think you've come to the wrong place. This issue relates to JavaScript-based UWP apps. I assume monogame uses C# and a whole different set of APIs/technologies.
