### ISSUE TITLE
Pasting layouts into new project removes cross-layer sprite hierarchies

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#4773] opened 2021-04-28 19:51 UTC
## Problem description

When pasting a layout which contains two objects in a child-parent hierarchy into a different project, the parental connection between the objects in that layout is not carried into the different project.

## Attach a .c3p

[CrossPaste.zip](https://github.com/Scirra/Construct-3-bugs/files/6394370/CrossPaste.zip)

## Steps to reproduce

1. Open the attached project "CrossPaste.c3p".
2. Note in Layout 1 there is a sprite on one layer that is a child of another sprite on a different layer.
3. Run the project, confirming that as the parent moves using its bullet behavior, the child moves with it.
4. Create a new project and paste Layout 1 from CrossPaste.c3p into your new project.
5. Run the pasted layout in your new project, noting that the child no longer sticks with the parent as the hierarchy was not kept when the layout was transferred to the new project.

## Observed result

Objects' child-parent hierarchy between two layers was lost when layout was pasted to a new project.

## Expected result

The hierarchy is kept when pasted to a new project, as happens when the child and parent are on the same layer of the pasted layout.

## More details

**Affected browsers/platforms:** Firefox, Chrome.

**First affected release:** No later than r241.

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 88.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
C3 release: r241 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 423 kb (0%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2021-04-29 13:37
Duplicate of an issue mentioned in #4735. Was fixed in r245 so it should be working properly in the latest beta.

**Closed by DiegoScirra** 2021-04-29 13:37 UTC
Labels: duplicate
