### ISSUE TITLE
Issues opening projects with many images from 210 onward (and NW.JS 47 +)

### ISSUE THREAD

**Issue by aiaicaptain** [Scirra/Construct-3-bugs#4118] opened 2020-08-16 11:50 UTC
## Problem description

After last stable update (210), and prompt to update NW.JS version the following happens, which was  100 % not an issue before hand:

DESKTOP VERSION:

I cannot open my large FOLDER BASED project at all. It just hangs up, no error, no nothing. CPU usage falls beneath 1% and that's forever. Tested on three PCs.

Single file project opens, but this is still an issue for me because large projects with lots of images open REALLY(Extremely) slow (not the case in Folder Projects) and becuase of the version control I use. Again, I have a large project.

BROWSER VERSION:

Sometimes opens the Folder Based Project... around 1 out of 3 attempts.

Before saying Construct 3 is not meant for games of this size (which I don't believe you will as you've said in the forums you're aiming construct to be the correct choice for larger games as well), know that before this update I had never had any issue, and I've even "stress tested" the project to around 20 k images.

## Steps to reproduce

1.Open c3p,(have patience, it will take a while.)
2. Save it as a FOLDER BASED project.
3.Open FOLDER BASED project with Desktop App
4.Open FOLDER BASED project with Browser App

## Observed result

DESKTOP APP will never load FOLDER BASED project
BROWSER APP will load, but not always.

## Expected result

I can open a large FOLDER BASED project in both Browser and Desktop versions as I could before 210, with not issues whatsoever.

## More details

**Affected browsers/platforms:** Chrome, Desktop

**First affected release:** 210 Stable

## System details

Tested on various (three) machines, to the same result.
[BigProject.ZIP](https://github.com/Scirra/Construct-3-bugs/files/5080589/BigProject.ZIP)

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2020-08-17 14:54
The browser version seems to open it fine every time for me. I can reproduce it taking forever with the NW.js version though. It seems to just fall idle and stop doing any further work. That's really weird and I don't know why that would happen - my best guess is there's another problem with the new Closure Compiler minifier we switched to recently. It may be that the next update of that fixes the issue since they fixed a bug that was affecting our code recently, so I'll try updating to that when it's out as a first step.

**Comment by AshleyScirra** [comment] 2020-09-01 14:08
It still reproduces for me after updating Closure Compiler, so I don't think it's to do with that. I've made some adjustments to the loading scheduling for the next release which seems to have solved it for me, but it's quite hard to tell since it's relatively unpredictable. Marking to check when the next release is out to verify.

**Comment by AshleyScirra** [comment] 2020-09-08 14:53
@aiaicaptain - r215 is now out, can you verify if it's working with that release?

**Comment by aiaicaptain** [comment] 2020-09-08 16:34
No, the problem persists for me.

**Comment by AshleyScirra** [comment] 2020-09-10 16:00
I could previously reproduce this before, but now with r215 it seems to reliably open the folder project. I tried 5 times with the browser and 5 times with the desktop build (NW.js 0.48.1) and it worked fine every time. Are you sure you were trying with r215?

**Comment by aiaicaptain** [comment] 2020-09-11 15:10
Hmmm, the project I attached to this issue really does open, but my personal huge project does not still. The only difference in terms of specs between the two are that my project has around 4k events +, along with many sprites. I even tried deleting a bunch of sprite objects to drastically lower the sprite count (this actually worked before), but now it won't open with even a low sprite count. Is there a chance that now it hangs up because of high event count?

**Comment by aiaicaptain** [comment] 2020-09-11 15:22
No, skip that, I deleted ALL events in my project and still it didn't run. I can't get it to open under 215 at all anymore (desktop, folder based) at all. i can still open it (and still every 5th attempt) from the browser version.

**Comment by aiaicaptain** [comment] 2020-09-11 15:28
I can upload a severely trimmed down version of my project, if you are willing to try and open it it'd be awesome.

**Comment by AshleyScirra** [comment] 2020-09-11 16:00
I think if the size of the project is the problem, it's best to address this with the actual original project. Could you send it to me at ashley@scirra.com?

**Comment by AshleyScirra** [comment] 2020-09-14 13:02
Project received by email but seems to work fine for me here, successfully opened as a folder project 10 times in a row with r215.

**Comment by AshleyScirra** [comment] 2020-09-15 14:33
Unable to further reproduce, so closing issue.

**Closed by AshleyScirra** 2020-09-15 14:33 UTC
Labels: can't reproduce, desktop
