### ISSUE TITLE
Crash with Tint, SetColor, object color (mutiple values modified)

### ISSUE THREAD

**Issue by sebastien-c3** [Scirra/Construct-3-bugs#2314] opened 2018-11-14 20:34 UTC
## Problem description

Crash when changing Tint, SetColor and object color when the values are multiple.

## Attach a .c3p

[color-crash-bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2582542/color-crash-bug.zip)

## Steps to reproduce

1. Open the file and go to the layout.
2. Select two objects of the same type.
3. Change the following multiple values to trigger the bug:
Tint: As indicated.
SetColor: As indicated.
9-patch: Tint.
SpriteFont: Tint.
Tilemap: Tint.
Tiled Background: Tint.
Text: Text color.
Particles: Tint.
ShadowLight: Shadow color.

## Observed result

Full crash. Maybe this occurs with other multiple value changes.
The problem also arises, where possible, with the SetColor effect.

## Expected result

No crash.

## Affected browsers

C3 Standalone.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r120/main.js, line 2, col 402660
Message: Uncaught TypeError: Cannot read property 'ǃVfN' of null
Stack: TypeError: Cannot read property 'ǃVfN' of null at ǃv.ǃV.ǃKY.ǃVkg.ǃVCk (https://editor.construct.net/r120/main.js:2:402660) at ǃv.ǃV.ǃKY.ǃoE.ǃVwe (https://editor.construct.net/r120/main.js:2:420230) at ǃv.ǃV.ǃKY.ǃoE.ǃfM (https://editor.construct.net/r120/main.js:2:420153) at ǃv.ǃV.ǃKY.ǃoE.ǃfe (https://editor.construct.net/r120/main.js:2:420065) at ǃv.ǃV.ǃKY.ǃVkg.ǃVuw (https://editor.construct.net/r120/main.js:2:400744) at ǃv.ǃV.ǃKY.ǃVkg.ǃVkI (https://editor.construct.net/r120/main.js:2:401463) at ǃv.ǃV.ǃKY.ǃVkg.ǃVkl (https://editor.construct.net/r120/main.js:2:401000) at HTMLInputElement.ǃVkB (https://editor.construct.net/r120/main.js:2:399242)
Construct 3 version: r120
URL: https://editor.construct.net/
Date: Wed Nov 14 2018 21:33:13 GMT+0100 (heure normale d’Europe centrale)
Uptime: 2821.9 s

Platform information
Browser: NW.js
Browser version: 0.33.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (@032b3ca19e9af20182f9bd03deefc0faf4695558) NWjs/0.33.0 (like Chrome/69.0.3497.81)
C3 release: r120 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2018-11-15 11:31
Can't reproduce in r125. This should have been fixed in r123:

> Possible crash editing opacity property in "multiple" state

> Color properties could incorrectly display as "multiple" state even when all colors were the same

Please file again if you can reproduce in the latest release.

**Closed by AshleyScirra** 2018-11-15 11:31 UTC
Labels: can't reproduce

**Comment by sebastien-c3** [comment] 2018-11-16 05:09
Thanks for your feedback, I'm indeed on the latest stable version.
After testing, everything seems to work with the latest beta.
