### ISSUE TITLE
Preload  sounds didn't work on iOS 11.2.5 in Native app and Safari

### ISSUE THREAD

**Issue by TombasOnly** [Scirra/Construct-3-bugs#1173] opened 2018-01-11 10:43 UTC
## Problem description

HW: iPad Mini 4
SW: iOS 11.2.5
Same behavior in Safari browser and Native cordova app.

When I checked Preload Sounds, game freeze on loading screen.
<img width="1024" alt="soubor_001" src="https://user-images.githubusercontent.com/31991351/34821282-797acfa2-f6c3-11e7-999f-57e73562ab35.png">

When I unchecked Preload Sounds, game load sucessfully, but without any sounds. Sounds didn't work.

It's look like somethnig is with audio opus decoder or iOS 11 is garbage :)

## Steps to reproduce

1. Checked - Preload Sounds.
2. Use Remote preview on Safari or Cordova app for iOS 11.2.5
3. Game freeze on loading screen.

1. Unchecked - Preload Sounds.
2. Use Remote preview on Safari or Cordova app for iOS 11.2.5
3. Game loading sucessfully, but sounds didn't work.

## Expected result

Game loading sucessfully with preload sounds.

## Affected browsers

Only iOS Safari or Cordova app

## System details

HW: iPad Mini 4
SW: iOS 11.2.5

**Comment by AshleyScirra** [comment] 2018-01-11 10:47
Sorry, there is nothing for us to investigate unless you follow the bug report guidelines and attach a project that reproduces the issue.

**Comment by TombasOnly** [comment] 2018-01-11 11:12
@AshleyScirra  Ok, I am sorry. It's commercial project, so I delete everything private. Here is minimal .c3p project, it has same issues. 

It didn't contains short sounds. But that contains sounds 30 sec to 1 minutes long. I didn't use music stream because I need music and game absolutely synchronized. In full version I used song subtitles, that desynchronized if I use music folder. So I need to use preload and sounds. Two weeks ago It works well, maybe is something different with new iOS version, I don't know :/

[aol_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/1622272/aol_bug.zip)

**Comment by AshleyScirra** [comment] 2018-01-12 18:17
I can reproduce: iOS 11.2 worked, iOS 11.2.2 fails. This appears to be a bug in Safari on iOS in the latest security update. I suspect it's due to memory management changes that have been rushed out to mitigate Spectre - on iOS 11.2.2, it logs strange errors about "cannot enlarge memory arrays" to the console, which looks wrong.

I filed a WebKit bug here: https://bugs.webkit.org/show_bug.cgi?id=181598 - closing this issue as we will follow up there. FWIW, Safari on macOS does not appear to be affected, just iOS.

**Closed by AshleyScirra** 2018-01-12 18:17 UTC
Labels: external, iOS, safari

**Comment by cihanyakar** [comment] 2018-03-25 17:19
iOS 11.2.6 work well
