### ISSUE TITLE
Remote preview not working on mobile

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#1645] opened 2018-05-30 18:18 UTC
## Problem description

Remote preview doesn't seem to be working on mobile devices

## Attach a .c3p

https://puu.sh/AvY6g/7e5d1d96b5.c3p

## Steps to reproduce

1. Open the empty project,
2. Launch remote preview
3. Remote preview on a mobile device

## Observed result

it shows Construct 3 remote preview Loading scripts.. (100%) but never previews

## Expected result

to see a white page since it'S an empty project

## Affected browsers

Both my phone and my tablet, phone is a brand new pixel xl

**Comment by AshleyScirra** [comment] 2018-05-31 10:28
Possible duplicate of #1616 - could you try clearing the browser cache on the mobile device and retrying? It should be fixed already, but we had to change something server-side.

**Comment by eleanorawesome** [comment] 2018-06-02 21:27
I cleared the cache but the issue is still there

**Comment by eleanorawesome** [comment] 2018-06-03 04:07
It works now, I don't know why. But it works !!!!!! Thank you !

**Closed** 2018-06-04 11:05 UTC
