### ISSUE TITLE
Construct 3 - Mouse Cursor Off-Set In Layout View

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#766] opened 2017-08-31 13:05 UTC
## Problem description

I've noticed that there is a slight off-set of the mouse cursor after switching to fullscreen mode and back.

## Attach a .c3p

Any of the examples will do.

## Steps to reproduce

1. Open any project
2. Be in layout view
3. Switch to fullscreen and back to windowed
4. Notice mouse off-set (depending on the window size, it gets worse)

## Observed result

A mouse off-set inside the layout view.

## Expected result

There should be no off-set when switching over to fullscreen and back.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: -
* Safari: -

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Nothing.

</details>

**Comment by AshleyScirra** [comment] 2017-08-31 14:00
I think this is another case of #671 (and also reported at #764) - currently resizing the window causes the layout view rendering to go a bit weird. I think actually the mouse is correct but the layout view rendering is offset, which is what happens in bug #671. So closing as duplicate of that.

**Closed by AshleyScirra** 2017-08-31 14:00 UTC
