### ISSUE TITLE
Tilemap collision cell optimization bugs

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4724] opened 2021-04-10 15:03 UTC
## Problem description
Case when tilemap collision under certain case causes bug.

Look image below.
Selected sprite can collide and is affected by wall behaind first wall. 2 wall is 8 pixels away and it seems collision cells are merged together under such case.
![bgrttrtr](https://user-images.githubusercontent.com/28864889/114274329-8eca7600-9a26-11eb-955d-44236f15d519.jpg)

## Attach a .c3p
[Bug_the_MaximusJr.zip](https://github.com/Scirra/Construct-3-bugs/files/6290070/Bug_the_MaximusJr.zip)

## Steps to reproduce

1.Preview project
2.
3.

## Observed result
Object can detect solid tilemaps 8 pixels away, which make plain sprite with bullet behavior bounce at random angle. Removing 2 wall, will make sprite bounce correctly

## Expected result
Sprite should bounce back directly.  

## More details

Can or should collision merge occure or  why it happens and could it be changed by user?

If this is not a bug and is edge case for better performance, which are possible limits?

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 89.0.4389.114
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
C3 release: r243.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 1.3 gb (1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2021-04-12 09:34
I can't see anything wrong in the provided project. Both the vertical lines drawn with 1px tiles can collide. And the sprites bounce off the first vertical line. So it all seems to be fine. Am I missing something?

**Comment by SnipG** [comment] 2021-04-12 14:29
8 pixel was biggest lenght that still made bug to occure. 9 pixel distance it did not cause bug. it might be 7/6 for you.

**Comment by SnipG** [comment] 2021-04-12 14:34
https://user-images.githubusercontent.com/28864889/114411906-49887e80-9bb5-11eb-9055-53efcfc4fc61.mov

**Comment by AshleyScirra** [comment] 2021-04-13 10:42
What is actually meant to be wrong in that video? Everything looks like it is colliding correctly.

**Comment by SnipG** [comment] 2021-04-13 13:02
As in original report "Object can detect solid tilemaps 8 pixels away, which make plain sprite with bullet behavior bounce at random angle. Removing 2 wall, will make sprite bounce correctly"

You can see line of bullets bounce at angle, when there is 2 wall. If it's removed, bounce is correct.
It's clearly visible, or it should happen like that? It's edge case that always been like that?

**Comment by AshleyScirra** [comment] 2021-04-14 12:01
Oh right, I see. Well the bounce angle is only an estimation and is not guaranteed to be exact. Given there is an arbitrary layout of collidable objects, we don't have an exact surface normal to use for the reflection angle, so it's estimated by testing collisions in a small localised area. The presence of other nearby solids can affect that. This is by design and I don't think it's easy to improve upon, so closing.

**Closed by AshleyScirra** 2021-04-14 12:01 UTC
Labels: not a bug
