### ISSUE TITLE
Audio fails to encode/import

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#1781] opened 2018-07-09 03:39 UTC
## Problem description

When I try to import an audio file, it says "failed", even though it plays fine in music players.

## Attach a .c3p

Zip includes the audio file, in various formats, none of which import

[sfx.zip](https://github.com/Scirra/Construct-3-bugs/files/2174572/sfx.zip)

## Steps to reproduce

1. Sounds -> import audio

## Observed result

Encoding Fail

## Expected result

Success

## Affected browsers

Latest desktop build

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.31.2
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@878cd31214ac27a3996927cd5c9c138b10c9fc8d) NWjs/0.31.2 (like Chrome/67.0.3396.87)
C3 release: r108.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 156 gb
Storage usage (approx): 432 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2018-07-09 11:14
Doesn't seem to affect the browser version, so adding the desktop label. We don't support .aiff files by the way, the other formats should work though. 

I've debugged the desktop version and I can see what the problem is, it's to do with how NWJS represents file meta data.

**Comment by shortercode** [comment] 2018-07-10 13:43
Should be fixed in the next release.

**Closed by shortercode** 2018-07-10 13:43 UTC
Labels: desktop
