### ISSUE TITLE
Tween suddenly not working correctly

### ISSUE THREAD

**Issue by 4demon** [Scirra/Construct-3-bugs#4122] opened 2020-08-17 18:13 UTC
## Problem description

I use the tween behaviour as a counter animation. Every second it sets its angle to 180, then tweens to 0. This has been working fine for months, however, on version 211 it will set its angle to 180 but not tween.

If I invert it, starting at 0, then tweening to 180, it works fine.

## Attach a .c3p

[TweenBug.zip](https://github.com/Scirra/Construct-3-bugs/files/5086058/TweenBug.zip)

## Steps to reproduce

1. Create sprite and give it the tween behaviour
2. Create an action that every 1 second it will set it's angle to 180 then another that tweens to 0
3. Play

## Observed result

It sets it to 180, but does not tween back to 0

## Expected result

It used to tween back to 0... it doesn't anymore

## More details

Seeing quite a few errors with this version, but this is the only one I'm able to replicate. Another is one of my functions has been duplicated 3 times, and even after deleting any reference to it they're still sat there. Restarting Construct 3 fixed this.

**Affected browsers/platforms:** 

**First affected release:** 

Worked in 210.2 but broke in 211.

**Comment by DiegoScirra** [comment] 2020-08-18 08:22
Duplicate of #4106. Fixed in the next beta.

**Closed by DiegoScirra** 2020-08-18 08:22 UTC
Labels: duplicate
