### ISSUE TITLE
Platform behavior passing through Jumpthru instead of landing on it

### ISSUE THREAD

**Issue by johnsmith27** [Scirra/Construct-3-bugs#2321] opened 2018-11-16 11:00 UTC
## Problem description
From a certain angle the platform behavior fail to land on a jumpthru platform and slowly passes through it.

Also from time to time, the platform behavior lands with an offset of (something like) -1 pixel on the Y axis, until a new jump happens (or falling away). Happens with both solid & jumpthru behaviors. (can also be seen in the attached video)

Project settings: 200*320 (portrait) & Point Sampling

## Attach a .c3p
https://www.dropbox.com/s/hygcxthlj9174ge/jumpthru_bug.c3p?dl=0

## Steps to reproduce
Jump on a higher platform from a little distance and try to land on its border.

Video: https://www.dropbox.com/s/tgpjlwaasturmx9/jumpthru.mp4?dl=0

## Observed result

See video

## Expected result

If reached, the platform behavior should land on it instead of slowly passing through..

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.102
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 90 mb (0.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 6
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2018-11-16 12:59
I tried this a couple of dozen times and couldn't reproduce any issue. Can you find a way to more reliably reproduce it?

It's also useful to ensure your project does not have any unrelated events, objects, or layouts - an absolutely minimal project will help rule out other potential causes of the bug. Also ideally the project can work automatically and not require any user input, to eliminate variation in inputs. Could you produce a reduced automatic project that demonstrates the problem?

**Comment by johnsmith27** [comment] 2018-11-16 16:07
Hi Ashley,

I tried to reproduce it automatically but without much success...  But if I use one input (spacebar) to restart the layout - generally for me it happens on the third or fourth try. (the landing sound doesnt play & it goes through again). 

https://www.dropbox.com/s/0hzosudn4vpa45n/jumpthru_bug_2.c3p?dl=0

And haven't specified but this problem also happens when testing the debug APK on my Android phone (Huawei P9) (only tried with the full project though, not with this minimal one)

**Comment by SnipG** [comment] 2018-11-16 21:17
I automated it.
[Tiny_Automated.zip](https://github.com/Scirra/Construct-3-bugs/files/2590862/Tiny_Automated.zip)

It seems it comes from lag+landing. You can enable every tick event to pressure fps, and see almost all jumps will fail.
If that platform land is so spetsific about fps, 1 pixel miss landing will bug it. Ofc it can easily fail on weaker devices like phones when you got more stuff going on project. 

Ones that fail landing, won't trigger Landed.

**Comment by johnsmith27** [comment] 2018-11-19 10:38
Hi,
Just letting you know, I increased the jump strength and the problem seems gone so far... so fine for me.

**Comment by SnipG** [comment] 2018-12-16 01:30
I checked this bug again.
Overall, when sprite has solid disabled and jumpthru enabled, sprites sometimes don't land  pixel perfect - i think this could cause the issue that player sprite sometimes will fall trough jumpthru sprite, on some edge case, but i am not 100% sure. 

When this "not" pixel perfect landing occures durning some edge collision, sprite won't trigger landed.
I think if collision gets fixed, fall trought will be fixed to.
When you have solid enabled, you never have case when sprite won't land pixel perfect.
I add 2 videos and example.
Example
[JumpThruBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2683182/JumpThruBug.zip)

2 Videos, 1 showing edge collision, other when platform won't land pixel perfect.
[2018-12-16 03-03-13.zip](https://github.com/Scirra/Construct-3-bugs/files/2683183/2018-12-16.03-03-13.zip)

**Comment by SnipG** [comment] 2019-01-05 11:38
Deleted my last previous examples,  where random noise, bad examples and did'nt rly show currect bug correctly.
Anyhow, now i got correct reproduce example for this annoying bug.

Example
[JumpThru_Bug1.zip](https://github.com/Scirra/Construct-3-bugs/files/2729447/JumpThru_Bug1.zip)

Steps to reproduce.
Click green box, let player sprite jump on red box.
When Sprite X Pos is 141 or 140, it will fail the jump and shows the bugged behavior.

Simple Video, how it happens on my PC
[2019-01-05 13-14-23.zip](https://github.com/Scirra/Construct-3-bugs/files/2729448/2019-01-05.13-14-23.zip)

It seems there is 2 kind of bad behavior depending on "something". 
 -  player gets stuck inside sprite and slowly starts to fall(which current bad case and shows up). 
 -  Or it just jumps thru, even trough it should have landed on sprite. Users don't see this, but still sprite should have landed on the platform. Which could ruin some platform games, as players know they should have jumped over the hole/s etc.
Both are bad cases. I think fixing one will fix other too.

**Comment by AshleyScirra** [comment] 2019-01-18 16:15
@SnipG - thanks for a great repro project, this helped a lot to identify the issue. It appears to come down to an edge case where you land on a platform using only horizontal motion (not vertical motion). I think it's fixed for the next release (both C2 + C3 runtimes).

**Closed by AshleyScirra** 2019-01-18 16:15 UTC

**Comment by SnipG** [comment] 2019-01-21 16:58
Just letting u know that the bug still happens, but is more rare now. 
[TinyLvl2.zip](https://github.com/Scirra/Construct-3-bugs/files/2779737/TinyLvl2.zip)
Its not automated example.

**Comment by AshleyScirra** [comment] 2019-01-21 17:03
I believe the case reported in this issue is now resolved. There may be another case where it happens; please file a separate issue for that and, as with this issue, it is essential to make a reliable reproduction project for the issue to be fixable.
