### ISSUE TITLE
Black screen on Preview from long long time - ITS URGENT FOR GAMEJAM

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#336] opened 2017-05-24 05:23 UTC
## Problem description
I have made game for GameJam
game is almost ready and ready to submit
But today morning i was doing some final works and when i do preview. Its a black screen only 
I have try to delete all object and all events totally made blank sheet then preview still its not working may be some bug is here
*Enter a concise description of your problem here*

## Attach a .c3p
Project made for Game jam So Not Sharing here
Please provide me Private Message Link
I will send .C3p file through Message only 
*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce
1. No steps required because on newly created project preview is working very fine
but in existing project its not working 

## Observed result
Black screen and on Debug mode showing loading ... 
*What do you see happen?*
Only black screen or Loading screen

## Expected result
Preview my project progress
*What did you expect to happen instead?*
preview 
## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by luckyrawatlucky** [comment] 2017-05-24 06:12
Its working now
I have just deleted Google Play Plugin and it working very well
Then now why Google Play plugin doing this 
if their is any reason please tell me

**Comment by 3dParadox** [comment] 2017-05-24 06:55
I had the black screen after updating to r30, and found deleting the "User Media" object fixed it.

I was only using it's voice to call out when things were triggered, so i didn't dig deeper.

**Comment by shortercode** [comment] 2017-05-24 10:51
seems like one of the preview wasn't loading one of the dependencies properly, I'm looking into it

**Comment by AshleyScirra** [comment] 2017-05-24 11:07
Can't reproduce after fixing #331 so think this is the same issue, should be fixed in r31. In the mean time you can roll back to r29.2 at https://editor.construct.net/r29-2/

**Closed by AshleyScirra** 2017-05-24 11:07 UTC
