### ISSUE TITLE
C3 r78 Debug Layout stuck at loading -  Desktop version

### ISSUE THREAD

**Issue by Kunnatam** [Scirra/Construct-3-bugs#1205] opened 2018-01-16 16:05 UTC
## Problem description

The problem is the debugger stuck at loading session for Construct 3 desktop version. 
-This also happens to every Construct3 starter template and my .c3p project so I would assume that it is not form project file.
* Construct 3 on Browser debug layout is working fine.
* Not working before Third-party plugins was installed.
* Not working after Third-party plugins was installed.

## Attach a .c3p

I encountered this issue on every project file including starter templates. I guess .c3p is not needed.

## Steps to reproduce

1.Open any project.
2.Click on debug layout.
3.Stuck at loading.

## Observed result

The debug window shows 'Inspector - Loading' and stuck

## Expected result

The debugger preview layout should be loaded.

## Affected browsers

* Chrome: no
* Desktop: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.27.4
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@d8d23fd3b95d7b3c7744027f2ea1c954aec28955) NWjs/0.27.4 (like Chrome/63.0.3239.132)
C3 release: r78
Language setting: en-US

Local storage
Storage quota (approx): 39 gb
Storage usage (approx): 385 mb (1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 5500 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2018-01-16 16:09
Can't reproduce here. Please always follow the bug report guidelines so we can identify the problem. Can you attach a project that demonstrates the issue?

**Comment by AshleyScirra** [comment] 2018-01-16 18:16
It still works for me, can't see anything wrong. The only issue is that the debug window can't be closed in r78 which should already be fixed for r79.

**Comment by Kunnatam** [comment] 2018-01-16 18:31
Do you have any idea what might be the cause? Debug on browser seems to be the only choice I have for now.
Anyways, if you allow me, I could make a thread on scirra forum to see if anyone has the same issue.

**Comment by AshleyScirra** [comment] 2018-01-16 18:41
It's a bit tricky because the desktop build leaves out dev tools to reduce bloat, but you could try this: download the Win64 "SDK" version of NW.js here - https://nwjs.io/downloads/
Extract it over the existing desktop build, and run nw.exe (not Construct3.exe). Then if you press F12 you should see dev tools open. If you press F12 when the frozen debug window is showing, there might be some error messages in the console, which it would be useful to know.

**Comment by Kunnatam** [comment] 2018-01-16 18:56
![err](https://user-images.githubusercontent.com/30936340/35006439-3c98cdc2-fb29-11e7-9bc3-0e325976dc82.png)
Got this on console log. Excuse my lack of programming knowledge, I have no clue what it is though.

**Comment by AshleyScirra** [comment] 2018-01-16 19:04
Are you sure you're using the latest desktop build? It was updated yesterday. These messages look like it's an old build. https://www.scirra.com/forum/construct-3-desktop-build-beta-currently-win64-only_t199344

**Comment by Kunnatam** [comment] 2018-01-16 19:25
You are right! It was an old build and getting new build fixed the issue. That seems a little bit odd to me because I have this issue since c3desktop first released but nobody else have this issue so I thought it was something else from my computer side.
Well, thanks for helping me here. It's the end of my struggling.

**Comment by AshleyScirra** [comment] 2018-01-16 19:37
OK, thanks for confirming!

**Closed by AshleyScirra** 2018-01-16 19:37 UTC
Labels: can't reproduce, desktop
