### ISSUE TITLE
Physics crashes with box2d.asm.js errors if physics sprites have animations

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1019] opened 2017-11-19 00:44 UTC
## Problem description

Game with physics freezes with the following errors in the console log.  If the sprite has animation speed set to 0 it won't crash it seems.

**edit( shortercode)**
<details><summary>View stack trace</summary>
box2d.asm.js:6 Uncaught abort() at Error
    at fb (https://editor.construct.net/r67/behaviors/physics/c2runtime/box2d.asm.js:30:26)
    at ua (https://editor.construct.net/r67/behaviors/physics/c2runtime/box2d.asm.js:416:61)
    at Function.o [as W] (https://editor.construct.net/r67/behaviors/physics/c2runtime/box2d.asm.js:16:91)
    at nc (https://editor.construct.net/r67/behaviors/physics/c2runtime/box2d.asm.js:166:483)
    at NB (https://editor.construct.net/r67/behaviors/physics/c2runtime/box2d.asm.js:195:40914)
    at _f (https://editor.construct.net/r67/behaviors/physics/c2runtime/box2d.asm.js:183:24253)
    at new Fx (https://editor.construct.net/r67/behaviors/physics/c2runtime/box2d.asm.js:653:22)
    at behaviorProto.Instance.behinstProto.createBody (https://editor.construct.net/r67/behaviors/physics/c2runtime/runtime.js:742:16)
    at behaviorProto.Instance.behinstProto.tick (https://editor.construct.net/r67/behaviors/physics/c2runtime/runtime.js:1079:9)
    at Runtime.logic (https://editor.construct.net/r67/preview/c2/preview.js:2588:29)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
c @ box2d.asm.js:6
ua @ box2d.asm.js:416
o @ box2d.asm.js:16
nc @ box2d.asm.js:166
NB @ box2d.asm.js:89
_f @ box2d.asm.js:331
Fx @ box2d.asm.js:653
behinstProto.createBody @ runtime.js:742
behinstProto.tick @ runtime.js:1079
Runtime.logic @ preview.js:2588
Runtime.tick @ preview.js:2312
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
requestAnimationFrame (async)
Runtime.tick @ preview.js:2223
tickFunc @ preview.js:596
box2d.asm.js:9 Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 33554432, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
box2d.asm.js:9 Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 33554432, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.

</details>

## Attach a .c3p

[PhysicsBug2.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1485173/PhysicsBug2.c3p.zip)

![image](https://user-images.githubusercontent.com/7268697/32986131-3a434900-ccd3-11e7-9035-0f56bf34098c.png)

## Steps to reproduce
1. run the c3p for about a minute

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 62.0.3202.94
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.125
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
C3 release: r67
Language setting: en-US

Local storage
Storage quota (approx): 11 gb
Storage usage (approx): 458 mb (4.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 5500 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2017-11-20 11:44
Looks similar to #838 

In that particular case there was 2 behaviours clashing with each other, causing a kind of ping pong effect and creating a new physics body each time. I expect this is something similar. I'm not 100% sure but I think there might be a leak in the physics plugin somewhere, and box2d has a set memory limit hence the "Cannot enlarge memory arrays[...]"

**Comment by AshleyScirra** [comment] 2017-11-20 12:03
Closing as duplicate of #838. You definitely should not use animated physics sprites, specifically because changing frame causes the physics body to be removed, and a new one teleported in to its place. This is obviously an unrealistic physics phenomenon so the physics stability will suffer as a result. You should use static sprites with physics and place any animated sprites on top, e.g. with the Pin behavior.

**Closed by AshleyScirra** 2017-11-20 12:03 UTC

**Comment by AshleyScirra** [comment] 2017-11-20 12:07
I noticed the physics tutorial didn't actually cover this point, so I updated the documentation here to mention that: https://www.construct.net/tutorials/physics-in-construct-the-basics-6
