### ISSUE TITLE
Platformer Behavior : ability to Jump before AND without "On-landed" Triggering

### ISSUE THREAD

**Issue by VonFirflirch** [Scirra/Construct-3-bugs#3597] opened 2020-01-20 19:38 UTC
## Problem description

As an object with the Platform Behavior falls, it's able to jump again before actually landing, allowing it to skip the On-landed trigger. 

I've included another, small "On-landed"-related issue in the .c3p below, let me know if I should make a bug report for it specifically, as well.

## Attach a .c3p

https://www.dropbox.com/s/34rn6cer0l2fnim/Jump_Before_Landing_Issue.c3p?dl=0

## Steps to reproduce

1. Make the Sprite object jump with the Up arrow key ;
2. Attempt to jump again just before landing, the timing is a bit tight ;

## Observed result

If done correctly, the Ground object will not change visibility, despite the On-landed trigger that should affect it.

## Expected result

It should not be possible to bypass the On-landed trigger.

## More details

**Affected browsers/platforms:** 
Chrome, on Windows.

**First affected release:** 
I didn't take the time to check specific older Construct 3 builds, but I was able to recreate the issue as early as the old C2 build I have, R262. 
I've noticed this problem for a while and I don't recall a C3 build where I didn't have to write around it. I should have made a bug report earlier, my apologies. I'll admit that I wonder why no one else ever did, though.

## System details

<details><summary>View details</summary>
I got the following information using R182.2, as R183 gives me a blank window instead when I try to click the option. The bug DOES happen on R183, however.

Platform information
Browser: Chrome
Browser version: 79.0.3945.130
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
C3 release: r182.2 (stable)
Language setting: fr-FR

Local storage
Storage quota (approx): 274 gb
Storage usage (approx): 228 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 705 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2020-01-21 11:24
This is currently by design. Note that it's classed as an animation trigger: it's designed for controlling the objects animations. If you go directly from falling to jumping with no gap in between, the player's animation should switch directly from falling to jumping, with no landing animation in between. This is why in some circumstances it won't trigger. Since the player animations don't always cover every step, it's not a reliable way to detect if the player landed on the floor.

Instead you can use 'Is on floor', and add 'Trigger once' if you want to make it a one-off event. This appears to work correctly.

**Closed by AshleyScirra** 2020-01-21 11:24 UTC
Labels: wontfix

**Comment by VonFirflirch** [comment] 2020-01-21 11:30
I see, sorry for the time wasted.
