### ISSUE TITLE
Layer name does not show up in Autocomplete

### ISSUE THREAD

**Issue by Souls3** [Scirra/Construct-3-bugs#3640] opened 2020-02-10 08:03 UTC
## Problem description

Layer name does no show up in Autocomplete if there is another layer with the same name but different case

## Attach a .c3p

[LayerNames.zip](https://github.com/Scirra/Construct-3-bugs/files/4179586/LayerNames.zip)

## Steps to reproduce

1. Add a new layer, name it "UI"
2. Add a new layout
3. Add a new layer in the new layout, name it "ui"
4. Add any event
5. Add an action: Set layer visible
6. Type a quotation mark in the layer field

## Observed result

Only "UI" (and the default layers) shows up

## Expected result

"UI" and "ui" should show up in Autocomplete.
OR, Construct shouldn't allow naming a layer "ui" in the first place.

## More details

**Affected browsers/platforms:** Chrome/Firefox

**First affected release:** r182.3 stable

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 72.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0
C3 release: r182.3 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 1 gb
Storage usage (approx): 370 kb (0%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA Quadro 600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    WebM Vorbis (audio/webm; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)

Video information

Supported decode formats:

    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2020-02-10 11:30
I don't see why this is a problem. Layer names are case insensitive so either "UI" or "ui" both work fine. Why should the autocomplete list include names that vary only by case if it has no effect?

**Comment by Souls3** [comment] 2020-02-10 12:22
Just for Clarity :)
But does that mean that when I make "UI" visible, C3 will make "UI" and "ui" both visible? i.e. The "UI" in autocomplete points to ALL layers with the name "ui" -independent on the case-?

**Comment by AshleyScirra** [comment] 2020-02-10 12:45
It only affects the layer on the running layout.

I don't this warrants a change, so closing as not a bug.

**Closed by AshleyScirra** 2020-02-10 12:45 UTC
