### ISSUE TITLE
Platform behavior bug with jumpthru 

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2537] opened 2019-01-23 00:40 UTC
## Problem description

Platform behavior fall though jumpthru, when it lands on it.

## Attach a .c3p
Messy automated example. Sometimes works everytime, next preview does not.
[IH...Platform (1).zip](https://github.com/Scirra/Construct-3-bugs/files/2785198/IH.Platform.1.zip)

## Steps to reproduce

1.Preview example
2.Wait few seconds, press blue box
3. Player second jump will bug

## Observed result
When player lands of platform, it will fall through it. 

X&Y vector durning bug - this is always the same when it bugs.
![screenshot 148](https://user-images.githubusercontent.com/28864889/51574782-f3d23980-1eb7-11e9-9d7d-f559830c0024.png)

Vectors when it does not bug.
![piccu1](https://user-images.githubusercontent.com/28864889/51575744-0484ae80-1ebc-11e9-9afb-c6c3de236843.jpg)

## Expected result

No bug

## First affected release
Always

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r135.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 1.2 gb (9.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-01-25 15:21
I can't reproduce your screenshots with the provided project, because the green sprite doesn't move far enough to the left to overlap the red platform next to it. It always stops short. Did you attach the right project?

**Comment by SnipG** [comment] 2019-01-25 15:46
Yes it right project. I too saw different behavior per PC. Also can't reproduce reliable on debug mode....etc. That's why i used text object. I thought maybe it works on your pc, similarly like on mine.

It does two jump, i tried to save 100% accurate cords of first land for 1 jump only, it did not reproduce anymore.

It took long time to get it reproduce almost everytime on my pc, but if its so chaotic, random, and everything affecting it(even different PC). I can't automate such thing. 

It does not affect me, so i give up on this. Someone else who is affected could take over and invest time into it. But if even 1 different tick affects it, i don't think there is much to do.

**Comment by SnipG** [comment] 2019-01-25 15:54
It literally happened between x pos ~ 157.81 - 157.89. I could make fast 1 more try, i trow out alot of sprites, and mark ones that fails. So on your PC you can select/seperate them yourself, as X pos could be different per PC

**Comment by AshleyScirra** [comment] 2019-01-25 15:54
OK, this seems too difficult to reproduce to investigate right now. Thanks for trying anyway, but closing for now - we'll take another look if someone can file another issue with a more reliable reproduction.

**Closed by AshleyScirra** 2019-01-25 15:54 UTC
Labels: can't reproduce

**Comment by SnipG** [comment] 2019-01-25 16:34
I leave it here. If there is someone else.
Takes 1-2 tried to make sprites bug.
[Tinybug.zip](https://github.com/Scirra/Construct-3-bugs/files/2796930/Tinybug.zip)

Same sprites that fail jump, will fall later though other platform, as they are still in state "pass solid". So when they finally fall though some other solid they change theyr state to correct one.

So reproduce could be done for jump or sprites that later fall though some other sprite.

![basbug](https://user-images.githubusercontent.com/28864889/51758917-9dd7de80-20cf-11e9-89a7-7e7c9fb6c687.jpg)
