### ISSUE TITLE
Platform behavior gets sucked down to ledges when trying to jump over (r158 regression))

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#3146] opened 2019-07-17 03:34 UTC
## Problem description

Object with platform behavior gets "sucked" down when trying to jump over a ledge, cutting the jump short and making it land.

## Attach a .c3p

https://www.dropbox.com/s/hg27x7mtv0nr5ff/Tokinsom_PlatformBug.c3p?dl=0

## Steps to reproduce

1. While holding (Right Arrow) to push against the wall, press (Up) to try and jump over it.

## Observed result

Platform object's jump is cut off and is sucked down to the ledge.

## Expected result

Platform object should jump clear over the ledge.

## More details
Pretty certain this is a result of this bug fix in r158: "Platform: in rare cases jumping almost through a jump-thru could get stuck sinking through it"

**Affected browsers/platforms:** 

All platforms, it's a behavior bug.

r158

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2019-07-17 11:44
Probably caused by the fix to #2905, which was a nightmare...

**Comment by AshleyScirra** [comment] 2019-07-17 16:05
I can't reproduce here, it seems to work correctly: [issue3146.zip](https://github.com/Scirra/Construct-3-bugs/files/3402767/issue3146.zip)

Am I missing something?

**Comment by Tokinsom** [comment] 2019-07-17 17:08
@AshleyScirra A friend of mine couldn't reproduce it either so I thought maybe it's my monitor's framerate or something? Sadly I was right - This only happens when running my monitor above 100hz. I can't reproduce it when it's 60hz or below.

This actually explains some of the little quirks I've had with the platform behavior over the last couple years. It appears some aspects of it are not 100% framerate independent.

Video showing results at 144 & 60 w/ the switch: https://www.dropbox.com/s/wb6ywwjf4n3rd1c/2019-07-17%2012-00-03.flv?dl=0

**Comment by AshleyScirra** [comment] 2019-07-18 11:36
Setting the timescale to 0.5 will give you the same delta time values as if you have a 120 Hz display on a 60 Hz display. If I do that I can indeed reproduce it.

**Comment by AshleyScirra** [comment] 2019-07-18 16:21
OK, so this was indeed the fix to #2905 incorrectly kicking in and causing this problem. I've updated the fix for #2905 to be stricter about the precise conditions it kicks in. I think this should both still fix the original problem and prevent this issue from happening, so it should be fixed in the next release. Given the nondeterministic nature of the issue marking this to check when the next release is out for extra verification.

**Comment by AshleyScirra** [comment] 2019-07-22 11:45
r159 is now out, please check again!

**Comment by AshleyScirra** [comment] 2019-08-12 15:15
Had 'need info' tag for 3 weeks with no response; no further reports of a problem though so closing.

**Closed by AshleyScirra** 2019-08-12 15:15 UTC

**Comment by craigsssmith** [comment] 2021-07-09 13:33
I came across this when I was trying to figure out why my players would sometimes 'stick' to ledges (with the Jump Thru behaviour) when jumping past them. It tends to happen most often when the height of the jump is just over the height required to reach the ledge, but I've observed it happening when the player would have travelled at least 16 pixels above the ledge, had the jump been allowed to continue to its full height.

From the comments in this issue and in #2905 it sounds like the issue is due to tiny rounding errors somewhere in the C3 engine. Then I noticed that I had "Fullscreen quality" set to "low" and  "Pixel rounding" incorrectly checked. Disabling "Pixel rounding" fixes the issue.

I don't know whether it's really a bug, but I thought I'd add this comment incase someone else arrives her with the same issue I had.

**Comment by AshleyScirra** [comment] 2021-07-09 15:47
Pixel rounding only affects how things are drawn, and does not affect the logic of the platform movement in any way.

**Comment by craigsssmith** [comment] 2021-07-12 13:46
Yeah, sorry, I realised I'm still seeing the same behaviour afterwards, it just didn't happy when I first tested it, but that's obviously just a coincidence.

Is there any way to disable this behaviour, because it's actually causing a bit of a headache? When the player jumps diagonally up to a platform that has collectables floating just above it, sometime they'll incorrectly stick to it and walk underneath the collectables, even though the initial jump trajectory was such that they would have reached high enough to collect them? In other words, the jump height is being reduced artificially.
