### ISSUE TITLE
Toggle Timeline Enable State in Edit mode crashes C3

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#5952] opened 2022-08-02 08:59 UTC
## Problem description
When I hit the toggle enable state on top to enable/disable all tracks in a timeline C3 crashes.

PS: Holding CTRL to "scrub" on the timeline it does not seem to work to preview it.
Enabling Edit mode and just draging on the timeline shows a preview.

## Attach a .c3p
just open the Animated Splash timeline example (thats where I found it)

## Steps to reproduce

1. open timeline
2. enable edit mode (pencil button)
3. hit checkbox on top to disable all tracks

## Observed result

Crash with error message
## Expected result

no crash :)
## More details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r302/main.js, line 908, col 455
Message: Uncaught TypeError: unexpected type
Stack: TypeError: unexpected type at R.i (https://editor.construct.net/r302/main.js:908:461) at d.xra (https://editor.construct.net/r302/projectResources.js:1096:483) at d.Lrc (https://editor.construct.net/r302/components/editors/layoutView/layoutView.js:157:173) at d.GO (https://editor.construct.net/r302/components/editors/layoutView/layoutView.js:151:77) at Array. (https://editor.construct.net/r302/components/editors/layoutView/layoutView.js:146:9) at window.Cl.dispatchEvent (https://editor.construct.net/r302/main.js:1097:42) at h_b (https://editor.construct.net/r302/components/editors/layoutView/layoutView.js:80:310)
Construct version: r302
URL: https://editor.construct.net/
Date: Tue Aug 02 2022 10:55:40 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 39 s

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 103.0.5060.134
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.2000000476837158
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
302
## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 103.0.5060.134
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.2000000476837158
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 143 gb
Storage usage (approx): 2.8 gb (2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by DiegoScirra** [comment] 2022-08-02 09:50
Can't reproduce the crash, there must be something else to it. 

About hitting ctrl to preview while scrubbing, that was changed during the last beta cycle so that just scrubbing the playhead would preview the timeline.

Now if you press ctrl while scrubbing, the timeline won't be previewed. The change was made because previewing the timeline by scrubbing is a rather important feature and quite a few people thought it was better for that to be the default behaviour.

**Comment by DiegoScirra** [comment] 2022-08-03 13:40
Turns out the problem happens when you set the path mode to cubic bezier.

**Comment by DiegoScirra** [comment] 2022-08-03 15:17
Will be fixed in the next beta, was a regression introduced in r220 as a result from improving the general performance of drawing bezier curves in a layout view.

revision 17544

**Closed by DiegoScirra** 2022-08-03 15:17 UTC
