### ISSUE TITLE
Anchor objects won't keep their positions

### ISSUE THREAD

**Issue by ArtRow** [Scirra/Construct-3-bugs#3678] opened 2020-02-29 17:10 UTC
## Problem description

Anchor objects won't keep their positions if canvas size isn't equal to viewport size of project.

## Attach a .c3p

[Anchor.zip](https://github.com/Scirra/Construct-3-bugs/files/4270609/Anchor.zip)

## Steps to reproduce

Red square (RS further) is a main guest of the test. It's anchored to the bottom edge.
Green square (GS further) is anchored to the top edge.

1. Open attached file and run it
2. Change aspect ratio via 3 buttons. RS and GS keep their position correctly
3. Set any canvas size that doesn't equal to the default (not 4:3).
4. Go to another layout
5. We lost RS. According to debugger it's out of canvas. GS keeps its position
6. If we set ratio to the default. We won't see the RS. It's still outside.
7. To get it back we should set ratio to 4:3 and **change layout** (restarting the layout doesn't work)
8. Our RS is back!

## Observed result

RS is lost if we play on canvas doesn't equal to the default size.

## Expected result

RS should keep their place despite canvas size

## More details

**Affected browsers/platforms:** 

**First affected release:** r182.4 stable

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r182.4 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 44 gb
Storage usage (approx): 658 mb (1.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1660 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2020-03-02 11:39
I think the problem is the Anchor behavior determines the distance to the edge of the viewport before 'On start of layout' runs, but you change the canvas size in 'On start of layout', so it uses the wrong viewport size.

Changing this would probably be a breaking change. I think it would be better to have some way to reset the anchor behavior like there is with the sine behavior.

But why are you doing this anyway? Why ask the player for their aspect ratio and customize the canvas size based on that? If you use 'Scale inner' or 'Scale outer' fullscreen modes, it will just do it for you and it should work fine with the Anchor behavior too.

**Comment by ArtRow** [comment] 2020-03-02 16:31
I'd like to run an app with one aspect ratio, that can be set on previous launch or on the start window. But I'm still looking for best solution.

'Scale outer' shows area user shouldn't see.
'Scale inner' is a good choice. I use it sometimes. Current project was started with that option but it doesn't more suitable. I have to prevent scaling to keep important areas on screen. I just afraid that scaling can be more that it should, even I set all important areas in safe zone. (For example on UWFHD monitors 2560x1080).

But you can allay my fears. I wonder, scale on fullscreen mode and scale on float window work the same? Using 'Scale inner' I can shrink floating window and see just narrow line of game (no black bars). On fullscreen mode on the ultra wide monitors will I see the same? Or game will keep minimal aspect ratio that is set on Viewport size input in construct settings?

**Comment by AshleyScirra** [comment] 2020-03-02 16:43
Why not just letterbox the game in 16:9 in windowed mode and use scale inner in fullscreen mode? That will avoid extreme aspect ratios in windowed mode, and automatically adapt to whatever the aspect ratio is in fullscreen mode, without the user having to do anything.

**Comment by ArtRow** [comment] 2020-03-02 16:58
That sounds I'd like to do, to have minimal ratio that can be adapted to any screen. But I just see "Fullscreen option" and no see options for windowed mode. Do you mean by "_letterbox the game in 16:9 in windowed mode_" set the viewport size of a project?

**Comment by AshleyScirra** [comment] 2020-03-02 17:03
Set the project properties to "Letterbox scale" and use the Browser object's 'Request fullscreen' action to switch in to scale inner for fullscreen.

**Comment by ArtRow** [comment] 2020-03-02 17:05
Thanks a lot!

**Comment by AshleyScirra** [comment] 2020-03-03 13:10
I don't want to make a potentially backwards-incompatible change, and it seems there isn't a need for a new feature for the Anchor behavior if you adjust how the fullscreen mode is handled, so there doesn't seem to be any action to take here, so closing.

**Closed by AshleyScirra** 2020-03-03 13:10 UTC

**Comment by ArtRow** [comment] 2020-03-03 22:33
No problem,
if you don't mind, I'll leave here last comment. I've spent a lot of time exploring anchor. If you will come back to that issue, it might be useful.
![001++](https://user-images.githubusercontent.com/46167226/75826130-d90b0d80-5db7-11ea-8c13-80ebd8385f35.png)



********
Under this line info not about issue. Just explanation why I'm using two scales in one project and found that anchor issue. I calculate the screen ratio just once at the app start (before fullscreen request). So the app doesn't changes its canvas till next launch.
<details><summary>Code</summary>

![003](https://user-images.githubusercontent.com/46167226/75821806-f340ed80-5daf-11ea-8e9c-b3f2708ca1c9.png)

</details>

![002](https://user-images.githubusercontent.com/46167226/75821055-9d1f7a80-5dae-11ea-87b2-2cbe6d2f826a.png)
