### ISSUE TITLE
"script minify" seems broken

### ISSUE THREAD

**Issue by kop9000** [Scirra/Construct-3-bugs#1163] opened 2018-01-10 22:02 UTC
I today exported the new version of the project to html5 format with the "minify script" setting, but it seems like after the export the project does not want to run in any browser. just a black screen.

Without configuring the "minify script" the project is working fine

http://v90421ou.beget.tech/gnrt/

[GE-NE-RA-TOR pre alfa 0.023.zip](https://github.com/Scirra/Construct-3-bugs/files/1620588/GE-NE-RA-TOR.pre.alfa.0.023.zip)

**Comment by AshleyScirra** [comment] 2018-01-10 22:06
It looks like you use the Physics behavior, so this would be a duplicate of #560.

**Closed by AshleyScirra** 2018-01-10 22:06 UTC

**Comment by kop9000** [comment] 2018-01-10 22:19
Tell me please, what should I do?

**Comment by AshleyScirra** [comment] 2018-01-11 09:57
Don't minify on export for the time being.

**Comment by kop9000** [comment] 2018-01-11 18:28
as it turned out this behavior was superfluous in my project. it was a little test
