### ISSUE TITLE
App Crash in Sprite Editor

### ISSUE THREAD

**Issue by 8bitThirsty** [Scirra/Construct-3-bugs#423] opened 2017-06-02 11:01 UTC
Got another crash in the sprite editor. It crashed twice in a row the first time it completely froze and wouldn't let me click the buttons to copy the crash report or save my work. Then I opened the project and attempted to load images more images into an already created animation. The issue was with the "Up" animation on the Sagan sprite.

[Bitmen.zip](https://github.com/Scirra/Construct-3-bugs/files/1047477/Bitmen.zip)

Error report information
Type: unhandled exception
File: https://editor.construct.net/r32/main.js, line 2, col 202615
Message: Uncaught Error: animation frame has no content
Stack: Error: animation frame has no content at h.ǃiRI (https://editor.construct.net/r32/main.js:61:188769) at h.ǃcf (https://editor.construct.net/r32/main.js:61:192577) at ǃNr.ǃlsd.ǃNr.ǃJV (https://editor.construct.net/r32/main.js:71:36945) at ǃNr.ǃlsd (https://editor.construct.net/r32/main.js:71:44908) at Function.ǃi.ǃa (https://editor.construct.net/r32/main.js:2:202594) at Function.ǃMW (https://editor.construct.net/r32/main.js:71:320594) at Function.ǃlML (https://editor.construct.net/r32/main.js:71:320464) at Function.s.ǃiBu.ǃlAG (https://editor.construct.net/r32/main.js:71:325752) at a.ǃlCi.ǃJh (https://editor.construct.net/r32/main.js:71:239337) at Array.ǃnu (https://editor.construct.net/r32/main.js:71:232706)
Construct 3 version: r32
URL: https://editor.construct.net/
Date: Wed May 31 2017 13:17:16 GMT-0400 (Eastern Daylight Time)
Uptime: 50.8 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.71
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.71 Safari/537.36
C3 release: r32

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by DiegoScirra** [comment] 2017-06-02 16:07
I can't reproduce this one.

By looking at the crash report I can tell you were trying to set an image point, and that is what caused the crash.

**Comment by DiegoScirra** [comment] 2017-06-07 13:36
Fixed in r36

**Closed by DiegoScirra** 2017-06-07 13:36 UTC
Labels: no repro
