### ISSUE TITLE
Drag and drop does not work

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1556] opened 2018-05-08 16:31 UTC
## Problem description

*Enter a concise description of your problem here*
You can not drag and drop from the properties window to the layout window, not project specific, happens in all projects, limited but to Mobile UI, seems a conflict with the menu swipe routine, I switched to desktop UI and I could drag and drop, switched back to Mobile UI and I could not drag and drop

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Create a new tile map object in the project window
2. Try to drag and drop it to the layout (not possible)
3.

## Observed result

*What do you see happen?*
You can create objects on the project window, but can’t add them to the layout

## Expected result

*What did you expect to happen instead?*
Need to be able to drag from the project window to the layout window

## Affected 
* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 11.0
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: iOS
Operating system version: 11.3
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPad; CPU OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
C3 release: r99 (beta)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
The Clipboard API is not supported. Some clipboard features may be unavailable.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Downloading local content is not supported.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Metal - 52.3.2)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Apple Inc.
Renderer: Apple A10X GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions:

EXT_blend_minmax
EXT_sRGB
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_depth_texture
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by zumwaltwood** [comment] 2018-05-08 18:30
Same behavior on my Samsung galaxy s7, can't drag and drop from the object tree, not only that, i can't scale existing objects in the layout, I'll keep playing around with that and file a separate bug report if i can't figure it out

**Comment by AshleyScirra** [comment] 2018-05-14 12:12
This is currently by design due to the aforementioned intention to only use mobile for light editing/review work rather than productivity work. This is one of the features that has simply not been transferred from desktop to mobile yet, but I'll leave this open to investigate how easy it would be to enable. (There are many subtleties to the differences between a click, tap and drag, so this isn't necessarily as obvious as it might seem.)

**Comment by KelseyHigham** [comment] 2018-05-19 11:53
I ran into this once. I wasn’t expecting dragging to work, because there isn’t enough room for that operation on a 320px wide screen. I was expecting to find a fallback in a context menu; something like “[Properties] Sprite -> Add to layout”, or “[Layout] -> Insert new instance”, or “[Properties] Sprite -> Copy”.

**Comment by AshleyScirra** [comment] 2018-06-29 14:59
I've essentially done @KelseyHigham's idea for the next release: the Project Bar menu for objects now has a "Create instance" option, which simply drops a new instance in the middle of the screen on the current layout. It's not quite drag-and-drop but it does mean there is at least some way to add new instances with the mobile UI.

**Closed by AshleyScirra** 2018-06-29 14:59 UTC
Labels: enhancement, mobile
