### ISSUE TITLE
Can't download exports on Chrome Version 65.0.3325.181 (64-Bit)

### ISSUE THREAD

**Issue by DasBilligeAlien** [Scirra/Construct-3-bugs#1449] opened 2018-03-29 19:36 UTC
## Problem description

When I try to download an Export in Chrome Version 65.0.3325.181 (64-Bit) the Browser flickers like when trying to open a new tab and nothnin happens. The downloads are logged in the export manager but I can't download then there either. 

I tried turning of my browser plugins but it did not help.

## Attach a .c3p
Was exportet using edge.
[MinDreams.zip](https://github.com/Scirra/Construct-3-bugs/files/1861652/MinDreams.zip)

## Steps to reproduce

 Can't reproduce outside my own computer/google acocunt.
1. Go to export.
2. clike any type of export.
3. wait until it is finished
4. click on download export
5. browser flickers.
6. no download

## Observed result

Flicker, then nothing.

## Expected result

A download in the browser. 

## Affected browsers

* Chrome: yes (but only the version on my computer)
* Firefox: -
* Edge: no
* Safari: no

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 6.8 gb
Storage usage (approx): 194 mb (2.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2018-03-30 10:43
Can't reproduce here, I have that exact version of Chrome. The screen does flicker as if it briefly opens a tab and closes it, but it still successfully downloads the export. (Might be worth checking if disabling browser addons helps.)

Still Chrome shouldn't be trying to open a new tab there so I might report that to Google.

**Comment by DasBilligeAlien** [comment] 2018-03-30 13:13
OK. Culprit seems to be the following browser extensions:

UBlock - When UBlock is tunred on I can't download. But I am sure it was
possible in the past.

windscribe - Also the Windscribe Browser extension. I have to whitelist the
editor for it to work. Again I am sure it worked without before. The VPN is
not active just the adblock functionality.

Anyway I found a workaround for me. I just turn them off to export then
back on. Maybe both are a bit overkill anyway.

Thanks for your time!

Best Wishes
Alban

2018-03-30 12:43 GMT+02:00 Ashley (Scirra) <notifications@github.com>:

**Comment by AshleyScirra** [comment] 2018-04-05 17:05
OK, I can reproduce when using UBlock. It does report that it's blocked the download by incrementing the number in the toolbar. Browser extensions can pretty much block anything for any reason so if you use them you should be on the lookout for blocked features like this. I suspect that Chrome shouldn't be attempting to open a new window either, which may also be why UBlock blocks the download (since it thinks it's a popup window or something).

I've filed two bugs to investigate both sides of this:
https://bugs.chromium.org/p/chromium/issues/detail?id=829427
https://github.com/uBlockAdmin/uBlock/issues/1754

I don't think the problem is in Construct - if it only breaks when you install UBlock (or some other extension) then it's most likely the browser extension causing it. So closing this issue and will follow up at those other reports.

**Closed by AshleyScirra** 2018-04-05 17:05 UTC
Labels: browser extension
