### ISSUE TITLE
Can't change layers on objects dropped onto overridden global layers

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#1394] opened 2018-03-16 19:23 UTC
## Problem description

It's not possible to change the layer of objects dropped onto global layers if the global layer was created in a different layout.

## Attach a .c3p

[GlobalLayerBug.zip](https://github.com/Scirra/Construct-3-bugs/files/1820547/GlobalLayerBug.zip)

## Steps to reproduce

1. Create a new project, add a second layout ("GlobalLayout")
2. In GlobalLayout, set the layer to global ("GlobalLayer")
3. Create a sprite, and place it in GlobalLayer.
4. In the first layout, add a layer to the top of the layer list and call it "GlobalLayer"
5. With GlobalLayer active, drag and drop a sprite into the layout.
6. In the properties view for the sprite, click the Layer dropdown.

## Observed result

Only "GlobalLayer" is available.

## Expected result

The user should be able to move objects out of the global layer using the dropdown.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 65.0.3325.162
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36
C3 release: r91 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 241 mb (0.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2018-03-19 12:20
It's actually listing all the layers of GlobalLayout. If you add an extra layer to GlobalLayout you'll see it in the list there too. It sort-of makes sense since objects on a global layer actually belong to the layout they were created on. When you see global layers in other layouts, you're essentially seeing imported instances from another layout. At the moment selecting them works the same as if you selected them on their own layout. On the other hand it seems reasonable to expect the current layout's layers to show up in that drop-down. I'm not sure how easy this would be to change though, currently the only way we derive the layout is by checking which the object itself belongs to, and if changed then the layer dropdown also becomes a way you can actually move instances between layouts.

**Comment by AshleyScirra** [comment] 2018-06-29 14:08
I think we will close this as wontfix since arguably it's working as intended. Global layers are slightly confusing in that they display instances from other layouts, but if you understand that then the way it currently work does make sense.

**Closed by AshleyScirra** 2018-06-29 14:08 UTC
Labels: usability, wontfix
