### ISSUE TITLE
iOS application hangs on startup, or there is no sound

### ISSUE THREAD

**Issue by Salfer13** [Scirra/Construct-3-bugs#4484] opened 2021-01-17 17:01 UTC
## Problem description

(Ios only)
I have 300+ layouts in my project and if I remove the audio plugin then the project loads and works.
I removed 150 layouts and the project loads successfully even with the audio plugin.
I don't understand what the connection between sound and layouts has to do with it, but it works.
I spent two days looking for the source of this problem.
If you uncheck the box (preload sound), then the project will load successfully, but there will be no sound with a 70% chance.

## Attach a .c3p

[Sleepy Ad.c3p](https://drive.google.com/file/d/17vt6dAf5UOfTxwbJOqymzdksrCIx6H1F/view?usp=sharing)
[X-Code 14.0+](https://drive.google.com/file/d/1XJdKbpjiyNcjmoGP5oyxmEwGTFEqfG2I/view?usp=sharing)

## Steps to reproduce

This error only reproduces on ios and ios emulator
We launch the application on iOS (with a 70% chance it will freeze on loading)
If you uncheck the sound preloading, then with a 70% chance the application will not have sound.

## Observed result

stuck boot process

## Expected result

the app is loaded with sound and will work

## System details

I hope this helps you.

2021-01-15 15:39:10.164711+0300 Sleepy Adventure[471:16544] Apache Cordova native platform version 6.1.0 is starting.
2021-01-15 15:39:10.164837+0300 Sleepy Adventure[471:16544] Multi-tasking -> Device: YES, App: YES
2021-01-15 15:39:10.275512+0300 Sleepy Adventure[471:16544] The preference key "AllowNewWindows" is not defined and will default to "FALSE"
2021-01-15 15:39:10.277377+0300 Sleepy Adventure[471:16544] The preference key "MediaPlaybackAllowsAirPlay" is not defined and will default to "TRUE"
2021-01-15 15:39:10.282963+0300 Sleepy Adventure[471:16544] The preference key "AllowBackForwardNavigationGestures" is not defined and will default to "FALSE"
2021-01-15 15:39:10.283033+0300 Sleepy Adventure[471:16544] The preference key "Allow3DTouchLinkPreview" is not defined and will default to "TRUE"
2021-01-15 15:39:10.283065+0300 Sleepy Adventure[471:16544] CDVWebViewEngine will reload WKWebView if required on resume
2021-01-15 15:39:10.283098+0300 Sleepy Adventure[471:16544] Using WKWebView
2021-01-15 15:39:10.283428+0300 Sleepy Adventure[471:16544] [CDVTimer][console] 0.057101ms
2021-01-15 15:39:10.283598+0300 Sleepy Adventure[471:16544] [CDVTimer][handleopenurl] 0.058055ms
2021-01-15 15:39:10.284838+0300 Sleepy Adventure[471:16544] [CDVTimer][intentandnavigationfilter] 1.183987ms
2021-01-15 15:39:10.284993+0300 Sleepy Adventure[471:16544] [CDVTimer][gesturehandler] 0.074983ms
2021-01-15 15:39:10.285191+0300 Sleepy Adventure[471:16544] [CDVTimer][inappbrowser] 0.155091ms
2021-01-15 15:39:10.286367+0300 Sleepy Adventure[471:16544] [CDVTimer][statusbar] 1.098990ms
2021-01-15 15:39:10.286447+0300 Sleepy Adventure[471:16544] [CDVTimer][TotalPluginStartup] 3.141999ms
2021-01-15 15:39:10.328999+0300 Sleepy Adventure[471:16544] WF: === Starting WebFilter logging for process Sleepy Adventure
2021-01-15 15:39:10.329046+0300 Sleepy Adventure[471:16544] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2021-01-15 15:39:10.329090+0300 Sleepy Adventure[471:16544] WF: _WebFilterIsActive returning: NO
2021-01-15 15:39:10.611024+0300 Sleepy Adventure[471:16544] IAB.close() called but it was already closed.

</details>

**Comment by AshleyScirra** [comment] 2021-01-19 16:01
I ran your Xcode project on an iPad five times and it successfully started up and played audio every time. I also took your .c3p file, built an Xcode project myself, and also ran that on the device; it also successfully played audio every time. I'm afraid there's little we can do to help unless you can find a reliable way to reproduce the problem.

**Comment by Salfer13** [comment] 2021-01-19 16:57
good day. I think the iPad is more powerful than the iPhone, so you don't have this problem. Try using an emulator in x-code. I have this problem reproduced on both the iPhone and the emulator.

**Comment by AshleyScirra** [comment] 2021-01-19 17:22
If the issue only happens because you are exceeding the hardware capabilities, such as running out of memory, then that is an issue with your game design, not Construct.

**Comment by Salfer13** [comment] 2021-01-19 17:41
In this example, what I threw is only layouts.
Is there an excess of hardware capabilities?

**Comment by AshleyScirra** [comment] 2021-01-20 10:50
Probably not, but I couldn't reproduce any problem with it either.

I'm afraid without a way to reproduce the problem, and the fact that your description appears to suggest an issue like exceeding the memory limits of the device (especially since preloading sounds will use more memory, and a minimal project that uses less memory does not appear to reproduce the problem), there doesn't appear to be anything we can do, so closing.

**Closed by AshleyScirra** 2021-01-20 10:50 UTC
Labels: can't reproduce, iOS

**Comment by Boulerzzz** [comment] 2021-02-16 14:21
@Salfer13 did you ever find a solution to this issue?

We have run into the same issue and the only solution to reliably launch the app seems to be by disabling "preload sounds". But then there won't be any sound at all most of the times.

We have this issue on physical iphone XS max (14.4) Ipad (14.4) and iphone 6s (13.7) as well as in the simulators.

I removed all the sound files and the game launches without any problem with "preload sounds" enabled. With even just 1 sound we have this problem. I'll try to reproduce in a minimal project tomorrow!

**Comment by Boulerzzz** [comment] 2021-02-16 17:30
Ok, so I tried for a few hours but could not reproduce this issue in a small project.

I decided to just change the "Cordova IOS scheme" to "Legacy" which solved all of my problems. Everything works as expected in "Legacy" mode.
