### ISSUE TITLE
System -> Wait Action clears local variables

### ISSUE THREAD

**Issue by thumbender** [Scirra/Construct-3-bugs#3297] opened 2019-09-04 07:11 UTC
## Problem description

System -> Wait Action clears local variables

## Attach a .c3p

[bugreport04092019.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3573151/bugreport04092019.c3p.zip)

## Steps to reproduce

1. set a local variable to 10
2. wait 1 sec
3. check value of local variable

## Observed result

local variable = 0

## Expected result

local variable = 10

## More details

Tested on chrome

**Affected browsers/platforms:** 

first noticed on R164

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.132
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_0
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
C3 release: r164 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 21 gb
Storage usage (approx): 530 mb (2.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by NetOneGames** [comment] 2019-09-04 09:05
Possibly to be expected as local variable is reset once its set of events are run and/or is reset every tick.  can be fixed by making it static.

**Comment by AshleyScirra** [comment] 2019-09-04 10:42
This is currently by design. The local variable is not static, so resets its value when the events in its scope finish. The wait means the block has finished before it resumes running the actions. You can work around this by just making the local variable static, or using function parameters, which are captured across waits.

**Closed by AshleyScirra** 2019-09-04 10:42 UTC
Labels: not a bug

**Comment by thumbender** [comment] 2019-09-04 11:49
Awesome, now I understand and see it as a feature instead of a bug. It just wasn't what I expected. Thank you for the prompt feedback!
