### ISSUE TITLE
Game won't load on Android Stock Browser (works on iOS)

### ISSUE THREAD

**Issue by Ninjadoodle** [Scirra/Construct-3-bugs#605] opened 2017-07-11 09:26 UTC
## Problem description

Game won't load on Android Stock Browser - GALAXY S7 ( works on iOS )

I've attached the minigame, and here is also a link for a quick test ...

[http://ninjadoodle.com/levels/level-12/](url)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
[L0000.zip](https://github.com/Scirra/Construct-3-bugs/files/1138353/L0000.zip)

## Steps to reproduce

1. Try to load the game in an Android Stock Browser

## Observed result

Game won't load

## Expected result

Game should load

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE ( Didn't see a crash )

</details>

**Comment by AshleyScirra** [comment] 2017-07-21 14:09
I assume you are using the Samsung Internet browser, which is actually different to the Android stock browser. It's the default on a Samsung Galaxy S8, and I could reproduce the issue there, so I assume you're really using that.

It turns out this is a bug in the Samsung browser; it indicates it supports WebM Opus audio but then fails to decode it. I filed an issue with Samsung [here](https://github.com/SamsungInternet/support/issues/14), and will follow up there, so closing this issue. Chrome for Android should still work though.

**Closed by AshleyScirra** 2017-07-21 14:09 UTC

**Comment by Ninjadoodle** [comment] 2017-07-22 00:29
Yeah, that's the one - that's a bit of a bummer as a lot of people use these phones / browsers. I hope this gets fixed by samsung. Thank you for filing the bug with them.

**Comment by AshleyScirra** [comment] 2017-08-10 12:57
I've tried the latest Samsung Internet beta and it's fixed. It should just be a matter of time for that to make its way to full release now.

**Comment by Ninjadoodle** [comment] 2017-08-10 13:19
Awesome, thank you heaps for following this up, I really appreciate it :)
