### ISSUE TITLE
Construct 3 on Ios does not saves login details or any changes 

### ISSUE THREAD

**Issue by newman321** [Scirra/Construct-3-bugs#890] opened 2017-10-06 07:49 UTC
open construct 3 on safari on ios 11  add it to home screen after that home screen version wont save any options after reopining the app icon

**Comment by AshleyScirra** [comment] 2017-10-06 10:28
Full steps to reproduce are as follows. Please remember to always follow the bug report guidelines to ensure we can help you.

1. Log in to editor.construct.net in Safari browser and tick "remember me"
2. Reload page and observe that you remain logged in
3. Open as "add to home screen app"; notice that you are not logged in
4. Try to log in and tick "remember me" again
5. Close the app and reload it
6. Still not logged in after restart

**Comment by TinyMartian** [comment] 2017-10-07 17:32
I would like to add that closing the app in iOS 11.0.2 on an iPad Pro (1st gen) completely closes the app including any project you were working on. Even switching apps (like checking your messager app) logs you out and closes your project.

**Comment by TinyMartian** [comment] 2017-10-07 19:02
One more thing, this only seems to be an issue when you run C3 as app from the home screen. If you open it from within Safari, close Safari and then reopen it, Safari remembers you. Not sure if that helps any.

**Comment by AshleyScirra** [comment] 2018-01-19 14:14
This issue is a combination of two iOS bugs. The first is that if you save anything in Safari, it is not loaded in a home screen web app. I filed a bug with Apple about this here: https://bugs.webkit.org/show_bug.cgi?id=181849

The second issue is that for security reasons our login form is hosted on a different origin, and home screen web apps never remember any cross-origin storage at all. This means your login is never remembered if you log in via the home screen. I filed a second bug with Apple about this here: https://bugs.webkit.org/show_bug.cgi?id=181850

This is entirely up to Apple to fix now, so closing this issue; follow up on those two bug reports for more progress.

**Closed by AshleyScirra** 2018-01-19 14:14 UTC
Labels: external, mobile, safari

**Comment by fedeali90** [comment] 2019-08-25 18:04
Any news on it? I’m experiencing these problems with latest C3 stable release on an iPad Pro (2nd gen) running iOS 12.4.

**Comment by tatosgames** [comment] 2019-11-04 02:30
Please, any way to workaround it? Construct in free version is quite unusefull...

**Comment by AshleyScirra** [comment] 2021-10-08 10:10
We already do use the Storage Access API. Unfortunately Safari seems to ignore that too. I'm not sure what we're supposed to do to make it work with our architecture.
