### ISSUE TITLE
Line Of Sight behavior falsely returning true/false values after multiple LOS are true

### ISSUE THREAD

**Issue by Rhindon** [Scirra/Construct-3-bugs#4515] opened 2021-01-29 08:20 UTC
## Problem description

_I believe this issue is more nuanced than what I will be reporting here, but I will try to be as accurate as can be per what I'm trying to do in my game and what I have further found in my debug efforts.

UPDATE: In the forum post (link below) fellow C3 user, dop2000, suggested that I remove the player object, "MrSpy" from the list of custom obstacles for the enemy Guards. That detail seems to have resolved my immediate problem for my game. I further commented that my adding the player object at all might have been on accident and I just didn't catch it - I don't remember why I would have added MrSpy as an obstacle at all to begin with. However, the stand-alone issue of LOS as detailed below and via the debug C3P file attached to this report is still viable as far as I can tell._

**MY GAME**
Further details can be found here: [https://www.construct.net/en/forum/construct-3/how-do-i-8/1st-instance-object-not-158025](https://www.construct.net/en/forum/construct-3/how-do-i-8/1st-instance-object-not-158025)
This post also contains a .c3p link for my game as is so far. It may prove further helpful.

In my game, I'm using Line Of Sight (LOS) to determine when a player can "steal" an item from an enemy. This requires that 1) the player has LOS to the enemy and 2) the enemy does not have LOS to the player.
When these conditions were true, and the player holds down a button and a meter build up to complete the pilfering.

The problem is that once the first instance of one of the two enemies has LOS to the player, it never seems to register as having no LOS even when clearly out of range.

**DEBUG C3P**
I created a separate (and minimal) setup of the scenario I described above (see attachment to this log).

When the GoodGuy object moves in range of any of the individual BadGuy objects, they will correctly register True LOS. Moving out of range registers a False LOS. As one would expect. However, if GoodGuy moves into the LOS range of both instances of the BadGuy object, and then moves out of range of only one of them (keeping in range of the other), they will both continue to register as True LOS when only one should still be True.

I added two BadGuy objects - red and orange - and created two instances of each. Both have overlapping LOS ranges (ven diagrams anyone?). Where the red and orange instances overlap, there is no issue. If the GoodGuy is in the range of both a red and an orange BadGuy, they will register the correct LOS status as the GoodGuy moves in and out of range.

So the problem seems isolated to C3 not differentiating an instance-by-instance basis of the same object.

## Attach a .c3p

[Mr Spy Micro-Missions Instance Not Working.zip](https://github.com/Scirra/Construct-3-bugs/files/5892405/Mr.Spy.Micro-Missions.Instance.Not.Working.zip)

## Steps to reproduce

1. Position multiple instances of an object with LOS.
2. Ensure that their LOS ranges overlap.
3. Move the object that the LOS object is checking for into the LOS range for one of the LOS objects, and then out of range. Confirm that the LOS object returns a true and then false value as expected.
4.  While still in range of one LOS object instance, move the object to be detected into a second LOS object's range so that both instances have LOS-is-true values.
5. Now move the object to be detected out of range of just one of the LOS objects. Confirm that both LOS object instances still return true values even though only one should actually still be true.

## Observed result

In my debug .c3p file (the one attached to this bug report), I observed that moving the object into range of multiple, simultaneous LOS objects keeps all instances of that object as LOS-is-true even after moving out of range of at least one of them.

In my game, the issue seems further compounded in that simply moving into the LOS of one instance leaves that instance in a constant LOS-is-true state, even if I never move into the LOS range of the second instance.

## Expected result

In both my debug and my current game files, I expect that moving into any LOS object's range will return a True value. Moving out of range will return a False value - regardless if the object I'm controlling is still in range of another instance of the same object or not.

## More details

**Affected browsers/platforms:** 

CHROME: Version 88.0.4324.104 (Official Build) (64-bit)
CHROME (mobile): Version 88.0.4324.93 (on OS Android 11, Pixel 3 Build/RQ1A.210105.003)
MS EDGE: Version 88.0.705.53 (Official build) (64-bit)

**First affected release:** 

C3 R225
NOTE: I managed to have this feature in my game working while using the same release version. I haven't made any particular changes to this part of my game once I got it working. So, I can't rule it out as a possibility, but I highly doubt it has anything to do with my current setup in the event sheet.

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 88.0.4324.104
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
C3 release: r225 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 142 gb
Storage usage (approx): 97 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2021-01-29 10:39
Please see the bug report guidelines - we can't debug such complex projects, and usually people reporting bugs with complex projects have actually just made a mistake in their events. Can you provide a minimal project as per the guidelines?

**Comment by Rhindon** [comment] 2021-01-29 17:38
My apologies for any hassle and/or confusion. The primary issue is the LOS behavior as detailed in the .c3p attached to this report - how the LOS behavior returns True when two instances of an LOS object has LOS to an object and then moves out of range of just one them yet both still return LOS as True.

The references to my personal project and my use of LOS was only meant as a supplement to try to help isolate the problem. If it helps, my personal project can be ignored for now. Do I need to resubmit or edit this post sans info about my personal project?

**Comment by AshleyScirra** [comment] 2021-01-30 11:20
Please see the bug report guidelines, they explain what to do. The key things are a minimal project and reliable steps to reproduce the problem. If you cannot reproduce the problem in a minimal project, it's probably just a mistake in your events, and therefore not something we deal with in bug reports. Closing this issue, please start over with a new report if you can attain these.

**Closed by AshleyScirra** 2021-01-30 11:20 UTC
