### ISSUE TITLE
Problem with C3 runtime and 'Force own Texture' setting: objects display incorrectly

### ISSUE THREAD

**Issue by lukasinspace** [Scirra/Construct-3-bugs#2294] opened 2018-11-11 12:55 UTC
## Problem description
Objects are displayed incorrectly when placed onto a layer that is set to 'Force own Texture' and C3 runtime is enabled. When previewed Sprite or 9patch objects either disappear from view or are positioned incorrectly within the layout (off to one side for example).

This problem doesn't occur when C2 runtime is enabled OR if C3 runtime is enabled and 'Force own Texture' is deselected. Problem only occurs when C3 runtime is enabled and 'Force own Texture' is selected.

## Attach a .c3p
[c3runtime bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2569366/c3runtime.bug.zip)

## Steps to reproduce

1. In a new C3 project create two layers. 
2. On the top layer place a 9 patch object and a sprite object. 
3. Set the top layer to 'Force own Texture'.
4. On the bottom layer place a sprite object and set its size to match the width and height of layout so as to completely cover the layout. 
5. Set runtime to 'C3 runtime'.
6. Preview the project.

## Observed result
The 9patch and sprite objects on top layer (which is set to 'Force own Texture')  either disappear from view, or seem to get shunted off to the side of the screen. The objects on top layer do not displayed as expected. 

## Expected result
Expect to see the 9patch object and sprite object on top layer positioned in the layout exactly as seen in the editor.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r124 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 32 gb
Storage usage (approx): 104 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment] 2018-11-12 11:17
I think this is another case of #2274 which should be fixed in the next build (can't reproduce in development copy here). Please file again if there's still an issue in the next release.

**Closed by AshleyScirra** 2018-11-12 11:17 UTC
