### ISSUE TITLE
Crashes when dragging in image

### ISSUE THREAD

**Issue by fingerskier** [Scirra/Construct-3-bugs#5328] opened 2021-12-23 15:52 UTC
## Problem description

Construct crashes when dragging in an image.

## Attach a .c3p

Did.

## Steps to reproduce

Drag in the image from this link (Chrome & Firefox) to the open sprite editor:
https://cdn-icons-png.flaticon.com/512/190/190238.png

## Observed result

Construct crashes

## Expected result

Image is pasted into the editor.

**Affected browsers/platforms:** 

Same on Chrome & Firefox

<details><summary>View details</summary>
Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'length') @ TypeError: Cannot read properties of undefined (reading 'length') at f_a.lbc.TM (https://editor.construct.net/r276-2/projectResources.js:2156:80)
Stack: TypeError: Cannot read properties of undefined (reading 'length') at f_a.lbc.TM (https://editor.construct.net/r276-2/projectResources.js:2156:80)
Construct 3 version: r276.2
URL: https://editor.construct.net/
Date: Thu Dec 23 2021 09:50:25 GMT-0600 (Central Standard Time)
Uptime: 45.5 s

Platform information
Browser: Chrome
Browser version: 96.0.4664.110
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
C3 release: r276.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.9664)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2
</details>

**Comment by AshleyScirra** [comment] 2022-01-03 12:38
It works fine here.

Assigning to @DiegoScirra in case he can find anything out from this, but we will likely need more detailed information about precisely what you are doing to be able to investigate this.

**Comment by DiegoScirra** [comment] 2022-01-04 14:37
Will be fixed beta r278. The problem is caused by dragging a image straight from one browser tab into another tab that is showing the Animations Editor.

**Comment by AshleyScirra** [comment] 2022-01-04 14:44
Updating milestone and closing issue.

**Closed by AshleyScirra** 2022-01-04 14:44 UTC
