### ISSUE TITLE
[C3 Desktop] Minor Issue With Display Scale Dialog

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#2198] opened 2018-10-29 15:56 UTC
## Problem description

The dialog to restart Construct 3 in order for display scale changes to apply repeats after a restart. This doesn't seem to be necessary since the restart has already been performed.

## Steps to reproduce

1. Open Construct 3 Desktop
2. Change display scale level (Menu > Level > Display scale > Inc/Dec scale)
3. Notice dialog asking for restart and click on "OK"
4. Manually restart Construct 3 Desktop Application
5. Resize the window or maximize it
6. Notice same dialog asking for a restart, despite an already performed restart

## Observed result

Display scale restart dialog repeats itself after performing a restart.

## Expected result

Display scale restart dialog should only display after display scale changes have been performed and not repeat itself after a restart.

## Affected browsers

* NW.js: yes
## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.33.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@8920e690dd011895672947112477d10d5c8afb09) NWjs/0.33.3 (like Chrome/69.0.3497.100)
C3 release: r123 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 117 gb
Storage usage (approx): 440 kb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2018-10-29 17:20
I can't reproduce this. No prompt appears for me after restarting Construct 3 after altering the display scale.

**Comment by TheRealDannyyy** [comment] 2018-10-29 17:30
I've been using the beta release, might be beta only? I also have to maximize the window again after the restart in order for it to appear.

**Comment by AshleyScirra** [comment] 2018-11-07 15:46
Thanks, I think I was missing the "resize the window" step before. Looks like a race condition loading the last zoom level with saving the current zoom level (aka devicePixelRatio), which probably was also causing #2199. Should be fixed in the next release.

**Closed by AshleyScirra** 2018-11-07 15:46 UTC
Labels: can't reproduce, desktop

**Comment by TheRealDannyyy** [comment] 2018-11-07 15:58
Will check both issues out when the next update is released. Thanks for the quick fix.

**Comment by TheRealDannyyy** [comment] 2018-11-12 14:39
I can confirm that issue #2199 and this one have been fixed. Thanks for that!

However there seems to be another issues related to restoring the window state, while using a modified display scale. Opened a new issue for that here: #2304
