### ISSUE TITLE
action "go to layout" doesn't work if behavior "tween" has loop set.

### ISSUE THREAD

**Issue by fedboi** [Scirra/Construct-3-bugs#4026] opened 2020-07-11 09:13 UTC
## Problem description

action "go to layout" doesn't work if behavior "tween" has loop set.

## Steps to reproduce

1. create sprite with tween beviour.
2. set tween with loop active
3. call action: Go to layout

## Observed result
crash

## Expected result

go to layout

## System details

Uncaught (in promise) TypeError: Cannot read property 'GetObjectClass' of null
at f.Tween._OnBeforeChangeLayout (tween.js:6)
at c.TimelineManager._OnBeforeChangeLayout (timelineManager.js:14)
at Array._beforeLayoutChange (timelineManager.js:2)
at e.Event.Handler._FireNonCancellable (handler.js:5)
at d.Event.Dispatcher.dispatchEvent (dispatcher.js:2)
at c.Runtime._DoChangeLayout (runtime.js:60)
at async c.Runtime._MaybeChangeLayout (runtime.js:58)
at async c.Runtime.Tick (runtime.js:53)

**Comment by Visual917** [comment] 2020-07-11 09:59
I have the same issue.
Example c3p: https://drive.google.com/file/d/1YZolMecBs6BDN3mVdUu8IJz086Ex2t2V/view?usp=sharing

**Comment by sizcoz** [comment] 2020-07-11 11:21
Having exactly the same issue.
Uncaught (in promise) TypeError: Cannot read property 'GetObjectClass' of null
    at f.Tween._OnBeforeChangeLayout (tween.js:6)
    at c.TimelineManager._OnBeforeChangeLayout (timelineManager.js:14)
    at Array._beforeLayoutChange (timelineManager.js:2)
    at e.Event.Handler._FireNonCancellable (handler.js:5)
    at d.Event.Dispatcher.dispatchEvent (dispatcher.js:2)
    at c.Runtime._DoChangeLayout (runtime.js:60)
    at async c.Runtime._MaybeChangeLayout (runtime.js:58)
    at async c.Runtime.Tick (runtime.js:53)

**Comment by DiegoScirra** [comment] 2020-07-12 09:12
Duplicate of #4011. See the comments in that issue for a few more details. The issue is not related to the loop setting, just changing layout when a tween is playing will crash the runtime.  This one will be fixed for the next beta.

**Closed by DiegoScirra** 2020-07-12 09:12 UTC
Labels: duplicate
