### ISSUE TITLE
Crash when rotating & undoing sprite.

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#6589] opened 2023-02-20 13:36 UTC
## Problem description

I'm not sure what specifically causes this crash but it reliably crashes.

## Attach a .c3p

[rotatecrash.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/10784907/rotatecrash.c3p.zip)

## Steps to reproduce

1. Rotate the sprite on the layout
2. Ctrl+Z

## Observed result

Crash

## Expected result

.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: expected finite number @ TypeError: expected finite number at O.m (https://editor.construct.net/r330/main.js:1030:407) at d.gca (https://editor.construct.net/r330/projectResources.js:823:238) at aYa.Sba.ef (https://editor.construct.net/r330/projectResources.js:1886:247) at window.sc.Ch (https://editor.construct.net/r330/projectResources.js:1859:319) at d.Ch (https://editor.construct.net/r330/projectResources.js:1736:9) at window.ueb.Ch (https://editor.construct.net/r330/main.js:2509:310) at Array. (https://editor.construct.net/r330/main.js:2482:496) at window.ueb.dispatchEvent (https://editor.construct.net/r330/main.js:1234:399) at ho (https://editor.construct.net/r330/main.js:914:214) at ar.g.Xh.Yw (https://editor.construct.net/r330/main.js:2519:498)
Stack: TypeError: expected finite number at O.m (https://editor.construct.net/r330/main.js:1030:407) at d.gca (https://editor.construct.net/r330/projectResources.js:823:238) at aYa.Sba.ef (https://editor.construct.net/r330/projectResources.js:1886:247) at window.sc.Ch (https://editor.construct.net/r330/projectResources.js:1859:319) at d.Ch (https://editor.construct.net/r330/projectResources.js:1736:9) at window.ueb.Ch (https://editor.construct.net/r330/main.js:2509:310) at Array. (https://editor.construct.net/r330/main.js:2482:496) at window.ueb.dispatchEvent (https://editor.construct.net/r330/main.js:1234:399) at ho (https://editor.construct.net/r330/main.js:914:214) at ar.g.Xh.Yw (https://editor.construct.net/r330/main.js:2519:498)
Construct version: r330
URL: https://editor.construct.net/r330/
Date: Mon Feb 20 2023 14:35:20 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 111.8 s

Platform information
Product: Construct 3 r330 (beta)
Browser: Chrome 110.0.5481.104
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by AshleyScirra** [comment] 2023-02-20 13:44
@DiegoScirra - looks like a regression caused by scene graph opacity changes.

**Comment by DiegoScirra** [comment] 2023-02-20 13:57
Will be fixed in the next beta.

**Closed by DiegoScirra** 2023-02-20 13:57 UTC
