### ISSUE TITLE
Window sizing is incorrect

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2791] opened 2019-04-01 10:58 UTC
## Problem description
"This is most likely same old chrome window issue. "

There is no reliable way to set/get window size. Window always opens differently then you have set it in properties. On chrome margin of error is small, but on installed desktop app it's much worse. + The inner and outer width act differently, when on chrome or on app. Does not matter the scale mode you use.

## Attach a .c3p
[WindowSizeBug.zip](https://github.com/Scirra/Construct-3-bugs/files/3028964/WindowSizeBug.zip)

## Steps to reproduce

1.Open example, preview.
2.See that you don't have correct width from platform info and small black border appears below
3.Note the numbers
4.Change from chrome to desktop app, see all numbers are different again

## Observed result
Outerwidth is incorrect in chrome, but is somewhat better in app version. While innerHeight is better in chrome, but worse in app etc. So its big mess.

on chrome InnerHeight is wrong by 3px and black border appers on bottom.
![Blackborder](https://user-images.githubusercontent.com/28864889/55322636-8e856080-5485-11e9-917c-b428e26b1908.jpg)

Also in chrome browser OuterWidth should be correct but it isen't, while on app version it is. OuterWidth  does not have to mesure scroll/link bar so it should be correct. So iam not sure what it mesures!!!

## Expected result
Correct values.
Add set window size to browser plugin, so one can use values from platform and  just resize the window, atm you can't.

## More details
All scales modes are show wrong values.

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
I tried 107 and 108 same issue
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 1.1 gb (8.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment] 2019-04-01 11:22
This is a Chrome bug. Duplicate of #947, #1059, #1200, #1318, #1987.

**Closed by AshleyScirra** 2019-04-01 11:22 UTC
Labels: chrome, external
