### ISSUE TITLE
Failed to create a new project offline bug :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6179] opened 2022-10-10 22:15 UTC
## Problem description

My electricity was turned off. The Internet is gone because I'm using a wi-fi router. I went into Construct but I can't create a new project.

## Attach a .c3p

There is not.

## Steps to reproduce

1. Open Construct r313b.
2. Create a new project.

## Observed result

![observed](https://user-images.githubusercontent.com/91274932/194959060-03e8db83-0df2-4462-a80c-fb773793d1e6.gif)

## Expected result

I can create a new project.

## More details

I also wanted to ask if it makes sense to report crashes if I can't reproduce them? I will only have information about the error and the saved project after the crash.

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r313b, r308-2s

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r313 (beta)
Browser: Chrome 106.0.5249.103
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 399 mb (0.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumdim64.dll)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
EXT_sRGB
KHR_parallel_shader_compile
OES_element_index_uint
OES_fbo_render_mipmap
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2022-10-11 12:41
I can actually reproduce this, but it's totally mystified me. When you click 'New project' it fetches the default icons, so it requests 6 image files. The first few succeed and the last few fail with just a mysterious "ERR_FAILED" code. All 6 icons are treated identically in requesting, caching, and serving.

It seems to work in Firefox so my best guess is this is somehow a Chrome bug, but it is going to be a nightmare to get to the bottom of this.

**Comment by AshleyScirra** [comment] 2022-10-11 12:52
I checked Chrome Canary and it doesn't seem to reproduce for me there. This suggests it is indeed a Chrome bug that they've already fixed in Canary.

Can you check Chrome Canary and see if the issue reproduces for you there?

**Comment by AshleyScirra** [comment] 2022-10-11 13:55
Looks like it might be caused by this Chrome issue in M106: https://bugs.chromium.org/p/chromium/issues/detail?id=1370035
The problem sounds like it is related to caches, which could be relevant to offline support.

**Comment by WilsonPercival** [comment] 2022-10-11 16:09
> Looks like it might be caused by this Chrome issue in M106: https://bugs.chromium.org/p/chromium/issues/detail?id=1370035 The problem sounds like it is related to caches, which could be relevant to offline support.

@AshleyScirra Looks like in Chrome Canary I can reproduce this error too.

![observed3](https://user-images.githubusercontent.com/91274932/195143743-06e476c7-ec08-4aa3-b39a-bc6a882ac11e.gif)

**Comment by skymen** [comment] 2022-10-13 08:11
I have the same issue, I cannot open or create projects since r312. It works fine with previous versions and it works fine in incognito mode. Initially, I guessed that it was somehow related to 3rd party addon loading but I'm not sure.

**Comment by AshleyScirra** [comment] 2022-10-13 11:19
@WilsonPercival @skymen can you both try Chrome Canary again today? Check for updates in Menu - Help - About, as I think a fix for this may have landed in Chrome very recently.

**Comment by F3der1co** [comment] 2022-10-13 13:30
I had the same problem yesterday.
Just now I tried to reproduce it in canary or incognito mode but couldn't in either. 
Only breaks in my normal Chrome or the Chrome PWA for me.

**Comment by WilsonPercival** [comment] 2022-10-13 16:51
> @WilsonPercival @skymen can you both try Chrome Canary again today? Check for updates to make sure Canary is up-to-date in Menu - Help - About, as I think a fix for this may have landed in Chrome very recently.

@AshleyScirra Everything is working.

![b](https://user-images.githubusercontent.com/91274932/195657547-8ee57b7e-6992-4d98-89ea-59a1e7f0938f.gif)

**Comment by AshleyScirra** [comment] 2022-10-14 10:08
OK, I think this is a Chrome issue that Google subsequently fixed, so closing.

**Closed by AshleyScirra** 2022-10-14 10:08 UTC
Labels: difficult, external, chrome

**Comment by WilsonPercival** [comment] 2022-11-02 16:29
@AshleyScirra I tried again and again the error.

https://user-images.githubusercontent.com/91274932/199546481-8ad2d3c8-85d8-4cbd-83ef-1a0c6dd3bbf0.mp4
