### ISSUE TITLE
Drag indicator bugs when moving var 2x under itself.

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#3542] opened 2019-12-12 15:19 UTC
## Problem description
Adding var and dragging it below it bugs seperator line. It allows to drag var 2x under itself

Some image to see line gets stuck.
![buggy](https://user-images.githubusercontent.com/28864889/70724163-c0ccaa80-1d02-11ea-8b31-ffe584f7a9c4.jpg)

## Steps to reproduce

1.Create new project. Create new var
2.Drag var under itself, then try to drag it further down. 

## Observed result
dragging it to way under itself bugs html object.

## Expected result
No buggys

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 79.0.3945.79
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36
C3 release: r179 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 96 mb
Storage usage (approx): 44 mb (45.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-12-12 17:09
It seems to work fine here. No project was provided so I made a bunch of every tick events and added a global variable. I can drag it anywhere and it displays correctly. Am I missing something?

**Comment by SnipG** [comment] 2019-12-12 17:41
Vid:
[2019-12-12 19-38-25.zip](https://github.com/Scirra/Construct-3-bugs/files/3957101/2019-12-12.19-38-25.zip)

**Comment by Wackytoaster** [comment] 2019-12-15 23:54
I can confirm this is a thing, it´s just a minor bug though since dragging again will make the line get unstuck again.

To get it stuck you have to drag some form of sub-event (or grouped event) onto the top-level like this:
![image](https://user-images.githubusercontent.com/31101309/70871328-8aab5700-1f9e-11ea-9958-efb27aaab55b.png)

**Comment by AshleyScirra** [comment] 2019-12-16 12:52
Thanks, I got it now. Was a regression in r173 when we re-did all the mouse code. Should be fixed in the next release.

**Closed by AshleyScirra** 2019-12-16 12:52 UTC
