### ISSUE TITLE
Invert timeline "Is playing" condition  produce unhandled exception

### ISSUE THREAD

**Issue by 1mrpaul1** [Scirra/Construct-3-bugs#5269] opened 2021-11-25 16:48 UTC
## Problem description

If to try to invert is plying condition in the timeline the game will close with error

Type: unhandled exception
File: https://editor.construct.net/r273/components/editors/eventSheetView/eventSheetView.js, line 98, col 53
Message: Uncaught TypeError: H9a.oAc is not a constructor
Stack: TypeError: H9a.oAc is not a constructor at d.FHb (https://editor.construct.net/r273/components/editors/eventSheetView/eventSheetView.js:98:53) at https://editor.construct.net/r273/components/editors/eventSheetView/eventSheetView.js:93:458 at https://editor.construct.net/r273/main.js:1678:100

## System details

Construct 3 version: r273
URL: https://editor.construct.net/r273/
Date: Thu Nov 25 2021 21:43:45 GMT+0300 (Москва, стандартное время)
Uptime: 11.1 s

Platform information
Browser: Chrome
Browser version: 96.0.4664.45
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
C3 release: r273 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6692)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

PASTE HERE

</details>

**Comment by DiegoScirra** [comment] 2021-11-25 18:10
This is a duplicate of #5263

**Closed by DiegoScirra** 2021-11-25 18:10 UTC
Labels: duplicate
