### ISSUE TITLE
XML attributes not working with Construct 3 runtime

### ISSUE THREAD

**Issue by esowe** [Scirra/Construct-3-bugs#2077] opened 2018-09-25 16:32 UTC
## Problem description

The XML object doesn't work as intended with XPath queries involving attributes, when using the Construct 3 runtime. This is possibly the same bug as in issue #2064 .

## Steps to reproduce

1. Run the attached project using the Construct 2 runtime.
2. Change to the Construct 3 runtime and run it again.

## Observed result

Queries using attributes aren't working when using the Construct 3 runtime. The other queries are.

## Expected result

The same result for both runtimes.

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

N/A

**Comment by AshleyScirra** [comment] 2018-09-25 16:40
Can't see a project attached here - did you forget to include it?

**Comment by esowe** [comment] 2018-09-25 17:17
Sorry, I forgot to zip the file before uploading it. The C3P file type isn't supported directly and I didn't notice the error message. Here is the file:
[XMLProblem.zip](https://github.com/Scirra/Construct-3-bugs/files/2416300/XMLProblem.zip)

**Comment by AshleyScirra** [comment] 2018-09-26 17:20
Yes, this is a duplicate of #2064 - it manifests identically and the fix for #2064 also fixes this issue. So it should be working in the next release.

**Closed by AshleyScirra** 2018-09-26 17:20 UTC
Labels: duplicate
