### ISSUE TITLE
Web Fonts Cause Cordova Export to get stuck on construct 3 loading screen

### ISSUE THREAD

**Issue by rhg1968** [Scirra/Construct-3-bugs#2691] opened 2019-03-05 18:37 UTC
## Problem description

If you run the attached project (with web fonts) in a browser (mobile or desktop), it works correctly. If you export it as an android debug version it gets hung on the construct 3 loading screen. If you remove the web fonts from the project, it will work after being exported again.

## Attach a .c3p
[FontTest.zip](https://github.com/Scirra/Construct-3-bugs/files/2932277/FontTest.zip)

Just change the file back to .c3p.

## Steps to reproduce

1. Change the file back from .zip to .c3p
2. Load it and press f4 and it runs and displays a test message on the screen. Makes use of a boot scene to make it similar to my game.
3. Export as an cordova android debug app
4. Try running on android device (mine is a galaxy s8+)

## Observed result

The construct 3 loading screen shows and it just gets stuck there.

## Expected result

That after the splash screen, that my test messages would show on the screen.

## More details

If I remove the fonts from the project and export again, it works correctly.

Works correctly on chrome on my desktop and chrome on my android device.

Once exported as an apk, the issue appears with the android(chrome) web view.

**Affected browsers/platforms:** 

Not sure because I haven't really tried exporting before. I am currently on r140.

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment] 2019-03-06 16:59
Can you post the system details for your S8+, the S8 we have in the office succeeds in loading the project. It has recently updated to Android 9 though. Also reassigning to @AshleyScirra

**Comment by rhg1968** [comment] 2019-03-06 17:04
Sure here is the galaxy s8+ info. If you need anything more, just let me know.
Android version  8.0.0
Samsung Experience version  9.0
Baseband version  G955USQS5CSB1
Kernel version 4.4.78
Build Number  R16NW.G955USQS5CSB1
Knox version  3.0
Android security patch level   2/1/2019

**Comment by AshleyScirra** [comment] 2019-03-06 17:13
@rhg1968 - is the Android Webview / Chrome apps up-to-date on the device?

**Comment by rhg1968** [comment] 2019-03-06 17:25
My device has no outstanding updates, both through the google play store or through system updates.

**Comment by rhg1968** [comment] 2019-03-06 18:07
Very interesting what I just found, but not really sure why it is making a difference.
I originally have been exporting for cordova with an android version of 5.0+
I decided to change it to version 8.0+ and now it doesn't hang on the splash screen and functions as expected.
Any ideas why this would be like this ?

**Comment by rhg1968** [comment] 2019-03-06 18:13
Now I changed my actual game, not the sample project I created, to export at 8.0+ and it still doesn't work. So not sure what is going on

**Comment by rhg1968** [comment] 2019-03-06 20:24
I also noticed the sample project, the one I included with this issue, compiled with android 8.0+ actually works on my device sometimes and other times it hangs on the splash screen as an APK. It almost appears like a timing issue with loading the fonts that I have included in the project.

**Comment by AshleyScirra** [comment] 2019-03-06 22:17
Which version of Construct are you using? Is it the latest? (If you include the system details in the report we don't have to check this.)

**Comment by rhg1968** [comment] 2019-03-06 23:00
I am using r140 and it was listed above but it was in the affect browsers and platforms section

**Comment by AshleyScirra** [comment] 2019-03-07 18:05
I also can't reproduce: it works fine as an APK on a Pixel 3.

I'm afraid we won't be able to help unless you can obtain some kind of error from the affected device. You'll need to set up [remote debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews) for the WebView in the APK and check for any errors in the console log. Otherwise we will have nothing to go on - it seems to work fine on our devices.

**Comment by rhg1968** [comment] 2019-03-07 20:14
I'll have to see what I can do. Even in my game if I try enough times on my phone, it will eventually work until the next time I start it up.

The usb port on my phone doesn't work well, I always charge through a pad, so hooking up to a computer may be difficult to try chrome dev tools.  I will try and see what I can do because it definitely seems to be some type of timing issue with the fonts that doesn't happen if I remove the fonts.

I'll let you know what I find and thank you for looking into this.

**Comment by rhg1968** [comment] 2019-03-08 10:57
Not that it probably helps but just thought I would toss in another data point 
On the simple project attached, if you remove the boot scene, delete it, change the first layout to be the one that is left (the one with the font on it), export it to android. Then it works everytime.

**Comment by AshleyScirra** [comment] 2019-03-08 12:16
To diagnose an issue it's more useful to have a project that reproduces the problem every time. That's what we need to debug; working projects aren't especially useful.

Since we don't currently have a way to investigate this any further I will leave this with you and close the issue. If you can provide something that we can use as the basis to further investigate the issue I'll reopen it.

**Closed by AshleyScirra** 2019-03-08 12:16 UTC
Labels: can't reproduce
