### ISSUE TITLE
Opening project from browser does not works in r80

### ISSUE THREAD

**Issue by newman321** [Scirra/Construct-3-bugs#1223] opened 2018-01-22 20:26 UTC
## Problem description

cant open projects i saved in local storage with r80

## Steps to reproduce

1.Open construct 3/r80 (whether by visiting editor.construct.net or editor.construct.net/r80/
2. click on browser 
3.No list of saved projects 

## Observed result

![screen shot 2018-01-22 at 11 53 31 pm](https://user-images.githubusercontent.com/426713/35242685-888a5b2e-ffcf-11e7-9bab-b64a669a9259.png)

## Expected result

To be able to select a saved project 
## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r80
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 238 mb (0.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 330M OpenGL Engine
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 2047
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_disjoint_timer_query
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
EXT_sRGB
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_draw_buffers
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>
Ps : i can see my projects in open recent but clicking on them does not loads them.

![screen shot 2018-01-22 at 11 57 41 pm](https://user-images.githubusercontent.com/426713/35242849-1beed980-ffd0-11e7-921d-4689e115d4f3.png)

i cleared my local storage and it worked fine for once then stuck again.

no problem with /r79

![screenshot 2018-01-22 23 59 00](https://user-images.githubusercontent.com/426713/35242890-400bda5c-ffd0-11e7-857c-72db2495dfdd.png)

**Comment by shortercode** [comment] 2018-01-23 13:30
I expect this is the same issue as #1109 but as you've already cleared your cache I don't think we'll be able to confirm the problem. I had thought r80 would be immune to the cloudflare bug so I'm surprised to hear that you still had a problem. I can't replicate this bug here.

Did the save continue to work for you after this, or did it break again the next time you opened C3?

**Comment by newman321** [comment] 2018-01-23 13:50
i can save projects but cant open them, as i mentioned above after clearing local storage i still have this problem (it just worked once when local storage was empty).

trying second one.

**Comment by newman321** [comment] 2018-01-23 13:53
cloud does not works eighter but i noticed whenever i click on folder or cloud the first time this error appears in console 
![screenshot 2018-01-23 17 22 40](https://user-images.githubusercontent.com/426713/35279352-238a57f4-0062-11e8-9691-a26f05259f24.png)

**Comment by newman321** [comment] 2018-01-23 14:01
i removed all cookies and local storage once again and this time it doesn't even works for the first time

**Comment by shortercode** [comment] 2018-01-23 14:03
Hmm yup that is definitely the cloudflare error. By default they try to minify JavaScript ( even though it's already minifed ), but we discovered their minifier doesn't support newer syntax so we turned it off. At least one of the CDN servers is apparently ignoring that setting. Whenever it comes across a string like
```javascript
const address = `https://my.server.com`; 
```
It decides everything after the double slash is a comment, and doesn't send it. It particularly prevents the code for browser and cloud saves from loading correctly.

**Comment by shortercode** [comment] 2018-01-23 14:04
If you click on the bit that says "sandbox.js:1" what does the very end of that file look like?

**Comment by shortercode** [comment] 2018-01-23 14:35
Okay I think I have backtracked this issue, I'm going to close this one as a duplicate of the original as they are definitely the same bug. Thanks for your help.

**Comment by shortercode** [comment] 2018-01-23 14:35
Closing as duplicate of #1109

**Closed by shortercode** 2018-01-23 14:35 UTC
Labels: need info
