### ISSUE TITLE
Document is not defined

### ISSUE THREAD

**Issue by MultiPain** [Scirra/Construct-3-bugs#3384] opened 2019-10-04 01:38 UTC
## Problem description

As soon as i'm adding 9patch object _with_ **or** _without_ a texture, C3 get black screen on startup. In console i see the error "Document is not defined". DOM elements still displaying (obviously, because its not part of the canvas), and events still working.

Works fine in EDGE and Firefox.

## Steps to reproduce

1. Create new project.
2. Add 9patch.
3. Run project.

## Observed result

Black screen on startup.

## Expected result

No black screen.

## More details

**Affected browsers/platforms:** Chrome, Opera, Windows

**First affected release:** r164.3 (and also in r169)

## Console error output

```
bootPreview.js:14 Registered service worker on https://preview.construct.net/local/
sw.js:268 [SW-Preview] Up to date
runtime.js:1 [C3 runtime] Hosted in worker, rendering with WebGL 1 [ANGLE (Intel(R) HD Graphics 3000 Direct3D9Ex vs_3_0 ps_3_0)] (standard compositing)
texture.js:1 Uncaught (in promise) ReferenceError: document is not defined
    at C3.Gfx.WebGLRendererTexture._CreateStatic (texture.js:1)
    at C3.Gfx.WebGLRenderer.CreateStaticTexture (webglRenderer.js:1)
    at self.NinePatchTextureSet._SliceImage (textureSet.js:1)
    at self.NinePatchTextureSet.CreateTextures (textureSet.js:1)
    at C3.Plugins.NinePatch.Type.CreatePatch (type.js:1)
    at new C3.Plugins.NinePatch.Instance (instance.js:1)
    at Function.C3.New (jsutil.js:1)
    at C3.Instance._CreateSdkInstance (instance.js:1)
    at C3.Runtime.CreateInstanceFromData (runtime.js:1)
    at C3.Layer.CreateInitialInstances (layer.js:1)
_CreateStatic @ texture.js:1
CreateStaticTexture @ webglRenderer.js:1
_SliceImage @ textureSet.js:1
CreateTextures @ textureSet.js:1
CreatePatch @ type.js:1
C3.Plugins.NinePatch.Instance @ instance.js:1
C3.New @ jsutil.js:1
_CreateSdkInstance @ instance.js:1
CreateInstanceFromData @ runtime.js:1
CreateInitialInstances @ layer.js:1
_CreateInitialInstances @ layout.js:1
_StartRunning @ layout.js:1
Start @ runtime.js:1
async function (async)
a @ 2407d360-cffc-42d4-a815-283e4d3ba522:1
(anonymous) @ 2407d360-cffc-42d4-a815-283e4d3ba522:1
```

## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 77.0.3865.90
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
C3 release: r164.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 134 gb
Storage usage (approx): 99 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 3000 Direct3D9Ex vs_3_0 ps_3_0)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-10-04 08:12
This looks like a duplicate of #3374 (depending on the settings, 9-patch also creates tiled textures similar to tiled background).

**Closed by AshleyScirra** 2019-10-04 08:12 UTC
Labels: duplicate
