### ISSUE TITLE
Crash while searching new built-in action Functions

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#2804] opened 2019-04-03 07:22 UTC
## Problem description

You can't get "Function" keyword results for the new built-in function and it will crash if there is an action function.

## Steps to reproduce

1. Create a Built-in Function event.
2. Add an action to call that function. It can be "On start of layout" as triggers, doesn't matter.
3. CTRL+F and search "Function".

## Observed result

Crashed.

## Expected result
No crash and display event lines that have the keyword "function" as results.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r143/components/bars/findResultsBar/findResultsBar.js, line 1, col 1897
Message: Uncaught TypeError: a is not a function
Stack: TypeError: a is not a function at Object.ǃFzM (https://editor.construct.net/r143/components/bars/findResultsBar/findResultsBar.js:1:1897) at Object.ǃLzd (https://editor.construct.net/r143/components/bars/findResultsBar/findResultsBar.js:1:1689) at Object.ǃNPs (https://editor.construct.net/r143/main.js:81:601157) at Object.ǃki (https://editor.construct.net/r143/main.js:2:289331) at d.ǃki (https://editor.construct.net/r143/main.js:2:261676) at HTMLDocument. (https://editor.construct.net/r143/main.js:2:259973)
Construct 3 version: r143
URL: https://editor.construct.net/r143/index.html
Date: Wed Apr 03 2019 15:17:15 GMT+0800 (Malaysia Time)
Uptime: 40.8 s

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r143 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 765M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment] 2019-04-03 11:04
I think this may be a duplicate of #2794 but will let @AshleyScirra cast his eye over it.

**Comment by AshleyScirra** [comment] 2019-04-03 12:31
Yep duplicate of #2794, will leave open to try to avoid more duplicates being filed.

**Closed** 2019-04-08 12:42 UTC
