### ISSUE TITLE
Potential Cloud-Save-Dependent Memory Leak 

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-3-bugs#4859] opened 2021-05-29 16:54 UTC
## Problem description

Construct 3 gets slower over time potentially due to a memory leak associated with cloud saves.

## Steps to reproduce

1. Open any project and utilize cloud save frequently
2. Check task manager for memory use

## Observed result

Increase in memory use per save.

## Expected result

No increase in memory use per save.

**Affected browsers/platforms:** Chrome

**Cloud Save Method:** DropBox

**First affected release:** I think this has happened for a couple of versions but most noticeable in r249
![Memory_Leak_Cloud_Save](https://user-images.githubusercontent.com/37854520/120078317-c5eef800-c063-11eb-880f-09d06f3f06b1.png)

**Comment by AshleyScirra** [comment] 2021-06-01 08:20
There are no clear steps to reproduce, nor is it clear this is actually a problem - frequently in garbage-collected languages like JavaScript, memory usage is allowed to increase long-term, until the browser/system decides it needs to reclaim memory, in which case it runs GC and then the memory usage will jump back down again. Further we have large numbers of users using the cloud save feature with apparently no such consequences. So since this may well not be a bug or may be something else but we can't investigate anyway, closing.

**Closed by AshleyScirra** 2021-06-01 08:20 UTC
Labels: no repro
