### ISSUE TITLE
Error Opening File on Web Editor r157

### ISSUE THREAD

**Issue by MAL-** [Scirra/Construct-3-bugs#3105] opened 2019-07-02 14:24 UTC
Error report information
Type: unhandled rejection
Reason: {"response":"{\n \"error\": {\n \"errors\": [\n {\n \"domain\": \"global\",\n \"reason\": \"internalError\",\n \"message\": \"Internal Error\"\n }\n ],\n \"code\": 500,\n \"message\": \"Internal Error\"\n }\n}\n","code":500,"status":
Construct 3 version: r157
URL: https://editor.construct.net/
Date: Tue Jul 02 2019 09:14:43 GMT-0400 (Eastern Daylight Time)
Uptime: 81.6 s

Platform information
Browser: Chrome
Browser version: 75.0.3770.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by shortercode** [comment] 2019-07-02 15:02
We've had a similar report to this before, so I would like to resolve this issue. But without the complete replication I can't do anything with this. **Please do not delete the issue template, fill in as much of the information that you can.**

**Comment by AshleyScirra** [comment] 2019-07-03 10:02
I don't think there's any action we can take from this since there are no steps to reproduce, so closing.

**Closed by AshleyScirra** 2019-07-03 10:02 UTC
Labels: ignored guidelines
