### ISSUE TITLE
Crash when adding as a child in hierarchy

### ISSUE THREAD

**Issue by ecations** [Scirra/Construct-3-bugs#4427] opened 2020-12-19 21:30 UTC
## Problem description

A Sprite Font object instance wouldn't get added to the hierarchy as a child (no arrow appeared), then when trying again, Construct crashed.

## Attach a .c3p

[011 crash.zip](https://github.com/Scirra/Construct-3-bugs/files/5720167/011.crash.zip)

## Steps to reproduce

I was not able to reproduce, but these are the steps that lead to the crash:

1. Try to add the Sprite Font with the text "Settings" to the hierarchy with the "settingsBG" as the parent.
2. Didn't work.
3. Tried again and got a crash report.

## Observed result

No parent-child relationship formed and then a crash.

## Expected result

Element becoming a child in the hierarchy.

## More details

**Affected browsers/platforms:** 

Chrome

**First affected release:** 

r229

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r229/projectResources.js, line 266, col 111
Message: Uncaught TypeError: Cannot read property '0' of null
Stack: TypeError: Cannot read property '0' of null at Object.v3a (https://editor.construct.net/r229/projectResources.js:266:111) at Object.s (https://editor.construct.net/r229/projectResources.js:262:273) at n.zvb (https://editor.construct.net/r229/projectResources.js:242:453) at n.Nsd (https://editor.construct.net/r229/projectResources.js:242:348) at n.fZa (https://editor.construct.net/r229/projectResources.js:241:400) at n.Tq (https://editor.construct.net/r229/projectResources.js:242:64) at Object.v3a (https://editor.construct.net/r229/projectResources.js:266:115) at Object.s (https://editor.construct.net/r229/projectResources.js:262:273) at n.zvb (https://editor.construct.net/r229/projectResources.js:242:453) at n.Nsd (https://editor.construct.net/r229/projectResources.js:242:348)
Construct 3 version: r229
URL: https://editor.construct.net/r229/
Date: Sat Dec 19 2020 23:18:34 GMT+0200 (Eastern European Standard Time)
Uptime: 226676.7 s

Platform information
Browser: Chrome
Browser version: 87.0.4280.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
C3 release: r229 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment] 2021-01-06 16:13
Can't reproduce this one, it looks like it works by just loading the example project and setting the relationship. There must be additional steps that need to happen before hand for the crash to be triggered. I'm leaving this open for a little while, but will have to close it if no additional information comes up.

**Closed** 2021-01-12 16:43 UTC
Labels: can't reproduce
