### ISSUE TITLE
Crash in Sprite Editor Deleting Image Point 2

### ISSUE THREAD

**Issue by 8bitThirsty** [Scirra/Construct-3-bugs#1204] opened 2018-01-16 16:02 UTC
## Problem description

When trying to delete Image Point 2 in a sprite the engine crashes.  Found in my game and easily reproduced in a new project. 
  
[New project.zip](https://github.com/Scirra/Construct-3-bugs/files/1635835/New.project.zip)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Create a sprite
2. Add 2 image points
3. Attempt to delete the 2nd image point

## Observed result

Engine Crashed.  Report Below.

## Expected result

Image point would be deleted

## Affected browsers

* Chrome: yes Version 63.0.3239.132 (Official Build) (64-bit)

## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r78/main.js, line 2, col 179707
Message: Uncaught TypeError: Right-hand side of 'instanceof' is not an object
Stack: TypeError: Right-hand side of 'instanceof' is not an object at Function.ǃl.ǃtc (https://editor.construct.net/r78/main.js:2:179707) at e.ǃVtC.ǃVtw (https://editor.construct.net/r78/main.js:74:140560) at i.ǃVS (https://editor.construct.net/r78/main.js:74:139255)
Construct 3 version: r78
URL: https://editor.construct.net/
Date: Tue Jan 16 2018 11:01:22 GMT-0500 (Eastern Standard Time)
Uptime: 13.2 s

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r78
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 5500 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2018-01-16 16:08
@DiegoScirra looks like a dupe?

**Comment by 8bitThirsty** [comment] 2018-01-16 16:10
Also reproduced in FireFox 57.0.4 (32-bit)

Error report information

Type: unhandled exception
File: https://editor.construct.net/r78/main.js, line 2, col 179698
Message: TypeError: invalid 'instanceof' operand l
Stack: ǃl.ǃtc@https://editor.construct.net/r78/main.js:2:179698 ǃVtw@https://editor.construct.net/r78/main.js:74:140557 ǃVtj/<@https://editor.construct.net/r78/main.js:74:139250
Construct 3 version: r78
URL: https://editor.construct.net/
Date: Tue Jan 16 2018 11:09:54 GMT-0500 (Eastern Standard Time)
Uptime: 72.3 s
Unable to collect further diagnostic information because a promise rejection occurred while trying to collect it.

**Comment by DiegoScirra** [comment] 2018-01-16 16:54
Duplicate of #1202

**Closed** 2018-01-17 12:53 UTC
Labels: duplicate
