### ISSUE TITLE
Issue launching a sample game

### ISSUE THREAD

**Issue by triptych** [Scirra/Construct-3-bugs#236] opened 2017-05-17 17:19 UTC
## Problem description

Editor reported an issue when launching a sample game
[Ghost Shooter.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1008562/Ghost.Shooter.c3p.zip)

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. open the game
2.hit preview
3.see error

## Observed result

Editor turned red

## Expected result

to launch game without any issues
## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r28/exporters/preview/exporter.js, line 1, col 1472
Message: Uncaught Error: unknown message 'undefined'
Stack: Error: unknown message 'undefined' at window.ǃHkg.ǃHkC (https://editor.construct.net/r28/exporters/preview/exporter.js:1:1478) at ǃHkp.p (https://editor.construct.net/r28/exporters/preview/exporter.js:1:694)
Construct 3 version: r28
URL: https://editor.construct.net/
Date: Wed May 17 2017 10:14:16 GMT-0700 (PDT)
Uptime: 359.6 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
C3 release: r28

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M370X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2017-05-17 17:30
Can't reproduce, works fine here. Do you have any browser addons? Does it work if you disable them?

**Comment by triptych** [comment] 2017-05-17 19:39
Yes, it works fine in incognito window (no issues). There must be a plugin conflict. I'll see if I can track it down and add a reference here.

**Comment by triptych** [comment] 2017-05-18 18:29
I can confirm it was a 3rd party plugin that caused the error. It's an internal tool chrome extension.  Not a bug in Construct.

**Comment by AshleyScirra** [comment] 2017-05-19 10:40
Can you tell us which one it is though? If possible we'd like to work around the problem, especially since other extensions might do similar things.

**Comment by AshleyScirra** [comment] 2017-06-01 11:28
2 weeks needing info without update, closing.

**Closed by AshleyScirra** 2017-06-01 11:28 UTC
Labels: need info

**Comment by triptych** [comment] 2017-06-01 17:01
Sorry, it's just an internal plugin that I don't know the mechanics of, if I can get a reproducible test case I'll open a new bug.
