### ISSUE TITLE
Mobile IAP not working when app is downloaded from App Store

### ISSUE THREAD

**Issue by Mr-Josh-web** [Scirra/Construct-3-bugs#3973] opened 2020-06-22 19:36 UTC
## Problem description

The problem is related with Mobile IAP, iOS and Construct 3 runtime.
The mobile IAP is working fine on Android, test-flight and development environment, but it does not work when the app is downloaded directly from the App Store.

The in-app-purchase item has been approved on App Store Connect and the app store review team has approved the app as in their enviornment the app works fine. I have spoken with the app store connect team and they said that everything is well configured on App Store Connect and they have said that the issue will be on the source code of my app.

## Attach a .c3p

https://drive.google.com/file/d/1uxmCDt4gKvyIYhR08KLp6G04SPMAOvqF/view?usp=sharing

## Steps to reproduce

1. Start up the mobile game
2. If the bottom button left is enabled (yellow background), it means that the product is available. If this bottom is grayed out, the product is not available.

When I install the app through test-flight or install directly the .ipa on an iPhone, this button is enabled. When the app is downloaded from the App Store, this button is grayed out which means that the in-app-purchase item is not available to purchase.

## Observed result

The bottom button left is grayed when the app is downloaded directly from the App Store.

## Expected result

The bottom buton left should be enabled (yellow background)

## More details

The Mobile IAP is working fine on Android, test-flight and development environment.
I have spoken with the App Store connect team and they said that everything is well configured and approved on the App Store connect. I have spoken with 2 different people from App Store Connect just to confirm that information and both of them have said that everything is ok on the App Store connect.

As it is a mobile game and it uses Mobile IAP, it cannot be tested on browsers so it has been only tested on Android and iOS devices.

**Affected browsers/platforms:** 

All iOS devices (iPhones, iPad, ...)

**First affected release:** 

I have just updated to the latest version of Construct 3 so I am not sure which version I was using. Perhaps I exported the iOS app using the r197 version, but as I have said, I am not sure.

I do not have that. I can't see crash report.

<details><summary>View details</summary>

It is not an issue with the browser so I do not think that this information is relevant. Let me know if it is.

</details>

Let me know if you need more information.

Thanks.

**Comment by AshleyScirra** [comment] 2020-06-23 10:57
This is very difficult and I can't see a way forwards right now I'm afraid. There are a number of difficulties:

> The mobile IAP is working fine on Android, test-flight and development environment, but it does not work when the app is downloaded directly from the App Store.

If this is true, then to test the minimal repro would mean publishing to the App Store and passing the app store review. We probably won't pass the app store review with this. Therefore we cannot test it.

Further if the problem was with Construct, I would expect it would also fail in development and in test-flight. But you say it works. This suggests the problem is a difference between test-flight and the app store. These are services provided by Apple and are beyond our control. I'm not aware of anything we would need to change in Construct to handle any differences either. The point of the testing platforms is they work the same. So I can't even think of anything even theoretical that we'd need to change.

Your events don't appear to properly handle error cases - for example it doesn't look like you check for purchase failed events, and it looks wrong to handle store registration failure by pretending it worked and carrying on. You may learn more about the problem if you properly handle and report errors in your events.

I've never heard of anyone else having any issues specific to the App Store, so this seems so far specific to just your app, which further suggests some kind of configuration problem. As I mentioned by email previously it may be that developer settings somehow interfere, so it would be worth getting a fresh device not used for development purposes and testing on that.

I'm afraid I doubt I can offer any more help. There doesn't seem anything for us to change, we don't have a way to test it, and the evidence points to some difference between test-flight and the App Store, which is Apple's responsbility. I hope this information helps you find some way to deal with the problem, but I cannot see anything else I can do to help at this point.

**Comment by Mr-Josh-web** [comment] 2020-06-23 15:25
Hi Ashley,

Many thanks for your reply.

In my opinion there are four possible problems:

1. **Issue within the Apple Store Connect**: this is actually impossible because if not there will be hundreds of newspapers and blogs talking about that.
2 **Configuration on App Store Connect**: I have spoken with 2 different people from the App Store connect and both of them said that everything is ok so we can discard  this point.
3 **The source code of my mobile application**: you said that there are some things wrong. I attached a c3p file to this issue. Could you please send me the corrected file so I can publish the app again or send me a c3p template file where I can see how I should handle Mobile IAP within the app? Could you connect me with a developer that has recently uploaded an iOS app with Mobile IAP and have no issues? Do you know someone who has recently publish an iOS app with Mobile IAP?
4 **Construct 3 might have a bug**: you say that there is not a bug.

It seems that this is happening to anybody else and the problem is that is happening in production environment.

- https://www.construct.net/en/forum/construct-3/how-do-i-8/complete-product-registration-151028
- https://github.com/Scirra/Construct-3-bugs/issues/3961

Regards.

**Comment by AshleyScirra** [comment] 2020-06-23 15:40
It's perfectly possible there's a bug in Apple Store Connect. Apple's software has been pretty poor in the past few years, and not all bugs affect all apps - it might be that it only happens in specific circumstances, and you are unlucky in meeting all those circumstances.

There is not yet any evidence those other issues are related - as I recall the issue with completing registration did reproduce in testflight, so if you do not see an issue there, then it most likely is not that bug.

The project should just display any errors that happen. Otherwise how do you know if any errors happened? You're just shooting in the dark if you ignore errors, you need to make them visible some way.

**Comment by Mr-Josh-web** [comment] 2020-06-23 15:50
Hi Ashley,

Many thanks for your prompt response.

As far as I know this issue is related:

- https://www.construct.net/en/forum/construct-3/how-do-i-8/complete-product-registration-151028 : check the latest comment of this post.

I go back to my previous message in order to see where the problem is in my code:

_I attached a c3p file to this issue. Could you please send me the corrected file so I can publish the app again or send me a c3p template file where I can see how I should handle Mobile IAP within the app? Could you connect me with a developer that has recently uploaded an iOS app with Mobile IAP and have no issues? Do you know someone who has recently publish an iOS app with Mobile IAP?_

Regards.

**Comment by AshleyScirra** [comment] 2020-06-23 16:40
It's hard to tell from forum posts - part of the reason we ask for bugs to be filed is so we have enough information to adequately assess the problem. Unfortunately if it's the same problem I don't see how that changes anything - the fact it works in testflight suggests Construct's code is all correct, otherwise it wouldn't work there.

Have you tried a fresh device like I suggested? It may be that development settings interfere in some way.

**Comment by Mr-Josh-web** [comment] 2020-06-23 17:17
Yes, I have tried with a fresh device and also ask other people to test the app

**Comment by Mr-Josh-web** [comment] 2020-06-24 08:19
Hi Ashley,

In order to see where the problem is, could you tell me the following?

1. Could you please send me the corrected file so I can publish the app again or send me a c3p template file where I can see how I should handle Mobile IAP within the app?

2. Could you connect me with a developer that has recently uploaded an iOS app with Mobile IAP and have no issues?

Also, do you know someone who has recently publish an iOS app with Mobile IAP?

Thanks.

Regards.

**Comment by AshleyScirra** [comment] 2020-06-24 10:50
I'm not sure why you're asking me to modify the project - it's trivial, just make sure if an error happens, something is shown on screen. A text object would do.

We aren't involved in publishing ourselves so if you want to get in touch with other developers, it would be best to ask on the forum.

**Comment by Mr-Josh-web** [comment] 2020-06-24 15:07
Hi Ashley,

I can't publish a game on production with errors or text messages on the screen.

Is there anything I can do to see where the problem is? Some things that I might check to identify the problem?

Thanks.

**Comment by AshleyScirra** [comment] 2020-06-24 15:17
I would argue you should report errors to the user, so the user knows that something has not worked as expected. It's still better to do that than to show the user non-functional controls that do nothing for no apparent reason. Still, it's up to you, if you're not happy with that then you need to invent some other diagnostic. All you need is some way to identify if an error happened. That could involve console logging, a secret menu option, a special debug screen, whatever you are happy with publishing.

Again I must emphasise this probably won't solve the problem, but whether or not errors have occurred is always essential information to know and help diagnose an issue.

**Comment by Mr-Josh-web** [comment] 2020-06-25 13:45
Hi Ashley,

In this thread you have a clear diagnostic of what is going on https://www.construct.net/en/forum/construct-3/how-do-i-8/complete-product-registration-151028#forumPost1014654

The problem is that "on complete product registration" is not fired and it is not able to make purchases.
You can create a simple mobile game, publish it to the App Store (they review apps in less than 24 hours). Then, connect your iphone via usb to your mac and start up xcode. Doing this, you will be able to see in the console if there are some errors.

Regards

**Comment by AshleyScirra** [comment] 2020-06-25 14:06
We don't at this have time have anything that can pass app store review. Could you try checking for any console errors?

**Comment by Mr-Josh-web** [comment] 2020-06-25 14:52
Hi Ashley,

You can use C3 sample projects: "Kiwi Story", "Demonoire", "Glokar" or "Pop Lab". Just add Mobile IAP and create an item on app store connect. Export the project to xcode and publish it. It will not take long. Onces you done and it has been published you can do it yourself.

I do not have now a Mac with me to test that unless you tell me other alternatives apart from xcode to test that.

Regards

**Comment by AshleyScirra** [comment] 2020-06-25 15:00
The problem we have is none of those projects support touch controls, so I would not expect them to pass app review, it will look like a broken title screen to the reviewer.

**Comment by Mr-Josh-web** [comment] 2020-06-25 15:03
Hi Ashley,

You can create a very simple mobile app(not need for a game) with 2 screens. It should not take more than 30 minutes or 1 hour.

Regards.

**Comment by AshleyScirra** [comment] 2020-06-25 16:33
In the whole history of Construct I've never had to publish something all the way to the app store just to test a bug - I guess it looks like we'll have to do this in this case.

FYI on the off chance this is somehow a variant of #3608 - which is a bug in cordova-plugin-purchase we've already reported to the developers - you could try ignoring the 'On store registration success' trigger. With that issue, in some cases the trigger does not fire.

**Comment by Mr-Josh-web** [comment] 2020-06-25 16:51
Ok, I will test that, but how should we know if the user has purchased the item or not?

**Comment by Dexus** [comment] 2020-06-25 18:57
One Question:
You did register your app at Apple Developer, you filled all the required forms and financial infos?

You registred the Items?

**Comment by Mr-Josh-web** [comment] 2020-06-25 20:21
Hi Dexus,

The item has been approved by Apple and the app is now "ready for sale" on App Store Connect and available on App Store.

I have filled the USA form and all the financial info required. There are as well an Australia, Brazil, Mexico and Taiwan forms but I have not filled these 4 because, as far as I know, they are not neeeded.

What do you mean by "register" the app? 

Let me know if you need further information.

Thanks.

Regards.

**Comment by Mr-Josh-web** [comment] 2020-06-25 20:26
Hi Dexus,

I can send you screenshots from the App Store Connect if needed so you can be 100% sure that what I am saying is right. Let me know if it would be useful for you.

Thanks again.

Regards.

**Comment by Dexus** [comment] 2020-06-26 14:43
Hi @Mr-Josh-web if your app is already in app-store live or any other app, you should be fine.
We had a lot of users that use our plugin but never done, all required steps to activate the developer account fully. Because of missing steps.

> What do you mean by "register" the app?

This mean that you should already have a bundle-id and setup your products in the apple developer dashboard.

**Comment by Mr-Josh-web** [comment] 2020-06-26 14:58
Hi @Dexus 

Could you please guide me to fully activate the developer account or to check what it might be wrong?

The in-app-purchases have been approved by App Store and in-app-purchases work fine on Test-flight and development environment. I have spoken with 2 different people from app store review team and both of them have told me that everything seems to be well configured.

> This mean that you should already have a bundle-id and setup your products in the apple developer dashboard.

Yes, I have that and the item has been already approved by the App Store

Thanks.

Regards.

**Comment by Mr-Josh-web** [comment] 2020-06-27 09:41
Hi Ashley,

> FYI on the off chance this is somehow a variant of #3608 - which is a bug in cordova-plugin-purchase we've already reported to the developers - you could try ignoring the 'On store registration success' trigger. With that issue, in some cases the trigger does not fire.

I have published a new version of the app to the App Store ignoring 'On store registration success' trigger and when I tried to purchase an item nothing happened. I waited 30sec then a minute then 5 mins and nothing happened.
The xcode project was exported without minfiying it, with a 12.0+ min. version of iOS and using the r204.2 stable version of Construct 3.

Regards.

**Comment by AshleyScirra** [comment] 2020-06-29 15:16
See my comment on the other IAP issue: https://github.com/Scirra/Construct-3-bugs/issues/3961#issuecomment-651186387

There's a chance this is fixed, so it's worth checking the next beta release.

**Comment by AshleyScirra** [comment] 2020-06-30 14:40
A potential fix is in r206, could you test again and see if that helps?

**Comment by Mr-Josh-web** [comment] 2020-06-30 16:33
Hi Ashley,

I have exported the project using the latest beta release (r206) using advance mode minifying and the app doesn't start up. It will be related with the new minifier you are using.  (This is another issue so I do not want to mix things up but it will be good to upload apps to production environment with advance minify mode).

Finally, I have exported the app minifying it with simple mode and seems to work fine on Test flight. I have just uploaded to App Store Connect and is now "waiting for review".

I should also point out that the "go to URL" is also failing in this new beta release (https://github.com/Scirra/Construct-3-bugs/issues/3992). I do not want to mix things up because we are here to solve the Mobile IAP issue. I just want to say that the app has the URL feature and it will be failing on a production environment.

I will let you know if the Mobile IAP works as soon as the app is approved.

Thanks. 

Regards.

I have just exported the project using the latest beta release version (r206) and minifying it with advanced mode.

The mobile app has been uploaded to the app store connect and it's now waiting for review. I'll let you know if this version of C3 solves the issue as soon as the review team approves it.

Thanks.

**Comment by Mr-Josh-web** [comment] 2020-07-02 07:50
Morning Ashley,

I can confirm that this beta version of C3 fixes the issue with Mobile IAP on iOS.

I will also test the next stable version to see if it works fine. Do you know more or less when the next stable version will be released?

Many thanks for the quick fix. 

Regards.

**Comment by AshleyScirra** [comment] 2020-07-02 09:45
That's great, thanks for confirming - it seems it was a duplicate of #3608 after all.

We don't have an ETA on the next stable release yet but they tend to come roughly every 2 months or so. The next one should be out by the end of August.

**Closed by AshleyScirra** 2020-07-02 09:45 UTC
Labels: difficult, duplicate, external, iOS
