### ISSUE TITLE
Websocket connection handshake fails in WebView

### ISSUE THREAD

**Issue by eonianvr** [Scirra/Construct-3-bugs#2937] opened 2019-05-13 20:34 UTC
My Project  is on stand by because of the bug reported on the signed APK with the multiplayer plugin

## Steps to reproduce
Create this issue to follow up on the post  https://bugs.chromium.org/p/chromium/issues/detail?id=961393  as the original issue was closed and there is not direction how to follow up on this.

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2019-05-13 21:10
Closing as duplicate of #2710. The problem is with the Android Webview, not Construct. We cannot fix it ourselves, so we filed a bug with Google, hence the report at crbug.com/961393. The issue will be followed up there.

**Closed by AshleyScirra** 2019-05-13 21:10 UTC
Labels: duplicate
