### ISSUE TITLE
Replace is causing a crash.

### ISSUE THREAD

**Issue by bible9230** [Scirra/Construct-3-bugs#1307] opened 2018-02-21 06:35 UTC
## Problem description
I am learning how to use multiplayer and was playing with the Pong file.  I added an object that I wanted to used instead of the Paddle.  All the variables and behaviors were duplicated so "replace" would be possible.  After replacing the paddle object and running the layout, it crashed.  When I add the exact same actions from scratch, it does not crash.

At line 7, the supplied .c3p file shows two lines of a disabled green InfoObject that were created from scratch.  If you disable these and run it there is no problem.

## Attach a .c3p

https://www.dropbox.com/s/dmtkbdavmm4dq40/Multiplayer%20pong%20testing.c3p?dl=0

## Steps to reproduce

1.  At line 7 "replace" the two Paddle objects with InfoObject
2.  Run the layout
3.  It will crash

## Observed result

It accepts the replacing of the objects but crashes when you run it.

## Expected result

No crash.

## Affected browsers

* Chrome: yes

## System details

Error report information
Type: assertion failure
Message: cannot find instance variable export index
Stack: Error at Function.ǃN.ǃdyJ (https://editor.construct.net/r87/main.js:2:206829) at t (https://editor.construct.net/r87/main.js:2:174040) at window.assert (https://editor.construct.net/r87/main.js:2:174447) at t.ǃNRy (https://editor.construct.net/r87/main.js:63:144706) at window.ǃdLe.ǃsgu (https://editor.construct.net/r87/main.js:63:362958) at window.ǃdLe.ǃNi$ (https://editor.construct.net/r87/main.js:63:355658) at a.map (https://editor.construct.net/r87/main.js:63:319581) at Array.map () at e.ǃNi$ (https://editor.construct.net/r87/main.js:63:319570) at d.map (https://editor.construct.net/r87/main.js:63:310809)
Construct 3 version: r87
URL: https://editor.construct.net/r87/
Date: Tue Feb 20 2018 22:00:06 GMT-0800 (PST)
Uptime: 78.4 s

Platform information
Browser: Chrome
Browser version: 64.0.3282.140
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_2
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
C3 release: r87 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M380 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by DiegoScirra** [comment] 2018-02-21 13:03
It seems there is a problem with the ReplaceObjectClassVisitor class when it is attempting to update instance variable parameters.

Not too sure what is the correct way to fix this, so assigning to @AshleyScirra

**Comment by AshleyScirra** [comment] 2018-02-22 12:40
I can't reproduce this with the following steps:

1. Open project
2. Open event sheet "Game events"
3. Right-click event 7, select 'Replace object'
4. Choose "Paddle", then choose "InfoObject"
5. Preview

It works OK. @DiegoScirra am I missing something?

**Comment by shortercode** [comment] 2018-02-22 12:41
@AshleyScirra it only crashes in production, appears in the console in dev

**Comment by AshleyScirra** [comment] 2018-02-22 13:12
Ah, production only... might be a minifier bug :-\

**Comment by bible9230** [comment] 2018-04-10 16:52
I am still getting a crash after replace.


Error report information
Type: assertion failure
Message: cannot find instance variable export index
Stack: Error at Function.ǃq.ǃRfb (https://editor.construct.net/r94-2/main.js:2:135921) at t (https://editor.construct.net/r94-2/main.js:2:102749) at window.assert (https://editor.construct.net/r94-2/main.js:2:103156) at t.ǃqNt (https://editor.construct.net/r94-2/main.js:63:145695) at window.ǃRCd.ǃZMU (https://editor.construct.net/r94-2/main.js:63:365375) at window.ǃRCd.ǃqmJ (https://editor.construct.net/r94-2/main.js:63:358025) at r.map (https://editor.construct.net/r94-2/main.js:63:321797) at Array.map () at e.ǃqmJ (https://editor.construct.net/r94-2/main.js:63:321786) at n.map (https://editor.construct.net/r94-2/main.js:63:313005)
Construct 3 version: r94.2
URL: https://editor.construct.net/r94-2/
Date: Tue Apr 10 2018 09:50:09 GMT-0700 (PDT)
Uptime: 45.7 s

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_2
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r94.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M380 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment] 2018-06-29 12:20
I cannot reproduce this any more using the r107.2 release. @bible9230 can you verify if it is fixed for you?

**Comment by bible9230** [comment] 2018-08-04 19:41
Yes. Thank you.

**Closed** 2018-08-06 11:54 UTC
