### ISSUE TITLE
Physic pushout is causing high cpu&gpu usage in c3runtime

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2011] opened 2018-09-08 19:11 UTC
## Problem description

Some strange case with physic behavior. Adding it on 5 sprites(250x250). On C2runtime cpu&gpu are both on ~0.5%, almost instantly after preview. But on c3runtime, GPU&CPU are on ~7%. After waiting it start to fall to 3% then stays around 3-1.5%. But it should be like c2runtime + some special put to sleep extra. 
Pushout is not working correctly in c3runtime. And results much higher GPU&CPU %.

## Attach a .c3p

[0010Physic_Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2363632/0010Physic_Bug.zip)

## Steps to reproduce

1.Preview example(chrome stable) with c2runtime. Maximise window. See low CPU usage
2.Switch C3runtime, preview. Maximise window. See Much higher CPU usage.

## Observed result
Physic behavior is causing some issue on C3runtime and have different CPU/GPU usage then c2runtime in same case.

## Expected result
Physic behavior when not doing anything should not add so much GPU&CPU usage(almost same as if physic behavior is removed).  After pushout is complete cpu&gpu should fall instantly alot, like c2runtime. 
Similar case to example, when only small corners are colliding, then in c2runtime cpu&gpu are 0.5% while c3runtime has both around 6-7%.

C3runtime should have even lower peformance impact then c2runtime, as it has some extra features to put object with physic to sleep.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.81
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36
C3 release: r115 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 476 mb (3.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2018-09-10 11:30
I don't think there's sufficient evidence of a bug here. I can reproduce measurement differences, but since we can't directly read the real CPU and GPU measurements in JavaScript, we have to use timer-based estimates. The problem with timing measurements is they can vary widely depending on the hardware power state. For example my desktop CPU clocks between 0.8 GHz - 4 GHz, so the same amount of work could take around 5x longer or shorter depending on its power state. Because our timer-based measurements only measure time, not the real usage, the measurements are liable to be out by a factor of up to 5x, especially when low power states are involved. I did try to run some profiles but when the system is 95%+ idle there is almost nothing significant in the measurements at all.

This is why our normal performance tests involve stressing the system until it drops to 30 FPS: the hardware will be in its top power state reducing timing variance due to hardware clock rate changes, the measured difference is much clearer, and running a profile produces useful measurements since almost all the time is taken up by useful work. I don't think it's worth trying to investigate anything which doesn't take this approach, since otherwise we might just be measuring the noise in power-management systems.

**Closed by AshleyScirra** 2018-09-10 11:30 UTC
Labels: not a bug

**Comment by SnipG** [comment] 2018-09-11 13:16
I tried multiple test to get reading at 30%FPS and there was almost no difference.
The reason I made the issue report, is that even though gpu&cpu readings on c3runtime could be false(in that certain case in main post ), and internals of c3 are complex. This problem messes up debug readings in stable+canary with c3runtime. So I hoped at frist, if this could be fixed, debug gets better too.
 
First case, I try to  develop a strong base for my project, i know base cpu reading in c3runtime. Whenever I add something new, I can see how much it affects(having cpu stable 6% or stable 8-10% certainly shows new code affect, and I can try optimize). But in c3runtime, if i let project sit 1min+. Cpu magically starts to lower to 2-1% from 6%. If i then start to move something fast it will go back up 6% but fast back down(but in frist ~1min preview, cpu stays 6% and when I move something it will go 6-7% and still stays 6%). If you go debug to see what changes, you literaly can`t read anything from it, like all reading before divided by 2 or 3(even draw calls). Even through you can get used to it and it does not affect much, it still thrive to look if I have something wrong or where does it come.
 
But it gets worse with c3runtime debug gpu reading.  This physic case adds huge gpu usage to random layer. So you can`t even use it to see how things really work or which layer affects the most. 
For example, with this bug most layers are on 0.5%, then random layer is on 3-5%. If you disable that layer, another gets 3-5% and so on. If i disable physic behavior, debug just shows single Layout reading at ~1-0%
I have no idea how timebased measurments are codes+chrome internals+real cpu usage. But debug is assigning  some reading to something like layers high gpu usage. Or when i did testing on canary i saw Cpu on 6-7% but Gpu were 9-13% then went  sometimes at 23% then went back down, versus 0.5% in c2runtime. 
Not sure if this stuff is worth spending time in. I am just pointing out my finding on some strange behaviors.

**Comment by AshleyScirra** [comment] 2018-09-11 13:38
As I said, it's not really useful to be taking performance readings with low usage numbers. They won't be accurate unless you're stressing the system.
