### ISSUE TITLE
r307 - broken sprite z-placement (or something wierd) after loading game (broken after r302)

### ISSUE THREAD

**Issue by MihaMS** [Scirra/Construct-3-bugs#6050] opened 2022-08-29 20:35 UTC
## Problem description

In r307 Beta - Saving and then Loading game is really breaks drawing of the sprites or/and layers. Spend a few hours, but can't really understand what's happening. It's really weird, pls watch the screenshots, I can't attach the project file.
First screenshot - game before loading, and Second screenshot - after loading. Something really weird happened - sprites on different layers is messed up with sprites on another layer with a strange visual effect...
Good news - in r302(stable) this doesn't happen, all works fine. So it's something recently broken.

Before Saveing and Loading:
![bug_before](https://user-images.githubusercontent.com/23280578/187293141-c19310b3-3ea1-47d6-b1ba-9043b973f165.png)

After Game was Loaded:
![bug_after](https://user-images.githubusercontent.com/23280578/187293174-5edbbb64-5471-49f6-923c-3de95c34cf46.png)

## Observed result

Game graphics is totally broken

## Expected result

Game looks the same as before loading

**Affected browsers/platforms:** 

Chrome (not tested with others)

**First affected release:** 

worked in r302(stable) but broke in r307beta (not tested in r303-306)
(tested on same project file without changes)
(and, ofcourse it's was a new save and loading for each C3 version, NOT loading game save from previous C3 release)

## System details

Windows 10

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by dop2000** [comment] 2022-08-30 04:43
Are you using hierarchies?

**Comment by MihaMS** [comment] 2022-08-30 05:14
> Are you using hierarchies?

In some places - yes, but not with this particular level objects that was affected (on screenshot).

**Comment by MihaMS** [comment] 2022-08-30 06:05
I recorded a video showing another weirdness happened with other objects... 
Maybe it's something with parallax or... idk... some objects on my layer called "Foreground" is moved and stretched heavily...

https://user-images.githubusercontent.com/23280578/187361364-e75c7725-eeac-4ca1-ad00-d2a4ac309435.mp4
maybe it will help somehow...

**Comment by MihaMS** [comment] 2022-08-30 11:01
also, while working in **r302** found another really strange behaviour of some sprite's collision polygon, that was created after start of layout (this side of the elevator is created and mirrored "On layout start"). As you can see on this record - at the beginning collision polygon works as it should, then if I load game (that was saved previously) - it breaks! Then, if I restart project in debugger - it works again, but after game loading - it fails again.
I also noticed that if I start layout close to this problematic sprite, and then load - it works fine, but if I do this father away - it breaks.
I don't know - is this have the same issue with what happened in r307, but looks like that something similar was in r302 but only with collision poligons, that became a bigger problem with whole sprites later...

https://user-images.githubusercontent.com/23280578/187419733-0dc7e516-6315-4c0b-9dc3-6ac417b2938b.mp4

This problematic part of elevator (sprite), was created "On Start of layout" condition in that way:

![Screenshot 2022-08-30 125749](https://user-images.githubusercontent.com/23280578/187419977-8c8032a2-e1ae-4a10-a14d-97ecdf49df95.png)

I hope this gives to you more understanding and clues of what happened)

**Comment by AshleyScirra** [comment] 2022-08-30 11:09
This may be impossible to fix unless you can provide a minimal project as per the bug report guidelines. Otherwise we have no way to verify if any change we make has fixed the problem.

**Comment by DiegoScirra** [comment] 2022-08-30 11:24
This is likely a duplicate of #6041

**Comment by AshleyScirra** [comment] 2022-08-30 15:21
r308 is now out, you can check again there to see if the issue resolved. If not we'll need a bug report following all the guidelines otherwise it's impossible for us to help, so closing this issue.

**Closed by AshleyScirra** 2022-08-30 15:21 UTC
Labels: no repro
