### ISSUE TITLE
When the full screen mode is turned off An error occurs

### ISSUE THREAD

**Issue by naruto700** [Scirra/Construct-3-bugs#888] opened 2017-10-05 18:09 UTC
## Problem description

*When the full screen mode is turned off
The game does not play in the middle of the screen as it does in construct 2*

## Attach a .c3p

*Please try a project Flying along*

## Steps to reproduce

1.full screen mode is turned off
2.The browser window is maximized

## Observed result

*The program logo remains in full-screen mode
The game works in the corner of the screen*

## Affected browsers

* Chrome: yes
* Firefox: yes

## System details

* Firefox 56.0  64bit  
Chrome 61.0 64bit  
windows 8 
screen resolution 1366*768
*

**Comment by AshleyScirra** [comment] 2017-10-06 10:20
Can't reproduce. No project provided so tried Ghost Shooter and it works correctly, so closing. Note what you describe is the correct behavior depending on the project settings.

**Closed by AshleyScirra** 2017-10-06 10:20 UTC
Labels: ignored guidelines

**Comment by naruto700** [comment] 2017-10-06 15:55
Thanks for the quick response
Sorry..My English is weak

That's what I see
https://imgur.com/a/N6DtX

**Comment by naruto700** [comment] 2017-10-06 16:01
That's what I see in construct2
https://imgur.com/a/e7LxS

**Comment by AshleyScirra** [comment] 2017-10-06 17:24
Without a way to reproduce the problem, there's not much we can do. It could be a graphics driver problem, check your system is up-to-date.

**Comment by naruto700** [comment] 2017-10-06 17:40
thank you very much :)
