### ISSUE TITLE
r72 Cause user to log out each time browser is restarted

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#1093] opened 2017-12-12 08:46 UTC
## Problem description
Construct keeps logging out by itself each time I restarted it. My Construct is viewed through the "add to desktop" mode.

## Steps to reproduce

1. Log-in Construct
2. Close Construct and all instances of the browser.
3. Re-open Construct.

## Observed result
Construct logged out.

## Expected result

Stay logged in

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 63.0.3239.84
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
C3 release: r72
Language setting: en-US

Local storage
Storage quota (approx): 7.2 gb
Storage usage (approx): 926 mb (12.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 765M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2017-12-12 11:45
Can't reproduce here, works normally in both browser and "add to homescreen" mode. Do you have any browser extensions that might be interfering?

**Comment by jaydonteh** [comment] 2017-12-12 14:36
It happens after the update to r72. I disabled all my extensions which is just adblockers and TunnelBear, but nothing seems to reverse the issue.

**Comment by AshleyScirra** [comment] 2017-12-12 14:58
Are there any messages in the browser console after you log in?

**Comment by jaydonteh** [comment] 2017-12-12 15:05
Nothing Suspicious tho
![console](https://user-images.githubusercontent.com/20452123/33891432-e163f372-df90-11e7-9e11-ad705d9e266d.png)

**Comment by AshleyScirra** [comment] 2018-01-02 15:32
Not sure there's anything we can do about this. I haven't seen any other similar reports and I can't reproduce it so closing as presumably a system-specific issue.

**Closed by AshleyScirra** 2018-01-02 15:32 UTC
Labels: can't reproduce
