### ISSUE TITLE
[R29] Impossible to save

### ISSUE THREAD

**Issue by el3um4s** [Scirra/Construct-3-bugs#258] opened 2017-05-18 22:23 UTC
## Problem description

Impossibile save c3p file

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Try to save a project

## Observed result

Crash
See the video
[![Alt text](https://img.youtube.com/vi/Q1UNBdHY2g0/0.jpg)](https://www.youtube.com/watch?v=Q1UNBdHY2g0)

## Expected result

Save the project

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'catch' of undefined @ TypeError: Cannot read property 'catch' of undefined at Sa (https://editor.construct.net/r29/cloud/sandbox.js:1:32469) at Wa (https://editor.construct.net/r29/cloud/sandbox.js:1:32958) at Za.eb.keys.then.gb (https://editor.construct.net/r29/cloud/sandbox.js:1:33324) at 
Stack: TypeError: Cannot read property 'catch' of undefined at Sa (https://editor.construct.net/r29/cloud/sandbox.js:1:32469) at Wa (https://editor.construct.net/r29/cloud/sandbox.js:1:32958) at Za.eb.keys.then.gb (https://editor.construct.net/r29/cloud/sandbox.js:1:33324) at 
Construct 3 version: r29
URL: https://editor.construct.net/
Date: Fri May 19 2017 00:00:28 GMT+0200 (CEST)
Uptime: 33 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.83
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Android
Operating system version: 6.0.1
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 3
Logical CPU cores: 6
User agent: Mozilla/5.0 (Linux; Android 6.0.1; Redmi Note 3 Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Mobile Safari/537.36
C3 release: r29

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Qualcomm
Renderer: Adreno (TM) 510
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_atc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment] 2017-05-18 22:45
Duplicate of [#251](https://github.com/Scirra/Construct-3-bugs/issues/251)

A bug fix will most likely be issued tomorrow morning, in the mean time you can use "Download a copy" as a work around. Sorry, we know it's a pain!

**Closed by shortercode** 2017-05-18 22:45 UTC
Labels: duplicate
