### ISSUE TITLE
Destroy w/ pinned object

### ISSUE THREAD

**Issue by Bigbeto123** [Scirra/Construct-3-bugs#3788] opened 2020-04-19 18:00 UTC
"Destroy with pinned object" from pinned behavior is bugged. As in the demonstration file shows, particles spawned by it will simply freeze in time for some reason, breaking lots of stuff around it (such as other pinned moving objects and such). Happened to a much more intensive degree in my project, but I'm not gonna waste my time to replicate every single thing. This should be more than enough to trace it.

## Attach a .c3p
[bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4499867/bug.zip)

1.create a sprite
2.create another one and pin to it
3.check the destroy w/ pinned object box and then destroy it via some way

stuff freezes around it. specially other moving pinned objects

as always, it should not be a broken mess

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.163
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
C3 release: r195 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 442 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Bigbeto123** [comment] 2020-04-19 18:01
Been quite a spree.
Back to what I said:
**Way too many bugs for a premium product**
Hopefully you understand where I came from now

**Comment by AshleyScirra** [comment] 2020-04-20 11:17
Looks like a duplicate of #3755 - works here and so should be already fixed for the next release.

Note the Pin behavior's destroy feature is currently only available in beta releases. The purpose of beta releases is to identify and fix issues like this, which has already happened. By using them you are opting in to potentially dealing with more bugs, which we warn about. I do not believe it is reasonable to complain about this since you have chosen to use less stable releases, so closing due to bad faith discussion again as per the forum & community guidelines. Almost all users are more constructive in their approach to bug reports. Please read the guidelines carefully to avoid further action being taken in future.

**Closed by AshleyScirra** 2020-04-20 11:17 UTC
