### ISSUE TITLE
Erro exporting Project to Android

### ISSUE THREAD

**Issue by dimielannes** [Scirra/Construct-3-bugs#5575] opened 2022-03-28 15:31 UTC
I'm trying to export my project but it's giving an error (since saturday 03/26/2022)

## Attach a .c3p
[Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/8364169/Bug.zip)

## Steps to reproduce

1. create new project
2. try export to android app bundle
3.

## Observed result

Failed to export project. Check the browser console (press F12) for more

...

main.js:759 Error exporting:  Error: Invalid Android version
    at vvb (/r287/exporters/cordova/exporter.js:17:274)
    at hvb (/r287/exporters/cordova/exporter.js:16:362)
    at kvb (/r287/exporters/cordova/exporter.js:8:156)
    at async p6.KH.$Pa.aQ (/r287/exporters/cordova/exporter.js:29:388)
    at async I6a.nlc (/r287/projectResources.js:2884:238)
    at async Object.CCG.ipa (/r287/main.js:759:144)

## Expected result

build fail

## More details

Win7 Google Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2022-03-28 15:57
Duplicate of #5546

**Closed by AshleyScirra** 2022-03-28 15:57 UTC
Labels: duplicate
