### ISSUE TITLE
Crash when selecting objects

### ISSUE THREAD

**Issue by ttekien** [Scirra/Construct-3-bugs#4289] opened 2020-10-13 18:25 UTC
## Problem description

New layer was created. Some objects in the layout were selected. Crash happened.

## Attach a .c3p

N/A

## Steps to reproduce

1. 
2.
3.

## More details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r220/components/bars/propertiesBar/propertiesBar.js, line 71, col 287
Message: Uncaught TypeError: Cannot read property 'Ik' of null
Stack: TypeError: Cannot read property 'Ik' of null at n.ca.RYc (https://editor.construct.net/r220/components/bars/propertiesBar/propertiesBar.js:71:287) at n.ca.UQ (https://editor.construct.net/r220/components/bars/propertiesBar/propertiesBar.js:52:229) at n.K$b (https://editor.construct.net/r220/components/bars/propertiesBar/propertiesBar.js:19:523) at Array.Qla (https://editor.construct.net/r220/components/bars/propertiesBar/propertiesBar.js:3:225) at d.Event.$Jc.G8c (https://editor.construct.net/r220/main.js:428:387) at window.jdb.dispatchEvent (https://editor.construct.net/r220/main.js:424:135) at window.jdb.qia (https://editor.construct.net/r220/main.js:2094:372) at p.w2c (https://editor.construct.net/r220/components/editors/layoutView/layoutView.js:157:503) at p.sq (https://editor.construct.net/r220/components/editors/layoutView/layoutView.js:157:187) at p.rc (https://editor.construct.net/r220/components/editors/layoutView/layoutView.js:151:107)
Construct 3 version: r220
URL: https://editor.construct.net/r220/
Date: Tue Oct 13 2020 20:21:26 GMT+0200 (czas środkowoeuropejski letni)
Uptime: 45 s

Platform information
Browser: NW.js
Browser version: 0.49.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.49.0 (like Chrome/86.0.4240.75)
C3 release: r220 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 570 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2020-10-13 18:26
Duplicate of #4287

**Closed by AshleyScirra** 2020-10-13 18:26 UTC
Labels: duplicate
