### ISSUE TITLE
GIF animation with several frames imported "From Files" only imports the first frame

### ISSUE THREAD

**Issue by Yaenne** [Scirra/Construct-3-bugs#1121] opened 2017-12-27 11:24 UTC
## Problem description

Importing an animated GIF into a sprite via "Import Frames" > "via Files" does not work.
Only the first frame will be imported.

## Attach a .c3p

https://www.dropbox.com/s/zcre1945c7yzysi/FrameImportIssue.zip?dl=0

## Steps to reproduce

1. Create a sprite
2. Go to "Animation Frames Window"
3. Choose "Import from Files"
4. Choose an animated GIF with more than 1 frames (see GIF in project folder)

## Observed result

Only the first frame will be imported.
In the Edge Browser nothing is imported at all.

## Expected result

All frames from the GIF should be imported to the "Animation Frames"

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 57.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
C3 release: r73
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 28 mb (1.4%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    UI animations are disabled in Firefox due to bug 1354501
    CSS containment is not supported. Editor performance may be significantly degraded.
    The <dialog> element is not supported. A polyfill is in use.
    This browser does not support pluralisation rules. Plural forms may not be correct.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_texture_filter_anisotropic
    EXT_disjoint_timer_query
    OES_texture_float_linear
    WEBGL_compressed_texture_s3tc
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context
    MOZ_WEBGL_lose_context
    MOZ_WEBGL_compressed_texture_s3tc

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    WebM Vorbis (audio/webm; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2017-12-28 23:01
Duplicate of #1077.

**Closed by AshleyScirra** 2017-12-28 23:01 UTC
