### ISSUE TITLE
Cannot load or save c3p projects locally after updating to C3 Release 142

### ISSUE THREAD

**Issue by gberenst** [Scirra/Construct-3-bugs#2772] opened 2019-03-25 14:22 UTC
## Problem description

I was working fine with C3, always saving project locally, and sometimes making backups by downloading c3p files to my computer. 
After release 142 and now 142.2 I can´t either open previously saved local c3p files (it says Failed to open project), nor saving it in local storage (it opens a popup that says failed to open list).

## Attach a .c3p

You can find it attached under a zip file
[Test142.zip](https://github.com/Scirra/Construct-3-bugs/files/3003699/Test142.zip)

## Steps to reproduce

1. Open file
2. Save it with Save as > Save to local browser

## Observed result

A pop up shows telling it failed to open project

## Expected result

save file locally as usual

## More details

**Affected browsers/platforms:** Chrome (It does not even open in Firefox)

**First affected release:** 142

## System details

Windows 10

**Comment by LukeNecklace** [comment] 2019-03-25 15:12
Confirmed.

I seem to be getting an "unable to get permission to persist storage. Try adding Construct 3 to your desktop/home screen." Message when I try to save it in chrome.

As for Firefox: I cannot replicate that issue. I was able to save it and open it like normal.

**Comment by gberenst** [comment] 2019-03-25 15:26
I am always using it with chrome by opening from desktop icon. I have also deleted and created new shortcut by launching from Chrome browser and installing it as an app again, but same issue happening. When opening downloaded c3p, I can work with localstorage data perfectly during game execution, but not with the c3p files.

**Comment by AshleyScirra** [comment] 2019-03-25 15:38
Can't reproduce here, the provided project saves and opens fine when saved to browser storage.

Can you check the browser console for any errors? Press F12 to open it.

**Comment by LukeNecklace** [comment] 2019-03-25 15:48
No errors but I got a couple of warnings:

![](https://i.imgur.com/cT5Ry7E.png)

**Comment by gberenst** [comment] 2019-03-25 16:23
I just get this on console when trying to open local
![image](https://user-images.githubusercontent.com/48917913/54936415-31c3fc00-4f01-11e9-89d3-3d2d19a6b8e7.png)

**Comment by gberenst** [comment] 2019-03-25 16:25
And this when trying to save in local browser:
![image](https://user-images.githubusercontent.com/48917913/54936533-6a63d580-4f01-11e9-98af-ae6ddf87dc31.png)

**Comment by LukeNecklace** [comment] 2019-03-28 01:33
Just to confirm, this is what I get when I load a file. I don't know why it's different to gberenst unless it is because he is using a different version. Everything loads fine for me.

![](https://i.imgur.com/TMFp5Nh.png)

**Comment by shortercode** [comment] 2019-03-28 11:50
By the sounds of it @gberenst has had some sort of partial corruption of his save data, we already have quite a few checks that should prevent this being a problem but I guess we missed some edge cases. I'm confused how it happened though... Under most error situations all local files will be deleted, causing a fresh start.

@LukeNecklace I don't think your having any issues, the warnings you posted a screenshot of aren't related to the save system. I'm not sure why your getting the "unable to persist" dialog message, but I wouldn't worry too much about it if I were you though. The "persistent storage" mode just tells the browser that it shouldn't delete save data without user input, unfortunately this doesn't protect against the "clear browsing data" tool in Chrome which just deletes the data for every site. I think they couldn't work out the UI for it unfortunately so it's kind of half finished...

**Comment by shortercode** [comment] 2019-03-28 18:33
It's hard to resolve what the exact issue that caused this corruption is, @gberenst can you recall what version you were using previously? It might be that a legacy save upgrade failed somehow.

My current plan is to harden the browser save system further against file corruption. Hopefully this will resolve any problems with your current save data, and prevent similar issues from occurring in future. While we try to preserve as much data as we can in these situations you may suffer partial/complete loss of any browser saves unfortunately. So I hope those backups you mention are up to date. Given the unknown state of your save data it's hard to predict what data will be preserved at this point.

However, if the failure was with the legacy save upgrade system and you can provide me with enough information to figure out how it broke I may be able to add additional code to recover broken data ( depending on what state it is in ).

**Comment by gberenst** [comment] 2019-03-28 18:40
@shortercode, thanks for the update, i am always using latest version, and updating every time a new version comes out. I was using 141, then 142, and finally 142.3 when problem showed up. Always udes windows 10 with chrome, never had any problem. Will try to revert version, uninstall and reinstall chrome.

**Comment by shortercode** [comment] 2019-04-02 13:36
Okay thanks for the extra information @gberenst I've completed the additional defensive pieces to the code I mentioned. I will review any changes we made between 141/142/142.2/142.3 to see if anything potentially bad crept in that could be effecting you.

**Comment by gberenst** [comment] 2019-04-02 20:07
@shortercode Thank you!!!

**Comment by shortercode** [comment] 2019-04-03 11:15
@gberenst I can't actually see any notable changes made to browser saves since last June, so I expect this is either a really obscure bug or something external. If it's the prior then we probably have no hope of identifying it, unless this starts happening to you frequently.

Either way the rework should hopefully resolve issues caused by both cases. It will be included in the next beta release. I'm going to close this issue as I don't think there's any other actions I can take directly related to this.

**Closed by shortercode** 2019-04-03 11:15 UTC
Labels: can't reproduce
