### ISSUE TITLE
Timeline ends with incorrect results when playing on multiple instances

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3213] opened 2019-08-14 11:58 UTC
## Problem description

This is linked to https://github.com/Scirra/Construct-3-bugs/issues/3212
Just describing a different issue in the c3p file:

When the timeline stops playing, some instances have incorrect end values.

## Attach a .c3p
Same as https://github.com/Scirra/Construct-3-bugs/issues/3212
[Transition system.zip](https://github.com/Scirra/Construct-3-bugs/files/3501205/Transition.system.zip)

## Steps to reproduce

1. (Optional) remove the destroy action in the events
2. Open the preview
3. Click anywhere on the layout

## Observed result
![image](https://user-images.githubusercontent.com/11213825/63019372-67ab5200-be9b-11e9-8351-39e810f67358.png)

Some squares take different end angle values which are wrong.

## Expected result

All the squares should end with the correct value (in that case, 0)

## More details

You can play the timeline in the editor to see what the  desired behavior is.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment] 2019-08-14 13:42
Duplicate of #3211

**Closed by DiegoScirra** 2019-08-14 13:42 UTC
Labels: duplicate
