### ISSUE TITLE
Loading a r177 project crashes C3 (desktop and mobile)

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#3506] opened 2019-11-29 13:33 UTC
## Problem description
I tried to load my last project on OneDrive I saved earlier today and now C3 crashes every time I try to open it. Same when I load the local backup file I made.

I can load a new project I just made for testing. No idea what the error means and why I cant open my game project anymore.

## Steps to reproduce

1. open project in 177
2. save project
3. open it again

## Observed result

Error report information
Type: assertion failure
Message: unsupported path mode
Stack: Error at Function.ǃDCO (https://editor.construct.net/r177/main.js:2:125274) at e (https://editor.construct.net/r177/main.js:2:85003) at https://editor.construct.net/r177/main.js:2:85333 at Function.ǃMuj (https://editor.construct.net/r177/projectResources.js:1:455787) at a.ǃKO (https://editor.construct.net/r177/projectResources.js:1:431841) at a.ǃKO (https://editor.construct.net/r177/projectResources.js:1:496868) at a.ǃ_PT (https://editor.construct.net/r177/projectResources.js:1:434706) at a.ǃ_PT (https://editor.construct.net/r177/projectResources.js:1:502214) at a.ǃae (https://editor.construct.net/r177/projectResources.js:1:502520) at Function.ǃMf_ (https://editor.construct.net/r177/projectResources.js:1:504142)
Construct 3 version: r177
URL: https://editor.construct.net/r177/
Date: Fri Nov 29 2019 14:30:58 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 19.4 s

Platform information
Browser: Chrome
Browser version: 78.0.3904.108
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
C3 release: r177 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 615 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
## More details

happens on Desktop and mobile version of 177

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
177
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 78.0.3904.108
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
C3 release: r177 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 21 gb
Storage usage (approx): 1.3 gb (6.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 615 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2019-11-29 14:03
I believe this is a duplicate of #3502 but I will leave it open for @DiegoScirra to confirm.

**Comment by TheBl4ckSh33p** [comment] 2019-11-29 15:12
Thanks! I hope there will be a new beta version soon. Need to finish the game and I made the mistake to use the beta right before release.

**Comment by TheBl4ckSh33p** [comment] 2019-11-29 15:15
Is it possible to use the previous version to open it without breaking everything? 🤔

**Comment by shortercode** [comment] 2019-11-29 15:23
You can _sometimes_ edit a c3p so that it will open in an older release, but I think in this situation the issue is related to projects having unexpected timeline settings. So I don't think an older version would open it. I guess you can try modifying a copy of your project to see if it works? An alternative is some cloud services keep previous revisions of files, so you might be able to recover your previous save from OneDrive.

We'll probably have a beta out on Monday. If it's urgent then @DiegoScirra might be able to recover your project.

**Comment by TheBl4ckSh33p** [comment] 2019-11-29 17:24
Thanks for your reply. I'll check if there are other versions on one drive but I made lots of changes and additions before it broke today. Don't want to lose hours of work. 😢

**Comment by DiegoScirra** [comment] 2019-11-29 17:27
This is already fixed in the next beta.

Manually fixing an project shouldn't be too hard, but you will need to be careful not to save it again in r177.

@TheBl4ckSh33p you can send your project to me at diego@scirra.com

**Comment by TheBl4ckSh33p** [comment] 2019-12-03 09:36
I can open it in r178. Thanks!

**Closed** 2019-12-03 10:11 UTC
