### ISSUE TITLE
Remote preview can't be up for a long time

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1146] opened 2018-01-06 15:43 UTC
## Problem description

Apart from getting crashes every now and then using remote preview, if it's kept for a longer time (~ 1 hour or so) the signaling ID is lost and the remote preview must be restarted again.

## Attach a .c3p

![image](https://user-images.githubusercontent.com/7268697/34641183-dca324e4-f308-11e7-9be7-658ab7d265f6.png)

Remote preview window seems fine though. It has 1 client connected out of 2 (since the 2nd client refreshed and couldn't connect anymore)

![image](https://user-images.githubusercontent.com/7268697/34641186-eb27984c-f308-11e7-83e3-5ae33700c9b6.png)

## Steps to reproduce

1. open a blank project
2. start remote preview
3. leave it like so for ~ 1h or more
4. try to refresh the page on the client who's previewing

## Observed result

At some point no client can connect anymore

## Expected result

I expect this to last for much longer than currently

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 63.0.3239.84
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
C3 release: r75
Language setting: en-US

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 1.8 gb (26.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2018-01-16 19:30
Currently the remote preview server disconnects hosts who are idle for 20 minutes. If anyone loads a remote preview, it resets the limit, so e.g. if someone joins every 15 minutes it will host indefinitely. There is a limit by design - if they could stay hosting indefinitely, then the signalling server would gradually clog up with long-term hosting clients until it got full. It's also not intended to be used for long-term hosting, remote preview is meant to be a quick-test type thing.

Still, I guess 20 minutes is pretty short for some cases. I've bumped up the limit on the server to 24 hours, so if you're hosting remote preview for 1 day and nobody connects to you, the server will kick you off. I'd be reluctant to increase it any further, hopefully this is enough.

**Comment by JeFawk** [comment] 2018-01-16 19:59
Awesome thanks! 24h should be more than enough.

**Comment by JeFawk** [comment] 2018-01-17 19:42
I just got this :/ 

The preview was up for i guess 30 minutes though yesterday it was up for way longer without many issues.

![image](https://user-images.githubusercontent.com/7268697/35063301-6024b1c4-fbcf-11e7-96b0-04e253af8e0c.png)

**Comment by JeFawk** [comment] 2018-01-23 15:26
I'm  still getting these more often than before really, happens even after 10 minutes of the remote preview being up.

![image](https://user-images.githubusercontent.com/7268697/35284059-851a1676-0062-11e8-91d3-ce50be3677ea.png)

**Comment by AshleyScirra** [comment] 2018-01-23 16:03
Bah. No idea where this is coming from, might be a CloudFlare timeout or something. Plus it takes ages to test...

**Comment by AshleyScirra** [comment] 2018-06-27 12:41
@JeFawk are you still having trouble with this?

**Comment by AshleyScirra** [comment] 2018-06-27 13:32
I'm not sure what was going on here and there's no clear way to investigate, so closing this one off. Please file a new issue if you have trouble again in future.

**Closed by AshleyScirra** 2018-06-27 13:32 UTC
Labels: difficult
