### ISSUE TITLE
Save error and Download a copy error

### ISSUE THREAD

**Issue by DinoS124** [Scirra/Construct-3-bugs#743] opened 2017-08-24 17:48 UTC
## Problem description

When I try to save my project, a small window pops up that says _Expected Array_. After I close it, the project is archiving, but it never ends and none of my changes are saved after I reopen the project. Also, when I try to download a copy, the editor crashes and an error window pops up (Type: unhandled rejection
Reason: Error: expected array @ TypeError: expected array at Function.!m.!Cj).

## Attach a .c3p

I can't because _Download a copy_ doesn't work.

## Observed result

The project won't save nor I can download a copy of it.

## Expected result

Save project and download a copy without a crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

I don't know why, but I can't copy the crash report. Nothing happens after I click _Copy information_ and try to paste it here or anywhere else. Sorry.

Platform information
Browser: Chrome
Browser version: 60.0.3112.101
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36
C3 release: r50

</details>

**Comment by Leralasss** [comment] 2017-08-24 19:00
happens to me on chrome too

**Comment by el3um4s** [comment] 2017-08-24 22:16
happens to me on chrome too

**Comment by JeFawk** [comment] 2017-08-25 00:33
same

**Comment by cihanyakar** [comment] 2017-08-25 06:55
Problem is in `.uistate.json` files.

Old r49 files like: 
``"uids": [4,13],`

r50's are  :
`"uids": "[4,13]",`

**Comment by DiegoScirra** [comment] 2017-08-25 10:01
Closing this one as it is a duplicate of #744.

**Closed by DiegoScirra** 2017-08-25 10:01 UTC
Labels: duplicate
