### ISSUE TITLE
[r29.2] Sprite objects turn red colour box and source image not found crashed

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#284] opened 2017-05-19 17:59 UTC
## Problem description
I never knew the image source was tied into the project that was open locally (I'm not sure if it was opened from local browser or local file). When I remove some of the source files used in the project, which was the images I made on my local disc, Construct just show the affected Sprite objects RED in colour. Yes the crash RED colour in rectangles the size the objects. When I tried to open the Sprite object, it crashed.

Silly me for not reporting this straight away. Because of that I have no crash report attached and the mentioned project has been worked on to this hour already. It recovered from the crash and the project isn't corrupted but the sprites are now unable to show properties. I have also have then deleted those Sprite objects and re-imported them.

## Observed result

Sprite objects unable to retrieve source image and crashed while opening affected Sprite objects. Very hard to explain, sorry.

## Expected result

No crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1458333730697632
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

Local storage
Storage quota (approx): 7.2 gb
Storage usage (approx): 413 mb (5.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2017-05-23 12:38
The files should be read when you import them, it shouldn't keep a reference to the location on disk. I just tried it: I imported a sprite from a PNG file on disk, moved the file somewhere else so the original path can't be found, and then saved the project - it seemed to save fine. So closing this for now, please file again if you find repro steps.

**Closed by AshleyScirra** 2017-05-23 12:38 UTC
Labels: no repro

**Comment by jaydonteh** [comment] 2017-05-23 13:37
@AshleyScirra Do you need to use 2 labels for no repro? Just sayin'

**Comment by AshleyScirra** [comment] 2017-05-23 13:49
They are two different issues, one means I can't reproduce it, the other means there aren't reproduction steps.
