### ISSUE TITLE
Load Project By File Crash on r165

### ISSUE THREAD

**Issue by rhg1968** [Scirra/Construct-3-bugs#3326] opened 2019-09-10 16:42 UTC
## Steps to reproduce

1. Load r165
2.Click on File Button to Load a Project
3.Construct crashes

## Observed result
Construct crashed

## Expected result
The open file dialog box would appear

## More details

**Affected browsers/platforms:** 

**First affected release:** 
r165

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: ǃOXR is not defined @ ReferenceError: ǃOXR is not defined at window.ǃOdg.ǃOXh (https://editor.construct.net/r165/main.js:210:91800) at window.ǃOdg.ǃKO (https://editor.construct.net/r165/main.js:210:90886) at window.ǃONn.ǃOmb (https://editor.construct.net/r165/components/misc/startPage/startPage.js:1:11478) at HTMLDivElement.ǃoZu.onclick (https://editor.construct.net/r165/components/misc/startPage/startPage.js:1:2132)
Stack: ReferenceError: ǃOXR is not defined at window.ǃOdg.ǃOXh (https://editor.construct.net/r165/main.js:210:91800) at window.ǃOdg.ǃKO (https://editor.construct.net/r165/main.js:210:90886) at window.ǃONn.ǃOmb (https://editor.construct.net/r165/components/misc/startPage/startPage.js:1:11478) at HTMLDivElement.ǃoZu.onclick (https://editor.construct.net/r165/components/misc/startPage/startPage.js:1:2132)
Construct 3 version: r165
URL: https://editor.construct.net/r165/
Date: Tue Sep 10 2019 12:41:06 GMT-0400 (Eastern Daylight Time)
Uptime: 47.2 s

Platform information
Browser: Chrome
Browser version: 76.0.3809.132
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
C3 release: r165 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment] 2019-09-10 17:12
Duplicate of #3319

**Closed by AshleyScirra** 2019-09-10 17:12 UTC
Labels: duplicate
