### ISSUE TITLE
[Firefox] Renaming objects in project windows weird graphical bug.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#1365] opened 2018-03-12 15:10 UTC
## Problem description

When trying to rename objects in the project bar. Weird graphical bug places the rename input field weirdly on the left hand side of the window.

## Attach a .c3p

N/A

![firefox](https://user-images.githubusercontent.com/27011641/37291835-d2e89fc6-260f-11e8-96e6-28b4c867981f.png)

## Steps to reproduce

1. Open editor in firefox.
2. Create a new sprite.
3. Right click to rename the sprite.

## Observed result

Renaming input box is places somewhere else on screen.

## Expected result

Should be placed where the original name is like in chrome.

## Affected browsers

* Chrome: no
* Firefox: yes

**Comment by tunepunk** [comment] 2018-03-12 15:20
This is something that must have broke with a Firefox update, as it's the same in previous C3 versions as well.

**Comment by nalcwap** [comment] 2018-03-12 22:47
i reported before in android firefox editores image the left part is bugged but not fixed ,example particle editor or image same bug not correct in firefox

**Comment by shortercode** [comment] 2018-03-13 11:48
I'm not quite sure what Firefox broke but I managed to find a pretty simple fix for this.

@nalcwap If your referring to #1180 I don't think it's related, but @DiegoScirra has been looking into that.

**Comment by AshleyScirra** [comment] 2018-03-16 11:29
The fix doesn't work in release. Don't want to hold up r91 for this so reopening to reinvestigate.

**Comment by nalcwap** [comment] 2018-03-17 00:08
shortercode  yes sorry i mean this error you post

**Comment by shortercode** [comment] 2018-06-29 13:59
Well I can't reproduce this issue in the current build, it looks to me like the fix in r91 does work so I'm just going to close this issue.

**Closed by shortercode** 2018-06-29 13:59 UTC
Labels: firefox
