### ISSUE TITLE
Preview Popup does not size correctly

### ISSUE THREAD

**Issue by pixelmetal** [Scirra/Construct-3-bugs#112] opened 2017-04-21 15:06 UTC
## Problem description

When previewing C3 projects in a popup window, the window does not take into account the size of the top bar. 

This occurs with C3 running in a Chrome tab when launched directly from Construct.net in Windows 7 & 10 or from a Desktop app shortcut on Windows 7 & 10. 

On OSX it occurs only when launching from a Desktop link (Applescript launch of Chrome with no interface).

## Attach a .c3p

No need, open any C3 project, observe results.

## Steps to reproduce

1. Make sure "Popup" is the preview style
2. Run a project
3. Observe

## Observed result

C3 does not take into account the size of the top bar on the window. In this example, the game canvas should be 1280x720, but it's scaled down to fit.
![popup_preview_size_01](https://cloud.githubusercontent.com/assets/1434926/25283371/8252d5f6-2681-11e7-9844-bc2c76649979.png)

## Expected result

C3 to size the preview window properly for accurate preview.

## Affected browsers

* Chrome: yes
* Firefox: N/A
* Edge: N/A
* Safari: N/A

## System details

Windows 10:
<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 59.0.3070.0
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3070.0 Safari/537.36

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 45 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

OSX 10.2:
<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Mac OS X
Operating system version: 10.12_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Local storage
Storage quota (approx): 28 gb
Storage usage (approx): 240 kb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 460 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment] 2017-04-21 15:15
Please include your system details as per the guidelines. There is a known bug in Chrome similar to what you describe, but it depends on the DPR, which is included in the platform information.

**Comment by AshleyScirra** [comment] 2017-04-21 16:12
Yep, looks like you have a high-DPI system, so closing as it's probably this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=677381

**Closed by AshleyScirra** 2017-04-21 16:12 UTC

**Comment by pixelmetal** [comment] 2017-04-21 16:23
The Windows 10 details show it's NOT a high-DPI display, only OSX is.

**Comment by AshleyScirra** [comment] 2017-04-21 17:00
I have a Windows 10 system with device pixel ratio 1, and it does not reproduce the problem. So it does seem consistent with the Chrome bug here.

**Comment by pixelmetal** [comment] 2017-04-21 17:24
Did you try launching C3 from desktop and not just in a browser tab? This will help me figure out what may be causing it on my end.

**Comment by AshleyScirra** [comment] 2017-04-21 18:16
Oh right, yes it does also reproduce on my Windows 10 low-dpi system when running from desktop. But the same bug report also mentions "This bug also affect the Chrome App API when creating window (chrome.app.window.create) with innerBounds." That sounds like it also covers this, so I think it's the same issue still.

**Comment by pixelmetal** [comment] 2017-04-21 18:41
Okay, thanks for clarifying.
