### ISSUE TITLE
Broken folder project - failing to save changes after importing sheet animation

### ISSUE THREAD

**Issue by rilem** [Scirra/Construct-3-bugs#4292] opened 2020-10-14 15:40 UTC
## Problem description

I noticed my Mighty Goose project was broken when I tried to open it today. It seems like the latest animation I added was missing from the project images folder. Upon inspecting the git history I noticed the images had never been committed. The animation was working in preview yesterday though. 

I manually placed the missing images in the images folder and the project could be opened again. However, GitHub desktop still could not detect any changes. Very weird. 

I recorded a session so you can see the issue. I've also captured the console window after the error occurs.

https://youtu.be/TnMO1muU_WM

Note: this happens with each sprite sheet. But it doesn't seem to happen when loading individual images as frames.

## Attach a .c3p

Ashley still has access to the Mighty Goose repository, I think it would be best if he took a look.

Troublesome file in question:
![download (66)](https://user-images.githubusercontent.com/1725985/96011324-12722400-0e43-11eb-9163-eb584ad8494a.png)

## Steps to reproduce

-Add new sprite
-Import animation from sprite sheet
-Save project
-Notice no file changes in version control

I tried reproducing it in a blank folder project. This works fine. Maybe this bug has something to do with the recent changes to folder projects?

## Observed result

Project does not save sprite images to the images folder and can not be opened next time opening the project.

## Expected result

Changes made are saved and project can be opened.

## More details

Running Chrome Version 86.0.4240.75 (Official Build) (64-bit)
Happened since the recent 220 beta updates (I would have preferred to stay on stable but Chrome decided to auto-update)

**Comment by AshleyScirra** [comment] 2020-10-14 15:49
Can you reproduce this in a new project? As ever it's extremely difficult to work with full projects when diagnosing problems.

It sounds like it might have been a git mixup as well. Having steps to reproduce would rule that out.

**Comment by rilem** [comment] 2020-10-14 15:59
Actually, I was able to reproduce it in a new project.

On the latest beta

Steps:

1. open Construct
2. create new project
3. new sprite -> import sheet animation
4. save as folder project
5. close project
6. open project
7. new sprite -> import sheet animation
8. save
9. notice the new images aren't saved in image folder
10. close project
11. open project -> fails.

**Comment by rilem** [comment] 2020-10-16 10:43
Any update on this issue? Curious for the reason why this is happening.

**Comment by cb130felix** [comment] 2020-10-16 12:46
+1 on this
This problem is something that is really affecting my team workflow since it limits a lot what we can do in our project. Also curious if we should expect a r200-3 before tuesday

**Comment by cb130felix** [comment] 2020-10-16 12:50
+1 on this
This problem is something that is really affecting my team workflow since it limits a lot what we can do in our project.We can't go back to stable because C3 doesn't have the "folder project" options there anymore and we need it for source control, wich means we're stuck with using a broken beta release 😬

Also curious if we should/could expect a r200-3 before tuesday with a fix. Thanks!

**Comment by AshleyScirra** [comment] 2020-10-16 13:13
Sorry, we won't be making a release before Tuesday at this point.

**Comment by AshleyScirra** [comment] 2020-10-16 15:37
This appears to be a regression caused by the fix to #4275. It should be fixed for the next release, currently scheduled for Tuesday.

**Comment by AshleyScirra** [comment] 2020-10-16 15:37
Actually will leave open with fixed tag since we already had two reports of this.

**Comment by AshleyScirra** [comment] 2020-10-20 14:30
This should be fixed in r221, can you confirm it's working as expected there?

**Comment by rilem** [comment] 2020-10-20 16:34
Working as expected! Saving seems to be significantly slower than before though.

**Comment by cb130felix** [comment] 2020-10-20 16:41
+1 on what @rilem said. It actually took C3 around 3~4 minutes to save a big project.

**Comment by AshleyScirra** [comment] 2020-10-20 17:13
Thanks for confirming, closing. I think Chrome virus scans every file it writes to disk, so a full save-as may take a while. A normal save should be fast though since it only writes changed files to disk.

**Closed by AshleyScirra** 2020-10-20 17:13 UTC
