### ISSUE TITLE
[r34] Unable to open Cloud projects on Google Drive (possibly other services too - untested)

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#431] opened 2017-06-02 22:27 UTC
## Problem description

Construct 3 is unable to refresh the file list for Google Drive. 

Notes: I normally have to hit refresh many times to get the list to refresh, but now it seems to fail 100% of the time. (Others have reported the same thing on the forums today.) I've had no trouble accessing Google Drive on the same machine using both the web interface or the PC desktop app. I have not attempted to get Dropbox or OneDrive to work because I don't normally use those services.

## Attach a .c3p

(This bug doesn't require a .c3p.)

## Steps to reproduce

1. Open Construct 3.
2. On the start page, click the "Cloud" button to open the Cloud file browser.
3. Select Google Drive as the service.
4. Wait for "Getting Files From Google Drive" message to go away.

## Observed result

"Failed to refresh file list" message is always shown.

## Expected result

The Google Drive file list should be refreshed.

## Affected browsers

* Chrome: yes

## System details

Platform information below.

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r34

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 43 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Hendrin** [comment] 2017-06-03 00:17
Console log: 

Object {message: "Cannot read property 'length' of undefined", stack: "TypeError: Cannot read property 'length' of undefi…/r34/cloud/sandbox.js:1:26630)↵    at <anonymous>"}message: "Cannot read property 'length' of undefined"stack: "TypeError: Cannot read property 'length' of undefined↵    at a.then.then (https://editor.construct.net/r34/cloud/sandbox.js:1:26630)↵    at <anonymous>"__proto__: Object
ǃgL.ǃEMX.then.then.then.catch @ main.js:149

**Comment by Hendrin** [comment] 2017-06-03 00:18
Only effects google drive. Onedrive and dropbox function normally.

**Comment by SupraBagels** [comment] 2017-06-03 00:57
Console log: `main.js:149 
Object {message: "Cannot read property 'length' of undefined", stack: "TypeError: Cannot read property 'length' of undefi…/r34/cloud/sandbox.js:1:26630)↵    at <anonymous>"}
message
:
"Cannot read property 'length' of undefined"
stack
:
"TypeError: Cannot read property 'length' of undefined↵    at a.then.then (https://editor.construct.net/r34/cloud/sandbox.js:1:26630)↵    at <anonymous>"
__proto__
:
Object
ǃgL.ǃEMX.then.then.then.catch	@	main.js:149
`
I get the problem with One Drive and Google Drive, (I dont have a Dropbox account).

**Comment by cmr333** [comment] 2017-06-03 07:09
Same error, this is just a suggestion but Google recently updated their "Google Authentication" for people who use smartphones as a way to access their Google accounts, is it possible that this is what is causing the error?

**Comment by cmr333** [comment] 2017-06-03 07:11
Console Log: `
main.js:149 Object {message: "Cannot read property 'length' of undefined", stack: "TypeError: Cannot read property 'length' of undefi…/r34/cloud/sandbox.js:1:26630)↵    at <anonymous>"}message: "Cannot read property 'length' of undefined"stack: "TypeError: Cannot read property 'length' of undefined↵    at a.then.then (https://editor.construct.net/r34/cloud/sandbox.js:1:26630)↵    at <anonymous>"__proto__: Objectconstructor: function Object()hasOwnProperty: function hasOwnProperty()isPrototypeOf: function isPrototypeOf()propertyIsEnumerable: function propertyIsEnumerable()toLocaleString: function toLocaleString()toString: function toString()valueOf: function valueOf()__defineGetter__: function __defineGetter__()__defineSetter__: function __defineSetter__()__lookupGetter__: function __lookupGetter__()__lookupSetter__: function __lookupSetter__()get __proto__: function __proto__()set __proto__: function __proto__()
ǃgL.ǃEMX.then.then.then.catch @ main.js:149`

**Comment by SupraBagels** [comment] 2017-06-03 18:31
UPDATE:  I created a dropbox account and everything work at the moment.   Google Drive and OneDrive doesn't work

**Comment by triptych** [comment] 2017-06-04 06:38
I'm having the same issue - on both my desktop and laptop:

```
main.js:149 
Object {message: "Cannot read property 'length' of undefined", stack: "TypeError: Cannot read property 'length' of undefi…/r34/cloud/sandbox.js:1:26630)↵    at <anonymous>"}
message
:
"Cannot read property 'length' of undefined"
stack
:
"TypeError: Cannot read property 'length' of undefined↵    at a.then.then (https://editor.construct.net/r34/cloud/sandbox.js:1:26630)↵    at <anonymous>"
__proto__
:
Object
﻿
``` 

OneDrive works, but google does not. Even tried in a new profile with no plugins.
​

**Comment by Scott943** [comment] 2017-06-04 12:13
Can also confirm that every was working fine until the latest Construct 3 update (r34). When I updated, I tried to save but it simply failed.

**Comment by TheRealDannyyy** [comment] 2017-06-04 13:05
Getting the same error using Google Drive. It seems to log me in just fine but it fails to fetch any data.
![console_googleerror](https://cloud.githubusercontent.com/assets/15656049/26761844/312e56c2-4937-11e7-837e-2f0f0217be55.PNG)

**Comment by hinklefoxmail** [comment] 2017-06-04 14:22
Same issue, dropbox worked but Google Drive did not. I am not even getting a message asking for what account it is attempting to access.

<img width="1256" alt="screen shot 2017-06-04 at 3 20 03 pm" src="https://cloud.githubusercontent.com/assets/15206556/26762399/5f66a48e-4939-11e7-8c71-ce8bcd41c292.png">

**Comment by triptych** [comment] 2017-06-04 15:39
I can also report that this is a recent regression. Drive access worked fine right before this update

**Comment by shortercode** [comment] 2017-06-05 10:12
I made some changes to google drive for r34 so best guess is something in there is causing an issue. However, I'm not able to replicate this bug myself. I'll have a look through and see if there's anything that could cause this.

**Comment by cmr333** [comment] 2017-06-05 10:19
> I made some changes to google drive for r34 so best guess is something in there is causing an issue. However, I'm not able to replicate this bug myself. I'll have a look through and see if there's anything that could cause this.

Yes it is, I've just tried logging onto cloud from my laptop (r32) and it worked, then I refreshed into r34 and the cloud loading failed again like my desktop (r34)

**Comment by shortercode** [comment] 2017-06-05 10:32
Have checked around the office and thankfully Ashley was able to replicate with his Google account. It will be fixed in r35.

**Comment by shortercode** [comment] 2017-06-05 10:59
Okay we've tested the fix and r35 should be going out at some point today, so closing this bug now. If anyone experiences this issue on r35 could you please reopen the issue.

**Closed by shortercode** 2017-06-05 10:59 UTC

**Comment by TheRealDannyyy** [comment] 2017-06-05 13:27
It works as intended now, although I still had to click the refresh icon once, before it started loading and displaying my projects.

The loading also took fairly long on my end, I would recommend adding an option to only load certain types of files (e.g. c3p files only).

**Comment by shortercode** [comment] 2017-06-05 13:49
@TheRealDannyyy There is a bug that the first getFiles request after an authentication returns an empty list of files. I'm not 100% sure why, and it's quite difficult to catch. I think it's actually a google drive bug but until I manage to catch an empty response in the network debugger I haven't got much to go on.

As for requesting files, we already use a very specific filter on file types. Currently we request non-trashed c3p, capx and folders. Folders are not exposed to users at the moment as we're still working on the feature.

**Comment by TheRealDannyyy** [comment] 2017-06-05 14:40
@shortercode Could you perhaps report this issue to the "Google Drive Team", so that they can look into this? Assuming that the issue is from their end and not just a minor coding mistake. ;)

**Comment by shortercode** [comment] 2017-06-05 14:54
@TheRealDannyyy I've been trying to debug it since my last message and having finally got a network trace of it I think it's probably an obscure timing issue (so my fault :P). But yeah I would have reported it when I had a replication.

**Comment by shortercode** [comment] 2017-06-07 11:25
@TheRealDannyyy after much searching, I have finally decided that it is an issue with the Google Drive API and I have a network log to prove it! I've filed a bug with them, and created a [tracking bug](https://github.com/Scirra/Construct-3-bugs/issues/458) on here for the issue.
