### ISSUE TITLE
Repost, can't open my project file, with attached project.

### ISSUE THREAD

**Issue by StefanSava** [Scirra/Construct-3-bugs#739] opened 2017-08-24 07:14 UTC
## Problem description

Can't open my project file. 

## Attach a .c3p

[3Pants.zip](https://github.com/Scirra/Construct-3-bugs/files/1248005/3Pants.zip)

## Steps to reproduce

1.Open File

## Observed result

Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project.

## Expected result

Just open project.

## Affected browsers

* Chrome: yes/no

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: name is reserved @ Error: name is reserved at q.l (https://editor.construct.net/r49/main.js:61:142658) at q (https://editor.construct.net/r49/main.js:61:150323) at Function.ǃr.ǃw (https://editor.construct.net/r49/main.js:2:205129) at window.ǃqTd.ǃlm (https://editor.construct.net/r49/main.js:61:404739) at t.ǃgbf.then (https://editor.construct.net/r49/main.js:61:161712) at 
Stack: Error: name is reserved at q.l (https://editor.construct.net/r49/main.js:61:142658) at q (https://editor.construct.net/r49/main.js:61:150323) at Function.ǃr.ǃw (https://editor.construct.net/r49/main.js:2:205129) at window.ǃqTd.ǃlm (https://editor.construct.net/r49/main.js:61:404739) at t.ǃgbf.then (https://editor.construct.net/r49/main.js:61:161712) at 
Construct 3 version: r49
URL: https://editor.construct.net/index.html
Date: Thu Aug 24 2017 10:11:46 GMT+0300 (E. Europe Daylight Time)
Uptime: 12.5 s

Platform information
Browser: Chrome
Browser version: 60.0.3112.101
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36
C3 release: r49

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by XpMonster** [comment] 2017-08-24 17:39
Well the answer probably is "Check it is a valid Construct 3 single-file (.c3p) project."
It should be single object in .c3p format and not .c3proj that you've sent.

**Comment by StefanSava** [comment] 2017-08-25 09:03
it's not that , the file i attached should be renamed from .zip to .c3p

**Comment by AshleyScirra** [comment] 2017-08-25 10:44
Should be fixed for r51. The problem is the project uses an object named 'Sign', which became a system expression in r48. As of r51 it will rename this object to Sign2 when loading the project to ensure it does not collide with the system expression, and this also allows the project to load successfully.

**Closed by AshleyScirra** 2017-08-25 10:44 UTC

**Comment by StefanSava** [comment] 2017-08-25 11:08
Thanks.
