### ISSUE TITLE
Unable to avoid selection of events

### ISSUE THREAD

**Issue by IcticStep** [Scirra/Construct-3-bugs#3572] opened 2020-01-05 19:44 UTC
## Problem description

Unable to avoid selection of events and actions in Event Sheet, when using split screen mode.

## Attach a .c3p

[Google Drive](https://drive.google.com/open?id=1237uoeY-a1NYHB2amaba8LRft6bc593G)

## Steps to reproduce

1. Open Event sheet 1.
2. Open Event sheet 2 in the right part of the screen.
3. Select anything from the Event sheet 2
4. Try to cancel the selection.

## Observed result
Nothing happens.

## Expected result
Expected avoiding of the selection after clickin on the empty space of screen.

## More details

**Affected browsers/platforms:** 
PC(Windows 10): yes
Chrome: yes

**First affected release:** 
Worked in Construct 2 but broke in Construct 3.
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 79.0.3945.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
C3 release: r171.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 28 gb
Storage usage (approx): 214 mb (0.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2020-01-06 11:46
This looks like an old regression originally introduced when #1142 was fixed. It used an incorrect size calculation to avoid detecting the scroll bar which affected this case. It should be fixed in the next beta.

**Closed by AshleyScirra** 2020-01-06 11:46 UTC
