### ISSUE TITLE
Xcode error with mobile advert plugin

### ISSUE THREAD

**Issue by RobinBloood** [Scirra/Construct-3-bugs#2882] opened 2019-04-23 11:31 UTC
Problem with Mobile advert plugin, without this plugin Xcode compilation without error. Even in empty project only with Mobile advert plugin.

## Attach a .c3p
https://drive.google.com/open?id=10Vnndx2DQdI2bakG_cWg53fNpp27oBFf

## Steps to reproduce

1. Export like Xcode project, min version 9+
2. Open in Xcode
3. Try to archive for AppStore

## Observed result

Error:
![56445770-a2dfaf00-6307-11e9-9ddc-cafc3c1093f8](https://user-images.githubusercontent.com/49883392/56577522-dfdfc600-65d3-11e9-9d33-c4c27e2a06c6.jpg)

## Expected result

Build without error

## System details

Platform information
Browser: Chrome
Browser version: 73.0.3683.103
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.2000000476837158
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
C3 release: r142.2 (stable)
Language setting: en-US

**Comment by shortercode** [comment] 2019-04-24 10:52
This would appear to be related to cocoapods, but it's not obvious what the cause of the problem is. I will investigate further.

**Comment by Boulerzzz** [comment] 2019-04-25 19:46
I updated apps on the app store on march 28th w/o any problems.
Last thursday (April 18th) I needed to update a few apps before easter but had to change my plans because I encountered this issue. So something broke the mobile advert on Xcode between those 2 dates.

I'm using C3 runtime and Xcode 10.1. Both legacy and default build system fails (with different errors)

**Comment by Evilobjective** [comment] 2019-04-26 03:51
Having a similar problem - went to update an app tonight that hasn't been touched since late march and I received Xcode error "No such module 'GoogleMobileAds' . The same error was reported/fixed/closed back in November 2017 (https://github.com/Scirra/Construct-3-bugs/issues/985) with @shortercode explaining it was something with the build server. I can file a separate bug report if you prefer but I suspect these are related...

Using C3 runtime Xcode 10.1 - Only tested with the legacy build system.

**Comment by Boulerzzz** [comment] 2019-04-26 04:06
Legacy build system will throw 'No such module 'GoogleMobileAds' '. But if you change to default build system you will see the same error as in the screenshot above. I guess its the same error but the build systems give slightly different error messages.

**Comment by Hodgekins** [comment] 2019-04-26 13:53
I get the same error in Xcode 10.2

When I open a workspace with the MobileAdvert module in Construct, Xcode asks me this question:

<img width="424" alt="Screenshot 2019-04-26 at 14 29 10" src="https://user-images.githubusercontent.com/2507526/56811779-70ffa880-6831-11e9-81ae-a33073faff79.png">

I go into my project build settings and change the Swift Language Version setting to 4.

When I try to build the project I get the same error as Boulerzzz: 

<img width="1138" alt="Screenshot 2019-04-26 at 14 50 24" src="https://user-images.githubusercontent.com/2507526/56812370-a6f15c80-6832-11e9-9801-ab8623625b10.png">

**Comment by shortercode** [comment] 2019-04-26 15:00
I don't think the cocoapod dependencies aren't syncing on the server. I just checked a build and it was missing the "Pods" folder which normally contains those frameworks.

It's possible to manually sync it if you have cocoapods installed, by doing that and increasing the swift language version to 4 I got the project to compile. Again I'm not sure why the swift version is wrong, this may be a cascade issue from the cocoapods failure.

I'm going to take a look at a build a little more closely, see if I can resolve the server issue.

**Comment by shortercode** [comment] 2019-04-26 15:26
Okay we should now have resolved the cocoapods issue, but still defaulting to swift 3 for some reason...

**Comment by Boulerzzz** [comment] 2019-04-26 15:29
@shortercode 
If it defaults to swift 3 we should use Xcode 10.1 and not 10.2 correct?

**Comment by shortercode** [comment] 2019-04-26 15:33
@Boulerzzz You can just change it to swift 4 in the build settings tab, the code is forwards compatible.

Swift 3 is legacy now so we shouldn't be using it, and as far as I'm aware the swift toolchain defaults to 4.x so it's a little puzzling how it's ended up at 3.x. Just looking at the code that deals with the swift interop and trying to decide why it's not working. There's a new version, so I might upgrade it and see if it works as intended.

**Comment by Boulerzzz** [comment] 2019-04-26 15:37
Alright! I'll experiment and google around a bit to see what works best for me!

Thanks for solving the cocoapods issue! :)

**Comment by Hodgekins** [comment] 2019-04-26 15:43
It's bloody working! 

I installed Cocoapods and ran _pod update_ from terminal in the project folder. Now it builds successfully using Swift 4 in Xcode 10.2 and everything works as it should. Thanks for the tips.

**Comment by shortercode** [comment] 2019-04-26 15:53
Haha glad you found your way @Hodgekins ! It's useful to have cocoapods installed if you end up doing anything with xcode projects, as it's the most common dependency tool.

`pod update --repo-update` is probably my most used command... 

I've just done some tweaking on the build server, updated the plugin that configures swift settings for our xcode projects to the latest version. After a test build it looks to be correctly setting the Swift version to 4 now. So with the cocoapods sync issue also being fixed xcode projects should pretty much work out the box again.

**Comment by Evilobjective** [comment] 2019-04-26 18:27
I appreciate the hard work @shortercode ! I'll try it again tonight, but unfortunately that won't be for another 7-8 hours.

**Comment by RobinBloood** [comment] 2019-04-26 18:36
Checked! Everything works for me. Thanks @shortercode !

**Comment by Boulerzzz** [comment] 2019-04-27 08:59
@shortercode
Just got some time to build and upload to the app store. It seems everything work just fine! Thanks!

**Comment by shortercode** [comment] 2019-04-29 10:01
Awesome, thanks for checking guys! Going to close this issue as it seems to be resolved. Let me know if anything else goes awry.

**Closed by shortercode** 2019-04-29 10:01 UTC
Labels: iOS
