### ISSUE TITLE
Tilemap problems

### ISSUE THREAD

**Issue by ibiz3091** [Scirra/Construct-3-bugs#2286] opened 2018-11-09 06:23 UTC
## Problem description

PC
![2018-11-09_09-09-43](https://user-images.githubusercontent.com/44605893/48246238-b35a3800-e3ff-11e8-82df-db3591c67fc3.png)

Mobile
![screenshot_20181109-091023_chrome](https://user-images.githubusercontent.com/44605893/48246273-e1d81300-e3ff-11e8-85de-b8e5b3e41f2b.jpg)

On mobile devices, there is also a slight blurring of sprites. Sprites are taken from the C2 project unchanged, when comparing two exports (Canvas+ Cocoon) and (C3 webview+) . In the Construct 3 export, the image on mobile devices is a bit blurry.

## Attach a .c3p
[Test2.zip](https://github.com/Scirra/Construct-3-bugs/files/2564793/Test2.zip)

## Steps to reproduce

1.
2.
3.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2018-11-09 10:41
The images look very similar. Can you be clearer about exactly what the problem is?

**Comment by ibiz3091** [comment] 2018-11-09 10:45
![screenshot_20181109-091023_chrome 2](https://user-images.githubusercontent.com/44605893/48258264-bcf69680-e425-11e8-8f3f-8264946079ee.jpg)

**Comment by ibiz3091** [comment] 2018-11-09 10:47
@AshleyScirra 
![screenshot_20181109-091023_chrome 2](https://user-images.githubusercontent.com/44605893/48258383-06df7c80-e426-11e8-9166-3803bb71023c.jpg)

**Comment by AshleyScirra** [comment] 2018-11-09 11:42
Please answer all questions to ensure we can help you:

- Also, what exactly is the problem with the sprites, can you demonstrate again there what the issue is?
- Does this reproduce in just the C3 runtime or both runtimes?

**Comment by AshleyScirra** [comment] 2018-11-09 13:47
Can't reproduce on a Pixel 3. We need information about the specific devices to be able to help. Closing, please always follow the bug report guidelines and provide all the requested information to ensure we can help.

**Closed by AshleyScirra** 2018-11-09 13:47 UTC
Labels: need info

**Comment by SnipG** [comment] 2018-11-09 16:13
Official tilemap example uses: integer scale,point sampling and pixel rounding. I haven't played around with tilemaps, but maybe try just integer scale.

**Comment by ibiz3091** [comment] 2018-11-09 16:31
@ @SnipG Have you watched C3p? The problem is on my mobile. Iphone 6 and Samsung A5 (2017)

**Comment by ibiz3091** [comment] 2018-11-09 18:03
@AshleyScirra 
I found out what the problem is with tilemaps on mobile. When you add a spritefont object to your project, you experience this issue with tilemap. If you remove the spritefont object from the project, the problem goes away.

**Comment by ibiz3091** [comment] 2018-11-09 18:06
@AshleyScirra Why do I have to solve problems for you guys? I gave you C3P. In which there was this problem... I spent the whole day looking for a pattern to this problem...

**Comment by SnipG** [comment] 2018-11-09 18:40
I looked into it, its  device pixel ratio is something 2.20/2.25? If you dublicate tile 7 into new spot 21(not at edge anymore). It will fix it. Its some sort of spritesheeting rounding error.

**Comment by ibiz3091** [comment] 2018-11-10 07:32
Good afternoon, I can't understand what the problem is... In more detail the problem is visible if to open construct on mobile. After you add this problem to the project (spritefont, particles, sprite)... If you remove (spritefont, particle, sprite) the problem goes away... I made a video for you.
@SnipG @AshleyScirra 
https://yadi.sk/d/m4aApVA1UoNmPg
