### ISSUE TITLE
9-patch borders have gone weird recently in desktop build

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#2290] opened 2018-11-10 01:25 UTC
## Problem description

Not sure which release this started happening, but I just noticed it in r124, because its a fairly subtle bug.

The borders don't seem to always be working correctly for me at the moment, and I have no idea why!

It use to work fine, I haven't touched this 9-patch object for a long time but now it's just started giving this visual glitch in preview.

Take a look at this image, see how the border is different in preview?

![image](https://user-images.githubusercontent.com/5744908/48295706-bc700580-e4e2-11e8-8819-82968f785170.png)

## Attach a .c3p

[9patch.zip](https://github.com/Scirra/Construct-3-bugs/files/2567977/9patch.zip)

## Steps to reproduce

1. Preview

## Observed result

Border is different in preview

## Expected result

Stay the same editor

## Affected browsers

Desktop build 

Chrome and Firefox seem fine

## System details

Multiple computers

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.33.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@8920e690dd011895672947112477d10d5c8afb09) NWjs/0.33.3 (like Chrome/69.0.3497.100)
C3 release: r124 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 147 gb
Storage usage (approx): 758 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2018-11-12 12:19
I can reproduce, but I think this is related to a Chrome bug we worked around recently - it no longer reproduces with the latest NW.js version (Chromium 70), whereas the latest desktop build is still on Chromium 69. So I think it will be fixed by the next update. That's a little delayed due to some server-side changes we're making but it should be along soon.

**Comment by AshleyScirra** [comment] 2018-12-05 18:30
A new desktop build based on Chrome 71 is now available. Can you check the issue is resolved there?

**Comment by munfraid** [comment] 2018-12-05 22:08
Had the same problem. Just tried a new build and can confirm it's working like charme on all three OS! 
Resolved, thanks

**Comment by alastajj** [comment] 2018-12-06 01:46
@AshleyScirra  I'm not sure, I can't open my project in this version. When I click the "cloud" button it says "failed to refresh list" and it won't open from recent projects, I use google drive.

**Comment by alastajj** [comment] 2018-12-06 12:48
Pretty sure it's all good now, thanks!

**Comment by AshleyScirra** [comment] 2018-12-06 13:32
Thanks for confirming!

**Closed by AshleyScirra** 2018-12-06 13:32 UTC
Labels: desktop, need info
