### ISSUE TITLE
Drawing canvas has shaky paste when rotated

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4962] opened 2021-07-17 16:08 UTC
## Problem description
Canvas pastes onto another canvas differently then sprite does.

![Middle](https://user-images.githubusercontent.com/28864889/126035800-f6c5e0a6-0a39-48e0-bd02-1e6f426959f4.jpg)

They should produce similar smoothness, but don't
![Middle2](https://user-images.githubusercontent.com/28864889/126043128-ad63a51b-fd6e-4e6a-b484-e785d526e0ca.jpg)

## Attach a .c3p
[Hey Y'all.zip](https://github.com/Scirra/Construct-3-bugs/files/6834645/Hey.Y.all.zip)

## Steps to reproduce

1.Preview project, drag two draggable object side by side
2.See one object does not paste smoothly when rotated
3.

## Observed result
Drawing canvas does not rotate correctly. Is shaky

## Expected result
Drawing canvas to rotate smooth

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 91.0.4472.124
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
C3 release: r256 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 1.3 gb (1.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2021-07-19 11:28
It's not clear to me that this is a bug. Perhaps the sprite is just unevenly drawn and so produces an uneven result when pasted while rotating on to a Drawing Canvas. Can you make a clearer project?

**Comment by SnipG** [comment] 2021-07-19 12:45
I have to test more options, but  upload a cleared project here:
[Case_4963_CanvasGlitz.zip](https://github.com/Scirra/Construct-3-bugs/files/6840937/Case_4963_CanvasGlitz.zip)

**Comment by SnipG** [comment] 2021-07-19 17:53
Correct example: [Case_4963_CanvasGlitz_OriginPoint.zip](https://github.com/Scirra/Construct-3-bugs/files/6842950/Case_4963_CanvasGlitz_OriginPoint.zip)

Issue seems to be: if drawingCanvas originpoint is top-left(default), then it's correct. Any other originpoint pasts with glitz

**Comment by AshleyScirra** [comment] 2021-08-06 14:43
In the project `Case_4963_CanvasGlitz_OriginPoint.zip`, I'm still not clear if there's a bug or what you're expecting it to do. The two rotating patterns on the left look almost identical. The top-left pattern pastes a rotating sprite directly to a DrawingCanvas, the bottom-left pattern pastes a sprite to a DrawingCanvas then pastes that rotating DrawingCanvas to another DrawingCanvas, and they produce a virtually identical result. The only difference is a slight quality difference, which I'm pretty sure is just the difference between texture sampling: the top-left one looks better because it's directly pasting a rotated sprite, so it texture-samples the rotated texture directly, whereas the bottom-left one looks a bit worse because it's first pasting a sprite to a DrawingCanvas (which will texture sample the Sprite texture with no rotation), then takes the result and rotates that, which will texture sample a pre-rendered surface rather than the original texture.

So is the only issue being reported the slight quality difference? If so then I don't think this is a bug, it's just what happens when you render to an intermediate surface first.

**Comment by SnipG** [comment] 2021-08-06 15:00
No, the issue is: Why different originpoint results different quality! Does incorrect originpoint handling is source of it?


Pasting canvas with originpoint middle:
![InCorrect](https://user-images.githubusercontent.com/28864889/128529884-b230c9a0-e1f0-41b7-8440-a3f08add6466.jpg)

Changing incorrect quality canvas originpoint to top-left.
![Correct](https://user-images.githubusercontent.com/28864889/128530128-44d092ba-27b1-4956-98d7-3e6acc678cbf.jpg)

**Comment by AshleyScirra** [comment] 2021-08-06 15:21
I'm still pretty sure this is some kind of difference with texture sampling. The Drawing Canvas rendering code doesn't care where the origin is - everything it does is based on the bounding box or bounding quad, which makes the location of the origin irrelevant (for two comparably located objects).

In general pasting to a surface, rotating and then pasting the surface itself is not guaranteed to produce the same result as pasting the original image rotated, as this project demonstrates. When pasting the original image, the texture sampler has access to the full-resolution original image, and can use the rotation to adjust how the texture is sampled. When pasting a pre-rendered surface, it can only sample the pre-rendered image, which was sampled at a different rotation. So the result will be inferior to pasting the original. I'm not sure why it looks better when the origin is in the top-left; I would guess this is just a different setup that by good fortune of the choice of the rotation parameters produces a good result even when using an inferior quality approach to pasting. Fully explaining the difference would probably mean delving in to the minutiae of texture sampling mathematics, which I don't think is worth studying here, but I'm pretty sure explains the difference, hence closing as not a bug.

**Closed by AshleyScirra** 2021-08-06 15:21 UTC
Labels: not a bug
