### ISSUE TITLE
Deleting sound folder can corrupt c3p.

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#4580] opened 2021-02-18 09:36 UTC
## Problem description

Deleting a folder containing sounds in use will corrupt the c3p. This doesn´t happen if you delete the sounds directly, only if you delete the folder that contains the sounds.

## Attach a .c3p

[broken.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/6001694/broken.c3p.zip)

## Steps to reproduce

1. Open file
2. Delete the "New folder" in the sounds folder
3. Save file (Local file, don´t know if that´s relevant)
4. Close and attempt to reopen

## Observed result

Project will not open due to missing files.

## Expected result

Project to open normally.

## More details
The actions that used the soundfiles will be kept but they will be visually removed in the editor. I manually edited those actions out of my project to un-corrupt it.

**Affected browsers/platforms:** Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 88.0.4324.182
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
C3 release: r236 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 1011 mb (0.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2021-02-18 17:21
Thanks, looks like an important issue. Should be fixed in the next beta.

**Closed by AshleyScirra** 2021-02-18 17:21 UTC

**Comment by Wackytoaster** [comment] 2021-02-20 09:32
@AshleyScirra
Possibly important update: This issue also appears with layouts if you delete a subfolder containing layouts. It´s possible other folders are affected aswell.

**Comment by AshleyScirra** [comment] 2021-02-20 11:22
Ah, well spotted, I could reproduce this with layouts and timelines too - both should also be fixed for the next release. Other items seemed to be working OK already.

The problem is if there were references to project items in the event sheet, and you deleted the folder rather than the item itself, the events would be left behind. That's why saving and loading fails to open the project - it saves references to items that were deleted. So any time you see something deleted being left behind somewhere in the editor, it's a serious bug that needs to be fixed - please do let me know if you spot any more after the next beta.
