### ISSUE TITLE
R141 - C3 crashes when create or open JSON file

### ISSUE THREAD

**Issue by el3um4s** [Scirra/Construct-3-bugs#2714] opened 2019-03-11 16:16 UTC
## Problem description

C3 crashes when create or open JSON file

## Steps to reproduce

Create a JSON file

![Annotazione 2019-03-11 173130](https://user-images.githubusercontent.com/23579630/54140293-9708ef00-4423-11e9-96b5-d798be77074c.jpg)

C3 chrashes

## Expected result

Create a JSON file (or open a JSON file)

## More details

**Affected browsers/platforms:** - Chrome, Windows

**First affected release:** first started happening in r141

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r141/main.js, line 2, col 151636
Message: Uncaught TypeError: Cannot read property 'ǃrMG' of undefined
Stack: TypeError: Cannot read property 'ǃrMG' of undefined at ǃl (https://editor.construct.net/r141/main.js:2:271748) at window.ǃJHu.ǃJIz (https://editor.construct.net/r141/components/editors/textEditor/textEditor.js:1:6186) at new window.ǃJHu (https://editor.construct.net/r141/components/editors/textEditor/textEditor.js:1:3142) at Function.ǃr.ǃX (https://editor.construct.net/r141/main.js:2:151615) at window.ǃJHS.ǃsu (https://editor.construct.net/r141/components/editors/textEditor/textEditor.js:1:955) at d (https://editor.construct.net/r141/components/bars/projectBar/projectBar.js:1:34873) at e.ǃrU (https://editor.construct.net/r141/components/bars/projectBar/projectBar.js:1:37944)
Construct 3 version: r141
URL: https://editor.construct.net/r141/
Date: Mon Mar 11 2019 17:15:12 GMT+0100 (Ora standard dell’Europa centrale)
Uptime: 13.8 s

Platform information
Browser: Chrome
Browser version: 72.0.3626.121
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
C3 release: r141 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by shortercode** [comment] 2019-03-11 16:37
I believe this is a duplicate of #2713, which should be fixed in the next release.

**Comment by el3um4s** [comment] 2019-03-11 16:48
@shortercode Thank you

**Comment by DiegoScirra** [comment] 2019-03-11 17:11
Yeah, this is fixed already.

**Comment by AshleyScirra** [comment] 2019-03-12 17:23
Should now be fixed in r141.2.

**Closed by AshleyScirra** 2019-03-12 17:23 UTC
