### ISSUE TITLE
DrawingCanvas exhibits artifacts while scaling the game resolution down.

### ISSUE THREAD

**Issue by whistlegraph** [Scirra/Construct-3-bugs#4884] opened 2021-06-11 00:53 UTC
Hi, my game makes heavy use of the DrawingCanvas object. I've been trying to make the drawing consistent when scaling the game window but when the game window is very small I notice two major issues:

The "On resolution changed" event fires every single frame after a change (you can see this when scaling the window down and up in my example project.)

The DrawingCanvas clears automatically after scaling to any resolution below the project resolution after trying to draw. I realize this is documented behavior but the "resolution" of my canvas does not actually change when this happens and keeps reporting the same resolution. I'm just not sure how to mitigate it because the event fires so inconsistently with a project that has Fullscreen Quality set to Low.

Drawing any object using "Paste object" on the DrawingCanvas when the display resolution is lower than the project resolution causes scaling artifacts when drawing that object.

I realize the effects compositor is complex and that this bug may point to other similar bugs that I've filed in the past. :(

At the very least I wish I could set a "minimum" scaled resolution though so that the players of my game don't see these artifacts and don't lose their pictures if they resize the window. Anyway - I hope this project example and the screenshot helps!

Note: I feel like the best solution to this problem for small resolution pixel art projects like mine would be for the engine to scale the game window with CSS after rendering at the project resolution settings. The reason I set up my project like this was because I assumed that using a fixed resolution for my game would prevent issues like this and make it easier to design.

## Attach a .c3p

[DrawingCanvas.zip](https://github.com/Scirra/Construct-3-bugs/files/6635050/DrawingCanvas.zip)

## Steps to reproduce

1. Open example project.
2. Make the width of the display window very small.
3. Click a few times to draw the smiley face.
4. Scale the window up to see the artifacts.
5. Have the JavaScript console open to observe the repeated "On resolution changed" event.

## More details

![Capture](https://user-images.githubusercontent.com/3620017/121614926-a1f0c680-ca14-11eb-9aa9-a55747ba2f49.PNG)

**Affected browsers/platforms:** All

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 91.0.4472.101
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36
C3 release: r251 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 566 gb
Storage usage (approx): 137 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6677)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2021-06-15 11:08
This appears to be a duplicate of #4008. See [this comment on that issue](https://github.com/Scirra/Construct-3-bugs/issues/4008#issuecomment-657570881).

With low quality fullscreen mode, the draw surface is actually the minimum of the window size or the draw size. This is to avoid wastefully rendering at a higher resolution than will be displayed. Therefore it is expected that resizing the window smaller in low quality fullscreen mode will change the render resolution, which in turn changes the Drawing Canvas resolution.

**Closed by AshleyScirra** 2021-06-15 11:08 UTC
Labels: duplicate
