### ISSUE TITLE
Expression editor issues

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#5161] opened 2021-10-27 11:38 UTC
## Problem description

There are two old problems with the expression editor which are probably related.

## Steps to reproduce

Issue 1:
Type a simple expression, for example _LayoutName_
Then move cursor to the start of the line and start typing _toke_
The editor suggest "tokenat" in the dropdown list, this is what we want, so press Enter or double-click to accept it.
_tokenat_ appears, but it erases _LayoutName_

![image](https://user-images.githubusercontent.com/36763350/139055999-a115e44a-45dd-4aaa-9d21-c6b118ced7f4.png)

Issue 2:
Type the same _LayoutName_ expression 
Move cursor to the start and start typing _toke_
Then press backspace a few times to delete "toke" part. 
What you have left if the original _LayoutName_ expression, but the dropdown list is still there.
If you press Enter now, you will end up with _tokenatLayoutName_
![image](https://user-images.githubusercontent.com/36763350/139056524-428df0f8-e0bd-4ad2-89b0-b5b7ebbfaf16.png)

## Expected result

The list with auto-suggestions should not erase the existing text or restore deleted characters.. 
These small issues are making the job of editing long expressions in C3 quite difficult. Imagine if instead of LayoutName you have a very long variable or object name and you have to retype it because you accidentally pressed Enter at the wrong time.

I checked the expression editor in C2 and it doesn't have these problems.

## More details

**Affected browsers/platforms:** All

**First affected release:** probably since r50 or even earlier.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 95.0.4638.54
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
C3 release: r268 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 127 gb
Storage usage (approx): 444 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8681)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_draw_instanced_base_vertex_base_instance
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_multi_draw_instanced_base_vertex_base_instance
WEBGL_video_texture
WEBGL_webcodecs_video_frame
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment] 2021-11-04 16:54
The first part is actually by design and dates back to issue #553 reported in 2017 where someone actually wanted it to work like this. It seems like a reasonable use case since it makes it easier to edit variables between alternatives, such as `Ability_07_Cooldown` -> `Ability_08_Cooldown` in the original example; if it didn't replace the remainder you'd get results like `Ability_08_Cooldown_Cooldown`. I think an argument can be made both ways, but we've had it working like this since 2017 and it was an early report, so I'd rather not change it. You can work around it by adding a space between what you're trying to type and the existing name, e.g. `toke LayoutName`, and then it will only autocomplete the first part before the space. I sometimes do something like this myself in various coding IDEs.

The second part I think is a bug and it ought to hide autocomplete in that case; that should be fixed for the next beta.

**Closed as completed by AshleyScirra** 2021-11-04 16:54 UTC

**Comment by dop2000** [comment] 2021-11-05 00:31
@AshleyScirra  Thanks for fixing the second part!

As for the first issue, I'm sorry, but this is a bad design.  I agree with the person who logged that old issue - if I need to change Ability_07_Cooldown to Ability_08_Cooldown, the autocomplete list should not appear at all. 
Even if it does open, it should work like this:
1. If the selected item in the list is _Ability_08_Cooldown_ and the expression under the cursor is also _Ability_08_Cooldown_, when I press Enter, the expression doesn't change.
2. If the selected item in the list is _Ability_08_Cooldown_ and the expression at the cursor is _tokenat()_, when I press Enter, _Ability_08_Cooldown_ should be added at the cursor position, it should not replace _tokenat_.

Expressions are very often modular. First you type tokenat(), then you wrap it with random(tokenat()), then Functions.getValue(random(tokenat()) and so on. And at each step there is a risk of accidentally erasing the previous expression if you forget to put an extra space.. This is quite annoying and I haven't seen any other IDEs doing this.

**Comment by AshleyScirra** [comment] 2021-11-05 15:49
In VS Code, if you start editing half way through an identifier, it doesn't attempt to show any autocomplete at all. I think Construct's approach is useful for changing between alternatives, as in the older issue. You can also hit escape and close the autocomplete and type in manually without autocomplete or any replacement, which matches what VS Code does by default.

I think there is some degree of subjectivity here. I suspect some people will prefer it as it is, but others would want it to work differently. This means I don't think it counts as a bug report - it's a design issue and so changes ought to be tracked as a feature request.

**Comment by AshleyScirra** [comment] 2021-11-05 15:59
One more thing: there's another autocomplete feature where the way it autocompletes depends on the character typed. Suppose you are editing an expression with | representing the caret. If you start with `|LayoutAngle` and type `ab`, you get `ab|LayoutAngle` and it's suggesting to autocomplete `abs`. Then there are two ways to autocomplete:

1. Hit enter: the entire identifier is replaced with the autocomplete suggestion, so you get `abs|`. This lets you quickly rename things.
2. Type `(` with autocomplete showing. As this is not a valid name character, this fills in autocomplete and then adds the typed character. So you end up with `abs(|LayoutAngle`.

I think if you get in to the habit of using option 2, then you can conveniently wrap expressions like you want.

**Comment by dop2000** [comment] 2021-11-06 03:28
> You can also hit escape and close the autocomplete
This is too dangerous, as Esc can close the dialog and all changes will be lost.

> Type ( with autocomplete showing. As this is not a valid name character, this fills in autocomplete and then adds the typed character

Thanks! I knew about "(", but it seems like typing any other character works too. 
Only pressing Enter erases the existing expression. I need to re-train myself to press Space instead..
