### ISSUE TITLE
export to app error

### ISSUE THREAD

**Issue by tkuet0219** [Scirra/Construct-3-bugs#3546] opened 2019-12-13 18:53 UTC
Error report information
Type: unhandled rejection
Reason: Error: expected string @ TypeError: expected string at Function.ǃp.ǃZb (https://editor.construct.net/r171-3/main.js:2:92312) at ǃp.ǃYz.ǃef.ǃYui.ǃKN (https://editor.construct.net/r171-3/main.js:210:2352) at ǃp.ǃYz.ǃYI.ǃYMi.ǃYM$ (https://editor.construct.net/r171-3/main.js:114:4811) at ǃp.ǃYz.ǃYI.ǃYMi.ǃYMm (https://editor.construct.net/r171-3/main.js:114:3637)
Stack: TypeError: expected string at Function.ǃp.ǃZb (https://editor.construct.net/r171-3/main.js:2:92312) at ǃp.ǃYz.ǃef.ǃYui.ǃKN (https://editor.construct.net/r171-3/main.js:210:2352) at ǃp.ǃYz.ǃYI.ǃYMi.ǃYM$ (https://editor.construct.net/r171-3/main.js:114:4811) at ǃp.ǃYz.ǃYI.ǃYMi.ǃYMm (https://editor.construct.net/r171-3/main.js:114:3637)
Construct 3 version: r171.3
URL: https://editor.construct.net/
Date: Sat Dec 14 2019 02:48:07 GMT+0800 (台北標準時間)
Uptime: 866.9 s

Platform information
Browser: Chrome
Browser version: 78.0.3904.108
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
C3 release: r171.3 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment] 2019-12-16 12:56
I'm afraid reports like this are generally not useful: we need all the requested information to be able to help, so closing. Also note that the crash report indicates r171.3 and the latest version is r179; we may well have already fixed the problem, which is why the bug report guidelines indicate to only test the latest release.

**Closed by AshleyScirra** 2019-12-16 12:56 UTC
Labels: ignored guidelines

**Comment by shortercode** [comment] 2019-12-16 14:13
As a note for @tkuet0219 we were not able to reproduce the issues locally, but a probably fix was added in r172. If you can replicate the issue in the latest beta, then we would be interested in looking into it. However, we would need a full report including what settings you used for export and a project that reproduces the issue.
