### ISSUE TITLE
Image editor: selection lost by clicking another tool

### ISSUE THREAD

**Issue by sebastien-c3** [Scirra/Construct-3-bugs#218] opened 2017-05-16 14:39 UTC
## Problem description

In image editor, selection with rectangle select tool is lost when another tool is selected.

## Steps to reproduce

1. Open image editor
2. Click rectangle select
3. Trace a selection
4. Change tool

## Affected browsers

* Chrome: yes

**Comment by sebastien-c3** [comment] 2017-05-16 14:53
PS: Idem when clicking an option.

**Comment by DiegoScirra** [comment] 2017-05-16 14:54
That is the intended behavior. It works in the same way as C2, it makes sense too.

Where you expecting for the selection to remain, and then be able to draw, with the selection rectangle acting as a mask?

**Comment by sebastien-c3** [comment] 2017-05-17 11:13
Sorry, you are right and finally, it's not a bug.
I forgot it was the same on C2 and I confused with classic image editors.
I hope this suggests future improvements "à la" Aseprite or other in C3.
That said, it would still be cool to not redo a selection after any manipulation.

**Comment by DiegoScirra** [comment] 2017-05-17 11:56
Closing this.

Will consider the suggestion for future improvements.

**Closed by DiegoScirra** 2017-05-17 11:56 UTC
