### ISSUE TITLE
Right click may crash Construct 3

### ISSUE THREAD

**Issue by rraffo** [Scirra/Construct-3-bugs#5537] opened 2022-03-20 16:41 UTC
## Problem description
Right-click on properties menu will crash Construct

## Attach a .c3p

[Right click crash.zip](https://github.com/Scirra/Construct-3-bugs/files/8311649/Right.click.crash.zip)

## Steps to reproduce

1. add a sprite to the layout
2. while sprite is selected, click "Edit instance variable" (ignore the opened window)
3. **right-click** the "instance variable" main menu in the property frame on the left.
4. Construct Crash
![x4CGXMrNyd](https://user-images.githubusercontent.com/58107632/159172910-05228abf-bb9a-4734-b9f1-64397ef021e8.png)

## Observed result

Construct crash

## Expected result

nothing.

## More details

Affected browsers:
Chrome Version 99.0.4844.74 (Official Build) (64-bit) for Windows 10
Fireworks does not cause the crash

Construct 3 R286

## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r286/components/bars/propertiesBar/propertiesBar.js, line 88, col 306
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'Qu')
Stack: TypeError: Cannot read properties of undefined (reading 'Qu') at Tcb (https://editor.construct.net/r286/components/bars/propertiesBar/propertiesBar.js:88:306) at d.ge (https://editor.construct.net/r286/components/bars/propertiesBar/propertiesBar.js:107:62) at Array. (https://editor.construct.net/r286/components/bars/propertiesBar/propertiesBar.js:94:124) at CCG.eh.g.J.kra.dispatchEvent (https://editor.construct.net/r286/main.js:1054:42) at CCG.eh.g.J.kra.pz (https://editor.construct.net/r286/main.js:1392:84) at Eq.g.J.UY.ge (https://editor.construct.net/r286/main.js:1314:9) at HTMLElement.ne (https://editor.construct.net/r286/main.js:1313:285)
Construct 3 version: r286
URL: https://editor.construct.net/r286/
Date: Sun Mar 20 2022 17:23:10 GMT+0100 (Central European Standard Time)
Uptime: 38.5 s

Platform information
Browser: Chrome
Browser version: 99.0.4844.74
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36
C3 release: r286 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.9416)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment] 2022-03-20 18:47
Duplicate of #5532. Fixed in the next beta.

**Closed by DiegoScirra** 2022-03-20 18:47 UTC
Labels: duplicate
