### ISSUE TITLE
Variables of objects created using a family as the object to create return no value

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#2353] opened 2018-11-21 06:15 UTC
## Problem description

Objects spawned using a family instead of a specific object type at creation are partly broken - their variables return nothing, even though they show up properly in the debugger. On the other hand, objects spawned through design-time placement, or spawned by specifying the exact object type are still working fine.

## Attach a .c3p

[FamilySpawnBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2602810/FamilySpawnBug.zip)

## Steps to reproduce

1. Create a sprite and put it in a family.
2. Add a number or string variable to the family and give it any value.
3. Add a new event with an "On start of layout" condition followed by a System: Create Object action, and specify the family as the object to create.
4. Add a way to output text to the project, like a text object or the browser plugin for logging.
5. Add an On Created event for the family, and output the family's variable to the log or the text box in that event.

## Observed result

The output is empty.

## Expected result

The value of the family's variable should be valid.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.102
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
C3 release: r126 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 80 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by tunepunk** [comment] 2018-11-21 10:05
Adding a behaviour (like sine) to a family, then creating object from that family. the new created object does not move using the sine behaviour as well. Family effects for family objects created does not work either.

**Comment by tunepunk** [comment] 2018-11-21 10:11
Seems like no Family properties at all work. Setting properties for that family, angle to 45, and opacity to 50 for that family. When created those properties does not apply either.

**Comment by AshleyScirra** [comment] 2018-11-22 10:53
Is this specific to the C3 runtime? Is it a regression? If so which release did this first occur in? These are all essential details to include with bug reports.

**Comment by AshleyScirra** [comment] 2018-11-22 11:12
It looks like a C3-runtime specific issue introduced in r125 for the fix to create instances even if they don't exist in any layout. Should be fixed for the next release.

**Closed by AshleyScirra** 2018-11-22 11:12 UTC

**Comment by Scoremonger** [comment] 2018-11-22 19:18
> Is this specific to the C3 runtime? Is it a regression? If so which release did this first occur in? These are all essential details to include with bug reports.

Sorry this bug report was inadequate, but honestly if you require every bug to also contain regression testing on both runtimes until the offending build/runtime is found, I think you're asking to much of us, your unpaid QA team. I want to help, and obviously your time is valuable, but so is mine. But anyway, in the future, in the case of major bugs like these family spawning ones, I'll see if I can carve out the time to get that additional info for you. But I will still err on the side of submitting a bug with too little information than no bug at all, because at least that way you're aware of the problem.

Regarding the runtime, perhaps you can include the project's current runtime in the "Platform information" copy/paste so users don't have to remember to include it.

**Comment by AshleyScirra** [comment] 2018-11-23 10:40
We deal with thousands of bug reports and as a small team it directly takes away from time spent writing new features. Writing a comprehensive bug report helps save the team time which means we can get on to addressing other things like feature requests more quickly - and we have hundreds of those too.
