### ISSUE TITLE
Google Play Services - Sign In Error

### ISSUE THREAD

**Issue by jagoman85** [Scirra/Construct-3-bugs#1282] opened 2018-02-12 12:50 UTC
## Problem description

The Google auto-sign-in popup doesn't show when including the Google Play Services Plugin and Leaderboard action. A strange non-native pop up appears, but user can still not sign in.
I've followed the Construct Manual, but still not able to resolve.

## Attach a .c3p

[Game.zip](https://github.com/Scirra/Construct-3-bugs/files/1716291/Game.zip)

## Steps to reproduce

1. Add app on Android Play Store Game Services
2. Add in Client ID and Client Secret in the GooglePlay Add-on
3. (Optional) Add Leaderboard ID into the game to load the leaderboard
4. Export the game as an APK, and upload to Play store
5. Test to see if auto sign-in prompt appears

## Observed result

A strange (not conventional / non-native) window pops up asking to sign in, but even after inputting details, it does not sign in. Leaderboards are not accessible.

## Expected result

Auto-sign in to Google Game Services occurs, and I can then access submit to the leaderboard.
If Auto-sign in doesn't occur, then Native Google Services pop up should appear asking to confirm sign in.

## Affected browsers

* APK: YES
* Chrome: N/A
* Firefox: N/A
* Edge: N/A
* Safari: N/A

**Comment by shortercode** [comment] 2018-02-12 13:08
This is a known issue with the Google Play plugin. It currently only works for HTML exports. We use their web API, which has been blocked in webviews. To get around this I am writing an interface to use the native API instead when in a webview. It's pretty close to completion and should be included in one of the upcoming beta releases.

**Comment by shortercode** [comment] 2018-02-12 13:09
Closing as duplicate of #452

**Closed by shortercode** 2018-02-12 13:09 UTC
Labels: duplicate
