### ISSUE TITLE
Deleting Instance Variables while Object is on Layout causes C3 to crash

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#876] opened 2017-10-04 15:27 UTC
## Problem description

Something silly happened: I had a few instances of an object on the stage with instance variables. I decided to change my system around so i deleted the instance variable and added a new one. Then i wanted to delete an Instance of the object from the Layout, which in turn caused C3 to crash. Weirdly enough, it didn't happen when i reopened the Project and tried it again but i thought i'd open up a Report anyway so you can see the Crash Report.

## Steps to reproduce

1. Add a Sprite
2. Give it random Inst Variables
3. Create multiple Instances of this Sprite on the Stage
4. Delete Instance Variables again or change them
5. Try to delete one of the Sprites off the layout

## Observed result

Crash.

## Expected result

Not to Crash...

## Affected browsers

* Chrome: yes

## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r59/main.js, line 61, col 136245
Message: Uncaught Error: object instance does not have associated behavior instance
Stack: Error: object instance does not have associated behavior instance at window.ǃgk.ǃcP (https://editor.construct.net/r59/main.js:61:136251) at d.ǃqVr (https://editor.construct.net/r59/main.js:61:206877) at d.ǃkp (https://editor.construct.net/r59/main.js:61:71074) at window.ǃUB.ǃkR (https://editor.construct.net/r59/components/editors/layoutView/layoutView.js:1:27263) at window.ǃUB.ǃbv (https://editor.construct.net/r59/components/editors/layoutView/layoutView.js:1:26774) at Array.ǃBe.ǃq.ǃBt.ǃq.ǃBs.ǃBd (https://editor.construct.net/r59/components/editors/layoutView/layoutView.js:1:3413) at ǃq.Event.ǃBHQ.ǃBHN (https://editor.construct.net/r59/main.js:2:263408) at ǃq.ǃT.ǃN.ǃqUn.dispatchEvent (https://editor.construct.net/r59/main.js:2:261697) at ǃq.ǃT.ǃN.ǃqUn.ǃbv (https://editor.construct.net/r59/main.js:2:306629) at ǃq.ǃT.ǃqXN.ǃqXc (https://editor.construct.net/r59/main.js:50:41499)
Construct 3 version: r59
URL: https://editor.construct.net/
Date: Wed Oct 04 2017 17:22:54 GMT+0200 (CEST)
Uptime: 9033.8 s

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r59
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 6100
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2017-10-04 15:33
It's much more likely we can fix the bug if you can provide specific reproduction steps. Steps like "give it random variables" or "delete or change them" are difficult to follow and make it unlikely I can follow exactly what you're doing.

**Comment by joelmayer87** [comment] 2017-10-04 15:40
Okay what i did was this:

For an Inventory system i added a Sprite 8x8 Pixels and at first i wanted to create the Items on the Screen by using one Sprite and then setting it's animation every tick to its instance variable, if that makes sense.

Then i remembered that with C3 you can actually create objects by name now so i changed my mind about that approach ;)

But i just added a Sprite and gave it the String Instance Variable "object" and set it to, lets say, Apple. Then i added an Every Tick event to set the obj_item sprite Animation to its inst variable "object".

Then i deleted this again and added two instance variables which are not going to be changed and are just descriptions of the Object in German and English and will show up on the Screen when the player overlaps, but i never got that far. So i added two string instance variables one descr_en and one descr_de. 

And then i cloned the object to make different items. Then i realized, that the old object was still on the layout so i tried to delete them and this was when the crash happened. It seems to say something about a Behaviour, the only behaviour added was a standard physics behaviour, i didn't change any settings... Hope this helps ;)

**Comment by AshleyScirra** [comment] 2017-10-06 11:01
I still can't follow these repro steps. The order seems jumbled (you only mention adding a behavior at the end), and you seem to change your mind half-way through ("then I remembered..."), and it seems to refer to elements of your project but there is no project file provided, and I'm not sure exactly what you're doing at some steps (did you delete just an instance from the layout or the whole object type from the project bar?)

I really want to fix this issue but I can't figure it out from the information provided. Can you provide a .c3p project to start with, and then a simple numbered step-by-step guide to reproduce the issue?

**Comment by joelmayer87** [comment] 2017-10-06 11:43
The problem is, that i can't reproduce it myself and these were the steps i was doing last when the crash happened, sorry. My uneducated guess is, that C3 somehow gets confused when deleting instance variables of an object off an object selected in the project management view and then trying to delete it off the stage but i don't know.

Maybe in this particular case it would be best to close this issue and in case it comes up again i'll try to reproduce it more coherently ;)

Thanks.

**Comment by tunepunk** [comment] 2017-11-06 15:01
Added reproduce steps to #962 

https://github.com/Scirra/Construct-3-bugs/issues/962

Crash seems to be caused by clipboard pasting object with some behaviour reference.

**Comment by AshleyScirra** [comment] 2017-11-06 15:05
Closing as repro steps for a similar error were provided in #962, so will follow up there.

**Closed by AshleyScirra** 2017-11-06 15:05 UTC
