### ISSUE TITLE
Anchor behaviour not working as expected

### ISSUE THREAD

**Issue by dru1000** [Scirra/Construct-3-bugs#1796] opened 2018-07-13 23:52 UTC
## Problem description

After enabling Anchor behavior on a sprite the sprite moves.

## Attach a .c3p
[anchor bug1.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2194477/anchor.bug1.c3p.zip)

## Steps to reproduce

1. Press A to enable anchor behavior on sprite

## Observed result

The sprite moves left by 8px

## Expected result

The sprite shouldn't move

## Affected browsers

* Chrome: yes

**Comment by eleanorawesome** [comment] 2018-07-16 03:05
This is what the anchor behavior is supposed to do, it's not a bug, refer to the manual on anchor https://www.construct.net/ca/make-games/manuals/construct-3/behavior-reference/anchor 
![image](https://user-images.githubusercontent.com/32940085/42741735-db0f34c8-8882-11e8-8222-473ea2a86004.png)

**Comment by dru1000** [comment] 2018-07-16 03:38
In the example I posted the viewport never changes. Its my understanding Anchor should only move (or not move) an object when the viewport changes.

**Comment by dru1000** [comment] 2018-07-17 01:32
I recreated the bug here just to be sure - https://www.dropbox.com/s/unj913xubrhnrh2/anchor-bug-1.c3p?dl=0

With Anchor set to Left, pressing A to enable the behavior jumps the sprite 8px to the right. With it set to Top it jumps 8px down.

I've done some more tests, I can consistently reproduce the bug but only when running it in Chrome Standalone Mode (from a desktop link without the browser address bar). Can you try it doing that?

In my tests It works fine in Chrome Browser, Firefox Browser, C3 Desktop. I've also tried on 2 PC's with the same results.

Plus I've tried disabling all browser extensions. 

Another oddity is it only happens with Fullscreen Mode set to OFF.

**Comment by dru1000** [comment] 2018-07-17 10:00
Maybe I'm losing the plot, but take a look at this example as well
https://www.dropbox.com/s/pze3jx6lh6brez7/VIewportTest.c3p?dl=0

1. Increase the size of the Browser window by dragging the right side out
2. Press SPACE to move the sprite to the right side
3. The Sprite moves to 600px which was the previous ViewportRight before the canvas was resized

It works fine if you disable then "Enable Anchor" behavior in the events.

**Comment by AshleyScirra** [comment] 2018-07-17 10:30
I think this is a combination of two things:

1) crbug.com/777854 which causes the preview window to be a slightly wrong size when running from the desktop, which affects the viewport

2) using fullscreen mode "off". The Anchor behavior is not designed to work in this mode at all. I'm not sure what you expect it to do in this case, because with fullscreen mode "off" the viewport never changes.

I don't think it's worth fixing the Anchor behavior to work in a mode that doesn't actually resize the viewport, so closing as wontfix.

**Closed by AshleyScirra** 2018-07-17 10:30 UTC
Labels: wontfix
