### ISSUE TITLE
(Editor) Event sheets still don't remember column widths & are sometimes squished

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#3710] opened 2020-03-14 19:23 UTC
## Problem description
There appears to be 2 bugs with event sheet columns:
1) Event sheet column widths are not remembered.
2) Sometimes instead of going to default widths they are squished.

Almost every time I open an event sheet I am greeted to something like this:
![image](https://user-images.githubusercontent.com/36490901/76688816-6e02d780-65fe-11ea-8e51-4d0546771837.png)

It is such an inconvenience to resize the columns all the time, and a legitimate productivity issue. I know this isn't a suggestion platform but alongside these issues being resolved, it would be great if all event sheets just shared the same column widths (or at least add the option in settings).

## Steps to reproduce

1. Make and adjust numerous event sheets.
2. Open and close them in no particular order.

## Observed result

Event sheet column widths are not remembered and/or squished.

## Expected result

Event sheet column widths should be as I left them.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** Always been an issue but using r190 currently

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.132
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
C3 release: r190 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 745 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2020-03-16 11:46
I can't follow those steps to reproduce because they are too vague. Can you provide reliable steps to reproduce?

**Comment by Tokinsom** [comment] 2020-03-16 20:13
Well in the case of event sheets _not remembering the widths_ you simply open and close one. Here's a .gif showing it in realtime
![TheGif](https://user-images.githubusercontent.com/36490901/76796059-9cb4b580-6798-11ea-9da5-a22962dba171.gif)

As for them being squished, it seems to happen randomly after the above steps, but I'll see if I can narrow it down.

**Comment by AshleyScirra** [comment] 2020-04-02 15:41
I can't reproduce this. If no project is provided I just open Ghost Shooter and try it there. If I do that, I can resize the event sheet column sizes, close the tab, and reopen it, and it looks exactly like I left it, so it seems to be working fine.

This is pretty much the usual way things go when issues don't attach a project or include clear steps to follow. There is likely something else going on that causes the issue, but without a project and steps to reproduce there's not much I can do about it. Can you provide those?

**Comment by AshleyScirra** [comment] 2020-04-15 15:35
It's been about 2 weeks and I don't have a way to reproduce this, so closing for now. Please file again if you can identify reliable steps to reproduce.

**Closed by AshleyScirra** 2020-04-15 15:35 UTC
Labels: can't reproduce
