### ISSUE TITLE
Layer Effects Bug

### ISSUE THREAD

**Issue by RorySoh** [Scirra/Construct-3-bugs#3254] opened 2019-08-23 18:16 UTC
## Problem description

Since r162, if you try to use a layer as a Subtract mask, it inverts the entire layer. This also seems to cause issues with other effects such as blur horizontal/vertical.

I use this to apply a layer as a Day/Night mask on the rest of the game.

## Attach a .c3p

[LayerMaskTest.zip](https://github.com/Scirra/Construct-3-bugs/files/3535704/LayerMaskTest.zip)

## Steps to reproduce

1. Add a layer on top of another layer
2. Make the top layer a non-transparent layer
3. Add Subtract effect to it

## Observed result

Layer flips vertically / gives a weird trippy effect.

## Expected result

It should just subtract onto the layer below.

## More details

This is how what I use this for:

https://imgur.com/UQFsUpw
The day night effect

This is what I get now
![Screenshot 2019-08-24 02 15 40](https://user-images.githubusercontent.com/5456478/63614233-20e4f700-c615-11e9-87fa-427d95532928.png)

I understand that the latest beta is trying to fix conflicts between multiple effects, but if it's at the expense of making single effects on layers faulty, it seems like a bad sacrifice! I hope this can be fixed on the next stable, I do want to develop on the latest stable of C3 when the next stable build is out :)

**Affected browsers/platforms:** 

**First affected release:** r162

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2019-08-27 11:57
This is a regression caused by the fix to #2121. The next release will revert the incorrect fix. Closing and reopening the original issue.

**Closed by AshleyScirra** 2019-08-27 11:57 UTC
