### ISSUE TITLE
Cutting an event while in a popup window causes C3 to crash

### ISSUE THREAD

**Issue by DrSquidge** [Scirra/Construct-3-bugs#3538] opened 2019-12-10 16:56 UTC
## Problem description

When using an event sheet in a popup window, cutting an event causes Construct 3 to crash. 

## Attach a .c3p

[Popup Window Crash](https://1drv.ms/u/s!Al0pc3FK6sBEgZ8pVGLpk2NyVixCDA)

## Steps to reproduce

1. Open project
2. Cut either the event or action
3. Observe crash

## Observed result

Construct 3 crashes.

## Expected result

To be able to cut an event/action without a crash

## More details

Works fine as an undocked pane, and when you have tabs open in the side-by-side view, just not a popup window. 

**Affected browsers/platforms:** 

Chrome, macOS

**First affected release:** 
Can reproduce in Kiwi Story in r171.3

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Document is not focused.
Construct 3 version: r179
URL: https://editor.construct.net/r179/
Date: Tue Dec 10 2019 16:48:54 GMT+0000 (Greenwich Mean Time)
Uptime: 110.1 s

Platform information
Browser: Chrome
Browser version: 78.0.3904.108
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
C3 release: r179 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) HD Graphics 6000
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context</details>

**Comment by AshleyScirra** [comment] 2019-12-11 13:03
Note this only reproduces when using the right-click menu 'Cut' option, not when using the Ctrl+X keyboard shortcut. (Probably because we resort to the clipboard API in that case)

**Comment by AshleyScirra** [comment] 2019-12-11 13:29
Should be fixed in the next release. As I suspected it turns out many clipboard operations don't work when the main window does not have focus, i.e. when you're using a popup window. This affected a few other cases like the Layout View 'Copy co-ordinates' menu option and the event sheet 'Copy as text' menu option. These should now all be handled in a popup window by either hiding menu options that aren't supported there, or falling back to what we call the "fake clipboard" (in-memory storage that isn't actually on the system clipboard). Thanks for the report!

**Comment by shortercode** [comment] 2019-12-11 13:36
That's a rather unpleasant edge case... Could it work if it was done using the clipboard API associated with the popup window instead? 

`element.ownerDocument.defaultView.navigator.clipboard`

**Comment by AshleyScirra** [comment] 2019-12-11 17:55
Hmm, that's an interesting idea actually. It might be a little bit hacky and we'd have to pass around windows or context elements a bit like the dialog system though. I'll reopen this and check it tomorrow.

**Comment by AshleyScirra** [comment] 2019-12-12 13:53
@shortercode's idea seems to work fine, which gives us a better workaround, since it means the real clipboard keeps working in popup windows. The code is a bit odd but it seems to work fine!

**Closed by AshleyScirra** 2019-12-12 13:53 UTC
