### ISSUE TITLE
Hangs up on boot on iphone

### ISSUE THREAD

**Issue by Madiosn** [Scirra/Construct-3-bugs#2924] opened 2019-05-07 11:54 UTC
## Problem description
The game freezes on the loading screen. And it does not load.

## Attach a .c3p
https://yadi.sk/d/sSaVvjRx3PUZQw

This file has been converted for xCode.
https://yadi.sk/d/Xt8ekCNROCctag

## Steps to reproduce

1. Run build in Xcode on device
2. 
3.

## Observed result
The application freezes on the boot screen and hangs.
Attached screen. https://yadi.sk/i/3JF1AvtpJnOFpw

## Expected result
After loading, level 1 should start.

When testing on a computer in Chrome / Safari, everything works OK

## More details

The problem appears on iphoneX and any other model with the help of Xcode test

**Affected browsers/platforms:** 
Tested on xCode latest version.
Macbook Pro with Mojave OS

**First affected release:** 
r147
## System details

2019-05-07 14:52:17.728376+0300 Dont Run[24780:10277916] ERROR: Error loading:  SyntaxError: The string did not match the expected pattern.

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment] 2019-05-07 12:49
The game is failing to load your font file, I'm not familiar with this system so I'm going to assign to @AshleyScirra 

I've created a minimal reproduction case for the issue:

[font_test_case.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3152667/font_test_case.c3p.zip)

It would appear to be failing in `async _LoadWebFont(a, b)` during ```new FontFace(a, `url(${c})`)``` and producing the cryptic error "SyntaxError: The string did not match the expected pattern.".

**Comment by AshleyScirra** [comment] 2019-05-07 17:01
No need for Xcode, reproduces in Remote Preview. It looks like Safari doesn't like a number as a font name - perhaps it's not a valid CSS identifier or something. So renaming the font file should be enough to fix this. You should also be using WOFF, since that's the only standard font file supported on all platforms. I've fixed the next release to handle this error loading the web font so the game continues to run, but the web font still fails to load, so you'll still need to rename it.

**Closed by AshleyScirra** 2019-05-07 17:01 UTC
Labels: iOS
