### ISSUE TITLE
Worker Breaks Android Exports

### ISSUE THREAD

**Issue by corlenbelspar** [Scirra/Construct-3-bugs#2692] opened 2019-03-05 21:04 UTC
## Problem description

If you export to Android debug APK with worker enabled, all you get is a black screen.

## Attach a .c3p

[https://drive.google.com/open?id=1Gyn3A59VbFeA5hvp8RPVm6aZA_16dZK9](https://drive.google.com/open?id=1Gyn3A59VbFeA5hvp8RPVm6aZA_16dZK9)

## Steps to reproduce

1. Export to Android debug APK.
2. Use it on your phone.

## Observed result

All I see is a black screen.

## Expected result

There should be a white screen because the first layout is a blank one with a white background.

## More details
**Affected browsers/platforms:** Android

**First affected release:** r140

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r140 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 42 gb
Storage usage (approx): 3.2 gb (7.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2019-03-06 16:35
Have been able to confirm this but not much more, the worker appears to be being created but I get nothing after that. Might be an oddity of the Chrome debugger but it's hard to tell. As @AshleyScirra wrote the original code for this I'm going to reassign it to him to investigate, hopefully he will have more luck!

**Comment by AshleyScirra** [comment] 2019-03-07 17:42
I can reproduce in r139 so I don't think this is unique to r140. It might be to do with the latest Chrome update, I am fairly sure this used to work... interestingly the "Hosted in worker" console log appears, which is printed from the runtime side, which would suggest the web worker has started up OK but the runtime fails some part of initialisation.

**Comment by AshleyScirra** [comment] 2019-03-07 17:57
Looks like a [Heisenbug](https://en.wikipedia.org/wiki/Heisenbug): attaching the debugger after initialisation shows a log from the runtime ("Hosted in worker"), but attaching the debugger before initialisation does not show a log, suggesting attaching a debugger causes it to fail earlier. This will reduce us to more primitive debugging techniques, and deserves the difficult tag...

**Comment by AshleyScirra** [comment] 2019-03-08 13:04
This appears to be a bug in the Chromium engine so filed [crbug.com/939775](https://bugs.chromium.org/p/chromium/issues/detail?id=939775). Closing this issue as will follow up there. Our next release will disable worker mode in Cordova to work around this.

**Closed by AshleyScirra** 2019-03-08 13:04 UTC
Labels: Android, difficult, external
