### ISSUE TITLE
Adding global layer with sub-layers results in crash

### ISSUE THREAD

**Issue by stalin-joseph** [Scirra/Construct-3-bugs#5208] opened 2021-11-09 14:01 UTC
## Problem description

Adding a global layer results in crash if it has any sub-layers in it.

## Attach a .c3p
[global_layers.zip](https://github.com/Scirra/Construct-3-bugs/files/7505196/global_layers.zip)

## Steps to reproduce

1. Add a sub-layer
2. Set the 'Global' option of the parent layer to 'Yes'
3. Add the parent layer to another layout

## Observed result

Construct 3 crashes.

## Expected result

The parent layer is added alongside with the nested sub-layers.

## More details

**Affected browsers/platforms:** All.

**First affected release:** 271

## System details

<details><summary>View details</summary>
Error report information
Type: unhandled exception
File: https://editor.construct.net/r271/main.js, line 482, col 182
Message: Uncaught TypeError: Cannot read property 'pua' of undefined
Stack: TypeError: Cannot read property 'pua' of undefined at Object.CCG.xka (https://editor.construct.net/r271/main.js:482:182) at Object.CCG.Ik (https://editor.construct.net/r271/main.js:497:261) at d.yf (https://editor.construct.net/r271/projectResources.js:1171:482) at d.yf (https://editor.construct.net/r271/projectResources.js:1171:298) at d.yf (https://editor.construct.net/r271/projectResources.js:1132:460) at vTb (https://editor.construct.net/r271/components/editors/layoutView/layoutView.js:77:284)
Construct 3 version: r271
URL: https://editor.construct.net/r271/
Date: Tue Nov 09 2021 20:53:35 GMT+0700 (Indochina Time)
Uptime: 20 s

Platform information
Browser: Chrome
Browser version: 85.0.4183.83
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
C3 release: r271 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2
</details>

**Comment by AshleyScirra** [comment] 2021-11-09 14:17
Looks like another case of #5209 which has a simpler repro so marking duplicate of that.

**Closed by AshleyScirra** 2021-11-09 14:17 UTC
Labels: duplicate
