### ISSUE TITLE
Property tab didn't have anything in it, crashing when I closed and reopened

### ISSUE THREAD

**Issue by damjancd** [Scirra/Construct-3-bugs#2218] opened 2018-10-31 16:12 UTC
## Problem description

Can't open properties at all now. 

## Attach a .c3p

Any new project does this

## Steps to reproduce

1. Open new project
2. Properties is not open
3. View -> Make properties tab visible
4. Crash

## Observed result

Crash

## Expected result

Notcrash

## Affected browsers

* Chrome: yes/no

## System details

<details>
<summary>Error report information</summary>
Type: unhandled exception
File: https://editor.construct.net/r123-2/components/misc/mainMenu/mainMenu.js, line 1, col 6714
Message: Uncaught ReferenceError: ǃm is not defined
Stack: ReferenceError: ǃm is not defined at ǃ$LW.ǃ$Lz.ǃ$Lh (https://editor.construct.net/r123-2/components/misc/mainMenu/mainMenu.js:1:6714) at a.ǃLK (https://editor.construct.net/r123-2/components/misc/mainMenu/mainMenu.js:1:7482)
Construct 3 version: r123.2
URL: https://editor.construct.net/r123-2/
Date: Thu Nov 01 2018 00:09:27 GMT+0800 (Singapore Standard Time)
Uptime: 21.3 s

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_1
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r123.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 6100
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context</summary>

</details>

**Comment by damjancd** [comment] 2018-10-31 16:14
Works properly after restart of Chrome. Don't know if this is a one off I can't really recreate. I'll leave the bug report maybe others will run into similar stuff

**Comment by shortercode** [comment] 2018-10-31 17:17
Can confirm the crash closing the properties bar, it's teardown method is broken in r123-2. I'm unable to reproduce your issue with it not opening in r123-2 though.

For reference you can close the bar in r122, then switch to r123-2 to test this.

**Comment by DiegoScirra** [comment] 2018-11-01 10:54
This should be fixed in the next beta release.

Leaving this one open in case someone else notices.

**Closed** 2018-11-06 12:56 UTC
