### ISSUE TITLE
Crash when changing size of dictionary in dictionary editor

### ISSUE THREAD

**Issue by driesdriessen** [Scirra/Construct-3-bugs#5582] opened 2022-03-30 12:36 UTC
## Problem description

C3 crashes when I change the size of a dictionary in the dictionary editor 

## Attach a .c3p

This error occurs in an empty project 

## Steps to reproduce

1. create new project
2. right-click on files in the Project bar
3. create new dictionary
4. change the size
5. C3 crashes

## Observed result

C3 crashes

## Expected result

Dictionary size changes

## More details

Chrome browser 92.0.4515.159 on OSx 11.6.4

Issue occurs in beta release 288
Issue does not occur in  in stable release 285.3

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js, line 60, col 313
Message: Uncaught TypeError: Cannot read property 'size' of null
Stack: TypeError: Cannot read property 'size' of null at Nib.w8b.pjc (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:60:313) at d.mE (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:15:504) at d.Qkb (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:34:46) at Array. (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:18:462) at CCG.Rh.g.mb.dispatchEvent (https://editor.construct.net/r288/main.js:1055:42) at HTMLInputElement.tsb (https://editor.construct.net/r288/main.js:1532:485)
Construct 3 version: r288
URL: https://editor.construct.net/r288/
Date: Wed Mar 30 2022 14:35:44 GMT+0200 (Midden-Europese zomertijd)
Uptime: 78.6 s

Platform information
Browser: Chrome
Browser version: 92.0.4515.159
Browser engine: Chromium
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_7
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
C3 release: r288 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel HD Graphics 5000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by DiegoScirra** [comment] 2022-03-30 12:53
Duplicate of #5579.

**Closed by DiegoScirra** 2022-03-30 12:53 UTC
Labels: duplicate
