### ISSUE TITLE
C3 Runtime not worked with Pathfinding behavior (export to .apk)

### ISSUE THREAD

**Issue by Sowhenifoundfreenickname** [Scirra/Construct-3-bugs#2128] opened 2018-10-09 10:31 UTC
## Problem description

C3 Runtime. When using the pathfinfing behavior and exporting the project to the apk file, it does not work on the smartphone, a black screen is displayed after C3 the splash screen. When you switch to c2 runtime, then everything is fine

## Attach a .c3p

[test.zip](https://github.com/Scirra/Construct-3-bugs/files/2459944/test.zip)

## Steps to reproduce

1.Run a project
2.Export to apk file
3.Install the apk file on your smartphone and run it

## Observed result

black screen

## Expected result

Working project

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2018-10-09 11:15
Does this affect the HTML5 export for you too? If so, likely a duplicate of #2120

**Comment by AshleyScirra** [comment] 2018-10-09 12:35
Looks like an issue with case-sensitive filenames. Should be fixed in the next release.

**Comment by AshleyScirra** [comment] 2018-10-10 19:17
Had three reports of this so will leave open with fixed label until next release.

**Closed** 2018-10-15 13:40 UTC
Labels: Android, c3runtime
