### ISSUE TITLE
(image editor) Image point reverts to old position on animation change

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#3797] opened 2020-04-21 17:41 UTC
## Problem description

(In the image editor) Image point reverts to previous position when I change animations. 
EDIT: This happens when both editing a single frame, and shift+clicking to apply image point positioning to all frames.

## Attach a .c3p

![TheGif](https://user-images.githubusercontent.com/36490901/79895722-f0847100-83cc-11ea-8c9a-456e7091815f.gif)

## Steps to reproduce

1. Make 2 animations with 1 frame each
2. Change the image point position on animation 1
3. Select animation 2, then go back to animation 1

## Observed result

The image point goes back to its original position before I moved it

## Expected result

The image point should stay where I put it

## More details

**Affected browsers/platforms:** 

**First affected release:** Seemed to start happening in the last few builds (r193-r196 or so)

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.163
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
C3 release: r196 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 1.8 gb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2020-04-30 17:01
Can't reproduce this one with those steps. Can you post a test project?

**Comment by AshleyScirra** [comment] 2020-05-19 15:15
Issues that cannot be reproduced are not actionable, so closing. Please re-file if you can find a way to more reliably reproduce it. Please always follow the bug report guidelines and include a project from the start, with every report, to avoid this happening.

**Closed by AshleyScirra** 2020-05-19 15:15 UTC
Labels: can't reproduce
