### ISSUE TITLE
Tilemaps can't erase in r117

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#4250] opened 2020-09-28 19:27 UTC
Tilemap object does not erase tiles in this beta
Using the erase tile action, as well as the erase range action no longer results in an empty tile.

https://www.dropbox.com/s/mtugd60suvt2zyu/r117tilemapnoerase.c3p?dl=1

1. Run the project.
                  ( If the tilemap from the editor is the same then the erase range action did not work.)
2. If you drag the left mouse button while down it should erase those tiles
3. If you drag the right mouse button while down it should set those tiles to an empty tile(0)
             

## Expected result
Erasing should give an empty tile like the empty texture at tile 0

## More details

**Affected browsers/platforms:** 
Chrome Version 85.0.4183.121
Construct 117
Windows 10

**First affected release:** 

The current stable release works as expected.

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2020-09-29 11:20
Duplicate of #4244

(note: r117 came out 2 years ago; I assume you meant r217)

**Closed by AshleyScirra** 2020-09-29 11:20 UTC
Labels: duplicate
