### ISSUE TITLE
[r20] Crash when adding a "set value" action to a group with local variable

### ISSUE THREAD

**Issue by Hieronims** [Scirra/Construct-3-bugs#109] opened 2017-04-21 11:47 UTC
## Problem description

Trying to add a "set value" action to a group results in a crash.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.On line 2 add an action system.
2. Choose "set value" for the test variable.
3. Give as value 100 for example.

## Observed result

The editor crashes

## Expected result

Do the same thing with a global variable outside a group do not pause problem

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HEREError report information
Type: unhandled rejection
Reason: TypeError: Right-hand side of 'instanceof' is not an object
Stack: TypeError: Right-hand side of 'instanceof' is not an object at Function.ǃS.ǃpf (https://editor.construct.net/r20/main.js:2:201429) at Function.ǃS.ǃl (https://editor.construct.net/r20/main.js:2:201553) at Function.ǃS.ǃnw (https://editor.construct.net/r20/main.js:2:201628) at te.ǃSNw (https://editor.construct.net/r20/main.js:61:274378) at window.ǃtwX.ǃSAw (https://editor.construct.net/r20/main.js:61:335532) at window.ǃtwX.Set (https://editor.construct.net/r20/main.js:61:335679) at ǃS.ǃtRN.then.r (https://editor.construct.net/r20/components/editors/eventSheetView/eventSheetView.js:1:67894)
Construct 3 version: r20
URL: https://editor.construct.net/
Date: Fri Apr 21 2017 13:46:29 GMT+0200 (Paris, Madrid (heure d’été))
Uptime: 715.3 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 3
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce 9400 GT Direct3D11 vs_4_0 ps_4_0)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_disjoint_timer_query, EXT_frag_depth, EXT_shader_texture_lod, EXT_sRGB, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_draw_buffers, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

[New_project.zip](https://github.com/Scirra/Construct-3-bugs/files/946937/New_project.zip)

</details>

**Comment by AshleyScirra** [comment] 2017-04-21 11:55
Likely duplicate of #107, and r21 was just released so this should be fixed now.

**Closed by AshleyScirra** 2017-04-21 11:55 UTC
