### ISSUE TITLE
Construct r305 (beta) crashes if you rename an animation

### ISSUE THREAD

**Issue by cagtzn** [Scirra/Construct-3-bugs#5984] opened 2022-08-11 15:10 UTC
## Problem description

If any animation is renamed, the editor crashes. You can try to rename the default animation, an old one, a newly created one or a duplicate and these all lead to a crash.

## Steps to reproduce

1) Rename any animation in any project (old or a new one with only a sprite object).

## Expected result

Animation has a new name.

## Observed result

Oops! Something went wrong. Construct ran into a problem and is unable to continue...

## More details

**Affected browsers/platforms:**  Chrome

**First affected release:**  worked in r304, not anymore in r305

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'iB') @ TypeError: Cannot read properties of undefined (reading 'iB') at wM.k9b.Alb (https://editor.construct.net/r305/projectResources.js:1913:347) at Array.tba (https://editor.construct.net/r305/projectResources.js:1909:147) at window.xab.dispatchEvent (https://editor.construct.net/r305/main.js:1090:42) at window.xab.Sr (https://editor.construct.net/r305/main.js:2349:85) at d.Ra (https://editor.construct.net/r305/projectResources.js:693:184) at d.gl (https://editor.construct.net/r305/projectResources.js:694:6) at https://editor.construct.net/r305/projectResources.js:244:318
Stack: TypeError: Cannot read properties of undefined (reading 'iB') at wM.k9b.Alb (https://editor.construct.net/r305/projectResources.js:1913:347) at Array.tba (https://editor.construct.net/r305/projectResources.js:1909:147) at window.xab.dispatchEvent (https://editor.construct.net/r305/main.js:1090:42) at window.xab.Sr (https://editor.construct.net/r305/main.js:2349:85) at d.Ra (https://editor.construct.net/r305/projectResources.js:693:184) at d.gl (https://editor.construct.net/r305/projectResources.js:694:6) at https://editor.construct.net/r305/projectResources.js:244:318
Construct version: r305
URL: https://editor.construct.net/r305/
Date: Thu Aug 11 2022 16:59:10 GMT+0200 (Central European Summer Time)
Uptime: 6.4 s

Platform information
Product: Construct 3 r305 (beta)
Browser: Chrome 104.0.5112.81
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment] 2022-08-11 15:47
Duplicate of #5974

**Closed by AshleyScirra** 2022-08-11 15:47 UTC
Labels: duplicate
