### ISSUE TITLE
Unable or difficult to select input fields with single number

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4476] opened 2021-01-15 03:28 UTC
## Problem description
Issue that needs check if it designed like that?

Case that single number input fields can be difficult to select with mouse alone.

See video. Go fullscreen

It is possible to click and use arrow keys to navigate. But if user likes to change some specific number, it might be difficult to do so.
I know there are shortcut keys to change increment.
But it should be drag and select. Not just drag alone.

https://user-images.githubusercontent.com/28864889/104677659-792d0500-56f2-11eb-9d78-caa404adc8e8.mov

## Steps to reproduce

1.Try selecting single number input fields
2.
3.

## Observed result
Single number inputfields has only drag available and selection is disabled or something

## Expected result
Selection and drag for input fields

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 87.0.4280.141
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
C3 release: r231 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 1.4 gb (1.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2021-01-15 13:08
Please follow the bug report guidelines, it's difficult to interpret bug reports like the one you wrote. (We also advise not to use videos in the bug report guidelines, because they're actually more difficult to follow than steps - I can't see what precise sequence of clicks or key presses you're using, for example.)

Minimal project: 
[issue4476.zip](https://github.com/Scirra/Construct-3-bugs/files/5820642/issue4476.zip)

Steps to reproduce:
1. Select the text object
2. Attempt to drag and select just the "10" part of "100%" in the opacity property

Observed result: entire property text selected, appears to activate drag-to-change
Expected result: partial text selection to work. It works correctly in r225 so this appears to be a regression in recent releases.

I would guess this is a regression caused by Pointer Event changes so assigning to @DiegoScirra

**Comment by SnipG** [comment] 2021-01-15 14:00
Out of the topic, but I disagree. I think cases like this, It should be adviced for users to be more specific. Example:  ie occasionally all comments and text fields has been showing same behavior for so long as C3 exisited randomly, and user points it out. Then he should make specific example of it. Isolated and specific repo case of one instance where it showing up. But here he would wonder why he would need it, if all cases of it bugs.

So there could be advice for users to remember doing isolated case:

"If reported issue is general behavior, then it's adviced to make specific reproduced example of one instance of it"

My thought about it.

**Comment by AshleyScirra** [comment] 2021-01-15 14:28
We ask for this information because it's generally impossible to help you without it. The information I posted in my comment is the type of information we need to be able to fix problems. We have a comprehensive explanation of the rationale for these requirements in the bug report guidelines.

**Comment by SnipG** [comment] 2021-01-15 16:03
I think there should be a change how issue reporting generally/overally happens, i am not sure what it might be.  To avoid and improve chances, like this issue or similar issues getting fixed faster, currently it almost got into next stable release. Even days before stable release, the report occured and developers would closed it down, and I might not added more specific information to it. 
And in case major issue like this, affecting basic/default use of whole editor.

Even though if reporting, guidlines, information and everything is very specific, helpful and best possible to hunt issues down. But in the end the issue reports don't occure at all, there chould or should be desire to improve it from developers end.

Because every bit information there is, is to make issue reporting better, hunt issues down faster. So it seems reasonable, extra changes are needed if current ones don't serve best way possible.

So, if there is need: want to make life better. You make rules for it. But it should not be in the end: rules are need to make life better. But they are there to accomplish the "want to make life better", so they are not the main thing. 
But in the end it could be:
"Rules are there to lower the time cost of each issue"

**Comment by DiegoScirra** [comment] 2021-01-15 17:14
A fix for this will be up in the next beta.

**Closed by DiegoScirra** 2021-01-15 17:14 UTC

**Comment by AshleyScirra** [comment] 2021-01-16 13:02
@SnipG - FWIW, we've evolved the bug report guidelines over many years to maximise the chance the problem can actually be fixed. I am pretty sure we have settled on just about the best way we can manage it. No way is perfect, but I think what we have is the best way to actually solve problems.
