### ISSUE TITLE
Loader stlye keep revert back to Construct 3 Splash

### ISSUE THREAD

**Issue by arcadesindo** [Scirra/Construct-3-bugs#5577] opened 2022-03-29 04:10 UTC
## Problem description
This has been happened multiple times, we've set the loader style to Nothing, but suddenly out of nowhere after opening the project again, it back to Construct 3 Splash.

## Attach a .c3p
null

## Steps to reproduce

Can't reproduce the issue, because it happened randomly

## More details

**Affected browsers/platforms:** 

**First affected release:** 285.3 (actually this issue already occured on the past version)

**Comment by szabeszg** [comment] 2022-03-29 06:01
Unfortunately, I cannot provide more info either but I found that in a HTML exported project the only reliable way to make sure "Construct 3 Splash" does not show up is to use "Progress bar only". Since my games load fast on broadband connections I've put up with it, but seeing this issue report, I thought my comment can also point out that something fishy seems to be going on here.

**Comment by AshleyScirra** [comment] 2022-03-29 10:39
Probably a duplicate of #5322 - by design using the free edition will switch the option back, and without steps to reproduce, I would assume that is what is happening.

**Closed by AshleyScirra** 2022-03-29 10:39 UTC
Labels: duplicate

**Comment by szabeszg** [comment] 2022-03-29 11:37
FYI: I do not use the free edition.

**Comment by AshleyScirra** [comment] 2022-03-29 11:40
If you open a project very quickly before Construct has established your account status, it will still act as if it's the free edition until your account status is resolved.
