### ISSUE TITLE
[r29] Any project crashes within a minute of opening

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#254] opened 2017-05-18 19:54 UTC
## Problem description

Any project I open is causing C3 to crash within a few seconds. So far I have tried my game jam project, a new empty project, and the Pop Lab example project.

## Attach a .c3p

Please just use Pop Lab, or create a new empty project.

## Steps to reproduce

1. Open a project, i.e. the Pop Lab example.
2. Wait 40 seconds or so.

## Observed result

C3 crashes with error message (see below).

## Expected result

No crashes.

## Affected browsers

* Chrome: yes

## System details

The following error report is after opening Pop Lab and waiting around 40 seconds.

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'catch' of undefined @ TypeError: Cannot read property 'catch' of undefined at Sa (https://editor.construct.net/r29/cloud/sandbox.js:1:32469) at Wa (https://editor.construct.net/r29/cloud/sandbox.js:1:32958) at Za.eb.keys.then.gb (https://editor.construct.net/r29/cloud/sandbox.js:1:33324) at 
Stack: TypeError: Cannot read property 'catch' of undefined at Sa (https://editor.construct.net/r29/cloud/sandbox.js:1:32469) at Wa (https://editor.construct.net/r29/cloud/sandbox.js:1:32958) at Za.eb.keys.then.gb (https://editor.construct.net/r29/cloud/sandbox.js:1:33324) at 
Construct 3 version: r29
URL: https://editor.construct.net/index.html
Date: Thu May 18 2017 12:48:17 GMT-0700 (Pacific Daylight Time)
Uptime: 122.6 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment] 2017-05-18 19:58
Do you have **Periodically back up project** enabled? There's an issue with saving at the moment, so it will choke up when it tries to autosave

**Comment by shortercode** [comment] 2017-05-18 20:03
Related to [#251](https://github.com/Scirra/Construct-3-bugs/issues/251)

**Comment by Scoremonger** [comment] 2017-05-18 21:06
@shortercode Yes, I did have auto-backup enabled (even though I have no idea how it works or where it saves backups). Once I turned it off the crashing stopped.

**Comment by shortercode** [comment] 2017-05-18 21:32
They save to the "local browser save", and will appear as <Project Name>.__autosave__.c3p

The feature probably needs a bit of tweaking to be honest, maybe some options for how often to save and how it saves etc.

**Comment by sielxm3d** [comment] 2017-05-19 00:51
This is a recent issue of up from r28 to r29 the error appear be from attempt to  load old project r28 on this newest version

**Comment by sielxm3d** [comment] 2017-05-19 00:55
I tried to save the new file with the new version of c3, but still our program insists on closing.

**Comment by AshleyScirra** [comment] 2017-05-19 10:43
Looks like a dupe of #251, should be working in r29.2 now.

**Closed by AshleyScirra** 2017-05-19 10:43 UTC
