### ISSUE TITLE
Vue.js devtools extension crashes when right clicking

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#1238] opened 2018-01-25 04:53 UTC
## Problem description

right clicking in new projects causes crash

## Attach a .c3p

c3p : https://drive.google.com/open?id=1bUHphYNapmwZWvXIDf3kGxJBbXzr9EWu
gif : https://drive.google.com/open?id=1QTZZmlWuxTj8HrF2Iu7OQrQ74dBlQLRk

## Steps to reproduce

create new project, right click

## Observed result

crash

## Expected result

right click context menu opens

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/, line 1, col 784
Message: Uncaught ReferenceError: o is not defined
Stack: ReferenceError: o is not defined at HTMLDocument.document.addEventListener.t (:1:784)
Construct 3 version: r81
URL: https://editor.construct.net/
Date: Wed Jan 24 2018 23:50:03 GMT-0500 (Eastern Standard Time)
Uptime: 39.4 s

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r81
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by armandoalonso** [comment] 2018-01-25 05:03
clearing chrome cache fixed the issue, this can be closed

**Comment by AshleyScirra** [comment] 2018-01-25 11:27
We're looking in to this, but none of us in the Scirra office can reproduce this. Any extra information about how this happens, when, or on which systems, would be helpful. It might be worth disabling browser addons too in case that's related.

**Comment by AshleyScirra** [comment] 2018-01-25 12:05
Can you confirm that if you go back to r80 it doesn't happen?

**Comment by rilem** [comment] 2018-01-25 12:18
Disabling the Vue.js devtools chrome extension fixed the issue on my machine!

**Comment by AshleyScirra** [comment] 2018-01-25 12:27
I can reproduce! This is awkward. Thanks for figuring that out.

**Comment by AshleyScirra** [comment] 2018-01-25 12:39
Filed issue with Vue.js here: https://github.com/vuejs/vue-devtools/issues/565

In the mean time, please remove the extension from Chrome. It causes errors on all web pages. It's worse in Construct 3 because we show the crash dialog when any error happens.

**Comment by shortercode** [comment] 2018-01-25 16:35
According to the Vue.js team this problem has now been fixed, and the patched version is available on the CWS. 

https://github.com/vuejs/vue-devtools/issues/514#issuecomment-360483571

**Comment by AshleyScirra** [comment] 2018-01-25 17:15
Think we can close this issue now if the update has been published.

**Closed by AshleyScirra** 2018-01-25 17:15 UTC
Labels: browser extension, external, fixed
