### ISSUE TITLE
Cannot export C3 runtime project with script minification enabled

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#1979] opened 2018-09-03 14:33 UTC
## Problem description

(C3 Runtime) Failed to Export Project (NW.js) with C3 Demos Demonoir, Kiwi Story, Glokar.

## Attach a .c3p

Please use any C3 Demos Demonoir, Kiwi Story, Glokar.

## Steps to reproduce

Open one of the Demo projects.
Switch to C3 runtime.
Export Project to NW.js

Following Setting Checked /  all other unchecked.

(general)

- Deduplicate
- Recrompress
- Minify

(nwjs specific)

- Win64
- Window Frame
- Resizable Window
- Ignore GPU Blacklist

## Observed result

Failed to Export Dialog

## Expected result

NWJS exported project

## Affected browsers

* Chrome: tested only Chrome 68

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 68.0.3440.106
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
C3 release: r115 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 47 gb
Storage usage (approx): 278 mb (0.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA Quadro K3100M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment] 2018-09-04 14:50
It works if you untick "minify script", and also reproduces if you do a HTML5 export with "minify script" enabled, so this appears to be an issue exclusively to do with script minification on export with the C3 runtime. Also it only reproduces in production which will make this difficult to investigate...

**Comment by AshleyScirra** [comment] 2018-09-05 17:13
This looks like a bug with the version of babel-minify we're using, which is a bit old now. The main difficulty is that babel-standalone aren't distributing standalone releases of babel-minify any more so to upgrade we have to figure out how to get an up-to-date build ourselves, which appears to have been left undocumented. After a bunch of looking around I think I've hacked something together which might work.

**Comment by AshleyScirra** [comment] 2018-09-06 13:54
This involved a whole bunch of changes, but I think I've got it working in the next release. Let's check when it's out.

**Comment by AshleyScirra** [comment] 2018-09-10 12:28
r116 is out now, can you verify it works with that?

**Comment by NetOneGames** [comment] 2018-09-11 11:00
Sorry I just saw this I will check tonight.   Thanks....

**Comment by AshleyScirra** [comment] 2018-09-12 18:52
I think this comes down to the use of the 'float' and 'int' system expressions. Think it's fixed in the next release but let's check when it's out.

**Comment by AshleyScirra** [comment] 2018-09-13 14:19
This should (hoepfully) be working now as of r117.2. Can you try that and check it works for you?

**Comment by NetOneGames** [comment] 2018-09-13 19:45
Tried , with the above settings
My Project in Canary with 68 nwjs  export
and Demonoir in Chrome 69 with nwjs 69 export
and got
**Sweet C3 runtime exports!**
So not extensive test but appears to work.   Nice one!
Great release today! lots fixed _and_ a new feature ..    Awesome....

**Comment by AshleyScirra** [comment] 2018-09-13 23:47
Thanks for verifying.

**Closed by AshleyScirra** 2018-09-13 23:47 UTC
Labels: c3runtime, difficult

**Comment by NetOneGames** [comment] 2018-09-21 13:50
Just to follow up on this,  I tried some pure html exports with minified and am getting blackscreen when hosted with console error Cannot read property 'apply' of undefined.   I will try to do some more testing next week  (away weekend) but this may not be totally resolved.  
ps Also Im noticing some touch issues in the nwjs build probably unrelated.

**Comment by NetOneGames** [comment] 2018-09-21 14:28
To confirm:  Minification is definitely also messing with touch (in the nwjs exports i tested).  it is like it is only accepting 1 touch at a time.

however i am unable to validate with a simple project.   I will try next week.
