### ISSUE TITLE
Failed to download local browser saves

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#3019] opened 2019-06-06 14:23 UTC
## Problem description
When tring to use new feature to download local browser saves, then download fails.
See picture:
![FailedDownload](https://user-images.githubusercontent.com/28864889/59040342-25540c00-887f-11e9-86f7-4dc3894181b6.jpg)

Tring to test which save causes it, atm i am not sure which it is.

## Steps to reproduce

1. Navigate settings, click download local browser saves
2. Save fails
3.

## Observed result
Save feature fails to download local browser saves

## Expected result
Save succeeds downloading saves.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 74.0.3729.169
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
C3 release: r152 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 1.7 gb (12.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2019-06-06 15:34
Mmm this looks troubling, it's actually failing to read one of the binary blobs for some reason. We can't really fix that. I might be able to work around it though, we've learnt a few tricks for getting around buggy blob implementations. If it turns out to be a corruption of a specific file then the best option for us is to probably skip it instead of trying to add it to the zip.

**Comment by SnipG** [comment] 2019-06-06 16:12
"A requested file or directory could not be found at the time an operation was processed." some message inside that console error.

This error could easily possible. I have multiple times backedup and moved browser saves from indexedDB, so it might think some saves should be there, but just aren't, as indexedDB host 4 main folders, i could maybe moved just one with saves etc. So script that host database with names, order.. etc just got it wrong when i want to export from browser with new feature.

**Comment by AshleyScirra** [comment] 2019-06-07 10:50
@shortercode - remember we previously had issues with drag-and-dropping files in to the editor then trying to read them after the original file was moved/renamed. It seems the blob refers to an actual file handle on disk. Is it possible that writing a blob to IndexedDB could have the same problem?

**Comment by shortercode** [comment] 2019-06-07 11:34
Well there's kind of 3 points of failure I can see here:
1. The Blob backing object is missing when saved to indexeddb - results in corrupted blob being saved in DB
2. The Blob is corrupted on disk at some point before we read it
3. The Blob backing object goes missing sometime after we get it from the DB

I would hope the first and second are already checked by the browser. The third is the most likely I think, but all 3 come under a class of hard to reproduce browser bugs in my book.

I've come up with what I think is a fairly simple fix here which should workaround it. Before I read all the blobs out of the database simultaneously and added them straight to the filemap, so we didn't find out until creating the ZIP archive that there was a problem. Now I get the blobs one at a time and immediately copy them ( which verifies if they can be read ). If it can't be read... then there's not much that can be done, so I've elected to just skip that blob.

If the issue is caused by the 3rd point of failure then there's a chance that valid files might be skipped due to the browser freeing blobs before they should be... I could implement a retry mechanism, but it would add complexity and doesn't guarantee to solve the problem.

**Comment by shortercode** [comment] 2019-06-07 16:32
I've merged in that change, but I'm reluctant to close this immediately. As we don't really know the circumstances it's a best guess fix. @SnipG if you could take a look after the next release that would be appreciated.

**Comment by AshleyScirra** [comment] 2019-06-10 14:22
r153 is now out, please check again!

**Comment by SnipG** [comment] 2019-06-10 23:22
Pc that had thous saves failed, so it takes sometime before i can test again.

**Comment by shortercode** [comment] 2019-06-13 15:29
Mmm well if the PC failed that is perhaps why it failed to read that file, unfortunate timing...

**Comment by SnipG** [comment] 2019-06-13 18:36
Putted in some effort to get them faster, but i got them: It work in r153 and skips one blob that fails.
![skip](https://user-images.githubusercontent.com/28864889/59458305-d24ffb00-8e22-11e9-8399-2862d599d9db.jpg)

**Comment by shortercode** [comment] 2019-06-14 13:11
Ah well I guess that's good. Wish I knew why it was failing to read that blob though, very odd... Not sure there's much more I can do at this point.

How did you go about forcing this error? If I can reproduce it on my PC I might be able to figure out a bit more.

**Comment by SnipG** [comment] 2019-06-14 16:44
Well i zipped my indexedDB Construct3 folders, where i send download link when i get it uploaded?

**Comment by shortercode** [comment] 2019-06-17 14:18
If your happy for me to look at your browser saves then you can send the zip file to iain@scirra.com

I will of course delete them after I have looked at them.

**Closed** 2019-06-18 13:44 UTC
Labels: need info
