### ISSUE TITLE
(Multiplayer) Problem rejoining a room as a host after the old host leaves

### ISSUE THREAD

**Issue by Lobo93** [Scirra/Construct-3-bugs#2273] opened 2018-11-07 13:15 UTC
## Problem description

Not sure if really a bug or if I'm doing something wrong.

Scenario: A host and a peer are in the same room. Both can send messages to each other.
The host leaves, then the peer rejoins the room and becomes the new host.
A new peer join this room. Now the peer can send messages to the new host, but the messages sent form the host won't reach the peer. 

## Attach a .c3p

[Host swap.zip](https://github.com/Scirra/Construct-3-bugs/files/2557453/Host.swap.zip)

## Steps to reproduce

1. Use the remote preview
2. Open an instance of the project (join as host)
3. Open a second instance of the project (join as peer)
4. Send messages between the instances
5. Disconnect from the first instance (the peer form the second instance now becomes the new host)
6. Open a third instance of the project (join as peer)
7. Send messages between the instances

## Observed result

After the host swap, messages from the host won't reach the peer

## Expected result

Messages would go both ways

## Affected browsers

* Chrome: yes (both desktop and mobile)
* Firefox: yes
* Edge: not tested
* Safari: not tested

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r124 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 58 gb
Storage usage (approx): 433 mb (0.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

(Again, sorry if it's not a bug, I'm really new to the multiplayer object)

**Comment by AshleyScirra** [comment] 2018-11-07 14:00
If you look in the browser console, the remaining peer crashes in step 5, which is why the later steps don't work. Should be fixed in the next build. You didn't mention it but based on the project settings I assume this is specific to the C3 runtime and did not reproduce in the C2 runtime?

When dealing with multiplayer it's also virtually impossible to tell what's really going on unless you visibly display key information - at least the peer/host state, and any join/leave/kick/connect/disconnect/error events. Otherwise you can only guess at what's happening instead of seeing it. This would probably have made the problem more obvious as well since you were using a crashed peer for the last couple of steps and had no way of telling.

**Closed by AshleyScirra** 2018-11-07 14:00 UTC
Labels: c3runtime
