### ISSUE TITLE
Error loading r122 

### ISSUE THREAD

**Issue by NoSoul8** [Scirra/Construct-3-bugs#2189] opened 2018-10-26 06:37 UTC
## Problem description

R122 fails to start on the first attempt for some reason. It fails first, throws an error after page refresh. After another refresh it works ok.

## Attach a .c3p

Not needed

## Steps to reproduce

1. go to https://www.construct.net/en/make-games/releases/beta/r122
2. click Launch r122
3. on warnings/error refresh browser page

## Observed result

Editor failed to load and crashed
![r122error](https://user-images.githubusercontent.com/34763413/47548712-e7ffc700-d90a-11e8-8ab4-f1122c4def61.PNG)

## Expected result

Editor runs as usual

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃsl' of null @ TypeError: Cannot read property 'ǃsl' of null at window.ǃbAe.ǃbnT (https://editor.construct.net/r122/components/misc/userAccount/userAccount.js:1:1342) at ǃn.ǃYa.addEventListener (https://editor.construct.net/r122/components/misc/userAccount/userAccount.js:1:5767) at Object.n.push.ǃn.ǃqm [as ǃbSs] (https://editor.construct.net/r122/main.js:2:205011) at t (https://editor.construct.net/r122/main.js:2:208014) at n (https://editor.construct.net/r122/main.js:2:207799)
Stack: TypeError: Cannot read property 'ǃsl' of null at window.ǃbAe.ǃbnT (https://editor.construct.net/r122/components/misc/userAccount/userAccount.js:1:1342) at ǃn.ǃYa.addEventListener (https://editor.construct.net/r122/components/misc/userAccount/userAccount.js:1:5767) at Object.n.push.ǃn.ǃqm [as ǃbSs] (https://editor.construct.net/r122/main.js:2:205011) at t (https://editor.construct.net/r122/main.js:2:208014) at n (https://editor.construct.net/r122/main.js:2:207799)
Construct 3 version: r122
URL: https://editor.construct.net/r122/
Date: Fri Oct 26 2018 10:26:35 GMT+0400 (Грузия, стандартное время)
Uptime: 5.4 s

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r122 (beta)
Language setting: en-US

WebGL information
Failed to create WebGL renderer. Try installing any available software updates.

</details>

**Comment by AshleyScirra** [comment] 2018-10-26 10:57
I've seen this sporadically but just always assumed it was some network fetches randomly failing. I just tried again though and it just failed in a similar way again. Checking dev tools it looks like Chrome is randomly cancelling cascades of fetch events. I've no idea why. I've never seen it occur in Firefox or Edge (I assume you have not been able to reproduce it there either?) so I filed a Chrome issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=899196
Closing as will follow up there. The work-around seems to be just try reloading a couple of times and it seems to eventually load successfully.

**Closed by AshleyScirra** 2018-10-26 10:57 UTC
Labels: chrome, external
