### ISSUE TITLE
False positive javascript in Remote Preview r152

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-3-bugs#3021] opened 2019-06-06 20:45 UTC
## Problem description

Im getting this issue when trying to preview my project, but i dont have any javascript.

## Attach a .c3p

![imagen](https://user-images.githubusercontent.com/6506303/59065281-b7a9df00-8882-11e9-9950-1ea966b31c80.png)

## Observed result

this popup when trying to remote preview in a project with no javascript code

## Expected result

just to preview

## More details

**First affected release:** r152

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2019-06-07 11:07
I can't reproduce remote previewing a new blank project. No project was provided so further investigation not possible, so closing.

I would guess this is just a caching issue - we updated the server-side remote preview code a couple of weeks ago for scripting. Try clearing your cache.

**Closed by AshleyScirra** 2019-06-07 11:07 UTC
Labels: can't reproduce
