### ISSUE TITLE
Strange behavior of "Darkness"-Layer in KiwiStory example

### ISSUE THREAD

**Issue by stetso** [Scirra/Construct-3-bugs#413] opened 2017-06-01 15:22 UTC
## Problem description

*Parallax effect of Darkness-Layer in KiwiStory (editor) - disappears when resizing editor window*

## Attach a .c3p

*Well, I guess everyone has it already :-)*

## Steps to reproduce

1. go to the KiwiStory - 2-cave layer 
2. scroll around - the Darkness layer is huge and moves with parallax effect
3. resize the sidebars (or the window size, just make the editor area bigger), at some point the layer snaps to how it should look 

## Observed result

*Parallax movement and wrong display of layer that is actually smaller and should not have parallax*

## Expected result

*Correct size and no parallax effect (as visible in larger editor area)*

## Affected browsers

* Chrome: yes
* Firefox: did not try
* Edge: did not try
* Safari: did not try

## System details

*Mac OS Sierra 10.12.5, Chrome 58.0.3029.110 (64-bit), Construct 3 r33*

GIF attached
![kiwistory_parallax_bug](https://cloud.githubusercontent.com/assets/23641211/26686778/4c55f068-46ee-11e7-984d-fcedb94b4e6c.gif)

**Comment by AshleyScirra** [comment] 2017-06-02 12:53
Can't reproduce on Windows. Might be a driver-related issue, #294 looks like another case of a macOS graphics glitch.

**Comment by AshleyScirra** [comment] 2017-06-02 15:56
Actually yes, can reproduce on macOS. Doesn't seem related to the particles bug, since that should be fixed now and it still reproduces.

**Comment by AshleyScirra** [comment] 2017-06-02 16:16
OK, this one does look like a driver bug. I found a straightforward workaround though. Should be fixed in r35.

**Closed by AshleyScirra** 2017-06-02 16:16 UTC
