### ISSUE TITLE
Impossible to import sounds in the desktop build

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#1787] opened 2018-07-10 21:21 UTC
## Problem description

No sounds can be imported on the desktop build.

## Attach a .c3p

not relevant

## Steps to reproduce

1. Open a new project and import a sound in .wav format
2. IN C2 and C3 browser-based, the sound is imported.
3. On the desktop build, it fails every time. Encoding displays "Queued" for half a second, then "Failed".

## Observed result

The sound is not imported

## Expected result

The sound should be correctly imported

## Affected browsers

Desktop build only.

**Comment by alastajj** [comment] 2018-07-11 02:02
Duplicate of #1781

**Comment by shortercode** [comment] 2018-07-11 10:42
@alastajj beat me to it!

**Comment by AshleyScirra** [comment] 2018-07-17 12:42
r109 is out now, can you check it works correctly now @RabloGames ?

**Comment by alastajj** [comment] 2018-07-18 05:04
It's working now, thanks!

**Comment by alastajj** [comment] 2018-07-18 05:05
@AshleyScirra  It's working now, thanks!

**Comment by RabloGames** [comment] 2018-07-18 06:52
@AshleyScirra Yes, I can confirm it's working fine! Thanks!

**Comment by AshleyScirra** [comment] 2018-07-18 09:05
Thanks for confirming!

**Closed by AshleyScirra** 2018-07-18 09:05 UTC
