### ISSUE TITLE
Text alignment - wrong position on IOS

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-3-bugs#4853] opened 2021-05-26 02:15 UTC
## Problem description

When I preview my projects (with remote preview) on iPhone, texts have wrong position and makes apps looking extremely weird.

I made a minimal project to reproduce the issue, included text with top, center and bottom vertical alignment, with bbcode enabled and disabled.

## Attach a .c3p

[TextAlignmentIOS.zip](https://github.com/Scirra/Construct-3-bugs/files/6543323/TextAlignmentIOS.zip)

## Steps to reproduce

1. Open attached project
2. Select remote preview 
3. Run it on iPhone

## Observed result

Text have wrong vertical position compared with the original project. 

## Expected result

Text should have same position as windows or android

## More details

![Windows](https://user-images.githubusercontent.com/53188782/119592354-fe32d400-bde0-11eb-8810-96087d76241c.jpg)

![IOS (iPhone, Safari)](https://user-images.githubusercontent.com/53188782/119592374-0854d280-bde1-11eb-9f17-7d76fb7c5922.jpg)

**Affected browsers/platforms:** Safari

**First affected release:** Don't know...

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 90.0.4430.212
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
C3 release: r249 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 269 gb
Storage usage (approx): 1 gb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce G105M Direct3D11 vs_4_1 ps_4_1, D3D11-9.18.13.4195)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2021-05-26 10:40
What version of iOS is it? The required text metrics needed to calculate correct vertical positioning are only supported on fairly recent iOS versions IIRC.

**Comment by Dramamini** [comment] 2021-05-27 00:04
Tested on 12.5.2 and 12.5.3

**Comment by AshleyScirra** [comment] 2021-05-27 11:02
Does it reproduce on iOS 14?

**Comment by AshleyScirra** [comment] 2021-05-27 15:36
I can reproduce a slight difference on iOS 14. Here's a clearer repro: 
[issue4853.zip](https://github.com/Scirra/Construct-3-bugs/files/6555170/issue4853.zip)

It looks like r241 had a similar slight offset, so it doesn't appear to be a regression.

Urgh, this vertical text alignment issue has proven a total nightmare to get right. I'm starting to wonder if it's even possible. I think Safari and Chrome just calculate text positions differently so it might not be possible to get it right...

**Comment by Dramamini** [comment] 2021-05-27 22:45
Ashley I think I have found a light in the dark. Text input has perfect vertical alignment on all devices, ios, android or windows. Don't know if this can help you to solve this mystery.. 
Repro: [Tex&TextInput.zip](https://github.com/Scirra/Construct-3-bugs/files/6557144/Tex.TextInput.zip)

A screenshot comparing text and text input across platforms:
![Text TextInput](https://user-images.githubusercontent.com/53188782/119905890-bf725a80-bf55-11eb-95ce-de9fdbf5f131.jpg)

**Comment by AshleyScirra** [comment] 2021-05-28 12:58
I'm aware that text vertical alignment works correctly in HTML. In Construct we have to write our own text layout engine for rendering to a canvas though, using some limited features that are inconsistent across browsers, which makes it very difficult to get right.

I think the problem is that Chrome and Safari have different ideas of where the "top" text baseline is. We have to use the "top" baseline when calculating how to vertically center text. So unfortunately this means the difference in center vertical alignment comes from the browsers having different ideas of where this baseline really is, rather than anything Construct is doing. Further, I don't believe it's possible to calculate the difference based on the available browser APIs like TextMetrics, so we can't work around it either.

I'm not sure which browser is correct so I filed issues with both Chrome ([1213949](https://bugs.chromium.org/p/chromium/issues/detail?id=1213949)) and Safari ([226334](https://bugs.webkit.org/show_bug.cgi?id=226334)). I don't believe it's possible for us to do anything further at this point, so closing this issue as we will follow up with the browser bug reports.

**Closed by AshleyScirra** 2021-05-28 12:58 UTC
Labels: browser, difficult, external
