### ISSUE TITLE
r36 Cancel export dialog crashes C3

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#465] opened 2017-06-08 14:20 UTC
## Problem description

just open a new blank project (same with a game), click export, then cancel > crash

## Attach a .c3p

---

## Steps to reproduce

1. open new project
2. export
3. cancel export window (cancel button)

## Observed result

crash report

## Expected result

no crash, just window closing

## Affected browsers
Chrome editor

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot set property 'tag' of null @ TypeError: Cannot set property 'tag' of null at g.ǃwt.then.then.then (https://editor.construct.net/r36/main.js:71:11082) at 
Stack: TypeError: Cannot set property 'tag' of null at g.ǃwt.then.then.then (https://editor.construct.net/r36/main.js:71:11082) at 
Construct 3 version: r36
URL: https://editor.construct.net/index.html
Date: Thu Jun 08 2017 16:19:11 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 12.4 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2017-06-08 15:11
Duplicate of #461, already fixed for next build.

**Comment by AshleyScirra** [comment] 2017-06-08 15:12
Actually going to leave this open until we release r37 to try to avoid further duplicates.

**Closed** 2017-06-12 13:38 UTC
Labels: duplicate
