### ISSUE TITLE
Webm videos are upside down if worker mode is set to No

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#4869] opened 2021-06-03 12:11 UTC
## Problem description

This one is wild :D 

I have tested on both Chrome and Firefox, but basically, if you use a webm video and worker mode is set to No, the video will play flipped upside down.

## Attach a .c3p

Video is too big to attach to github, and I'd rather not mess with the video in case this is due to some metadata stuff or any other issue that would just vanish if I edited the video
https://mega.nz/file/UpFEjBJZ#5I6y5k-DD9Sheja579T5nSsd8QyDPp0Hny6caockm4s

## Steps to reproduce

1. Preview
2. Switch Worker mode
3. Preview again

## Observed result

Video is flipped upside down

## Expected result

Video does not flip upside down :D 

## More details

**Affected browsers/platforms:** Chrome Firefox, didn't test more

**First affected release:** Could repro on both 241, 249 and 250, I have no idea how far back this goes, but this was 100% not an issue a few months ago

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2021-06-03 16:23
It looks fine to me in Chrome with r250 with worker mode both on and off. So it seems fine to me.

For some reason the video doesn't seem to play for me in Firefox. I don't know why or if that's related, it doesn't seem to log any error.

The video has a very strange name - `function newpath() {}` - possibly some mistake? I doubt it's related though (unless the weird name is why Firefox can't play it).

**Comment by skymen** [comment] 2021-06-03 16:26
Yeah the strange name is just some reference to functions syntax, I doubt it's the cause of the issue too.

I might need to specify I'm on Windows 10, with Chrome 91.0.4472.77 64 bits with hardware acceleration on.

Also, the webm has an alpha channel, which is why Firefox might have troubles playing it?

**Comment by AshleyScirra** [comment] 2021-06-21 08:38
I've tried this on two Windows machines and an Android device and it appears the right way up on all of them. So it sounds like the issue is specific to just your device, which is a further signal that it may be a graphics driver issue. I think videos with alpha are still a somewhat exotic format, so it seems likely that it's less well tested and the driver might be mis-handling the video data when it has alpha. It probably also explains why Firefox can't play it (presumably it does not support videos with alpha yet).

I don't think there's anything we can do about this, so closing. You could try filing it with Google at crbug.com in case they can figure it out. They'd probably need full system details to track down any potential graphics driver issues.

**Closed by AshleyScirra** 2021-06-21 08:38 UTC
Labels: can't reproduce
