### ISSUE TITLE
Can't download images. r135.2

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#2542] opened 2019-01-24 06:50 UTC
## Problem description

Can't download images. r135.2

## Steps to reproduce

1. Try to download an image in the image editor.

## Observed result

Nothing.

## Expected result

Should download the image.

## First affected release

r135.2

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r135.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 54 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 755M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by Ind1eed** [comment] 2019-01-24 16:45
Just observed the issue appears in the stable as well. (r131). Just created blank project with a few layers and trying to import PNG images,

**Comment by DiegoScirra** [comment] 2019-01-25 11:02
@bilgekaan Have you checked that **"Automatic Downloads"** chrome setting is turned on or off?

@Ind1eed Is this drag and drop in the Animations Editor or the Layout? Or maybe both?

**Comment by Ind1eed** [comment] 2019-01-25 11:52
I tested drag and drop in the layout view.

Pt., 25 sty 2019, 12:02: DiegoScirra <notifications@github.com> napisał(a):

**Comment by AshleyScirra** [comment] 2019-01-25 14:05
Also works fine for me. IIRC Chrome recently merged some popup blocking and downloading logic - if you have popups blocked for Construct 3 it might also block downloads. Perhaps that's the problem?

**Comment by Ind1eed** [comment] 2019-01-25 14:47
I enabled popups, still doesn't work.

pt., 25 sty 2019 o 15:05 Ashley (Scirra) <notifications@github.com>
napisał(a):

**Comment by AshleyScirra** [comment] 2019-01-25 15:19
That doesn't make any sense - I'm sure the image content has nothing to do with whether you can download it...

**Comment by Ind1eed** [comment] 2019-01-25 15:21
But the problem is that you can"t download it.

Pt., 25 sty 2019, 16:19: Ashley (Scirra) <notifications@github.com>
napisał(a):

**Comment by bilgekaan** [comment] 2019-01-25 15:52
My bad, it works fine. I don't know why but I press the image format to download it instead of the save icon. :D Sorry to waste your time, I will be more careful next time.

**Comment by DiegoScirra** [comment] 2019-01-25 15:53
Ok then. Going to close this.

**Closed by DiegoScirra** 2019-01-25 15:53 UTC
Labels: can't reproduce
