### ISSUE TITLE
C3 Desktop build, get error after login time expired

### ISSUE THREAD

**Issue by redfoc** [Scirra/Construct-3-bugs#2107] opened 2018-10-06 03:13 UTC
## Problem description

I not open my C3 desktop build version more than 7 days. after i open it, i get this error. so, i can't re-login or do something with my project.

## Steps to reproduce

1.
2.
3.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

Error report information
Type: unhandled rejection
Reason: Error: expected function @ TypeError: expected function at Function.ǃv.ǃdv (https://editor.construct.net/r120/main.js:2:110544) at Function.ǃv.ǃNm (https://editor.construct.net/r120/main.js:2:142951) at a.ǃDG (https://editor.construct.net/r120/main.js:81:33447) at Object.n.push.ǃv.ǃcS [as ǃVHi] (https://editor.construct.net/r120/main.js:81:33837) at n (https://editor.construct.net/r120/main.js:2:205661) at t (https://editor.construct.net/r120/main.js:2:205446)
Stack: TypeError: expected function at Function.ǃv.ǃdv (https://editor.construct.net/r120/main.js:2:110544) at Function.ǃv.ǃNm (https://editor.construct.net/r120/main.js:2:142951) at a.ǃDG (https://editor.construct.net/r120/main.js:81:33447) at Object.n.push.ǃv.ǃcS [as ǃVHi] (https://editor.construct.net/r120/main.js:81:33837) at n (https://editor.construct.net/r120/main.js:2:205661) at t (https://editor.construct.net/r120/main.js:2:205446)
Construct 3 version: r120
URL: https://editor.construct.net/
Date: Sat Oct 06 2018 10:05:51 GMT+0700 (Indochina Time)
Uptime: 4.5 s

Platform information
Browser: NW.js
Browser version: 0.33.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@8920e690dd011895672947112477d10d5c8afb09) NWjs/0.33.3 (like Chrome/69.0.3497.100)
C3 release: r120 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon(TM) R7 200 Series Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment] 2018-10-08 12:38
This doesn't look related to using Construct offline at all. It does not attempt to access your account until it has finished loading, so a crash on startup is probably not related to the account. Additionally the crash message appears to be because it failed to load an addon, which isn't anything to do with your account either.

Have you installed any content blocking browser extensions like ad or tracking blocking? This might be preventing Construct from loading some resources. Can you also open the browser console (press F12 to open it) and check for any errors there?

**Comment by redfoc** [comment] 2018-10-08 12:45
Hi Ashley.

Today, i can get access to my Construct 3 again. I don't know why, even though yesterday i was still get an error.

So, i get this error for unknown bugs, and also get fixed for unknown reason.

Note: i not install or remove any addons, change system settings or clear something, since before get this error until today.

**Comment by AshleyScirra** [comment] 2018-10-08 13:06
We have a mitigation for the particular kind of error in the crash report for the next release. Since it cannot be reproduced any more I'm going to close this issue, but please file it again if you encounter it again after the next release, and be sure to press F12 and see if there are any more error messages you can find - those might help figure out what's going on.

**Closed by AshleyScirra** 2018-10-08 13:06 UTC
Labels: can't reproduce, need info
