### ISSUE TITLE
Undo doesnt affect resized object

### ISSUE THREAD

**Issue by Mak14** [Scirra/Construct-3-bugs#2675] opened 2019-03-02 19:07 UTC
## Problem description

Hi, i found such issue. in r139 release.
When i'm resizing sprite on the scene, for example the width of the sprite, it's X position is also moving to the cursor direction ( which is okay), but if i press undo ( ctrl+z) after that, the size of the sprite is not changing to it's origin state. 
I see that the sprite is just moving to it's origin point before the action, but the shape is not undoing.
Stable version r136 works fine in Firefox ( can't test in in chrome since i'm working with 139 there)

## Attach a .c3p
 
This happens in any project
 Even with a single sprite.

## Steps to reproduce

1. Open C3
2. Create new sprite, remember it's origin point.
3. Drag one of the tranfsormation points to the right  
4. Press Ctrl+z or Undo button

## Observed result

Sprite is moved to it's origin point, but the shape of the sprite hasn't  restored to the original state.

## Expected result

Expecting the sprite shape become like it was before the transformation

## More details
It's also happens when you edit the shape holding down ctrl btn.
Tiled background objects works good, and the shape is undoing

**Affected browsers/platforms:** Tested in Chrome and Firefox r139

**First affected release:** r139

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.119
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
C3 release: r139 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 3.8 gb
Storage usage (approx): 407 mb (10.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 7800 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2019-03-04 10:51
Duplicate of #2660. Fixed in the next release

**Closed by DiegoScirra** 2019-03-04 10:51 UTC
