### ISSUE TITLE
Find results minor bug

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#1990] opened 2018-09-04 15:47 UTC
## Problem description

When you try to click on one of the results of the match list, you have to click on where the text is for C3 to to direct to that line of event. This bug only applies to the "Match" column.

## Steps to reproduce

Pretty much self explanatory.

## Observed result

Can't click on blank spaces.

## Expected result

Able to click on blank spaces and still register that particular row.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 68.0.3440.106
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
C3 release: r115 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.8 gb
Storage usage (approx): 362 mb (4.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 765M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2018-09-04 16:41
This only reproduces when the results bar can scroll horizontally. Actual steps to reproduce:

1. Open Ghost Shooter
2. Right-click Player and choose 'Find all references'
3. Ensure find results bar has horizontal scrolling - if necessary expand the 'icon' column to be really wide
4. Scroll bar all the way to the right
5. Double-click the right edge of a result, past the end of the text.

If you inspect the last cell, it has some weird layout to handle the scrolling involving using 100% width (which will take the size of the scroll container, and not fill up the full width), and then adding padding to extend it further (which does not extend the content size, so the last cell does layout at a minimum size to try to avoid overflow, rather than using all available space). This is a problem with the table control which Diego wrote so assigning to him - looks like a bunch of styles need to be refactored to properly handle scrolling.

**Comment by DiegoScirra** [comment] 2018-10-17 14:33
Fixed in the next release

**Closed by DiegoScirra** 2018-10-17 14:33 UTC
