### ISSUE TITLE
App still runs on background on Android device.

### ISSUE THREAD

**Issue by angelo-lopez** [Scirra/Construct-3-bugs#751] opened 2017-08-25 12:30 UTC
## Problem description

The game that I am testing on an Android device (exported to Cordova/Android and built with Cordova CLI) continues to run even in the background. Pressing the back or home button and answering calls does not put the game on pause. I've tested this on a Nexus, Samsung and HTC phones with same results. This happens with or without the Browser object. 

## Attach a .c3p
[TestProject.zip](https://github.com/Scirra/Construct-3-bugs/files/1251722/TestProject.zip)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Export project with Cordova/Android.
2. Build APK with Cordova CLI
3. Transfer apk to an Android phone/device.
4. Install apk.
5. Run app.
6. Now try the following: a) hit the home button. b) hit the back button. c) accept incoming phone call

## Observed result

The app continues to run in the background.

## Expected result

The app should be paused or suspended.

## Affected browsers

* Chrome: Yes. Game has paused but audio is still playing
* Firefox: Not tested.
* Edge: Not tested.
* Safari: Not tested.

## Affected mobile device

* Nexus 5
* HTC One M8
* Samsung A5
* Samsung J3
* Hudl2

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment] 2017-08-25 14:45
I think this is caused by [KeepRunning](https://cordova.apache.org/docs/en/latest/config_ref/) in the cordova config. Although I'm not familiar with our bindings for app suspension and restoration so I'll need to check if there's anything odd in there

**Comment by angelo-lopez** [comment] 2017-08-25 14:48
Thanks Iain.

**Comment by angelo-lopez** [comment] 2017-08-25 15:06
I just checked the config.xml file and it doesn't have any entry for KeepRunning. The Cordova documentation states that the default is set to true. I'll try tonight and add an entry for KeepRunning and set it to false and see what happens.

**Comment by drexegar** [comment] 2017-08-25 15:33
Hey Angelo-lopez good luck, I've been dealing with this problem for a while too. I interested to see what you find under the Cordova Hood.

**Comment by shortercode** [comment] 2017-08-25 15:41
Let me know how you get on, if it does solve the issue for you then we can look into adding it either as the default or as a project setting for the next release ( presuming that it's an easy addition )

**Comment by drexegar** [comment] 2017-08-27 19:21
It seems that browser options do not work (maybe its just android) but also "Pause on unfocus" in the properties manager doesn't work either.

**- App does stop running when in the background for me except the music continues
- If I turn off the screen while playing the app, both the app and music both continue while screen is off**


**A quick fix to stop the app from running while the screen is off is by adding:

<preference name="KeepRunning" value="false" />

to the "config.xml"**

I did it in android studio but manually should be fine too.

So the only problem left is the music that keeps running in the background on android.

**Comment by angelo-lopez** [comment] 2017-08-28 10:24
@shortercode: 
Adding the "KeepRunning" preference to config.xml file did nothing to pause the app in the background. Setting it to "false" or "true" didn't seem to make any difference. I've modified the MainActivity.java and overriden the onPause() method to call it's superclass implementation. But no luck in that as well. The one thing that almost worked for me was to attach the onPause event listener in the deviceready event. I've added an alert function that would pause the game when it goes into the background. An alert dialog would be visible to the user when the game goes back into the foreground asking the user if he/she would like to continue. The problem is that the music kept playing even when the game was on the background. I don't particularly like alert dialogs in a mobile application, plus the fact that it ruins the feel and motif of the game even if you customise the alert dialog with navigator.notification.alert.

//Here's how I've managed to pause the game:
(function() {
	document.addEventListener("deviceready", function ()
	{
		document.addEventListener("pause", onPause, false);
		window.cr_createRuntime({
			exportType: "cordova"
		});

	}, false);

	function onPause() {
		alert("Press OK to continue playing...");
	}
})();

Problem is that the music kept running in the background.

I've tried the Construct 3 debug apk export option and the game goes into pause with no problem. But I've encountered the same issue of the music that stays running in the background.

@drexegar:
Maybe this will help with the music problem:
Phonegap provides the "media" object. Some of the functions that it exposes are:

1. media.play (Start or resume playing an audio file)

2. media.pause (Pause playback of an audio file)

Maybe they can be implemented inside ondeviceready with the onPause and onResume events?

**Comment by drexegar** [comment] 2017-08-28 10:45
That's weird!!! That "KeepRunning" on false works for me, without it, my game stops in the background normally when into menu or switch apps, but when I turn off the screen **during gameplay** the characters keep fighting while the screen is off!

Ill run some test with your ideas, thank you so much for the reply.

**Comment by angelo-lopez** [comment] 2017-08-28 11:25
@drexegar 
start.js file in www folder.

**Comment by drexegar** [comment] 2017-08-28 15:54
Thanks for your help i will try it out after work and will keep you posted.

**Comment by drexegar** [comment] 2017-08-29 13:17
Too be honest I don't even no where to begin, I also notice your solution from earlier keep the video from stopping, I have no idea why your app keeps running in the background but with my "false" line my app stops running when the screen is off, but this also disable any abilities for the music to be stop. I'm going to post more bugs to construct with a file because none of these solutions are stable.

**Comment by AshleyScirra** [comment] 2017-08-29 15:28
@shortercode - the runtime uses page visibility API events (IIRC) to suspend and resume the runtime, perhaps those aren't being triggered in Cordova. I just checked C2's code and it does add "pause" and "resume" events on document for Cordova, which I guess are the cordova equivalents (don't know why they reinvented that wheel), and it looks like those calls were lost along the way in the port to C3, so maybe we just need to add those events back in.

**Comment by drexegar** [comment] 2017-08-29 15:32
Ahhh ok cool! Look forward to that fix.

**Comment by angelo-lopez** [comment] 2017-08-29 16:16
Awesome!!!

**Comment by AshleyScirra** [comment] 2017-08-31 09:56
Well, it turns out the page visibility API events that the C2 runtime uses were, um, somehow deleted along the way to moving to C3. So in C3 it actually makes no effort to suspend the runtime on any platform! I've added the events back in for r52 and they look like they work in apps as well, so this ought to be fixed by then, but it'll be worth double-checking on your end.

**Comment by AshleyScirra** [comment] 2017-08-31 11:11
r52 is out, can you check if it's working for you now?

**Comment by drexegar** [comment] 2017-08-31 11:36
Just woke up will test now before I head out, will give results in about 6 min

**Comment by drexegar** [comment] 2017-08-31 11:47
Ok so here are the results:

**1. Everything Stops when app goes into the background (both music and the app)
So that works great!**

**2. However... All these actions gets ignored when the power button is pressed, and the game fully runs in the background with music and actions intact while the screen is off.**

**Comment by AshleyScirra** [comment] 2017-08-31 12:21
Some phones actually leave the device on for a while (maybe up to 30 seconds) after hitting the power button, so if you wake it again it can wake up quickly. Does it properly suspend if you wait longer?

**Comment by angelo-lopez** [comment] 2017-08-31 12:41
I'm working at the moment, and won't be able to check my project until later this evening. I'll do some tests as soon as I get home. Thanks for addressing this issue Ashley.

**Comment by drexegar** [comment] 2017-08-31 12:51
The app fully runs constantly in the background, i test it for 3 min with the screen off and still running.

**Comment by AshleyScirra** [comment] 2017-08-31 14:01
Will take another look, thanks for testing.

**Comment by angelo-lopez** [comment] 2017-08-31 22:54
I had the same results as drexegar after updating to r52.  Using the "debug apk" export option, gameplay and sound would pause when game is interrupted (pressing the home button or when another app goes into the foreground). However, both gameplay and sound continues to run in the background when the screen is off.

**Comment by AshleyScirra** [comment] 2017-09-01 10:21
OK, added back the Cordova-specific events for the next build, let's see if that sorts it.

**Comment by AshleyScirra** [comment] 2017-09-01 12:12
OK, r53 is out, let me know if that works better!

**Comment by angelo-lopez** [comment] 2017-09-01 13:10
Thank you so much Ashley and to the rest of your team!!! The game now properly suspends when interrupted (ie. when pressing the home button, another app goes into foreground and when pressing the power button). Both gameplay, music and sfx are being suspended. I've used the "debug apk" export option. You have made my day.

Hey drexegar, this is great news!!!

**Comment by AshleyScirra** [comment] 2017-09-01 14:33
Great, thanks for confirming!

**Closed by AshleyScirra** 2017-09-01 14:33 UTC
Labels: check next release
