### ISSUE TITLE
Opacity and effects adjustments leading to an "Assertion Failure" in the editor.

### ISSUE THREAD

**Issue by AnarchyPlexian** [Scirra/Construct-3-bugs#1351] opened 2018-03-08 07:50 UTC
## Problem description

I tried to get two layers' effects to render in the editor, but they fail because of possibly some sort of opacity and effect blending issue.

## Attach a .c3p

[ABHG.zip](https://github.com/Scirra/Construct-3-bugs/files/1792070/ABHG.zip)

## Steps to reproduce

1. Make one layer with Tint effect.
2. Add another layer above it and add a sprite with the Darken effect.
3. Adjust the sprite's opacity below 100%, then set the layout's "Show Translucent Inactive Layers" to true.

(Although the same issue did happen with a few other effects, like Adjust HSL and Softlight.)

## Observed result

An assertion failure message came up.

## Expected result

I've expected both layers and objects to just render and blend with each other.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: Warning: setting texture1 to current render texture
Stack: Error at Function.ǃr.ǃUCn (https://editor.construct.net/r89/main.js:2:206736) at r (https://editor.construct.net/r89/main.js:2:174060) at window.assert (https://editor.construct.net/r89/main.js:2:174460) at ǃr.ǃzw.ǃUrK.ǃUTm (https://editor.construct.net/r89/main.js:63:46105) at r (https://editor.construct.net/r89/components/editors/layoutView/layoutView.js:1:40241) at Function.ǃr.ǃUrN (https://editor.construct.net/r89/components/editors/layoutView/layoutView.js:1:41471) at o.ǃTvI (https://editor.construct.net/r89/main.js:63:278398) at o.ǃLI (https://editor.construct.net/r89/main.js:63:277527) at d.ǃLI (https://editor.construct.net/r89/main.js:63:261795) at window.ǃaL.ǃwJ (https://editor.construct.net/r89/components/editors/layoutView/layoutView.js:1:7190)
Construct 3 version: r89
URL: https://editor.construct.net/index.html
Date: Wed Mar 07 2018 23:29:18 GMT-0800 (Pacific Standard Time)
Uptime: 231.6 s

Platform information
Browser: Chrome
Browser version: 64.0.3282.186
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
C3 release: r89 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 8400 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

Construct 3 version: r89

**Comment by AshleyScirra** [comment] 2018-03-12 14:22
Please don't include how to build the project you provided in the steps to reproduce. It took me a while to figure out the real steps to reproduce: just make both layers in the project visible.

**Comment by AshleyScirra** [comment] 2018-04-05 11:30
I can't reproduce this in my local dev copy, so it might be fixed in the next release. Otherwise it might be a production-only bug which would suggest a minifier bug, which would be difficult...

**Comment by AshleyScirra** [comment] 2018-04-23 10:48
Can you verify if this is still an issue?

**Comment by AshleyScirra** [comment] 2018-06-29 12:33
No response after 2 months so closing.

**Closed by AshleyScirra** 2018-06-29 12:33 UTC
Labels: need info
