### ISSUE TITLE
Android games vibrate upon touching for few seconds

### ISSUE THREAD

**Issue by cmr333** [Scirra/Construct-3-bugs#1212] opened 2018-01-18 18:44 UTC
## Problem description

When I test my games on Android, the phone vibrates when my finger is on anywhere on the screen for 1 second, however the vibrate doesn't happen if it detects two or more fingers at once.

## Attach a .c3p

[Test Mobile.zip](https://github.com/Scirra/Construct-3-bugs/files/1644040/Test.Mobile.zip)

## Steps to reproduce

1. Create new project
2. Type ID/desc
3. Export to Android (debug apk)
4. Install on Android
5. Run game on Android
6. Place finger anywhere for 1 second and it'll vibrate

## Observed result

Vibrates when pressing anywhere on the screen for 1 second

## Expected result

Nothing is supposed to happen since I don't have any form of vibration codes inside as far as construct 3 is concerned 

## Affected browsers

~

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r79
Language setting: en-US

Local storage
Storage quota (approx): 7.1 gb
Storage usage (approx): 409 mb (5.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2018-01-19 12:12
@shortercode any ideas why this might be happening?

**Comment by shortercode** [comment] 2018-01-19 12:35
Hmm well it sounds like some form of haptic feedback. The only hit I can find is [this](https://stackoverflow.com/questions/23245170/phonegap-how-can-i-prevent-the-beep-vibration-when-a-hold-touch-events-occu) My best guess is the browser thinks it's either selecting something, or opening a context menu.

**Comment by AshleyScirra** [comment] 2018-01-19 12:42
The runtime already blocks contextmenu events, it must be something else. Maybe it's one of those CSS styles.

**Comment by AshleyScirra** [comment] 2018-02-05 15:55
@shortercode do you mind taking this one on?

**Comment by shortercode** [comment] 2018-02-05 16:07
I can do, I haven't figured out quite what causes this but I'll give it a go if I can replicate it.

**Comment by AshleyScirra** [comment] 2018-03-05 16:20
This keeps being mentioned all over the place (e.g. [here](https://www.facebook.com/ConstructTeam/photos/a.436917163009977.87989.130477053653991/1602426429792372/?type=3&comment_id=1602459199789095&comment_tracking=%7B%22tn%22%3A%22R0%22%7D)). Would be good if this could get looked in to soonish.

**Comment by shortercode** [comment] 2018-03-05 17:28
While I can confirm that it happens, I haven't been able to find a way to disable it so far. Also remarkably hard to google, so much junk of people either trying to ADD vibration to apps or disable keyboard haptic feedback. Disabling "vibrate on tap" in the settings menu prevents it, but I'm still not sure of the source of the vibration so it's making it hard to backtrack.

I have tried the standard methods of preventDefault on various events, css rules like `user-select` , etc. With no luck. This also happens in chrome, so it's not cordova related. Supposedly you can disable vibration by view in Android but that doesn't help for chrome.

**Comment by shortercode** [comment] 2018-03-08 18:26
Should be fixed for r90.

**Comment by AshleyScirra** [comment] 2019-09-04 12:30
Looks like this has come back in r164. Reproduces just by previewing a new project on Android.

**Comment by AshleyScirra** [comment] 2019-09-04 12:45
So it looks like the fix for #3191 (working around a weird Safari quirk) in turn exposed a weird Android quirk which made this behavior come back. Fixed it by adjusting which events we block again (this has been a real game of whack-a-mole...) I think we'll have a .2 stable release out at some point to deal with an unrelated Physics bug and this fix will ship with that.

**Closed by AshleyScirra** 2019-09-04 12:45 UTC
