### ISSUE TITLE
can't use c3 without internet

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6128] opened 2022-09-23 15:45 UTC
## Problem description

today I had internet problems for a bit and still wanted to work on my projects.

## Observed result
c3 only showed a huge logo and the console errors:
Failed to load resource: net::ERR_FAILED
root-sw.js:399          
Uncaught (in promise) TypeError: Failed to fetch
    at HandleFetch (root-sw.js:399:36)
![cannot use c3 without internet](https://user-images.githubusercontent.com/89512047/191998775-2197a915-d81c-4434-bd9b-a1655dc1515d.png)

## Expected result
c3 is usable when offline

Chadori had some similar issues and paraphrasing this is what he said (I'm not 100% sure if it's the same issue):
"Found the issue, Construct 3's online dependencies are synchronous prerequisites to start the application as long as the WiFi  / LAN is on. If the Construct 3 services fails to load, the entire app fails.
Their analytics service stops the entire editor from loading if it fails.
I have no choice but to stop all internet connection tasks and turn off WiFi, just to load Construct 3."

**Comment by AshleyScirra** [comment] 2022-09-23 16:34
Whenever people file these issues it's usually because it didn't finish saving for use offline. Are you sure you waited for the "ready to use offline" message to appear? It could take a while to appear on slower connections. Try clearing your cache, loading Construct, waiting for the message to appear, then go offline and try again. Usually it works after that.

(Regarding what Chadori said that does not follow the design of Construct and it should certainly be able to start up without reaching the analytics or accounts services, or any other online dependency.)

**Comment by F3der1co** [comment] 2022-09-23 17:20
I'm pretty sure it was ready for offline use, as I worked the whole day on the same project. I just rebooted when the internet went down.
I'll try to find a repro.

**Comment by AshleyScirra** [comment] 2022-09-26 16:07
OK - this issue isn't actionable until we have steps to reproduce (which ought to involve a step of "wait for the ready to use offline notification"). So closing for now, but please file again if you can find steps to reproduce.

**Closed by AshleyScirra** 2022-09-26 16:07 UTC
Labels: no repro
