### ISSUE TITLE
Game runs 100% cpu under stable R111

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#1909] opened 2018-08-08 18:43 UTC
## Problem description

I recently came back to my main project having taken a break to work on something else and now i find under stable R111 the project runs at 100% cpu, the same project under stable R104 (which i was using) the game runs at 30% cpu. 

Something as obviously changed and makes R111 unusable for me.

I can't attach the file because its a commercial project, and since i dont know whats causing it i can't reproduce in another c3p.

Is there somewhere i can send it privately for you to look at?

I'm eager to finish the game and even resubscribed to do so and i could do without things like this, especially since its supposed to be a stable build!

## Attach a .c3p

n/a

## Steps to reproduce

n/a

## Observed result

100% cpu usage after a few seconds of running the game under stable R111

## Expected result

should be around 30% cpu usage as it runs under stable R104

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2018-08-08 20:27
Are you using the C2 or C3 runtimes? There have been minimal changes to the C2 runtime recently as most work is focused on the C3 runtime. Can you identify the specific version of C3 that changed between r104 and r111? If you run the debugger where does the profiler indicate the CPU time is being spent?

**Comment by mOOnpunk** [comment] 2018-08-09 07:04
Its the c2 runtime, i can't try the c3 runtime because it uses litetween which isn't supported.

I will try running the file under each beta version and see when the high cpu started.

**Comment by AshleyScirra** [comment] 2018-08-09 11:05
Not sure what could have had this kind of effect in r108/r108.2. If you can't isolate it please send the project to ashley@scirra.com with a clear description of what to do and a reference to this issue.

**Comment by mOOnpunk** [comment] 2018-08-09 17:28
I've uploaded it to dropbox and recent the email. Thanks.

**Comment by AshleyScirra** [comment] 2018-08-10 12:15
I haven't received any email yet, even after checking the spam folder. However separately I happened to find an issue with a fix that was done in r108 and corrected it for the next release. If that happens to be the same issue then this may be fixed at the next release anyway.

**Comment by mOOnpunk** [comment] 2018-08-10 12:42
I've recent the email. How long until the next release? Thanks.

**Comment by AshleyScirra** [comment] 2018-08-10 13:47
I still haven't received any email. Our beta releases are typically weekly towards the beginning of the week.

**Comment by mOOnpunk** [comment] 2018-08-10 15:28
I've sent the link via a temp email "ignzqdlo@sharklasers.com" so it may go to your spam folder. Hopefully this works. Any chance you can get the new release out before the weekend as i'm stuck until you do.

**Comment by AshleyScirra** [comment] 2018-08-10 15:38
Thanks, I finally received the link! I can reproduce the issue in r112, but it doesn't reproduce any more in the next release. So it seems it was the same issue and should be fixed in the next beta. It should be out early next week. I'll close this issue once you've tried the next release and verified it's fixed for you as well.

**Comment by mOOnpunk** [comment] 2018-08-10 15:46
Thanks good to hear. I look forward to the next release. I guess i'll have to revert back to r104 until then.

**Comment by mOOnpunk** [comment] 2018-08-10 15:48
As a matter of interest what exactly was causing it, if infact it was the issue you've fixed?

**Comment by AshleyScirra** [comment] 2018-08-10 16:51
It's hard to explain. It was a change made deep in the event engine to fix an issue with OR blocks, but it accidentally had unintended consequences.

**Comment by AshleyScirra** [comment] 2018-08-13 11:36
r113 is out now, please check again!

**Comment by mOOnpunk** [comment] 2018-08-13 18:05
It's fixed the cpu bug but i've noticed its changed the way the game works. I don't know if i was unknowing making use of the bug, and now its been fixed its my code thats wrong, or if the code is right and the bug fix has caused other issues. 

The issue is with OR events with negated conditions. Not sure why i had the conditions negated with an OR, but it worked before and now it doesn't, but un-negating the conditions seems to fix things.

**Comment by AshleyScirra** [comment] 2018-08-14 08:13
Originally reported issue appears to be fixed so closing. Please file a new issue following all the guidelines if anything else is wrong. We've not had any other reports of issues with OR blocks so far.

**Closed by AshleyScirra** 2018-08-14 08:13 UTC
