### ISSUE TITLE
Global layers invisible sprite bug :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6508] opened 2023-02-12 21:44 UTC
## Problem description

The sprite disappears.

## Attach a .c3p

No.

## Steps to reproduce

1. Create a new project.
2. Add a sprite.
3. Add layout.
4. On the new layout, add a layer and make it global.
5. Add a new layer on the first layout.
6. Drag layer 0 under layer 1. The sprite will disappear.
7. Save and load the project. After loading, you will not be able to select the sprite, but you will be able to interact with it - rotate and twist.

## Observed result

https://user-images.githubusercontent.com/91274932/218338781-14c0238f-4932-4a51-a660-54845df085a6.mp4

## Expected result

The sprite does not disappear.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r329b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r329 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 167 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2023-02-14 12:16
What is happening here is that when a layer is added as a sub-layer of an overridden layer, later when the overridden layer is going to be drawn, it is drawing the source global layer and it's sub-layers rather than its own, as expected.

This means than any sub-layers (and it's content) on an overridden layer are essentially hidden, because their parent layer's own content is being ignored.

I am not really sure what is the expected behaviour here. We could either have all the instances which become invisible also not be interactable for consistency. We could also draw the sub-layers of the overridden layer along with the sub-layers of the source global layer.

@AshleyScirra, any thoughts?

**Comment by AshleyScirra** [comment] 2023-02-14 12:58
I think in a way this is connected to #6503. It turns out that the various ways that global layers and sub-layers interact are surprisingly complicated. For example in that case if you have an override layer under a global layer, it's possible to create a cyclic reference which recurses infinitely, which is something that definitely should not be allowed (and should be fixed now).

As for this issue I'm not sure really, what is the correct design? On the one hand it seems convenient that you can just set one override layer and get all the global layer's sub-layers with it automatically. That avoids the need for adding extra override sub-layers every time you add an extra sub-layer to the global layer. However that then lets you put an override layer as a sub-layer of another override layer which itself shows a range of sub-layers, which seems weird. On the other hand if global layers don't inherit their sub-layers, it's potentially more flexible as you can pick and choose which individual sub-layers of a global layer you want, but it's more work to update the project if changes are made.

Given the point of global layers is to avoid having to make changes for every layout across the project, I suspect the latter option is not the best choice. However the first has its own complications anyway. Perhaps, also given the risk of cyclic references, we should leave it as is (so global layers inherit all their sub-layers) but then entirely disallow combining override layers and global layers as sub-layers of each other. That in turn may have backwards compatibility implications though if projects already exist that do that. So perhaps the best option is to just ignore sub-layers of an overridden layer... which sounds like is what already happens. In that case I guess the editing tools should disallow interaction with the unused sub-layers, but then we have a weird situation where these sub-layers are basically useless as they don't do anything and can't be interacted with in any way until you move them somewhere else again. I'm not sure there's a better alternative 🤷

**Comment by DiegoScirra** [comment] 2023-02-16 14:37
Given that it's difficult to tell what the proper behaviour be, I will leave it as it is now and just disable interactivity of instances which became invisible. I also noticed another similar but opposite case in which it was not possible to interact with an instance which was visible.

Both changes will be available in the next beta.

**Closed by DiegoScirra** 2023-02-16 14:37 UTC
Labels: difficult
