### ISSUE TITLE
[R90.2]Beta update when having added the application icon to desktop (Chrome)

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#1386] opened 2018-03-15 16:00 UTC
## Problem description
I have added C3 to my desktop using the "Add to desktop" feature from Chrome.
I have set the settings of C3 to "Beta release".

Since R90.2, every time I open it, it offers me to update from R89 to R90.2.
I click Update now and it does.
Yet when I close it and launch it again, the same update offer happens again.

## Attach a .c3p

Not related to a capx, it is on C3's launch.

## Steps to reproduce

1. Use R89 (or older ?) in Chrome.
2. Add to desktop.
3. Put the "Updates" setting from C3 to "Beta releases"
4. Execute from the icon proposed on your desktop.

## Observed result

On launch, the upgrade dialog let's you know you are using an older release and that 90.2 is available and offers to update to it.
Even though I already did each time I have launched C3 since r90.2's release.

## Expected result

For the update to "stick"

## Extra notes

Another way to reproduce is to connect to construct.net (Chrome and Firefox for this one) and go to the Releases part. 
Select Stable beta when your Update setting is set to use beta release.
Updating equals going to another URL.
In browsers it is OK to do so.
Nevertheless, in the "icon" version, the URL seems to be stuck to the latest stable release.
Is there anyway to modify which URL/Release to open using the added to desktop version ?

## Affected browsers

* Chrome: yes
* Firefox: no
* Edge: not tested (doesn't offer the "desktop icon" application anyway, right ?)
* Safari: not tested (doesn't offer the "desktop icon" application anyway, right ?)

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 65.0.3325.162
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36
C3 release: r90.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 12 gb
Storage usage (approx): 748 mb (5.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2018-03-15 16:12
When you do "add to desktop" you're essentially bookmarking editor.construct.net. That URL loads the latest stable release (currently r89). When you opt-in to beta releases, you'll see a beta update notification if  you load a stable release with a newer beta release available (e.g. r90.2 is currently available). So it's all working as expected, even if it's not quite ideal. The main issue is you can't see the URL bar to see what's happening - it's more obvious if you had a normal bookmark.

Not quite sure what we can do about this - we've set up editor.construct.net/beta to redirect to the latest beta release, but you can't 'add to desktop' with that URL, since it will immediately redirect you to a specific beta release.

**Comment by AshleyScirra** [comment] 2018-03-19 11:43
Closing as this is more or less by design at the moment. We might want to figure out a better way of handling this but I don't think it's actually a bug.

**Closed by AshleyScirra** 2018-03-19 11:43 UTC
