### ISSUE TITLE
(r65) Crash on startup due to Ublock Origin blocking new Mobile Advert plugin

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#980] opened 2017-10-31 14:33 UTC
## Problem description

Starting up construct crashes it immediately, after update. Clearing cache and app data did not help, but works in incognito mode. Tried clearing cache several times, to no avail.

starting editor with https://editor.construct.net/r64/ works.

Seems like update process can break C3.

iMac / Chrome

## Attach a .c3p

N/A

## Steps to reproduce

1. Start Construct 3 and let it update to r65

## Observed result

Construct Crashes.

## Expected result

Should not crash

## Affected browsers

* Chrome: yes

## System details

Error report information
Type: unhandled rejection
Reason: Error: expected function @ TypeError: expected function at Function.ǃm.ǃtd (https://editor.construct.net/r65/main.js:2:179079) at Function.ǃm.ǃt (https://editor.construct.net/r65/main.js:2:207238) at a.ǃrf (https://editor.construct.net/r65/main.js:73:30533) at Object.n.push.ǃm.ǃAC [as ǃReq] (https://editor.construct.net/r65/main.js:73:30922) at n (https://editor.construct.net/r65/main.js:2:267676) at t (https://editor.construct.net/r65/main.js:2:267462)
Stack: TypeError: expected function at Function.ǃm.ǃtd (https://editor.construct.net/r65/main.js:2:179079) at Function.ǃm.ǃt (https://editor.construct.net/r65/main.js:2:207238) at a.ǃrf (https://editor.construct.net/r65/main.js:73:30533) at Object.n.push.ǃm.ǃAC [as ǃReq] (https://editor.construct.net/r65/main.js:73:30922) at n (https://editor.construct.net/r65/main.js:2:267676) at t (https://editor.construct.net/r65/main.js:2:267462)
Construct 3 version: r65
URL: https://editor.construct.net/
Date: Tue Oct 31 2017 15:24:36 GMT+0100 (CET)
Uptime: 5.4 s

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_5
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r65
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GTX 775M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2047
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by discmach** [comment] 2017-10-31 14:38
Just got the update, and yeah this crash error. 

Error report information
Type: unhandled rejection
Reason: Error: expected function @ TypeError: expected function at Function.ǃm.ǃtd (https://editor.construct.net/r65/main.js:2:179079) at Function.ǃm.ǃt (https://editor.construct.net/r65/main.js:2:207238) at a.ǃrf (https://editor.construct.net/r65/main.js:73:30533) at Object.n.push.ǃm.ǃAC [as ǃReq] (https://editor.construct.net/r65/main.js:73:30922) at n (https://editor.construct.net/r65/main.js:2:267676) at t (https://editor.construct.net/r65/main.js:2:267462)
Stack: TypeError: expected function at Function.ǃm.ǃtd (https://editor.construct.net/r65/main.js:2:179079) at Function.ǃm.ǃt (https://editor.construct.net/r65/main.js:2:207238) at a.ǃrf (https://editor.construct.net/r65/main.js:73:30533) at Object.n.push.ǃm.ǃAC [as ǃReq] (https://editor.construct.net/r65/main.js:73:30922) at n (https://editor.construct.net/r65/main.js:2:267676) at t (https://editor.construct.net/r65/main.js:2:267462)
Construct 3 version: r65
URL: https://editor.construct.net/
Date: Tue Oct 31 2017 14:35:47 GMT+0000 (GMT Standard Time)
Uptime: 2.5 s

Platform information
Browser: Chrome
Browser version: 62.0.3202.75
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36
C3 release: r65
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: Google SwiftShader
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 0.125 to 2048
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_draw_buffers, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

**Comment by AshleyScirra** [comment] 2017-10-31 14:40
Can't reproduce in Chrome stable, Chrome Canary, Firefox or Edge. Everything looks OK here. Are you using any third-party addons or browser extensions?

**Comment by discmach** [comment] 2017-10-31 14:43
Just "turned off" Ublock Origin, and it started up fine. 

Ublock Origin last released an update October 15th. 
I was running C3 fine on v64 in the last 2 weeks no problem (outside the other issues.)

**Comment by AshleyScirra** [comment] 2017-10-31 14:46
The new Mobile Advert plugin has the id "advert", and is loaded from a path like "editor.construct.net/r65/plugins/advert/plugin.js". If Ublock Origin is blindly blocking any requests with the word "advert" in the name, I guess it would fail to load and crash on startup. Which would be awkward...

**Comment by AshleyScirra** [comment] 2017-10-31 14:49
I can reproduce by installing Ublock Origin, and confirmed it is blocking the URL to the new advert plugin.

>_<

**Comment by tunepunk** [comment] 2017-10-31 14:56
Construct 3 started after deactivating completely removing Adblock Plus. Although Adblock plus was deactivated (do not block) for construct.net

Is there something we can add to whitelist? I need an adblocker?

**Comment by tunepunk** [comment] 2017-10-31 15:02
"editor.construct.net/r65/plugins/advert/plugin.js" 

Would changing "advert" to "monetization" help?  lol

**Comment by AshleyScirra** [comment] 2017-10-31 15:09
Whitelisting the whole editor.construct.net domain would be a good idea to prevent any similar problems. We don't show ads there so there's nothing to block.

I think I've got this fixed for the next build - we simply changed the URL to something else and it looks like it's not blocked any more :P (not exactly robust ad blocking!) I guess we need a fix for this pretty soon since ad blockers are widely used. I'll get this out tomorrow at the latest.

**Comment by tunepunk** [comment] 2017-10-31 15:13
Reactivated Adblocker and checked that I already had editor.construct.net and construct.net on the whitelist but now it's crashing again. :) Wow those adblockers are really sensitive 😛

**Comment by pwrtoppl** [comment] 2017-10-31 15:15
@tunepunk  you could also try *.construct.net\*
I got this to work on my Android device using a custom VPN (whitelisted exception)

**Comment by tunepunk** [comment] 2017-10-31 15:19
@pwrtoppl that didn't help. Strange that even whitelisted sites get blocked like this. Hopefully ashley will have sorted it shortly :)

**Comment by pwrtoppl** [comment] 2017-10-31 15:22
@tunepunk are you closing out all Chrome tabs beforehand? Maybe there is an instance of it running in the background. You may need to try using Task Manager, or wait like you mentioned. Still a fantastic update today

**Comment by discmach** [comment] 2017-10-31 17:10
Yes works with ublock on.

**Comment by tunepunk** [comment] 2017-10-31 18:35
Not crashing with Adblock Plus either now.

**Comment by AshleyScirra** [comment] 2017-10-31 18:42
OK, thanks for confirming.

**Closed by AshleyScirra** 2017-10-31 18:42 UTC
Labels: browser extension, need info

**Comment by alastajj** [comment] 2017-11-02 02:00
The irony of people that use adblock and yet still wanting to use it for profit.

**Comment by tunepunk** [comment] 2017-11-02 10:51
I wouldn't wanna ruin my games by putting ads in them. Let alone play games with ads in them. Instant uninstall for me. Hence adblocker, but i still feel like hypocrite since my daytime job is doing banners for others. 😛

**Comment by pwrtoppl** [comment] 2017-11-02 14:08
@alastajj I am going to assume you haven't worked for a bigger corporation yet, so I'll explain a bit here. Blocking desktop ads is something a lot of companies are doing these days. Not only are they annoying and get in the way of processes executed by companies, they sometimes can be dangerous to organizations.
I'm also guessing you don't following any security information sites, but the most recent Wannacry knockoff served itself as a Flash update advert. And there have been many times where blocking such adverts before they are delivered to employees of a company has proven more than effective at blocking one such vector of attacks. This and educating users against phishing are two common methods to prevent companies from being attacked by outside sources (using firewalls and exchange filters also help here, but malicious content does still slip through).
From personal experience at a hyper-marketing company I can tell you it was required every machine deployed to a user have at minimum two adblockers and ghostery installed (take a look at ghostery if you want to see how many ads get dragged through a site as well as everything tracked when you visit). If you are in a competitive market, you block ads and run extensions that block/obfuscate information (ublock origin is one of these) . 
The last thing you want is information about processes revealed to competitors about anything regarding your company. That's simply bad business.
This all holds true for companies that supply phones. Currently where I am, we are provided phones with custom VPNs installed to ensure the same firewall rules we apply to the desktop/server environment is applied to the users when they are mobile. Again, security related. 

Now, as for mobile, companies aiming to make money often do one of three methods. 
1 - insert just ads - which has a highly favorable outcome with most consumers (Google mobile revenue consumer reports, there are many that point to just ads as a driver to higher downloads)
2 - ads with purchases - a newer industry standard, using video reward ads to give users 'second lives' 'extra income' etc, coupled with purchases for additional access/unlocked content, to give more popular companies maximum revenue, this also includes games with ads that have a purchase option to remove said ads (as many smaller companies/individuals will do, usually as a form of direct support to the developer)
3 - just IAPs - either by subscription or individual unlocks, this can include games with multiple types of currency, or apps that offer a premium experience with different tiered purchasing options for higher cost, but often, multiple purchasing directives. IAPs by themselves are not as common as #2, since they can be hit or miss depending on targeted audience budgets.
These are the three pretty common methods used by companies and individual developers to generate revenue, because, at the end of the day, companies aren't doing this because they like individual consumers, they want to make money. 

Ads serve as an important alternative to direct purchases and subscriptions that allow users to enjoy content for a few seconds of a banner/full screen ad/rewarded video.

None of this is irony. It's business.

**Comment by AshleyScirra** [comment] 2017-11-02 15:36
Please don't use bug reports for general discussions, it sends notifications to everyone involved in the bug report every time you comment. Locking this report now, please continue on the forum if you wish to discuss further.
