### ISSUE TITLE
Origin Moves Around After Changing Location / Then Cycling Frames/Animations

### ISSUE THREAD

**Issue by brainwavecreations** [Scirra/Construct-3-bugs#5935] opened 2022-07-29 00:53 UTC
Bug Video: https://youtu.be/RLO-Kszdf50

Problem description: 

The Origin Point will move back to default center, or elsewhere if importing multiple images for a new animation.  Then Set to Animation, or Set to All Animations.  It does not seem to happen with existing animations already on the Player Sprite Object.   Also, if you Preview the Animation and Close Animations Editor, or just Close Animations Editor it is fine when you return.

Attach a .c3p:  Attached
[Bugged 1 - Player Initialization & Player Animations.zip](https://github.com/Scirra/Construct-3-bugs/files/9215096/Bugged.1.-.Player.Initialization.Player.Animations.zip)

Steps to reproduce

1. Add New Animation
2. Change Origin Point
3. Set to Animation and/or All Animations
4. Cycle through frames/animations without previewing and closing animations editor, or just closing the animations editor
5. Watch as the Origin Point moves around while cycling Frames/Animations

Observed result:

Watch as the Origin Point moves around while cycling Frames/Animations on new animation

## Expected result

Origin Point should stay where it is placed, and then set to animation/animations

More details: None.  It's explained pretty well above.

**Affected browsers/platforms:** 
Windows 10, all chromium browsers I have (Chrome, Brave)

Noticed it with r304

**First affected release:** 
Noticed it with r304

System details:
Windows 10, all chromium browsers I have (Chrome, Brave)

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 103.0.5060.134
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 195 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2022-07-29 11:10
Just tried this out, does it only happen when using the keyboard shortcuts to go through the frames/animations?

**Comment by brainwavecreations** [comment] 2022-07-29 14:33
If I remember correctly.  I'm pretty sure it happened while using the mouse cursor as well.  But, I pulled two all nighters this past week, and my memory is shot.  I'm not 100% because I normally use the CTRL and arrows.  But, I do recall clicking around after adding one animation.  I can test again during down time this weekend, if you need.  

I just made all three bug videos public.  No worries.

**Comment by brainwavecreations** [comment] 2022-07-29 14:36
I just confirmed, yes it does happen when clicking to different frames as well.  Figured I'd test before I get into my to-do list for the day.,

**Comment by brainwavecreations** [comment] 2022-07-29 14:39
So either CTRL and arrows, or clicking around it will move the image point, and the collision box in my other bug report.  But, you can get around it, by simply closing the animations editor right after assigning to entire animation or all animations.  Then reload the animations editor.  

Even if you do the apply to all animations, or this animation.  Then run a preview directly after doing that, it will preview fine.  But, once you navigate to other frames without closing the animations editor first, both the origin/image points will move.  Along with the collision box points as in the other bug.

**Comment by DiegoScirra** [comment] 2022-07-29 16:26
I see, I thought I was working on a related issue, but now that I see the video it's the same thing. The problem is caused by cropping a whole animation before using the image point tool to apply changes to a whole animation.

I am pretty sure this was introduced by attempting to fix #5605

**Comment by DiegoScirra** [comment] 2022-07-29 17:15
This will be fixed in the next beta.

Revision 17541

**Closed by DiegoScirra** 2022-07-29 17:15 UTC

**Comment by brainwavecreations** [comment] 2022-07-29 18:44
> I see, I thought I was working on a related issue, but now that I see the video it's the same thing. The problem is caused by cropping a whole animation before using the image point tool to apply changes to a whole animation.
> 
> I am pretty sure this was introduced by attempting to fix #5605

Yeah, exactly.  Cropping and then setting the origin/image points afterward, and not closing out of the Animations Editor.  Thanks so much for all of your work, @DiegoScirra !  You are the man!  I hope you have a fantastic weekend :)
