### ISSUE TITLE
Browser "On mobile back button pressed" (Android)

### ISSUE THREAD

**Issue by C3GameDev** [Scirra/Construct-3-bugs#4520] opened 2021-02-02 13:26 UTC
## Problem description

The "On mobile back button pressed" from the C3 default Browser Addon is not working on Android 10 + 11 (maybe from Android 8+, on Android 7 it's working fine).

## Attach a .c3p

[https://creative-gamez.de/test.c3p](https://creative-gamez.de/test.c3p)

## Steps to reproduce

1. Export for Android (used the C3 build service, debug apk)
2. Start the app
3. Press the phone's "back button"

## Observed result

The App will close!

## Expected result

The shown text "Test" should be changed to "Don't close the app!"

## More details
I've tested it on Android 7, 10 and 11.
The error only appears on Android 10 and 11, on Android 7 it works fine (I heard something about from Android8+ there was a change)
Important (if you do this step, it also works on Android 10 + 11):
1. Start the app
2. Press the phone's menue-button (not back-button). Now the app should be tabbed out / move to the background.
3. Move the app back to the foreground
4. Now press the back-button and it works!

**Affected browsers/platforms:** Android 10, Android 11

**First affected release:** r225 Stable

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2021-02-02 14:09
This is a duplicate of #4259. It's a bug in Cordova - we reported it to them here but it looks like they are yet to act on it: https://github.com/apache/cordova-android/issues/1106

**Closed by AshleyScirra** 2021-02-02 14:09 UTC
Labels: duplicate

**Comment by dop2000** [comment] 2021-02-02 16:22
@AshleyScirra  It has been over two months since you reported this bug to Cordova, and it hasn't even been acknowledged..
