### ISSUE TITLE
there is a problem in construct 3:

### ISSUE THREAD

**Issue by abdo160** [Scirra/Construct-3-bugs#1695] opened 2018-06-13 20:30 UTC
## Problem description

when i paste any image twice in sprite editor it shows me this error:
Error report information Type: unhandled rejection Reason: Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0. @ Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0. at Function.ǃQbz (https://editor.construct.net/r98/main.js:74:423140) at e.ǃQlw.ǃQbn (https://editor.construct.net/r98/main.js:74:223739) at e.ǃQlw.ǃdx (https://editor.construct.net/r98/main.js:74:216811) at e.ǃQlw.ǃQ$H (https://editor.construct.net/r98/main.js:74:217318) at e.ǃQlc.ǃQ$F (https://editor.construct.net/r98/main.js:74:206404) at e.ǃQlc.ǃQ$Z (https://editor.construct.net/r98/main.js:74:206226) Stack: Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0. at Function.ǃQbz (https://editor.construct.net/r98/main.js:74:423140) at e.ǃQlw.ǃQbn (https://editor.construct.net/r98/main.js:74:223739) at e.ǃQlw.ǃdx (https://editor.construct.net/r98/main.js:74:216811) at e.ǃQlw.ǃQ$H (https://editor.construct.net/r98/main.js:74:217318) at e.ǃQlc.ǃQ$F (https://editor.construct.net/r98/main.js:74:206404) at e.ǃQlc.ǃQ$Z (https://editor.construct.net/r98/main.js:74:206226) Construct 3 version: r98 URL: https://editor.construct.net/ Date: Tue Jun 05 2018 18:45:35 GMT+0300 (Egypt Daylight Time) Uptime: 736.3 s Platform information Browser: Chrome Browser version: 66.0.3359.181 Browser engine: Blink Browser architecture: 64-bit Context: browser Operating system: Windows Operating system version: 7 Operating system architecture: 64-bit Device type: desktop Device pixel ratio: 1 Logical CPU cores: 4 Approx. device memory: 4 GB User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36 C3 release: r98 (stable) Language setting: en-US WebGL information Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium) Numeric version: 1 Supports NPOT textures: partial Supports GPU profiling: no Vendor: Google Inc. Renderer: ANGLE (Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0) Major performance caveat: no Maximum texture size: 8192 Point size range: 1 to 256 Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_color_buffer_half_float, EXT_frag_depth, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_color_buffer_float, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

**Comment by DiegoScirra** [comment] 2018-06-25 13:32
Didn't follow guide lines and can't reproduce it, closing.

**Closed by DiegoScirra** 2018-06-25 13:32 UTC
Labels: can't reproduce, ignored guidelines
