### ISSUE TITLE
Mobile Advert Issue - C3Runtime [r156]

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#3079] opened 2019-06-25 13:39 UTC
## Problem description

I was used @shortercode 's  GDPR template but it is works different with **C3Runtime**.

Everything works fine with **C2Runtime**. Some triggers don't work when you use offline and when you set user consent one time.

**Offline Tests:**
I can't set user consent "Personalized, non-personalized or add-free" status. This works with C2Runtime.
Show consent fails and shows me fail message - It is OK

**Online Tests:**
When I click Configure button. Configuration OK. After I want select user consent with buttons first time it's works but after I can't change that.
Show Consent button don't show me any fail or OK messages.

## Attach a .c3p

[AdvertTestGDPR.zip](https://github.com/Scirra/Construct-3-bugs/files/3325468/AdvertTestGDPR.zip)

## Steps to reproduce

**Offline Steps - C2Runtime:**
1. Close network connection.
2. Run app
3. Click 1 time "Configure" - (It will show error message)
4. Click "Set personalized" - (It will show personalized OK)
5. Click "Set non-personalised" - (It will show non-personalised OK)

**Offline Steps - C3Runtime:**
1. Close network connection.
2. Run app
3. Click 1 time "Configure" - (It will show error message)
4. Click "Set personalized" - (It will not show any message)
5. Click "Set non-personalised" -  (It will not return any message)

## Expected result

It should work like C2Runtime

**Affected browsers/platforms:** Android - 5.0.2

**Comment by shortercode** [comment] 2019-06-25 14:56
The issue seems to be that modifying the user personalisation value when unconfigured is allowed in the C2 runtime, but not in the C3.

Realistically it should be disallowed in both, if configuration has failed then I wouldn't expect adverts to work anyway.

**Comment by QuasarX** [comment] 2019-06-25 15:08
Hmm, I need change my event codes if C3runtime will work different. Well you can try using online phone. You can't set personalisation after 1st time.

Try this please,

1. Open network connection.
2. Run app
3. Click 1 time "Configure" - (It will show Config OK message)
4. Click "Set personalized" - (It will show Succesfull message)
5. Click "Set non-personalised" - **(It will not return any message)**

**Comment by shortercode** [comment] 2019-06-25 15:12
Yes I found a bug in the method that deals with that, when it entered the method it set the status to busy but it never cleared it after completion.

**Comment by shortercode** [comment] 2019-06-26 16:59
The bug with` set user personalisation` should be resolved in the next beta release.

As for the other part I will consider the implications and update this issue.

**Comment by shortercode** [comment] 2019-07-12 15:28
I can't really see any reason why you would want to customise the user personalisation state if the plugin hasn't been configured, as it won't have any effect. So I've put some changes into the C2 runtime so that behaves as the C3 runtimes does ( basically ignores the action if it's unconfigured ). This was the intended behaviour, and the way the rest of the plugin behaves in this situation.

**Closed by shortercode** 2019-07-12 15:28 UTC
