### ISSUE TITLE
Behaviors Platform, Sine and Jump-thru do not always work together

### ISSUE THREAD

**Issue by TomoloGames** [Scirra/Construct-3-bugs#4564] opened 2021-02-13 15:49 UTC
**Problem description**

If the player has a platform behavior and is jumping on a sine with the jump-thru behavior, the player sometimes fall under the sine. This happens when the player is falling and the sine is moving up.

[BugReportFile.zip](https://github.com/Scirra/Construct-3-bugs/files/5975932/BugReportFile.zip)

**Steps to reproduce**

1. Create a sprite with platform behavior. Create a sprite with sine and jump-thru behavior.
2. Jump on the sprite with sine and jump-thru behavior a couple times.

**Observed result**

Player is falling through the sine instead of landing on it.

**Expected result**

Player should land and not fall through.

**More details**

I stumbled upon this problem a few months ago but I created a workaround that worked pretty well but not perfectly. I didn't file a bug report though!

**Comment by AshleyScirra** [comment] 2021-02-17 16:55
This is basically a duplicate of #4406 but with different parameters. It's an extremely complicated problem as explained [in my comment on that issue](https://github.com/Scirra/Construct-3-bugs/issues/4406#issuecomment-744545966).

The core of the problem is it's very difficult to resolve the situation of a jumpthru moving upwards in to the player. Unlike solids, the player is allowed to intersect a jumpthru and fall through it. If a jumpthru suddenly teleports in to the player, then it is valid to ignore it and let the player carry on falling through it. Upwards motion, particularly fast upwards motion, is actually indistinguishable from this case - it's just the movement happens in steps. The platform behavior attempts to resolve a landing on an upwards moving jumpthru using a tolerance, but no matter what tolerance is set, it's always possible to exceed this with further changes to the player speed and jumpthru speed. I actually tried increasing the tolerance and the problem still reproduced in your project, just more rarely. We also cannot keep setting larger tolerances, otherwise other circumstances start to exhibit snapping problems, such as reported previously in issue #3631.

I'm afraid I don't think there's a good way to resolve this case - jumpthrus basically don't work well if you move them upwards quickly. The only way around this is to tune the parameters so it doesn't happen. The slower the jumpthru moves, the more reliable it should be - or just use a solid, which should always be reliable, since the player is not allowed to intersect it.

**Closed by AshleyScirra** 2021-02-17 16:55 UTC
