### ISSUE TITLE
error when moving a keyframe in a timeline

### ISSUE THREAD

**Issue by teaaaaaaaa** [Scirra/Construct-3-bugs#5995] opened 2022-08-15 20:29 UTC
## Problem description

moving a keyframe from outside of the timeline's length causes an error

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'da') @ TypeError: Cannot read properties of null (reading 'da') at d.da (https://editor.construct.net/r305/projectResources.js:1118:489) at d.jo (https://editor.construct.net/r305/projectResources.js:1100:168) at jo.next () at d.Sqa (https://editor.construct.net/r305/projectResources.js:1101:401) at d.mIb (https://editor.construct.net/r305/projectResources.js:1122:143) at window.Gb.qq.Qnb (https://editor.construct.net/r305/components/bars/timelineBar/timelineBar.js:333:263) at window.Gb.qq.ea (https://editor.construct.net/r305/components/bars/timelineBar/timelineBar.js:338:304) at V1.Fib (https://editor.construct.net/r305/components/bars/timelineBar/timelineBar.js:144:178) at V1.F4 (https://editor.construct.net/r305/components/bars/timelineBar/timelineBar.js:143:499) at u2.Ovc (https://editor.construct.net/r305/components/bars/timelineBar/timelineBar.js:173:396)
Stack: TypeError: Cannot read properties of null (reading 'da') at d.da (https://editor.construct.net/r305/projectResources.js:1118:489) at d.jo (https://editor.construct.net/r305/projectResources.js:1100:168) at jo.next () at d.Sqa (https://editor.construct.net/r305/projectResources.js:1101:401) at d.mIb (https://editor.construct.net/r305/projectResources.js:1122:143) at window.Gb.qq.Qnb (https://editor.construct.net/r305/components/bars/timelineBar/timelineBar.js:333:263) at window.Gb.qq.ea (https://editor.construct.net/r305/components/bars/timelineBar/timelineBar.js:338:304) at V1.Fib (https://editor.construct.net/r305/components/bars/timelineBar/timelineBar.js:144:178) at V1.F4 (https://editor.construct.net/r305/components/bars/timelineBar/timelineBar.js:143:499) at u2.Ovc (https://editor.construct.net/r305/components/bars/timelineBar/timelineBar.js:173:396)
Construct version: r305
URL: https://editor.construct.net/r305/
Date: Mon Aug 15 2022 13:19:45 GMT-0700 (Pacific Daylight Time)
Uptime: 7038.7 s

Platform information
Product: Construct 3 r305 (beta)
Browser: Edge 104.0.1293.47
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.47
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment] 2022-08-16 10:24
@teaaaaaaaa - please always follow the bug report guidelines otherwise it's frequently impossible for us to help.

@DiegoScirra - are you able to reproduce?

**Comment by DiegoScirra** [comment] 2022-08-16 10:46
Can't reproduce it.

**Comment by AshleyScirra** [comment] 2022-08-16 10:48
Closing as report is not actionable.

**Closed by AshleyScirra** 2022-08-16 10:48 UTC
Labels: ignored guidelines
