### ISSUE TITLE
Exporting to NW.js Issues

### ISSUE THREAD

**Issue by drezgames** [Scirra/Construct-3-bugs#1248] opened 2018-01-28 03:00 UTC
## Problem description

I've finally a way to consistently reproduce the crash when I try to export to NW.js. The problem is that about halfway through (building the zip) it will crash the editor.  Then there are times when it would work fine, then after using c3 desktop for a while, it would then start to fail. Turns out there seems to be a correlation of running the editor (it works) then close the editor and start it up again (then its starts to fail).

## Steps to reproduce

1. Run the editor, load a project and export to NW.js (it works)
2. Close the editor, start editor again and try to export (will fail, sometimes right away sometimes on the 2-3 close/start)
3. Now, what I discovered is that if I reboot my machine, then load editor I can now export without issue until I close the editor/start it again.

This is crazy and driving me totally insane. How can this be solved?  

## System details

I've included my system info if this helps.
<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.27.4
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@d8d23fd3b95d7b3c7744027f2ea1c954aec28955) NWjs/0.27.4 (like Chrome/63.0.3239.132)
C3 release: r81.2
Language setting: en-US

Local storage
Storage quota (approx): 877 gb
Storage usage (approx): 75 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by drezgames** [comment] 2018-01-28 08:30
Whelp, after running c3 desktop on a fresh win 10 install, I conclude that NW.js exporting is bugged.
1. export using NW.js (works)
2. close the editor and load it again
3. goto 1 and after about 3-4 times it WILL FAIL
4. does not seem to work again until you reboot machine
5. same problem with the web version as well.

**Comment by AshleyScirra** [comment] 2018-01-29 13:06
Are you sure this only happens in the desktop build and never in the browser? They use almost identical code for NW.js export as of r81.2.

Can you also please copy and paste in one of the crash reports? This is valuable information if we can't reproduce the issue ourselves.

**Comment by drezgames** [comment] 2018-01-29 18:21
Yesterday, all day long, after each reboot, I could export repeatedly about 4 times then it would crash, both desktop and browser. I forgot to update the title. So today, I am trying to make it crash to send you the crash report, but can't get it crash at all. I really do not understand this. I mean, there is nothing different from today than yesterday (unless there has been a update maybe)? I will keep trying and as soon as it does I will send that report. BTW where will the be located? In the AppData folder?

**Comment by drezgames** [comment] 2018-01-29 19:37
Ok, so I finally got it to crash now. If you can tell me where the crash reports are located I will send them along.

**Comment by AshleyScirra** [comment] 2018-01-29 19:44
Normally a crash dialog appears with diagnostic information which you can copy and paste. Are you seeing something else instead?

**Comment by drezgames** [comment] 2018-01-29 21:15
All I see is the the export failed dialog and you can press the [ok] button, that dialog goes away and the export progress bar remains updating and the only think that can be done is kill the app window with via the [X] button.

**Comment by drezgames** [comment] 2018-02-01 02:06
The new version still crashes. It's intermittent. I sent you a video showing what happens in the above comment.

**Comment by AshleyScirra** [comment] 2018-02-05 17:08
There's no project in this report so I opened Ghost Shooter. I exported it to NW.js 10 times in a row and it succeeded every time. I'm afraid there's not much more I can do if I can't reproduce the problem.

**Comment by TheRealDannyyy** [comment] 2018-02-08 16:15
Maybe try to update to the most recent version of NW.js using [the manager](https://www.construct.net/de/make-games/manuals/construct-3/interface/dialogs/nw-js-version-manager) or better, delete all existing NW.js downloads in storage and download them again.

I could reproduce this in the past and I remember fixing it by doing that.

**Comment by drezgames** [comment] 2018-02-08 17:14
@AshleyScirra 
Yes, I understand.

@TheRealDannyyy 
Yes, I always use the latest NW.js and C3.

I've not been using it much the past week. When there is a new update I will grab that and then try and so far its been working. What usually happens is that when I feel confident that its all working I will start to use it for hours at a time then when I try to export it crashes until I reboot my system. So I really don't know, it seem to be intermittent for me. At this moment it seems to be working fine.

**Comment by AshleyScirra** [comment] 2018-02-09 12:09
Not sure there's anything that can be done if we can't reproduce it and you say it's working again, so closing. Please file a new issue with the best steps to reproduce you can find if you have issues again.

**Closed by AshleyScirra** 2018-02-09 12:09 UTC
Labels: can't reproduce
