### ISSUE TITLE
The back button does not work in Android

### ISSUE THREAD

**Issue by Sirtaximan** [Scirra/Construct-3-bugs#4817] opened 2021-05-10 19:41 UTC
## Problem description

In many Android, C3 ignores the command and the button closes the game, and if it works, if you answer a call or turn off the screen, then it stops working.

## Attach a .c3p

 https://mega.nz/file/WIAEGbgS#OJ7ZGY3scL6tfhxprGXo57lohUKjQ_yyht3vw5QAZig

## Steps to reproduce

1. Run the game on android (it fails more on phones without physical button).
2. Press the back button
3. If the game does not close, turn off the screen or answer a call, turn on the screen or return to the game and press the button.

## Observed result

The game closes

## Expected result

The game should perform the action that I program in the browser (press the back button)

## More details

 Android

**Affected browsers/platforms:** 

**First affected release:**  I saw it at r2.41

## System details

<details><summary>View details</summary>

Android 10

</details>

**Comment by AshleyScirra** [comment] 2021-05-11 11:27
Duplicate of #4259 - it's a Cordova bug: https://github.com/apache/cordova-android/issues/1106

**Closed by AshleyScirra** 2021-05-11 11:27 UTC
Labels: duplicate
