### ISSUE TITLE
Random crash (possible corruption) with no error after changing events and running debug layout multiple times

### ISSUE THREAD

**Issue by LukeNecklace** [Scirra/Construct-3-bugs#2962] opened 2019-05-23 06:44 UTC
## Problem description

Random crash with no error message when changing events and then running debug layout multiple times.

**Note:** I was testing a possible bug where one of my functions in my game project would not run when an event condition was disabled. For some reason, I could not reproduce that in this project example, but I was getting this crash a lot anyway so I thought I would share this instead.

## Attach a .c3p

https://www.dropbox.com/s/flq56oxofwa1tdb/Random%20crash%20with%20no%20error%20after%20changing%20events%20and%20running%20debug%20layout%20multiple%20times.c3p?dl=0

## Steps to reproduce

1. Change some events.
2. Run debug layout.
3. Continue steps 1 and 2 repeatedly.

## Observed result

Program will eventually close itself without asking to save project (crash without error).
If you keep an eye on the console log with F12 every time you run the debug layout, you will eventually start seeing errors.

**Note:** This also caused my original file before I uploaded it to Dropbox to become corrupted. I could not open my local file of this project anymore from the recent projects tab, it just says "fail to open", but the dropbox download should work. So if this crash happens enough with you, it is likely to corrupt the file.

## Expected result

No automatic closing of the program without me pressing the X button (crash with no errror).
No corruption of local saved file.
I should be able to continue editing the project as much as I want without it crashing or corrupting the file.

## More details
I'm not exactly sure what's causing the issue. I just know that I have a similar but more complicated set of events in my actual game file that is not just causing crashes but also what I was trying to test initially with the function not running with a disabled condition. I am still trying to replicate that but for some reason I cannot seem to, I can only replicate the crash side of things (which is good in a way because I've been trying to work out why it's been crashing like this for ages).

**Affected browsers/platforms:** Desktop

**First affected release:** r150 (although the crash was happening a few versions back as well. I can't remember which one it was).

## System details

![console errors before crash](https://user-images.githubusercontent.com/28833199/58231101-79d49300-7d79-11e9-8c3e-1e0a1c729048.png)

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r150 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 67 gb
Storage usage (approx): 1.4 gb (2.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment] 2019-05-23 16:13
I haven't been able to reproduce any issue in the browser build, so tentatively labelling this as a desktop only issue. As for the file corruption was that a local c3p, local folder, cloud or browser based project?

**Comment by 7Soul** [comment] 2019-05-23 20:36
My C3 has been doing the same whenever I have the console open while using the editor. This started with r150 too and happens on a blank project. Just need to test the game, open console, go edit something in the editor and bam, it just closes with no error. The console also shows that red error every time I test a project (all local files)

**Comment by LukeNecklace** [comment] 2019-05-24 01:13
Thanks 7Soul. That's exactly it. But it also sometimes crashes like this and without the console. Having the console open though makes it more likely to crash.

@shortercode Sorry, I did not test this with browser versions but since you already have it does appear to be related to the desktop version only. The saved file was a cloud save using dropbox. I was able to access the file again after I downloaded it from dropbox but it was not possible to open it from the recent projects tab, it would just tell me that it failed to open the file. This is quite unusual because even in my actual game project, I have not experienced corruption, but when I did when I was testing for this crash.

**Comment by AshleyScirra** [comment] 2019-05-24 12:18
When Construct crashes, it shows a crash dialog. If the app closes that means the browser engine crashed, not Construct, and if it doesn't happen in Chrome it suggests it's a problem with NW.js. It sounds a lot like issues #2768 and #2933. We might be able to file an issue with NW.js, but it looks difficult because the steps to reproduce do not appear to be reliable or deterministic - we need a fixed number of steps that always reproduces the issue. Without that it's going to be very difficult to do anything about this. You could try directly reporting the issue to the NW.js developers, but they will similarly need reliable steps to reproduce.

**Comment by LukeNecklace** [comment] 2019-05-24 14:39
I tested this combination of steps with perhaps some variation as described before, and it happens without mistake when using the program like this. Sure, it doesn't exactly do it every single time at a fixed rate, it just happens when these actions are repeated over a short period of time. It might have something to do with the previous debug layout session running when opening another debug layout. I believed initially it had something to do with changing events and then closing the debug layout because that used to happen a lot. But it needs to run for a while and a certain amount of changes had to happen before it crashes. It is hard to say what the amount of changes are though. I'm just hoping at this point that this puts someone in the right direction because like others, I have been putting up with this type of crash for ages.

It doesn't feel like it's getting any better as updates happen either. I was hoping this would be something within in your control because you guys are much more efficient than NWjs fixing their bugs but if it's out of your control, god help us all.

**Comment by LukeNecklace** [comment] 2019-05-29 07:44
**Question:**
Would it be possible that changing the events, running the debug layout, waiting for it to load and start running and closing it could possibly cause the browser engine to crash? Is it getting stuck in some sort of loop where it cannot close like normal so it just crashes the entire program?

**Comment by AshleyScirra** [comment] 2019-05-29 10:41
It's really not worth speculating without debugging and properly diagnosing the issue.

**Comment by LukeNecklace** [comment] 2019-05-29 13:15
Feel free to do that then. I'm giving you my feedback based on my experience using your program. It's up to you now.

**Comment by LukeNecklace** [comment] 2019-06-19 09:45
Like I said I would add to this if I came across something new, but I really can't afford to be dedicating a heap of my time to debug this problem. The only reason why I'm here is because it's annoying me and I know it's annoying others too. I some more possibilities to share that I've noticed when I'm trying to test things in my project that I haven't shared here in better detail:

I've been keeping an eye on the type of things I am doing with Construct when I debug my game when this happens. I'm basically expecting my program to close without an error message now especially with the browser console open. I still cannot pinpoint exactly when it's happening, but I am able to provide a good idea of what combination of steps increase the chances of it happening.

**Possibility 1:**
1. Make changes to events (preferably deleting, adding, moving around and trying this with disabled events).
2. Run project with debug layout.
3. Press F12 to open console.
4. Let it run for a minute but during that time browse the debug layout like you're trying to debug a game.
5. Save your project (cloud save) to drop box when there are unsaved changes.
6. Let it run for a minute but during that time browse the debug layout like you're trying to debug a game.

**Possibility 2:**
1. Make changes to events (preferably deleting, adding, moving around and trying this with disabled events).
2. Run the project with debug layout.
3. Press 12 to open console.
4. Let it run for a minute but during that time browse the debug layout like you're trying to debug a game.
5. Make changes to events (preferably deleting, adding, moving around and trying this with disabled events).
6. Restart the debugger with the restart button on the debugger (not the run debug layout again) but keep the console window open.
7. Let it run for a minute but during that time browse the debug layout like you're trying to debug a game.
8. Repeat steps 1 - 6 until it closes on its down.

**Possibility 3:**
1. Make changes to events (preferably deleting, adding, moving around and trying this with disabled events).
2. Run project with debug layout.
3. Press F12 to open console.
4. Let it run for a minute but during that time browse the debug layout like you're trying to debug a game.
5. Make changes to events (preferably deleting, adding, moving around and trying this with disabled events).
6. Run project with debug layout from the drop down box in the editor (not the restart button).
7. Let it run for a minute but during that time browse the debug layout like you're trying to debug a game.
8. Save your project (cloud save) to drop box when there are unsaved changes.
9. Repeat steps 1 - 6.

**Possibility 4:**
1. Make changes to events (preferably deleting, adding, moving around and trying this with disabled events).
2. Run project with debug layout.
3. Press F12 to open console.
4. Let it run for a minute but during that time browse the debug layout like you're trying to debug a game.
5. Make changes to events (preferably deleting, adding, moving around and trying this with disabled events).
6. Run project with debug layout from the drop down box in the editor (not the restart button).
7. Let it run for a minute but during that time browse the debug layout like you're trying to debug a game.
8. Detach the debug window from the game so it has a separate window and move it around, even close it so it automatically reattaches itself to the game.
9. Let it run for a minute but during that time browse the debug layout like you're trying to debug a game.
10. Make changes to events (preferably deleting, adding, moving around and trying this with disabled events).
11. Save your project (cloud save) to drop box when there are unsaved changes.
12. Repeat steps 1 - 10.

These are the types of things I'm doing when I'm testing my game and Construct just closes along with all the windows.

Apart from that, is there any type of information that's recorded on the system when a crash like this happens at all?

**Comment by AshleyScirra** [comment] 2019-06-19 14:28
I finally found reliable steps to reproduce: preview, open dev tools, resize the preview window, then close it. For me that always causes a crash by the second try. It looks like an NW.js bug so filed it here: https://github.com/nwjs/nw.js/issues/7088
Closing this issue as we will follow up on the NW.js issue.

**Closed by AshleyScirra** 2019-06-19 14:28 UTC
Labels: desktop, external

**Comment by LukeNecklace** [comment] 2019-06-19 14:32
Oh resizing it caused it! That's a weird one! Bloody hell!

Thank you, Ash, I hope they fix it soon, it's so inconvenient.

**Comment by LukeNecklace** [comment] 2019-06-19 14:39
Last thing: I think the corruption would have been caused if Construct was in the process of saving the file when the crash happens because it never corrupted my major game project and I always saved before debugging like this.

**Comment by AshleyScirra** [comment] 2019-06-19 15:05
The corruption is a separate issue and, as ever, cannot be investigated unless we have a full report including reliable steps to reproduce it.
