### ISSUE TITLE
Spritesheets not appearing. Crashes Construct.

### ISSUE THREAD

**Issue by daleinen7** [Scirra/Construct-3-bugs#1362] opened 2018-03-11 14:23 UTC
## Problem description

A few sprites won't show up in the layout view and are instead a transparent red block. Double clicking on them shows the sprite as expected in the editor. When I try to view spritesheets Construct crashes. 

Also trying to preview the project fails. Construct says to restart the program. 

## Attach a .c3p
(Note this is the full project not a minimal file but should be immediately clear upon opening)
https://drive.google.com/file/d/1OhigWBkx6vWwLaWQMkbgKoyFe9Id27uQ/view?usp=sharing

## Steps to reproduce

1.Open project.
2.Right click main project folder in project tab
3.Click Tools -> View Spritesheets

## Observed result

Construct 3 crashes. 

## Expected result

*What did you expect to happen instead?*

## Affected browsers

I am using the desktop version. Though it happens in Chrome as well. 

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Exception in job handler: RangeError: Source is too large
Construct 3 version: r89
URL: https://editor.construct.net/
Date: Sun Mar 11 2018 09:13:36 GMT-0500 (Central Daylight Time)
Uptime: 190 s

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r89 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 550 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment] 2018-03-12 13:05
The project opens, previews and displays spritesheets just fine for me here, using Chrome 65 (latest stable). It looks like you're using the desktop build. Can you reproduce the problem when using Chrome or does it only happen in the desktop build?

**Comment by daleinen7** [comment] 2018-03-12 13:57
Yesterday when I was trying it with Chrome it wouldn't crash, but it froze
while trying to build the spritesheets.

Last night, deleting the tileset (which was a transparent red box instead
of any of the tiles) from the project made the few other transparent red
boxes turn normal, and the project previewed fine.

Today it works completely as expected on both the desktop and browser even
with the tileset. So I'm not sure what was happening over the weekend, or
what changed so it's normal now.

**Comment by AshleyScirra** [comment] 2018-03-12 14:34
Closing, please re-file if you can find a reliable way to reproduce it.

**Closed by AshleyScirra** 2018-03-12 14:34 UTC
Labels: can't reproduce
