### ISSUE TITLE
Construct crashes when entering a number after a left parenthesis, before an object name

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#1380] opened 2018-03-13 20:26 UTC
## Problem description

Entering a "1" after the left parenthesis of a term like (Sprite.X) crashes Construct.

## Attach a .c3p

[ParenthesisCrash.zip](https://github.com/Scirra/Construct-3-bugs/files/1808539/ParenthesisCrash.zip)

## Steps to reproduce

1. Create a sprite (i.e. "Sprite")
2. In an event sheet, create an action or condition with an expression field, i.e., System; Compare Two Values.
3. Add an expression with an object name in parentheses. (i.e., (Sprite.X))
4. Move the cursor between the left parenthesis and the start of the expression.
5. Type a number, i.e. (1Sprite.X)

## Observed result

Construct crashes, and my lunch break is over.

## Expected result

My lunch break should continue uninterrupted (ideally indefinitely). Also, Construct should not crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r90-2/main.js, line 2, col 228610
Message: Uncaught InvalidStateError: Failed to execute 'surroundContents' on 'Range': The Range has partially selected a non-Text node.
Stack: Error: Failed to execute 'surroundContents' on 'Range': The Range has partially selected a non-Text node. at Function.ǃgOh (https://editor.construct.net/r90-2/main.js:2:228610) at n.ǃhT (https://editor.construct.net/r90-2/main.js:2:228838) at ǃs.ǃG.ǃV.ǃ$Fg.ǃ$FK (https://editor.construct.net/r90-2/main.js:155:117067) at window.ǃ$FL.ǃ$FM (https://editor.construct.net/r90-2/main.js:155:122952) at ǃ$Fw (https://editor.construct.net/r90-2/main.js:155:119380)
Construct 3 version: r90.2
URL: https://editor.construct.net/r90-2/
Date: Tue Mar 13 2018 13:22:03 GMT-0700 (Pacific Daylight Time)
Uptime: 313 s

Platform information
Browser: Chrome
Browser version: 65.0.3325.146
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36
C3 release: r90.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment] 2018-03-14 15:26
Closed as duplicate of #1373. Which will be fixed in r91.

**Closed by shortercode** 2018-03-14 15:26 UTC
Labels: duplicate
