### ISSUE TITLE
Groups and local variables bug

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#3330] opened 2019-09-13 14:51 UTC
## Problem description
when i move my local variable above a group while both are inside the same group,
the parent group goes poof with everything inside of it too.
when i press ctrl+z, it duplicates the parent group and makes everything a child of itself so there's two parent groups, one inside the other and they'Re duplicates.

it's consistent I made it happen twice in a row

![image](https://user-images.githubusercontent.com/32940085/64871972-50838f80-d614-11e9-87c8-7c9da9ea7284.png)

## Attach a .c3p
I don't have time to do it right now but im leaving it here to add to later. 

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: cannot undelete active project object @ Error: cannot undelete active project object at t.ǃoiK (https://editor.construct.net/r164-3/projectResources.js:1:23952) at t.ǃoiK (https://editor.construct.net/r164-3/projectResources.js:1:260825) at t.ǃoiK (https://editor.construct.net/r164-3/projectResources.js:1:260859) at t.ǃoPz (https://editor.construct.net/r164-3/projectResources.js:1:23812) at t.ǃoPz (https://editor.construct.net/r164-3/projectResources.js:1:260733) at ǃJC.ǃio.ǃtSX (https://editor.construct.net/r164-3/projectResources.js:1:547224) at window.ǃo_q.ǃoja (https://editor.construct.net/r164-3/projectResources.js:1:544530) at e.ǃoja (https://editor.construct.net/r164-3/projectResources.js:1:50212) at window.ǃwrV.ǃoja (https://editor.construct.net/r164-3/main.js:210:97058) at Array. (https://editor.construct.net/r164-3/main.js:210:61931)
Stack: Error: cannot undelete active project object at t.ǃoiK (https://editor.construct.net/r164-3/projectResources.js:1:23952) at t.ǃoiK (https://editor.construct.net/r164-3/projectResources.js:1:260825) at t.ǃoiK (https://editor.construct.net/r164-3/projectResources.js:1:260859) at t.ǃoPz (https://editor.construct.net/r164-3/projectResources.js:1:23812) at t.ǃoPz (https://editor.construct.net/r164-3/projectResources.js:1:260733) at ǃJC.ǃio.ǃtSX (https://editor.construct.net/r164-3/projectResources.js:1:547224) at window.ǃo_q.ǃoja (https://editor.construct.net/r164-3/projectResources.js:1:544530) at e.ǃoja (https://editor.construct.net/r164-3/projectResources.js:1:50212) at window.ǃwrV.ǃoja (https://editor.construct.net/r164-3/main.js:210:97058) at Array. (https://editor.construct.net/r164-3/main.js:210:61931)
Construct 3 version: r164.3
URL: https://editor.construct.net/index.html
Date: Fri Sep 13 2019 10:44:58 GMT-0400 (Eastern Daylight Time)
Uptime: 18513.3 s

Platform information
Browser: Chrome
Browser version: 76.0.3809.132
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
C3 release: r164.3 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment] 2019-09-13 14:59
This sounds very much like a duplicate of #3325 which @AshleyScirra has fixed for the next release. As this appears to be a slightly different reproduction I won't close it immediately. I am assigning to Ashley to review it instead.

@eleanorawesome I would advise looking at the comment Ashley gave in the linked issue, as well as the reproduction I gave to see if it matches your issue.

**Comment by AshleyScirra** [comment] 2019-09-13 15:05
It may be a duplicate, but if it's not, there is no project attached so there is no way for us to investigate it. Please ensure you can follow all the guidelines before filing an issue, otherwise the report is probably useless.

**Closed by AshleyScirra** 2019-09-13 15:05 UTC
Labels: no repro
