### ISSUE TITLE
many crashes when running android software

### ISSUE THREAD

**Issue by ERAgames777** [Scirra/Construct-3-bugs#3128] opened 2019-07-12 06:49 UTC
When people run the game on android about 50% of the number of installations fail, I opened crash reports in google developer and this is what i see:
![er1](https://user-images.githubusercontent.com/33450672/61108152-04449380-a49b-11e9-9e91-9285d14bac43.png)
![er2](https://user-images.githubusercontent.com/33450672/61108153-04449380-a49b-11e9-9c00-e08f6975d580.png)
![er3](https://user-images.githubusercontent.com/33450672/61108154-04dd2a00-a49b-11e9-80aa-6e1d73879bf5.png)
![er4](https://user-images.githubusercontent.com/33450672/61108156-04dd2a00-a49b-11e9-8986-da92beb90ea7.png)

**Comment by QuasarX** [comment] 2019-07-12 09:11
What is your game name and store URL?

**Comment by ERAgames777** [comment] 2019-07-12 10:19
1- construct3, construct2runtime, stable-r157
2- from unofficial plugins: this behavior is [litetween()](https://www.construct.net/en/forum/extending-construct-2/addons-29/behavior-litetween-48240) and plugin BHT Smart Random [()](http://blackhornettechnologies.com/construct2/plugins/BHTSmartRandom.aspx)
from official plugins: this AJAX; Array; Audio; Browser; GooglePlay; LocalStorage; MobileAdvert; MobileIAP; Touch.
3- game name is "Fishing rain" [()](https://play.google.com/store/apps/details?id=com.eragames.fishingrain)

**Comment by shortercode** [comment] 2019-07-12 10:39
I'm afraid this crash reports only contain references to the Android internals, so we have pretty much nothing to go on here.

I don't like closing issues like this, as there is obviously a problem, but other than blindly testing every aspect of your project I'm not sure what I can do to resolve this. Are you able to get any more details from the crash reporting system?

It does occur to me that it is quite similar to #3042, which has more informative stack traces. However, the hope was that it would be resolved in r157 once we moved to the latest version of Admob ( awaiting feedback to confirm ). Additionally "ClassNotFoundException" is a pretty generic java error, so it might not be related.

**Comment by ERAgames777** [comment] 2019-07-12 11:18
@shortercode
Yes, I can get more detailed information about failures, but how can I do this for you?

**Comment by shortercode** [comment] 2019-07-12 11:32
I'm going to be honest, I'm not sure. If you can find any stack that look different, or find something that can get more information from those stack traces perhaps?

**Comment by QuasarX** [comment] 2019-07-12 11:57
I just installed and it is crashed.
ZTE Blade S6 - Android 5.0

**Comment by ERAgames777** [comment] 2019-07-12 12:23
@QuasarX Yes, all failures occur when you first start. On the second launch, for some reason, the game starts working)

**Comment by ERAgames777** [comment] 2019-07-12 12:26
@shortercode 
Yes, I will watch crash reports and look for different stacks.

**Comment by ERAgames777** [comment] 2019-07-12 12:41
@shortercode
Here I found a couple of dissimilar failures:
![er1](https://user-images.githubusercontent.com/33450672/61128765-4508d080-a4cc-11e9-8ccd-2d1aaec11aa1.jpg)
![er2](https://user-images.githubusercontent.com/33450672/61128767-45a16700-a4cc-11e9-8b87-a5c09fb07ff6.jpg)
![er3](https://user-images.githubusercontent.com/33450672/61128768-45a16700-a4cc-11e9-9fe4-72d29449391a.jpg)

**Comment by shortercode** [comment] 2019-07-12 12:59
The first one is interesting, a crash in the G play plugin. I can probably resolve it, but I need to have a think about how it could have gotten into such a weird state.

The other 2 are OpenGL issues coming from the OS.

@ERAgames777 Have you been able to reproduce this on one of your test devices? Curious if you get the same situation as @QuasarX

**Comment by shortercode** [comment] 2019-07-12 13:02
Sorry I missed this comment

> @QuasarX Yes, all failures occur when you first start. On the second launch, for some reason, the game starts working)

If you have a reproduction with the app locally can you please reduce it down to a minimal reproduction and share it with me please.

**Comment by ERAgames777** [comment] 2019-07-12 13:36
@shortercode
Write your email so that I can send you a file.

**Comment by shortercode** [comment] 2019-07-12 17:10
iain@scirra.com

**Comment by ERAgames777** [comment] 2019-07-12 19:31
@shortercode 
I sent you a project, replacing some of the project properties with "test". I also created another very important problem ([this problem](https://github.com/Scirra/Construct-3-bugs/issues/3062)), but you closed it because I didn’t provide the project, you may now be able to understand the reason for the reason that you have a project.

**Comment by ERAgames777** [comment] 2019-07-14 08:23
@AshleyScirra 
I tried to export without minifying the script and users had 0% failure. Apparently the litetween or BHT random plugin has some kind of malfunction when turning on the minification.

**Comment by shortercode** [comment] 2019-07-15 10:28
Thanks for sending it over @ERAgames777 I will take a look today.

The other issue is assigned to @AshleyScirra , he closed it because your bug report was literally just a crash report with a brief description. He will want a new bug report with all the parts of the template completed, ideally it should have a _minimal_ project that only includes the content required to demonstrate the bug.

**Comment by shortercode** [comment] 2019-07-15 10:42
@ERAgames777 the project you provided requires 3rd party addons, I cannot use it.

**Comment by ERAgames777** [comment] 2019-07-15 10:51
@shortercode 
You can see links to these plugins in response: https://github.com/Scirra/Construct-3-bugs/issues/3128#issuecomment-510834789

**Comment by ERAgames777** [comment] 2019-07-15 10:59
@shortercode in the comments there are links to plugins
 https://github.com/Scirra/Construct-3-bugs/issues/3128#issuecomment-510834789

**Comment by shortercode** [comment] 2019-07-15 11:06
@ERAgames777 what export settings are you using with the project?

**Comment by ERAgames777** [comment] 2019-07-15 11:13
@shortercode
![image](https://user-images.githubusercontent.com/33450672/61212299-48de6200-a71b-11e9-863a-c7bb02aec140.png)

**Comment by shortercode** [comment] 2019-07-15 12:00
How about the "cordova options" ?

**Comment by ERAgames777** [comment] 2019-07-15 12:03
@shortercode 
![image](https://user-images.githubusercontent.com/33450672/61214819-6531cd00-a722-11e9-86e1-a30a18f658bb.png)

**Comment by shortercode** [comment] 2019-07-15 14:13
Thanks. I haven't managed to replicate any crashes yet, but trying a few things.

Incidentally do you mean to close your application after showing an interstitial advert? When I close the languages menu it shows an advert, then closes the app. I checked the event sheet and I can see an event for this so it's not a crash or anything.

**Comment by ERAgames777** [comment] 2019-07-16 08:53
@shortercode 
Yes, after displaying ads, the application should be closed on the menu of languages. Failure occurs when you first start the application, with the second launch of the application will not fail. I want to note that only 50% of android devices will fail, perhaps your device does not fall into these lists. Maybe the failure occurs due to the large processing of the cells of the array array, since I have an array of 1000x50, which is probably why. Although if you do not select the option to minify the script, then there will be 0% of failures.

**Comment by shortercode** [comment] 2019-07-16 10:31
Yes I'm aware of when the failure should occur, but haven't seen it on any of the devices I've tested yet. There's a couple more for me to try, but I'm starting to think I need to try a

When the app started I tried clicking a few buttons before the application closed, and I assumed it was a crash before I back tracked it and realised it was as designed. If memory serves the close button wasn't in English, I assumed it was a "cancel" not a "close app". You might want to reconsider that flow, but that's unrelated to this bug.

Given where the crash occurs I would think it's entirely unrelated to JS minification or anything to do with JS. If it is... then it's some sort of really obscure cascade failure.

**Comment by AshleyScirra** [comment] 2019-08-20 14:29
This issue is ~1 month old and still has 'need info' and 'no repro' tags, so normally we'd close the issue as it is not actionable. @shortercode is there anything else to follow up here or can the issue be closed?

**Comment by shortercode** [comment] 2019-08-20 14:42
It reached a bit of an impasse, there is obviously a problem but I haven't been able to replicate anything. I've been meaning to try some release builds on device but haven't god around to it, but if I can't replicate anything after that it can be closed I think.

**Comment by shortercode** [comment] 2020-01-23 19:20
I haven't been able to replicate these issues, and it's not immediately clear if they are still occurring. I'm going to close this issue as unable to replicate. If we get a cleared replication in future we can look into it again.

**Closed by shortercode** 2020-01-23 19:20 UTC
Labels: Android, no repro
