### ISSUE TITLE
Issue with Properties Bar on iOS in desktop UI mode

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1502] opened 2018-04-20 13:27 UTC
## Problem description

*Enter a concise description of your problem here*

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Add a new sprite to your project
2. Select it from the project object tree
3. Properties window not updated to the properties of the sprite, the sprites are not available for properties

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2018-04-20 15:17
Can't reproduce on an iPad Air 2 running iOS 11.3. Tapping a Sprite in the Project Bar correctly switches the Properties Bar to the Sprite's properties. Did you include all the necessary steps?

**Comment by AshleyScirra** [comment] 2018-04-23 10:26
It's not clear what the problem is or how to reproduce it, so closing. We can investigate if enough details are provided that we can observe the problem.

**Comment by zumwaltwood** [comment] 2018-04-23 11:42
Your choice, I've given instructions, just create the shortcut like your
instructions say on the ipad, then use it, when you do, log in, then try to
cloud save, that's broken, plus it always logs you out

**Comment by zumwaltwood** [comment] 2018-04-23 13:03
Crap, well the properties window steps are reproducable every time in
safari on ipad 12.9 inch retna model MPKY2LL/A ios 11.3

Open Safari
Use R95.2 because R96 will not load on my ipad, that always shows error,

"Error loading! Try disabling browser addons, they can sometimes break
Construct 3. Unhandled promise rejection: TypeError: Type error"

Then in R95.2 open any sprite, save it, select something else like the
keyboard, then reselect the sprite, the properties window does not change
to the sprite properties but instead stays on the keyboard properties.

**Comment by zumwaltwood** [comment] 2018-04-23 13:09
fixed the R96 problem, anyone with that needs to totally clear their
safari cache, then re-download

**Comment by zumwaltwood** [comment] 2018-04-23 13:30
R96, same problem in Firefox on iPad, no sprite properties available

**Comment by AshleyScirra** [comment] 2018-04-23 14:15
It sounds like you are describing additional steps that weren't in the original report. I'd suggest either editing the original report to include the complete steps or filing a new report that is as clear and comprehensive as possible, to ensure we can effectively deal with the report. Otherwise if all the information is fragmented across several comments, it's difficult to understand what you really mean.

**Comment by zumwaltwood** [comment] 2018-04-23 14:44
Nope, nothing new, the properties window doesn't show sprite details, ill
create another ticket later if that's what you want, but i confirmed it
exists on R96 with chrome, safari, Firefox, all on ipad have this issue.

**Comment by zumwaltwood** [comment] 2018-04-23 16:02
You can simply follow my initial report and get exactly the same results,
open any project or make one, select any sprite and you will see no
properties exist for it, basically the properties window isn't updated when
sprites are selected, in any browser on the ipad, I'm at work so i can't
check browser on the desktop right now, sorry.

This problem persists into R96

**Comment by AshleyScirra** [comment] 2018-04-23 16:02
I'm afraid I could not reproduce the problem following your original report. Unless I can, there is not much we can do.

**Comment by zumwaltwood** [comment] 2018-04-23 16:08
I've sent many screenshots, and now I've sent screenshots of the problem
using 3 different browsers and R96, are you using the full desktop user
interface?

**Comment by zumwaltwood** [comment] 2018-04-23 16:10
only option i probably have left is to video record the problem when i get
home, post it to YouTube and submit that, this is fully repeatable issue on
safari, Firefox and chrome so far, all on the 12.9 inch ipad

**Comment by zumwaltwood** [comment] 2018-04-23 16:14
Actually, downloading techsmith capture on the ipad now for this

**Comment by zumwaltwood** [comment] 2018-04-23 16:46
https://youtu.be/qMbG7ZazZBc

There you go, a video about the properties, also one showing the sprite
sheet locking up but I think you already can reproduce that

https://youtu.be/qhFA3t2LmTo

**Comment by AshleyScirra** [comment] 2018-04-23 17:03
So you're using iOS but you've switched the UI to desktop mode? That's the step I was missing, I was looking at it in the default mobile view. This is why we need clear information about how to reproduce the problem!

FYI due to Apple's restrictions, both Chrome and Firefox on iOS are actually just skins for Safari. They're not actually different browsers, so there's not much point testing them in addition to Safari on iOS, and they'll both still be affected by Safari bugs on iOS.

**Comment by zumwaltwood** [comment] 2018-04-23 17:16
Mobile ui is useless for me the way i work, nothing i do will be in the
mobile ui.
My fault
Jonathan Wood

**Comment by AshleyScirra** [comment] 2018-04-25 17:14
Still can't reproduce on an iPad Pro running iOS 11.3 set to desktop mode. The Properties Bar always updates as expected. I really cannot see anything wrong.

I double-checked the video you provided and it looks like you first deleted all the instances from the layout. When there are no instances there is nothing to select and so the properties do not update. This was not included in your steps to reproduce. If I follow the steps you gave, everything works correctly. Please take care to ensure you mention everything necessary to reproduce the problem.

**Closed by AshleyScirra** 2018-04-25 17:14 UTC
Labels: iOS, not a bug

**Comment by zumwaltwood** [comment] 2018-04-25 17:38
All sprites have this issue in desktop ui mode, you can not update any
properties unless you add it to the scene itself, then you only have the
properties for that instance.

**Comment by AshleyScirra** [comment] 2018-04-25 17:53
Yes, that's exactly what I was talking about. In fact the same issue is filed here: #1305

**Comment by zumwaltwood** [comment] 2018-04-25 18:11
The point is, the prefab sprite should be able to have its default
properties set, but you can't set them, you can only set the instance
properties if you drag it on the screen, that's no way by design, because
you can't fix default properties.
