### ISSUE TITLE
Remote preview update has rare crash.

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1112] opened 2017-12-19 12:51 UTC
## Problem description

Every 1 in ~ 20 refreshes after the project has been updated by the host, C3 crashes on the host's computer.

## Attach a .c3p

Happens with the realtime shooting multiplayer template.

## Steps to reproduce

1. Start remote preview
2. Start the game using the remote preview link on a computer
3. Update the game and build (F4)
4. Refresh the game on the computer
5. repeat 3-4 until crash, it happens at Loading Scripts on the computer, the loading freezes there and C3 crashes.

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Failed to fetch @ TypeError: Failed to fetch
Stack: TypeError: Failed to fetch
Construct 3 version: r73
URL: https://editor.construct.net/index.html
Date: Tue Dec 19 2017 14:47:52 GMT+0200 (GTB Standard Time)
Uptime: 3421 s

Platform information
Browser: Chrome
Browser version: 63.0.3239.84
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
C3 release: r73
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by JeFawk** [comment] 2017-12-19 12:52
This is exactly the issue I get when sometimes the preview (the normal one) won't load anything. I filed a bug and it was suggested that some chrome extension has a problem (connection dropped or something) or that my router has a problem.

**Comment by JeFawk** [comment] 2017-12-19 13:28
On the client that created the crash in the console I just get the multiplayer "Peer connection established to host" and stuck at

![image](https://user-images.githubusercontent.com/7268697/34159256-45e5c59c-e4d1-11e7-9f87-a00d266bc4f6.png)

**Comment by AshleyScirra** [comment] 2017-12-19 15:59
I repeated it 10 times and it worked fine every time. Can you open Chrome's dev tools for C3, reproduce the issue, then look for the failing request in the network tab? (It should show up red.) The error report just says "failed to fetch", knowing at least the failing URL would be a big help.

**Comment by JeFawk** [comment] 2017-12-19 21:15
I will try in the following days. I saw that it says only failed to fetch, figured it's kinda useless.

**Comment by JeFawk** [comment] 2017-12-20 08:23
I managed. I used the project I sent you via email a few days ago and 3 devices. This time it crashed on my tablet.

This is from C3 that had the remote preview on. It seems it doesn't matter if you updated the project or not.

I'll keep C3 crashed opened for a while if you need more info from somewhere else.

![image](https://user-images.githubusercontent.com/7268697/34197263-5574fec2-e56e-11e7-982f-7c7e436cd6d5.png)

And console

![image](https://user-images.githubusercontent.com/7268697/34197288-7255f762-e56e-11e7-8144-32b69ebf63d7.png)


And this is on the client side that crashed it.


![new_bitmap_image](https://user-images.githubusercontent.com/7268697/34197555-b2747930-e56f-11e7-8861-c12890093535.jpg)


![new_bitmap_image_2](https://user-images.githubusercontent.com/7268697/34197557-b6e5a91c-e56f-11e7-812c-a3a1fb8ded2b.jpg)


Error report information
Type: unhandled rejection
Reason: Error: Failed to fetch @ TypeError: Failed to fetch
Stack: TypeError: Failed to fetch
Construct 3 version: r73
URL: https://editor.construct.net/index.html
Date: Wed Dec 20 2017 10:10:11 GMT+0200 (GTB Standard Time)
Uptime: 932.7 s

Platform information
Browser: Chrome
Browser version: 63.0.3239.84
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
C3 release: r73
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by JeFawk** [comment] 2018-01-05 07:00
Still happening in r75

Error report information
Type: unhandled rejection
Reason: Error: Failed to fetch @ TypeError: Failed to fetch at n (https://editor.construct.net/r75/main.js:2:193768) at 
Stack: TypeError: Failed to fetch at n (https://editor.construct.net/r75/main.js:2:193768) at 
Construct 3 version: r75
URL: https://editor.construct.net/index.html
Date: Thu Jan 04 2018 20:54:19 GMT+0200 (GTB Standard Time)
Uptime: 10054 s

Platform information
Browser: Chrome
Browser version: 63.0.3239.84
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
C3 release: r75
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment] 2018-01-16 19:19
Have you seen this happen since r76? In that release we added some extra code so that if anything fails during launching any kind of preview, it falls back to showing a "Failed to start preview" message. That ought to catch this type of error, I think (but haven't been able to reproduce yet to verify).

**Comment by JeFawk** [comment] 2018-01-16 19:29
This?

![image](https://user-images.githubusercontent.com/7268697/35008124-2ddd4b7a-fb04-11e7-98bd-a28c75b2748b.png)

I think i filed a bug about this that when you leave the remote preview up for longer than 1 hour or so the link doesnt work anymore and this screen appears for clients trying to join.

Was this to avoid the crash?

**Comment by AshleyScirra** [comment] 2018-01-16 19:37
This is separate to the host timeout. In this issue I'm concerned with the crash with the message "failed to fetch". Have you seen that in r76+?

**Comment by JeFawk** [comment] 2018-01-16 19:38
Not yet. I've been using remote preview a decent amount too.

**Comment by AshleyScirra** [comment] 2018-01-17 00:15
OK, I'm guessing this has been mitigated since r76 then, so closing. If you run in to it again let me know.

**Closed by AshleyScirra** 2018-01-17 00:15 UTC
Labels: can't reproduce

**Comment by JeFawk** [comment] 2018-01-29 23:34
It happened again for the first time after it was fixed. The client did not have any error message, was just stuck in the Construct 3 loading screen while the app crashed in the background.

Error report information
Type: unhandled rejection
Reason: Error: Failed to fetch @ TypeError: Failed to fetch
Stack: TypeError: Failed to fetch
Construct 3 version: r81.2
URL: https://editor.construct.net/index.html
Date: Tue Jan 30 2018 01:31:36 GMT+0200 (GTB Standard Time)
Uptime: 27130.7 s

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r81.2
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by JeFawk** [comment] 2018-02-18 06:10
This is still happening, and started becoming quite often. 3 crashes just in the past 6 hours.

**Comment by AshleyScirra** [comment] 2018-02-18 14:05
Please file a new issue following all the guidelines. In particular please look in the browser console/network tab to get more useful information about exactly which request failed and why - the crash report is not useful in this case.

**Comment by JeFawk** [comment] 2018-02-18 17:24
This happens randomly, what should I write at reproduction steps to be useful?

Also maybe you can point me towards the right direction regarding more info. I provided what you asked for so I wouldn't really know where to start.
