### ISSUE TITLE
[r212] Containers containing an array/dictionary are broken, lead to bugs and crashes

### ISSUE THREAD

**Issue by birbdoy** [Scirra/Construct-3-bugs#4144] opened 2020-08-22 20:21 UTC
## Problem description

When in the current layout there's an object (e.g. sprite or tiled background) in a container also containing an array or a dictionary things start to break. There might be more but this is what I've found so far: 
- changing/restarting the layout crashes the game
- deleting the object during runtime only deletes one instance at a time instead of all which are currently picked

## Attach a .c3p

[ContainerBugs.zip](https://github.com/Scirra/Construct-3-bugs/files/5113913/ContainerBugs.zip)

## Steps to reproduce

1. Open LayoutRestart.c3p
2. Start and hit any key on your keyboard
3. Open Destroy.c3p
4. Start and hit any key on your keyboard multiple times

## Observed result

LayoutRestart.c3p: the game crashes

Destroy.c3p: only one instance gets deleted per hit

## Expected result

No crashes or weird behaviors

## More details

**Affected browsers/platforms:** Chrome/Firefox

**First affected release:**  worked in r211, stopped working in r212

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 84.0.4147.135
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
C3 release: r212 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 267 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 3GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2020-08-24 10:56
Duplicate of #4137. Fixed in the next beta.

**Closed by DiegoScirra** 2020-08-24 10:56 UTC
Labels: duplicate
