### ISSUE TITLE
Tilemap tiling issue

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-3-bugs#4244] opened 2020-09-24 21:45 UTC
After testing multiple versions of my project (some old, some new) the following issue arises in each of the versions with my procedural generation setup:

Open in version 210.2 Stable or 216: Tiles maintain the expected order (trees don't overlap caves for example)

Open in version 217: When setting tiles they no longer order despite using the exact same method (exact same project), the pattern is lost, caves are overlapping trees, trees are on the wrong land areas, the map is ends up being filled to the brim as I continue scrolling.
![ProceduralGenErrorImage](https://user-images.githubusercontent.com/37854520/94203899-1b3f8d80-fe75-11ea-9368-a491f68bb6d4.png)

As usual, I don't feel comfortable releasing my project publicly, if more info is required let me know. 

## Steps to reproduce

1. Preview
2. Scroll with camera
3. Tiles generate while scrolling
4. Pattern breaks in r217

## Observed result

There is no longer a pattern, tiles with little to no association end up mixed together.

## More details
I tried with a few different procedural gen projects and some are fine while others have problems, however my main project stores the tile IDs of the tile map tiles in arrays unlike in the other projects. Considering that one of the changes in r217 deals with setting tile ID actions for tile maps I think this might be a potential culprit. 

**Affected browsers/platforms:** Chrome, Microsoft Edge

**First affected release:** <!-- Worked in r210.2, r216 issues arise in r217

## System details
<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 85.0.4183.121
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
C3 release: r217 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 269 gb
Storage usage (approx): 791 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon(TM) Vega 8 Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by OneRepCloser** [comment] 2020-09-25 06:52
Question: Is setting a tile to -1 inappropriate in r217?

**Comment by OneRepCloser** [comment] 2020-09-25 07:10
After further testing I may have identified the issue. In r217, I'm unable to erase tiles either by setting their tile ID or erasing them directly. This leads to the convoluted mixing of tiles as you see in the image above because they are carrying over without being erased.

**Comment by OneRepCloser** [comment] 2020-09-25 07:16
[TestTileErase_r217.zip](https://github.com/Scirra/Construct-3-bugs/files/5281182/TestTileErase_r217.zip)
[TestTIleErase_r210.2.zip](https://github.com/Scirra/Construct-3-bugs/files/5281183/TestTIleErase_r210.2.zip)

**Comment by OneRepCloser** [comment] 2020-09-25 07:25
I'd like to add on by saying that the bug fix for tile IDs brought in r217 did solve one of the issues I was dealing with where invisible tiles were being registered as solids, making what seemed empty, impassable. 

Thus, hopefully rather than a regression (If this is actually a problem and not just on my end) we can find a way to maintain the tile ID fix, while still allowing for the erasing of tiles.

**Comment by AshleyScirra** [comment] 2020-09-25 12:12
Thanks for the report, this is indeed a regression in r217 caused by the fix for #4216 which accidentally broke erasing tiles. The fix for this is trivial though, so I think we will proceed with the stable release scheduled for next week, and include the fix in that release.

**Closed by AshleyScirra** 2020-09-25 12:12 UTC
