### ISSUE TITLE
Old function plugin still overwrites the new c3_callFunction function

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#2883] opened 2019-04-23 17:55 UTC
## Problem description

Adding the old function plugin to a project overwrites the c3_callFunction function which means that there is no way to call the new functions through JS.

## Attach a .c3p

[c3callfunctionbug.zip](https://github.com/Scirra/Construct-3-bugs/files/3108902/c3callfunctionbug.zip)

The zip contains two c3p files, one with and one without the old function plugin

## Steps to reproduce

1. Preview
2. Look at the console

## Observed result

With the old function, the c3_callFunction function stops calling the new functions

## Expected result

Either we should decide to leave c2_callFunction to old functions and c3_callFunction to the new one, or have the c3_callFunction call both the new and old functions when the old function are in the project.

## More details
I understand there might be some talk about backwards compatibility and whatnot, but I believe that anyone that was using c3_callFunction for the old functions can replace a "3" with a "2" in a fairly short time. Also worst case scenario, the new c3_callFunction checks for new functions first. If none exist with the given name, it checks if c2_callFunction exists and if it does, call it with the given name.
(also pls update the sdk doc page)

**Comment by AshleyScirra** [comment] 2019-04-23 18:27
It's a difficult problem for backwards-compatibility, since existing code expects `c3_callFunction` to call legacy functions, and ideally the API should be identical with built-in functions so existing JS code keeps working even when you switch to builtin functions. Also the name `c2_callFunction` is misleading because the function plugin is still supported in the C3 runtime (for the time being, anyway). It's not possible to resolve the right function from a single call in case a project has both a legacy and builtin function with the same name; and as noted changing the call creates either backwards compatibility problems, or forwards compatibility problems, and also makes it harder to migrate legacy functions to new functions as now you also have to update a bunch of JS code.

So given the thorny issues around it this is currently by design. It's only a problem if you mix old and new functions. I did not expect this to be a major problem - presumably you'd migrate in one go? Do you expect to be using a mix of old and new functions for a long time?

**Comment by skymen** [comment] 2019-04-23 18:37
Well in that case why not make the new functions a new function name then? To avoid overwriting entirely and make the new function clear?

Also I'm not the one who's gonna run into issues with this. Basically I'm making a behavior for Spritefont named Spritefont Deluxe that will have many additional features. Among these features is a tag that will get replaced by a function call's return value. This is designed specifically for dialogue heavy projects that keep all of the dialogues in a big XML and thus can't use the C3 expression syntax
(i.e "Hey, you talked to me " & NPC.talkedTo & " times today.") 

And I can't expect all of these projects to keep to one standard or the other. In fact it is very possible that these projects won't move to new functions for the systems that are too complex to move (for instance, functions that get a variadic number of vars and dynamic var types). So here I am left with a tough decision to make: Do I assume they're using the old functions, or do I assume they're using the new functions? Should I make a different tag for each of them? But in both of these cases I can't control it as long as this is an issue. 

Given that Spritefont Deluxe is specifically designed for big projects in mind, having that kind of limitation is much harder to deal with both for me and the user of the addon.

**Comment by AshleyScirra** [comment] 2019-04-24 10:35
> Well in that case why not make the new functions a new function name then? Something like c3_Function or c3_builtInFunction to avoid overwriting entirely and make the new function clear?

That is still backwards incompatible, just differently. If we do that, the next user will come along and file a bug about how the new builtin functions has a different JS API and requires all the JS to be updated, when it could've stayed the same.

If your main use case is to call functions from a plugin, this API is not designed for that. You should use triggers in your own plugin instead of hacking in function calls. Then your plugin would be entirely self-contained, wouldn't have an unnecessary dependency on unrelated event features, and this problem will solve itself. There isn't even a way to properly specify a builtin function in the SDK (currently intentionally, because I don't see any good reason to do this - are you using a string for a function name or something? that would mean renaming function breaks things again, which they're specifically designed to avoid...)

Given it's not clear that making changes would actually improve things, and your stated use case is not intended to be supported, closing as wontfix.

**Closed by AshleyScirra** 2019-04-24 10:35 UTC
Labels: sdk, wontfix
