### ISSUE TITLE
Editor windows break when restarting C3

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#5010] opened 2021-08-11 13:57 UTC
## Problem description

When I change the UI layout for C3 (to add  a Z order bar, or a bookmarks bar, or a timeline bar), if I restart C3, and the editor has logged me out in the process, I'm left with floating dialogs in the middle of my editor that I cannot remove unless I remove the indexed DB for UI data manually, (or clear the entire cache, which is what most people would do, deleting all of their saved addons in the process)

## Attach a .c3p

n/a

## Steps to reproduce

1. Add a bookmarks bar in the layout
2. restart C3 and switch from stable to beta, so the editor logs you out
3. start project

## Observed result

![image](https://user-images.githubusercontent.com/11213825/129041209-78752fbd-6920-4445-b968-603116b4d64d.png)

A floating dialog with no content

## Expected result

Either remove the bar, and let me add it back when I log back in, or save the layout per account, and load it back when I log back in.

## More details

**Affected browsers/platforms:** Only tested Chrome

**First affected release:** Been happening for a long while, I don't know since when.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment] 2021-08-20 12:08
Can't reproduce this one. The only thing I am seeing is that you can get the timeline bar to be open with a guest account if it was open before refreshing C3.

**Comment by skymen** [comment] 2021-08-20 18:18
Try with bookmarks and z order bar. One of them eventually breaks.

Also it only does that if you log out after refreshing (usually happens when I switch from the beta to the stable branch)

I tried to replicate it, but the output seems to have changed in latest beta? Instead I get this: https://youtu.be/FtgotrqXCdc

<details> <summary> the new error </summary>
Error report information
Type: unhandled exception
File: https://editor.construct.net/r259/main.js, line 1229, col 268
Message: Uncaught TypeError: Cannot read property 'ui' of undefined
Stack: TypeError: Cannot read property 'ui' of undefined at Qf.g.Za.zka.ov (https://editor.construct.net/r259/main.js:1229:268) at Qf.g.Za.zka.ov (https://editor.construct.net/r259/main.js:1245:439) at lga (https://editor.construct.net/r259/main.js:320:235) at qga (https://editor.construct.net/r259/main.js:322:132) at isa.p1 (https://editor.construct.net/r259/main.js:1258:362) at HTMLDocument.fsa (https://editor.construct.net/r259/main.js:1253:42)
Construct 3 version: r259
URL: https://editor.construct.net/r259/
Date: Fri Aug 20 2021 20:15:16 GMT+0200 (Central European Summer Time)
Uptime: 19.5 s

Platform information
Browser: Chrome
Browser version: 92.0.4515.159
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
C3 release: r259 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-26.20.100.6911)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2
</details>

**Comment by DiegoScirra** [comment] 2021-08-20 21:02
I haven been trying out several things in relation to this and #5011 and have found a few different issues already, just not the one I am looking for.

As for the output, it changes with every version because the minification/mangling process is unique to each version, just to make it a little bit harder to reverse engineer C3.

**Comment by skymen** [comment] 2021-08-20 21:51
Lol so that would explain why I wasn't able to reproduce some of the issues consistently across versions.

Welp, I don't think there aren't many ways for me to report more accurately than this, but if you need me for anything just ask and I'll be glad to help.

Overall, all I wanna do is maximize how much control I have over the layout, and minimize the mental headache of having to manually delete my UI data every time one of the 8 random things that can happen to break my layout happens.

**Comment by AshleyScirra** [comment] 2021-09-13 16:09
@DiegoScirra - is there anything else to do on this? It's been left open for about a month with a 'can't reproduce' tag.

**Comment by DiegoScirra** [comment] 2021-09-15 13:12
A bunch of fixes for issues that popped up while I was trying to fix this one went out already. It's hard to tell if the reported issue was fixed though, because I was ever able to reproduce it.

**Comment by skymen** [comment] 2021-09-15 16:03
I don't recall having it in the latest releases. I've had one or two of the issues I mentionned in my other bug report still, but not this one specifically, so maybe it was fixed. I can reopen an issue later if I ever get that specific issue again

**Comment by DiegoScirra** [comment] 2021-09-15 18:15
I'll close this then.

**Closed by DiegoScirra** 2021-09-15 18:15 UTC
Labels: can't reproduce
