### ISSUE TITLE
Cant open from storage in older versions of construct 3

### ISSUE THREAD

**Issue by newman321** [Scirra/Construct-3-bugs#997] opened 2017-11-07 19:48 UTC
## Problem description

title says it all

## Attach a .c3p

no .c3p

## Steps to reproduce

1.open construct 3 r66 https://editor.construct.net/r66/
2. click on open from local storage 
3. it just spins endlessly 

## Observed result

 it just spins endlessly 

## Expected result

be able to open projects 

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 62.0.3202.89
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36
C3 release: r66
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 102 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 330M OpenGL Engine
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 2047
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_disjoint_timer_query
EXT_frag_depth
EXT_shader_texture_lod
EXT_sRGB
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_draw_buffers
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

Google chrome console error : 

Uncaught SyntaxError: Unterminated template literal

some parts of construct 3 are not styled 

![screenshot 2017-11-07 23 18 00](https://user-images.githubusercontent.com/426713/32514328-edf9b9c2-c411-11e7-8a91-8f228ce18ed0.png)

**Comment by AshleyScirra** [comment] 2017-11-07 19:52
It works for me here, and there's none of those styling problems either, but assigning to Iain to double-check.

**Comment by shortercode** [comment] 2017-11-09 12:26
Working fine for me as well, although I did find an unrelated bug in local saves so thanks!

Your styling issues look very strange, and I expect this might be the cause. Not really sure what could be causing this. Do you have this styling issue on all versions of C3? If you run C3 in incognito mode does it work correctly?

**Comment by newman321** [comment] 2017-11-09 15:25
Its fine in incognito mode

**Comment by newman321** [comment] 2017-11-09 19:02
Disabled all extensions but still had problem, thats ok if i be have to use an old version i will clear cache and that probably will solve the problem

**Comment by shortercode** [comment] 2017-11-10 11:31
I guess an extension could have potentially broken your local storage, extensions have far reaching effects and can often break webpages in subtle ways. Makes it hard to predict what's wrong here. 

At the moment the only known forwards compatibility issue is if you go back to before folders existed in C3. As it wouldn't know what to do with the data for folders when it tried to load, I'm not sure how badly it would break though.

Have you succeeded in getting it to work with a cleared cache? If so I'd like to close this as an external issue.

**Comment by newman321** [comment] 2017-11-11 06:57
as i need to re-install all ad-ons and reconfigure all settings after clearing caches i would rather not to clear caches until im have to.

that would be nice if there was an option to export settings and add-ons.

**Comment by shortercode** [comment] 2017-11-13 11:49
That seems fair! I don't like asking people to clear the cache, it's not a great workaround... 

I'll look into how feasible a settings import/export is, I could see it being helpful in bug reports like this as well.

**Closed by shortercode** 2017-11-13 11:49 UTC
Labels: need info

**Comment by newman321** [comment] 2017-12-19 09:45
@shortercode how adding import/export is going ? do you have any plans to add it ?

**Comment by AshleyScirra** [comment] 2017-12-19 11:49
This is a closed bug report. If you want to track a feature idea post it here: https://construct3.ideas.aha.io/
