### ISSUE TITLE
Tile Map Crashing Construct 3

### ISSUE THREAD

**Issue by anonymouslybanana** [Scirra/Construct-3-bugs#4868] opened 2021-06-03 11:05 UTC
## Problem description

When a tile map is added to any project, including a fresh one, using the default tile map, and is dragged onto the project so that it can be drawn on, when clicking the pencil tool the entire program turns red and I receive an error message saying "Oops! Something Went Wrong!"and that construct 3 can no longer continue.

## Attach a .c3p

[https://drive.google.com/file/d/1y2hS1Czp3ipyFLQzklz3MoZ0olFOj4-T/view?usp=sharing](url)

## Steps to reproduce

1. If the tile map is not inserted already, simply add the default tile map to the project
2. Simply press the pencil icon on the tile map tab, and the error will occur
3. I have tested this on multiple projects, even this fresh one, and they all have the same result.

## Observed result

[https://drive.google.com/file/d/1_pLuQ1W4E7gfGrAcUjvH7u1IVGjsGXaS/view?usp=sharing](url)

## Expected result

I expected to be able to use the tile map tool.

## More details

This issue is occurring on the Safari browser, I have not tested it on other browsers. I'm using the most recent release of Construct 3 Free Version. I really hope this issue can be fixed, because I'm required to use this feature for a school project.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r241/components/editors/layoutView/layoutView.js, line 19, col 372
Message: Error: unsupported event object
Stack: nMc@https://editor.construct.net/r241/components/editors/layoutView/layoutView.js:19:344 Cod@https://editor.construct.net/r241/components/bars/tilemapBar/tilemapBar.js:85:115
Construct 3 version: r241
URL: https://editor.construct.net/
Date: Thu Jun 03 2021 03:38:47 GMT-0700 (PDT)
Uptime: 45 s

Platform information
Browser: Safari
Browser version: 14.0.2
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_7
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15
C3 release: r241 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Apple Inc.
Renderer: Apple GPU
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_blend_minmax, EXT_sRGB, EXT_frag_depth, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_standard_derivatives, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, OES_vertex_array_object, OES_element_index_uint, WEBGL_lose_context, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_depth_texture, WEBGL_draw_buffers, ANGLE_instanced_arrays, WEBGL_debug_shaders, WEBGL_debug_renderer_info, EXT_color_buffer_half_float, WEBGL_color_buffer_float

</details>

**Comment by AshleyScirra** [comment] 2021-06-03 11:49
This looks like a duplicate of #4723 and should have already been fixed in r248.

As per the bug report guidelines, please only report issues that still occur in the latest beta release, to avoid filing issues that have already been fixed.

**Closed by AshleyScirra** 2021-06-03 11:49 UTC
Labels: duplicate
