### ISSUE TITLE
Construct Animate crashes after adding keyframe

### ISSUE THREAD

**Issue by TinyMartian99** [Scirra/Construct-3-bugs#5859] opened 2022-07-05 17:19 UTC
## Problem description

Construct Animate crashes after you play an animation in the timeline, pause it, and then try to add a keyframe.

## Attach a .c3p

[SimpleTween.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9048253/SimpleTween.c3p.zip)

## Steps to reproduce

1. Create a simple tween animation
2. Push the play button in the timeline tool bar
3. Pause the animation
4. Try to add a keyframe
5.  App crashes

## Observed result

After I viewed the animation and tried to adding a keyframe, I got an error report and was forced to restart the app.

## Expected result

A keyframe should've been added without error.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://animate.construct.net/r301/projectResources.js, line 1108, col 489
Message: Uncaught TypeError: Cannot read properties of null (reading 'da')
Stack: TypeError: Cannot read properties of null (reading 'da') at d.da (https://animate.construct.net/r301/projectResources.js:1108:489) at d.Nn (https://animate.construct.net/r301/projectResources.js:1091:168) at Nn.next () at m (https://animate.construct.net/r301/projectResources.js:903:118) at m (https://animate.construct.net/r301/projectResources.js:903:190) at m (https://animate.construct.net/r301/projectResources.js:903:153) at d.aab (https://animate.construct.net/r301/projectResources.js:904:19) at O2.mec (https://animate.construct.net/r301/components/bars/timelineBar/timelineBar.js:125:185) at O2.Xi (https://animate.construct.net/r301/components/bars/timelineBar/timelineBar.js:124:156) at f (https://animate.construct.net/r301/components/bars/timelineBar/timelineBar.js:71:107)
Construct version: r301
URL: https://animate.construct.net/r301/
Date: Tue Jul 05 2022 10:06:50 GMT-0700 (Pacific Daylight Time)
Uptime: 6902.1 s

Platform information
Product: Construct Animate r301 (beta)
Browser: Chrome 103.0.5060.114
Browser engine: Chromium
Context: browser
Operating system: macOS 11.6.5
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 16 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (ATI Technologies Inc.)
Renderer: ANGLE (ATI Technologies Inc., AMD Radeon R9 M380 OpenGL Engine, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw
</details>

**Comment by AshleyScirra** [comment] 2022-07-06 11:14
@DiegoScirra - looks like a regression in r299 or so, when the timeline first got the ability to pause playback. We'll need to fix this before the stable release.

**Comment by DiegoScirra** [comment] 2022-07-11 11:09
This will be fixed in the next beta.

**Closed by DiegoScirra** 2022-07-11 11:09 UTC
