### ISSUE TITLE
Platform Sinking Into Jump-Thru Objects At Peak of Jump (Again)

### ISSUE THREAD

**Issue by AySquirrel** [Scirra/Construct-3-bugs#2905] opened 2019-04-30 18:00 UTC
## Problem description

Platform instances will sink into jump-thru objects if the jump-thru object is landed on at the peak of a jump.

## Attach a .c3p

[JumpThruSinkTrial.zip](https://github.com/Scirra/Construct-3-bugs/files/3132491/JumpThruSinkTrial.zip)

## Steps to reproduce

1. Run project
2. Watch each red square jump
3. Press 'R' to restart layout when necessary

## Observed result

Some squares land on the green platform, some squares fall through the platform, BUT a good chunk of the squares get stuck on the platform and 'sink' into it (indicated by the fact that they remain blue instead of changing back to red by either landing or falling)

## Expected result

All of the squares to either land on the green platform or fall through it and revert back to their red color upon doing so

## More details

**Affected browsers/platforms:** 

Chrome, Firefox

**First affected release:** 

r120

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.103
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
C3 release: r147 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 4.4 gb (7.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by SnipG** [comment] 2019-04-30 19:30
On Start of Layout -> set minimum framerate to 61 and it won't happen anymore ;)

**Comment by AshleyScirra** [comment] 2019-05-01 10:19
I still can't reproduce this. I ran the project 10 times and every time all objects returned to a red color. I'm afraid there's nothing we can do unless we have a reliable way to reproduce the problem.

**Comment by SnipG** [comment] 2019-05-01 20:39
It's Pc specific, something to do with dt and how chrome handles it per pc or something, i think.
Example reproduced buggy behavior  everytime on my pc, with all cases AySquirrel posted. 
Anyway, setting fps to 61 fixed it for me on all cases which i tried, even old examples where it bugged. Not sure if it's solid fix.

To speculate a bit, then this behavior could be cause problems with wider range of cases, when using dt and keeping it on default 30. When you make specific logic and you don't consider surrounding world(building logic using time etc): then on some pc player won't jump so high, AI won't reach some range,  AI/Player jump over hole will fail etc. It small margin but as it seems it's hard to reproduce and discover, one could consider logic to be same on all PC.
I did not know it about it neither, but last time i posted my example on same case, you told my AI with double jump does not even reach platform.

For you to see how it reproduce on some pc, is best to use phone or two. I get bugged behavior on my phone too, similarly as on pc. But using 61 framerate setting fixes it. Maybe its sideeffect on weaker gpus and you got some latest geforce 1080 gpu etc.

**Comment by AySquirrel** [comment] 2019-05-01 22:36
Yeah the minimum framerate thing fixing it is super interesting... I tried setting the timescale to 60/61 since that has a similar effect to changing the framerate, and all of the rectangles that stayed blue corrected themselves to red after a few seconds too

I just uploaded the project online and had some of my friends test it, and they got mixed results as well. The sinking apparently does happen on mobile, and one friend who said it looked fine on firefox tried it again on chrome and said then he saw it bug out.  I tried testing that and noticed it definitely does happen a lot more frequently on chrome. So it has to do with different browsers AND different framerates I guess? I'm not really sure what else to try...

**Comment by SnipG** [comment] 2019-05-02 00:19
I checked the Minimum Framerate 61 effect and it seems to apply more stable dt compared to 60 and below, even on mobile(with stable i mean consistent). Not sure what kind math adds in then but it seems to make dt based object moves much more stable and values are same on pc and mobile. When using default framerate 60 or 30, object are placed/moved with different distances depending on pc or mobile(as their dt is not consistent). While having worker enabled with 61 framerate, dt has fickering results and instantly bugs out with your platform example.

Even tested remote preview into Mozilla and it too has correct values(same as chrome) if framerate is set to 61, from correct dt is calculated. while using 60, trows it off a little depending on browser or platform.

From this, framerate/dt could need somekind internal fix (clamping!) So pc ,mobile, or worker mode at 60fps dt is 0.16666 and not something else. Atm it somehow flickers and causing code/behaviors using dt to bug out. From looks of this, not sure if it's something Ashley could even fix.

Image from my test. While using framerate 61 on mobile, dt is same and also the values on red box are same on mobile,chrome, firefox and platform jumpthry example does not bug.. But with default 30/60 they all different and that platform jumpthru example bugs out. 
![TinyTest](https://user-images.githubusercontent.com/28864889/57051157-d7992200-6c88-11e9-9c8d-bf270891144a.jpg)

But clamping values to get same dt values across all device/browser might impact on performance etc, if it's even keep working like that.

**Comment by AshleyScirra** [comment] 2019-05-02 10:16
If it depends on specific dt values it would be essentially nondeterministic, and setting a minimum framerate would remove the nondeterminism. However setting a minimum framerate is a workaround, *not* a fix - don't confuse the two. It could potentially still happen with a minimum framerate set, since the real problem has not been solved.

I think the best way forwards would be to reproduce the problem with a minimum framerate set, which should make the reproduction deterministic (i.e. reliable).

**Comment by AySquirrel** [comment] 2019-05-02 17:45
Setting the minimum framerate to 60 (or anything below) at the start of the layout and then running it, the sinking still occurs on my end on both pc and mobile. It's only when I set it to something higher than 60 and the game begins to run in slow motion that the problem goes away.

**Comment by SnipG** [comment] 2019-05-02 18:26
I can reproduce it with minimum framerate set, but then i had to change a bit jumpthru angle.
Built something into original example.
[Bug_CaseMaker.zip](https://github.com/Scirra/Construct-3-bugs/files/3139414/Bug_CaseMaker.zip)

To make case to reproduce everytime:
* Let example run for sometime.
* When player sinks into jumpthru, note down its values from text object(jump strenght and platform angle, least 5 places after decimal). If player does not sink into jumpthru, then it's something else and does not reproduce after.
*Disable jumpthru angle randomizer and below insert values collected.
*Also Disable Jump strenght randomizer event below.
Now test case, if it does reproduce with all platforms, then additionally:
*Disable all pick object conditions where it compares Player.bugged not equal to 1
*Disable all compares with"Airborne" below the compare player.bugged not equal to 1

Now you should have case that reproduce bug everytime, without layout reset.

**Comment by AshleyScirra** [comment] 2019-05-03 10:25
For the best chance of a fix, the repro should demonstrate the issue immediately, with no user input required.

**Comment by SnipG** [comment] 2019-05-05 04:28
Example with no user input needed. Using it, I can reproduce bugged behavior everytime. It's still chaotic ,so it can't be demostrated immediately, let example run and it finds it pretty fast.
[JumpThruDtBug_HandsFree.zip](https://github.com/Scirra/Construct-3-bugs/files/3145128/JumpThruDtBug_HandsFree.zip)

**Comment by Wackytoaster** [comment] 2019-06-13 18:02
Here is another repro, it should reproduce within a few jumps, but it doesn´t reliably reproduce at any specific value.

[jumpthrough.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3287299/jumpthrough.c3p.zip)

It´s quite an interesting problem. You would guess that there is only two outcomes, either the player lands or he doesn´t. But instead the player enters this weird quantum superposition (lol) where he seems to be both. Some things to note:

- When the player is in this sinking state, he can actually jump. That would mean that he is on a floor since only then jumping is possible (no doublejump), but...
- In the sinking state, **Is on floor** is false. Also **on landed** doesn´t trigger
- Further: If the player sinks down to the floor, **Is on floor** will be true, but **on landed** doesn´t trigger.
- While in the sinking state, the platform behavior shows that it is in **jumping** state

So (assumptions ahead)... my guess is that, possibly because of floating point errors (considering the precise and unreliable nature of the bug) the player **lands** on the platform while **jumping** which was never accounted for. Probably because usually you have to **fall** to be able to land, since jumping implies you are moving away from the floor.

[jumpthrough2.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3287429/jumpthrough2.c3p.zip)

So naturally I went ahead and made the jumpthrough platform move upwards quick enough to catch the player while he is still jumping and lo and behold, again we have this weird sinking state (though sometimes the player just completely ignores the platform)

**Comment by AshleyScirra** [comment] 2019-07-04 16:24
OK, so this is super difficult but I think I've narrowed down what's going on. I couldn't reproduce any problem with @Wackytoaster 's project but I could sporadically reproduce it with @SnipG 's last project. It looks like the unlucky convergence in rare circumstances of a number of factors:

- the vector Y is a small upwards value (i.e. just before the peak of the jump)
- due to taking in to account the acceleration of gravity, the object actually moves *down* a small distance, even though the vector Y is *up*
- the peak of the jump exactly coincides with the top of the jump-thru, meaning it detects itself as being on the floor
- because you can jump upwards through a jump-thru, it only handles landing on them when you are falling (vector Y is *down*) *and* it's *not* already on a floor

The end result is nothing actually handles the "landed on floor" state so it gets stuck with a small upwards vector Y, but sinking slowly down due to the acceleration of gravity.

I added an extra bit of code to try to handle this case for the next release. After watching it for some time it seems to have resolved it, but given the non-deterministic nature of the problem I can't be 100% sure, so marking this issue to check again when the next release is out. It might also have broken something else, in which case we'll probably be really stuck... even after 8 years we continue to find bizarre new edge cases in the Platform behavior - I really can't believe how difficult it has been to get exactly right! By now the code is riddled with handling awful edge cases...

**Comment by Wackytoaster** [comment] 2019-07-04 17:00
I´m surprised you couldn´t reproduce the problem with my project, but either way, good thing you found a solution.

**Comment by AshleyScirra** [comment] 2019-07-15 15:33
r158 is now out, please check again!

**Comment by SnipG** [comment] 2019-07-15 21:42
I think it is fixed now in c3runtime.
Just strange it did not show up before, in 8 year. Because how often it reproduced and how many platformers had been made in c2.

**Comment by AySquirrel** [comment] 2019-07-16 00:15
Oh my gosh it's gone
AHAHAHAHA
IT'S DEAD
IT'S FINALLY DEAD
LET'S GOOOOOOOOOOOO

**Comment by AshleyScirra** [comment] 2019-07-16 09:54
Thanks for confirming!

**Closed by AshleyScirra** 2019-07-16 09:54 UTC
Labels: difficult

**Comment by AshleyScirra** [comment] 2019-07-22 11:46
Just a heads up: we had to change the fix for this issue in r159 because it caused another issue (#3146). As far as I could tell the altered fix still also fixes this original issue as well, but I'm mentioning it just in case anyone spots it coming back.
