### ISSUE TITLE
Extremely weird performance issue (steam/nw.js)

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#5199] opened 2021-11-06 19:15 UTC
## Problem description

I have no idea how or why, but something weird is going on. I'm currently preparing for launch on steam and all (yay) and I've noticed when I test the game through steam, it runs oddly slow. Now, 150fps is ok mostly, but I'm also worried on slower computers it might not be ok anymore. (Not to mention I have a 240hz monitor). But the issue is ONLY in steam.

- In Preview: 240fps (800-900 uncapped)
- raw nw.js export: 240fps
- nw.js export with steam dlls: 150fps
- when downloaded and played through steam: 150fps

So I'm somewhere losing several hundred (or at least  90+) fps? But wait, there's more! I found out how to get those fps back.

**When I include a video in the project, have it play and then pause+hide it. Boom, fps capped at 240 even in steam. What?**
![image](https://user-images.githubusercontent.com/31101309/140621057-621f05d6-3ac1-41d7-84a4-5bf0f55d234f.png)

I really don't know where to even start with this, so I start here. I guess the video thing is a feasible workaround (when I just pause it automatically instead of on button input) But I think there's something going on that should be adressed anyway.

## Attach a .c3p

I can't really attach anything for obvious reasons, but if you need anything I'll mail you project files/exported projects and whatever you might need.

## Steps to reproduce

1. ??
2. ????
3. ???

## Observed result

The game runs slow once steam dlls are added unless there is a video set to pause.

## Expected result

The game to run as fast as expected.

## More details
Followed the steps in this guide (everything works as expected)
https://www.construct.net/en/make-games/addons/84/greenworks/documentation
NW.js 0.52.0
Steamworks SDK v1.50

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 95.0.4638.69
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
C3 release: r270 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 6.3 gb (4.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6079)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Wackytoaster** [comment] 2021-11-06 19:31
Just as a little update. I've now included a video of a cuttlefish in my game that plays offscreen but is paused "on start of layout" and this does indeed fix the issue. :V

**Comment by AshleyScirra** [comment] 2021-11-08 12:41
Aside from the fact there's not enough information to investigate this as per the bug report guidelines, if a normal export is fine, that suggests Construct's code is all working fine. If the problem only happens when Steam is involved, that suggests the problem is caused by Steam. I've heard of the Steam overlay can cause other issues too, so it seems plausible Steam is interfering in some way. Issues caused by Steam will need to be followed up with Valve instead. So closing as the assumption is this is not related to Construct itself.

I guess it might be a weird graphics driver issue too that only comes in to play when Steam is active, but that would still not be caused by Construct, and Valve would still be in a better position to deal with that.

**Closed by AshleyScirra** 2021-11-08 12:41 UTC
Labels: no repro, external

**Comment by Wackytoaster** [comment] 2021-11-09 12:07
Understandable. I will try to raise the issue with steam. I'll update here if I find out anything. I have a feeling though this won't be fruitful. At least there is a mundane workaround, as weird as it may be.
