### ISSUE TITLE
Can't use cloud with desktop version

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#3606] opened 2020-01-23 19:51 UTC
## Problem description

I tried Google Drive, OneDrive and Dropbox and they won't work on the desktop version. It says "Failed to refresh file list" and gives the error below:

![image](https://user-images.githubusercontent.com/2965842/73018303-6b6fd700-3e32-11ea-99b6-719f5208b183.png)

I know Chrome has local file support now but I don't want to use it because it's still in beta. I also like the ability to use external editors in the desktop version.

**Version:** 183.2 - Chromium 79

**Comment by AshleyScirra** [comment] 2020-01-24 10:29
Please try to always follow the bug report guidelines, such as including your system info. It may be your desktop download is out of date. Without more information all I will do is try cloud save, it'll probably work, and then I'll close this as "can't reproduce".

**Comment by bilgekaan** [comment] 2020-01-24 11:59
The desktop version is the latest, Chromium 79. 

Platform info:

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.43.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.43.1 (like Chrome/79.0.3945.79)
C3 release: r183.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 55 gb
Storage usage (approx): 234 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2020-01-24 14:03
I just tried it and it worked fine. I can only guess it's a networking issue or something. We have no way to investigate this further so closing.

**Closed by AshleyScirra** 2020-01-24 14:03 UTC
Labels: can't reproduce, desktop
