### ISSUE TITLE
Minifying project using Physics behavior breaks export

### ISSUE THREAD

**Issue by jakemay74** [Scirra/Construct-3-bugs#560] opened 2017-06-26 19:33 UTC
## Problem description

I exported my project as html5 and uploaded it to bitballoon. When I attempt to load the export from the link it just hangs on a black screen and doesn't even reach the C3 loading screen.  

The project runs fine when previewing the entire project and using remote preview, and the build exports successfully without generating any errors.  

I've tried using builds without using a loader layout and no preloaded sounds, but with the same result.

## Attach a .c3p

https://www.dropbox.com/s/9d5m6t704y3jivf/hypnosprog.c3p?dl=0

Here's the bitballoon link demonstrating the problem: http://hypnosprog01.bitballoon.com/

## Steps to reproduce

1. Open hypnosprog.c3p
2. Export an HTML5 build
3. Upload build (I've only tested on bitballoon)
4. Attempt to open link

## Observed result

Export build fails to start loading.

## Expected result

Build loads. 

## Affected browsers

 Chrome: yes
 Firefox: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Scoremonger** [comment] 2017-06-28 06:25
I was having the same problem today with NW export for win32, but was able to get it to work by disabling javascript minify.

**Comment by jakemay74** [comment] 2017-06-28 08:15
Unticking the export options seems to work for me too.

**Comment by AshleyScirra** [comment] 2017-07-06 11:46
I can reproduce, and it seems to be the Physics behavior that causes it. A minimal repro is just the "Physics basics" template, exporting with minify enabled.

At first look it seems to be a problem caused by our script minification library, so it's not directly our code. It's also running in to issues minifying the big block of asm.js code in the physics behavior, so it could be a tricky one to narrow down...

**Comment by shortercode** [comment] 2017-07-06 11:52
@AshleyScirra should we be miniyfing the asm.js code? Isn't it likely to break the asm validation

**Comment by AshleyScirra** [comment] 2017-07-06 12:18
We've always minified it before and it seemed to work. I think asm.js itself runs the output through a minifier for final builds. Although one workaround might be to make that script external and not minify it, but it's a very large script and minifying does reduce the size a lot.

**Comment by shortercode** [comment] 2017-07-06 12:31
They give you the option of running the closure compiler over the non-asm code but use their own optimiser for the asm part. [emscripten issue 4820](https://github.com/kripken/emscripten/issues/4820#issuecomment-269245836).

It's not really surprising it's large, the asm.js format is excessively verbose for type security...

**Comment by AshleyScirra** [comment] 2017-07-19 14:21
Looking in to this some more, it's tricky to move box2d to an external library, since all the API calls in the behavior itself need to be made minify-proof (i.e. quoted properties). That might still be the easiest thing to do in the short term.

However it also looks like there's a WebAssembly build of box2d available now: https://github.com/kripken/box2d.js/

It appears that has a WASM binary with a separate bindings script. So that should make it easier to minify the bindings only, together with the runtime script. It definitely seems worth minifying the bindings since they tend to use a lot of very long names (e.g. just one name alone is `_emscripten_bind_b2Body_SetLinearDamping_1`).

**Comment by Scott943** [comment] 2017-08-19 13:20
@AshleyScirra @shortercode 

Has this issue been resolved? It would be real nice if we could minify the script with projects with physics, so our projects could run faster and cleaner!

**Comment by AshleyScirra** [comment] 2018-01-12 13:33
This should be fixed in r78 (at last!)

**Closed by AshleyScirra** 2018-01-12 13:33 UTC
Labels: difficult
