### ISSUE TITLE
C3 sometimes crashes

### ISSUE THREAD

**Issue by rogerty** [Scirra/Construct-3-bugs#4913] opened 2021-06-23 09:45 UTC
## Problem description

When I leave C3 open for about 5-15 minutes (AFK), when I return to the computer, I see it has crashed.
C3 dialog: "Oops! Something went wrong."
It's difficult to reproduce, so I cannot answer all questions.
I know that it might be a problem on my side, but I don't know for sure. So that is why I report this to inform you.

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 91.0.4472.114
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
C3 release: r253 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 60 gb
Storage usage (approx): 896 mb (1.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8189)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by henrikszucs** [comment] 2021-06-23 09:50
What crash type is it? Aw snap crash or javascript error? If javascript error you can see in the browser console f12. If chrome "Aw snap" crash you can send in: chrome://crashes/

**Comment by rogerty** [comment] 2021-06-23 09:55
A C3 dialog: "Oops! Something went wrong."
It just happened again, after creating a 3D object in layout view. Here are the details:

Error report information
Type: unhandled rejection
Reason: Error: expected string @ TypeError: expected string at Function.Q.s (https://editor.construct.net/r253/main.js:836:233) at Function.ma.Jtb (https://editor.construct.net/r253/main.js:874:44) at r (https://editor.construct.net/r253/main.js:2278:120) at Yo.J5a.pRb (https://editor.construct.net/r253/main.js:2274:96) at Yo.J5a.ARa (https://editor.construct.net/r253/main.js:1052:274) at mmb (https://editor.construct.net/r253/main.js:1052:102)
Stack: TypeError: expected string at Function.Q.s (https://editor.construct.net/r253/main.js:836:233) at Function.ma.Jtb (https://editor.construct.net/r253/main.js:874:44) at r (https://editor.construct.net/r253/main.js:2278:120) at Yo.J5a.pRb (https://editor.construct.net/r253/main.js:2274:96) at Yo.J5a.ARa (https://editor.construct.net/r253/main.js:1052:274) at mmb (https://editor.construct.net/r253/main.js:1052:102)
Construct 3 version: r253
URL: https://editor.construct.net/r253/
Date: Wed Jun 23 2021 11:53:45 GMT+0200 (Midden-Europese zomertijd)
Uptime: 961.1 s

Platform information
Browser: Chrome
Browser version: 91.0.4472.114
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
C3 release: r253 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8189)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by brushfe** [comment] 2021-06-23 10:16
I just had this error pop up. I opened a project (from a local folder), made a cup of coffee, and then returned to find the error message on screen. No interaction with C3 at all.

Error report information
Type: unhandled rejection
Reason: Error: expected string @ TypeError: expected string at Function.Q.s (https://editor.construct.net/r253/main.js:836:233) at Function.ma.Jtb (https://editor.construct.net/r253/main.js:874:44) at r (https://editor.construct.net/r253/main.js:2278:120) at Yo.J5a.pRb (https://editor.construct.net/r253/main.js:2274:96) at Yo.J5a.ARa (https://editor.construct.net/r253/main.js:1052:274) at mmb (https://editor.construct.net/r253/main.js:1052:102)
Stack: TypeError: expected string at Function.Q.s (https://editor.construct.net/r253/main.js:836:233) at Function.ma.Jtb (https://editor.construct.net/r253/main.js:874:44) at r (https://editor.construct.net/r253/main.js:2278:120) at Yo.J5a.pRb (https://editor.construct.net/r253/main.js:2274:96) at Yo.J5a.ARa (https://editor.construct.net/r253/main.js:1052:274) at mmb (https://editor.construct.net/r253/main.js:1052:102)
Construct 3 version: r253
URL: https://editor.construct.net/r253/
Date: Wed Jun 23 2021 06:14:05 GMT-0400 (Eastern Daylight Time)
Uptime: 301.4 s

Platform information
Browser: Chrome
Browser version: 91.0.4472.114
Browser engine: Chromium
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
C3 release: r253 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Plus Graphics OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

**Comment by Alaadel** [comment] 2021-06-23 16:44
Maybe it is a Chrome issue. Does it happen in other browsers too?

**Comment by TetroniMike** [comment] 2021-06-23 17:23
Same problem in r253 in Chrome, will try another browser, here's my crash log:

`Error report information
Type: unhandled rejection
Reason: Error: expected string @ TypeError: expected string at Function.Q.s (https://editor.construct.net/r253/main.js:836:233) at Function.ma.Jtb (https://editor.construct.net/r253/main.js:874:44) at r (https://editor.construct.net/r253/main.js:2278:120) at Yo.J5a.pRb (https://editor.construct.net/r253/main.js:2274:96) at Yo.J5a.ARa (https://editor.construct.net/r253/main.js:1052:274) at mmb (https://editor.construct.net/r253/main.js:1052:102)
Stack: TypeError: expected string at Function.Q.s (https://editor.construct.net/r253/main.js:836:233) at Function.ma.Jtb (https://editor.construct.net/r253/main.js:874:44) at r (https://editor.construct.net/r253/main.js:2278:120) at Yo.J5a.pRb (https://editor.construct.net/r253/main.js:2274:96) at Yo.J5a.ARa (https://editor.construct.net/r253/main.js:1052:274) at mmb (https://editor.construct.net/r253/main.js:1052:102)
Construct 3 version: r253
URL: https://editor.construct.net/r253/
Date: Wed Jun 23 2021 10:19:00 GMT-0700 (Pacific Daylight Time)
Uptime: 600.6 s

Platform information
Browser: Chrome
Browser version: 91.0.4472.106
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36
C3 release: r253 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA Quadro K2200 Direct3D11 vs_5_0 ps_5_0, D3D11-26.21.14.4112)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2`

**Comment by uboel** [comment] 2021-06-24 04:38
Hello,

Same problem here with Chrome and Firefox, both updated to the latest version.

Here are the debug info:

Error report information

Type: unhandled rejection
Reason: Error: expected string @ Q.s@https://editor.construct.net/r253/main.js:836:233 ma.Jtb@https://editor.construct.net/r253/main.js:874:44 r@https://editor.construct.net/r253/main.js:2278:120 z<@https://editor.construct.net/r253/main.js:2274:96 ARa@https://editor.construct.net/r253/main.js:1052:274 this.mmb@https://editor.construct.net/r253/main.js:1052:102
Stack: Q.s@https://editor.construct.net/r253/main.js:836:233 ma.Jtb@https://editor.construct.net/r253/main.js:874:44 r@https://editor.construct.net/r253/main.js:2278:120 z<@https://editor.construct.net/r253/main.js:2274:96 ARa@https://editor.construct.net/r253/main.js:1052:274 this.mmb@https://editor.construct.net/r253/main.js:1052:102
Construct 3 version: r253
URL: https://editor.construct.net/r253/
Date: Thu Jun 24 2021 06:36:15 GMT+0200 (heure d’été d’Europe centrale)
Uptime: 613.4 s
Platform information

Browser: Firefox
Browser version: 89.0
Browser engine: Gecko
Context: browser
Operating system: Mac OS X
Operating system version: 10
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0
C3 release: r253 (beta)
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Plus Graphics 655
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by JobiDoop** [comment] 2021-06-24 05:24
Hello

Same problem here, using desktop version beta 253r

Error report information
Type: unhandled rejection
Reason: Error: expected string @ TypeError: expected string at Function.Q.s (https://editor.construct.net/r253/main.js:836:233) at Function.ma.Jtb (https://editor.construct.net/r253/main.js:874:44) at r (https://editor.construct.net/r253/main.js:2278:120) at Yo.J5a.pRb (https://editor.construct.net/r253/main.js:2274:96) at Yo.J5a.ARa (https://editor.construct.net/r253/main.js:1052:274) at mmb (https://editor.construct.net/r253/main.js:1052:102)
Stack: TypeError: expected string at Function.Q.s (https://editor.construct.net/r253/main.js:836:233) at Function.ma.Jtb (https://editor.construct.net/r253/main.js:874:44) at r (https://editor.construct.net/r253/main.js:2278:120) at Yo.J5a.pRb (https://editor.construct.net/r253/main.js:2274:96) at Yo.J5a.ARa (https://editor.construct.net/r253/main.js:1052:274) at mmb (https://editor.construct.net/r253/main.js:1052:102)
Construct 3 version: r253
URL: https://editor.construct.net/r253/
Date: Thu Jun 24 2021 08:23:38 GMT+0300 (Arabian Standard Time)
Uptime: 182.2 s

Platform information
Browser: NW.js
Browser version: 0.54.0
Browser engine: Chromium
Context: nwjs
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 32
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@62f83a7521ae1f32e563795732dff0c9da1b660d) NWjs/0.54.0 (like Chrome/91.0.4472.77)
C3 release: r253 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7111)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by armandoalonso** [comment] 2021-06-24 11:40
I am experiencing the exact same behavior on edge, 
what's interesting is if I have 2 tabs open with construct both tabs crash as the same time. with the same error 


Error report information
Type: unhandled rejection
Reason: Error: expected string @ TypeError: expected string at Function.Q.s (https://editor.construct.net/r253/main.js:836:233) at Function.ma.Jtb (https://editor.construct.net/r253/main.js:874:44) at r (https://editor.construct.net/r253/main.js:2278:120) at Yo.J5a.pRb (https://editor.construct.net/r253/main.js:2274:96) at Yo.J5a.ARa (https://editor.construct.net/r253/main.js:1052:274) at mmb (https://editor.construct.net/r253/main.js:1052:102)
Stack: TypeError: expected string at Function.Q.s (https://editor.construct.net/r253/main.js:836:233) at Function.ma.Jtb (https://editor.construct.net/r253/main.js:874:44) at r (https://editor.construct.net/r253/main.js:2278:120) at Yo.J5a.pRb (https://editor.construct.net/r253/main.js:2274:96) at Yo.J5a.ARa (https://editor.construct.net/r253/main.js:1052:274) at mmb (https://editor.construct.net/r253/main.js:1052:102)
Construct 3 version: r253
URL: https://editor.construct.net/r253/
Date: Thu Jun 24 2021 07:36:05 GMT-0400 (Eastern Daylight Time)
Uptime: 900.8 s

Platform information
Browser: Edge
Browser version: 91.0.864.54
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54
C3 release: r253 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by AshleyScirra** [comment] 2021-06-24 13:49
I think this might be something to do with autosave, perhaps when using the cloud autosave. If you're affected, what are your autosave settings and does changing them affect it?

**Comment by uboel** [comment] 2021-06-24 14:20
Hi Ashley,

It also happens when saving on a local drive. I tried both the Cloud and the local save target. I have the auto backup activated to the browser storage.

Kind regards,

Ulric

**Comment by SnipG** [comment] 2021-06-24 15:24
Took 4 min. 2 to retest and 2 to test in incognito mode. Local folder, backup time 2min.

**Comment by JobiDoop** [comment] 2021-06-24 18:17
hello

I just stop the option called (periodically back up active project), in save sittings, and it seem to me works fine the problem did not show up again, maybe right about back up issue.

I am using desktop version. 253r beta

**Comment by uboel** [comment] 2021-06-25 08:01
Hi,

This morning, I also tested disabling the automatic backup feature...I worked more than 2h without a glitch!

Ulric

**Comment by AshleyScirra** [comment] 2021-06-28 14:49
I think this was caused by a Closure Compiler bug incorrectly mangling autosave code on build. I think I found a workaround, but marking to verify when the next release is out.

**Comment by AshleyScirra** [comment] 2021-06-29 14:09
I think this should now be fixed in r254. Can those affected confirming it's working there now?

**Comment by brushfe** [comment] 2021-06-29 20:10
@AshleyScirra So far, so good! Thanks for the quick fix!

**Comment by uboel** [comment] 2021-06-30 09:35
@AshleyScirra The editor is not crashing anymore...but I reactivated the auto backup feature more than an hour ago (first pointing to the browser and now pointing to a local folder) and it seems no backup is performed at all...

![image](https://user-images.githubusercontent.com/28643164/123938098-1aed9900-d997-11eb-89f3-e296f7957538.png)

Ulric

**Comment by AshleyScirra** [comment] 2021-06-30 10:24
Thanks for confirming, closing issue.

As ever if any other issues come up please file a new issue following all the guidelines. It's entirely no autosave will be made for long periods of time: if your project is not yet saved anywhere, or is already saved and has no modifications, Construct won't autosave it (as it either can't or there's no changes worth saving). So it's not necessarily a problem if autosaves aren't made for a while, it depends on what you're doing.

**Closed by AshleyScirra** 2021-06-30 10:24 UTC
