### ISSUE TITLE
It is unable to exit program when there are unsaved changes

### ISSUE THREAD

**Issue by cihanyakar** [Scirra/Construct-3-bugs#1428] opened 2018-03-25 17:07 UTC
## Problem description

You can't close editor without saving the changes.
 
## Steps to reproduce

1. Open a project
2. Make same changes
3. Try close the app without saving 

## Observed result

Endless confirm dialogs...

## Expected result

Only one dialog

## Affected browsers

* Desktop
## System details

Desktop build

**Comment by luisforte** [comment] 2018-03-25 17:14
You dont have the checkbox "Dont show anymore.." ?

**Comment by cihanyakar** [comment] 2018-03-25 17:22
There is. But it is not the solution.I must use task manager to exit.

**Comment by DiegoScirra** [comment] 2018-03-26 10:42
This looks like a duplicate of #1413

**Closed** 2018-03-26 12:53 UTC
Labels: duplicate
