### ISSUE TITLE
Pressing "Esc" wont close a window in a few cases

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#4303] opened 2020-10-22 09:31 UTC
## Problem description

In the latest beta release pressing "Esc" wont close a window depending on the situation. For example, if you create a new sprite, draw a few pixels on it using the brush tool, you wont be able to close the animation editor by pressing "Esc" anymore unless you click outside the canvas. This is not how the editor behaves in the current stable release.

## Attach a .c3p

Can be reproduced on an empty project.

## Steps to reproduce

1. Create a new sprite.
2. Draw a few pixels on it.
3. Press "Esc" to try to close the animation editor Window.

## Observed result

The window wont be close.

## Expected result

The window to be closed.

## More details

**Affected browsers/platforms:** Chrome/Windows 10.

**First affected release:** Works on r218, but is broken on r221.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment] 2020-10-22 14:45
Fixed in the next beta, was a regression in r219 caused by fixing #4261.

**Closed by DiegoScirra** 2020-10-22 14:45 UTC

**Comment by BonzerKitten** [comment] 2020-10-23 01:55
@DiegoScirra Thanks for the fix! Have a great day.
