### ISSUE TITLE
Tweening value to change WarpObject parameters stops working properly after repetitive activation

### ISSUE THREAD

**Issue by marcosfl** [Scirra/Construct-3-bugs#3180] opened 2019-07-31 17:34 UTC
## Problem description

I tried creating an effect using Tween and the WarpObject effect in the player object. The WarpObject effect would start with all parameters set to 0, and the Tween would activate a "value" type that goes from 0 to 1 or from 1 to 0. Then another event would check if this corresponding tween tag was playing. If it was playing, all WarpObject effect parameters would be set to the tag's value. That way, the WarpObject effect would not start or stop instantly, but rather would smoothly set the tween's value, creating a better and smoother effect for some situations in the game.

That's what should happen, but what is really happening is that this effect only works the first time. After that the WarpObject effect just makes the player object "shake". It is not setting the parameters values properly. I've attached a .c3p file representing the issue. 

## Attach a .c3p

[tween effect bug.zip](https://github.com/Scirra/Construct-3-bugs/files/3453108/tween.effect.bug.zip)

## Steps to reproduce

1. Press the keys 1 or 2 to activate the effect using Tween Value and WarpObject
2. The first time, the effect will work fine. Keep pressing 1 and 2 and you'll see that the player object will just start to "shake" once you press the key.

## Observed result

The intended effect works only once. After the first use of the effect, it starts looking weird.

## Expected result

I expect that the effect should work always the same way. It shouldn't look different in the second or third use. It should always be like the first time you activate it. Also, the first time using the effect shows the right way the effect should look. The other attempts just look buggy.

## More details

Affected browsers/platforms (that I've tested): Windows 64 and Google Chrome

First affected release (that I've noticed): r157

I'm currently using the r159 release

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 75.0.3770.142
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
C3 release: r159 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 62 gb
Storage usage (approx): 558 mb (0.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment] 2019-08-12 15:04
Assigning to @AshleyScirra because this isn't really a problem with tweens but with certain effects.

**Comment by AshleyScirra** [comment] 2019-08-15 16:07
The issue is that the warp effect's speed parameter is implemented using a formula proportional to `sin(speed * time)`. This means if you gradually adjust the speed, there is a rippling effect as the phase of the sin curve is essentially moving rapidly across a sine curve.

I don't think it's feasible to fix this, since normally the fix would be to store a time counter and increment it according to the speed, but shader effects have no convenient way to store persistent data like that. They're basically stateless, hence the use of the simple `speed * time` formula.

Your project tries to interpolate all six parameters of the warp effect - you can get a reasonable result if you just interpolate the four non-speed parameters. In fact if you simply want to fade in and fade out a warp effect, you probably only need to adjust the amplitude parameter.

**Closed by AshleyScirra** 2019-08-15 16:07 UTC
Labels: wontfix
