### ISSUE TITLE
C3 Tint which only has one parameter is not compatible with C2 which had 3 parameters , or is just not working

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#659] opened 2017-08-02 19:08 UTC
## Problem description

C3 Tint which only has one parameter is not compatible with C2 which had 3 parameters , or is just not working

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
[tint.zip](https://github.com/Scirra/Construct-3-bugs/files/1195011/tint.zip)

## Steps to reproduce

move sliders in cap3

## Observed result

only red changes

## Expected result

all colors change

this works in C2

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2017-08-03 09:43
Looks like a dupe of #573. In C3 the tint effect has changed from 3 parameters for R, G, B to one color parameter. So you just need to set parameter 0 to something like `rgb(SliderBar.Value, SliderBar2.Value, SliderBar3.Value)`. We should probably document this somewhere though.

**Closed by AshleyScirra** 2017-08-03 09:43 UTC
Labels: duplicate, not a bug
