### ISSUE TITLE
Instance variable description

### ISSUE THREAD

**Issue by Keevle** [Scirra/Construct-3-bugs#1682] opened 2018-06-08 07:26 UTC
## Problem description

I tried to add some description to my instant variable.The desired result was id be able to type in a description but all it does is allow e.I can set the instance variable name to anything

## Steps to reproduce

1.Make a blank sprite
2.Add a instance variable to the sprite
3.Try and add a discription to that instance variable

## Observed result
It only allows you to use the E letter

## Expected result

It would allow me to use any letter
## Affected browsers

* Chrome: yes
* Firefox: N/a
* Edge: N/a
* Safari: N/a

**Comment by AshleyScirra** [comment] 2018-06-08 10:46
Can't reproduce, works fine in Chrome here. No project or system details provided so cannot investigate further, so closing. Try disabling any browser addons you have.

**Closed by AshleyScirra** 2018-06-08 10:46 UTC
Labels: can't reproduce

**Comment by Keevle** [comment] 2018-06-09 09:07
This was using the desktop client
