### ISSUE TITLE
Crash when hitting undo after creating folders and dropping event sheets into them

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#2316] opened 2018-11-15 02:52 UTC
## Problem description

After creating a number of folders and dropping event sheets into them, I hit undo and Construct crashed.

## Attach a .c3p

This can be reproduced with a new project.

## Steps to reproduce

I've gotten this crash with as few as a couple event sheets/folders, but creating three of each as described below seems to consistently crash things.

1. Create a new project.
2. Right click on the "Event sheets" folder in the project view and choose "Add event sheet"
3. Repeat this step to create a third event sheet.
4. Right click on the "Event sheets" folder in the project view and choose "Add subfolder"
5. Repeat this step twice more to create a total of three folders.
6. Click and drag the first event sheet into the first folder.
7. Click and drag the second and third event sheets into the second and third folders, respectively. Note that one or all of the folders will be collapsed.
8. Hit ctrl+z several times to undo all the changes.

## Observed result

When undo hits one of the collapsed folders, Construct crashes.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: overwriting project bar item map entry
Stack: Error at Function.ǃTB$ (https://editor.construct.net/r125/main.js:2:142544) at i (https://editor.construct.net/r125/main.js:2:104360) at https://editor.construct.net/r125/main.js:2:104763 at Object.ǃT$ (https://editor.construct.net/r125/components/bars/projectBar/projectBar.js:1:4313) at Object.ǃbw (https://editor.construct.net/r125/components/bars/projectBar/projectBar.js:1:30504) at Object.f [as ǃitO] (https://editor.construct.net/r125/components/bars/projectBar/projectBar.js:1:17446) at Object.ǃgu (https://editor.construct.net/r125/main.js:81:502970) at Object.ǃitV (https://editor.construct.net/r125/main.js:81:514303) at Object.ǃTKt (https://editor.construct.net/r125/main.js:81:501922) at i.ǃTKt (https://editor.construct.net/r125/main.js:81:82313)
Construct 3 version: r125
URL: https://editor.construct.net/r125/index.html
Date: Wed Nov 14 2018 18:37:27 GMT-0800 (Pacific Standard Time)
Uptime: 60.6 s

Platform information
Browser: Chrome
Browser version: 70.0.3538.102
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
C3 release: r125 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment] 2018-11-15 11:21
This seems quite awkward to reproduce reliably, although I have managed to get it to reproduce a few times. You only need 1 event sheet and folder, but you are right that it seems key that the folder must appear to be in the collapsed state before you hit undo. Collapsing the folder then undoing doesn't seem to be the same.

**Comment by AshleyScirra** [comment] 2018-11-16 12:52
I can't reproduce this - tried several times and even with a mix of collapsed/expanded folders it seems to work fine. Do the reproduction steps actually depend on the specific expand/collapse states? Maybe it can be narrowed down to more specific steps?

**Comment by Scoremonger** [comment] 2018-11-16 17:03
The way I'm getting it is to follow those steps very precisely, as in: once I create the project, immediately right click to create the event sheets, one after the next (i.e., I don't left click on anything at any point), followed by immediately creating the folders, still not left-clicking anything, then finally, while the most recently created folder is still waiting to be renamed, by left clicking and dragging the event sheets into the folders. 

When I do it this way, I always gotten at least one (sometimes two or three) of the folders to appear in a collapsed state after having an event sheets dropped into them. It does seem pretty random as to which folders start collapsed. But for me this always works - maybe a dozen times in a row now. The attached images show the folder states just after dropping in the third event sheet into the third folder on two subsequent attempts.

![2018-11-16 08_28_17-rewsr - construct 3 beta](https://user-images.githubusercontent.com/28039905/48634665-ef9b1480-e97a-11e8-80ff-a70cc00269f2.jpg)
![2018-11-16 08_37_41-adsfads - construct 3 beta](https://user-images.githubusercontent.com/28039905/48634690-fcb80380-e97a-11e8-9509-ac11271e81b2.jpg)

The reproduction steps do depend on the specific expand/collapse states in the sense that if none of the folders appear in a collapsed state after having an event sheet dropped into them, the undo crash won't happen. That, and the crash only happens when you attempt to undo moving an event sheet into one of the folders that begins collapsed. Note that it doesn't matter if the folder in question is still collapsed or not when the undo reaches it - you can expand the folder manually and still get the crash when an undo operation is applied to it. Manually collapsing folders doesn't lead to the crash either.

I have tried narrowing down the steps by doing various permutations of the ones above , but so far I have had no luck getting this to reproduce 100% of the time with fewer than three event sheets/folders or with doing things in a different order.

**Comment by SnipG** [comment] 2018-11-18 17:13
I reproduce this shady bug.
Record  simple video, post video.
[2018-11-18 19-06-53.zip](https://github.com/Scirra/Construct-3-bugs/files/2593008/2018-11-18.19-06-53.zip)
Shady bug goes away ;)

**Comment by AshleyScirra** [comment] 2018-11-19 12:43
It turns out I can reproduce this only in the release builds - our development copies don't reproduce the issue. Which probably means it's another nightmarish minification-related problem...

**Comment by AshleyScirra** [comment] 2018-11-22 17:19
Finally got this to reproduce in a development build! There is hope it may not be minifier related after all. Minimal repro: 
[foldertest.zip](https://github.com/Scirra/Construct-3-bugs/files/2608943/foldertest.zip)

**Comment by AshleyScirra** [comment] 2018-11-22 18:01
Here's the missing repro step:

- Drop the event sheet in to a folder *with the mouse at the very top or bottom of the selection rectangle*. It doesn't reproduce dropping in the middle.

The repro steps were essentially using a random drop location inside the selection rectangle, resulting in a seemingly random reproduction, but it is in fact deterministic based on the drop location.

The reason this is important is the top quarter and bottom quarter of the selection rectangles register as "before" or "after" insert positions, and the middle is "inside". Dropping in "before" or "after" on certain folder types like event sheet folders would hit test as the "before" or "after" position, but actually drop the item inside. The mismatch caused an invalid undo state that crashed when you did undo. It also caused the item to not be expanded, because it only did that for the "inside" insertion.

That was tough - but should be fixed for the next release!

**Closed by AshleyScirra** 2018-11-22 18:01 UTC
