### ISSUE TITLE
Project not loading on iOS 11.2_6 Safari with a .m4a file inside + problem reproducing audio on iOS Safari

### ISSUE THREAD

**Issue by IJCT95** [Scirra/Construct-3-bugs#1452] opened 2018-03-30 19:29 UTC
## Problem description

if you have a project with a .m4a file it wont load in iOS safari when doing the remote preview.
also Construct 3 cant reproduce the file when you click on it.

*Enter a concise description of your problem here*
i have problems reproducing sounds on iOS, i tried attaching 2 files, a .webm and an .m4a to see if that could fix the problem but i found out that the project wont even load on iOS Safari if i have that .m4a file on the project, why is that?

## Attach a .c3p
https://drop.me/aLvnEA

## Steps to reproduce

1. import a .m4a file to construct 3
2. press "remote preview"
3. the game is stuck on the splash screen, doesnt load on **iOS SAFARI** (11.2_6)

## Observed result
the game is stuck on the splash screen, doesnt load on **iOS SAFARI** (11.2_6)

## Expected result

project loads normally

## Affected browsers

* Chrome: yes (only on iOS)
* Firefox: yes (only on iOS)
* Safari: yes (only on iOS)

</details>

**Comment by shortercode** [comment] 2018-04-03 09:43
@IJCT95 How long is this m4a file? iOS has issues when decoding very short m4a audio files. The issue has been around a long time and is unlikely to be fixed.

**Comment by IJCT95** [comment] 2018-04-04 17:25
i didnt knew that, its around 2 seconds or 1 second long, i will test with a longer audio.

**Comment by AshleyScirra** [comment] 2018-04-05 17:40
Works fine for me on an iPad Air running iOS 11.2.6. Can you provide any more details on how to reproduce the problem?

**Comment by AshleyScirra** [comment] 2018-04-11 10:05
Can't see any issue here and lacking further details so closing.

**Closed by AshleyScirra** 2018-04-11 10:05 UTC
Labels: can't reproduce

**Comment by IJCT95** [comment] 2018-04-13 23:05
i found the real problem, i was using the beta desktop version of Construct 3, have a lot of bugs.

**Comment by AshleyScirra** [comment] 2018-04-14 09:16
Please always follow the guidelines since providing the requested platform information would have identified that.
