### ISSUE TITLE
[C3 Desktop] Dialogs Look "Blurry" With Modified Display Scale

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#2199] opened 2018-10-29 16:05 UTC
## Problem description

In Construct 3 Desktop, changing the display scale and restarting C3 in order to apply the changes, results in blurry dialogs. (I'm not sure but icons could be affected as well.)

## Steps to reproduce

1. Open Construct 3 Desktop
2. Change display scale level (Menu > Level > Display scale > Inc/Dec scale)
3. Open "About" dialog or similar
4. Notice strong blur despite the rest of the application being sharp and clear

## Observed result

Dialogs seem to be blurry and not sharp/clear as expected.
![c3 display scale](https://user-images.githubusercontent.com/15656049/47663301-f49b4e00-db9c-11e8-8165-085709782a11.PNG)

## Expected result

Dialogs should not be blurry with a modified display scale.

## Affected browsers

* NW.js: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.33.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@8920e690dd011895672947112477d10d5c8afb09) NWjs/0.33.3 (like Chrome/69.0.3497.100)
C3 release: r123 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 117 gb
Storage usage (approx): 512 kb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2018-10-29 17:17
I think this might be caused by the same underlying problem as #2198

**Comment by AshleyScirra** [comment] 2018-11-07 15:50
The steps to reproduce don't include "reload Construct 3". If you're not doing that after changing the zoom level, then things may indeed look blurry until you reload C3. Otherwise it's likely the same cause as #2198 and should be fixed in the next build.

**Closed by AshleyScirra** 2018-11-07 15:50 UTC
Labels: desktop, difficult
