### ISSUE TITLE
Layout resets every now and then.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4087] opened 2020-08-03 14:48 UTC
## Problem description

Sometimes my layout resets and today specially this weird thing happened, where a window was empty and immovable:
![bug](https://user-images.githubusercontent.com/34659544/89195065-96c04500-d57e-11ea-9aec-f3636cba8873.PNG)

## Attach a .c3p

Any file should present it. It's an editor thing.

## Steps to reproduce

I could not find a reliable way to reproduce it. I've tried restarting the editor, the browser and the pc, but it did not happen consistently. The only way I can see it happening is when I don't use the editor for a while, close chrome and then come back to it after some hours, usually the next day.

## Observed result

Layout resetting itself.

## Expected result

Layout staying like I left it.

## More details

**Affected browsers/platforms:** Latest Chrome.

**First affected release:** Seen on 208 and 209, but not much before that. I only remember it starting to happen recently.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment] 2020-08-03 16:42
I've never seen this. As with any report, unless you can find reliable steps to reproduce it, there is probably nothing we can do.

**Comment by dupuqub** [comment] 2020-08-03 18:35
I cleaned my cache, and so far it's fixed and I cannot reproduce it again. I'm gonna wait for something to happen, but maybe it was something confliting in the cache.

**Comment by AshleyScirra** [comment] 2020-08-04 09:11
OK, closing since there's no way to investigate this.

**Closed by AshleyScirra** 2020-08-04 09:11 UTC
Labels: no repro

**Comment by dupuqub** [comment] 2020-08-07 09:48
Hi @AshleyScirra, I hope you could open this issue again.

It actually happened again and I realized every time it happens, C3 also logs me out.

I work with dual monitors on 1600x900 resolution, can this be related to maybe some visual glitch?

Also, and still, the only way I am able to reproduce it is by turning my windows 10 off and on again. It happens every time and every time I have to reset to "factory settings" and input all my preferences again.

Below there's an image showing what appears in HTML body:
![otherbug](https://user-images.githubusercontent.com/34659544/89632460-996db380-d878-11ea-97f9-91227c4f6657.PNG)

I get these warnings:
![otherbug2](https://user-images.githubusercontent.com/34659544/89632998-84455480-d879-11ea-8224-44b5fec53b9a.PNG)

And, maybe unrelated, I also get this warning, although I think this is related to the OneDrive issue:
![bug](https://user-images.githubusercontent.com/34659544/89633065-a212b980-d879-11ea-9f18-e26dc4d80d83.PNG)

I would appreciate any help, and I can send you any data you want, I still didn't reboot C3 so I still get this weird empty section, therefore I think there could be something somewhere you could point me to look at.

**Comment by AshleyScirra** [comment] 2020-08-07 11:55
In general, we can only solve issues if you follow the bug report guidelines including the steps to reproduce, which is why we require them. I'm afraid if you don't have steps to reproduce, there is very little we can do. If you can find steps to reproduce, please file a new issue following all the guidelines.
