### ISSUE TITLE
Random crash after creating 9-Patch

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#55] opened 2017-04-11 10:52 UTC
## Problem description

Was just trying to create a 9-Patch object and I drew some place-holder art, but then it crashed when I exited the 9-patch image editor.

## Steps to reproduce

1. Create a 9-patch object.
2. Draw some stuff on it.
3. Close the 9-patch image editor.

## Observed result

Crashed.

## Expected result

Don't crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: TypeError: Failed to execute 'putImageData' on 'CanvasRenderingContext2D': parameter 1 is not of type 'ImageData'.
Stack: TypeError: Failed to execute 'putImageData' on 'CanvasRenderingContext2D': parameter 1 is not of type 'ImageData'. at Function.ǃLRI (https://editor.construct.net/r16/main.js:63:372841) at Function.ǃLRs (https://editor.construct.net/r16/main.js:63:372889) at Function.ǃLRA (https://editor.construct.net/r16/main.js:63:351231) at he.then (https://editor.construct.net/r16/main.js:63:351543)
Construct 3 version: r16
URL: https://editor.construct.net/index.html
Date: Tue Apr 11 2017 14:37:13 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 2293.6 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by DiegoScirra** [comment] 2017-04-11 11:00
Do you have some more details on this? Like what tools did you used.

**Comment by jaydonteh** [comment] 2017-04-11 17:11
First i used the fill tool, then the colour picker. After that, the rectangles which then proceeds to closing the image editor with a crash.

**Comment by DiegoScirra** [comment] 2017-04-11 18:17
Still can't reproduce this one, there has to be something else to it.

I am creating an empty project, then creating a 9-Patch object, then I draw on top of it using several different tools, and I can close the editor with no problems.

**Comment by jaydonteh** [comment] 2017-04-11 18:19
Trying to reproduce and rethink what i did prior to crash but failed. Perhaps another random crash to be unraveled in the future.

**Comment by AshleyScirra** [comment] 2017-04-21 15:17
Closing as there are no reproduction steps and the bug has been idle for a while. Please file again if you can reproduce.

**Closed by AshleyScirra** 2017-04-21 15:17 UTC
Labels: no repro
