### ISSUE TITLE
Audio Replace issue

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#6175] opened 2022-10-09 14:08 UTC
## Problem description
With the new "Folder" structure instead of the old "Flat" way, I thought I can use this feature for my purposes. I wanted to switch a set of audiofiles by just switching the the name of the Folder, while keeping the names of the audiofiles in the different folders identic. In the BugReport File these would be the set "X" and "Y". 

Now it seems that for Construct the different location where the file should be saved does not count, it will just replace one file with the other at the moment of the import.

## Attach a .c3p
[AudioReplace.zip](https://github.com/Scirra/Construct-3-bugs/files/9741735/AudioReplace.zip)

## Steps to reproduce

1.open the project file, rightclick on empty Sounds Folder "Y" - click on import sounds
2.I ve put a soundfile into the Bugreport zip File. drag and drop this file 1_1.wav into the Dialog to import it
3.click on import

## Observed result
Construct 3 ask you for replaceing the file or cancel

## Expected result
although the file has the same name, it should be imported into the empty folder because it is saved in a different location

## More details

**Affected browsers/platforms:** 
tested in chrome on mac, r313

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r313 (beta)
Browser: Chrome 106.0.5249.103
Browser engine: Chromium
Context: browser
Operating system: macOS 11.7.0
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 207 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel Inc.)
Renderer: ANGLE (Intel Inc., Intel(R) HD Graphics 630, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment] 2022-10-10 10:57
It's currently by design that even in folders mode, all project files still have to have unique names. This is for two reasons:

1) It is still possible to switch folder projects back to flat mode, and flat mode requires unique names for all project files regardless of their folder. Supporting this significantly complicates the ability to switch between the two modes.
2) There are still significant parts of Construct that internally work by looking up project files by name, regardless of their folder. Audio files are one example of this (note how the list to choose an audio file lists only the name, not the folder path). So there would need to be significant work done to properly support files with the same names in different folders in all these existing cases.

So for now we've kept the restriction that all project filenames must be unique, as it solves both these problems.

I would like to properly support having the same filenames in different folders, but it would be much easier if we could first retire "flat" mode. However I'm not sure if that's feasible (for backwards-compatibility) and it would probably take a long time to reach the point the old mode could be retired without causing too much disruption. Either way I'm afraid it's not something we plan on doing in the short term, and I think this would be better tracked as a further feature request, so closing.

**Closed by AshleyScirra** 2022-10-10 10:57 UTC
Labels: enhancement
