### ISSUE TITLE
Dark Theme: Collapsing folder animation has a hitch at the end

### ISSUE THREAD

**Issue by shortercode** [Scirra/Construct-3-bugs#637] opened 2017-07-21 10:33 UTC
## Problem description

This only occurs on the dark theme. When collapsing a folder in the project bar the animation hitches at the end. Best guess is that the height of the row is different in the collapsed state than the target height in the animation. Alternatively the css class could be changing before the animation finishes.

I realise this is nitpicking slightly, but I thought I'd report it anyway 😛 

## Attach a .c3p

Blank project is fine.

## Steps to reproduce

1. Open new project
2. Try toggling the collapse state on the layouts folder
3. Observe a slight hitch at the end of the collapse animation (not expand for some reason)

## Observed result

Smoothly animates 95% of the height, pauses, then last 5%.

## Expected result

Smoothly animates 100% of the height.

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r45

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 90 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment] 2019-01-17 15:18
The problem is the dark theme adds an extra 8px bottom margin on item child containers, in order to space out child items and the folders that follow them. The collapse animation animates the height to 0px and then removes the element (using `display: none`). A zero height still includes the 8px margin, so the last step snaps from an overall height of 8px to 0px, resulting in the visual hitch.

Unfortunately even if this is switched to padding and the box model changed to `border-box` (so padding contributes to height), a quirk of CSS means that you can't make an element smaller than its padding. So the animation to a zero height clamps to a minimum of 8px high, and then it steps again to 0px when removed.

Given the minor severity of the issue and the awkwardness in fixing it, closing as wontfix.

**Closed by AshleyScirra** 2019-01-17 15:18 UTC
Labels: theme, wontfix
